### ISSUE TITLE
NetworkInterface.getByInetAddress() return null on Android platform

### ISSUE THREAD

**Issue by kyze8439690** [netty/netty#10045]
### Netty version
4.1.45.Final
### JVM version (e.g. `java -version`)
Java1.8
### OS version (e.g. `uname -a`)
Android 9.0

Exception stack:
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Enumeration.hasMoreElements()' on a null object reference
       at io.netty.util.NetUtil.<clinit>(NetUtil.java:173)
       at io.netty.util.internal.MacAddressUtil.bestAvailableMac(MacAddressUtil.java:50)
       at io.netty.util.internal.MacAddressUtil.defaultMachineId(MacAddressUtil.java:138)
       at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:99)
       at io.netty.channel.DefaultChannelId.newInstance(DefaultChannelId.java:55)
       at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:101)
       at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:73)
       at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:80)
       at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
       at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:89)
       at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:75)
       at java.lang.reflect.Constructor.newInstance0(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
       at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:44)
       at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:302)
       at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:264)
       at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:260)
       at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:245)
```

Info: According to Android official document, `NetworkInterface.getByInetAddress()` may return null if there is no network interface with the specified IP address.

https://developer.android.com/reference/java/net/NetworkInterface.html#getByInetAddress(java.net.InetAddress)

**Comment by normanmaurer** [comment]
I am a bit confused as this is calling `NetworkInterface.getInetAddresses()` which should `never` return `null`. What I am missing ?

**Comment by normanmaurer** [comment]
I mean we can add an extra null check but I am not sure why this would happen in the first place.

**Comment by getsurfboard** [comment]
I don't know the cause of this crash either. This is a small crash of an online app. I can not reproduce it. Maybe it is asynchronous issue? BTW, according to JDK document, `NetworkInterface.getInetAddresses()` may return null too.

https://docs.oracle.com/javase/8/docs/api/java/net/NetworkInterface.html#getByInetAddress-java.net.InetAddress-

**Comment by normanmaurer** [comment]
@getsurfboard nope it does not... you linked to the wrong Javadoc:

https://docs.oracle.com/javase/8/docs/api/java/net/NetworkInterface.html#getInetAddresses--

**Comment by kyze8439690** [comment]
Sorry, my bad. I think it is an android-specific issue, until now the crash rate is not very high. I will pay attention to it.  Thanks.

**Comment by normanmaurer** [comment]
I mean its not a big deal to add a null check but even after looking at the source I can not see why it may return null :/

**Comment by kyze8439690** [comment]
The world of Android is very fragmented and it is not surprising to find any inconsistencies 😄

**Comment by normanmaurer** [comment]
@kyze8439690 let me just add a null check... It doesn't hurt us and if it helps you it can't hurt either :)

**Comment by kyze8439690** [comment]
Thanks, I appreciate it

**Comment by normanmaurer** [comment]
@kyze8439690 see https://github.com/netty/netty/pull/10056
