### ISSUE TITLE
Failure to run a service that uses a Netty library having built it with Graal native-image

### ISSUE THREAD

**Issue by CremboC** [netty/netty#10051]
### Expected behavior
Ability to build and run a service using Netty with GraalVM [native-image](https://www.graalvm.org/docs/reference-manual/native-image/).

### Actual behavior
It seems like Netty already has some support for GraalVM, but there still some issues. I can't find any reference to this error below, so maybe I'm doing something wrong! Any ideas would be greatly appreciated.

Failure during runtime:
```
com.oracle.svm.core.jdk.UnsupportedFeatureError: Unsupported method of Unsafe
	at com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:101)
	at jdk.internal.misc.Unsafe.staticFieldOffset(Unsafe.java:230)
	at sun.misc.Unsafe.staticFieldOffset(Unsafe.java:662)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:281)
	at java.security.AccessController.doPrivileged(AccessController.java:81)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:266)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:272)
	at io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:222)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:209)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.cached(AsciiString.java:1406)
	at io.grpc.netty.shaded.io.netty.util.AsciiString.<clinit>(AsciiString.java:47)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:72)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:74)
	at com.oracle.svm.core.hub.ClassInitializationInfo.invokeClassInitializer(ClassInitializationInfo.java:350)
	at com.oracle.svm.core.hub.ClassInitializationInfo.initialize(ClassInitializationInfo.java:270)
	at java.lang.Class.ensureInitialized(DynamicHub.java:496)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:269)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1500(InstantiatingGrpcChannelProvider.java:71)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:202)
	at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:209)
	at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:192)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:155)
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.create(EnhancedBigtableStub.java:163)
	at com.google.cloud.bigtable.data.v2.BigtableDataClient.create(BigtableDataClient.java:152)
```

### Steps to reproduce
Try building a service that uses a library that uses Netty under the hood (in my particular example, `google-cloud-bigtable`).

### Netty version
The library uses a shaded version of Netty `grpc-netty-shaded`, but using the latest version `1.27.1`, which I'm pretty sure it's Netty 4.1.44+ (but I don't know how to verify).

### JVM version (e.g. `java -version`)
N/A

### OS version (e.g. `uname -a`)
macOS Catalina

**Comment by normanmaurer** [comment]
please ensure you use the latest netty release and re-open if you still see issues.

**Comment by dzou** [comment]
Encountered the same error, also trying to use `grpc-netty-shaded`.

**Comment by rpuch** [comment]
As a work-around: `-Dio.netty.noUnsafe=true` added at run time (that is, if your built application is called `app`, it is `./app -Dio.netty.noUnsafe=true`) seems to solve the problem.

Please note that it compleletely disables the usage of `Unsafe` by Netty. I'm not sure what this means (probably, some performance penalty).

Kudos to @johnou
