### ISSUE TITLE
AssertionError in ScheduledFutureTask

### ISSUE THREAD

**Issue by djelinski** [netty/netty#10070]
```
WARNING Unexpected exception in the selector loop.
java.lang.AssertionError
    at io.netty.util.concurrent.ScheduledFutureTask.setConsumed(ScheduledFutureTask.java:112)
    at io.netty.util.concurrent.AbstractScheduledEventExecutor.pollScheduledTask(AbstractScheduledEventExecutor.java:134)
    at io.netty.util.concurrent.SingleThreadEventExecutor.fetchFromScheduledTaskQueue(SingleThreadEventExecutor.java:284)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:461)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
```
Happens relatively frequently ever since we upgraded our application from 4.1.42 to 4.1.45. This is caused by JVM returning the same nanoTime value on consecutive calls. In debugger I found that value returned by nanoTime was exactly equal to deadlineNanos.

Fix is pretty simple: change the check in ScheduledFutureTask.java:112 or the one in AbstractScheduledEventExecutor.java:130 so they are consistent, 

### Steps to reproduce
N/A

### Netty version
4.1.45, but the problematic assertion was introduced in https://github.com/netty/netty/commit/feb804dca8579c93ff3224564aafcf5938bb2c52#diff-a6871cf1d78dcb4ff1db3d6bb5e117b9, so presumably all versions since 4.1.44 are affected.

### JVM version (e.g. `java -version`)
8u232

### OS version (e.g. `uname -a`)
Windows 10

**Comment by normanmaurer** [comment]
@djelinski interested in doing a PR ?
