### ISSUE TITLE
Unexpected exception in Bootstrap.doResolveAndConnect0 leaks SocketChannel

### ISSUE THREAD

**Issue by blindpirate** [netty/netty#10109]
### Context 

During the investigation of https://github.com/vert-x3/vertx-web/issues/1055 , it seems that unexpected exception thrown at https://github.com/netty/netty/blob/56055f4404fbebeb6403165d352d62330a1bf81d/transport/src/main/java/io/netty/bootstrap/Bootstrap.java#L192 causes leaking  `SocketChannel`.

The leaked `SocketChannel` is opened via 

```
Opened socket channel 908737395 by thread:vert.x-eventloop-thread-0 on Sat Mar 14 18:20:36 CST 2020
	at sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:105)
	at sun.nio.ch.SelectorProviderImpl.openSocketChannel(SelectorProviderImpl.java:60)
	at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:68)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:87)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:80)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:298)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:157)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:141)
	at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:136)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:89)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:75)
	at io.vertx.core.http.impl.HttpChannelConnector.doConnect(HttpChannelConnector.java:137)
	at io.vertx.core.http.impl.HttpChannelConnector.connect(HttpChannelConnector.java:111)
	at io.vertx.core.http.impl.pool.Pool$Holder.connect(Pool.java:127)
	at io.vertx.core.http.impl.pool.Pool.checkPendingTasks(Pool.java:258)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

When `IllegalStateException` is thrown [at this line](https://github.com/netty/netty/blob/56055f4404fbebeb6403165d352d62330a1bf81d/transport/src/main/java/io/netty/bootstrap/Bootstrap.java#L192) because of executor shutting down:

```
        if (executor.isShuttingDown()) {
            throw new IllegalStateException("executor not accepting a task");
        }
```

`Bootstrap.doResolveAndConnect0` returns failed `Promise` without closing `channel`.

### Expected behavior

All open `SocketChannel`s get closed correctly in any cases.

### Actual behavior

Unexpected exceptions may leak `SocketChannel`.

### Steps to reproduce

See https://github.com/vert-x3/vertx-web/issues/1055

### Netty version

All versions so far.

### JVM version (e.g. `java -version`)

```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
```

### OS version (e.g. `uname -a`)

macOS 10.14.6

**Comment by blindpirate** [comment]
Thanks @normanmaurer !
