### ISSUE TITLE
 io.netty.util.IllegalReferenceCountException: refCnt: 0

### ISSUE THREAD

**Issue by pjmike** [netty/netty#10102]
Firstly，I set FullHttpRequest to the attribute of channel，when I get the FullHttpRequest from the channel' attribute somethere，it's ok. 

However，when I convey the channel to thread pool thread，I get the FullHttpRequest from the channel，then I print out the FullHttpRequest，an error occurred :

```java
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1489)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1418)
	at io.netty.buffer.AbstractByteBuf.checkDstIndex(AbstractByteBuf.java:1444)
	at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:1025)
	at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:49)
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:834)
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1247)
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1242)
```
the part of source code about thread pool: 
```java

ExecutorService routePool = new ThreadPoolExecutor(5, 100, 30L, TimeUnit.MILLISECONDS,
            new LinkedBlockingDeque<>(), new ThreadFactoryBuilder().setNameFormat("Route-%d-thread").build());

routePool.execute(()-> {
            try {
                route(channel);
            } catch (GatewayException e) {
                e.printStackTrace();
            }
        });

```
the part of code about  getting FullhttpRequest
```java
 FullHttpRequest httpRequest = channel.attr(Attributes.REQUEST).get();

 System.out.println(httpRequest.content().toString(CharsetUtil.UTF_8));
```
### Expected behavior
I m expect that all should be okay in thread pool
### Actual behavior
An error occur
### Minimal yet complete reproducer code (or URL to code)
URL to code:  https://github.com/pjmike/netty-gateway/blob/master/netty-gateway-core/src/main/java/com/pjmike/filter/route/NettyRoutingFilter.java
### Netty version
4.1.47.Final 
### JVM version (e.g. `java -version`)
jdk 1.8.0_121
### OS version (e.g. `uname -a`)
windows 10 x64

**Comment by normanmaurer** [comment]
You probably need to retain the reference as you are writing out the same request to the Channel and so it will be released.

**Comment by bdsilva** [comment]
I am facing a similar issue. Can you please describe what and how you would retain the reference? I am trying to simply write a ResponseFilter and do this line
`requestBody = ((DefaultFullHttpRequest) httpRequest).content().toString(CharsetUtil.UTF_8);` 

`io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1490) ~[netty-all-4.1.56.Final.jar!/:4.1.56.Final]
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1419) ~[netty-all-4.1.56.Final.jar!/:4.1.56.Final]
	at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:481) ~[netty-all-4.1.56.Final.jar!/:4.1.56.Final]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.getBytes(PooledUnsafeDirectByteBuf.java:130) ~[netty-all-4.1.56.Final.jar!/:4.1.56.Final]
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:1041) ~[netty-all-4.1.56.Final.jar!/:4.1.56.Final]
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1248) ~[netty-all-4.1.56.Final.jar!/:4.1.56.Final]
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:1243) ~[netty-all-4.1.56.Final.jar!/:4.1.56.Final]
`
