### ISSUE TITLE
mvn test failed on netty-transport-native-epoll

### ISSUE THREAD

**Issue by yzhang90** [netty/netty#10114]
Running `mvn test` under the root directory on the branch 4.1 gives the following error:
```
[INFO] --- maven-dependency-plugin:2.10:unpack-dependencies (unpack) @ netty-transport-native-epoll ---
[INFO] Unpacking /home/zy/workspace/rv-project/netty/transport-native-unix-common/target/classes to /home/zy/workspace/rv-project/netty/transport-native-epoll/target/unix-common-lib with includes "META-INF/native/**" and excludes ""
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Netty 4.1.48.Final-SNAPSHOT:
[INFO] 
[INFO] Netty/Dev-Tools .................................... SUCCESS [  0.317 s]
[INFO] Netty .............................................. SUCCESS [  1.826 s]
[INFO] Netty/Common ....................................... SUCCESS [ 35.520 s]
[INFO] Netty/Buffer ....................................... SUCCESS [ 24.414 s]
[INFO] Netty/Resolver ..................................... SUCCESS [  1.170 s]
[INFO] Netty/Transport .................................... SUCCESS [ 51.302 s]
[INFO] Netty/Codec ........................................ SUCCESS [  8.115 s]
[INFO] Netty/Codec/DNS .................................... SUCCESS [  1.343 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  1.153 s]
[INFO] Netty/Handler ...................................... SUCCESS [02:11 min]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [  4.174 s]
[INFO] Netty/Codec/HTTP2 .................................. SUCCESS [ 11.582 s]
[INFO] Netty/Codec/Memcache ............................... SUCCESS [  1.139 s]
[INFO] Netty/Codec/MQTT ................................... SUCCESS [  1.372 s]
[INFO] Netty/Codec/Redis .................................. SUCCESS [  1.129 s]
[INFO] Netty/Codec/SMTP ................................... SUCCESS [  1.100 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  1.373 s]
[INFO] Netty/Codec/Stomp .................................. SUCCESS [  1.084 s]
[INFO] Netty/Codec/XML .................................... SUCCESS [  1.094 s]
[INFO] Netty/Handler/Proxy ................................ SUCCESS [ 10.315 s]
[INFO] Netty/Resolver/DNS ................................. SUCCESS [ 34.931 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  0.426 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  0.466 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [ 12.460 s]
[INFO] Netty/Example ...................................... SUCCESS [  1.514 s]
[INFO] Netty/Transport/Native/Unix/Common ................. SUCCESS [  1.059 s]
[INFO] Netty/Testsuite .................................... SUCCESS [11:46 min]
[INFO] Netty/Transport/Native/Unix/Common/Tests ........... SUCCESS [  0.427 s]
[INFO] Netty/Transport/Native/Epoll ....................... FAILURE [  0.063 s]
[INFO] Netty/Transport/Native/KQueue ...................... SKIPPED
[INFO] Netty/Resolver/DNS/MacOS ........................... SKIPPED
[INFO] Netty/All-in-One ................................... SKIPPED
[INFO] Netty/Tarball ...................................... SKIPPED
[INFO] Netty/Testsuite/Autobahn ........................... SKIPPED
[INFO] Netty/Testsuite/Http2 .............................. SKIPPED
[INFO] Netty/Testsuite/OSGI ............................... SKIPPED
[INFO] Netty/Testsuite/Shading ............................ SKIPPED
[INFO] Netty/Testsuite/NativeImage ........................ SKIPPED
[INFO] Netty/Transport/BlockHound/Tests ................... SKIPPED
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/BOM .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17:29 min
[INFO] Finished at: 2020-03-17T11:44:34-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-transport-native-epoll: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-transport-native-epoll
```
However, `mvn clean package` succeed.

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

### OS version (e.g. `uname -a`)
Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hyperxpro** [comment]
Too less information to debug. Send entire mvn test log.

**Comment by yzhang90** [comment]
@hyperxpro here is the whole log
[mvn.log](https://github.com/netty/netty/files/4346163/mvn.log)
Thanks.

**Comment by hyperxpro** [comment]
Surprisingly I couldn't find anything.

@normanmaurer Can you help?

**Comment by normanmaurer** [comment]
nothing in there that is useful... Can you run with `-e` ?

**Comment by hyperxpro** [comment]
@yzhang90 Updates?

**Comment by paul-lysak** [comment]
I have the same issue - tests failing in `Netty/Transport/Native/Epoll`.

**JVM**

```
$ java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9-Ubuntu-216.04.1)
OpenJDK 64-Bit Server VM (build 13.0.1+9-Ubuntu-216.04.1, mixed mode, sharing)
```

**OS**

```
$ uname -a
Linux plysak-HP-ZBook-15u-G3 4.15.0-112-generic #113~16.04.1-Ubuntu SMP Fri Jul 10 04:37:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

This is the test that fails: ` EpollDatagramMulticastTest.testMulticast` and this is `io.netty.channel.epoll.EpollDatagramMulticastTest.txt` file content: 
```
-------------------------------------------------------------------------------
Test set: io.netty.channel.epoll.EpollDatagramMulticastTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.054 s <<< FAILURE! - in io.netty.channel.epoll.EpollDatagramMulticastTest
testMulticast(io.netty.channel.epoll.EpollDatagramMulticastTest)  Time elapsed: 1.053 s  <<< ERROR!
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address family not supported by protocol
```

This is the fresh code from branch `4.1`. I've installed all the libs requested in https://netty.io/wiki/setting-up-development-environment.html and https://netty.io/wiki/native-transports.html. Running `mvn clean package` to build it.

Do you need `mvn -e ..` output or other data?



With OpenJDK 8 it was failing even earlier - in `Netty/Handler`. For that setup I don't have a result of the full run at hand, but when running `mvn test` in the `handler` folder test errors were reproducible:

```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.318 s - in io.netty.handler.ssl.SniClientTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ConscryptJdkSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptJdkSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptJdkSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptJdkSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptJdkSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptJdkSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   ConscryptSslEngineTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3972 expected:<false> but was:<true>
[ERROR]   JdkConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3974 expected:<false> but was:<true>
[ERROR]   JdkConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3974 expected:<false> but was:<true>
[ERROR]   JdkConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3974 expected:<false> but was:<true>
[ERROR]   JdkConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3974 expected:<false> but was:<true>
[ERROR]   JdkConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3974 expected:<false> but was:<true>
[ERROR]   JdkConscryptSslEngineInteropTest>SSLEngineTest.testDefaultProtocolsIncludeTLSv13:3974 expected:<false> but was:<true>
[INFO] 
[ERROR] Tests run: 2823, Failures: 18, Errors: 0, Skipped: 136
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:30 min
[INFO] Finished at: 2020-08-18T17:15:23+03:00
[INFO] Final Memory: 35M/702M
[INFO] ------------------------------------------------------------------------
```





And with OpenJDK 11 on CentOS server - in `Netty/Testsuite`:

```
[ERROR] Failures: 
[ERROR]   DatagramMulticastTest.testMulticast:49->AbstractComboTestsuiteTest.run:67->testMulticast:97
```
Report file content:

```
-------------------------------------------------------------------------------
Test set: io.netty.testsuite.transport.socket.DatagramMulticastTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.326 s <<< FAILURE! - in io.netty.testsuite.transport.socket.DatagramMulticastTest
testMulticast(io.netty.testsuite.transport.socket.DatagramMulticastTest)  Time elapsed: 10.191 s  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at io.netty.testsuite.transport.socket.DatagramMulticastTest.testMulticast(DatagramMulticastTest.java:97)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.netty.testsuite.transport.AbstractComboTestsuiteTest.run(AbstractComboTestsuiteTest.java:67)
        at io.netty.testsuite.transport.socket.DatagramMulticastTest.testMulticast(DatagramMulticastTest.java:49)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```
