### ISSUE TITLE
io.netty.handler.codec.compression.DecompressionException: Unsupported compression method 0 in the GZIP header

### ISSUE THREAD

**Issue by rajcspsg** [netty/netty#10168]
### Expected behavior

I'm expecting `HttpDecompressor` to decompress the payload correctly when the request payload is compresssed with gzip.

### Actual behavior

I'm getting the below exception - 

```
io.netty.handler.codec.compression.DecompressionException: Unsupported compression method 0 in the GZIP header at io.netty.handler.codec.compression.JdkZlibDecoder.readGZIPHeader(JdkZlibDecoder.java:321) at io.netty.handler.codec.compression.JdkZlibDecoder.decode(JdkZlibDecoder.java:212) at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498) at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:343) at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:254) at io.netty.handler.codec.http.HttpContentDecoder.decodeContent(HttpContentDecoder.java:161) at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:150) at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:47) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce

```
    curl --location --request POST 'http://localhost:5880/' \
    --header 'Content-Type: application/json' \
    --header 'Accept: */*' \
    --header 'Accept-Encoding: gzip' \
    --header 'Accept-Language: en-US,en;q=0.9' \
    --header 'Connection: Keep-Alive' \
    --header 'Content-Encoding: gzip' \
    --header 'Content-Type: text/plain' \
    --data-raw '�VP*I-.QR�R0T���-!'
```

The request payload '�VP*I-.QR�R0T���-!' is Gzip compression of string `"{ \"test\" : 1 }"` using below logic - 

```
     public static byte[] compress(String str) throws Exception {
        if (str == null || str.length() == 0) {
            return null;
        }
        System.out.println("String length : " + str.length());
        ByteArrayOutputStream obj=new ByteArrayOutputStream();
        GZIPOutputStream gzip = new GZIPOutputStream(obj, 2);
        gzip.write(str.getBytes("UTF-8"));
        gzip.close();

        return obj.toByteArray();
    }
```

### Minimal yet complete reproducer code (or URL to code)

```
    public void start() {
        System.out.println("In Start method");
        try {
            ServerBootstrap b = new ServerBootstrap();
            EventLoopGroup bossGroup = new NioEventLoopGroup();
            EventLoopGroup workerGroup = new NioEventLoopGroup();

            b.group(bossGroup, workerGroup)
                    .channel(NioServerSocketChannel.class)
                    .childHandler(new HttpServerPipelineFactory())
                    .option(ChannelOption.SO_BACKLOG, 128)
                    .childOption(ChannelOption.WRITE_BUFFER_WATER_MARK, WriteBufferWaterMark.DEFAULT)
                    .childOption(ChannelOption.AUTO_READ, false)
                    .childOption(ChannelOption.SO_KEEPALIVE, true);

            ChannelFuture f = b.bind(listenerPort).sync();
            System.out.println("server started listening on port " + listenerPort);
            f.channel().closeFuture().sync();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

HTTP pipeline factory class is - 

```
    public class HttpServerPipelineFactory extends ChannelInitializer<Channel> {

        @Override
        protected void initChannel(Channel ch) {
            ChannelPipeline pipeline = ch.pipeline();
            pipeline.addLast("codec", new HttpServerCodec());
            pipeline.addLast("compress", new HttpContentCompressor());
            pipeline.addLast("decompress", new HttpContentDecompressor());
            pipeline.addLast("aggregator", new HttpObjectAggregator( 512 * 1024));
            pipeline.addLast("chunked", new ChunkedWriteHandler());
            pipeline.addLast("flow", new FlowControlHandler());
            pipeline.addLast("keep-alive", new HttpServerKeepAliveHandler());
            pipeline.addLast("request", new HTTPRequestHandler());
        }
    }
```

HTTPRequestHandler is - 

```
    import static io.netty.handler.codec.http.HttpHeaderNames.CONTENT_LENGTH;
    import static io.netty.handler.codec.http.HttpResponseStatus.OK;
    import static io.netty.handler.codec.http.HttpVersion.HTTP_1_1;
    import static io.netty.util.CharsetUtil.UTF_8;

    public class HTTPRequestHandler extends SimpleChannelInboundHandler<FullHttpRequest> {

        private static Logger logger = LoggerFactory.getLogger(HTTPRequestHandler.class);

        @Override
        protected void channelRead0(ChannelHandlerContext ctx, FullHttpRequest request) {
            System.out.println("uri is " + request.uri());
            String responseStr = request.method() +"/ Got request at " + request.uri();
            System.out.println("body is \n" + request.content().toString(UTF_8));
            FullHttpResponse response = new DefaultFullHttpResponse(HTTP_1_1, OK, Unpooled.copiedBuffer(responseStr.getBytes()), false);
            response.headers().set(CONTENT_LENGTH, response.content().readableBytes());
            ctx.channel().writeAndFlush(response);
            ctx.read();
        }

        @Override
        public void channelActive(ChannelHandlerContext ctx) throws Exception {
            super.channelActive(ctx);
            ctx.read();
        }
    }

```
### Netty version

`4.1.14.Final`

### JVM version (e.g. `java -version`)

```
openjdk version "1.8.0_232"
```

### OS version (e.g. `uname -a`)

```
Darwin BOSM0001-RANATA.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64
```

**Comment by hyperxpro** [comment]
Not Netty bug.

You can't take bytes and send directly like that using cURL.

**Comment by rajcspsg** [comment]
@hyperxpro what should be the correct way to compress the payload?

**Comment by hyperxpro** [comment]
Your way of compressing is correct but you're sending compressed data in a wrong way.

**Comment by rajcspsg** [comment]
Any example of how to send the compressed data correctly?

**Comment by hyperxpro** [comment]
```java
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

public class GG {

    public static void main(String[] args) throws IOException, InterruptedException {
        byte[] compressedData = new byte[0];

        HttpClient client = HttpClient.newHttpClient();
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create("http://localhost:5880/"))
                .setHeader("Content-Type", "application/json")
                .setHeader("Accept", "*/*")
                .setHeader("Accept-Encoding", "gzip")
                .setHeader("Accept-Language", "en-US,en;q=0.9")
                .setHeader("Connection", "Keep-Alive")
                .setHeader("Content-Encoding", "gzip")
                .POST(HttpRequest.BodyPublishers.ofByteArray(compressedData))
                .build();

        client.send(request, HttpResponse.BodyHandlers.ofByteArray());
    }
}

```

**Comment by hyperxpro** [comment]
Replace `compressedData` byte array with your compressed data byte array.

**Comment by rajcspsg** [comment]
Thanks @hyperxpro 

I made it work with below code as well

```
import org.apache.http.HttpEntity;
import org.apache.http.client.entity.EntityBuilder;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.util.EntityUtils;

public class GzippedHttpRequestLocalDemo {

    public static void main(String[] args) throws Exception {

        try(CloseableHttpClient httpclient = HttpClients.createDefault()) {
            HttpPost httppost = new HttpPost("http://localhost:5880/test");
            String payload = "{ \"test\" : 1 }";
            EntityBuilder builder = EntityBuilder.create().gzipCompress().setContentEncoding("gzip").chunked().setText(payload);
            HttpEntity entity = builder.build();
            httppost.setEntity(entity);
            System.out.println();
            httppost.setHeader("Accept-Encoding", "gzip,deflate");
            httppost.setHeader("Content-Encoding", "gzip");
            System.out.println("Executing request: " + httppost.getRequestLine());
            CloseableHttpResponse response = httpclient.execute(httppost);
            try {
                System.out.println("----------------------------------------");
                System.out.println(response.getStatusLine());
                System.out.println(EntityUtils.toString(response.getEntity()));
            } finally {
                response.close();
            }
        }
    }
}

```

**Comment by slandelle** [comment]
This won't work, see #2132.

`HttpContentDecompressor` extends `HttpContentDecoder` that currently only decodes `HttpRequest`s and `HttpContentCompressor` extends `HttpContentEncoder` that currently only encodes `HttpResponse`s.

In short: Netty only support compressing server side and decompressing client side.
