### ISSUE TITLE
io.netty.handler.codec.CodecException: invalid WebSocket Extension handshake for "permessage-deflate; server_no_context_takeover; client_no_context_takeover"

### ISSUE THREAD

**Issue by jliu1970** [netty/netty#10191]
### Expected behavior
Connection established successfully
### Actual behavior
io.netty.handler.codec.CodecException: invalid WebSocket Extension handshake for "permessage-deflate; server_no_context_takeover; client_no_context_takeover"
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketClientExtensionHandler.channelRead(WebSocketClientExtensionHandler.java:110)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1486)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1235)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
### Minimal yet complete reproducer code (or URL to code)

if (null != group) {
            group.shutdownGracefully();
        }

        String websocketUrl = getUrl("testurl");

        URI uri = new URI(websocketUrl);
        String scheme = uri.getScheme() == null ? "ws" : uri.getScheme();
        final String host = uri.getHost() == null ? "127.0.0.1" : uri.getHost();
        final int port;
        if (uri.getPort() == -1) {
            if ("ws".equalsIgnoreCase(scheme)) {
                port = 80;
            } else if ("wss".equalsIgnoreCase(scheme)) {
                port = 443;
            } else {
                port = -1;
            }
        } else {
            port = uri.getPort();
        }

        if (!"ws".equalsIgnoreCase(scheme) && !"wss".equalsIgnoreCase(scheme)) {
            System.err.println("Only WS(S) is supported.");
            return false;
        }

        final boolean ssl = "wss".equalsIgnoreCase(scheme);
        final SslContext sslCtx;
        if (ssl) {
            sslCtx = SslContextBuilder.forClient()
                    .trustManager(InsecureTrustManagerFactory.INSTANCE).build();
        } else {
            sslCtx = null;
        }

        group = new NioEventLoopGroup();
        try {
            // Connect with V13 (RFC 6455 aka HyBi-17). You can change it to V08 or V00.
            // If you change it to V00, ping is not supported and remember to change
            // HttpResponseDecoder to WebSocketHttpResponseDecoder in the pipeline.
            final WebSocketClientHandler handler =
                    new WebSocketClientHandler(
                            WebSocketClientHandshakerFactory.newHandshaker(
                                    uri, WebSocketVersion.V13, null, true, getHeaders()));

            Bootstrap b = new Bootstrap();
            b.group(group)
                    .channel(NioSocketChannel.class)
                    .handler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        protected void initChannel(SocketChannel ch) {
                            ChannelPipeline p = ch.pipeline();
                            if (sslCtx != null) {
                                p.addLast(sslCtx.newHandler(ch.alloc(), host, port));
                            }
                            p.addLast(
                                    new HttpClientCodec(),
                                    new HttpObjectAggregator(8192),
                                    WebSocketClientCompressionHandler.INSTANCE,
                                    handler);
                        }
                    });

            Channel websocketChannel = b.connect(uri.getHost(), port).sync().channel();
            handler.handshakeFuture().sync();

            webSocketKeepAliveHandler.start(
                    websocketChannel, connectionInfo.getWshbExpiry(), connectionInfo.getNumberOfRetries());
        } catch (WebSocketHandshakeException e) {
            logger.error("WebSocketHandshakeException: " + e.getMessage());
        } catch (Exception e) {
            logger.error("An exception occurred while attempting to setup the websocket connection. e: " + e.getMessage());
        }

### Netty version
4.1.35 Final, 4.1.48 Final
### JVM version (e.g. `java -version`)
java 8

**Comment by jliu1970** [comment]
please help to advise. Thanks, Jimmy

**Comment by normanmaurer** [comment]
@amizurov can you help ?

**Comment by amizurov** [comment]
@normanmaurer yes, I'll try to help soon.

**Comment by jliu1970** [comment]
Thanks, @normanmaurer !

**Comment by jliu1970** [comment]
Thanks, @amizurov

**Comment by amizurov** [comment]
@jliu1970 Hi, Did you play with this variables and set them to `true` ? https://github.com/netty/netty/blob/37948bc9debb3646150365e21da5d38342bbb3c5/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/extensions/compression/PerMessageDeflateServerExtensionHandshaker.java#L133-L134

**Comment by jliu1970** [comment]
Thanks so much for the advice, Andrey. 
I haven't tried that. I am very new to Netty and here is my understanding of overwrite the default serverNoContext and clientNoContext setting:

create a child class of WebSocketClientExtensionHandler, in the constructor, use the new instance of PerMessageDeflateClientExtensionHandshaker that has the serverNoContext and clientNoContext set to true. Add the new handler to the ChannelPipeline. As the example below:

_```
public final class WebSocketClientCompressionHandler extends WebSocketClientExtensionHandler {
    public static final WebSocketClientCompressionHandler INSTANCE = new WebSocketClientCompressionHandler();

    private WebSocketClientCompressionHandler() {
        super(new WebSocketClientExtensionHandshaker[]{new PerMessageDeflateClientExtensionHandshaker(), new DeflateFrameClientExtensionHandshaker(false), new DeflateFrameClientExtensionHandshaker(true)});
    }
}
```_

Thanks again for the quick help! It is truly appreciated.
Jimmy

**Comment by jliu1970** [comment]
Please comment, @amizurov

**Comment by amizurov** [comment]
> Please comment, @amizurov

For clarification, I meant that if you did not change the source code(I wrote above) and just played with examples so such exception: ```io.netty.handler.codec.CodecException: invalid WebSocket Extension handshake for "permessage-deflate; server_no_context_takeover; client_no_context_takeover" ```should not happened.

Could you please provide reproducer client and server.

**Comment by jliu1970** [comment]
Thanks for the response, @amizurov . I did not change the source code.

The source client code is the one that I posted in the initial question. However, the server code was from a third party software that I don't have access to.

Thanks
Jimmy

**Comment by amizurov** [comment]
Hmm looks like your third party server send in handshake response extensions (permessage-deflate; server_no_context_takeover; client_no_context_takeover) even if client is not requested it.

@jliu1970 Could you please create your own CompressionHandler and enabled (client_no_context_takeover, server_no_context_takeover) e.g:
```
@ChannelHandler.Sharable
public final class CustomWebSocketClientCompressionHandler extends WebSocketClientExtensionHandler {

    public static final CustomWebSocketClientCompressionHandler INSTANCE = new CustomWebSocketClientCompressionHandler();

    private CustomWebSocketClientCompressionHandler() {
        super(new PerMessageDeflateClientExtensionHandshaker(6, ZlibCodecFactory.isSupportingWindowSizeAndMemLevel(), MAX_WINDOW_SIZE, true, true),
                new DeflateFrameClientExtensionHandshaker(false),
                new DeflateFrameClientExtensionHandshaker(true));
    }
}
```

**Comment by jliu1970** [comment]
Thanks so much for the advise, @amizurov . I will proceed as you suggested and let you know.
Have a nice weekend,
Jimmy

**Comment by jliu1970** [comment]
Thanks so much, @amizurov. The solution worked for me 👍
