### ISSUE TITLE
Netty stops closing sockets and starts burning 100% CPU

### ISSUE THREAD

**Issue by igor-lukyanov** [netty/netty#10220]
We develop a pretty high-loaded proxy service based on netty (≈15-20k simultaneous open sockets per process). We encountered a bug when under some rare circumstances netty starts to burn 100% CPU and stops closing sockets, twice during last month and on different hosts.

Stacktrace of the stuck thread
```
"epollEventLoopGroup-7-2" #21 prio=10 os_prio=0 cpu=479213039.41ms elapsed=1475360.37s tid=0x00007f684800f800 nid=0x238 runnable  [0x00007f6835bb1000]
   java.lang.Thread.State: RUNNABLE
        at io.netty.resolver.dns.DnsResolveContext.internalResolve(DnsResolveContext.java:280)
        at io.netty.resolver.dns.DnsResolveContext.resolve(DnsResolveContext.java:205)
        at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1059)
        at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached(DnsNameResolver.java:1037)
        at io.netty.resolver.dns.DnsNameResolver.doResolveUncached(DnsNameResolver.java:941)
        at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:885)
        at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:728)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66)
        at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51)
        at somepackage.AddressValidationInetSocketAddressResolver.doResolve(AddressValidationInetSocketAddressResolver.java:53)
        at somepackage.AddressValidationInetSocketAddressResolver.doResolve(AddressValidationInetSocketAddressResolver.java:26)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:200)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116)
        at somepackage.Http2ProxyHandler.connectAndExec(Http2ProxyHandler.java:233)
```

### Expected behavior
Normally lsof -i -a -n -p gives zero sockets in CLOSE_WAIT state.

### Actual behavior
In our case it shows 20k CLOSE_WAIT sockets (incoming) and the number keeps growing until the open fd limit is reached. It's accompanied by 100% CPU core consumption.

### Netty version
4.1.47.Final
Native netty epoll is used.

### JVM version (e.g. `java -version`)
OpenJDK Runtime Environment (build 12.0.2+9-Debian-1)

### OS version (e.g. `uname -a`)
Linux hostname 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@igor-lukyanov thats interesting... do you have a full thread-dump ? How did you "detect" that the included thread-dump is the one to blame ?

**Comment by igor-lukyanov** [comment]
> How did you "detect" that the included thread-dump is the one to blame ?
@normanmaurer Using htop, it was the thread eating 100% CPU. 
I called jstack multiple times and the call stack of this thread was the same, so it was apparently stuck in an infinite loop somewhere inside DnsResolveContext.internalResolve.
[jstack.txt](https://github.com/netty/netty/files/4539548/jstack.txt)

**Comment by normanmaurer** [comment]
@igor-lukyanov perfect... let me dig in...

**Comment by normanmaurer** [comment]
@igor-lukyanov ok I think I know what the problem is... stay tuned.

**Comment by normanmaurer** [comment]
@igor-lukyanov https://github.com/netty/netty/pull/10221 PTAL

**Comment by igor-lukyanov** [comment]
@normanmaurer thank you for the instant solution.
