### ISSUE TITLE
Native.epollWait0 block and high cpu

### ISSUE THREAD

**Issue by zenios** [netty/netty#10239]
Hi All 

I am using netty (4.1.48.Final) with vertx and on random intervals i get very high cpu spikes and the following error messages

```
impl.BlockedThreadChecker Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 1816 ms, time limit is 1000 ms
io.vertx.core.VertxException: Thread blocked
	at app//io.netty.channel.epoll.Native.epollWait0(Native Method)
	at app//io.netty.channel.epoll.Native.epollWait(Native.java:113)
	at app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:286)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)

impl.BlockedThreadChecker Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 21448 ms, time limit is 1000 ms
io.vertx.core.VertxException: Thread blocked
	at app//io.netty.channel.epoll.Native.epollWait0(Native Method)
	at app//io.netty.channel.epoll.Native.epollWait(Native.java:113)
	at app//io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:286)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:351)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)

```

These two logs happened at a a time were the system was more or less idle

Some more info

```
4.19.0-8-cloud-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 GNU/Linux

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)

```

Any idea what could be causing this blocks or some hints on how to investigate what is happening?  

Thanks

**Comment by ninja-** [comment]
epollWait always shows up as consuming majority of the cpu or stacktrace and that means nothing.
you should start by digging deeper, for example by using a profiler

**Comment by zenios** [comment]
The problem here is not the high cpu usage but why its blocking the event loop. In the second stack trace it takes more than 20 s for the eventloop to unblock

Is this a case of a spinning selector?

p.s: I assume the high cpu usage is the consequence of the block and not an issue as such

**Comment by ninja-** [comment]
I don't think that's accurate. Probably vertx BlockedThreadChecker returns some garbage data.

**Comment by normanmaurer** [comment]
Please report this to `vertx`. It is expected that this method may block for a long period of time.
