### ISSUE TITLE
Utf8Validator should not trigger on private use area

### ISSUE THREAD

**Issue by xxDark** [netty/netty#10236]
### Expected behavior
Utf8Validator does not threat UTF-8 private use characters as invalid

### Actual behavior
Invalid UTF-8 exception is thrown

### Steps to reproduce
Pass any private use character to Utf8Validator, checks will fail

### Minimal yet complete reproducer code (or URL to code)
See steps to reproduce

### Netty version
4.1.49.Final

Edit: see https://en.wikipedia.org/wiki/Private_Use_Areas
```
[14:09:20] [epollEventLoopGroup-2-1/ERROR]: SocketClient exception
io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: bytes are not UTF-8
	at io.netty.handler.codec.http.websocketx.Utf8Validator.process(Utf8Validator.java:96) ~[waterfall.jar:?]
	at io.netty.buffer.AbstractByteBuf.forEachByteAsc0(AbstractByteBuf.java:1336) ~[waterfall.jar:?]
	at io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1316) ~[waterfall.jar:?]
	at io.netty.handler.codec.http.websocketx.Utf8Validator.check(Utf8Validator.java:73) ~[waterfall.jar:?]
	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.checkUTF8String(Utf8FrameValidator.java:89) ~[waterfall.jar:?]
	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:51) ~[waterfall.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[waterfall.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[waterfall.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
[14:09:20] [epollEventLoopGroup-2-1/INFO]: Client shutdown
```

**Comment by xxDark** [comment]
Will close that until we investigate.
