### ISSUE TITLE
 Failed to mark a promise as failure

### ISSUE THREAD

**Issue by timandy** [netty/netty#10240]
### Exception stacktrace
 17:46:00.505 [] [work-6-5] WARN  i.n.channel.ChannelOutboundBuffer - Failed to mark a promise as failure because it has failed already: DefaultChannelPromise@7caeb396(failure: io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: send close frame timed out), unnotified cause: io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: send close frame timed out
	at io.netty.handler.codec.http.websocketx.WebSocketProtocolHandler$2.run(WebSocketProtocolHandler.java:131)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

java.nio.channels.ClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:606)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1352)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606)
	at io.netty.handler.codec.http.websocketx.WebSocketProtocolHandler$1.operationComplete(WebSocketProtocolHandler.java:102)
	at io.netty.handler.codec.http.websocketx.WebSocketProtocolHandler$1.operationComplete(WebSocketProtocolHandler.java:99)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.handler.codec.http.websocketx.WebSocketProtocolHandler$2.run(WebSocketProtocolHandler.java:131)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
### Steps to reproduce
The sever has about 20,000 websocket connections with one test client . I shut down the client. Then the error printed many times.

### Netty version
4.1.49

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_201"
OpenJDK Runtime Environment (IcedTea 3.11.0) (Alpine 8.201.08-r0)
OpenJDK 64-Bit Server VM (build 25.201-b08, mixed mode)

### OS version (e.g. `uname -a`)
docker container 
Linux chatroom-dev 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 Linux

**Comment by timandy** [comment]
By the way , Some `channnel.close()` may be called in the business thread pool which type is DefaultEventExecutorGroup.

**Comment by normanmaurer** [comment]
Yep that is a bug... looking into it

**Comment by svaithia** [comment]
@timandy we're seeing increase in netty direct ByteBuf memory usage go up and in the logs, we're consistently seeing this log message whenever the memory increases. 

Do you by any chance remember how to reproduce this issue?
> The sever has about 20,000 websocket connections with one test client . I shut down the client. Then the error printed many times.
What exactly do you mean by you shut down the client? Do you mean you killed it without sending the Close frame?

I would like to test out whether this error is the reason for memory increase, maybe this causes a leak somewhere. If it is, then it might be a good case for us to upgrade to the latest version with this issue fixed.

Thanks

**Comment by timandy** [comment]
> What exactly do you mean by you shut down the client? Do you mean you killed it without sending the Close frame?

Yes, I force killed the client process without sending the close frame. Then the log was printed on server side.
