### ISSUE TITLE
NPE in CompositeByteBuf when reading from channel

### ISSUE THREAD

**Issue by rdicroce** [netty/netty#10245]
### Expected behavior
There should not be a NullPointerException.

### Actual behavior
A NullPointerException occurs:
```
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280) ~[netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.45.Final.jar:4.1.45.Final]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
at io.netty.buffer.CompositeByteBuf.toComponentIndex0(CompositeByteBuf.java:893) ~[netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.buffer.CompositeByteBuf.addFlattenedComponents(CompositeByteBuf.java:464) ~[netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.handler.codec.ByteToMessageDecoder$2.cumulate(ByteToMessageDecoder.java:132) ~[netty-all-4.1.45.Final.jar:4.1.45.Final]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:274) ~[netty-all-4.1.45.Final.jar:4.1.45.Final]
... 15 more
```

### Steps to reproduce
Not entirely clear. A coworker discovered that this happens sometimes with very high throughput. After scrutinizing the code a bit, I suspect this is a regression introduced by #8939. The only way a NPE could occur at line 893 is if the components array is null. It looks like that can only happen if the buffer passed to addFlattenedComponents() is a WrappedCompositeByteBuf. WCBB uses the special constructor in CBB that sets components to null, and does not override toComponentIndex0().

### Netty version
4.1.45.Final

### JVM version (e.g. `java -version`)
11 (not sure exactly which update)

### OS version (e.g. `uname -a`)
Windows 10

**Comment by rdicroce** [comment]
Coworker reports that this NPE does not occur anymore after downgrading Netty to 4.1.34.Final, which is the last version before #8939.

**Comment by hyperxpro** [comment]
High throughput in sense of Bandwidth or Connections?

**Comment by rdicroce** [comment]
Bandwidth. AIUI he had a simulator running that only created one connection but was sending messages constantly.

**Comment by njhill** [comment]
@rdicroce sorry about this. Your analysis looks correct to me and this appears to be an oversight. WCBB instances need to be unwrapped here. I will provide a fix asap.

One way to work-around in the meantime would be to run with `-Dio.netty.leakDetection.level=disabled`

**Comment by njhill** [comment]
@rdicroce @normanmaurer please see #10247
