### ISSUE TITLE
Blockhound detects a blocking call inside GlobalEventExecutor#addTask

### ISSUE THREAD

**Issue by pbetkier** [netty/netty#10257]
### Expected behavior
No blocking calls detected by BlockHound.

### Actual behavior

I observe the same problem originally reported by @62mkv in https://github.com/reactor/reactor-netty/issues/1086:

Occasionally, BlockHound-enabled Spring Boot (w/WebFlux) test suite fails to complete correctly because of such exception w/ the following trace:

```
18:03:03.327 [reactor-http-nio-2] ERROR io.netty.util.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
reactor.blockhound.BlockingOperationError: Blocking call! sun.misc.Unsafe#park
        at sun.misc.Unsafe.park(Unsafe.java)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
        at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:418)
        at java.util.AbstractQueue.add(AbstractQueue.java:95)
        at io.netty.util.concurrent.GlobalEventExecutor.addTask(GlobalEventExecutor.java:141)
        at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:206)
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

reactor-netty maintainer @violetagg suggested the issue should be moved to this project. I haven't found it here, so I'm opening it.

### Workaround
It's possible to whitelist this directly in the application as a temporary solution:
```
  private static final class NettyWorkaroundBlockHoundIntegration implements BlockHoundIntegration {
    @Override
    void applyTo(BlockHound.Builder builder) {
      builder.allowBlockingCallsInside(GlobalEventExecutor.class.name, 'addTask')
    }
  }
```

### Netty version
4.1.48.Final
### JVM version (e.g. `java -version`)
openjdk version "11.0.4" 2019-07-16
### OS version (e.g. `uname -a`)
Mac OS X 10.15.2 x86_64, Win10

**Comment by normanmaurer** [comment]
@pbetkier are you interested in providing a PR ?

**Comment by pbetkier** [comment]
sure

**Comment by normanmaurer** [comment]
@pbetkier cool... please ping me once done and I will review

**Comment by pbetkier** [comment]
I have trouble simulating the blocking call in the unit tests (`NettyBlockHoundIntegrationTest`).

In my WebFlux application test suite the blocking call appears when `SingleThreadEventExecutor` is shut down and [sets `terminationFuture`](https://github.com/netty/netty/blob/363c4ecc7f2f2ec0d499ceae17c23ada5d0b0765/common/src/main/java/io/netty/util/concurrent/SingleThreadEventExecutor.java#L1051). We end up in `GlobalEventExecutor#addTask`, where we make a blocking call on the queue lock. In the tests I tried to set up  `GlobalEventExecutor#addTask` passes without blocking – `tryAcquire` on the queue lock comes `true` and I don't end up in the blocking calls of `acquireQueued`.

Do you have tips on how to trigger this problem in tests? Here's what I've tried to do:
```
    @Test(timeout = 5000L)
    public void testGlobalEventExecutorAddTask() throws InterruptedException {
        CountDownLatch latch = new CountDownLatch(2);

        SingleThreadEventExecutor executor =
                new SingleThreadEventExecutor(null, new DefaultThreadFactory("test"), true) {
                    @Override
                    protected void run() {
                        while (!confirmShutdown()) {
                            Runnable task = takeTask();
                            if (task != null) {
                                task.run();
                            }
                        }
                    }
                };

        executor.execute(() -> {
            latch.countDown();
        });

        executor.terminationFuture().addListener((FutureListener) future -> latch.countDown());
        executor.shutdownGracefully();

        latch.await();
    }
```

**Comment by 62mkv** [comment]
hi @pbetkier not sure if this counts as "in tests" (in the sense you're asking for), but for us it manifests as follows: 

```
11:05:01.817 [SpringContextShutdownHook] DEBUG kn.internal.pcip.middleware.amqp.AbstractAmqpReceiver - Cancelling subscription for MyIopmFakeProcessor
11:05:01.817 [SpringContextShutdownHook] INFO  reactor.rabbitmq.Receiver - Cancelling consumer amq.ctag-NCAPJpl-MlGRD35bxuuaZw consuming from fake-iopm-queue
11:05:02.156 [SpringContextShutdownHook] ERROR kn.internal.pcip.middleware.config.RabbitmqConfiguration - Error when closing connection to RabbitMQ: connection is already closed due to connection error; cause: java.io.IOException: I/O thread: reached EOF
11:05:02.157 [SpringContextShutdownHook] ERROR kn.internal.pcip.middleware.config.RabbitmqConfiguration - Error when closing connection to RabbitMQ: connection is already closed due to connection error; cause: java.io.IOException: I/O thread: reached EOF
11:05:04.160 [reactor-http-epoll-4] ERROR io.netty.util.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
reactor.blockhound.BlockingOperationError: Blocking call! sun.misc.Unsafe#park
	at sun.misc.Unsafe.park(Unsafe.java)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at java.util.concurrent.LinkedBlockingQueue.offer(LinkedBlockingQueue.java:418)
	at java.util.AbstractQueue.add(AbstractQueue.java:95)
	at io.netty.util.concurrent.GlobalEventExecutor.addTask(GlobalEventExecutor.java:141)
	at io.netty.util.concurrent.GlobalEventExecutor.execute(GlobalEventExecutor.java:206)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:1051)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
11:05:07.156 [SpringContextShutdownHook] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - QueuedThreadPool[jetty-http@18034b2a]@6c67432c{STOPPING,8<=0<=200,i=6,r=-1,q=0}[NO_TRY] Couldn't stop Thread[jetty-http@18034b2a-36,5,main]
11:05:07.157 [SpringContextShutdownHook] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - QueuedThreadPool[jetty-http@678ca8f1]@e26b8e0{STOPPING,8<=0<=200,i=6,r=-1,q=0}[NO_TRY] Couldn't stop Thread[jetty-http@678ca8f1-288,5,main]
11:05:07.160 [SpringContextShutdownHook] INFO  org.eclipse.jetty.server.AbstractConnector - Stopped ServerConnector@651e7695{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
```

**Comment by normanmaurer** [comment]
@pbetkier I will need to look into how to write a test... At worse we could just merge the fix first and then do a followup for the PR. WDYT ?

**Comment by pbetkier** [comment]
I've created a PR, verified it solves my problem after `mvn install` and using the SNAPSHOT version in my project.
