### ISSUE TITLE
JDK13 UnsupportedOperationException-->HttpMethod.valueOf(“GET”);

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty#10268]
### Actual behavior
public class TestWebApp {
    public static void main(String[] args) {
        HttpMethod get = HttpMethod.valueOf("GET");
    }
}
### Minimal yet complete reproducer code (or URL to code)

2020/05/10 14:37:20 DEBUG [              main ] i.n.u.i.l.InternalLoggerFactory : Using SLF4J as the default logging framework
2020/05/10 14:37:20 DEBUG [              main ]       i.n.u.i.PlatformDependent : Platform: Windows
2020/05/10 14:37:20 DEBUG [              main ]      i.n.u.i.PlatformDependent0 : -Dio.netty.noUnsafe: false
2020/05/10 14:37:20 DEBUG [              main ]      i.n.u.i.PlatformDependent0 : Java version: 13
2020/05/10 14:37:20 DEBUG [              main ]      i.n.u.i.PlatformDependent0 : sun.misc.Unsafe.theUnsafe: available
2020/05/10 14:37:20 DEBUG [              main ]      i.n.u.i.PlatformDependent0 : sun.misc.Unsafe.copyMemory: available
2020/05/10 14:37:20 DEBUG [              main ]      i.n.u.i.PlatformDependent0 : java.nio.Buffer.address: available
2020/05/10 14:37:20 DEBUG [              main ]      i.n.u.i.PlatformDependent0 : direct buffer constructor: unavailable java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:227)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:135)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
	at top.test.TestWebApp.main(TestWebApp.java:9)

2020/05/10 14:37:20 DEBUG [              main ]      i.n.u.i.PlatformDependent0 : java.nio.Bits.unaligned: available, true
2020/05/10 14:37:20 DEBUG [              main ]      i.n.u.i.PlatformDependent0 : jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @48cf768c
2020/05/10 14:37:20 DEBUG [              main ]      i.n.u.i.PlatformDependent0 : java.nio.DirectByteBuffer.<init>(long, int): unavailable
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:642)
	at java.base/java.lang.reflect.Method.invoke(Method.java:559)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:347)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:338)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
2020/05/10 14:37:20 DEBUG [              main ]       i.n.u.i.PlatformDependent : sun.misc.Unsafe: available
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.netty.util.AsciiString.<init>(AsciiString.java:223)
	at io.netty.util.AsciiString.<init>(AsciiString.java:210)
	at io.netty.util.AsciiString.cached(AsciiString.java:1401)
	at io.netty.util.AsciiString.<clinit>(AsciiString.java:48)
	at io.netty.handler.codec.http.HttpMethod.<init>(HttpMethod.java:135)
	at io.netty.handler.codec.http.HttpMethod.<clinit>(HttpMethod.java:36)
	at top.test.TestWebApp.main(TestWebApp.java:9)

2020/05/10 14:37:20 DEBUG [              main ]       i.n.u.i.PlatformDependent : maxDirectMemory: 4280287232 bytes (maybe)
2020/05/10 14:37:20 DEBUG [              main ]       i.n.u.i.PlatformDependent : -Dio.netty.tmpdir: C:\Users\hxm\AppData\Local\Temp (java.io.tmpdir)
2020/05/10 14:37:20 DEBUG [              main ]       i.n.u.i.PlatformDependent : -Dio.netty.bitMode: 64 (sun.arch.data.model)
2020/05/10 14:37:20 DEBUG [              main ]       i.n.u.i.PlatformDependent : -Dio.netty.maxDirectMemory: -1 bytes
2020/05/10 14:37:20 DEBUG [              main ]       i.n.u.i.PlatformDependent : -Dio.netty.uninitializedArrayAllocationThreshold: -1
2020/05/10 14:37:20 DEBUG [              main ]            i.n.u.i.CleanerJava9 : java.nio.ByteBuffer.cleaner(): available
2020/05/10 14:37:20 DEBUG [              main ]       i.n.u.i.PlatformDependent : -Dio.netty.noPreferDirect: false

### Netty version
    <netty.version>4.1.49.Final</netty.version>
### JVM version (e.g. `java -version`)
    JDK13
### OS version (e.g. `uname -a`)
    WIN10

**Comment by slandelle** [comment]
Those are just DEBUG logs when initializing Netty internals, not an issue.

**Comment by heixiaoma** [comment]
Yes. This error occurs when debugging a project. I don't know how to avoid it

**Comment by slandelle** [comment]
Again, there's no error, those are **DEBUG** logs, not ERROR ones.
If you don't want to see them, properly configure your logging framework, typically [slf4j](http://www.slf4j.org/) + a backend such as [logback](http://logback.qos.ch/).

**Comment by heixiaoma** [comment]
Thank you for your reply. The debug log is not the error log. It's OK to configure one
