### ISSUE TITLE
If the request contains a string of millions of lengths, and if the request is sent at a very high rate, will it cause an io.netty.util.internal.OutOfDirectMemoryError exception?

### ISSUE THREAD

**Issue by asdf2014** [netty/netty#10282]
If the request contains a string of millions of lengths, and if the request is sent at a very high rate, will it cause an `io.netty.util.internal.OutOfDirectMemoryError` exception?

BTW, I have tried many times and have not found the LEAK log..

### Expected behavior

Netty service runs steadily without reporting OOM exceptions.

### Actual behavior

```java
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 788529159, max: 804257792)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:742)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:697)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:215)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	at io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:777)
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

### Steps to reproduce

Many requests containing a string of millions of lengths are sent at a very high rate

### Netty version

4.1.47.Final

### JVM version (e.g. `java -version`)

```bash
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

### OS version (e.g. `uname -a`)

Linux x86_64 GNU/Linux

**Comment by asdf2014** [comment]
@normanmaurer PTAL. Even if `-Dio.netty.leakDetection.level=advanced` and `-Dio.netty.leakDetectio.maxRecords=10` were added to increase the leak detection level, no LEAK logs were found..

**Comment by asdf2014** [comment]
@normanmaurer FYI, I increased the `-XX:MaxDirectMemorySize` parameter, and after running the program for a long time, only one LEAK message appeared, as follows:

```java
Recent access records: 
#1:
	Hint: 'decoder' will handle the message from this point.
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.lang.Thread.run(Thread.java:748)
#2:
	Hint: 'DefaultChannelPipeline$HeadContext#0' will handle the message from this point.
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.lang.Thread.run(Thread.java:748)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
	io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:777)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	java.lang.Thread.run(Thread.java:748)
```

**Comment by normanmaurer** [comment]
@asdf2014 what is decoder here ?

**Comment by asdf2014** [comment]
@normanmaurer The decoder is [WordSplitter](https://github.com/opentsdb/opentsdb/blob/master/src/tsd/WordSplitter.java).

**Comment by normanmaurer** [comment]
@asdf2014 are you sure this is the right one as it used netty 3... ?

**Comment by asdf2014** [comment]
@normanmaurer Most of the logic is the same, except that we use `ByteToMessageDecoder` instead of `OneToOneDecoder` to adapt to Netty 4.

**Comment by normanmaurer** [comment]
@asdf2014 please share the code...

**Comment by johnou** [comment]
Anyway sounds like you need to implement some batching or stream logic, it shouldn't OOM unless you are writing faster than you can process or you really are trying to allocate a single string instance that big.. you might consider working with the data at bye array or even better bytebuf level.

**Comment by asdf2014** [comment]
@normanmaurer Sorry I can't.. @johnou Thanks for your comment. Indeed, it may be because the speed of accepting the request is too fast. After lowering the maxContentLength parameter of HttpObjectAggregator, many requests with too large Content-Length will be rejected, and indeed the OOM exception is no longer reported. Yep, I am also considering whether it can be processed at the byte array or ByteBuf level.

**Comment by normanmaurer** [comment]
@asdf2014 sorry without seeing the code I can not help much I guess.

**Comment by asdf2014** [comment]
@normanmaurer It does not matter, you have helped a lot, thank you for taking the time to help follow up this issue, thank you very much.

**Comment by asdf2014** [comment]
Hi, @normanmaurer . I am so glad to tell you that this problem has been solved by limiting the number of active channels. As mentioned by @johnou, the speed of writing data from Netty is faster than the speed we can process in the back-end program, which cause the direct memory couldn't be released in time, resulting in OOM exceptions. Thank you both for following up this issue, thank you very much!

**Comment by normanmaurer** [comment]
Closing this
