### ISSUE TITLE
Server-side NotYetConnectedException

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#10298]
I am investigating a very strange and intermittent failure observed in Netty where an `EpollSocketChannel`-based server will encounter a `NotYetConnectedException` when apparently trying to interact with its client:

```
(epollEventLoopGroup-3-16) {MyChannelInboundHandler#exceptionCaught}: java.nio.channels.NotYetConnectedException: null 
     at io.netty.channel.unix.Errors.ioResult(Errors.java:171) 
     at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:143) 
     at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:348) 
     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:778) 
     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) 
     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) 
     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) 
     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
     at java.lang.Thread.run(Thread.java:834)
```

https://github.com/netty/netty/blob/91a7f49f0daa38f657d31b6d6335606bcf380f26/transport-native-unix-common/src/main/java/io/netty/channel/unix/Errors.java#L170-L172

It occurs *after* the server has successfully read at least some bytes from the client. I am also *not* observing a `channelInactive` before this exception occurs.

It occurs *very* rarely (< 0.00001%) but on enough repeat occasions to be concerning. I so far have been unable to correlate it to any other patterns that might stick out. It happens rarely enough that I am starting to suspect some type of bug or race in the Netty/Epoll/Kernel/TCP layers.

So my question is: what could possibly explain a server encountering `ERRNO_ENOTCONN_NEGATIVE` when reading from a client socket (without first receiving a `channelInactive`)?

As a side note, I think the usage of `NotYetConnectedException` is potentially a bit misleading here, as [`ENOTCONN`](https://stackoverflow.com/a/902964) simply means the socket is not connected (but perhaps it previously was).

### Netty version

4.1.49

### JVM version

JDK 11

**Comment by normanmaurer** [comment]
@Bennett-Lynch interesting... I will check once I have a few cycles

**Comment by Bennett-Lynch** [comment]
I'm closing this out for now since I have a little more data showing some of the original assumptions to be incorrect. I still suspect there is an issue here with Netty's Epoll implementation and I will create a separate issue once I have more details.
