### ISSUE TITLE
How to solve the problem of frequent memory broadcast and memory overflow?

### ISSUE THREAD

**Issue by itlidaye** [netty/netty#10315]
How to solve the problem of frequent memory broadcast and memory overflow?
`
 protected void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {
        //logger.info("channelRead0 {}",msg);
        try {
            SocketIO.sendMessage(msg);
        }finally {

        }

    }

public class SocketIO {

    private static final Set<Channel> CHANNEL_GROUP= new ConcurrentHashSet<>();

    public static boolean add(Channel channel){
        return CHANNEL_GROUP.add(channel);
    }

    public static boolean remove(Channel channel){
        return CHANNEL_GROUP.remove(channel);
    }

    public static void sendMessage(Object msg){
        for (Channel channel : CHANNEL_GROUP) {
            ReferenceCountUtil.retain(msg);
            channel.writeAndFlush(msg);
        }
    }

}`

![heap](https://user-images.githubusercontent.com/15826407/82797146-3ee3ce80-9ea9-11ea-8c8d-476dc4494c79.png)
![object](https://user-images.githubusercontent.com/15826407/82797152-41462880-9ea9-11ea-88f2-4034858f0b99.png)

**Comment by zhenjunMa** [comment]
```
public static void sendMessage(Object msg){
    for (Channel channel : CHANNEL_GROUP) {
        ReferenceCountUtil.retain(msg);
        channel.writeAndFlush(msg);
    }
    //maybe need this?
    ReferenceCountUtil.release(msg);
}
```

**Comment by itlidaye** [comment]
>  ReferenceCountUtil.release(msg);

This is not needed

**Comment by normanmaurer** [comment]
Actually the `release(msg)` is needed as `retain(msg)` is called before

**Comment by itlidaye** [comment]
> Actually the `release(msg)` is needed as `retain(msg)` is called before
Thank you, this can solve the problem of memory overflow

**Comment by itlidaye** [comment]
> Actually the `release(msg)` is needed as `retain(msg)` is called before
@normanmaurer 

            ReferenceCountUtil.release(msg);
            for (Channel channel : CHANNEL_GROUP) {
                ReferenceCountUtil.retain(msg);
                channel.writeAndFlush(msg);
            }

io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.util.internal.ReferenceCountUpdater.retain0(ReferenceCountUpdater.java:123)
	at io.netty.util.internal.ReferenceCountUpdater.retain(ReferenceCountUpdater.java:110)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.retain(AbstractReferenceCountedByteBuf.java:80)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.retain(AbstractReferenceCountedByteBuf.java:26)
	at io.netty.util.ReferenceCountUtil.retain(ReferenceCountUtil.java:40)
	at com.shiku.socket.core.SocketIO.sendMessage(SocketIO.java:43)
	at com.shiku.socket.handler.PacketHandler.channelRead0(PacketHandler.java:19)

**Comment by zhenjunMa** [comment]
@itlidaye 
you should call release() at last  like what i said above
> ```
> public static void sendMessage(Object msg){
>     for (Channel channel : CHANNEL_GROUP) {
>         ReferenceCountUtil.retain(msg);
>         channel.writeAndFlush(msg);
>     }
>     ReferenceCountUtil.release(msg);
> }
> ```
