### ISSUE TITLE
Epoll client channel throws NotYetConnectedException on connect failure

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#10411]
I am observing a intermittent failure case where a client using the `EpollSocketChannel` transport will have a `NotYetConnectedException` raised on its pipeline as part of a connection attempt failing.

### Expected behavior

Connection failures will result in the `connect()` future failing and not invoke any handlers in the channel pipeline.

### Actual behavior

`NotYetConnectedException` is sometimes thrown on the pipeline for the failed channel:

```
(epollEventLoopGroup-3-16) {ChannelInboundHandler#exceptionCaught}: java.nio.channels.NotYetConnectedException: null
     at io.netty.channel.unix.Errors.ioResult(Errors.java:171)
     at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:143)
     at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:348)
     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:778)
     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
     at java.lang.Thread.run(Thread.java:834)
```

Accompanied by `ClosedChannelException` for the actual connect future:

```
java.nio.channels.ClosedChannelException: null
     at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:957)
     at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(AbstractChannel.java:976)
     at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:552)
     at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
     at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
     at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
     at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.connect(CombinedChannelDuplexHandler.java:495)
     at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:51)
     at io.netty.channel.CombinedChannelDuplexHandler.connect(CombinedChannelDuplexHandler.java:296)
     at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
     at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
     at io.netty.handler.logging.LoggingHandler.connect(LoggingHandler.java:231)
     at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:548)
     at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:533)
     at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:517)
     at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:978)
     at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:253)
     at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:250)
     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
     at java.lang.Thread.run(Thread.java:834)
```

### Steps to reproduce

Issue happens very intermittently and is difficult to reproduce on-demand.

I am not deeply familiar w/ Epoll so I am raising this issue to see if someone with more experience here might be able to spot some type of defect. I think these lines from the stack trace are relevant:

```
     at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:348)
     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:778)
     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
```

https://github.com/netty/netty/blob/4e86f768b916a34d3a929251eff8428ef47be65d/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L468-L476

https://github.com/netty/netty/blob/4e86f768b916a34d3a929251eff8428ef47be65d/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java#L778

https://github.com/netty/netty/blob/4e86f768b916a34d3a929251eff8428ef47be65d/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollChannel.java#L347-L348

I noticed that commit https://github.com/netty/netty/commit/c7cb104dc48f179b61ed1146b6c0529c2e1115bc#diff-db3e069239a403b954e3ebc024ba9507L336 removed a `&& ch.isOpen()` check that used to previously guard the `epollInReady()` call:

https://github.com/netty/netty/blob/dbbdbe11a6237cc08a9a6eafeeac9c7d80924305/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollEventLoop.java#L336

I'm wondering if that behavior is correct. Rather than dropping `ch.isOpen()` to support half-closed, should there at least be a check to see if the channel was *ever* open? I suspect this change might make sense from a server perspective but perhaps not a client perspective?

### Netty version

4.1.50

**Comment by normanmaurer** [comment]
On my to do list for tomorrow....

**Comment by normanmaurer** [comment]
alright... it took me a bit more then expected but I am looking at this as we speak.

**Comment by normanmaurer** [comment]
@Bennett-Lynch so I did look into it a bit today and honestly I still have no idea what exactly happens. I mean we could "hide" the error by checking `isOpen()` but this still does not feel right to me as I would like to understand why it happens in the first place. 

So this can only happen if the FD is closed before the connect(...) is actually executed which means something must have called `close()` before. I wonder what this was. It may be something that happened during pipeline initialisation (like for example during `channelRegistered(....)` calls. Do you have some more details for me how the pipeline looks like in terms of handlers ?

**Comment by Bennett-Lynch** [comment]
> @Bennett-Lynch so I did look into it a bit today and honestly I still have no idea what exactly happens. I mean we could "hide" the error by checking isOpen() but this still does not feel right to me as I would like to understand why it happens in the first place.

Thanks a bunch for taking a look, @normanmaurer. Agree on not just hiding it. Likewise, I have considered placing an `isOpen()` check in my own pipeline before trying to handle this exception, but that also does not feel right.

> So this can only happen if the FD is closed before the connect(...) is actually executed which means something must have called close() before. I wonder what this was.

Are we sure this is always the case? See [here](https://stackoverflow.com/questions/900042/what-causes-the-enotconn-error/902964#902964) for other potential explanations of `ENOTCONN`, which I believe is the error code triggering this behavior. Are we making potentially faulty assumptions about what some of the Epoll error codes might represent?

> It may be something that happened during pipeline initialisation (like for example during channelRegistered(....) calls. Do you have some more details for me how the pipeline looks like in terms of handlers?

Sure. The only Netty handlers in the pipeline are `HttpClientCodec` and `LoggingHandler`. There are a few custom handlers in the pipeline but none of them use `channelRegistered(..)` or `handlerAdded(..)`.

There does exist logic outside of the pipeline that may try to close the client channel, but I have metrics for when this behavior is triggered and it does not appear to be triggered in this case. It looks like this though:

```
connectFuture.addListener(ChannelFutureListener.CLOSE);
connectFuture.cancel(true);
```

Again, I am quite confident that this behavior is not being triggered, but I will do some additional validation to ensure that.

**Comment by normanmaurer** [comment]
> Are we sure this is always the case? See here for other potential explanations of ENOTCONN, which I believe is the error code triggering this behavior. Are we making potentially faulty assumptions about what some of the Epoll error codes might represent?

Yes I am pretty sure in this case as you can see from your stack trace `connect` (sys call) is never called which means the socket was never connected in the first place.

> Sure. The only Netty handlers in the pipeline are HttpClientCodec and LoggingHandler. There are a few custom handlers in the pipeline but none of them use channelRegistered(..) or handlerAdded(..).

> There does exist logic outside of the pipeline that may try to close the client channel, but I have metrics for when this behavior is triggered and it does not appear to be triggered in this case. It looks like this though:

> connectFuture.addListener(ChannelFutureListener.CLOSE);
connectFuture.cancel(true);

> Again, I am quite confident that this behavior is not being triggered, but I will do some additional validation to ensure that.

Actually this is interesting as I think this could lead up to the situation where we may race and close the channel in between which in this case would just close the FD.

Also as a side note even if the channel is never connected you may see `exceptionCaught` be called if for example ?`channelRegistered(...)` or `handlerAdded(...)` throws.

@Bennett-Lynch would it be possible for you to run a custom jar with some more logging enabled when this issue happens ?

**Comment by Bennett-Lynch** [comment]
> Actually this is interesting as I think this could lead up to the situation where we may race and close the channel in between which in this case would just close the FD.

I wonder if `cancel(true)` would make this more racy than `cancel(false)`? Again, I don't think this is being triggered, but I will try to confirm this with 100% confidence. I will need to await some recent changes to be rolled out before validating.

> Also as a side note even if the channel is never connected you may see exceptionCaught be called if for example ?channelRegistered(...) or handlerAdded(...) throws.

Understood, as far as I can tell this is not the case though.

> @Bennett-Lynch would it be possible for you to run a custom jar with some more logging enabled when this issue happens ?

I would probably be more likely to be able to apply custom git diffs/patches rather than an entire jar. Would also need the logging to only be during exceptional cases. If it logs extra in the happy case it will be quite noisy and expensive.

**Comment by rishika728** [comment]
@normanmaurer , is there some way possible to find which handler in the channel pipeline triggered the read() ? The exception stack trace simply reports the `EpollEventLoop.processReady()` as the trigger point, but doesn't mention anything about the caller/trigger handler. Does the`EpollEvent` have any useful information that could be used to decipher the trigger handler class ? 

```
(epollEventLoopGroup-3-16) {ChannelInboundHandler#exceptionCaught}: java.nio.channels.NotYetConnectedException: null
     at io.netty.channel.unix.Errors.ioResult(Errors.java:171)
     at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:143)
     at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:348)
     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:778)
     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
     at java.lang.Thread.run(Thread.java:834)
```

**Comment by rishika728** [comment]
@normanmaurer, any ideas w.r.t the last few updates.

**Comment by normanmaurer** [comment]
Please re-open if you still see this
