### ISSUE TITLE
Specified EventLoop in DnsNameResolverBuilder is not used at runtime

### ISSUE THREAD

**Issue by violetagg** [netty/netty#10460]
### Expected behavior
Specified `EventLoop` in `DnsNameResolverBuilder` is used at runtime

### Actual behavior
Specified `EventLoop` in `DnsNameResolverBuilder` is NOT used at runtime

### Steps to reproduce
Scenario 1. Run the provided example below, you will see that the resolver and the client use one and the same `EventLoop`
Scenario 2. Run the provided example below with `-DuseKQueue` and kqueue natives in the path, the following exception will be thrown

```
Exception in thread "main" java.lang.IllegalStateException: failed to create a new resolver
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:72)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:194)
	at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:180)
	at io.netty.bootstrap.Bootstrap$1.operationComplete(Bootstrap.java:166)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetSuccess(AbstractChannel.java:984)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:504)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.nio.NioEventLoop

Caused by: java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.nio.NioEventLoop
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:461)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:87)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:81)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:323)
	at io.netty.bootstrap.AbstractBootstrap.register(AbstractBootstrap.java:227)
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:456)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:473)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:111)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:91)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:76)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:70)
	... 22 more
```

The problem is that in the code below the channel's event loop replaces the original configuration.
https://github.com/netty/netty/blob/686df17b1a1bca9ca2d26fe53e5e4eb3404a6b3f/transport/src/main/java/io/netty/bootstrap/Bootstrap.java#L191-L194

Also the exception `java.lang.IllegalStateException: incompatible event loop type: io.netty.channel.nio.NioEventLoop`
is thrown because the channel's event loop replaces the original configuration, but the channel factory is taken
from the original configuration. When different transport is used for the resolver and for the client the event loop
and the channel factory are not compatible.

### Minimal yet complete reproducer code (or URL to code)

```
public class Application {
	static final boolean USE_KQUEUE = System.getProperty("useKQueue") != null;

	public static void main(String[] args) throws Exception {
		SslContext sslCtx = SslContextBuilder.forClient().build();

		EventLoopGroup clientGroup = new NioEventLoopGroup(1);

		EventLoopGroup resolverGroup;
		DnsAddressResolverGroup resolver;
		if (USE_KQUEUE) {
			resolverGroup = new KQueueEventLoopGroup(1);
			resolver = new DnsAddressResolverGroup(
					new DnsNameResolverBuilder(resolverGroup.next())
							.channelFactory(KQueueDatagramChannel::new)
							.socketChannelFactory(KQueueSocketChannel::new));
		}
		else {
			resolverGroup = new NioEventLoopGroup(1);
			resolver = new DnsAddressResolverGroup(
					new DnsNameResolverBuilder(resolverGroup.next())
							.channelFactory(NioDatagramChannel::new)
							.socketChannelFactory(NioSocketChannel::new));
		}

		try {
			Bootstrap b = new Bootstrap();
			b.group(clientGroup)
			 .channel(NioSocketChannel.class)
			 .resolver(resolver)
			 .handler(new ChannelInitializer<Channel>() {
			     @Override
			     protected void initChannel(Channel ch) {
			         ch.pipeline().addLast(sslCtx.newHandler(ch.alloc()), new LoggingHandler());
			     }
			 });

			Channel ch = b.connect("example.com", 443).sync().channel();

			ch.closeFuture().sync();
		}
		finally {
			clientGroup.shutdownGracefully();
			resolverGroup.shutdownGracefully();
		}
	}
}
```

### Netty version
Latest snapshot

### JVM version (e.g. `java -version`)
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)

### OS version (e.g. `uname -a`)
Mac OS

**Comment by normanmaurer** [comment]
Yep that is a bug...

**Comment by normanmaurer** [comment]
@violetagg PTAL https://github.com/netty/netty/pull/10479
