### ISSUE TITLE
UnsupportedOperationException with NonStickyEventExecutorGroup

### ISSUE THREAD

**Issue by qerub** [netty/netty#10501]
Netty version: 4.1.45

While investigating an application issue I came across an interesting exception:

```
java.lang.UnsupportedOperationException
  at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.iterator(BaseMpscLinkedArrayQueue.java:201)
  at java.util.AbstractCollection.remove(AbstractCollection.java:282)
  at io.netty.util.conuccrent.NonStickyEventExecutorGroup$NonStickOrderedEventExecutor.execute(NonStickEventExecutorGroup.java:342)
  at io.netty.channel.DefaultChannelPipline.callHandlerAddedInEventLoop(DefaultChannelPipeline.java:1138)
  at io.netty.channel.DefaultChannelPipline.addLast(DefaultChannelPipeline.java:219)
```

The code in question looks like this:

https://github.com/netty/netty/blob/338e1a991c5d15695bd654a7b8d2bd4008e868ae/common/src/main/java/io/netty/util/concurrent/NonStickyEventExecutorGroup.java#L338-L344

The call to `remove` will always fail because `tasks` is a `PlatformDependent.newMpscQueue()` that doesn't implement `remove` or `iterator`. Looks like a dormant bug in 4 year old code to me (that didn't wake up until our application failed in an exceptional way).

**Comment by normanmaurer** [comment]
will have a look...

**Comment by normanmaurer** [comment]
@qerub honestly I think we should just remove the `tasks.remove(...)` call here. WDYT ?

**Comment by qerub** [comment]
@normanmaurer: I unfortunately don't fully grasp all the state transitions and thread intertwinings of this code, but I think that `tasks.remove(command)` doesn't make sense (and should be removed as you suggest) since there's no connection between the `command` and `executor.execute(this)` failing (the `command` is executed via `safeExecute` and has been dequeued so it won't affect later execution runs).
