### ISSUE TITLE
SslHandler should have option to enable / disable harmless exceptions

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#10587]
### Expected behavior.
SslHandler should have an option of whether we want to swallow harmless exceptions or not.

### Actual behavior
SslHandler throws an exception in itself and we're unable to handle it.

### Steps to reproduce
Do anything which causes SslHandler to throw a swallow exception.

### Minimal yet complete reproducer code (or URL to code)
NONE

### Netty version
4.1.52.Final

### JVM version (e.g. `java -version`)
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.8.10.1 (build 11.0.8+10-LTS, mixed mode)

### OS version (e.g. `uname -a`)
Windows 10 Pro 64-Bit

**Comment by hyperxpro** [comment]
```
18 Sep 2020 12:23:17.808 [nioEventLoopGroup-3-1] DEBUG i.n.h.s.SslHandler - [id: 0x6f041a86, L:/192.168.1.5:9110 - R:/192.168.1.5:21172] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
18 Sep 2020 12:23:18.313 [nioEventLoopGroup-3-1] DEBUG i.n.h.s.SslHandler - [id: 0x6f041a86, L:/192.168.1.5:9110 - R:/192.168.1.5:21172] Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred while writing close_notify in response to the peer's close_notify
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:233) ~[?:?]
	at sun.nio.ch.IOUtil.read(IOUtil.java:223) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:358) ~[?:?]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at java.lang.Thread.run(Thread.java:834) [?:?]
18 Sep 2020 12:23:18.316 [nioEventLoopGroup-3-1] INFO  c.s.e.c.s.t.UpstreamHandler - Closing Upstream 192.168.1.5:21172 and Downstream 127.0.0.1:9111 Channel

Process finished with exit code -1
```

**Comment by hyperxpro** [comment]
Okay, I see:
```java
 @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        if (ignoreException(cause)) {
            // It is safe to ignore the 'connection reset by peer' or
            // 'broken pipe' error after sending close_notify.
            if (logger.isDebugEnabled()) {
                logger.debug(
                        "{} Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred " +
                        "while writing close_notify in response to the peer's close_notify", ctx.channel(), cause);
            }

            // Close the connection explicitly just in case the transport
            // did not close the connection automatically.
            if (ctx.channel().isActive()) {
                ctx.close();
            }
        } else {
            ctx.fireExceptionCaught(cause);
        }
    }
```

But I think we should have some way to configure whether want to swallow or not.

**Comment by johnou** [comment]
Can you extend the handler and override ignoreException?

**Comment by hyperxpro** [comment]
> Can you extend the handler and override ignoreException?

If SslHandler is created by SniHandler then I can't.

**Comment by violetagg** [comment]
> > Can you extend the handler and override ignoreException?
> 
> If SslHandler is created by SniHandler then I can't.

You should be able to provide your own SslHandler
https://github.com/netty/netty/blob/79a7c157a3e122872321844b73c4881e412dba77/handler/src/main/java/io/netty/handler/ssl/SniHandler.java#L150-L152

**Comment by hyperxpro** [comment]
Perfect! Thanks a lot @violetagg!

Hope this code will help someone else too in future. :)
```java
import io.netty.channel.ChannelHandlerContext;
import io.netty.handler.ssl.SslHandler;

import javax.net.ssl.SSLEngine;

public final class TLSHandler extends SslHandler {

    public TLSHandler(SSLEngine engine) {
        super(engine);
    }

    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
        ctx.fireExceptionCaught(cause);
    }
}
```
