### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by sealte** [netty/netty#10593]
### Expected behavior
No error is thrown.
### Actual behavior
The following error is thrown:

```java
Caused by: io.netty.channel.socket.ChannelOutputShutdownException: Channel output shutdown
	at io.netty.channel.AbstractChannel$AbstractUnsafe.shutdownOutput(AbstractChannel.java:640)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:949)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:898)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer;
	at io.netty.buffer.PooledByteBuf._internalNioBuffer(PooledByteBuf.java:189)
	at io.netty.buffer.PooledByteBuf.internalNioBuffer(PooledByteBuf.java:201)
	at io.netty.channel.ChannelOutboundBuffer.nioBuffers(ChannelOutboundBuffer.java:447)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:392)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
	... 17 more
```

### Steps to reproduce
Run the provided reproducer code.
### Minimal yet complete reproducer code (or URL to code)
https://github.com/sealte/nety4152bug/blob/a7437dd15b023c5ba00c80e4a3821948949b60ba/src/test/java/com/example/netty4152bug/Netty4152BugApplicationTests.java#L15
### Netty version
4.1.52.Final
### JVM version (e.g. `java -version`)
/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version (e.g. `uname -a`)
Darwin vapple.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

### Description
Based on the error, it seems to be compiled in JDK 8 incompatible way somehow. FYI, the method signature of java.nio.ByteBuffer.limit() has been changed since JDK 9.

JDK 8:
```java
Buffer limit(int newLimit)
```
JDK 13:
```java
ByteBuffer limit(int newLimit)
```
I confirmed that it's working with JDK 13.

**Comment by slandelle** [comment]
> Based on the error, it seems to be compiled in JDK 8 incompatible way somehow.

Exactly. You can't compile Netty with Java 9+ and have it run with Java 8 because you would bind to a method that doesn't exist. Java is backward compatible (old code can run on new JVM), not forward compatible (the other way around).

>  FYI, the method signature of java.nio.ByteBuffer.limit() has been changed since JDK 9.

Not exactly. Old Buffer methods are still there but ByteBuffer now overrides to return ByteBuffer instead of Buffer.

The only workaround would be to uglify the code to use static helpers that would take a Buffer to force proper bind.

**Comment by normanmaurer** [comment]
hmm... This is strange as we release netty from a docker container that uses java8. Are you sure this happens by just depend on the netty jar ?

**Comment by johnou** [comment]
@normanmaurer I think we can work around this by casting to java.nio.Buffer.

**Comment by johnou** [comment]
see https://github.com/classgraph/classgraph/commit/dbc97867416f81efcc633334a6a9cf27b699caac

**Comment by slandelle** [comment]
@sealte Did you recompile Netty yourself?

**Comment by sealte** [comment]
Sorry, my mistake.  I recompile Netty use JDK13 for [#10562](https://github.com/netty/netty/issues/10562).
This bug doesn't exists.
