### ISSUE TITLE
SSLEngine Close called again by Http2ConnectionHandler

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#10634]
### Expected behavior
If Channel is closed due to an exception, then `ctx.channel().close();` call is made. This closes SSLEngine also.

### Actual behavior
`Http2ConnectionHandler` calls for SSLEngine Close even after it's already closed and tries to send `GOAWAY` frame.

### Steps to reproduce
Establish connection with HTTP/2, close the connection from client forcefully to cause an exception, and `Http2ConnectionHandler` will try to close SSLEngine again.

### Minimal yet complete reproducer code (or URL to code)
In Handler:
```java
    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        ctx.channel().close();
    }
```
In ALPNHandler:
```java
@Override
    protected void configurePipeline(ChannelHandlerContext ctx, String protocol) {
        if (protocol.equalsIgnoreCase(ApplicationProtocolNames.HTTP_2)) {
            ctx.pipeline().addLast(
                    Http2FrameCodecBuilder.forServer()
                            .autoAckSettingsFrame(true)
                            .autoAckPingFrame(true)
                            .validateHeaders(true)
                            .build(),
                    new HTTP2Handler()
            );
        } else if (protocol.equalsIgnoreCase(ApplicationProtocolNames.HTTP_1_1)) {
            // DA DA DA
        }
    }
```
### Netty version
4.1.52.Final
### JVM version (e.g. `java -version`)
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.8.10.1 (build 11.0.8+10-LTS, mixed mode)

### OS version (e.g. `uname -a`)
Windows 10 Pro x64

**Comment by hyperxpro** [comment]
Stacktrace:
```
03 Oct 2020 13:53:52.998 [nioEventLoopGroup-3-1] DEBUG i.n.h.l.LoggingHandler - [id: 0x1dcb8464, L:/192.168.1.100:9110 - R:/192.168.1.100:1100] EXCEPTION: java.io.IOException: An established connection was aborted by the software in your host machine
java.io.IOException: An established connection was aborted by the software in your host machine
	at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_265]
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43) ~[?:1.8.0_265]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_265]
	at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_265]
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377) ~[?:1.8.0_265]
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:253) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1133) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:350) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
03 Oct 2020 13:53:52.998 [nioEventLoopGroup-3-1] DEBUG i.n.h.l.LoggingHandler - [id: 0x1dcb8464, L:/192.168.1.100:9110 - R:/192.168.1.100:1100] CLOSE
03 Oct 2020 13:53:53.000 [nioEventLoopGroup-3-1] DEBUG i.n.h.c.h.Http2ConnectionHandler - [id: 0x1dcb8464, L:/192.168.1.100:9110 - R:/192.168.1.100:1100] Sending GOAWAY failed: lastStreamId '1', errorCode '0', debugData ''. Forcing shutdown of the connection.
javax.net.ssl.SSLException: SSLEngine closed already
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:854) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:811) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:792) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.close(Http2ConnectionHandler.java:476) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.logging.LoggingHandler.close(LoggingHandler.java:247) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:622) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:606) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:472) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:957) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:232) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at com.shieldblaze.expressgateway.core.server.http.HTTP2Handler.exceptionCaught(HTTP2Handler.java:109) [classes/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.logging.LoggingHandler.exceptionCaught(LoggingHandler.java:205) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.exceptionCaught(Http2ConnectionHandler.java:567) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at com.shieldblaze.expressgateway.core.tls.SNIHandler$TLSHandler.exceptionCaught(SNIHandler.java:109) [classes/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:125) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:177) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.52.Final.jar:4.1.52.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
03 Oct 2020 13:53:53.005 [nioEventLoopGroup-3-1] DEBUG i.n.h.l.LoggingHandler - [id: 0x1dcb8464, L:/192.168.1.100:9110 ! R:/192.168.1.100:1100] USER_EVENT: io.netty.channel.socket.ChannelInputShutdownReadComplete@6887c7bc
03 Oct 2020 13:53:53.005 [nioEventLoopGroup-3-1] DEBUG i.n.h.l.LoggingHandler - [id: 0x1dcb8464, L:/192.168.1.100:9110 ! R:/192.168.1.100:1100] INACTIVE

```

**Comment by ka11i0** [comment]
Hello. Could you provide complete reproduce code?? I'm having trouble reproducing your error with the code you provided.

**Comment by hyperxpro** [comment]
1. Start HTTP/2 Server
2. Connect Client to Server
3. Forcefully close the connection so that you get: `java.io.IOException: An established connection was aborted by the software in your host machine`.
4. Since the channel is already closed, `Http2ConnectionHandler` will try to send `GOAWAY` but everything is closed. `Http2ConnectionHandler` should not send `GOAWAY` is the channel is closed.

**Comment by normanmaurer** [comment]
This is expected... we only try to write the go away if the channel is still active. that said it is possible that while we try to process pending writes in the `SslHandler` we will close the `SSLEngine` and so will fail all the remaining pending writes.
