### ISSUE TITLE
NIOSocketChannel consuming heap

### ISSUE THREAD

**Issue by vamsiganji** [netty/netty#10660]
### Actual behavior

We have 5 NIOSocketChannel sessions occupying 12GB of heap out of 24 GB. One of them 3 GB

### Steps to reproduce

Not sure how to reproduce, but the issue keeps happening every 2 weeks

![image](https://user-images.githubusercontent.com/72225830/95485763-2b209c80-0960-11eb-8f7c-b29694ac0fd4.png)

### Netty version

4.1.16

### JVM version (e.g. `java -version`)

OpenJDK Runtime Environment (Zulu 8.27.0.7-linux64) (build 1.8.0_162-b01)
OpenJDK 64-Bit Server VM (Zulu 8.27.0.7-linux64) (build 25.162-b01, mixed mode)

### OS version (e.g. `uname -a`)

Linux t4rtp-epn4-e1 3.10.0-1101.el7.x86_64 #1 SMP Sun Nov 24 10:56:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chrisvest** [comment]
Your Netty version is 3 years old. Try upgrading it to 4.1.52.Final and see if the problem persists.

**Comment by vamsiganji** [comment]
Thanks for the reply, we have already deployed our product in the production and see the issue there . Can you please confirm if this issue is fixed in the latest library? Updating the library in production is a very long process

**Comment by chrisvest** [comment]
It can't confirm that it's fixed because it's not clear what the cause is.

**Comment by vamsiganji** [comment]
Is there a way we can enable some debugs in netty to get more information when this happens again ?

**Comment by normanmaurer** [comment]
your best bet is to check in the heap dump to see where the memory is consumed and what holds the reference to it.

**Comment by hyperxpro** [comment]
@vamsiganji  2 GB memory consumption under load full or normally? Can you give brief information about the load?

**Comment by vamsiganji** [comment]
@hyperxpro when NIO occupies 12 GB of heap we see the problem with the application. Total of 5 NIO sessions( 3 GB - 1 GB each)  occupy 12 GB in this case. In a normal situation, these should not go over 100 MB of heap space. 

We have a total of 24GB assigned to the process.

**Comment by normanmaurer** [comment]
Without looking at the whole heapdump I can not tell you what is wrong... it should be visible in the heapdump what the problem is

**Comment by vamsiganji** [comment]
@normanmaurer would it be possible for you to take a quick look at the heap if we can give you access to MAT ?

**Comment by normanmaurer** [comment]
sorry but I don't have the time atm... It should be quite easy to spot what exactly takes up so much space....

**Comment by vamsiganji** [comment]
Thanks for the reply. From what i see EPollSelectorImpl is the object consuming memory. As i drill down this object i see more and more instances of EPollSelectorImpl, some thing like a recursion. Please check the below image

![image](https://user-images.githubusercontent.com/72225830/95977670-2425de00-0de7-11eb-8f75-e9aa975f1573.png)

**Comment by hyperxpro** [comment]
Did you tried upgrading to Netty 4.1.53.Final?

**Comment by vamsiganji** [comment]
@hyperxpro we are having this issue in production environment in one of our customers. So the update to the library can happen only in the next release which will take time. How ever we want to find out the root cause of this issue and confirm if this is fixed in 4.1.53 version.

**Comment by normanmaurer** [comment]
While there seems to be multiple selectors it seems like all of these are different instances (at least from a quick look).  I would check what is stored in the NioSocketChannel itself for example ... it may be that some handler in the pipeline of the channel does hold up a lot of memory for example.

Beside this it could also be a JDK bug ... looking at the version you are using I would suggest upgrading it as well. There version in use is multiple years old...

**Comment by vamsiganji** [comment]
@normanmaurer Could this be related to

 https://issues.redhat.com/browse/XNIO-172?page=com.atlassian.streams.streams-jira-plugin%3Aactivity-stream-issue-tab ?

**Comment by vamsiganji** [comment]
@normanmaurer We do see the below stack traces when the issue happens. I know this is quite old of an issue, but can you please help to see if this related to https://github.com/netty/netty/pull/565 ? 

java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x00007f22baf76690> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x00007f22baf70298> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00007f22baf70158> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)

**Comment by normanmaurer** [comment]
I don't think so...  Like I said I am sure some of the handlers in the pipeline for example hold up on  lot of memory . Inspect the heap dump and you will find it.

**Comment by vamsiganji** [comment]
@normanmaurer Thanks for the reply. I looked at the heapdump i dont see any handler holding up the memory. All i see is many objects of EPollSelectorImpl . I am really stuck here

![image](https://user-images.githubusercontent.com/72225830/96857966-a8064880-142d-11eb-8749-e12dffabdca0.png)

**Comment by normanmaurer** [comment]
If you can provide me with the heap dump I can have a look this week. You can sent the link to norman dot maurer at googlemmail dot com

**Comment by Aaron-zheng** [comment]
hi all, i hit the same problem as well. the heap dump will stuck in the epollselectorImpl loop. 
@vamsiganji @normanmaurer is it possible by upgrading the netty version to fix this problem?

**Comment by xing535** [comment]
i hit the same problem as well.May I ask if it can be resolved by upgrading the version。


> hi all, i hit the same problem as well. the heap dump will stuck in the epollselectorImpl loop. @vamsiganji @normanmaurer is it possible by upgrading the netty version to fix this problem?

**Comment by zy0000001** [comment]
I have also encountered this problem. How can I solve it?

**Comment by xing535** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by normanmaurer** [comment]
Please upgrade and let us know if you still see the issue...

**Comment by xing535** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by normanmaurer** [comment]
English please @xing535
