### ISSUE TITLE
question for mulitpart name and filename (MemoryFileUpload)

### ISSUE THREAD

**Issue by thomasmey** [netty/netty#10779]
Hi,

one question regarding the name and filename that is being passed to the MemoryFileUpload.

My selfmade fuzzer insert a randomly generated string, i.e. full unicode into the name and filename of multipart/data.
are there any restrictions regarding the content of the name and filename?
what happens when the name/filename contains characters like "; (i.e. characters being used in creating content-disposition header itself?

because on the consuming side I see error in parsing the created multipart body:

[...] Caused by: java.lang.IllegalArgumentException: Error parsing content disposition: form-data; name="???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????"?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????N?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? ?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? ?????????????????????"; filename="???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????"?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????N?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? ?????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????? ?????????????????????"
	at org.glassfish.jersey.media.multipart.FormDataBodyPart.getContentDisposition(FormDataBodyPart.java:197)
	at org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readMultiPart(MultiPartReaderClientSide.java:224)
	... 66 common frames omitted
Caused by: java.text.ParseException: Next event is not a Separator
	at org.glassfish.jersey.message.internal.HttpHeaderReader.nextSeparator(HttpHeaderReader.java:119)
	at org.glassfish.jersey.message.internal.HttpHeaderReader.readParameters(HttpHeaderReader.java:284)
	at org.glassfish.jersey.media.multipart.ContentDisposition.<init>(ContentDisposition.java:69)
	at org.glassfish.jersey.media.multipart.FormDataContentDisposition.<init>(FormDataContentDisposition.java:72)
	at org.glassfish.jersey.media.multipart.FormDataContentDisposition.<init>(FormDataContentDisposition.java:68)
	at org.glassfish.jersey.media.multipart.FormDataBodyPart.getContentDisposition(FormDataBodyPart.java:195)

(above logging prints non-ascii characters as ?)

it looks like the name string contains a " which isn't escaped by netty.

ideas?

### Netty version
4.1.52.Final

**Comment by chrisvest** [comment]
@thomasmey Hi Thomas. Do you think you could create a self-contained automated test for this? The parsing in this area is kind of complicated, and from [reading](https://tools.ietf.org/html/rfc7578#section-4.2) [the](https://tools.ietf.org/html/rfc2183#section-2.3) [specs](https://tools.ietf.org/html/rfc5987) it's not really clear to me how it should be handled.
