### ISSUE TITLE
Cannot write/flush HTTP/2 with voidPromise

### ISSUE THREAD

**Issue by valerauko** [netty/netty#10816]
### Expected behavior
Can `write` / `writeAndFlush` frames that may close the stream from a HTTP/2 context

### Actual behavior
`Http2ConnectionHandler#closeStream` tries to `addListener` to the future even if it's void. If void, that will fail.

### Steps to reproduce
`writeAndFlush` a Http2DataFrame to the context with Http2FrameCodec present

### Minimal yet complete reproducer code (or URL to code)
Ran into this using netty [from Clojure](https://github.com/valerauko/iny/blob/7e71ddf649d5b64626139beb784eabf9b5ad88a5/src/iny/http2/handler.clj#L86-L98).

### Netty version
4.1.54

**Comment by valerauko** [comment]
@normanmaurer I wrapped the `addListener` call in a try-catch to extract the stacktrace:

```
2020-11-30 12:54:06,441 ERROR [epollEventLoopGroup-3-5] io.netty.util.internal.logging.AbstractInternalLogger | Unexpected exception: 
java.lang.IllegalStateException: void future
	at io.netty.channel.VoidChannelPromise.fail(VoidChannelPromise.java:198)
	at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:58)
	at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:26)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStream(Http2ConnectionHandler.java:623)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.closeStreamLocal(Http2ConnectionHandler.java:587)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledBase.writeComplete(DefaultHttp2ConnectionEncoder.java:622)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.writeAllocatedBytes(DefaultHttp2RemoteFlowController.java:368)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.write(DefaultHttp2RemoteFlowController.java:547)
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor$State.write(WeightedFairQueueByteDistributor.java:604)
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:292)
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distributeToChildren(WeightedFairQueueByteDistributor.java:325)
	at io.netty.handler.codec.http2.WeightedFairQueueByteDistributor.distribute(WeightedFairQueueByteDistributor.java:273)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:627)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes(DefaultHttp2RemoteFlowController.java:267)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:189)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
        at (my handler) ...
```
