### ISSUE TITLE
IndexOutOfBoundsException in HttpPostMultipartRequestDecoder.offer() when Netty updated 4.1.49 -> 4.1.54 

### ISSUE THREAD

**Issue by IgorAlelekov** [netty/netty#10824]
### Expected behavior
No Exception thrown 

### Actual behavior
Exception thrown in ServerHandler
java.lang.IndexOutOfBoundsException: writerIndex(178) + minWritableBytes(178) exceeds maxCapacity(178): UnpooledSlicedByteBuf(ridx: 178, widx: 178, cap: 178/178, unwrapped: CompositeByteBuf(ridx: 0, widx: 178, cap: 178, components=1))
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:296)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:282)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1105)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1098)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1089)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:340)
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:52)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
	at test.TestServerHandler.channelRead0(TestServerHandler.java:57)

### Steps to reproduce
Launch attached TestServer and TestClient to see Exception thrown in TestServer

### Netty version
4.1.54

### JVM version (e.g. `java -version`)
1.8.0_131

### OS version (e.g. `uname -a`)
win10

**Comment by IgorAlelekov** [comment]
[test.zip](https://github.com/netty/netty/files/5596363/test.zip)

**Comment by doom369** [comment]
@IgorAlelekov looks like the same as https://github.com/netty/netty/issues/10281. I have to override `HttpPostMultipartRequestDecoder` in order to fix it.

**Comment by IgorAlelekov** [comment]
Thanks, @doom369, could you please to share your own fix as workaround?
