### ISSUE TITLE
Check for valid status codes should be done in CloseWebSocketFrame instead of WebSocketCloseStatus

### ISSUE THREAD

**Issue by violetagg** [netty/netty#10838]
According to the specification https://tools.ietf.org/html/rfc6455#section-7.4

```
1006 is a reserved value and MUST NOT be set as a status code in a
Close control frame by an endpoint.  It is designated for use in
applications expecting a status code to indicate that the
connection was closed abnormally, e.g., without sending or
receiving a Close control frame.
```

I want to use `WebSocketCloseStatus` in the applications in order to indicate that the
connection was closed abnormally.

I do not intent to send `CloseWebSocketFrame` with such `WebSocketCloseStatus` (with 1006 status code).

However the current implementation checks the validity of the status codes in `WebSocketCloseStatus`
instead of `CloseWebSocketFrame`.

Isn't it more correct if the check for a valid status code is in `CloseWebSocketFrame`?

### Expected behavior
To be able to create `WebSocketCloseStatus` with status code 1006
and `CloseWebSocketFrame ` to fail when constructed with `WebSocketCloseStatus` with status code 1006

### Actual behavior
`WebSocketCloseStatus` fails when created with status code 1006

### Proposed solution

I can create a PR with the patch below

```
diff --git a/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CloseWebSocketFrame.java b/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CloseWebSocketFrame.java
index 7231bde8f4..834d0e6eee 100644
--- a/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CloseWebSocketFrame.java
+++ b/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/CloseWebSocketFrame.java
@@ -40,7 +40,7 @@ public class CloseWebSocketFrame extends WebSocketFrame {
      *            example, <tt>1000</tt> indicates normal closure.
      */
     public CloseWebSocketFrame(WebSocketCloseStatus status) {
-        this(status.code(), status.reasonText());
+        this(requireValidStatusCode(status), status.reasonText());
     }
 
     /**
@@ -53,7 +53,7 @@ public class CloseWebSocketFrame extends WebSocketFrame {
      *            Reason text. Set to null if no text.
      */
     public CloseWebSocketFrame(WebSocketCloseStatus status, String reasonText) {
-        this(status.code(), reasonText);
+        this(requireValidStatusCode(status), reasonText);
     }
 
     /**
@@ -201,4 +201,13 @@ public class CloseWebSocketFrame extends WebSocketFrame {
         super.touch(hint);
         return this;
     }
+
+    static int requireValidStatusCode(WebSocketCloseStatus status) {
+        if (WebSocketCloseStatus.isValidStatusCode(status.code())) {
+            return status.code();
+        }
+        else {
+            throw new IllegalArgumentException("WebSocket close status code does NOT comply with RFC-6455: " + status.code());
+        }
+    }
 }
diff --git a/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java b/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java
index 92b1dbaef5..f634240ef5 100644
--- a/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java
+++ b/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketCloseStatus.java
@@ -208,16 +208,26 @@ public final class WebSocketCloseStatus implements Comparable<WebSocketCloseStat
 
     // 1004, 1005, 1006, 1015 are reserved and should never be used by user
     //public static final WebSocketCloseStatus SPECIFIC_MEANING = register(1004, "...");
-    //public static final WebSocketCloseStatus EMPTY = register(1005, "Empty");
-    //public static final WebSocketCloseStatus ABNORMAL_CLOSURE = register(1006, "Abnormal closure");
-    //public static final WebSocketCloseStatus TLS_HANDSHAKE_FAILED(1015, "TLS handshake failed");
+
+    public static final WebSocketCloseStatus EMPTY =
+        new WebSocketCloseStatus(1005, "Empty");
+
+    public static final WebSocketCloseStatus ABNORMAL_CLOSURE =
+        new WebSocketCloseStatus(1006, "Abnormal closure");
+
+    public static final WebSocketCloseStatus TLS_HANDSHAKE_FAILED =
+        new WebSocketCloseStatus(1015, "TLS handshake failed");
 
     private final int statusCode;
     private final String reasonText;
     private String text;
 
     public WebSocketCloseStatus(int statusCode, String reasonText) {
-        if (!isValidStatusCode(statusCode)) {
+        this(statusCode, reasonText, true);
+    }
+
+    public WebSocketCloseStatus(int statusCode, String reasonText, boolean validate) {
+        if (validate && !isValidStatusCode(statusCode)) {
             throw new IllegalArgumentException(
                 "WebSocket close status code does NOT comply with RFC-6455: " + statusCode);
         }
```

### Netty version
4.1.55.Final-SNAPSHOT

**Comment by violetagg** [comment]
Also  for `CloseWebSocketFrame` constructors where you can provide directly `int` for the status code, I see that the status code is check when sending the frame, but isn't it better to check it when constructing `CloseWebSocketFrame`?

`new CloseWebSocketFrame(1006, "Abnormal closure")`

```
io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Invalid close frame getStatus code: 1006
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:426)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:422)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.checkCloseFrameBody(WebSocket08FrameDecoder.java:479)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:339)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
```
