### ISSUE TITLE
java.lang.OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by milkywhut** [netty/netty#10897]
Hi! We use spring cloud gateway and write some custom web filters. We've catch an error java.lang.OutOfMemoryError: Direct buffer memory and see some memory leaks with help of jvm option -Dio.netty.leakDetection.level=advanced.

Our jvm options:

```
 -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
                -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC
                -XX:+UseStringDeduplication -XX:G1ReservePercent=10
                -XX:SoftRefLRUPolicyMSPerMB=1
                -XX:HeapDumpPath=/home/jboss/dumps/heap/
                -Dio.netty.leakDetection.level=advanced
```
```
2020-12-11 10:57:59.379  WARN 21 --- [or-http-epoll-2] r.netty.http.client.HttpClientConnect    : [id: 0x1fdea6b5, L:/10.124.35.214:50428 - R:my-server-backend/170.30.56.193:80] The connection observed an error

io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Direct buffer memory
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:104) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[netty-transport-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[netty-transport-native-epoll-4.1.51.Final-linux-x86_64.jar!/:4.1.51.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.51.Final.jar!/:4.1.51.Final]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
`Caused by: java.lang.OutOfMemoryError: Direct buffer memory
        at java.base/java.nio.Bits.reserveMemory(Bits.java:175) ~[na:na]
        at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118) ~[na:na]
        at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317) ~[na:na]
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:755) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:731) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:247) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:215) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.buffer.PoolArena.reallocate(PoolArena.java:394) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:306) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.buffer.AbstractByteBuf.setCharSequence0(AbstractByteBuf.java:703) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.buffer.AbstractByteBuf.writeCharSequence(AbstractByteBuf.java:1188) ~[netty-buffer-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.handler.codec.http.HttpRequestEncoder.encodeInitialLine(HttpRequestEncoder.java:68) ~[netty-codec-http-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.handler.codec.http.HttpRequestEncoder.encodeInitialLine(HttpRequestEncoder.java:28) ~[netty-codec-http-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:95) ~[netty-codec-http-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:189) ~[netty-codec-http-4.1.51.Final.jar!/:4.1.51.Final]
        at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89) ~[netty-codec-4.1.51.Final.jar!/:4.1.51.Final]
        ... 11 common frames omitted
```

During that pod's RAM overflows that leads to pod's restart.

Example of our filter:
```
@Slf4j
@Component
@RequiredArgsConstructor
public class JwtAuthenticationFilter implements WebFilter, PermissionFilter {

    private final JwtService tokenService;
    private final AuthenticationService authenticationService;
    private final AuthorizedClientStoreService authorizedClientStore;

    @Override
    public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain webFilterChain) {
        ServerHttpRequest request = exchange.getRequest();
        ServerHttpResponse response = exchange.getResponse();

        if (isPermitAll(request.getURI().getPath())) {
            return webFilterChain.filter(exchange);
        }

        String authorization = null;
        String negotiate = null;
        String authCode = RestUtils.getAuthorizationCodeCookieFromHttpRequest(request);
        if (StringUtils.isNotBlank(authCode)) {
            AuthorizedClientStoredEntity entity
                    = authorizedClientStore.getAuthorizedClientStoredEntityByAuthorizationCode(authCode);
            negotiate = entity.getNegotiate();
            OAuth2AuthorizedClient client
                    = authorizedClientStore.constructOAuth2AuthorizedClientFromAuthorizedClientStoredEntity(entity);
            if (client != null) {
                authorization = RestConstants.BEARER + client.getAccessToken().getTokenValue();
            }
        }
        //TODO remove before official release. Saved for backward compatibility for test purposes
        else {
            HttpCookie accessTokenCookie = RestUtils.getHttpCookieByName(RestConstants.ACCESS_TOKEN, request.getCookies());
            if (accessTokenCookie != null) {
                authorization = RestConstants.BEARER + accessTokenCookie.getValue();
            }
        }

        //TODO remove before official release. Saved for backward compatibility for test purposes
        if (StringUtils.isBlank(authorization)) {
            authorization = request.getHeaders()
                    .getFirst(AuthorizationHeader.AUTHORIZATION_HEADER);
        }

        //TODO Saved for backward compatibility for test purposes. In official release authorization must not be blank because it will be obtained from OAuth2 authentication
        if (StringUtils.isNotBlank(authorization)) {
            return handleAuthorizationHeader(authorization, negotiate, exchange, request, response, webFilterChain);
        } else {
            return redirectTo(RestConstants.OAUTH2_SIGN_IN_URI, exchange, request, response);
        }
    }

    public Mono<Void> handleAuthorizationHeader(String bearerToken,
                                                String negotiate,
                                                ServerWebExchange exchange,
                                                ServerHttpRequest request,
                                                ServerHttpResponse response,
                                                WebFilterChain webFilterChain) {
        String facadeAccessToken = bearerToken.replace(RestConstants.BEARER, StringUtils.EMPTY);
        TokenVerificationResult verificationResult = tokenService.validateFacadeAccessToken(facadeAccessToken);
        switch (verificationResult.getStatus()) {
            case VALID:
                JwtToken accessTokenModel = tokenService.parseFacadeAccessTokenToModel(facadeAccessToken);
                JwtAuthentication auth = new JwtAuthentication(facadeAccessToken, accessTokenModel, true);
                return authenticate(bearerToken, negotiate, auth, exchange, webFilterChain);
            case EXPIRED:
                return redirectTo(RestConstants.REFRESH_URI, exchange, request, response);
            case INVALID:
            default:
                return redirectTo(RestConstants.OAUTH2_SIGN_IN_URI, exchange, request, response);
        }
    }

    public Mono<Void> authenticate(String bearerToken,
                                   String negotiate,
                                   JwtAuthentication auth,
                                   ServerWebExchange exchange,
                                   WebFilterChain webFilterChain) {
        ServerWebExchange exchangeWithPrincipal = exchange.mutate().request(
                exchange.getRequest().mutate()
                        .header(RestConstants.AUTHORIZATION_HEADER, bearerToken)
                        .header(RestConstants.NEGOTIATE.trim(), negotiate)
                        .build()).principal(Mono.just(auth)).build();
        Context securityContext = ReactiveSecurityContextHolder.withSecurityContext(Mono.just(new SecurityContextImpl(auth)));
        return webFilterChain.filter(exchangeWithPrincipal)
                .subscriberContext(context -> context.putAll(securityContext));
    }

    private Mono<Void> redirectTo(String redirectUrl,
                                  ServerWebExchange exchange,
                                  ServerHttpRequest request,
                                  ServerHttpResponse response) {
        authenticationService.holdRedirectUrl(request, response);
        response.getHeaders().add(RestConstants.LOCATION, redirectUrl);
        response.setStatusCode(HttpStatus.FOUND);
        return Mono.empty();
    }
```

![image](https://user-images.githubusercontent.com/15321390/103137146-d5969900-46df-11eb-87f4-657d4cb1e89b.png)

Heap dump analysis with jxray:
![image](https://user-images.githubusercontent.com/15321390/103137342-9b2dfb80-46e1-11eb-98fd-26aa52f7e808.png)

Memory diff gotten with jcmd:
```
[0x00007efe82a2164f] Unsafe_AllocateMemory0+0x5f
[0x00007efe648b2350]
                             (malloc=197040KB type=Other +114688KB #60 +7)
```
Heap dump:
[heap_oom.zip](https://github.com/netty/netty/files/5742107/heap_oom.zip)
Jxray analysis:
[oom_jxray.pdf](https://github.com/netty/netty/files/5742109/oom_jxray.pdf)
Combined logs:
[log.txt](https://github.com/netty/netty/files/5742117/log.txt)

Native memory diff:
[jcmd_detailed_native_memory_diff.txt](https://github.com/netty/netty/files/5742114/jcmd_detailed_native_memory_diff.txt)

### Netty version
io.projectreactor.netty:reactor-netty:jar:0.9.11.RELEASE from org.springframework.boot:spring-boot-starter-parent:2.3.3.RELEASE with org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR8

io.projectreactor.netty:reactor-netty:jar:0.9.15.RELEASE  from org.springframework.boot:spring-boot-starter-parent:2.3.7.RELEASE with org.springframework.cloud:spring-cloud-dependencies:Hoxton.SR9

### JVM version (e.g. `java -version`)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9+11-LTS, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Redhat openjdk/openjdk-11-rhel7 packed in docker image and running on openshift

Please provide us with any suggestions how to fix this problem. I'm still thinking that it's our code issue.

**Comment by normanmaurer** [comment]
Please open in the reactor repo...From your logs it seems like you miss to release buffers. I am not sure if this usually needs to be done by the user of project-reactor or if it should be done under the hood by it. /cc @violetagg

**Comment by violetagg** [comment]
@milkywhut I would recommend you to open issue in Spring Cloud Gateway/Reactor Netty repository.
