### ISSUE TITLE
OpenSslX509TrustManagerWrapper - java.security.NoSuchProviderException: no such provider: SunJSSE

### ISSUE THREAD

**Issue by ihudedi** [netty/netty#10901]
Hi,
In OpenSslX509TrustManagerWrapper you specify hard coded SunJSSE provider.
In case I don't have this provider ( I am using BCJSSE)
I am getting the following error:
2020-12-28 23:23:10,101 DEBUG [ForkJoinPool.commonPool-worker-3] (OpenSslX509TrustManagerWrapper:97) -  Unable to access wrapped TrustManager
java.security.NoSuchProviderException: no such provider: SunJSSE
               at sun.security.jca.GetInstance.getService(Unknown Source) ~[?:?]
               at sun.security.jca.GetInstance.getInstance(Unknown Source) ~[?:?]
               at javax.net.ssl.SSLContext.getInstance(Unknown Source) ~[?:?]
               at io.netty.handler.ssl.OpenSslX509TrustManagerWrapper.newSSLContext(OpenSslX509TrustManagerWrapper.java:159) ~[netty-handler-4.1.53.Final.jar!/:4.1.53.Final]
               at io.netty.handler.ssl.OpenSslX509TrustManagerWrapper.<clinit>(OpenSslX509TrustManagerWrapper.java:64) ~[netty-handler-4.1.53.Final.jar!/:4.1.53.Final]
               at io.netty.handler.ssl.ReferenceCountedOpenSslContext.chooseTrustManager(ReferenceCountedOpenSslContext.java:577) ~[netty-handler-4.1.53.Final.jar!/:4.1.53.Final]
               at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext.newSessionContext(ReferenceCountedOpenSslClientContext.java:154) ~[netty-handler-4.1.53.Final.jar!/:4.1.53.Final]
               at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:194) ~[netty-handler-4.1.53.Final.jar!/:4.1.53.Final]
               at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:827) ~[netty-handler-4.1.53.Final.jar!/:4.1.53.Final]
               at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:576) ~[netty-handler-4.1.53.Final.jar!/:4.1.53.Final]

Thanks,
Itay

**Comment by normanmaurer** [comment]
This is expected and the reason why it is only logged via `debug`. Does the log show up more then once ?

**Comment by ihudedi** [comment]
Hi @normanmaurer 
No it print only once.
Thanks,
Itay

**Comment by normanmaurer** [comment]
So like I said this is expected... Lets close this
