### ISSUE TITLE
Blocking call in UnixResolverDnsServerAddressStreamProvider.parse

### ISSUE THREAD

**Issue by violetagg** [netty/netty#10925]
### Expected behavior

No blocking calls reported by BlockHound

### Actual behavior

The exception below appears when BlockHound is installed

```
reactor.blockhound.BlockingOperationError: Blocking call! java.io.FileInputStream#readBytes
     	at java.io.FileInputStream.readBytes(FileInputStream.java)
     	at java.io.FileInputStream.read(FileInputStream.java:255)
     	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
     	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
     	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
     	at java.io.InputStreamReader.read(InputStreamReader.java:184)
     	at java.io.BufferedReader.fill(BufferedReader.java:161)
     	at java.io.BufferedReader.readLine(BufferedReader.java:324)
     	at java.io.BufferedReader.readLine(BufferedReader.java:389)
     	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parse(UnixResolverDnsServerAddressStreamProvider.java:175)
     	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:98)
     	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:133)
     	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:72)
     	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.provider(DnsServerAddressStreamProviders.java:139)
     	at io.netty.resolver.dns.DnsServerAddressStreamProviders$DefaultProviderHolder$1.nameServerAddressStream(DnsServerAddressStreamProviders.java:129)
     	at io.netty.resolver.dns.DnsNameResolver.doResolveAllUncached0(DnsNameResolver.java:1070)
     	at io.netty.resolver.dns.DnsNameResolver.access$600(DnsNameResolver.java:90)
     	at io.netty.resolver.dns.DnsNameResolver$6.run(DnsNameResolver.java:1053)
     	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
     	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
     	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
     	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
     	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
     	at java.lang.Thread.run(Thread.java:748)
```

### Netty version

4.1.57.Final

### JVM version (e.g. `java -version`)

JDK 8

### OS version (e.g. `uname -a`)

MacOS

**Comment by normanmaurer** [comment]
@violetagg can you provide a PR ?

**Comment by violetagg** [comment]
@normanmaurer I was thinking for allowing blocking calls when loading `etcResolverFiles`, is that what you are thinking also?

**Comment by normanmaurer** [comment]
This sounds good
