### ISSUE TITLE
4.1.57 could not load a native library: netty_transport_native_unix_linux aarch_64/x86_64

### ISSUE THREAD

**Issue by matteobertozzi** [netty/netty#10926]
### Expected behavior
Epoll.isAvailable() should return true, since it's available

### Actual behavior
using 4.1.57 Epoll.isAvailable() is returning false since netty_transport_native_unix could not be loaded with 4.1.56 there is no problem. I can reproduce the result on both x86 and aarch64
```
Caused by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_unix_linux_aarch_64
Caused by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_unix_linux_x86_64
```
```
java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.channel.unix.Unix.ensureAvailability(Unix.java:111)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:40)
	at test.netty.App.main(App.java:7)
Caused by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_unix_linux_x86_64
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
	at io.netty.channel.unix.Unix.loadNativeLibrary(Unix.java:84)
	at io.netty.channel.unix.Unix.<clinit>(Unix.java:56)
	... 2 more
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_unix
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
		at io.netty.channel.unix.Unix.loadNativeLibrary(Unix.java:87)
		... 3 more
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_unix.so
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
		... 4 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_unix in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1873)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
			... 4 more
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_unix in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
				at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
				at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
				at java.base/java.lang.System.loadLibrary(System.java:1873)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.base/java.lang.reflect.Method.invoke(Method.java:566)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:385)
				at java.base/java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:377)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
				... 5 more
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_unix_linux_x86_64.so
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:175)
	... 4 more
	Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_unix_linux_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
		at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
		at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
		at java.base/java.lang.System.loadLibrary(System.java:1873)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:351)
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
		... 4 more
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_unix_linux_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
			at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
			at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
			at java.base/java.lang.System.loadLibrary(System.java:1873)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.base/java.lang.reflect.Method.invoke(Method.java:566)
			at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:385)
			at java.base/java.security.AccessController.doPrivileged(Native Method)
			at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:377)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:341)
			... 5 more
```

### Steps to reproduce
 - simple main app with Epoll.isAvailable()
 - build with 4.1.56 epoll is available
 - build with 4.1.57 epoll is not available
 - if using netty-all, epoll is available on x86 but not on aarch64

### Minimal yet complete reproducer code (or URL to code)
https://gist.github.com/matteobertozzi/779cf48ad1464b121061a02c46cdc5dc

### Netty version
4.1.57

### JVM version (e.g. `java -version`)
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)

openjdk version "15.0.1" 2020-10-20
OpenJDK Runtime Environment Corretto-15.0.1.9.1 (build 15.0.1+9)
OpenJDK 64-Bit Server VM Corretto-15.0.1.9.1 (build 15.0.1+9, mixed mode, sharing)

openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode)

### OS version (e.g. `uname -a`)
Linux 5.4.0-1035-aws

**Comment by njhill** [comment]
I see the same issue when upgrading to 4.1.47.Final.
