### ISSUE TITLE
IndexOutOfBoundsException in the SniHandler for the specific clients

### ISSUE THREAD

**Issue by doom369** [netty/netty#10922]
After adding `SniHandler` to the pipeline I'm getting IndexOutOfBoundsException errors for some clients:

```
12:38:21.226 DEBUG- Unexpected client hello packet: 160301005d0100005903011111111111111111111111111111111111111111111111111111111111111111200c9ad2d690dc2a9db30ffe91f223e7c5ecd895ce8662feb6aa91c3d4d066558b001200040005002f00160013000a0009000300120100
java.lang.IndexOutOfBoundsException: index: 89, length: 2 (expected: range(0, 89))
	at io.netty.buffer.AbstractByteBuf.checkRangeBounds(AbstractByteBuf.java:1426) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1433) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1420) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.buffer.AbstractByteBuf.getShort(AbstractByteBuf.java:375) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.buffer.AbstractByteBuf.getUnsignedShort(AbstractByteBuf.java:391) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.handler.ssl.AbstractSniHandler.extractSniHostname(AbstractSniHandler.java:69) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:124) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:149) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[x-0.68.2-SNAPSHOT-1,459.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

It doesn't necessarily mean that's this is `SniHandler` bug, it could be a wrong TLS header, however, I'm don't have enough knowledge here to make conclusions. Is that expected behavior for the `SniHandler`?

Netty version: 4.1.56.Final
netty-tcnative-boringssl-static: 2.0.35.Final

**Comment by normanmaurer** [comment]
Nope... will have a look

**Comment by normanmaurer** [comment]
@doom369 This looks a malformed Handshake as we check the "length" up front and so we should never have any problems to access needed data.
