### ISSUE TITLE
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory

### ISSUE THREAD

**Issue by wenlongkang** [netty/netty#10979]
server broadcast messages to 1600 clients and the I log out the direct buffer ，the direct buffer keep growing, cause an io.netty.util.internal.OutOfDirectMemoryError exception. when the server stop send messages to client the direct buffer  not released.

### Actual behavior
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 520093696, max: 524288000)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:725)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:680)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
        at io.netty.buffer.PoolArena.reallocate(PoolArena.java:397)
        at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:119)
        at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:310)
        at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:281)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1118)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1111)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1102)
        at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:777)
        at io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:593)
        at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:96)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)

### Steps to reproduce

server broadcast messages to 1600 clients  about 50 messages per second

### Minimal yet complete reproducer code (or URL to code)

public final class MessageDecoder extends ByteToMessageDecoder {
	
	private final static Logger logger = LoggerFactory.getLogger(MessageDecoder.class);

    @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf in, List<Object> out) throws Exception {
        //decodeByte(in, out);
        //decodeFrames(in, out);
        byte b = in.readByte();
        if(b == Packet.KEEPALIVE_BYTE){
            out.add(new Packet((byte)TypeEnum.KEEPALIVE_VALUE));
        }else if(b == Packet.PULL_MSG_BYTE){
            out.add(new Packet((byte)TypeEnum.PULL_VALUE));
        }else {
            in.readerIndex(in.readerIndex() - 1);
            int readableBytes = in.readableBytes();
            if(readableBytes > Packet.HEADER_LENGTH){
                in.markReaderIndex();
                Packet packet = decodeFrame1(in);
                if(packet == null){
                    in.resetReaderIndex();
                }else {
                    out.add(packet);
                }
            }
        }
    }

    private Packet decodeFrame1(ByteBuf in) {

        byte headerLength = in.readByte();//1
        int bodyLength = in.readInt();//4
        byte cmd = in.readByte();//1
        byte subtype = in.readByte();//1
        int diyType  = in.readInt();//4
        int dataId = in.readInt();//4
        int readableBytes = in.readableBytes();
        if(bodyLength > readableBytes){
            return null;
        }
        Packet packet = new Packet();
        packet.body = new byte[bodyLength];
        in.readBytes(packet.body);
        packet.setSubType(subtype);
        packet.setCmd(cmd);
        packet.setDataId(dataId);
        packet.setDiyType(diyType);

        return packet;
    }

}

@ChannelHandler.Sharable
public final class MessageEncoder extends MessageToByteEncoder<Packet> {
	
    public static final MessageEncoder INSTANCE = new MessageEncoder();

    private static Logger logger = LoggerFactory.getLogger(MessageEncoder.class);

    @Override
    protected void encode(ChannelHandlerContext ctx, Packet packet, ByteBuf out) throws Exception {

        if (packet.cmd == TypeEnum.KEEPALIVE_VALUE) {          //packet.cmd == Packet.KEEPALIVE_BYTE
            out.writeByte(Packet.KEEPALIVE_BYTE);
        } 
        else if(packet.cmd == (byte)TypeEnum.PULL_VALUE){   //packet.cmd == Packet.PULL_MSG_BYTE
            out.writeByte(Packet.PULL_MSG_BYTE);
        }
        else {
        	out.writeByte(Packet.HEADER_LENGTH);
            out.writeInt(packet.getBodyLength());
            out.writeByte(packet.cmd);
            out.writeByte(packet.subType);
            out.writeInt(packet.diyType);
            out.writeInt(packet.dataId);
            if (packet.getBodyLength() > 0) {
                out.writeBytes(packet.body);
            }
        }
    }
}

public class DirectMemoryReporter {
    private Logger log = LoggerFactory.getLogger(DirectMemoryReporter.class);
    private AtomicLong atomicLong;
    private void init() throws ClassNotFoundException, NoSuchFieldException {

        Field field = ReflectionUtils.findField(PlatformDependent.class, "DIRECT_MEMORY_COUNTER");
        field.setAccessible(true);
        try {
            atomicLong = (AtomicLong) field.get(PlatformDependent.class);
        }catch (Exception e){

        }
    }

    public void start() throws NoSuchFieldException, ClassNotFoundException {
        init();

        Executors.newSingleThreadScheduledExecutor().scheduleAtFixedRate(new Runnable() {
            @Override
            public void run() {
                long MB = atomicLong.get()/1024/1024;
                log.info("DirectMemory : {}",MB);
            }
        },0,1, TimeUnit.SECONDS);
    }
}
### Netty version
4.1.42.Final

### JVM version (e.g. `java -version`)
[root@bogon live]# java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) Server VM (build 25.261-b12, mixed mode)

### OS version (e.g. `uname -a`)
[root@bogon live]# uname -a
Linux bogon 3.10.0-862.el7.x86_64 #1 SMP Fri Apr 20 16:44:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by hyperxpro** [comment]
Release those `ByteBuf`s.

**Comment by wenlongkang** [comment]
> Release those `ByteBuf`s.

my decoder extend ByteToMessageDecoder ,should I release bytebuffer by my self？

**Comment by hyperxpro** [comment]
> > Release those `ByteBuf`s.
> 
> hi, @hyperxpro my decoder extend ByteToMessageDecoder ,should I release bytebuffer by my self？

No. Release buffer when you create yourself else clear or fully consume the buffer created by internal Netty.

**Comment by wenlongkang** [comment]
I did not create the Bytebyf myself ...and I  added the  -Dio.netty.leakDetectionLevel=paranoid  parameter ,but no LEAK logs were found.

**Comment by hyperxpro** [comment]
Try to clear (or read everything) the buffer in decoder.

**Comment by wenlongkang** [comment]
@hyperxpro  When should I clear the bytebuffer? In my decoder, if the readable length of bytebuf is less than the length of my message, I didn‘t read from bytebuf and returned directly without clear the bytebuf,Is this correct？

**Comment by hyperxpro** [comment]
I am not too sure but you've to clear the `ByteBuf` once you're done with it in your decoder.

**Comment by sdman123** [comment]
@wenlongkang Hello, I also encountered this problem, how did you solve this problem finally?
