### ISSUE TITLE
Unexpected WebClient blocks reported by BlockHound

### ISSUE THREAD

**Issue by aztosca** [netty/netty#11004]
I'm new to webflux so I posted a [question on stackoverflow](https://stackoverflow.com/questions/66091050/why-is-webclient-blocking-in-this-web-flux-app) thinking I was doing something wrong in my code, but after seeing [this issue](https://github.com/netty/netty/issues/10925) and related [pull request](https://github.com/netty/netty/pull/10935), I'm thinking I just need to tell BlockHound to ignore some calls. 

I created [my own BlockHoundIntegration](https://github.com/aztosca/web-client-test/blob/master/src/main/java/org/app/webclienttest/MyBlockHoundIntegration.java) that suppresses the BlockHound exceptions when added to the BlockHound.install() call, but wanted to raise an issue here to see if maybe this is something that should be addressed in NettyBlockHoundIntegration.

### Expected behavior
No blocking calls reported by BlockHound
### Actual behavior
Blocking calls reported by BlockHound
### Steps to reproduce

1. Run the simple boot app linked below in the _reproducer code_ section.
2. target http://localhost:8080/test-web-client

### Minimal yet complete reproducer code (or URL to code)
https://github.com/aztosca/web-client-test
https://github.com/aztosca/web-client-test/blob/master/src/main/java/org/app/webclienttest/WebClientTestApplication.java
### Netty version
4.1.58
### JVM version (e.g. `java -version`)
openjdk version "11.0.2"
### OS version (e.g. `uname -a`)
MacOS 11.2

**Comment by aztosca** [comment]
Thanks @violetagg . [MyBlockHoundIntegration](https://github.com/aztosca/web-client-test/blob/master/src/main/java/org/app/webclienttest/MyBlockHoundIntegration.java) had another entry that allows reading the truststore. Was there any reason not to include this (or similar) in the PR? I understand some things shouldn't be allowed by default and maybe folks need to make up their on mind on this one.

I did some testing with WebClient and can see that the blocking call only happens once on the first http**s** endpoint WebClient calls so it seems like I can safely allow it.

For quick reference of the BlockHound setting and blocking call it allows...

```
        builder.allowBlockingCallsInside(
        		"io.netty.handler.ssl.SslContext",
        		"newClientContextInternal");
```

```
Caused by: reactor.blockhound.BlockingOperationError: Blocking call! java.io.FileInputStream#readBytes
	at java.base/java.io.FileInputStream.readBytes(FileInputStream.java)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:271)
	at java.base/sun.security.util.DerValue.init(DerValue.java:388)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:331)
	at java.base/sun.security.util.DerValue.<init>(DerValue.java:344)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1993)
	at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:222)
	at java.base/java.security.KeyStore.load(KeyStore.java:1479)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.loadKeyStore(TrustStoreManager.java:365)
	at java.base/sun.security.ssl.TrustStoreManager$TrustAnchorManager.getTrustedCerts(TrustStoreManager.java:313)
	at java.base/sun.security.ssl.TrustStoreManager.getTrustedCerts(TrustStoreManager.java:55)
	at java.base/sun.security.ssl.TrustManagerFactoryImpl.engineInit(TrustManagerFactoryImpl.java:49)
	at java.base/javax.net.ssl.TrustManagerFactory.init(TrustManagerFactory.java:278)
	at java.base/sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:88)
	at java.base/javax.net.ssl.SSLContext.init(SSLContext.java:297)
	at io.netty.handler.ssl.JdkSslContext.<clinit>(JdkSslContext.java:75)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:821)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:577)
        ......
```

**Comment by violetagg** [comment]
@aztosca In the example, I do not see the SslContext customisation. https://github.com/aztosca/web-client-test/blob/master/src/main/java/org/app/webclienttest/WebClientTestApplication.java

Do you use the default security in WebClient?

**Comment by aztosca** [comment]
Yeah, default. The injected WebClient.Builder I'm using is spring's pre-configured one, and I'm not using any other ssl related command line settings when running the app.
