### ISSUE TITLE
Sporadic connection timeouts

### ISSUE THREAD

**Issue by hypervisorfdi** [netty/netty#11039]
### Expected behavior
No connect timeouts

### Actual behavior
sporadic timeouts:

```
Feb 25 11:28:16 production sysloghost 16:574 WARN  hystrix-rates7 it-ribbon.ConnectByNetty [ApiProxy_production-2.53.0_] [1376034708849074] Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: rates.services.international.com/12.225.246.84:9202
Feb 25 11:28:16 production sysloghost 16:583 WARN  hystrix-location7 it-ribbon.ConnectByNetty [ApiProxy_production-2.53.0_] [1376038585215371] Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: locactions.services.international.com/10.234.16.105:9354
Feb 25 11:28:16 production2 sysloghost 16:669 WARN  hystrix-maps7 it-ribbon.ConnectByNetty [ApiProxy_production2-2.53.0_] [1376033247237515] Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: maps.services.international.com/12.225.16.56:9280
Feb 25 11:28:16 production2 sysloghost 16:673 WARN  hystrix-maps1 it-ribbon.ConnectByNetty [ApiProxy_production2-2.53.0_] [1376033344765043] Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: maps.services.international.com/12.225.16.56:9280
Feb 25 11:28:20 production sysloghost 20:737 WARN  hystrix-maps3 it-ribbon.ConnectByNetty [ApiProxy_production-2.53.0_] [1376042309925718] Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: maps.services.international.com/12.225.16.56:9280
Feb 25 11:28:20 production sysloghost 20:741 WARN  hystrix-configuration2 it-ribbon.ConnectByNetty [ApiProxy_production-2.53.0_] [1376042406841151] Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: configuration.services.international.com/12.225.16.57:9280
```

### Stacktrace

```
 Request Failed.
 com.netflix.client.ClientException: Number of retries on next server exceeded max 1 retries, while making a call for: maps.services.international.com:9280
   at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:352)
   at com.netflix.loadbalancer.reactive.LoadBalancerCommand$4.call(LoadBalancerCommand.java:345)
   at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onError(OperatorOnErrorResumeNextViaFunction.java:140)
   at rx.internal.operators.OperatorRetryWithPredicate$SourceSubscriber$1$1.onError(OperatorRetryWithPredicate.java:107)
   at rx.observers.SerializedObserver.onError(SerializedObserver.java:153)
   at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:78)
   at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.innerError(OnSubscribeConcatMap.java:192)
   at rx.internal.operators.OnSubscribeConcatMap$ConcatMapInnerSubscriber.onError(OnSubscribeConcatMap.java:340)
   at rx.observers.Subscribers$5.onError(Subscribers.java:230)
   at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onError(OnSubscribeDoOnEach.java:87)
   at rx.observers.SerializedObserver.onError(SerializedObserver.java:153)
   at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:78)
   at rx.internal.operators.OnSubscribeConcatMap$ConcatMapSubscriber.onError(OnSubscribeConcatMap.java:155)
   at rx.internal.operators.OperatorDoAfterTerminate$1.onError(OperatorDoAfterTerminate.java:56)
   at rx.internal.operators.OperatorTake$1.onError(OperatorTake.java:65)
   at io.reactivex.netty.protocol.http.client.RedirectOperator$RedirectSubscriber.onError(RedirectOperator.java:237)
   at io.reactivex.netty.protocol.http.client.RequestProcessingOperator$1.onError(RequestProcessingOperator.java:68)
   at rx.internal.operators.OperatorTake$1.onError(OperatorTake.java:65)
   at io.reactivex.netty.client.ConnectionPoolImpl$3.call(ConnectionPoolImpl.java:276)
   at io.reactivex.netty.client.ConnectionPoolImpl$3.call(ConnectionPoolImpl.java:271)
   at rx.observers.Subscribers$3.onError(Subscribers.java:142)
   at io.reactivex.netty.contexts.http.HttpContextClientChannelFactory$ContextCapturingSubscriber.onError(HttpContextClientChannelFactory.java:97)
   at io.reactivex.netty.client.ClientChannelFactoryImpl._onConnectFailed(ClientChannelFactoryImpl.java:145)
   at io.reactivex.netty.client.ClientChannelFactoryImpl.access$000(ClientChannelFactoryImpl.java:41)
   at io.reactivex.netty.client.ClientChannelFactoryImpl$2.operationComplete(ClientChannelFactoryImpl.java:77)
   at io.reactivex.netty.client.ClientChannelFactoryImpl$2.operationComplete(ClientChannelFactoryImpl.java:72)
   at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
   at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
   at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
   at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
   at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
   at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
   at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
   at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:262)
   at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
   at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
   at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
   at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
   at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
   at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
   at java.lang.Thread.run(Thread.java:748)
 Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: maps.services.international.com/12.225.16.56:9280
   at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
   ... 9 more

```

### Steps to reproduce
n/a

### Minimal yet complete reproducer code (or URL to code)
n/a

### Netty version
netty-transport-native-unix-common-4.1.58.Final.jar
netty-common-4.1.58.Final.jar
netty-handler-4.1.58.Final.jar
netty-transport-native-epoll-4.1.58.Final.jar
netty-codec-4.1.58.Final.jar
netty-transport-4.1.58.Final.jar
rxnetty-contexts-0.5.1.jar
netty-buffer-4.1.58.Final.jar
rxnetty-servo-0.5.1.jar
netty-resolver-4.1.58.Final.jar
netty-codec-http-4.1.58.Final.jar
rxnetty-0.5.1.jar

### JVM version (e.g. `java -version`)
1.8.0_201-b09

### OS version (e.g. `uname -a`)
CentOS 7

### current code in use

```
public class ConnectByNetty extends Subscriber<ByteBuf> {
    
    private void writeResponse(HttpClientRequest<ByteBuf> request, LoadBalancingHttpClient<ByteBuf, ByteBuf> client) {
        Subscription subscribtion = null;
        try {
            subscribtion = client
                    .submit(request)
                    .doOnNext(this::updateResponse)
                    .switchMap(HttpClientResponse::getContent)
                    .subscribe(this);
            cdl.await(endpoint.getReadTimeout(), TimeUnit.MILLISECONDS);
        } catch (Exception e) {
            LOG.warn("Request Failed.", e);
            throw new RuntimeException("Request failed.", e);
        } finally {
            if (subscribtion != null) {
                subscribtion.unsubscribe();
            }
        }

        if (toThrow != null) {
            LOG.warn("Request Failed.", toThrow);
            throw new RuntimeException(toThrow);
        }
    }

    @Override
    public void onCompleted() {
        cdl.countDown();
    }

    @Override
    public void onError(Throwable e) {
        toThrow = e;
        cdl.countDown();
    }

    @Override
    public void onNext(ByteBuf t) {
        t.forEachByte(value -> {
            getResp().getOutputStream().write(value);
            return true;
        });
    }
    
    HttpServletResponse getResp() {
        return this.resp;
    }
```

**Comment by normanmaurer** [comment]
Please open the issue in rx-netty ... This just means that netty was not able to connect in the given time (by default the connect timeout is 10s).
