### ISSUE TITLE
DNS name resolution fails (probably related to VPN)

### ISSUE THREAD

**Issue by andrashatvani** [netty/netty#11063]
### Expected behavior
DNS name resolution succeeds with netty as it does with other tools, such as Safari or curl.

### Actual behavior
With nslookup the following result wilt be shown:
```
$ nslookup blueops-keycloak.dev-exahatvani.svc.k8s-test.wrwks.at
Server:		172.19.214.226
Address:	172.19.214.226#53

Non-authoritative answer:
Name:	blueops-keycloak.dev-exahatvani.svc.k8s-test.wrwks.at
Address: 10.131.0.163
```

However, Netty's DNS name resolution gives up after first try of the first DNS server, which is `10.0.0.138`.
```
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'blueops-keycloak.dev-exahatvani.svc.k8s-test.wrwks.at' failed to resolve 'blueops-keycloak.dev-exahatvani.svc.k8s-test.wrwks.at'
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:966)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:414)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:463)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:225)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.0.0.138:53] query via UDP timed out after 5000 milliseconds (no stack trace available)
```

Although there are two resolvers:
```
$ scutil --dns 
DNS configuration

resolver #1
  search domain[0] : wrwks.local
  search domain[1] : home
  nameserver[0] : 172.19.214.226
  nameserver[1] : 172.19.214.227
  flags    : Supplemental, Request A records
  reach    : 0x00000002 (Reachable)
  order    : 1

resolver #2
  nameserver[0] : 10.0.0.138
  if_index : 6 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)
  order    : 200000
```

### Steps to reproduce
I'm using `spring.security.oauth2.resourceserver.jwt.jwk-set-uri` for JWT authentication the following environment:
- my machine is connected via VPN to the client's network
- the server component having trouble with the DNS resolution is run locally
- the server `blueops-keycloak.dev-exahatvani.svc.k8s-test.wrwks.at` which `spring.security.oauth2.resourceserver.jwt.jwk-set-uri` is set to is in a k8s cluster.
Netty apparently doesn't event try the DNS servers ` 172.19.214.226` and ` 172.19.214.226` respectively.

### Minimal yet complete reproducer code (or URL to code)
-

### Netty version
4.1.59

### JVM version (e.g. `java -version`)
openjdk version "15.0.2" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.2+7)

### OS version (e.g. `uname -a`)
Darwin TheMachine 20.4.0 Darwin Kernel Version 20.4.0: Tue Feb 23 23:43:36 PST 2021; root:xnu-7195.100.354.131.1~3/RELEASE_X86_64 x86_64

**Comment by andrashatvani** [comment]
Perhaps not an issue
