### ISSUE TITLE
The server receives incomplete data, causing an exception in Protobuf

### ISSUE THREAD

**Issue by qq443547953** [netty/netty#11085]
### Expected behavior

The server receives incomplete data, causing an exception in Protobuf
MasterHandler.java:198 code：
final Request request = Request.newBuilder().mergeFrom(sm.getBody()).build();

### Actual behavior
```
com.google.protobuf.UninitializedMessageException: Message missing required fields: rid, operate
  at com.google.protobuf.AbstractMessage$Builder.newUninitializedMessageException(AbstractMessage.java:770) ~[protobuf-java-2.5.0.jar!/:na]
  at com.data.jobcenter.protocol.Protocol$Request$Builder.build(Protocol.java:8336) ~[jobcenter-schedule-1.0.0.13.jar!/:1.0.0.13]
  at com.data.jobcenter.schedule.master.MasterHandler.messageReceived(MasterHandler.java:198) ~[jobcenter-schedule-1.0.0.13.jar!/:1.0.0.13]
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.handler.codec.oneone.OneToOneDecoder.handleUpstream(OneToOneDecoder.java:70) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.10.5.Final.jar!/:na]
  at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.10.5.Final.jar!/:na]
--
```
![Uploading image.png…]()

``` server messageReceived 
@Override
	public void messageReceived(ChannelHandlerContext ctx, MessageEvent e) throws Exception {
final Channel channel = ctx.getChannel();
			SocketMessage sm = (SocketMessage) e.getMessage();

			// try {
			DebugInfoLog.info("master接收netty消息 SocketMessage长度 = " + (sm == null ? 0 : sm.toString().length())
					+ ",源地址来自:" + ctx.getChannel().getRemoteAddress() + " 目标地址:" + ctx.getChannel().getLocalAddress()
					+ " kind:" + (sm == null || sm.getKind() == null ? null : sm.getKind().getNumber())+ "时间戳:" + System.currentTimeMillis());
			// } catch (Exception ex) {
			// DebugInfoLog.error("master接收netty消息记录日志时发生异常", ex);
			// }
if (sm.getKind() == Kind.REQUEST) {
				//google protocol解码后返回为 SocketMessage类型类型 if(!(e.getMessage() instanceof SocketMessage)) return; 
				final Request request = Request.newBuilder().mergeFrom(sm.getBody()).build();
				if (request.getOperate() == Operate.HeartBeat) {
					beHeartBeat.beHeartBeat(context, channel, request);
				} else {
					DebugInfoLog.info("master接收netty消息 kind是REQUEST，但operate不是HeartBeat");
				}
```
``` 
 NioServerSocketChannelFactory channelFactory = new NioServerSocketChannelFactory(Executors.newCachedThreadPool(), Executors.newCachedThreadPool());
        bootstrap = new ServerBootstrap(channelFactory);
        pipelineFactory = new ChannelPipelineFactory() {
            private final ProtobufVarint32LengthFieldPrepender frameEncoder = new ProtobufVarint32LengthFieldPrepender();
            private final ProtobufEncoder protobufEncoder = new ProtobufEncoder();

            @Override
            public ChannelPipeline getPipeline() throws Exception {
                ChannelPipeline p = pipeline();
                p.addLast("frameDecoder", new ProtobufVarint32FrameDecoder());
                p.addLast("protobufDecoder", new ProtobufDecoder(Protocol.SocketMessage.getDefaultInstance()));
                p.addLast("frameEncoder", frameEncoder);
                p.addLast("protobufEncoder", protobufEncoder);
                p.addLast("handler", handler);
                return p;
            }

        };
```
### Netty version
3.10.5.Final
### JVM version (e.g. `java -version`)
1.8

**Comment by hyperxpro** [comment]
Netty 3 has reached EOL and is unsupported. Please use the latest version of Netty.
