### ISSUE TITLE
Support for OCSP Stapling

### ISSUE THREAD

**Issue by nycnewman** [netty/netty#11097]
### Expected behavior

Library supports ability to use OCSP Stapling when using JDK 9 or higher

### Actual behavior

Hardcoded exceptions in JDK SslContext and lack of functions block use of OCSP Stapling in JDK implementation

### Steps to reproduce

Build program enabling OCSP and exception thrown stating that OCSP is not support by SSLProvider: JDK

### Netty version

Latest

### JVM version (e.g. `java -version`)

OpenJDK 11

### OS version (e.g. `uname -a`)

Darwin but looks like same would apply for Linux/Windows

**Comment by normanmaurer** [comment]
@nycnewman can you show the exception and maybe also a reproducer ?

**Comment by nycnewman** [comment]
This is the exception: 
java.lang.IllegalArgumentException: OCSP is not supported with this SslProvider: JDK
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:463)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:571)
	at com.daml.ledger.api.tls.TlsConfiguration.server(TlsConfiguration.scala:66)
	at com.daml.platform.apiserver.LedgerApiServer.$anonfun$acquire$2(LedgerApiServer.scala:37)
	at scala.Option.flatMap(Option.scala:271)
	at com.daml.platform.apiserver.LedgerApiServer.$anonfun$acquire$1(LedgerApiServer.scala:37)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

I see this explicitly throw in the source code when enableOcsp() is called on a JDK SslContext. There are a couple of places in the code where this appears to be hardcoded. I am trying to pull together a simpler test bed as this is currently in a complex product code base. OCSP Stapling doesn't appear to be supported in BoringSSL which we use at the moment and my tests on switching to JDK hit this issue. I can see Stapling work with a native Java app.

**Comment by normanmaurer** [comment]
hmm `enableOcsp` should not be needed for JDK. It should just work out of the box as all the setup / handling should be done internally by the JDK or I am missing anything ?

**Comment by nycnewman** [comment]
I would agree but setting all the security and environment variables that work for a native Java client do not appear to work here. i.e.

export JDK_JAVA_OPTIONS="-javaagent:./jSSLKeyLog.jar=server.log -Djava.security.properties=./java.security -Dcom.sun.net.ssl.checkRevocation=true -Djdk.tls.client.enableStatusRequestExtension=true -Djdk.tls.server.enableStatusRequestExtension=true -Djava.security.debug='certpath ocsp'"

**Comment by nycnewman** [comment]
Closing this out as I was able to resolve. Issue was that JDK ignores if certificate chain is not included in server side certificate. i.e. if chain length in cert file is 1 (only server certificate and not CA chain) then StatusResponseManager.java (line 277) will ignore and disable Stapling. Don't see this documented anywhere so leaving here for others.
