### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: unsupported JNI version 0xFFFFFFFF required by

### ISSUE THREAD

**Issue by azzahrah** [netty/netty#11158]
Development
IDE : Netbeans 11.3
Dev OS: Windows 10
Java : Openjdk-11.0.10.9-hotspot

Production
OS : LInux Ubuntu 20.04
Java: Openjdk 11.0.9.1 2020-11-04

this happen only when i use epoll, iouring working fine...
```
Caused by: java.lang.UnsatisfiedLinkError: unsupported JNI version 0xFFFFFFFF required by /tmp/libnetty_transport_native_epoll_x86_644138891611177706243.so
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:344)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:200)
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:290)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:70)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
        at com.pusatgps.main.Config.<init>(Config.java:207)
        at com.pusatgps.main.main.main(main.java:67)
        Suppressed: java.lang.UnsatisfiedLinkError: unsupported JNI version 0xFFFFFFFF required by /tmp/libnetty_transport_native_epoll_x86_644138891611177706243.so
                at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
                at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
                at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
                at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
                at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
                at java.base/java.lang.Runtime.load0(Runtime.java:768)
                at java.base/java.lang.System.load(System.java:1837)
                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:378)
                at java.base/java.security.AccessController.doPrivileged(Native Method)
                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:370)
                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:336)
                ... 6 more
        Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
                at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                at java.base/java.lang.System.loadLibrary(System.java:1873)
                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:344)
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
                ... 5 more
                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
                        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                        at java.base/java.lang.System.loadLibrary(System.java:1873)
                        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:378)
                        at java.base/java.security.AccessController.doPrivileged(Native Method)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:370)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:336)
                        ... 6 more
        Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:221)
                at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:293)
                ... 4 more
        Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll.so
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:170)
                ... 5 more
                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
                        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                        at java.base/java.lang.System.loadLibrary(System.java:1873)
                        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:344)
                        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
                        ... 5 more
                        Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path: [/usr/java/packages/lib, /usr/lib/x86_64-linux-gnu/jni, /lib/x86_64-linux-gnu, /usr/lib/x86_64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
                                at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                at java.base/java.lang.System.loadLibrary(System.java:1873)
                                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:378)
                                at java.base/java.security.AccessController.doPrivileged(Native Method)
                                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:370)
                                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:336)
                                ... 6 more


```

**Comment by chrisvest** [comment]
Do you have more than one version of Netty on your class path? Try running `mvn dependency:analyze-duplicate` (if you use Maven)

**Comment by azzahrah** [comment]
Scan Result
```
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------------< pusatgps:servergps >-------------------------
[INFO] Building ServerGPSV4R3 4
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.0.2:analyze-duplicate (default-cli) @ servergps ---
[INFO] No duplicate dependencies found in <dependencies/> or in <dependencyManagement/>
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.173 s
[INFO] Finished at: 2021-04-16T06:19:04+07:00
[INFO] ------------------------------------------------------------------------
```

this is what causes the error, after remove dependency google.com.firebase, error went away..
```
 <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>7.1.1</version>
        </dependency>
```

**Comment by chrisvest** [comment]
@azzahrah Weird the scan didn't find anything. Maybe that plug-in doesn't do what I thought it would do.

But it sounds like you got it fixed, so we can close this issue then?

**Comment by horschi** [comment]
Is there any way to solve this problem without removing firebase? Can I explicit set the right version or something else to fix it?

**Comment by chrisvest** [comment]
You can use the version of gRPC that don't shade Netty, then you can control the version via Maven or Gradle.
