### ISSUE TITLE
 java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.EpollChannelOption

### ISSUE THREAD

**Issue by 1ssqq1lxr** [netty/netty#11152]
### Expected behavior
Successfully started

### Actual behavior
 java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.EpollChannelOption

### Netty version
4.1.60.final

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode

### OS version (e.g. `uname -a`)
Linux localhost.localdomain 5.11.12-1.el7.elrepo.x86_64 #1 SMP Tue Apr 6 11:17:14 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 1ssqq1lxr** [comment]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.channel.epoll.EpollChannelOption
	at io.netty.channel.epoll.EpollServerSocketChannelConfig.getOption(EpollServerSocketChannelConfig.java:54)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:537)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at reactor.netty.transport.TransportConnector.lambda$bind$0(TransportConnector.java:81)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by normanmaurer** [comment]
This looks like a classpath problem
