### ISSUE TITLE
On android5.1.1 use netty 4.1, cannot receive msg from remote server

### ISSUE THREAD

**Issue by 871225223** [netty/netty#11247]
### Expected behavior
use udp control outside device

### Actual behavior
Send command to remote server is normal, but cannot receive msg from remote server

### Minimal yet complete reproducer code (or URL to code)

    public void start() {
        workerGroup = new NioEventLoopGroup();
        bootstrap = new Bootstrap();
        bootstrap.channel(NioDatagramChannel.class);
        bootstrap.group(workerGroup);
        bootstrap.option(ChannelOption.SO_BROADCAST, true);
        bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 3000);
        bootstrap.option(ChannelOption.RCVBUF_ALLOCATOR, new AdaptiveRecvByteBufAllocator(256, 256, 512));
        // bootstrap.option(ChannelOption.SO_RCVBUF, 256);
        // bootstrap.option(ChannelOption.SO_SNDBUF, 1024);
        connect();
    }

    public void connect() {
        final UdpClient self = this;
        bootstrap.handler(new ChannelInitializer<NioDatagramChannel>() {

            @Override
            protected void initChannel(NioDatagramChannel ch) throws Exception {
                ChannelPipeline cp = ch.pipeline();
                cp.addLast("logger", new LoggingHandler(LogLevel.DEBUG));
                cp.addLast("decoder", new ClientDecoder(self));
                cp.addLast("encoder", new ClientEncoder(self));
                // if (hostPort == PORT_9901) {
                // cp.addLast("timeout_inactive", new ReadTimeoutHandler(heartbeatTimeout));
                // }
                cp.addLast("handler", new ClientHandler(self));
            }

        });
        channelFuture = bootstrap.connect(inetSocketAddress, localAddress);
        channelFuture.addListener(new ChannelFutureHandler(this));
    }

### Netty version
netty-all-4.1.59.Finall

### JVM version (e.g. `java -version`)
jdk7

### OS version (e.g. `uname -a`)
android5.1.1

**Comment by 871225223** [comment]
Supplement:
This client program all function work normally that run on android7.1 or pc

**Comment by 871225223** [comment]
Supplement:
I/System.out: 07:25:31.287 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
I/System.out: 07:25:31.288 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Platform: Android
    07:25:31.289 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 6
I/System.out: 07:25:31.289 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Platform: Android
I/System.out: 07:25:31.291 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
I/System.out: 07:25:31.295 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: unavailable
    java.lang.NoSuchMethodException: copyMemory [class java.lang.Object, long, class java.lang.Object, long, long]
        at java.lang.Class.getMethod(Class.java:664)
        at java.lang.Class.getDeclaredMethod(Class.java:626)
I/System.out:     at io.netty.util.internal.PlatformDependent0$2.run(PlatformDependent0.java:132)
        at java.security.AccessController.doPrivileged(AccessController.java:45)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:128)
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
        at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:252)
        at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:165)
        at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:135)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
        at com.iwhalecloud.zsmartcity.lcg.prot.udp.client.UdpClient.start(UdpClient.java:156)
        at com.iwhalecloud.zsmartcity.lcg.prot.dev.Lcg.initMode2(Lcg.java:152)
        at com.iwhalecloud.zsmartcity.lcg.prot.dev.Lcg.init(Lcg.java:104)
        at com.iwhalecloud.zsmartcity.toll.driver.LcgIniter.init(LcgIniter.java:20)
        at com.iwhalecloud.zsmartcity.toll.UdpClientService.onCreate(UdpClientService.java:36)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:2761)
        at android.app.ActivityThread.access$1800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1386)
        at android.os.Handler.dispatchMessage(Handler.java:102)
I/System.out:     at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:925)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:720)
    07:25:31.299 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable

**Comment by normanmaurer** [comment]
Please update to latest version and check
