### ISSUE TITLE
Windows test-failures

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#11285]
```
021-05-19T18:16:47.0732101Z 18:16:47.068 [main] INFO  i.n.t.t.s.DatagramMulticastIPv6Test - Running: testMulticast 3 of 4 (Bootstrap(BootstrapConfig(group: OioEventLoopGroup, channelFactory: ReflectiveChannelFactory(OioDatagramChannel.class), options: {SO_TIMEOUT=10, ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@3a80515c)) + Bootstrap(BootstrapConfig(group: NioEventLoopGroup, channelFactory: NioDatagramChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@3a80515c))) with UnpooledByteBufAllocator
2021-05-19T18:16:47.1436303Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.286 s <<< FAILURE! - in io.netty.testsuite.transport.socket.DatagramMulticastIPv6Test
2021-05-19T18:16:47.1439470Z [ERROR] testMulticast  Time elapsed: 2.286 s  <<< ERROR!
2021-05-19T18:16:47.1495875Z io.netty.channel.ChannelException: java.net.SocketException: An operation was attempted on something that is not a socket (Error getting socket option)
2021-05-19T18:16:47.1498782Z 	at io.netty.channel.socket.DefaultDatagramChannelConfig.getNetworkInterface(DefaultDatagramChannelConfig.java:239)
2021-05-19T18:16:47.1503080Z 	at io.netty.testsuite.transport.socket.DatagramMulticastTest.testMulticast(DatagramMulticastTest.java:75)
2021-05-19T18:16:47.1506418Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-05-19T18:16:47.1508839Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-05-19T18:16:47.1512279Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-05-19T18:16:47.1514308Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-05-19T18:16:47.1516304Z 	at io.netty.testsuite.transport.AbstractComboTestsuiteTest.run(AbstractComboTestsuiteTest.java:67)
2021-05-19T18:16:47.1519440Z 	at io.netty.testsuite.transport.socket.DatagramMulticastTest.testMulticast(DatagramMulticastTest.java:49)
2021-05-19T18:16:47.1522705Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-05-19T18:16:47.1525501Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-05-19T18:16:47.1528093Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-05-19T18:16:47.1530096Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-05-19T18:16:47.1531528Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2021-05-19T18:16:47.1533510Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2021-05-19T18:16:47.1535761Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2021-05-19T18:16:47.1538049Z 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2021-05-19T18:16:47.1541643Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2021-05-19T18:16:47.1543209Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-05-19T18:16:47.1545777Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2021-05-19T18:16:47.1547481Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2021-05-19T18:16:47.1549308Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2021-05-19T18:16:47.1554425Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2021-05-19T18:16:47.1556087Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2021-05-19T18:16:47.1557291Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2021-05-19T18:16:47.1558687Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2021-05-19T18:16:47.1560787Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2021-05-19T18:16:47.1562243Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2021-05-19T18:16:47.1563436Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-05-19T18:16:47.1564636Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2021-05-19T18:16:47.1565756Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
2021-05-19T18:16:47.1566774Z 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
2021-05-19T18:16:47.1568373Z 	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:43)
2021-05-19T18:16:47.1570255Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2021-05-19T18:16:47.1571668Z 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
2021-05-19T18:16:47.1575246Z 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
2021-05-19T18:16:47.1578460Z 	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
2021-05-19T18:16:47.1581430Z 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
2021-05-19T18:16:47.1583542Z 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2021-05-19T18:16:47.1585244Z 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2021-05-19T18:16:47.1586703Z 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2021-05-19T18:16:47.1588247Z 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2021-05-19T18:16:47.1589953Z 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
2021-05-19T18:16:47.1592021Z 	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:82)
2021-05-19T18:16:47.1594195Z 	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:73)
2021-05-19T18:16:47.1596541Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
2021-05-19T18:16:47.1598626Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
2021-05-19T18:16:47.1614333Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
2021-05-19T18:16:47.1618063Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
2021-05-19T18:16:47.1620719Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
2021-05-19T18:16:47.1623660Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
2021-05-19T18:16:47.1629063Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
2021-05-19T18:16:47.1632776Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2021-05-19T18:16:47.1637110Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2021-05-19T18:16:47.1640759Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2021-05-19T18:16:47.1642687Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2021-05-19T18:16:47.1646742Z Caused by: java.net.SocketException: An operation was attempted on something that is not a socket (Error getting socket option)
2021-05-19T18:16:47.1648463Z 	at java.base/java.net.TwoStacksPlainDatagramSocketImpl.socketGetOption(Native Method)
2021-05-19T18:16:47.1650788Z 	at java.base/java.net.AbstractPlainDatagramSocketImpl.getOption(AbstractPlainDatagramSocketImpl.java:386)
2021-05-19T18:16:47.1653222Z 	at java.base/java.net.TwoStacksPlainDatagramSocketImpl.getOption(TwoStacksPlainDatagramSocketImpl.java:146)
2021-05-19T18:16:47.1655266Z 	at java.base/java.net.MulticastSocket.getNetworkInterface(MulticastSocket.java:577)
2021-05-19T18:16:47.1658738Z 	at io.netty.channel.socket.DefaultDatagramChannelConfig.getNetworkInterface(DefaultDatagramChannelConfig.java:237)
2021-05-19T18:16:47.1661838Z 	... 54 more
2021-05-19T18:16:47.1662284Z 
```

**Comment by normanmaurer** [comment]
Another one:

```
2021-05-19T17:58:35.8107086Z [INFO] Running io.netty.testsuite.transport.socket.DatagramConnectNotExistsTest
2021-05-19T17:58:35.8120099Z 17:58:35.809 [Time-limited test] INFO  i.n.t.t.s.DatagramConnectNotExistsTest - Running: testConnectNotExists 1 of 2 with UnpooledByteBufAllocator
2021-05-19T17:58:45.8511140Z [ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.037 s <<< FAILURE! - in io.netty.testsuite.transport.socket.DatagramConnectNotExistsTest
2021-05-19T17:58:45.8667909Z [ERROR] testConnectNotExists  Time elapsed: 10.005 s  <<< ERROR!
2021-05-19T17:58:45.8669566Z org.junit.runners.model.TestTimedOutException: test timed out after 10000 milliseconds
2021-05-19T17:58:45.8670979Z 	at java.base@11.0.11/java.lang.Object.wait(Native Method)
2021-05-19T17:58:45.8671877Z 	at java.base@11.0.11/java.lang.Object.wait(Object.java:328)
2021-05-19T17:58:45.8673569Z 	at app//io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:275)
2021-05-19T17:58:45.8676009Z 	at app//io.netty.util.concurrent.DefaultPromise.syncUninterruptibly(DefaultPromise.java:411)
2021-05-19T17:58:45.8680688Z 	at app//io.netty.testsuite.transport.socket.DatagramConnectNotExistsTest.testConnectNotExists(DatagramConnectNotExistsTest.java:63)
2021-05-19T17:58:45.8684359Z 	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-05-19T17:58:45.8686561Z 	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-05-19T17:58:45.8689073Z 	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-05-19T17:58:45.8691099Z 	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
2021-05-19T17:58:45.8692808Z 	at app//io.netty.testsuite.transport.AbstractTestsuiteTest.run(AbstractTestsuiteTest.java:62)
2021-05-19T17:58:45.8696303Z 	at app//io.netty.testsuite.transport.socket.DatagramConnectNotExistsTest.testConnectNotExists(DatagramConnectNotExistsTest.java:45)
2021-05-19T17:58:45.8699705Z 	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-05-19T17:58:45.8702888Z 	at java.base@11.0.11/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-05-19T17:58:45.8706068Z 	at java.base@11.0.11/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-05-19T17:58:45.8709226Z 	at java.base@11.0.11/java.lang.reflect.Method.invoke(Method.java:566)
2021-05-19T17:58:45.8711034Z 	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2021-05-19T17:58:45.8713006Z 	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2021-05-19T17:58:45.8715246Z 	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2021-05-19T17:58:45.8717494Z 	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
2021-05-19T17:58:45.8719927Z 	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
2021-05-19T17:58:45.8722449Z 	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
2021-05-19T17:58:45.8724334Z 	at java.base@11.0.11/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2021-05-19T17:58:45.8725497Z 	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
```

**Comment by normanmaurer** [comment]
We dont see this problems anymore... lets close this
