### ISSUE TITLE
StringIndexOutOfBoundsException caused by empty content value

### ISSUE THREAD

**Issue by togetsukyo** [netty/netty#11408]
### Actual behavior

A recent [commit](https://github.com/netty/netty/commit/89c241e3b1795ff257af4ad6eadc616cb2fb3dc4) causing [this line](https://github.com/netty/netty/blob/netty-4.1.63.Final/codec-http/src/main/java/io/netty/handler/codec/http/HttpUtil.java#L600) to throw exception if we've got empty content-length header:

```
Content-Length: \r\n\r\n
```

Stack trace:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
    at java.lang.StringLatin1.charAt(StringLatin1.java:47) 
    at java.lang.String.charAt(String.java:693) 
    at io.netty.handler.codec.http.HttpUtil.normalizeAndGetContentLength(HttpUtil.java:600) 
    at io.netty.handler.codec.http.HttpObjectDecoder.readHeaders(HttpObjectDecoder.java:642) 
    at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:257)
    at io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:123)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) 
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) 
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) 
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) 
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) 
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) 
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) 
    at java.lang.Thread.run(Thread.java:829)
```

### Expected behavior

It should gracefully handle the StringIndexOutOfBoundsException and throw exception saying that Content-Length header is invalid.

### Steps to reproduce

This can be easily reproduced by the following test code:

```
@Test
public void test() {
    assertThatThrownBy(() -> {
        ch.writeInbound(Unpooled.copiedBuffer("GET / HTTP/1.0\r\n", CharsetUtil.UTF_8));
        ch.writeInbound(Unpooled.copiedBuffer("Content-Length: \r\n\r\n", CharsetUtil.UTF_8));
    }).hasCauseInstanceOf(StringIndexOutOfBoundsException.class)
            .hasMessageContaining("String index out of range: 0");
}
```

### Netty version

4.1.63.Final

**Comment by NiteshKant** [comment]
Thanks for the report @togetsukyo , here is the PR for the fix: https://github.com/netty/netty/pull/11409
