### ISSUE TITLE
Netty cannot handle HTTP/2 (h2) Prior Knowledge correctly

### ISSUE THREAD

**Issue by hyperxpro** [netty/netty#11403]
### Expected behavior
Netty should be capable of handling HTTP/2 (h2) Prior Knowledge which happens even before ALPN.

### Actual behavior
HTTP/2 (h2) Prior Knowledge Preface message is being discarded because it was received even before the ALPN pipeline was configured.

### Steps to reproduce
Use Java 11 HttpClient with HTTP version set to 2.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/shieldblaze/ExpressGateway/blob/main/protocol-http/src/test/java/com/shieldblaze/expressgateway/protocol/http/adapter/mix/Http2TLSBackendAndNonTLSClientTest.java

### Netty version
4.1.65.Final

### JVM version (e.g. `java -version`)
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment Corretto-11.0.11.9.1 (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.11.9.1 (build 11.0.11+9-LTS, mixed mode)

### OS version (e.g. `uname -a`)
Windows 10 Pro x64

**Comment by hyperxpro** [comment]
Some log:
```
[INFO] Running com.shieldblaze.expressgateway.protocol.http.adapter.mix.Http2TLSBackendAndTLSClientTest
21 Jun 2021 07:11:27.459 [HttpClient-6-Worker-1] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=localhost
21 Jun 2021 07:11:27.475 [epollEventLoopGroup-22-1] DEBUG i.n.h.s.SslHandler - [id: 0xb24b34b6, L:/127.0.0.1:9110 - R:/127.0.0.1:47032] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
21 Jun 2021 07:11:27.519 [epollEventLoopGroup-22-2] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=localhost
21 Jun 2021 07:11:27.520 [epollEventLoopGroup-22-2] DEBUG i.n.h.s.SslHandler - [id: 0x472c8cf7, L:/127.0.0.1:35618 - R:localhost/127.0.0.1:33373] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
21 Jun 2021 07:11:27.525 [nioEventLoopGroup-20-2] DEBUG i.n.h.s.SslHandler - [id: 0x22ded8cb, L:/127.0.0.1:33373 - R:/127.0.0.1:35618] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
21 Jun 2021 07:11:29.565 [nioEventLoopGroup-20-2] DEBUG i.n.b.PoolThreadCache - Freed 18 thread-local buffer(s) from thread: nioEventLoopGroup-20-2
21 Jun 2021 07:11:30.240 [HttpClient-7-Worker-0] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=localhost
21 Jun 2021 07:11:30.257 [epollEventLoopGroup-25-1] DEBUG i.n.c.DefaultChannelPipeline - Discarded inbound message PooledUnsafeDirectByteBuf(ridx: 0, widx: 121, cap: 249) that reached at the tail of the pipeline. Please check your pipeline configuration.
21 Jun 2021 07:11:30.257 [epollEventLoopGroup-25-1] DEBUG i.n.c.DefaultChannelPipeline - Discarded message pipeline : [ConnectionTracker#0, ConnectionTimeoutHandler#0, TLSHandler, ALPNHandler#0, DefaultChannelPipeline$TailContext#0]. Channel : [id: 0xad9d65dd, L:/127.0.0.1:9110 - R:/127.0.0.1:47036].
21 Jun 2021 07:11:30.258 [epollEventLoopGroup-25-1] DEBUG i.n.h.s.SslHandler - [id: 0xad9d65dd, L:/127.0.0.1:9110 - R:/127.0.0.1:47036] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_256_GCM_SHA384
21 Jun 2021 07:11:30.263 [epollEventLoopGroup-25-1] ERROR c.s.e.p.h.a.h.HTTP2InboundAdapter - Caught error at HTTP2InboundAdapter
io.netty.handler.codec.http2.Http2Exception: HTTP/2 client preface string missing or corrupt. Hex dump for received bytes: 000000040100000000
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.readClientPrefaceString(Http2ConnectionHandler.java:306) ~[netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:239) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1368) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1245) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1282) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at com.shieldblaze.expressgateway.core.ConnectionTimeoutHandler.channelRead(ConnectionTimeoutHandler.java:87) [classes/:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.65.Final.jar:4.1.65.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
21 Jun 2021 07:11:30.276 [epollEventLoopGroup-25-1] DEBUG i.n.h.c.h.Http2ConnectionHandler - [id: 0xad9d65dd, L:/127.0.0.1:9110 - R:/127.0.0.1:47036] Sent GOAWAY: lastStreamId '2147483647', errorCode '1', debugData ''. Forcing shutdown of the connection.
Error:  Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.567 s <<< FAILURE! - in com.shieldblaze.expressgateway.protocol.http.adapter.mix.Http2TLSBackendAndTLSClientTest
Error:  http2Test  Time elapsed: 2.751 s  <<< ERROR!
java.io.IOException: /127.0.0.1:47036: GOAWAY received
	at com.shieldblaze.expressgateway.protocol.http.adapter.mix.Http2TLSBackendAndTLSClientTest.http2Test(Http2TLSBackendAndTLSClientTest.java:79)
Caused by: java.io.IOException: /127.0.0.1:47036: GOAWAY received
```

**Comment by hyperxpro** [comment]
Same results with `OkHttp` using HTTP/2 Prior Knowledge.

**Comment by hyperxpro** [comment]
@normanmaurer I have a solution in mind, should fire a draft PR?

**Comment by normanmaurer** [comment]
@hyperxpro yes please...
