### ISSUE TITLE
Potentially fatal bug in InternalThreadLocalMap.java

### ISSUE THREAD

**Issue by Mairuis** [netty/netty#11447]
### Expected behavior

return the power of two

### Actual behavior

return a negative number by overflow

### Steps to reproduce

when ThreadLocal count greater than 2^30

this is InternalThreadLocalMap.expandIndexedVariableTableAndSet implement
```java
private void expandIndexedVariableTableAndSet(int index, Object value) {
    Object[] oldArray = indexedVariables;
    final int oldCapacity = oldArray.length;
    int newCapacity = index;
    newCapacity |= newCapacity >>>  1;
    newCapacity |= newCapacity >>>  2;
    newCapacity |= newCapacity >>>  4;
    newCapacity |= newCapacity >>>  8;
    newCapacity |= newCapacity >>> 16;
    newCapacity ++;
    Object[] newArray = Arrays.copyOf(oldArray, newCapacity);
    Arrays.fill(newArray, oldCapacity, newArray.length, UNSET);
    newArray[index] = value;
    indexedVariables = newArray;
}
```

should implement like HashMap, let the max ThreadLocal instance count to be 2^30

### Minimal yet complete reproducer code (or URL to code)

```java
public static void main(String[] args) throws InterruptedException {
    for (int i = 0; i <= (1 << 30); i++) {
        InternalThreadLocalMap.nextVariableIndex();
    }
    final FastThreadLocalThread thread = new FastThreadLocalThread(() -> {
        try {
            final FastThreadLocal<Object> objectFastThreadLocal = new FastThreadLocal<>();
            objectFastThreadLocal.set("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    });
    thread.start();
    thread.join();
}
```

exception:
```
java.lang.NegativeArraySizeException: -2147483648
	at java.base/java.util.Arrays.copyOf(Arrays.java:3720)
	at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
	at io.netty.util.internal.InternalThreadLocalMap.expandIndexedVariableTableAndSet(InternalThreadLocalMap.java:342)
	at io.netty.util.internal.InternalThreadLocalMap.setIndexedVariable(InternalThreadLocalMap.java:326)
	at io.netty.util.concurrent.FastThreadLocal.setKnownNotUnset(FastThreadLocal.java:214)
	at io.netty.util.concurrent.FastThreadLocal.set(FastThreadLocal.java:193)
	at com.mairuis.sharp.request.worker.WorkerThreadLocalArray.lambda$main$0(WorkerThreadLocalArray.java:48)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
### Netty version
4.1.65.Final
### JVM version (e.g. `java -version`)

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

### OS version (e.g. `uname -a`)
Windows 10 19041.985

**Comment by chrisvest** [comment]
Did you see this bug in the wild? I'm curious about the use case for that many thread locals.

There might be a check missing to give a nicer error message, but I don't think this issue is "fatal".

**Comment by chrisvest** [comment]
Also, we love contributions if you want to have a go at fixing this.

**Comment by Mairuis** [comment]
thank you for your reply. I will do that if I have time.
