### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Operation timed out

### ISSUE THREAD

**Issue by aakejiang** [netty/netty#11465]
### Expected behavior
I'm facing an exception from Netty. My app is running and it happens randomly.
### Actual behavior
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Operation timed out
at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:177)
at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:346)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:782)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:432)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)

**Comment by hyperxpro** [comment]
Please specify Netty, JVM, and OS versions.

**Comment by aakejiang** [comment]
Netty: 4.1.36.Final
Java 8
OS: Linux 3.10.0-1062.9.1.el7.x86_64
Running on Docker

**Comment by hyperxpro** [comment]
Please upgrade to the latest Netty version and see if the issue still persists.

**Comment by aakejiang** [comment]
This is how i handle the exception:

```
    @Override
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
        String srcDest = ctx.channel().toString();
        ctx.close();
        logger.warn("server channel error {}", srcDest, cause);
        super.exceptionCaught(ctx, cause);
    }
```

and the output log:
```
2021-07-09 13:24:20.262 [epollEventLoopGroup-2-2] WARN  xx.xxx.ServerChannelHandler.exceptionCaught(ServerChannelHandler.java:79) - server channel error [id: 0x938121c6, L:/10.5.8.208:3000 - R:/10.5.2.31:52956]
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Operation timed out
at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
at io.netty.channel.unix.Errors.ioResult(Errors.java:146)
at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:177)
at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:346)
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:782)
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:432)
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
```

The remoteAddr R:/10.5.2.31 is now not existing. It is destroyed one hour ago.
