### ISSUE TITLE
Flaky test on windows: Http2MultiplexTransportTest

### ISSUE THREAD

**Issue by NiteshKant** [netty/netty#11542]
Test failure observed on CI[1] for PR: #11539 

```java
2021-08-02T17:47:46.6668896Z [ERROR] testFireChannelReadAfterHandshakeSuccess_JDK  Time elapsed: 5.009 s  <<< ERROR!
2021-08-02T17:47:46.6670678Z java.util.concurrent.TimeoutException: testFireChannelReadAfterHandshakeSuccess_JDK() timed out after 5000 milliseconds
2021-08-02T17:47:46.6673301Z 	at org.junit.jupiter.engine.extension.TimeoutInvocation.createTimeoutException(TimeoutInvocation.java:70)
2021-08-02T17:47:46.6676031Z 	at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:59)
2021-08-02T17:47:46.6678501Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2021-08-02T17:47:46.6681225Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2021-08-02T17:47:46.6684183Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2021-08-02T17:47:46.6686984Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2021-08-02T17:47:46.6689409Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2021-08-02T17:47:46.6692079Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2021-08-02T17:47:46.6695101Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2021-08-02T17:47:46.6698369Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2021-08-02T17:47:46.6701506Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2021-08-02T17:47:46.6704084Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2021-08-02T17:47:46.6706367Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2021-08-02T17:47:46.6708984Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
2021-08-02T17:47:46.6711980Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-02T17:47:46.6715273Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
2021-08-02T17:47:46.6718494Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
2021-08-02T17:47:46.6721407Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
2021-08-02T17:47:46.6724209Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2021-08-02T17:47:46.6727101Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-02T17:47:46.6729944Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2021-08-02T17:47:46.6732228Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2021-08-02T17:47:46.6734518Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2021-08-02T17:47:46.6737402Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-02T17:47:46.6740449Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2021-08-02T17:47:46.6743300Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2021-08-02T17:47:46.6744989Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-08-02T17:47:46.6748294Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-08-02T17:47:46.6752289Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2021-08-02T17:47:46.6859413Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-02T17:47:46.6862313Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2021-08-02T17:47:46.6865314Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2021-08-02T17:47:46.6867694Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2021-08-02T17:47:46.6870490Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-02T17:47:46.6877715Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2021-08-02T17:47:46.6880518Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2021-08-02T17:47:46.6882214Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-08-02T17:47:46.6886027Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-08-02T17:47:46.6890109Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2021-08-02T17:47:46.6893331Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-02T17:47:46.6896203Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2021-08-02T17:47:46.6898446Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2021-08-02T17:47:46.7003174Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2021-08-02T17:47:46.7006669Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-08-02T17:47:46.7009643Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2021-08-02T17:47:46.7012476Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2021-08-02T17:47:46.7016302Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2021-08-02T17:47:46.7040497Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2021-08-02T17:47:46.7044080Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2021-08-02T17:47:46.7046634Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
2021-08-02T17:47:46.7048547Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
2021-08-02T17:47:46.7050840Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
2021-08-02T17:47:46.7053122Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
2021-08-02T17:47:46.7055032Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
2021-08-02T17:47:46.7057713Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
2021-08-02T17:47:46.7060575Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
2021-08-02T17:47:46.7063401Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2021-08-02T17:47:46.7066056Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2021-08-02T17:47:46.7068045Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2021-08-02T17:47:46.7069698Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2021-08-02T17:47:46.7070904Z 	Suppressed: java.lang.InterruptedException
2021-08-02T17:47:46.7073165Z 		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
2021-08-02T17:47:46.7077017Z 		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
2021-08-02T17:47:46.7079507Z 		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
2021-08-02T17:47:46.7082514Z 		at io.netty.handler.codec.http2.Http2MultiplexTransportTest.testFireChannelReadAfterHandshakeSuccess(Http2MultiplexTransportTest.java:579)
2021-08-02T17:47:46.7087187Z 		at io.netty.handler.codec.http2.Http2MultiplexTransportTest.testFireChannelReadAfterHandshakeSuccess_JDK(Http2MultiplexTransportTest.java:461)
2021-08-02T17:47:46.7090351Z 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-08-02T17:47:46.7092261Z 		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-08-02T17:47:46.7094529Z 		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-08-02T17:47:46.7096198Z 		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-08-02T17:47:46.7097711Z 		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
2021-08-02T17:47:46.7099789Z 		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2021-08-02T17:47:46.7102260Z 		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2021-08-02T17:47:46.7104761Z 		at org.junit.jupiter.engine.extension.TimeoutInvocation.proceed(TimeoutInvocation.java:46)
2021-08-02T17:47:46.7105990Z 		... 58 more
```

[1] https://pipelines.actions.githubusercontent.com/obCqqsCMwwGme5y2aRyYOiZvWeJK4O0EY5AYRUDMSELILdqEjV/_apis/pipelines/1/runs/6426/signedlogcontent/19?urlExpires=2021-08-03T17%3A12%3A26.1539722Z&urlSigningMethod=HMACV1&urlSignature=jwbIl3OCMtUkfYSWqfwP3qOgeYp%2BxyOuCtJJ9srs8SM%3D

**Comment by NiteshKant** [comment]
Also observed on #11517 (https://github.com/netty/netty/pull/11517#issuecomment-891881343)

**Comment by hyperxpro** [comment]
Happened on #11547 also.
[17.txt](https://github.com/netty/netty/files/6931998/17.txt)

**Comment by hyperxpro** [comment]
Should we disable this test for the time being? @NiteshKant

**Comment by NiteshKant** [comment]
I am not sure how to disable it only for windows.

**Comment by hyperxpro** [comment]
This is how Norman did: https://github.com/netty/netty/commit/8af59e4b401470c6435def0063654d0372626506

We should do the same.

**Comment by NiteshKant** [comment]
Sweet, you want to send a PR?

**Comment by hyperxpro** [comment]
Sure

**Comment by Scottmitch** [comment]
```
Suppressed: java.lang.InterruptedException
[58813](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58814)
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1040)
[58814](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58815)
		at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1345)
[58815](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58816)
		at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
[58816](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58817)
		at io.netty.handler.codec.http2.Http2MultiplexTransportTest.testFireChannelReadAfterHandshakeSuccess(Http2MultiplexTransportTest.java:582)
[58817](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58818)
		at io.netty.handler.codec.http2.Http2MultiplexTransportTest.testFireChannelReadAfterHandshakeSuccess_OPENSSL(Http2MultiplexTransportTest.java:472)
[58818](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58819)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[58819](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58820)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[58820](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58821)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[58821](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58822)
		at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[58822](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58823)
		at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
[58823](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58824)
		at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
[58824](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58825)
		at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
[58825](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58826)
		at org.junit.jupiter.engine.extension.SameThreadTimeoutInvocation.proceed(SameThreadTimeoutInvocation.java:45)
[58826](https://github.com/netty/netty/actions/runs/3305457148/jobs/5455609609#step:6:58827)
		... 61 more
```

**Comment by normanmaurer** [comment]
Didn't see this for a long time... let's close it
