### ISSUE TITLE
[QUESTION] finishConnect(..) failed: Protocol not available

### ISSUE THREAD

**Issue by andreypfau** [netty/netty#11586]
what does this mean and how to fix it?

```
io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Protocol not available: /37.123.151.61:8999
Caused by: java.net.ConnectException: finishConnect(..) failed: Protocol not available
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[vpnendpoint.jar:?]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:287) ~[vpnendpoint.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710) [vpnendpoint.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687) [vpnendpoint.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567) [vpnendpoint.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:470) [vpnendpoint.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) [vpnendpoint.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [vpnendpoint.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [vpnendpoint.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [vpnendpoint.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by hyperxpro** [comment]
Please use issue template and provide detailed information.

**Comment by andreypfau** [comment]
There are not template for questions. It's not bug report

**Comment by normanmaurer** [comment]
It means that the protocol you tried to use is not supported (like for example TCP or UDP).
