### ISSUE TITLE
`DatagramDnsQueryDecoder.newQuery()` raises `IndexOutOfBoundsException`

### ISSUE THREAD

**Issue by ikhoon** [netty/netty#11591]
### Actual behavior

I tried to upgrade Netty 4.1.66 to 4.1.67, but our CI tests produced the following error when resolving a DNS query.
```java
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(36) + length(2) exceeds writerIndex(36): PooledUnsafeDirectByteBuf(ridx: 36, widx: 36, cap: 2048)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(36) + length(2) exceeds writerIndex(36): PooledUnsafeDirectByteBuf(ridx: 36, widx: 36, cap: 2048)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
	at io.netty.buffer.AbstractByteBuf.readUnsignedShort(AbstractByteBuf.java:765)
	at io.netty.handler.codec.dns.DatagramDnsQueryDecoder.newQuery(DatagramDnsQueryDecoder.java:87)
	at io.netty.handler.codec.dns.DatagramDnsQueryDecoder.decode(DatagramDnsQueryDecoder.java:64)
	at io.netty.handler.codec.dns.DatagramDnsQueryDecoder.decode(DatagramDnsQueryDecoder.java:33)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 16 common frames omitted
```

When `DatagramDnsQueryDecoder.newQuery(packet, but)` was called, the `buf` had been already fully consumed by `DnsMessageUtil.decodeDnsQuery()`. 
https://github.com/netty/netty/blob/794c45fd590ffc51b16bb4b8af87556c0d2025fb/codec-dns/src/main/java/io/netty/handler/codec/dns/DatagramDnsQueryDecoder.java#L57-L64

I guess the problem is caused by the changes in https://github.com/netty/netty/pull/11415/files#diff-41d08a26f08dcb6f92085ad9bb565c833bbe0e0d425e0fe7147fcc51b56d164aR64

### Minimal yet complete reproducer code (or URL to code)

https://github.com/line/armeria/blob/b5a2e1c264c264a4f504dfc1a5990866dea7b86f/core/src/test/java/com/linecorp/armeria/client/DnsMetricsTest.java#L67

### Netty version

4.1.67.Final

### JVM version (e.g. `java -version`)

OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

### OS version (e.g. `uname -a`)

Darwin  20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
Doh! Yeah let me fix this

**Comment by normanmaurer** [comment]
@ikhoon PTAL https://github.com/netty/netty/pull/11592
