### ISSUE TITLE
GraalVM native-image canno tcompile netty-all 68

### ISSUE THREAD

**Issue by adiantek** [netty/netty#11737]
I'm trying to create native-image with netty, but it fails with the simple example. I used https://github.com/graalvm/graalvm-ce-builds/releases/tag/vm-21.2.0
Java 16 based (experimental)
Linux (amd64)

```console
$ native-image --version
GraalVM 21.2.0 Java 16 CE (Java Version 16.0.2+7-jvmci-21.2-b08)
$ cat Test.java
public class Test {
public static void main(String[] args) {
io.netty.channel.epoll.Epoll.ensureAvailability();
}
}
$ wget "https://repo1.maven.org/maven2/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar"
$ javac -cp netty-all-4.1.68.Final.jar Test.java
$ native-image -cp netty-all-4.1.68.Final.jar:. Test
$ native-image -cp netty-all-4.1.68.Final.jar:. Test
[test:589626]    classlist:     747.73 ms,  0.96 GB
[test:589626]        (cap):     461.03 ms,  0.96 GB
[test:589626]        setup:   1,653.45 ms,  0.96 GB
To see how the classes got initialized, use --trace-class-initialization=io.netty.util.AbstractReferenceCounted
[test:589626]     analysis:   2,827.45 ms,  1.68 GB
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.util.AbstractReferenceCounted the class was requested to be initialized at run time (from jar:file:///home/ubuntu/test/test/netty-all-4.1.68.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties with 'io.netty.util.AbstractReferenceCounted'). To see why io.netty.util.AbstractReferenceCounted got initialized use --trace-class-initialization=io.netty.util.AbstractReferenceCounted

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[test:589626]      [total]:   5,392.75 ms,  1.68 GB
# Printing build artifacts to: /home/ubuntu/test/test/test.build_artifacts.txt
Error: Image build request failed with exit status 1
$ native-image --trace-class-initialization=io.netty.util.AbstractReferenceCounted -cp netty-all-4.1.68.Final.jar:. Test
[test:589993]    classlist:     761.97 ms,  0.96 GB
[test:589993]        (cap):     485.80 ms,  0.96 GB
[test:589993]        setup:   1,719.92 ms,  0.96 GB
[test:589993]     analysis:   2,768.25 ms,  1.68 GB
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.util.AbstractReferenceCounted the class was requested to be initialized at run time (from jar:file:///home/ubuntu/test/test/netty-all-4.1.68.Final.jar!/META-INF/native-image/io.netty/common/native-image.properties with 'io.netty.util.AbstractReferenceCounted'). io.netty.channel.epoll.Epoll caused initialization of this class with the following trace: 
        at io.netty.util.AbstractReferenceCounted.<clinit>(AbstractReferenceCounted.java:26)
        at java.lang.Class.forName0(Unknown Source)
        at java.lang.Class.forName(Class.java:466)
        at io.netty.util.internal.ClassInitializerUtil.tryLoadClass(ClassInitializerUtil.java:41)
        at io.netty.util.internal.ClassInitializerUtil.tryLoadClasses(ClassInitializerUtil.java:34)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:72)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)


Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[test:589993]      [total]:   5,405.54 ms,  1.68 GB
# Printing build artifacts to: /home/ubuntu/test/test/test.build_artifacts.txt
Error: Image build request failed with exit status 1
$ uname -a
Linux ryz2 5.8.0-36-generic #40-Ubuntu SMP Tue Jan 5 21:54:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by chrisvest** [comment]
Epoll is not fully supported on native image, and since you use netty-all you get epoll included. So this is "expected" for now.

If you know how to debug this stuff, then I invite you help out on #11163.
