### ISSUE TITLE
netty-testsuite-autobahn  build failed

### ISSUE THREAD

**Issue by otfot** [netty/netty#11777]
### Expected behavior
build  netty success 
### Actual behavior
netty-testsuite-autobahn build failed
### Netty version
4.1.70.Final
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_302"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM (Temurin)(build 25.302-b08, mixed mode)
### OS version (e.g. `uname -a`)
Darwin Kernel Version 21.1.0

use `mvn clean  install -Dmaven.test.skip=true  -X` , and the log is 
```txt
[INFO] 
[INFO] --- autobahntestsuite-maven-plugin:0.1.5:fuzzingclient (default) @ netty-testsuite-autobahn ---
[DEBUG] Dependency collection stats {ConflictMarker.analyzeTime=31370, ConflictMarker.markTime=24301, ConflictMarker.nodeCount=34, ConflictIdSorter.graphTime=15534, ConflictIdSorter.topsortTime=23951, ConflictIdSorter.conflictIdCount=17, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=130071, ConflictResolver.conflictItemCount=34, DefaultDependencyCollector.collectTime=10261188, DefaultDependencyCollector.transformTime=250494}
[DEBUG] me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:jar:0.1.5
[DEBUG]    org.python:jython-standalone:jar:2.7.1:runtime
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.0:compile
[DEBUG]    org.apache.maven:maven-project:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-profile:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-model:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-artifact-manager:jar:2.0.6:compile
[DEBUG]          org.apache.maven:maven-repository-metadata:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-registry:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:2.0.6:compile
[DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[DEBUG]          classworlds:classworlds:jar:1.1-alpha-2:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:3.0.8:compile
[DEBUG]    com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[DEBUG]       junit:junit:jar:4.10:compile
[DEBUG]          org.hamcrest:hamcrest-core:jar:1.1:compile
[DEBUG] Created new class realm plugin>me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:0.1.5
[DEBUG] Importing foreign packages into class realm plugin>me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:0.1.5
[DEBUG]   Imported:  < project>io.netty:netty-parent:4.1.70.Final
[DEBUG] Populating class realm plugin>me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:0.1.5
[DEBUG]   Included: me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:jar:0.1.5
[DEBUG]   Included: org.python:jython-standalone:jar:2.7.1
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.8
[DEBUG]   Included: com.googlecode.json-simple:json-simple:jar:1.1.1
[DEBUG]   Included: junit:junit:jar:4.10
[DEBUG]   Included: org.hamcrest:hamcrest-core:jar:1.1
[DEBUG] Configuring mojo me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:0.1.5:fuzzingclient from plugin realm ClassRealm[plugin>me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:0.1.5, parent: sun.misc.Launcher$AppClassLoader@7852e922]
[DEBUG] Configuring mojo 'me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:0.1.5:fuzzingclient' with basic configurator -->
[DEBUG]   (f) cases = [*]
[DEBUG]   (f) excludeCases = []
[DEBUG]   (f) failOnNonStrict = false
[DEBUG]   (f) generateJUnitXml = true
[DEBUG]   (f) mainClass = io.netty.testsuite.autobahn.AutobahnServer
[DEBUG]   (f) port = -1
[DEBUG]   (f) skip = false
[DEBUG]   (f) project = MavenProject: io.netty:netty-testsuite-autobahn:4.1.70.Final-SNAPSHOT @ /Users/otfot/IdeaProjects/netty/testsuite-autobahn/pom.xml
[DEBUG] -- end configuration --
Exception in thread "Thread-327" java.lang.NoClassDefFoundError: io/netty/channel/EventLoopGroup
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at me.normanmaurer.maven.autobahntestsuite.FuzzingClientMojo$1.run(FuzzingClientMojo.java:169)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.EventLoopGroup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Netty/Dev-Tools 4.1.70.Final-SNAPSHOT .............. SUCCESS [  2.147 s]
[INFO] Netty/Common 4.1.70.Final-SNAPSHOT ................. SUCCESS [ 37.009 s]
[INFO] Netty/Buffer 4.1.70.Final-SNAPSHOT ................. SUCCESS [ 13.913 s]
[INFO] Netty/Resolver 4.1.70.Final-SNAPSHOT ............... SUCCESS [  5.989 s]
[INFO] Netty/Transport 4.1.70.Final-SNAPSHOT .............. SUCCESS [ 17.097 s]
[INFO] Netty/Codec 4.1.70.Final-SNAPSHOT .................. SUCCESS [ 16.752 s]
[INFO] Netty/Codec/DNS 4.1.70.Final-SNAPSHOT .............. SUCCESS [  5.738 s]
[INFO] Netty/Codec/HAProxy 4.1.70.Final-SNAPSHOT .......... SUCCESS [  4.264 s]
[INFO] Netty/Handler 4.1.70.Final-SNAPSHOT ................ SUCCESS [ 14.245 s]
[INFO] Netty/Codec/HTTP 4.1.70.Final-SNAPSHOT ............. SUCCESS [ 15.160 s]
[INFO] Netty/Codec/HTTP2 4.1.70.Final-SNAPSHOT ............ SUCCESS [ 14.689 s]
[INFO] Netty/Codec/Memcache 4.1.70.Final-SNAPSHOT ......... SUCCESS [  5.296 s]
[INFO] Netty/Codec/MQTT 4.1.70.Final-SNAPSHOT ............. SUCCESS [  4.753 s]
[INFO] Netty/Codec/Redis 4.1.70.Final-SNAPSHOT ............ SUCCESS [  3.742 s]
[INFO] Netty/Codec/SMTP 4.1.70.Final-SNAPSHOT ............. SUCCESS [  3.162 s]
[INFO] Netty/Codec/Socks 4.1.70.Final-SNAPSHOT ............ SUCCESS [  5.547 s]
[INFO] Netty/Codec/Stomp 4.1.70.Final-SNAPSHOT ............ SUCCESS [  3.593 s]
[INFO] Netty/Codec/XML 4.1.70.Final-SNAPSHOT .............. SUCCESS [  3.111 s]
[INFO] Netty/Handler/Proxy 4.1.70.Final-SNAPSHOT .......... SUCCESS [  3.647 s]
[INFO] Netty/Resolver/DNS 4.1.70.Final-SNAPSHOT ........... SUCCESS [  6.450 s]
[INFO] Netty/Transport/RXTX 4.1.70.Final-SNAPSHOT ......... SUCCESS [  3.447 s]
[INFO] Netty/Transport/SCTP 4.1.70.Final-SNAPSHOT ......... SUCCESS [  4.057 s]
[INFO] Netty/Transport/UDT 4.1.70.Final-SNAPSHOT .......... SUCCESS [  3.497 s]
[INFO] Netty/Transport/Native/Unix/Common 4.1.70.Final-SNAPSHOT SUCCESS [  7.645 s]
[INFO] Netty/Testsuite 4.1.70.Final-SNAPSHOT .............. SUCCESS [ 10.825 s]
[INFO] Netty/Transport/Native/Unix/Common/Tests 4.1.70.Final-SNAPSHOT SUCCESS [  3.193 s]
[INFO] Netty/Transport/Native/Epoll 4.1.70.Final-SNAPSHOT . SUCCESS [  5.076 s]
[INFO] Netty/Transport/Native/KQueue 4.1.70.Final-SNAPSHOT  SUCCESS [ 23.925 s]
[INFO] Netty/Resolver/DNS/MacOS 4.1.70.Final-SNAPSHOT ..... SUCCESS [ 28.930 s]
[INFO] Netty/All-in-One 4.1.70.Final-SNAPSHOT ............. SUCCESS [  3.711 s]
[INFO] Netty/Example 4.1.70.Final-SNAPSHOT ................ SUCCESS [ 11.952 s]
[INFO] Netty/Testsuite/Autobahn 4.1.70.Final-SNAPSHOT ..... FAILURE [ 12.967 s]
[INFO] Netty/Testsuite/Http2 4.1.70.Final-SNAPSHOT ........ SKIPPED
[INFO] Netty/Testsuite/OSGI 4.1.70.Final-SNAPSHOT ......... SKIPPED
[INFO] Netty/Testsuite/Shading 4.1.70.Final-SNAPSHOT ...... SKIPPED
[INFO] Netty/Testsuite/Native 4.1.70.Final-SNAPSHOT ....... SKIPPED
[INFO] Netty/Testsuite/NativeImage 4.1.70.Final-SNAPSHOT .. SKIPPED
[INFO] Netty/Testsuite/NativeImage/Client 4.1.70.Final-SNAPSHOT SKIPPED
[INFO] Netty/Testsuite/NativeImage/ClientRuntimeInit 4.1.70.Final-SNAPSHOT SKIPPED
[INFO] Netty/Transport/BlockHound/Tests 4.1.70.Final-SNAPSHOT SKIPPED
[INFO] Netty/Microbench 4.1.70.Final-SNAPSHOT ............. SKIPPED
[INFO] Netty/BOM 4.1.70.Final-SNAPSHOT .................... SKIPPED
[INFO] Netty 4.1.70.Final ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:07 min
[INFO] Finished at: 2021-10-18T19:47:21+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:0.1.5:fuzzingclient (default) on project netty-testsuite-autobahn: Unable to connect to server in 10000 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal me.normanmaurer.maven.autobahntestsuite:autobahntestsuite-maven-plugin:0.1.5:fuzzingclient (default) on project netty-testsuite-autobahn: Unable to connect to server in 10000
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Unable to connect to server in 10000
    at me.normanmaurer.maven.autobahntestsuite.FuzzingClientMojo.execute (FuzzingClientMojo.java:215)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :netty-testsuite-autobahn

```

**Comment by Otfot** [comment]
> It seems to work up to Maven versions `3.8.1.` Anything above that throws that Exception.

I switch my maven version to 3.8.1 and build success,  thanks a lot.
