### ISSUE TITLE
Pool Chunk Initialization error in PooledByteBufAllocator

### ISSUE THREAD

**Issue by rishika728** [netty/netty#11820]
### Issue
While trying to allocate a new Direct Buffer using PooledByteBufAllocator, Netty is failing to initialize the PoolChunk. An assertion error is thrown when executing the initBufWithSubpage function here https://github.com/netty/netty/blob/netty-4.1.68.Final/buffer/src/main/java/io/netty/buffer/PoolChunk.java#L569

Full stack trace 

```
java.lang.AssertionError: null | 
    at io.netty.buffer.PoolChunk.initBufWithSubpage(PoolChunk.java:569) | 
    at io.netty.buffer.PoolThreadCache$SubPageMemoryRegionCache.initBuf(PoolThreadCache.java:315) | 
    at io.netty.buffer.PoolThreadCache$MemoryRegionCache.allocate(PoolThreadCache.java:376) | 
    at io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:167) | 
    at io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:151) | 
    at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:148) | 
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:134) | 
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:126) | 
    at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395) | 
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187) | 
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178) | 
 at io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53) | 
    at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114) | 
    at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75) | 
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:780) | 
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) | 
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) | 
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) | 
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) | 
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) | 
    at java.lang.Thread.run(Thread.java:829) |
```

I suspect that this could be possible when a Worker Thread is evicted from the EventLoopGroup and the ThreadCache cleared. PooledAllocator could possibly be holding a stale Worker Thread reference (if the cleanup logic did not clear the stale references) and when executing the logic, it encountered this null object. 

1. Has this issue been seen before with PoolChunk in Allocator execution and if yes under what circumstances can we expect it to happen ? 
2. Is there something we should be doing in the Application code to prevent this in the first place ? 

### Netty version
4.1.68.Final

### JVM version (e.g. `java -version`)
Java 11

### OS version (e.g. `uname -a`)
x86_64 x86_64 x86_64 GNU/Linux

**Comment by chrisvest** [comment]
You write that you have this issue with Netty 4.1.51, but link to code under the 4.1.66 tag? Regardless, Netty should not throw NullPointerExceptions when allocating. I recommend upgrading to the latest version to see if the problem goes away. There have been a number of changes to that code since 4.1.51.

**Comment by rishika728** [comment]
My bad, we are using Netty version 4.1.68.Final. Code Link - https://github.com/netty/netty/blob/netty-4.1.68.Final/buffer/src/main/java/io/netty/buffer/PoolChunk.java#L569

**Comment by chrisvest** [comment]
How often do you run into this issue, and does it disappear if you set this system property `io.netty.recycler.delayedQueue.ratio` to `0`, e.g. with `-Dio.netty.recycler.delayedQueue.ratio=0` on the command line?

**Comment by rishika728** [comment]
The occurrence is rare and am unaware of a definitive way to reproduce this. I can try setting `io.netty.recycler.delayedQueue.ratio` to 0. Any side affects to this change ?

**Comment by normanmaurer** [comment]
@rishika728 a bit more GC...

**Comment by hyperxpro** [comment]
@normanmaurer @chrisvest 

Using 'assert' is easy and minimalistic but debugging it is hard. Should we take different way in Netty 5?

**Comment by normanmaurer** [comment]
@chrisvest do we want to close this now that the recycler was rewritten ?

**Comment by chrisvest** [comment]
Let's close it for now. We can always reopen (or create a new issue) if something like this shows up again.
