### ISSUE TITLE
Unable to 

### ISSUE THREAD

**Issue by jsa34** [netty/netty#11885]
### Expected behavior
Using Java 16/17 I can connect with a host by host name successfully, just as with Java 8

### Actual behavior
When running the same code with Java 8, I can successfully connect to a remote host by name, but with Java 16 and 17 I cannot.

Stacktrace:
java.lang.ExceptionInInitializerError
	at xxx
Caused by: java.net.UnknownHostException: failed to resolve 'abcdefg' after 10 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1046)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:999)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:417)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:628)
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:65)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:461)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:200)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:192)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

### Steps to reproduce
I am using Redisson, which is using Netty:

        Config config = new Config();
        config.useSingleServer()
                .setAddress(PropertyLoader.getProperty(REDIS_URL));
        CLIENT = Redisson.create(config);

### Netty version
4.1.68-FINAL (via Redisson)

### JVM version (e.g. `java -version`)
17.0.1

### OS version (e.g. `uname -a`)
Window 10 21H2

**Comment by normanmaurer** [comment]
@jsa34 Please show the full stack trace (seems like you trimmed it). Also can you check with "pure" netty ?

**Comment by jsa34** [comment]
Step failed
java.lang.ExceptionInInitializerError
	at com.test.automation.test-project.dao.redis.UserLoginFilter.getUnusedUserLogin(UserLoginFilter.java:31)
	at com.test.automation.test-project.caches.AdminUserCache.getUnusedAdminFrom(AdminUserCache.java:44)
	at com.test.automation.test-project.caches.AdminUserCache.getAnyUserWithJob(AdminUserCache.java:22)
	at com.test.automation.test-project.stepdefs.login.LoginPage.thePasswordIsChangedForAnyUserWithJob(LoginPage.java:78)
	at ✽.The password is changed for any user with job "Test Job"(file:///C:/Users/me/IdeaProjects/test-project-test-automation/src/test/resources/features/test-project_search/job_search.feature:4)
Caused by: java.net.UnknownHostException: failed to resolve 'hostname' after 10 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1046)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:999)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:417)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:628)
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:65)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:461)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:200)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:192)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1301)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by jsa34** [comment]
I tried with a "pure netty" connection (as far as I can tell) using the following code:

https://gist.github.com/jsa34/b5d0afad6ed542098134644276f9f0ce

This was successful, but I don't know how netty is being configured within Redisson for dns resolving / host connections

**Comment by jsa34** [comment]
A little bit of investigation:

Java 8 - both hostname and FQHN resolve
Java 9+ - only FQHN resolves

At least I have found a workaround.

Odd as pinging hostname resolves to expected host...

**Comment by flupec** [comment]
Faced same issue with Spring WebClient that's based on Netty. DNS suffixes cannot be resolved on Windows and Java 9+. I think this [hack](https://github.com/netty/netty/blob/9cd94547d0211c04b610878e5e267c8de2342b97/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java#L189:L202) is responsible for such behaviour.

Why is reflection used here? You can acquire instance of ResolverConfiguration via static method, no?

**Comment by dlehammer** [comment]
I've experienced the symptom similarly to @flupec in a Spring Boot context, albeit in a Linux environment (Fedora 36 & Java 17).
I.e. Netty unable to resolve the local machine alias ~ `$HOSTNAME`.

I found a **workaround**; explicitly adding the machine alias to `/etc/hosts` seemed to appease Netty (no other services has needed this, and `ping` etc. resolved the machine alias fine before I made any changes!)
```
127.0.0.1 my-machine-alias my-machine-alias.localdomain
```

I too am unable to understand why Netty tries to handle a responsibility owned by the OS, i.e. I somewhat understand the desire to cache resolved DNS-data, but caching it inside each service running on a OS is just asking for support tickets...

I'm not that familiar with the Windows DNS cache support, but on Linux most distributions provide a OS level cache for this specific purpose, ex. https://manpages.ubuntu.com/manpages/trusty/man8/dnscache.8.html 🤓
