### ISSUE TITLE
<tcnative.version> out of sync in pom.xml and bom/pom.xml

### ISSUE THREAD

**Issue by dferstay** [netty/netty#11910]
I was about to upgrade from 4.1.70.Final to 4.1.71.Final and noticed that the version of tcnative has become out of sync between pom.xml and bom/pom.xml

- pom.xml points to 2.0.46.Final: https://github.com/netty/netty/blob/netty-4.1.71.Final/pom.xml#L511
- bom/pom.xml points at 2.0.44.Final: https://github.com/netty/netty/blob/netty-4.1.71.Final/bom/pom.xml#L68

I'm not sure what the ramifications of this version mismatch are.  I use tcnative in my Netty application.  Is upgrading to 4.1.71.Final safe and if so, what version of tcnative should I refer to in my build?

### Netty version

netty-4.1.71.Final

**Comment by dferstay** [comment]
The ramifications appear rather serious; I see the following exception during testing with Netty 4.1.71.Final and my project pointing to any of the following versions of tcnative: 2.0.44.Final, 2.0.45.Final, 2.0.46.Final
```
java.lang.UnsatisfiedLinkError: failed to load the required native library
        at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:596)
        at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:837)
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:611)
        at com.splunk.s2s.client.core.netty.SSLContextFactory.createSSLContext(SSLContextFactory.java:92)
        at com.splunk.s2s.client.core.S2SClient.<init>(S2SClient.java:98)
        at com.splunk.s2s.client.core.S2SClientPool.<init>(S2SClientPool.java:42)
        at com.splunk.s2s.client.api.ClientFactory.lambda$createClient$3(ClientFactory.java:151)
        at com.splunk.s2s.client.core.DNSResolvingClient.<init>(DNSResolvingClient.java:62)
        at com.splunk.s2s.client.api.ClientFactory.createClient(ClientFactory.java:166)
        at com.splunk.s2s.client.api.ClientFactory.create(ClientFactory.java:88)
        at com.splunk.s2s.client.benchmark.ClientBenchmark.setup(ClientBenchmark.java:162)
        at com.splunk.s2s.client.benchmark.jmh_generated.ClientBenchmark_send_jmhTest._jmh_tryInit_f_clientbenchmark0_G(ClientBenchmark_send_jmhTest.java:463)
        at com.splunk.s2s.client.benchmark.jmh_generated.ClientBenchmark_send_jmhTest.send_Throughput(ClientBenchmark_send_jmhTest.java:71)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:453)
        at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
        at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:107)
        at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
        ... 24 more
        Suppressed: java.lang.IllegalStateException: Multiple resources found for 'META-INF/native/libnetty_tcnative_linux_x86_64.so': ...
```

**Comment by dferstay** [comment]
Duplicate of https://github.com/netty/netty/issues/11908
