### ISSUE TITLE
WebSocketServerProtocolHandler throwing Exception without preceding HttpObjectAggregator

### ISSUE THREAD

**Issue by faceless2** [netty/netty#11952]
I'm building a service which will work with both HTTP and Websockets, and potentially take large uploads from both. Because of this I'm not using Aggregators for either, but streaming the received chunks to the processing threads as they arrive so they can be processed.

However the WebSocketServerProtocolHandler doesn't work without a preceding HttpObjectAggregator. If I leave it out I get:

```
java.lang.ClassCastException: class io.netty.handler.codec.http.DefaultHttpRequest cannot be cast to class io.netty.handler.codec.http.FullHttpRequest (io.netty.handler.codec.http.DefaultHttpRequest and io.netty.handler.codec.http.FullHttpRequest are in unnamed module of loader 'app')
	at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler.channelRead(WebSocketServerProtocolHandshakeHandler.java:63)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
```

I can see in https://github.com/netty/netty/commit/afa9e71ed37ad1e46a837f3212d6ff1712f12a92 that this case has been considered already and it looks like it should be working.

Here's my testcase - uncomment the `new HttpObjectAggregator(65536)` to see the difference.

```java
import io.netty.channel.*;
import io.netty.handler.logging.*;
import io.netty.handler.codec.http.*;
import io.netty.handler.codec.http.websocketx.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.bootstrap.ServerBootstrap;

public class NettyTest {
    public static void main(String[] args) throws Exception {
        EventLoopGroup bossGroup = new NioEventLoopGroup(1);
        EventLoopGroup workerGroup = new NioEventLoopGroup();
        ServerBootstrap bootstrap = new ServerBootstrap();
        bootstrap.group(bossGroup, workerGroup)
          .channel(NioServerSocketChannel.class)
          .handler(new LoggingHandler(LogLevel.INFO))
          .childHandler(new ChannelInitializer<SocketChannel>() {
            @Override public void initChannel(SocketChannel ch) {
                ChannelPipeline p = ch.pipeline();
                p.addLast(new HttpServerCodec());
//                p.addLast(new HttpObjectAggregator(65536));
                p.addLast(new WebSocketServerProtocolHandler("/ws", null, true));
                p.addLast(new SimpleChannelInboundHandler<WebSocketFrame>() {
                    @Override protected void channelRead0(ChannelHandlerContext ctx, WebSocketFrame msg) throws Exception {
                        System.out.println("Received " + msg);
                    }
                });
            }
        });
        bootstrap.bind(8080).sync().channel().closeFuture().sync();

    }
}
```

This is with Netty 4.1.63

I'm only a couple of days into Netty so this could well be user error.

Any suggestions? Other than using an Aggregator, that is.

**Comment by faceless2** [comment]
PS. One option I'd considered was to insert a preceding `HttpObjectAggregator` so that `isStartMessage()` only matches if the `Connection: upgrade` header was present. However looking at `MessageAggregator` I can see it's supposed to aggregate if it matches `isContentMessage` too, which would catch every `HttpContent`. So I've abandoned that approach, but I'm happy to revisit if you think this is the correct approach.

**Comment by faceless2** [comment]
Thank you Norman! I'll have a play with this next week.

**Comment by faceless2** [comment]
Confirmed fixed, thanks again
