### ISSUE TITLE
Assertion error when resizing buffers that had an initial capacity of zero

### ISSUE THREAD

**Issue by ebradshaw** [netty/netty#11955]
### Expected behavior

ByteBuf.capacity() should be able to successfully resize up to maxCapacity regardless of it's initial state.  

### Actual behavior

If two zero length buffers are created and resized to 17, an AssertionError is thrown:

```
java.lang.AssertionError
	at __randomizedtesting.SeedInfo.seed([7DAACA0E7D79473:4594B38D5FFB07BE]:0)
	at io.netty.buffer.PoolChunk.initBufWithSubpage(PoolChunk.java:573)
	at io.netty.buffer.PoolThreadCache$SubPageMemoryRegionCache.initBuf(PoolThreadCache.java:315)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.allocate(PoolThreadCache.java:376)
	at io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:167)
	at io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:151)
	at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:148)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
	at io.netty.buffer.PoolArena.reallocate(PoolArena.java:286)
	at io.netty.buffer.PooledByteBuf.capacity(PooledByteBuf.java:118)
```

Note: Initializing the two buffers with a length of 1 appears to fix the issue.

### Minimal yet complete reproducer code (or URL to code)

```
    @Test
    public void testNetty() {

        ByteBufAllocator allocator = new PooledByteBufAllocator(true);

        ByteBuf a = allocator.buffer(0, 16384);
        ByteBuf b = allocator.buffer(0, 16384);

        System.out.println("a.capacity(" + 16 + ")");
        a.capacity(16);
        System.out.println("b.capacity(" + 16 + ")");
        b.capacity(16);
        System.out.println("a.capacity(" + 17 + ")");
        a.capacity(17);
        System.out.println("b.capacity(" + 17 + ")");
        b.capacity(17);

    }
```

### Netty version

4.1.70.FINAL

### JVM version (e.g. `java -version`)

17.0.1

**Comment by ebradshaw** [comment]
After a bit more digging, I realized that this issue only surfaces when io.netty.allocator.directMemoryCacheAlignment is set to a positive value.  Here's a test that fails:

```
public class NettyTest {

    static {
        System.setProperty("io.netty.allocator.directMemoryCacheAlignment", "64");
    }

    @Test
    public void testNetty() {

        ByteBufAllocator allocator = new PooledByteBufAllocator(true);

        ByteBuf a = allocator.buffer(0, 16384);
        ByteBuf b = allocator.buffer(0, 16384);

        System.out.println("a.capacity(" + 16 + ")");
        a.capacity(16);
        System.out.println("b.capacity(" + 16 + ")");
        b.capacity(16);
        System.out.println("a.capacity(" + 17 + ")");
        a.capacity(17);
        System.out.println("b.capacity(" + 17 + ")");
        b.capacity(17);

    }

}
```

**Comment by chrisvest** [comment]
Thanks for the test. I'm looking into it.

**Comment by normanmaurer** [comment]
I think I have a fix... PR will be opened soon

**Comment by normanmaurer** [comment]
@chrisvest @ebradshaw this should be fixed by https://github.com/netty/netty/pull/11987

**Comment by ebradshaw** [comment]
Excellent.  Thanks @normanmaurer!
