### ISSUE TITLE
Error parsing POST request with =

### ISSUE THREAD

**Issue by sd205** [netty/netty#11985]
### Expected behavior
Able to parse request body to POST request with string containing equals sign

### Actual behavior
Throws an exception:

io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$ErrorDataDecoderException: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:615)
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBody(HttpPostStandardRequestDecoder.java:366)
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:295)
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:47)
        at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:223)
        at com.blade.mvc.http.HttpRequest.init(HttpRequest.java:376)
        at com.blade.server.netty.HttpServerHandler.buildWebContext(HttpServerHandler.java:96)
        at com.blade.server.netty.HttpServerHandler.lambda$channelRead0$0(HttpServerHandler.java:85)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createTempFile(File.java:2024)
        at java.io.File.createTempFile(File.java:2070)
        at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.tempFile(AbstractDiskHttpData.java:90)
        at io.netty.handler.codec.http.multipart.AbstractDiskHttpData.addContent(AbstractDiskHttpData.java:162)
        at io.netty.handler.codec.http.multipart.DiskAttribute.addContent(DiskAttribute.java:98)
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.setFinalBuffer(HttpPostStandardRequestDecoder.java:624)
        at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.parseBodyAttributes(HttpPostStandardRequestDecoder.java:595)
        ... 16 more

### Steps to reproduce
Request body, only the formatString is material, any string containing = will cause the exception:
{"formatString":"=","delimiters":null,"params":["","","","","","","","","",""]}

### Minimal yet complete reproducer code (or URL to code)
See above

### Netty version
4.1.48, via Blade MVC 2.0.15.RELEASE https://github.com/lets-blade/blade

### JVM version (e.g. `java -version`)
1.8.0_271

### OS version (e.g. `uname -a`)
Windows 10

**Comment by sd205** [comment]
See also https://github.com/netty/netty/issues/11985

**Comment by fredericBregier** [comment]
Hi @sd205 
I follow your example:

        String testWithEqual = "{\"formatString=\":\"=\",\"delimiters=\":null,\"params\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}";
        byte[] bodyBytes = ("--be38b42a9ad2713f\n" +
                            "content-disposition: form-data; name=\"data\"; filename=\"data.json\"\n" +
                            "content-length: 81\n" +
                            "content-type: application/json; charset=UTF-8\n" +
                            "\n" +
                            testWithEqual + "\n" +
                            "--be38b42a9ad2713f--").getBytes();
        ByteBuf content = Unpooled.directBuffer(bodyBytes.length);
        content.writeBytes(bodyBytes);
        FullHttpRequest req = new DefaultFullHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/", content);
        req.headers().add("Content-Type", "multipart/form-data;boundary=be38b42a9ad2713f");
        try {
            HttpDataFactory factory = new DefaultHttpDataFactory(false); // test also with true
            HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(factory, req);
            assertEquals(1, decoder.getBodyHttpDatas().size());
            InterfaceHttpData data = decoder.getBodyHttpData("data");
            assertTrue(data instanceof MemoryFileUpload); // If Factory as True : DiskFileUpload
            assertEquals(testWithEqual, ((MemoryFileUpload) data).getString());
            factory.cleanAllHttpData();
            decoder.destroy();
        } catch (HttpPostRequestDecoder.ErrorDataDecoderException e) {
            fail("Was not expecting an exception");
        } finally {
            assertTrue(req.release());
        }

No error found...

I saw also the issue within "blade" but see nothing more, as @wanglunhui2012 wrote too, no error.

Can you elaborate a bit your issue?

**Comment by fredericBregier** [comment]
@sd205 see comment in https://github.com/lets-blade/blade/issues/427

**Comment by fredericBregier** [comment]
@sd205 Note that when using either multipart or url form message (with field=value in the body, value being url encoded), it is fine.

**Comment by fredericBregier** [comment]
@sd205 It seems that this issue is a missused of Netty contract for `HttpPostRequestDecoder` with blade.
I don't know if it's relared to your usage or to blade itself and its contract.
The issue is that you passed a data as Body that is not a request (neither `Content-Type: application/x-www-form-urlencoded` or `Content-Type: multipart/form-data;boundary="xxx"`) but a simple Json, which is not the responsability of `HttpPostRequestDecoder` to decode.

@normanmaurer I think this issue can be closed then.
