### ISSUE TITLE
Unable to resolve master.****.cache.amazonaws.com

### ISSUE THREAD

**Issue by Brainhu** [netty/netty#11993]
### Actual behavior
Unable to resolve master.****.cache.amazonaws.com

io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'master..cache.amazonaws.com' failed to resolve 'master..cache.amazonaws.com'
at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1013) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:966) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:414) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:463) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:225) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177) [netty-resolver-dns-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.63.Final.jar!/:4.1.63.Final]
at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.100.0.10:53] query via UDP timed out after 5000 milliseconds (no stack trace available)

### Steps to reproduce
sometimes happen  no regular
### Netty version
4.1.63
### JVM version (e.g. `java -version`)
1.8

**Comment by rdtriny** [comment]
1. Try to resolve the domain name manually, using 'dig' or 'nslookup' command.
2. If it works, try to ping the  nameserver, in your case , it's 10.100.0.10.
3. If step 2 works and network latency is much less than 5000ms, checkout and close the vpns or firewalls on the localhost.
4. Give Another try to see if it works.

**Comment by Brainhu** [comment]
> 1. Try to resolve the domain name manually, using 'dig' or 'nslookup' command.
> 2. If it works, try to ping the  nameserver, in your case , it's 10.100.0.10.
> 3. If step 2 works and network latency is much less than 5000ms, checkout and close the vpns or firewalls on the localhost.
> 4. Give another try to see if it works.

**Comment by Brainhu** [comment]
> 1. Try to resolve the domain name manually, using 'dig' or 'nslookup' command.
> 2. If it works, try to ping the  nameserver, in your case , it's 10.100.0.10.
> 3. If step 2 works and network latency is much less than 5000ms, checkout and close the vpns or firewalls on the localhost.
> 4. Give another try to see if it works.

异常发生的频率不高，平均1-2天一次，所以你的方案查不出问题根源。而且我的程序几十个，为何就其中的几个会出现这个异常。

**Comment by normanmaurer** [comment]
Please use English.

**Comment by Brainhu** [comment]
> Please use English.

The frequency of abnormal occurs is not high, an average of 1-2 days, so Rdtriny's way can't find the reason. And dozens of our procedures, why there are several exceptions.

**Comment by chenyu1st** [comment]
I also encountered the same problem, not only on eks, but also on the local self-built k8s, only the redis domain name can not be resolved, no other domain names, I also feel very strange

**Comment by danowensdev** [comment]
We have also encountered the same problem, but on Azure Container Apps. The problem is also sporadic.
Error below:
```
 io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'xyz-user-test.xyz-xyz.westeurope.azurecontainerapps.io' [A(1)] and search domain query for configured domains failed as well: [k8se-apps.svc.cluster.local, svc.cluster.local, cluster.local]
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1088)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1035)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:422)
	at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:493)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:261)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:208)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [32843: /127.0.0.11:53] DefaultDnsQuestion(xyz-user-test.xyz-xyz.westeurope.azurecontainerapps.io. IN A) query '32843' via UDP timed out after 5000 milliseconds (no stack trace available)
```
