### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by azzahrah** [netty/netty#12002]
Frame Decoder

```
public class Gt06FrameDecoder extends ByteToMessageDecoder {
    @Override
    protected void decode(ChannelHandlerContext ctx, ByteBuf buf, List<Object> out) throws Exception {
        /*
        Header      2byte       0x7878 or 0x7979
        Length      1/2Byte     Protocol Number + Information Content + Information Serial Number+ Error Check
        Protocol    1Byte
        Content `   NByte
        Serial      2Byte
        ErrorCheck  2Byte
        End         2Byte
         */
        if (buf.readableBytes() < 5) {
            return;
        }
        int length = 2 + 2; // head and tail
        byte header1=buf.getByte(buf.readerIndex());
        byte header2=buf.getByte(buf.readerIndex() + 1);

        if (header1 == 0x78 && header2 == 0x78) {
            length += 1 + buf.getUnsignedByte(buf.readerIndex() + 2);
        } else if (header1 == 0x79 && header2 == 0x79) {
            length += 2 + buf.getUnsignedShort(buf.readerIndex() + 2);
        }

        if (buf.readableBytes() >= length && buf.getUnsignedShort(buf.readerIndex() + length - 2) == 0x0d0a) {
            out.add(buf.readRetainedSlice(length));
            return;
        }
        int endIndex = buf.readerIndex() - 1;
        do {
            endIndex = buf.indexOf(endIndex + 1, buf.writerIndex(), (byte) 0x0d);
            if (endIndex > 0 && buf.writerIndex() > endIndex + 1 && buf.getByte(endIndex + 1) == 0x0a) {
                out.add(buf.readRetainedSlice(endIndex + 2 - buf.readerIndex()));
            }
        } while (endIndex > 0);
    }
}

```

### Netty version
 4.1.73.Final

### JVM version (e.g. `java -version`)
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-116.04.1)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-116.04.1, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Linux vmi228471.contaboserver.net 5.15.0-051500-generic #202110312130 SMP Sun Oct 31 21:33:20 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

java.lang.IndexOutOfBoundsException: readerIndex(10) + length(1) exceeds writerIndex(10): PooledSlicedByteBuf(ridx: 10, widx: 10, cap: 10/10, unwrapped: PooledUnsafeDirectByteBuf(ridx: 190, widx: 192, cap: 192))
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730)
        at io.netty.buffer.AbstractByteBuf.readUnsignedByte(AbstractByteBuf.java:744)
        at io.netty.buffer.WrappedByteBuf.readUnsignedByte(WrappedByteBuf.java:534)
        at io.netty.buffer.AdvancedLeakAwareByteBuf.readUnsignedByte(AdvancedLeakAwareByteBuf.java:408)
        at com.pusatgps.main.protocol.encoderdecoder.Gt06ProtocolDecoderV3.decodeGps(Gt06ProtocolDecoderV3.java:383)
        at com.pusatgps.main.protocol.encoderdecoder.Gt06ProtocolDecoderV3.decodeBasic(Gt06ProtocolDecoderV3.java:1277)
        at com.pusatgps.main.protocol.encoderdecoder.Gt06ProtocolDecoderV3.channelRead(Gt06ProtocolDecoderV3.java:1655)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by amizurov** [comment]
Hello @azzahrah, i have not look to this code deeply but i think the problem in your decoder and how you calculate `length`. Maybe i missing something.

**Comment by azzahrah** [comment]
@amizurov 
protocol structure have been mentioned above, but i will describe:
header start with 7878 7979, after header is length of package that length of package consume 1byte if header 7878, and 2byte i header 7979, below is detail:

header 7878 (2byte)
length of package (1 or 2byte)
protocol (1byte)
N content
serial (2byte)
crc (2byte)
end (2byte) 0xD0xA

below is fetch length data
```
buf.getUnsignedByte(buf.readerIndex() + 2);
```

my frame decoder working fine, but sometime error like above,

**Comment by azzahrah** [comment]
@normanmaurer , @amizurov 
thank i have been check, my device send data that not expected, so the problem is on my frameDecoder, below is wrong data...
```
78781f1216010e0a042fc900000000000000000000000000000000000000000000000000
```

**Comment by amizurov** [comment]
Cool, but your decoder should consider this scenario as a protocol violation or skip this characters if they can appear by some reason.
