### ISSUE TITLE
DnsNameResolver can not detect failure when bind to localAddress already in use

### ISSUE THREAD

**Issue by copbint** [netty/netty#12001]
### Expected behavior
After this PR: [Allow to config dns bind address in DnsNameResolver #11061](https://github.com/netty/netty/pull/11061), it is able to config DnsNameResolver localAddress. 
When localAddress is already in use, it is expected to detect the failure:
```java
        ChannelFuture future;
        if (localAddress == null) {
            future = b.register();
        } else {
            future = b.bind(localAddress); 
        }
        Throwable cause = future.cause();
        if (cause != null) { // should not be null when Address already in use
            if (cause instanceof RuntimeException) {
                throw (RuntimeException) cause;
            }
            if (cause instanceof Error) {
                throw (Error) cause;
            }
            throw new IllegalStateException("Unable to create / register Channel", cause);
        }
```
Actually `cause` will be null, I think it is beacause of the bind task is not completed yet here.
Simply change the code like this will solve the problem, but I'm not sure is it OK to block here. 
```java
future = b.bind(localAddress).awaitUninterruptibly();
```

Any suggestion will be great appreciated!

I'd like to submit a PR if there is a proper way to solve this.

### Netty version
4.1.72

### JVM version (e.g. `java -version`)
11.0.8

### OS version (e.g. `uname -a`)
windows 10

**Comment by Shoothzj** [comment]
Do you have real stackrace, I don't know if `ch=future.channel()` will throw an exception?
cc @normanmaurer

**Comment by copbint** [comment]
When localAddress is already in use, with or without awaitUninterruptibly() behaves differently: 

# b.bind(localAddress)  `without` awaitUninterruptibly()
Will not throw Address already in use Exception, but will fail when doing hostname query
```
Caused by: java.net.UnknownHostException: Failed to resolve 'localhost2' after 3 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:35)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:442)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:184)
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:35)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:442)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:224)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:176)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.resolver.dns.DnsNameResolverException: [/10.98.48.39:53] failed to send a query via UDP (no stack trace available)
Caused by: io.netty.channel.StacklessClosedChannelException: null
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
```

# b.bind(localAddress)  `with` awaitUninterruptibly()
```
Caused by: java.lang.IllegalStateException: Unable to create / register Channel
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:548)
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:516)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newNameResolver(DnsAddressResolverGroup.java:114)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:92)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:77)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:70)
	at reactor.netty.transport.TransportConnector.doResolveAndConnect(TransportConnector.java:261)
	at reactor.netty.transport.TransportConnector.lambda$connect$6(TransportConnector.java:110)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125)
	.......
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:455)
	at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:814)
	at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:785)
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:133)
	at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:130)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:130)
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:201)
	at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:196)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	... 4 common frames omitted

```

**Comment by ShijunDeng** [comment]
We had the same problem.Is there a good solution?

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty/pull/12034

**Comment by copbint** [comment]
That's great! Thanks!
