### ISSUE TITLE
Unsupported CipherSuite: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256

### ISSUE THREAD

**Issue by mdj1342** [netty/netty#12056]
###  Behavior
I have this problem when I use netty 4.1.68.Final and netty-tcnative to 4.1.42.Final. This happens while building SSL contexts with both OPENSSL and JDK SSL provider.

Error Stack：
```
javax.net.ssl.SSLException: failed to set cipher suite: [TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384, TLS_CHACHA20_POLY1305_SHA256]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:315)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:45)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:349)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:336)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:473)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606)
	at com.oracle.oci.sfw.netty.tls.NettySslBuilder.build(NettySslBuilder.java:419)
	at com.oracle.oci.sfw.netty.service.server.DocumentServerApplication.start(DocumentServerApplication.java:45)
	at com.oracle.oci.sfw.netty.service.server.DocumentServerApplication.start(DocumentServerApplication.java:22)
	at com.oracle.oci.sfw.netty.bootstrap.Application.run(Application.java:31)
	at com.oracle.oci.sfw.netty.service.server.DocumentServerApplication.main(DocumentServerApplication.java:86)
Caused by: java.lang.IllegalArgumentException: unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256(ECDHE-ECDSA-CHACHA20-POLY1305)
	at io.netty.handler.ssl.CipherSuiteConverter.convertToCipherStrings(CipherSuiteConverter.java:472)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:301)
	... 10 more
Exception in thread "main" java.lang.NullPointerException: sslContext
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897)
	at com.oracle.oci.sfw.netty.bootstrap.NettyServerBuilder.sslContext(NettyServerBuilder.java:61)
```

### Netty version
    <netty-version>4.1.68.Final</netty-version>
    <netty-tcnative-version>2.0.42.Final</netty-tcnative-version>

### JVM version (e.g. `java -version`)

openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8-LTS, mixed mode, sharing

### OS version (e.g. `uname -a`)
Linux vm 5.4.17-2102.206.1.el7uek.x86_64 #2 SMP Wed Oct 6 16:40:40 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Like the exception states `TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256` is not supported. Choose a different ciphersuite.
