### ISSUE TITLE
javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify

### ISSUE THREAD

**Issue by GREATwo** [netty/netty#12087]
get  javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify when use wss,how to solve

**Comment by chrisvest** [comment]
I think you should see if upgrading to a more recent version helps you.

**Comment by thomas-trendsoft** [comment]
I have a same issue also given in issue #9266. I used the httpsnoopclient example and for the most servers it works. But for some it won't works. 

i have java 12.0.1 and use netty-4.1.74.Final. If we miss some cipher or any other implementation it would be nice to have some real info. but i don't know if the error is more on server side. i tried with jetty current version http client on same java and it works. also curl and simple browser request was working. 

for rework i expanded the plain httpsnoop client example in start with:

`
    	  System.setProperty(org.slf4j.impl.SimpleLogger.DEFAULT_LOG_LEVEL_KEY, "Trace");
    	  System.setProperty("ssl.debug", "true");
    	  System.setProperty("javax.net.debug", "ssl");
          InternalLoggerFactory.setDefaultFactory(Slf4JLoggerFactory.INSTANCE);

`
With this I tried enable all debugging and get only the same java ssl exception message:

` 
 javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:254)
  	at java.base/sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:733)
  	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1867)
  	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1067)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
  	at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:206)
`

the only diff is the url i use. pleas don't laugh ;) 

https://api.whatdoestrumpthink.com/api/v1/quotes/random

i was working to get a joke bot working and also same problem on some other sites.

**Comment by thomas-trendsoft** [comment]
i tried also with java 17 and same error. some other ssl site not working on snoop but every other client is:

https://api.chucknorris.io/jokes/random

javax.net.ssl|DEBUG|0C|nioEventLoopGroup-2-1|2022-02-20 23:44:54.260 CET|Alert.java:238|Received alert message (
"Alert": {
  "level"      : "fatal",
  "description": "handshake_failure"
}
)
javax.net.ssl|ERROR|0C|nioEventLoopGroup-2-1|2022-02-20 23:44:54.262 CET|TransportContext.java:312|Fatal (HANDSHAKE_FAILURE): Received fatal alert: handshake_failure (
"throwable" : {
  javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
  	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
  	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:180)
  	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)

**Comment by chrisvest** [comment]
Those debug properties might have to be set on the command line, to guarantee they're applied early enough. Also, since they apply to the JDK SSL implementation, the logging they produce is not going to go into the logging framework configured for Netty. I think it logs to System.err. There should be a lot of output from it, once you find it.

**Comment by thomas-trendsoft** [comment]
i got all debugging messages i expected but cannot explain why the remote side closed the session, while every other client won't do this. i know you are not my debugging service but i thougt my info would probaply help, unless i seem to be not the only one with this problem in this or the other mentioned issue #9266 . in the later case of the chuck norris api i think i could be the cipher algorithm used by the remote side. 

if i can help with any further information please advice.

**Comment by thomas-trendsoft** [comment]
ok, searched a little more and found one missing cipher also in the other connections. 

ECDHE-ECDSA-CHACHA20-POLY1305

so found the ticket #12056. but this only an option if i am the server not the client. so i am stuck here if i need netty as a client to connect a server with these limitations?

**Comment by thomas-trendsoft** [comment]
ok, one more: 

i read more manual and found the openssl engine to take as advice. so i expended the pom.xml and init my sslcontext with:

`              sslCtx = SslContextBuilder.forClient()
            		  .sslProvider(SslProvider.OPENSSL)
            		  .startTls(true)
            		  .protocols(new String[] {"TLSv1.2"})
            		  .trustManager(InsecureTrustManagerFactory.INSTANCE).build();
`

Now i get a more clear message from OpenSSL:

`[nioEventLoopGroup-2-1] DEBUG io.netty.handler.logging.LoggingHandler - [id: 0xdfae365a, L:/192.168.178.28:42118 - R:api.whatdoestrumpthink.com/54.230.206.25:443] CLOSE
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
`

so i thougth it could be a nasty server thing. but as last "proof" i tried also:

`openssl s_client -connect api.whatdoestrumpthink.com:443 -tls1_2`

this works fine. so i still don't really know if it is a server thing

**Comment by patpatpat123** [comment]
having the same issue
