### ISSUE TITLE
Could not initialize class io.netty.util.internal.PlatformDependent0

### ISSUE THREAD

**Issue by the-college-dropout** [netty/netty#12100]
### Expected behavior

Server to be online

### Actual behavior

Server didn't went online
throws
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:101)
	at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
	at io.netty.util.Signal$1.<init>(Signal.java:27)
	at io.netty.util.Signal.<clinit>(Signal.java:27)
	at io.netty.util.concurrent.DefaultPromise.<clinit>(DefaultPromise.java:42)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:51)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
	at NettyServer.main(NettyServer.java:24)

Process finished with exit code 1

### Steps to reproduce

I'm not really sure what to write in this collumn，since it's my first time to use github

### Minimal yet complete reproducer code (or URL to code)

not sure either
### Netty version
4.1.6 Final

**Comment by the-college-dropout** [comment]
really struggling to get this problem solved, i'm so sorry that i couldn't explain my problem well.
Please help me out , thanks

**Comment by normanmaurer** [comment]
4.1.6 is super old... Please use the latest version, chances are good its fixed.
