### ISSUE TITLE
Socksproxy example throws OutOfDirectMemoryError

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#12115]
I did several tests with the Socksproxy example.
I only changed the port and I added throwable.printStackTrace(); to all the exceptionCaught methods.
I download two 1 GB files via the Socks proxy server multiple times.
After some time I will always see a message like:

io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 7549747200, max: 7560757248)
        at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:802)
        at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:731)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:632)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:607)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:202)
        at io.netty.buffer.PoolArena.tcacheAllocateNormal(PoolArena.java:186)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:136)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:395)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:139)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)

I also tested with very high memory settings: -Xmx7524m -Xms7524m -server.
With higher settings it just takes longer until the error appears. I can easily reproduce it every time.

Is there a bug somewhere in the code? It's strange that the ResourceLeakDetector doesn't find anything.
I tested with the latest 4.1.74.Final and also with an older version.

**Comment by chrisvest** [comment]
Do you do any chunking in your pipeline? One gigabyte is quite a lot to move around in a single ByteBuf, if that's what's happening.

**Comment by WhiteTrashLord** [comment]
I could fix the OutOfDirectMemoryError by changing the code. I removed all the promise stuff in the class SocksServerConnectHandler. My code works more like the HexDumpProxy example now. The class SocksServerConnectHandler is not used like a Sharable. It seems to cause no problems but it's bad example code. I have no idea why the current code which uses a promise seems to be buggy. Maybe a real Netty expert can check it. I am not sure if my changed code is fully working. I need to do more tests.
