### ISSUE TITLE
io.netty.util.internal.OutOfDirectMemoryError

### ISSUE THREAD

**Issue by tsangyi** [netty/netty#12137]
### Expected behavior
The netty used by the gateway spring cloud gateway in our project
### Actual behavior
Reported an error after running for a period of time: io.netty.util.internal.OutOfDirectMemoryError

### Steps to reproduce
The project always runs for a period of time to report an error.

2022-02-28 11:50:36.831 ERROR 7542 --- [or-http-epoll-1] o.s.w.s.adapter.HttpWebHandlerAdapter    : [5f24f22e] Error [reactor.netty.ReactorNetty$InternalNettyException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3204448263, max: 3220439040)] for HTTP GET "/cis/system/car/tree", but ServerHttpResponse already committed (200 OK)
2022-02-28 11:50:36.832 ERROR 7542 --- [or-http-epoll-1] reactor.core.publisher.Operators         : Operator called default onErrorDropped

reactor.netty.ReactorNetty$InternalNettyException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3204448263, max: 3220439040)
 Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
 |_ checkpoint ⇢ springfox.boot.starter.autoconfigure.SwaggerUiWebFluxConfiguration$CustomWebFilter [DefaultWebFilterChain]
 |_ checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
 |_ checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
 |_ checkpoint ⇢ HTTP GET "/cis/system/car/tree" [ExceptionHandlingWebHandler]
Stack trace:
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3204448263, max: 3220439040)
 at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:754)
 at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:709)
 at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:755)
 at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:731)
 at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:247)
 at io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
 at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
 at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356)
### Question
This is an error reported by netty's NoCleaner memory allocation, ```PlatformDependent.allocateDirectNoCleaner (capacity) ```. There is no memory released in this method.
I know there's a way to free memory, ```PlatformDependent.freeDirectNoCleaner (chunk.memory)```
I want to know when DirectNoCleaner frees memory and why it causes heap external memory to pile up.

My current solution is to configure parameters：```-Dio.netty.maxDirectMemory=0```。In order not to use DirectNoCleaner，Further testing is under way.
### Netty version
4.1.49.Final
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
centos 8

**Comment by caozhongyang** [comment]
how to solve the problem, thank you
