### ISSUE TITLE
WebSocket server throws casting exception in 5.0.0.Alpha1

### ISSUE THREAD

**Issue by imryao** [netty/netty#12216]
### Expected behavior

Run without exception.

### Actual behavior

```
[multithreadEventLoopGroup-1-1] INFO io.netty5.handler.logging.LoggingHandler - [id: 0x54777d0a, L:/[0:0:0:0:0:0:0:0]:8080] READ: [id: 0xd00fe526, L:/127.0.0.1:8080 - R:/127.0.0.1:60554]
[multithreadEventLoopGroup-1-1] INFO io.netty5.handler.logging.LoggingHandler - [id: 0x54777d0a, L:/[0:0:0:0:0:0:0:0]:8080] READ COMPLETE
java.lang.ClassCastException: class io.netty5.buffer.PooledUnsafeDirectByteBuf cannot be cast to class io.netty5.handler.codec.http.HttpObject (io.netty5.buffer.PooledUnsafeDirectByteBuf and io.netty5.handler.codec.http.HttpObject are in unnamed module of loader 'app')
	at io.netty5.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler.channelRead(WebSocketServerProtocolHandshakeHandler.java:60)
	at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:364)
	at io.netty5.channel.DefaultChannelHandlerContext.findAndInvokeChannelRead(DefaultChannelHandlerContext.java:358)
	at io.netty5.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:339)
	at io.netty5.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:98)
	at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:364)
	at io.netty5.channel.DefaultChannelHandlerContext.findAndInvokeChannelRead(DefaultChannelHandlerContext.java:358)
	at io.netty5.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:339)
	at io.netty5.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:90)
	at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:364)
	at io.netty5.channel.DefaultChannelHandlerContext.findAndInvokeChannelRead(DefaultChannelHandlerContext.java:358)
	at io.netty5.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:339)
	at io.netty5.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:414)
	at io.netty5.handler.codec.ByteToMessageDecoderForBuffer.channelRead(ByteToMessageDecoderForBuffer.java:231)
	at io.netty5.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:220)
	at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:364)
	at io.netty5.channel.DefaultChannelHandlerContext.findAndInvokeChannelRead(DefaultChannelHandlerContext.java:358)
	at io.netty5.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:339)
	at io.netty5.channel.ChannelHandler.channelRead(ChannelHandler.java:237)
	at io.netty5.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:364)
	at io.netty5.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:824)
	at io.netty5.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:187)
	at io.netty5.channel.nio.NioHandler.processSelectedKey(NioHandler.java:584)
	at io.netty5.channel.nio.NioHandler.processSelectedKey(NioHandler.java:544)
	at io.netty5.channel.nio.NioHandler.processSelectedKeysOptimized(NioHandler.java:525)
	at io.netty5.channel.nio.NioHandler.processSelectedKeys(NioHandler.java:457)
	at io.netty5.channel.nio.NioHandler.run(NioHandler.java:434)
	at io.netty5.channel.SingleThreadEventLoop.runIo(SingleThreadEventLoop.java:207)
	at io.netty5.channel.SingleThreadEventLoop.run(SingleThreadEventLoop.java:191)
	at io.netty5.util.concurrent.SingleThreadEventExecutor.lambda$doStartThread$4(SingleThreadEventExecutor.java:768)
	at io.netty5.util.internal.ThreadExecutorMap.lambda$apply$1(ThreadExecutorMap.java:68)
	at io.netty5.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce

Run the example code.

### Minimal yet complete reproducer code (or URL to code)

https://github.com/netty/netty/tree/main/example/src/main/java/io/netty5/example/http/websocketx/server

### Netty version

```
5.0.0.Alpha1
```

### JVM version (e.g. `java -version`)

```
java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

```
Darwin localhost 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64
```

**Comment by centratelemedia** [comment]
@chrisvest 
we have same issue, any plan to fix those sample?
