### ISSUE TITLE
Allow configuration of unsafe legacy connection configuration in client mode

### ISSUE THREAD

**Issue by dgolombek** [netty/netty#12230]
### Expected behavior

When using Netty with netty-tcnative-openssl, the SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION and SSL_OP_LEGACY_SERVER_CONNECT options are cleared by default (https://github.com/netty/netty-tcnative/blob/7fe09518b64b10897f7286b39b79650ccb05c4cf/openssl-dynamic/src/main/c/sslcontext.c#L374), and there is no way to turn them back on currently.

We could add this to ReferenceCountedOpenSslContext, either in the constructor (as a new  SslContextOption that was applied after the call to SSLContext.make), or as a method that directly exposed access to SSLContext.setOptions (although that would be tricky with BoringSSL support).

### Actual behavior

Trying to connect to a website that doesn't support Renegotiation Indication Extension (RFC 5746) fails

```
java.net.ConnectException: error:141E3152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled
at org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
at org.asynchttpclient.netty.channel.NettyConnectListener$1.onFailure(NettyConnectListener.java:151)
at org.asynchttpclient.netty.SimpleFutureListener.operationComplete(SimpleFutureListener.java:26)
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
at io.netty.handler.ssl.SslHandler.handleUnwrapThrowable(SslHandler.java:1307)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1289)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1330)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: javax.net.ssl.SSLHandshakeException: error:141E3152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1347)
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1308)
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1384)
at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:202)
at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1388)
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1283)
... 20 common frames omitted
```

### Steps to reproduce

Try to connect to https://health.ucdavis.edu/ with a Netty Client. 

### Minimal yet complete reproducer code (or URL to code)

I can provide code later

### Netty version

netty version 4.1.75.Final
netty-tcnative version 2.0.50.Final

### JVM version (e.g. `java -version`)

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### OS version (e.g. `uname -a`)

Darwin ip-192-168-1-155.us-west-2.compute.internal 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64

**Comment by Fury-Fox** [comment]
How to allow configuration of unsafe legacy connection configuration in server mode?
