### ISSUE TITLE
PlatformDependent pattern to check for failure to bind is incorrect when used under authbind

### ISSUE THREAD

**Issue by senthilnest** [netty/netty#1231]
I've been having very long startup times with netty 4 and when I did jstack, it indicated it was looping in PlatformDependent::isRoot0. When I did strace, I saw it was trying and failing to bind to each port from 1023 to 1. I then took that code into my main code and saw that the problem is that under authbind, the error message is "operation not permitted" which unfortunately does not match the regex of "._permission._denied.*".

Thanks,
Senthil.

**Comment by jayv** [comment]
Hi @trustin @normanmaurer,
Just tried to deploy the `EpollEventLoopGroup` with `authbind` on Netty 4.1.4 and that fails to bind with to port 80 and 443, NIO works fine. I'm not sure how to debug it further and whether I should reopen this issue or start a new one, at least it's related to the JNI driver in combination with`authbind`. 

```
io.netty.channel.unix.Errors$NativeIoException: bind() failed: Permission denied
        at io.netty.channel.unix.Errors.newIOException(Errors.java:109)
        at io.netty.channel.unix.Socket.bind(Socket.java:231)
        at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:91)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:511)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:496)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:363)
        at io.netty.util.concurrent.SingleThreadEventExecutor.safeExecute(SingleThreadEventExecutor.java:451)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
```

**Comment by normanmaurer** [comment]
@jayv please open a new one with exact steps to reproduce

**Comment by jayv** [comment]
Done: https://github.com/netty/netty/issues/5789

- Jo Voordeckers
