### ISSUE TITLE
EventLoop threads getting stuck trying to close channel.

### ISSUE THREAD

**Issue by stefanklas** [netty/netty#12365]
### Expected behavior
Expecting threads to close channel without problem. 

### Actual behavior
Thread getting stuck trying to close channel, when calling `channel.close().awaitUninterruptibly()`

**Extract from thread dump:** 
```
"epollEventLoopGroup-3-2" id=36 state=WAITING
    - waiting on <0x2236fb83> (a io.netty.channel.DefaultChannelPromise)
    - locked <0x2236fb83> (a io.netty.channel.DefaultChannelPromise)
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:502)
    at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:275)
    at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
    at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
    at com.oracle.pic.apigw.state.client.NettyHttp2Client.stop(NettyHttp2Client.java:247)
    
"epollEventLoopGroup-3-10" id=251 state=WAITING
    - waiting on <0x20e565cc> (a io.netty.channel.DefaultChannelPromise)
    - locked <0x20e565cc> (a io.netty.channel.DefaultChannelPromise)
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:502)
    at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:275)
    at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
    at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
    at com.oracle.pic.apigw.state.client.NettyHttp2Client.stop(NettyHttp2Client.java:247)  
    
```
    
  
  **Stop Method Hanging**
 ``` 
 public synchronized void stop() {
      if (running.compareAndSet(true, false)) {
          if (channel != null) {
              channel.close().awaitUninterruptibly();
          }
      }
  }
  ```
Channel is HTTP2

```

private class Http2ClientInitializer extends ChannelInitializer<SocketChannel> {
    private HttpToHttp2ConnectionHandler connectionHandler;

    @Override
    public void initChannel(SocketChannel ch) {
        final Http2Connection connection = new DefaultHttp2Connection(false);
        connectionHandler = new HttpToHttp2ConnectionHandlerBuilder()
            .frameListener(new DelegatingDecompressorFrameListener(
                connection,
                new InboundHttp2ToHttpAdapterBuilder(connection)
                    .maxContentLength(maxContentLength)
                    .propagateSettings(true)
                    .build()))
            .connection(connection)
            .build();
        if (sslCtx != null) {
            configureSsl(ch);
        } else {
            configureClearText(ch);
        }
    }

```

Similar setup to https://netty.io/4.1/xref/io/netty/example/http2/helloworld/client/Http2ClientInitializer.html
### Steps to reproduce
Not clear how to reproduce. 

Event was triggered by VM containing netty server physically being shut down.

### Netty version
4.1.70

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (build 1.8.0_322-b06)

### OS version (e.g. `uname -a`)
Linux (4.14.35-2047.511.5.7.el7uek.x86_64) x86_64 x86_64 x86_64 GNU/Linux

**Comment by chrisvest** [comment]
The `awaitUninterruptibly()` is just blocking until the future completes. You need to look into where that close task ends up and why it doesn't complete.

**Comment by stefanklas** [comment]
Would the eventLoop(thread) that controls the channel is trying to be closed is stuck (in some sync task), would this cause the command channel.close().awaitUninterruptibly() to hang?

**Comment by normanmaurer** [comment]
@stefanklas yes... you are not allowed to block. the eventLoop. Maybe a `jstack` will tell you what's going on

**Comment by stefanklas** [comment]
Ok many thanks. This is problem i believe.
