### ISSUE TITLE
tcnative is missing native lib on SUSE

### ISSUE THREAD

**Issue by ashertarno** [netty/netty#12432]
we are using netty via vertx. all netty dependencies are brought by vertx, except tcnative which is a part of our project.
while we were working with an older version of vertx that incorporates netty 4.1.72 and tcnative 2.0.46 - all worked well.
here is the list of netty jars deployed to the system in the working environment:

> netty-buffer-4.1.72.Final.jar
netty-codec-4.1.72.Final.jar
netty-codec-dns-4.1.72.Final.jar
netty-codec-http-4.1.72.Final.jar
netty-codec-http2-4.1.72.Final.jar
netty-codec-socks-4.1.72.Final.jar
netty-common-4.1.72.Final.jar
netty-handler-4.1.72.Final.jar
netty-handler-proxy-4.1.72.Final.jar
netty-resolver-4.1.72.Final.jar
netty-resolver-dns-4.1.72.Final.jar
netty-tcnative-classes-2.0.46.Final.jar
netty-transport-4.1.72.Final.jar

once we have updated to a newer vertx version, it brought netty 4.1.77.Final in, we've also upgraded tcnative to 2.0.48.Final.
here is the list of netty jars deployed to the system after the upgrade:

> netty-buffer-4.1.77.Final.jar
netty-codec-4.1.77.Final.jar
netty-codec-dns-4.1.77.Final.jar
netty-codec-http-4.1.77.Final.jar
netty-codec-http2-4.1.77.Final.jar
netty-codec-socks-4.1.77.Final.jar
netty-common-4.1.77.Final.jar
netty-handler-4.1.77.Final.jar
netty-handler-proxy-4.1.77.Final.jar
netty-resolver-4.1.77.Final.jar
netty-resolver-dns-4.1.77.Final.jar
netty-transport-4.1.77.Final.jar
netty-tcnative-2.0.48.Final-linux-x86_64.jar
netty-tcnative-classes-2.0.48.Final.jar

now we are running into a 
```
io.vertx.core.VertxException: OpenSSL is not available 
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64_suse, netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
...
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64_suse.so
...
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64_fedora.so
...
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_x86_64.so
...
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
```
(full stack trace is below)

i don't know if it's expected that no suse.so is provided out of the box, but in the **netty-tcnative-2.0.48.Final-linux-x86_64.jar**
i do see **libnetty_tcnative_linux_x86_64.so**.  so my guess would be that netty in such case should be looking for it instead of **libnetty_tcnative_x86_64.so** (_linux_ is the diff)

### Netty version
4.1.77.Final with tcnative 2.0.48.Final

### JVM version (e.g. `java -version`)
11

### OS version (e.g. `uname -a`)
SUSE Linux Enterprise Server 15 SP2

full error stack trace:

```
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_linux_x86_64_suse, netty_tcnative_linux_x86_64, netty_tcnative_linux_x86_64_fedora, netty_tcnative_x86_64, netty_tcnative]
                                                              at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
                                                              at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
                                                              at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
                                                              at io.vertx.core.net.impl.SSLHelper.resolveEngineOptions(SSLHelper.java:74)
                                                              ... 78 more
                                                              Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_64_suse
                                                                      at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
                                                                      at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
                                                                      ... 81 more
                                                              **Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64_suse.so**
                                                                      at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
                                                                      ... 82 more
                                                                      Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_suse in java.library.path: [/usr/local/lib]
                                                                              at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                              at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                              at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                              at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                              at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
                                                                              at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
                                                                              ... 82 more
                                                                              Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_suse in java.library.path: [/usr/local/lib]
                                                                                      at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                                      at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                                      at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                                      at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                                                                      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                                                                      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                                                                      at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
                                                                                      at java.base/java.security.AccessController.doPrivileged(Native Method)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
                                                                                      ... 83 more
                                                              Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_tcnative_linux_x86_6416931155112832328266.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory
at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
                                                                      at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
                                                                      at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
                                                                      at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
                                                                      at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
                                                                      at java.base/java.lang.Runtime.load0(Runtime.java:768)
                                                                      at java.base/java.lang.System.load(System.java:1837)
                                                                      at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
                                                                      at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:218)
                                                                      at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
                                                                      ... 81 more
                                                                      Suppressed: java.lang.UnsatisfiedLinkError: /tmp/libnetty_tcnative_linux_x86_6416931155112832328266.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory
                                                                              at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
                                                                              at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
                                                                              at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
                                                                              at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
                                                                              at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
                                                                              at java.base/java.lang.Runtime.load0(Runtime.java:768)
                                                                              at java.base/java.lang.System.load(System.java:1837)
                                                                              at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
                                                                              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                                                              at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                                                              at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                                                              at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                                                              at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
                                                                              at java.base/java.security.AccessController.doPrivileged(Native Method)
                                                                              at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
                                                                              at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
                                                                              ... 83 more
                                                                      Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path: [/usr/local/lib]
                                                                              at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                              at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                              at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                              at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                              at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
                                                                              at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
                                                                              ... 82 more
                                                                              Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64 in java.library.path: [/usr/local/lib]
at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                                      at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                                      at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                                      at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                                                                      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                                                                      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                                                                      at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
                                                                                      at java.base/java.security.AccessController.doPrivileged(Native Method)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
                                                                                      ... 83 more
                                                              Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_linux_x86_64_fedora
                                                                      at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
                                                                      at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
                                                                      ... 81 more
                                                              **Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_linux_x86_64_fedora.so**
                                                                      at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
                                                                      ... 82 more
                                                                      Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_fedora in java.library.path: [/usr/local/lib]
                                                                              at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                              at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                              at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                              at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                              at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
                                                                              at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
                                                                              ... 82 more
                                                                              Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_linux_x86_64_fedora in java.library.path: [/usr/local/lib]
                                                                                      at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                                      at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                                      at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                                      at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                                                                      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                                                                      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                                                                      at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
                                                                                      at java.base/java.security.AccessController.doPrivileged(Native Method)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
                                                                                      ... 83 more
                                                             Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_x86_64
                                                                      at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
                                                                      at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
                                                                      ... 81 more
                                                              **Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_x86_64.so**
                                                                      at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
                                                                      ... 82 more
                                                                      Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: [/usr/local/lib]
                                                                              at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                              at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                              at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                              at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                              at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
                                                                              at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
                                                                              ... 82 more
                                                                              Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path: [/usr/local/lib]
                                                                                      at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                                      at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                                      at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                                      at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                                                                      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                                                                      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                                                                      at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
                                                                                      at java.base/java.security.AccessController.doPrivileged(Native Method)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
                                                                                      ... 83 more
                                                              Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
                                                                      at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
                                                                      at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
                                                                      ... 81 more
                                                              **Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so**
                                                                      at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
                                                                      ... 82 more
                                                                      Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: [/usr/local/lib]
                                                                              at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                              at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                              at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                              at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                              at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
                                                                              at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
                                                                              ... 82 more
                                                                              Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path: [/usr/local/lib]
                                                                                      at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
                                                                                      at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
                                                                                      at java.base/java.lang.System.loadLibrary(System.java:1873)
                                                                                      at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                                                                                      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                                                                                      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                                                                      at java.base/java.lang.reflect.Method.invoke(Method.java:566)
                                                                                      at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
                                                                                      at java.base/java.security.AccessController.doPrivileged(Native Method)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
                                                                                      at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
                                                                                      ... 83 more
```

**Comment by chrisvest** [comment]
Netty 4.1.77.Final should use tcnative 2.0.52.Final. Does it work if you upgrade to that version?

**Comment by chrisvest** [comment]
Aha, the real cause is hidden deeper in the middle of the stack trace:

```
java.lang.UnsatisfiedLinkError: /tmp/libnetty_tcnative_linux_x86_6416931155112832328266.so: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```

If you have OpenSSL installed, it doesn't have the expected name.

**Comment by ashertarno** [comment]
@chrisvest thanks for looking into this. 2.0.52 didn't work either. does the newer version is looking for a different openssl name than the older one? did the naming convention change?

**Comment by chrisvest** [comment]
Alternatively, you can switch to the boringssl version of tcnative. That version has boringssl statically linked in, so the openssl from you distro is not used.

**Comment by xitizzzz** [comment]
@chrisvest @ashertarno did you come to any conclusion why we are having this error ? I see the same error for netty 4.1.79.Final with tcnative to 2.0.53.Final

**Comment by chrisvest** [comment]
Yeah, you need to either create a `libssl.so.1.0.0` symlink for your openssl so tcnative can find it, or use the boringssl variant of tcnative.
