### ISSUE TITLE
No logging of byte distribution write error

### ISSUE THREAD

**Issue by fgarsombke** [netty/netty#12443]
### Expected behavior
Print t throwable when a writer error is thrown.

Line here:

https://github.com/netty/netty/blob/201f6b6bb2dcdff07df6e30552b96fedbcf21759/codec-http2/src/main/java/io/netty/handler/codec/http2/WeightedFairQueueByteDistributor.java#L614

### Actual behavior
When a writer error is thrown the error message is "byte distribution write error" but the t throwable is not printed.

```
io.grpc.StatusRuntimeException: INTERNAL: Connection closed after GOAWAY. HTTP/2 error code: INTERNAL_ERROR, debug data: byte distribution write error
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at com.rachio.user.api.user.UserServiceGrpc$UserServiceBlockingStub.getVisibleElements(UserServiceGrpc.java:4110)
	at com.rachio.user.UserClientWrapper.getVisibleElements(UserClientWrapper.java)
	at com.rachio.api.service.grpc.LocationServiceImpl.getLocationVisibleElement(LocationServiceImpl.java:131)
	at com.rachio.api.service.grpc.LocationServiceImpl.getLocation(LocationServiceImpl.java:122)
	at com.rachio.api.service.grpc.LocationServiceImpl.getLocation(LocationServiceImpl.java:115)
	at com.rachio.api.service.grpc.LocationServiceImpl$$FastClassBySpringCGLIB$$3783b184.invoke(<generated>)
```

### Steps to reproduce
I really don't know. We see this randomly with Grpc. Would love to know what is actually causing this.

### Netty version
io.netty 4.1.73.Final
jetty-9.4.z-SNAPSHOT

### JVM version (e.g. `java -version`)
1.8.0_332

### OS version (e.g. `uname -a`)
Fargate Linux 1.4.0

**Comment by chrisvest** [comment]
The stack trace for the `Http2Exception` produced by the `connectionError` seems to be missing entirely.

**Comment by fgarsombke** [comment]
@chrisvest Aha, that helps a bit!

The error posted above is from an external gRPC service (API) accessing an internal gRPC service.

After searching for `Http2Exception` here is the error from the internal service.

This is getting propagated back to the gRPC client which is throwing the error shown above. Wondering If you have any ideas around handling this scenario? If not I will have our team do some more investigating. Thank you for the idea on what to search for!

```
2022-06-04 12:45:01,700 [] WARN  NettyServerHandler Stream Error
io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:172)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:481)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:105)
	at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:357)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1007)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:963)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:515)
	at io.netty.handler.codec.http2.DefaultHttp2Connection.close(DefaultHttp2Connection.java:153)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:209)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:417)
	at io.grpc.netty.NettyServerHandler.channelInactive(NettyServerHandler.java:627)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by normanmaurer** [comment]
Maybe @ejona86 can help

**Comment by ejona86** [comment]
> When a writer error is thrown the error message is "byte distribution write error" but the t throwable is not printed.

You are showing client-side. I think it is appropriate the additional error information is not included in the debug info sent to the client. But it should have been logged on server-side. That isn't something for Netty to do though, and I expect grpc is already logging this on server-side.

Although looking at gRPC, it appears _all_ connection errors were changed to FINE many years ago:
https://github.com/grpc/grpc-java/blob/a738bc8f22978f592efe38a0f4ca9cb5a7347aa6/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L541

So something probably needs to be done there to not lose the error information in a case like this. But also avoid logging more mundane errors. Maybe we should log if `cause.getCause() != null`. In any case, this is a gRPC thing and would be an issue there, not here in Netty. (Once we know what exception is happening, then Netty might come into play again.)

> io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place

This looks unrelated. It doesn't have ByteDistributor in the stack trace and is not actually thrown (it is a future failure). This normally happens due to deadlines/client cancellation. It is tracked by https://github.com/grpc/grpc-java/issues/6943

**Comment by ejona86** [comment]
Closing, but open an issue on grpc/grpc-java.
