### ISSUE TITLE
Netty fails to determine type parameters

### ISSUE THREAD

**Issue by zcourts** [netty/netty#1247]
``` java

/usr/lib/jvm/jdk1.7-u17/bin/java -Didea.launcher.port=7538 -Didea.launcher.bin.path=/home/courtney/bin/idea/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/jdk1.7-u17/jre/lib/jfxrt.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/jfr.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/rt.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/resources.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/jsse.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/deploy.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/javaws.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/jce.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/management-agent.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/plugin.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/charsets.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/ext/zipfs.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/ext/dnsns.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/ext/localedata.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/jdk1.7-u17/jre/lib/ext/sunec.jar:/home/courtney/projects/Higgs/higgs-boson/target/classes:/home/courtney/projects/Higgs/higgs-core/target/classes:/home/courtney/.m2/repository/org/slf4j/slf4j-api/1.6.1/slf4j-api-1.6.1.jar:/home/courtney/.m2/repository/org/slf4j/slf4j-log4j12/1.7.0/slf4j-log4j12-1.7.0.jar:/home/courtney/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/courtney/.m2/repository/com/google/guava/guava/13.0.1/guava-13.0.1.jar:/home/courtney/.m2/repository/io/netty/netty-all/4.0.0.CR2-SNAPSHOT/netty-all-4.0.0.CR2-SNAPSHOT.jar:/home/courtney/.m2/repository/com/esotericsoftware/kryo/kryo/2.21/kryo-2.21.jar:/home/courtney/.m2/repository/com/esotericsoftware/reflectasm/reflectasm/1.07/reflectasm-1.07-shaded.jar:/home/courtney/.m2/repository/org/ow2/asm/asm/4.0/asm-4.0.jar:/home/courtney/.m2/repository/com/esotericsoftware/minlog/minlog/1.2/minlog-1.2.jar:/home/courtney/.m2/repository/org/objenesis/objenesis/1.2/objenesis-1.2.jar:/home/courtney/.m2/repository/junit/junit/4.8.2/junit-4.8.2.jar:/home/courtney/bin/idea/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain io.higgs.boson.demo.DemoClient
io.netty.util.internal.logging.Slf4JLogger 07:28:10,059 DEBUG InternalLoggerFactory:71 - Using SLF4J as the default logging framework
io.netty.util.internal.logging.Slf4JLogger 07:28:10,067 DEBUG MultithreadEventLoopGroup:76 - io.netty.eventLoopThreads: 16
io.netty.util.internal.logging.Slf4JLogger 07:28:10,082 DEBUG NioEventLoop:76 - io.netty.selectorAutoRebuildThreshold: 512
io.netty.util.internal.logging.Slf4JLogger 07:28:10,108 DEBUG PlatformDependent:71 - Platform: Android
io.netty.util.internal.logging.Slf4JLogger 07:28:10,117 DEBUG PlatformDependent:76 - UID: 1000
io.netty.util.internal.logging.Slf4JLogger 07:28:10,118 DEBUG PlatformDependent:76 - Java version: 7
io.netty.util.internal.logging.Slf4JLogger 07:28:10,120 DEBUG PlatformDependent0:76 - java.nio.ByteBuffer.cleaner: available
io.netty.util.internal.logging.Slf4JLogger 07:28:10,120 DEBUG PlatformDependent0:76 - java.nio.Buffer.address: available
io.netty.util.internal.logging.Slf4JLogger 07:28:10,121 DEBUG PlatformDependent0:76 - sun.misc.Unsafe.theUnsafe: available
io.netty.util.internal.logging.Slf4JLogger 07:28:10,121 DEBUG PlatformDependent0:71 - sun.misc.Unsafe.copyMemory: available
io.netty.util.internal.logging.Slf4JLogger 07:28:10,122 DEBUG PlatformDependent0:76 - java.nio.Bits.unaligned: true
io.netty.util.internal.logging.Slf4JLogger 07:28:10,122 DEBUG PlatformDependent:76 - sun.misc.Unsafe: available
io.netty.util.internal.logging.Slf4JLogger 07:28:10,123 DEBUG PlatformDependent:71 - Javassist: unavailable
io.netty.util.internal.logging.Slf4JLogger 07:28:10,124  WARN PlatformDependent:131 - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
io.netty.util.internal.logging.Slf4JLogger 07:28:10,124 DEBUG PlatformDependent:76 - io.netty.preferDirect: false
io.higgs.EventTunnel$1 07:28:10,144  WARN BosonClient:52 - Unhandled exception
java.lang.IllegalStateException: cannot determine the type of the type parameter 'SM': class io.higgs.EventProcessor
    at io.netty.util.internal.TypeParameterMatcher.fail(TypeParameterMatcher.java:171)
    at io.netty.util.internal.TypeParameterMatcher.find0(TypeParameterMatcher.java:165)
    at io.netty.util.internal.TypeParameterMatcher.find(TypeParameterMatcher.java:93)
    at io.netty.channel.ChannelInboundMessageHandlerAdapter.<init>(ChannelInboundMessageHandlerAdapter.java:63)
    at io.higgs.EventProcessor.<init>(EventProcessor.java:85)
    at io.higgs.boson.BosonClient.newConnectFuture(BosonClient.java:67)
    at io.higgs.HiggsClient.connect(HiggsClient.java:57)
    at io.higgs.boson.BosonClient.connect(BosonClient.java:63)
    at io.higgs.boson.demo.DemoClient.main(DemoClient.java:25)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

Process finished with exit code 1

```

Refactored some code just now to use a generic class as a handler and it results in this.
Why is it necessary for Netty to determine the type parameters of the handler?

Assuming I've got this right, It's also determined that the OS is Android somehow which is incorrect, running Ubuntu 12.10

**Comment by Qix-** [comment]
Sorry to gravedig here, but would incorporating a constructor overload to take a `Class<E>` be suitable? Running into this incredibly vague exception, and I'm not entirely sure why or what I need to do.

Does this mean child classes of `ChannelHandler` cannot be generic? That seems like a serious limitation.

I wouldn't mind having to pass down a `Class<E>` object if a resolution needs to occur. I would speculate most people running into this sort of issue are wrapping Netty anyway (I know I am). That wouldn't be an issue and I assume it would be completely non-breaking.

**Comment by trustin** [comment]
@Qix- I'm not sure what Netty version you are using, but our API has been changed a lot since then. If your comment is about other handler classes than what are mentioned here, please let me know what classes you were referring to. It would be even better if you file a separate issue against 4.1.
