### ISSUE TITLE
NPE in SSL handler after 4.1.77.Final -> 4.1.78.Final update

### ISSUE THREAD

**Issue by doom369** [netty/netty#12473]
```
11:29:02.695 WARN - Failed to remove a handler: io.netty.handler.ssl.SslHandler
java.lang.NullPointerException: Cannot invoke "io.netty.handler.ssl.SslHandler$SslHandlerCoalescingBufferQueue.isEmpty()" because "this.pendingUnencryptedWrites" is null
        at io.netty.handler.ssl.SslHandler.handlerRemoved0(SslHandler.java:677) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:261) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:614) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:572) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:509) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.handler.ssl.SniHandler.replaceHandler(SniHandler.java:134) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.handler.ssl.SniHandler.onLookupComplete(SniHandler.java:114) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.handler.ssl.AbstractSniHandler.onLookupComplete(AbstractSniHandler.java:132) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:190) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:149) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:487) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:385) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[webdash-0.76.3-SNAPSHOT-1,293.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Java:

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

```

**Comment by hyperxpro** [comment]
@normanmaurer @chrisvest PTAL

**Comment by chrisvest** [comment]
Huh, the SslHandler code hasn't changed, so maybe handlerRemoved0 is somehow called twice, or called before handlerAdded?

**Comment by chrisvest** [comment]
@doom369 When you get that log message, you should _also_ get a `ChannelPipelineException` propagating through the pipeline. We tried to remove the handler because we got an exception when we tried to add it, and that's the root cause we need to look at.

**Comment by chrisvest** [comment]
That `ChannelPipelineException` should have a message containing `.handlerAdded() has thrown an exception`

**Comment by normanmaurer** [comment]
@doom369 the only reason for this I can think of is that you might not use the required `netty-tcnative*` version and so `handlerAdded` throws before it was able to init the `pendingUnencryptedWrites`. So I think you need to update the netty-tcnative version on your side. That said I think we also should make this a bit more robust, let me do that.

**Comment by normanmaurer** [comment]
@doom369 see https://github.com/netty/netty/pull/12490

**Comment by doom369** [comment]
> the only reason for this I can think of is that you might not use the required netty-tcnative* version 

That was my first thought, but I didn't have a chance to check. Every time I update netty - I don't know if I have to update tcnative, and if yes - what version should I use. During a single netty release, sometimes few tcnative releases are done, so it's always an unknown thing for me.

> @doom369 see https://github.com/netty/netty/pull/12490

Looks good.

**Comment by normanmaurer** [comment]
> > the only reason for this I can think of is that you might not use the required netty-tcnative* version 
> 
> 
> 
> That was my first thought, but I didn't have a chance to check. Every time I update netty - I don't know if I have to update tcnative, and if yes - what version should I use. During a single netty release, sometimes few tcnative releases are done, so it's always an unknown thing for me.
> 
> 
> 
> > @doom369 see https://github.com/netty/netty/pull/12490
> 
> 
> 
> Looks good.

Just depend on netty-bom ? This will ensure the right version is used
