### ISSUE TITLE
How does netty support OpenSSL PSK

### ISSUE THREAD

**Issue by xiongyue23** [netty/netty#12485]
### Expected behavior
How does netty support OpenSSL PSK？I want SslProvider used SslProvider.OPENSSL，but an error will be reported，IllegalStateException("no X509KeyManager found")。

PSKServerKeyManager implements org.conscrypt.PSKKeyManager

SslProvider sslProvider = SslProvider.JDK;  
    	SslContextBuilder builder = SslContextBuilder.forServer(new PSKServerKeyManager(pskConfig))
                .sslProvider(sslProvider)
                .applicationProtocolConfig(pskConfig.getProtocolConfig())
                .protocols(pskConfig.getProtocols())
                .ciphers(pskConfig.getCiphers());

### Netty version
4.1.63
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_312"
### OS version (e.g. `uname -a`)
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by chrisvest** [comment]
Can you include the stack trace from the error?
Also, can you try the latest version? 4.1.63 is a bit old at this point.

**Comment by xiongyue23** [comment]
First,thank you for your answer. I update  netty version 4.1.77.Final, and used 
netty-tcnative-boringssl-static 2.0.53.Final
conscrypt-openjdk-uber 2.5.2

Code for creating SSLEngine on the server
`public static SSLEngine createTlsPskServerEngine(SocketChannel ch, TlsPskConfiguration pskConfig) throws Exception {
        //SslProvider sslProvider = SslProvider.JDK;
        SslProvider sslProvider = SslProvider.OPENSSL;
        SslContextBuilder builder = SslContextBuilder.forServer(new PSKServerKeyManager(pskConfig))
                .sslProvider(sslProvider)
                .applicationProtocolConfig(pskConfig.getProtocolConfig())
                .protocols(pskConfig.getProtocols())
                .ciphers(pskConfig.getCiphers());
        //builder.sslContextProvider(new OpenSSLProvider());//当sslProvider = SslProvider.JDK时才需要配置ContextProvider
        SslContext sslContext = builder.build();
        SSLEngine sslEngine = sslContext.newEngine(ch.alloc());
        sslEngine.setUseClientMode(false);
        sslEngine.setNeedClientAuth(true);//客户端需要认证
        return sslEngine;
    }`

When I try to establish a TLS-PSK channel, the following error is reported:
`Caused by: java.lang.IllegalStateException: no X509KeyManager found
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.chooseX509KeyManager(ReferenceCountedOpenSslContext.java:666) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.providerFor(ReferenceCountedOpenSslContext.java:989) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:132) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:356) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:336) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:473) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606) ~[netty-handler-4.1.77.Final.jar:4.1.77.Final]
	at com.iot.core.netty.tls.CachedSSLEngineFactory.createTlsPskServerEngine(CachedSSLEngineFactory.java:73) ~[classes/:?]
	at com.iot.core.netty.server.pipeline.TlsPipelineInitializer$1.doPsk(TlsPipelineInitializer.java:117) ~[classes/:?]
	at com.iot.core.netty.server.pipeline.TlsPipelineInitializer$SslCheckHandler.decode(TlsPipelineInitializer.java:274) ~[classes/:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449) ~[netty-codec-4.1.77.Final.jar:4.1.77.Final]
	... 21 more
`

**Comment by hyperxpro** [comment]
Can you show `PSKServerKeyManager` code?

**Comment by xiongyue23** [comment]
This class implements org.conscrypt.PSKKeyManager

```java
/**
 * PSK server key manager.
 */
public class PSKServerKeyManager implements PSKKeyManager {

    private PSKConfiguration configuration;

    public PSKServerKeyManager(PSKConfiguration configuration) {
        this.configuration = configuration;
    }

    @Override
    public String chooseServerKeyIdentityHint(SSLEngine engine) {
        return configuration.getIdentityHint();
    }

    @Override
    public String chooseClientKeyIdentity(String identityHint, SSLEngine engine) {
        return configuration.getIdentitySupplier().get();
        //return configuration.getIdentity();
    }

    @Override
    public SecretKey getKey(String identityHint, String identity, SSLEngine engine) {
        String psk = configuration.getPskFun().apply(identity);
        return new PSKSecretKey(identity, psk);
        //return configuration.getKeyStore().getPSKSecretKey(identity);
    }


    @Override
    public String chooseServerKeyIdentityHint(Socket socket) {
        return configuration.getIdentityHint();
    }

    @Override
    public String chooseClientKeyIdentity(String identityHint, Socket socket) {
        return configuration.getIdentitySupplier().get();
        //return configuration.getIdentity();
    }

    @Override
    public SecretKey getKey(String identityHint, String identity, Socket socket) {
        String psk = configuration.getPskFun().apply(identity);
        return new PSKSecretKey(psk, identity);
        //return configuration.getKeyStore().getPSKSecretKey(identity);
    }


}
```

**Comment by hyperxpro** [comment]
This is not supported if I'm correct. SslContext expects `X509KeyManager` or it's extensions.

**Comment by xiongyue23** [comment]
> This is not supported if I'm correct. SslContext expects `X509KeyManager` or it's extensions.

How to make netty support OpenSSL PSK ？

**Comment by hyperxpro** [comment]
You have to extend `X509KeyManager` and make it work internally with PSK.

**Comment by xiongyue23** [comment]
Thank you very much.
