### ISSUE TITLE
Intermittent DNS issue connecting to read/write from AWS Redis cluster

### ISSUE THREAD

**Issue by prem1er** [netty/netty#12619]
### Expected behavior
Successfully able to query and add data to a Redis cache in AWS. 

### Actual behavior
Using Spring ReactiveRedisTemplate to query for data from a Redis cache there is an exception thrown from Netty regarding the DNS entry of the server. 

```
Unable to decode DNS response: UDP [[id: 0xddd128d9]] io.netty.handler.codec.CorruptedFrameException: Unable to decode response
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:62)
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:31)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(2) exceeds writerIndex(0): PooledUnsafeDirectByteBuf(ridx: 0, widx: 0, cap: 4096)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:749)
	at io.netty.buffer.AbstractByteBuf.readUnsignedShort(AbstractByteBuf.java:765)
	at io.netty.handler.codec.dns.DnsResponseDecoder.decode(DnsResponseDecoder.java:37)
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decodeResponse(DatagramDnsResponseDecoder.java:67)
	at io.netty.resolver.dns.DnsNameResolver$1.decodeResponse(DnsNameResolver.java:208)
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:60)
	... 18 more
```

### Steps to reproduce
Redis Template Configuration 
```
@Bean
    public ReactiveRedisTemplate<String, Object> redisTemplate() {
        RedisSerializer<String> serializer = new StringRedisSerializer();
        JdkSerializationRedisSerializer jdkSerializer = new JdkSerializationRedisSerializer();

        RedisSerializationContext<String, Object> serializationContext = RedisSerializationContext
                .<String, Object> newSerializationContext().key(serializer).value(jdkSerializer).hashKey(serializer)
                .hashValue(jdkSerializer).build();

        ReactiveRedisTemplate<String, Object> template = new ReactiveRedisTemplate<>(
                redisConnectionFactory(redisHostname, redisPort), serializationContext);

        return template;
    }
```

Connection Configuration 
```
@Bean
    public ReactiveRedisConnectionFactory redisConnectionFactory(String hostname, int port) {
        RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration(hostname, port);
        redisStandaloneConfiguration.setPassword(RedisPassword.of(redisAuthToken));

        LettuceConnectionFactory factory = new LettuceConnectionFactory(redisStandaloneConfiguration,
                LettuceClientConfiguration.builder().useSsl().disablePeerVerification().build());

        return factory;
    }
```

Connection Code
``` 
redisTemplate.opsForValue().set(
MessageFormat.format(CACHE_KEYS.get(CACHENAME_DEVEXGATEWAY_TOKEN_PASSWORD),
username, clientId), token,Duration.ofSeconds(getCacheExpiry(CACHENAME_DEVEXGATEWAY_TOKEN_PASSWORD)))
```

### Netty version
4.1.76.Final

### JVM version (e.g. `java -version`)
Open JDK 1.8_322

### OS version (e.g. `uname -a`)
MacOS - Darwin 88e9fe7e5c3c 20.6.0 Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64 x86_64

**Comment by hyperxpro** [comment]
This issue should be filed with Spring team.

**Comment by prem1er** [comment]
Hi thanks for the update. I can post there. Is there a reason it should go to Spring, just so I have more context? The stack trace is from netty packages.

**Comment by prem1er** [comment]
Is it simply because I'm using the Spring Data Redis when the issue occurred

**Comment by hyperxpro** [comment]
So Spring is trying to decode something which is not valid for DNS response as per Netty.

So Spring Data have to handle this.

**Comment by chrisvest** [comment]
The DNS server sent an empty datagram packet, and the exception comes from trying to decode a DNS response out of that.
We can't really do anything about that in Netty. Sounds like it's just AWS being weird from time to time.

**Comment by prem1er** [comment]
Hi thank you. I created an issue on Spring https://github.com/spring-projects/spring-data-redis/issues/2373 and they told me the problem is in Netty and to raise something here. Not sure how to proceed. TIA

**Comment by mp911de** [comment]
Neither Spring Data Redis doesn't configure any netty components. The only thing that the Lettuce driver configured is a `AddressResolverGroup` via https://github.com/lettuce-io/lettuce-core/blob/main/src/main/java/io/lettuce/core/resource/AddressResolverGroupProvider.java

That one seems not to have any means to cause the mentioned buffer underrun.

**Comment by chrisvest** [comment]
You can try to use packet capture on the host to either confirm or falsify that we get empty UDP packets as response from the DNS server. If the packets are originally non-empty, then their associated netty buffers become truncated, or something like that, somewhere. The stack trace says there's nothing else in the pipeline, though, so that's why I don't think this is the case.

**Comment by prem1er** [comment]
Thank you. I will try to capture the network packets when this issue occurs. I will mention one other thing. We have used the same Redis cluster in AWS for quite some time now and just recently switched from Spring MVC/Tomcat to Webflux/Netty/Reactive Redis Template. It was only after switching did we see this problem.
