### ISSUE TITLE
`MixedFileUpload` has inconsistent `ReferenceCounted` behavior when migrating from memory to disk

### ISSUE THREAD

**Issue by yawkat** [netty/netty#12627]
I can work on a patch for this. My proposed solution is to make `MixedFileUpload` use its own ref counting, like `MemoryFileUpload` already does. However this would be a big change to `MixedFileUpload` so I'm not sure about its compat implications.

---

### Expected behavior

`MixedFileUpload` should behave like a normal `ReferenceCounted` object: Every retain should have a corresponding release that should succeed.

### Actual behavior

Migration of `MixedFileUpload` from memory to disk, when the memory limit is reached, essentially resets the `refCnt` to 1, so if there were more `retain` calls before, their `release` calls will fail.

### Steps to reproduce

Run the test case below. The test case passes if migration is not triggered, e.g. by removing the `addContent` line, or by changing the `limitSize` parameter to a higher value. If migration is triggered, the test case fails with:

```
io.netty.util.IllegalReferenceCountException: refCnt: 1, decrement: 2
	at app//io.netty.util.internal.ReferenceCountUpdater.retryRelease0(ReferenceCountUpdater.java:183)
	at app//io.netty.util.internal.ReferenceCountUpdater.nonFinalRelease0(ReferenceCountUpdater.java:167)
	at app//io.netty.util.internal.ReferenceCountUpdater.release(ReferenceCountUpdater.java:154)
	at app//io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:81)
	at app//io.netty.handler.codec.http.multipart.MixedFileUpload.release(MixedFileUpload.java:370)
	at app//com.example.MixedFileUploadTest.multipleRetain(MixedFileUploadTest.java:48)
...
```

### Minimal yet complete reproducer code (or URL to code)

```java
package com.example;

import io.netty.buffer.Unpooled;
import io.netty.handler.codec.http.multipart.MixedFileUpload;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

public class MixedFileUploadTest {
    private Path tmpDir;

    @BeforeEach
    public void setUp() throws IOException {
        tmpDir = Files.createTempDirectory("MixedFileUploadTest");
    }

    @AfterEach
    public void tearDown() throws IOException {
        Files.list(tmpDir).forEach(path -> {
            try {
                Files.delete(path);
            } catch (IOException e) {
                throw new UncheckedIOException(e);
            }
        });
        Files.delete(tmpDir);
    }

    @Test
    public void multipleRetain() throws IOException {
        MixedFileUpload mixedFileUpload = new MixedFileUpload(
                "foo", "foo", "foo", "foo",
                StandardCharsets.UTF_8,
                -1, 2, tmpDir.toString(), false
        );

        mixedFileUpload.retain();

        // trigger moving to disk
        mixedFileUpload.addContent(Unpooled.wrappedBuffer(new byte[5]), true);

        mixedFileUpload.release(2);
    }
}
```

### Netty version

4.1.77.Final

### JVM version (e.g. `java -version`)

```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

```
Linux yawkat-oracle 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by yawkat** [comment]
MixedAttribute probably has the same issue

**Comment by chrisvest** [comment]
Oof! Yes, they should maintain their own independent reference counts, and in turn the references they have to their internal resources should only count as one reference.

I'll be happy to review a PR that fixes this!
