### ISSUE TITLE
Direct buffers not supported when setting up SSL handler channel for Elasticsearch cluster

### ISSUE THREAD

**Issue by oreoluwa-xyz** [netty/netty#12643]
Hello everyone,

I am working on a project to setup an SSL handler channel for an elasticsearch cluster.
Everything works fine except in a few cases when a user requests a large amount of data from the cluster.
Smaller queries respond quite well, but when the response is large, the response to the user truncates without sending a portion of the data back, and we see the error below in our logs.

[2022-07-25T16:48:18,819][INFO ][c.l.m.s.SSLNettyHttpServerTransport] [<hostname>] Error in channel handler: java.lang.IllegalArgumentException: promise already done: DefaultChannelPromise@15a2257(failure: java.lang.UnsupportedOperationException: Direct buffers not supported)
java.lang.IllegalArgumentException: promise already done: DefaultChannelPromise@15a2257(failure: java.lang.UnsupportedOperationException: Direct buffers not supported)
        at io.netty.channel.AbstractChannelHandlerContext.isNotValidPromise(AbstractChannelHandlerContext.java:891) ~
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:773) 
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701) 
        at io.netty.handler.ssl.SslHandler.finishWrap(SslHandler.java:899) ~
        at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:885) ~
        at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:797) ~
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:778) ~
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) 
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) 
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) 
        at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127) 
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) 
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) 
        at io.netty.channel.AbstractChannelHandlerContext.access$2100(AbstractChannelHandlerContext.java:56) 
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1150) 
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073) 
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) 
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) 
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) 
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) 
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) 
        at java.lang.Thread.run(Thread.java:834) [?:?]

Any help in resolving this will be greatly appreciated.

### Netty version

Netty 4.1.41.Final

**Comment by chrisvest** [comment]
`4.1.41.Final` is pretty old. Can you try a more recent version? It would also be helpful if you can change your code to log the stack trace of that `java.lang.UnsupportedOperationException` (the promise `cause()`).

**Comment by oreoluwa-xyz** [comment]
@chrisvest Using a more recent version worked, thanks.
For my case Netty 4.1.49.Final was required.
