### ISSUE TITLE
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 7449083911, max: 7460618240)

### ISSUE THREAD

**Issue by silencewen** [netty/netty#12779]
### Expected behavior
normal running

2G of heap memory, 2G of off-heap memory

### Actual behavior
In the case of normal requests everything is fine without oom, but when we have a large batch of requests (request body is a base64 string) the memory usage is incrementing until there is an OOM
error Info：

o.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 7449083911, max: 7460618240)

detail

io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 7449083911, max: 7460618240)
at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
at io.netty.buffer.PoolArena.allocate(PoolArena.java:226)
at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
at java.lang.Thread.run(Thread.java:748)
### Steps to reproduce
Requests with base64 strings in the request body are executed 222 times every half hour, with an OOM error message after a few hours.
<img width="743" alt="image" src="https://user-images.githubusercontent.com/30278151/188875917-2edd5e75-93ca-4376-9c1d-9e3244bb0dbf.png">

### Minimal yet complete reproducer code (or URL to code)
I have used DataBufferUtils.release(dataBuffer) to release the databuff object after the request and wrote a filter to release the databuffer object again at the end, but it doesn't seem to work.

@Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        ServerHttpResponse response = exchange.getResponse();

        ReferenceCountUtil.safeRelease(exchange.getRequest().getBody());
        DataBufferFactory bufferFactory = response.bufferFactory();
        ReferenceCountUtil.safeRelease(bufferFactory);

        return chain.filter(exchange);
    }
### JVM version (e.g. `java -version`)
JDK 8

### OS version (e.g. `uname -a`)
Linux version 3.10.0-1160.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )

SO，what should I do.

**Comment by normanmaurer** [comment]
We will need more info... Also enable the leak detector to see if there are any leaks

**Comment by silencewen** [comment]
netty version：4.1.48.final
![image](https://user-images.githubusercontent.com/30278151/189281502-3e0c4076-9e33-48fe-9d4b-b56af642084f.png)

**Comment by chrisvest** [comment]
Your netty version is pretty old. I recommend upgrading to a more recent version before investigating this further.

**Comment by silencewen** [comment]
> 

ok，thank you for your suggestion
let me try update netty version.

**Comment by chrisvest** [comment]
Guessing this got resolved. Otherwise we can reopen.

**Comment by 0x822a5b87** [comment]
> > 
> 
> ok，thank you for your suggestion let me try update netty version.

Did upgrading netty solve this problem? If so, can you tell me which version you upgraded to? thanks.

**Comment by caozhongyang** [comment]
> > 
> 
> ok，thank you for your suggestion let me try update netty version.

Did upgrading netty solve this problem? If so, can you tell me which version you upgraded to? thanks.
