### ISSUE TITLE
NPE with Paranoid leak detector and using a ByteProcessor on a CompositeBuffer of CompositeBuffer

### ISSUE THREAD

**Issue by mederel** [netty/netty#12787]
### Expected behavior

No exception

### Actual behavior

Getting a NullPointerException

```
Caused by: java.lang.NullPointerException
    at io.netty.buffer.CompositeByteBuf.toComponentIndex0(CompositeByteBuf.java:930)
    at io.netty.buffer.CompositeByteBuf.forEachByteAsc0(CompositeByteBuf.java:672)
    at io.netty.buffer.CompositeByteBuf.forEachByteAsc0(CompositeByteBuf.java:682)
    at io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1281)
    at io.netty.buffer.WrappedCompositeByteBuf.forEachByte(WrappedCompositeByteBuf.java:393)
    at io.netty.buffer.AdvancedLeakAwareCompositeByteBuf.forEachByte(AdvancedLeakAwareCompositeByteBuf.java:657)
```

### Steps to reproduce

* set ResourceLeakDetector in Paranoid mode
* create a CompositeBuffer of CompositeBuffer of Buffers
* run a ByteProcessor on the ByteBuf

### Minimal yet complete reproducer code (or URL to code)

[netty-paranoid-leak.zip](https://github.com/netty/netty/files/9535586/netty-paranoid-leak.zip)

### Netty version

4.1.81.Final

### JVM version (e.g. `java -version`)

11.0.16

### OS version (e.g. `uname -a`)

Ubuntu 20.04.5 LTS

**Comment by chrisvest** [comment]
Thanks for the report.
