### ISSUE TITLE
Chrome/Firefox send `upgrade-insecure-requests` header

### ISSUE THREAD

**Issue by glennosss** [netty/netty#12798]
https://github.com/netty/netty/pull/12755 is unfortunately breaking Chrome and Firefox which both (rightly or wrongly) send the `upgrade-insecure-requests` header:

```
[DEBUG|2022-09-13 10:23:29.419|netty-worker1 ||io.netty.handler.codec.http2.Http2FrameCodec] Stream exception thrown for unknown stream 1.
io.netty.handler.codec.http2.Http2Exception$StreamException: Illegal connection-specific header 'upgrade-insecure-requests' encountered.
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:153)
	at io.netty.handler.codec.http2.HpackDecoder.validate(HpackDecoder.java:412)
	at io.netty.handler.codec.http2.HpackDecoder.access$000(HpackDecoder.java:56)
	at io.netty.handler.codec.http2.HpackDecoder$Http2HeadersSink.appendToHeaderList(HpackDecoder.java:639)
	at io.netty.handler.codec.http2.HpackDecoder.insertHeader(HpackDecoder.java:506)
	at io.netty.handler.codec.http2.HpackDecoder.decode(HpackDecoder.java:294)
	at io.netty.handler.codec.http2.HpackDecoder.decode(HpackDecoder.java:131)
```

With Netty 4.1.80 and below I was able to run with `validateHeaders(true)` (the default). However with Netty 4.1.81 the only work around I've found is;
```
        Http2FrameCodecBuilder builder = Http2FrameCodecBuilder.forServer();
        builder.validateHeaders(false);
```

@chrisvest My thanks for implementing these extra validations. And my thanks too for helping me investigate this. I am running with a particularly restrictive 'Content-Security-Policy' header - but that doesn't seem to be related as the exception above occurs well before a cache-clean web-browser sends the `upgrade-insecure-requests` header.

**Comment by chrisvest** [comment]
Just verified that the validation is fine for Safari but fails with Firefox.
