### ISSUE TITLE
DNS resolving issue for AWS Elsticache nodes

### ISSUE THREAD

**Issue by Frank591** [netty/netty#12842]
### Actual behavior
We use Redisson client to work with to several big Elasticache clusters(up to 150 nodes). Under the hood, Redisson uses netty for work with DNS resolving. 
We get a lot of errors like this:
`io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'test-elasticache-cluster-0003-002.test-eslaticache-cluster.nfbjaw.euw1.cache.amazonaws.com' and search domain query for configured domains failed as well: [eu-west-1.compute.internal]
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
	at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:467)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:240)
	at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:192)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/*.*.*.*:53] query via UDP timed out after 5000 milliseconds (no stack trace available)`
The more nodes in a cluster - the more errors we get. 
Firstly we think that we faced some internal AWS limits, but AWS support checked it and didn't confirm reaching any limits on their side. Potentially the problem can be in netty DNS resolving mechanism. 
I searched open issues in this repository with similar problems and this one looks pretty similar https://github.com/netty/netty/issues/11993

### Expected behavior
DNS names of elasticache nodes should be resolved correctly. 

### Steps to reproduce

Collegue of mine investigated the hypothesis with the problem in netty DNS resolving process and created a simple test app based on Redisson [DNSMonitor](https://github.com/redisson/redisson/blob/master/redisson/src/main/java/org/redisson/connection/DNSMonitor.java) to reproduce the problem. This class uses netty for DNS resolving and it allowed us to reproduce the problem. 

`
package com.test;

import io.netty.channel.EventLoop;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioDatagramChannel;
import io.netty.handler.logging.LogLevel;
import io.netty.resolver.AddressResolver;
import io.netty.resolver.dns.DefaultDnsCache;
import io.netty.resolver.dns.DefaultDnsCnameCache;
import io.netty.resolver.dns.DnsAddressResolverGroup;
import io.netty.resolver.dns.DnsNameResolverBuilder;
import io.netty.resolver.dns.DnsServerAddressStreamProviders;
import io.netty.resolver.dns.LoggingDnsQueryLifeCycleObserverFactory;
import io.netty.util.concurrent.Future;
import io.netty.util.concurrent.FutureListener;
import java.net.InetSocketAddress;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.concurrent.CompletableFuture;

import java.util.concurrent.TimeUnit;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import picocli.CommandLine;

public class TestDNS {
    private static final Logger log = LoggerFactory.getLogger(TestDNS.class);
    // possibility of timeout increases with high resolver count
    private static final int MAX_RESOLVER_COUNT =  Runtime.getRuntime().availableProcessors() * 4;

    private static final int MAX_THREAD_COUNT =  Runtime.getRuntime().availableProcessors() * 4;

    private static final int MAX_MONITOR_COUNT = Runtime.getRuntime().availableProcessors() * 4;
    private static final int MONITOR_INTERVAL_SECOND = 3;
    private static final int MIN_TTL = 15;
    private static final int MAX_TTL = 300;
    private static final int NEGATIVE_TTL = 15;

    public static void main(String[] args)  {
        Parameters parameters = new Parameters();
        new CommandLine(parameters).parseArgs(args);
        NioEventLoopGroup defaultEventLoopGroup = new NioEventLoopGroup(MAX_THREAD_COUNT);
        NioEventLoopGroup nioGroup = new NioEventLoopGroup(MAX_THREAD_COUNT);
        AddressResolver<InetSocketAddress>[] arr = new AddressResolver[MAX_RESOLVER_COUNT];
        DefaultDnsCnameCache defaultDnsCnameCache = new DefaultDnsCnameCache(MIN_TTL, MAX_TTL);
        DefaultDnsCache defaultDnsCache = new DefaultDnsCache(MIN_TTL, MAX_TTL, NEGATIVE_TTL);
        for (int i = 0; i < MAX_RESOLVER_COUNT; i++) {
            arr[i] = createResolver(defaultEventLoopGroup, nioGroup, defaultDnsCache, defaultDnsCnameCache);
        }

        if (parameters.slave) {
            log.info("Slave dns check starting");
            Map<Host, InetSocketAddress> slaves = getSlaves();
            for (Map.Entry<Host, InetSocketAddress> entry : slaves.entrySet()) {
                Future<InetSocketAddress> resolveFuture = arr[0].resolve(InetSocketAddress.createUnresolved(entry.getKey().host(), entry.getKey().port()));
                resolveFuture.syncUninterruptibly();
                slaves.put(entry.getKey(), resolveFuture.getNow());
            }
            for (int i = 0; i < MAX_MONITOR_COUNT; i++) {
                // Pick different resolver
                scheduleMonitorSlaves(defaultEventLoopGroup, arr[(i+MAX_MONITOR_COUNT) % arr.length], slaves);
            }
        }
        if (parameters.master) {
            log.info("Master dns check starting");
            scheduleMonitorMaster(defaultEventLoopGroup, arr[0], new Host("clustercfg.production-game-objects.nfbjaw.euw1.cache.amazonaws.com", 6379));
        }

        System.out.println("Press any key for exit");
        Scanner userInput = new Scanner(System.in);
        if (!userInput.hasNext()) ;
        System.out.println("Application will stop soon");
    }

    private static AddressResolver<InetSocketAddress> createResolver(NioEventLoopGroup defaultEventLoopGroup, NioEventLoopGroup group, DefaultDnsCache defaultDnsCache, DefaultDnsCnameCache defaultDnsCnameCache) {
        final EventLoop loop = group.next();
        DnsNameResolverBuilder builder = new DnsNameResolverBuilder()
                .eventLoop(loop).channelType(NioDatagramChannel.class).queryTimeoutMillis(5000)
                .dnsQueryLifecycleObserverFactory(new LoggingDnsQueryLifeCycleObserverFactory(LogLevel.INFO))
                .nameServerProvider(DnsServerAddressStreamProviders.platformDefault()).resolveCache(defaultDnsCache).cnameCache(defaultDnsCnameCache);
        DnsAddressResolverGroup resolverGroup = new DnsAddressResolverGroup(builder);
        return resolverGroup.getResolver(defaultEventLoopGroup.next());
    }

    private static void scheduleMonitorSlaves(NioEventLoopGroup defaultEventLoopGroup, AddressResolver<InetSocketAddress> resolver, Map<Host, InetSocketAddress> slaves) {
        defaultEventLoopGroup.schedule(() -> {
            CompletableFuture<Void> future = monitorSlaves(resolver, slaves);
            future.whenComplete((r,e) -> scheduleMonitorSlaves(defaultEventLoopGroup, resolver, slaves));
        }, MONITOR_INTERVAL_SECOND, TimeUnit.SECONDS);
    }

    private static void scheduleMonitorMaster(NioEventLoopGroup defaultEventLoopGroup, AddressResolver<InetSocketAddress> resolver, Host master) {
        defaultEventLoopGroup.schedule(() -> {
            CompletableFuture<Void> future = monitorMaster(resolver, master);
            future.whenComplete((r,e) -> scheduleMonitorMaster(defaultEventLoopGroup, resolver, master));
        }, MONITOR_INTERVAL_SECOND, TimeUnit.SECONDS);
    }

    private static CompletableFuture<Void> monitorMaster(AddressResolver<InetSocketAddress> resolver, Host master) {
        log.info("Monitor master is working");
        CompletableFuture<Void> promise = new CompletableFuture<>();
        Future<List<InetSocketAddress>> allNodes = resolver.resolveAll(InetSocketAddress.createUnresolved(master.host(), master.port()));
        allNodes.addListener(new FutureListener<List<InetSocketAddress>>() {
            @Override
            public void operationComplete(Future<List<InetSocketAddress>> future) throws Exception {
                if (!future.isSuccess()) {
                    promise.complete(null);
                    log.error("Master monitor err=", future.cause());
                    return;
                }
                List<InetSocketAddress> nodes = new ArrayList<>();
                for (InetSocketAddress address : future.getNow()) {
                    nodes.add(address);
                }
                log.info("Resolve ALL node size is {}", nodes.size());
                promise.complete(null);
            }
        });
        return CompletableFuture.allOf(promise);
    }

    private static CompletableFuture<Void> monitorSlaves(AddressResolver<InetSocketAddress> resolver, Map<Host, InetSocketAddress> slaves) {
        log.info("Monitor slaves is working");
        List<CompletableFuture<Void>> futures = new ArrayList<>();
        for (Map.Entry<Host, InetSocketAddress> entry : slaves.entrySet()) {
            CompletableFuture<Void> promise = new CompletableFuture<>();
            futures.add(promise);

            log.debug("Request sent to resolve ip address for slave host: {}", entry.getKey().host());

            Future<InetSocketAddress> resolveFuture = resolver.resolve(InetSocketAddress.createUnresolved(entry.getKey().host(), entry.getKey().port()));
            resolveFuture.addListener((FutureListener<InetSocketAddress>) future -> {
                if (!future.isSuccess()) {
                    log.error("Unable to resolve " + entry.getKey().host(), future.cause());
                    promise.complete(null);
                    return;
                }

                log.debug("Resolved ip: {} for slave host: {}", future.getNow().getAddress(), entry.getKey().host());

                InetSocketAddress currentSlaveAddr = entry.getValue();
                InetSocketAddress newSlaveAddr = future.getNow();
                if (!newSlaveAddr.getAddress().equals(currentSlaveAddr.getAddress())) {
                    log.info("Detected DNS change. Slave {} has changed ip from {} to {}", entry.getKey().host(), currentSlaveAddr.getAddress().getHostAddress(), newSlaveAddr.getAddress().getHostAddress());
                }
                promise.complete(null);
            });
        }
        return CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]));
    }

    private static Map<Host, InetSocketAddress> getSlaves() {
        Map<Host, InetSocketAddress> slaves = new HashMap<>();
      // add 44 nodes of real elsaticache cluster 
        return slaves;

    }
}
`

### Netty version
4.1.75

### JVM version (e.g. `java -version`)
 java-17-amazon-corretto-jdk_17.0.3.6-1_amd64

### OS version (e.g. `uname -a`)
ubuntu-bionic-18.04-amd64

**Comment by normanmaurer** [comment]
I will have a look

**Comment by Frank591** [comment]
@normanmaurer , pls let me know if you require any additional information from my side for investigation

**Comment by mrniko** [comment]
@normanmaurer 

Here is the solution I use to resolve the issue https://github.com/redisson/redisson/blob/2d83ebdf64bde8793b8c3b24be81ad23e72119d5/redisson/src/main/java/org/redisson/connection/SequentialDnsAddressResolverFactory.java

**Comment by normanmaurer** [comment]
@mrniko can you be more explicit on what exactly fixes it ? Is it about to limit the concurrent DNS queries ?

**Comment by trustin** [comment]
Let me take a look early next week unless someone does before I do.

**Comment by tommyulfsparre** [comment]
We are hitting the same or a similar issue replacing a DNS resolver with Netty DNS. Comparing the two resolver it seems like Netty DNS will reuse a local source port for the UDP socket for multiple lookups:  

```
11:32:09.731587 IP 172.21.54.99.59908 > 10.1.0.1.53: 20347+ A? test1.example.com. (58)
11:32:09.732138 IP 172.21.54.99.59908 > 10.1.0.1.53: 54688+ A? test2.example.com. (58)
```

This sound like Netty is setting `SO_REUSEADDR` on the UDP socket but the only reference I have found is here: [DnsNameResolver.java](https://github.com/netty/netty/blob/9cd94547d0211c04b610878e5e267c8de2342b97/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolver.java#L1319) which is for handling DNS over TCP?  Not claiming this to be the issue but I wanted to see if it makes a difference not setting `SO_REUSEADDR` here.

**Comment by trustin** [comment]
I sent out #13014 that adds a new construct called `ConcurrencyLimit` which abstracts how we should limit concurrent actions, with one simple implementation that's similar to @mrniko's `AsyncSemaphore`. Please let me know what you think. Once approved and merged, I'll send out a follow-up PR that uses `ConcurrencyLimit` for limiting DNS queries.

**Comment by tommyulfsparre** [comment]
@trustin this seem to be a good thing in general to support but im curious; would this be required to not get timeouts when doing a large amount of concurrent DNS request with Netty?

**Comment by trustin** [comment]
@tommyulfsparre I think we have two problems that need to be dealt with. One is to rate-limit outgoing DNS queries as @mrniko suggested, and the other is using more than one source port as you suggested. I'm currently looking into the former at the moment, although we also are interested in yours.

Did you make sure using different source ports (e.g. using more than one resolver to distribute the queries across multiple ports) actually fixes the problem in your case?

**Comment by tommyulfsparre** [comment]
@trustin Agree! 

> Did you make sure using different source ports (e.g. using more than one resolver to distribute the queries across multiple ports) actually fixes the problem in your case

No I haven't found a way to make the Netty `DnsNameResolver` use multiple ports instead of using multiple resolvers as im not familiar enough with the Netty codebase yet. Will see if I manage to figure it out and will report back unless someone else does it before me.

**Comment by trustin** [comment]
A few days ago, @normanmaurer told me he found an issue where the resolve sends excessive number of DNS queries in a certain case, which means we may be able to fix this issue without introducing rate limiter. Did you have a chance to dig deeper since then, Norman?

**Comment by normanmaurer** [comment]
@trustin it was actually just one extra query for a CNAME chain: https://github.com/netty/netty/pull/13150

**Comment by jgaoIXL** [comment]
Hi, is there a timeline on when this will be fixed?

**Comment by normanmaurer** [comment]
If this still happens please share some more details

**Comment by jgaoIXL** [comment]
> If this still happens please share some more details
I just realized there is this PR https://github.com/netty/netty/pull/13150, sorry just want to clarify if that is the fix for this issue, because I saw this issue is still open and was confused.

**Comment by jgaoIXL** [comment]
Hi, @normanmaurer, yes, this is still happening in our production, we have a 14 shards elasticache cluster in cluster mode using r5a.8xlarge node. And we keep getting this exception in Redisson client. So I am wondering if there is already a fix like the one you mentioned [#13150 ](https://github.com/netty/netty/pull/13150)? If not, what is the timeline to fix this issue?
`Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'ixldev-cluster-0004-002.ixldev-cluster.cqc1cq.usw2.cache.amazonaws.com' and search domain query for configured domains failed as well: [ixl.dev]
    at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1069)
    at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1022)
    at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418)
    at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:651)
    at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:66)
    at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:478)
    at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
    at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
    at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
    at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
    at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:625)
    at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:105)
    at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:232)
    at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:224)
    at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1306)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
    at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by mrniko** [comment]
@jgaoIXL 

Did you try to define `addressResolverGroupFactory = SequentialDnsAddressResolverFactory(1)` ?

**Comment by jgaoIXL** [comment]
> @jgaoIXL
> 
> Did you try to define `addressResolverGroupFactory = new SequentialDnsAddressResolverFactory(1)` in Redisson configuration ?

Yes, I did, and it did not solve the issue completely, I also experimented with cocurrency level of 2, also did not help.

**Comment by kmsbmadhan** [comment]
Is there any update fixing this issue, we are seeing intermittent errors in logs as well

**Comment by Delice0** [comment]
Any updates on this?

**Comment by shichanglin5** [comment]
same issue，there is no problem in testing dns resolution through nslookup:
```log
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'arex-demo-arex-redis.arex-demo.svc.cluster.local' [A(1), AAAA(28)] and search domain query for configured domains failed as well: [arex-demo.svc.cluster.local, svc.cluster.local, cluster.local]
	... 56 more
```

**Comment by rehevkor5** [comment]
> The underlying issue is with EKS ... API Priority and Fairness

@doctorpangloss I am curious about the information you saw that led you to that conclusion?

I have encountered this issue in an AWS Elasticache client within an EKS cluster, but I did not see any rejected or queued requests in the Kube API flowcontrol metrics during that time - and in particular not any rejected/queued requests in the priority level that we've configured CoreDNS to use.

In addition, based on our configuration of CoreDNS and ndots, I would expect CoreDNS to recognize the cluster DNS name as fully qualified immediately, and fall through without querying KubeAPI... but I could be mistaken about how that works. And perhaps your CoreDNS config is different than mine.

**Comment by kfko** [comment]
any update on this? We are experiencing the same issue. What is curious it recently happened on two different redis clusters at the same time and only on some pods.
