### ISSUE TITLE
javax.net.ssl.SSLException: java.io.EOFException: Read error

### ISSUE THREAD

**Issue by ragner** [netty/netty#12874]
I am testing  https://github.com/adamfisk/LittleProxy plus https://github.com/ganskef/LittleProxy-mitm with Netty 4.1.82
and the "tls handshake"/"https request" looks working but I am always getting  java.io.EOFException: Read error

I have found a similar issue at: https://github.com/koush/AndroidAsync/issues/594

### Netty version 
4.1.82.Final

### JVM version (e.g. `java -version`)
openjdk 11.0.12 2021-07-20

### OS version (e.g. `uname -a`)
Android 8.1

E/o.l.p.i.ClientToProxyConnection: [LittleProxy-0-ClientToProxyWorker-4] (AWAITING_INITIAL) [id: 0x89f3efce, L:::/:::8182 ! R:/127.0.0.1:42551]: Caught an exception on ClientToProxyConnectionio.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: java.io.EOFException: Read error
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.net.ssl.SSLException: java.io.EOFException: Read error
        at com.android.org.conscrypt.SSLUtils.toSSLException(SSLUtils.java:295)
        at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1093)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:851)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:678)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:644)
        at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:296)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1343)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
    	... 16 common frames omitted
    Caused by: java.io.EOFException: Read error
        at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
        at com.android.org.conscrypt.SslWrapper.readDirectByteBuffer(SslWrapper.java:492)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1052)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataHeap(ConscryptEngine.java:1072)
        at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1044)
        at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:805)
    	... 24 common frames omitted

**Comment by Leonardo-Fischer** [comment]
Is there any updates about this issue?

**Comment by normanmaurer** [comment]
You need to ask the conscrypt developers
