### ISSUE TITLE
Sometimes (not always) decoder.hasnext() throws EndOfDataDecoderException

### ISSUE THREAD

**Issue by jhpark0912** [netty/netty#12957]
I upload files with netty server but, sometimes failed to upload. 
When failed to upload, I could always check the same log.

io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$EndOfDataDecoderException: null
           at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.hasNext(HttpPostMultipartRequestDecoder.java:366) ~[netty-all-4.0.24.Final.jar:4.0.24.Final]
           at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.hasNext(HttpPostRequestDecoder.java:241) ~[netty-all-4.0.24.Final.jar:4.0.24.Final]
           at UploadHandler.readChunk(UploadHandler.java:104) 
           at UploadHandler.channelRead0(UploadHandler.java:79) 
In   [  public boolean hasNext() ](https://github.com/netty/netty/blob/be5b5a3b29806429103c088555b5e211efe9985f/codec-http/src/main/java/io/netty/handler/codec/http/multipart/HttpPostMultipartRequestDecoder.java#L351), it says, "OK except if end of list". I think netty sever has not read all the data yet, but, it tries to read some chunk data so it throws exception.

I'll try to update netty to 4.0.56.Final and try catch for exception. It will be work? or any solution for this exception?

### Netty version
netty-4.0.24.Final

### JVM version (e.g. `java -version`)
jdk_1.8.0_65

### OS version (e.g. `uname -a`)
windows server 2012

**Comment by hyperxpro** [comment]
Netty 4.0.X has reached EPL. Please upgrade to latest 4.1.X version.

**Comment by jhpark0912** [comment]
I want to upgrade 4.1.x but, it has aws upload issues. So, I used this version, and upgrade 4.0.56. I'll find another way. thx.
