### ISSUE TITLE
Suffering from memory leaks due "org.jboss.netty.channel.socket.nio.NioAcceptedSocketChannel"

### ISSUE THREAD

**Issue by jcornejoga** [netty/netty#12963]
### Expected behavior

Netty attending requests with no issues.

### Actual behavior

After some requests we're getting the error "java.lang.OutOfMemoryError: native memory exhausted"

Here is a portion of the stack trace:

java.lang.OutOfMemoryError: native memory exhausted
        at sun.misc.Unsafe.allocateDBBMemory(Native Method)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:253)
        at sun.nio.ch.IOUtil.write(IOUtil.java:70)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:485)
        at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$UnpooledSendBuffer.transferTo(SocketSendBufferPool.java:203)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.write0(AbstractNioWorker.java:201)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.writeFromUserCode(AbstractNioWorker.java:146)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:99)
        at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:779)
        at org.jboss.netty.handler.logging.LoggingHandler.handleDownstream(LoggingHandler.java:338)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
        at org.jboss.netty.channel.Channels.write(Channels.java:725)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)

### Steps to reproduce

We are using a ChannelPipeline with a netstring encoder (extends OneToOneEncoder)  and a netstring decoder (extends ReplayingDecoder) and our requests handler (extends SimpleChannelHandler).

We're hardcoding the response for now to respond with 500,000 strings, each string is around 80 characters length. We're doing this to reproduce the issue. 

We're sending one request at a time. After around 10 requests served successfully, we get the mentioned error. The java application continues to work fine but if we repeat the request it fails everytime on the same place.

### Minimal yet complete reproducer code (or URL to code)

Configuring ServerBootstrap:

this.channelFactory = new NioServerSocketChannelFactory(
                            Executors.newCachedThreadPool(new ThreadFactoryBuilder()
                                                                            .setNameFormat("boss-%02d")
                                                                            .build()), //boss executor
                            Executors.newFixedThreadPool(threadPoolSize, new ThreadFactoryBuilder()
                                                                            .setNameFormat("worker-%02d")
                                                                            .build()) //worker executor
                            );

ServerBootstrap bootstrap = new ServerBootstrap(this.channelFactory);
bootstrap.setPipelineFactory(this.channelPipelineFactory);

portion of our ChannelPipelineFactory implementation:

pipeline.addLast("Logging", logginHandler);
        pipeline.addLast("TNetstring decoder", new TNetstringDecoder());
        pipeline.addLast("TNetstring encoder", new TNetstringEncoder());
        pipeline.addLast("IlmConnection handler", new DS8kConnectionHandler(mcstoreManger));

encode method on our TNetStringEncoder class:

try
{
 LOG.debug("before returning netstring");
    @SuppressWarnings("unchecked")
    Map<? extends CharSequence, ?> map = (Map<? extends CharSequence, ?>) msg;
    return ChannelBuffers.wrappedBuffer(TNetstring.dump(map, ENCODER_CHARSET));
}
catch (Exception e)

As mentioned before, the exception is happening on these places in the code:

        at org.jboss.netty.channel.Channels.write(Channels.java:725)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)

After using Memory Analizer on eclipse using the dumps java is producing and it points to the class "org.jboss.netty.channel.socket.nio.NioAcceptedSocketChannel"

<img width="842" alt="image" src="https://user-images.githubusercontent.com/113806277/199773773-63eee085-9d06-42a7-ae8d-4ab6d2f7fef9.png">

### Netty version

3.10.6

### JVM version (e.g. `java -version`)

java version "1.8.0_291"

### OS version (e.g. `uname -a`)

AIX 7

**Comment by chrisvest** [comment]
First, 3.10.6 is 8 years old, and we don't support the 3.x line anymore.

Second, you're running out of _native_ memory, not heap memory. Eclipse MAT is only telling you where your heap memory is going.
You need to figure out where the native memory is going.
You can turn on leak detection.
If you use a pooling allocator, you can also try switching to a non-pooling one.
You could try switching to only use on-heap buffers - this will cause memory to be copied when IO happens (actually this is what the `sun.nio.ch.Util.getTemporaryDirectBuffer` call is doing, so maybe you're already doing this).
As a last resort, you can also trawl through the heap dump you have and find all of the DirectByteBuffers and see who keeps them alive.
