### ISSUE TITLE
Websocket opens serverNoContext, eventloop will block, which will seriously affect performance

### ISSUE THREAD

**Issue by yuanzhixiang** [netty/netty#12996]
### Expected behavior

Turning on serverOnContext doesn't affect performance

### Actual behavior

when websocket opens serverNoContext, eventloop will block on `at jdk.internal.ref.PhantomCleanable.remove(PhantomCleanable.java:103)`, in the example below, blocking on the lock at 0x912

```
"nioEventLoopGroup-3-11@2026" prio=10 tid=0x1e nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks nioEventLoopGroup-3-1@1612
	 blocks nioEventLoopGroup-3-2@1961
	 blocks nioEventLoopGroup-3-3@1985
	 blocks nioEventLoopGroup-3-4@2010
	 blocks nioEventLoopGroup-3-5@2020
	 blocks nioEventLoopGroup-3-6@2021
	 blocks nioEventLoopGroup-3-7@2022
	 blocks nioEventLoopGroup-3-8@2023
	 blocks nioEventLoopGroup-3-9@2024
	 blocks nioEventLoopGroup-3-12@2027
	 blocks nioEventLoopGroup-3-15@2030
	  at jdk.internal.ref.PhantomCleanable.remove(PhantomCleanable.java:103)
	  - locked <0x912> (a jdk.internal.ref.CleanerImpl$PhantomCleanableRef)
	  at jdk.internal.ref.PhantomCleanable.clean(PhantomCleanable.java:131)
	  at java.util.zip.Deflater$DeflaterZStreamRef.clean(Deflater.java:955)
	  at java.util.zip.Deflater.end(Deflater.java:890)
	  - locked <0x91f> (a java.util.zip.Deflater$DeflaterZStreamRef)
	  at io.netty.handler.codec.compression.JdkZlibEncoder.finishEncode(JdkZlibEncoder.java:361)
	  at io.netty.handler.codec.compression.JdkZlibEncoder.close(JdkZlibEncoder.java:306)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:753)
	  at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:727)
	  at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:994)
	  at io.netty.channel.AbstractChannel.close(AbstractChannel.java:280)
	  at io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:569)
	  at io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:556)
	  at io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:504)
	  at io.netty.channel.embedded.EmbeddedChannel.finishAndReleaseAll(EmbeddedChannel.java:494)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder.cleanup(DeflateEncoder.java:161)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder.compressContent(DeflateEncoder.java:144)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder.encode(DeflateEncoder.java:88)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateEncoder.encode(PerMessageDeflateEncoder.java:92)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateEncoder.encode(PerMessageDeflateEncoder.java:31)
	  at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	  at io.netty.handler.codec.http.websocketx.WebSocketProtocolHandler.write(WebSocketProtocolHandler.java:118)
	  at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler.write(WebSocketServerProtocolHandler.java:54)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
	  at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
	  at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
	  at org.example.WebsocketServer.writeAndFlush(WebsocketServer.java:75)
	  at org.example.WebsocketServer$1$1.lambda$channelRead$0(WebsocketServer.java:59)
	  at org.example.WebsocketServer$1$1$$Lambda$51/0x0000000800d12328.run(Unknown Source:-1)
	  at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	  at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159)
	  at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174)
	  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:-1)
	  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167)
	  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:-1)
	  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:833)

"nioEventLoopGroup-3-1@1612" prio=10 tid=0x14 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for nioEventLoopGroup-3-11@2026 to release lock on <0x912> (a jdk.internal.ref.CleanerImpl$PhantomCleanableRef)
	  at jdk.internal.ref.PhantomCleanable.remove(PhantomCleanable.java:103)
	  at jdk.internal.ref.PhantomCleanable.clean(PhantomCleanable.java:131)
	  at java.util.zip.Deflater$DeflaterZStreamRef.clean(Deflater.java:955)
	  at java.util.zip.Deflater.end(Deflater.java:890)
	  - locked <0x921> (a java.util.zip.Deflater$DeflaterZStreamRef)
	  at io.netty.handler.codec.compression.JdkZlibEncoder.finishEncode(JdkZlibEncoder.java:361)
	  at io.netty.handler.codec.compression.JdkZlibEncoder.close(JdkZlibEncoder.java:306)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:753)
	  at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:727)
	  at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:994)
	  at io.netty.channel.AbstractChannel.close(AbstractChannel.java:280)
	  at io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:569)
	  at io.netty.channel.embedded.EmbeddedChannel.close(EmbeddedChannel.java:556)
	  at io.netty.channel.embedded.EmbeddedChannel.finish(EmbeddedChannel.java:504)
	  at io.netty.channel.embedded.EmbeddedChannel.finishAndReleaseAll(EmbeddedChannel.java:494)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder.cleanup(DeflateEncoder.java:161)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder.compressContent(DeflateEncoder.java:144)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateEncoder.encode(DeflateEncoder.java:88)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateEncoder.encode(PerMessageDeflateEncoder.java:92)
	  at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateEncoder.encode(PerMessageDeflateEncoder.java:31)
	  at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:90)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	  at io.netty.handler.codec.http.websocketx.WebSocketProtocolHandler.write(WebSocketProtocolHandler.java:118)
	  at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler.write(WebSocketServerProtocolHandler.java:54)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
	  at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
	  at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
	  at org.example.WebsocketServer.writeAndFlush(WebsocketServer.java:75)
	  at org.example.WebsocketServer$1$1.lambda$channelRead$0(WebsocketServer.java:59)
	  at org.example.WebsocketServer$1$1$$Lambda$51/0x0000000800d12328.run(Unknown Source:-1)
	  at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	  at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159)
	  at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174)
	  at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:-1)
	  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167)
	  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:-1)
	  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce

reproduce project: https://github.com/yuanzhixiang/websocket-performance-bug

Start the server first, then start the client, break the point in the `jdk.internal.ref.PhantomCleanable#insert` synchronization code block, and then run jstack \<server pid> to reproduce.

### Netty version

4.1.84.Final

### JVM version (e.g. `java -version`)

jdk17

### OS version (e.g. `uname -a`)

macos 12.6 and linux

**Comment by normanmaurer** [comment]
There is really nothing we can do about this. Maybe open an issue for OpenJDK to replacing locking with some lock-free implementation.

**Comment by yuanzhixiang** [comment]
> There is really nothing we can do about this. Maybe open an issue for OpenJDK to replacing locking with some lock-free implementation.

The reset method of java.util.zip.Deflater is lock-free, this method maybe used here to remark the memory.
