### ISSUE TITLE
Upgrade 4.1.77 -> netty-all-4.1.85 shows java.lang.NoSuchMethodError: io.netty.internal.tcnative.SSL.bioSetFd

### ISSUE THREAD

**Issue by WhiteTrashLord** [netty/netty#13011]
I upgraded the Netty version from 4.1.77 to netty-all-4.1.85 and SSL stopped working. I didn't do any code changes.
This is the exception:

io.netty.channel.ChannelPipelineException: io.netty.handler.ssl.SslHandler.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:624)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:381)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:370)
	at telnet.TelnetServerInitializer.initChannel(TelnetServerInitializer.java:50)
	at telnet.TelnetServerInitializer.initChannel(TelnetServerInitializer.java:1)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:406)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchMethodError: io.netty.internal.tcnative.SSL.bioSetFd(JI)V
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.bioSetFd(ReferenceCountedOpenSslEngine.java:619)
	at io.netty.handler.ssl.SslHandler.setOpensslEngineSocketFd(SslHandler.java:2143)
	at io.netty.handler.ssl.SslHandler.handlerAdded(SslHandler.java:1981)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	... 24 more
io.netty.channel.

I used this code for SSL:

SslContextBuilder.forServer(certificate, privateKey)
			                     .sslProvider(SslProvider.OPENSSL)
			                     .build();

I am building the Netty jar with custom code. So far it worked great. Is this a bug which happened in a recent version?

**Comment by normanmaurer** [comment]
You need to also upgrade the netty-tcnative version

**Comment by WhiteTrashLord** [comment]
Sorry I really used an old version of netty-tcnative
