### ISSUE TITLE
EpollDatagramChannel NullPointerException when sending to unresolved address leading to ChannelOutputShutdown

### ISSUE THREAD

**Issue by nmonsees** [netty/netty#13015]
### Expected behavior

`EpollDatagramChannel` remains open after writing to unresolved address, similarly to `NioDatagramChannel`

### Actual behavior

`EpollDatagramChannel` shuts down with a `NullPointerException`, while `NioDatagramChannel` remains open after throwing an `UnresolvedAddressException`

### Steps to reproduce

`EpollDatagramChannel.write` to unresolved address

### Minimal yet complete reproducer code (or URL to code)

```

        InetSocketAddress goodHost = new InetSocketAddress("localhost", SERVER_PORT);
        InetSocketAddress unresolvedHost = new InetSocketAddress("NOT_A_REAL_ADDRESS", SERVER_PORT);

        Assert.assertFalse(goodHost.isUnresolved());
        Assert.assertTrue(unresolvedHost.isUnresolved());

        String message = "hello world!";
        udpClientChannel.writeAndFlush(getDatagramPacket(message, goodHost)).await();
        udpClientChannel.writeAndFlush(getDatagramPacket(message, unresolvedHost)).await();

        // DatagramChannel should still be open after sending to unresolved address
        Assert.assertTrue(udpClientChannel.isOpen());

        // DatagramChannel should still be able to send messages outbound
        udpClientChannel.writeAndFlush(getDatagramPacket(message, goodHost)).await();
        udpClientChannel.writeAndFlush(getDatagramPacket(message, unresolvedHost)).await();

        Assert.assertTrue(udpClientChannel.isOpen());
```

Full gist: https://gist.github.com/nmonsees/d45d01764c65e2900c55061f11ae2041

With `NioDatagramChannel` this test succeeds and the channel remains open, but `EpollDatagramChannel` closes after the first attempted write to the unresolved address.

`EpollDatagramChannel` stacktrace:

```
    [junit] /0:0:0:0:0:0:0:0%0:16600 error while writing: 
    [junit] io.netty.channel.socket.ChannelOutputShutdownException: Channel output shutdown
    [junit] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.shutdownOutput(AbstractChannel.java:638)
    [junit] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.handleWriteError(AbstractChannel.java:963)
    [junit] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:943)
    [junit] 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.flush0(AbstractEpollChannel.java:520)
    [junit] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:905)
    [junit] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
    [junit] 	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
    [junit] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    [junit] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    [junit] 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    [junit] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    [junit] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    [junit] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    [junit] 	at java.base/java.lang.Thread.run(Thread.java:829)
    [junit] Caused by: java.lang.NullPointerException
    [junit] 	at io.netty.channel.unix.Socket.sendToAddress(Socket.java:150)
    [junit] 	at io.netty.channel.epoll.EpollDatagramChannel.doWriteMessage(EpollDatagramChannel.java:376)
    [junit] 	at io.netty.channel.epoll.EpollDatagramChannel.doWrite(EpollDatagramChannel.java:329)
    [junit] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:941)
    [junit] 	... 17 more
```

`NioDatagramChannel` stacktrace:

```
    [junit] /0:0:0:0:0:0:0:0:16600 error while writing: 
    [junit] java.nio.channels.UnresolvedAddressException
    [junit] 	at java.base/sun.nio.ch.Net.checkAddress(Net.java:131)
    [junit] 	at java.base/sun.nio.ch.Net.checkAddress(Net.java:139)
    [junit] 	at java.base/sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:502)
    [junit] 	at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:295)
    [junit] 	at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:142)
    [junit] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:941)
    [junit] 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:354)
    [junit] 	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:905)
    [junit] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:742)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:728)
    [junit] 	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
    [junit] 	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
    [junit] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    [junit] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    [junit] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
    [junit] 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    [junit] 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    [junit] 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    [junit] 	at java.base/java.lang.Thread.run(Thread.java:829)
```

### Netty version

4.1.59

**Comment by nmonsees** [comment]
This commit looks relevant, but I'm not sure the fix made its way to `EpollDatagramChannel` - https://github.com/netty/netty/commit/4f5f4cdc9df6e8c3bf65d3f72ef7cf5a8404fdd4

**Comment by normanmaurer** [comment]
@nmonsees thanks... fix was merged
