### ISSUE TITLE
High CPU Usage with NioEventLoopGroup

### ISSUE THREAD

**Issue by jiangmincong** [netty/netty#13032]
### Actual behavior
 PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                               
   9872 root    20   0 31.308g 3.495g  17252 R 98.7  2.8   4:16.51 java                                                                                                                  
   2000 root    20   0 31.308g 3.495g  17252 S  4.0  2.8  24:52.29 java                                                                                                                  
   1425 root    20   0 31.308g 3.495g  17252 S  3.0  2.8  33:08.25 java                                                                                                                  
   3024 root    20   0 31.308g 3.495g  17252 S  2.7  2.8  24:27.00 java                                                                                                                  
   4170 root    20   0 31.308g 3.495g  17252 S  2.3  2.8  23:53.89 java                                                                                                                  
   4169 root    20   0 31.308g 3.495g  17252 S  2.0  2.8  26:18.76 java                                                                                                                  
   1197 root    20   0 31.308g 3.495g  17252 S  1.3  2.8   0:52.63 java                                                                                                                  
   1198 root    20   0 31.308g 3.495g  17252 S  1.3  2.8   0:52.64 java                                                                                                                  
   1199 root    20   0 31.308g 3.495g  17252 S  1.3  2.8   0:52.41 java                                                                                                                  
   1200 root    20   0 31.308g 3.495g  17252 S  1.3  2.8   0:52.44 java                                                                                                                  
   1201 root    20   0 31.308g 3.495g  17252 S  1.3  2.8   0:52.48 java                                                                                                                  
   1202 root    20   0 31.308g 3.495g  17252 S  1.3  2.8   0:52.52 java                                                                                                                  
   1203 root    20   0 31.308g 3.495g  17252 S  1.3  2.8   0:52.58 java                                                                                                                  
   1204 root    20   0 31.308g 3.495g  17252 S  1.3  2.8   0:52.41 java                                                                                                                  
   2001 root    20   0 31.308g 3.495g  17252 S  1.3  2.8  17:57.51 java                                                                                                                  
   2008 root    20   0 31.308g 3.495g  17252 S  1.3  2.8  17:53.57 java                                                                                                                  
   2071 root    20   0 31.308g 3.495g  17252 S  1.3  2.8  17:2
  

"nioEventLoopGroup-4-4" #757 prio=10 os_prio=0 tid=0x00007ff188007000 nid=0x2690 runnable [0x00007fed065dc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000645294d90> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000645294e08> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000643a64378> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:814)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

### Netty version
4.1.67.Final

### JVM version (e.g. `java -version`)
1.8.0_202
### OS version (e.g. `uname -a`)
CentOS Linux release 7.2.1511

**Comment by chrisvest** [comment]
`epollWait` is a blocking call that does not consume CPU while waiting… something else is going on. Look at your process with a profiler. I also recommend upgrading to the latest version of Netty.

**Comment by Serenagirl** [comment]
> `epollWait` is a blocking call that does not consume CPU while waiting… something else is going on. Look at your process with a profiler. I also recommend upgrading to the latest version of Netty.
hello，does epoll wait affect java performance? How do you avoid this block? In addition, the same code and configuration are used. The x86 Linux environment uses epoll, and the printing stack on the ARM uses nio. However, the system supports epoll and the usenative configuration is added. Why?

**Comment by chrisvest** [comment]
> hello，does epoll wait affect java performance? How do you avoid this block? In addition, the same code and configuration are used. The x86 Linux environment uses epoll, and the printing stack on the ARM uses nio. However, the system supports epoll and the usenative configuration is added. Why?

Not sure what you're asking. We use the blocking feature of epoll when there are no tasks to run, and no I/O to perform. When this is the case, we let the event loop thread wait in the epoll call until we either get new tasks to run, or more I/O to perform.
