### ISSUE TITLE
netty 4.1.77.Final cassandra OperationTimedOutException

### ISSUE THREAD

**Issue by ningjieu** [netty/netty#13062]
When I updated netty from  4.1.71.Final to 4.1.77.Final , using  cassandra-driver-core-3.0.0.jar to visit Apache Cassandra 3.11.5, it was found that sometimes  OperationTimedOutException was thrown (config connectTimeOut:500ms) while (one or one hundred application servers) connecting to the cassandra server. But it never happend with netty 4.1.71.Final. I'm sorry I cannot reproduce it in other envirment, maybe someone else also encountered this issue. I wonder if 4.1.77.Final version has some loss of performance or some bugs。

Even though connecting was successful, NoHostAvailableExcption maybe occur.I think that after connecting,some problem lead to Cassandra client lost the alive connection to the server.So a query is timing out on the client side for some reason, despite the server apparently being fine.  Then the driver marks the server as down and NoHostAvailableExcption occured.

Is this problem similar to issue in the site below?
https://github.com/netty/netty/issues/5486

exception 1:com.datastax.driver.core.exceptions.OperationTimedOutException: [/X.X.X.X:XXXX] Timed out waiting for server response

exception 2:com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (no host was tried)

JDK 1.8

**Comment by normanmaurer** [comment]
Sorry but we need more details to be useful. Also a side note 4.1.77.Final is quite old, why not update to the latest if you update already ?

**Comment by ningjieu** [comment]
> Sorry but we need more details to be useful. Also a side note 4.1.77.Final is quite old, why not update to the latest if you update already ?

I have changed it to Netty 4.1.86.Final. But the timeout issue also happened.  There was no relative "io.netty" debug log. At this version, the timeout issue rate is less than it at version 4.1.77.final.
@normanmaurer

**Comment by ningjieu** [comment]
Also there is other exception debug log in cassandra client datastax containing netty exception:
com.datastax.driver.core.Connection$Dispatcher.exceptionCaught(Connection.java:1036)

io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(4) exceeds writerIndex(9): PooledSlicedByteBuf(ridx: 9,widx: 9, cap: 9/9, unwrapped: PooledUnsafeDirectByteBuf(ridx: 9, widx: 72, cap: 2048))
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
at io.netty.channel.AbstarctChannelHandlerContext.invokerChannelRead(AbstarctChannelHandlerContext.jar:444) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]

**Comment by ningjieu** [comment]
If client version is netty 4.1.86, must server version be equal or greater than some version like 4.1.86? (I did not upgrate server cassandra version with netty-all-4.0.44.Final.jar.)

**Comment by normanmaurer** [comment]
@ningjieu please paste the full stacktrace and no it shouldn't matter if you use different versions

**Comment by ningjieu** [comment]
> @ningjieu please paste the full stacktrace and no it shouldn't matter if you use different versions

@normanmaurer I typed it word-by-word here.
com.datastax.driver.core.Connection@Dispatcher.exceptionCautht(Connection.java:1036)
    Connection[/10.*.*.*:9042-3, inFlight=0, closed=false] connection error
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(4) exceeds writerIndex(9): PooledSlicedByteBuf(ridx: 9, widx: 9, cp:9/9, unwrapped: PooledUnsafeDirectByteBuf(ridx: 9, widx: 72, cap: 2048))
    at io.netty.hander.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.hander.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.hander.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.hander.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.hander.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.DefaultChannelPipeline$HeadContext.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[netty-transport-classes-epoll-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[netty-transport-classes-epoll-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[netty-transport-classes-epoll-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.86.Final.jar:4.1.86.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.86.Final.jar:4.1.86.Final] 
    at java.lang.Thread.run(Thread.java:748) ~[?1.8.0_272]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(9) + length(4) exceeds writerIndex(9): PooledSlicedByteBuf(ridx: 9, widx: 9, cp:9/9, unwrapped: PooledUnsafeDirectByteBuf(ridx: 9, widx: 72, cap: 2048))
    at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.86.Final.java:4.1.86.Final]
    at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809) ~[netty-buffer-4.1.86.Final.java:4.1.86.Final]
    at com.datastax.driver.core.Response$Result$1.decode(Response.java:240)
    ~[cassandra-driver-core-3.0.0.jar:?]
    at com.datastax.driver.core.Response$Result$1.decode(Response.java:237)
    ~[cassandra-driver-core-3.0.0.jar:?]
    at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:266)
    ~[cassandra-driver-core-3.0.0.jar:?]
    at com.datastax.driver.core.Message$ProtocolDecoder.decode(Message.java:246)
    ~[cassandra-driver-core-3.0.0.jar:?]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[netty-codec-4.1.86.Final.jar:4.1.86.Final]
    ... 20 more

**Comment by normanmaurer** [comment]
Sorry but you will need to work with the Cassandra folks on that.

**Comment by normanmaurer** [comment]
Closing this as there was no followup.
