### ISSUE TITLE
Request to remove the dependency on netty-transport-native-unix-common for Windows environments

### ISSUE THREAD

**Issue by NarendranJothiram** [netty/netty#13101]
### Expected behavior

netty-transport-native-unix-common to get added as dependency only for UNIX environments. This allows our application/product to not use an unused dependency in classpath like how it was in Netty version 4.1.77.

### Actual behavior

Dependency on netty-transport-native-unix-common was not there for netty running on windows server or windows environments until Netty version 4.1.77.

This commit looks to have introduced an new required dependency which is applicable only for UNIX environments:

https://github.com/netty/netty/commit/bc085b06e3153bc975353671151c0c90e4265baa#diff-c8414afca33f9431351e310ca1203eff4c16093b1a0a2fc587f3b302de217e4a

### Steps to reproduce

Initialize channel connect without netty-transport-native-unix-common.jar in the classpath.

### Minimal yet complete reproducer code (or URL to code)

Have logs information about this dependency change.

Failed to initialize a channel. Closing: [id: 0xf1d83c78] io.netty.channel.ChannelInitializer.exceptionCaught(ChannelInitializer.java:97)
io.netty.channel.ChannelPipelineException: io.netty.handler.ssl.SslHandler.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:624)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:223)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:195)
	at com.vmware.vdi.lmv.natter.natter.NatterConnection$2.a(SourceFile:427)
	at com.vmware.vdi.lmv.natter.natter.NatterConnection$2.initChannel(SourceFile:414)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:514)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:429)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:486)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
**Caused by: java.lang.NoClassDefFoundError: io/netty/channel/unix/UnixChannel
	at io.netty.handler.ssl.SslHandler.setOpensslEngineSocketFd(SslHandler.java:2142)
	at io.netty.handler.ssl.SslHandler.handlerAdded(SslHandler.java:1981)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:1114)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609)
	... 24 more
Caused by: java.lang.ClassNotFoundException: io.netty.channel.unix.UnixChannel
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 28 more**
2023-01-05T17:22:36.997+05:30 WARN  (1240-27CC) <pool-17-thread-1> [DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. io.netty.channel.DefaultChannelPipeline.onUnhandledInboundException(DefaultChannelPipeline.java:1152)
io.netty.channel.StacklessClosedChannelException

**Comment by chrisvest** [comment]
It is harmless to have it on the class path on Windows.

**Comment by NarendranJothiram** [comment]
Yes, agreed it is harmless. Request made is why to have an UNIX jar dependency which is not useful for windows environment ?

**Comment by hyperxpro** [comment]
@NarendranJothiram Is there any downside to having this in classpath on Windows?

**Comment by NarendranJothiram** [comment]
mvn repository also has about this library information as: 

https://mvnrepository.com/artifact/io.netty/netty-transport-native-unix-common/4.1.86.Final

"Static library which contains common unix utilities."

As this module was created for UNIX purpose, felt like it is broken now by mandating UNIX transport jars to be used in windows as well with no specific reason. 

Also, one less jar to get ported each time when a product ships. Our product never runs in UNIX and gets deployed only in windows servers.

**Comment by normanmaurer** [comment]
@NarendranJothiram this is by design... We use it to test if the `Channel` is of type `UnixChannel` as in this case we can support some feature.

**Comment by NarendranJothiram** [comment]
Thanks for confirming, it is by design and there are no plans of removing this dependency in future.
