### ISSUE TITLE
netty closes connection with an exception if the application is configured to use SOCKS5 proxy

### ISSUE THREAD

**Issue by Drugoy** [netty/netty#13159]
### Expected behavior
No error should occur, the application should be able to reach the resource using proxy.

### Actual behavior
Application throws an error:
```
WARN  [reactor-http-epoll-9] Loggers.java:304  [c0eda415, L:/10.188.200.245:56008 ! R:10.88.8.12/10.88.8.12:1080] The connection observed an error
java.nio.channels.ClosedChannelException: null
    at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1065)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
    at io.netty.handler.proxy.ProxyHandler.channelInactive(ProxyHandler.java:230)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:303)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:274)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:301)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:871)
```

### Steps to reproduce
1. Set up this socks5-proxy: https://github.com/serjs/socks5-server with auth.
2. Configure the app to use it and run it.
3. Make the application access some resource via that proxy.

### Minimal yet complete reproducer code (or URL to code)
Sorry, I don't own that code.

### Netty version
Reproducible on 4.1.86.Final and 4.1.87.Final

### JVM version (e.g. `java -version`)
openjdk version "11.0.15" 2022-04-19
IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15+10)
Eclipse OpenJ9 VM 11.0.15.0 (build openj9-0.32.0, JRE 11 Linux amd64-64-Bit Compressed References 20220422_425 (JIT enabled, AOT enabled)
OpenJ9   - 9a84ec34e
OMR      - ab24b6666
JCL      - b7b5b42ea6 based on jdk-11.0.15+10)

### OS version (e.g. `uname -a`)
Linux my-app 5.4.88-1.el7.elrepo.x86_64 #1 SMP Thu Jan 7 19:04:31 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

As far as I understand, the issue is about using that particular SOCKS5 proxy (this is what we'd like to switch to, but can't due to this bug), the error doesn't seem to occur with proxy <a href="https://www.inet.no/dante/">dante</a>.

**Comment by hyperxpro** [comment]
This is a Reactor Netty issue.

https://github.com/reactor/reactor-netty

**Comment by Drugoy** [comment]
Resolved there.
