### ISSUE TITLE
java.nio.channels.ClosedChannelException: null

### ISSUE THREAD

**Issue by svraj379** [netty/netty#13185]
We are using Spring boot with Netty server all on production environment we are seeing following error. can you please give some pointers on this

t io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:281) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.85.Final.jar:4.1.85.Final]
io.netty.channel.unix.Errors$NativeIoException: recvAddress(..) failed: Connection reset by peer
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403) ~[netty-transport-classes-epoll-4.1.85.Final.jar:4.1.85.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:305) ~[netty-transport-4.1.85.Final.jar:4.1.85.Final]
java.nio.channels.ClosedChannelException: null

**Comment by normanmaurer** [comment]
This means the connection was closed (for whatever reason)

**Comment by hyperxpro** [comment]
Fixed by https://github.com/netty/netty/pull/13099
