### ISSUE TITLE
tcnative can not found netty-tcnative in java.library.path

### ISSUE THREAD

**Issue by qq1014853731** [netty/netty#13249]
### Expected behavior
I am developing an Mqtt server. When I want to create an OpenSslContext, netty has an error

### Actual behavior
I checked my java code, which is Ok's, but he still threw an error: no netty_tcnative in java.library.path, which did not print successfully. I debugged my code and found that it depends on netty-tcnative. So I installed tcnative according to the official tutorial. The dependencies are as follows. It is also OK

```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative</artifactId>
            <classifier>${os.detected.classifier}</classifier>
        </dependency>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <classifier>${os.detected.classifier}</classifier>
        </dependency>

        ....

        <extensions>
            <!-- privide os.detected.classifier -->
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.5.0.Final</version>
            </extension>
        </extensions>
```
![image](https://user-images.githubusercontent.com/52345437/221465572-38107d29-fddc-4952-a9e7-ae22836a5881.png)

I am using [moquette](https://github.com/moquette-io/moquette) create a mqtt server，it's no problem，moquette's code:

![image](https://user-images.githubusercontent.com/52345437/221465992-461bfbfa-321e-447e-94f7-bd7e138804e6.png)
![image](https://user-images.githubusercontent.com/52345437/221466423-032f33a1-f991-48a2-a22b-1348fd44fe89.png)

```text
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.moquette.broker.Server]: Factory method 'server' threw exception; nested exception is java.lang.UnsatisfiedLinkError: failed to load the required native library
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 19 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:596)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:215)
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:45)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:349)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:336)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:473)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606)
	at io.moquette.broker.DefaultMoquetteSslContextCreator.initSSLContext(DefaultMoquetteSslContextCreator.java:93)
	at io.moquette.broker.NewNettyAcceptor.initialize(NewNettyAcceptor.java:184)
	at io.moquette.broker.Server.startServer(Server.java:224)
	at io.moquette.broker.Server.startServer(Server.java:167)
	at org.springblade.mqtt.broker.core.MqttServerAutoConfiguration.server(MqttServerAutoConfiguration.java:113)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 20 common frames omitted
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_osx_x86_64, netty_tcnative_x86_64, netty_tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
	... 36 common frames omitted
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_osx_x86_64
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 38 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
			at java.lang.Runtime.loadLibrary0(Runtime.java:843)
			at java.lang.System.loadLibrary(System.java:1134)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 39 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_osx_x86_64 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
				at java.lang.Runtime.loadLibrary0(Runtime.java:843)
				at java.lang.System.loadLibrary(System.java:1134)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 40 common frames omitted
	Caused by: java.lang.IllegalStateException: Multiple resources found for 'META-INF/native/libnetty_tcnative_osx_x86_64.jnilib' with different content: [jar:file:/Users/chukongxiang/.m2/repository/io/netty/netty-tcnative/2.0.53.Final/netty-tcnative-2.0.53.Final-osx-x86_64.jar!/META-INF/native/libnetty_tcnative_osx_x86_64.jnilib, jar:file:/Users/chukongxiang/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.53.Final/netty-tcnative-boringssl-static-2.0.53.Final-osx-x86_64.jar!/META-INF/native/libnetty_tcnative_osx_x86_64.jnilib]
		at io.netty.util.internal.NativeLibraryLoader.getResource(NativeLibraryLoader.java:301)
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:179)
		... 39 common frames omitted
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative_x86_64
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 38 common frames omitted
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative_x86_64.jnilib
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:181)
		... 39 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
			at java.lang.Runtime.loadLibrary0(Runtime.java:843)
			at java.lang.System.loadLibrary(System.java:1134)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 39 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative_x86_64 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
				at java.lang.Runtime.loadLibrary0(Runtime.java:843)
				at java.lang.System.loadLibrary(System.java:1134)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 40 common frames omitted
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 38 common frames omitted
	Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.jnilib
		at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:181)
		... 39 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
			at java.lang.Runtime.loadLibrary0(Runtime.java:843)
			at java.lang.System.loadLibrary(System.java:1134)
			at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 39 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1863)
				at java.lang.Runtime.loadLibrary0(Runtime.java:843)
				at java.lang.System.loadLibrary(System.java:1134)
				at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 40 common frames omitted
```

**Note: The console does not print：Successfully xxxx**

debug:
![image](https://user-images.githubusercontent.com/52345437/221466872-1c26c692-27e2-4d16-9377-7a74ce7f20f6.png)
The libName variable has value: [netty_tcnative_osx_x86_64, netty_tcnative_x86_64, netty_tcnative], they all threw exceptions

openssl:
![image](https://user-images.githubusercontent.com/52345437/221469083-5f0b4c28-0fba-4a58-943f-a20a4d017a56.png)

### Netty version
netty-all 4.1.78

### JVM version (e.g. `java -version`)
java version "1.8.0_361" 

### OS version (e.g. `uname -a`)
MacOS Monterey 12.6
Darwin Kernel Version 21.6.0

**Comment by qq1014853731** [comment]
Ohhhhhhh, i saw this exception:
```text
Multiple resources found for 'META-INF/native/libnetty_tcnative_osx_x86_64.jnilib' with different content: [jar:file:/Users/chukongxiang/.m2/repository/io/netty/netty-tcnative/2.0.53.Final/netty-tcnative-2.0.53.Final-osx-x86_64.jar!/META-INF/native/libnetty_tcnative_osx_x86_64.jnilib, jar:file:/Users/chukongxiang/.m2/repository/io/netty/netty-tcnative-boringssl-static/2.0.53.Final/netty-tcnative-boringssl-static-2.0.53.Final-osx-x86_64.jar!/META-INF/native/libnetty_tcnative_osx_x86_64.jnilib]
```

I change my pom.xml:
```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <classifier>${os.detected.classifier}</classifier>
        </dependency>

        ....

        <extensions>
            <!-- privide os.detected.classifier -->
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.5.0.Final</version>
            </extension>
        </extensions>
```
**### remove dependency:** 
```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-tcnative</artifactId>
            <classifier>${os.detected.classifier}</classifier>
        </dependency>
```

Closed!
