### ISSUE TITLE
DefaultResourceLeak.dispose method got a NullPointerException

### ISSUE THREAD

**Issue by carvinhappy** [netty/netty#13264]
Hi all,
In our project, we got a NullPointerException in the method DefaultResourceLeak.dispose calling, the exception stack trace and code as follows :

`
Caused by: java.lang.NullPointerException: null
	at io.netty.util.ResourceLeakDetector$DefaultResourceLeak.dispose(ResourceLeakDetector.java:453)
	at io.netty.util.ResourceLeakDetector.reportLeak(ResourceLeakDetector.java:300)
	at io.netty.util.ResourceLeakDetector.track0(ResourceLeakDetector.java:258)
	at io.netty.util.ResourceLeakDetector.track(ResourceLeakDetector.java:246)
	at io.netty.buffer.AbstractByteBufAllocator.toLeakAwareBuffer(AbstractByteBufAllocator.java:43)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:363)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
	at io.lettuce.core.protocol.CommandArgs$KeyArgument.encode(CommandArgs.java:656)
	at io.lettuce.core.protocol.CommandArgs.encode(CommandArgs.java:346)
	at io.lettuce.core.protocol.Command.encode(Command.java:119)
	at io.lettuce.core.protocol.AsyncCommand.encode(AsyncCommand.java:185)
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:90)
	... 18 common frames omitted
` 
<br>

boolean dispose() {
            clear();
            return allLeaks.remove(this); // Is the allLeaks null ?
        }

I'm confused what is causing this problem? Is the "allLeaks" referencing object collected by the gc ?
Thanks a lot.

### Steps to reproduce
cannot reproduce

### Netty version
4.1.46.Final
### JVM version (e.g. `java -version`)
1.8.0_181
### OS version (e.g. `uname -a`)
CentOS 7.4

**Comment by normanmaurer** [comment]
Honestly I have no idea... That said 4.1.46.Final is multiple years old. Please upgrade to the latest version and see if the problems still arise.

**Comment by carvinhappy** [comment]
Ok, thanks a lot.
