### ISSUE TITLE
Too many open files causes tight loop, no recovery

### ISSUE THREAD

**Issue by dewjose** [netty/netty#1328]
Netty 3.5.\* handled this case more gracefully. Once the open file handle count retreated to below the limit the netty pipeline recovered and continued to operate.

With netty 4.0 the pipeline crashes, I can't catch this exception, or don't know how, and the JVM spins out of contro.

05/02/2013 15:12:20  WARN nioEventLoopGroup-10-2 io.netty.channel.DefaultChannelPipeline:151 - An exceptionCaught() event was fired, and it reached at the end of the pipeline. It usually means the last h\
andler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:226)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:108)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:61)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:401)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:365)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:302)
        at io.netty.channel.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
        at java.lang.Thread.run(Thread.java:722)

**Comment by Hanson1129** [comment]
It seems not work with my test...
When "Too many open files" happens,the great URLClassLoader cannot do any classloading because URLClassLoader need a FD to findClass.
So the anonymous inner class , new Runnable(){} will cause a problem.
The stack is like this:

``` java 

16:17:51.483 [HSF-HTTP-Boss-15-thread-2] DEBUG i.n.c.AbstractChannelHandlerContext - An exception java.lang.IllegalAccessError: tried to access class io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor$2 from class io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor
        at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.exceptionCaught(ServerBootstrap.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:275)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:267)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1301)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:296)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:275)
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:914)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:102)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
        at com.taobao.hsf.remoting.netty.common.RemotingThreadFactory$PooledByteBufRunnable.run(RemotingThreadFactory.java:38)
        at java.lang.Thread.run(Thread.java:662)
was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.6.0_32]
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:152) ~[na:1.6.0_32]
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:140) ~[netty-all-4.1.6.Final.jar!/:na]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75) ~[netty-all-4.1.6.Final.jar!/:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [netty-all-4.1.6.Final.jar!/:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574) [netty-all-4.1.6.Final.jar!/:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488) [netty-all-4.1.6.Final.jar!/:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [netty-all-4.1.6.Final.jar!/:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-all-4.1.6.Final.jar!/:na]
        at com.taobao.hsf.remoting.netty.common.RemotingThreadFactory$PooledByteBufRunnable.run(RemotingThreadFactory.java:38) [hsf.remoting.netty-2.1.1.6.9-mtop.jar!/:na]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_32]

```

And even log.warn may cause NoClassDefFoundError,see the issue [issue 5962](https://github.com/netty/netty/issues/5962).We want to log in file and we don't want our Boss thread carsh.Buy we have found a way to work-around.

So we must do preloading before "Too many open files".
This is my pull request [pr](https://github.com/netty/netty/pull/6055)
