### ISSUE TITLE
 java.lang.UnsatisfiedLinkError io.netty.channel.unix.Socket.recvAddress

### ISSUE THREAD

**Issue by ioleo** [netty/netty#13333]
### Expected behavior

It just works™

### Actual behavior

When trying to use Netty client I'm getting:

```
 java.lang.UnsatisfiedLinkError: 'int io.netty.channel.unix.Socket.recvAddress(int, long, int, int)'
    at io.netty.channel.unix.Socket.recvAddress(Native Method)
    at io.netty.channel.unix.Socket.recvAddress(Socket.java:283)
    at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:349)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:786)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce

Use Netty Client to make a call to AWS DynamoDB. The actual call seems irrelevant, as the stack trace shows its netty internals.

### Minimal yet complete reproducer code (or URL to code)

https://github.com/ioleo/dynamo-repro

Run `docker-compose up -d`
Run `sbt reStart`

Make HTTP call:
```
POST http://localhost:8080/events HTTP/1.1
Content-Type: application/json

{
  "id": "foobar",
  "action": "subscribe",
  "timestamp": "2000-01-01T00:00:00Z"
}
```

Under the hood ZIO DynamoDB library is called, which relies on Netty Client.

**AFAIK: This issue is only reproducable on Intel machines**

```
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  10
  On-line CPU(s) list:   0-9
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Core(TM) i9-10980HK CPU @ 2.40GHz
```

### Netty version

See `lock.sbt`, depending on component either `4.1.79.Final` or `4.1.86.Final`.

### JVM version (e.g. `java -version`)

```
$ java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc36) (build 17.0.6+10)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc36) (build 17.0.6+10, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)

```
$ uname -a
Linux avm-dev 5.15.94-1.qubes.fc32.x86_64 #1 SMP Sun Feb 19 07:18:46 CET 2023 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/fedora-release
Fedora release 36 (Thirty Six)
```

**Comment by slandelle** [comment]
Your lock.sbt is a mess. All your netty modules should be aligned, you shouldn’t mix 4.1.79.Final and 4.1.86.Final.
You should upgrade everything to the latest version.

**Comment by ioleo** [comment]
Aligning the netty versions helped.
