### ISSUE TITLE
Thread blocked causing high latency and CPU uses

### ISSUE THREAD

**Issue by onlynishant** [netty/netty#13347]
### Specification:
We are using Netty version `4.1.91.Final` with `Epoll` on a bare metal server with the below config:
```
OS: Centos 7.6
Java version: 11 (IBM OpenJ9) [JVM main params: -Xms28g -Xmx28g -Xmn14g -Xgc:concurrentScavenge]
CPU: 48 core
RAM: 64G

<netty.version>4.1.91.Final</netty.version>
<tcnative.version>2.0.59.Final</tcnative.version>
<bouncycastle.version>1.69</bouncycastle.version>
```
### Use case:
Each of these servers receives **10-20k JSON request/sec** from 100-500 other external servers on 20-50k established connections in normal times both on HTTP and HTTPS (**_netty-tcnative-boringssl-static_**) POST. These external servers also recycle connections in frequent intervals.

### Sample code:

```
private Class<? extends ServerSocketChannel> getBestAvailableServerSocketChannel() {
    if (Util.IS_OS_LINUX && Epoll.isAvailable()) {
      Logger.INFO_LOG.info("Using EpollServerSocketChannel");
      return EpollServerSocketChannel.class;
    } else if (Util.IS_OS_MAC) {
      Logger.INFO_LOG.info("Using KQueueServerSocketChannel");
      return KQueueServerSocketChannel.class;
    } else {
      Logger.INFO_LOG.info("Using NioServerSocketChannel");
      return NioServerSocketChannel.class;
    }
  }
...
...
// config SSLContext
SslProvider provider = SslProvider.isAlpnSupported(SslProvider.OPENSSL) ? SslProvider.OPENSSL : SslProvider.JDK;
sslCtx = SslContextBuilder.forServer(keyManagerFactory)
    .sslProvider(provider)
    /* NOTE: the cipher filter may not include all ciphers required by the HTTP/2 specification.
     * Please refer to the HTTP/2 specification for cipher requirements. */
//        .ciphers(Http2SecurityUtil.CIPHERS, SupportedCipherSuiteFilter.INSTANCE)
    .applicationProtocolConfig(new ApplicationProtocolConfig(
        Protocol.ALPN,
        // NO_ADVERTISE is currently the only mode supported by both OpenSsl and JDK providers.
        SelectorFailureBehavior.NO_ADVERTISE,
        // ACCEPT is currently the only mode supported by both OpenSsl and JDK providers.
        SelectedListenerFailureBehavior.ACCEPT,
        // support both HTTP2 and HTTP1.1
//            ApplicationProtocolNames.HTTP_2,
        ApplicationProtocolNames.HTTP_1_1
    ))
    .sessionCacheSize(SSL_SESSION_CACHE_SIZE) // 1800
    .sessionTimeout(SSL_SESSION_CACHE_TIMEOUT_SECOND) // 1024 * 100
    .build();

...
...
// configure server
ServerBootstrap httpServer = new ServerBootstrap();

// ioThreadExecutors = CPU core / 2
// workerThreadExecutors = ioThreadExecutors * 8
httpServer = httpServer.group(ioThreadExecutors, workerThreadExecutors);

Class<? extends ServerSocketChannel> serverSocketChannelClass = builder.serverSocketChannelClass;
if (serverSocketChannelClass == null) {
  serverSocketChannelClass = getBestAvailableServerSocketChannel();
}

httpServer.channel(serverSocketChannelClass) // Here, we specify to use the NioServerSocketChannel class which is used to instantiate a new Channel to accept incoming connections.
        .handler(new LoggingHandler(logLevel))
        .childHandler(channelInitializer)
        /*
         option() is for the NioServerSocketChannel that accepts incoming connections.
         childOption() is for the Channels accepted by the parent ServerChannel, which is NioSocketChannel in this case.
         https://netty.io/4.1/api/io/netty/channel/ChannelOption.html
         */
        .option(ChannelOption.SO_BACKLOG, 2048)
        /*
        Allow multiple I/O thread to bind to same port. By default, each port will be managed by single dedicated I/O thread
        https://stackoverflow.com/questions/67145817/netty-how-many-thread-is-accepting-connections-on-a-server-port-80
         */
        .option(UnixChannelOption.SO_REUSEPORT, true)
        .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
        // https://netty.io/wiki/tcp-fast-open.html
//        .option(ChannelOption.TCP_FASTOPEN, 1000)
        // http://normanmaurer.me/presentations/2014-twitter-meetup-netty/slides.html#11.0
        .childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
        .childOption(ChannelOption.SO_SNDBUF, 10 * 1024 * 1024)
        .childOption(ChannelOption.SO_RCVBUF, 10 * 1024 * 1024)
        .childOption(ChannelOption.SO_REUSEADDR, true)
        .childOption(ChannelOption.SO_KEEPALIVE, true)
        .childOption(ChannelOption.TCP_NODELAY, true);

if (serverSocketChannelClass == EpollServerSocketChannel.class) {
  httpServer.option(EpollChannelOption.EPOLL_MODE, EpollMode.EDGE_TRIGGERED);
}


// for each port, bind it multiple times
for (int i = 0; i < channelThreadCount; i++) {
  ChannelFuture f = httpServer.bind(port).sync();
  channelFutureSet.add(f);
}


// channelInitializer class

@Override
  public void initChannel(SocketChannel ch) {
    ChannelPipeline pipeline = ch.pipeline();
    int port = ch.localAddress().getPort();

    // Add SSL handler first to encrypt and decrypt everything.
    SslContext sslContext = sslContextMap.get(port);
    if (sslContext != null) {
      pipeline.addLast(sslContext.newHandler(ch.alloc()));
    }

    /*
    On top of the SSL handler, add  other handlers
    A combination of HttpRequestDecoder and HttpResponseEncoder

    Headers Validation takes time and most of the time it is not needed directly in the decoder/encoder
    http://normanmaurer.me/presentations/2014-twitter-meetup-netty/slides.html#5.0
     */
    pipeline.addLast(new HttpServerCodec(DEFAULT_MAX_INITIAL_LINE_LENGTH, DEFAULT_MAX_HEADER_SIZE, DEFAULT_MAX_CHUNK_SIZE, false));

    pipeline.addLast(new HttpServerKeepAliveHandler());

    // It is useful when you don't want to take care of HTTP messages whose transfer encoding is 'chunked'
    // MAX_REQUEST_CONTENT_LENGTH = 1048576; //1 mb
    pipeline.addLast(new HttpObjectAggregator(MAX_REQUEST_CONTENT_LENGTH)); // inbound


    // Business logic in seprate thead because it may take 10-100ms time and we don't want to block worker thread
    // EventExecutorGroup handlerExecutorGroup = new DefaultEventExecutorGroup(core * 8, handlerThreadFactory);
    pipeline.addLast(handlerExecutorGroup, "handler", new HttpEndServer(channelHandlerMap.get(port)));

  }



///
public class HttpEndServer extends SimpleChannelInboundHandler<Object> implements HttpServer {


  ...
  ...

@Override
  public void channelRead0(ChannelHandlerContext ctx, Object msg) {
    if (msg instanceof HttpRequest) {
      HttpRequest request = (HttpRequest) msg;
      ByteBuf content = null;
      if (msg instanceof HttpContent) {
        HttpContent httpContent = (HttpContent) msg;
        content = httpContent.content();
      }

      QueryStringDecoder queryStringDecoder = new QueryStringDecoder(request.uri());
      String path = queryStringDecoder.path();

      RequestHandler requestHandler = handler.get(path);
      if (requestHandler == null) {
        requestHandler = handler.get(DEFAULT_PATH);
      }
      // call business handler
      requestHandler.handle(ctx, this, request, content);
    }
  }

  @Override
  public void channelWritabilityChanged(ChannelHandlerContext ctx) throws Exception {
    log.info("channel Writability Changed");
    while (outboundQueue.relaxedPeek() != null) {
      Object out = outboundQueue.relaxedPoll();
      if (out != null) {
        ChannelFuture cf = ctx.writeAndFlush(out);
      /*
      Adds ChannelFuture- Listener to receive notification after write completes
       */
        cf.addListener((ChannelFutureListener) future -> {
          if (future.isSuccess()) {
            // Write operation completes without error
            log.debug("channelWritabilityChanged: Write successful.");
          } else {
            // Logs an error
            log.error("channelWritabilityChanged: Write error. msg: {}", future.cause().getLocalizedMessage());
          }
        });
      }
    }

    super.channelWritabilityChanged(ctx);
    log.debug("Writeability Changed Event");
  }

  @Override
  public void sendResponse(ChannelHandlerContext ctx, HttpRequest request, FullHttpResponse response) {

    // HTTP 2
    String streamId = getStreamId(request);

    if (streamId != null && !streamId.isEmpty()) {
      setStreamId(response, streamId);
    }

    // Get keep-alive info
    boolean keepAlive = HttpUtil.isKeepAlive(request);

    // Set keep-alive response header
    if (keepAlive) {
      // Add 'Content-Length' header only for a keep-alive connection.
      response.headers().setInt(HttpHeaderNames.CONTENT_LENGTH, response.content().readableBytes());
      // Add keep alive header as per:
      // - https://www.w3.org/Protocols/HTTP/1.1/draft-ietf-http-v11-spec-01.html#Connection
      response.headers().set(CONNECTION, HttpHeaderValues.KEEP_ALIVE);
    } else {
      // Tell the client we're going to close the connection.
      response.headers().set(CONNECTION, CLOSE);
    }

    // Write the response.
    // no need to call flush for non-ssl HTTP/2 as channelReadComplete(...) will take care of it.
    if (streamId != null && !streamId.isEmpty() && !isSSL) {
      ctx.write(response);
    } else {
      /*
       check before writeAndFlush if channel is active
       otherwise we will get io.netty.channel.StacklessClosedChannelException
       */
      if (ctx.channel().isWritable()) {
        // Writes the data and flushes it
        ChannelFuture cf = ctx.writeAndFlush(response);
      /*
      Adds ChannelFuture- Listener to receive notification after write completes
       */
        cf.addListener((ChannelFutureListener) future -> {
          if (future.isSuccess()) {
            // Write operation completes without error
            log.debug("Write successful.");
          } else {
            // Logs an error
            log.error("Write error. msg: {}", future.cause().getLocalizedMessage());
          }
        });

        if (!keepAlive) {
          cf.addListener(ChannelFutureListener.CLOSE);
        }
      } else {
        //Channel not even open and therefore it's not writable
        log.warn("channel is not writable so adding to queue.");
        outboundQueue.add(response);
//        ctx.close();
      }
    }

//    if (!keepAlive) {
//      // If keep-alive is off, close the connection once the content is fully written.
//      ctx.writeAndFlush(Unpooled.EMPTY_BUFFER).addListener(ChannelFutureListener.CLOSE);
//    }
  }
}
```

**There are many error msg of these 4 types:**

- sendResponse$1(186): Write error. msg: SSLEngine closed already
- exceptionCaught(62): An exception is thrown. msg: recvAddress(..) failed: Connection reset by peer
- sendResponse(195): channel is not writable so adding to queue.
- exceptionCaught(62): An exception is thrown. msg: javax.net.ssl.SSLHandshakeException: error:10000070:SSL routines:OPENSSL_internal:BAD_PACKET_LENGTH

I also see latency shoots up very high sometimes (> 200ms) while normally it's under 50ms. Is there anything wrong in the code?

<img width="1719" alt="Screenshot 2023-04-20 at 4 40 08 PM" src="https://user-images.githubusercontent.com/19163787/233348928-325edf23-a41a-4f11-b07d-4f90f796dc1c.png">

**Comment by franz1981** [comment]
I suggest to profile and check https://github.com/netty/netty/issues/12708
I won't suggest checking 2 interface types in a row, it will likely cause a scalability issue leading to high cpu usage (in usr space).
Try checking again Vs the specific type you expect to receive first, if possible. Said that, profiling is the way to go

**Comment by onlynishant** [comment]
@franz1981 thanks for the quick reply. 
> I suggest to profile and check https://github.com/netty/netty/issues/12708

I will check

I googled a lot and tried many things but didn't find any solution to most of these errors. Please point me somewhere where I can check about these.
> exceptionCaught(62): An exception is thrown. msg: recvAddress(..) failed: Connection reset by peer

This is actually expected because our peers reset the connection at regular intervals. This is relatively lower in numbers.

 > sendResponse$1(186): Write error. msg: SSLEngine closed already
 >sendResponse(195): channel is not writable so adding to queue.
 
 these 2 errors are widespread.

**Comment by onlynishant** [comment]
I also see I/O threads are blocked in thread dump
```
"I/O-1-1" prio=5 Id=69 RUNNABLE
	at java.base@11.0.17/java.lang.Thread.getStateImpl(Native Method)
	at java.base@11.0.17/java.lang.Thread.getState(Thread.java:1341)
	- locked java.lang.Thread$ThreadLock@94081081
	at app//io.netty.util.Recycler$LocalPool.release(Recycler.java:344)
	at app//io.netty.util.Recycler$DefaultHandle.recycle(Recycler.java:257)
	at app//io.netty.channel.AbstractChannelHandlerContext$WriteTask.recycle(AbstractChannelHandlerContext.java:1273)
	at app//io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1250)
	at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.17/java.lang.Thread.run(Thread.java:839)

	Locked ownable synchronizers: 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@8ea2eda7
	
"I/O-1-2" prio=5 Id=70 RUNNABLE
	at java.base@11.0.17/java.lang.Thread.getStateImpl(Native Method)
	at java.base@11.0.17/java.lang.Thread.getState(Thread.java:1341)
	- locked java.lang.Thread$ThreadLock@3c56b07e
	at app//io.netty.util.Recycler$LocalPool.release(Recycler.java:344)
	at app//io.netty.util.Recycler$DefaultHandle.recycle(Recycler.java:257)
	at app//io.netty.channel.AbstractChannelHandlerContext$WriteTask.recycle(AbstractChannelHandlerContext.java:1273)
	at app//io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1250)
	at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.17/java.lang.Thread.run(Thread.java:839)

	Locked ownable synchronizers: 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@a34ee9bc
...
...
"I/O-1-14" prio=5 Id=82 BLOCKED on java.lang.Thread$ThreadLock@94081081 owned by "I/O-1-1" Id=69
	at java.base@11.0.17/java.lang.Thread.getState(Thread.java:1334)
	at app//io.netty.util.Recycler$LocalPool.release(Recycler.java:344)
	at app//io.netty.util.Recycler$DefaultHandle.unguardedRecycle(Recycler.java:265)
	at app//io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry.unguardedRecycle(PoolThreadCache.java:476)
	at app//io.netty.buffer.PoolThreadCache$MemoryRegionCache.allocate(PoolThreadCache.java:396)
	at app//io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:168)
	at app//io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:152)
	at app//io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:151)
	at app//io.netty.buffer.PoolArena.allocate(PoolArena.java:137)
	at app//io.netty.buffer.PoolArena.allocate(PoolArena.java:129)
	at app//io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396)
	at app//io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at app//io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at app//io.netty.handler.ssl.SslHandler$SslEngineType$1.allocateWrapBuffer(SslHandler.java:233)
	at app//io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:2276)
	at app//io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:826)
	at app//io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:800)
	at app//io.netty.handler.ssl.SslHandler.flush(SslHandler.java:781)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:925)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:531)
	at app//io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125)
	at app//io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:356)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:907)
	at app//io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:893)
	at app//io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:127)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:923)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:941)
	at app//io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247)
	at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.17/java.lang.Thread.run(Thread.java:839)

	Locked ownable synchronizers: 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@db3fa03

...
...
"I/O-1-15" prio=5 Id=83 BLOCKED on java.lang.Thread$ThreadLock@3c56b07e owned by "I/O-1-2" Id=70
	at java.base@11.0.17/java.lang.Thread.getState(Thread.java:1334)
	at app//io.netty.util.Recycler$LocalPool.release(Recycler.java:344)
	at app//io.netty.util.Recycler$DefaultHandle.unguardedRecycle(Recycler.java:265)
	at app//io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry.unguardedRecycle(PoolThreadCache.java:476)
	at app//io.netty.buffer.PoolThreadCache$MemoryRegionCache.allocate(PoolThreadCache.java:396)
	at app//io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:168)
	at app//io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:152)
	at app//io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:151)
	at app//io.netty.buffer.PoolArena.allocate(PoolArena.java:137)
	at app//io.netty.buffer.PoolArena.allocate(PoolArena.java:129)
	at app//io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396)
	at app//io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at app//io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at app//io.netty.channel.unix.PreferredDirectByteBufAllocator.ioBuffer(PreferredDirectByteBufAllocator.java:53)
	at app//io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:120)
	at app//io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:75)
	at app//io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:785)
	at app//io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.17/java.lang.Thread.run(Thread.java:839)

	Locked ownable synchronizers: 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@3357f3a8
...
...
"I/O-1-19" prio=5 Id=87 BLOCKED on java.lang.Thread$ThreadLock@94081081 owned by "I/O-1-1" Id=69
	at java.base@11.0.17/java.lang.Thread.getState(Thread.java:1334)
	at app//io.netty.util.Recycler$LocalPool.release(Recycler.java:344)
	at app//io.netty.util.Recycler$DefaultHandle.recycle(Recycler.java:257)
	at app//io.netty.channel.AbstractChannelHandlerContext$WriteTask.recycle(AbstractChannelHandlerContext.java:1273)
	at app//io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1250)
	at app//io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.17/java.lang.Thread.run(Thread.java:839)

	Locked ownable synchronizers: 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@8f4ea206
...
...
"I/O-1-23" prio=5 Id=91 BLOCKED on java.lang.Thread$ThreadLock@3c56b07e owned by "I/O-1-2" Id=70
	at java.base@11.0.17/java.lang.Thread.getState(Thread.java:1334)
	at app//io.netty.util.Recycler$LocalPool.release(Recycler.java:344)
	at app//io.netty.util.Recycler$DefaultHandle.unguardedRecycle(Recycler.java:265)
	at app//io.netty.buffer.PoolThreadCache$MemoryRegionCache$Entry.unguardedRecycle(PoolThreadCache.java:476)
	at app//io.netty.buffer.PoolThreadCache$MemoryRegionCache.allocate(PoolThreadCache.java:396)
	at app//io.netty.buffer.PoolThreadCache.allocate(PoolThreadCache.java:168)
	at app//io.netty.buffer.PoolThreadCache.allocateSmall(PoolThreadCache.java:152)
	at app//io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:151)
	at app//io.netty.buffer.PoolArena.allocate(PoolArena.java:137)
	at app//io.netty.buffer.PoolArena.allocate(PoolArena.java:129)
	at app//io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396)
	at app//io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	at app//io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at app//io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:2265)
	at app//io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1348)
	at app//io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1257)
	at app//io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1297)
	at app//io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at app//io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at app//io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at app//io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at app//io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at app//io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at app//io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at app//io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
	at app//io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499)
	at app//io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base@11.0.17/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.17/java.lang.Thread.run(Thread.java:839)

	Locked ownable synchronizers: 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@d94468a7
```

**Comment by franz1981** [comment]
> are blocked in the thread dump

Java version: 11 (IBM OpenJ9) that's why: I would open a bug to "them": it seems J9 `Thread.getStateImpl` got some weird scalability problem due to this
![image](https://user-images.githubusercontent.com/13125299/233767696-5941d398-ed72-4f33-aba9-dcdfe3f9aeac.png)

@chrisvest 
```java
void release(DefaultHandle<T> handle, boolean guarded) {
            if (guarded) {
                handle.toAvailable();
            } else {
                handle.unguardedToAvailable();
            }
            Thread owner = this.owner;
            if (owner != null && Thread.currentThread() == owner && batch.size() < chunkSize) {
                accept(handle);
            } else if (owner != null && owner.getState() == Thread.State.TERMINATED) {
                this.owner = null;
                pooledHandles = null;
            } else {
                MessagePassingQueue<DefaultHandle<T>> handles = pooledHandles;
                if (handles != null) {
                    handles.relaxedOffer(handle);
                }
            }
        }
```
I've never expected 
```java
       } else if (owner != null && owner.getState() == Thread.State.TERMINATED) {
```
to be a scalability bottleneck on J9 :O It's surprising and a bit horrible.

I would suggest to use a different JDK version from other vendors in the meantime, for better performance OR
you can receive a performance hit and disable pooling by adding
```
-Dio.netty.recycler.maxCapacityPerThread=0
```
to your JVM application parameters.

Just to double check @onlynishant you didn't have any similar problem with Netty?
Which version you were running before, if any?

**Comment by onlynishant** [comment]
> I would suggest to use a different JDK version from other vendors in the meantime

Let me try another vendor. Any recommendation? The main reason we use OpenJ9 is that it's `concurrentScavenge` GC policy performs much better than other gc policy of openJDK like G1GC or even ZGC on our workload (3M req/sec).

> Just to double check @onlynishant you didn't have any similar problem with Netty?
Which version you were running before, if any?

We were using `4.1.86.Final` earlier and we had issue in that version also

**Comment by franz1981** [comment]
Thanks for confirming @onlynishant whatever that's not using J9

**Comment by franz1981** [comment]
If you have any performance metrics you. An share when will work would be great :) we have spent tons of cycles on improving http 1.1 and pipeline traversal with many cores

**Comment by franz1981** [comment]
@mcraveiro this is still a bug that worth fixing IMO

**Comment by franz1981** [comment]
@onlynishant 
> we had issue in that version also

This same problem?

**Comment by onlynishant** [comment]
@franz1981 we did have scaling issue but not able to recall if root cause was the same. once I will able to fix the issue, I will try to run it with old Netty version and will share the details.

> If you have any performance metrics you can share when will work would be great :) 

sure. I am currently running some test with openJDK 17. I will share the data if it will be stable for few days.

Thanks.

**Comment by franz1981** [comment]
Many thanks @onlynishant !

**Comment by franz1981** [comment]
Just FYI you can profile your app with `-e lock` and you will able to see the exact lock contended (that we know already sadly!!)

**Comment by chrisvest** [comment]
>  it seems J9 Thread.getStateImpl got some weird scalability problem

Jeez. We went this route to get away from reference processing overhead.

From the code, it looks like [`Thread.isAlive`](https://github.com/eclipse-openj9/openj9/blob/03967d8cc24dc1f60168110c9d207d2dff57765a/jcl/src/java.base/share/classes/java/lang/Thread.java#L756-L761) will fare better than [`Thread.getState`](https://github.com/eclipse-openj9/openj9/blob/55b9267740559406b8471000cd3a3b6f681dc095/runtime/jcl/common/thread.cpp#L76-L102) on J9.
Looks [pretty cheap](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/lang/Thread.java#L1798-L1815) in openjdk as well.

**Comment by franz1981** [comment]
@chrisvest thanks Chris, let's go with this then +100

**Comment by onlynishant** [comment]
Any help to fix the other 2 SSL-related errors?

```
2023-04-22 21:27:44.895 [ERROR] [Handler-Worker-Thread-3-167] io.pawan.core.handler.HttpEndServer:exceptionCaught(60): An exception is thrown. msg: javax.net.ssl.SSLHandshakeException: error:10000070:SSL routines:OPENSSL_internal:BAD_PACKET_LENGTH

2023-04-22 21:27:44.645 [ERROR] [Handler-Worker-Thread-3-161] io.pawan.core.handler.HttpEndServer:lambda$sendResponse$0(162): Write error. msg: SSLEngine closed already
```
