### ISSUE TITLE
WriteTask can use unguarded release?

### ISSUE THREAD

**Issue by franz1981** [netty/netty#13356]
https://github.com/netty/netty/issues/13153 improved buffer releases, but WriteTask was left out, see 
```java
at app//io.netty.util.Recycler$LocalPool.release(Recycler.java:344)
	at app//io.netty.util.Recycler$DefaultHandle.recycle(Recycler.java:257)
	at app//io.netty.channel.AbstractChannelHandlerContext$WriteTask.recycle(AbstractChannelHandlerContext.java:1273)
	at app//io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1250)
```
@normanmaurer @chrisvest wdyt?

**Comment by normanmaurer** [comment]
@franz1981 sounds ok to me... @chrisvest thoughts ?

**Comment by chrisvest** [comment]
@franz1981 @normanmaurer I don't see a problem with doing that.

**Comment by normanmaurer** [comment]
@franz1981 its still on your radar ?
