### ISSUE TITLE
Netty faulty channel failed due to failed to handshake with servers within 10000ms

### ISSUE THREAD

**Issue by soullkk** [netty/netty#13401]
### Expected behavior

Netty client successfully handshake with servers

### Actual behavior
```
2023-04-02 08:45:46,931 WARN  [qtp1319386445-175[groupBy_[ODAEDATASET__DEFAULT_tbl_data_res_1010_1__DEFAULT]_4a84cfcd-c0bf-447a-9017-638bb1f59291]][][org.apache.druid.java.util.http.client.NettyHttpClient] Netty faulty channel failed!!!
org.jboss.netty.channel.ChannelException: Failed to handshake with host[https://x.x.x.x:26202]
        at org.apache.druid.java.util.http.client.pool.ChannelResourceFactory$2$1.operationComplete(ChannelResourceFactory.java:157) ~[druid-core-0.21.1-h0.gdd.sop.r49.jar:?]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1461) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.ssl.SslHandler.access$200(SslHandler.java:180) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.ssl.SslHandler$1.run(SslHandler.java:372) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.6.Final.jar:?]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
Caused by: javax.net.ssl.SSLException: Handshake did not complete within 10000ms
        ... 6 more

Caused by: org.jboss.netty.channel.ChannelException: Failed to handshake with host[https://x.x.x.x:26202]
        at org.apache.druid.java.util.http.client.pool.ChannelResourceFactory$2$1.operationComplete(ChannelResourceFactory.java:157) ~[druid-core-0.21.1-h0.gdd.sop.r49.jar:?]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:395) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1461) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.ssl.SslHandler.access$200(SslHandler.java:180) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.handler.ssl.SslHandler$1.run(SslHandler.java:372) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.6.Final.jar:?]
        ... 1 more
Caused by: javax.net.ssl.SSLException: Handshake did not complete within 10000ms
        at org.jboss.netty.handler.ssl.SslHandler$1.run(SslHandler.java:372) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369) ~[netty-3.10.6.Final.jar:?]
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) ~[netty-3.10.6.Final.jar:?]
        ... 1 more
```

### Steps to reproduce
Issue happens very intermittently and is difficult to reproduce on-demand.

The exception description in the source code：org.jboss.netty.handler.ssl.SslHandler#handshake
I have added some logs in the following methods.

**handshake():**
logger.warn("test0522, begin handshake, channel is " + channel + " current system time is " + System.currentTimeMillis());
engine.beginHandshake();
...
logger.warn("test0522, wrapNonAppData, current system time is " + System.currentTimeMillis());
wrapNonAppData(ctx, channel).addListener(new ChannelFutureListener() {

**wrapNonAppData():**
for (;;) {
logger.warn("test0522, method wrapNonAppData, loop1");
...
msg.writeBytes(outNetBuf);
logger.warn("test0522, method wrapNonAppData, msg is " + msg.toString(Charset.defaultCharset()));
...
switch (handshakeStatus) {
case FINISHED:
logger.warn("test0522, method wrapNonAppData, case finished" + " current system time is " + System.currentTimeMillis());
case NEED_TASK:
logger.warn("test0522, method wrapNonAppData, case need_task" + " current system time is " + System.currentTimeMillis());
case NEED_UNWRAP:
logger.warn("test0522, method wrapNonAppData, case need_unwrap" + " current system time is " + System.currentTimeMillis());
case NOT_HANDSHAKING:
logger.warn("test0522, method wrapNonAppData, case not_handshaking" + " current system time is " + System.currentTimeMillis());
case NEED_WRAP:
logger.warn("test0522, method wrapNonAppData, case need_wrap" + " current system time is " + System.currentTimeMillis());

**unwrap():**
Location of logs is similar to method of wrapNonAppData():

**The log is as follows：**

```
2023-05-24 06:34:52,602 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, begin handshake, channel is [id: 0x033c684b, /192.168.0.3:36631 => /192.168.0.3:26202] current system time is 1684910092602
2023-05-24 06:34:52,604 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, wrapNonAppData, current system time is 1684910092604
2023-05-24 06:34:52,604 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, loop1
2023-05-24 06:34:52,604 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, msg is 
2023-05-24 06:34:52,604 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, case need_unwrap current system time is 1684910092604
2023-05-24 06:34:52,604 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, loop1
2023-05-24 06:34:52,604 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, case need_unwrap current system time is 1684910092604
2023-05-24 06:34:52,604 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, bytebytesProduced == 0
2023-05-24 06:34:53,201 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method unwrap, loop1
2023-05-24 06:34:53,201 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method unwrap, loop2
2023-05-24 06:34:53,201 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method unwrap, need task, current system time is 1684910093201
2023-05-24 06:34:53,203 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method unwrap, loop1
2023-05-24 06:34:53,203 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method unwrap, loop2
2023-05-24 06:34:53,203 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method unwrap, need wrap, current system time is 1684910093203
2023-05-24 06:34:53,203 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, loop1
2023-05-24 06:34:53,203 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, msg is 
2023-05-24 06:34:53,203 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, case need_unwrap current system time is 1684910093203
2023-05-24 06:34:53,203 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, loop1
2023-05-24 06:34:53,203 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, case need_unwrap current system time is 1684910093203
2023-05-24 06:34:53,203 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] test0522, method wrapNonAppData, bytebytesProduced == 0
2023-05-24 06:34:53,207 WARN  [HttpClient-Netty-Worker-7][ROOT][org.jboss.netty.handler.ssl.SslHandler] Unexpected leftover data after SSLEngine.unwrap(): status=OK handshakeStatus=NEED_WRAP consumed=0 produced=0 remaining=1274 data=14030300010117030304efe11316516dd791753535e79190433e87a54104958b1719b9185db4330fc2a4cb7dffea7b14879d1d45c09a66925671cc2d86bd7ab3d22fac809841dee58fc7ab939f89fdca5f80441dd2da5832ec9681b85960b3d9423a79a568e1ebd5a51933bbea4b5dd630b956c7f28f9ef424a5fb612b828f0630af00532c7cf2d468055586bf15527ea89d377935b3dad65a770cf82915bcc32bb24965f02ac3d8a679383d8be49da17d6afc6512d628ebd27df25d912a8292a5e69ee294e496e0e1c826ff84b526d37983e8cc02c3e9c7cd5f2451edbb718799982e854abc199fe68e845a6fb18550cf9a712411233234abf82a0956fd99ffab701005a92ee30ae31a7a2b1a54fd12392763fd5c3a2a094684274dce890bb03e3df38563254b2508b4f7a84e7f05b628c8b73a1546dfed66c28ddede264c19634474ec46b5f5732de9ff8fdc8bc40e41c114fc320d2d489a400ed0271f2761e98c2634e7d4b6231ebac124e0f67a32762f3095cfdac6144ec32361b9136a83f82b868f0c8e60a69e841b4cba1bbbb854473e3dc16cff91d365f1cc21fdacf58128693c376ff1d59569b89d822eae63a04f44c369a182cb6a0c5a70a995ddaecad3aa585c60f42f5c1c94d0197bf99427b65f9b6942cb1e4cd42c858744cc96c2e98e0b3765aad904138a7a9292a420867546c255118a97616f414a21f66ab14905ae1d588b09d2cdf4e8ede8f6500c169d532f1196b7457df811a66f1eb0c93de0df1966dd1989b92afe96c5660eaedf633cf9128b247e38dd4b4e684fe94d5114ebcb36bf950130c0f05ad621b669428ec3aa7fda01b23004df5a1bd050713a69a4d16aa506f849be2e7892db7e96cda6c7f9403b059cc86468e762a559c51d571e7105302ec9a3737d906773e816865799b37ca7674093ee037e05e69f9ca64a8cd6bec048615a5592b807e1cd9d165c7cc000c5f58bf7982ee247b1c472bc87f73c6c2ad4db68031528eebf98cf653ecabc029977fb8df31f46df086816c8fa86b466345699d1860d1f8309bcbee9d24041d576cfece3b4e4413e36cccea9226ca27a6a6768a63e6a656d1935182640818e916378c49e65998fcff3522a5319bf536b03c82d7a56c3eb8d75eba71560c284e0dc6711185f088438ea4ecbdf377e972d73ac319b985d3d47e4562cc44bdc9b6cd1b9015d6c0c34289021865cf81ec7e826682758b9124fbcc874b49bc6c90aef4ded8d563205bb303fec68fe38f5821ca932f8659b530b39897982f9d17e29dd8b69d9dfa54efba38646f41bb822002dad33d8782e5bd59320130a02be353a55980e8c4e87dc173bf3d1b12a8815cf595befe3890bb8a57e03d51a5ce7e4721c426f2929e01bbf5ff1f5d32a6e88b5e41b62ea10252b396673f89c6c101ce6df67
f1ce10be6df7a3fca164b6f33a372d4a133b841ad01833cf4c1848af00f10e161b6b6ec93a77e0e8e9ca321599bddc25d2e55d476e7283c3af6aaa632af62dac272e7b2b06be8e68eef2c643b96ffb7c3b0bca455d6ae51ebb61f8841ed958186ca473cd2168b58db46ba79b8d4db122cce672a4965e042e14aca01f7f3cd5e9cc8b686f2686aecbd3bcfe80f98e73f6f9ea079f44e65eb7399f806fc1971d72219
254226f3bb20f1fccaacfb879614f37d8b02d05fc679a51fd3c1ad2fbbeae5bfd7f7affe8eee91f0eabe8fee7fcece491503c6db353bbb38ddab6392d1a399de1836499b284c6355f8d8fab66b299e289572ba9f99b091f223cf25e7262708b9086ad
```

I tried to grab the handshake timeout packets and found that the client closed the connection after the Change Cipher Spec. client port is 36631, server port is 26202
![image](https://github.com/netty/netty/assets/55041925/49edb659-5a23-45b1-8409-1d3492ef06a5)

### Netty version
3.10.6
### JVM version (e.g. `java -version`)
jre-24.10.652-euler_arm64
### OS version (e.g. `uname -a`)
eulerosv2r11.aarch64

**Comment by soullkk** [comment]
The message with number 66013 is a reset message.
![image](https://github.com/netty/netty/assets/55041925/c7453da9-40cd-49e2-80c4-bdaea2bdf5b2)

**Comment by chrisvest** [comment]
You're gonna have to upgrade to the latest Netty 4.1.
We don't support Netty 3 anymore.

**Comment by soullkk** [comment]
Do you have any suggestions to help me continue analyzing this issue, please

**Comment by soullkk** [comment]
Please give me some suggestions to continue analyzing this issue. 
Apache Druid uses version 3.10.6 and cannot be upgrade to version 4.1 at the moment.

**Comment by normanmaurer** [comment]
Sorry but the only thing I can tell you is that the handshake was not completed within the timeout. Like @chrisvest said, this version is EOL for years. We dont support it anymore

**Comment by jwelevate** [comment]
Hello, are you able to find some workaround for the issue?

**Comment by soullkk** [comment]
> Hello, are you able to find some workaround for the issue?

When we used netty 3.10.6-Final and TLS 1.3, we found that SSL handshake accidentally failed. We reduced TLS version to 1.2 to solve this problem

**Comment by jwelevate** [comment]
thanks, that helps.

**Comment by rookieuncle** [comment]
> > 您好，您能找到解决该问题的方法吗？
> 
> 当我们使用netty 3.10.6-Final和TLS 1.3时，我们发现SSL握手意外失败。我们将 TLS 版本降低到 1.2 来解决这个问题

Thank you. In Apache Druid, I also encountered the same problem, which was very helpful to me

**Comment by soullkk** [comment]
> > > 您好，您能找到解决该问题的方法吗？
> > 
> > 
> > 当我们使用netty 3.10.6-Final和TLS 1.3时，我们发现SSL握手意外失败。我们将 TLS 版本降低到 1.2 来解决这个问题
> 
> Thank you. In Apache Druid, I also encountered the same problem, which was very helpful to me

> We also encountered this problem in Apache Druid at the beginning

**Comment by rookieuncle** [comment]
> > > > 您好，您能找到解决该问题的方法吗？
> > > 
> > > 
> > > 当我们使用netty 3.10.6-Final和TLS 1.3时，我们发现SSL握手意外失败。我们将TLS版本降到1.2来解决这个问题
> > 
> > 
> > 谢谢。在Apache Druid中，我也遇到了同样的问题，这对我很有帮助
> 
> > 我们一开始在Apache Druid中也遇到过这个问题

Sorry, I couldn't find a solution
