### ISSUE TITLE
Socksproxy example is suspected of having a memory leak

### ISSUE THREAD

**Issue by selcarpa** [netty/netty#13422]
### Expected behavior

Automatically release memory

### Actual behavior

Direct Memory Leak

### Steps to reproduce

I ran the socksproxy example project, setting the jvm parameters.
```
-Xmx200M -XX:MaxDirectMemorySize=50M -Dio.netty.leakDetection.level=PARANOID -Dio.netty.resourceLeakDetection
```

Then I start the edge browser and use socks5 to proxy the traffic.

Then use https://github.com/openspeedtest/Speed-Test to perform a proxy speed test. It was normal at first, when the test progressed to upload. There is a direct memory growth as shown in the figure, and it will not be released

![image](https://github.com/netty/netty/assets/25505798/0121b170-9b41-457a-868f-346bd2487f37)

Please tell me why it happened and how to solve it.

### Minimal yet complete reproducer code (or URL to code)

https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/socksproxy

### Netty version

4.1.92.Final-SNAPSHOT

### JVM version (e.g. `java -version`)

JVM: OpenJDK 64-Bit Server VM (11.0.19+7-LTS, mixed mode)
Java: version 11.0.19 2023-04-18 LTS, vendor Azul Systems, Inc.
Java Home: C:\Users\at\.jdks\azul-11.0.19

### OS version (e.g. `uname -a`)

Windows11

**Comment by franz1981** [comment]
If there are no logs related memory leaks (reported stack traces) is unlikely there is any leak on Netty side. Let us know if you find anything suspicious in the logs

**Comment by selcarpa** [comment]
> If there are no logs related memory leaks (reported stack traces) is unlikely there is any leak on Netty side. Let us know if you find anything suspicious in the logs

After using these two parameters, netty did not report any memory leaks.
```
-Dio.netty.leakDetection.level=PARANOID -Dio.netty.resourceLeakDetection
```
So I'm not too sure whether it's because of netty itself or because of the example.

**Comment by franz1981** [comment]
> So I'm not too sure whether it's because of netty itself or because of the example.

In either case I would say it's not a Netty thing.
One common misconception related Netty allocators is that it an release back memory to the Operating System: it won't.
When it grows it keep on growing to accommodate the maximum load, regardless which direct memory settings are used, or failing with OutOfMemory if beyond such.
If your memory just keep on growing until certain limits ( ie not unbounded) then is perfectly fine and it is not a problem.

**Comment by selcarpa** [comment]
> In either case I would say it's not a Netty thing. One common misconception related Netty allocators is that it an release back memory to the Operating System: it won't. When it grows it keep on growing to accommodate the maximum load, regardless which direct memory settings are used, or failing with OutOfMemory if beyond such. If your memory just keep on growing until certain limits ( ie not unbounded) then is perfectly fine and it is not a bug.

But here netty not only does not release memory to the operating system, but also does not collect direct memory for reuse, and it has been kept occupied.
Perhaps I have misunderstood netty's memory recovery method.
Thank you for your answer, I'm doing some more testing around this issue.

**Comment by franz1981** [comment]
@selcarpa you can print at interval the pinned memory used by the pooled allocators and you can see if memory grow unfounded or not (although it should fail with some OOM killer at OS level first, likely).
If Netty is not reusing the memory it should grow unbounded under further steady load.

**Comment by selcarpa** [comment]
```java
public final class SocksServer {

    ...

    public static void main(String[] args) throws Exception {
        ...
        new Thread() {
            @Override
            public void run() {
                memStat();
            }
        }.start();
      ...
    }

    private static void memStat() {
        Executors.newSingleThreadScheduledExecutor().scheduleAtFixedRate(
                new Runnable() {
                    @Override
                    public void run() {
                        ByteBufAllocatorMetric metric = ((ByteBufAllocatorMetricProvider) ByteBufAllocator.DEFAULT).metric();
                        System.out.println("Direct: " + metric.usedDirectMemory() + ", Heap: " + metric.usedHeapMemory());
                    }
                }, 0, 1, java.util.concurrent.TimeUnit.SECONDS
        );
    }
}

```
I added these codes to https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/socksproxy/SocksServer.java
And changed the startup parameters
```
-Xmx4000M -Dio.netty.leakDetection.level=PARANOID -Dio.netty.resourceLeakDetection
```

Still use https://github.com/openspeedtest/Speed-Test to test, this is the printed, when memory reaches 536870912, it will not change

```log
Connected to the target VM, address: '127.0.0.1:6425', transport: 'socket'
Direct: 0, Heap: 0
Direct: 0, Heap: 0
22:49:33.621 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942] REGISTERED
22:49:33.630 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942] BIND: 0.0.0.0/0.0.0.0:1080
22:49:33.635 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] ACTIVE
22:49:33.758 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0x4be01c88, L:/127.0.0.1:1080 - R:/127.0.0.1:6481]
22:49:33.760 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
22:49:33.959 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0x13ddc8f8, L:/127.0.0.1:1080 - R:/127.0.0.1:6480]
22:49:33.960 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
Direct: 8388608, Heap: 0
Direct: 8388608, Heap: 0
Direct: 8388608, Heap: 0
Direct: 8388608, Heap: 0
Direct: 8388608, Heap: 0
Direct: 8388608, Heap: 0
Direct: 8388608, Heap: 0
Direct: 8388608, Heap: 0
22:49:41.463 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0xb4eeb029, L:/127.0.0.1:1080 - R:/127.0.0.1:6486]
22:49:41.463 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
22:49:41.770 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0x1e399b57, L:/127.0.0.1:1080 - R:/127.0.0.1:6488]
22:49:41.770 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
22:49:42.076 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0x9d855687, L:/127.0.0.1:1080 - R:/127.0.0.1:6492]
22:49:42.077 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
Direct: 20971520, Heap: 0
22:49:42.363 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0x8a3a52c9, L:/127.0.0.1:1080 - R:/127.0.0.1:6494]
22:49:42.364 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
java.io.IOException: 你的主机中的软件中止了一个已建立的连接。
	at java.base/sun.nio.ch.SocketDispatcher.read0(Native Method)
	at java.base/sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:233)
	at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:223)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:356)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:256)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
	at io.netty.buffer.WrappedByteBuf.writeBytes(WrappedByteBuf.java:821)
	at io.netty.buffer.AdvancedLeakAwareByteBuf.writeBytes(AdvancedLeakAwareByteBuf.java:636)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
Direct: 25165824, Heap: 0
22:49:58.893 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0x8613c619, L:/127.0.0.1:1080 - R:/127.0.0.1:6502]
22:49:58.894 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
22:49:59.129 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0x81d5cc0e, L:/127.0.0.1:1080 - R:/127.0.0.1:6504]
22:49:59.130 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
Direct: 109051904, Heap: 0
22:49:59.431 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0x70f52a61, L:/127.0.0.1:1080 - R:/127.0.0.1:6506]
22:49:59.432 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
22:49:59.729 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0x66cb0880, L:/127.0.0.1:1080 - R:/127.0.0.1:6508]
22:49:59.729 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
22:50:00.030 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0xf70d4152, L:/127.0.0.1:1080 - R:/127.0.0.1:6510]
22:50:00.030 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
22:50:00.064 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ: [id: 0xb621073e, L:/127.0.0.1:1080 - R:/127.0.0.1:6512]
22:50:00.064 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x1f153942, L:/0:0:0:0:0:0:0:0:1080] READ COMPLETE
Direct: 293601280, Heap: 0
Direct: 419430400, Heap: 0
Direct: 562036736, Heap: 0
Direct: 675282944, Heap: 0
Direct: 738197504, Heap: 0
Direct: 775946240, Heap: 0
Direct: 775946240, Heap: 0
Direct: 775946240, Heap: 0
Direct: 826277888, Heap: 0
Direct: 843055104, Heap: 0
Direct: 830472192, Heap: 0
Direct: 868220928, Heap: 0
Direct: 864026624, Heap: 0
Direct: 855638016, Heap: 0
Direct: 855638016, Heap: 0
Direct: 855638016, Heap: 0
Direct: 834666496, Heap: 0
Direct: 813694976, Heap: 0
Direct: 805306368, Heap: 0
Direct: 780140544, Heap: 0
Direct: 763363328, Heap: 0
Direct: 738197504, Heap: 0
Direct: 717225984, Heap: 0
Direct: 692060160, Heap: 0
Direct: 671088640, Heap: 0
Direct: 641728512, Heap: 0
Direct: 612368384, Heap: 0
Direct: 583008256, Heap: 0
Direct: 553648128, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
Direct: 536870912, Heap: 0
```

Is it as expected

**Comment by chrisvest** [comment]
I recommend you also log `PooledByteBufAllocator.pinnedDirectMemory` — this will show the memory that's in use by direct buffers. This is in contrast to the used memory, which is what the pool has taken up. There's also a version for heap memory.
Pinned memory should go up and down as buffers are allocated and released, while used memory will only grow due to pooling.

**Comment by selcarpa** [comment]
> I recommend you also log `PooledByteBufAllocator.pinnedDirectMemory` — this will show the memory that's in use by direct buffers. This is in contrast to the used memory, which is what the pool has taken up. There's also a version for heap memory. Pinned memory should go up and down as buffers are allocated and released, while used memory will only grow due to pooling.

It is indeed so, I printed this part, it is indeed "go up and down as buffers are allocated and released".
What puzzles me is that the direct memory keeps rising until OutOfMemory. I am learning this part and trying to find out the reason.
Thanks

**Comment by WhiteTrashLord** [comment]
I am sure that there is some problem with the example code. I suspect this weird "Promise<Channel>" code.

I had the same problem a while ago https://github.com/netty/netty/issues/12115

**Comment by 15989206052** [comment]
> > I recommend you also log `PooledByteBufAllocator.pinnedDirectMemory` — this will show the memory that's in use by direct buffers. This is in contrast to the used memory, which is what the pool has taken up. There's also a version for heap memory. Pinned memory should go up and down as buffers are allocated and released, while used memory will only grow due to pooling.
> 
> It is indeed so, I printed this part, it is indeed "go up and down as buffers are allocated and released". What puzzles me is that the direct memory keeps rising until OutOfMemory. I am learning this part and trying to find out the reason. Thanks

yes, I also printed pinnedDirectMemory and usedDirectMemory, pinnedDirectMemory remain very low but OutOfMemory, did you find the root cause now?

![Image](https://github.com/user-attachments/assets/65862e43-5164-4a4a-9b7a-f9f836f4175a)
