### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: 'int io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errorEHOSTUNREACH()

### ISSUE THREAD

**Issue by jam49** [netty/netty#13447]
### Expected behavior

Should work on debian, doesnt, same jar works on macos.

### Actual behavior

Caused by: java.lang.UnsatisfiedLinkError: 'int io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errorEHOSTUNREACH()
```
Unable to connect to registry service, attempt 1 of 3 UNKNOWN java.lang.UnsatisfiedLinkError: 'int io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errorEHOSTUNREACH()'
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.822+0000] {subprocess.py:93} INFO - io.grpc.StatusRuntimeException: UNKNOWN
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.822+0000] {subprocess.py:93} INFO - 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:240)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.823+0000] {subprocess.py:93} INFO - 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:221)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.823+0000] {subprocess.py:93} INFO - 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:140)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.823+0000] {subprocess.py:93} INFO - 	at com.ibm.datahub.registry.proto.JobInstanceServiceGrpc$JobInstanceServiceBlockingStub.get(JobInstanceServiceGrpc.java:448)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.823+0000] {subprocess.py:93} INFO - 	at com.ibm.cedp.advtech.datamovement.analyticsengine.RegistryGrpc.publishJobMetrics(RegistryGrpc.java:25)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.824+0000] {subprocess.py:93} INFO - 	at com.ibm.cedp.advtech.datamovement.analyticsengine.AnalyticsEngineManager.reportCounts(AnalyticsEngineManager.java:548)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.824+0000] {subprocess.py:93} INFO - 	at com.ibm.cedp.advtech.datamovement.analyticsengine.AnalyticsEngineProcessor.runJob(AnalyticsEngineProcessor.java:287)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.824+0000] {subprocess.py:93} INFO - 	at com.ibm.cedp.advtech.datamovement.analyticsengine.AnalyticsEngineProcessor.validateConfiguration(AnalyticsEngineProcessor.java:228)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.824+0000] {subprocess.py:93} INFO - 	at com.ibm.cedp.advtech.datamovement.DMTProcessor.execute(DMTProcessor.java:45)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.824+0000] {subprocess.py:93} INFO - 	at com.ibm.cedp.advtech.datamovement.DMTProcessor.main(DMTProcessor.java:27)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.825+0000] {subprocess.py:93} INFO - Caused by: java.lang.UnsatisfiedLinkError: 'int io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errorEHOSTUNREACH()'
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.825+0000] {subprocess.py:93} INFO - 	at io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errorEHOSTUNREACH(Native Method)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.825+0000] {subprocess.py:93} INFO - 	at io.netty.channel.unix.Errors.<clinit>(Errors.java:62)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.825+0000] {subprocess.py:93} INFO - 	at io.netty.channel.unix.Socket.connect(Socket.java:351)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.826+0000] {subprocess.py:93} INFO - 	at io.netty.channel.epoll.AbstractEpollChannel.doConnect0(AbstractEpollChannel.java:773)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.826+0000] {subprocess.py:93} INFO - 	at io.netty.channel.epoll.EpollSocketChannel.doConnect0(EpollSocketChannel.java:138)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.826+0000] {subprocess.py:93} INFO - 	at io.netty.channel.epoll.AbstractEpollChannel.doConnect(AbstractEpollChannel.java:758)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.826+0000] {subprocess.py:93} INFO - 	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.connect(AbstractEpollChannel.java:600)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.827+0000] {subprocess.py:93} INFO - 	at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1342)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.827+0000] {subprocess.py:93} INFO - 	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:653)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.827+0000] {subprocess.py:93} INFO - 	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:632)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.827+0000] {subprocess.py:93} INFO - 	at io.netty.channel.ChannelDuplexHandler.connect(ChannelDuplexHandler.java:54)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.828+0000] {subprocess.py:93} INFO - 	at io.grpc.netty.WriteBufferingAndExceptionHandler.connect(WriteBufferingAndExceptionHandler.java:150)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.828+0000] {subprocess.py:93} INFO - 	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:655)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.828+0000] {subprocess.py:93} INFO - 	at io.netty.channel.AbstractChannelHandlerContext.access$1000(AbstractChannelHandlerContext.java:61)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.828+0000] {subprocess.py:93} INFO - 	at io.netty.channel.AbstractChannelHandlerContext$9.run(AbstractChannelHandlerContext.java:637)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.828+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.829+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.829+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.829+0000] {subprocess.py:93} INFO - 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.829+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.830+0000] {subprocess.py:93} INFO - 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.830+0000] {subprocess.py:93} INFO - 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-06-15T00:07:57Z -3- analytics_engine_manager : [2023-06-15T00:07:57.830+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:833)
```
### Steps to reproduce

basic grpc call on debian.

### Netty version
```
mvn dependency:tree | grep netty
[INFO] |  +- io.grpc:grpc-netty:jar:1.27.0:compile
[INFO] |  +- io.netty:netty-tcnative-boringssl-static:jar:2.0.48.Final:compile
[INFO] |  |  \- io.netty:netty-tcnative-classes:jar:2.0.48.Final:compile
[INFO] |  +- io.netty:netty-transport:jar:4.1.91.Final:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.91.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.91.Final:compile
[INFO] |  |  \- io.netty:netty-resolver:jar:4.1.91.Final:compile
[INFO] |  +- io.netty:netty-codec:jar:4.1.91.Final:compile
[INFO] |  +- io.netty:netty-handler:jar:4.1.91.Final:compile
[INFO] |  |  \- io.netty:netty-transport-native-unix-common:jar:4.1.91.Final:compile
[INFO] |  +- io.netty:netty-codec-http:jar:4.1.91.Final:compile
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.91.Final:compile
[INFO] |  +- io.netty:netty-codec-socks:jar:4.1.91.Final:compile
[INFO] |  +- io.netty:netty-handler-proxy:jar:4.1.91.Final:compile
[INFO] |  |  +- io.netty:netty-all:jar:4.1.74.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-classes-epoll:jar:4.1.74.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-classes-kqueue:jar:4.1.74.Final:compile
[INFO] |  |  |  +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.74.Final:runtime
[INFO] |  |  |  +- io.netty:netty-transport-native-epoll:jar:linux-aarch_64:4.1.74.Final:runtime
[INFO] |  |  |  +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.74.Final:runtime
[INFO] |  |  |  \- io.netty:netty-transport-native-kqueue:jar:osx-aarch_64:4.1.74.Final:runtime
[INFO] |  |  \- org.apache.arrow:arrow-memory-netty:jar:7.0.0:compile
```

### JVM version (e.g. `java -version`)

does the same thing on java 11 and 8

java -version
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode, sharing)

java -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (build 17.0.7+7-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.7+7-Debian-1, mixed mode, sharing)
 echo $JAVA_HOME
/usr/lib/jvm/java-8-openjdk-amd64/

### OS version (e.g. `uname -a`)

uname -a
Linux airflow-worker-0 3.10.0-1160.88.1.el7.x86_64 #1 SMP Sat Feb 18 13:27:00 UTC 2023 x86_64 GNU/Linux

**Comment by jam49** [comment]
The issue would seem to indicate a missing or mismatched native library, but no indication as to which one.

**Comment by chrisvest** [comment]
I'd start by upgrading all the 4.1.74 dependencies to 4.1.91.
Using the netty-bom can help you keep all your Netty dependencies in order.

**Comment by jam49** [comment]
I'll try making them all the same, however this works fine on macOs.

**Comment by chrisvest** [comment]
Perhaps your macOS runs just never needed to go through the code path handling connection errors. Or you used the Nio transport on macOS.

**Comment by chrisvest** [comment]
Have you gotten a `NoRouteToHostException` on macOS with the kqueue transport?

**Comment by jam49** [comment]
grpc is choosing the transport so no. perhaps a dumb question. how does netty figure out which native lib to use? at runtime or build time? anyway i think i got it working. undoing numerous changes to try and figure out what fixed it.

**Comment by chrisvest** [comment]
The transport used is explicitly configured. Netty requires that integrators (grpc in this case, probably) choose event loop and channel implementations. This happens at runtime.

If you didn't see a native error on macOS, then the `Errors` classes likely hasn't been initialized, because class initialization is lazy in Java, and that explains why you haven't gotten an `UnsatisfiedLinkError` on macOS, even though your dependencies have mismatched versions.

**Comment by jam49** [comment]
yeah thx, that is what it is looking like. running another test using only the 91 version.

**Comment by jam49** [comment]
works, as chris says make sure all your netty versions are the same.
