### ISSUE TITLE
Dose DomainSocketAddress support Android

### ISSUE THREAD

**Issue by BFELFISH** [netty/netty#13479]
I want to set up a Grpc Server on Android with Unix Domain Socket.But if I use DomainSocketAddress for NettyServerBuilder.I got this error:
```IOException:Failed to bind to address /data/user/0/com.example.grpc_proxy/files/containerd.sock
2023-07-10 14:37:56.695 29230-29375 System.err              com.example.grpc_proxy               W  java.io.IOException: Failed to bind to address /data/user/0/com.example.grpc_proxy/files/containerd.sock
2023-07-10 14:37:56.695 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:328)
2023-07-10 14:37:56.695 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.internal.ServerImpl.start(ServerImpl.java:185)
2023-07-10 14:37:56.695 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.internal.ServerImpl.start(ServerImpl.java:94)
2023-07-10 14:37:56.695 29230-29375 System.err              com.example.grpc_proxy               W  	at com.example.grpc_proxy.proxy.GrpcProxy.init(GrpcProxy.java:452)
2023-07-10 14:37:56.695 29230-29375 System.err              com.example.grpc_proxy               W  	at com.example.grpc_proxy.MainActivity.lambda$onCreate$0$com-example-grpc_proxy-MainActivity(MainActivity.java:26)
2023-07-10 14:37:56.695 29230-29375 System.err              com.example.grpc_proxy               W  	at com.example.grpc_proxy.MainActivity$$ExternalSyntheticLambda0.run(Unknown Source:2)
2023-07-10 14:37:56.695 29230-29375 System.err              com.example.grpc_proxy               W  	at java.lang.Thread.run(Thread.java:930)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  Caused by: java.net.SocketException: Unsupported address type
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at sun.nio.ch.Net.translateToSocketException(Net.java:135)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at sun.nio.ch.Net.translateException(Net.java:166)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at sun.nio.ch.Net.translateException(Net.java:172)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:76)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:143)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
2023-07-10 14:37:56.697 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2023-07-10 14:37:56.698 29230-29375 System.err              com.example.grpc_proxy               W  	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2023-07-10 14:37:56.698 29230-29375 System.err              com.example.grpc_proxy               W  	... 1 more
2023-07-10 14:37:56.698 29230-29375 System.err              com.example.grpc_proxy               W  Caused by: java.nio.channels.UnsupportedAddressTypeException
2023-07-10 14:37:56.698 29230-29375 System.err              com.example.grpc_proxy               W  	at sun.nio.ch.Net.checkAddress(Net.java:104)
2023-07-10 14:37:56.698 29230-29375 System.err              com.example.grpc_proxy               W  	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:218)
2023-07-10 14:37:56.698 29230-29375 System.err              com.example.grpc_proxy               W  	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
2023-07-10 14:37:56.698 29230-29375 System.err              com.example.grpc_proxy               W  	... 16 more```

**Comment by chrisvest** [comment]
Only our epoll and kqueue transports support domain sockets in Netty 4.1.
I don't know if Android supports epoll, but that's what I would try next.

**Comment by normanmaurer** [comment]
Like @chrisvest said... closing this
