### ISSUE TITLE
Netty thread 100% CPU utilization

### ISSUE THREAD

**Issue by kent-b** [netty/netty#13547]
### Expected behavior
No blocked thread

### Actual behavior
After running our netty-based service for minutes to hours, eventually one thread will run in a loop and consume 100% of a core on an EC2 instance.

This is the stack trace:
```
"Info-executor-11" #50 daemon prio=5 os_prio=0 cpu=353928278.59ms elapsed=594662.06s tid=0x00007fe0a400dfc0 nid=0xb09 runnable  [0x00007fe05d6ed000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.peek(BaseMpscLinkedArrayQueue.java:382)
	at io.netty.util.internal.shaded.org.jctools.queues.MpscUnboundedArrayQueue.peek(MpscUnboundedArrayQueue.java:23)
	at co.cask.http.internal.NonStickyEventExecutorGroup$NonStickyOrderedEventExecutor.run(NonStickyEventExecutorGroup.java:286)
	at io.netty.util.concurrent.UnorderedThreadPoolEventExecutor$NonNotifyRunnable.run(UnorderedThreadPoolEventExecutor.java:292)
	at java.util.concurrent.Executors$RunnableAdapter.call(java.base@17.0.8/Executors.java:539)
	at java.util.concurrent.FutureTask.run(java.base@17.0.8/FutureTask.java:264)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(java.base@17.0.8/ScheduledThreadPoolExecutor.java:304)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.8/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.8/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.8/Thread.java:833)
```

### Steps to reproduce
Run service until CPU util jumps to 100%

### Netty version
4.1.95.Final

### JVM version (e.g. `java -version`)
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+7-Ubuntu-120.04.2)
OpenJDK 64-Bit Server VM (build 17.0.8+7-Ubuntu-120.04.2, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Ubuntu 20.04.6 LTS
kernel 5.15.0-1036-aws

**Comment by chrisvest** [comment]
Do you use ARM or x86_64 instances?

**Comment by franz1981** [comment]
I would rather open an issue to JCTools reporting the CPU arch and if the build is a custom one or not: looking the stack trace it has happened at co.cask.http.internal.NonStickyEventExecutorGroup$NonStickyOrderedEventExecutor.run(NonStickyEventExecutorGroup.java:286) which is not a Netty package, anyway.
@nitsanw as well

**Comment by franz1981** [comment]
Feel free to close it @chrisvest

**Comment by kent-b** [comment]
> Do you use ARM or x86_64 instances?

x86_64

**Comment by normanmaurer** [comment]
I dont think you use netty 4.1.95.Final as there is no `peek` call in this version. Can you please update netty to the latest release and recheck ? Please re-open if the issue still persist.
