### ISSUE TITLE
netty Channel is connecting to remote servers but not localhost/127.0.0.1

### ISSUE THREAD

**Issue by rajcspsg** [netty/netty#13545]
### Expected behavior

both remote and local servers be connected.

### Actual behavior

only remote servers are connected but not to localhost/127.0.0.1

### Steps to reproduce

I've provided minimum code to reproduce the issue.

### Minimal yet complete reproducer code (or URL to code)

```java

import io.netty.bootstrap.Bootstrap;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelHandler;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.ChannelOption;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.epoll.Epoll;
import io.netty.channel.epoll.EpollEventLoopGroup;
import io.netty.channel.epoll.EpollSocketChannel;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.handler.codec.http.HttpRequestEncoder;
import io.netty.handler.logging.LogLevel;
import java.net.InetSocketAddress;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;
import org.example.NamedThreadFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class NettyConnectionDemo {

    protected final Class<? extends SocketChannel> channelClass;
    protected final EventLoopGroup ioWorkers;

    protected LogLevel level;

    Logger log = LoggerFactory.getLogger(NettyConnectionDemo.class);
    protected long connectTimeOutMills = TimeUnit.SECONDS.toMillis(3);

    public NettyConnectionDemo(Class<? extends SocketChannel> channelClass, EventLoopGroup ioWorkers) {
        this.channelClass = channelClass;
        this.ioWorkers = ioWorkers;
        init();
    }

    public NettyConnectionDemo() {
        this(0);
    }

    public NettyConnectionDemo(int ioThreads) {
        if (ioThreads < 0) {
            ioThreads = 0;
        }
        EventLoopGroup workerGroup;
        Class<? extends SocketChannel> channelClass;
        if (Epoll.isAvailable()) {
            channelClass = EpollSocketChannel.class;
            workerGroup = new EpollEventLoopGroup(ioThreads, new NamedThreadFactory("ClientConfig-ioWorkers", true));
        } else {
            channelClass = NioSocketChannel.class;
            workerGroup = new NioEventLoopGroup(ioThreads, new NamedThreadFactory("ClientConfig-ioWorkers", true));
        }
        this.channelClass = channelClass;
        this.ioWorkers = workerGroup;
        init();
    }

    public Class<? extends SocketChannel> getChannelClass() {
        return channelClass;
    }

    public EventLoopGroup getIoWorkers() {
        return ioWorkers;
    }

    public LogLevel getLevel() {
        return level;
    }

    public void setLevel(LogLevel level) {
        this.level = level;
    }

    public long getConnectTimeOutMills() {
        return connectTimeOutMills;
    }

    public void setConnectTimeOutMills(long connectTimeOutMills) {
        this.connectTimeOutMills = connectTimeOutMills;
    }

    public void destory() {
        if (ioWorkers != null) {
            ioWorkers.shutdownGracefully();
        }
    }

    protected final Bootstrap booter = new Bootstrap();

    @ChannelHandler.Sharable
    class ShareableChannelInboundHandler extends ChannelInboundHandlerAdapter {}

    Bootstrap getBooter() {
        return booter;
    }

    private void init() {
        booter.group(ioWorkers);
        booter.channel(channelClass);
    }

    protected void initBooterOptions() {
        booter.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 30000);
    }

    protected ChannelHandler initHandlerAdapter(ChannelHandler init, Consumer<ChannelHandlerContext> closeListener) {
        ChannelHandler handler = new ShareableChannelInboundHandler() {
            @Override
            public void channelRegistered(ChannelHandlerContext ctx) throws Exception {
                Channel ch = ctx.channel();
                LogLevel level = getLevel();
                ch.pipeline().addLast(new ChannelInboundHandlerAdapter() {
                    @Override
                    public void channelRegistered(ChannelHandlerContext ctx) throws Exception {
                        log.info("channelRegistered:{}", ctx.channel());
                        super.channelRegistered(ctx);
                    }

                    @Override
                    public void channelActive(ChannelHandlerContext ctx) throws Exception {
                        log.info("channelActive:{}", ctx.channel());
                        super.channelActive(ctx);
                    }

                    @Override
                    public void channelInactive(ChannelHandlerContext ctx) throws Exception {
                        log.info("channelInactive:{}", ctx.channel());
                        if (closeListener != null) {
                            try {
                                closeListener.accept(ctx);
                            } catch (Throwable e) {
                                log.error(e.getMessage(), e);
                            }
                        }
                        super.channelInactive(ctx);
                    }

                    @Override
                    public void channelUnregistered(ChannelHandlerContext ctx) throws Exception {
                        log.info("channelUnregistered:{}", ctx.channel());
                        super.channelUnregistered(ctx);
                    }
                });
                
                ch.pipeline().addLast(init);
                ctx.pipeline().remove(this);
                ctx.fireChannelRegistered();
            }
        };
        return handler;
    }

    protected ChannelFuture doBooterConnect(InetSocketAddress address, final ChannelHandler init, Consumer<ChannelHandlerContext> closeListener) {
        ChannelFuture cf;
        synchronized (booter) {
            ChannelHandler handler = initHandlerAdapter(init, closeListener);
            booter.handler(handler);
            cf = booter.connect(address);
        }
        return cf;
    }

    public final ChannelFuture connect(InetSocketAddress address) {
        return doBooterConnect(address, null, null);
    }

    public final ChannelFuture connect(InetSocketAddress address, ChannelHandler handler) {
        return doBooterConnect(address, handler, null);
    }

    public static void main(String[] args) throws InterruptedException {
        NettyConnectionDemo cb = new NettyConnectionDemo(NioSocketChannel.class, new NioEventLoopGroup());
        ChannelFuture cf = cb.connect(new InetSocketAddress("google.com", 80)).syncUninterruptibly();
        System.out.println(cf.channel());
    }
}

```

when I use below code I get ConnectionException

```java
ChannelFuture cf = cb.connect(new InetSocketAddress("localhost", 3000)).syncUninterruptibly();
ChannelFuture cf = cb.connect(new InetSocketAddress("127.0.0.1", 3000)).syncUninterruptibly();
```

The exception is -

>	SLF4J: Defaulting to no-operation (NOP) logger implementation
>	SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
>	Exception in thread "main" io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:3000
>	Caused by: java.net.ConnectException: Connection refused
>		at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
>		at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
>		at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
>		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
>		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
>		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
>		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
>		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
>		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
>		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
>		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
>		at java.lang.Thread.run(Thread.java:750)

Note: The local server i'm running is sample docusaurus site. https://docusaurus.io/docs/installation see here to run server locally.

1. npx create-docusaurus@latest my-website classic
2. cd my-website && npm start

### Netty version

4.1.96.Final

### JVM version (e.g. `java -version`)

```bash
$ java -version
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (Zulu 8.70.0.23-CA-macos-aarch64) (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (Zulu 8.70.0.23-CA-macos-aarch64) (build 25.372-b07, mixed mode)
```
### OS version (e.g. `uname -a`)

```bash
$ uname -a
Darwin 400269m0.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64
```

**Comment by chrisvest** [comment]
"Connection refused" means there's no server listening on `localhost:3000`.

**Comment by rajcspsg** [comment]
@chrisvest 

please run the below code and start the http server -

```bash
npx create-docusaurus@latest my-website classic
cd my-website && npm start
```

I also noticed one more thing. If I started http server by netty locally then it is connecting. Looks like something is different for nodejs based http services.

**Comment by chrisvest** [comment]
Can you connect to the server by other means, like `curl`?

**Comment by rajcspsg** [comment]
Yes, I can connect using curl .
<img width="1189" alt="Screenshot 2023-08-14 at 9 19 34 AM" src="https://github.com/netty/netty/assets/10123965/a0444f03-c142-4e15-9b6f-1b941999cd6a">

**Comment by He-Pin** [comment]
@rajcspsg I encountered  this once and retry Connection helps. I raised a discussion in netty's discussion.

**Comment by chrisvest** [comment]
@rajcspsg This happens because your server only listens on IPv6 localhost and not on IPv4 localhost, so all accesses to `127.0.0.1` (which is what `java` resolves `localhost` to) on port `3000` get connection refused. Meanwhile, `curl` figures to try IPv6 localhost. Why they have different preferences, I do not know.

```
|  Welcome to JShell -- Version 17.0.8
|  For an introduction type: /help intro

jshell> import io.netty.bootstrap.*;

jshell> import io.netty.channel.*;

jshell> import io.netty.channel.epoll.*;

jshell> import io.netty.handler.logging.*;

jshell> import io.netty.util.*;

jshell> var group = new EpollEventLoopGroup(1);
group ==> io.netty.channel.epoll.EpollEventLoopGroup@38d8f54a

jshell> var cb = new Bootstrap().group(group).channel(EpollSocketChannel.class).handler(new LoggingHandler(LogLevel.INFO)).connect(NetUtil.LOCALHOST4, 3000).addListener(f -> { System.out.printf("success? %s%n", f);}).sync()
20:42:01.511 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xb7e45aba] REGISTERED
20:42:01.511 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xb7e45aba] CONNECT: localhost/127.0.0.1:3000
success? AbstractBootstrap$PendingRegistrationPromise@1e9aed03(failure: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:3000)
20:42:01.512 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xb7e45aba] CLOSE
20:42:01.512 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0xb7e45aba] UNREGISTERED
|  Exception io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:3000
|  Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
|        at Errors.newConnectException0 (Errors.java:166)
|        at Errors.handleConnectErrno (Errors.java:131)
|        at Socket.finishConnect (Socket.java:359)
|        at AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect (AbstractEpollChannel.java:710)
|        at AbstractEpollChannel$AbstractEpollUnsafe.finishConnect (AbstractEpollChannel.java:687)
|        at AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady (AbstractEpollChannel.java:567)
|        at EpollEventLoop.processReady (EpollEventLoop.java:499)
|        at EpollEventLoop.run (EpollEventLoop.java:407)
|        at SingleThreadEventExecutor$4.run (SingleThreadEventExecutor.java:997)
|        at ThreadExecutorMap$2.run (ThreadExecutorMap.java:74)
|        at FastThreadLocalRunnable.run (FastThreadLocalRunnable.java:30)
|        at Thread.run (Thread.java:833)

jshell> var cb = new Bootstrap().group(group).channel(EpollSocketChannel.class).handler(new LoggingHandler(LogLevel.INFO)).connect(NetUtil.LOCALHOST6, 3000).addListener(f -> { System.out.printf("success? %s%n", f);}).sync()
20:42:04.289 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x52632986] REGISTERED
20:42:04.289 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x52632986] CONNECT: localhost/[0:0:0:0:0:0:0:1]:3000
success? AbstractBootstrap$PendingRegistrationPromise@75947236(success)
20:42:04.289 [epollEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x52632986, L:/[0:0:0:0:0:0:0:1%0]:38026 - R:localhost/[0:0:0:0:0:0:0:1]:3000] ACTIVE
cb ==> AbstractBootstrap$PendingRegistrationPromise@75947236(success)

jshell> 
```

**Comment by rajcspsg** [comment]
Thanks Chris or your exaplanation Using `NetUtil.LOCALHOST6` fixes this issue. 
I'll close this issue
