### ISSUE TITLE
Missing graalvm native image reflection hints for SelectorProvider

### ISSUE THREAD

**Issue by czp3009** [netty/netty#13575]
### Expected behavior
Netty should cover all graalvm native image reflection hints

### Actual behavior
https://github.com/netty/netty/blob/4.1/transport/src/main/resources/META-INF/native-image/io.netty/netty-transport/reflection-config.json

Although there are configuration for `java.lang.management.ManagementFactory` and `java.lang.management.RuntimeMXBean` etc. But not include `java.nio.channels.spi.SelectorProvide` which is invoke by reflection in [SelectorProviderUtil](https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/socket/nio/SelectorProviderUtil.java)

Netty code in `io.netty.channel.socket.nio.SelectorProviderUtil`:
```java
@SuppressJava6Requirement(reason = "Usage guarded by java version check")
static Method findOpenMethod(String methodName) {
    if (PlatformDependent.javaVersion() >= 15) {
        try {
            return SelectorProvider.class.getMethod(methodName, java.net.ProtocolFamily.class);
        } catch (Throwable e) {
            logger.debug("SelectorProvider.{}(ProtocolFamily) not available, will use default", methodName, e);
        }
    }
    return null;
}
```

In fact, Netty will use `SelectorProviderUtil.findOpenMethod` to find and invoke reflective two methods in `SelectorProvider` in a Spring application:
```java
public SocketChannel openSocketChannel(ProtocolFamily family)
public ServerSocketChannel openServerSocketChannel(ProtocolFamily family)
```

### Steps to reproduce
After compiled a Spring application to graalvm native image, and set log level for `io.netty` to TRACE, such exception will show up(which can't reproduce in jvm application):
```
2023-08-31T01:27:05.755+08:00 TRACE 55266 --- [           main] io.netty.channel.nio.NioEventLoop        : instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@28fee399
2023-08-31T01:27:05.755+08:00 DEBUG 55266 --- [           main] i.n.c.socket.nio.SelectorProviderUtil    : SelectorProvider.openServerSocketChannel(ProtocolFamily) not available, will use default

java.lang.NoSuchMethodException: java.nio.channels.spi.SelectorProvider.openServerSocketChannel(java.net.ProtocolFamily)
        at java.base@17.0.8/java.lang.Class.checkMethod(DynamicHub.java:1038) ~[monolith-service:na]
        at java.base@17.0.8/java.lang.Class.getMethod(DynamicHub.java:1023) ~[monolith-service:na]
        at io.netty.channel.socket.nio.SelectorProviderUtil.findOpenMethod(SelectorProviderUtil.java:39) ~[na:na]
        at io.netty.channel.socket.nio.NioServerSocketChannel.<clinit>(NioServerSocketChannel.java:57) ~[monolith-service:4.1.97.Final]
        at reactor.netty.resources.DefaultLoopNIO.getChannel(DefaultLoopNIO.java:45) ~[na:na]
        at reactor.netty.resources.LoopResources.onChannel(LoopResources.java:243) ~[monolith-service:1.1.10]
        at reactor.netty.tcp.TcpResources.onChannel(TcpResources.java:251) ~[monolith-service:1.1.10]
        at reactor.netty.transport.TransportConfig.lambda$connectionFactory$1(TransportConfig.java:277) ~[monolith-service:1.1.10]
        at reactor.netty.transport.TransportConnector.doInitAndRegister(TransportConnector.java:277) ~[na:na]
        at reactor.netty.transport.TransportConnector.bind(TransportConnector.java:87) ~[na:na]
        at reactor.netty.transport.ServerTransport.lambda$bind$0(ServerTransport.java:115) ~[monolith-service:1.1.10]
        at reactor.core.publisher.MonoCreate.subscribe(MonoCreate.java:58) ~[na:na]
        at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[monolith-service:3.5.9]
        at reactor.core.publisher.Mono.block(Mono.java:1737) ~[monolith-service:3.5.9]
        at reactor.netty.transport.ServerTransport.bindNow(ServerTransport.java:149) ~[monolith-service:1.1.10]
        at reactor.netty.transport.ServerTransport.bindNow(ServerTransport.java:134) ~[monolith-service:1.1.10]
        at org.springframework.boot.web.embedded.netty.NettyWebServer.startHttpServer(NettyWebServer.java:145) ~[monolith-service:3.1.3]
        at org.springframework.boot.web.embedded.netty.NettyWebServer.start(NettyWebServer.java:100) ~[monolith-service:3.1.3]
        at org.springframework.boot.web.reactive.context.WebServerManager.start(WebServerManager.java:55) ~[na:na]
        at org.springframework.boot.web.reactive.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:41) ~[na:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179) ~[monolith-service:6.0.11]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357) ~[monolith-service:6.0.11]
        at java.base@17.0.8/java.lang.Iterable.forEach(Iterable.java:75) ~[monolith-service:na]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156) ~[monolith-service:6.0.11]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124) ~[monolith-service:6.0.11]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:958) ~[monolith-service:6.0.11]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:611) ~[monolith-service:6.0.11]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[monolith-service:3.1.3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[monolith-service:3.1.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[monolith-service:3.1.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[monolith-service:3.1.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[monolith-service:3.1.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[monolith-service:3.1.3]
        at com.hkmci.masterspace.monolith.ApplicationKt.main(Application.kt:15) ~[monolith-service:na]
        at com.hkmci.masterspace.monolith.ApplicationKt.main(Application.kt) ~[monolith-service:na]

```

### Minimal yet complete reproducer code (or URL to code)
Create a empty Webflux Spring application with [Spring Initializr](https://start.spring.io/) and compile to native image.

set log level of  `io.netty` to TRACE.

Just run the application, the exception above will show up.

### Netty version
4.1.97.Final

### JVM version (e.g. `java -version`)
[GraalVM for JDK 17 Community 17.0.8](https://github.com/graalvm/graalvm-ce-builds/releases/tag/jdk-17.0.8)(native image)

### OS version (e.g. `uname -a`)
Ubuntu22.04

**Comment by normanmaurer** [comment]
@czp3009 want to do a PR ? /cc @violetagg

**Comment by czp3009** [comment]
hi @normanmaurer i create a PR here https://github.com/netty/netty/pull/13579

**Comment by violetagg** [comment]
@czp3009 Spring is not using directly the metadata from Netty as it contains also some old declarations. Instead Spring is using https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/io.netty so you need to make a PR there.

**Comment by violetagg** [comment]
Can you verify that you are seeing this https://github.com/netty/netty/discussions/13500#discussioncomment-6506620

**Comment by czp3009** [comment]
@violetagg Thank you for your answer. Although the problem may not be related to netty, I was really confused.

I notice that in `io.netty` directory in [graalvm-reachability-metadata](https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/io.netty), `netty-transport` only have version `4.1.76.Final`, but `netty-common` have version `4.1.80.Final`.

So,

1. if i want make PR to modify `netty-transport`, should i create version `4.1.80.Final` for `netty-transport`, or just modify on version `4.1.76.Final`?
2. netty version used by Spring is `4.1.97.Final`. Does spring really use old versions of reachability-metadata from network instead of butlin json in jar?

**Comment by violetagg** [comment]
@czp3009 May be in `netty-common`. My last PR was there https://github.com/oracle/graalvm-reachability-metadata/pull/103
About the versions, if you take a look in my comment above - the metadata from `graalvm-reachability-metadata` will be applied even for newer versions

```
[INFO] Downloaded GraalVM reachability metadata repository from file:/.../.m2/repository/org/graalvm/buildtools/graalvm-reachability-metadata/0.9.23/graalvm-reachability-metadata-0.9.23-repository.zip
[INFO] [graalvm reachability metadata repository for io.netty:netty-buffer:4.1.94.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-buffer:4.1.94.Final]: Configuration directory is io.netty/netty-buffer/4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-common:4.1.94.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-common:4.1.94.Final]: Configuration directory is io.netty/netty-common/4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-codec-http:4.1.94.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-codec-http:4.1.94.Final]: Configuration directory is io.netty/netty-codec-http/4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-transport:4.1.94.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-transport:4.1.94.Final]: Configuration directory is io.netty/netty-transport/4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-codec-http2:4.1.94.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-codec-http2:4.1.94.Final]: Configuration directory is io.netty/netty-codec-http2/4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-handler:4.1.94.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-handler:4.1.94.Final]: Configuration directory is io.netty/netty-handler/4.1.80.Final
[INFO] [graalvm reachability metadata repository for io.netty:netty-resolver-dns:4.1.94.Final]: Configuration directory not found. Trying latest version.
[INFO] [graalvm reachability metadata repository for io.netty:netty-resolver-dns:4.1.94.Final]: Configuration directory is io.netty/netty-resolver-dns/4.1.80.Final
```

**Comment by violetagg** [comment]
Please check for more history about why it is what it is #12601

**Comment by czp3009** [comment]
@violetagg Thank you very much for your patience, I now fully understand `graalvm-reachability-metadata`, as well as the library version control.

But I still have a question. Should I PR to the `netty-common` folder instead of `netty-transport` because the class `SelectorProvider` that needs to be add more reflection configs in this PR is from Java standard lib, or because all future metadata updates should commit to `netty-common`?

**Comment by violetagg** [comment]
@czp3009 I will try to generate a metadata similar to what I did last week for kqueue https://github.com/oracle/graalvm-reachability-metadata/pull/379

**Comment by czp3009** [comment]
@violetagg Maybe I misunderstood or expressed it wrongly, I mean if I want to add metadata for `SelectorProvider`, should I also submit it to 'metadata/io.netty/netty-common/4.1.80.Final/reflect-config.json'?

**Comment by violetagg** [comment]
> @violetagg Maybe I misunderstood or expressed it wrongly, I mean if I want to add metadata for `SelectorProvider`, should I also submit it to 'metadata/io.netty/netty-common/4.1.80.Final/reflect-config.json'?

yes

**Comment by violetagg** [comment]
@czp3009 I think this should be enough, can you test it?

```
{
  "condition":{"typeReachable":"io.netty.channel.socket.nio.NioServerSocketChannel"},
  "name":"java.nio.channels.spi.SelectorProvider",
  "methods":[
    {"name":"openServerSocketChannel","parameterTypes":["java.net.ProtocolFamily"] },
    {"name":"openSocketChannel","parameterTypes":["java.net.ProtocolFamily"] }
  ]
}
```

**Comment by czp3009** [comment]
@violetagg i copy it to my Spring project, and is works fine!

**Comment by czp3009** [comment]
I create PR in graalvm-reachability-metadata: https://github.com/oracle/graalvm-reachability-metadata/pull/382

**Comment by violetagg** [comment]
@czp3009 I think we can close this one

**Comment by NicklasWallgren** [comment]
We encountered this issue today.

I think this issue should remain open until https://github.com/oracle/graalvm-reachability-metadata/pull/382 has been merged. @czp3009 needs help writing unit tests.

**Comment by violetagg** [comment]
@NicklasWallgren I'm gonna take a look at https://github.com/oracle/graalvm-reachability-metadata/pull/382

**Comment by violetagg** [comment]
@NicklasWallgren I've proposed tests for validating the change in the metadata.

**Comment by NicklasWallgren** [comment]
> @NicklasWallgren I've proposed tests for validating the change in the metadata.

Great!, Thank you
