### ISSUE TITLE
[Intermittent] Handshake Hangs During Connection Issues

### ISSUE THREAD

**Issue by Wathsara** [netty/netty#13582]
### Problem

I am using Netty to implement a WebSocket client. I attached the code we are executing for handshake and additionally, when the channel becomes inactive, we have implemented a retry policy in our client. 

During the WebSocket handshake process, we've encountered an issue where the code appears to hang indefinitely when there are connection issues with the server. Surprisingly, this behavior occurs without throwing any exceptions and happens intermittently.

### Expected Behavior:

The WebSocket handshake should either succeed or throw an appropriate exception when there are server connection issues.

### Problem
what can lead to this sort of hang during the WebSocket handshake process.

##### Handshake code
```
public boolean handhshake(Object... params) throws InterruptedException, URISyntaxException, SSLException {

        boolean isDone;
        URI uri = new URI(url);
        String scheme = uri.getScheme() == null ? "ws" : uri.getScheme();
        final String host = uri.getHost() == null ? "127.0.0.1" : uri.getHost();
        final int port;
        if (uri.getPort() == -1) {
            if ("ws".equalsIgnoreCase(scheme)) {
                port = 80;
            } else if ("wss".equalsIgnoreCase(scheme)) {
                port = 443;
            } else {
                port = -1;
            }
        } else {
            port = uri.getPort();
        }

        if (!"ws".equalsIgnoreCase(scheme) && !"wss".equalsIgnoreCase(scheme)) {
            log.error("Only WS(S) is supported.");
            return false;
        }

        final boolean ssl = "wss".equalsIgnoreCase(scheme);
        final SslContext sslCtx;
        if (ssl) {
            sslCtx = SslContextBuilder.forClient()
                    .trustManager(InsecureTrustManagerFactory.INSTANCE).build();
        } else {
            sslCtx = null;
        }

        group = new NioEventLoopGroup();

        // Prepare the HTTP request header.
        HttpHeaders headers = new DefaultHttpHeaders().add(ACCESS_TOKEN, + accessToken);
        for (Object param : params) {
            if (param instanceof Channel) {
                AttributeKey<String> key = AttributeKey.valueOf(CHANNEL_ID);
                if (((Channel) param).attr(key) != null) {
                    headers.add(CHANNEL_ID, ((Channel) param).attr(key).get());
                }
            }
        }

        try {
            handler =
                    new WebSocketClientHandler(
                            WebSocketClientHandshakerFactory.newHandshaker(
                                    uri, WebSocketVersion.V13, null,
                                    true, headers), this);

            Bootstrap b = new Bootstrap();
            b.group(group)
                    .channel(NioSocketChannel.class)
                    .handler(new ChannelInitializer<SocketChannel>() {

                        @Override
                        protected void initChannel(SocketChannel ch) {

                            ChannelPipeline p = ch.pipeline();
                            if (sslCtx != null) {
                                setProxy(p);
                                p.addLast(sslCtx.newHandler(ch.alloc(), host, port));
                            }
                            p.addLast(
                                    new HttpClientCodec(),
                                    new HttpObjectAggregator(8192),
                                    WebSocketClientCompressionHandler.INSTANCE,
                                    handler);
                        }
                    });

            channel = b.connect(uri.getHost(), port).sync().channel();
            isDone = handler.handshakeFuture().sync().isSuccess();
        } catch (Exception ex) {
            log.error("Handshake Failed.", ex);
            isDone = false;
        }
        return isDone;
    }
```

#### Retry Code
We have written the `WebSocketClientHandler` extending the `SimpleChannelInboundHandler`

```
public ChannelFuture handshakeFuture() {

    return handshakeFuture;
}

@Override
public void handlerAdded(ChannelHandlerContext ctx) {

    handshakeFuture = ctx.newPromise();
}
    
@Override
public void channelInactive(ChannelHandlerContext ctx) {

    log.info("Disconnected client connection.");
    isDisconnected = true;
    cancelTimer();
    if (!WebSocketClient.isRetryStarted()) {
        startRetrying(ctx.channel());
    }
}

private void startRetrying(Channel channel) {

        WebSocketClient.setIsRetryStarted(true);
        while (true) {
            boolean result;
            try {
                log.info("Trying to reconnect the server...");
                result = client.handhshake(channel);
                if (result) {
                    isDisconnected = false;
                    WebSocketClient.setIsRetryStarted(false);
                    log.info("Agent successfully reconnected to server.");
                    break;
                }
                Thread.sleep(SOCKET_RETRY_INTERVAL);
            } catch (InterruptedException | URISyntaxException | SSLException e) {
                log.error("Error occurred while reconnecting to server.", e);
            }
        }
    }
    
```

**Comment by Wathsara** [comment]
Found the exact issue.

```
ERROR org.agent.WebSocketClientHandler - Exception caught : java.lang.NullPointerException: value
 at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:39) ~[netty-common-4.1.96.Final.jar:4.1.96.Final]
 at io.netty.handler.codec.DefaultHeaders.fromObject(DefaultHeaders.java:1117) ~[netty-codec-4.1.96.Final.jar:4.1.96.Final]
 at io.netty.handler.codec.DefaultHeaders.addObject(DefaultHeaders.java:364) ~[netty-codec-4.1.96.Final.jar:4.1.96.Final]
 at io.netty.handler.codec.http.DefaultHttpHeaders.add(DefaultHttpHeaders.java:115) ~[netty-codec-http-4.1.96.Final.jar:4.1.96.Final]
 ```
 
In our handshake method, we attempt to insert the channel ID of the disconnected channel into a header in order to validate whether it's a retry attempt from the server. It appears that, even though the AttributeKey (channel-id) is available, its value is null on the client side.
 
```
      for (Object param : params) {
            if (param instanceof Channel) {
                AttributeKey<String> key = AttributeKey.valueOf(CHANNEL_ID);
                if (((Channel) param).attr(key) != null) {
                    headers.add(CHANNEL_ID, ((Channel) param).attr(key).get());
                }
            }
        }
```
