### ISSUE TITLE
direct buffer constructor: unavailable

### ISSUE THREAD

**Issue by alebastrov** [netty/netty#13688]
### Expected behavior
"Not to use reflective access to final fields"

### Actual behavior
I see in logs
~~~
DEBUG i.n.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:289)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:282)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:333)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:88)
	at io.netty.channel.nio.NioEventLoop.<clinit>(NioEventLoop.java:84)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:182)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:38)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:69)
	at de.bwaldvogel.mongo.MongoServer.bind(MongoServer.java:79)
	at de.bwaldvogel.mongo.MongoServer.bind(MongoServer.java:74)
	at de.bwaldvogel.mongo.MongoServer.bind(MongoServer.java:70)
~~~
### Steps to reproduce
Use JVM 18 for example

### Netty version
4.1.94-Final

### JVM version (e.g. `java -version`)
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Darwin MacBook-Pro-2021.local 20.6.0 Darwin Kernel Version 20.6.0: Fri Dec 16 00:35:00 PST 2022; root:xnu-7195.141.49~1/RELEASE_X86_64 x86_64

**Comment by chrisvest** [comment]
This is just debug logging telling you about internal configurations.
Turn off trace logging to hide the stack trace.
Or enable reflective access to make that constructor available.
