### ISSUE TITLE
an exception occured when using pipeline: IllegalStateException: new buffer must have at least one element

### ISSUE THREAD

**Issue by nammmi** [netty/netty#13723]
#### Current Behavior

It looks like netty threw an IllegalStateException: new buffer must have at least one element. the physical connection established with redis was abnormal and out of sync.
<details>
<summary>Stack trace</summary>

```java

org.springframework.data.redis.connection.RedisPipelineException: Pipeline contained one or more invalid commands; nested exception is io.lettuce.core.RedisException: io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.closePipeline(LettuceConnection.java:560)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection$$FastClassBySpringCGLIB$$4eafebcc.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:747)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at com.tencent.tsf.sleuth.instrument.redis.RedisCommonInterceptor.invoke(RedisCommonInterceptor.java:35)
	at com.tencent.tsf.sleuth.instrument.redis.SleuthRedisAspect.interceptorRedis(SleuthRedisAspect.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection$$EnhancerBySpringCGLIB$$5355a6b3.closePipeline(<generated>)
	at sun.reflect.GeneratedMethodAccessor517.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.redis.core.CloseSuppressingInvocationHandler.invoke(CloseSuppressingInvocationHandler.java:61)
	at com.sun.proxy.$Proxy391.closePipeline(Unknown Source)
	at org.springframework.data.redis.core.RedisTemplate.lambda$executePipelined$0(RedisTemplate.java:290)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:224)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:171)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:281)
	at org.springframework.data.redis.core.RedisTemplate.executePipelined(RedisTemplate.java:264)
	at com.xxx.eam.eam.eambatch.application.util.RedisUtil.uploadByPipeline(RedisUtil.java:124)
	at com.xxx.eam.eam.eambatch.application.util.RedisUtil.uploadByPipeline(RedisUtil.java:147)
	at com.xxx.eam.eam.eambatch.application.cache.task.UploadRoleCacheTask.executeUploadRoleCacheTask(UploadRoleCacheTask.java:81)
	at com.xxx.eam.eam.eambatch.application.cache.task.UploadRoleCacheTask.run(UploadRoleCacheTask.java:49)
	at com.xxx.eam.eam.eambatch.application.cache.config.BatchUploadConfig.doJob(BatchUploadConfig.java:98)
	at com.xxx.dbsp.client.schedule.callable.JobExecuteCallable.call(JobExecuteCallable.java:38)
	at com.xxx.dbsp.client.schedule.callable.JobExecuteCallable.call(JobExecuteCallable.java:21)
	at com.xxx.dbsp.client.schedule.impl.JobScheduleServiceImpl$1.handle(JobScheduleServiceImpl.java:114)
	at com.xxx.dbsp.client.schedule.impl.AsyncScheduleServiceImpl.lambda$execute$0(AsyncScheduleServiceImpl.java:62)
	at org.springframework.cloud.sleuth.instrument.async.TraceRunnable.run(TraceRunnable.java:62)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.lettuce.core.RedisException: io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.
	at io.lettuce.core.LettuceFutures.awaitAll(LettuceFutures.java:88)
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.closePipeline(LettuceConnection.java:517)
	... 35 more
Caused by: io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:93)
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:75)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at io.lettuce.core.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:366)
	at io.lettuce.core.protocol.CommandHandler.write(CommandHandler.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.lang.IllegalStateException: new buffer must have at least one element
	at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.newBufferPoll(BaseMpscLinkedArrayQueue.java:458)
	at io.netty.util.internal.shaded.org.jctools.queues.BaseMpscLinkedArrayQueue.relaxedPoll(BaseMpscLinkedArrayQueue.java:514)
	at io.netty.util.internal.shaded.org.jctools.queues.MpscChunkedArrayQueue.relaxedPoll(MpscChunkedArrayQueue.java:43)
	at io.netty.util.Recycler$LocalPool.claim(Recycler.java:280)
	at io.netty.util.Recycler.get(Recycler.java:168)
	at io.netty.util.internal.ObjectPool$RecyclerObjectPool.get(ObjectPool.java:84)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.newEntry(PoolThreadCache.java:456)
	at io.netty.buffer.PoolThreadCache$MemoryRegionCache.add(PoolThreadCache.java:358)
	at io.netty.buffer.PoolThreadCache.add(PoolThreadCache.java:187)
	at io.netty.buffer.PoolArena.free(PoolArena.java:228)
	at io.netty.buffer.PooledByteBuf.deallocate(PooledByteBuf.java:176)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.handleRelease(AbstractReferenceCountedByteBuf.java:111)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:101)
	at io.lettuce.core.protocol.CommandArgs$ValueArgument.encode(CommandArgs.java:695)
	at io.lettuce.core.protocol.CommandArgs.encode(CommandArgs.java:344)
	at io.lettuce.core.protocol.Command.encode(Command.java:119)
	at io.lettuce.core.protocol.AsyncCommand.encode(AsyncCommand.java:183)
	at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:90)
	... 19 more

```

</details>

#### Input Code

<details>
<summary>Input Code</summary>

```java

pipeline:

    public void uploadByPipeline(Map<String, Object> bigMap, int count) {
        try {
            redisTemplate.getOperations().executePipelined(new SessionCallback<Object>() {
                @Override
                public <K, V> Object execute(RedisOperations<K, V> operations) throws DataAccessException {
                    ValueOperations<String, Object> v = (ValueOperations<String, Object>) operations.opsForValue();
                    bigMap.entrySet().forEach(entry -> {
                        v.set(entry.getKey(), entry.getValue(), 24, TimeUnit.HOURS);
                    });
                    return null;
                }
            });
        }
        catch (Exception e) {
            ...
        }
    }


redis configuration:

        @Bean("paramRedisFactory")
    public LettuceConnectionFactory paramRedisFactory() {
            GenericObjectPoolConfig genericObjectPoolConfig = new GenericObjectPoolConfig();
            genericObjectPoolConfig.setMaxIdle(paramRedisProperties.getMaxIdle());
            genericObjectPoolConfig.setMinIdle(paramRedisProperties.getMinIdle());
            genericObjectPoolConfig.setMaxTotal(paramRedisProperties.getMaxActive());
            genericObjectPoolConfig.setMaxWaitMillis(paramRedisProperties.getMaxWait());

            RedisStandaloneConfiguration configuration = new RedisStandaloneConfiguration(paramRedisProperties.getHost(),
                paramRedisProperties.getPort());

            configuration.setPassword(RedisPassword.of(paramRedisProperties.getPassword()));
            LettuceClientConfiguration clientConfiguration = LettucePoolingClientConfiguration.builder()
                .commandTimeout(Duration.ofMillis(paramRedisProperties.getTimeout()))
                .shutdownTimeout(Duration.ofMillis(paramRedisProperties.getShutdownTimeout()))
                .poolConfig(genericObjectPoolConfig).build();

            LettuceConnectionFactory factory = new LettuceConnectionFactory(configuration, clientConfiguration);
            return factory; 
    }

```

</details>

#### Environment

- Netty version : 4.1.77
- Lettuce version(s): [5.0.5.RELEASE]
- Spring Data Redis version: [2.0.14.RELEASE]
- JRE version: OpenJDK Runtime Environment (8.0_181-b13) (build 1.8.0_181-b13)
- Java VM: OpenJDK 64-Bit Server VM (25.181-b13 mixed mode linux-aarch64 compressed oops)

**Comment by nitsanw** [comment]
I'm sorry but I will not spend any time on this kind of configuration (1.8u181, on arm). If you can reproduce on the latest version of 1.8 please let me know.

**Comment by nammmi** [comment]
> I'm sorry but I will not spend any time on this kind of configuration (1.8u181, on arm). If you can reproduce on the latest version of 1.8 please let me know.

Thank you, we will consider upgrading jdk1.8 version to the latest one. But the strange thing is that after this problem appeared twice in two days, it never appeared again. We haven't changed anything during this time. Does this mean that we have triggered a jdk bug or arm compatibility issue?

**Comment by nitsanw** [comment]
Either one, or neither. I can't tell. You are so many bug fixes behind, and in particular on ARM it seems like a waste of time to even check.
I hope this is not an important system.

**Comment by normanmaurer** [comment]
Let moe close this... Please reopen if you can still reproduce with a recent idk version
