### ISSUE TITLE
Missing graalvm native image reflection hints for PlatformDependent0

### ISSUE THREAD

**Issue by NicklasWallgren** [netty/netty#13764]
### Expected behavior
Netty should cover all graalvm native image reflection hints.

### Actual behavior
`NoSuchMethodException` due to missing native image reflection hints.

### Steps to reproduce
After compiled a Spring application to graalvm native image, and set log level for io.netty to TRACE, such exception will show up(which can't reproduce in jvm application):

```
13:27:04.390 [tomcat-handler-0] DEBUG i.n.util.internal.PlatformDependent0 transactionId:  traceId:  - -Dio.netty.noUnsafe: false
13:27:04.390 [tomcat-handler-0] DEBUG i.n.util.internal.PlatformDependent0 transactionId:  traceId:  - Java version: 21
13:27:04.390 [tomcat-handler-0] DEBUG i.n.util.internal.PlatformDependent0 transactionId:  traceId:  - sun.misc.Unsafe.theUnsafe: available
13:27:04.390 [tomcat-handler-0] DEBUG i.n.util.internal.PlatformDependent0 transactionId:  traceId:  - sun.misc.Unsafe.copyMemory: available
13:27:04.390 [tomcat-handler-0] DEBUG i.n.util.internal.PlatformDependent0 transactionId:  traceId:  - sun.misc.Unsafe.storeFence: available
13:27:04.390 [tomcat-handler-0] DEBUG i.n.util.internal.PlatformDependent0 transactionId:  traceId:  - java.nio.Buffer.address: available
13:27:04.390 [tomcat-handler-0] DEBUG i.n.util.internal.PlatformDependent0 transactionId:  traceId:  - direct buffer constructor: unavailable
java.lang.NoSuchMethodException: java.nio.DirectByteBuffer.<init>(long, long)
        at java.base@21.0.1/java.lang.Class.checkMethod(DynamicHub.java:1065)
        at java.base@21.0.1/java.lang.Class.getConstructor0(DynamicHub.java:1228)
        at java.base@21.0.1/java.lang.Class.getDeclaredConstructor(DynamicHub.java:2930)
        at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:291)
        at java.base@21.0.1/java.security.AccessController.executePrivileged(AccessController.java:129)
        at java.base@21.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:286)
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:331)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:86)
        at io.netty.util.ConstantPool.<init>(ConstantPool.java:34)
        at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27)
        at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27)
        at reactor.netty.resources.DefaultPooledConnectionProvider.<clinit>(DefaultPooledConnectionProvider.java:101)
        at reactor.netty.resources.ConnectionProvider$Builder.build(ConnectionProvider.java:497)
        at reactor.netty.resources.ConnectionProvider.create(ConnectionProvider.java:162)
        at reactor.netty.tcp.TcpResources.create(TcpResources.java:408)
        at reactor.netty.tcp.TcpResources.getOrCreate(TcpResources.java:361)
        at reactor.netty.http.HttpResources.get(HttpResources.java:109)
        at org.springframework.http.client.ReactorResourceFactory.start(ReactorResourceFactory.java:223)
```

```
java.lang.reflect.InaccessibleObjectException: Unable to make static boolean java.nio.Bits.unaligned() accessible: module java.base does not "opens java.nio" to unnamed module @21213b92
        at java.base@21.0.1/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base@21.0.1/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base@21.0.1/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base@21.0.1/java.lang.reflect.Method.checkCanSetAccessible(Method.java:203)
        at java.base@21.0.1/java.lang.reflect.Method.setAccessible(Method.java:197)
        at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:34)
        at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:382)
        at java.base@21.0.1/java.security.AccessController.executePrivileged(AccessController.java:129)
        at java.base@21.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:345)
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:331)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:86)
        at io.netty.util.ConstantPool.<init>(ConstantPool.java:34)
        at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27)
        at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27)
        at reactor.netty.resources.DefaultPooledConnectionProvider.<clinit>(DefaultPooledConnectionProvider.java:101)
        at reactor.netty.resources.ConnectionProvider$Builder.build(ConnectionProvider.java:497)
        at reactor.netty.resources.ConnectionProvider.create(ConnectionProvider.java:162)
        at reactor.netty.tcp.TcpResources.create(TcpResources.java:408)
        at reactor.netty.tcp.TcpResources.getOrCreate(TcpResources.java:361)
        at reactor.netty.http.HttpResources.get(HttpResources.java:109)
        at org.springframework.http.client.ReactorResourceFactory.start(ReactorResourceFactory.java:223)
```

```
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$7 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @21213b92
        at java.base@21.0.1/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:394)
        at java.base@21.0.1/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:714)
        at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:571)
        at io.netty.util.internal.PlatformDependent0$7.run(PlatformDependent0.java:429)
        at java.base@21.0.1/java.security.AccessController.executePrivileged(AccessController.java:129)
        at java.base@21.0.1/java.security.AccessController.doPrivileged(AccessController.java:319)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:420)
        at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:331)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:86)
        at io.netty.util.ConstantPool.<init>(ConstantPool.java:34)
        at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27)
        at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27)
        at reactor.netty.resources.DefaultPooledConnectionProvider.<clinit>(DefaultPooledConnectionProvider.java:101)
        at reactor.netty.resources.ConnectionProvider$Builder.build(ConnectionProvider.java:497)
        at reactor.netty.resources.ConnectionProvider.create(ConnectionProvider.java:162)
        at reactor.netty.tcp.TcpResources.create(TcpResources.java:408)
        at reactor.netty.tcp.TcpResources.getOrCreate(TcpResources.java:361)
        at reactor.netty.http.HttpResources.get(HttpResources.java:109)
```

### Minimal yet complete reproducer code (or URL to code)
Create a empty Webflux Spring application with [Spring Initializr](https://start.spring.io/) and compile to native image.

set log level of io.netty to TRACE.

Just run the application, the exception above will show up.

### Netty version
4.1.101.FINAL

**Comment by violetagg** [comment]
@NicklasWallgren I'm gonna take a look at this.

**Comment by violetagg** [comment]
@NicklasWallgren Please follow this PR https://github.com/oracle/graalvm-reachability-metadata/pull/434
