### ISSUE TITLE
PoolSubpage allocate failed

### ISSUE THREAD

**Issue by echooymxq** [netty/netty#13777]
```java
java.lang.ArrayIndexOutOfBoundsException: -1
        at io.netty.buffer.PoolChunk.initBufWithSubpage(PoolChunk.java:578)
        at io.netty.buffer.PoolArena.tcacheAllocateSmall(PoolArena.java:167)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:134)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:126)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:396)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179) 
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:140)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:120)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:150)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:748)
```
We encountered an issue in our production environment when the allocate error occurred. 
case1: numAvail > 0, doNotDestroy is false. 
case2: numAvail == 0, doNotDestroy is true. 
Both of these cases have occurred. As per my understanding, when we synchronized the head page, the situation of numAvail being equal to 0 should never occur. I have compared the code of the current latest branch with version 4.1.78, and they are nearly identical.

No
### Netty version
4.1.78.Final
### JVM version (e.g. `java -version`)
1.8.0_221
### OS version (e.g. `uname -a`)
linux 4.19.90 aarch64

**Comment by cb1271290526** [comment]
hello，I've had the same problem recently. How did you resolve it?

**Comment by normanmaurer** [comment]
@cb1271290526 just upgrade to the latest version..

**Comment by cb1271290526** [comment]
> [@cb1271290526](https://github.com/cb1271290526) just upgrade to the latest version..

thank you, and do you know the reason? I read the releated code, it seems like this [issue](https://github.com/netty/netty/issues/13625): when  allocating or releasing memory, the netty locks incorrect poolsubpage head.
