### ISSUE TITLE
netty-all maven dependency does not include netty_transport_native_epoll_ppcle_64.so

### ISSUE THREAD

**Issue by rickyma** [netty/netty#13770]
I've encountered an exception running with latest netty-all dependencies on a machine with ppc64le arch.

netty-all does not include netty_transport_native_epoll_ppcle_64.so under META-INF/native folder. (Now there are only aarch_64, x86_64).
I want my jar to include all of the *.so under META-INF/native folder.
Any ideas?

ERROR log as belows:

Suppressed: java.lang.UnsatisfiedLinkError: no org_apache_uniffle_netty_transport_native_epoll in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860) ~[?:1.8.0_362]
				at java.lang.Runtime.loadLibrary0(Runtime.java:843) ~[?:1.8.0_362]
				at java.lang.System.loadLibrary(System.java:1136) ~[?:1.8.0_362]
				at org.apache.uniffle.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
				at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
				at org.apache.uniffle.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:378) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_362]
				at org.apache.uniffle.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:370) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:336) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:308) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.epoll.Native.<clinit>(Native.java:85) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:51) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:185) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:36) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:113) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:100) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:77) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.common.util.NettyUtils.createEventLoop(NettyUtils.java:50) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.common.netty.client.TransportClientFactory.<init>(TransportClientFactory.java:88) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.client.impl.grpc.ShuffleServerGrpcNettyClient.<init>(ShuffleServerGrpcNettyClient.java:69) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.client.impl.grpc.ShuffleServerGrpcNettyClient.<init>(ShuffleServerGrpcNettyClient.java:61) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.client.factory.ShuffleServerClientFactory.createShuffleServerClient(ShuffleServerClientFactory.java:56) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.client.factory.ShuffleServerClientFactory.getShuffleServerClient(ShuffleServerClientFactory.java:73) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.client.impl.ShuffleWriteClientImpl.getShuffleServerClient(ShuffleWriteClientImpl.java:1024) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.client.impl.ShuffleWriteClientImpl.registerShuffle(ShuffleWriteClientImpl.java:546) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.spark.shuffle.RssShuffleManager.lambda$registerShuffleServers$3(RssShuffleManager.java:881) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:3.3.1]
				at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1723) ~[?:1.8.0_362]
				at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647) ~[?:1.8.0_362]
				at org.apache.spark.shuffle.RssShuffleManager.registerShuffleServers(RssShuffleManager.java:879) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:3.3.1]
				at org.apache.spark.shuffle.RssShuffleManager.lambda$registerShuffle$1(RssShuffleManager.java:444) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:3.3.1]
				at org.apache.uniffle.common.util.RetryUtils.retryWithCondition(RetryUtils.java:82) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.common.util.RetryUtils.retry(RetryUtils.java:61) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.uniffle.common.util.RetryUtils.retry(RetryUtils.java:32) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
				at org.apache.spark.shuffle.RssShuffleManager.registerShuffle(RssShuffleManager.java:433) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:3.3.1]
				at org.apache.spark.ShuffleDependency.<init>(Dependency.scala:103) ~[spark-core_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec$.prepareShuffleDependency(ShuffleExchangeExec.scala:402) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.shuffleDependency$lzycompute(ShuffleExchangeExec.scala:173) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.shuffleDependency(ShuffleExchangeExec.scala:167) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.doExecute(ShuffleExchangeExec.scala:189) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.InputAdapter.inputRDD(WholeStageCodegenExec.scala:527) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs(WholeStageCodegenExec.scala:455) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs$(WholeStageCodegenExec.scala:454) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:498) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SortExec.inputRDDs(SortExec.scala:132) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:751) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.InputAdapter.doExecute(WholeStageCodegenExec.scala:513) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.joins.SortMergeJoinExec.inputRDDs(SortMergeJoinExec.scala:408) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:751) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.inputRDD$lzycompute(ShuffleExchangeExec.scala:135) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.inputRDD(ShuffleExchangeExec.scala:135) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.shuffleDependency$lzycompute(ShuffleExchangeExec.scala:169) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.shuffleDependency(ShuffleExchangeExec.scala:167) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.exchange.ShuffleExchangeExec.doExecute(ShuffleExchangeExec.scala:189) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.DeserializeToObjectExec.doExecute(objects.scala:96) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:194) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:232) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151) ~[spark-core_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:229) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:190) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:173) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:172) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.Dataset.rdd$lzycompute(Dataset.scala:3403) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.Dataset.rdd(Dataset.scala:3401) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.Dataset.$anonfun$toJavaRDD$1(Dataset.scala:3414) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.Dataset.$anonfun$withNewRDDExecutionId$1(Dataset.scala:3854) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:111) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:178) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:97) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:806) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.Dataset.withNewRDDExecutionId(Dataset.scala:3852) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.spark.sql.Dataset.toJavaRDD(Dataset.scala:3414) ~[spark-sql_2.12-3.3.1.jar:3.3.1]
				at org.apache.livy.thriftserver.session.SqlJob.executeSql(SqlJob.java:154) ~[livy-thriftserver-session-0.8.0-incubating.jar:0.8.0-incubating]
				at org.apache.livy.thriftserver.session.SqlJob.call(SqlJob.java:93) ~[livy-thriftserver-session-0.8.0-incubating.jar:0.8.0-incubating]
				at org.apache.livy.thriftserver.session.SqlJob.call(SqlJob.java:50) ~[livy-thriftserver-session-0.8.0-incubating.jar:0.8.0-incubating]
				at org.apache.livy.rsc.driver.JobWrapper.call(JobWrapper.java:84) ~[livy-rsc-0.8.0-incubating.jar:0.8.0-incubating]
				at org.apache.livy.rsc.driver.JobWrapper.call(JobWrapper.java:34) ~[livy-rsc-0.8.0-incubating.jar:0.8.0-incubating]
				at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_362]
				at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
				at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
				at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
**Caused by: java.io.FileNotFoundException: META-INF/native/liborg_apache_uniffle_netty_transport_native_epoll_ppcle_64.so**
	at org.apache.uniffle.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:170) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
	at org.apache.uniffle.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:305) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
	at org.apache.uniffle.io.netty.channel.epoll.Native.<clinit>(Native.java:85) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
	at org.apache.uniffle.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39) ~[rss-client-spark3-shaded-0.9.0-SNAPSHOT.jar:?]
	... 99 more

**Comment by normanmaurer** [comment]
we do not release native libraries for ppcle_64.

**Comment by rickyma** [comment]
> we do not release native libraries for ppcle_64.

What for? Could I know the reason? Thanks. @normanmaurer

**Comment by normanmaurer** [comment]
@rickyma nobody needed it and we had no way to build it. If you can provide some docker image / config to cross compile for it on intel we might be able to add it.
