### ISSUE TITLE
Http2Exception Frame length: 12870851 exceeds maximum: 16384

### ISSUE THREAD

**Issue by njimenezotto** [netty/netty#13793]
### Expected behavior
Grpc server and client works well with large metadata in TLS communication.

### Actual behavior
Client throws the error:

```
10:34:08.362 [grpc-nio-worker-ELG-1-2] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_128_GCM_SHA256
10:34:08.372 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=999990}
10:34:08.375 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
10:34:08.434 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=2147483647, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=9999990}
10:34:08.437 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] OUTBOUND SETTINGS: ack=true
10:34:08.469 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
10:34:08.471 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] INBOUND SETTINGS: ack=true
10:34:08.516 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: localhost:50054, :path: /com.example.ErrorHeaderService/sendOk, :method: POST, :scheme: https, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.59.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
10:34:08.529 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=11 bytes=00000000060a04746f746f
10:34:08.641 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] INBOUND PING: ack=false bytes=1234
10:34:08.641 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] OUTBOUND PING: ack=true bytes=1234
10:34:09.235 [grpc-nio-worker-ELG-1-2] DEBUG io.grpc.netty.NettyClientHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] OUTBOUND GO_AWAY: lastStreamId=2147483647 errorCode=6 length=45 bytes=4672616d65206c656e6774683a2031323837303835312065786365656473206d6178696d756d3a203136333834
10:34:09.238 [grpc-nio-worker-ELG-1-2] DEBUG i.n.h.c.http2.Http2ConnectionHandler - [id: 0xa22789b9, L:/127.0.0.1:54291 - R:localhost/127.0.0.1:50054] Sent GOAWAY: lastStreamId '2147483647', errorCode '6', debugData ''. Forcing shutdown of the connection.
io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
	at com.example.ErrorHeaderServiceGrpc$ErrorHeaderServiceBlockingStub.sendOk(ErrorHeaderServiceGrpc.java:179)
	at org.sample.ErrorHeaderClient.main(ErrorHeaderClient.java:54)
Caused by: io.netty.handler.codec.http2.Http2Exception: Frame length: 12870851 exceeds maximum: 16384
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:109)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processHeaderState(DefaultHttp2FrameReader.java:186)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:147)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1466)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1329)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1378)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

Server traces
```
10:34:08.404 [grpc-nio-worker-ELG-3-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] HANDSHAKEN: protocol:TLSv1.3 cipher suite:TLS_AES_128_GCM_SHA256
10:34:08.422 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] OUTBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=2147483647, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=9999990}
10:34:08.429 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
10:34:08.447 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] INBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=999990}
10:34:08.450 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] OUTBOUND SETTINGS: ack=true
10:34:08.452 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] INBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
10:34:08.472 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] INBOUND SETTINGS: ack=true
10:34:08.552 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] INBOUND HEADERS: streamId=3 headers=GrpcHttp2RequestHeaders[:path: /com.example.ErrorHeaderService/sendOk, :authority: localhost:50054, :method: POST, :scheme: https, te: trailers, content-type: application/grpc, user-agent: grpc-java-netty/1.59.1, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
10:34:08.634 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] INBOUND DATA: streamId=3 padding=0 endStream=true length=11 bytes=00000000060a04746f746f
10:34:08.635 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] OUTBOUND PING: ack=false bytes=1234
10:34:08.644 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] INBOUND PING: ack=true bytes=1234
10:34:09.053 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:status: 200, content-type: application/grpc, grpc-status-details-bin: LARGE METADATA, grpc-status: 3, grpc-message: LARGE MESSAGE] padding=0 endStream=true
10:34:09.239 [grpc-nio-worker-ELG-3-1] DEBUG io.grpc.netty.NettyServerHandler - [id: 0x369a7fc5, L:/127.0.0.1:50054 - R:/127.0.0.1:54291] INBOUND GO_AWAY: lastStreamId=2147483647 errorCode=6 length=45 bytes=4672616d65206c656e6774683a2031323837303835312065786365656473206d6178696d756d3a203136333834

```

### Steps to reproduce
The frame size issue only shows up when using TLS.
In that case, changing the inbound metadata/message size of the grpc channel and server changes nothing even if I see my values in the NettyServerBuilder (inspecting on debug grpcEmbeddedServer).
In plaintext, I have tuned a size value to reproduce that those values are well assigned by having the response in one case (sendOk sends a shorter response than sendWithError).

### Minimal yet complete reproducer code (or URL to code)
Grpc server and client reproducing the issue.

https://github.com/noeliajimenezg/errorHeader/tree/master

### Netty version
server: io.micronaut.grpc:micronaut-grpc-server-runtime 4.2.3
client: io.grpc:grpc-netty-shaded:1.59.1

### JVM version (e.g. `java -version`)
21

### OS version (e.g. `uname -a`)
Linux and Mac OS

**Comment by njimenezotto** [comment]
This PR https://github.com/netty/netty/pull/13786 fix my issue
