### ISSUE TITLE
As of Netty 4.1.108.Final, an exception is logged in debug level if no Bouncy Castle provider is used

### ISSUE THREAD

**Issue by privatestatic** [netty/netty#13967]
After upgrading netty from 4.1.107.Final to 4.1.108.Final, an exception is logged in debug level for a missing Bouncy Castle provider when no Bouncy Castle provider is used.

Netty otherwise seems to work correctly.

The problem seems to be caused by the changes in the JdkSslServerContext in commit [e817660](https://github.com/netty/netty/commit/e8176601344b1c22e0f6c1dfc2861d7a92f54030).

### Expected behavior
It would probably be better if in this case only a note is logged, but not the stack trace.

### Actual behavior
An exception is logged when no Bouncy Castle provider is used.

`24-04-10 11:48:41,113 D [nioEventLoopGroup-2-1     BouncyCastlePemReader            87] Cannot load Bouncy Castle provider
java.lang.ClassNotFoundException: org.bouncycastle.jce.provider.BouncyCastleProvider
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:398) ~[?:?]
	at io.netty.handler.ssl.BouncyCastlePemReader$1.run(BouncyCastlePemReader.java:80) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.handler.ssl.BouncyCastlePemReader$1.run(BouncyCastlePemReader.java:73) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at io.netty.handler.ssl.BouncyCastlePemReader.tryLoading(BouncyCastlePemReader.java:73) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.handler.ssl.BouncyCastlePemReader.isAvailable(BouncyCastlePemReader.java:60) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1180) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.handler.ssl.JdkSslServerContext.checkIfWrappingTrustManagerIsSupported(JdkSslServerContext.java:82) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.handler.ssl.JdkSslServerContext.<clinit>(JdkSslServerContext.java:65) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:472) [netty-handler-4.1.108.Final.jar:4.1.108.Final]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:610) [netty-handler-4.1.108.Final.jar:4.1.108.Final]`

### JVM version (e.g. `java -version`)
openjdk 11.0.21 2023-10-17
OpenJDK Runtime Environment Temurin-11.0.21+9 (build 11.0.21+9)
OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)

### OS version (e.g. `uname -a`)
OS Name	Microsoft Windows Server 2022 Standard
Version	10.0.20348 Build 20348

**Comment by normanmaurer** [comment]
This is just a debug log as we try to load bouncy castle and fallback to something else if it's not there. Nothing to worry about.
