### ISSUE TITLE
java.lang.NoSuchMethodError: io.netty.channel.epoll.EpollEventLoop.deadlineNanos()J

### ISSUE THREAD

**Issue by henry-sun** [netty/netty#14059]
sorry，my english is not very well：

2024.05.20 13:28:57.911 INFO  28446 --- [ioEventLoopGroup-5-1] i.n.u.i.l.Slf4JLogger                    : Starting with epoll library
2024.05.20 13:28:57.914 INFO  28446 --- [ioEventLoopGroup-5-1] i.n.u.i.l.Slf4JLogger                    : Starting without optional kqueue library
2024.05.20 13:28:57.958 WARN  28446 --- [e-epollEventLoop-6-1] i.n.u.i.l.Slf4JLogger                    : Unexpected exception in the selector loop.
java.lang.NoSuchMethodError: io.netty.channel.epoll.EpollEventLoop.deadlineNanos()J
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:243)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:269)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2024.05.20 13:28:58.959 WARN  28446 --- [e-epollEventLoop-6-1] i.n.u.i.l.Slf4JLogger                    : Unexpected exception in the selector loop.
java.lang.NoSuchMethodError: io.netty.channel.epoll.EpollEventLoop.deadlineNanos()J
	at io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:243)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:269)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by henry-sun** [comment]
my project run well in my local env，my local env is windows，but when move to linux server，it appear the problem

**Comment by chrisvest** [comment]
Make sure your Netty dependencies are the same version.

**Comment by normanmaurer** [comment]
Yes this looks like a version missmatch

**Comment by henry-sun** [comment]
thans for your answer，i try to change my project's netty version as same as "spring-boot-starter-redis" 's netty version，it work!
