### ISSUE TITLE
HttpPostRequestDecoder$TooLongFormFieldException

### ISSUE THREAD

**Issue by heixiaoma** [netty/netty#14125]
After upgrading to 4.1.110.Final, I found that when posting a large amount of data, such as a List collection containing 100 UUIDs sent in the application/json;charset=UTF-8 format, the following error occurs.
 
```
io.netty.handler.codec.http.multipart.HttpPostRequestDecoder$TooLongFormFieldException: null
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.offer(HttpPostStandardRequestDecoder.java:341)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.<init>(HttpPostStandardRequestDecoder.java:198)
	at io.netty.handler.codec.http.multipart.HttpPostStandardRequestDecoder.<init>(HttpPostStandardRequestDecoder.java:165)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.java:118)
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.java:92)
	at cn.hserver.plugin.web.handlers.HServerContentHandler.handlerBody(HServerContentHandler.java:94)
	at cn.hserver.plugin.web.handlers.HServerContentHandler.channelRead0(HServerContentHandler.java:43)
	at cn.hserver.plugin.web.handlers.HServerContentHandler.channelRead0(HServerContentHandler.java:26)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:300)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:750)

```

https://github.com/netty/netty/commit/a300058380ec531db9af9d18585bd732e3039355

**Comment by heixiaoma** [comment]
> HttpPostStandardRequestDecoder

new DefaultHttpDataFactory(Integer.MAX_VALUE);

**Comment by heixiaoma** [comment]
I found that it gets restricted when it exceeds 1024.

**Comment by heixiaoma** [comment]
HttpPostRequestDecoder decoder = new HttpPostRequestDecoder( req, -1,-1);
With the above configuration, I disabled caching and completed the parsing.

**Comment by gniadeck** [comment]
I also noticed this change and looks like it was introduced to fix [this vulnerability](https://github.com/advisories/GHSA-5jpm-x58v-624v). `maxUnbufferedBytes` was set to `1024` by default, and it was marked as a breaking change ([commit](https://github.com/netty/netty/commit/0d0c6ed782d13d423586ad0c71737b2c7d02058c)). I think such value might be too small especially for parsing JSON through `HttpPostRequestDecoder`, but it can be easily adjusted through constrcutor as you posted above (setting it to -1 should disable the check, but can also potentially expose you to OOM that was fixed)

**Comment by heixiaoma** [comment]
> I also noticed this change and looks like it was introduced to fix [this vulnerability](https://github.com/advisories/GHSA-5jpm-x58v-624v). `maxUnbufferedBytes` was set to `1024` by default, and it was marked as a breaking change ([commit](https://github.com/netty/netty/commit/0d0c6ed782d13d423586ad0c71737b2c7d02058c)). I think such value might be too small especially for parsing JSON through `HttpPostRequestDecoder`, but it can be easily adjusted through constrcutor as you posted above (setting it to -1 should disable the check, but can also potentially expose you to OOM that was fixed)

I also think 1024 is relatively small. Thank you for your reply. Currently, I have resolved this issue and the best way is to make a parameter configuration to prevent larger JSON submissions

**Comment by rakeshdavanum** [comment]
Hi @heixiaoma , @gniadeck , 
We have a Micronaut 3.x based application that is bringing in netty-codec-http as a dependency and we are running into this issue. We are currently unable to upgrade our application to Micronaut 4.x at the moment. Is there anyway we can override the default value for max fields (128) (and max buffered bytes (1024)) using a configuration or an system property or anything? Thanks!

**Comment by heixiaoma** [comment]
> Hi @heixiaoma , @gniadeck , We have a Micronaut 3.x based application that is bringing in netty-codec-http as a dependency and we are running into this issue. We are currently unable to upgrade our application to Micronaut 4.x at the moment. Is there anyway we can override the default value for max fields (128) (and max buffered bytes (1024)) using a configuration or an system property or anything? 



Thank

> Hi @heixiaoma , @gniadeck , We have a Micronaut 3.x based application that is bringing in netty-codec-http as a dependency and we are running into this issue. We are currently unable to upgrade our application to Micronaut 4.x at the moment. Is there anyway we can override the default value for max fields (128) (and max buffered bytes (1024)) using a configuration or an system property or anything? Thanks!

You can force a reduction in the Netty version, as the new version has this adjustment

**Comment by heixiaoma** [comment]
> Hi @heixiaoma , @gniadeck , We have a Micronaut 3.x based application that is bringing in netty-codec-http as a dependency and we are running into this issue. We are currently unable to upgrade our application to Micronaut 4.x at the moment. Is there anyway we can override the default value for max fields (128) (and max buffered bytes (1024)) using a configuration or an system property or anything? Thanks!

I haven't used Micronaut before, reducing the netty version is one way. The rest, you need to submit a problem to the Micronaut project to see if any optional configurations have been made

**Comment by gniadeck** [comment]
@rakeshdavanum looks like the issue was fixed on the micronaut site: https://github.com/micronaut-projects/micronaut-core/issues/10825
