### ISSUE TITLE
Netty IllegalStateException - SSLEngine already closed

### ISSUE THREAD

**Issue by ravindradaramwar** [netty/netty#14150]
We have server/client product where client connects to server over ssl. For this we are using netty framework 3.9.4.

There is no issue with few client connections. But observing below exception when trying to connect the client in thousands.

```
java.lang.IllegalStateException: SSLEngine already closed
    at org.jboss.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1074)
    at org.jboss.netty.handler.ssl.SslHandler.handleDownstream(SslHandler.java:623)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
    at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendDownstream(DefaultChannelPipeline.java:784)
    at org.jboss.netty.channel.SimpleChannelHandler.writeRequested(SimpleChannelHandler.java:292)
    at org.jboss.netty.channel.SimpleChannelHandler.handleDownstream(SimpleChannelHandler.java:254)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:591)
    at org.jboss.netty.channel.DefaultChannelPipeline.sendDownstream(DefaultChannelPipeline.java:582)
    at org.jboss.netty.channel.Channels.write(Channels.java:704)
    at org.jboss.netty.channel.Channels.write(Channels.java:671)
    at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
    at com.symantec.dlp.communications.transportlayer.impl.NettyTransportConnection$WriteOutboundDataTask.run(NettyTransportConnection.java:2126)
    at com.symantec.dlp.communications.transportlayer.impl.PrioritizedTaskQueue.run(PrioritizedTaskQueue.java:79)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:750)
```
I searched for this error and it looks like observed by many. But I could not find if it is solved in any of the future releases. Can someone help me to resolve this issue?

Netty Version - 3.9.4

**Comment by hyperxpro** [comment]
Netty 3.9 is EOL.

**Comment by ravindradaramwar** [comment]
Yes. I just want to know if it is fixed in any of the 3.x releases.

**Comment by chrisvest** [comment]
You should upgrade to the latest 3.x and begin the work to upgrade to Netty 4.1.x in any case.
