### ISSUE TITLE
JDK SSL Engine still requires heap ByteBuf?

### ISSUE THREAD

**Issue by franz1981** [netty/netty#14208]
https://github.com/netty/netty/pull/9696 has introduced a change to use heap buffers (both while wrapping and unwrapping) with the JDK SSL engine and this comment: https://github.com/netty/netty/blob/59ccbd9fd692b11f858bfbfe0ea79de364792a17/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L343-L345

seems to point to a copy happening within the JDK code, and the comment at https://github.com/netty/netty/issues/9685#issuecomment-544157904 seems to refer to this JDK impl at: https://github.com/AdoptOpenJDK/openjdk-jdk11u/blob/master/src/java.base/share/classes/sun/security/ssl/SSLEngineImpl.java#L207 but I cannot really spot where the copy into an heap buffer is happening, actually....
any pointer @normanmaurer @chrisvest ?

If this is no longer valid maybe we could add some flag to behave differently based on the JDK version which introduce the change, and return back just using direct buffer...
It would avoid additional allocations of heap arenas, which are rarely used by users - and the copy into an I/O buffer(s) while sending the out buffer to the wire.

**Comment by franz1981** [comment]
@Tim-Brooks as well because was mentioned at https://github.com/netty/netty/pull/9696

**Comment by Tim-Brooks** [comment]
The code you are looking for is `CipherSpi#bufferCrypt`. The ssl engine calls that. As of JDK21 it still uses byte arrays. 

I doubt this will change in the near future. The entire `CipherCore` class defines methods which operate directly on byte arrays. This is how `AESCipher`, `ChaCha20Cipher`, etc are implemented. Modern implementations use `VarHandles` and/or are intrinsified for performance reasons. They seem to be pretty committed to byte arrays for this class at the time being. 

This is just my understanding of the code from previous investigations. So it is possible I am missing something.

**Comment by franz1981** [comment]
It seems that I've answered this by myself running `SocketSslEchoTest` and placing a debug point on the `HeapByteBuffer` constructor:
```
Breakpoint reached
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:78)
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:408)
	at com.sun.crypto.provider.GCTR.blocksUntilRollover(GCTR.java:79)
	at com.sun.crypto.provider.GCTR.update(GCTR.java:115)
	at com.sun.crypto.provider.GCTR.doFinal(GCTR.java:257)
	at com.sun.crypto.provider.GaloisCounterMode$GCMEncrypt.doFinal(GaloisCounterMode.java:1230)
	at com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:447)
	at javax.crypto.Cipher.doFinal(Cipher.java:2500)
	at sun.security.ssl.SSLCipher$T12GcmWriteCipherGenerator$GcmWriteCipher.encrypt(SSLCipher.java:1790)
	at sun.security.ssl.OutputRecord.t10Encrypt(OutputRecord.java:441)
	at sun.security.ssl.OutputRecord.encrypt(OutputRecord.java:345)
	at sun.security.ssl.SSLEngineOutputRecord.encode(SSLEngineOutputRecord.java:287)
	at sun.security.ssl.SSLEngineOutputRecord.encode(SSLEngineOutputRecord.java:189)
	at sun.security.ssl.SSLEngineImpl.encode(SSLEngineImpl.java:305)
	at sun.security.ssl.SSLEngineImpl.writeRecord(SSLEngineImpl.java:251)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:146)
	at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:123)
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:564)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1129)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:867)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:820)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:941)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:921)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:907)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:215)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:146)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:937)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:957)
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1263)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:-1)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:-1)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)
Breakpoint reached
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:78)
	at java.nio.ByteBuffer.wrap(ByteBuffer.java:408)
	at com.sun.crypto.provider.GCTR.blocksUntilRollover(GCTR.java:79)
	at com.sun.crypto.provider.GCTR.update(GCTR.java:115)
	at com.sun.crypto.provider.GCTR.doFinal(GCTR.java:257)
	at com.sun.crypto.provider.GaloisCounterMode$GCMDecrypt.doFinal(GaloisCounterMode.java:1476)
	at com.sun.crypto.provider.GaloisCounterMode.engineDoFinal(GaloisCounterMode.java:447)
	at javax.crypto.Cipher.doFinal(Cipher.java:2500)
	at sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1659)
	at sun.security.ssl.SSLEngineInputRecord.decodeInputRecord(SSLEngineInputRecord.java:239)
	at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:196)
	at sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:159)
	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:111)
	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:308)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1443)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1336)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1385)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:530)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:469)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1407)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:918)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:833)
```

**Comment by franz1981** [comment]
@Tim-Brooks you wrote while I was pressing `enter` on the keyboard :P thanks for the answer!

**Comment by franz1981** [comment]
@Tim-Brooks I'm checking some Netty tests which uses `CipherSpi#bufferCrypt` somehow, but now that I see the code you pointed, it's more clear...

**Comment by franz1981** [comment]
I'm reading https://bugs.openjdk.org/browse/JDK-8318756 to better understand if there's anything relevant

**Comment by franz1981** [comment]
Ok it seems that, as @Tim-Brooks has said, there are no relevant changes in the recent JDK version which show any benefit from using direct buffers (and will likely won't, according to some implementations there) - it means that the current strategy used on the Netty JDK SSL handler engine is the best we could do :/ 

Thanks!

**Comment by chrisvest** [comment]
I took a look at ACCP as well, to see if they offered optimizations for `CipherSpi.engineUpdate(ByteBuffer input, ByteBuffer output)` when the buffers are direct (since ACCP uses BoringSSL under the hood) but alas, no. They also transport everything through byte arrays.
