### ISSUE TITLE
Netty issue with DNS resolution in Kubernetes environment

### ISSUE THREAD

**Issue by ma-romani** [netty/netty#14364]
### Expected behavior
We are currently using Netty as a dependency across a Springboot-based microservices platform. These microservices run as containers in a Kubernetes environment. This type of environment is very dynamic and subject to frequent autoscaling events that add or remove Virtual Machines from the Kubernetes cluster, consequently moving around the containers running inside the cluster.
The same environments also run the "internal DNS component", a set of containers distributed across the Kubernetes cluster that answer DNS queries and handle DNS resolution for all the connections happening inside the environment.

In this scenario, a container using Netty should be able resolve DNS queries by reaching any of the available DNS container replicas running in the cluster. Connectivity between any Netty application and the internal DNS should be always working apart from a few moments during cluster autoscaling events that move some containers around the cluster.
 
### Actual behavior
We experience DNS issues due to Netty during cluster autoscaling (downscaling) events.
After some digging, we identified the following order of events:
   1. Container A on Kubernetes Node A makes dns query with src port 12345 to DNS container on Node B. 
   2. Node B is scaled down and goes away. 
   3. Node A has a UDP conntrack entry for the src and dst NAT. This entry will stick around for 2mins. (this is default config in Linux)
   4. Container A makes use of same source port every time for the dns query. This matching the udp conntrack table entry and so the same NAT is used. 
   5. Query fails due to node B being gone

When this kind of situation occurs, the issue is not temporary and persists until the microservice using Netty is restarted. Only Netty clients are affected. Other Java or non-Java clients do not experience the issue.

### Netty version
reactor-netty = 1.1.19
reactor-netty-core = 1.1.19
netty-resolver-dns = 4.1.109
netty-resolver = 4.1.109

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

### OS version (e.g. `uname -a`)
Not very useful in a container environment. 

### Looking for a solution
The issue seems to be that Netty handles DNS queries with a sort of connection pool with connections that are reused and never replaced. This causes problems in kubernetes environments with dynamic nodes and linux NAT system.
I am looking for a solution that does not require to replace Netty. Is this behavior changed in later versions?
Or better, is there a way to disable/change this behavior via some configuration?

**Comment by bryce-anderson** [comment]
@ma-romani, do you have an idea when this started happening? There was _potentially_ a change in behavior in 394a20f436daa8719b77f60ce9cc8b5daffffd6e which was first released in netty 4.1.107-Final but I'm not sure if that lines up with when the problem started happening.

**Comment by normanmaurer** [comment]
Yeah would be good if it started at a specific version or if its like this forever

**Comment by ma-romani** [comment]
Hi,
small correction about current Netty versions, I missed a parent POM

reactor-netty = 1.1.19
reactor-netty-core = 1.1.19
netty-resolver-dns = 4.1.105
netty-resolver = 4.1.105



@bryce-anderson @normanmaurer it's not trivial to determine if the issue was there from the beginning or not. The issue appeared a few times in the last 6 months (mostly March and June). However, due to a coincidental infrastructure configuration, the issue had been hidden for an unknown amount of time prior to that.
It was hidden by the fact that, when DNS containers are deployed to all nodes, DNS resolution prioritizes DNS containers on the same node. In this scenario, when nodes get downscaled, both DNS "server" containers and application "client" containers are shut down at the same time since they are "paired" on the same node.

The issue appeared when an infrastructural change did not guarantee DNS containers on all nodes anymore. We are not in full control of the infrastructure so it was difficult to understand the cause. The issue is now under control because we got the infrastructure provider to temporarily rollback the change in order to save the production environment.

I noticed that 6 months we were using an older version of Netty. I am trying to trace back the history of the project's POM to better pinpoint the actual version so that we can exclude newer versions.

**Comment by ma-romani** [comment]
Update:
6 months (March 2024) ago we had netty version 4.1.87.Final
a couple months prior (January 2024) we had netty version 4.1.31

As I said before, it's unclear if the issue was hidden from the start or just for some time prior to March 2024.

**Comment by normanmaurer** [comment]
This sounds very similar to the issue here 

https://quentin.machu.dev/2018/06/24/5-15s-dns-lookups-on-kubernetes/

Do you agree @ma-romani ?

**Comment by ma-romani** [comment]
Hi @normanmaurer 
initially we investigated in that direction because the issue looks similar indeed.
But we eventually ruled it out due to several reasons:

- the issue only affected netty clients. Other java clients (even from the same impacted container instances) did not experience it. Equivalent curl requests fired from the same containers did not experience the issue.
- the issue is triggered by downscaling events. If cluster autoscaling is disabled, the issue never happens.
- we did some TCP dumps on the nodes hosting impacted pods and could not confirm the scenario described in the linked page
- we eventually got troubleshooting help from the infrastructure provider, who identified the root cause of the issue at low level, which I wrote in the first message under "actual behavior"

**Comment by normanmaurer** [comment]
@ma-romani this might be just because non-netty resolvers are using a new socket per query while netty use the same for all. I wonder if this is the root-cause to all the problems. 

Would it be possible to capture a Wireshark dump when this happens to understand if we actually receive the response at all or not ?

**Comment by ma-romani** [comment]
@normanmaurer yes something like that is the root-cause of the problem in our hypothesis. I was wondering if you can confirm that netty uses the same port for DNS queries and if this behavior can be modified through some configuration and/or update. I had a look at the javadoc but I did non find anything relevant for the issue.

Right now I cannot take a tcp dump easily since the issue is kept under control via infrastructure trick. But when we opened older dumps on whireshark we saw that the response was never received. Only packets with source = application IP and destination = DNS ip were captured, no packets were captured in the other direction for the impacted "conversation". Other working DNS queries (other clients) were fully captured correctly with both request and response.

**Comment by normanmaurer** [comment]
As we use the same socket it uses the same source port... at the moment the only thing that we can do is to create a new resolver.

**Comment by ma-romani** [comment]
Is it feasible to implement? Just to understand if we can expect to properly solve the issue in the future through a library upgrade or not.  I imagine that this partial incompatibility with some mechanisms found in environments such as Kubernetes and Openshift could cause issue to other people.

**Comment by solidcellaMoon** [comment]
I have the same problem and I am using Spring Cloud 2022.0.5

- reactor-netty: 1.1.5
- reactor-netty-core: 1.1.5
- netty-resolver-dns: 4.1.77.Final
- netty-resolver: 4.1.77.Final

**Comment by normanmaurer** [comment]
Can you please try to use `ChannelPerResolve` strategy and see if this solves the issue: https://github.com/netty/netty/commit/9ff63a5993abd184d433196542c5e442dc2e512f#diff-695d5a21b52a0681b0d498e1051a281dabec7585fb8c8837db73b40eb7fb4ad4R33 ?

**Comment by ma-romani** [comment]
@normanmaurer what are the steps needed to try the new strategy? Should we upgrade to a new version? Should we add some form of configuration?

**Comment by normanmaurer** [comment]
@ma-romani upgrade to 4.1.114.Final and set the `ChannelPerResolve` strategy on the `DnsNameResolverBuilder`

**Comment by prabalpsr** [comment]
@normanmaurer do you suggest using `ChannelPerResolve**r**` or the new `ChannelPerResolution` strategy (Use a new Channel per resolution or per explicit query) with netty 4.1.114.Final. 

We are seeing similar issue in our application deployed on Kubernetes and hence are taking up this release. We wanted to be sure on what option we should proceed with. The enum definition of `ChannelPerResolution` seems to be more oriented towards the Kubernetes environment but your comment suggests to go with `ChannelPerResolver`.

Here is the definition of `ChannelPerResolution` from enum definition of the 2 strategies
/**
     * Use a new {@link io.netty.channel.Channel} per resolution or per explicit query. As of today this is similar
     * to what the {@link io.netty.resolver.DefaultNameResolver} (JDK default) does. As we will need to open and close
     * a new socket for each resolution it will come with a performance overhead. That said using this strategy should
     * be the most robust and also guard against problems that can arise in kubernetes (or similar) setups.
     */
------------------------------------------------

@ma-romani 
Thanks for opening up this issue as it kind of is similar to the issue that we are seeing in our code running on Kubernetes. I don't know what version of kubernetes you guys are on, but did you check the open issues in kubernetes. We found this bug being fixed in the kubernetes code  [#127780](https://github.com/kubernetes/kubernetes/pull/127780) and it completely mimics our issue. This new bug has been reported as part of Issue [#125467](https://github.com/kubernetes/kubernetes/issues/125467) “Conntrack tables having stale entries for UDP connection”

Sorry this last comment has nothing to do with Netty but just wanted to point it out, if it helped others

**Comment by normanmaurer** [comment]
The new `ChannelPerResolution`.

**Comment by normanmaurer** [comment]
@prabalpsr @ma-romani any update ?

**Comment by prabalpsr** [comment]
@normanmaurer: Our current testing shows that the issue is resolved with the latest Netty fix (114) in our app. However, we are still working on rolling out the K8 fix as we noticed contract corruption in UDP DNS resolution calls when DNS resolution exception occurred.

**Comment by ma-romani** [comment]
@normanmaurer sorry we have not tested yet, I am still trying to plan some tests with netty 4.1.114.Final together with our development team.

@prabalpsr thank you for pointing out the k8s issue. We are running on Openshift, between version 4.14 and 4.15, which are based on k8s 1.27 and 1.28 respectively. I see that the Conntrack tables issue was introduced in k8s 1.29 so it should not be impacting us right now. I will keep an eye on it in preparation of our next update cycle.

**Comment by dpozinen** [comment]
I'm using lettuce redis and am facing the same issue, I have tried the new `ChannelPerResolution`, but unfortunately it didn't change anything:
```

Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to redis.ix-redis/<unresolved>:30036
 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:63) ~[lettuce-core-6.4.0.RELEASE.jar!/:6.4.0.RELEASE/83f459a]
 	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:41) ~[lettuce-core-6.4.0.RELEASE.jar!/:6.4.0.RELEASE/83f459a]
 	at io.lettuce.core.AbstractRedisClient.getConnection(AbstractRedisClient.java:354) ~[lettuce-core-6.4.0.RELEASE.jar!/:6.4.0.RELEASE/83f459a]
 	at io.lettuce.core.RedisClient.connect(RedisClient.java:219) ~[lettuce-core-6.4.0.RELEASE.jar!/:6.4.0.RELEASE/83f459a]
 	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1(StandaloneConnectionProvider.java:112) ~[spring-data-redis-3.3.5.jar!/:3.3.5]
 	at java.base/java.util.Optional.orElseGet(Optional.java:364) ~[na:na]
 	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:112) ~[spring-data-redis-3.3.5.jar!/:3.3.5]
 	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1778) ~[spring-data-redis-3.3.5.jar!/:3.3.5]
	... 50 common frames omitted
Caused by: java.net.UnknownHostException: Failed to resolve 'redis.ix-redis' [A(1)]
 	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1150) ~[netty-resolver-dns-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1097) ~[netty-resolver-dns-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:455) ~[netty-resolver-dns-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:686) ~[netty-resolver-dns-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.resolver.dns.DnsResolveContext.access$500(DnsResolveContext.java:70) ~[netty-resolver-dns-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:513) ~[netty-resolver-dns-4.1.114.Final.jar!/:4.1.114.Final]
        ...
 	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1491) ~[netty-resolver-dns-4.1.114.Final.jar!/:4.1.114.Final]
 	...
 	at io.netty.channel.epoll.EpollDatagramChannel.processPacket(EpollDatagramChannel.java:662) ~[netty-transport-classes-epoll-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.channel.epoll.EpollDatagramChannel.recvmsg(EpollDatagramChannel.java:697) ~[netty-transport-classes-epoll-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.channel.epoll.EpollDatagramChannel.access$300(EpollDatagramChannel.java:56) ~[netty-transport-classes-epoll-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:536) ~[netty-transport-classes-epoll-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:501) ~[netty-transport-classes-epoll-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:399) ~[netty-transport-classes-epoll-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.114.Final.jar!/:4.1.114.Final]
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.114.Final.jar!/:4.1.114.Final]
 	at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
Caused by: io.netty.resolver.dns.DnsErrorCauseException: Query failed with NXDOMAIN
 	at io.netty.resolver.dns.DnsResolveContext.onResponse(..)(Unknown Source) ~[netty-resolver-dns-4.1.114.Final.jar!/:4.1.114.Final]

```

**Comment by jose-galvez** [comment]
I was running into a similar connection error as @dpozinen with our Kubernetes setup using Redisson in our JDK8 setups (JDK17 works fine). I tracked down the problem to https://github.com/netty/netty/pull/14375/, specifically to setting the `localAddress` to `InetSocketAddress(0)` by default on the `DnsNameResolverBuilder`since that means the "if" changes in `DnsNameResolver` always go to the `else` part so it always binds to that address and never "registers" the option (this is still the same situation after the refactoring done in https://github.com/netty/netty/pull/14374). By undoing the changes to `DnsNameResolverBuilder` done in https://github.com/netty/netty/pull/14375/ we fixed our dns/connection issues.

I don't know why this makes the resolutions/connections fail on JDK8 and not in JDK17, but that has been our experience. Maybe removing that default SocketAddress change helps others too
