### ISSUE TITLE
java.lang.IllegalStateException: failed to create a child event loop

### ISSUE THREAD

**Issue by faranak-cs** [netty/netty#14397]
### Expected behavior
Run all integration tests
### Actual behavior
Fails on integration tests phase in Jenkins pipeline
### Steps to reproduce
Error comes up when I try to build the code on **Jenkins**. The code contains **UT** and **IT** based on `Java17`, `Maven 3.6.0` and `Testcontainers`. All the tests are **running OK** locally but failing on **Jenkins pipeline** on **IT** stage.
### Error:
```shell
java.lang.IllegalStateException: failed to create a child event loop

	at org.apache.pulsar.shade.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)

	at org.apache.pulsar.shade.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)

	at org.apache.pulsar.shade.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)

	at org.apache.pulsar.shade.io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)

	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)

	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)

	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:69)

	at org.apache.pulsar.shade.org.asynchttpclient.netty.channel.NioTransportFactory.newEventLoopGroup(NioTransportFactory.java:32)

	at org.apache.pulsar.shade.org.asynchttpclient.netty.channel.NioTransportFactory.newEventLoopGroup(NioTransportFactory.java:21)

	at org.apache.pulsar.shade.org.asynchttpclient.netty.channel.ChannelManager.<init>(ChannelManager.java:133)

	at org.apache.pulsar.shade.org.asynchttpclient.DefaultAsyncHttpClient.<init>(DefaultAsyncHttpClient.java:92)

	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.<init>(AsyncHttpConnector.java:183)

	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnectorProvider.getConnector(AsyncHttpConnectorProvider.java:52)

	at org.apache.pulsar.client.admin.internal.PulsarAdminImpl.<init>(PulsarAdminImpl.java:150)

	at org.apache.pulsar.client.admin.internal.PulsarAdminBuilderImpl.build(PulsarAdminBuilderImpl.java:44)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.base/java.lang.reflect.Method.invoke(Method.java:568)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)

	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)

	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)

	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)

	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)

	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)

	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)

	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)

	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)

	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)

	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)

	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)

	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)

	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)

	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)

	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)

	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)

	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)

	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)

	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)

	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)

	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)

	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)

	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)

	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

Caused by: org.apache.pulsar.shade.io.netty.channel.ChannelException: failed to open a new selector

	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:179)

	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:146)

	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:183)

	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:38)

	at org.apache.pulsar.shade.io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)

	... 61 more

Caused by: java.io.IOException: Too many open files

	at java.base/sun.nio.ch.EventFD.eventfd0(Native Method)

	at java.base/sun.nio.ch.EventFD.<init>(EventFD.java:40)

	at java.base/sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:82)

	at java.base/sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:36)

	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:177)

	... 65 more

``` 
### Minimal yet complete reproducer code (or URL to code)
```groovy
#!/usr/bin/env groovy


def java = null
def maven = null
def mavenEnv = null
def version = null
def mvnLocalHome = "/path/to/local/"
def img = null


def wasManuallyKickedOff() {
    return currentBuild.rawBuild.getCauses()[0].class.toString().endsWith('UserIdCause')
}

def isRelease() {
    return env.BRANCH_NAME == 'master' && wasManuallyKickedOff()
}

def currentVersion(mavenEnv) {
    withEnv(mavenEnv) {
        def pom = readMavenPom file: 'pom.xml'
        def version = sh script: "echo ${pom.getVersion().trim()} | grep -Eo '[0-9\\.]+'", returnStdout: true
        return version.trim()
    }
}

def createVersion(version) {
    version = version + (isRelease() ? '' : "-${env.BRANCH_NAME}-SNAPSHOT")
    return version
}

pipeline {
    agent {
        label 'docker'
    }
    stages {
        stage('Initialize') {
            steps {
                script {
                    checkout scm
                    java = tool name: 'Eclipse Temurin openjdk17-17.0.6_10', type: 'jdk'
                    maven = tool name: 'maven 3.6.0', type: 'maven'
                    mavenEnv = ["MVN_HOME=${maven}", "JAVA_HOME=${java}", "PATH+MAVEN=${maven}/bin"]
                    sh 'echo from here *****************************************'
                    sh 'echo ${JAVA_HOME}'
                    version = createVersion(currentVersion(mavenEnv))
                }
            }
        }
        stage('Build and unit test') {
            steps {
                script {
                    withEnv(mavenEnv) {
                        sh 'echo "testcontainers.reuse.enable=true" > /opt/jenkins/.testcontainers.properties'
                        sh "mvn clean test install -B -U -e -Dmaven.repo.local=${mvnLocalHome} -DskipITs"
                    }
                }
            }
        }
        stage('(**PRODUCTION Version) ITs: "datastax/lunastreaming-all:3.1_4.6"') {
            steps {
                script {
                    withEnv(mavenEnv) {
                        sh "mvn clean verify -pl integration-tests -Dmaven.repo.local=${mvnLocalHome} -P datastax_lunastreaming_all_3_1_4_6"
                    }
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    withEnv(mavenEnv) {
                        if (isRelease()) {
                            sh "mvn -Dresume=false release:clean release:prepare release:perform -Dmaven.javadoc.skip=true -DskipTests -Dmaven.repo.local=${mvnLocalHome}"
                        } else {
                            sh "mvn versions:set -DnewVersion=${version} -Dmaven.repo.local=${mvnLocalHome}"
                            sh "mvn deploy -DskipTests -Dmaven.repo.local=${mvnLocalHome}"
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by faranak-cs** [comment]
I tried to add the following stage in Jenkinsfile. `ulimit -n `is 8192. I want to change it to 16384 but it gives the **error:** `line 1: ulimit: open files: cannot modify limit: Operation not permitted`

### Stage
```groovy
stage('Check limits') {
            steps {
                script {
                    sh 'ulimit -n 16383'
                    sh 'ulimit -n'
                    sh 'ulimit -n -S'
                    sh 'ulimit -n -H'
                }
            }
        }
```

**Comment by normanmaurer** [comment]
This has nothing to do with netty but with configure your build system.... closing

**Comment by faranak-cs** [comment]
@normanmaurer Thanks for getting back. Can you please further guide here #14396. It would be very helpful, thanks again!
