### ISSUE TITLE
Issues with direct buffers on JDK24

### ISSUE THREAD

**Issue by denismakogon** [netty/netty#14392]
Here's the problem. We use custom-built JDK24 (jlink-ed) runtimes in order to limit JVM footprint on a system (think of serverless), custom runtime consists of the following modules:
```txt
java.base
java.naming
java.logging
java.sql
java.xml
java.desktop
java.net.http
```

On our runtime, for some reason, Netty's has issues with direct buffers. Therefore we see a message like this:
```text
INFO: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
```
and then we have the following error message:
```txt
"readerIndex: 383, writerIndex: 69 (expected: 0 <= readerIndex <= writerIndex <= capacity(69))"
```
followed by the stack trace:
```java
at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) 
at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) 
at io.netty.buffer.CompositeByteBuf.readerIndex(CompositeByteBuf.java:1965) 
at io.netty.buffer.CompositeByteBuf.readerIndex(CompositeByteBuf.java:49) 
```

So, apparently there's something that our runtime might be missing, therefore I'd like to know what's missing in our runtime and causing direct buffer issues?

### Netty version
4.1.108

### JVM version (e.g. `java -version`)
24 build 16

### OS version (e.g. `uname -a`)
Oracle Linux

**Comment by normanmaurer** [comment]
@denismakogon please show the full stack trace.

**Comment by denismakogon** [comment]
That's the maximum of what I can share:
```java
at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) 
at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) 
at io.netty.buffer.CompositeByteBuf.readerIndex(CompositeByteBuf.java:1965) 
at io.netty.buffer.CompositeByteBuf.readerIndex(CompositeByteBuf.java:49) 
at oracle.nosql.driver.util.NettyByteInputStream.setOffset(NettyByteInputStream.java:58) 
at oracle.nosql.driver.util.NettyByteInputStream.skip(NettyByteInputStream.java:63) 
at oracle.nosql.driver.util.SerializationUtil.readStdUTF8String(SerializationUtil.java:296) 
at oracle.nosql.driver.util.SerializationUtil.readString(SerializationUtil.java:219) 
at oracle.nosql.driver.Nson.readString(Nson.java:336) 
at oracle.nosql.driver.values.FieldFinder$MapWalker.next(FieldFinder.java:446) 
at oracle.nosql.driver.ops.serde.nson.NsonSerializerFactory$PutRequestSerializer.deserialize(NsonSerializerFactory.java:686) 
at oracle.nosql.driver.http.Client.processOKResponse(Client.java:1111) 
at oracle.nosql.driver.http.Client.processResponse(Client.java:1092) 
at oracle.nosql.driver.http.Client.execute(Client.java:644) 
at oracle.nosql.driver.http.NoSQLHandleImpl.put(NoSQLHandleImpl.java:182) 

```

**Comment by franz1981** [comment]
Can you enable debug logs (or debug it) to see what happen around this? 

https://github.com/netty/netty/blob/7679b9efdec71b54d06db91eef40ad913681294a/common/src/main/java/io/netty/util/internal/PlatformDependent.java#L193

https://github.com/openjdk/jdk/blob/jdk-24%2B18/src/jdk.unsupported/share/classes/sun/misc/Unsafe.java#L1743

shows that `Unsafe::invokeCleaner` should be still there unless the opened modules are not enough to hit it, which should be logged at https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/CleanerJava9.java#L71-L73
if you enable debug logging

Another possitibility is that `Unsafe` itself is not usable

**Comment by denismakogon** [comment]
After some experiments it was figured out that our JDK setup was clearly missing one of the JDK internal modules that is intentionally excluded. But the problem is why would netty need JDK internals and why it's not documented anywhere which exact JDK modules it requires (note that I'm not talking about `module-info.java`)?

**Comment by normanmaurer** [comment]
It should work without unsafe etc ... can I see your InputStream implementation ?

**Comment by normanmaurer** [comment]
@denismakogon ping ...

**Comment by denismakogon** [comment]
Hey! Sorry, had to move fast and skip the issue we've encountered.
I didn't look close what exactly causing the error, but we use the following library: https://github.com/oracle/nosql-java-sdk.

Our main problem is that we use modular custom runtimes, and for some reason we can't figure out which modules netty needs because many of them are not imported/used in "normal" way but through the reflection. So, I wonder what internal modules does netty needs to operate normally?

**Comment by normanmaurer** [comment]
@denismakogon it doesn't need any... internal APIs are just used for max performance and so if not available we will fallback to not using them.

**Comment by normanmaurer** [comment]
@denismakogon after having a look at the implementation I think something is wrong here:

https://github.com/oracle/nosql-java-sdk/blob/main/driver/src/main/java/oracle/nosql/driver/util/ByteInputStream.java#L45

```
    /**
     * Sets the read offset. It can only be set smaller than the current
     * offset
     * @param offset the offset
     * @throws IllegalArgumentException if the offset exceeds the current offset
     */
    public void setOffset(int offset);
```

And here is the implementation of skip:

https://github.com/oracle/nosql-java-sdk/blob/main/driver/src/main/java/oracle/nosql/driver/util/NettyByteInputStream.java#L64C1-L67C6
```
    @Override
    public void skip(int toSkip) {
        setOffset(getOffset() + toSkip);
    }
```

Which in fact should throw as it set the offset to something larger then the current offset.

That said I think the real problem comes from how SerializationUtil.readStdUTF8String(...) interacts with the `NettyByteInputStream`:
https://github.com/oracle/nosql-java-sdk/blob/main/driver/src/main/java/oracle/nosql/driver/util/SerializationUtil.java#L274C27-L274C44

```
    private static String readStdUTF8String(ByteInputStream in)
        throws IOException {

        final int length = readPackedInt(in);
        if (length < -1) {
            throw new IOException("Invalid length of String: " + length);
        }
        if (length == -1) {
            return null;
        }
        if (length == 0) {
            return EMPTY_STRING;
        }

        if (in.isDirect()) {
            final byte[] bytes = new byte[length];
            in.readFully(bytes);
            return StandardCharsets.UTF_8.decode(
                ByteBuffer.wrap(bytes)).toString();
        } else {
            final byte[] bytes = in.array();
            int offset = in.getOffset();
            in.skip(length);
            return StandardCharsets.UTF_8.decode(
                ByteBuffer.wrap(bytes, offset, length)).toString();
        }
    }
```

Here it calls `in.getOffset()` which only returns the readerIndex of the underlying `ByteBuf`:
https://github.com/oracle/nosql-java-sdk/blob/main/driver/src/main/java/oracle/nosql/driver/util/NettyByteInputStream.java#L45

And then directly use the underlying array without taking the offset of the array into account (which might be not 0) and should by obtained via `ByteBuf.arrayOffset()`.
