### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: minNewCapacity : -2147483236 (expected: >= 0)

### ISSUE THREAD

**Issue by sdman123** [netty/netty#14461]
### Netty version
4.1.100

### JVM version (e.g. `java -version`)
jdk1.8

### description
Recently, we suddenly reported an Exception online：
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: minNewCapacity : -2147483236 (expected: >= 0)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:294)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: minNewCapacity : -2147483236 (expected: >= 0)
        at io.netty.util.internal.ObjectUtil.checkPositiveOrZero(ObjectUtil.java:144)
        at io.netty.buffer.AbstractByteBufAllocator.calculateNewCapacity(AbstractByteBufAllocator.java:253)
        at io.netty.handler.codec.ByteToMessageDecoder.expandCumulation(ByteToMessageDecoder.java:560)
        at io.netty.handler.codec.ByteToMessageDecoder$1.cumulate(ByteToMessageDecoder.java:103)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:288)
        ... 16 common frames omitted

I built the server with netty, using a custom decoder extends ByteToMessageDecoder，and rewrite decode() method：
protected void decode(ChannelHandlerContext ctx, ByteBuf buf, List<Object> list) {
	if (buf.readableBytes() > 4) {
		byte[] dataLength = new byte[4];
		buf.getBytes(buf.readerIndex(), dataLength);
		int messageLength = castInt(dataLength); 
		if (buf.readableBytes() >= messageLength && messageLength <= buf.writerIndex()) {
			byte[] decoded = new byte[messageLength];
			buf.readBytes(decoded);
			MyMsg bm = createMsg(decoded, messageLength);
			list.add(bm);
		}
	}
}

According to the error, I browsed the source code, 
in io.netty.handler.codec.ByteToMessageDecoder#expandCumulation method, some of the code looks like the following：
        int oldBytes = oldCumulation.readableBytes();
        int newBytes = in.readableBytes();
        int totalBytes = oldBytes + newBytes;
totalBytes does not exceed Interger.MAX_VALUE?

Although I restarted the service and temporarily solved the problem, I don't know when it will be reported again, and how should I resolve the Exception above fundamentally?

**Comment by normanmaurer** [comment]
Please upgrade to latest netty version and reopen if you can still observe the problem
