### ISSUE TITLE
IOException: Maximum number of bytes read

### ISSUE THREAD

**Issue by scarytom** [netty/netty#14479]
This issue was introduced in v4.1.115 by commit [fbf7a70](https://github.com/netty/netty/commit/fbf7a704a82e7449b48bd0bbb679f5661c6d61a3)

### Expected behavior
Netty starts without error

### Actual behavior
Netty logs an exception when starting:
```
io.netty.util.internal.PlatformDependent -- Error while reading content of /etc/os-release
java.io.IOException: Maximum number of bytes read: 8192
	at io.netty.util.internal.BoundedInputStream.checkMaxBytesRead(BoundedInputStream.java:79)
	at io.netty.util.internal.BoundedInputStream.read(BoundedInputStream.java:58)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:350)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:393)
	at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:217)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:171)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:188)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:160)
	at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:370)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:347)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:436)
	at io.netty.util.internal.PlatformDependent$4.run(PlatformDependent.java:246)
	at io.netty.util.internal.PlatformDependent$4.run(PlatformDependent.java:235)
```
What is strange is that `/etc/os-release` is a symlink to `/usr/lib/os-release`, which itself is just a 386 byte file, way under 8192 bytes.  This leads me to think there is a bug in the new `BoundedInputStream` class, but I can't immediately spot it.

### Steps to reproduce
start netty up on a system which has a non-zero /etc/os-release

### Netty version
4.1.115

### JVM version (e.g. `java -version`)
openjdk version "21.0.5" 2024-10-15 LTS
OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.5+11 (build 21.0.5+11-LTS, mixed mode, sharing)

### OS version (e.g. `uname -a`)
Linux 5d84cc8b4bf8 6.8.0-48-generic #48~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  7 11:24:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by scarytom** [comment]
I think the bug is [here](https://github.com/netty/netty/blob/e3b92c3a940038ebf19d7eb2c3436436e3d8c0a3/common/src/main/java/io/netty/util/internal/BoundedInputStream.java#L57)

Instead of
```java
int num = Math.min(len, maxBytesRead - numRead + 1);
```
this line should read
```java
int num = Math.min(len, maxBytesRead - (numRead + 1));
```

I might put a pull request together, but will need to add a unit test case first.

**Comment by Jire** [comment]
Also getting this on Arch.

Contents of `/etc/os-release`:

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo
```

**Comment by wbkys** [comment]
4.1.115.Final also encountered this problem, windos->docker(FROM openjdk:8-jdk-alpine)
