### ISSUE TITLE
IOException reading /etc/os-release in Epoll.isAvailable() after netty update 4.1.114.Final -> 4.1.115.Final

### ISSUE THREAD

**Issue by doom369** [netty/netty#14523]
```
10:08:34.701 DEBUG - Error while reading content of /etc/os-release
java.io.IOException: Maximum number of bytes read: 8192
        at io.netty.util.internal.BoundedInputStream.checkMaxBytesRead(BoundedInputStream.java:79)
        at io.netty.util.internal.BoundedInputStream.read(BoundedInputStream.java:58)
        at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:350)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:393)
        at java.base/sun.nio.cs.StreamDecoder.lockedRead(StreamDecoder.java:217)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:171)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:188)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:160)
        at java.base/java.io.BufferedReader.implReadLine(BufferedReader.java:370)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:347)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:436)
        at io.netty.util.internal.PlatformDependent$4.run(PlatformDependent.java:246)
        at io.netty.util.internal.PlatformDependent$4.run(PlatformDependent.java:235)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
        at io.netty.util.internal.PlatformDependent.addFilesystemOsClassifiers(PlatformDependent.java:235)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:226)
        at io.netty.util.internal.ClassInitializerUtil.tryLoadClasses(ClassInitializerUtil.java:32)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:83)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:40)
```

`os-release` content:

```
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

```
java -version
openjdk version "21.0.5" 2024-10-15
OpenJDK Runtime Environment (build 21.0.5+11-Ubuntu-1ubuntu122.04)
OpenJDK 64-Bit Server VM (build 21.0.5+11-Ubuntu-1ubuntu122.04, mixed mode, sharing)
```

**Comment by chrisvest** [comment]
Related PR: https://github.com/netty/netty/pull/14480

**Comment by doom369** [comment]
thanks, closing as duplcate
