### ISSUE TITLE
Enhance CleanerJava9.freeDirectBuffer for support the DirectBuffer is sliced or duplicated

### ISSUE THREAD

**Issue by xumanbu** [netty/netty#14567]
In JDK11+, PlatformDependent.freeDirectBuffer throws an exception when the DirectBuffer is sliced or duplicated. Should we support this scenario by freeing the original Buffer of the sliced or duplicated Buffer?

```
Suppressed: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.apache.uniffle.io.netty.util.internal.CleanerJava9.freeDirectBuffer(CleanerJava9.java:88)
at org.apache.uniffle.io.netty.util.internal.PlatformDependent.freeDirectBuffer(PlatformDependent.java:521)
at org.apache.uniffle.common.util.RssUtils.releaseByteBuffer(RssUtils.java:422)
at org.apache.uniffle.client.impl.ShuffleReadClientImpl.close(ShuffleReadClientImpl.java:335)
at org.apache.spark.shuffle.reader.RssShuffleDataIterator.cleanup(RssShuffleDataIterator.java:217)
at org.apache.spark.shuffle.reader.RssShuffleReader$MultiPartitionIterator.lambda$new$0(RssShuffleReader.java:289)
at scala.Function0.apply$mcV$sp(Function0.scala:39)
at org.apache.spark.util.CompletionIterator$$anon$1.completion(CompletionIterator.scala:47)
at org.apache.spark.shuffle.reader.RssShuffleReader$MultiPartitionIterator.lambda$new$1(RssShuffleReader.java:301)
at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1(TaskContextImpl.scala:144)
at org.apache.spark.TaskContextImpl.$anonfun$invokeTaskCompletionListeners$1$adapted(TaskContextImpl.scala:144)
at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:199)
... 10 more
Caused by: java.lang.IllegalArgumentException: duplicate or slice
at java.base/jdk.internal.misc.Unsafe.invokeCleaner(Unsafe.java:3846)
at jdk.unsupported/sun.misc.Unsafe.invokeCleaner(Unsafe.java:1260)
... 25 more
Caused by: java.lang.IllegalArgumentException: duplicate or slice
at java.base/jdk.internal.misc.Unsafe.invokeCleaner(Unsafe.java:3846)
at jdk.unsupported/sun.misc.Unsafe.invokeCleaner(Unsafe.java:1260)
... 31 more
```

**Comment by normanmaurer** [comment]
@xumanbu I think in this case you want to pass the original buffer to the `freeDirectBufffer` method. Also be aware that this is an internal method and so we don't encourage people use it directly
