### ISSUE TITLE
Http server crashes with "java.io.IOException: Too many open files" when hit by multiple requests

### ISSUE THREAD

**Issue by tomassommar** [netty/netty#1578]
This is easily demonstrated using [the provided Http Snoop example implementation](https://github.com/netty/netty/tree/master/example/src/main/java/io/netty/example/http/snoop) of a Netty Http Server. 

When this server is set up and stressed with multiple requests, after about 3000 - 4000 requests, the server fails with an java.io.IOException:

```
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:152)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:111)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:69)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:465)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:359)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Thread.java:662)
```

This is reproducable by running the following integration test:

```
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpRequestBase;
import org.apache.http.impl.client.DefaultHttpClient;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.JUnit4;

import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class HttpSnoopServerStressTests {

    private static final int NUMBER_OF_THREADS = 100;
    private static final int NUMBER_OF_REQUESTS = 1000;

    private SnoopServerTests snoopServerTests;
    private ThreadPoolExecutor executor;
    private static int executionCounter;

    @Before
    public void setUp() throws Exception {
        BlockingQueue blockingQueue = new ArrayBlockingQueue(NUMBER_OF_THREADS);
        executor = new ThreadPoolExecutor(NUMBER_OF_THREADS, NUMBER_OF_THREADS, 1, TimeUnit.SECONDS, blockingQueue);
        snoopServerTests = new SnoopServerTests();
    }

    @Test
    public void multiThreaded_getRequest_shouldNotFail() throws Exception {
        for (int i = 0; i < NUMBER_OF_THREADS; i++) {
            SnoopServerTestsRunnable runnable = new SnoopServerTestsRunnable();
            executor.execute(runnable);
        }
        waitForExecutionToFinish();
    }

    private void waitForExecutionToFinish() throws InterruptedException {
        executor.shutdown();
        while (!executor.awaitTermination(1, TimeUnit.SECONDS)) {
            Thread.currentThread().sleep(100L);
        }
    }

    private class SnoopServerTestsRunnable implements Runnable {

        @Override
        public void run() {
            try {
                for (int i = 0; i < NUMBER_OF_REQUESTS; i++) {
                    snoopServerTests.get_request_returns200OK();
                }

                printToConsole();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        private synchronized void printToConsole() {
            executionCounter++;
            System.out.printf("Execution number %d. Executed %d number of requests.%n", executionCounter, NUMBER_OF_REQUESTS);
        }
    }

    @RunWith(JUnit4.class)
    private class SnoopServerTests {

        @Test
        public void get_request_returns200OK() throws Exception {
            HttpClient client = new DefaultHttpClient();
            HttpRequestBase request = new HttpGet("http://HOSTNAME:8080/");

            HttpResponse response = client.execute(request);

            assertThat(response.getStatusLine().getStatusCode(), is(200));
        }
    }
}
```

When the test have ran for a couple of minutes (of course depending on your current environment), reaching approx. 3000 to 4000 requests, the server stops to respond. The above mentioned IOException is logged at the server.

This has been reproduced on 4.0.0.CR1, 4.0.0.CR9, as well as the latest snapshot 4.0.0.CR10-SNAPSHOT. 

Help with this issue would be very appreciated.

**Comment by xiaoyaoweizi** [comment]
Hi. Have the issue solved?I have met the same problem.and I use netty-4.0.34.jar.the execption show:
```
[nioEventLoopGroup-4-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.8.0_101]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422) ~[na:1.8.0_101]
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250) ~[na:1.8.0_101]
	at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:135) ~[netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:69) ~[netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.34.Final.jar:4.0.34.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.34.Final.jar:4.0.34.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```
Now I know the only solution is to increase this limit of open files in Linux system.Is there any drawbacks for the file system, latency, performance for other running applications, or anything else? Or is it the ulimit -n with a high value is already the chosen solution? what is the highest value for the Linux `system?`

**Comment by Scottmitch** [comment]
`ulimit` may not provide the whole picture. Please see http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by juliuskrah** [comment]
I am also getting this error after having the application run for about 2 months

```bash
WARN  [nioEventLoopGroup-2-1] DefaultChannelPipeline: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110)

```

How do I prevent the application from opening multiple connections that don't close?

Below are the relevant parts of the code that is running:

```java
public class TcpServerHandler extends SimpleChannelInboundHandler<ByteBuf> {
	
	@Override
	public void channelRead0(ChannelHandlerContext ctx, ByteBuf buf) throws Exception {
		// ReferenceCountUtil.release is called by SimpleChannelInboundHandler
		// ...
		ChannelFuture cf = ctx.writeAndFlush(Unpooled.copiedBuffer(new byte[] { 0x06 }));
		if (!cf.isSuccess())
			log.error("Sending acknowledgement failed with root cause", cf.cause());
		} else
			log.warn("Nothing happened");
	}
}
```

I don't think `ulimit` is the solution here as some resources are not freed up. I only get this error after the application has run for a few months, after which I have to restart it.

My configuration settings are:

```properties
SO_BACKLOG=100
BOSS_GROUP_THREADS=2
WORKER_GROUP_THREADS=2
```
