### ISSUE TITLE
ClassCastException sometimes (very few times) with an encoder

### ISSUE THREAD

**Issue by flozano** [netty/netty#1980]
```
10:52:55.674 [nioEventLoopGroup-4-2] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.ClassCastException: com.notnoop.apns.EnhancedApnsNotification cannot be cast to io.netty.buffer.ByteBuf
        at io.netty.handler.ssl.SslHandler.flush0(SslHandler.java:435) ~[netty-all-4.0.12.Final.jar:na]
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:420) ~[netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:675) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.DefaultChannelHandlerContext.access$1600(DefaultChannelHandlerContext.java:29) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.DefaultChannelHandlerContext$WriteTask.run(DefaultChannelHandlerContext.java:908) [netty-all-4.0.12.Final.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354) [netty-all-4.0.12.Final.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) [netty-all-4.0.12.Final.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [netty-all-4.0.12.Final.jar:na]
        at java.lang.Thread.run(Unknown Source) [na:1.7.0_45]
```

ApnsNotificationEncoder extends MessageToByteEncoder<EnhancedApnsNotification>, registered and working 99,999% of the time, ApnsNotification is an interface implemented by EnhancedApnsNotification, and I only have one channel.write() in the whole code. Am I doing something wrong, or maybe there is a problem with matching interfaces/classes-implementing-interfaces in encoder pipeline?

**Comment by normanmaurer** [comment]
@flozano I will close this for now ... please re-open if it still happens with the latest release and provide infos how to reproduce
