### ISSUE TITLE
HttpContentCompressor fails on client side: cannot send more responses than requests

### ISSUE THREAD

**Issue by slandelle** [netty/netty#2131]
Hi,

I'm trying to implement request compression and use HttpContentCompressor (this is actually an old async-http-client issue), but I get the following stacktrace (Netty 3.9.0, but same thing with older versions):

java.lang.IllegalStateException: cannot send more responses than requests
    at org.jboss.netty.handler.codec.http.HttpContentEncoder.writeRequested(HttpContentEncoder.java:100) ~[netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.Channels.write(Channels.java:704) ~[netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.Channels.write(Channels.java:671) ~[netty-3.9.0.Final.jar:na]
    at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248) ~[netty-3.9.0.Final.jar:na]

Here's a simple test case: https://github.com/slandelle/netty-request-compression/blob/master/src/main/java/slandelle/RequestCompressionTest.java

Cheers,

Stéphane

**Comment by timboudreau** [comment]
I'm running into this issue in a pretty legitimate situation:  Adding a feature to [Acteur](https://github.com/timboudreau/acteur) to be able to respond to a `POST` with a redirect **before** `HttpObjectAggregator` is called - i.e. no `100 Continue` response is sent, just a redirect immediately upon receiving the headers.  I.e. someone has a large upload, and I want to redirect them to a server for media uploads *without* also causing their browser to send the request body twice - just annotate your Acteur with `@Early` and it will get called as soon as headers arrive.

It seems that if you send a response that early, the state of the compressor is still `AWAIT_HEADERS`, and it is hard-coded to only tolerate that with a `100-Continue` response.  Seems like at the least, any of the redirect response codes should be okay here too.

Workaround is to have remove the compressor from the pipeline when intercepting requests early, but that shouldn't be necessary.  I'll also be using this feature for acteurs that want to process HTTP chunks on their own, though I suspect since that handles responses more conventionally, that probably won't tickle this bug.

```
Caused by: java.lang.IllegalStateException: cannot send more responses than requests
	at io.netty.handler.codec.http.HttpContentEncoder.encode(HttpContentEncoder.java:110)
	at io.netty.handler.codec.http.HttpContentEncoder.encode(HttpContentEncoder.java:51)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
```
