### ISSUE TITLE
exception when client close connection sometimes

### ISSUE THREAD

**Issue by leepengg** [netty/netty#2332]
2014-03-20 08:17:36.335 [nioEventLoopGroup-3-5] WARN  io.netty.channel.DefaultChannelPipeline - An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.7.0_45]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.7.0_45]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.7.0_45]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.7.0_45]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379) ~[na:1.7.0_45]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:446) ~[sea-1.0-SNAPSHOT.jar:na]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:871) ~[sea-1.0-SNAPSHOT.jar:na]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[sea-1.0-SNAPSHOT.jar:na]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:108) ~[sea-1.0-SNAPSHOT.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:494) [sea-1.0-SNAPSHOT.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:461) [sea-1.0-SNAPSHOT.jar:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) [sea-1.0-SNAPSHOT.jar:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) [sea-1.0-SNAPSHOT.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [sea-1.0-SNAPSHOT.jar:na]
        at java.lang.Thread.run(Thread.java:744) [na:1.7.0_45]2014-03-20 08:22:25.066 [pool-4-thread-1] 

jdk：
java version "1.7.0_45"
Java(TM) SE Runtime Environment (build 1.7.0_45-b18)
Java HotSpot(TM) 64-Bit Server VM (build 24.45-b08, mixed mode)

netty：
4.0.17.Final

os：ubuntu 12.04

**Comment by literadix** [comment]
How can I catch this exception so I can handle it and remove this message from the log file ? Could you please provide an example? I need to free ressources an user connection has claimed. Actually

**Comment by ninja-** [comment]
You're supposed to ignore exceptons when channel is inactive(exceptionCaught). Unless you're interested in them.

**Comment by ninja-** [comment]
Just add an empty exceptioncaught method to your handler
