### ISSUE TITLE
SSLEngine is closing / closed Exception

### ISSUE THREAD

**Issue by trustin** [netty/netty#2333]
Reported via the Google group:

> I encountered the following exception in Netty 3.8.
> 
> I traced netty's implementation.  It looks like this exception occurred because there was an attempt to initiate a handshake for a SSL Engine that is already closed.  When SslHandler::channelDisconnected() invokes SslHandler::unwrap(), the logic inside the unwrap() method that determines whether to initiate a handshake incorrectly evaluates to true.  This triggers an attempt to handshake on an already closed connection, which will result in an exception being thrown.
> 
> Does anyone know if there is a fix for this problem?  
> 
> Thank you.

```
javax.net.ssl.SSLException: SSLEngine is closing/closed
at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:692)
at sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:734)
at org.jboss.netty.handler.ssl.SslHandler.handshake(SslHandler.java:433)
at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1233)
at org.jboss.netty.handler.ssl.SslHandler.channelDisconnected(SslHandler.java:668)
at org.jboss.netty.channel.Channels.fireChannelDisconnected(Channels.java:396)
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:360)
at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:81)
at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
at org.jboss.netty.channel.Channels.close(Channels.java:828)
at org.jboss.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1431)
at org.jboss.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1305)
at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:925)
at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:744)
```

**Comment by StinkySandwich** [comment]
I still have this same issue in 4.0.45.Final

**Comment by johnou** [comment]
@StinkySandwich kindly open a new issue with a fresh stacktrace and reproducer.
