### ISSUE TITLE
Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel

### ISSUE THREAD

**Issue by rzo12345** [netty/netty#2341]
release 5.0.0 alpha1
code:
```        ServerBootstrap bootstrap = new ServerBootstrap();
        bootstrap.group(bossGroup, workerGroup)
        .channel(NioServerSocketChannel.class);
...
bootstrap.bind(new InetSocketAddress(port)).sync();

```

Exception:
```

`io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
    at io.netty.bootstrap.Bootstrap$BootstrapChannelFactory.newChannel(Bootstrap.java:299)
    at io.netty.bootstrap.Bootstrap.createChannel(Bootstrap.java:99)
    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:263)
    at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:234)
    at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:230)
...
Caused by: java.lang.NoSuchMethodException: io.netty.channel.socket.nio.NioServerSocketChannel.<init>(io.netty.channel.EventLoop)
    at java.lang.Class.getConstructor0(Class.java:2706)
    at java.lang.Class.getConstructor(Class.java:1657)
    at io.netty.bootstrap.Bootstrap$BootstrapChannelFactory.newChannel(Bootstrap.java:296)
    ... 6 more

```
Taking a look at the code:
NioServerSocketChannel has a constructor with 2 args, whereas BootstrapChannelFactory.newChannel requires a constructor with a single arg:

```

```
           Constructor<? extends T> constructor = clazz.getConstructor(EventLoop.class);
```

```

```

**Comment by MadhuMalluri** [comment]
Could you please let us know the issue that you faced? I am receiving similar error with my application

**Comment by xixingya** [comment]
> Could you please let us know the issue that you faced? I am receiving similar error with my application

hello，you shoud use NioSocketChannel.class in the channel
