### ISSUE TITLE
4.0.18.Final: Channel.write() can invoke a handler that has been removed from pipeline

### ISSUE THREAD

**Issue by benevans** [netty/netty#2352]
I was trying to write a channel handler that removed itself from the pipeline on channelActive(), but found that sometimes writes would still end up invoking the handler even after it had been removed. 

Here is a simple test program that demonstrates the issue: 

``` java
import io.netty.bootstrap.Bootstrap;
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.channel.socket.nio.NioSocketChannel;

import java.net.InetSocketAddress;
import java.util.concurrent.CountDownLatch;

public class HandlerRemoveRace {

    public static void main(String[] args) throws Exception {
        NioEventLoopGroup eventLoop = new NioEventLoopGroup(1);

        try {
            // Dummy server that just accepts connections, nothing more
            ServerBootstrap server = new ServerBootstrap();
            server.group(eventLoop)
                    .channel(NioServerSocketChannel.class)
                    .childHandler(new ChannelInboundHandlerAdapter() {
                        @Override
                        public void channelRead(ChannelHandlerContext ctx, Object msg) { }
                    });
            server.bind(9999).sync();

            // Signals to coordinate threads and force the race condition
            CountDownLatch startWriting = new CountDownLatch(1);
            CountDownLatch doneWriting = new CountDownLatch(1);

            Bootstrap client = new Bootstrap()
                    .group(eventLoop)
                    .channel(NioSocketChannel.class)
                    .handler(new RemoveAfterConnect(startWriting, doneWriting));
            Channel ch = client.connect(new InetSocketAddress("127.0.0.1", 9999)).channel();

            startWriting.await();
            // IO thread is in channelActive, write immediately before IO thread removes handler
            ChannelFuture writeFuture = ch.write("BOOM");
            doneWriting.countDown();
            writeFuture.sync(); // should throw IllegalStateException from the write
        } catch (Exception e) {
            e.printStackTrace(System.out);
        } finally {
            eventLoop.shutdownGracefully();
        }
    }

    static class RemoveAfterConnect extends ChannelDuplexHandler {
        private final CountDownLatch startWriting, doneWriting;

        RemoveAfterConnect(CountDownLatch startWriting, CountDownLatch doneWriting) {
            this.startWriting = startWriting;
            this.doneWriting = doneWriting;
        }

        @Override
        public void write(ChannelHandlerContext ctx, Object msg, ChannelPromise promise) throws Exception {
            System.out.printf("write: %s, (removed=%b)\n", msg, ctx.isRemoved());
            if (ctx.isRemoved()) {
                promise.setFailure(new IllegalStateException("write called after handler removed!"));
            }
            else promise.setSuccess();
        }

        @Override
        public void channelActive(ChannelHandlerContext ctx) throws Exception {
            System.out.println("channel active, signal writers");
            startWriting.countDown(); // start writing
            doneWriting.await(); // wait for writes
            System.out.println("now removing this handler");
            ctx.pipeline().remove(this);
            // Should find that the write tasks end up invoking this handler
            // because they were instantiated with a ref to this ChannelHandlerContext
            // just before the handler was removed.
        }
    }
}
```

Running this program produces the output:

```
channel active, signal writers
now removing this handler
write: BOOM, (removed=true)
java.lang.IllegalStateException: write called after handler removed!
    at HandlerRemoveRace$RemoveAfterConnect.write(HandlerRemoveRace.java:44)
    at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:666)
    at io.netty.channel.DefaultChannelHandlerContext.access$2000(DefaultChannelHandlerContext.java:30)
    at io.netty.channel.DefaultChannelHandlerContext$AbstractWriteTask.write(DefaultChannelHandlerContext.java:945)
    at io.netty.channel.DefaultChannelHandlerContext$AbstractWriteTask.run(DefaultChannelHandlerContext.java:934)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:744)
```

This program uses CountDownLatches to force a race between the main thread and the I/O thread. When the RemoveAfterConnect handler gets the channelActive callback in the I/O thread, it signals the main thread to start writing, then it removes itself from the pipeline after the write was enqueued. 

As far as I can tell, when the main thread calls Channel.write(), a WriteTask is created with a reference to the handler because it's still in the pipeline at that time. So when the I/O thread processes the WriteTask, the removed handler's write() method still gets invoked, even though it's not actually in the pipeline anymore.

I thought this might be a bug because it seems to violate the channel handler thread model, i.e. if a handler was removed in the I/O thread, then it shouldn't be invoked in the I/O thread again.

(Originally reported here: https://groups.google.com/d/msg/netty/ttdksfSHdSg/yY8wfjXF_jsJ)

**Comment by normanmaurer** [comment]
@benevans this is fixed in the master branch. There you should not observe this race anymore
