### ISSUE TITLE
Native.epollCreate(...) fails on kernel < 2.6.27

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#2361]
Caused by: java.lang.IllegalStateException: failed to create a child event loop

at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:68) ~[netty-all-4.0.18.Final.jar:4.0.18.Final]

at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49) ~[netty-all-4.0.18.Final.jar:4.0.18.Final]

at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:56) ~[netty-all-4.0.18.Final.jar:4.0.18.Final]

at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:48) ~[netty-all-4.0.18.Final.jar:4.0.18.Final]

at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:41) ~[netty-all-4.0.18.Final.jar:4.0.18.Final]

....

Caused by: java.lang.RuntimeException: Error during epoll_create(...): Function not implemented

at io.netty.channel.epoll.Native.epollCreate(Native Method) ~[netty-all-4.0.18.Final.jar:4.0.18.Final]

at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:71) ~[netty-all-4.0.18.Final.jar:4.0.18.Final]

at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:71) ~[netty-all-4.0.18.Final.jar:4.0.18.Final]

at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64) ~[netty-all-4.0.18.Final.jar:4.0.18.Final]

... 44 common frames omitted

**Comment by lizuojing** [comment]
It happens when i run my app for about two hours.I search many messages but all of them are not work.Can you tell me why it happens.
