### ISSUE TITLE
Memory Pool updates lead to OOM

### ISSUE THREAD

**Issue by timothyjward** [netty/netty#2447]
Hi,

I've been using netty as the basis for a bi-directional high throughput asynchronous messaging system. The messages generate variable amounts of work (on both sides) and are therefore processed in a separate thread (after frame decoding). Messages are published from outside the event loop. I'm using pooled byte buffers, and a fixed buffer length prediction of 64k

I started with the 5.0 Alpha1 release, which works very well. I'm seeing up to 40000 msg/s on fairly modest hardware, and stable latencies of 100 µs + ping.

Having looked at the latest 4.0 release I saw that there has been some performance work done, particularly regarding the memory pool and event work queue. This seemed like it would be a benefit, so I grabbed a build of jetty-master from Jenkins. The build is 9107, (commit 79fc0d2408cf4a89929254822835d456ab5d0036).

My basic tests all pass with the new build, but a throughput test I was running blows up very quicky with an OOM (after about 900 messages). There are no changes between the tests other than the update to netty.

```
09:13:11.937 [nioEventLoopGroup-4-1] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetectionLevel: simple
09:13:12.993 [nioEventLoopGroup-4-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.OutOfMemoryError: Direct buffer memory
    at java.nio.Bits.reserveMemory(Bits.java:658) ~[na:1.7.0_21]
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[na:1.7.0_21]
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306) ~[na:1.7.0_21]
    at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:434) ~[na:na]
    at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:179) ~[na:na]
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:168) ~[na:na]
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:98) ~[na:na]
    at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:261) ~[na:na]
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155) ~[na:na]
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146) ~[na:na]
    at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:107) ~[na:na]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:113) ~[na:na]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:507) ~[na:na]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:464) ~[na:na]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:378) ~[na:na]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:350) ~[na:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:824) ~[na:na]
    at java.lang.Thread.run(Thread.java:722) ~[na:1.7.0_21]
```

If I disable the use of direct buffers then I get a similar OOM, although that one is because I run out of heap.

My Java is:

```
localhost:bin timothyjward$ ./java -version
java version "1.7.0_21"
Java(TM) SE Runtime Environment (build 1.7.0_21-b12)
Java HotSpot(TM) 64-Bit Server VM (build 23.21-b01, mixed mode)
```

**Comment by CIsMe** [comment]
Whether you have solved the problem.  There is an article about this problem.I suggest you take look.
url:http://blog.csdn.net/mrsunnycream/article/details/45046013

**Comment by louxiu** [comment]
@CIsMe I think the problem described by that article has already be fixed by https://github.com/netty/netty/pull/3833
