### ISSUE TITLE
Netty  NioEventLoop select  method consume cpu 

### ISSUE THREAD

**Issue by fuyou001** [netty/netty#2465]
Netty version:4.0.17.Final

``` lang=java
  nettyGroup = new NioEventLoopGroup(Runtime.getRuntime().availableProcessors(), serverBossTF);
        workerGroup = new NioEventLoopGroup(Runtime.getRuntime().availableProcessors()*4, serverWorkerTF);
        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(nettyGroup, workerGroup)
                    .channel(NioServerSocketChannel.class)
                            // .option(ChannelOption.SO_REUSEADDR, true)
                    .childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                    .childOption(ChannelOption.TCP_NODELAY, true)
                    .localAddress(new InetSocketAddress(serverConfig.getPort()))
                    .childHandler(new ChannelInitializer<SocketChannel>() {
                        @Override
                        public void initChannel(SocketChannel ch)
                                throws Exception {
                            ch.pipeline().addLast(connetManageHandler);
                            ch.pipeline().addLast(new NettyRequestEncoder());
                            ch.pipeline().addLast(new NettyResponseEncoder());
                            ch.pipeline().addLast(new NettyWrapDecoder());
                            ch.pipeline().addLast(nettyServerHandler);
                        }
                    });

            ChannelFuture f = b.bind().sync();
            log.warn(NettyServer.class.getName() + " started and listen on " + f.channel().localAddress());
            f.channel().closeFuture().sync();
```

the jstack:

``` lang
the stack of busy(13.4%) thread(23632/0x5c50) of java process(23481) of user(fuyou001):
"NETTYSERVER-WORKER-19-thread-11" prio=10 tid=0x00002aaabcb3a800 nid=0x5c50 runnable [0x0000000045e37000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:210)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:65)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
        - locked <0x000000076c0e30b0> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000076c0e3b70> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000076c076c08> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:605)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Thread.java:662)

The stack of busy(13.0%) thread(23639/0x5c57) of java process(23481) of user(fuyou001):
"NETTYSERVER-WORKER-19-thread-18" prio=10 tid=0x00002aaabc28e800 nid=0x5c57 runnable [0x000000004653e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:210)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:65)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
        - locked <0x000000076c377718> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000076c411c88> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000076c0af150> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:605)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Thread.java:662)

The stack of busy(12.7%) thread(23635/0x5c53) of java process(23481) of user(fuyou001):
"NETTYSERVER-WORKER-19-thread-14" prio=10 tid=0x00002aaabc507800 nid=0x5c53 runnable [0x000000004613a000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:210)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:65)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
        - locked <0x000000076dca18d8> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000076dca3d30> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000076d742828> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:605)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Thread.java:662)

The stack of busy(12.6%) thread(23628/0x5c4c) of java process(23481) of user(fuyou001):
"NETTYSERVER-WORKER-19-thread-7" prio=10 tid=0x00002aaabc5bf800 nid=0x5c4c runnable [0x0000000045a33000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:210)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:65)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
        - locked <0x000000076f42bef8> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000076f42e4d0> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000076f3c8308> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:605)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:306)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Thread.java:662)
```

**Comment by tramchamploo** [comment]
Also focus on this. So what's the conclusion?

**Comment by ronenhamias** [comment]
is there any actual resolution / recommendation to this issue?

**Comment by lkoszanski** [comment]
Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: ronenhamiasSent: Wednesday, August 12, 2015 08:58To: netty/nettyReply To: netty/nettySubject: Re: [netty] Netty  NioEventLoop select  method consume cpu  (#2465)is there any actual resolution / recommendation to this issue?

—Reply to this email directly or view it on GitHub.

**Comment by adjsnlxx** [comment]
netty 4.1.5
jdk 1.8.101
the CPU usage is almost 100%.

"nioEventLoopGroup-3-2" #56 prio=10 os_prio=0 tid=0x0000000017f2b800 nid=0x46c7 runnable [0x00002af3fe020000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000006f3392138> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000006f33941c8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000006f33920f0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:731)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

**Comment by huangyiminghappy** [comment]
by use nio,also meet the same question:
"$_NIOREACTOR-2-RW" #28 prio=5 os_prio=0 tid=0x00007f988c154800 nid=0x794e runnable [0x00007f98d011c000]
55531-   java.lang.Thread.State: RUNNABLE
55567-	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
55625-	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
55691-	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
55760-	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
55826-	- locked <0x000000064008fcb0> (a sun.nio.ch.Util$3)
55879-	- locked <0x000000064008fc98> (a java.util.Collections$UnmodifiableSet)
55952-	- locked <0x000000064008a840> (a sun.nio.ch.EPollSelectorImpl)
56016-	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
56073-	at io.mycat.net.NIOReactor$RW.run(NIOReactor.java:91)
56128-	at java.lang.Thread.run(Thread.java:745)

**Comment by BoaNeo** [comment]
I came here from a Google search on NioEventLoop CPU usage because I just found that my completely idle Java process using Netty 4.1.12, with no active connections, is using 25% CPU (one core completely blocked).

I have 13 nioeventloop threads like the one below, all identical except for the "- lock" lines (All 39 of these are unique, so I guess no indication of deadlock(?)):

"nioEventLoopGroup-3-12@1877" prio=10 tid=0x3f nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.KQueueArrayWrapper.kevent0(KQueueArrayWrapper.java:-1)
	  at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	  at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	  - locked <0x7c4> (a sun.nio.ch.KQueueSelectorImpl)
	  - locked <0x859> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x7c5> (a io.netty.channel.nio.SelectedSelectionKeySet)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	  at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:752)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:408)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	  at java.lang.Thread.run(Thread.java:745)

All other threads in the process are accounted for and either waiting or in long-term sleep, except this one:

"threadDeathWatcher-4-1@1777" daemon prio=1 tid=0x2a nid=NA sleeping
  java.lang.Thread.State: TIMED_WAITING
	  at java.lang.Thread.sleep(Thread.java:-1)
	  at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152)
	  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	  at java.lang.Thread.run(Thread.java:745)

Has anyone had high CPU usage with no connections and been able to find out why?

**Comment by johnou** [comment]
@BoaNeo please try updating to the latest Netty release and Java then report back if problems persist.

**Comment by BoaNeo** [comment]
Thx, I'll try that, but unfortunately it happens at random so it will probably be gone after a restart even if the underlying issue is not.

**Comment by nquoctuan** [comment]
@BoaNeo 
I get same issue, and not really sure about netty. It is java 1.8.0_91-b14 and playframewok 2.5.3 (with netty 4.0).

Do you have any solution for this issue?

`"lettuce-nioEventLoop-3-1" #17 daemon prio=5 os_prio=0 tid=0x00007f393899e800 nid=0x212b runnable [0x00007f3922270000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000d57cd568> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000000d57cd588> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000d57cd520> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:639)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:325)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)`

**Comment by guss77** [comment]
I have the same issue, I think, with Netty 4.1.19, on Java 11 (I tried both OpenJDK and Amazon Corretto, both behave the same) - after running for about 24 hours, CPU usage starts climbing up with more and more CPU time spent in `EPoll.wait`:

```
14063 14122 0x372a 14.9 04:42:03 vert.x-eventloo
"vert.x-eventloop-thread-1" #55 prio=5 os_prio=0 cpu=16924095.28ms elapsed=113580.47s tid=0x00007f450c1b4000 nid=0x372a runnable  [0x00007f44b07a1000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPoll.wait(java.base@11.0.2/Native Method)
        at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.2/EPollSelectorImpl.java:120)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.2/SelectorImpl.java:124)
        - locked <0x00000000ce6358b8> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x00000000ce6368e0> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(java.base@11.0.2/SelectorImpl.java:136)
        at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
```

The first line is the last line of `ps` output showing Java threads sorted (ascending) by CPU time - the `14.9` number is the average CPU utilization across the lifetime of the thread (which is mostly idling for about 24 hours before it starts consuming CPU, so the `14.9` is actually about 30% current CPU usage of 1 core). The rest is the jstack output grepped on the native thread ID from column 3 of the `ps` output.

Anyway, this problem is very weird as it looks awfully like the "EPoll wait" bug that was supposedly fixed in Java 7 and worked around in Netty, but keeps happening with relatively up to date components - but only on one application I have: I'm running several different applications with the same core stack (Vert.x 3.6, Netty 4.1.19, Java 11, Ubuntu 18.04 on EC2), and only this one application exhibits this issue. It's not load related: the problematic application is not the least loaded of all of them, but it is pretty lightly loaded and spends most of its time idling.

Anyway, if there is any information I can provide to track down this problem, I will be very happy to do a lot of work to figure out the problem or a workaround.

For completion, the output above was generated by the following script that I created to help me figure out what Java thread is eating up the CPU - it uses `ps` to list Java threads, sort them by CPU usage, calculate the "Java native thread id" for jstack, then use jstack to extract the stack of the most CPU intensive thread. Because `ps` limitations the CPU usage measurements are "life time" usage and are unaffected by new thread activity spikes - which is actually beneficial for this analysis, but the CPU usage number shown in the output is a lot lower than what you'd expect to see in a CPU usage monitor:

```
(ps -L -C java -o pid,tid,pcpu,time,comm | tail -n+2 | sort -k3 | while read pid tid pcpu time threadname; do echo $pid $tid 0x$(printf %x $tid) $pcpu $time $threadname; printf %x $tid > /tmp/lasttid.$$; echo $pid > /tmp/javapid.$$; done; sudo jstack $(cat /tmp/javapid) | tee jstack.log | grep nid=0x$(cat /tmp/lasttid) -A10)  | tee process-report.txt
```

**Comment by guss77** [comment]
BTW - the Netty workaround of rebuilding the selector never triggers, even when the threshold is set very low. I expect to see warnings in the logs such as "Selector.select() returned prematurely" (https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/nio/NioEventLoop.java#L851) but I see none of that.

**Comment by franz1981** [comment]
Not sure, but it could be related to https://github.com/netty/netty/issues/9112

**Comment by guss77** [comment]
@franz1981 I'm not sure I understand correctly the situation in issue #9112, but it seems to me that the issue there is that the event loop doesn't spend enough time in `EPoll.wait()` (it wakes up too often), where is my issue that it spends way too much time in `EPoll.wait()`

[Here is a snapshot of visualvm showing my app with all the high CPU threads](https://imgur.com/CGQOY2c) are spinning on select and friends. Granted most of the action is in the multiple Hazelcast threads, which are also configured with theor version of the "epoll wait bug workaround", but the Netty event loops (under the Vert.x threads) are no slouches either.

**Comment by franz1981** [comment]
@guss77 
Have you tried with https://github.com/jvm-profiling-tools/async-profiler using `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints`?
It would give you a more realistic view of where time is spent then VisualVM

**Comment by guss77** [comment]
@franz1981 Here is the output of the async profiler running 5 minutes on a machine a bit early in its load cycle, with top showing about 25% CPU spent on the Java service with load average at about 0.6 for the 2 core system.

[service load profiling report.txt](https://github.com/netty/netty/files/3152772/service.load.profiling.report.txt)

According to the profiler, about 6% of CPU time is spent on selecting (sum of all samples with `io.netty.channel.nio.NioEventLoop.select` somewhere in their stack). I'm not really sure I understand what the async-profiler measures, but 6% it still quite a lot, IMHO.

The profiling also shows that the G1 garbage collector is responsible for ~20% of CPU time, and netty internal queue handling is responsible for an additional ~12%. Again, mostly idling server (the most busy client is the ~10 calls/minute load balancer health check), so I would expect to see most of the load produced by the running infrastructure, but 25% load on an idle server is ridiculous.

I'd appreciate if you can offer insights into the profiler output.

**Comment by franz1981** [comment]
@guss77 
Sorry, I haven't mentioned to use the flamegraph visualization instead, with many threads/long running calls I think that make much easier to spot weird behaviours.
If posssible, try 
```$ profiler.sh -d 10 -e cpu -t -f  /tmp/select.svg <pid of your application>```
The `-t` arg allow to collect traces per-thread, while if you omit it, the per-thread traces will be merged (making easier to answer the question "how much select is costing me in *total*?).

P.S. 
Remember to add `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` to your JVM args.

**Comment by guss77** [comment]
@franz1981, sorry it took to long to get back to you: I had to implement some automatic logic to get a capture from a live server, then wait for it to misbehave. And possibly all the required switches make the server behave better? Anyway, please see attached flame graph
[flame.svg.gz](https://github.com/netty/netty/files/3179219/flame.svg.gz)

**Comment by franz1981** [comment]
@guss77 Looking at the flames it seems to me that is selectNow your most expensive NioEventLoop call:
![image](https://user-images.githubusercontent.com/13125299/58072909-738bbe80-7ba1-11e9-9ce8-0330b0161fee.png)

And, looking to the code, NioEventLoop::select will call selectNow only if a specific deadline has been hit or if there are tasks to be executed: I'm not sure in which case you've fallen, but it looks to me you have some task to be executed or some periodic scheduled task.
![image](https://user-images.githubusercontent.com/13125299/58074083-94094800-7ba4-11e9-8632-ff5110b6f83c.png)
Would be great if you could provide which one of the 2 selectNow calls are being called and it will make evident where the issue is :+1:

**Comment by guss77** [comment]
@franz1981 - I'm not sure how to do that. 

There are a few scheduled tasks in the system (a handful - around 6 different types), which are mostly  daily schedules using `EventLoop.scheduleAtFixedRate()`, and a couple of timers that are set up in as part of some type of requests processing and are very short lived one-off timers.

So I doubt there's a lot of calls in the `hasTasks()` branch. But how can I check?

**Comment by franz1981** [comment]
@guss77 
I would run `jstack -F` with `-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints` to check which line of code is being hit but the issue.

The scheluded tasks are being handled while computing `selectDeadLineNanos`, not on `hasTasks` (although it seems more natural), so *maybe* we would find that they are the reason of this weird behaviour.
I've run both Epoll and NIO idle event loops for ~1 day with 3 different Linux distributions (CentOS, RHEL and Fedora) without being able to reproduce it...

**Comment by guss77** [comment]
@franz1981, thanks, I'll try that the next time I catch a server misbehaves.

Regarding reproduction: the problem, and the weird thing - as I've noted a while above - I have several different applications with almost identical stacks (web services with different APIs on top of Vert.x+Netty+Corretto JVM+Ubuntu 18.04) and only this one service is misbehaving.

**Comment by grinbvi** [comment]
"it is quite normal that epollWait(...) blocks... It will only unblock if the Selector is waken up or there is something to handle. So I think it is all good." Here is the  result of epollWait() blocking:
![image](https://user-images.githubusercontent.com/57609916/73020947-3ccf0d80-3dec-11ea-980b-515c7206e3d3.png)
The above data is from the New Relic Thread Profiler taken every 100 milliseconds during the test when the number of users was increasing. epollWait is a bottleneck.
