### ISSUE TITLE
NioEventLoop takes too long to shut dowm

### ISSUE THREAD

**Issue by vkorenev** [netty/netty#2545]
Netty version: 4.0.19.Final

NioEventLoop.shutdownGracefully(long quietPeriod, long timeout, TimeUnit unit) takes more than 1 second to shut down even if the specified quietPeriod is very short.

This is a big problem in a project with lots of unit tests.

NioEventLoop thread is blocked in selector.select(timeoutMillis) call at NioEventLoop.java:618

A simple test:

``` java
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.ChannelInboundHandlerAdapter;
import io.netty.channel.ChannelInitializer;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import org.junit.Test;

import static java.util.concurrent.TimeUnit.MILLISECONDS;
import static org.junit.Assert.assertTrue;

public class NettyNioTest {
  @Test
  public void testShutdown() throws Exception {
    EventLoopGroup serverEventLoopGroup = new NioEventLoopGroup();
    ServerBootstrap serverBootstrap = new ServerBootstrap();
    serverBootstrap.group(serverEventLoopGroup)
            .channel(NioServerSocketChannel.class)
            .childHandler(new ChannelInitializer<SocketChannel>() {
              @Override
              public void initChannel(SocketChannel ch) throws Exception {
                ch.pipeline().addLast(new ChannelInboundHandlerAdapter());
              }
            });

    serverBootstrap.bind(0).sync();

    final long t0 = System.currentTimeMillis();
    serverEventLoopGroup.shutdownGracefully(50, 5000, MILLISECONDS).sync();
    final long t = System.currentTimeMillis() - t0;
    assertTrue("Shutdown took " + t + " ms", t < 200);
  }
}
```

$ java -version
java version "1.7.0_60"
Java(TM) SE Runtime Environment (build 1.7.0_60-b19)
Java HotSpot(TM) 64-Bit Server VM (build 24.60-b09, mixed mode)

Operating system: Ubuntu Linux 14.04 64-bit

$ uname -a
Linux quark 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by julienledem** [comment]
Any workaround to this?

**Comment by julienledem** [comment]
I think I've found a workaround:
```
eventLoopGroup.submit(new Callable<Future<?>>() {
        @Override
        public Future<?> call() {
          return eventLoopGroup.shutdownGracefully();
        }
      }).get();
```
I've noticed a bunch of ```if inEventLoop()``` so I tried that ;)

**Comment by julienledem** [comment]
@normanmaurer @trustin Do you have an idea what's happening? This is making the Drill test suite quite slow has it takes 1 sec every time we close one of those.

**Comment by jroper** [comment]
I've noticed this a few times, both on Linux and OSX, it can have a massive impact on the performance of tests, where it's not uncommon to start an event loop group and shut it down for each test.  The work around is to simply not wait for the event loop to shutdown, but it just seems very unreasonable that this should take longer than a second, and not waiting for shutdown is not very hygienic, especially if you want to gracefully capture and handle errors on shutdown.  I put together this micro benchmark to illustrate how bad the problem is:

```java
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.util.concurrent.Future;

import java.util.concurrent.CountDownLatch;

public class Test {
    public static void main(String... args) throws Exception {
        // Warmup
        test(10, true);

        int dontAwaitTimes = 1000;
        int awaitTimes = 10;

        // Test not awaiting
        long dontAwaitStartTime = System.currentTimeMillis();
        test(dontAwaitTimes, false);
        long dontAwaitTime = System.currentTimeMillis() - dontAwaitStartTime;
        System.out.println("Without awaiting: " + dontAwaitTime + "ms, " + (dontAwaitTime / dontAwaitTimes) + "ms per event loop shutdown");

        // Test awaiting
        long awaitStartTime = System.currentTimeMillis();
        test(awaitTimes, true);
        long awaitTime = System.currentTimeMillis() - awaitStartTime;
        System.out.println("Awaiting: " + awaitTime + "ms, " + (awaitTime / awaitTimes) + "ms per event loop shutdown");
    }

    public static void test(int times, boolean awaitShutdown) throws Exception {
        for (int i = 0; i < times; i++) {
            NioEventLoopGroup group = new NioEventLoopGroup();
            // Make the group do some work to ensure it's actually started
            CountDownLatch latch = new CountDownLatch(1);
            group.execute(latch::countDown);
            latch.await();
            // Shutdown
            Future<?> shutdown = group.shutdownGracefully();
            if (awaitShutdown) {
                shutdown.await();
            }
        }
    }
}
```

The output:

```
Without awaiting: 4855ms, 4ms per event loop shutdown
Awaiting: 22037ms, 2203ms per event loop shutdown
```

So, if you don't await for the graceful shutdown to finish, you can start/stop 1000 event loops in just under 5 seconds.  However, starting/stopping only 10 event loops, when you're waiting for graceful shutdown to finish between each iteration, is taking over 2 seconds per event loop group.

Taking a few thread dumps while running the above shows that the event loop threads are all still hanging around while the we're waiting for the graceful shutdown to finish.

**Comment by jroper** [comment]
Ok, I just read the javadocs for `shutdownGracefully(int, int, TimeUnit)`, and the reason for the long shutdown in my benchmark makes complete sense. I changed my code above to do a shutdown with zero quiet period, and the difference between waiting and not waiting is in the microseconds, which is what you would expect.

**Comment by julienledem** [comment]
@jroper In Drill we're using ```shutdownGracefully(0, 0, TimeUnit.SECONDS)``` and still see a 1 second wait time for the shutdown to complete.
See code there: 
https://github.com/apache/drill/blob/7a151d691979acb12f1d9b5fac54f1179a4b095b/exec/rpc/src/main/java/org/apache/drill/exec/rpc/BasicServer.java#L223
It sounds like this is not the case for you, are you doing anything different?

**Comment by jroper** [comment]
At the moment I'm just doing `shutdownGracefully(0, 10, TimeUnit.SECONDS)` in my code, and my tests are taking same amount of time to run whether I wait for the returned future or not.  I haven't looked into it any further than that.

**Comment by julienledem** [comment]
For me there is no difference between ```shutdownGracefully(0, 0, TimeUnit.SECONDS)``` and ```shutdownGracefully(0, 10, TimeUnit.SECONDS)```. The Future takes 1s to return.

**Comment by vietj** [comment]
@julienledem where you using a `Bootstrap` with a `DnsAddressResolverGroup`

**Comment by normanmaurer** [comment]
I think I fixed this one some time ago. Please re-test and reopen if still an issue

**Comment by orangy** [comment]
I have the same issue, but with 4.1.9.Final
I've noticed something weird with `SslHandler`, in `channelInactive` it calls `notifyClosePromise` which calls `fireUserEventTriggered` and thus schedules new task in the queue, which prevents graceful shutdown to exit immediately, it sleeps for 100ms and then waits some time on select before actually exiting.

**Comment by Scottmitch** [comment]
@orangy - Can you clarify where (starting in `notifyClosePromise`) the `Runnable` is queued on the `EventLoop`? If we are on the event loop (which I would expect we should be when being notified of `channelInactive`) then I wouldn't expect anything to be queued.

**Comment by orangy** [comment]
I've caused it to terminate unsafely and then got a `RejectedExecutionException` to get the exact stack trace. Is it what you are looking for?
```
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:821)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:327)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:320)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:746)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:317)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireUserEventTriggered(CombinedChannelDuplexHandler.java:432)
	at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
	at io.netty.handler.codec.ByteToMessageDecoder.userEventTriggered(ByteToMessageDecoder.java:336)
	at io.netty.handler.codec.http.HttpObjectDecoder.userEventTriggered(HttpObjectDecoder.java:460)
	at io.netty.channel.CombinedChannelDuplexHandler.userEventTriggered(CombinedChannelDuplexHandler.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
	at io.netty.handler.ssl.SslHandler.notifyClosePromise(SslHandler.java:1399)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:861)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Scottmitch** [comment]
@orangy - Would you mind opening another issue? Can you provide this stack trace and also explain how your are initializing the pipeline. It looks like the even loop is processing the channel inactive and then one of your channel handlers has specified a different executor to execute on.
