### ISSUE TITLE
TrafficShapingHandlerTest failure (on CI server for seemingly unrelated PR)

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#2859]
This seems like a threshold detection test and has been observed to intermittently fail.  CI server link to build: https://secure.motd.kr/jenkins/job/pr_2858_akamai_netty_http2_cipher_list/1/.  The PR was branched off of master (c40b0d2)

**Error Message**
>Error during exceution of TrafficShapping: java.lang.AssertionError: The interval of time is incorrect:12 not> 100

**Stacktrace**
>java.lang.AssertionError: Error during exceution of TrafficShapping: java.lang.AssertionError: The interval of time is incorrect:12 not> 100
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at io.netty.testsuite.transport.socket.TrafficShapingHandlerTest.testTrafficShapping0(TrafficShapingHandlerTest.java:352)
	at io.netty.testsuite.transport.socket.TrafficShapingHandlerTest.testWriteTrafficShapping(TrafficShapingHandlerTest.java:163)

**Standard Output**
>13:00:59.943 [Thread-6] INFO  i.n.t.t.s.TrafficShapingHandlerTest - Running: testWriteTrafficShapping 1 of 3 (ServerBootstrap(group: NioEventLoopGroup, channelFactory: NioServerSocketChannel.class, localAddress: /127.0.0.1:39230, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: NioEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}) + Bootstrap(group: NioEventLoopGroup, channelFactory: NioSocketChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, remoteAddress: /127.0.0.1:39230)) with UnpooledByteBufAllocator
13:00:59.943 [Thread-6] INFO  i.n.t.t.s.TrafficShapingHandlerTest - TEST: TEST WRITE RUN: 1 Exec: false Read: false Write: true Global: false
13:01:00.014 [testsuite-nio-worker-3-1] INFO  ServerTSH - Step: 0 Read: 1 blocks
13:01:00.025 [testsuite-nio-worker-3-2] INFO  ClientTSH - Step: 0 Interval: 71 compareTo 10 (0)
13:01:00.115 [testsuite-nio-worker-3-1] INFO  ServerTSH - Step: 1 Read: 1 blocks
13:01:00.195 [testsuite-nio-worker-3-1] INFO  ServerTSH - Step: 1 Read: 1 blocks
13:01:00.205 [testsuite-nio-worker-3-2] INFO  ClientTSH - Step: 1 Interval: 181 compareTo 100 (0)
13:01:00.276 [testsuite-nio-worker-3-1] INFO  ServerTSH - Step: 2 Read: 1 blocks
13:01:00.286 [testsuite-nio-worker-3-2] INFO  ClientTSH - Step: 2 Interval: 81 compareTo 10 (0)
13:01:00.367 [testsuite-nio-worker-3-1] INFO  ServerTSH - Step: 3 Read: 1 blocks
13:01:00.377 [testsuite-nio-worker-3-2] INFO  ClientTSH - Step: 3 Interval: 91 compareTo 10 (0)
13:01:00.377 [Thread-6] INFO  i.n.t.t.s.TrafficShapingHandlerTest - TEST: TEST WRITE RUN: 1 Average of traffic: 9.437788 compare to 12
13:01:00.378 [Thread-6] INFO  i.n.t.t.s.TrafficShapingHandlerTest - Running: testWriteTrafficShapping 2 of 3 (ServerBootstrap(group: NioEventLoopGroup, channelFactory: NioServerSocketChannel.class, localAddress: /127.0.0.1:37249, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: NioEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}) + Bootstrap(group: OioEventLoopGroup, channelFactory: OioSocketChannel.class, options: {SO_TIMEOUT=10, ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, remoteAddress: /127.0.0.1:37249)) with UnpooledByteBufAllocator
13:01:00.378 [Thread-6] INFO  i.n.t.t.s.TrafficShapingHandlerTest - TEST: TEST WRITE RUN: 2 Exec: false Read: false Write: true Global: false
13:01:00.461 [testsuite-nio-worker-3-0] INFO  ServerTSH - Step: 0 Read: 1 blocks
13:01:00.472 [testsuite-oio-worker-3-1] INFO  ClientTSH - Step: 0 Interval: 83 compareTo 10 (0)
13:01:00.554 [testsuite-nio-worker-3-0] INFO  ServerTSH - Step: 1 Read: 1 blocks
13:01:00.636 [testsuite-nio-worker-3-0] INFO  ServerTSH - Step: 1 Read: 1 blocks
13:01:00.646 [testsuite-oio-worker-3-1] INFO  ClientTSH - Step: 1 Interval: 175 compareTo 100 (0)
13:01:00.728 [testsuite-nio-worker-3-0] INFO  ServerTSH - Step: 2 Read: 1 blocks
13:01:00.738 [testsuite-oio-worker-3-1] INFO  ClientTSH - Step: 2 Interval: 92 compareTo 10 (0)
13:01:00.821 [testsuite-nio-worker-3-0] INFO  ServerTSH - Step: 3 Read: 1 blocks
13:01:00.831 [testsuite-oio-worker-3-1] INFO  ClientTSH - Step: 3 Interval: 93 compareTo 10 (0)
13:01:00.831 [Thread-6] INFO  i.n.t.t.s.TrafficShapingHandlerTest - TEST: TEST WRITE RUN: 2 Average of traffic: 9.061947 compare to 12
13:01:00.832 [Thread-6] INFO  i.n.t.t.s.TrafficShapingHandlerTest - Running: testWriteTrafficShapping 3 of 3 (ServerBootstrap(group: OioEventLoopGroup, channelFactory: OioServerSocketChannel.class, localAddress: /127.0.0.1:41043, options: {SO_TIMEOUT=10, ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: OioEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}) + Bootstrap(group: NioEventLoopGroup, channelFactory: NioSocketChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, remoteAddress: /127.0.0.1:41043)) with UnpooledByteBufAllocator
13:01:00.832 [Thread-6] INFO  i.n.t.t.s.TrafficShapingHandlerTest - TEST: TEST WRITE RUN: 3 Exec: false Read: false Write: true Global: false
13:01:01.335 [testsuite-oio-worker-3-1] INFO  ServerTSH - Step: 0 Read: 1 blocks
13:01:01.346 [testsuite-nio-worker-3-2] INFO  ClientTSH - Step: 0 Interval: 503 compareTo 10 (0)
13:01:01.347 [testsuite-oio-worker-3-1] INFO  ServerTSH - Step: 1 Read: 2 blocks
13:01:01.357 [testsuite-nio-worker-3-2] INFO  ClientTSH - Step: 1 Interval: 12 compareTo 100 (0)

**Standard Error**
>java.lang.AssertionError: The interval of time is incorrect:12 not> 100
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at io.netty.testsuite.transport.socket.TrafficShapingHandlerTest$ClientHandler.messageReceived(TrafficShapingHandlerTest.java:439)
	at io.netty.testsuite.transport.socket.TrafficShapingHandlerTest$ClientHandler.messageReceived(TrafficShapingHandlerTest.java:394)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:390)
	at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:356)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:390)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:896)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:122)
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)

**Comment by Scottmitch** [comment]
Haven't observed this in a while ... closing.
