### ISSUE TITLE
ProxyHandlerTest unit test failures

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3082]
I am seeing a build failure in the `:netty-handler-proxy` component.

```bash
Tests run: 30, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 9.4 sec <<< FAILURE! - in io.netty.handler.proxy.ProxyHandlerTest
test[3: Single-chain: successful connection](io.netty.handler.proxy.ProxyHandlerTest)  Time elapsed: 0.035 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at io.netty.handler.proxy.ProxyHandlerTest$TestItem.assertProxyHandlers(ProxyHandlerTest.java:493)
	at io.netty.handler.proxy.ProxyHandlerTest$SuccessTestItem.test(ProxyHandlerTest.java:549)
	at io.netty.handler.proxy.ProxyHandlerTest.test(ProxyHandlerTest.java:350)

test[6: Double-chain: successful connection](io.netty.handler.proxy.ProxyHandlerTest)  Time elapsed: 0.136 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at io.netty.handler.proxy.ProxyHandlerTest$TestItem.assertProxyHandlers(ProxyHandlerTest.java:493)
	at io.netty.handler.proxy.ProxyHandlerTest$SuccessTestItem.test(ProxyHandlerTest.java:549)
	at io.netty.handler.proxy.ProxyHandlerTest.test(ProxyHandlerTest.java:350)


Results :

Failed tests: 
  ProxyHandlerTest.test:350 
Expected: is <true>
     but: was <false>
  ProxyHandlerTest.test:350 
Expected: is <true>
     but: was <false>

Tests run: 30, Failures: 2, Errors: 0, Skipped: 0
```

**Comment by Scottmitch** [comment]
Haven't observed this in a while ... closing for now
