### ISSUE TITLE
After channel has been closed by server, client hangs on channel.isOpen()

### ISSUE THREAD

**Issue by DmitryLobachov** [netty/netty#3097]
Reopen of https://github.com/netty/netty/issues/2946

You asked about thread dump, so here it is:
```java
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	  at java.util.concurrent.Semaphore.acquire(Semaphore.java:312)
	  at fw.NettyTest.netty(NettyTest.java:175)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:483)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	  at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	  at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	  at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)

"nioEventLoopGroup-3-1@2056" prio=10 tid=0xf nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.EPollArrayWrapper.epollWait(EPollArrayWrapper.java:-1)
	  at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	  at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	  - locked <0x832> (a sun.nio.ch.EPollSelectorImpl)
	  - locked <0x833> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x834> (a io.netty.channel.nio.SelectedSelectionKeySet)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	  at java.lang.Thread.run(Thread.java:745)

"nioEventLoopGroup-4-1@2046" prio=10 tid=0x18 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.EPollArrayWrapper.epollWait(EPollArrayWrapper.java:-1)
	  at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	  at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	  - locked <0x835> (a sun.nio.ch.EPollSelectorImpl)
	  - locked <0x836> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x837> (a io.netty.channel.nio.SelectedSelectionKeySet)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	  at java.lang.Thread.run(Thread.java:745)

"nioEventLoopGroup-2-1@1915" prio=10 tid=0xe nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.EPollArrayWrapper.epollWait(EPollArrayWrapper.java:-1)
	  at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	  at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	  - locked <0x838> (a sun.nio.ch.EPollSelectorImpl)
	  - locked <0x839> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x83a> (a io.netty.channel.nio.SelectedSelectionKeySet)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	  at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	  at java.lang.Thread.run(Thread.java:745)

"process reaper@1592" daemon prio=10 tid=0xd nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.misc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	  at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	  at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	  at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at java.lang.Thread.run(Thread.java:745)

"Thread-0@686" prio=5 tid=0xc nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:255)
	  at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129)
	  at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28)
	  at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:219)
	  at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:117)
	  at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:28)
	  at fw.NettyTest$EchoServer.run(NettyTest.java:73)

"Finalizer@2095" daemon prio=8 tid=0x3 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:142)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:158)
	  at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler@2096" daemon prio=10 tid=0x2 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)

"Signal Dispatcher@2094" daemon prio=9 tid=0x4 nid=NA runnable
  java.lang.Thread.State: RUNNABLE

```

**Comment by normanmaurer** [comment]
It hangs on the sync on a DefaultChannelPromise. This looks more like an user error than a bug.
