### ISSUE TITLE
EpollSocketGatheringWriteTest Intermittent Test Failure 

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3138]
``` bash
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 33.09 sec <<< FAILURE! - in io.netty.channel.epoll.EpollSocketGatheringWriteTest
testGatheringWriteBig(io.netty.channel.epoll.EpollSocketGatheringWriteTest)  Time elapsed: 30.014 sec  <<< ERROR!
java.lang.Exception: test timed out after 30000 milliseconds
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:503)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:254)
    at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129)
    at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28)
    at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:218)
    at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:117)
    at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:28)
    at io.netty.testsuite.transport.socket.SocketGatheringWriteTest.testGatheringWrite0(SocketGatheringWriteTest.java:119)
    at io.netty.testsuite.transport.socket.SocketGatheringWriteTest.testGatheringWriteBig(SocketGatheringWriteTest.java:88)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at io.netty.testsuite.transport.AbstractComboTestsuiteTest.run(AbstractComboTestsuiteTest.java:67)
    at io.netty.testsuite.transport.socket.SocketGatheringWriteTest.testGatheringWriteBig(SocketGatheringWriteTest.java:82)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:74)
```

**Comment by Scottmitch** [comment]
I will close this ... haven't observed this in a while.

**Comment by Scottmitch** [comment]
Observed while building https://github.com/netty/netty/pull/7041 built on CI https://garage.netty.io/teamcity/viewLog.html?buildId=22852&buildTypeId=pulls_netty&guest=1 (centos6-1)

```
[io.netty:netty-transport-native-epoll] 22:53:53.827 [Time-limited test] INFO  io.netty.testsuite.util.TestUtils - Dumping heap: EpollDomainSocketGatheringWriteTest.225353.827.hprof
[22:53:54][io.netty:netty-transport-native-epoll] 22:53:54.435 [Time-limited test] INFO  io.netty.testsuite.util.TestUtils - Dumping threads: EpollDomainSocketGatheringWriteTest.225353.827.threads
[22:53:54][io.netty:netty-transport-native-epoll] 22:53:54.520 [Time-limited test] INFO  i.n.c.e.EpollDomainSocketGatheringWriteTest - Running: testGatheringWriteWithComposite 1 of 1 (ServerBootstrap(ServerBootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollServerDomainSocketChannel.class, localAddress: /tmp/NETTY3159501846500165932UDS, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)})) + Bootstrap(BootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollDomainSocketChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@6aa37519))) with UnpooledByteBufAllocator
[22:53:55][io.netty:netty-transport-native-epoll] 22:53:55.679 [Time-limited test] INFO  i.n.c.e.EpollDomainSocketGatheringWriteTest - Running: testGatheringWriteWithComposite 1 of 1 (ServerBootstrap(ServerBootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollServerDomainSocketChannel.class, localAddress: /tmp/NETTY2558609176679417580UDS, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)})) + Bootstrap(BootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollDomainSocketChannel.class, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@6aa37519))) with PooledByteBufAllocator
[22:53:55][io.netty:netty-transport-native-epoll] 22:53:55.898 [Time-limited test] INFO  i.n.c.e.EpollDomainSocketGatheringWriteTest - Running: testGatheringWriteNotAutoRead 1 of 1 (ServerBootstrap(ServerBootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollServerDomainSocketChannel.class, localAddress: /tmp/NETTY5145158878927879447UDS, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)})) + Bootstrap(BootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollDomainSocketChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@6aa37519))) with UnpooledByteBufAllocator
[22:53:56][io.netty:netty-transport-native-epoll] 22:53:56.447 [Time-limited test] INFO  i.n.c.e.EpollDomainSocketGatheringWriteTest - Running: testGatheringWriteNotAutoRead 1 of 1 (ServerBootstrap(ServerBootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollServerDomainSocketChannel.class, localAddress: /tmp/NETTY214157586182004370UDS, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)})) + Bootstrap(BootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollDomainSocketChannel.class, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@6aa37519))) with PooledByteBufAllocator
[22:53:57][io.netty:netty-transport-native-epoll] 22:53:56.996 [Time-limited test] INFO  i.n.c.e.EpollDomainSocketGatheringWriteTest - Running: testGatheringWrite 1 of 1 (ServerBootstrap(ServerBootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollServerDomainSocketChannel.class, localAddress: /tmp/NETTY8754826688301134784UDS, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)})) + Bootstrap(BootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollDomainSocketChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@6aa37519))) with UnpooledByteBufAllocator
[22:53:57][io.netty:netty-transport-native-epoll] 22:53:57.094 [Time-limited test] INFO  i.n.c.e.EpollDomainSocketGatheringWriteTest - Running: testGatheringWrite 1 of 1 (ServerBootstrap(ServerBootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollServerDomainSocketChannel.class, localAddress: /tmp/NETTY7481055296495828487UDS, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)})) + Bootstrap(BootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollDomainSocketChannel.class, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@6aa37519))) with PooledByteBufAllocator
[22:53:57][io.netty:netty-transport-native-epoll] 22:53:57.544 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz
[22:54:02][io.netty:netty-transport-native-epoll] 22:54:02.620 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (1%)
[22:54:07][io.netty:netty-transport-native-epoll] 22:54:07.682 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (3%)
[22:54:12][io.netty:netty-transport-native-epoll] 22:54:12.788 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (5%)
[22:54:17][io.netty:netty-transport-native-epoll] 22:54:17.815 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (8%)
[22:54:22][io.netty:netty-transport-native-epoll] 22:54:22.828 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (12%)
[22:54:27][io.netty:netty-transport-native-epoll] 22:54:27.866 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (16%)
[22:54:32][io.netty:netty-transport-native-epoll] 22:54:32.965 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (20%)
[22:54:38][io.netty:netty-transport-native-epoll] 22:54:38.024 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (23%)
[22:54:43][io.netty:netty-transport-native-epoll] 22:54:43.139 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (25%)
[22:54:48][io.netty:netty-transport-native-epoll] 22:54:48.169 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (27%)
[22:54:53][io.netty:netty-transport-native-epoll] 22:54:53.230 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (32%)
[22:54:58][io.netty:netty-transport-native-epoll] 22:54:58.241 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (36%)
[22:55:03][io.netty:netty-transport-native-epoll] 22:55:03.283 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (39%)
[22:55:08][io.netty:netty-transport-native-epoll] 22:55:08.303 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (43%)
[22:55:13][io.netty:netty-transport-native-epoll] 22:55:13.381 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (47%)
[22:55:18][io.netty:netty-transport-native-epoll] 22:55:18.408 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (51%)
[22:55:23][io.netty:netty-transport-native-epoll] 22:55:23.430 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (56%)
[22:55:28][io.netty:netty-transport-native-epoll] 22:55:28.507 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (59%)
[22:55:33][io.netty:netty-transport-native-epoll] 22:55:33.511 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (62%)
[22:55:38][io.netty:netty-transport-native-epoll] 22:55:38.540 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (68%)
[22:55:43][io.netty:netty-transport-native-epoll] 22:55:43.598 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (72%)
[22:55:48][io.netty:netty-transport-native-epoll] 22:55:48.622 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (75%)
[22:55:53][io.netty:netty-transport-native-epoll] 22:55:53.639 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (79%)
[22:55:58][io.netty:netty-transport-native-epoll] 22:55:58.656 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (83%)
[22:56:03][io.netty:netty-transport-native-epoll] 22:56:03.685 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (87%)
[22:56:08][io.netty:netty-transport-native-epoll] 22:56:08.709 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (91%)
[22:56:13][io.netty:netty-transport-native-epoll] 22:56:13.758 [main] INFO  io.netty.testsuite.util.TestUtils - Compressing the heap dump: /var/lib/teamcity-agent/work/a00bdf77e621d005/transport-native-epoll/EpollDomainSocketGatheringWriteTest.225353.827.hprof.xz (94%)
[22:56:17][io.netty:netty-transport-native-epoll] Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 178.464 sec <<< FAILURE! - in io.netty.channel.epoll.EpollDomainSocketGatheringWriteTest
[22:56:17][io.netty:netty-transport-native-epoll] testGatheringWriteBig(io.netty.channel.epoll.EpollDomainSocketGatheringWriteTest)  Time elapsed: 35.043 sec  <<< FAILURE!
[22:56:17][io.netty:netty-transport-native-epoll] java.lang.AssertionError
[22:56:17][io.netty:netty-transport-native-epoll] 
[22:56:17][io.netty:netty-transport-native-epoll] Running io.netty.channel.epoll.EpollDomainSocketObjectEchoTest
[22:56:17][io.netty:netty-transport-native-epoll] 22:56:17.661 [main] INFO  i.n.c.e.EpollDomainSocketObjectEchoTest - Running: testObjectEchoNotAutoRead 1 of 1 (ServerBootstrap(ServerBootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollServerDomainSocketChannel.class, localAddress: /tmp/NETTY3270455589005972319UDS, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)})) + Bootstrap(BootstrapConfig(group: EpollEventLoopGroup, channelFactory: EpollDomainSocketChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@6aa37519))) with UnpooledByteBufAllocator
[22:56:17][io.netty:netty-transport-native-epoll] io.netty.channel.epoll.EpollDomainSocketGatheringWriteTest
[22:56:17][io.netty.channel.epoll.EpollDomainSocketGatheringWriteTest] testGatheringWriteBig
[22:56:17][testGatheringWriteBig] java.lang.AssertionError
[22:56:17][testGatheringWriteBig] java.lang.AssertionError
```

**Comment by Scottmitch** [comment]
Possibly related https://github.com/netty/netty/issues/7062

**Comment by normanmaurer** [comment]
Did not see this for a long time... let me close it
