### ISSUE TITLE
HashedWheelTimerTest.testExecutionOnTime() fails on IBM JDK 7

### ISSUE THREAD

**Issue by trustin** [netty/netty#3179]
Error Message

```
Timeout + 100000 delay 799 must be 125 < 650
```

Stacktrace

```
java.lang.AssertionError: Timeout + 100000 delay 799 must be 125 < 650
    at org.junit.Assert.fail(Assert.java:88)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at io.netty.util.HashedWheelTimerTest.testExecutionOnTime(HashedWheelTimerTest.java:151)
```

/cc @normanmaurer

**Comment by normanmaurer** [comment]
Let me close this. Its not clear if this is reproducible or even still exists. We can re-open if its reported again .
