### ISSUE TITLE
Install openssl libraries on CI

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3213]
I observed the following output in the build log:
```
10:26:32.823 [main] WARN  i.n.t.t.socket.SocketStartTlsTest - OpenSSL is unavailable and thus will not be tested.
java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative3948312964485521518.so: /usr/lib/libssl.so.10: version `libssl.so.10' not found (required by /tmp/libnetty-tcnative3948312964485521518.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.7.0-u72-b30]
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965) ~[na:1.7.0-u72-b30]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890) ~[na:1.7.0-u72-b30]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851) ~[na:1.7.0-u72-b30]
	at java.lang.Runtime.load0(Runtime.java:795) ~[na:1.7.0-u72-b30]
	at java.lang.System.load(System.java:1062) ~[na:1.7.0-u72-b30]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193) ~[netty-common-4.0.25.Final-SNAPSHOT.jar:4.0.25.Final-SNAPSHOT]
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:39) ~[netty-handler-4.0.25.Final-SNAPSHOT.jar:4.0.25.Final-SNAPSHOT]
	at io.netty.testsuite.transport.socket.SocketSslEchoTest.data(SocketSslEchoTest.java:94) ~[netty-testsuite-4.0.25.Final-SNAPSHOT-tests.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0-u72-b30]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0-u72-b30]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0-u72-b30]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0-u72-b30]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:na]
	at org.junit.runners.Parameterized.allParameters(Parameterized.java:292) [junit-4.11.jar:na]
	at org.junit.runners.Parameterized.<init>(Parameterized.java:282) [junit-4.11.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.7.0-u72-b30]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) [na:1.7.0-u72-b30]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.7.0-u72-b30]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) [na:1.7.0-u72-b30]
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29) [junit-4.11.jar:na]
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21) [junit-4.11.jar:na]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [junit-4.11.jar:na]
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26) [junit-4.11.jar:na]
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59) [junit-4.11.jar:na]
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26) [junit-4.11.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262) [surefire-junit4-2.15.jar:2.15]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.15.jar:2.15]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124) [surefire-junit4-2.15.jar:2.15]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200) [surefire-booter-2.15.jar:2.15]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) [surefire-booter-2.15.jar:2.15]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.15.jar:2.15]
```

We should install all the needed libraries

**Comment by trustin** [comment]
Fixed with the following build instructions - http://netty.io/wiki/forked-tomcat-native.html#wiki-h4-4
