### ISSUE TITLE
scheduleTaskAtFixedRateB sporadic test failure

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#3231]
This was observed on the CI server in a `leak` build http://clinker.netty.io/jenkins/job/netty-leak/branch/4.1/37/console on the 4.1 branch.

```
05:36:01 Running io.netty.channel.SingleThreadEventLoopTest
05:36:11 Tests run: 15, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.466 sec <<< FAILURE! - in io.netty.channel.SingleThreadEventLoopTest
05:36:11 scheduleTaskAtFixedRateB(io.netty.channel.SingleThreadEventLoopTest)  Time elapsed: 0.573 sec  <<< FAILURE!
05:36:11 java.lang.AssertionError: null
05:36:11 	at org.junit.Assert.fail(Assert.java:86)
05:36:11 	at org.junit.Assert.assertTrue(Assert.java:41)
05:36:11 	at org.junit.Assert.assertTrue(Assert.java:52)
05:36:11 	at io.netty.channel.SingleThreadEventLoopTest.testScheduleTaskAtFixedRate(SingleThreadEventLoopTest.java:187)
05:36:11 	at io.netty.channel.SingleThreadEventLoopTest.scheduleTaskAtFixedRateB(SingleThreadEventLoopTest.java:159)
05:36:11 
05:36:11 Running io.netty.channel.FailedChannelFutureTest
05:36:11 Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in io.netty.channel.FailedChannelFutureTest
05:36:11 Running io.netty.channel.embedded.EmbeddedChannelTest
05:36:11 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.netty.channel.embedded.EmbeddedChannelTest
05:36:12 
05:36:12 Results :
05:36:12 
05:36:12 Failed tests: 
05:36:12   SingleThreadEventLoopTest.scheduleTaskAtFixedRateB:159->testScheduleTaskAtFixedRate:187 null
05:36:12 
05:36:12 Tests run: 98, Failures: 1, Errors: 0, Skipped: 6
```

**Comment by trustin** [comment]
Fixed by 49988a68212939423ae5e98d8b4ff60aeea0e980
