### ISSUE TITLE
DecoderException building Acteur

### ISSUE THREAD

**Issue by timboudreau** [netty/netty#3247]
I'm updating my netty-5 branch of Acteur, and have a test failing with the exception thrown below, which does not contain any code of mine in its stack trace.

Commenting the test `if (oldInputLength == in.readableBytes())` in `ByteToMessageDecoder` fixes the problem.

Are you sure it is _always_ the case that `decode()` _will_ change the position of the `ByteBuf`?

```
testGets(com.mastfrog.acteur.ComprehensiveTest)  Time elapsed: 0.264 sec  <<< ERROR!
io.netty.handler.codec.DecoderException: io.netty.handler.codec.http.HttpRequestDecoder.decode() did not read anything but decoded a message.
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:289)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:169)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
    at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:955)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:122)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by timboudreau** [comment]
I see on migrating to `4.0.25.Final`, that this bug is now present in Netty 4.  Ported the hack from the netty-5 branch of Acteur to the trunk.

**Comment by trustin** [comment]
Would you mind if I ask you to insert a `LoggingHandler` in front of the `HttpRequestDecoder` so that we know what traffic is exactly causing the decoder to panic?

**Comment by timboudreau** [comment]
Okay, clone [acteur](https://github.com/timboudreau/acteur) and check out the branch netty-3247.  When you build it, `ComprehensiveTest` will fail.

Interestingly, if you run the test by itself (not as part of building everything and running all tests), it will pass.  Some sort of race condition or static state inside netty getting shared cross-test?

The only thing logged by the logging handler in this test is
```
/echo - Connecting - null
```

**Comment by timboudreau** [comment]
Another report of this in [the netty google group](https://groups.google.com/forum/#!topic/netty/2yotqLsrUBY)

**Comment by Iker-Jimenez** [comment]
as I said in #3519 , this has been introduced post 4.0.23.Final. Based on @timboudreau comment above, it was either introduced in 4.0.24 or 4.0.25. We noticed it when we upgraded to 4.0.26. We had to rollback to 4.0.23 because of this.

**Comment by ddossot** [comment]
After seeing this issue in one of our Aleph based project (backed by Netty `4.1.0.Beta3`), we realized that our production systems on `4.0.26.Final` suffer from the same problem (~40 occurences per million requests).

**Comment by ddossot** [comment]
We've tested with `4.0.24.Final` and see the issue there too. We're downgrading to `4.0.23.Final`.

**Comment by Iker-Jimenez** [comment]
Hi, we are blocked on 4.0.23.Final and cannot upgrade because of this. Any chance it can be looked at soon enough?

**Comment by timboudreau** [comment]
Looking at the code in question, it seems like (to my uncaffeinated brain at the moment), there are a few potential problems:

 * It assumes there are enough bytes for decode() to decode something (otherwise decoding no bytes and leaving it alone is sane - wouldn't this be the case if you had, say, partial bytes of a chunk incoming?) - is that really true?
 * It assumes nothing else can possibly write to `in` while it is working (see my all-caps comment below).  Is that guaranteed to be true?  All it would take is something writing exactly `oldInputLength` bytes to the buffer while this method is running, but before it tests `in.readableBytes()` again.

There is some clever code here (search on `Cumulation`) that manages the input `ByteBuf`.  All of it seems to assume that another thread can't possibly receive a packet and add it while decoding is happening.  I'm not sure that's true (if making `channelRead()` synchronized [not a great idea] cures it, then that's the problem).

```java
                int oldInputLength = in.readableBytes();
                decode(ctx, in, out);

                // Check if this handler was removed before continuing the loop.
                // If it was removed, it is not safe to continue to operate on the buffer.
                //
                // See https://github.com/netty/netty/issues/1664
                if (ctx.isRemoved()) {
                    break;
                }

                if (outSize == out.size()) {
                    if (oldInputLength == in.readableBytes()) {
                        break;
                    } else {
                        continue;
                    }
                }

               // <----- AND WHAT IF ANOTHER THREAD ADDS oldInputLength BYTES TO THE BUFFER WHILE THIS THREAD IS HERE?

                if (oldInputLength == in.readableBytes()) {
                    throw new DecoderException(
                            StringUtil.simpleClassName(getClass()) +
                            ".decode() did not read anything but decoded a message.");
                }
```

**Comment by Scottmitch** [comment]
`ByteToMessageDecoder` is not thread safe (its main use case is to be invoked from the event loop thread)....but it does expose a few protected methods (`callDecode`  is one of them) which may be a problem if it is invoked from outside the event loop. Are you calling `callDecode()` (or other protected methods) from a non event loop thread @timboudreau @Iker-Jimenez @ddossot?

**Comment by timboudreau** [comment]
Would having more than one thread in the `EventLoopGroup` for events have that result?

**Comment by Scottmitch** [comment]
@timboudreau - Not unless there is a bug in Netty :) For 4.x the same thread should be used to processes I/O events.

**Comment by timboudreau** [comment]
Consider the possibility that there is one :-)

The netty-3247 branch of acteur (link above) offers a 100% reproducible test case.

**Comment by normanmaurer** [comment]
Will check today

**Comment by Scottmitch** [comment]
@timboudreau - I tried to build real quick...had issues with the maven compiler plugin defaulting to 1.7 instead of 1.8 and getting compiler errors.... lets see if @normanmaurer has better luck.

**Comment by timboudreau** [comment]
I think Acteur is all set up to use my Maven repository (there are a bunch of related projects that use git submodules and a remote parent - which is needed to fetch the parent for building one in isolation).  In a pinch:

```sh
git clone git@github.com:timboudreau/mastfrog-parent.git
cd mastfrog-parent
./init
cd acteur-modules/acteur-parent
git checkout netty-3247
mvn clean install
```

The init script will checkout submodules and do the initial build.

Yeah, I have some users who insist on OpenJDK which is still at 1.7 - causes some frustration for me too.

**Comment by normanmaurer** [comment]
Looking at it now.

**Comment by normanmaurer** [comment]
@timboudreau I'm confused.. I used the steps you posted and needed to do some small adjustments to have it build. Anyway I can not reproduce the exception here :(

I guess I will need a bit more help here.
