### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/tomcat/jni/CertificateVerifier

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3293]
Error Message

```
org/apache/tomcat/jni/CertificateVerifier
Stacktrace

java.lang.NoClassDefFoundError: org/apache/tomcat/jni/CertificateVerifier
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at io.netty.handler.ssl.SslContext.newClientContext(SslContext.java:655)
    at io.netty.handler.ssl.SslContext.newClientContext(SslContext.java:601)
    at io.netty.handler.ssl.SslContext.newClientContext(SslContext.java:535)
    at io.netty.handler.ssl.SslContext.newClientContext(SslContext.java:400)
    at io.netty.handler.proxy.ProxyHandlerTest.<clinit>(ProxyHandlerTest.java:92)
```

See also:
 http://clinker.netty.io/jenkins/job/netty-openjdk7/branch/4.1/32/testReport/junit/io.netty.handler.proxy/ProxyHandlerTest/initializationError/

This happens in 4.1 and master.

@trustin any idea as the dependency looks ok to me in pom.xml and the class should exist ?

**Comment by lukehutch** [comment]
I'm seeing this issue again with Netty-5.0.0-Alpha2-SNAPSHOT.

**Comment by lukehutch** [comment]
Ah, I see what's going on. In my case, I was specifically requesting SslContext.newServerContext(SslProvider.OPENSSL, ...).

Since this exception is confusing and doesn't describe the real problem, it would be great if the code could be modified to give an exception:

in SslContext near line 257:

        // Suggestion: add this:
        if (!OpenSsl.isAvailable()) {
            logger.info("OpenSSL provider not available, falling back to JDK SSL provider");
            provider = SslProvider.JDK;
        }
        // ... before this:
        switch (provider) {
        case JDK:
            return new JdkSslServerContext(
                    trustCertChainFile, trustManagerFactory, keyCertChainFile, keyFile, keyPassword,
                    keyManagerFactory, ciphers, cipherFilter, apn, sessionCacheSize, sessionTimeout);
        case OPENSSL:
            return new OpenSslServerContext(
                    keyCertChainFile, keyFile, keyPassword, trustManagerFactory,
                    ciphers, apn, sessionCacheSize, sessionTimeout);
        default:
            throw new Error(provider.toString());
        }

**Comment by lukehutch** [comment]
However, after removing the SslProvider.OPENSSL parameter and adding the netty-tcnative dependency to my project .pom as the following,

		<dependency>
			<groupId>io.netty</groupId>
			<artifactId>netty-tcnative</artifactId>
			<version>1.1.30.Fork2</version>
			<classifier>linux-x86_64</classifier>
		</dependency>

I get this exception on SslContext.newServerContext(ssc.certificate(), ssc.privateKey()) :

[WARN] OpenSsl - Failed to get the list of available OpenSSL cipher suites.
java.lang.Exception: Invalid Server SSL Protocol (error:00000000:lib(0):func(0):reason(0))
	at org.apache.tomcat.jni.SSLContext.make(Native Method)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:60)
	at io.netty.handler.ssl.SslContext.defaultProvider(SslContext.java:99)
	at io.netty.handler.ssl.SslContext.defaultServerProvider(SslContext.java:86)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:254)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:212)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:184)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:128)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:114)
	at gribbit.server.GribbitServer.start(GribbitServer.java:208)
	at msgboard.main.Main.main(Main.java:27)
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/tomcat/jni/CertificateVerifier
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:263)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:212)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:184)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:128)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:114)
	at gribbit.server.GribbitServer.start(GribbitServer.java:208)
	at msgboard.main.Main.main(Main.java:27)
Caused by: java.lang.ClassNotFoundException: org.apache.tomcat.jni.CertificateVerifier
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by normanmaurer** [comment]
You need version 1.1.32.Fork1

**Comment by lukehutch** [comment]
That fixed it, thanks.
