### ISSUE TITLE
io.netty.bootstrap.BootstrapTest.testAsyncResolutionFailure sometimes fails

### ISSUE THREAD

**Issue by trustin** [netty/netty#3297]
Failing for the past 1 build (Since Failed#57 )
Took 10 sec.
Error Message
```
Expected: is <true>
     but: was <false>
```
Stacktrace
```
java.lang.AssertionError: 
Expected: is <true>
     but: was <false>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:865)
	at org.junit.Assert.assertThat(Assert.java:832)
	at io.netty.bootstrap.BootstrapTest.testAsyncResolutionFailure(BootstrapTest.java:254)
```
Standard Output
```
10:42:03.586 [defaultEventLoopGroup-30-0] WARN  i.n.u.c.SingleThreadEventExecutor - Unexpected exception from an event executor: 
java.lang.NullPointerException: remoteAddress
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeConnect(DefaultChannelHandlerInvoker.java:230) ~[classes/:na]
	at io.netty.channel.PausableChannelEventExecutor.invokeConnect(PausableChannelEventExecutor.java:107) ~[classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:422) ~[classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:416) ~[classes/:na]
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:1017) ~[classes/:na]
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:240) ~[classes/:na]
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:230) ~[classes/:na]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:43) ~[classes/:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:122) ~[netty-common-5.0.0.Alpha2-SNAPSHOT.jar:5.0.0.Alpha2-SNAPSHOT]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-common-5.0.0.Alpha2-SNAPSHOT.jar:5.0.0.Alpha2-SNAPSHOT]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-common-5.0.0.Alpha2-SNAPSHOT.jar:5.0.0.Alpha2-SNAPSHOT]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-common-5.0.0.Alpha2-SNAPSHOT.jar:5.0.0.Alpha2-SNAPSHOT]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-common-5.0.0.Alpha2-SNAPSHOT.jar:5.0.0.Alpha2-SNAPSHOT]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-common-5.0.0.Alpha2-SNAPSHOT.jar:5.0.0.Alpha2-SNAPSHOT]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-common-5.0.0.Alpha2-SNAPSHOT.jar:5.0.0.Alpha2-SNAPSHOT]
```

**Comment by normanmaurer** [comment]
@trustin did not see this for a long time now. I think we should close this for now. WDYT ?

**Comment by SerCeMan** [comment]
Same error occured
```
java.lang.NullPointerException: remoteAddress
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeConnect(DefaultChannelHandlerInvoker.java:240)
    at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:216)
    at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:210)
    at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:990)
    at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:237)
    at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:234)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by normanmaurer** [comment]
Can you always reproduce and what version?

**Comment by SerCeMan** [comment]
```
netty-all-4.1.0.Beta8
```
Error isn't reproducible

**Comment by pdwinkel** [comment]
Using 4.1.0-CR7:

```
08:45:31.554 WARN  io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151) [WebSocketClient-group-thread-10] 
                                            A task raised an exception.
java.lang.NullPointerException: remoteAddress
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeConnect(DefaultChannelHandlerInvoker.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:371)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:202)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:1140)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:245)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:234)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
```

Can not reproduce it, but seeing it almost weekly ;-(

**Comment by pdwinkel** [comment]
Well, I can 'reproduce' it by starting my server and wait. The NPE happens normally within 10 minutes after start of server. After 10 minutes restart server and wait again...

The NPE happend the fourth time I started my server.

**Comment by normanmaurer** [comment]
Can you share your server?

**Comment by pdwinkel** [comment]
I just created a test program which give the same NPE:
```
16:32:48.251 [WebSocketClient-vehicle-5:8620-group-thread-0] WARN io.netty.util.concurrent.SingleThreadEventExecutor - A task raised an exception.
java.lang.NullPointerException: remoteAddress
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeConnect(DefaultChannelHandlerInvoker.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:371)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:202)
	at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:1140)
	at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:245)
	at io.netty.bootstrap.Bootstrap$3.run(Bootstrap.java:234)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
```
I'll make a zip file and pm it to you

**Comment by pdwinkel** [comment]
I sent the zip file to your gmail account

**Comment by normanmaurer** [comment]
Will check soon

**Comment by normanmaurer** [comment]
Ok I know what is wrong.... let me work on a fix

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5212
