### ISSUE TITLE
Netty 4.0.25 fails as OSGi bundle

### ISSUE THREAD

**Issue by davsclaus** [netty/netty#3302]
Using Netty 4.0.24 works fine. But when installing the new 4.0.25 version in OSGi such as Apache Karaf, there is an error about an empty version
```
2015-01-02 09:56:00,501 | ERROR | l Console Thread | Console                          | ?                                   ? | 17 - org.apache.karaf.shell.console - 2.4.0 | Exception caught while executing command
org.osgi.framework.BundleException: Could not create bundle object.
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2960)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.karaf.features.internal.FeaturesServiceImpl.installBundleIfNeeded(FeaturesServiceImpl.java:920)[7:org.apache.karaf.features.core:2.4.0]
	at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeature(FeaturesServiceImpl.java:673)[7:org.apache.karaf.features.core:2.4.0]
	at org.apache.karaf.features.internal.FeaturesServiceImpl.doInstallFeatures(FeaturesServiceImpl.java:432)[7:org.apache.karaf.features.core:2.4.0]
	at org.apache.karaf.features.internal.FeaturesServiceImpl$1.call(FeaturesServiceImpl.java:402)[7:org.apache.karaf.features.core:2.4.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)[:1.7.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)[:1.7.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)[:1.7.0_45]
	at java.lang.Thread.run(Thread.java:744)[:1.7.0_45]
Caused by: java.lang.IllegalArgumentException: invalid version "": invalid format
	at org.osgi.framework.Version.<init>(Version.java:147)[karaf.jar:2.4.0]
	at org.apache.felix.framework.util.VersionRange.parse(VersionRange.java:93)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.manifestparser.ManifestParser.normalizeImportClauses(ManifestParser.java:325)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.util.manifestparser.ManifestParser.<init>(ManifestParser.java:180)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.BundleRevisionImpl.<init>(BundleRevisionImpl.java:121)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1243)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:112)[org.apache.felix.framework-4.4.1.jar:]
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2907)[org.apache.felix.framework-4.4.1.jar:]
	... 9 more
Caused by: java.util.NoSuchElementException
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349)[:1.7.0_45]
	at org.osgi.framework.Version.<init>(Version.java:126)[karaf.jar:2.4.0]
	... 16 more
```

**Comment by davsclaus** [comment]
To reproduce then you can download Apache Karaf 2.4.0 and start it with

    bin/karaf

And then from the shell just type

    install mvn:io.netty/netty-common/4.0.24.Final

which works.

    install mvn:io.netty/netty-common/4.0.25.Final

which fails.

```
karaf@root> install mvn:io.netty/netty-common/4.0.24.Final
Bundle ID: 54
karaf@root> install mvn:io.netty/netty-common/4.0.25.Final
Bundle IDs:
Error executing command: Error installing bundles:
	Unable to install bundle mvn:io.netty/netty-common/4.0.25.Final
```

To see the log you can type `log:display`

And to see the bundles installed type `ls`

**Comment by davsclaus** [comment]
I suspect its the addition of the new dependency for eclipse that has an invalid version specification. See the screenshot where we show 4.0.24 vs 4.0.25

![netty-osgi-bug](https://cloud.githubusercontent.com/assets/477100/5595014/ecab3a16-9267-11e4-9a7a-c7e5e38715bb.png)

The version range `version="[1,)"` is likely invalid as the version after the comma is empty. So it could be
`version="[1,2)"` to denote all 1.x versions.

See also: http://stackoverflow.com/questions/8353771/osgi-valid-version-ranges

**Comment by pdwinkel** [comment]
Also the bindex tool fails:

```
[ERROR  ] 2015-01-02 14:15:15: Error calling analyzer "org.osgi.service.indexer.impl.BundleAnalyzer" on resource /home/peter/develop/bundles/netty-common-4.0.25.Final.jar.
java.lang.NumberFormatException: For input string: "[1,)"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at org.osgi.framework.Version.<init>(Version.java:127)
    at org.osgi.service.indexer.impl.types.VersionRange.<init>(VersionRange.java:59)
    at org.osgi.service.indexer.impl.BundleAnalyzer.doImports(BundleAnalyzer.java:299)
    at org.osgi.service.indexer.impl.BundleAnalyzer.analyzeResource(BundleAnalyzer.java:64)
    at org.osgi.service.indexer.impl.RepoIndex.generateResource(RepoIndex.java:266)
    at org.osgi.service.indexer.impl.RepoIndex.index(RepoIndex.java:185)
    at org.osgi.impl.bundle.bindex.cli.Index.main(Index.java:81)
```

See also: https://github.com/bndtools/bnd/issues/760

**Comment by trustin** [comment]
Thanks for reporting, folks.  It should be fixed in c0cda20b1e358f1cb085de90ca0f139f2e56b937

**Comment by trustin** [comment]
Does anybody in this thread know how to validate the OSGi manifest file during the Maven build process? It would be great we don't make this mistake anymore. I could set up a Jenkins job dedicated to this, but it's probably better making the validation the part of the usual build process.

**Comment by davsclaus** [comment]
I am not aware of a simple plugin for that. At Apache Camel we use Apache Karaf maven plugins that validate Karaf features which as part of that, also validate the OSGi bundles. But this requires using karaf feature xml file. Not sure if you can do it without and as plain OSGi.

https://github.com/apache/camel/blob/master/platforms/karaf/features/pom.xml#L176

**Comment by rovarga** [comment]
Would switching to maven-bundle-plugin help? That could auto-generate the manifest, which mostly prevents simple typos, but could end up adding things that are not strictly necessary.

pax-exam can be used to write UTs to check if things resolve as bundles (https://git.opendaylight.org/gerrit/gitweb?p=bgpcep.git;a=blob;f=integration-tests/src/test/java/org/opendaylight/protocol/integration/AbstractBundleTest.java;h=8ebfb2b69db0fadd186ac7a7836a270b66ca9160;hb=HEAD).
