### ISSUE TITLE
SslHandler issue with latest 4.1b4 snapshot

### ISSUE THREAD

**Issue by alkemist** [netty/netty#3324]
With the latest Snapshot I get this making an HTTPS request with a client:

```
Uncaught execution exception io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: index: 6995, length: 5596 (expected: range(0, 8192))
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:834)
	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory.lambda$newThread$90(DefaultExecController.java:82)
	at ratpack.exec.internal.DefaultExecController$ExecControllerBindingThreadFactory$$Lambda$14/1771421544.run(Unknown Source)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: index: 6995, length: 5596 (expected: range(0, 8192))
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1106)
	at io.netty.buffer.PooledHeapByteBuf.internalNioBuffer(PooledHeapByteBuf.java:268)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1104)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:979)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:919)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:323)
	... 15 more
```

Submitted without reproducible case in case you can easily spot the problem and if it's easier for you to reproduce.

**Comment by trustin** [comment]
Thanks for the heads up. Fixed in: 392fb764b6dd4cc05b3dc8f2f3bb53eae689b868

**Comment by normanmaurer** [comment]
@trustin thanks man!

**Comment by alkemist** [comment]
Many thanks for the prompt action.
