### ISSUE TITLE
Failure To Build Netty 4.0.25.Final

### ISSUE THREAD

**Issue by sherman94062** [netty/netty#3332]
This is likely my issue but wanted to check to see.  I'll install a 64-bit Ubuntu image and retry the same thing.  When trying to build the example code, I get a Maven error:
[ERROR] Failed to execute goal on project netty-example: Could not resolve dependencies for project io.netty:netty-example:jar:4.0.25.Final: Failure to find io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
It's possible that I'm running 32-bit Debian and the build for 4.0.25 only supports 64-bit?
Not urgent, just wanted to see if anyone knew a simple way to resolve.

**Comment by sfat** [comment]
@sherman94062 can you try this?  ```mvn -U <YOUR GOALS>```. That error usually occurrs when maven fails to update localy repository:
> ▶ mvn --help
> usage: mvn [options] [<goal(s)>] [<phase(s)>]
> ....
> -U,--update-snapshots                  Forces a check for missing
>                                                       releases and updated snapshots on

**Comment by sherman94062** [comment]
Thanks Andrei, will try that later today.
There is a help page referenced in the error message that I've yet to review.
I've gotten the same result on Fedora and Ubuntu VM's on VirtualBox, so I think it's something having to do with dependencies.
Thx,Mike

**Comment by junjiemars** [comment]
I'd same the problem, my env is 
```
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2015-03-10T15:58:03+08:00)
Maven home: /opt/java/maven/3.2.5
Java version: 1.8.0_25, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk1.8.0_25/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.2.0-69-generic-pae", arch: "i386", family: "unix"
```

I try to compile transport-native-epoll, but got the following output:
```
[ERROR] Failed to execute goal on project netty-transport-native-epoll: Could not resolve dependencies for project io.netty:netty-transport-native-epoll:jar:4.1.0.Beta5-SNAPSHOT: Failure to find io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project netty-transport-native-epoll: Could not resolve dependencies for project io.netty:netty-transport-native-epoll:jar:4.1.0.Beta5-SNAPSHOT: Failure to find io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:220)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.resolveProjectDependencies(LifecycleDependencyResolver.java:127)
	at org.apache.maven.lifecycle.internal.MojoExecutor.ensureDependenciesAreResolved(MojoExecutor.java:257)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:200)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.project.DependencyResolutionException: Could not resolve dependencies for project io.netty:netty-transport-native-epoll:jar:4.1.0.Beta5-SNAPSHOT: Failure to find io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:211)
	at org.apache.maven.lifecycle.internal.LifecycleDependencyResolver.getDependencies(LifecycleDependencyResolver.java:195)
	... 22 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Failure to find io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:384)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
	... 23 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	... 24 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:206)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 26 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by trustin** [comment]
You need to build on 64-bit Linux, because we do not distribute the native library JARs for 32-bit operating systems. Are you sure you want to run Netty on 32-bit OS?

**Comment by junjiemars** [comment]
@trustin Oh, it really bad news, I just want to build/test it on developing box, then deploy it to 64bits box.

**Comment by junjiemars** [comment]
@trustin I resolved io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 can not be found on 32-bit Linux,
1) git clone [netty-tcnative.git](git@github.com:netty/netty-tcnative.git)
2) run ```mvn -X compile```, it will be failed on 32-bit Linux
3) found the Makefile under the ./target/native-build, insert ```-DLARGEFILE64_SOURCE``` into ```CFLAGS``` section nearly 262 line
4) comment 2 <forceAutogen .../> and <forceConfigure .../> sections in pom.xml
5) run ```mvn -X install``` to install io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 into local repository
6) now, io.netty:netty-tcnative:jar:linux-x86_32:1.1.32.Fork1 can be maven found, done.

**Comment by trustin** [comment]
@junjiemars Filed an issue for you: netty/netty-tcnative#29 Let's continue discussion there.

**Comment by normanmaurer** [comment]
Let us close this and just continue in  netty/netty-tcnative#29 as @trustin suggested
