### ISSUE TITLE
ISE: void future when using IdleStateHandler with SSLHandler

### ISSUE THREAD

**Issue by sirmax** [netty/netty#3364]
Netty version: 4.0.25.Final

I encountered `java.lang.IllegalStateException: void future` when using `IdleStateHandler` together with `SSLHandler`.

    java.lang.IllegalStateException: void future
            at io.netty.channel.VoidChannelPromise.fail(VoidChannelPromise.java:178)
            at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:44)
            at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:24)
            at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:259)
            at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
            at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
            at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
            at io.netty.handler.ssl.SslHandler.finishWrap(SslHandler.java:533)
            at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:504)
            at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:454)
            ...

It seems that I've managed to cause `flush()` on `SSLHandler` when it had empty `pendingUnencryptedWrites`. It sent an empty buffer together with `VoidPromise`, which blew up `IdleStateHandler`.

I've already reported in #2618 that `IdleStateHandler` does not "unvoid" the promises. But that issue had turned into an API improvement scheduled for 4.1. @normanmaurer had noted that Netty uses `VoidPromise` only when a client code does, and it was a valid point at the time. However, it has changed later in #2752 [here](https://github.com/netty/netty/blob/7764b0e3/handler/src/main/java/io/netty/handler/ssl/SslHandler.java#L379).

Workaround:
Insert a singleton handler between `SSLHandler` and `IdleStateHandler` that would unvoid the promises.

**Comment by normanmaurer** [comment]
@sirmax fixed... thanks for reporting.
