### ISSUE TITLE
Netty4: "ChunkedInput.isEndOfInput() failed"

### ISSUE THREAD

**Issue by mfulgo** [netty/netty#3368]
Running `4.0.25.Final`, it seems that `ChunkedWriteHandler` is mishandling its input.  From the log below, you can see that first, it is closing its stream (due to a `ClosedChannelException`). Then, in response to the ChannelInactive event, it logs a warning when it attempts to discard the stream because the stream is already closed.

```
DEBUG 20:20:47.870 [nioEventLoopGroup-3-9] java.lang.Thread.getStackTrace(Unknown Source)
	net.pms.io.WaitBufferedInputStream.close(WaitBufferedInputStream.java:78)
	java.io.PushbackInputStream.close(Unknown Source)
	io.netty.handler.stream.ChunkedStream.close(ChunkedStream.java:93)
	io.netty.handler.stream.ChunkedWriteHandler.closeInput(ChunkedWriteHandler.java:325)
	io.netty.handler.stream.ChunkedWriteHandler$3.operationComplete(ChunkedWriteHandler.java:282)
	io.netty.handler.stream.ChunkedWriteHandler$3.operationComplete(ChunkedWriteHandler.java:278)
	io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
	io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
	io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:645)
	io.netty.channel.ChannelOutboundBuffer.remove(ChannelOutboundBuffer.java:290)
	io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:589)
	io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:568)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:71)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:157)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	java.lang.Thread.run(Unknown Source)
TRACE 20:20:47.870 [nioEventLoopGroup-3-9] Ready to Stop: true
TRACE 20:20:47.871 [nioEventLoopGroup-3-9] The channel future completed:
TRACE 20:20:47.871 [nioEventLoopGroup-3-9]   isSuccess: false
TRACE 20:20:47.871 [nioEventLoopGroup-3-9]   isCancelled: false
TRACE 20:20:47.871 [nioEventLoopGroup-3-9]   getCause: 
	java.nio.channels.ClosedChannelException: null
WARN  20:20:47.871 [nioEventLoopGroup-3-9] ChunkedInput.isEndOfInput() failed
java.io.IOException: Stream closed
	at java.io.PushbackInputStream.ensureOpen(Unknown Source) ~[na:1.8.0_31]
	at java.io.PushbackInputStream.read(Unknown Source) ~[na:1.8.0_31]
	at io.netty.handler.stream.ChunkedStream.isEndOfInput(ChunkedStream.java:82) ~[ums.jar:5.0.1]
	at io.netty.handler.stream.ChunkedWriteHandler.discard(ChunkedWriteHandler.java:177) [ums.jar:5.0.1]
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:203) [ums.jar:5.0.1]
	at io.netty.handler.stream.ChunkedWriteHandler.channelInactive(ChunkedWriteHandler.java:147) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194) [ums.jar:5.0.1]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [ums.jar:5.0.1]
	at io.netty.handler.codec.http.HttpObjectAggregator.channelInactive(HttpObjectAggregator.java:236) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194) [ums.jar:5.0.1]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:247) [ums.jar:5.0.1]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:132) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:208) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:194) [ums.jar:5.0.1]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:828) [ums.jar:5.0.1]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:576) [ums.jar:5.0.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [ums.jar:5.0.1]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [ums.jar:5.0.1]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [ums.jar:5.0.1]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [ums.jar:5.0.1]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_31]
```

The relevant [calling code](https://github.com/UniversalMediaServer/UniversalMediaServer/blob/c95fae7954a1c984d3d30602409d0996007ba783/src/main/java/net/pms/network/RequestV2.java#L914) is essentially:
```java
ctx.writeAndFlush(new ChunkedStream(largeInputStream, 8*1024))
```

**Comment by SubJunk** [comment]
@normanmaurer the attempted fix doesn't seem to work; I'm still getting the error with http://clinker.netty.io/nexus/content/repositories/snapshots/io/netty/netty-all/4.0.26.Final-SNAPSHOT/netty-all-4.0.26.Final-20150201.085343-43.jar

**Comment by mfulgo** [comment]
Ah. I see where this went astray... Commit 14390be references this bug instead of #3369, which is what it actually fixes.  @SubJunk, that's why you're still getting the error.

**Comment by SubJunk** [comment]
@mfulgo yeah it looks like it. Really hoping this issue can be fixed before the next release :)

**Comment by trustin** [comment]
You guys are right. It's not fixed yet. We love contributions by the way. :-)

**Comment by mfulgo** [comment]
@trustin I wouldn't mind writing a patch, but I'm not sure I understand it well enough to do the right thing. Unfortunately, the `ChunkedInput` interface doesn't have an `.isClosed()` method, so you can't add a check for that in line 177 of `ChunkedWriteHandler`.  You could always specifically catch the IOException and match on the message, but that's almost always the wrong thing to do.

**Comment by SubJunk** [comment]
Any updates on this? :)

**Comment by trustin** [comment]
Fixed: f1f7f92 (master), f4e527c (4.1), 28caa873 (4.0)

**Comment by SubJunk** [comment]
@trustin thanks!

**Comment by mfulgo** [comment]
@trustin Thanks!
