### ISSUE TITLE
Netty 4.0.25.Final running resteasy sometimes hangs with message "Force-closing a channel whose registration task was not accepted by an event loop"

### ISSUE THREAD

**Issue by mxk1235** [netty/netty#3393]
At some point the server starts timing out over half the request with the following stack trace.  I am not sure what uses a SingleThreadExecutor on the internals, but a quick search didn't find in any code above netty.  any help is appreciated.

this is running on Ubuntu 14, java8, netty 4.0.25.Final

2015-02-06_07:02:32.04919 44263127 [nioEventLoopGroup-2-1] WARN  i.n.channel.AbstractChannel - Force-closing a channel whose registration task was not accepted by an e
vent loop: [id: 0x3e4727ce, /127.0.0.1:41544 => /127.0.0.1:9384]
2015-02-06_07:02:32.04920 java.util.concurrent.RejectedExecutionException: event executor terminated
2015-02-06_07:02:32.04921       at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:745) ~[shopvac.jar:na]
2015-02-06_07:02:32.04921       at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:322) ~[shopvac.jar:na]
2015-02-06_07:02:32.04921       at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:728) ~[shopvac.jar:na]
2015-02-06_07:02:32.04922       at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:420) ~[shopvac.jar:na]
2015-02-06_07:02:32.04923       at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60) [shopvac.jar:na]
2015-02-06_07:02:32.04923       at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48) [shopvac.jar:na]
2015-02-06_07:02:32.04923       at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64) [shopvac.jar:na]
2015-02-06_07:02:32.04924       at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:251) [shopvac.jar:na]
2015-02-06_07:02:32.04924       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [shopvac.jar:na]
2015-02-06_07:02:32.04925       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [shopvac.jar:na]
2015-02-06_07:02:32.04925       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [shopvac.jar:na]
2015-02-06_07:02:32.04925       at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [shopvac.jar:na]
2015-02-06_07:02:32.04926       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [shopvac.jar:na]
2015-02-06_07:02:32.04927       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [shopvac.jar:na]
2015-02-06_07:02:32.04927       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [shopvac.jar:na]
2015-02-06_07:02:32.04927       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [shopvac.jar:na]
2015-02-06_07:02:32.04928       at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [shopvac.jar:na]
2015-02-06_07:02:32.04928       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [shopvac.jar:na]
2015-02-06_07:02:32.04928       at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]
2015-02-06_07:02:32.04936 44263132 [nioEventLoopGroup-2-1] ERROR i.n.u.c.D.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
2015-02-06_07:02:32.04936 java.util.concurrent.RejectedExecutionException: event executor terminated
2015-02-06_07:02:32.04937       at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:745) ~[shopvac.jar:na]
2015-02-06_07:02:32.04937       at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:322) ~[shopvac.jar:na]
2015-02-06_07:02:32.04937       at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:728) ~[shopvac.jar:na]
2015-02-06_07:02:32.04938       at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671) [shopvac.jar:na]
2015-02-06_07:02:32.04938       at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:641) [shopvac.jar:na]
2015-02-06_07:02:32.04938       at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:138) [shopvac.jar:na]
2015-02-06_07:02:32.04938       at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93) [shopvac.jar:na]
2015-02-06_07:02:32.04939       at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28) [shopvac.jar:na]
2015-02-06_07:02:32.04940       at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:251) [shopvac.jar:na]
2015-02-06_07:02:32.04940       at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [shopvac.jar:na]
2015-02-06_07:02:32.04940       at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [shopvac.jar:na]
2015-02-06_07:02:32.04941       at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [shopvac.jar:na]
2015-02-06_07:02:32.04941       at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [shopvac.jar:na]
2015-02-06_07:02:32.04941       at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [shopvac.jar:na]
2015-02-06_07:02:32.04942       at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [shopvac.jar:na]
2015-02-06_07:02:32.04942       at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [shopvac.jar:na]
2015-02-06_07:02:32.04942       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [shopvac.jar:na]
2015-02-06_07:02:32.04943       at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [shopvac.jar:na]
2015-02-06_07:02:32.04943       at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [shopvac.jar:na]
2015-02-06_07:02:32.04944       at java.lang.Thread.run(Thread.java:745) [na:1.8.0_20]

**Comment by trustin** [comment]
Seems like the event loop has been shut down by RestEasy already? Did you talk to the RestEasy community to see if it's their bug?

**Comment by mxk1235** [comment]
i did a cursory search through debug logs but did not find any errors or shutdown happening in the resteasy or my custom handlers.  basically, tried to post the issue to see if anyone else has already seen it.

i'm currently trying to track this bug from another direction, trying to eliminate possibilities that there is some sort of blocking operation, but i'll update this issue with my findings.

**Comment by normanmaurer** [comment]
@mxk1235 like @trustin said this seems like a RestEasy bug. Please re-open if you still think it is a netty bug
