### ISSUE TITLE
channelFuture.addListener() throws exception if channel is closed

### ISSUE THREAD

**Issue by tbocek** [netty/netty#3449]
Hi,

I get the following error when I want to add a listener, but the channel is closed. I expect that the listener is added and the operationComplete() is called with a future in a failed state. However, I get this exception:

```
10:18:02.144 [Thread-0] ERROR i.n.u.c.D.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:745) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:322) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:728) ~[netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671) [netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:641) [netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:138) [netty-common-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
	at net.tomp2p.connection.Sender.afterConnect(Sender.java:736) [classes/:na]
	at net.tomp2p.holep.HolePuncher.tryConnect(HolePuncher.java:456) [classes/:na]
	at net.tomp2p.holep.HolePunchScheduler.run(HolePunchScheduler.java:36) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
```

A workaround for me is to use try-catch, but I was expecting that when adding a listener, that operationComplete() is called.

**Comment by normanmaurer** [comment]
@tbocek this will only happen once you shutdown the EventLoop that belongs to the Channel.

**Comment by tbocek** [comment]
I checked the netty code again, and it seems that in such a case, the error is just logged. The operationComplete() is never called and no exception is thrown back to the user. So I cannot react on it.

That means I need to make sure beforehand that the EventLoop is still alive. Wouldn't it make sense that instead of logging the exception, notifying the listener with a failed state?

**Comment by normanmaurer** [comment]
@tbocek the problem is that this would not full-fill the contract that the listeners will be notified with the EventLoops thread. Maybe what we should do is throw an IllegalStateException on addListener(...)

@trustin wdyt ?

**Comment by tbocek** [comment]
@normanmaurer I don't mind if the listener is called or an exception thrown. Currently, the call is silently (ok, there is logging) dropped and any kind of feedback to the API user where the API user can react on it would be good.

**Comment by trustin** [comment]
I think it might be useful for users to specify some catch-all callback for rejected executions.  By default, we just log, and you could override that behavior.

**Comment by trustin** [comment]
@tbocek Interested in sending a pull request? It should be pretty straightforward:

* Add a dedicated listener interface that handles a rejected task + the default implementation.
* Add the getter/setter of the rejected task listener to `EventExecutorGroup` and implement them properly.

**Comment by trustin** [comment]
Should be fixed by #5087
