### ISSUE TITLE
HttpRequestDecoder decode() problem (rarely but occured)

### ISSUE THREAD

**Issue by bwzhang2011** [netty/netty#3519]
@normanmaurer , I encoutered httpRequestDecoder problem in my prod environment. here comes the stacktrace from the log (hope if you have spare time, please take a look and feed back) : 

io.netty.handler.codec.DecoderException: HttpRequestDecoder.decode() did not read anything but decoded a message.
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:335)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:956)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)

By the way, I used the 5.0.0 snapshot2 version in my prod environment. I don't know the reason for such error.

**Comment by normanmaurer** [comment]
@bwzhang2011 please upgrade to 5.0.0.Alpha3-SNAPSHOT and re-open if it still persist

**Comment by bwzhang2011** [comment]
@normanmaurer, I did find the same log while upgraded to 5.0.0.Alpha3-SNAPSHOT and it occurred rarely.

**Comment by normanmaurer** [comment]
Any reproducer?

**Comment by bwzhang2011** [comment]
@normanmaurer, like this(part of the pipeline):
// 压缩与否自动支持
pipeline.addLast(DEFLATOR_TAG,new HttpContentCompressor());

// http编码支持
pipeline.addLast(ENCODER_TAG,new HttpResponseEncoder());

// http解码支持
pipeline.addLast(DECODER_TAG,new HttpRequestDecoder());

**Comment by Iker-Jimenez** [comment]
we can reproduce this. Started happening when we upgraded from 4.0.23.Final to 4.0.26.Final.

**Comment by normanmaurer** [comment]
@Iker-Jimenez can you share an app and steps to reproduce this with me ? Or a unit test that reproduce this ?

**Comment by Iker-Jimenez** [comment]
I think this is the same as https://github.com/netty/netty/issues/3247

**Comment by ddossot** [comment]
@Iker-Jimenez Did you downgrade back to `4.0.23.Final` or did you try with `4.0.24.Final` ? `4.0.25.Final` seems have the issue per https://github.com/netty/netty/issues/3247#issuecomment-69491567 so I'm trying to see how far back we need to downgrade...

**Comment by Iker-Jimenez** [comment]
@ddossot we didn't try 4.0.24, we knew 4.0.23 was good and we went back to it. We cannot reproduce this easily in non-prod systems so we took the safe approach.

**Comment by ddossot** [comment]
@Iker-Jimenez Gotcha, we have the same problem: this issue only shows in prod so we'll probably follow your path and play it safe...

**Comment by normanmaurer** [comment]
@Iker-Jimenez sorry I totally missed this.

I think this was fixed by @trustin in netty 4.0.27.Final by this:
https://github.com/netty/netty/commit/2c14406b55e2879a6acef051049eccca24ed0202#diff-bf7a179a319b29e0262d5badaf3770e0

Could you please try to use netty 4.0.32.Final and see if the issue is still there ?
