### ISSUE TITLE
OutOfMemory error while doing a file upload of size 7GB through Netty

### ISSUE THREAD

**Issue by karuturi** [netty/netty#3559]
This is the exception I see

```
java.lang.OutOfMemoryError: Java heap space
    at io.netty.buffer.UnpooledHeapByteBuf.capacity(UnpooledHeapByteBuf.java:114)
    at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:251)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:849)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:841)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:831)
    at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:337)
    at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:48)
    at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.offer(HttpPostRequestDecoder.java:236)
    at org.apache.cloudstack.storage.resource.HttpUploadServerHandler.channelRead0(HttpUploadServerHandler.java:200)
    at org.apache.cloudstack.storage.resource.HttpUploadServerHandler.channelRead0(HttpUploadServerHandler.java:65)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

I see that its trying to allocate bytes for new capacity. 

```
byte[] newArray = new byte[newCapacity];
```

But, why is this happening only for big files? Is it not releasing the existing memory?
Is there any max file size limit?

**Comment by rfielding** [comment]
HttpPostRequestDecoder is at fault.  The whole point of the interface is to iterate the metadata/data for each part in upload order, and to get a ChannelBuffer for the part rather than a byte array.  But the way that the object is constructed defeats the purpose of this interface.  Even for gigabyte sized files, there is no need to buffer more than a few kilobytes during the upload.  i.e.: Memory usage should be proportional to the number of concurrent sessions, and be totally unrelated to the size of files being upload.  There is a similar issue with realizing http responses into byte arrays.

**Comment by jknack** [comment]
Also ran into this problem with a 1.8GB file.

**Comment by rfielding** [comment]
@jknack I had run into not only this problem last year, but all the dependents on this code that *also* make this assumption (netty -> Finagle/Finatra -> user apps).  I gave up on the framework eventually.  This issue was closed, so you can assume that it will never be fixed.

http4s downloaded a 47GB file - though I didn't try uploading such a large file.  Or you can use a raw http connection and implement your own multipart handling (it's not that hard if you get rid of the layers of abstraction).  Actually, I eventually moved on to Go, where I could control the details of the http connection completely.  The problem is that you only need buffers large enough to absorb incoming traffic without creating delays, which is really only a few kB, and stream them the way that http was designed.

**Comment by Scottmitch** [comment]
I'm not familiar with the multipart decoder but it is concerning that we must hold so much in memory ... @normanmaurer @trustin - any thoughts?

**Comment by jknack** [comment]
Here is the stacktrace for 4.1.x

```
Caused by: java.lang.OutOfMemoryError: Java heap space
	at io.netty.buffer.UnpooledHeapByteBuf.copy(UnpooledHeapByteBuf.java:473) ~[netty-buffer-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.readFileUploadByteMultipart(HttpPostMultipartRequestDecoder.java:1492) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.getFileUpload(HttpPostMultipartRequestDecoder.java:902) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:563) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDisposition(HttpPostMultipartRequestDecoder.java:804) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:501) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDelimiter(HttpPostMultipartRequestDecoder.java:657) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:488) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBodyMultipart(HttpPostMultipartRequestDecoder.java:453) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBody(HttpPostMultipartRequestDecoder.java:422) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:347) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.<init>(HttpPostMultipartRequestDecoder.java:193) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.java:97) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
	at io.netty.handler.codec.http.multipart.HttpPostRequestDecoder.<init>(HttpPostRequestDecoder.java:68) ~[netty-codec-http-4.1.0.CR7.jar:4.1.0.CR7]
```

The HttpPostRequestDecoder was created like:

```java
HttpPostRequestDecoder decoder = new HttpPostRequestDecoder(new DefaultHttpDataFactory(true), req);
```

Where ```req``` is a ```FullHttpRequest```

**Comment by rfielding** [comment]
@Scottmitch it's the general issue of holding things in byte arrays.  I spent quite a few days debug-stepping through Netty+Finagle, trying to troubleshoot large file uploads and downloads.  Increasing max size allowed just expands memory usage so that we run out of memory.  

The first problem was trying to read entire request (head and body) into byte arrays, and the other problem was serializing objects into byte arrays before sending them out.  The ChannelBuffer abstraction is supposed to prevent this, but there are locations that turn the channel buffers into byte arrays.  This can easily take thousands of times more memory than is actually required.

**Comment by Scottmitch** [comment]
@rfielding @jknack - Thanks for the additional info. I understand the issue but I don't have time to dig in at the moment. @rfielding - Did you come up with alternative approaches though your investigation into Netty+Finagle and do you have interest in submitting a PR?

**Comment by rfielding** [comment]
@Scottmitch I had made a change to Netty that fixed the problem for myself in Netty, but then higher layers that used Netty also presumed that they could access uploaded items in any order (which therefore presumes that they are sitting in a hashtable), which caused Finagle to crash before it even reached my handler.  

So, I unfortunately had to switch frameworks to meet my requirements.    I can now do multi-gigabyte file up/down (even on a RaspberryPi) and stay under a few hundred kilobytes while doing so (I did it in Go, but think I could have done it with Java.)  The main thing is using ChannelBuffers to avoid holding objects in memory.

**Comment by jknack** [comment]
@rfielding agreed. My app uses http://jooby.org which has support for multiple servers including undertow, jetty and netty (netty is the default web server).

As a workaround, I switched to undertow and had no problem with big uploads.

**Comment by fredericBregier** [comment]
DefaultHttpDataFactory has a specific argument: 

- https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/multipart/DefaultHttpDataFactory.java#L95 where the max size could be set (or using the other constructor that will set useDisk to true).

If setting this, you shall not have any memory issue (except if there is a bug in coding), that's why there are 3 implementations of attributes (memory based - default - , disk based and mixed one).

Perhaps chaning the default behavior would be a nice thing, preventing this kind of issue?

**Comment by fredericBregier** [comment]
Quick note: I note that you set "true" so meaning using disk based, so if there is such a memory issue, it means that there is a bug.

**Comment by rfielding** [comment]
That's good that at least the large files can be written to disk.  (Go's framework actually works like this by default.... where files over 10MB spill out to disk to free up memory.)  There is still a problem if the file is being written to disk.  If the file comes in over SSL, you don't want to spill the beans by leaving the plaintext version of it sitting in a cache on the filesystem.  If you just get filehandles for incoming files in the order they arrive, you can push them through the appropriate ciphers on their way to disk or S3, etc.

**Comment by normanmaurer** [comment]
Let me close this as it had no activity for a long time... Please re-open if you still think there is an issue

**Comment by ysde** [comment]
Hi, has this netty oom problem been fixed ?

Thank you

**Comment by hyperxpro** [comment]
Same issue here too.
