### ISSUE TITLE
SSLHandler may incur performance degradation.

### ISSUE THREAD

**Issue by jingene** [netty/netty#3639]
Netty version : 4.0.26.Final
JDK : 1.7.0_25(HotSpot)

Hello, I'm using Netty as a HTTP file server(and also using TLS). 
I ran some performance tests(bulk HTTPS GET requests), and I found IOThread block concurrently(using visualVM).
This affects critical performance degradation on my server.

As you can see below, java.security.SecureRandom.nextBytes method "BLOCKED" in IOThread.
###################################################################################
"nioEventLoopGroup-3-24" prio=10 tid=0x00007fc8400c8800 nid=0x3ef6 waiting for monitor entry [0x00007fc7555dc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
    at java.security.SecureRandom.nextBytes(SecureRandom.java:455)
    - waiting to lock <0x00000007700560f0> (a java.security.SecureRandom)
    at sun.security.ssl.CipherBox.encrypt(CipherBox.java:309)
    at sun.security.ssl.EngineOutputRecord.encrypt(EngineOutputRecord.java:148)
    at sun.security.ssl.EngineOutputRecord.write(EngineOutputRecord.java:310)
    at sun.security.ssl.EngineOutputRecord.write(EngineOutputRecord.java:270)
    at sun.security.ssl.EngineWriter.writeRecord(EngineWriter.java:185)
    - locked <0x0000000771329ee0> (a sun.security.ssl.EngineWriter)
    at sun.security.ssl.SSLEngineImpl.writeRecord(SSLEngineImpl.java:1272)
    at sun.security.ssl.SSLEngineImpl.writeAppRecord(SSLEngineImpl.java:1242)
    - locked <0x0000000771329f40> (a java.lang.Object)
    at sun.security.ssl.SSLEngineImpl.wrap(SSLEngineImpl.java:1157)
    - locked <0x0000000771329f10> (a java.lang.Object)
    at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509)
    at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:650)
    at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:494)
    at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:469)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:735)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:716)
    at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
    at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:197)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:735)
    at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:32)
    at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1033)
    at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:965)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
###################################################################################
I know it's not netty's logic. but I think wrap() method in SSLHandler become asynchronous to avoid blocking IOThread(using ThreadPoolExecutor or ~).

java.security.SecureRandom documentation says :
  Depending on the implementation, the generateSeed and nextBytes methods may block as entropy is being gathered, for example, if they need to read from /dev/random on various unix-like operating systems(https://docs.oracle.com/javase/7/docs/api/java/security/SecureRandom.html).

The alternative is to using "/dev/urandom" instead of "/dev/random" in JVM option.
But as I know urandom is insecure than random.

Please review this issue.

**Comment by trustin** [comment]
It seems like the system has run out of entrophy, although it's not very usual for busy systems.

You can feed `/dev/random` using daemons like:

* haveged - http://www.issihosts.com/haveged/
* timer_entropyd - http://www.vanheusden.com/te/
* audio_entropyd - http://www.vanheusden.com/aed/

**Comment by jingene** [comment]
@trustin 
Thank you for your reply, but I attached another thread-dump when io.netty.handler.ssl.SslHandler.wrap() BLOCKed in IOThread(using PooledByteBufAllocator)
###############################################################################
"nioEventLoopGroup-3-14" prio=10 tid=0x00007fed1c0b3800 nid=0x3484 waiting for monitor entry [0x00007fec35228000]
   java.lang.Thread.State: BLOCKED (on object monitor)
    at io.netty.buffer.PoolArena.free(PoolArena.java:202)
    - locked <0x0000000770013878> (a io.netty.buffer.PoolArena$DirectArena)
    at io.netty.buffer.PooledByteBuf.deallocate(PooledByteBuf.java:147)
    at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:106)
    at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:50)
    at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:59)
    at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:84)
    at io.netty.channel.PendingWriteQueue.remove(PendingWriteQueue.java:213)
    at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:496)
    at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:469)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:735)

**Comment by trustin** [comment]
Is is blocked there indefinitely? If so, it deserves a new issue, because it seems unrelated to this issue.

**Comment by jingene** [comment]
@trustin
No. IOThread wasn't freezed, but blocking occurs frequently.
During the perf-test, " /proc/sys/kernel/random/entropy_avail" value was not dropped below 100.
I think drained-entropy is not an issue.

**Comment by trustin** [comment]
Alright. Did you try the OpenSSL-based SSLEngine we provide, then?

**Comment by normanmaurer** [comment]
@trustin not really related to the original issue but maybe we should review our PooledByteBufAllocator and how it synchronize on the PoolArena's. Maybe we could do something smart here... WDYT ? Should I open another issue for this ?

**Comment by normanmaurer** [comment]
@jingene for more infos about our OpenSSL-based SSLEngine check this:

http://netty.io/wiki/forked-tomcat-native.html#wiki-h2-1
