### ISSUE TITLE
Immediate HTTP/2 stream removal kills connection for HEADERS

### ISSUE THREAD

**Issue by ejona86** [netty/netty#3643]
Issue #3557 seeks to improve handling of DATA frames now that streams are immediately removed. DATA frame handling is "okay" now, but could be improved. However, HEADERS frames are handled very poorly.

I'm seeing exceptions like:
```
Caused by: io.netty.handler.codec.http2.Http2Exception: Request stream 11 is not correct for server connection
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:58)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:1002)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:873)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:829)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:269)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:260)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:54)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:450)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:459)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:226)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:130)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:39)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:99)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:288)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:329)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:316)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1001)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:891)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:316)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:956)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:127)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	... 3 more
```

If a client sends RST_STREAM (for one of its streams) while a server-sent HEADERS frame is en route, then the client would cause the above error and reset the _connection_. This sort of situation is also likely if trailers are involved.

This makes RST_STREAM very dangerous with the current implementation. I've encountered some users that RST_STREAM very often, and the above error is reliable for those users.

@Scottmitch @nmittler @buchgr

**Comment by nmittler** [comment]
IIUC, [this is the problem](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L268).  We just blindly try to create the stream without first checking if it's for a previously existing stream (by checking the streamId).  I think this should be easy to fix.  I'll try to throw together a PR.

**Comment by louiscryan** [comment]
I see the same issue manifest in a different way.

Clients can send WINDOW_UPDATE to a server that has already closed it's stream. This occurs when the server sends a sequence of DATA frames and then immediately closes the stream. The client after processing some of the received DATA frames decides it needs to release more flow control and sends WINDOW_UPDATE.  This races with the server.


The client will happily process the other DATA frames but the server sees this as a fatal error and closes the connection which is ugly.

**Comment by Scottmitch** [comment]
@nmittler - +1. This code doesn't look right to me.

@louiscryan -

>This occurs when the server sends a sequence of DATA frames and then immediately closes the stream.

The `immediately closes` portion of this statement.  It seems like you are implying the ["half closed (local)" state transition](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L451) is skipped on the server side?  Is a "RST_STREAM" being generated for some reason?  Shouldn't the normal flow be to go to h

**Comment by ejona86** [comment]
@Scottmitch, in the case @louiscryan is referring to the client already sent END_STREAM in the past; it was the server who was keeping the stream in half closed state. This would very easily happen with a GET request if the response is > 32 KB and < 64 KB (also if > 64 KB, but it becomes more complex then).

**Comment by louiscryan** [comment]
Yes, its exactly as Eric described. The client has already half-closed before the server starts responding which is the case for pretty much all of HTTP.

**Comment by Scottmitch** [comment]
@ejona86 @louiscryan - Thanks for clarifying.  This makes sense.  I think this is a bug in the window update code [here](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L486).  We should not require the stream....

[section 6.9](https://tools.ietf.org/html/draft-ietf-httpbis-http2-17#section-6.9):
> WINDOW_UPDATE can be sent by a peer that has sent a frame bearing the
   END_STREAM flag.  This means that a receiver could receive a
   WINDOW_UPDATE frame on a "half closed (remote)" or "closed" stream.
   A receiver MUST NOT treat this as an error, see Section 5.1.

**Comment by nmittler** [comment]
@Scottmitch +1 .. would you mind throwing a PR together to fix that? I'm working on bringing back stream history ATM.

**Comment by Scottmitch** [comment]
@nmittler - I will.  Before you work on history can you take a look at https://github.com/netty/netty/issues/3557#issuecomment-94026540?

**Comment by Scottmitch** [comment]
@nmittler - Do you want me to fix https://github.com/netty/netty/issues/3643#issuecomment-93985930 in my PR too?

**Comment by nmittler** [comment]
@Scottmitch Yeah, if it's not too much trouble go ahead and fix the HEADERS problem as well.  Unfortunately, I think we need to fix this for virtually all frames on the receiving side. :/ ... having some sort of history would make this a lot simpler.

I'm currently bringing back a garbage collector concept (in a hopefully cleaner way) as a backup solution if we can't find a good way to deal without having history.

**Comment by Scottmitch** [comment]
@nmittler - See https://github.com/netty/netty/issues/3653

**Comment by nmittler** [comment]
@Scottmitch @ejona86 see my comment in another thread regarding history: https://github.com/netty/netty/issues/3653#issuecomment-94176994

**Comment by adleong** [comment]
Hi @nmittler,

I believe that I'm running into this problem on netty-4.1.10.final.  The problem seems to be that we receive a RST_STREAM from the client as we're about to write a HEADERS frame to that stream.  Since the stream no longer exists, we attempt to create it which causes the `stream is not correct for server connection` error.

https://github.com/netty/netty/commit/ab925abc7db806ead57f8d9ea50ff322ce2ff891 does not protect against this issue since `writeHeaders` only checks if the stream exists and doesn't check if the `streamMayHaveExisted`.

https://github.com/netty/netty/blob/ab925abc7db806ead57f8d9ea50ff322ce2ff891/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L151

Was the `streamMayHaveExisted` check deliberately omitted from `writeHeaders`?  Any help understanding this issue and potential solutions is greatly appreciated!

Here is the relevant frame log and stack trace:
<details>

```
TRACE 0628 11:31:59.749 PDT finagle/netty4-5:
----------------INBOUND--------------------
[id: 0xf1e8fd93, L:/127.0.0.1:4141 - R:/127.0.0.1:61009] DATA: streamId=73, padding=0, endStream=true, length=5, bytes=0000000000
------------------------------------
TRACE 0628 11:31:59.751 PDT finagle/netty4-5:
----------------INBOUND--------------------
[id: 0xf1e8fd93, L:/127.0.0.1:4141 - R:/127.0.0.1:61009] RST_STREAM: streamId=71, errorCode=8
------------------------------------
TRACE 0628 11:31:59.751 PDT finagle/netty4-5:
----------------OUTBOUND--------------------
[id: 0xf1e8fd93, L:/127.0.0.1:4141 - R:/127.0.0.1:61009] GO_AWAY: lastStreamId=73, errorCode=1, length=54, bytes=526571756573742073747265616d203731206973206e6f7420636f727265637420666f722073657276657220636f6e6e656374696f6e
------------------------------------
DEBUG 0628 11:31:59.751 PDT finagle/netty4-5: [id: 0xf1e8fd93, L:/127.0.0.1:4141 - R:/127.0.0.1:61009] Sent GOAWAY: lastStreamId '73', errorCode '1', debugData 'Request stream 71 is not correct for server connection'. Forcing shutdown of the connection.
TRACE 0628 11:31:59.754 PDT finagle/netty4-5:
----------------OUTBOUND--------------------
[id: 0x270cd8d2, L:/127.0.0.1:65363 - R:/127.0.0.1:7778] RST_STREAM: streamId=63289, errorCode=8
------------------------------------
E 0628 18:31:59.753 UTC THREAD102: [S L:/127.0.0.1:4141 R:/127.0.0.1:61009 S:71] ignoring exception
com.twitter.finagle.ChannelWriteException: com.twitter.finagle.UnknownChannelException: Request stream 71 is not correct for server connection at remote address: /127.0.0.1:61009. Remote Info: Not Available. Remote Info: Not Available
Caused by: com.twitter.finagle.UnknownChannelException: Request stream 71 is not correct for server connection at remote address: /127.0.0.1:61009. Remote Info: Not Available
  at com.twitter.finagle.ChannelException$.apply(Exceptions.scala:258)
  at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.operationComplete(ChannelTransport.scala:105)
  at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.operationComplete(ChannelTransport.scala:102)
  at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
  at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
  at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
  at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
  at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:208)
  at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:146)
  at io.netty.handler.codec.http2.H2FrameCodec.write(H2FrameCodec.scala:141)
  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
  at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
  at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1089)
  at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1136)
  at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1078)
  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
  at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.handler.codec.http2.Http2Exception: Request stream 71 is not correct for server connection
  at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
  at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:839)
  at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:705)
  at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:625)
  at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:156)
  ... 16 more

E 0628 18:31:59.753 UTC THREAD102: [S L:/127.0.0.1:4141 R:/127.0.0.1:61009 S:71] unexpected error
com.twitter.finagle.ChannelWriteException: com.twitter.finagle.UnknownChannelException: Request stream 71 is not correct for server connection at remote address: /127.0.0.1:61009. Remote Info: Not Available. Remote Info: Not Available
Caused by: com.twitter.finagle.UnknownChannelException: Request stream 71 is not correct for server connection at remote address: /127.0.0.1:61009. Remote Info: Not Available
  at com.twitter.finagle.ChannelException$.apply(Exceptions.scala:258)
  at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.operationComplete(ChannelTransport.scala:105)
  at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.operationComplete(ChannelTransport.scala:102)
  at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
  at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
  at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
  at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:122)
  at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:208)
  at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:146)
  at io.netty.handler.codec.http2.H2FrameCodec.write(H2FrameCodec.scala:141)
  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
  at io.netty.channel.AbstractChannelHandlerContext.access$1900(AbstractChannelHandlerContext.java:38)
  at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1089)
  at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1136)
  at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1078)
  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
  at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.handler.codec.http2.Http2Exception: Request stream 71 is not correct for server connection
  at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
  at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:839)
  at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:705)
  at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:625)
  at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:156)
  ... 16 more
```

</details>

Thanks!

**Comment by Scottmitch** [comment]
Possibly related: https://github.com/netty/netty/pull/6916

**Comment by adleong** [comment]
@Scottmitch ah, yes, I think that's it!
