### ISSUE TITLE
Review synchronization in PooledByteBufAllocator

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#3654]
@jingene reported:
```
Thank you for your reply, but I attached another thread-dump when io.netty.handler.ssl.SslHandler.wrap() BLOCKed in IOThread(using PooledByteBufAllocator)
###############################################################################
"nioEventLoopGroup-3-14" prio=10 tid=0x00007fed1c0b3800 nid=0x3484 waiting for monitor entry [0x00007fec35228000]
java.lang.Thread.State: BLOCKED (on object monitor)
at io.netty.buffer.PoolArena.free(PoolArena.java:202)
- locked <0x0000000770013878> (a io.netty.buffer.PoolArena$DirectArena)
at io.netty.buffer.PooledByteBuf.deallocate(PooledByteBuf.java:147)
at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:106)
at io.netty.buffer.AbstractDerivedByteBuf.release(AbstractDerivedByteBuf.java:50)
at io.netty.util.ReferenceCountUtil.release(ReferenceCountUtil.java:59)
at io.netty.util.ReferenceCountUtil.safeRelease(ReferenceCountUtil.java:84)
at io.netty.channel.PendingWriteQueue.remove(PendingWriteQueue.java:213)
at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:496)
at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:469)
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:735)
```

We should review if we can improve this. 

This was first mentioned in https://github.com/netty/netty/issues/3639

**Comment by buchgr** [comment]
@normanmaurer @jingene +1, we are seeing the same locks causing some contention in GRPC.

**Comment by normanmaurer** [comment]
Should be a lot better now.
