### ISSUE TITLE
ChannelFuture is not done after shutdown - causing deadlocks

### ISSUE THREAD

**Issue by krasa** [netty/netty#3662]
netty version: 4.1.0.Beta4, 4.0.27.Final, 4.0.25.Final

causes: https://github.com/twitter/cloudhopper-smpp/issues/92

testcase:
```
public class Netty4Deadlock {

    private static final Logger logger = LoggerFactory.getLogger(Netty4Deadlock.class);

    public static void main(String[] args) throws Exception {
        DefaultChannelGroup channels = new DefaultChannelGroup(GlobalEventExecutor.INSTANCE);
        Bootstrap bootstrap = new Bootstrap();
        NioEventLoopGroup group = new NioEventLoopGroup();
        bootstrap.group(group);
        bootstrap.channel(NioSocketChannel.class);
        bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 10000);
        bootstrap.handler(new LoggingHandler());

        //nothing running on the port 5000
        ChannelFuture connectFuture = bootstrap.connect(new InetSocketAddress("localhost", 5000));

        destroy(channels, group);

        logger.info("isDone={}", connectFuture.isDone()); //false
        logger.info("isCancelled={}", connectFuture.isCancelled()); //false
        logger.info("deadlock here:");
        connectFuture.awaitUninterruptibly();
        logger.info("done"); //never gets here
    }

    private static void destroy(DefaultChannelGroup channels, NioEventLoopGroup workerGroup) {
        logger.info("destroy");
        channels.close().awaitUninterruptibly();

        workerGroup.shutdownGracefully();

        try {
            // Wait until all threads are terminated.
            workerGroup.terminationFuture().sync();
        } catch (InterruptedException e) {
            logger.warn("Thread interrupted closing executors.", e);
        }
    }
}
```

thread dump:
```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.65-b04 mixed mode):

"Monitor Ctrl-Break" daemon prio=6 tid=0x0000000011196800 nid=0x2128 runnable [0x00000000115ee000]
   java.lang.Thread.State: RUNNABLE
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.read(SocketInputStream.java:152)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	- locked <0x00000007ab11a240> (a java.io.InputStreamReader)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	- locked <0x00000007ab11a240> (a java.io.InputStreamReader)
	at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at com.intellij.rt.execution.application.AppMain$1.run(AppMain.java:93)
	at java.lang.Thread.run(Thread.java:745)

"Service Thread" daemon prio=6 tid=0x000000000f0d7800 nid=0x236c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" daemon prio=10 tid=0x000000000f0d5800 nid=0x2430 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" daemon prio=10 tid=0x000000000f0d4000 nid=0x362c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" daemon prio=10 tid=0x000000000f0d2800 nid=0x31dc runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" daemon prio=10 tid=0x000000000f0cb000 nid=0x2a14 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" daemon prio=8 tid=0x000000000f077800 nid=0xb08 in Object.wait() [0x000000001067e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007aae85608> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000007aae85608> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" daemon prio=10 tid=0x000000000f06e000 nid=0x2b2c in Object.wait() [0x000000001045f000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007aae85190> (a java.lang.ref.Reference$Lock)
	at java.lang.Object.wait(Object.java:503)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:133)
	- locked <0x00000007aae85190> (a java.lang.ref.Reference$Lock)

"main" prio=6 tid=0x000000000032f000 nid=0x3a34 in Object.wait() [0x0000000001fae000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000007ac130128> (a io.netty.channel.DefaultChannelPromise)
	at java.lang.Object.wait(Object.java:503)
	at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:286)
	- locked <0x00000007ac130128> (a io.netty.channel.DefaultChannelPromise)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:135)
	at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:28)
	at com.cloudhopper.smpp.demo.perftest.Netty4Deadlock.main(Netty4Deadlock.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

"VM Thread" prio=10 tid=0x000000000f068800 nid=0x3554 runnable 

"GC task thread#0 (ParallelGC)" prio=6 tid=0x0000000001dde000 nid=0x310c runnable 

"GC task thread#1 (ParallelGC)" prio=6 tid=0x0000000001ddf800 nid=0x2454 runnable 

"GC task thread#2 (ParallelGC)" prio=6 tid=0x0000000001de1800 nid=0x263c runnable 

"GC task thread#3 (ParallelGC)" prio=6 tid=0x0000000001de3000 nid=0x38c8 runnable 

"VM Periodic Task Thread" prio=10 tid=0x000000000f0d8800 nid=0x34cc waiting on condition 

```

**Comment by normanmaurer** [comment]
@krasa thanks will check

**Comment by normanmaurer** [comment]
@krasa thanks for reporting.. I know the root-cause. Working on a fix.

**Comment by normanmaurer** [comment]
@krasa this should be fixed by #3683. Can you verify ?

**Comment by krasa** [comment]
@normanmaurer works fine, thanks!

**Comment by normanmaurer** [comment]
@krasa awesome thanks!

**Comment by normanmaurer** [comment]
Fixed
