### ISSUE TITLE
Enabled SecurityManager results in ClassNotFoundError during io.netty.util.NetUtil initialization

### ISSUE THREAD

**Issue by spinscale** [netty/netty#3680]
Hey,

Netty version used: 4.0.27

Setup: An application that has the security manager enabled, spits an not really helpful `ClassNotFoundError` in case that the application is not allowed to read a file due to the security manager. The reason for this is the try to read the file `/proc/sys/net/core/somaxconn` in https://github.com/netty/netty/blob/4.0/common/src/main/java/io/netty/util/NetUtil.java#L238

Exception looks like this:

```
Caused by: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
	at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:455)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:306)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:271)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:267)
	at org.elasticsearch.http.netty.NettyHttpServerTransport$1.onPortNumber(NettyHttpServerTransport.java:261)
	at org.elasticsearch.common.transport.PortsRange.iterate(PortsRange.java:69)
	at org.elasticsearch.http.netty.NettyHttpServerTransport.doStart(NettyHttpServerTransport.java:257)
	... 45 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.NetUtil
	at io.netty.channel.socket.DefaultServerSocketChannelConfig.&lt;init&gt;(DefaultServerSocketChannelConfig.java:39)
	at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.&lt;init&gt;(NioServerSocketChannel.java:189)
	at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.&lt;init&gt;(NioServerSocketChannel.java:187)
	at io.netty.channel.socket.nio.NioServerSocketChannel.&lt;init&gt;(NioServerSocketChannel.java:85)
	at io.netty.channel.socket.nio.NioServerSocketChannel.&lt;init&gt;(NioServerSocketChannel.java:70)
	at sun.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:453)
	... 51 more
```

if you need more infos, drop me a note, I am happy to help!

**Comment by normanmaurer** [comment]
@spinscale thanks for reporting. Let me fix this.

**Comment by normanmaurer** [comment]
Actually the scope of this needs to be broaden as we need to also ensure property access works in the static initializer. So this will be a bigger change.

**Comment by normanmaurer** [comment]
@trustin @Scottmitch FYI

**Comment by Scottmitch** [comment]
@normanmaurer - Lets fix this one and any others we can think of.  If we suspect this is a systemic problem lets open another issue.

**Comment by normanmaurer** [comment]
@Scottmitch +1 @spinscale fine with this ?

**Comment by spinscale** [comment]
@normanmaurer sure!

**Comment by normanmaurer** [comment]
@spinscale cool! Was this the only problem you needed to fix to get it run with a SecurityManager ?

**Comment by spinscale** [comment]
yes, mainly due to having specific permissions on how to access files, we dont do any property based security. You can see our policy file at https://github.com/elastic/elasticsearch/blob/master/dev-tools/tests.policy

**Comment by normanmaurer** [comment]
@spinscale thanks!

**Comment by normanmaurer** [comment]
Fixed
