### ISSUE TITLE
CompressorHttp2ConnectionEncoder is flushing in writeData

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#3711]
@Scottmitch @ejona86

Use of EmbeddedChannel in the compressor causes writes to the channel to become flushed immediately to the wire. 

See EmbeddedChannel.writeOutbound

at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:474)
    at io.netty.channel.ChannelHandlerAdapter.flush(ChannelHandlerAdapter.java:277)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
    at io.netty.channel.embedded.EmbeddedEventLoop.invokeFlush(EmbeddedEventLoop.java:247)
    at io.netty.channel.PausableChannelEventExecutor.invokeFlush(PausableChannelEventExecutor.java:46)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:480)
    at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:1006)
    at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:230)
    at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:205)
    at io.netty.handler.codec.http2.CompressorHttp2ConnectionEncoder.writeData(CompressorHttp2ConnectionEncoder.java:94)
    at io.netty.handler.codec.http2.DataCompressionHttp2Test$5.run(DataCompressionHttp2Test.java:246)
    at io.netty.handler.codec.http2.Http2TestUtil$1.run(Http2TestUtil.java:47)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:328)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
    at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
    at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
    at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
    at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
    at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)

**Comment by Scottmitch** [comment]
@louiscryan - We may be able to avoid using embedded channel (especially if it is causing heart-ache). It was just used to be consistent with the codec-http.

**Comment by ejona86** [comment]
@louiscryan, I don't think that flush actually matters. The flush occurs, but isn't going to actual I/O. Instead, the buffers wait until [nextReadableBuf()](https://github.com/netty/netty/blob/c98195714d393a71acd315d989887c97c217d389/codec-http2/src/main/java/io/netty/handler/codec/http2/CompressorHttp2ConnectionEncoder.java#L280). All the buffers returned from `nextReadableBuf()` seem to just go to `writeData()`.

**Comment by Scottmitch** [comment]
Yes it should not be going out to I/O directly, it will go through a `writeData`.  The EmbeddedChannel is a bit of a convenience / hack to re-use the compression libraries because they are setup to use channels.

**Comment by normanmaurer** [comment]
@louiscryan @Scottmitch @ejona86 @nmittler is there anything we need to do before 4.1.0.Final ?

**Comment by louiscryan** [comment]
Let me do a little digging but hopefully not

**Comment by normanmaurer** [comment]
@louiscryan can we close this one ?

**Comment by louiscryan** [comment]
Yeah given the low level of interest given that it's EmbeddedChannel feel free to close.
