### ISSUE TITLE
OpenSSL zlib compression (DEFLATE) broken in Netty 4.0.27.Final and netty-tcnative-1.1.32.Final

### ISSUE THREAD

**Issue by lkoszanski** [netty/netty#3722]
When using Netty with OpenSSL and zlib compression enabled I get the following error:

io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:346)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:229)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:283)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLException: error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac
    at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:590)
    at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:660)
    at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1114)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:981)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:934)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:315)
    ... 15 more

This behaviors was verified on both Linux and Mac OS X. 

Steps to reproduce:
1. Complie OpenSSL with zlib support enabled
2. Compile netty-tcnative-1.1.32.Fork1 against the said OpenSSL library
3. When using Netty make sure to clear the default behavior that disables OpenSSL compression:
   org.apache.tomcat.jni.SSLContext.clearOptions(ctx, org.apache.tomcat.jni.SSL.SSL_OP_NO_COMPRESSION);
4. Try sending at least 35 characters over established SSL netty channel. For some reason the bug does not seem to manifest itself with less then 35 chars...

**Comment by thanhnguyen** [comment]
Confirmed this on Windows using the latest Netty 5 code as well. It shows the same error.

**Comment by normanmaurer** [comment]
We not support compression with OPENSSL
