### ISSUE TITLE
HTTP/2 examples don't work with JDK SslProvider

### ISSUE THREAD

**Issue by ejona86** [netty/netty#3758]
The examples make an effort to swap to OpenSsl if it supports ALPN. However, if the JDK SslProvider is selected, then it will fail with (server-side):
```
Exception in thread "main" java.lang.UnsupportedOperationException: JDK provider does not support CHOOSE_MY_LAST_PROTOCOL failure behavior
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:231)
	at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:161)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:399)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:381)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:338)
	at io.netty.example.http2.server.Http2Server.main(Http2Server.java:55)
```

And on client-side:
```
Exception in thread "main" java.lang.UnsupportedOperationException: JDK provider does not support CHOOSE_MY_LAST_PROTOCOL failure behavior
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:241)
	at io.netty.handler.ssl.JdkSslClientContext.<init>(JdkSslClientContext.java:189)
	at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:729)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:211)
	at io.netty.example.http2.client.Http2Client.main(Http2Client.java:80)
```

Swapping to a JDK-supported behavior, like FATAL_ALERT, succeeds.

**Comment by Scottmitch** [comment]
@ejona86 - Thanks for reporting. I'll pick something that is supported by both JDK and OpenSSL.

**Comment by Scottmitch** [comment]
I have a PR pending for this...

**Comment by Scottmitch** [comment]
Addressed by https://github.com/netty/netty/issues/3767
