### ISSUE TITLE
Epoll client's connect future with ALLOW_HALF_CLOSURE enabled reports success on failed connection

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#3785]
The connect ChannelFuture of an Epoll client that has ALLOW_HALF_CLOSURE enabled reports success and doesn't raise an Exception. The Channel says it's active and even the ChannelHandler's methods such as channelActive() get called.

There is an exception under the hood (see below) but it's not getting exposed to the user. An unit test is attached (see below).

```
Netty 4.1.0-Beta6-SNAPSHOT

$ java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)

$ uname -a
Linux ardverk 3.19.3-1-ARCH #1 SMP PREEMPT Thu Mar 26 14:56:16 CET 2015 x86_64 GNU/Linux
```

### Exception

```
[epollEventLoopGroup-2-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: readAddress() failed: Connection refused
	at io.netty.channel.epoll.Native.newIOException(Native.java:127)
	at io.netty.channel.epoll.Native.ioResult(Native.java:143)
	at io.netty.channel.epoll.Native.readAddress(Native.java:284)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:235)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:254)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

### Unit Test

```
public class EpollHalfClosedConnectTest {
  
  @Test(expected=ConnectException.class)
  public void useNioHalfClosedConnect() throws Exception {
    connect(false);
  }
  
  @Test(expected=ClosedChannelException.class)
  public void useEpollHalfClosedConnect() throws Exception {
    connect(true);
  }
  
  private void connect(boolean useEpoll) throws Exception {
    Class<? extends SocketChannel> channelType
        = useEpoll ? EpollSocketChannel.class : NioSocketChannel.class;
  
    EventLoopGroup group = useEpoll 
        ? new EpollEventLoopGroup() 
        : new NioEventLoopGroup();
        
    ChannelHandler handler = new ChannelInboundHandlerAdapter() {
      @Override
      public void channelActive(ChannelHandlerContext ctx) throws Exception {
        Channel channel = ctx.channel();
        fail("Should have never been called: " + channel);
      }
    };
    
    try {
      Bootstrap bootstrap = new Bootstrap();
      
      bootstrap.group(group)
        .channel(channelType)
        .option(ChannelOption.ALLOW_HALF_CLOSURE, true)
        .handler(handler);
      
      ChannelFuture connectFuture = bootstrap.connect("localhost", 9999)
          .syncUninterruptibly();
      
      assertTrue(connectFuture.isDone());
      assertFalse(connectFuture.isSuccess());
      
    } finally {
      group.shutdownGracefully().awaitUninterruptibly();
    }
  }
}
```

### Log Output

```
[epollEventLoopGroup-2-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: readAddress() failed: Connection refused
	at io.netty.channel.epoll.Native.newIOException(Native.java:127)
	at io.netty.channel.epoll.Native.ioResult(Native.java:143)
	at io.netty.channel.epoll.Native.readAddress(Native.java:284)
	at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:235)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:254)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
[epollEventLoopGroup-2-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.AssertionError: Should have never been called: [id: 0x88d3ca97, /127.0.0.1:45718]
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at io.netty.channel.EpollHalfClosedConnectTest$1.channelActive(EpollHalfClosedConnectTest.java:43)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelActiveNow(ChannelHandlerInvokerUtil.java:48)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelActive(DefaultChannelHandlerInvoker.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:128)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:917)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.fulfillConnectPromise(AbstractEpollStreamChannel.java:695)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.finishConnect(AbstractEpollStreamChannel.java:728)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollOutReady(AbstractEpollStreamChannel.java:747)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:254)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Scottmitch** [comment]
@normanmaurer - I'll give this to you :)

**Comment by normanmaurer** [comment]
@Scottmitch you are so good too me ;)

**Comment by normanmaurer** [comment]
@rkapsi do you grant us to include your test-case into netty ?

**Comment by rkapsi** [comment]
@normanmaurer - yes of course.

**Comment by normanmaurer** [comment]
Thanks!

Working on a fix

**Comment by normanmaurer** [comment]
@rkapsi please check the fix https://github.com/netty/netty/pull/3832

**Comment by normanmaurer** [comment]
@rkapsi should be fixed now... Please reopen if you still think it is an issue. Thanks again for reporting and the test-case!

**Comment by rkapsi** [comment]
@normanmaurer: confirm. My canary test started passing (or rather failing) as soon as the new SNAPSHOT went live. Thanks!

**Comment by normanmaurer** [comment]
Awesome. Thanks!
