### ISSUE TITLE
Setting WRITE_BUFFER_LOW_WATER_MARK before WRITE_BUFFER_HIGH_WATER_MARK results in an internal Exception

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#3806]
Setting the WRITE_BUFFER_LOW_WATER_MARK before WRITE_BUFFER_HIGH_WATER_MARK results in an internal Exception (appears only in the logs) if the value is larger than the default high water mark value. The WRITE_BUFFER_HIGH_WATER_MARK call appears to have no effect in this context.

Setting the values in the reverse order works.

```
Netty 4.1.0-Beta6-SNAPSHOT
```

```
[main] WARN io.netty.bootstrap.Bootstrap - Failed to set a channel option: [id: 0xd686a724]
java.lang.IllegalArgumentException: writeBufferLowWaterMark cannot be greater than writeBufferHighWaterMark (65536): 131072
	at io.netty.channel.DefaultChannelConfig.setWriteBufferLowWaterMark(DefaultChannelConfig.java:334)
	at io.netty.channel.socket.DefaultSocketChannelConfig.setWriteBufferLowWaterMark(DefaultSocketChannelConfig.java:332)
	at io.netty.channel.socket.DefaultSocketChannelConfig.setWriteBufferLowWaterMark(DefaultSocketChannelConfig.java:35)
	at io.netty.channel.DefaultChannelConfig.setOption(DefaultChannelConfig.java:183)
	at io.netty.channel.socket.DefaultSocketChannelConfig.setOption(DefaultSocketChannelConfig.java:121)
	at io.netty.bootstrap.Bootstrap.init(Bootstrap.java:253)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:317)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:280)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:276)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:251)
```

```
@Test
public void bootstrap() {
  Bootstrap bootstrap = new Bootstrap();
  
  bootstrap.group(new NioEventLoopGroup())
    .channel(NioSocketChannel.class)
    .option(ChannelOption.WRITE_BUFFER_LOW_WATER_MARK, 128*1024)
    .option(ChannelOption.WRITE_BUFFER_HIGH_WATER_MARK, 512*1024)
    .handler(new ChannelInboundHandlerAdapter());
  
  bootstrap.bind(0);
}
```

**Comment by trustin** [comment]
We probably need a new option that accepts a pair of integers.

**Comment by normanmaurer** [comment]
@trustin should I take care?

**Comment by trustin** [comment]
@normanmaurer Go ahead. :-)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5060
