### ISSUE TITLE
OutOfMemoryError causes spin on cpu

### ISSUE THREAD

**Issue by tsholmes** [netty/netty#3807]
On 3.9.4, when an `OutOfMemoryError` occurs while creating an `NioClientSocketChannelFactory`, the epoll thread spins consuming 100% of a core. When we get an error creating this, we call `shutdownNow` on the provided `ExecutorService`s which interrupts the spinning thread, but it does not respond.

The OOM error:
```
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:640)
        at java.util.concurrent.ThreadPoolExecutor.addThread(ThreadPoolExecutor.java:681)
        at java.util.concurrent.ThreadPoolExecutor.addIfUnderMaximumPoolSize(ThreadPoolExecutor.java:727)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:655)
        at org.jboss.netty.util.internal.DeadLockProofWorker.start(DeadLockProofWorker.java:38)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.openSelector(AbstractNioSelector.java:349)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.<init>(AbstractNioSelector.java:100)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:52)
        at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45)
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:45)
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:28)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.newWorker(AbstractNioWorkerPool.java:143)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:81)
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39)
        at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:33)
        at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:151)
        at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:133)
```

jstack with the remaining threads (only others left are internal jvm threads):
```
"New I/O worker #2" prio=10 tid=0xf3fecc00 nid=0x3d8b runnable [0xf3cad000]
   java.lang.Thread.State: RUNNABLE
        at java.util.HashMap$KeyIterator.<init>(HashMap.java:826)
        at java.util.HashMap$KeyIterator.<init>(HashMap.java:826)
        at java.util.HashMap.newKeyIterator(HashMap.java:840)
        at java.util.HashMap$KeySet.iterator(HashMap.java:874)
        at java.util.HashSet.iterator(HashSet.java:153)
        at sun.nio.ch.SelectorImpl.processDeregisterQueue(SelectorImpl.java:127)
        - locked <0xc4dcdd10> (a java.util.HashSet)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:62)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
        - locked <0xc4dcb648> (a sun.nio.ch.Util$2)
        - locked <0xc4dcb658> (a java.util.Collections$UnmodifiableSet)
        - locked <0xc4dcb600> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
        at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:418)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)

"New I/O worker #1" prio=10 tid=0xf3d98c00 nid=0x3d89 runnable [0xf3cfe000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
        at sun.nio.ch.EPollArrayWrapper.interrupt(EPollArrayWrapper.java:256)
        at sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:175)
        - locked <0xc4dce000> (a java.lang.Object)
        at java.nio.channels.spi.AbstractSelector$1.interrupt(AbstractSelector.java:193)
        at java.nio.channels.spi.AbstractSelector.begin(AbstractSelector.java:198)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:64)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
        - locked <0xc4dcb818> (a sun.nio.ch.Util$2)
        - locked <0xc4dcb828> (a java.util.Collections$UnmodifiableSet)
        - locked <0xc4dcb7c8> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
        at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:68)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.select(AbstractNioSelector.java:418)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:212)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
        at java.lang.Thread.run(Thread.java:662)
```

**Comment by normanmaurer** [comment]
Netty 3.x is considered as EOL. Please upgrade to 4.x
