### ISSUE TITLE
Failed to open a socket on Android

### ISSUE THREAD

**Issue by marcusant** [netty/netty#3818]
When testing one of my projects that uses netty on Android, I received the following exceptions after trying to connect to a remote server. 

I'm using netty 5.0.0.Alpha2 on Android 5.0.2

This is my first time testing on Android (it's typically a desktop project), so I'm unsure of the version that this started at.

Here's the stacktrace
```
W/System.err( 8055): io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel
W/System.err( 8055):    at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
W/System.err( 8055):    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:315)
W/System.err( 8055):    at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:156)
W/System.err( 8055):    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:138)
W/System.err( 8055):    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
W/System.err( 8055): Caused by: io.netty.channel.ChannelException: Failed to open a socket.
W/System.err( 8055):    at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:62)
W/System.err( 8055):    at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:79)
W/System.err( 8055):    at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:72)
W/System.err( 8055):    at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
W/System.err( 8055):    at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:60)
W/System.err( 9187): io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel
W/System.err( 9187):    at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
W/System.err( 9187):    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:315)
W/System.err( 9187):    at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:156)
W/System.err( 9187):    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:138)
W/System.err( 9187):    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:119)
W/System.err( 9187): Caused by: io.netty.channel.ChannelException: Failed to open a socket.
W/System.err( 9187):    at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:62)
W/System.err( 9187):    at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:79)
W/System.err( 9187):    at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:72)
W/System.err( 9187):    at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
W/System.err( 9187):    at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:60)
```

And this is how I connect
```
            EventLoopGroup group = new NioEventLoopGroup()
            Bootstrap b = new Bootstrap();
            b.group(group)
                    .channel(NioSocketChannel.class)
                    .handler(new ChannelInitializer<SocketChannel>() {
                @Override
                protected void initChannel(SocketChannel ch) throws Exception {
                    ch.pipeline().addLast(new ObjectEncoder())
                    ch.pipeline().addLast(new ObjectDecoder(ClassResolvers.softCachingConcurrentResolver(this.getClass().getClassLoader())))
                    ch.pipeline().addLast(new VoxelGameClientHandler())
                }
            })

            b.connect(hostname, port).sync().channel().closeFuture().sync()
```

**Comment by normanmaurer** [comment]
@marcusant please try netty 4.0 or 4.1 as 5.0 is not android compatible as far as I know.

**Comment by marcusant** [comment]
Getting the same exception with 4.1.0.Beta5

```
W/System.err(21545): io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioSocketChannel
W/System.err(21545):    at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
W/System.err(21545):    at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:315)
W/System.err(21545):    at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:157)
W/System.err(21545):    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
W/System.err(21545):    at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:120)
W/System.err(21545): Caused by: io.netty.channel.ChannelException: Failed to open a socket.
W/System.err(21545):    at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:62)
W/System.err(21545):    at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:79)
W/System.err(21545):    at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:72)
W/System.err(21545):    at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
W/System.err(21545):    at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:60)
```

**Comment by marcusant** [comment]
Seems to work well with 4.0 and INTERNET permissions. Thank you for your suggestion.

**Comment by falkbene** [comment]
I was encountering the same issue. Adding 
`<uses-permission android:name="android.permission.INTERNET" />` and 
`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />` to the AndroidManifest.xml resolved the issue for me. Was also using 4.0.
