### ISSUE TITLE
SslHandler still have memory leak, 4.0.28.Final

### ISSUE THREAD

**Issue by ivanpopelyshev** [netty/netty#3859]
My game servers at gameofbombs.com are crashing too often. Most of clients use simple ws://, but every time part of stacktrace shows that someone uses websockets through SSL:

```
"nioEventLoopGroup-4-3" 23 prio=10 os_prio=0 tid=0x00007ff190044800 nid=0x251 runnable [0x00007ff18aa98000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Runtime.gc(Native Method)
        at java.lang.System.gc(System.java:993)
        at java.nio.Bits.reserveMemory(Bits.java:649)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.allocateDirect(UnpooledUnsafeDirectByteBuf.java:108)
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:69)
        at io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:50)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146)
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:83)
        at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1504)
        at io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:1514)
        at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:499)
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:477)
        at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1307)
        at io.netty.handler.ssl.SslHandler.close(SslHandler.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:543)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:528)
        at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:543)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:528)
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:394)
        at com.bm.server.AbstractWebSocket.exceptionCaught(AbstractWebSocket.java:72)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:79)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
        at io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:705)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:246)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:224)
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:834)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:87)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:162)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

That's how I close connection in case of error in com.bm.server.AbstractWebSocket:

```java
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
        accessLogger.error("error in websocket", cause);
        ctx.close();
    }
```

BTW, sometimes server survives through this problem. All players have big lag and game continues.
I have memory dump and stacktrace. What else can I look for?

**Comment by ivanpopelyshev** [comment]
Ok, I'm an idiot. Just googled http://netty.io/wiki/forked-tomcat-native.html .

**Comment by doom369** [comment]
You also may be interested in enabling native epoll transport http://netty.io/wiki/native-transports.html. It gave me 30% performance boost, while openSSL is only ~15%.

I have currently server on production for about 1 month with average load 50 req-sec and no issues so far.

**Comment by trustin** [comment]
Looking from the thread dump, you seem to be using an unpooled allocator which might be the culprit.  Did you try to use the pooled allocator?

    serverBootstrap.childOption(ChannelOptions.ALLOCATOR, PooledByteBufAllocator.DEFAULT);

For more information, take a look into @normanmaurer's slides - http://normanmaurer.me/presentations/2014-facebook-eng-netty/slides.html

**Comment by normanmaurer** [comment]
So I think we can close this... @trustin WDYT ?

**Comment by ivanpopelyshev** [comment]
Yep, you can close this. Thank you for advices, it helped :+1:
