### ISSUE TITLE
Change in the minimum requirements for using Epoll?

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#3861]
Hello,

has there been any change in the minimum requirements for using Epoll? We're keying everything off of `Epoll#isAvailable()` and it went almost unnoticed but my hard-coded Epoll test for issue https://github.com/netty/netty/issues/3709 started suddenly failing on our build machines.

```
Netty 4.1.0-Beta6-SNAPSHOT
```

```
-sh-4.1$ uname -a
Linux localhost 2.6.32-504.el6.x86_64 #1 SMP Wed Oct 15 04:27:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

```
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libnetty-transport-native-epoll2085384940434733335.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/libnetty-transport-native-epoll2085384940434733335.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1083)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:193)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:50)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:30)
```

**Comment by normanmaurer** [comment]
I wonder if we publish snapshots via our ubuntu ci by mistake. We should only do this via our centos slaves. I will check tomorrow if @trustin not beats me

**Comment by rkapsi** [comment]
I've narrowed the build down to `netty-all-4.1.0.Beta6-20150604.173400-69` (published on Thu Jun 04 17:34:00 UTC 2015 to your snapshot repository). Prior builds work fine.

**Comment by trustin** [comment]
The job `netty-deploy` was not pinned to any slaves, so it was always possible to deploy from non-CentOS6.  I've changed the job so that it's always run on CentOS 6 slaves and re-run the for all branches. Please wait for about an hour to see if the problem persists after updating to the latest snapshot.  If so, please reopen.

**Comment by rkapsi** [comment]
Confirm, fixed.
