### ISSUE TITLE
EmbeddedChannel constructor throws IllegalStateException

### ISSUE THREAD

**Issue by jroper** [netty/netty#3921]
On Netty 4.0.29, when I try to construct an `EmbeddedChannel`, I get an `IllegalStateException`:

```
java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.executor(AbstractChannelHandlerContext.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:222)
	at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:834)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:504)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded(DefaultChannelPipeline.java:482)
	at io.netty.channel.DefaultChannelPipeline.addLast0(DefaultChannelPipeline.java:146)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:129)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:257)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:244)
	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:79)
```

I'm not sure what the problem is, it first registers the event loop, this is usually an asynchronous operation so adding the handler straight after would usually be a race condition, but the implementation of the `EmbeddedEventLoop` register looks like it should be synchronous, so it looks like it should work with no problems.

**Comment by jroper** [comment]
I misread the code, I thought it was adding the handlers after registering with the event loop, but it's actually adding the handlers before registering with the event loop, which is clearly not allowed.

**Comment by normanmaurer** [comment]
@jroper can you show me the code you use ?

**Comment by jroper** [comment]
Sorry, I just noticed... the problem is that my `handlerAdded` callback is throwing an exception, and firing that exception is failing due to no event loop.  Up to you if you think this should be handled better, if not, just close this issue.

**Comment by normanmaurer** [comment]
@jroper it's a bug... Let me fix it.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/3935
