### ISSUE TITLE
NullPointerException in PendingWriteQueue

### ISSUE THREAD

**Issue by mingyu89** [netty/netty#3967]
Netty Version: 4.0.27.final

Hi. When there're network outages, sometimes on server side we saw handler's exceptionCaught was called with a NullPointerException in PendingWriteQueue. 
@trustin  Is it a race condition between adding SslHandler and closing channel?
Thanks.

```
java.lang.NullPointerException
        at io.netty.channel.PendingWriteQueue.recycle(PendingWriteQueue.java:248) 
        at io.netty.channel.PendingWriteQueue.removeAndWrite(PendingWriteQueue.java:196) 
        at io.netty.channel.PendingWriteQueue.removeAndWriteAll(PendingWriteQueue.java:150) 
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:455)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:735)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:735)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:716) 
        at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:735)
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:716)
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:735)
        at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:32) 
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1033)
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:965)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by normanmaurer** [comment]
That's strange... let me check

**Comment by normanmaurer** [comment]
@mingyu89 thanks for reporting.. I think I know what the problem is and I'm working on a fix.

**Comment by mingyu89** [comment]
@normanmaurer Thank you!
