### ISSUE TITLE
4.0.30.Final-SNAPSHOT - Test Errors

### ISSUE THREAD

**Issue by gitai** [netty/netty#4002]
Executing ‘mvn test’ in 4.0 branch root results with 1 error:

Mac OS 10.10.4 / JDK 8u45 / Maven 3.3.3 / Git 2.3.2  

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Netty .............................................. SUCCESS [01:56 min]
[INFO] Netty/Common ....................................... SUCCESS [ 52.834 s]
[INFO] Netty/Buffer ....................................... SUCCESS [ 15.103 s]
[INFO] Netty/Transport .................................... SUCCESS [ 54.274 s]
[INFO] Netty/Codec ........................................ SUCCESS [ 12.017 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  3.524 s]
[INFO] Netty/Handler ...................................... SUCCESS [ 18.533 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [  8.416 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  3.778 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  2.501 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  2.528 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [ 22.586 s]
[INFO] Netty/Example ...................................... SUCCESS [  4.101 s]
[INFO] Netty/Testsuite .................................... SUCCESS [16:48 min]
[INFO] Netty/Testsuite/OSGI ............................... FAILURE [ 24.074 s]
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/All-in-One ................................... SKIPPED
[INFO] Netty/Tarball ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22:40 min
[INFO] Finished at: 2015-07-18T14:16:27+03:00
[INFO] Final Memory: 105M/1104M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project netty-testsuite-osgi: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/xyz/dev/netty/testsuite-osgi/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-testsuite-osgi

-------------------------------------------------------------------------------
Test set: io.netty.osgitests.OsgiBundleTest
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.819 sec <<< FAILURE! - in io.netty.osgitests.OsgiBundleTest
testResolvedBundles(io.netty.osgitests.OsgiBundleTest)  Time elapsed: 4.583 sec  <<< ERROR!
java.io.IOException: Error resolving artifact io.netty:netty-buffer:jar:4.0.30.Final-SNAPSHOT: Could not find artifact io.netty:netty-buffer:jar:4.0.30.Final-SNAPSHOT
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:355)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolveFile(AetherBasedResolver.java:313)
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:297)
	at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:131)
	at org.apache.felix.framework.util.SecureAction.getURLConnectionInputStream(SecureAction.java:525)
	at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:166)
	at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:77)
	at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:878)
	at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550)
	at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153)
	at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2943)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:169)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:142)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:308)
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:177)
	at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:267)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:98)
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

**Comment by normanmaurer** [comment]
Try 

mvn clean install

**Comment by gitai** [comment]
Thanks. Look OK now.. 'mvn clean install' completed without errors so as a subsequent 'mvn test' 
though I checked out a branch of netty-4.0.29.Final tag beforehand and 'mvn test' worked right out of the box…
