### ISSUE TITLE
Error using Netty SPDY with jdk1.8

### ISSUE THREAD

**Issue by allnash** [netty/netty#4064]
java.lang.ExceptionInInitializerError: 
     io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:232)
     io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:161)
     io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:399)
     io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:219)

Java code
 // Configure SSL.
        SelfSignedCertificate ssc = new SelfSignedCertificate();
        SslContext sslCtx = SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey())
            .applicationProtocolConfig(new ApplicationProtocolConfig(
                        Protocol.ALPN, // <---- FAILS HERE 
                        // NO_ADVERTISE is currently the only mode supported by both OpenSsl and JDK providers.
                        SelectorFailureBehavior.NO_ADVERTISE,
                        // ACCEPT is currently the only mode supported by both OpenSsl and JDK providers.
                        SelectedListenerFailureBehavior.ACCEPT,
                        ApplicationProtocolNames.SPDY_3_1,
                        ApplicationProtocolNames.HTTP_1_1))
            .build();

        // Configure the server.
        EventLoopGroup bossGroup = new NioEventLoopGroup(1);
        EventLoopGroup workerGroup = new NioEventLoopGroup();

**Comment by Scottmitch** [comment]
@allnash - Does your full exception look something like this:

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.netty.handler.ssl.JdkSslContext.toNegotiator(JdkSslContext.java:252)
	at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:162)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:399)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:219)
	at io.netty.example.spdy.server.SpdyServer.main(SpdyServer.java:69)
Caused by: java.lang.RuntimeException: NPN unsupported. Is your classpatch configured correctly? See http://www.eclipse.org/jetty/documentation/current/npn-chapter.html#npn-starting
	at io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator$1.<init>(JdkNpnApplicationProtocolNegotiator.java:27)
	at io.netty.handler.ssl.JdkNpnApplicationProtocolNegotiator.<clinit>(JdkNpnApplicationProtocolNegotiator.java:24)
	... 5 more
```

If so you are attempting to use the java ssl provider and you should reference `https://wiki.eclipse.org/Jetty/Feature/NPN` for how to configure your bootclaspath.  Please let me know if this fixes your issue.

**Comment by allnash** [comment]
Ok I'll give it a try.

Thanks,
Nash

**Comment by Scottmitch** [comment]
@allnash - I'll close this for now. Please re-open if there is still an issue.
