### ISSUE TITLE
NPE in DnsNameResolver in conjunction with a negative caching policy

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#4065]
There is a NPE in the DnsNameResolver if a negative caching policy is being used and the hostname doesn't resolve.

See attached unit test (feel free to copy it).

Netty: 4.1-Beta6-SNAPSHOT

```
public class NegativeTtlTest {

  @Test
  public void negativeTtlNPE() {
    
    EventLoopGroup group = new NioEventLoopGroup();
    
    try (DnsNameResolver resolver = new DnsNameResolver(
        group.next(), 
        NioDatagramChannel.class, 
        DnsServerAddresses.defaultAddresses())) {
      
      resolver.setNegativeTtl(10);
      
      String hostname = "example.com.netty.io";
      
      // The above hostname doesn't resolve. It's expected but 
      // in conjunction with the negative TTL caching policy it's
      // ending up caching a null value which in turn yields in
      // a NPE on the next lookup.
      try {
        resolver.resolve(hostname, 0)
          .syncUninterruptibly();
        
      } catch (Exception expected) {
        if (!(expected instanceof UnknownHostException)) {
          // We didn't expect this one!
          throw expected;
        }
      }
      
      // NPE!
      resolver.resolve(hostname, 0)
        .syncUninterruptibly();
      
    } finally {
      group.shutdownGracefully();
    }
  }
}
```

```
java.lang.NullPointerException
	at io.netty.resolver.dns.DnsCacheEntry.retainedResponse(DnsCacheEntry.java:65)
	at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:696)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:120)
	at io.netty.resolver.dns.DnsNameResolverContext.resolve(DnsNameResolverContext.java:109)
	at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:650)
	at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:69)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:133)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:99)
	at NegativeTtlTest.negativeTtlNPE(NegativeTtlTest.java:47)
```

**Comment by Scottmitch** [comment]
@trustin - I will assign to you for now.

**Comment by trustin** [comment]
@rkapsi I've just pushed a major update related with `DnsNameResolver` which might fix this issue as well as other known issues. Could you please try again with the latest snapshot build?

**Comment by trustin** [comment]
@rkapsi I have just added a new test case for negative cache: ad0b7ca56db391248c95ff2c0e24793cc3a4d9d5 and it seems to work fine now.

**Comment by rkapsi** [comment]
@trustin the attached Unit Test (see above) is now failing with:

```
[nioEventLoopGroup-2-1] WARN io.netty.util.concurrent.DefaultPromise - An exception was thrown by io.netty.resolver.dns.DnsNameResolverContext$2.operationComplete()
java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:854)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:344)
	at io.netty.resolver.dns.DnsNameResolverContext$2.operationComplete(DnsNameResolverContext.java:150)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:567)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:184)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:167)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:998)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:94)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:699)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by trustin** [comment]
#4099 should solve this problem fundamentally. Please review.
