### ISSUE TITLE
Force-closing a channel whose registration task was not accepted by an event loop

### ISSUE THREAD

**Issue by Unisay** [netty/netty#4067]
Sometimes Netty terminates connection abruptly with this stacktrace:
```
18:38:46.904 [nioEventLoopGroup-34-1] WARN  io.netty.channel.AbstractChannel - Force-closing a channel whose registration task was not accepted by an event loop: [id: 0xcfbdfd31, /127.0.0.1:36412 => /127.0.0.1:8888]
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:707) ~[netty-common-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:299) ~[netty-common-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:690) ~[netty-common-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:421) ~[netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:60) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:48) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.MultithreadEventLoopGroup.register(MultithreadEventLoopGroup.java:64) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:251) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111) [netty-common-4.0.29.Final.jar:4.0.29.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.29.Final.jar:4.0.29.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_51]
[
```
I am at Ubuntu 14.10, Java build 1.8.0_51-b16

**Comment by Scottmitch** [comment]
@Unisay - A channel is attempted to be registered to an event loop that has been shutdown, thus the registration fails and the channel is closed. I take it that you are requesting that this behavior (channel is closed) changes? If so, do you have any suggestions. If not can you explain the issue?

Why is the event loop being shutdown?

**Comment by Unisay** [comment]
@Scottmitch 
Unfortunately I have only rough idea of what is "channel registration" and "event loop".

In my integration tests I use mockserver-netty. For every test (sequentially) I start and stop mockserver (which starts-stops netty). Sometimes start happens just after it has been stopped. I can provide more detailed logs of netty a bit later.

**Comment by normanmaurer** [comment]
@Unisay basically this means you try to register no channels to a EventLoopGroup after it was shutdown. There is nothing we can do about this. It's kind of the same like shutdown a ExecutorService and calling execute(Runnable) after it.
