### ISSUE TITLE
netty  java.lang.UnsupportedOperationException: libsctp.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by molele2** [netty/netty#4090]
I try netty-all-4.0.30.Final.jar netty-all-4.0.25.Final.jar  for storm test,The test have some error:

21966 [Thread-15] ERROR org.apache.storm.zookeeper.server.NIOServerCnxnFactory - Thread Thread[Thread-15,5,main] died
io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.sctp.nio.NioSctpServerChannel
	at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:457) ~[nettycloud.jar:na]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:308) ~[nettycloud.jar:na]
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:273) ~[nettycloud.jar:na]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:269) ~[nettycloud.jar:na]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:244) ~[nettycloud.jar:na]
	at com.warunion.spouts.netty.NettySpout$1.run(NettySpout.java:70) ~[nettycloud.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_71]
Caused by: java.lang.UnsupportedOperationException: libsctp.so.1: cannot open shared object file: No such file or directory
	at sun.nio.ch.SctpNet.socket0(Native Method) ~[na:1.7.0_71]
	at sun.nio.ch.SctpNet.socket(SctpNet.java:90) ~[na:1.7.0_71]
	at sun.nio.ch.SctpServerChannelImpl.<init>(SctpServerChannelImpl.java:89) ~[na:1.7.0_71]
	at com.sun.nio.sctp.SctpServerChannel.open(SctpServerChannel.java:101) ~[na:1.7.0_71]
	at io.netty.channel.sctp.nio.NioSctpServerChannel.newSocket(NioSctpServerChannel.java:53) ~[nettycloud.jar:na]
	at io.netty.channel.sctp.nio.NioSctpServerChannel.<init>(NioSctpServerChannel.java:66) ~[nettycloud.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_71]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[na:1.7.0_71]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.7.0_71]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[na:1.7.0_71]
	at java.lang.Class.newInstance(Class.java:379) ~[na:1.7.0_71]
	at io.netty.bootstrap.AbstractBootstrap$BootstrapChannelFactory.newChannel(AbstractBootstrap.java:455) ~[nettycloud.jar:na]
	... 6 common frames omitted

**Comment by Scottmitch** [comment]
Do you have libsctp.so in you LD_LIBRARY_PATH or LD_PRELOAD environment variables?

**Comment by normanmaurer** [comment]
@molele2 I guess you have not installed the correct libraries ?

Check the Getting started here:
http://openjdk.java.net/projects/sctp/html/gettingstarted.html

**Comment by normanmaurer** [comment]
if you still have issues please reopen
