### ISSUE TITLE
Internal MpscLinkedQueue hangs on high frequency operations

### ISSUE THREAD

**Issue by wumo** [netty/netty#4110]
Netty version: 4.0.30.Final

Context: when I write some benchmark codes to compare MpscLinkedQueue impmented in Netty internal with the one in JCTools, I find MpscLinkedQueue in Netty hangs on high frequency operations(add/peek/poll).

code to reproduce:
```java
public class Benchmark {
    @Test
    public void testNettyMpscQueue() throws InterruptedException {
        testMpscQueue(PlatformDependent.<Integer>newMpscQueue());
    }

    @Test
    public void testJCToolsMpscQueue() throws InterruptedException {
        testMpscQueue(QueueFactory.newQueue(new ConcurrentQueueSpec(0, 1, 0, Ordering.FIFO, Preference.NONE)));
    }

    public void testMpscQueue(Queue<Integer> queue) throws InterruptedException {
        int nThreads = 4;
        ExecutorService executor = Executors.newFixedThreadPool(nThreads);
        CountDownLatch latch = new CountDownLatch(nThreads);
        AtomicBoolean loc = new AtomicBoolean(false);
        long start = System.nanoTime();
        long due = 1000000000L;
        for (int i = 0; i < nThreads; i++)
            executor.submit(() -> {
                Random rand = new Random(System.nanoTime());
                while ((System.nanoTime() - start) < due) {//terminate in short time
                    if (rand.nextBoolean()) {//add element or try to consume one
                        queue.add(1);
                    } else {
                        Integer num = queue.peek();
                        if (num != null && loc.compareAndSet(false, true)) {//make sure only one consumer
                            num = queue.poll();
                            loc.set(false);
                        }
                    }
                }
                latch.countDown();
            });

        latch.await();
    }
}
```

Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\wumo>java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by wumo** [comment]
The thread dumps shows below:
```java
"pool-1-thread-4" #15 prio=5 os_prio=0 tid=0x0000000019491800 nid=0x2580 runnable [0x0000000019fbe000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.internal.MpscLinkedQueue.peekNode(MpscLinkedQueue.java:109)
	at io.netty.util.internal.MpscLinkedQueue.peek(MpscLinkedQueue.java:156)
	at test.Benchmark.lambda$testMpscQueue$0(Benchmark.java:46)
	at test.Benchmark$$Lambda$1/1521118594.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(Redefined)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Redefined)
	at java.lang.Thread.run(Thread.java:745)

"pool-1-thread-3" #14 prio=5 os_prio=0 tid=0x0000000019490800 nid=0x15a4 waiting on condition [0x0000000019ebe000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000081f09368> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Redefined)
	at java.lang.Thread.run(Thread.java:745)

"pool-1-thread-2" #13 prio=5 os_prio=0 tid=0x0000000019490000 nid=0x1448 runnable [0x0000000019dbe000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.internal.MpscLinkedQueue.peekNode(MpscLinkedQueue.java:109)
	at io.netty.util.internal.MpscLinkedQueue.peek(MpscLinkedQueue.java:156)
	at test.Benchmark.lambda$testMpscQueue$0(Benchmark.java:46)
	at test.Benchmark$$Lambda$1/1521118594.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(Redefined)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Redefined)
	at java.lang.Thread.run(Thread.java:745)

"pool-1-thread-1" #12 prio=5 os_prio=0 tid=0x00000000194a8000 nid=0x1494 runnable [0x0000000019cbe000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.internal.MpscLinkedQueue.peekNode(MpscLinkedQueue.java:109)
	at io.netty.util.internal.MpscLinkedQueue.peek(MpscLinkedQueue.java:156)
	at test.Benchmark.lambda$testMpscQueue$0(Benchmark.java:46)
	at test.Benchmark$$Lambda$1/1521118594.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(Redefined)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Redefined)
	at java.lang.Thread.run(Thread.java:745)
```
3 of the 4 threads are running on peekNode(MpscLinkedQueue.java) method. maybe the peekNode() has some problem.

**Comment by normanmaurer** [comment]
@trustin will you check or should I take care ?

**Comment by trustin** [comment]
@normanmaurer Please take care. Stuck with other stuff at the moment.

**Comment by normanmaurer** [comment]
@trustin will do... this sounds like a critical bug.

**Comment by normanmaurer** [comment]
Sorry was very busy over the last days. Will try to work on it tomorrow first

**Comment by normanmaurer** [comment]
@wumo actually this is a bug in our javadocs. peek() MUST only be used by a single consumer to work correctly. Let me fix it.

The only methods that are safe to call from multiple threads are:
 - offer(...), add(...), addAll(...), isEmpty()

**Comment by wumo** [comment]
@normanmaurer well, that would explain it. Thx!

**Comment by normanmaurer** [comment]
@wuma let me fix the javadocs

**Comment by normanmaurer** [comment]
Fixed javadocs
