### ISSUE TITLE
SslHandshakeCompletionEvent not fired for all ssl handlers

### ISSUE THREAD

**Issue by isbo** [netty/netty#4135]
Our server serves SSL connections on two different ports (4433 and 4435 in the logs below). We initialize netty OpenSsl SslContext for each with separate certs/keys/etc. However, it seems that the SslHandshakeCompletionEvent event is fired for channels associated with only one of the contexts - specifically the one that was initialized last. This behavior doesn't line up with the documentation of SslHandshakeCompletionEvent. Is this a bug?

We are using netty 4.0.25.Final with netty-tcnative:1.1.32.Fork1. 

2015-08-26 08:22:45.398 [nioEventLoopGroup-3-15] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x24b2dfd2, /x.x.x.x:31104 => /x.x.x.x:4433] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
2015-08-26 08:22:45.404 [nioEventLoopGroup-3-5] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x359bcfc8, /x.x.x.x:53150 => /x.x.x.x:4435] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2015-08-26 08:22:45.404 [nioEventLoopGroup-3-5] INFO com.example.HttpRequestHandler - [id: 0x359bcfc8, /x.x.x.x:53150 => /x.x.x.x:4435]got ssl success event

**Comment by normanmaurer** [comment]
Thats very strange... Coukd you try upgrading netty and if you still see the issue share a reproducer?

**Comment by isbo** [comment]
upgrade to 4.0.30.Final? or higher?

**Comment by Scottmitch** [comment]
@isbo - 4.0.30.Final is the latest release for 4.0.  I suggest starting there.

netty-tcnative also has a newer version [netty-tcnative : 1.1.33.Fork5](http://search.maven.org/#artifactdetails%7Cio.netty%7Cnetty-tcnative%7C1.1.33.Fork5%7Cjar). Is it possible for you to updated to this too?

**Comment by isbo** [comment]
I upgraded to 4.0.30.Final and  netty-tcnative : 1.1.33.Fork5. Still seeing the same behavior.

Also noticed a new exception in the logs - which probably is a separate issue:
Caused by: java.lang.NoSuchMethodError: org.apache.tomcat.jni.SSL.clearError()V
        at io.netty.handler.ssl.OpenSslEngine.shutdown(OpenSslEngine.java:263)
        at io.netty.handler.ssl.OpenSslEngine.closeInbound(OpenSslEngine.java:811)
        at io.netty.handler.ssl.OpenSslEngine.closeAll(OpenSslEngine.java:772)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:720)
        at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:791)
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1129)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1019)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:959)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
        ... 18 common frames omitted

**Comment by Scottmitch** [comment]
@isbo - `clearError()` was added by https://github.com/netty/netty-tcnative/commit/7d603d9b1f322d37a6b00eb8c9213d13fcd7d776 which should be in 1.1.33.Fork3 (and later).

**Comment by isbo** [comment]
Thanks for noticing that - turns out I only upgraded the .so but not the jar. Fixed and the error went away.

**Comment by isbo** [comment]
Hi @trustin why is this not considered a bug? I can repro it on the latest netty 4.0 stable and tcnative as  suggested by @normanmaurer.

**Comment by trustin** [comment]
Ugh, I misread the thread. Let me relabel it.

**Comment by Scottmitch** [comment]
@isbo - Thanks for upgrading and verifying the issue still exists. Could you share a reproducer?

**Comment by normanmaurer** [comment]
@isbo once I have a reproducer I can look into it.

**Comment by isbo** [comment]
thanks guys, i will try to get a repro program in a day or two.

**Comment by normanmaurer** [comment]
@isbo any news ?

**Comment by normanmaurer** [comment]
@isbo ping

**Comment by isbo** [comment]
@normanmaurer apologies for the late reply. I was unable to repro this issue with a reproducer that tries to mimic what we do in production: https://gist.github.com/isbo/f36de422ac4b661cb689.

Which strongly suggests to me that the problem must have been somewhere in our code. Anyway, this is a non-issue for us since we are now terminating one of the ssl endpoints further upstream. Please feel free to close. Thanks!

**Comment by isbo** [comment]
I forgot that I only tried to repro on my laptop (mac) not on Linux. Let me try it there just to be sure since tcnative is involved.

**Comment by normanmaurer** [comment]
Let me close this and please reopen if you think this is still an issue and can provide more details
