### ISSUE TITLE
unable to compile branch 4.0

### ISSUE THREAD

**Issue by lokeshhctm** [netty/netty#4151]
00:33:09.425 [main] WARN  o.o.p.u.m.i.AetherBasedResolver - Error resolving artifactio.netty:netty-transport-sctp:jar:4.0.31.Final-SNAPSHOT:Could not find artifact io.netty:netty-transport-sctp:jar:4.0.31.Final-SNAPSHOT
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact io.netty:netty-transport-sctp:jar:4.0.31.Final-SNAPSHOT
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444) ~[pax-url-aether-2.2.0.jar:na]
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246) ~[pax-url-aether-2.2.0.jar:na]
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223) ~[pax-url-aether-2.2.0.jar:na]
	at shaded.org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294) ~[pax-url-aether-2.2.0.jar:na]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:344) [pax-url-aether-2.2.0.jar:na]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolveFile(AetherBasedResolver.java:313) [pax-url-aether-2.2.0.jar:na]
	at org.ops4j.pax.url.mvn.internal.AetherBasedResolver.resolve(AetherBasedResolver.java:297) [pax-url-aether-2.2.0.jar:na]
	at org.ops4j.pax.url.mvn.internal.Connection.getInputStream(Connection.java:131) [pax-url-aether-2.2.0.jar:na]
	at org.apache.felix.framework.util.SecureAction.getURLConnectionInputStream(SecureAction.java:525) [org.apache.felix.framework-4.6.0.jar:na]
	at org.apache.felix.framework.cache.JarRevision.initialize(JarRevision.java:166) [org.apache.felix.framework-4.6.0.jar:na]
	at org.apache.felix.framework.cache.JarRevision.<init>(JarRevision.java:77) [org.apache.felix.framework-4.6.0.jar:na]
	at org.apache.felix.framework.cache.BundleArchive.createRevisionFromLocation(BundleArchive.java:878) [org.apache.felix.framework-4.6.0.jar:na]
	at org.apache.felix.framework.cache.BundleArchive.reviseInternal(BundleArchive.java:550) [org.apache.felix.framework-4.6.0.jar:na]
	at org.apache.felix.framework.cache.BundleArchive.<init>(BundleArchive.java:153) [org.apache.felix.framework-4.6.0.jar:na]
	at org.apache.felix.framework.cache.BundleCache.create(BundleCache.java:277) [org.apache.felix.framework-4.6.0.jar:na]
	at org.apache.felix.framework.Felix.installBundle(Felix.java:2943) [org.apache.felix.framework-4.6.0.jar:na]
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:169) [org.apache.felix.framework-4.6.0.jar:na]
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:142) [org.apache.felix.framework-4.6.0.jar:na]
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:308) [pax-exam-container-native-4.4.0.jar:na]
	at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:177) [pax-exam-container-native-4.4.0.jar:na]
	at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79) [pax-exam-spi-4.4.0.jar:na]
	at org.ops4j.pax.exam.junit.impl.ProbeRunner$2.evaluate(ProbeRunner.java:267) [pax-exam-junit4-4.4.0.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) [junit-4.12.jar:4.12]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) [junit-4.12.jar:4.12]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363) [junit-4.12.jar:4.12]
	at org.ops4j.pax.exam.junit.impl.ProbeRunner.run(ProbeRunner.java:98) [pax-exam-junit4-4.4.0.jar:na]
	at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:93) [pax-exam-junit4-4.4.0.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264) [surefire-junit4-2.15.jar:2.15]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.15.jar:2.15]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124) [surefire-junit4-2.15.jar:2.15]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200) [surefire-booter-2.15.jar:2.15]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) [surefire-booter-2.15.jar:2.15]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.15.jar:2.15]
Caused by: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact io.netty:netty-transport-sctp:jar:4.0.31.Final-SNAPSHOT
	at shaded.org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:434) ~[pax-url-aether-2.2.0.jar:na]

**Comment by Scottmitch** [comment]
Have you configured your build to pull from sonatype's snapshot repo?

https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-transport-sctp/4.0.31.Final-SNAPSHOT/

**Comment by lokeshhctm** [comment]
Can you please describe where i can configure and how?

**Comment by Scottmitch** [comment]
@lokeshhctm - It depends upon your build tool. We generally support maven and checkout http://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository for 1 way to configure maven to pull from sonatype snapshot repo.

**Comment by normanmaurer** [comment]
@lokeshhctm ensure you use maven >= 3.2.1. This should work....
