### ISSUE TITLE
HttpProxyHandler has runtime dependency on Java 1.7

### ISSUE THREAD

**Issue by dgrabows** [netty/netty#4180]
As of 4.1.0.Beta5, io.netty.handler.proxy.HttpProxyHandler has a runtime dependency on Java 1.7+. The download page (http://netty.io/downloads.html) indicates that Java 1.6 is the minimum version supported for Netty 4.X.

The issue appears to be references to java.net.InetSocketAddress.getHostString() in HttpProxyHandler ([here](https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/HttpProxyHandler.java#L117) and [here](https://github.com/netty/netty/blob/4.1/handler-proxy/src/main/java/io/netty/handler/proxy/HttpProxyHandler.java#L130)). getHostString() was introduced in Java 1.7 (http://docs.oracle.com/javase/7/docs/api/java/net/InetSocketAddress.html#getHostString()).

When running on Java 1.6, an example stack trace is:

    Caused by: java.lang.IllegalAccessError: tried to access method java.net.InetSocketAddress.getHostString()Ljava/lang/String; from class io.netty.handler.proxy.HttpProxyHandler
    	at io.netty.handler.proxy.HttpProxyHandler.newInitialMessage(HttpProxyHandler.java:130)
    	at io.netty.handler.proxy.ProxyHandler.sendInitialMessage(ProxyHandler.java:208)
    	at io.netty.handler.proxy.ProxyHandler.channelActive(ProxyHandler.java:187)
    	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelActiveNow(ChannelHandlerInvokerUtil.java:48)
    	... 24 more

**Comment by Scottmitch** [comment]
@trustin - Would you mind taking this one?

**Comment by normanmaurer** [comment]
@dgrabows actually only the "core" has java 1.6 as minimum. Codecs may needed higher java versions. Closing this.
