### ISSUE TITLE
HttpResponseEncoder removes itself prematurely (?)

### ISSUE THREAD

**Issue by timboudreau** [netty/netty#4181]
In the [netty-5 branch of Acteur](https://github.com/timboudreau/acteur/tree/netty-5), some tests are failing, with the stack trace entirely in Netty code, claiming that `DefaultFullHttpResponse` is not a message type that can be decoded.

Is the HttpResponseEncoder somehow getting removed from the pipeline prematurely?

Interestingly, HTTP POSTs seem to work, but GETs do not (I am not 100% sure all POSTs work, just one in the test in question) - something in the special handling for allowing a 100-Continue response first?

This started sometime in June with 5.0.0-Alpha3 - I just built it from master to test if this problem is still here.

	testGets(com.mastfrog.acteur.ComprehensiveTest)  Time elapsed: 0.414 sec  <<< ERROR!
	java.lang.UnsupportedOperationException: unsupported message type: DefaultFullHttpResponse (expected: ByteBuf, FileRegion)
		at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:256)
		at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:801)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1286)
		at io.netty.channel.ChannelHandlerInvokerUtil.invokeWriteNow(ChannelHandlerInvokerUtil.java:157)
		at io.netty.channel.DefaultChannelHandlerInvoker.invokeWrite(DefaultChannelHandlerInvoker.java:337)
		at io.netty.channel.PausableChannelEventExecutor.invokeWrite(PausableChannelEventExecutor.java:132)
		at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:483)
		at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:491)
		at io.netty.handler.codec.MessageAggregator.decode(MessageAggregator.java:222)
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89)
		at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
		at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
		at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
		at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
		at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
		at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:359)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:955)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
		at io.netty.util.concurrent.SingleThreadEventExecutor$3.run(SingleThreadEventExecutor.java:131)
		at java.lang.Thread.run(Thread.java:745)

**Comment by Scottmitch** [comment]
Is this for a client or server use case?  Are there any protocol upgrades anticipated?

> Is the HttpResponseEncoder somehow getting removed from the pipeline prematurely?

@timboudreau - Would you be able to verify if this is the case?

**Comment by timboudreau** [comment]
Server use case, no protocol upgrades.

Re removal from the pipeline - I suppose I could implement a wrapper Pipeline that logs adds/removes, but that might not be trivial.

**Comment by timboudreau** [comment]
The root of the problem is the `100-CONTINUE` response from HttpObjectAggregator.  Workaround is to change it `newContinueResponse()` to return a ByteBuf, not a DefaultFullHttpResponse.

So maybe the problem is the order of the aggregator in the pipeline?  But then, what changed, since it worked before?

**Comment by timboudreau** [comment]
Workaround [diff here](https://github.com/timboudreau/acteur/commit/d8b6cb3c2fd8def902a210a4161e385577070a46#diff-db7d1b77c0239cf610c56a059a0ee459R209)

**Comment by Scottmitch** [comment]
@timboudreau - Thanks for pointing this out and demonstrating a work around. It appears the `HttpObjectAggregator` has been writing a `FullHttpMessage` since 2013 https://github.com/netty/netty/commit/3444c0665490bfbd3fd100146a11736de9d58d36.

> So maybe the problem is the order of the aggregator in the pipeline?

Makes sense since the write operation is going to walk backwards in the pipeline.  Have you tried putting `HttpResponseEncoder` (or `HttpServerCodec`) before the `HttpObjectAggregator`?

**Comment by timboudreau** [comment]
Yup, changing the order of the HttpResponseEncoder solves the problem.

The mystery is why it ever worked.
