### ISSUE TITLE
Netty-4.1.0-Beta6: OpenSSL seems broken (NoSuchMethodError: org.apache.tomcat.jni.SSL.newMemBIO())

### ISSUE THREAD

**Issue by mubarak** [netty/netty#4183]
Netty version: Netty-4.1.0-Beta6

Context: When i use Netty-4.1.0-Beta6 with OpenSSL as SSL engine, i am getting 

```
Sep 02 22:39:45 rest-standalone docker[13210]: Exception in thread "main" java.lang.NoSuchMethodError: org.apache.tomcat.jni.SSL.newMemBIO()J
Sep 02 22:39:45 rest-standalone docker[13210]: at io.netty.handler.ssl.OpenSslContext.newBIO(OpenSslContext.java:512)
Sep 02 22:39:45 rest-standalone docker[13210]: at io.netty.handler.ssl.OpenSslContext.toBIO(OpenSslContext.java:505)
Sep 02 22:39:45 rest-standalone docker[13210]: at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:439)
Sep 02 22:39:45 rest-standalone docker[13210]: at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:406)
Sep 02 22:39:45 rest-standalone docker[13210]: at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:306)
```

```
root@7e4c24294fc6:/# java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

Operating system:
```
uname -a
Linux 7e4c24294fc6 3.18.6 #2 SMP Sat Feb 28 02:23:04 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

There is a shared library at `/tmp`:
```
-rw-r--r-- 1 root root 1078878 Sep  2 22:42 libnetty-tcnative7267949618399486662.so
```

**Comment by normanmaurer** [comment]
@mubarak you need to use netty-tcnative version 1.1.33.Fork6.

**Comment by doom369** [comment]
@normanmaurer sorry, was a bit busy. Tried latest 4.0.32.Final and 1.1.33.Fork8 - works like a charm. Thank you!
