### ISSUE TITLE
NullPointer @     at io.netty.buffer.PoolChunk.initBufWithSubpage

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4198]
out of nowhere...

Caused by: java.lang.NullPointerException
    at io.netty.buffer.PoolChunk.initBufWithSubpage(PoolChunk.java:381)
    at io.netty.buffer.PoolChunk.initBufWithSubpage(PoolChunk.java:369)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:194)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:132)
    at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262)
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:157)
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:148)
    at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:101)
    at io.netty.handler.codec.MessageToByteEncoder.allocateBuffer(MessageToByteEncoder.java:140)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:105)
    ... 39 more

netty 4.1 beta 6

**Comment by normanmaurer** [comment]
Will check... Any special setting?

**Comment by normanmaurer** [comment]
@ninja- ^^

**Comment by normanmaurer** [comment]
@ninja- also very strange as this means the `buf` was null. I see no way how this can happen :/

**Comment by ninja-** [comment]
@normanmaurer :/ have I written a null by any chance?

**Comment by normanmaurer** [comment]
@ninja- no... Let me think a bit about it but at the moment I'm not sure how this ever could happen.

**Comment by ninja-** [comment]
@normanmaurer that was my fault, sorry for the problem. if you are wondering I had my reference counted object and the counter wasn't thread safe (volatile wasn't enough, needed to change to AtomicInteger...)

**Comment by Scottmitch** [comment]
@ninja- - Is this a custom `ReferenceCounted` object, or one of Netty's?

**Comment by ninja-** [comment]
@Scottmitch a custom one

**Comment by merlimat** [comment]
I'm seeing the same exact NPE stack trace on netty-4.0.32 (and on previous versions).

```
00:05:11.766 [BookKeeperClientWorker-6-0] ERROR o.a.bookkeeper.util.SafeRunnable     - Unexpected throwable caught 
java.lang.NullPointerException: null
        at io.netty.buffer.PoolChunk.initBufWithSubpage(PoolChunk.java:381) ~[netty-all-4.0.32.Final.jar:4.0.32.Final]
        at io.netty.buffer.PoolChunk.initBufWithSubpage(PoolChunk.java:369) ~[netty-all-4.0.32.Final.jar:4.0.32.Final]
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:194) ~[netty-all-4.0.32.Final.jar:4.0.32.Final]
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:132) ~[netty-all-4.0.32.Final.jar:4.0.32.Final]
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:271) ~[netty-all-4.0.32.Final.jar:4.0.32.Final]
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155) ~[netty-all-4.0.32.Final.jar:4.0.32.Final]
        at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.insert(EntryCacheImpl.java:102) ~[managed-ledger-0.1.jar:na]
        at org.apache.bookkeeper.mledger.impl.EntryCacheImpl.lambda$asyncReadEntry$38(EntryCacheImpl.java:244) ~[managed-ledger-0.1.jar:na]
        at org.apache.bookkeeper.client.PendingReadOp.submitCallback(PendingReadOp.java:402) ~[bookkeeper-server-4.3.1.33.jar:4.3.1]
        at org.apache.bookkeeper.client.PendingReadOp.readEntryComplete(PendingReadOp.java:377) ~[bookkeeper-server-4.3.1.33.jar:4.3.1]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadCompletion$1.readEntryComplete(PerChannelBookieClient.java:1131) ~[bookkeeper-server-4.3.1.33.jar:4.3.1]
        at org.apache.bookkeeper.proto.PerChannelBookieClient.handleReadResponse(PerChannelBookieClient.java:1067) ~[bookkeeper-server-4.3.1.33.jar:4.3.1]
        at org.apache.bookkeeper.proto.PerChannelBookieClient$ReadV2ResponseCallback.safeRun(PerChannelBookieClient.java:926) ~[bookkeeper-server-4.3.1.33.jar:4.3.1]
        at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:31) ~[bookkeeper-server-4.3.1.33.jar:4.3.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
```

Multiple times, I've been getting a NPE with empty stack trace, that I've been finally able to track down to the same `allocator.directBuffer()` call.

From comments above, I cannot understand how an error in handling these buffer could result in this NPE. 

I know that if I have some thread holding on a buffer, and then this buffer goes back to pool it may be possible that these buffer and the ByteBuf instance to be reused. In this case the first thread can get either 2 conditions: 
 1. Touch/Read an invalid buffer (refCnt==0) and that should throw exception
 2. Use the ByteBuf after it has been recycled. Probably lead to seeing corrupted data but ByteBuf should not throw exception

So far I haven't seen any refCnt exception or any data corruption. Still, I don't understand how either case should cause NPE.

Any clues / suggestions?

**Comment by normanmaurer** [comment]
@merlimat can I somehow reproduce it ?

**Comment by normanmaurer** [comment]
@merlimat do you run with assert's enabled ?

**Comment by normanmaurer** [comment]
@merlimat also could you tell me what previous versions you tried ?

**Comment by normanmaurer** [comment]
@merlimat @ninja- good news (well at least kind of) ! I'm able to reproduce it with a unit test. Looking into fixing it now.

**Comment by merlimat** [comment]
@normanmaurer great! Tell me if I can help testing it

**Comment by ninja-** [comment]
@normanmaurer oh that's nice. from what I remember the issue was improper reference counting on my side, but after fixing it I don't think I encountered it again

**Comment by normanmaurer** [comment]
Sure will do :)

**Comment by normanmaurer** [comment]
@merlimat can you please verify https://github.com/netty/netty/pull/4388 ?

**Comment by merlimat** [comment]
@normanmaurer Sorry for delay. Tested with real-ish traffic, 48 threads hitting a single arena for many hours and looks like everything worked great. Thanks!

**Comment by normanmaurer** [comment]
@merlimat :tada: thanks!
