### ISSUE TITLE
How can I handle an ireglary closed connection ?

### ISSUE THREAD

**Issue by literadix** [netty/netty#4229]
Could you please help us and show how to handle IO exceptions? I have taken the TelnetServer example. It is working just fine. But if I close the client by killing the client connection, I get an error thrown which I can not catch:

java.io.IOException: Connection closed by remote client
    at sun.nio.ch.SocketDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:192)
    ...
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    ...

How can I catch this error, so it will not be shown in my logs. I have already handled the disconnection:

    /**
     * @see io.netty.channel.ChannelInboundHandlerAdapter#channelUnregistered(io.netty.channel.ChannelHandlerContext)
     */
    @Override
    public void channelUnregistered(final ChannelHandlerContext ctx) throws Exception {
        final String host = ((InetSocketAddress) ctx.channel().remoteAddress()).getAddress().getHostAddress();
        final int port = ((InetSocketAddress) ctx.channel().remoteAddress()).getPort();
        System.out.println(String.format("unregistered host:%s port:%d", host, port));

        super.channelUnregistered(ctx);
    }

I would be very nice if you could change the telnet server example.

Thank you very much in advice,

Maciej

relevant code: https://github.com/netty/netty/tree/master/example/src/main/java/io/netty/example/telnet

**Comment by literadix** [comment]
Bricks and Mortality: I have found a solution which was already there:

in TelnetServerHandler.java 

    @Override
    public void exceptionCaught(final ChannelHandlerContext ctx, final Throwable cause) {
        // cause.printStackTrace(); THIS WAS SHOWING THE EXCEPTION
        ctx.close();
    }

:+1:
