### ISSUE TITLE
Http2ConnectionHandler.onStreamError NullPointerException

### ISSUE THREAD

**Issue by blucas** [netty/netty#4240]
Netty Version: latest master (94bf412edbea73c0b1dbac4ada8919708c4f369e)

/cc @Scottmitch @nmittler 

The NPE is being generated because the ```ctx``` is ```null```.  I believe this is happening because ```Http2ConnectionHandler``` is setting ```ctx``` to ```null``` before triggering the ```onStreamClosed()``` and ```writeError()``` methods.  See below

1. Netty triggers ```Http2ConnectionHandler.channelInactive()``` [here](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L424)
2. ```Http2ConnectionHandler``` sets the flowControllers ```ctx``` to ```null``` [here](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L428)
3. ```Http2ConnectionHandler``` calls ```byteDecoder.channelInactive()``` [here](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L430)
4. Which in turn cancels any pending writes [here](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L93)
5. Each pending frame will try to trigger ```writeError``` [here](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L627)
6. ```writeError``` will call ```frame.error(ctx, cause)```, but ```ctx``` is ```null``` [here](https://github.com/netty/netty/blob/master/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L744)

```ctx``` in step 6 is ```null``` because step 2 was invoked prior to telling the ```byteDecoder``` that the channel is inactive (step 3).

BTW, the *real* exception that was thrown was ```io.netty.handler.codec.http2.Http2Exception$StreamException: Stream closed before write could take place``` - but this was masked because of the NPE.

I don't know the code well enough to provide a fix for this, so it is up to Scott and Nathan, unless it is as simple as executing step 3 before step 2.  Again, I wouldn't know the repercussions of doing something like that.

Stacktrace I received from the application:
```
11:59:08,437 ERROR [DefaultHttp2Connection] [epollEventLoopGroup-25-1] Caught RuntimeException from listener onStreamClosed.
java.lang.NullPointerException
        at io.netty.handler.codec.http2.Http2ConnectionHandler.onStreamError(Http2ConnectionHandler.java:620)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.onException(Http2ConnectionHandler.java:564)
        at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledData.error(DefaultHttp2ConnectionEncoder.java:335)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.writeError(DefaultHttp2RemoteFlowController.java:744)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.cancel(DefaultHttp2RemoteFlowController.java:627)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.cancel(DefaultHttp2RemoteFlowController.java:609)
        at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$2.onStreamClosed(DefaultHttp2RemoteFlowController.java:93)
        at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:263)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1143)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams$2.process(DefaultHttp2Connection.java:1090)
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.forEachActiveStream(DefaultHttp2Connection.java:1114)
        at io.netty.handler.codec.http2.DefaultHttp2Connection.forEachActiveStream(DefaultHttp2Connection.java:135)
        at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:231)
        at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:430)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:56)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:92)
        at io.netty.channel.PausableChannelEventExecutor.invokeChannelInactive(PausableChannelEventExecutor.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:337)
        at io.netty.channel.ChannelHandlerAdapter.channelInactive(ChannelHandlerAdapter.java:130)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:56)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:92)
        at io.netty.channel.PausableChannelEventExecutor.invokeChannelInactive(PausableChannelEventExecutor.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:337)
        at io.netty.channel.ChannelHandlerAdapter.channelInactive(ChannelHandlerAdapter.java:130)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:56)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:92)
        at io.netty.channel.PausableChannelEventExecutor.invokeChannelInactive(PausableChannelEventExecutor.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:337)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:307)
        at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:666)
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:56)
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:92)
        at io.netty.channel.PausableChannelEventExecutor.invokeChannelInactive(PausableChannelEventExecutor.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:337)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:937)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:706)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:343)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:257)
        at io.netty.util.concurrent.SingleThreadEventExecutor$3.run(SingleThreadEventExecutor.java:131)
        at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
        at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
        at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
        at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
        at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
        at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)
```

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler any takers ;) ?

**Comment by nmittler** [comment]
Yeah, I think we should just not set them to `null` ... ever :).  Especially not in `channelInactive`, that's just too early.  If we wanted to set them to `null`, `handlerRemoved` might be more appropriate.  @Scottmitch  WDYT?

**Comment by Scottmitch** [comment]
> Yeah, I think we should just not set them to null ... ever :).

Agreed. This is not necessary, and if is causing problems can be removed.

**Comment by nmittler** [comment]
Ok cool ... I'll send a PR out shortly.

**Comment by Scottmitch** [comment]
I have one pending now...but feel free to submit one if you want

**Comment by nmittler** [comment]
@Scottmitch seems easy enough ... might be faster if I do it (no legal involved) ... your call.

**Comment by Scottmitch** [comment]
@nmittler - Please feel free to remove the lines where the flow controller's channel handler context is set to null. Thanks!
