### ISSUE TITLE
java.io.IOException: readAddress() failed: Transport endpoint is not connected

### ISSUE THREAD

**Issue by ninja-** [netty/netty#4251]
(suddenly)

java.io.IOException: readAddress() failed: Transport endpoint is not connected
    at io.netty.channel.epoll.Native.newIOException(Native.java:133)
    at io.netty.channel.epoll.Native.ioResult(Native.java:149)
    at io.netty.channel.epoll.Native.readAddress(Native.java:290)
    at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:244)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:784)
    at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollRdHupReady(AbstractEpollChannel.java:339)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:337)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:253)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at java.lang.Thread.run(Thread.java:745)

is this supposed to fire as an exception in the channel?

**Comment by normanmaurer** [comment]
Yes it is expected to fire an exception and the close the channel if auto close is used.

**Comment by ninja-** [comment]
ok thanks

**Comment by hepin1989** [comment]
I encounter NPE sometimes,and don't know why,the version is 4.1.0-beta6

**Comment by normanmaurer** [comment]
@hepin1989 please not hijack the issue but create a new one showing the NPE and add as much infos as possible.

**Comment by hepin1989** [comment]
ok,then should we delete the comment here,for the NEP I really can not come up with some detail,it triggered channelActive,and before channelInactive,but when you call remoteAddr,it just return null.
