### ISSUE TITLE
un-catchable IOException when client hangs too early.

### ISSUE THREAD

**Issue by loolooyyyy** [netty/netty#4272]
## Environment: 
- netty 5.0.0 Alpha3
- use case: A socks server (from the examples, a little modified).
- Client is google-chrome-beta, latest on Fedora

## Scenario:
Chrome connects to netty's socks server, ask for a web page. the page begins loading but before it's fully loaded, chrome process is killed on the OS (or simply the tab in the browser is closed!) so the connection to netty from google is hang to early.

## The problem:
Netty, in it's loop which is out of user-code's control is still trying to read/write? to the hung socket. This raises an ugly IOException

```java
java.io.IOException: Connection reset by peer
    at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:192)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
    at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311)
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:853)
    at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:240)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:115)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:514)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:471)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:385)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:351)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
    at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
    at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
    at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706)
    at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661)
    at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)
```

**Comment by Scottmitch** [comment]
@loolooyyyy - Can you provide more details as to what you think the issue is and what you would expect in this situation? This sounds like expected behavior.

**Comment by loolooyyyy** [comment]
I think maybe there should be a way to catch that IOException, do something with it rather than having it raised. For instance have it delegated to a handler in channel's pipeline, and log it like "connection closed: .....". 

Right now, only the stacktrace is printed, nothing is being logged and the work around is to modify netty itself: `io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe` and put a try/catch in `read()`. Is there anyway to do it from my handler?

**Comment by Scottmitch** [comment]
@loolooyyyy - My mistake. I took a quick glance and thought this was getting propagated to `exceptionCaught` handler. Let me take another look :smile:

**Comment by Scottmitch** [comment]
@loolooyyyy - What commit are you on? Seems like the exception should be caught in [AbstractNioByteChannel$NioByteUnsafe.read](https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L136) and propegated up the pipeline in [AbstractNioByteChannel$NioByteUnsafe.handleReadException](https://github.com/netty/netty/blob/master/transport/src/main/java/io/netty/channel/nio/AbstractNioByteChannel.java#L87). Seems like you can quickly reproduce the issue...would you mind setting a break point in these areas and seeing if it is hitting this code?

**Comment by loolooyyyy** [comment]
I am terribly sorry for taking up you time for this! a had reviewed all my code, I really did! and didn't find anything. till now, that you pointed to the `catch` thing in the code it sounded strange if it wasn't working. (don't know why **now** but) ran a `grep stacktrace -iR * ' and yes it was one of my handlers.
(guilty as charged).

**Comment by Scottmitch** [comment]
@loolooyyyy - No problem. Thanks for reaching out and glad all is well in the world :wink:
