### ISSUE TITLE
SmartOS io.netty.channel.ChannelException

### ISSUE THREAD

**Issue by sigil66** [netty/netty#4286]
Trying to track this down on SmartOS:

```
Failed to set a channel option: [id: 0xbc4c59fa, /192.168.1.70:52373 => /192.168.1.80:8080]
io.netty.channel.ChannelException: java.net.SocketException: Invalid argument
    at io.netty.channel.socket.DefaultSocketChannelConfig.setTrafficClass(DefaultSocketChannelConfig.java:266)
    at io.netty.channel.socket.DefaultSocketChannelConfig.setOption(DefaultSocketChannelConfig.java:117)
    at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:238)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Invalid argument
    at sun.nio.ch.Net.setIntOption0(Native Method)
    at sun.nio.ch.Net.setSocketOption(Net.java:334)
    at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:179)
    at sun.nio.ch.SocketAdaptor.setIntOption(SocketAdaptor.java:281)
    at sun.nio.ch.SocketAdaptor.setTrafficClass(SocketAdaptor.java:378)
    at io.netty.channel.socket.DefaultSocketChannelConfig.setTrafficClass(DefaultSocketChannelConfig.java:264)
```

truss shows the failure here:

```
/12:    setsockopt(113, SOL_SOCKET, SO_SNDBUF, 0xFFFFFD7FEB9FDEB0, 4, SOV_DEFAULT) = 0
/12:    setsockopt(113, SOL_SOCKET, SO_RCVBUF, 0xFFFFFD7FEB9FDEB0, 4, SOV_DEFAULT) = 0
/12:    setsockopt(113, ipv6, 38, 0xFFFFFD7FEB9FDEB0, 4, SOV_DEFAULT) Err#22 EINVAL
```

JVM info:
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

JVM started with:
-Djava.net.preferIPv4Stack=true

Netty Version:
4.0.28.Final

**Comment by normanmaurer** [comment]
We just use the jdk api here. Not much we can do... Maybe setting the traffic class is not supported on smartos?

**Comment by sigil66** [comment]
Well there is IPV6 support in SmartOS. In this instance I don't have an IPV6 interface plumbed. I guess I am wondering why the option is still passed  when I "disable" IPV6 via the JVM Opt.

**Comment by normanmaurer** [comment]
@sigil66 I think we fixed this recently. Please test again with latest version and reopen if you still see the problem.

**Comment by normanmaurer** [comment]
Let me close this as there was no activity for a long time and as stated I think we fixed it
