### ISSUE TITLE
SSL handshake fails with Android client

### ISSUE THREAD

**Issue by johnou** [netty/netty#4459]
We are currently using the JDK SSL provider for testing (will switch over to OpenSsl when it is working on all devices).

Our game establishes an SSL connection without problems on PC / IOS but on Android the handshake fails.. Server side is using a self signed certificate created with SelfSignedCertificate, client source between all devices is the "same", simple SslStream with "untrusted" ValidateRemoteCertificate stub.

As suggested by http://stackoverflow.com/questions/13390964/java-ssl-fatal-error-80-unwrapping-net-record-after-adding-the-https-en I have tried setting the host and port of the server in the ssl engine but receive the same exception.

```
Using SSLEngineImpl.
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_RSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_DHE_DSS_WITH_AES_256_CBC_SHA256
Ignoring unavailable cipher suite: TLS_DHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
Ignoring unavailable cipher suite: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
nioEventLoopGroup-3-1, READ: TLSv1 Handshake, length = 69
*** ClientHello, TLSv1
RandomCookie:  GMT: 1447018523 bytes = { 196, 139, 105, 210, 133, 16, 38, 61, 96, 65, 56, 191, 157, 136, 103, 190, 233, 239, 31, 184, 3, 22, 219, 188, 212, 53, 155, 194 }
Session ID:  {}
Cipher Suites: [TLS_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA, SSL_RSA_WITH_RC4_128_SHA, SSL_RSA_WITH_RC4_128_MD5, SSL_RSA_WITH_DES_CBC_SHA, SSL_RSA_EXPORT_WITH_RC4_40_MD5, SSL_RSA_EXPORT_WITH_RC2_CBC_40_MD5, SSL_RSA_EXPORT_WITH_DES40_CBC_SHA, Unknown 0x0:0x60, Unknown 0x0:0x61, SSL_RSA_EXPORT1024_WITH_DES_CBC_SHA, SSL_RSA_EXPORT1024_WITH_RC4_56_SHA]
Compression Methods:  { 0 }
***
Warning: No renegotiation indication in ClientHello, allow legacy ClientHello
%% Initialized:  [Session-1, SSL_NULL_WITH_NULL_NULL]
matching alias: key
%% Negotiating:  [Session-1, TLS_RSA_WITH_AES_128_CBC_SHA]
*** ServerHello, TLSv1
RandomCookie:  GMT: 1447018530 bytes = { 139, 105, 20, 122, 42, 226, 209, 82, 168, 5, 165, 206, 9, 119, 182, 241, 216, 113, 107, 152, 21, 58, 17, 124, 146, 60, 20, 164 }
Session ID:  {86, 64, 192, 34, 237, 169, 247, 131, 206, 116, 10, 253, 195, 189, 101, 48, 20, 10, 253, 94, 187, 61, 19, 8, 134, 124, 45, 238, 3, 56, 209, 225}
Cipher Suite: TLS_RSA_WITH_AES_128_CBC_SHA
Compression Method: 0
***
Cipher suite:  TLS_RSA_WITH_AES_128_CBC_SHA
*** Certificate chain
chain [0] = [
[
  Version: V3
  Subject: CN=example.com
  Signature Algorithm: SHA1withRSA, OID = 1.2.840.113549.1.1.5

  Key:  Sun RSA public key, 1024 bits
  modulus: 103058540584568376650059788913972627420769636168177654070399935749240048492167664197004877811881065300318574180814909980791013291963396980953082680805789270097339756872515280450293670491696360476974830823130180924508555776884045254249153630567923726329301459145894591630115282799444035199402622124819158009871
  public exponent: 65537
  Validity: [From: Sun Nov 09 16:47:11 CET 2014,
               To: Sat Jan 01 00:59:59 CET 10000]
  Issuer: CN=example.com
  SerialNumber: [    d5cc8baf 741e4ced]

]
  Algorithm: [SHA1withRSA]
  Signature:
0000: 20 96 1C D1 21 5A 82 A7   8C 42 CC C4 E4 91 8C 44   ...!Z...B.....D
0010: CE 2F 18 2D 0B 23 0E 73   8F A1 03 CC D9 C7 26 CB  ./.-.#.s......&.
0020: CB 81 0C BD 41 6B 5D 08   A9 5C 23 11 39 F8 7B B6  ....Ak]..\#.9...
0030: 61 B5 9E CF 83 FA E2 3B   62 85 C2 6F F4 65 29 0D  a......;b..o.e).
0040: 48 C5 1B D6 C1 68 65 A7   98 A9 F6 62 62 1F F7 82  H....he....bb...
0050: 29 97 DA 6D 67 32 59 7C   59 29 DA 76 2B D0 8C 47  )..mg2Y.Y).v+..G
0060: 2F A8 17 F4 A0 08 B2 1A   52 C3 70 03 65 43 4C C0  /.......R.p.eCL.
0070: 95 A9 F4 20 5A E7 AA A9   C2 92 C2 52 09 32 AF 9C  ... Z......R.2..

]
***
*** ServerHelloDone
nioEventLoopGroup-3-1, WRITE: TLSv1 Handshake, length = 518
nioEventLoopGroup-3-1, READ: TLSv1 Alert, length = 2
nioEventLoopGroup-3-1, RECV TLSv1 ALERT:  warning, internal_error
SSL -- handshake alert:  internal_error
nioEventLoopGroup-3-1, fatal error: 80: problem unwrapping net record
javax.net.ssl.SSLProtocolException: handshake alert: internal_error
%% Invalidated:  [Session-1, TLS_RSA_WITH_AES_128_CBC_SHA]
nioEventLoopGroup-3-1, SEND TLSv1 ALERT:  fatal, description = internal_error
nioEventLoopGroup-3-1, WRITE: TLSv1 Alert, length = 2
nioEventLoopGroup-3-1, called closeOutbound()
nioEventLoopGroup-3-1, closeOutboundInternal()
nioEventLoopGroup-3-1, called closeInbound()
nioEventLoopGroup-3-1, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
2015-11-09 16:47:46,619 ERROR [nioEventLoopGroup-3-1] omitted: unexpected exception 
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLProtocolException: handshake alert: internal_error
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:380)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLProtocolException: handshake alert: internal_error
	at sun.security.ssl.ServerHandshaker.handshakeAlert(ServerHandshaker.java:1757)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1771)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1075)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:901)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:775)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1138)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1028)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:968)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:349)
	... 15 more
nioEventLoopGroup-3-1, called closeOutbound()
nioEventLoopGroup-3-1, closeOutboundInternal()
nioEventLoopGroup-3-1, called closeInbound()
nioEventLoopGroup-3-1, closeInboundInternal()
```

**Comment by johnou** [comment]
As suggested by http://stackoverflow.com/questions/13390964/java-ssl-fatal-error-80-unwrapping-net-record-after-adding-the-https-en I have tried setting the host and port of the server in the ssl engine but receive the same exception.

**Comment by doom369** [comment]
@johnou so maybe problem in Android code? Please post your code. I'm using both JDK provider and openSSL with Android clients and all is fine. (java 1.8)

**Comment by Scottmitch** [comment]
What version of netty, java, and android are you using?

**Comment by johnou** [comment]
Netty 4.0.33.Final
Java 1.8.0_25 x64
Android 6.0

I am working on putting together a repro project.

**Comment by johnou** [comment]
Server side project can be found here https://github.com/johnou/ssl-server-test I will report back here when the client side is done.

**Comment by johnou** [comment]
Not a bug in Netty! Turns out there was an undocumented exception being thrown in the SSL authenticated callback which was being swallowed..

11-11 01:12:50.858 25012 25139 I Unity   : NullReferenceException: Object reference not set to an instance of an object
11-11 01:12:50.858 25012 25139 I Unity   :   at Mono.Security.X509.X509Certificate.get_Hash () [0x00000] in <filename unknown>:0
11-11 01:12:50.858 25012 25139 I Unity   :   at Mono.Security.X509.X509Certificate.VerifySignature (System.Security.Cryptography.RSA rsa) [0x00000] in <filename unknown>:0
11-11 01:12:50.858 25012 25139 I Unity   :   at Mono.Security.X509.X509Certificate.VerifySignature (System.Security.Cryptography.AsymmetricAlgorithm aa) [0x00000] in <filename unknown>:
011-11 01:12:50.858 25012 25139 I Unity   :   at System.Security.Cryptography.X509Certificates.X509Chain.IsSignedWith (System.Security.Cryptography.X509Certificates.X509Certificate2 signed, System.Security.Cryptography.AsymmetricAlgorithm pubkey) [0x00000] in <filename unknown>:
0
11-11 01:12:50.858 25012 25139 I Unity   :   at System.Security.Cryptography.X509Certificates.X509Chain.Process (Int32 n) [0x00000] in <filename unknown>:0
11-11 01:12:50.858 25012 25139 I Unity   :   at System.Security.Cryptography.X509Certificates.X509Chain.ValidateChain (X509ChainStatusFlags flag) [0x00000] in <filename unknown>:0
11-11 01:12:50.858 25012 25139 I Unity   :   at System.Security.Cryptography.X509Certificates.X509Chain.Build (System.Security.Cryptograp

This is caused by "Strip Bytecode" in Unity publish settings and only affects Android. The fix consists of adding the below to link.xml.

```
       <assembly fullname="mscorlib">
               <namespace fullname="System.Security.Cryptography" preserve="all"/>
       </assembly>
```

**Comment by Scottmitch** [comment]
Thanks for clarifying the issue @johnou!
