### ISSUE TITLE
EPollArrayWrapper.interrupt

### ISSUE THREAD

**Issue by lixusign** [netty/netty#4460]
cpu all exhaust . cpu switch 250k . netty 4.0.25-final , jdk 1.7.0 76   linux 64x86

"pool-13-thread-1" prio=10 tid=0x00007f2f313b1000 nid=0x2d58 runnable [0x00007f2f2acca000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
	at sun.nio.ch.EPollArrayWrapper.interrupt(EPollArrayWrapper.java:274)
	at sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:193)
	- locked <0x00000007976d2db8> (a java.lang.Object)
	at io.netty.channel.nio.NioEventLoop.wakeup(NioEventLoop.java:591)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:735)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:853)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:710)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:681)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:716)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:954)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:243)

**Comment by Scottmitch** [comment]
Can you describe the issue a bit more? Can you provide a reproducer?

**Comment by normanmaurer** [comment]
Closing as we need more info. Please reopen with more infos if you think there is an issue.

**Comment by greenlaw110** [comment]
Kind of the similar issue happening on undertow:
https://stackoverflow.com/questions/44665552/undertow-xnio-i-o-thread-consistently-eat-cpu
