### ISSUE TITLE
Explicitly document system requirements for HTTP/2 (ALPN and ciphers)

### ISSUE THREAD

**Issue by jchambers** [netty/netty#4522]
I'll stop short of asserting it won't work for anybody, but I was unable to get Netty's HTTP/2 implementation to work with Java 7. In particular, the problem seems to be that the ciphers specified in [`Http2SecurityUtil`](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2SecurityUtil.java) aren't available in Java 7, which leads to exceptions that look like this:

```
Nov 28, 2015 4:47:12 PM io.netty.handler.ssl.ApplicationProtocolNegotiationHandler handshakeFailure
WARNING: [id: 0x549ce599, /127.0.0.1:63577 => /127.0.0.1:8443] TLS handshake failed:
javax.net.ssl.SSLHandshakeException: No appropriate protocol
	at sun.security.ssl.Handshaker.activate(Handshaker.java:449)
	at sun.security.ssl.SSLEngineImpl.kickstartHandshake(SSLEngineImpl.java:708)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:806)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:758)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.JdkSslEngine.unwrap(JdkSslEngine.java:82)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1138)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1028)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:968)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:360)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:163)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:155)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:950)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
```

This happened when running the [HTTP/2 "hello world" example](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http2/helloworld) with Oracle's JDK 1.7.0_60 under OS X 10.11 (15A284). When I switched to Java 8 (and the matching version of `alpn-boot`), everything worked as expected.

I don't think this is a bad thing, per se, but the [README](https://github.com/netty/netty/blob/4.1/README.md) says:

> You require the following to build Netty:
>
> * Latest stable Oracle JDK 7
> * ...
>
> Note that this is build-time requirement. JDK 5 (for 3.x) or 6 (for 4.0+) is enough to run your Netty-based application.

Looks like some extra caveats may be needed in the system requirements.

**Comment by blucas** [comment]
@jchambers - HTTP/2 requires ciphers that are not included in Java 7. This is not a "netty" thing, so much a a Java thing. If you use native ssl in your service, then you can use netty's HTTP/2 codec with Java 7.

**Comment by jchambers** [comment]
Right. Totally understood. I'm not saying it's a defect, but I am saying it might make things easier for newcomers if it were documented somewhere (since it's a non-obvious exception to the "core" system requirements). Your point about using native SSL and Java 7 seems worthy of mention, too!

**Comment by blucas** [comment]
I agree with you.  I think the documentation could do with some updates and general improvements.  It would be good to see codec specific documentation, such as an (HTTP/1.x || WebSocket || HTTP/2 || STOMP) section outlining the requirements, examples, and optional goodies (compression for example).

The documentation section is all available on GitHub, so I'm sure Norman and Trustin would appreciate any PRs you'd be willing to provide.

**Comment by nmittler** [comment]
Yeah, we should probably expand the docs in the readme. Perhaps we should even break out details of using TLS (as we did for grpc: https://github.com/grpc/grpc-java/blob/master/SECURITY.md).

@normanmaurer @Scottmitch WDYT?

**Comment by jchambers** [comment]
> Perhaps we should even break out details of using TLS into a separate doc

That sounds like a good idea to me. Since I'm writing a thing that uses HTTP/2, it'd be great to have somewhere to point end users that explains both the broader requirements (HTTP/2 requires ALPN and some ciphers that aren't in Java 7) and the specifics of addressing those requirements with Netty (including native SSL).

Relatedly, I'll update the summary of this issue to be less about Java 8 and more about system requirements for HTTP/2.

**Comment by normanmaurer** [comment]
Sounds good

**Comment by Scottmitch** [comment]
+1 for better docs.

@nmittler - The link you provided looks like a great start! I wonder if we could "borrow" the non-gRPC specific stuff. Either promote it to Netty somewhere and link from it from gRPC, or just duplicate it for now. WDYT?

**Comment by nmittler** [comment]
@Scottmitch I'm fine with duplicating for now ... we can refactor the grpc docs later.

**Comment by normanmaurer** [comment]
+1

**Comment by Scottmitch** [comment]
I'll submit a PR.

**Comment by normanmaurer** [comment]
Thx!

**Comment by Scottmitch** [comment]
@jchambers - Check out https://github.com/netty/netty/wiki/Requirements-for-4.x

**Comment by jchambers** [comment]
Thank you! Sorry I wasn't able to devote attention to this in a timely manner, but I look forward to contributing to the wiki soon.
