### ISSUE TITLE
WebSocketHandshaker.finishHandshake could result in recursive channelRead event

### ISSUE THREAD

**Issue by jroper** [netty/netty#4533]
I'm not sure if this behaviour is by design or not, but if it is by design, I think it's not very good, because it leads to a very hard to debug race condition, and quite difficult state management.

So, here's the logic of my websocket client handler:

1. Handler receives response
2. `WebSocketClientHandshaker.finishHandshake()` is invoked
3. If that is successful, I setup the pipeline to start handling the WebSocket messages. In my particular case, doing this could immediately trigger the application to start sending messages, which is ok, because the handshake was successful and everything is ready to go.
4. If it's not successful, then I don't do the above

The problem is, `finishHandshake()` can, in some circumstances (I would guess, when the response was received with the first websocket frame already, but I'm not sure), recursively invoke `channelRead` with a websocket frame.  Here's a stack trace showing it happening in Netty 4.0.33:

```
	at com.typesafe.service.internal.client.WebSocketSupervisor.channelRead(WebSocketClient.scala:240)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:216)
	at io.netty.channel.CombinedChannelDuplexHandler.handlerRemoved(CombinedChannelDuplexHandler.java:109)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:527)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:521)
	at io.netty.channel.DefaultChannelPipeline.replace0(DefaultChannelPipeline.java:456)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:405)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:378)
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker.finishHandshake(WebSocketClientHandshaker.java:265)
	at com.typesafe.service.internal.client.WebSocketSupervisor.channelRead(WebSocketClient.scala:178)
```

So, the problem with this is that my pipeline is not yet setup to handle the websocket messages, so this causes problems.  Now, I could set up the pipeline to handle websocket messages before doing the handshake, but like I said, this could result in messages immediately being sent, which would be a problem because at this point, the websocket decoder might not be in the pipeline, and what if the handshake fails?

At a minimum, if this behaviour is by design and unavoidable, it should be clearly documented that the pipeline needs to be ready to receive websocket frames before `finishHandshake` is invoked, and it should probably also be documented that the pipeline must not start sending frames until after `finishHandshake` is invoked.  But I think it would be much better if `finishHandshake` was guaranteed to not start sending frames down the pipeline, so that the logic for setting up the pipeline can be simple without having to worry about recursion.

**Comment by Scottmitch** [comment]
I can see how this may be problematic. To clarify you are using the `WebSocketClientProtocolHandler.ClientHandshakeStateEvent.HANDSHAKE_COMPLETE` user event as the trigger point to setup your pipeline with application level websocket handlers? I guess we could add another user which is fired before the [WebSocketClientHandshaker calls replace](https://github.com/netty/netty/blob/4.0/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketClientHandshaker.java#L265) ... would this be sufficient?

**Comment by jroper** [comment]
Actually no I didn't know that event existed, I started my code by copying the Netty websocket samples to know how to implement websockets in Netty, which don't use these events:

https://github.com/netty/netty/blob/master/example/src/main/java/io/netty/example/http/websocketx/client/WebSocketClientHandler.java

Looking at that code, there seems to be a similar race condition as was in my code, the `handshakeFuture` could already be completed before `finishHandshake` returns due to the fact that events could be fired, synchronously processed, and failed during the `finishHandshake` call, meaning the `setSuccess` call immediately after it will throw an exception.  It should probably not be calling `setSuccess` where it does, rather it should be listening to the the `HANDSHAKE_COMPLETE` user event.  Doing this would also guide everyone that implements websockets in Netty to do the right thing.

**Comment by normanmaurer** [comment]
@jroper let me fix this.

**Comment by normanmaurer** [comment]
@jroper https://github.com/netty/netty/pull/4815 should fix it. PTAL

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4815
