### ISSUE TITLE
NPE in PooledByteBufAllocator.newDirectBuffer

### ISSUE THREAD

**Issue by trustin** [netty/netty#4547]
4.1.0.Beta8. It seems to me this should never occur but..

```
2015-12-09 16:19:00 [WARN ](Slf4JLogger.java:151) [nioEventLoopGroup-5-11] [14496455302260] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception. 
java.lang.NullPointerException: null 
at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:257) 
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:157) 
at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:148) 
at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:109) 
at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:73) 
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:111) 
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467) 
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381) 
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) 
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) 
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) 
at java.lang.Thread.run(Thread.java:745)
```

**Comment by normanmaurer** [comment]
Hmm... Is this maybe related to:
https://github.com/netty/netty/pull/4388
https://github.com/netty/netty/issues/4198

Looks a bit different though...

**Comment by normanmaurer** [comment]
Let me try to find out whats wrong....  @trustin I guess this is hard to reproduce?

**Comment by mauhiz** [comment]
We saw it appear during a JVM shutdown. Wasn't able to reproduce so far

**Comment by ninja-** [comment]
I feel like https://github.com/netty/netty/pull/4548 - a fix for other issue(?), could also solve this. That's because based on what @mauhiz said, nio event loop tries to read from a channel in shutdown() (in a task after shutdown... ) while it already destroyed the allocator.

**Comment by normanmaurer** [comment]
@ninja- this is in no way related at all

**Comment by normanmaurer** [comment]
@trustin the NPE would only happen if a final field would be null which should never happen. I think this is a Java bug, or could you think of anything else ?

**Comment by mauhiz** [comment]
Per Java specs, the only way for such a final field to be null is if an incomplete object is leaked like [here](https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/AbstractByteBufAllocator.java#L71). Now, to understand the exact race condition that led to the error... :angel:

**Comment by normanmaurer** [comment]
@trustin @mauhiz I wonder if it could be related to this:

https://github.com/netty/netty/blob/4.1/buffer/src/main/java/io/netty/buffer/PooledByteBufAllocator.java#L194

**Comment by trustin** [comment]
@normanmaurer I guess not..

**Comment by normanmaurer** [comment]
@trustin did this happened again ? If not can we close this ?

**Comment by trustin** [comment]
Not a Netty issue but a user problem related with Tomcat class loaders.

**Comment by buchgr** [comment]
@trustin interesting. do you know what the issue was exactly? I would be interested, in what can make a final field null?

**Comment by zhuhengwei** [comment]
This issue is related to the class loader mechanism of Tomcat. Upgrading the Tomcat version can solve it. For Tomcat 5/6, the parameter **ENABLE_CLEAR_REFERENCES** has a default value of **true**, and when Tomcat is turned off, final and static objects will be automatically cleaned up. For Tomcat 7, the configuration item is changed to **clearReferencesStatic**, and the default value is changed to **false**, which solves the problem. For more details, please refer to org.apache.catalina.loader.WebappClassLoader#clearReferences.
