### ISSUE TITLE
HTTP2 padding merging breaks flow control

### ISSUE THREAD

**Issue by louiscryan** [netty/netty#4573]
@Scottmitch 
@nmittler 

In DefaultHttp2Controller.enqueueFrame we increment the pendingBytes based on the size of the frame passed regardless of whether it was merged. Since merging uses padding = max(padding, new.padding) the number of bytes added to the merged frame may be less than newFrame.size().

This eventually leads to the flow controller allocating bytes to write when there are no frames which causes an assertion.

As a general rule it would make sense for the flow-controller unit tests to always use padding.

Working on fix for the immediate issue. Found this while working on stress test to find memory leak

```
Caused by: io.netty.handler.codec.http2.Http2Exception: byte distribution write error
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:96) ~[classes/:na]
	at io.netty.handler.codec.http2.PriorityStreamByteDistributor$WriteVisitor.visit(PriorityStreamByteDistributor.java:416) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.forEachActiveStream(DefaultHttp2Connection.java:1134) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.forEachActiveStream(DefaultHttp2Connection.java:135) ~[classes/:na]
	at io.netty.handler.codec.http2.PriorityStreamByteDistributor$WriteVisitor.writeAllocatedBytes(PriorityStreamByteDistributor.java:396) ~[classes/:na]
	at io.netty.handler.codec.http2.PriorityStreamByteDistributor.distribute(PriorityStreamByteDistributor.java:93) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:743) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultWritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:792) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes(DefaultHttp2RemoteFlowController.java:275) ~[classes/:na]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:349) ~[classes/:na]
	at io.netty.handler.codec.http2.FindTheLeakTest$1.run(FindTheLeakTest.java:103) ~[test-classes/:na]
	at io.netty.handler.codec.http2.Http2TestUtil$1.run(Http2TestUtil.java:46) ~[test-classes/:na]
	... 4 common frames omitted
Caused by: java.lang.AssertionError: null
	at io.netty.handler.codec.http2.PriorityStreamByteDistributor$PriorityState.updateStreamableBytes(PriorityStreamByteDistributor.java:349) ~[classes/:na]
	at io.netty.handler.codec.http2.PriorityStreamByteDistributor.updateStreamableBytes(PriorityStreamByteDistributor.java:81) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.incrementStreamWindow(DefaultHttp2RemoteFlowController.java:399) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.decrementFlowControlWindow(DefaultHttp2RemoteFlowController.java:505) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.writeAllocatedBytes(DefaultHttp2RemoteFlowController.java:380) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultWritabilityMonitor$1.write(DefaultHttp2RemoteFlowController.java:786) ~[classes/:na]
	at io.netty.handler.codec.http2.PriorityStreamByteDistributor$WriteVisitor.visit(PriorityStreamByteDistributor.java:412) ~[classes/:na]
	... 14 common frames omitted
18:51:59.807 [defaultEventLoopGroup-3-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.AssertionError: null
	at io.netty.handler.codec.http2.PriorityStreamByteDistributor$PriorityState.updateStreamableBytes(PriorityStreamByteDistributor.java:349) ~[classes/:na]
	at io.netty.handler.codec.http2.PriorityStreamByteDistributor.updateStreamableBytes(PriorityStreamByteDistributor.java:81) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.cancel(DefaultHttp2RemoteFlowController.java:476) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$DefaultState.cancel(DefaultHttp2RemoteFlowController.java:454) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:111) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:263) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1177) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams$2.process(DefaultHttp2Connection.java:1124) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.forEachActiveStream(DefaultHttp2Connection.java:1148) ~[classes/:na]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.forEachActiveStream(DefaultHttp2Connection.java:135) ~[classes/:na]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:371) ~[classes/:na]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:569) ~[classes/:na]
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelInactiveNow(ChannelHandlerInvokerUtil.java:56) ~[classes/:na]
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelInactive(DefaultChannelHandlerInvoker.java:102) [classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:132) [classes/:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:910) [classes/:na]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:678) [classes/:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:310) [classes/:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor.confirmShutdown(SingleThreadEventExecutor.java:609) [classes/:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:765) [classes/:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [classes/:na]
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Scottmitch** [comment]
@louiscryan - makes sense. I guess we should only be incrementing by the frame size change in the event we merged frames (otherwise we will be double counting the bytes before the merge)?

**Comment by Scottmitch** [comment]
@louiscryan - Any updates on this. It would be nice to get this in before the next release. I can take over this if you don't have cycles.

**Comment by Scottmitch** [comment]
@louiscryan - I'll take this over for now. We can improve tests later.

**Comment by louiscryan** [comment]
Sorry Scott. Let me dig up my PR tomorrow and at least send that over so
you can take it over. It's pretty small

**Comment by Scottmitch** [comment]
@louiscryan - No problem. I have a PR pending, but if you push yours I can make sure I covered everything. I'll also ping you for a review of my PR.
