### ISSUE TITLE
Unexpected exception in the selector loop

### ISSUE THREAD

**Issue by nezhazheng** [netty/netty#4583]
Version: netty-all-5.0.0.Alpha2
What happend..

18:23:06.850 109893 [nioEventLoopGroup-1-545] WARN i.n.c.nio.NioEventLoop  Unexpected exception in the selector loop.
java.nio.channels.ClosedSelectorException: null
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:84) ~[na:1.7.0_91]
	at sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:106) ~[na:1.7.0_91]
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:619) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:307) ~[netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1706) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1661) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126) [netty-all-5.0.0.Alpha2.jar:5.0.0.Alpha2]

**Comment by normanmaurer** [comment]
@nezhazheng Please use latest 4.1.0 release (4.1.0.Beta8) or 4.0.33.Final. There should be no issue there.
