### ISSUE TITLE
Possible leak in FixedChannelPool

### ISSUE THREAD

**Issue by kennethjor** [netty/netty#4609]
I've been trying to debug a very odd problem we're seeing in our use of `FixedChannelPool`. I can acquire and release channels from the pool just fine, but eventually a situation occurs where the internal `acquiredChannelCount` does not match what has actually been released and acquired. This leads to a situation where the pool thinks it's got the maximum amount of channels outstanding, even though all the channels have already been release, leading to a pending acquire queue which never progresses.

I have forked [FixedChannelPoolTest.java](https://github.com/kennethjor/netty/blob/pool-leak/transport/src/test/java/io/netty/channel/pool/FixedChannelPoolTest.java) and managed to replicate the issue. In order to make it happen, I need to spawn about a hundred threads, each acquiring and releasing about 50,000 channels before I can get an acquired channel discrepancy. This of course leads me to believe it's an obscure race condition somewhere. Another interesting thing to note is that this only occurs if I explicitly close the channel before releasing it. If I don't close it, it doesn't seem to happen.

Or perhaps I'm doing something wrong. It wouldn't be the first time. Any help would be appreciated.

**Comment by normanmaurer** [comment]
Let me have a look

**Comment by normanmaurer** [comment]
@kennethjor can you also include which version of netty?

**Comment by ninja-** [comment]
@normanmaurer his fork is 4.0.34.Final-SNAPSHOT

**Comment by normanmaurer** [comment]
@kennethjor hmm I think your test is not correct and so it will show the error. The problem is that you completely exit the for loop on an error while acquire and not wait for the latch to be completely countdown.

Please try this test code and see if you still see the issue (I not see it with this):

```java
    @Test
    public void testAcquireReleaseMany() throws Exception {
        EventLoopGroup group = new LocalEventLoopGroup(8);
        LocalAddress addr = new LocalAddress(LOCAL_ADDR_ID);
        Bootstrap cb = new Bootstrap();
        cb.remoteAddress(addr);
        cb.group(group)
                .channel(LocalChannel.class);

        ServerBootstrap sb = new ServerBootstrap();
        sb.group(group)
                .channel(LocalServerChannel.class)
                .childHandler(new ChannelInitializer<LocalChannel>() {
                    @Override
                    public void initChannel(LocalChannel ch) throws Exception {
                        ch.pipeline().addLast(new ChannelInboundHandlerAdapter());
                    }
                });

        // Start server
        Channel sc = sb.bind(addr).syncUninterruptibly().channel();
        CountingChannelPoolHandler handler = new CountingChannelPoolHandler();

        int maxChannels = 8;
        final ChannelPool pool = new FixedChannelPool(cb, handler, maxChannels, Integer.MAX_VALUE);

        ExecutorService executor = Executors.newCachedThreadPool();
        final int n = 50;
        final int m = n * 1000;
        final CountDownLatch latch = new CountDownLatch(n);
        final Set<Channel> channels = Collections.newSetFromMap(new ConcurrentHashMap<Channel, Boolean>());
        final AtomicInteger rounds = new AtomicInteger();
        for (int i=0 ; i<n ; i++) {
            executor.execute(new Runnable() {
                @Override
                public void run() {
                    try {
                        for (int i = 0; i < m; i++) {
                            rounds.incrementAndGet();
                            Future<Channel> future1 = pool.acquire().syncUninterruptibly();
                            assertTrue(future1.isSuccess());
                            Channel channel = future1.getNow();
                            assertNotNull(channel);
                            channels.add(channel);
                            try {
                                channel.close().syncUninterruptibly();
                            }
                            catch (Throwable e) {
                                e.printStackTrace();
                                //System.out.println("Close error: " + e.getClass().getName() + ": " + e.getMessage());
                            }
                            try {
                                pool.release(channel).syncUninterruptibly();
                            }
                            catch (IllegalStateException e) {
                                if (!e.getMessage().equals("Channel is unhealthy not offering it back to pool")) {
                                    throw e;
                                }
                            }
                            catch (Throwable e) {
                                System.out.println("Release error: " + e.getClass().getName() + ": " + e.getMessage());
                            }
                        }
                    }
                    catch (Throwable e) {
                        System.out.println("Error: " + e.getClass().getName() + ": " + e.getMessage());
                    }
                    latch.countDown();
                }
            });
        }
        latch.await();
        Thread.sleep(500);

//        assertEquals(channels.size(), handler.channelCount());
//        assertEquals(rounds.get() - channels.size(), handler.acquiredCount());
//        assertEquals(rounds.get(), handler.releasedCount());

        sc.close().syncUninterruptibly();
        for (Channel channel : channels) {
            channel.close().syncUninterruptibly();
        }
        group.shutdownGracefully();

        // Check internal acquired count.
        Field acquiredChannelCountField = FixedChannelPool.class.getDeclaredField("acquiredChannelCount");
        acquiredChannelCountField.setAccessible(true);
        int acquiredChannelCount = (Integer) acquiredChannelCountField.get(pool);
        assertEquals(0, acquiredChannelCount);
    }
```

To make it easier I just adjusted the code you provided and not did any more changes there.

**Comment by kennethjor** [comment]
@normanmaurer Thank you for the very quick reply. I did see that as well and modified the test. Newest version is pushed to my fork, but I'm still seeing the error. Full test output:

```
/usr/lib/jvm/java-8-oracle/bin/java -ea -server -dsa -da -ea:io.netty... -XX:+AggressiveOpts -XX:+TieredCompilation -XX:+UseBiasedLocking -XX:+UseFastAccessorMethods -XX:+OptimizeStringConcat -XX:+HeapDumpOnOutOfMemoryError -Xbootclasspath/p:/home/kenn/.m2/repository/org/mortbay/jetty/alpn/alpn-boot/8.1.6.v20151105/alpn-boot-8.1.6.v20151105.jar -D_ -D_ -Didea.launcher.port=7533 -Didea.launcher.bin.path=/home/kenn/Storage/local/idea-IC-143.381.42/bin -Didea.junit.sm_runner -Dfile.encoding=UTF-8 -classpath /home/kenn/Storage/local/idea-IC-143.381.42/lib/idea_rt.jar:/home/kenn/Storage/local/idea-IC-143.381.42/plugins/junit/lib/junit-rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/home/kenn/Projects/netty/transport/target/test-classes:/home/kenn/Projects/netty/transport/target/classes:/home/kenn/Projects/netty/buffer/target/classes:/home/kenn/Projects/netty/common/target/classes:/home/kenn/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar:/home/kenn/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/kenn/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/kenn/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/home/kenn/.m2/repository/org/easymock/easymock/3.2/easymock-3.2.jar:/home/kenn/.m2/repository/cglib/cglib-nodep/2.2.2/cglib-nodep-2.2.2.jar:/home/kenn/.m2/repository/org/objenesis/objenesis/1.3/objenesis-1.3.jar:/home/kenn/.m2/repository/org/easymock/easymockclassextension/3.2/easymockclassextension-3.2.jar:/home/kenn/.m2/repository/org/jmock/jmock-junit4/2.6.0/jmock-junit4-2.6.0.jar:/home/kenn/.m2/repository/org/jmock/jmock/2.6.0/jmock-2.6.0.jar:/home/kenn/.m2/repository/org/mockito/mockito-core/1.10.8/mockito-core-1.10.8.jar:/home/kenn/.m2/repository/ch/qos/logback/logback-classic/1.0.13/logback-classic-1.0.13.jar:/home/kenn/.m2/repository/ch/qos/logback/logback-core/1.0.13/logback-core-1.0.13.jar:/home/kenn/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 io.netty.channel.pool.FixedChannelPoolTest,testAcquireReleaseMany "Until Failure"
10:53:35.502 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
10:53:35.506 [main] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
10:53:35.513 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
10:53:35.513 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
10:53:35.514 [main] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
10:53:35.514 [main] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
10:53:35.515 [main] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
10:53:35.515 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
10:53:35.515 [main] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
10:53:35.515 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
10:53:35.632 [main] DEBUG i.n.util.internal.PlatformDependent - Javassist: available
10:53:35.632 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
10:53:35.632 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
10:53:35.633 [main] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
10:53:35.678 [main] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x38319457c435ea7c (took 15 ms)
10:53:35.712 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
10:53:35.713 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
10:53:35.713 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
Acquire error: java.nio.channels.ClosedChannelException: null
Acquire error: java.nio.channels.ClosedChannelException: null
Acquire error: java.nio.channels.ClosedChannelException: null
Acquire error: java.nio.channels.ClosedChannelException: null
Acquire error: java.nio.channels.ClosedChannelException: null

java.lang.AssertionError: 
Expected :0
Actual   :8
  <Click to see difference>



	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.netty.channel.pool.FixedChannelPoolTest.testAcquireReleaseMany(FixedChannelPoolTest.java:409)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:136)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)


Process finished with exit code 255
```

I also see quite a few "connection refused" exceptions, but I'm not sure they are related to the bug so I've filtered them out. While it didn't happen this time, usually the discrepancy is exactly equal to the number of `ClosedChannelException` seen. Not sure if this is related though.

Could it be that the acquire code will increment the internal counter even if the acquire failed?

**Comment by kennethjor** [comment]
@normanmaurer Sorry I completely missed your point about properly waiting for the latch. You are quite right, that was an oversight on my part. I will close this issue and continue to look for the error in my own code, I must be using the channel pools wrong or something.
