### ISSUE TITLE
IndexOutOfBoundsException for CompositeByteBuf

### ISSUE THREAD

**Issue by valodzka** [netty/netty#4679]
This code worked up to netty 4.0.32, but stopped in 4.0.33.Final

        ByteBufAllocator alloc = ByteBufAllocator.DEFAULT;
        CompositeByteBuf cBuff = alloc.compositeDirectBuffer();
        cBuff.addComponent(alloc.buffer(8).writeLong(0));
        cBuff.addComponent(alloc.buffer(8).writeLong(0));
        
        // work as expected
        System.err.println("str="+ cBuff.toString(0, 16, StandardCharsets.UTF_8));
        // fails
        System.err.println("str="+ cBuff.toString(3, 13, StandardCharsets.UTF_8));

Exception:

    Exception in thread "main" java.lang.IndexOutOfBoundsException: index: 3, length: 13 (expected: range(0, 13))
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1142)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1137)
	at io.netty.buffer.UnpooledHeapByteBuf.internalNioBuffer(UnpooledHeapByteBuf.java:280)
	at io.netty.buffer.ByteBufUtil.decodeString(ByteBufUtil.java:558)
	at io.netty.buffer.AbstractByteBuf.toString(AbstractByteBuf.java:978)
	at Tester.main(Tester.java:24)

**Comment by normanmaurer** [comment]
will have a look

**Comment by windie** [comment]
Fixed in #4681

**Comment by normanmaurer** [comment]
@valodzka could you test with latest 4.0 branch: 

This test works for me:

```

    @Test
    public void testToStringComposite() {
        CompositeByteBuf cBuff = compositeBuffer();
        cBuff.addComponent(buffer(8).writeLong(0));
        cBuff.addComponent(buffer(8).writeLong(0));

        // work as expected
        System.err.println("str="+ cBuff.toString(0, 16, CharsetUtil.UTF_8));
        // fails
        System.err.println("str="+ cBuff.toString(3, 13, CharsetUtil.UTF_8));
    }
```

**Comment by normanmaurer** [comment]
@valodzka doh! I did not notice @windie fixed it and @Scottmitch pulled it in. @windie @Scottmitch you rock!
