### ISSUE TITLE
DnsNameResolverTest.testResolveIp failure

### ISSUE THREAD

**Issue by slandelle** [netty/netty#4720]
I backported DNS related code to AHC as I can't directly jump from 3.10 to 4.1.

This test crashed on Travis that runs on EC2:

```
Tests run: 12, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.423 sec <<< FAILURE! - in TestSuite
testResolveIp on testResolveIp(io.netty.resolver.dns.DnsNameResolverTest)(io.netty.resolver.dns.DnsNameResolverTest)  Time elapsed: 0.017 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[10.0.0.1]> but was:<[ip-10-0-0-1.ec2.internal]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at io.netty.resolver.dns.DnsNameResolverTest.testResolveIp(DnsNameResolverTest.java:501)
```

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4723
