### ISSUE TITLE
OpenSSL provider allows null cert chain even if client authentication is required

### ISSUE THREAD

**Issue by floragunncom** [netty/netty#4725]
Expected javax.net.ssl.SSLException: Received fatal alert: bad_certificate because of javax.net.ssl.SSLHandshakeException: null cert chain but no such exception is thrown when using OpenSSL as provider: 
https://github.com/floragunncom/netty/commit/fc8c77e61ec799a90e5b253a6ebb301ce1d19dd2

With JDK provider it fails correctly:
https://github.com/floragunncom/netty/commit/8ff146bd8738a9b1e85d1625e90fbdbf7d718bcc

**Comment by floragunncom** [comment]
Env is: Netty 4.0.33 with netty-tcnative 1.1.33.Fork10 on osx-x86_64 and OpenSSL 1.0.2d 9 Jul 2015

Maybe related to #4722

**Comment by normanmaurer** [comment]
@floragunncom but it still fails the handshake right ? At least that is what I see here.

**Comment by normanmaurer** [comment]
@floragunncom actually I think it only fails in the 4.0 branch and did not in 4.0.33.Final. Could you run again with latest 4.0 branch. That said there is still a small bug which cause the SslHandshakeException have not the correct message. Working on a fix now

**Comment by floragunncom** [comment]
latest 4.0 branch gives:

<pre>
13:11:50.897 [nioEventLoopGroup-3-1] DEBUG io.netty.handler.ssl.OpenSslEngine - SSL_read failed: OpenSSL error: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
13:11:50.897 [nioEventLoopGroup-2-1] DEBUG io.netty.handler.ssl.OpenSslEngine - SSL_read failed: OpenSSL error: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:00000000:lib(0):func(0):reason(0)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:400)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:829)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: error:00000000:lib(0):func(0):reason(0)
	at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:761)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:722)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:797)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:840)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1085)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:963)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:903)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369)
	... 12 more
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:00000000:lib(0):func(0):reason(0)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:400)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:829)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: error:00000000:lib(0):func(0):reason(0)
	at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:761)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:722)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:797)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:840)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1085)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:963)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:903)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369)
	... 12 more
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:400)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:829)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
	at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:564)
	at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:765)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:722)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:797)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:840)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1085)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:963)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:903)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369)
	... 12 more
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:400)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:279)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:829)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.net.ssl.SSLHandshakeException: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
	at io.netty.handler.ssl.OpenSslEngine.shutdownWithError(OpenSslEngine.java:564)
	at io.netty.handler.ssl.OpenSslEngine.sslReadErrorResult(OpenSslEngine.java:765)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:722)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:797)
	at io.netty.handler.ssl.OpenSslEngine.unwrap(OpenSslEngine.java:840)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1085)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:963)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:903)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369)
	... 12 more

</pre>

**Comment by normanmaurer** [comment]
What is wrong with this? You send no cert so a handshake dailure sound right...

**Comment by floragunncom** [comment]
nothing really wrong, just a bit a vacuous error message

**Comment by normanmaurer** [comment]
A fix for a better exception error message is in the making. Stay tuned...

**Comment by floragunncom** [comment]
thanks :-)

**Comment by normanmaurer** [comment]
Fixed error message via https://github.com/netty/netty/pull/4729
