### ISSUE TITLE
PooledByteBufAllocatorTest.testConcurrentUsage test failure

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#4777]
I have seen this from 2 PRs with unrelated changes thus far.

https://garage.netty.io/teamcity/viewLog.html?buildId=5167&buildTypeId=pulls_netty&guest=1
```
[13:07:48][io.netty:netty-buffer] Running io.netty.buffer.PooledByteBufAllocatorTest
[13:07:48][io.netty:netty-buffer] 13:07:48.432ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 16
[13:07:48][io.netty:netty-buffer] 13:07:48.433ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 16
[13:07:48][io.netty:netty-buffer] 13:07:48.433ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
[13:07:48][io.netty:netty-buffer] 13:07:48.433ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
[13:07:48][io.netty:netty-buffer] 13:07:48.433ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
[13:07:48][io.netty:netty-buffer] 13:07:48.433ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
[13:07:48][io.netty:netty-buffer] 13:07:48.433ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
[13:07:48][io.netty:netty-buffer] 13:07:48.434ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
[13:07:48][io.netty:netty-buffer] 13:07:48.434ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
[13:07:48][io.netty:netty-buffer] 13:07:48.434ain] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
[13:07:48][io.netty:netty-buffer] 13:07:48.629 [Thread-172] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
[13:10:19][io.netty:netty-buffer] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 150.497 sec <<< FAILURE! - in io.netty.buffer.PooledByteBufAllocatorTest
[13:10:19][io.netty:netty-buffer] testConcurrentUsage(io.netty.buffer.PooledByteBufAllocatorTest)  Time elapsed: 150.462 sec  <<< ERROR!
[13:10:19][io.netty:netty-buffer] java.lang.OutOfMemoryError: unable to create new native thread
[13:10:19][io.netty:netty-buffer] 	at java.lang.Thread.start0(Native Method)
[13:10:19][io.netty:netty-buffer] 	at java.lang.Thread.start(Thread.java:714)
[13:10:19][io.netty:netty-buffer] 	at io.netty.buffer.PooledByteBufAllocatorTest.testConcurrentUsage(PooledByteBufAllocatorTest.java:50)
[13:10:19][io.netty:netty-buffer] 
[13:10:19][io.netty:netty-buffer] Running io.netty.buffer.ByteBufProcessorTest
[13:10:19][io.netty:netty-buffer] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in io.netty.buffer.ByteBufProcessorTest
[13:10:19][io.netty:netty-buffer] Running io.netty.buffer.ReadOnlyUnsafeDirectByteBufferBufTest
[13:10:19][io.netty:netty-buffer] Tests run: 17, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.015 sec - in io.netty.buffer.ReadOnlyUnsafeDirectByteBufferBufTest
[13:10:19][io.netty:netty-buffer] Running io.netty.buffer.DefaultByteBufHolderTest
[13:10:19][io.netty:netty-buffer] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.netty.buffer.DefaultByteBufHolderTest
[13:10:19][io.netty:netty-buffer] Running io.netty.buffer.UnsafeByteBufUtilTest
[13:10:19][io.netty:netty-buffer] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in io.netty.buffer.UnsafeByteBufUtilTest
[13:10:19][io.netty:netty-buffer] Running io.netty.buffer.BigEndianCompositeByteBufTest
[13:10:19][io.netty:netty-buffer] io.netty.buffer.PooledByteBufAllocatorTest
[13:10:19][io.netty.buffer.PooledByteBufAllocatorTest] testConcurrentUsage
[13:10:19][testConcurrentUsage] java.lang.OutOfMemoryError: unable to create new native thread
[13:10:19]
[testConcurrentUsage] java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:714)
	at io.netty.buffer.PooledByteBufAllocatorTest.testConcurrentUsage(PooledByteBufAllocatorTest.java:50)
```

**Comment by trustin** [comment]
I wonder if this failure is simply due to the CI machine is out of memory temporarily. As you know, there's a chance of running 3+ builds in a single CI machine in our configuration.

**Comment by normanmaurer** [comment]
@trustin yeah I guess so... maybe we want to disable the test for now as it is super heavy ?

**Comment by trustin** [comment]
@normanmaurer Perhaps we should just reduce the number of concurrent jobs on the machine? If this keeps happening we might have to investigate further. We lose the chance of doing so by just ignoring it.

**Comment by normanmaurer** [comment]
to 2 ?

**Comment by trustin** [comment]
We currently have 3 containers in the machine and TeamCity just thinks we have 3 machines. I wonder if we can tell TeamCity that they are actually a same machine and jobs should not run concurrently. Didn't have time to take a close look..

**Comment by trustin** [comment]
Yeah, let's start from reducing to 2.

**Comment by normanmaurer** [comment]
@trustin can you do as I can not find it :/

**Comment by trustin** [comment]
@normanmaurer will try today. :-)

**Comment by Scottmitch** [comment]
@trustin thanks for taking care!

**Comment by trustin** [comment]
Configured so that more than two concurrent builds cannot run. However, we will need more sophisticated mechanism to utilize the machines more efficiently. Asked a question to Jetbrains:

https://teamcity-support.jetbrains.com/hc/en-us/community/posts/206403679-Restricting-concurrent-builds-between-multiple-agents

 We currently just use a global shared resource, as described here:

https://confluence.jetbrains.com/display/TCD9/Shared+Resources#SharedResources-UsingSharedResourcesinBuildConfigurations

**Comment by Scottmitch** [comment]
@trustin - I'll assign to you for now since you took some action regarding this issue ... feel free to close if you feel the CI changes addressed the failures.

**Comment by trustin** [comment]
We don't see the CI failures related with this anymore. TeamCity shared resource seems to work. However, it seems like there's no perfect solution to our setup, according to the response from JetBrains.
