### ISSUE TITLE
WebSocket Compression for client not working

### ISSUE THREAD

**Issue by kaendfinger** [netty/netty#4794]
I helped implement WebSocket compression the Dart VM (https://www.dartlang.org/)

However, when I try to connect to it via Netty 5.0.0-Alpha-2:

```
Exception in thread "Thread-1" io.netty.handler.codec.CodecException: invalid WebSocket Extension handhshake for "permessage-deflate; client_max_window_bits=15"
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketClientExtensionHandler.channelRead(WebSocketClientExtensionHandler.java:111)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84)
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	at io.netty.channel.PausableChannelEventExecutor.invokeChannelRead(PausableChannelEventExecutor.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:389)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:243)
```

The WebSocket server and client pass all WebSocket compression tests for Autobahn, and works in all major browsers.

I could be wrong, but I believe this is a problem with Netty's implementation.

**Comment by normanmaurer** [comment]
will have a look

**Comment by kaendfinger** [comment]
@normanmaurer It seems I had to enable the client max window bits flag for WebSocket compression.

```java
super(
                 new PerMessageDeflateClientExtensionHandshaker(6, true /* enabled this flag */, 15, false, false),
                 new DeflateFrameClientExtensionHandshaker(false),
                 new DeflateFrameClientExtensionHandshaker(true));
```

This really should be enabled by default. All other implementations of WebSockets work fine.

**Comment by normanmaurer** [comment]
@kaendfinger this is because specify a custom window size is only possible with jdk7 or if jzlib is used so we are playing safe here. I wonder if we should maybe use true if jdk7 is used or if jzlib is used. WDYT ?

**Comment by kaendfinger** [comment]
That sounds like the best way to do it :)

**Comment by normanmaurer** [comment]
@kaendfinger ok let me take a stab.

**Comment by normanmaurer** [comment]
@kaendfinger Please check https://github.com/netty/netty/pull/4813

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4813
