### ISSUE TITLE
Native transport package prefix not working.

### ISSUE THREAD

**Issue by Harry5573** [netty/netty#4800]
It appears that the native transport package prefix property that was added in (https://github.com/netty/netty/commit/53323530c1b47e225c28fc4e3a4a4f9de1b7a0e3) is not working.

Netty build: 4.0.34.Final
Error:
> 
[06:07:43] [Server thread/ERROR]: Exception stopping the server
java.lang.UnsatisfiedLinkError: failed to load the required native library
        at net.minecraft.util.io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:76) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.server.v1_7_R4.ServerConnection.<init>(ServerConnection.java:44) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.server.v1_7_R4.MinecraftServer.ai(MinecraftServer.java:1328) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.server.v1_7_R4.MinecraftServer.stop(MinecraftServer.java:401) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Krunchit-80a1691]
Caused by: java.lang.UnsatisfiedLinkError: net.minecraft.util.io.netty.channel.epoll.Native.epollin()I
        at net.minecraft.util.io.netty.channel.epoll.Native.epollin(Native Method) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.util.io.netty.channel.epoll.Native.<clinit>(Native.java:52) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.util.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:32) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.server.v1_7_R4.ServerConnection.<init>(ServerConnection.java:44) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.server.v1_7_R4.MinecraftServer.ai(MinecraftServer.java:1328) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:147) ~[spigot.jar:git-Krunchit-80a1691]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:470) ~[spigot.jar:git-Krunchit-80a1691]
        ... 1 more

Shaded package: `net.minecraft.util.io.netty`
Property: `System.setProperty("io.netty.native.epoll.nettyPackagePrefix", "net/minecraft/util/");`
Operating system: `Centos 6.7`

**Comment by normanmaurer** [comment]
@Harry5573 @Scottmitch is working on it.

**Comment by Scottmitch** [comment]
@Harry5573 - Yes this previous commit was only part of the puzzle. Standby for a new PR which completes the picture.

**Comment by Scottmitch** [comment]
@Harry5573 - Also a side note ... currently `io.netty.native.epoll.nettyPackagePrefix` will change to `io.netty.packagePrefix` (we can discuss in the PR). You will also have to append this same prefix to the native library packaged in the Netty jar (to ensure the correct native library is being used).

Assuming `-Dio.netty.packagePrefix=net.minecraft.util."

Then rename `META-INF/native/libnetty-transport-native-epoll.so` to `META-INF/native/libnet-mincraft-util-netty-transport-native-epoll.so`

**Comment by Scottmitch** [comment]
@Harry5573 - Please try PR #4820.

**Comment by MarcMagnin** [comment]
Hi, 

My netty dependencies are (gradle project):
`compile 'io.netty:netty-all:4.1.8.Final'`
`compile 'io.netty:netty-transport-native-epoll:4.1.8.Final:linux-x86_64'`

I'm shading `io.netty` to `io.netty.shadednetty` using shadow plugin and setting `System.setProperty("io.netty.packagePrefix", "io.netty.shadednetty");`

I've rename `libnetty-transport-native-epoll.so` to `libio-netty-shadednetty-netty-transport-native-epoll.so` but I still got a `java.lang.UnsatisfiedLinkError: no io-netty-shadednetty-shadednettynetty-transport-native-epoll in java.library.path`

Any help would be great!
Regards

**Comment by MarcMagnin** [comment]
all good, 
With `relocate 'io.netty', 'shade.io.netty'`, it needed a `System.setProperty("shade.io.netty.packagePrefix", "shade.");` and a rename of `META-INF/native/lib-netty-transport-native-epoll.so` to `META-INF/native/libshade-netty-transport-native-epoll.so`

**Comment by shanky-259** [comment]
@MarcMagnin Hey, I was wondering how you renamed the META-INF entry for `lib-netty-transport-native-epoll.so`. I would appreciate any sort of advice to rename META-INF entries in the bundle using bazel build tool.
