### ISSUE TITLE
java.lang.AssertionError during CI run

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#4823]
```
o.netty.channel.unix.Errors$NativeIoException: syscall:read(...)() failed: Connection reset by peer
------- Stdout: -------
09:42:06.159 [Time-limited test] DEBUG i.n.c.e.EpollSocketTestPermutation - /proc/sys/net/ipv4/tcp_fastopen: 0 (non-existent)
09:42:06.159 [Time-limited test] INFO  i.n.c.epoll.EpollSocketStartTlsTest - Running: testStartTlsNotAutoRead[0: serverEngine = io.netty.handler.ssl.JdkSslServerContext@5b69c34e, clientEngine = io.netty.handler.ssl.JdkSslClientContext@7c9564c4] 1 of 3 (ServerBootstrap(group: EpollEventLoopGroup, channelFactory: EpollServerSocketChannel.class, localAddress: /0:0:0:0:0:0:0:1%1:44532, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}) + Bootstrap(group: EpollEventLoopGroup, channelFactory: EpollSocketChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, remoteAddress: /0:0:0:0:0:0:0:1%1:44532)) with UnpooledByteBufAllocator
09:42:06.168 [testsuite-epoll-worker-11-3] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x5035aedf, L:/0:0:0:0:0:0:0:1%0:44532 - R:/0:0:0:0:0:0:0:1%0:37935] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
09:42:06.169 [testsuite-epoll-worker-11-2] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x97a09ed1, L:/0:0:0:0:0:0:0:0%0:0 - R:0:0:0:0:0:0:0:1%1/0:0:0:0:0:0:0:1:44532] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
09:42:06.210 [Time-limited test] INFO  i.n.c.epoll.EpollSocketStartTlsTest - Running: testStartTlsNotAutoRead[0: serverEngine = io.netty.handler.ssl.JdkSslServerContext@5b69c34e, clientEngine = io.netty.handler.ssl.JdkSslClientContext@7c9564c4] 2 of 3 (ServerBootstrap(group: EpollEventLoopGroup, channelFactory: EpollServerSocketChannel.class, localAddress: /0:0:0:0:0:0:0:1%1:33656, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}) + Bootstrap(group: NioEventLoopGroup, channelFactory: NioSocketChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, remoteAddress: /0:0:0:0:0:0:0:1%1:33656)) with UnpooledByteBufAllocator
09:42:06.219 [testsuite-epoll-worker-11-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xbb6665f7, L:/0:0:0:0:0:0:0:1%0:33656 - R:/0:0:0:0:0:0:0:1%0:53524] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
09:42:06.220 [testsuite-nio-worker-7-2] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xc52187b9, L:/0:0:0:0:0:0:0:1:53524 - R:/0:0:0:0:0:0:0:1%1:33656] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
09:42:06.261 [Time-limited test] INFO  i.n.c.epoll.EpollSocketStartTlsTest - Running: testStartTlsNotAutoRead[0: serverEngine = io.netty.handler.ssl.JdkSslServerContext@5b69c34e, clientEngine = io.netty.handler.ssl.JdkSslClientContext@7c9564c4] 3 of 3 (ServerBootstrap(group: NioEventLoopGroup, channelFactory: NioServerSocketChannel.class, localAddress: /0:0:0:0:0:0:0:1%1:41511, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, childGroup: NioEventLoopGroup, childOptions: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}) + Bootstrap(group: EpollEventLoopGroup, channelFactory: EpollSocketChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, remoteAddress: /0:0:0:0:0:0:0:1%1:41511)) with UnpooledByteBufAllocator
09:42:06.273 [testsuite-nio-worker-7-3] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xb77816a8, L:/0:0:0:0:0:0:0:1:41511 - R:/0:0:0:0:0:0:0:1:46438] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
09:42:06.274 [testsuite-epoll-worker-11-2] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xbfbb4f93, L:/0:0:0:0:0:0:0:0%0:0 - R:0:0:0:0:0:0:0:1%1/0:0:0:0:0:0:0:1:41511] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
09:42:06.313 [Time-limited test] INFO  i.n.c.epoll.EpollSocketStartTlsTest - Running: testStartTlsNotAutoRead[0: serverEngine = io.netty.handler.ssl.JdkSslServerContext@5b69c34e, clientEngine = io.netty.handler.ssl.JdkSslClientContext@7c9564c4] 1 of 3 (ServerBootstrap(group: EpollEventLoopGroup, channelFactory: EpollServerSocketChannel.class, localAddress: /0:0:0:0:0:0:0:1%1:41841, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}) + Bootstrap(group: EpollEventLoopGroup, channelFactory: EpollSocketChannel.class, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, remoteAddress: /0:0:0:0:0:0:0:1%1:41841)) with PooledByteBufAllocator
09:42:06.322 [testsuite-epoll-worker-11-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x528c6464, L:/0:0:0:0:0:0:0:1%0:41841 - R:/0:0:0:0:0:0:0:1%0:57340] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
09:42:06.323 [testsuite-epoll-worker-11-3] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x3fb619cd, L:/0:0:0:0:0:0:0:0%0:0 - R:0:0:0:0:0:0:0:1%1/0:0:0:0:0:0:0:1:41841] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
09:42:06.364 [Time-limited test] INFO  i.n.c.epoll.EpollSocketStartTlsTest - Running: testStartTlsNotAutoRead[0: serverEngine = io.netty.handler.ssl.JdkSslServerContext@5b69c34e, clientEngine = io.netty.handler.ssl.JdkSslClientContext@7c9564c4] 2 of 3 (ServerBootstrap(group: EpollEventLoopGroup, channelFactory: EpollServerSocketChannel.class, localAddress: /0:0:0:0:0:0:0:1%1:36959, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, childGroup: EpollEventLoopGroup, childOptions: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}) + Bootstrap(group: NioEventLoopGroup, channelFactory: NioSocketChannel.class, options: {ALLOCATOR=PooledByteBufAllocator(directByDefault: true)}, remoteAddress: /0:0:0:0:0:0:0:1%1:36959)) with PooledByteBufAllocator
09:42:06.369 [testsuite-nio-worker-7-1] WARN  i.n.u.c.SingleThreadEventExecutor - A task raised an exception.
java.lang.AssertionError: null
    at io.netty.channel.AbstractChannelHandlerContext$8.run(AbstractChannelHandlerContext.java:459) ~[classes/:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339) ~[classes/:na]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356) [classes/:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [classes/:na]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [classes/:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.7.0_79]
09:42:16.372 [defaultEventExecutorGroup-24-2] WARN  i.n.t.t.socket.SocketStartTlsTest - Unexpected exception from the server side
io.netty.channel.unix.Errors$NativeIoException: syscall:read(...)() failed: Connection reset by peer
------- Stderr: -------
[jetty-alpn-agent] Replacing: sun/security/ssl/Alerts
```

**Comment by normanmaurer** [comment]
not sure yet how this can happen though....

**Comment by normanmaurer** [comment]
Actually I think I know what is the problem... working on a fix, which is tricky...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/4863
