### ISSUE TITLE
Consider making Snappy class public

### ISSUE THREAD

**Issue by trustin** [netty/netty#4892]
Maybe useful for users who want to use Snappy compression without handlers? (like Base64 in Netty)

https://groups.google.com/d/topic/netty/I8-M02b2ghg/discussion

**Comment by normanmaurer** [comment]
@trustin will take care.

**Comment by trustin** [comment]
Thanks, @normanmaurer

**Comment by AshwinJay** [comment]
Thank you very much!

**Comment by AshwinJay** [comment]
@trustin and @normanmaurer I was trying to use the Snappy codec and it seems to me that the limit to the input `ByteBuf` is 36KB. Beyond this, the codec throws an `IndexOutOfBoundsException`. Is there an undocumented limit to the input size?

```java
java.lang.ArrayIndexOutOfBoundsException: -30567

	at io.netty.buffer.HeapByteBufUtil.getInt(HeapByteBufUtil.java:48)
	at io.netty.buffer.UnpooledHeapByteBuf._getInt(UnpooledHeapByteBuf.java:378)
	at io.netty.buffer.UnpooledHeapByteBuf.getInt(UnpooledHeapByteBuf.java:373)
	at io.netty.handler.codec.compression.Snappy.encode(Snappy.java:103)
	at io.jarasandha.util.io.NettySnappyBug.compressUsingNetty(NettySnappyBug.java:51)
	at io.jarasandha.util.io.NettySnappyBug.testSnappy(NettySnappyBug.java:30)
```

```java
import io.netty.buffer.ByteBuf;
import io.netty.buffer.ByteBufAllocator;
import io.netty.buffer.Unpooled;
import io.netty.handler.codec.compression.Snappy;
import org.junit.Test;

import java.util.Random;

import static java.lang.String.format;

/**
 * Created by ashwin.jayaprakash on 9/11/16.
 */
public class NettySnappyBug {
    @Test
    public void testSnappy() {
        for (int multiplier = 1; multiplier < 125; multiplier++) {
            System.out.println("Trying out input size [" + multiplier + "]");

            byte[] bytes = new byte[multiplier * 1024];
            Random random = new Random();
            random.nextBytes(bytes);

            ByteBuf uncompressedByteBuf = Unpooled.wrappedBuffer(bytes);
            ByteBuf compressedByteBuf = null;
            try {
                compressedByteBuf = compressUsingNetty(ByteBufAllocator.DEFAULT, uncompressedByteBuf);
                System.out.println(format("Raw bytes [%s], compressed [%s]",
                        bytes.length, compressedByteBuf.readableBytes()));
            } finally {
                try {
                    uncompressedByteBuf.release();
                } finally {
                    if (compressedByteBuf != null) {
                        compressedByteBuf.release();
                    }
                }
            }

            System.out.println();
        }
    }

    private static ByteBuf compressUsingNetty(ByteBufAllocator allocator, ByteBuf rawByteBuf) {
        final Snappy snappy = new Snappy();
        final ByteBuf compressedByteBuf = allocator.buffer();
        try {
            snappy.encode(rawByteBuf, compressedByteBuf, rawByteBuf.readableBytes());
        } catch (Throwable t) {
            compressedByteBuf.release();
            throw t;
        }
        return compressedByteBuf;
    }
}
```

Have I made a wrong assumption about the API?

Thanks.

**Comment by AshwinJay** [comment]
I guess I can answer my own question. I see here that the slice length is always at Short.MAX_VALUE:
https://github.com/netty/netty/blob/83c349ffa94d3992c4ee511d3625afc0c97c12bb/codec/src/main/java/io/netty/handler/codec/compression/SnappyFrameEncoder.java#L71
