### ISSUE TITLE
netty jdk 1.8 window x86_64  compile error

### ISSUE THREAD

**Issue by jiang2015** [netty/netty#4904]
netty jdk 1.8 window x86_64  compile error message is :

F:\workspace\netty-4.1>java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

F:\workspace\netty-4.1>mvn clean install -Dmaven.test.skip
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.netty:netty-tests
uite-osgi:jar:4.1.0.CR4-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.ops4j.pax.exam:maven-paxexam-plugin is missing. @ l
ine 220, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your
 build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed pro
jects.
[WARNING]
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: windows-x86_64
[WARNING] Failed to inject repository session properties.
java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/ecli
pse/aether/RepositorySystemSession;
        at kr.motd.maven.os.RepositorySessionInjector.injectRepositorySession(RepositorySessionInjec
tor.java:22)
        at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:148)
        at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:107)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: windows
[INFO] os.detected.arch: x86_64
[INFO] os.detected.classifier: windows-x86_64
---------------------------------------------------
constituent[0]: file:/F:/work/soft/apache-maven-3.0.5/lib/aether-api-1.13.1.jar
constituent[1]: file:/F:/work/soft/apache-maven-3.0.5/lib/aether-connector-wagon-1.13.1.jar
constituent[2]: file:/F:/work/soft/apache-maven-3.0.5/lib/aether-impl-1.13.1.jar
constituent[3]: file:/F:/work/soft/apache-maven-3.0.5/lib/aether-spi-1.13.1.jar
constituent[4]: file:/F:/work/soft/apache-maven-3.0.5/lib/aether-util-1.13.1.jar
constituent[5]: file:/F:/work/soft/apache-maven-3.0.5/lib/commons-cli-1.2.jar
constituent[6]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-aether-provider-3.0.5.jar
constituent[7]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-artifact-3.0.5.jar
constituent[8]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-compat-3.0.5.jar
constituent[9]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-core-3.0.5.jar
constituent[10]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-embedder-3.0.5.jar
constituent[11]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-model-3.0.5.jar
constituent[12]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-model-builder-3.0.5.jar
constituent[13]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-plugin-api-3.0.5.jar
constituent[14]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-repository-metadata-3.0.5.jar
constituent[15]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-settings-3.0.5.jar
constituent[16]: file:/F:/work/soft/apache-maven-3.0.5/lib/maven-settings-builder-3.0.5.jar
constituent[17]: file:/F:/work/soft/apache-maven-3.0.5/lib/plexus-cipher-1.7.jar
constituent[18]: file:/F:/work/soft/apache-maven-3.0.5/lib/plexus-component-annotations-1.5.5.jar
constituent[19]: file:/F:/work/soft/apache-maven-3.0.5/lib/plexus-interpolation-1.14.jar
constituent[20]: file:/F:/work/soft/apache-maven-3.0.5/lib/plexus-sec-dispatcher-1.3.jar
constituent[21]: file:/F:/work/soft/apache-maven-3.0.5/lib/plexus-utils-2.0.6.jar
constituent[22]: file:/F:/work/soft/apache-maven-3.0.5/lib/sisu-guava-0.9.9.jar
constituent[23]: file:/F:/work/soft/apache-maven-3.0.5/lib/sisu-guice-3.1.0-no_aop.jar
constituent[24]: file:/F:/work/soft/apache-maven-3.0.5/lib/sisu-inject-bean-2.3.0.jar
constituent[25]: file:/F:/work/soft/apache-maven-3.0.5/lib/sisu-inject-plexus-2.3.0.jar
constituent[26]: file:/F:/work/soft/apache-maven-3.0.5/lib/wagon-file-2.4.jar
constituent[27]: file:/F:/work/soft/apache-maven-3.0.5/lib/wagon-http-2.4-shaded.jar
constituent[28]: file:/F:/work/soft/apache-maven-3.0.5/lib/wagon-provider-api-2.4.jar
---------------------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/aether/RepositorySystemSessio
n
        at kr.motd.maven.os.DetectExtension.injectSession(DetectExtension.java:115)
        at kr.motd.maven.os.DetectExtension.afterProjectsRead(DetectExtension.java:92)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.RepositorySystemSession
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.ja
va:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
        ... 15 more

**Comment by darionyaphet** [comment]
maybe `mvn clean install -DskipTests` ?

**Comment by jiang2015** [comment]
i have deal with this problem，use maven 3.3.9  maven project problem

**Comment by trustin** [comment]
Yep, it happens with old Maven versions.

**Comment by OrangeDog** [comment]
See also https://github.com/trustin/os-maven-plugin/issues/21
