### ISSUE TITLE
[WebSocket] o.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:5

### ISSUE THREAD

**Issue by BorisKourt** [netty/netty#4957]
Hello,

I am getting the following:

```
WARNING: error in websocket handler
io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:5
```

From this request:

```clj
"host" "192.168.0.100",
"upgrade" "websocket",
"user-agent" "arduino-WebSocket-Client",
"sec-websocket-protocol" "arduino",
"connection" "Upgrade",
"sec-websocket-key" "i8CA6i/CaJ2D/TgcvnJs5w==",
"sec-websocket-version" "13"
```

I stumbled on this issue from searching: https://github.com/netty/netty/issues/2953 But it doesn't look like it fits, as there are no Extensions specified in the request?

I am trying to establish a WebSocket connection via the following Arduino/esp8266 library: https://github.com/Links2004/arduinoWebSockets

This has stumped me for a while now, as I am not sure how to debug this further. Is there something wrong with the way that request was issued, or is it missing something? 

Thank you for any help.

***
Stack Trace
```dtrace
WARNING: error in websocket handler
io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:5
    at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412)
    at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:188)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
    at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
    at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by normanmaurer** [comment]
@BorisKourt You should configure your `WebSocketServerHandshakerFactory` to allow extensions. It is a constructor param (default to false).
