### ISSUE TITLE
IOOBE in DefaultDnsRecordDecoder#decodeName

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5014]
Netty 4.1.0-CR4/Final-SNAPSHOT

I'm opening a PR for a Unit Test shortly.

```
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(63) + length(1) exceeds writerIndex(63): PooledUnsafeDirectByteBuf(ridx: 63, widx: 63, cap: 4096)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[classes/:na]
	at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83) ~[classes/:na]
	at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154) [classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354) [classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145) [classes/:na]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078) [classes/:na]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:94) [classes/:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510) [classes/:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467) [classes/:na]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381) [classes/:na]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353) [classes/:na]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [classes/:na]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [classes/:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(63) + length(1) exceeds writerIndex(63): PooledUnsafeDirectByteBuf(ridx: 63, widx: 63, cap: 4096)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1346) ~[classes/:na]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:648) ~[classes/:na]
	at io.netty.buffer.AbstractByteBuf.readUnsignedByte(AbstractByteBuf.java:662) ~[classes/:na]
	at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeName(DefaultDnsRecordDecoder.java:111) ~[classes/:na]
	at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeRecord(DefaultDnsRecordDecoder.java:46) ~[classes/:na]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decodeRecords(DatagramDnsResponseDecoder.java:109) ~[classes/:na]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:66) ~[classes/:na]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:1) ~[classes/:na]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[classes/:na]
	... 13 common frames omitted
```

**Comment by normanmaurer** [comment]
working on a fix

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5017
