### ISSUE TITLE
operationComplete never call

### ISSUE THREAD

**Issue by hbyscpp** [netty/netty#5032]
hi normanmaurer,

sometimes  operationComplete never call

code is like below:
     ChannelFuture writeFuture = ch.writeAndFlush(req);
		writeFuture.addListener(new ChannelFutureListener() {
			@Override
			public void operationComplete(ChannelFuture future)
					throws Exception {
				if (future.isCancelled()) {
					 System.out.println("cancel");
					return;
				}
				if (future.cause() != null) {
					 System.out.println("failure");
					return;
				}
				if (future.isSuccess()) {
                                       System.out.println("success");
}

	}

"hamster-client-io-pool-worker-2-thread-3" prio=10 tid=0x00007f6468003800 nid=0x3637 runnable [0x00007f64e05f1000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x000000078c82b718> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000078c82b778> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000078c82b680> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:621)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)

i use btrace watch,operationComplete never call. ch is active. no deadlock，server does not receive request，Thanks！

netty version is 4.1.0.CR2

**Comment by normanmaurer** [comment]
@hbyscpp can you share a full reproducer ?

**Comment by normanmaurer** [comment]
Please reopen with more info
