### ISSUE TITLE
ApplicationProtocolNegotiationHandler doesn't work with SniHandler

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5066]
Netty 4.1.0.Final-SNAPSHOT

The `ApplicationProtocolNegotiationHandler` is expecting the `SslHandler` to be present at pipeline construction time (see `#handlerAdded(...)`) and consequently fails with the `SniHandler` because it's adding it at a later point in time.

```java
Caused by: java.lang.IllegalStateException: cannot find a SslHandler in the pipeline (required for application-level protocol negotiation)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.handlerAdded(ApplicationProtocolNegotiationHandler.java:85) ~[netty-all-4.1.0.Final-SNAPSHOT.jar:4.1.0.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:723) [netty-all-4.1.0.Final-SNAPSHOT.jar:4.1.0.Final-SNAPSHOT]
	... 19 common frames omitted
```

IMHO that whole block of code can be moved into `userEventTriggered()`

```java
@Override
public void userEventTriggered(ChannelHandlerContext ctx, Object evt) throws Exception {
  if (evt instanceof SslHandshakeCompletionEvent) {
    if (sslHandler == null) {
      final SslHandler sslHandler = ctx.pipeline().get(SslHandler.class);
      if (sslHandler == null) {
        throw new IllegalStateException("cannot find a SslHandler in the pipeline (required for application-level protocol negotiation)");
      }
      this.sslHandler = sslHandler;
    }

    ctx.pipeline().remove(this);
    // ...
  }
}
```

**Comment by Scottmitch** [comment]
thanks for reporting @rkapsi - let me take care

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5077
