### ISSUE TITLE
All worker threads waiting for addBefore task to finish

### ISSUE THREAD

**Issue by flozano** [netty/netty#5104]
Netty 4.1.0.CR6
JDK 1.8.0_20
Linux 2.6.32-431.el6.x86_64

The EventLoopGroup size is 2.
In our code we try to add an idleStateHandler

```java
channel.pipeline().addBefore(ChannelHandlerConstant.MQTT_DECODER_HANDLER_NAME,
						ChannelHandlerConstant.KEEP_ALIVE_TIMER_HANDLER_NAME, idleStateHandler);
```

And, since upgraded to CR6, quickly all the threads are locked like this:

```
"mqtt-netty-worker-3-2" #37 prio=5 os_prio=0 tid=0x00007fb085424800 nid=0x14fa in Object.wait() [0x00007fb0517b7000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:502)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:255)
    - locked <0x00000000e6dd0a98> (a io.netty.util.concurrent.PromiseTask)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:33)
    at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:32)
    at io.netty.channel.DefaultChannelPipeline.waitForFuture(DefaultChannelPipeline.java:783)
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:300)
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)

"mqtt-netty-worker-3-1" #36 prio=5 os_prio=0 tid=0x00007fb085422800 nid=0x14f9 in Object.wait() [0x00007fb0518b8000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:502)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:255)
    - locked <0x00000000e6dd0d38> (a io.netty.util.concurrent.PromiseTask)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:33)
    at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:32)
    at io.netty.channel.DefaultChannelPipeline.waitForFuture(DefaultChannelPipeline.java:783)
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:300)
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
(...)
```

It doesn't reproduce in the previous netty version we used (4.1.0.Beta8).

**Comment by normanmaurer** [comment]
@flozano can you show me the code where you add the handler ?

**Comment by flozano** [comment]
Sure, here it is:
```java
	public void setIdleTimeSeconds(int idleTimeSeconds) {
		if (idleTimeSeconds > 0) {
			IdleStateHandler idleStateHandler = new IdleStateHandler(idleTimeSeconds, 0, 0);

			try {
				channel.pipeline().remove(ChannelHandlerConstant.KEEP_ALIVE_TIMER_HANDLER_NAME);
			} catch (NoSuchElementException e) {
				// Should happen
			}

			try {
				channel.pipeline().addBefore(ChannelHandlerConstant.MQTT_DECODER_HANDLER_NAME,
						ChannelHandlerConstant.KEEP_ALIVE_TIMER_HANDLER_NAME, idleStateHandler);
				LOGGER.debug("Added IdleStateHandler (channel={}, idleTimeSeconds={})", this, idleTimeSeconds);
			} catch (NoSuchElementException e) {
				// Should not happen
				LOGGER.error("Could not add IdleStateHandler: {} (channel={})", e.getMessage(), channel);
			}
		}
	}
```
```java

```

**Comment by normanmaurer** [comment]
@flozano quick question. Is this done from the EventLoop thread or not ?

**Comment by normanmaurer** [comment]
also was the "ChannelHandlerConstant.MQTT_DECODER_HANDLER_NAME" added with a custom ChannelHandlerInvoker or EventExecutorGroup.

**Comment by normanmaurer** [comment]
@flozano also when you say these are locked are these never recover ?

**Comment by flozano** [comment]
Yes, the full stack-trace shows `setIdle` as invoked in threads `mqtt-netty-worker-3-1` and `mqtt-netty-worker-3-2.`, which are the NioEventLoopGroup threads:
```java
return new NioEventLoopGroup(0, new DefaultThreadFactory("mqtt-netty-worker"));
```

the `` was added in the ChannelInitializer as:
```java
p.addLast(MQTT_DECODER_HANDLER_NAME, new MqttDecoder(brokerSettings.getMaxPayloadSize()));
```
so nothing special there either.

**Comment by flozano** [comment]
> @flozano also when you say these are locked are these never recover ?

Yeah, no recovery in sight, the server gets fully locked.

**Comment by flozano** [comment]
This is full stack-trace of one of the locked threads:
```
"mqtt-netty-worker-3-2" #37 prio=5 os_prio=0 tid=0x00007fb085424800 nid=0x14fa in Object.wait() [0x00007fb0517b7000]
   java.lang.Thread.State: WAITING (on object monitor)
    at java.lang.Object.wait(Native Method)
    at java.lang.Object.wait(Object.java:502)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:255)
    - locked <0x00000000e6dd0a98> (a io.netty.util.concurrent.PromiseTask)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:33)
    at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:32)
    at io.netty.channel.DefaultChannelPipeline.waitForFuture(DefaultChannelPipeline.java:783)
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:300)
    at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:248)
    at com.my.server.common.ClientChannel.setIdleTimeSeconds(ClientChannel.java:355)
    at com.my.server.impl.MQTTProtocolProcessorImpl.lambda$processConnect$182(MQTTProtocolProcessorImpl.java:219)
    at com.my.server.impl.MQTTProtocolProcessorImpl$$Lambda$48/395923385.accept(Unknown Source)
    at java.util.concurrent.CompletableFuture.doWhenComplete(CompletableFuture.java:2048)
    at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2563)
    at com.my.server.impl.MQTTProtocolProcessorImpl.processConnect(MQTTProtocolProcessorImpl.java:196)
    at com.my.server.impl.MQTTProtocolProcessorImpl.lambda$onMessage$172(MQTTProtocolProcessorImpl.java:72)
    at com.my.server.impl.MQTTProtocolProcessorImpl$$Lambda$46/1016023276.run(Unknown Source)
    at com.my.server.executor.impl.QueueOnChannelTaskExecutorImpl$InternalChannelTask.run(QueueOnChannelTaskExecutorImpl.java:103)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:73)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:373)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by normanmaurer** [comment]
@flozano I tried to reproduce here but no luck with a unit test. Any way I can reproduce this easily ?

**Comment by flozano** [comment]
We haven't isolated the issue yet I'm afraid, we can try

**Comment by jorcasso** [comment]
I found that the issue occurs as of version 4.1.0.CR3, in version 4.1.0.CR2 it is working fine.

**Comment by normanmaurer** [comment]
@flozano from the stack trace may it be possible that while the thread is an EventLoop thread it may be possible that the addBefore(...) call is done in an EventLoop that not belongs to the Channel and so it's pipeline ?

**Comment by jorcasso** [comment]
We have only one eventLoop instance in the server for the worker threads, so I think is not possible that the Channel belongs to another one.

**Comment by normanmaurer** [comment]
@johnou this is strange as the posted stack can only happen when the pipeline operation is executed from outside the EventLoop that belongs to it. And from what @flozano said you have 2 threads.

**Comment by normanmaurer** [comment]
I think I can reproduce it here...

**Comment by normanmaurer** [comment]
@flozano can you try to alter the code to:

```java
public void setIdleTimeSeconds(int idleTimeSeconds) {
        channel.eventLoop().execute(() -> {
            if (idleTimeSeconds > 0) {
                IdleStateHandler idleStateHandler = new IdleStateHandler(idleTimeSeconds, 0, 0);

                try {
                    channel.pipeline().remove(ChannelHandlerConstant.KEEP_ALIVE_TIMER_HANDLER_NAME);
                } catch (NoSuchElementException e) {
                    // Should happen
                }

                try {
                    channel.pipeline().addBefore(ChannelHandlerConstant.MQTT_DECODER_HANDLER_NAME,
                            ChannelHandlerConstant.KEEP_ALIVE_TIMER_HANDLER_NAME, idleStateHandler);
                    LOGGER.debug("Added IdleStateHandler (channel={}, idleTimeSeconds={})", this, idleTimeSeconds);
                } catch (NoSuchElementException e) {
                    // Should not happen
                    LOGGER.error("Could not add IdleStateHandler: {} (channel={})", e.getMessage(), channel);
                }
            }
        });
    }
```

**Comment by jorcasso** [comment]
@normanmaurer with that modification the issue does not reproduce

**Comment by normanmaurer** [comment]
@jorcasso ok that is what I expected... So let me think of a good way to fix it. On a related not writing concurrent code is hard :(

**Comment by flozano** [comment]
cool, thanks. With this condition, is it safe to use CR6 if we only modify the pipeline by submitting stuff to `channel.eventLoop().execute(`?

**Comment by normanmaurer** [comment]
Yep

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5110

**Comment by neeraj20gupta** [comment]
@normanmaurer Is this issue only present in 4.1.0 CR6 release or in 4.0.36 as well? We are facing a similar scenario with 4.0.36.

**Comment by normanmaurer** [comment]
@neeraj20gupta in 4.0.36 as well. Will release 4.0.37.Final this week.

**Comment by neeraj20gupta** [comment]
cool, thanks.

**Comment by neeraj20gupta** [comment]
@normanmaurer 
However in my case the threads do recover back. While running benchmarks on the server we observed that for most duration EventLoopGroup worker threads are in wait state.

Please see the attached snapshot from visual VM. Netty Worker threads
![nettywait](https://cloud.githubusercontent.com/assets/13968394/15535821/9ef28854-228c-11e6-92c0-a49786b5561e.png)

I am not sure that if this is the desired behavior?
Netty version 4.0.36

**Comment by piweiwen** [comment]
"HandshakeBatchTimer0" prio=10 tid=0x00007f8350329000 nid=0x6d41 in Object.wait() [0x00007f833ce33000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:503)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:255)
	- locked <0x0000000605e8dec0> (a io.netty.util.concurrent.PromiseTask)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:33)
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:32)
	at io.netty.channel.DefaultChannelPipeline.waitForFuture(DefaultChannelPipeline.java:667)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:558)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:509)
	at com.suning.pushservice.ps.device.HandshakeHandler.batchHandler(HandshakeHandler.java:175)
	at com.suning.pushservice.ps.device.AbstractBatchHandler$InternalHandler.processInterval(AbstractBatchHandler.java:200)
	at com.suning.pushservice.ps.device.AbstractBatchHandler$InternalHandler.access$400(AbstractBatchHandler.java:128)
	at com.suning.pushservice.ps.device.AbstractBatchHandler$InternalHandler$1.run(AbstractBatchHandler.java:151)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)

I am not sure that if this is the same issue 
Netty version 4.0.36
