### ISSUE TITLE
netty-transport-native-epoll-*-linux-x86_64.jar is not OSGi bundle

### ISSUE THREAD

**Issue by MilosFabian** [netty/netty#5119]
Hello,
basically, reopening https://github.com/netty/netty/issues/3781
I am working on OpenDaylight project and we would like use netty-transport-native-epoll due to the TCP MD5 signature support. Currently we are using Netty version 4.0.33.Final and bumping to 4.0.36.Final right now.
Unfortunately, netty-transport-native-epoll-*-linux-x86_64.jar is not a bundle and since the OpenDaylight is running in OSGi container (Apache Karaf) we are not able use it directly as a bundle (like other Netty artifacts).
It would be great for us if the jar is packed as a bundle as well.

Thanks,
Milos Fabian

**Comment by normanmaurer** [comment]
@MilosFabian we love PRs.. so maybe you can provide one as I don't have any good OSGI knowledge :(

**Comment by MilosFabian** [comment]
Alright, I will work on it :)

**Comment by normanmaurer** [comment]
Thanks ❤️!

**Comment by MilosFabian** [comment]
I am sorry for a delay...finally I found some time take a look at it.
I managed produce bundle (include manifest in jar) for netty-transport-native-epoll-*-linux-x86_64
However, when I was trying to use the bundle in OSGi (Apache Karaf) I hit a problem when loading native library.
The Epoll.isAvailable() returns false with following unavailability cause.

java.lang.ClassNotFoundException: io.netty.channel.epoll.NativeStaticallyReferencedJniMethods
	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_45]
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)[:1.8.0_45]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1937)[:1.8.0_45]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1822)[:1.8.0_45]
	at java.lang.Runtime.load0(Runtime.java:809)[:1.8.0_45]
	at java.lang.System.load(System.java:1086)[:1.8.0_45]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:214)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:261)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:62)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33)

More investigation needed.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5326
