### ISSUE TITLE
SSLHandler OutOfMemory - Direct buffer

### ISSUE THREAD

**Issue by talbs1986** [netty/netty#5120]
Hi ,

we are keep having direct memory buffer issues with netty 4.0.x . 
in the below stack you can see us using version 36 but it happens for 33 as well.

we use netty as our network layer to receive websocket frames from the client app,
as you can see below, our pipeline is basic ssl , http and our handler.
in the handler we release every frame we receive. we do not use ByteBuffer.directAlocate() anywhere in our code except internal netty usage.

this issue keeps happening in unknown times at our application , but they do not occur immediately, for instance can be happening after 1 day / 3 days / etc ....  

can you please advise on how to proceed ?

Details - 
```
-XX:MaxDirectMemorySize=1G
Netty : 4.0.36
Jdk : 1.8.0.45
```

Pipeline -
```
@Override
	public void initChannel(final Channel ch) throws Exception {

		ChannelPipeline pipeline = ch.pipeline();

                //SSLEngine is native Jdk
		SSLEngine engine = WebSocketSslServerSslContext.getInstance().getServerContext().createSSLEngine();
		engine.setUseClientMode(false);
		SslHandler sslHandler = new SslHandler(engine);

		pipeline.addLast("ssl", sslHandler);
		pipeline.addLast("decoder", new HttpRequestDecoder());
		pipeline.addLast("aggregator", new HttpObjectAggregator(65536));
		pipeline.addLast("encoder", new HttpResponseEncoder());
		pipeline.addLast("handler", webSocketHandler); // our handler
	}
```

Handler -

```
public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
		try {
			if (msg instanceof FullHttpRequest) {
				FullHttpRequest req = (FullHttpRequest) msg;
				handleHttpShakeHand(ctx, req);
				req.release();
			}
			else if (msg instanceof WebSocketFrame) {
                            try {
				handleWebSocketFrame(ctx, (WebSocketFrame) msg);
                             }
                             finally {
                                   ( (WebSocketFrame) msg).release();
                             }
			}
		}
		catch (Throwable t) {
			logger.error("error: ", t);
		}
	}
```

Stack -
```
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:658) ~[?:1.8.0_45]
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123) ~[?:1.8.0_45]
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311) ~[?:1.8.0_45]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.allocateDirect(UnpooledUnsafeDirectByteBuf.java:106) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:67) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:51) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:177) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:168) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:105) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1461) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:1471) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:523) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:501) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:649) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:630) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:649) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:32) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:957) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:889) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
```

**Comment by Scottmitch** [comment]
Can you provide a heap dump while you are in this state?

Also are you able to reproduce in a controlled environment and/or run with a [higher leak detector level](http://netty.io/wiki/reference-counted-objects.html#leak-detection-levels)?

**Comment by normanmaurer** [comment]
Drom the stack it looks like you may write to fast and not take Channel.isWritable() into account

**Comment by talbs1986** [comment]
thanks for the quick replies ! :D 

@Scottmitch 
unfortunately we cannot reproduce it in controlled environment, we tried "bombing" the network layer with messages but that doesnt seem to do the trick.
we have added the netty LeakDetector=advanced flag now and waiting for it to happen again .. :/
when it will ill post the results.

@normanmaurer 
no we do not use the isWritable, should it matter ? 
im guessing that if the channel is not currently writable then different error would be produced other than creating a buffer and trying to send it thru the wire... 

what are the best practices in case channel isnt writable and the message needs to be sent ?

**Comment by Scottmitch** [comment]
> no we do not use the isWritable, should it matter ? 

@talbs1986 - Yes. An extreme example to demonstrate when not taking this into account can cause problems: What if your peer just writes data, and never reads? The more typical example is you have a mismatch in bandwidth and your server generates data much faster than your peer reads that data. Either way the solution will depend on what your use case will tolerate but some form of back pressure should be applied (server stop reading until channel is writable, send error and close connection, etc...)

**Comment by talbs1986** [comment]
@Scottmitch 
thanks for the explanation, however farther reviewing our code , i do see a use of isWritable() , but it happens not exactly before the actual ctx writeAndFlush and if returns false then we only write to a log file , which we do not find any trace of this log line.
i.e
```
public void sendMessage(ChannelHandlerContext ctx,String msg) {
         if (!ctx.channel().isWritable())
             logger.debug("Channel isnt writable for msg={}",msg);

         sendMessageToNetwork(ctx,msg);
}

private void sendMessageToNetwork(ChannelHandlerContext ctx,String msg) {
         TextWebSocketFrame txtFrame = new TextWebSocketFrame(msg);
	  ChannelFuture future = ctx.writeAndFlush(txtFrame);
          future.addListener(new ChannelFutureListener() {

				@Override
				public void operationComplete(ChannelFuture arg0) throws Exception {
					if (arg0 != null) {
						Throwable cause = arg0.cause();
						if (cause != null) {
								logger.info("closing channel: " + sessionId);
								channel.close();
						}
					}
				}
			});
}
```

**Comment by talbs1986** [comment]
update:
the same exception has happened last night , leakDetector was set to advanced but not nothing got printed by the logger.

**Comment by Scottmitch** [comment]
@talbs1986 - Please provide a heap dump while in this condition. Since it sounds as though you have no back pressure mechanism is the amount of `ChannelOutboundBuffer$Entry` objects abnormally high?

**Comment by talbs1986** [comment]
Closing.

seems like @Scottmitch  were right , it was due to back pressure, the issue was easily reproduced after adding Therad.sleep(10_000) for each received message on the client side.

noticed that using channel.isWritable() is not the correct approach for us , as the channel might not be writable but it wont cause the OutOfMemory error when trying to write and the message still needs to be sent to the client asap.
