### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.lang.NoSuchMethodError: io.netty.util.internal.AppendableCharSequence.charAtUnsafe(I)C

### ISSUE THREAD

**Issue by cmoulliard** [netty/netty#5225]
This error is reported by Netty 4.0.27 when a GET HTTP request is processed

````
[d #0 - NettyEventExecutorGroup] NettyHttpConsumer              WARN  HttpServerChannelHandler is not found as attachment to handle exception, send 404 back to the client.
io.netty.handler.codec.DecoderException: java.lang.NoSuchMethodError: io.netty.util.internal.AppendableCharSequence.charAtUnsafe(I)C
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:229)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:339)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:324)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:847)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: io.netty.util.internal.AppendableCharSequence.charAtUnsafe(I)C
	at io.netty.handler.codec.http.HttpObjectDecoder.findNonWhitespace(HttpObjectDecoder.java:740)
	at io.netty.handler.codec.http.HttpObjectDecoder.splitInitialLine(HttpObjectDecoder.java:690)
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:207)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:315)
	... 11 more
````

**Comment by slandelle** [comment]
Are you sure you're not mixing artifacts with different versions?

**Comment by cmoulliard** [comment]
No.

```
mvn dependency:tree | grep netty
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[INFO] +- org.apache.camel:camel-netty4-http:jar:2.15.1.redhat-621084:compile
[INFO] |  +- org.apache.camel:camel-netty4:jar:2.15.1.redhat-621084:compile
[INFO] |  |  +- io.netty:netty-codec:jar:4.0.27.Final:compile
[INFO] |  |  +- io.netty:netty-transport:jar:4.0.27.Final:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.0.27.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.0.27.Final:compile
[INFO] |  |  \- io.netty:netty-common:jar:4.0.27.Final:compile
[INFO] |  \- io.netty:netty-codec-http:jar:4.0.32.Final:compile
```

**Comment by slandelle** [comment]
Yes you do: io.netty:netty-codec-http:jar:**4.0.32**.Final:compile

**Comment by normanmaurer** [comment]
@cmoulliard as @slandelle pointed out you must not mix different version of netty.

**Comment by abhowmik** [comment]
I have a similar issue but not sure if the codec is a problem but I do get the same error
mvn dependency:tree | grep netty
[INFO] +- io.jooby:jooby-netty:jar:2.9.1:compile
[INFO] |  +- io.netty:netty-handler:jar:4.1.45.Final:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.45.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.45.Final:compile
[INFO] |  |  +- io.netty:netty-transport:jar:4.1.45.Final:compile
[INFO] |  |  |  \- io.netty:netty-resolver:jar:4.1.45.Final:compile
[INFO] |  |  \- io.netty:netty-codec:jar:4.1.45.Final:compile
[INFO] |  +- io.netty:netty-codec-http:jar:4.1.52.Final:compile
[INFO] |  \- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.52.Final:compile
[INFO] |     \- io.netty:netty-transport-native-unix-common:jar:4.1.52.Final:compile

Does that mean I have to remove [INFO] |  +- io.netty:netty-codec-http:jar:4.1.52.Final:compile?

**Comment by chrisvest** [comment]
@abhowmik 

> Does that mean I have to remove [INFO] | +- io.netty:netty-codec-http:jar:4.1.52.Final:compile?

That, or you could upgrade all of them to 4.1.52.
