### ISSUE TITLE
PooledByteBufAllocatorTest.testNumThreadCachesWithNoDirectArenas test failure

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5227]
Discovered on a build of PR https://github.com/netty/netty/pull/5204

https://garage.netty.io/teamcity/viewLog.html?buildId=8205&buildTypeId=pulls_netty&tab=buildLog#_focus=5836

```
[17:17:59][io.netty:netty-buffer] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 213.671 sec <<< FAILURE! - in io.netty.buffer.PooledByteBufAllocatorTest
[17:17:59][io.netty:netty-buffer] testNumThreadCachesWithNoDirectArenas(io.netty.buffer.PooledByteBufAllocatorTest)  Time elapsed: 0.268 sec  <<< FAILURE!
[17:17:59][io.netty:netty-buffer] java.lang.AssertionError: expected:<1> but was:<0>
[17:17:59][io.netty:netty-buffer] 	at org.junit.Assert.fail(Assert.java:88)
[17:17:59][io.netty:netty-buffer] 	at org.junit.Assert.failNotEquals(Assert.java:834)
[17:17:59][io.netty:netty-buffer] 	at org.junit.Assert.assertEquals(Assert.java:645)
[17:17:59][io.netty:netty-buffer] 	at org.junit.Assert.assertEquals(Assert.java:631)
[17:17:59][io.netty:netty-buffer] 	at io.netty.buffer.PooledByteBufAllocatorTest.testNumThreadCachesWithNoDirectArenas(PooledByteBufAllocatorTest.java:135)
[17:17:59][io.netty:netty-buffer] 
[17:17:59][io.netty:netty-buffer] Running io.netty.buffer.FixedCompositeByteBufTest
[17:17:59][io.netty:netty-buffer] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec - in io.netty.buffer.FixedCompositeByteBufTest
[17:17:59][io.netty:netty-buffer] Running io.netty.buffer.BigEndianCompositeByteBufTest
[17:18:00][io.netty:netty-buffer] io.netty.buffer.PooledByteBufAllocatorTest
[17:18:00][io.netty.buffer.PooledByteBufAllocatorTest] testNumThreadCachesWithNoDirectArenas
[17:18:00][testNumThreadCachesWithNoDirectArenas] java.lang.AssertionError: expected:<1> but was:<0>
[17:18:00]
[testNumThreadCachesWithNoDirectArenas] java.lang.AssertionError: expected:<1> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at io.netty.buffer.PooledByteBufAllocatorTest.testNumThreadCachesWithNoDirectArenas(PooledByteBufAllocatorTest.java:135)
```

**Comment by Scottmitch** [comment]
@normanmaurer - can you take a look?

**Comment by normanmaurer** [comment]
@Scottmitch yep yep

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5241
