### ISSUE TITLE
io.netty.handler.ssl.JdkSslRenegotiateTest.testRenegotiateServer test failure

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#5254]
Found while building a PR:

```
Stacktraces:
(new) io.netty.handler.ssl.JdkSslRenegotiateTest.testRenegotiateServer
org.junit.runners.model.TestTimedOutException: test timed out after 5000 milliseconds
    at sun.misc.Unsafe.park(Native Method)
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:994)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1303)
    at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:236)
    at io.netty.handler.ssl.RenegotiateTest.testRenegotiateServer(RenegotiateTest.java:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
    at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.lang.Thread.run(Thread.java:745)
------- Stdout: -------
06:51:13.058 [Time-limited test] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
06:51:13.137 [Time-limited test] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x973feda4f764fe10 (took 3 ms)
06:51:14.313 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
06:51:14.319 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
06:51:14.320 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
06:51:14.322 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
06:51:14.326 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent - Java version: 7
06:51:14.326 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
06:51:14.326 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
06:51:14.341 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
06:51:14.644 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent - Javassist: available
06:51:14.645 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
06:51:14.646 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
06:51:14.647 [Time-limited test] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
06:51:14.678 [Time-limited test] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
06:51:14.684 [Time-limited test] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
06:51:14.685 [Time-limited test] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
06:51:14.832 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 16
06:51:14.833 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 16
06:51:14.833 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
06:51:14.833 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
06:51:14.833 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
06:51:14.833 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
06:51:14.833 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
06:51:14.833 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
06:51:14.834 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
06:51:14.834 [Time-limited test] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
06:51:14.856 [Time-limited test] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
06:51:14.857 [Time-limited test] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
06:51:14.857 [Time-limited test] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
06:51:14.880 [Time-limited test] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
06:51:14.923 [Time-limited test] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
06:51:16.252 [Time-limited test] DEBUG io.netty.handler.ssl.JdkSslContext - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1] 
06:51:16.267 [Time-limited test] DEBUG io.netty.handler.ssl.JdkSslContext - Default cipher suites (JDK): [TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA]
06:51:16.386 [Time-limited test] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 18365 (auto-detected)
06:51:16.390 [Time-limited test] DEBUG io.netty.util.NetUtil - Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%1)
06:51:16.391 [Time-limited test] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128
06:51:16.393 [Time-limited test] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: da:19:ac:ff:fe:77:f9:80 (auto-detected)
06:51:16.687 [Time-limited test] DEBUG i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.java.net.InetSocketAddressMatcher
06:51:16.951 [localEventLoopGroup-2-2] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity: 262144
06:51:17.218 [localEventLoopGroup-2-2] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=example.com
06:51:17.334 [localEventLoopGroup-2-3] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x8bc8b2f1, L:local:test - R:local:E:25a3150b] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
06:51:17.376 [localEventLoopGroup-2-2] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x25a3150b, L:local:E:25a3150b - R:local:test] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
------- Stderr: -------
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker
[jetty-alpn-agent] Replacing: sun/security/ssl/HelloExtensions
[jetty-alpn-agent] Replacing: sun/security/ssl/SupportedEllipticCurvesExtension
[jetty-alpn-agent] Replacing: sun/security/ssl/HelloExtension
[jetty-alpn-agent] Replacing: sun/security/ssl/ExtensionType
[jetty-alpn-agent] Replacing: sun/security/ssl/SupportedEllipticPointFormatsExtension
[jetty-alpn-agent] Replacing: sun/security/ssl/SignatureAlgorithmsExtension
[jetty-alpn-agent] Replacing: sun/security/ssl/RenegotiationInfoExtension
[jetty-alpn-agent] Replacing: sun/security/ssl/ServerHandshaker
[jetty-alpn-agent] Replacing: sun/security/ssl/ServerHandshaker$3
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker$2
[jetty-alpn-agent] Replacing: sun/security/ssl/Alerts
```

**Comment by normanmaurer** [comment]
Did mot see this for a long time now. Let me close this.
