### ISSUE TITLE
NPE in HttpObjectAggregator

### ISSUE THREAD

**Issue by yanns** [netty/netty#5256]
With Netty `4.0.36.Final`.

The code:
```
class DelayHandler extends ChannelInboundHandlerAdapter {
  override def channelRead(ctx: ChannelHandlerContext, msg: AnyRef): Unit = {
    msg match {
      case request: HttpRequest ⇒
        ctx.executor().schedule(new Runnable {
          override def run(): Unit = ctx.fireChannelRead(msg)
        }, 3, TimeUnit.SECONDS)
      case _ ⇒
        ctx.fireChannelRead(msg)
    }
  }
}
```

Stack trace:
```
[http-server-worker-1] [] [] ERROR d.c.sphere.http.server.AsyncHttpHandler - Uncaught exception:
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[netty-codec-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at de.commercetools.sphere.http.server.DelayHandler.channelRead(DelayHandler.scala:26) [classes/:na]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277) [netty-codec-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264) [netty-codec-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-common-4.0.36.Final.jar:4.0.36.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: java.lang.NullPointerException: null
	at io.netty.handler.codec.http.HttpObjectAggregator.decode(HttpObjectAggregator.java:209) ~[netty-codec-http-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.http.HttpObjectAggregator.decode(HttpObjectAggregator.java:57) ~[netty-codec-http-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[netty-codec-4.0.36.Final.jar:4.0.36.Final]
	... 20 common frames omitted
```

What I want to achieve:
I'd like to slow down incoming requests if there are too many requests.
This code only tests the slowing down of requests.

**Comment by normanmaurer** [comment]
@yanns that is because you not delay `HttpContent` as well and so produce out of order sequence of messages.

This will fix it:
class DelayHandler extends ChannelInboundHandlerAdapter {
  override def channelRead(ctx: ChannelHandlerContext, msg: AnyRef): Unit = {
    msg match {
      case request: HttpObject ⇒
        ctx.executor().schedule(new Runnable {
          override def run(): Unit = ctx.fireChannelRead(msg)
        }, 3, TimeUnit.SECONDS)
      case _ ⇒
        ctx.fireChannelRead(msg)
    }
  }
}
```

**Comment by yanns** [comment]
Thx it is working!
