### ISSUE TITLE
HTT/2 upgrade NPE when performing an upgrade with initial settings window size > 65535

### ISSUE THREAD

**Issue by vietj** [netty/netty#5301]
I'm currently seing an NPE when doing an HTTP/2 upgrade with initial settings with a window size > 65535 when calling `onHttpServerUpgrade` after the `Http2ConnectionHandler` is created.

As the window size is greater than the default value, it tries to write pending bytes, however the handler is not yet in the pipeline as `onHttpServerUpgrade ` must happen before the `Http2ConnectionHandler` is in the pipeline.

When `onHttpServerUpgrade ` is called after it is in the pipeline, then the preface will be sent and the settings cannot be applied to the connection.

The NPE happens because it tries to send bytes and use the `ChannelHandlerContext` that is not sent yet.

Here is the stack trace:

```
java.lang.NullPointerException
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.maxUsableChannelBytes(DefaultHttp2RemoteFlowController.java:262)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writableBytes(DefaultHttp2RemoteFlowController.java:274)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.access$1000(DefaultHttp2RemoteFlowController.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:710)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.initialWindowSize(DefaultHttp2RemoteFlowController.java:740)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$ListenerWritabilityMonitor.initialWindowSize(DefaultHttp2RemoteFlowController.java:788)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.initialWindowSize(DefaultHttp2RemoteFlowController.java:175)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.remoteSettings(DefaultHttp2ConnectionEncoder.java:108)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.onHttpServerUpgrade(Http2ConnectionHandler.java:150)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.createConnAndHandle(HttpServerImpl.java:676)
```

**Comment by vietj** [comment]
to me it seems that setting the initial window size should not try to send frames, i.e the part in `initialWindowSize` :

```
            if (delta > 0) {
                // The window size increased, send any pending frames for all streams.
                writePendingBytes();
            }
```

should not be called is this situation

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch @ejona86 WDYT ?

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch ping :)

**Comment by normanmaurer** [comment]
@vietj sounds like a valid assumption. Could you provide a PR ?

**Comment by Scottmitch** [comment]
Will take a look soon sry for the delay

**Comment by nmittler** [comment]
vietj@ why are there pending bytes on the server before the connection is established?

**Comment by vietj** [comment]
@nmittler there are no pending bytes I think.

the issue happens because it asks if there are pending bytes on DefaultRemoteFlowController#writableBytes() that calls DefaultHttp2RemoteFlowController#maxUsableChannelBytes() that tries to access the ChannelHandlerContext that is not set yet because the handler is not yet in the pipeline.

@normanmaurer I can provide a PR (that would fix what I observe), however it would be something untested from Netty side as there are not yet tests for this in Netty codebase.

**Comment by nmittler** [comment]
@vietj hmm, ok ... in that case, it's surprising that our server upgrade handler has been working to this point.

I've created #5305

**Comment by vietj** [comment]
@nmittler it does not fail if you send initial settings with a window size =< 65535, that may explain this
