### ISSUE TITLE
Rejected Execution Exception under load

### ISSUE THREAD

**Issue by JatinderSingh** [netty/netty#5304]
I am getting below exception when the netty based server is under high load.

 ERROR io.netty.util.concurrent.DefaultPromise.rejectedExecution - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:672) ~[netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:264) ~[netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:655) ~[netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:671) [netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.util.concurrent.DefaultPromise.notifyLateListener(DefaultPromise.java:641) [netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:138) [netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93) [netty-transport-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28) [netty-transport-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:251) [netty-transport-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:84) [netty-transport-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153) [netty-transport-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:187) [netty-transport-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:947) [netty-transport-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:110) [netty-transport-native-epoll-4.1.0.Beta4-linux-x86_64.jar:na]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:329) [netty-transport-native-epoll-4.1.0.Beta4-linux-x86_64.jar:na]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:250) [netty-transport-native-epoll-4.1.0.Beta4-linux-x86_64.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703) [netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]

**Comment by maseev** [comment]
@JatinderSingh It looks like you're using the beta version of Netty 4.1. Have you tried [this](http://mvnrepository.com/artifact/io.netty/netty-transport-native-epoll/4.1.0.CR7) one? Also, it would be helpful if you include the application code you're trying to run.

**Comment by JatinderSingh** [comment]
@maseev I had tried CR7 version twice but ran into some lock issues on same which resulted in massive throughput drop so i reverted to Beta4. The app is built on top of server https://github.com/JatinderSingh/http-server which abstracts interaction with netty.

**Comment by normanmaurer** [comment]
@JatinderSingh from the exception it looks like the EventLoopGroup was shutdown too early. Also would be interesting to know what "these lock issues" are. Can you provide some more infos ?

**Comment by JatinderSingh** [comment]
@normanmaurer  I ran perf-java-top on my process and raw_spin_unlock was eating up about 30% cpu and causing app to crash again and again for CR7 version. 

App was not given a kill signal, or any internal shutdown was not called in this case. It happened on 3 app servers out of 34 while load was very high.

**Comment by normanmaurer** [comment]
@JatinderSingh if you can share some of the debug info I may be able to help. Without it its hard.

**Comment by JatinderSingh** [comment]
@normanmaurer Could you guide me what info shall i share with you?

The Exception occurs only under peak production load on some days only.

**Comment by JatinderSingh** [comment]
@normanmaurer  could the lock issue in CR7 be caused by [](https://github.com/netty/netty/issues/5104) in case pipeline for http server is started with separate boss and worker event loops?

**Comment by normanmaurer** [comment]
@JatinderSingh without more infos I can not tell you much. The exception you pasted means that EventLoop or EventExecutor was shutdown while there are still tasks to handle.

**Comment by JatinderSingh** [comment]
@normanmaurer I found this exception before the series of above exceptions start. 

`2016-07-27 04:20:26,258 [epollEventLoopGroup-3-3] ERROR io.maelstorm.server.ConnectionManager - Unexpected exception from downstream for [id:
 0x434ef763, /204.13.193.74:54968 => /68.67.170.249:80]
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
        at java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:105) ~[na:1.8.0_74]
        at io.netty.util.ResourceLeakDetector.reportLeak(ResourceLeakDetector.java:224) ~[netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.util.ResourceLeakDetector.open(ResourceLeakDetector.java:189) ~[netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.buffer.AbstractByteBufAllocator.toLeakAwareBuffer(AbstractByteBufAllocator.java:35) ~[netty-buffer-4.1.0.Beta4.jar:4.1.0.
Beta4]
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:250) ~[netty-buffer-4.1.0.Beta4.jar:4.1.0.Beta4
]
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:155) ~[netty-buffer-4.1.0.Beta4.jar:4.1.0.Beta
4]
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:146) ~[netty-buffer-4.1.0.Beta4.jar:4.1.0.Beta
4]
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:107) ~[netty-buffer-4.1.0.Beta4.jar:4.1.0.Beta4]
        at io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(AdaptiveRecvByteBufAllocator.java:104) ~[netty-transport-4.1.0.B
eta4.jar:4.1.0.Beta4]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:608) ~[netty-tran
sport-native-epoll-4.1.0.Beta4-linux-x86_64.jar:na]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:329) [netty-transport-native-epoll-4.1.0.Beta4-linux-x86_64
.jar:na]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:250) [netty-transport-native-epoll-4.1.0.Beta4-linux-x86_64.jar:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703) [netty-common-4.1.0.Beta4.jar:4.1.0.B
eta4]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.1.0.Beta4.jar:4.1.0.Beta4]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]`

It seems like one out event loop out of multiple got above exception and same stopped but other event loops were running so throughput from server dropped and was not processing requests assigned to that loop.

**Comment by normanmaurer** [comment]
This looks like jdk bug

**Comment by JatinderSingh** [comment]
Below is version of oracle java which i am using, Will check if issue persists after upgrading JDK.

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)

**Comment by normanmaurer** [comment]
@JatinderSingh I am suspecting a JDK bug because it complains about a JDK class itself:

```
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code at java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:105) ~[na:1.8.0_74] at 
```

**Comment by normanmaurer** [comment]
@JatinderSingh any update ?

**Comment by JatinderSingh** [comment]
@normanmaurer  Hey it repeats itself in newer JDK as well. I checked same error and people from elastic cache are also facing same issue when system memory is nearly full. Do you have any workarounds in mind for same?

**Comment by normanmaurer** [comment]
@JatinderSingh nope.. I guess best would be to open a jdk bug or try using a different GC.

**Comment by balsukrishna** [comment]
Hello,
I encountered similar issue which is happening  sometimes but cannot reproduce.

Setup: A server and client(both netty) communicating.

Client Sending to Server:
```
//Get event loop and submit a task which will notify if doesn't get response before timeout interval
executor = getChannel().eventLoop()
executor.schedule(new RequestTimeoutTask(this, firstRequestTimeout), delay, TimeUnit.MILLISECONDS);
getChannel().writeAndFlush(someWrapper, promise); //This is the step causing exception


2016-12-12 00:00:02,253-[ERROR] [pool-10-thread-1] [i.n.u.c.D.rejectedExecution] - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:714) ~[netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:281) ~[netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:672) ~[netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.util.concurrent.DefaultPromise.execute(DefaultPromise.java:674) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:590) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:416) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.channel.DefaultChannelHandlerInvoker.safeExecuteOutbound(DefaultChannelHandlerInvoker.java:391) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeWrite(DefaultChannelHandlerInvoker.java:344) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:400) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:266) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1181) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:291) [netty-all-4.1.0.CR6.jar:4.1.0.CR6]
    .
   .
```
I haven't closed event loop. I can still see keep-alive messages and other messages being sent/receive.
Java Version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)```

**Comment by JatinderSingh** [comment]
The issue here is one of event loop worker has stopped accepting all requests passed to it and is throwing above exception, while other worker threads keep on processing requests normally. Exception pasted above are follow up exceptions of `java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code at java.lang.ref.ReferenceQueue.poll(ReferenceQueue.java:105) ~[na:1.8.0_74] at `

**Comment by balsukrishna** [comment]
I am using SingleThreadEventExecutor.
> other worker threads keep on processing requests normally

**Comment by normanmaurer** [comment]
Please update to latest java version and reopen if the issue still happens.
