### ISSUE TITLE
Netty 4.1.0.Final : testSoLingerZeroCausesOnlyRstOnClose failed

### ISSUE THREAD

**Issue by samjegal** [netty/netty#5335]
Testsuite module failed on my env, windows 10, but osx is good work for test case.

```
10:25:26.230 [Time-limited test] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
10:25:26.245 [Time-limited test] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
10:25:26.245 [Time-limited test] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
10:25:26.246 [Time-limited test] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
10:25:26.301 [testsuite-nio-worker-3-1] DEBUG i.n.u.i.JavassistTypeParameterMatcherGenerator - Generated: io.netty.util.internal.__matchers__.java.net.InetSocketAddressMatcher
10:25:26.315 [testsuite-nio-worker-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
10:25:26.319 [testsuite-nio-worker-3-1] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available

java.lang.AssertionError: actual message: An existing connection was forcibly closed by the remote host

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at io.netty.testsuite.transport.socket.SocketRstTest.assertRstOnCloseException(SocketRstTest.java:38)
	at io.netty.testsuite.transport.socket.SocketRstTest.testSoLingerZeroCausesOnlyRstOnClose(SocketRstTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.netty.testsuite.transport.AbstractComboTestsuiteTest.run(AbstractComboTestsuiteTest.java:67)
	at io.netty.testsuite.transport.socket.SocketRstTest.testSoLingerZeroCausesOnlyRstOnClose(SocketRstTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5336
