### ISSUE TITLE
[4.1] "Too many open files" exceptions when using the new DNS resolver

### ISSUE THREAD

**Issue by mnowrot** [netty/netty#5356]
To recreate, try to connecting ca 10.000 - 20.000 times using `Bootstrap` instances that have the new DNS Resolver set (with default configuration). After switching back to Java/OS DNS resolver, these exceptions are gone.

**Comment by normanmaurer** [comment]
Can you share a reproducer?

**Comment by mnowrot** [comment]
For the time being, I can provide a stacktrace:
```
java.lang.IllegalStateException: failed to create a new resolver
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:198) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:169) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:144) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
<snip>
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
<snip>
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
<snip>
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
<snip>
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:288) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:262) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at 
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1336) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:544) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145) [netty-all-4.1.0.Final.jar:4.1.0.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioDatagramChannel
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:318) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:278) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsNameResolver.newChannel(DnsNameResolver.java:183) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:164) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:318) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:96) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:85) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:67) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	... 87 more
Caused by: io.netty.channel.ChannelException: Failed to open a socket.
	at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:86) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:114) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_60]
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:318) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:278) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsNameResolver.newChannel(DnsNameResolver.java:183) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:164) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:318) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:96) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:85) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:67) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	... 87 more
Caused by: java.net.SocketException: Too many open files
	at sun.nio.ch.Net.socket0(Native Method) ~[?:1.8.0_60]
	at sun.nio.ch.Net.socket(Net.java:411) ~[?:1.8.0_60]
	at sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:115) ~[?:1.8.0_60]
	at sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:42) ~[?:1.8.0_60]
	at io.netty.channel.socket.nio.NioDatagramChannel.newSocket(NioDatagramChannel.java:84) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.channel.socket.nio.NioDatagramChannel.<init>(NioDatagramChannel.java:114) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at sun.reflect.GeneratedConstructorAccessor33.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_60]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_60]
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:318) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:278) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsNameResolver.newChannel(DnsNameResolver.java:183) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsNameResolver.<init>(DnsNameResolver.java:164) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsNameResolverBuilder.build(DnsNameResolverBuilder.java:318) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:96) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:85) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:67) ~[netty-all-4.1.0.Final.jar:4.1.0.Final]
	... 87 more
```

**Comment by normanmaurer** [comment]
Sorry but the stack trace is not really helpful to trouble shoot this :(

**Comment by slandelle** [comment]
@mnowrot How many different names are you trying to resolve and at which rate?
If you're trying to just resolve a few, but many times, `InflightNameResolver` is supposed to take care of this.
Otherwise, if you're trying to resolve 10.000 different names concurrently without any kind throttling, I think it's no surprise you run out of open files, the resolver doesn't have any kind of built-in queueing mechanism.

**Comment by mnowrot** [comment]
@slandelle in a failing example I'm trying to resolve only one name ("localhost") and the concurrency level is ca. 25.
@normanmaurer It won't be easy to extract a reproducer, as it is a part of a larger solution, but I'll try my best below:

```
// Start the connection attempt.
        final Bootstrap b = new Bootstrap();

final DnsAddressResolverGroup resolverGroup =
                new DnsAddressResolverGroup(NioDatagramChannel.class, DnsServerAddresses.defaultAddresses());

        // As a group there is used eventLoop from inboundChannel. It guarantees that inbound and outbound channels
        // will be handled on the same thread.
        b.group(inboundChannel.eventLoop())
                .channel(inboundChannel.getClass())
                .handler(new OutboundChannnelInitializer(inboundChannel))
                .resolver(resolverGroup)
                .option(ChannelOption.AUTO_READ, false);

        b.connect(host, port);
```

The above code is being invoked from a inbound pipeline (you can imagine a reverse-proxy for your intuition) which is in turn invoked by a load tester (siege, ab or others).

**Comment by normanmaurer** [comment]
@mnowrot do you reuse the "resolverGroup" ? Or create a new one overtime ?

**Comment by mnowrot** [comment]
@normanmaurer I was creating a new one for each client connection. What is the suggested practice here, creating a new resolverGroup each time or reusing a single one across the application?

**Comment by normanmaurer** [comment]
@mnowrot you should reuse... if you create a new one per client connection you opened one extra fd per  connection. The creation of the extra fd was actually fixed here:

https://github.com/netty/netty/commit/804e058e27e16e346b565ce4490f6177574e267d

Still you should reuse the resolver and close it once done with it.
