### ISSUE TITLE
4.1.0-CR7 => 4.1.1.Final introduced regressions

### ISSUE THREAD

**Issue by mosesn** [netty/netty#5376]
This [test](https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/test/scala/com/twitter/finagle/netty4/ssl/Netty4SslHandlerTest.scala#L52-L60) in finagle started failing when we moved to 4.1.1.Final.  The fix was to change from extending a `ChannelHandlerAdapter` to extending a `ChannelInitializer` in [Netty4SslHandler](https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/main/scala/com/twitter/finagle/netty4/ssl/Netty4SslHandler.scala#L26), although I'm not sure why that changed anything.

Is this expected?  On our end, it looks like a regression.

**Comment by mosesn** [comment]
Here's the full stacktrace:

```
                     1) auto-remove(com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest)
                     org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException: NoSuchElementException was thrown during property evaluation.
                       Message: io.netty.channel.embedded.EmbeddedChannel$2
                       Occurred when passed generated values (
                         arg0 = ClientSslContext(null)
                       )
                     	at org.scalatest.prop.Checkers$.doCheck(Checkers.scala:428)
                     	at org.scalatest.prop.GeneratorDrivenPropertyChecks$class.forAll(GeneratorDrivenPropertyChecks.scala:914)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest.forAll(Netty4SslHandlerTest.scala:19)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest$$anonfun$1.apply$mcV$sp(Netty4SslHandlerTest.scala:53)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest$$anonfun$1.apply(Netty4SslHandlerTest.scala:53)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest$$anonfun$1.apply(Netty4SslHandlerTest.scala:53)
                     	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
                     	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
                     	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
                     	at org.scalatest.Transformer.apply(Transformer.scala:22)
                     	at org.scalatest.Transformer.apply(Transformer.scala:20)
                     	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
                     	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
                     	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
                     	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
                     	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
                     	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
                     	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
                     	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest.org$scalatest$OneInstancePerTest$$super$runTest(Netty4SslHandlerTest.scala:19)
                     	at org.scalatest.OneInstancePerTest$class.runTest(OneInstancePerTest.scala:129)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest.runTest(Netty4SslHandlerTest.scala:19)
                     	at org.scalatest.OneInstancePerTest$class.runTests(OneInstancePerTest.scala:177)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest.runTests(Netty4SslHandlerTest.scala:19)
                     	at org.scalatest.Suite$class.run(Suite.scala:1424)
                     	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
                     	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
                     	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
                     	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
                     	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
                     	at org.scalatest.FunSuite.run(FunSuite.scala:1555)
                     	at org.scalatest.OneInstancePerTest$class.runTest(OneInstancePerTest.scala:126)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest.runTest(Netty4SslHandlerTest.scala:19)
                     	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
                     	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
                     	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
                     	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
                     	at scala.collection.immutable.List.foreach(List.scala:381)
                     	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
                     	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
                     	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
                     	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest.org$scalatest$OneInstancePerTest$$super$runTests(Netty4SslHandlerTest.scala:19)
                     	at org.scalatest.OneInstancePerTest$class.runTests(OneInstancePerTest.scala:184)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest.runTests(Netty4SslHandlerTest.scala:19)
                     	at org.scalatest.Suite$class.run(Suite.scala:1424)
                     	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
                     	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
                     	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
                     	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
                     	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
                     	at org.scalatest.FunSuite.run(FunSuite.scala:1555)
                     	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:99)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.CompositeRequest.runChild(CompositeRequest.java:66)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConcurrentCompositeRequest$1$1.run(ConcurrentCompositeRequest.java:38)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConcurrentRunnerScheduler.finished(ConcurrentRunnerScheduler.java:95)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConcurrentCompositeRequest$1.evaluate(ConcurrentCompositeRequest.java:47)
                     	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                     	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConsoleRunnerImpl.run(ConsoleRunnerImpl.java:428)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConsoleRunnerImpl.main(ConsoleRunnerImpl.java:774)
                     	at org.pantsbuild.tools.junit.ConsoleRunner.main(ConsoleRunner.java:12)
                     Caused by: java.util.NoSuchElementException: io.netty.channel.embedded.EmbeddedChannel$2
                     	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1068)
                     	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:417)
                     	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
                     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:141)
                     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:127)
                     	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:120)
                     	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1293)
                     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:141)
                     	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:127)
                     	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:799)
                     	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:498)
                     	at io.netty.channel.AbstractChannel$AbstractUnsafe.register(AbstractChannel.java:465)
                     	at io.netty.channel.embedded.EmbeddedEventLoop.register(EmbeddedEventLoop.java:130)
                     	at io.netty.channel.embedded.EmbeddedEventLoop.register(EmbeddedEventLoop.java:124)
                     	at io.netty.channel.embedded.EmbeddedChannel.setup(EmbeddedChannel.java:178)
                     	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:137)
                     	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:121)
                     	at io.netty.channel.embedded.EmbeddedChannel.<init>(EmbeddedChannel.java:99)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest.channel(Netty4SslHandlerTest.scala:50)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(Netty4SslHandlerTest.scala:54)
                     	at com.twitter.finagle.netty4.ssl.Netty4SslHandlerTest$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(Netty4SslHandlerTest.scala:53)
                     	at org.scalatest.prop.GeneratorDrivenPropertyChecks$$anonfun$32.liftedTree9$1(GeneratorDrivenPropertyChecks.scala:901)
                     	at org.scalatest.prop.GeneratorDrivenPropertyChecks$$anonfun$32.apply(GeneratorDrivenPropertyChecks.scala:900)
                     	at org.scalatest.prop.GeneratorDrivenPropertyChecks$$anonfun$32.apply(GeneratorDrivenPropertyChecks.scala:898)
                     	at org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:714)
                     	at org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:714)
                     	at org.scalacheck.Prop$.secure(Prop.scala:458)
                     	at org.scalacheck.Prop$$anonfun$forAllShrink$1.org$scalacheck$Prop$$anonfun$$result$1(Prop.scala:714)
                     	at org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:751)
                     	at org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:708)
                     	at org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:293)
                     	at org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:292)
                     	at org.scalacheck.PropFromFun.apply(Prop.scala:21)
                     	at org.scalacheck.Test$.org$scalacheck$Test$$workerFun$1(Test.scala:323)
                     	at org.scalacheck.Test$$anonfun$2.apply(Test.scala:352)
                     	at org.scalacheck.Test$$anonfun$2.apply(Test.scala:352)
                     	at org.scalacheck.Platform$.runWorkers(Platform.scala:40)
                     	at org.scalacheck.Test$.check(Test.scala:352)
                     	at org.scalatest.prop.Checkers$.doCheck(Checkers.scala:372)
                     	... 61 more

                     FAILURES!!!
                     Tests run: 3,  Failures: 1
```

**Comment by mosesn** [comment]
As I continue fixing tests, here's another big swath of them.  It looks like the way EmbeddedChannel works changed?  I was able to fix ChannelTransportTest by removing [this line][0].

[0]: https://github.com/twitter/finagle/blob/develop/finagle-netty4/src/test/scala/com/twitter/finagle/netty4/transport/ChannelTransportTest.scala#L29

**Comment by mosesn** [comment]
I'm also seeing problems with [HttpContentCompressor][0].  Almost all of the [tests][1] for [TextualContentCompressor][2] failed.  Here's a representative stack trace:

```
                     1) enabled for application/json(com.twitter.finagle.netty4.http.TextualContentCompressorTest)
                     java.lang.NullPointerException
                     	at io.netty.handler.codec.http.HttpContentCompressor.beginEncode(HttpContentCompressor.java:127)
                     	at com.twitter.finagle.netty4.http.TextualContentCompressor.beginEncode(TextualContentCompressor.scala:15)
                     	at com.twitter.finagle.netty4.http.TextualContentCompressorTest$$anonfun$2$$anonfun$apply$1.apply$mcV$sp(TextualContentCompressorTest.scala:23)
                     	at com.twitter.finagle.netty4.http.TextualContentCompressorTest$$anonfun$2$$anonfun$apply$1.apply(TextualContentCompressorTest.scala:21)
                     	at com.twitter.finagle.netty4.http.TextualContentCompressorTest$$anonfun$2$$anonfun$apply$1.apply(TextualContentCompressorTest.scala:21)
                     	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
                     	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
                     	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
                     	at org.scalatest.Transformer.apply(Transformer.scala:22)
                     	at org.scalatest.Transformer.apply(Transformer.scala:20)
                     	at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:166)
                     	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
                     	at org.scalatest.FunSuite.withFixture(FunSuite.scala:1555)
                     	at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:163)
                     	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
                     	at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:175)
                     	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
                     	at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:175)
                     	at org.scalatest.FunSuite.runTest(FunSuite.scala:1555)
                     	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
                     	at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:208)
                     	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
                     	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
                     	at scala.collection.immutable.List.foreach(List.scala:381)
                     	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
                     	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
                     	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
                     	at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:208)
                     	at org.scalatest.FunSuite.runTests(FunSuite.scala:1555)
                     	at org.scalatest.Suite$class.run(Suite.scala:1424)
                     	at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1555)
                     	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
                     	at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:212)
                     	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
                     	at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:212)
                     	at org.scalatest.FunSuite.run(FunSuite.scala:1555)
                     	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:99)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.CompositeRequest.runChild(CompositeRequest.java:66)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConcurrentCompositeRequest$1$1.run(ConcurrentCompositeRequest.java:38)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConcurrentRunnerScheduler.finished(ConcurrentRunnerScheduler.java:95)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConcurrentCompositeRequest$1.evaluate(ConcurrentCompositeRequest.java:47)
                     	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                     	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConsoleRunnerImpl.run(ConsoleRunnerImpl.java:428)
                     	at __shaded_by_pants__.org.pantsbuild.tools.junit.impl.ConsoleRunnerImpl.main(ConsoleRunnerImpl.java:774)
                     	at org.pantsbuild.tools.junit.ConsoleRunner.main(ConsoleRunner.java:12)
```

[0]: https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/HttpContentCompressor.java
[1]: https://github.com/twitter/finagle/blob/develop/finagle-netty4-http/src/test/scala/com/twitter/finagle/netty4/http/TextualContentCompressorTest.scala
[2]: https://github.com/twitter/finagle/blob/develop/finagle-netty4-http/src/main/scala/com/twitter/finagle/netty4/http/TextualContentCompressor.scala

**Comment by mosesn** [comment]
I figured out the `HttpContentCompressor`.  It didn't require that you called `handlerAdded` before `beginEncode` before, but now it does.  I added it to an EmbeddedChannel and it works now.

**Comment by mosesn** [comment]
@dschobel figured out why we didn't have to remove that dummy ChannelHandler anymore, we were working around the bug that was fixed here: https://github.com/netty/netty/commit/a2040a2e481e0981eadcf016edae63e756ce5d13

So the only mystery is why I had to switch from ChannelHandlerAdapter to ChannelInitializer.

**Comment by normanmaurer** [comment]
So this change is still needed ?

**Comment by mosesn** [comment]
The ChannelHandlerAdapter to ChannelInitializer?  Yes, it's still needed as far as I can tell.  We'll open source the change I made soon.

**Comment by normanmaurer** [comment]
@mosesn thanks... please ping me once you did so I can reproduce and have a look.

**Comment by normanmaurer** [comment]
Let me close this for now. If you still think there is an issue please re-open

**Comment by mosesn** [comment]
Whoops, I forgot to follow up on this, but my change migrating was open sourced weeks ago.  https://github.com/twitter/finagle/commit/9871fc8612336f04d57ce7bb19a5cee25b984bb5

Looks like I can't reopen the ticket by myself?  I think I don't have the permissions to do it.

**Comment by Scottmitch** [comment]
thanks @mosesn ... assigned to @normanmaurer

**Comment by normanmaurer** [comment]
@mosesn so which problem exactly you are still seeing ?

**Comment by mosesn** [comment]
We had to change from ChannelHandlerAdapter to ChannelInitializer in https://github.com/twitter/finagle/commit/9871fc8612336f04d57ce7bb19a5cee25b984bb5#diff-1b54c74fe70b79bf4822c7501deb4256L26 to get the same behavior we were getting before.

**Comment by normanmaurer** [comment]
Ok will check

**Comment by normanmaurer** [comment]
@mosesn is this still a problem ? Sorry I totally lost track :(

**Comment by mosesn** [comment]
Yeah, I don't remember what broke anymore.  Probably changing it back would also be a breaking change at this point.
