### ISSUE TITLE
AbstractBootstrap#initAndRegister crash doesn't notify promise

### ISSUE THREAD

**Issue by slandelle** [netty/netty#5387]
`initAndRegister` can possibly crash, eg:

```
java.net.SocketException: Too many open files
	at sun.nio.ch.Net.socket0(Native Method)
	at sun.nio.ch.Net.socket(Net.java:411)
	at sun.nio.ch.Net.socket(Net.java:404)
	at sun.nio.ch.SocketChannelImpl.<init>(SocketChannelImpl.java:105)
	at sun.nio.ch.SelectorProviderImpl.openSocketChannel(SelectorProviderImpl.java:60)
	at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:60)
	... 64 common frames omitted
Wrapped by: io.netty.channel.ChannelException: Failed to open a socket.
	at io.netty.channel.socket.nio.NioSocketChannel.newSocket(NioSocketChannel.java:62)
	at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:72)
	at org.asynchttpclient.netty.channel.NioSocketChannelFactory.newChannel(NioSocketChannelFactory.java:25)
	at org.asynchttpclient.netty.channel.NioSocketChannelFactory.newChannel(NioSocketChannelFactory.java:19)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:308)
```

The problem is that the `newSocket` isn't monitored with a try/catch, so promise isn't notify and the caller crash.

IMHO, such Exception should be dealt with in the promise. Users shouldn't have to combine 2 different Exception handling mechanisms and both wrap the call with a try/catch AND check the future.

**Comment by normanmaurer** [comment]
@slandelle you are right... let me fix.

**Comment by slandelle** [comment]
Awesome, thanks!
I can provide a PR if you want, but I first wanted to be sure it was a bug and not intended behavior.

**Comment by normanmaurer** [comment]
@slandelle a pr would be awesome! Please also add a test that we catch when `ChannelFactory.newChannel(...)` throws and notify the promise.

**Comment by slandelle** [comment]
Actually, having a look at `BootstrapTest#testLateRegistrationConnect` makes me think that `connect` is expected to possibly throw exceptions.

I can't say I like this behavior, but it is what it is, and IMHO can't be changed/fixed outside a new version.

WDYT?

**Comment by slandelle** [comment]
Should Exception be thrown AND listener notified?

**Comment by normanmaurer** [comment]
@slandelle I think you misread the test case. It only throws because we do `syncUninterruptibly()`.

**Comment by slandelle** [comment]
My bad...

**Comment by normanmaurer** [comment]
@slandelle no worries!

**Comment by slandelle** [comment]
Done, see #5388

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5388
