### ISSUE TITLE
OOM Direct buffer memory from SslHandler.flush

### ISSUE THREAD

**Issue by Kangmo** [netty/netty#5452]
## Problem description
First of all thanks for the library.
I am a newbie in Netty, so this might be happening because of my lack of knowlege on Netty.

ScaleChain, a private blockchain implementation in Scala uses Netty for (1) peer to peer networking and (2) HTTP json rpc service.

As I did not call any json rpc during my test I am assuming that the OOM exception is raised on the P2P communication module.

## Netty Version
4.0.36.Final but I see the following message while I build my project.
```
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* io.netty:netty-all:4.0.23.Final -> 4.0.36.Final
```

## Netty related logs
```
11:06:27.412 [run-main-0] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
11:06:27.510 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
11:06:27.513 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
11:06:27.513 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
11:06:27.514 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
11:06:27.518 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
11:06:27.527 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
11:06:27.566 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
11:06:27.571 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
11:06:27.573 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
11:06:27.573 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
11:06:27.573 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/32/kg_v9zzx5h786qjbkzqtg6sr0000gn/T (java.io.tmpdir)
11:06:27.573 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
11:06:27.573 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
11:06:27.612 [run-main-0] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
11:06:27.650 [run-main-0] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
11:06:27.650 [run-main-0] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
11:06:27.768 [run-main-0] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x40f125211a759185 (took 5 ms)
11:06:28.542 [run-main-0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
11:06:28.548 [run-main-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
11:06:28.549 [run-main-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
11:06:28.569 [run-main-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: unpooled
11:06:28.569 [run-main-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
11:06:28.569 [run-main-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
11:06:28.574 [run-main-0] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
11:06:28.681 [run-main-0] DEBUG io.netty.handler.ssl.OpenSsl - netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
11:06:29.725 [run-main-0] DEBUG io.netty.handler.ssl.JdkSslContext - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1] 
11:06:29.732 [run-main-0] DEBUG io.netty.handler.ssl.JdkSslContext - Default cipher suites (JDK): [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA]
11:06:30.051 [run-main-0] DEBUG io.netty.util.NetUtil - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1)
11:06:30.052 [run-main-0] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128 (non-existent)
11:06:30.082 [nioEventLoopGroup-2-1] INFO  i.s.blockchain.net.NodeClient - Successfully bound port : 7647
11:06:30.303 [nioEventLoopGroup-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacity.default: 262144
[GC (Allocation Failure)  424223K->139844K(600576K), 0.0832492 secs]
11:06:30.590 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x3786d125, L:/0:0:0:0:0:0:0:0:7647] RECEIVED: [id: 0x162c61d7, L:/127.0.0.1:7647 - R:/127.0.0.1:51041]
11:06:30.592 [nioEventLoopGroup-7-1] DEBUG i.n.h.s.u.InsecureTrustManagerFactory - Accepting a server certificate: CN=example.com


```

## Call stack

```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:693)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
[GC (System.gc())  137937K->133652K(710144K), 0.0018692 secs]
[Full GC (System.gc())  133652K->133538K(710144K), 0.1659851 secs]
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.allocateDirect(UnpooledUnsafeDirectByteBuf.java:106)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:67)
	at io.netty.buffer.UnpooledByteBufAllocator.newDirectBuffer(UnpooledByteBufAllocator.java:51)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:177)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:168)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:105)
	at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1461)
	at io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:1471)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:523)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:649)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:630)
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:649)
	at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:957)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:889)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:374)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

```

## Netty related codes
I am using a modified version of the SecureChat sample code with my own encoder/decoder.
Server/Client initializer, handler are here.

https://github.com/ScaleChain/scalechain/tree/proto-new-chain/scalechain-net/src/main/scala/io/scalechain/blockchain/net/p2p

### Encoder/Decoder
https://github.com/ScaleChain/scalechain/tree/proto-new-chain/scalechain-net/src/main/java/io/scalechain/blockchain/net/p2p

## Execution environment
MacOS 10.11.1 (15B42)
```
$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
You have new mail in /var/mail/kangmo
```

## Reproduction steps  

Check out source code.
```
git clone https://github.com/ScaleChain/scalechain
cd scalechain
git checkout eb6f1498e3f47277847e8b4eec2ebe02832750a3
```

Create .env file in the scalechain folder with the following content.
With the default MaxDirectMemorySize 64m, the issue takes several hours for reproduction. After reducing it to 1m, it is reproduced in an hour.
```
RPC_PORT_BASE=8080
P2P_PORT_BASE=7643
CASSANDRA_IP_LAST_BASE=102
JAVA_OPTIONS="-verbosegc -Xmx2048m -XX:MaxDirectMemorySize=1m -XX:-HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/kangmo/crypto/scalechain/target/oom_dump.hprof"
MINER_INITIAL_DELAY_MS=3076
MINER_HASH_DELAY_MS=1
```

Download sbt if not installed. 
```
(on mac)
brew install sbt
```

Compile the code
```
cd scalechain
sbt clean compile
```

Open up five terminal to run five scalechain nodes.
These nodes sends messages to each other using netty 4.
### terminal 1 
```
cd scalechain
./run.sh 0
```

### terminal 2
```
cd scalechain
./run.sh 1
```

### terminal 3 
```
cd scalechain
./run.sh 2
```

### terminal 4 
```
cd scalechain
./run.sh 3
```

### terminal 5 
```
cd scalechain
./run.sh 4
```

Wait for an hour. We have OOM error on one of five scalechain/target/sc*.log. where * is 1,2,3,4, or 5

**Comment by Kangmo** [comment]
### Question  

I have another exception connection getting reset. 
Could this happened because of the above memory allocation failure?

```
01:46:20.216 [nioEventLoopGroup-3-4] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xf71d872e, L:/127.0.0.1:7643 - R:/127.0.0.1:50550] Swallowing a harmless 'connection reset by peer / broken pipe' error that occurred while writing close_notify in response to the peer's close_notify
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[na:1.8.0_91]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[na:1.8.0_91]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[na:1.8.0_91]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[na:1.8.0_91]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[na:1.8.0_91]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:357) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:898) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) ~[netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:528) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.36.Final.jar:4.0.36.Final]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

```

**Comment by Kangmo** [comment]
After upgrading Netty from 4.0.37.Final to 4.1.1.Final, I see the following call stack.

```
15:51:42.935 [nioEventLoopGroup-17-1] ERROR i.s.blockchain.net.NodeClientHandler - io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 64 byte(s) of direct memory (used: 1048576, max: 1048576). Stack : io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 64 byte(s) of direct memory (used: 1048576, max: 1048576)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:592)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:546)
	at io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf.allocateDirect(UnpooledUnsafeNoCleanerDirectByteBuf.java:30)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:68)
	at io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf.<init>(UnpooledUnsafeNoCleanerDirectByteBuf.java:25)
	at io.netty.buffer.UnsafeByteBufUtil.newUnsafeDirectByteBuf(UnsafeByteBufUtil.java:625)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:265)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:170)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:131)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:73)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:111)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:390)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by NiteshKant** [comment]
@Kangmo you are giving the VM just 1M of Direct memory:

```
-XX:MaxDirectMemorySize=1m 
```

How much data is read/written on the connections?

**Comment by Kangmo** [comment]
@NiteshKant, the following is the list of tcp connections on five java processes without the MaxDirectMemorySize option. Now I am running Netty 4.1.1.Final, so the limit on the direct memory is same to the heap, which is 2GB.

Because it took almost a day to reproduce the issue, I have set MaxDirectMemorySize to 1m for the reproduction to finish in an hour.

Here is the netty settings logged with Netty 4.1.1.Final.
```
18:33:42.181 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
18:33:42.183 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
18:33:42.183 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
18:33:42.184 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: true
18:33:42.184 [run-main-0] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
18:33:42.186 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - Java version: 8
18:33:42.186 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
18:33:42.186 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: available
18:33:42.186 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
18:33:42.187 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - Javassist: unavailable
18:33:42.188 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - You don't have Javassist in your class path or you don't have enough permission to load dynamically generated classes.  Please check the configuration for better performance.
18:33:42.188 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/32/kg_v9zzx5h786qjbkzqtg6sr0000gn/T (java.io.tmpdir)
18:33:42.188 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
18:33:42.188 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
18:33:42.188 [run-main-0] DEBUG i.n.util.internal.PlatformDependent - io.netty.maxDirectMemory: 1908932608 bytes
18:33:42.206 [run-main-0] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 16
18:33:42.224 [run-main-0] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
18:33:42.224 [run-main-0] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
18:33:42.243 [run-main-0] DEBUG i.n.util.internal.ThreadLocalRandom - -Dio.netty.initialSeedUniquifier: 0x4e860c22ba8fc2f9
18:33:42.484 [run-main-0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.bytebuf.checkAccessible: true
18:33:42.487 [run-main-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: paranoid
18:33:42.487 [run-main-0] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.maxRecords: 4
18:33:42.496 [run-main-0] DEBUG i.n.buffer.AdvancedLeakAwareByteBuf - -Dio.netty.leakDetection.acquireAndReleaseOnly: false
18:33:42.618 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 16
18:33:42.618 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 16
18:33:42.618 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
18:33:42.618 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
18:33:42.618 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
18:33:42.618 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
18:33:42.618 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
18:33:42.618 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
18:33:42.618 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
18:33:42.619 [run-main-0] DEBUG i.n.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
18:33:42.631 [run-main-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
18:33:42.631 [run-main-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 65536
18:33:42.631 [run-main-0] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
[GC (Allocation Failure)  702108K->152508K(890880K), 0.0387469 secs]
18:33:42.871 [run-main-0] DEBUG io.netty.handler.ssl.OpenSsl - netty-tcnative not in the classpath; OpenSslEngine will be unavailable.
18:33:43.230 [run-main-0] DEBUG io.netty.handler.ssl.JdkSslContext - Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1] 
18:33:43.230 [run-main-0] DEBUG io.netty.handler.ssl.JdkSslContext - Default cipher suites (JDK): [TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, SSL_RSA_WITH_3DES_EDE_CBC_SHA]
18:33:43.290 [run-main-0] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 519 (auto-detected)
18:33:43.293 [run-main-0] DEBUG io.netty.util.NetUtil - Loopback interface: lo0 (lo0, 0:0:0:0:0:0:0:1)
18:33:43.294 [run-main-0] DEBUG io.netty.util.NetUtil - /proc/sys/net/core/somaxconn: 128 (non-existent)

```

I have been running these processes for 110 minutes, and they are reading/writing 300MB per process.
So, per process, it is 
```
                                                               interface           state        bytes in       bytes out   rx dupe    rx ooo     re-tx
java.519                                                                                         299 MiB         301 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49524<->localhost:7647                            lo0     Established          36 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7643<->localhost:49518                            lo0     Established          36 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49476<->localhost:7646                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7643<->localhost:49470                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49309<->localhost:7645                            lo0     Established          38 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7643<->localhost:49304                            lo0     Established          38 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7643<->localhost:49281                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp6 *.8080<->*.*                                                             Listen
    tcp4 127.0.0.1:49278<->localhost:7644                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp6 *.7643<->*.*                                                             Listen
java.560                                                                                         263 MiB         259 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49521<->localhost:7647                            lo0     Established          36 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7644<->localhost:49520                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49472<->localhost:7646                            lo0     Established          38 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7644<->localhost:49468                            lo0     Established          38 MiB          36 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7644<->localhost:49303                            lo0     Established          37 MiB          36 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49281<->localhost:7643                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7644<->localhost:49278                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp6 *.8081<->*.*                                                             Listen
    tcp6 *.7644<->*.*                                                             Listen
java.627                                                                                         262 MiB         267 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49523<->localhost:7647                            lo0     Established          36 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7645<->localhost:49519                            lo0     Established          36 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49474<->localhost:7646                            lo0     Established          38 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7645<->localhost:49469                            lo0     Established          38 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7645<->localhost:49309                            lo0     Established          37 MiB          38 MiB     0 B       0 B       0 B
    tcp6 *.8082<->*.*                                                             Listen
    tcp4 127.0.0.1:49303<->localhost:7644                            lo0     Established          36 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49304<->localhost:7643                            lo0     Established          37 MiB          38 MiB     0 B       0 B       0 B
    tcp6 *.7645<->*.*                                                             Listen
java.681                                                                                         298 MiB         307 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49522<->localhost:7647                            lo0     Established          36 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7646<->localhost:49517                            lo0     Established          36 MiB          39 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7646<->localhost:49476                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7646<->localhost:49474                            lo0     Established          38 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7646<->localhost:49472                            lo0     Established          37 MiB          38 MiB     0 B       0 B       0 B
    tcp6 *.8083<->*.*                                                             Listen
    tcp4 127.0.0.1:49469<->localhost:7645                            lo0     Established          38 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49468<->localhost:7644                            lo0     Established          36 MiB          38 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49470<->localhost:7643                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp6 *.7646<->*.*                                                             Listen
java.722                                                                                         307 MiB         293 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7647<->localhost:49524                            lo0     Established          38 MiB          36 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7647<->localhost:49523                            lo0     Established          38 MiB          36 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7647<->localhost:49522                            lo0     Established          38 MiB          36 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:7647<->localhost:49521                            lo0     Established          37 MiB          36 MiB     0 B       0 B       0 B
    tcp6 *.8084<->*.*                                                             Listen
    tcp4 127.0.0.1:49517<->localhost:7646                            lo0     Established          39 MiB          36 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49519<->localhost:7645                            lo0     Established          38 MiB          36 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49520<->localhost:7644                            lo0     Established          37 MiB          37 MiB     0 B       0 B       0 B
    tcp4 127.0.0.1:49518<->localhost:7643                            lo0     Established          38 MiB          36 MiB     0 B       0 B       0 B
    tcp6 *.7647<->*.*                                                             Listen
```

**Comment by Kangmo** [comment]
A question : 
If I do not release the message in chanelRead method of the channel handler, is there any possibility that the direct memory can leak?

**Comment by normanmaurer** [comment]
Yes!

You must release it

**Comment by Kangmo** [comment]
Using BufferPools plugin of visualvm, found that Netty only uses 2,455 B for the direct memory.
Looks like the issue happened because I did not release the message on channel handler.

A quick question : 
I copied my code from the securechat example. Do handlers in the securechat example require to release messages? If yes,  I would be happy to contribute to release messages in channelRead0.

```
https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/securechat/SecureChatClientHandler.java
https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/securechat/SecureChatServerHandler.java
```

**Comment by Kangmo** [comment]
I will close the issue as the issue seems to be caused because I did not release message.

**Comment by normanmaurer** [comment]
Nope as SimpleChannelInboundHandler does it for you

**Comment by Kangmo** [comment]
I see. Thanks. What happens if the sub class of SimpleChannelInboundHandler releases the incoming message? I am using -Dio.netty.leakDetectionLevel=paranoid but no exception is thrown even though I am releasing message in the sub class of SimpleChannelInboundHandler.
