### ISSUE TITLE
When I deployed to linux and start, after a while netty throws a warn

### ISSUE THREAD

**Issue by lijunyong** [netty/netty#5470]
[ WARN ] [2016-06-29 17:35:04] io.netty.channel.DefaultChannelPipeline [151] - An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:311)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Scottmitch** [comment]
what version of Netty? What is your expected behavior?

**Comment by lijunyong** [comment]
@Scottmitch the version is netty-all-4.0.27.final

**Comment by Scottmitch** [comment]
@lijunyong - I would prefer to find the origin of this exception instead of turning the log statement off ... this is unexpected behavior.

Can you please put a breakpoint at [1] and provide the stacktrace for `t`?

[1] https://github.com/netty/netty/blob/netty-4.0.27.Final/transport/src/main/java/io/netty/channel/AbstractChannelHandlerContext.java#L278

**Comment by lijunyong** [comment]
this stacktrance is: java.lang.NullPointerException
[http://i1.piimg.com/4851/3440f0e19350df09.png]

**Comment by normanmaurer** [comment]
@lijunyong please show us the stack of the NPE then.

**Comment by johnou** [comment]
@lijunyong if no stacktrace is present you may need to run your JVM with the -XX:-OmitStackTraceInFastThrow flag.

**Comment by lijunyong** [comment]
@johnou I add it in my JVM
[http://i2.piimg.com/4851/486c44325301c2da.png](url)

**Comment by lijunyong** [comment]
I already know the cause of the problem, It's not the netty bug.Thanks

**Comment by normanmaurer** [comment]
Ok let me close it then
