### ISSUE TITLE
Netty 4.0.37.Final: Exception while changing pipeline

### ISSUE THREAD

**Issue by JuKu** [netty/netty#5492]
Hi,

My application message handler replaces one decoder of pipeline, like this:
```Java
public class LoginHandler extends ChannelInboundHandlerAdapter {

    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        //...

        //replace decoder
        getLogger().debug("replace message decoder with sector message decoder now.");

        ctx.channel().pipeline().remove("decoder");

       ctx.channel().pipeline().addLast("decoder", new SectorMessageDecoder());

       //add message handler to pipeline
       ctx.channel().pipeline().addLast("handler", messageHandler);
    }

}
```

But the following exception is thrown:
```
[DEBUG, main] replace message decoder with sector message decoder now.
118477 [nioEventLoopGroup-5-6] WARN io.netty.channel.DefaultChannelPipeline  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NoClassDefFoundError: com/pentaquin/proxy/lib/message/SectorMessageDecoder
	at com.pentaquin.region.server.handler.LoginHandler.onChannelRead(LoginHandler.java:99)
	at com.pentaquin.region.server.handler.LoginHandler.onChannelRead(LoginHandler.java:24)
	at com.pentaquin.region.server.handler.BasicHandler.channelRead(BasicHandler.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:240)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:321)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:328)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:890)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:564)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:505)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:419)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
```

What is the cause of this exception?
Thanks!

EDIT:
Sry, I havent seen "java.lang.NoClassDefFoundError: com/pentaquin/proxy/lib/message/SectorMessageDecoder" before...
But why can he find this class sometimes and sometimes not?

**Comment by johnou** [comment]
Instead of remove / add could you use replace? wrt to NoClassDefFoundError has your JVM thrown OOM?

**Comment by normanmaurer** [comment]
@JuKu this looks like a class-loader issue. Nothing related to netty.
