### ISSUE TITLE
NetUtil: Failed to retrieve the list of available network interfaces

### ISSUE THREAD

**Issue by Ewg777** [netty/netty#5524]
``W/io.netty.util.NetUtil: Failed to retrieve the list of available network interfaces
                                                                         java.net.SocketException
                                                                             at java.net.NetworkInterface.rethrowAsSocketException(NetworkInterface.java:248)
                                                                             at java.net.NetworkInterface.readIntFile(NetworkInterface.java:243)
                                                                             at java.net.NetworkInterface.getByNameInternal(NetworkInterface.java:121)
                                                                             at java.net.NetworkInterface.getNetworkInterfacesList(NetworkInterface.java:309)
                                                                             at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:298)
                                                                             at io.netty.util.NetUtil.<clinit>(NetUtil.java:157)
                                                                             at io.netty.util.internal.MacAddressUtil.bestAvailableMac(MacAddressUtil.java:53)
                                                                             at io.netty.channel.DefaultChannelId.defaultMachineId(DefaultChannelId.java:127)
                                                                             at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:104)
                                                                             at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
                                                                             at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
                                                                             at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:83)
                                                                             at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
                                                                             at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:84)
                                                                             at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:70)
                                                                             at java.lang.Class.newInstanceImpl(Native Method)
                                                                             at java.lang.Class.newInstance(Class.java:1215)
                                                                             at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
                                                                             at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
                                                                             at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281)
                                                                             at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277)
                                                                             at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:252)
``
```java
            final ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup, workerGroup)
                    .channel(NioServerSocketChannel.class)
                    .option(ChannelOption.TCP_NODELAY, true)
                    .childOption(ChannelOption.SO_KEEPALIVE, true);
            ChannelFuture future = b.bind(PORT).sync();

            future.channel().closeFuture().sync();
```
Is it okay?

**Comment by normanmaurer** [comment]
@Ewg777 but it still works ?

**Comment by Ewg777** [comment]
@normanmaurer yeap

**Comment by normanmaurer** [comment]
@Ewg777 for whatever reason we where not able to get all the network interfaces. There is not much we can do here. That said as you stated it will still work.
