### ISSUE TITLE
SimpleChannelPool problematic throwable handling

### ISSUE THREAD

**Issue by Spikhalskiy** [netty/netty#5541]
Netty version: 4.0.38.Final

Context:

I try to use SimpleChannelPool under heavy load and after some errors "Caused by: java.net.SocketException: Too many open files" started to get exceptions that are very hard to read and that doesn't have a lot of sense to save in this current state (at least because it's exception log for 600Kb):
```
[14 Jul 2016 14:24:47,190][WARN ][SingleThreadEventExecutor,httpClient-1-1] - A task raised an exception.
java.lang.IllegalStateException: complete already: DefaultPromise@4a75ea21(failure: java.lang.StackOverflowError)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:123)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:152)
	at io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:112)
	at io.netty.channel.pool.FixedChannelPool.acquire0(FixedChannelPool.java:230)
	at io.netty.channel.pool.FixedChannelPool.access$300(FixedChannelPool.java:37)
	at io.netty.channel.pool.FixedChannelPool$3.run(FixedChannelPool.java:204)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:402)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:136)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: complete already: DefaultPromise@4a75ea21(failure: java.lang.StackOverflowError)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:123)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:152)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	... 9 more
//...
Caused by: java.lang.IllegalStateException: complete already: DefaultPromise@4a75ea21(failure: java.lang.StackOverflowError)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:123)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:152)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	... 1017 more
Caused by: java.lang.IllegalStateException: complete already: DefaultPromise@4a75ea21(failure: java.lang.StackOverflowError)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:123)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:152)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
//...
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	at io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:112)
	at io.netty.channel.pool.FixedChannelPool.acquire0(FixedChannelPool.java:230)
	at io.netty.channel.pool.FixedChannelPool.access$300(FixedChannelPool.java:37)
	at io.netty.channel.pool.FixedChannelPool$3.run(FixedChannelPool.java:204)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:402)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:136)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
Caused by: java.lang.IllegalStateException: complete already: DefaultPromise@4a75ea21(failure: java.lang.StackOverflowError)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:123)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:152)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
//...
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	at io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:112)
	at io.netty.channel.pool.FixedChannelPool.acquire0(FixedChannelPool.java:230)
	at io.netty.channel.pool.FixedChannelPool.access$300(FixedChannelPool.java:37)
	at io.netty.channel.pool.FixedChannelPool$3.run(FixedChannelPool.java:204)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
Caused by: java.lang.IllegalStateException: complete already: DefaultPromise@4a75ea21(failure: java.lang.StackOverflowError)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:123)

//...
Caused by: java.lang.IllegalStateException: complete already: DefaultPromise@4a75ea21(failure: java.lang.StackOverflowError)
	... 1024 more
//...
Caused by: java.lang.IllegalStateException: complete already: DefaultPromise@4a75ea21(failure: java.lang.StackOverflowError)
	... 1024 more
Caused by: java.lang.StackOverflowError
	at io.netty.util.concurrent.DefaultPromise.notifyListenersWithStackOverFlowProtection(DefaultPromise.java:428)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:424)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:120)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:152)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
//...
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
	at io.netty.channel.pool.SimpleChannelPool.notifyHealthCheck(SimpleChannelPool.java:195)
	at io.netty.channel.pool.SimpleChannelPool.doHealthCheck(SimpleChannelPool.java:170)
	at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:142)
```
[Full exception log without cuts](https://github.com/netty/netty/files/364662/exceptionLog.txt)

It looks like there are possible several problems that could lead to such stacktrace, but at least one is: SimpleChannelPool#acquireHealthyFromPoolOrNew:

```
       catch (Throwable cause) {
            promise.setFailure(cause);
        }
```
which executes on each level from the bottom and each level throws the same IllegalStateException to the top level. On the same time, it's unclear which code set result to Promise (StackOverflowError from too large recursion pooling -> checking looks like).

One more idea: maybe it's worth to make reasonable (maybe configurable) limitation for recursion here.

**Comment by normanmaurer** [comment]
Fixe by https://github.com/netty/netty/pull/5587
