### ISSUE TITLE
java.lang.UnsupportedOperationException during MpscQueue usage

### ISSUE THREAD

**Issue by mrniko** [netty/netty#5581]
Hi!

I have encounter an issue starting from 4.0.38 version with object created via `PlatformDependent.newMpscQueue` method. I see from source code you have changed queue implementation from 4.0.38 version now it uses impl from `io.netty.util.internal.shaded.org.jctools.queues` package instead of yours. And it breaks down sometimes right during simple iteration.

java.lang.UnsupportedOperationException
	at io.netty.util.internal.shaded.org.jctools.queues.MpscChunkedArrayQueue.iterator(MpscChunkedArrayQueue.java:145)
	at org.redisson.command.CommandBatchService.checkConnectionFuture(CommandBatchService.java:338)
	at org.redisson.command.CommandBatchService.execute(CommandBatchService.java:249)
	at org.redisson.command.CommandBatchService.executeAsyncVoid(CommandBatchService.java:138)
	at org.redisson.RedissonBitSet.setAsync(RedissonBitSet.java:227)
	at org.redisson.RedissonBitSet.set(RedissonBitSet.java:70)
	at org.redisson.RedissonBitSetTest.testAnd(RedissonBitSetTest.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

Does anyone else encountered with such problem?

**Comment by Scottmitch** [comment]
This seems like expected behavior as the operation is currently not supported [1]. Would you like to make a feature request to JCTools [2]?

/cc @nitsanw

[1] https://github.com/JCTools/JCTools/blob/master/jctools-core/src/main/java/org/jctools/queues/MpscChunkedArrayQueue.java#L145
[2] https://github.com/JCTools/JCTools/issues

**Comment by nitsanw** [comment]
AFAIK the queue was previously also from JCTools, just source imported rather than properly depended on. That said, this really depends which previous version we're talking about.
Please open a ticket describing your usecase at JCTools and I'll reply there.

**Comment by normanmaurer** [comment]
@nitsanw it was forked but also a bit modified.

**Comment by mrniko** [comment]
> Would you like to make a feature request to JCTools [2]?

Done. Thank you all!
