### ISSUE TITLE
CPU 100% using netty 4.0.24

### ISSUE THREAD

**Issue by likebean** [netty/netty#5621]
In our Product env,CPU 100% occur,Here is env  info:

```
NULL           ===============================
1TISIGINFO     Dump Event "user" (00004000) received 
1TIDATETIME    Date:                 2016/08/02 at 10:00:52
1TIFILENAME    Javacore filename:    /opt/IBM/WebSphere/AppServer/profiles/AppSrv01/javacore.20160802.100052.4568.0001.txt
1TIREQFLAGS    Request Flags: 0x81 (exclusive+preempt)
1TIPREPSTATE   Prep State: 0x4 (exclusive_vm_access)
NULL           ------------------------------------------------------------------------
0SECTION       GPINFO subcomponent dump routine
NULL           ================================
2XHOSLEVEL     OS Level         : Linux 2.6.32-279.el6.x86_64
2XHCPUS        Processors -
3XHCPUARCH       Architecture   : amd64
3XHNUMCPUS       How Many       : 8
3XHNUMASUP       NUMA is either not supported or has been disabled by user
NULL           
1XHERROR2      Register dump section only produced for SIGSEGV, SIGILL or SIGFPE.
NULL           
NULL           ------------------------------------------------------------------------
0SECTION       ENVINFO subcomponent dump routine
NULL           =================================
1CIJAVAVERSION JRE 1.6.0 IBM J9 2.4 Linux amd64-64 build jvmxa6460sr9-20111111_94827
1CIVMVERSION   VM build 20111111_094827
1CIJITVERSION  JIT enabled, AOT enabled - r9_20101028_17488ifx45
1CIGCVERSION   GC - 20101027_AA_CMPRSS
1CIRUNNINGAS   Running as a standalone JVM
```

and we use netty 4.0.24.

and below is TOP -H result:

```
26334 wasuser   20   0 6103m 1.1g  58m R 86.6 14.7 175:00.15 java                                                                                                                                         
26342 wasuser   20   0 6103m 1.1g  58m R 86.6 14.7 173:12.17 java                                                                                                                                         
26340 wasuser   20   0 6103m 1.1g  58m R 84.9 14.7 175:00.22 java                                                                                                                                         
26346 wasuser   20   0 6103m 1.1g  58m R 76.4 14.7 175:16.43 java                                                                                                                                         
26338 wasuser   20   0 6103m 1.1g  58m R 64.5 14.7 176:56.61 java                                                                                                                                         
26336 wasuser   20   0 6103m 1.1g  58m R 61.1 14.7 175:26.48 java                                                                                                                                         
26332 wasuser   20   0 6103m 1.1g  58m R 54.3 14.7 175:45.02 java                                                                                                                                         
26344 wasuser   20   0 6103m 1.1g  58m R 54.3 14.7 175:41.66 java 
``` 

we found top 5 thread's current stack is like:

```
3XMTHREADINFO      "client.worker-thread-3" J9VMThread:0x0000000064C89500, j9thread_t:0x00007F5CC435C350, java/lang/Thread:0x000000000705CF40, state:CW, prio=5
3XMTHREADINFO1            (native thread ID:0x66DE, native priority:0x5, native policy:UNKNOWN)
3XMTHREADINFO2            (native stack address range from:0x00007F5C4A005000, to:0x00007F5C4A046000, size:0x41000)
3XMTHREADINFO3           Java callstack:
4XESTACKTRACE                at java/nio/Bits.copyFromByteArray(Native Method)
4XESTACKTRACE                at java/nio/DirectByteBuffer.put(DirectByteBuffer.java:330(Compiled Code))
4XESTACKTRACE                at java/nio/DirectByteBuffer.put(DirectByteBuffer.java:292(Compiled Code))
4XESTACKTRACE                at io/netty/buffer/UnpooledDirectByteBuf.setBytes(UnpooledDirectByteBuf.java(Compiled Code))
4XESTACKTRACE                at io/netty/buffer/UnpooledDirectByteBuf.setBytes(UnpooledDirectByteBuf.java(Compiled Code))
4XESTACKTRACE                at io/netty/buffer/AbstractByteBuf.writeBytes(AbstractByteBuf.java:850(Compiled Code))
4XESTACKTRACE                at io/netty/channel/nio/AbstractNioChannel.newDirectBuffer(AbstractNioChannel.java:392(Compiled Code))
4XESTACKTRACE                at io/netty/channel/nio/AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:269(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:651(Compiled Code))
4XESTACKTRACE                at io/netty/channel/DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1054(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:714(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651(Compiled Code))
4XESTACKTRACE                at io/netty/handler/codec/MessageToByteEncoder.write(MessageToByteEncoder.java:107(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:714(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:643(Compiled Code))
4XESTACKTRACE                at io/netty/handler/timeout/IdleStateHandler.write(IdleStateHandler.java:259(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext.access$2000(AbstractChannelHandlerContext.java(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java(Compiled Code))
4XESTACKTRACE                at io/netty/channel/AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:918(Compiled Code))
4XESTACKTRACE                at io/netty/util/concurrent/SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380(Compiled Code))
4XESTACKTRACE                at io/netty/channel/nio/NioEventLoop.run(NioEventLoop.java:357(Compiled Code))
4XESTACKTRACE                at io/netty/util/concurrent/SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
4XESTACKTRACE                at java/lang/Thread.run(Thread.java:736)
```

Any advice?

L.J.W

**Comment by Feng-Zihao** [comment]
The information you post is so limited. More detail? Especially on the situation and use scenery?

**Comment by likebean** [comment]
Our netty usage is normal.what infomation else needed?

**Comment by Scottmitch** [comment]
Can you provide a few (e.g. 5) `jstack` outputs while in this 100% CPU usage state, and a few (e.g. 5) `jstack` outputs when in a "normal" state?

A write is being processed in the stack trace above ... just curious how are you handling back pressure? When you are in this 100% cpu usage state ... what is the state of the peer you are communicating with (is it reading data "fast enough")? Also what does your local state look like ... can you provide a heap dump?

**Comment by luengnat** [comment]
you might want to track the GC CPU as well. It looks like you use unpooled DirectByteBuffer. This will cause a high GC rate to clean up the DBB

**Comment by likebean** [comment]
Following is client code:

```
    bootstrap.channel(NioSocketChannel.class);
            bootstrap.option(ChannelOption.TCP_NODELAY, true);
            bootstrap.option(ChannelOption.SO_KEEPALIVE, false);
            bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, getConnectTimeout());
            bootstrap.option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT);
            bootstrap.option(ChannelOption.RCVBUF_ALLOCATOR, AdaptiveRecvByteBufAllocator.DEFAULT);
```
and attchment is javacore file.(I am using IBM J9 JDK,javacore same as jstack in oracle jdk)

**Comment by likebean** [comment]
Following is client code:
```
    bootstrap.channel(NioSocketChannel.class);
            bootstrap.option(ChannelOption.TCP_NODELAY, true);
            bootstrap.option(ChannelOption.SO_KEEPALIVE, false);
            bootstrap.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, getConnectTimeout());
            bootstrap.option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT);
            bootstrap.option(ChannelOption.RCVBUF_ALLOCATOR, AdaptiveRecvByteBufAllocator.DEFAULT);
```

follow is full thread  stack:
[issue-stack.txt](https://github.com/netty/netty/files/400688/issue-stack.txt)

**Comment by luengnat** [comment]
Can you try to run it again with higher setting for MaxDirectMemorySize to see whether it helps? The option looks like this:

-XX:MaxDirectMemorySize=1024m

**Comment by likebean** [comment]
luengnat,thanks for reply,but  when the issue occur,there are few business(in night),so I think it is not caused by high load.

**Comment by luengnat** [comment]
How often does it happen? You seem to use quite an old JVM. IBM JVM has a bunch of fixes in this particular area.

**Comment by likebean** [comment]
This is the First happen.

**Comment by luengnat** [comment]
@likebean Did you find anything?

**Comment by normanmaurer** [comment]
Closing and make with need more info
