### ISSUE TITLE
udt example cannot load the library

### ISSUE THREAD

**Issue by laohoutou** [netty/netty#5652]
I failed to use the udt transport in the netty, when I use the example, it shows me the error:

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.barchart.udt.EpollUDT.<init>(EpollUDT.java:140)
	at com.barchart.udt.nio.SelectorUDT.<init>(SelectorUDT.java:78)
	at com.barchart.udt.nio.SelectorProviderUDT.openSelector(SelectorProviderUDT.java:107)
	at com.barchart.udt.nio.SelectorProviderUDT.openSelector(SelectorProviderUDT.java:24)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:141)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:134)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:109)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:33)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:77)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:48)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:57)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:74)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:69)
	at io.netty.example.udt.echo.message.MsgEchoServer.main(MsgEchoServer.java:44)
Caused by: java.lang.RuntimeException: load
	at com.barchart.udt.SocketUDT.<clinit>(SocketUDT.java:146)
	... 14 more
Caused by: java.lang.IllegalStateException: Fatal: library load failed.
	at com.barchart.udt.lib.LibraryLoaderUDT.load(LibraryLoaderUDT.java:75)
	at com.barchart.udt.SocketUDT.<clinit>(SocketUDT.java:142)
	... 14 more

I run the demo in the ubuntu14.04(32bit)，anyway  can I try to fix it up?

**Comment by normanmaurer** [comment]
@laohoutou you may want to open an issue on the barchart issue tracker.

**Comment by laohoutou** [comment]
@normanmaurer thank you, I forgot to import some jars about the barchart.
