### ISSUE TITLE
Android Exception Ljava/lang/NoSuchMethodError; thrown while initializing Lorg/jboss/marshalling/Marshalling;

### ISSUE THREAD

**Issue by donggx** [netty/netty#5706]
Exception Ljava/lang/NoSuchMethodError; thrown while initializing Lorg/jboss/marshalling/Marshalling;
08-16 07:35:54.686 29429-29651/com.netty.test W/ChannelInitializer: Failed to initialize a channel. Closing: [id: 0xc439463f]
                                                                              java.lang.NoSuchMethodError: <init> [boolean]
                                                                                  at org.jboss.marshalling.Marshalling$OptionalDataExceptionCreateAction$1.run(Marshalling.java:384)
                                                                                  at org.jboss.marshalling.Marshalling$OptionalDataExceptionCreateAction$1.run(Marshalling.java:377)
                                                                                  at java.security.AccessController.doPrivileged(AccessController.java:45)
                                                                                  at org.jboss.marshalling.Marshalling$OptionalDataExceptionCreateAction.<init>(Marshalling.java:377)
                                                                                  at org.jboss.marshalling.Marshalling$OptionalDataExceptionCreateAction.<init>(Marshalling.java:372)
                                                                                  at org.jboss.marshalling.Marshalling.<clinit>(Marshalling.java:370)
                                                                                  at com.netty.connection.codec.util.MarshallingCodeCFactory.buildMarshallingDecoder(MarshallingCodeCFactory.java:31)

this is code :

import io.netty.handler.codec.marshalling.DefaultMarshallerProvider;
import io.netty.handler.codec.marshalling.DefaultUnmarshallerProvider;
import io.netty.handler.codec.marshalling.MarshallerProvider;
import io.netty.handler.codec.marshalling.MarshallingDecoder;
import io.netty.handler.codec.marshalling.MarshallingEncoder;
import io.netty.handler.codec.marshalling.UnmarshallerProvider;

import org.jboss.marshalling.MarshallerFactory;
import org.jboss.marshalling.Marshalling;
import org.jboss.marshalling.MarshallingConfiguration;

public class MarshallingCodeCFactory {
	

	public static MarshallingEncoder buildMarshallingEncoder() {
		final MarshallerFactory factory = Marshalling.getProvidedMarshallerFactory("serial");
		final MarshallingConfiguration config = new MarshallingConfiguration();
		config.setVersion(5);
		MarshallerProvider provider = new DefaultMarshallerProvider(factory, config);
		MarshallingEncoder encoder = new MarshallingEncoder(provider);
		return encoder;
	}

	public static MarshallingDecoder buildMarshallingDecoder() {
		final MarshallerFactory factory = Marshalling.getProvidedMarshallerFactory("serial");
		final MarshallingConfiguration config = new MarshallingConfiguration();
		config.setVersion(5);
		UnmarshallerProvider provider = new DefaultUnmarshallerProvider(factory, config);
		MarshallingDecoder decoder = new MarshallingDecoder(provider);
		return decoder;
	}

}

**Comment by normanmaurer** [comment]
This looks like a class path exception. Please check android docs or consult android devs

**Comment by normanmaurer** [comment]
Or it could also be jboss marshalling bug.

**Comment by donggx** [comment]
the class path is right，it looks like：

   packagingOptions {
        exclude 'META-INF/INDEX.LIST'
        exclude "META-INF/io.netty.versions.properties"
    }

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.jboss.marshalling:jboss-marshalling:1.4.9.Final'
    compile 'org.jboss.marshalling:jboss-marshalling-serial:1.4.9.Final'
}

I can user the libray of netty-all-5.0.0.Alpha2.jar
