### ISSUE TITLE
EpollServerSocketChannel error

### ISSUE THREAD

**Issue by beykery** [netty/netty#5707]
when i use the EpollServerSocketChannel ,the exception stack trace is below:

Exception in thread "Application" io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.epoll.EpollServerSocketChannel
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:281)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:277)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:252)
	at org.ngame.socket.NServer.start(NServer.java:236)
	at org.ngame.socket.NServer.start(NServer.java:161)
	at org.ngame.server.BaseServer.start(BaseServer.java:275)
	at org.ngame.app.Application.start(Application.java:187)
	at org.ngame.app.Application.start(Application.java:276)
	at org.ngame.app.Application.main(Application.java:340)
Caused by: java.lang.UnsatisfiedLinkError: io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errnoENOTCONN()I
	at io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errnoENOTCONN(Native Method)
	at io.netty.channel.unix.Errors.<clinit>(Errors.java:40)
	at io.netty.channel.unix.FileDescriptor.<clinit>(FileDescriptor.java:48)
	at io.netty.channel.epoll.EpollServerSocketChannel.<init>(EpollServerSocketChannel.java:46)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	... 10 more

why?
the netty version is netty-all-4.1.4.Final

**Comment by alexandnpu** [comment]
Today I came to the similar stacktrace as yours. After some debugging, I found that it is due to the mismatch between your eventloop type and bootstrap channel type. You can try to give it a check.

Hope it helps.
