### ISSUE TITLE
Epoll TCP-MD5 keymapping limitation

### ISSUE THREAD

**Issue by aenniw** [netty/netty#5719]
I came across an issue while using netty-4.0.37.final and Epoll, if TCP-MD5SIG map contains >=256 entries following error occurs: "setsockopt() failed: Cannot allocate memory" could someone provide some info about this issue ? Thanks. 

full error log:

java.lang.IllegalStateException: channel not registered to an event loop
	at io.netty.channel.AbstractChannel.eventLoop(AbstractChannel.java:116)[69:io.netty.transport:4.0.37.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.doDeregister(AbstractEpollChannel.java:132)[73:io.netty.transport-native-epoll:4.0.37.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.doClose(AbstractEpollChannel.java:109)[73:io.netty.transport-native-epoll:4.0.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.closeForcibly(AbstractChannel.java:638)[69:io.netty.transport:4.0.37.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:312)[69:io.netty.transport:4.0.37.Final]
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:272)[69:io.netty.transport:4.0.37.Final]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:268)[69:io.netty.transport:4.0.37.Final]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:257)[69:io.netty.transport:4.0.37.Final]

io.netty.channel.ChannelException: setsockopt() failed: Cannot allocate memory
	at io.netty.channel.epoll.Native.setTcpMd5Sig0(Native Method)[73:io.netty.transport-native-epoll:4.0.37.Final]
	at io.netty.channel.epoll.Native.setTcpMd5Sig(Native.java:243)[73:io.netty.transport-native-epoll:4.0.37.Final]
	at io.netty.channel.epoll.TcpMd5Util.newTcpMd5Sigs(TcpMd5Util.java:69)[73:io.netty.transport-native-epoll:4.0.37.Final]
	at io.netty.channel.epoll.EpollServerSocketChannel.setTcpMd5Sig(EpollServerSocketChannel.java:130)[73:io.netty.transport-native-epoll:4.0.37.Final]
	at io.netty.channel.epoll.EpollServerSocketChannelConfig.setTcpMd5Sig(EpollServerSocketChannelConfig.java:167)[73:io.netty.transport-native-epoll:4.0.37.Final]
	at io.netty.channel.epoll.EpollServerSocketChannelConfig.setOption(EpollServerSocketChannelConfig.java:73)[73:io.netty.transport-native-epoll:4.0.37.Final]
	at io.netty.channel.DefaultChannelConfig.setOptions(DefaultChannelConfig.java:113)[69:io.netty.transport:4.0.37.Final]
	at io.netty.bootstrap.ServerBootstrap.init(ServerBootstrap.java:153)[69:io.netty.transport:4.0.37.Final]
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:310)[69:io.netty.transport:4.0.37.Final]
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:272)[69:io.netty.transport:4.0.37.Final]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:268)[69:io.netty.transport:4.0.37.Final]
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:257)[69:io.netty.transport:4.0.37.Final]

**Comment by normanmaurer** [comment]
Can you sharr a reproducer?

**Comment by normanmaurer** [comment]
@aenniw  this is not a netty bug but related to your `/proc/sys/net/core/optmem_max` setting. Try to increase it and you will see it works.

See also:

http://bird.network.cz/pipermail/bird-users/2015-August/009870.html

**Comment by aenniw** [comment]
Thanks for explanation, this solved the issue.
Regards
