### ISSUE TITLE
netty OutOfDirectMemoryError in socks server

### ISSUE THREAD

**Issue by wudizhanche1000** [netty/netty#5723]
Netty: 4.1.4.Final
Java: 1.8.0_101
OS: Linux 4.4.0-31-generic 

This happened in my code and netty example socks proxy code.

I test it with following command where 1000M is a 1000M file contains random data
`proxychains ab -n 1000 -c 100 http://127.0.0.1/1000M`
It costs huge amount of memory(over 4GB) and prints exception like this. Why would it happen, could you please check this?

**Backtrace**
`io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 3724541952, max: 3726639104)
    at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:614)
    at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:568)
    at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:686)
    at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:675)
    at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:237)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:221)
    at io.netty.buffer.PoolArena.allocate(PoolArena.java:141)
    at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:262)
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:179)
    at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:170)
    at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:131)
    at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:73)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
    at java.lang.Thread.run(Thread.java:745)
`

**Comment by maseev** [comment]
@wudizhanche1000 It would be great if you could provide some code example and full stacktrace. 

As I'm aware of, Netty's proxy example uses backpressure mechanism (it changes channel's AUTO_READ property depending on the channel's writability status), so It's very unlikely that the problem in Netty's example code.

Can you provide a reproducer or a snippet of code that contains the main logic of your program? It would be more simpler to help you if you could provide this information.

**Comment by wudizhanche1000** [comment]
@maseev I just compile socksproxy in example code. And test it with following command 
`proxychains ab -n 1000 -c 100 http://127.0.0.1/1000M ` where I start a nginx service on localhost port 80, and put a random file size of 1000M. 

After read your comment, I test example code again with AUTO_READ off, and it failed again, here's my changes.

**SocksServerConnectHandler.java** line 56
`                              
responseFuture.addListener(new ChannelFutureListener() {
@Override
public void operationComplete(ChannelFuture channelFuture) {
    ctx.pipeline().remove(SocksServerConnectHandler.this);
    ctx.channel().config().setAutoRead(false);
    outboundChannel.config().setAutoRead(false);
    outboundChannel.pipeline().addLast(new RelayHandler(ctx.channel()));
    ctx.pipeline().addLast(new RelayHandler(outboundChannel));
}
});
`
**RelayHandler.java** line 38
`  @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) {
        if (relayChannel.isActive()) {
            relayChannel.writeAndFlush(msg).addListener((ChannelFutureListener) future -> {
                if (future.isSuccess()) {
                    ctx.read();
                }
            });
        } else {
            ReferenceCountUtil.release(msg);
        }
    }`

**Comment by wudizhanche1000** [comment]
I don't know why github didn't format my code, I just turn auto read off and add a listener for reading following data.

**Comment by maseev** [comment]
@wudizhanche1000 It's kinda difficult to understand what your application is actually doing. I think you simply forgot to release incoming byte buffers somewhere. Try to enable [memory leak detection](http://netty.io/wiki/reference-counted-objects.html#leak-detection-levels) in Netty.

**Comment by wudizhanche1000** [comment]
@maseev this is not my code, it's sample code in [netty example](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/socksproxy), and no memory leak was detected even in PARANOID level.

**Comment by refine36** [comment]
@wudizhanche1000 i have meet the same question, have you solve it yet?

**Comment by mrniko** [comment]
Same issue with Netty: 4.1.6.Final and memory leak detection doesn't help

**Comment by doom369** [comment]
Same issue, also Netty: 4.1.4.Final.

I was able to make dump diff.

![4e628062-cd2f-11e6-9d4f-8df914157cb9](https://cloud.githubusercontent.com/assets/1536494/21694551/8bd52746-d38e-11e6-91a3-f30f2022c52c.png)

**Comment by Scottmitch** [comment]
> It seems that there is something leak in HttpPostMultipartRequestDecoder

@refine36 - Why do you think the leak is in `HttpPostMultipartRequestDecoder `? Do you have a leak report?

**Comment by normanmaurer** [comment]
Let me close this as there was no more followup from the reporter. Please reopen if you still think there is an issue after upgrading to latest version and provide more infos
