### ISSUE TITLE
The example of websocketx doesn't work.

### ISSUE THREAD

**Issue by joymufeng** [netty/netty#5759]
This issue exists in netty-4.1.4.Final.
**Test-1:  Run server.WebSocketServer and client.WebSocketClient with JDK 1.6.0_65**
Input "hello" in WebSocketClient's console, no response back:
```
WebSocket Client connected!
hello
```
**Test-2:  Run server.WebSocketServer and client.WebSocketClient with JDK 1.7.0_80 or JDK 1.8.0_51**
Input "hello" in WebSocketClient's console, `CorruptedFrameException` exception thrown:
```
WebSocket Client connected!
hello
WebSocket Client disconnected!
io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:4
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:188)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```
**Test-3:  Remove `WebSocketClientCompressionHandler.INSTANCE` from  client.WebSocketClient's Pipeline, run with JDK 1.6.0_65**
```
p.addLast(
          new HttpClientCodec(),
          new HttpObjectAggregator(8192),
          //WebSocketClientCompressionHandler.INSTANCE,
          handler);
```
Input "hello" in WebSocketClient's console,  it works well:
```
WebSocket Client connected!
hello
WebSocket Client received message: HELLO
```

**Comment by normanmaurer** [comment]
Checking...

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5797

**Comment by HK-hub** [comment]
I also encountered this problem, please let me know if there is a possible solution, but I encountered this problem in version 4.4.6 of Vert.x. And basically can not solve this problem from the source code
