### ISSUE TITLE
IndexOutOfBoundsException from CompositeByteBuf.forEachByteDesc

### ISSUE THREAD

**Issue by npordash** [netty/netty#5773]
After updating from 4.1.4.Final to 4.1.5.Final I have failing tests because of the following:

```java
java.lang.IndexOutOfBoundsException: index: 21, length: 1 (expected: range(0, 21))
	at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1359)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1354)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1349)
	at io.netty.buffer.CompositeByteBuf.findComponent(CompositeByteBuf.java:1407)
	at io.netty.buffer.CompositeByteBuf._getByte(CompositeByteBuf.java:751)
	at io.netty.buffer.AbstractByteBuf.forEachByteDesc0(AbstractByteBuf.java:1297)
	at io.netty.buffer.AbstractByteBuf.forEachByteDesc(AbstractByteBuf.java:1277)
```

This seems to be specific to CompositeByteBuf:

```java

// Doesn't throw
Unpooled.copiedBuffer("test", StandardCharsets.UTF_8)
    .forEachByteDesc(ByteProcessor.FIND_CR);

// Throws (forEachByteDesc)
Unpooled.compositeBuffer()
    .addComponent(true, Unpooled.copiedBuffer("test", StandardCharsets.UTF_8))
    .forEachByteDesc(ByteProcessor.FIND_CR);

// Doesn't throw (forEachByte)
Unpooled.compositeBuffer()
    .addComponent(true, Unpooled.copiedBuffer("test", StandardCharsets.UTF_8))
    .forEachByte(ByteProcessor.FIND_CR);
```

**Comment by normanmaurer** [comment]
Will have a look

**Comment by normanmaurer** [comment]
@npordash I think I have an idea... stay tuned

**Comment by Scottmitch** [comment]
thanks for the repro @npordash

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty/pull/5783

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5783
