### ISSUE TITLE
Epoll transport doesn't work with custom FileRegion implementation

### ISSUE THREAD

**Issue by akurilov** [netty/netty#5800]
- Netty version: 4.1.5.Final, 5.0.0.Alpha2
- Tried to use custom FileRegion implementation with epoll transport
- Expected: any FileRegion DMA implementation works with epoll transport as with NIO transport
- Observerd: epoll transport expects only the particular DefaultFileRegion implementation:

```
java.lang.UnsupportedOperationException: unsupported message type: DataItemFileRegion (expected: ByteBuf, DefaultFileRegion)
	at io.netty.channel.epoll.AbstractEpollStreamChannel.filterOutboundMessage(AbstractEpollStreamChannel.java:539)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:799)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1291)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:826)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:733)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.write(CombinedChannelDuplexHandler.java:525)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:111)
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:748)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:740)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:826)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:733)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:714)

**Comment by normanmaurer** [comment]
@akurilov let me fix this.

**Comment by Scottmitch** [comment]
also FYI Netty 5.x has been discontinued.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5825
