### ISSUE TITLE
java.lang.IncompatibleClassChangeError issue happened in 4.x android device

### ISSUE THREAD

**Issue by xiepengchong** [netty/netty#5822]
java.lang.IncompatibleClassChangeError: interface not implemented
	at org.jboss.netty.util.HashedWheelTimer$Worker.fetchExpiredTimeouts(HashedWheelTimer.java)
	at org.jboss.netty.util.HashedWheelTimer$Worker.fetchExpiredTimeouts(HashedWheelTimer.java)
	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:368)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at java.lang.Thread.run(Thread.java:841

I think this is caused by my modify for compileSdkVersion from 19 to 23,
can any one konw how to resolve this problem
thanks

 my netty version is netty-3.2.3.Final.jar

**Comment by Scottmitch** [comment]
Netty 3.x has been EOL. Please update to Netty 4 for support.
