### ISSUE TITLE
UnsatisfiedLinkError: org.apache.tomcat.jni.Library.version(I)I

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#5827]
We're trying to upgrade to OpenSSL 1.0.2h it has started failing with the following error (see below). Not sure what has changed. I found a few recent tickets with the same or similar exception but we're not using OSGi.

```
java.lang.UnsatisfiedLinkError: org.apache.tomcat.jni.Library.version(I)I
	at org.apache.tomcat.jni.Library.version(Native Method) ~[netty-tcnative-1.1.33.Fork22-linux-x86_64.jar:1.1.33.Fork22]
	at org.apache.tomcat.jni.Library.initialize(Library.java:178) ~[netty-tcnative-1.1.33.Fork22-linux-x86_64.jar:1.1.33.Fork22]
	at io.netty.handler.ssl.OpenSsl.initializeTcNative(OpenSsl.java:385) ~[netty-all-4.1.6.Final-SNAPSHOT.jar:4.1.6.Final-SNAPSHOT]
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:110) [netty-all-4.1.6.Final-SNAPSHOT.jar:4.1.6.Final-SNAPSHOT]
```

**Comment by rkapsi** [comment]
Disregard, problem is on this side of the screen.

We run a fedora derivative but our previous OpenSSL libs were built the non-fedora way. The plain linux-x86_64.jar just happened to work. Switching to linux-x86_64-fedora.jar resolved the problem
