### ISSUE TITLE
OpenSSL Issue

### ISSUE THREAD

**Issue by damage85** [netty/netty#5835]
I used netty4+netty-tcnative.fork16 on centos 6.5, openssl 1.0.2h was installed, and I found a problem as below, I had no idea how to fix this.  My question is I don't know why netty-tcnative try to find libcrypto.so.1.0.0 and how to change the ssl version it needs.

> [root@datanode008 lib64]# ll _cry_
> -rw-r--r--. 1 root root 4023062 5月   9 20:32 libcrypto.a
> lrwxrwxrwx. 1 root root      19 9月  13 15:20 libcrypto.so -> libcrypto.so.1.0.1e
> -rwxr-xr-x. 1 root root 1408384 3月   9 2016 libcrypto.so.0.9.8e
> lrwxrwxrwx. 1 root root      19 9月  13 15:20 libcrypto.so.10 -> libcrypto.so.1.0.1e
> lrwxrwxrwx. 1 root root      19 9月  13 15:15 libcrypto.so.1.0.0 -> libcrypto.so.1.0.1e
> -rwxr-xr-x. 1 root root 1969952 5月   9 20:32 libcrypto.so.1.0.1e
> lrwxrwxrwx. 1 root root      19 9月  13 15:20 libcrypto.so.6 -> libcrypto.so.0.9.8e
> lrwxrwxrwx. 1 root root      25 9月  13 15:40 libcrypt.so -> ../../lib64/libcrypt.so.1
> lrwxrwxrwx. 1 root root      19 6月  26 2015 libcryptui.so.0 -> libcryptui.so.0.0.0
> -rwxr-xr-x. 1 root root   78312 8月  23 2010 libcryptui.so.0.0.0
> lrwxrwxrwx. 1 root root      30 6月  26 2015 libk5crypto.so -> ../../lib64/libk5crypto.so.3.1
> 
>  DEBUG i.n.u.internal.NativeLibraryLoader    Unable to load the library: netty-tcnative.
> java.lang.UnsatisfiedLinkError: /tmp/libnetty-tcnative3758370492280953597.so: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /tmp/libnetty-tcnative3758370492280953597.so)
>         at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_91]
>         at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) ~[na:1.8.0_91]
>         at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) ~[na:1.8.0_91]
>         at java.lang.Runtime.load0(Runtime.java:809) ~[na:1.8.0_91]
>         at java.lang.System.load(System.java:1086) ~[na:1.8.0_91]
>         at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:214) ~[io.netty.netty-common-4.1.0.CR6.jar:4.1.0.CR6]
>         at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:161) ~[io.netty.netty-common-4.1.0.CR6.jar:4.1.0.CR6]
>         at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:78) [io.netty.netty-handler-4.1.0.CR6.jar:4.1.0.CR6]
>         at com.relayrides.pushy.apns.ApnsClient.getBaseSslContextBuilder(ApnsClient.java:366) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.getSslContextWithCertificateAndPrivateKey(ApnsClient.java:358) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:354) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:331) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:234) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:209) [com.relayrides.pushy-0.6.1.jar:na]
>         at im.actor.server.sequence.ApplePushExtension.im$actor$server$sequence$ApplePushExtension$$$anonfun$7(ApplePushExtension.scala:70) [im.actor.server.actor-core-1.0.153.jar:1.0.153]
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:166) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:164) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
>         at scala.concurrent.package$.blocking(package.scala:123) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at im.actor.server.sequence.ApplePushExtension.im$actor$server$sequence$ApplePushExtension$$$anonfun$6(ApplePushExtension.scala:69) [im.actor.server.actor-core-1.0.153.jar:1.0.153]
>         at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:407) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>  DEBUG io.netty.handler.ssl.OpenSsl    Failed to load netty-tcnative; OpenSslEngine will be unavailable. See http://netty.io/wiki/forked-tomcat-native.html for more information.
> java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-linux-x86_64, netty-tcnative-linux-x86_64-fedora, netty-tcnative]
>         at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:167) ~[io.netty.netty-common-4.1.0.CR6.jar:4.1.0.CR6]
>         at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:78) ~[io.netty.netty-handler-4.1.0.CR6.jar:4.1.0.CR6]
>         at com.relayrides.pushy.apns.ApnsClient.getBaseSslContextBuilder(ApnsClient.java:366) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.getSslContextWithCertificateAndPrivateKey(ApnsClient.java:358) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12InputStream(ApnsClient.java:354) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.getSslContextWithP12File(ApnsClient.java:331) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:234) [com.relayrides.pushy-0.6.1.jar:na]
>         at com.relayrides.pushy.apns.ApnsClient.<init>(ApnsClient.java:209) [com.relayrides.pushy-0.6.1.jar:na]
>         at im.actor.server.sequence.ApplePushExtension.im$actor$server$sequence$ApplePushExtension$$$anonfun$7(ApplePushExtension.scala:70) [im.actor.server.actor-core-1.0.153.jar:1.0.153]
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:166) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:164) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
>         at scala.concurrent.package$.blocking(package.scala:123) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at im.actor.server.sequence.ApplePushExtension.im$actor$server$sequence$ApplePushExtension$$$anonfun$6(ApplePushExtension.scala:69) [im.actor.server.actor-core-1.0.153.jar:1.0.153]
>         at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:39) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:407) ~[com.typesafe.akka.akka-actor_2.11-2.4.6.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) ~[org.scala-lang.scala-library-2.11.8.jar:na]
>  INFO  com.relayrides.pushy.apns.ApnsClient    OpenSSL (via netty-tcnative) not available; will use JDK SSL provider.
>  DEBUG io.netty.handler.ssl.JdkSslContext    Default protocols (JDK): [TLSv1.2, TLSv1.1, TLSv1]

**Comment by normanmaurer** [comment]
Please upgrade to latest version and let us know if you still see an issue
