### ISSUE TITLE
io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:4

### ISSUE THREAD

**Issue by fangqiao** [netty/netty#5837]
Hi,

I am developing a simple Websocket messaging application using Netty.

I slightly modified the official Netty Websocket client example as front end testing tool, just added sending cookies at handshake for authorization.

The socket was able to open. But when TextWebSocketFrame was sent back from backend, the client thrown out the following excepton:

io.netty.handler.codec.CorruptedFrameException: RSV != 0 and no extension negotiated, RSV:4
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:412)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:188)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

I am using 4.1.5.

Thanks in advance.

**Comment by fangqiao** [comment]
By commenting out the WebSocketClientCompressionHandler at frontend and WebSocketServerCompressionHandler at server side, the problem was solved.

I guess it is incompatibility between the two handlers.

**Comment by sunng87** [comment]
When using websocket compression, you need to set `allowExtension` to `true` when adding WebSocketServerProtocolHandler and WebSocketClientProtocolHandler.

**Comment by fangqiao** [comment]
@sunng87  thanks. It works.

**The example code set allowExtension to false.**  even compression handler was added.

May I suggest to update the example?

**Comment by normanmaurer** [comment]
This is fixed in 4.1 branch and will be part of the next release.

**Comment by HK-hub** [comment]
I have also encountered this problem, please let me know if there is a possible solution
