### ISSUE TITLE
Memory leak :  java.lang.OutOfMemoryError “Direct buffer memory”

### ISSUE THREAD

**Issue by uglycow** [netty/netty#5842]
you may encounter this problem when you are using 
``` java
public static final ByteBufAllocator byteBufAllocator = UnpooledByteBufAllocator.DEFAULT;
```
and configure your Encoder as “preferDirect = false”, so you are using  HeapBuf for encoding.
``` java
public class NettyProtocolEncoder extends MessageToByteEncoder<Object> {

    public NettyProtocolEncoder() {
        super(false);
    }
```

the problem is caused by the code below

``` java

protected final Object filterOutboundMessage(Object msg) {
        if (msg instanceof ByteBuf) {
            ByteBuf buf = (ByteBuf) msg;
            if (buf.isDirect()) {
                return msg;
            }

            return newDirectBuffer(buf);
        }

        if (msg instanceof FileRegion) {
            return msg;
        }

        throw new UnsupportedOperationException(
                "unsupported message type: " + StringUtil.simpleClassName(msg) + EXPECTED_TYPES);
    }


 static final class ThreadLocalDirectByteBuf extends UnpooledDirectByteBuf {

        private static final Recycler<ThreadLocalDirectByteBuf> RECYCLER = new Recycler<ThreadLocalDirectByteBuf>() {
            @Override
            protected ThreadLocalDirectByteBuf newObject(Handle handle) {
                return new ThreadLocalDirectByteBuf(handle);
            }
        };

        static ThreadLocalDirectByteBuf newInstance() {
            ThreadLocalDirectByteBuf buf = RECYCLER.get();
            buf.setRefCnt(1);
            return buf;
        }

        private final Handle handle;

        private ThreadLocalDirectByteBuf(Handle handle) {
            super(UnpooledByteBufAllocator.DEFAULT, 256, Integer.MAX_VALUE);
            this.handle = handle;
        }

        @Override
        protected void deallocate() {
            if (capacity() > THREAD_LOCAL_BUFFER_SIZE) {
                super.deallocate();
            } else {
                clear();
                RECYCLER.recycle(this, handle);
            }
        }
    }
```

- netty tried to convert the HeapBuf into a DirectBuf (filterOutboundMessage method)。The DirectBuf  is retrieved from RECYCLER
- RECYCLER  may hold a large amount of ThreadLocalDirectByteBuf. 
- RECYCLER  is not used to retrieve buffer when reading data. Attempts  to allocate DirectBuffer may trigger FullGC
- your peer could be in the same situation. so both side get blocked.

i'm wondering why we are not using RECYCLER  when reading data?

**Comment by Underbalanced** [comment]
- Do you have the full stack trace?  
- What happens when you use Pooled && !preferDirect? Over Unpooled and && !preferDirect?
- Is this your handler? Where is your logic from Object with it being written to the channel or channel handler context with it passing through the pipline? The code you said that is causing the problem does not seem to have a problem and is acting on the msg as its intended to.

Hopefully with a bigger picture we can resolve this problem.

**Comment by uglycow** [comment]
@Underbalanced 

With default configuration,  io.netty.buffer.ByteBufUtil.ThreadLocalUnsafeDirectByteBuf#RECYCLER could cache too many buffers.

``` java
static final class ThreadLocalUnsafeDirectByteBuf extends UnpooledUnsafeDirectByteBuf {

        private static final Recycler<ThreadLocalUnsafeDirectByteBuf> RECYCLER =
                new Recycler<ThreadLocalUnsafeDirectByteBuf>() {
                    @Override
                    protected ThreadLocalUnsafeDirectByteBuf newObject(Handle handle) {
                        return new ThreadLocalUnsafeDirectByteBuf(handle);
                    }
                };

        static ThreadLocalUnsafeDirectByteBuf newInstance() {
            ThreadLocalUnsafeDirectByteBuf buf = RECYCLER.get();
            buf.setRefCnt(1);
            return buf;
        }

        private final Handle handle;

        private ThreadLocalUnsafeDirectByteBuf(Handle handle) {
            super(UnpooledByteBufAllocator.DEFAULT, 256, Integer.MAX_VALUE);
            this.handle = handle;
        }

        @Override
        protected void deallocate() {
            if (capacity() > THREAD_LOCAL_BUFFER_SIZE) {
                super.deallocate();
            } else {
                clear();
                RECYCLER.recycle(this, handle);
            }
        }
    }
```
the stack trace is
``` java
java.lang.Thread.State: RUNNABLE
	  at io.netty.buffer.ByteBufUtil$ThreadLocalUnsafeDirectByteBuf.newInstance(ByteBufUtil.java:827)
	  at io.netty.buffer.ByteBufUtil.threadLocalDirectBuffer(ByteBufUtil.java:810)
	  at io.netty.channel.nio.AbstractNioChannel.newDirectBuffer(AbstractNioChannel.java:408)
	  at io.netty.channel.nio.AbstractNioByteChannel.filterOutboundMessage(AbstractNioByteChannel.java:275)
	  at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:742)
	  at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1304)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:619)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:676)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:612)
	  at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:113)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:619)
	  at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:676)
	  at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:667)
	  at bz.test.netty.client.ClientHandler.write(ClientHandler.java:20)
	  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:619)
	  at io.netty.channel.AbstractChannelHandlerContext.access$1800(AbstractChannelHandlerContext.java:32)
	  at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:904)
	  at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:889)
	  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	  at java.lang.Thread.run(Thread.java:745)

```
with some configuration, u could limit the amount of cached buffer.
so i wont say it's a memory  leak problem.
