### ISSUE TITLE
SingleThreadEventLoopTest#scheduleLaggyTaskAtFixedRateB failure

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#5851]
```
[01:10:22][io.netty.channel.SingleThreadEventLoopTest] scheduleLaggyTaskAtFixedRateB
[01:10:22][scheduleLaggyTaskAtFixedRateB] java.lang.AssertionError: expected:<5> but was:<0>
[01:10:22]
[scheduleLaggyTaskAtFixedRateB] java.lang.AssertionError: expected:<5> but was:<0>
	at io.netty.channel.SingleThreadEventLoopTest.testScheduleLaggyTaskAtFixedRate(SingleThreadEventLoopTest.java:244)
	at io.netty.channel.SingleThreadEventLoopTest.scheduleLaggyTaskAtFixedRateB(SingleThreadEventLoopTest.java:223)
```

**Comment by Scottmitch** [comment]
Discovered while building PR https://github.com/netty/netty/pull/5844

https://garage.netty.io/teamcity/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=12611#_focus=84902&state=84902
