### ISSUE TITLE
SSLHandler Removal Exceptions 

### ISSUE THREAD

**Issue by Underbalanced** [netty/netty#5860]
I use SSL as my form of server to server authentication in a back-end configuration. When I remove or close the SSL Handler so that I can make my connection unsecured once authenticated. I keep getting exceptions and I have tried this in multiple ways on both the client and server.  My handlers and pipeline...
```
p.addFirst("ssl",  sslCtx.newHandler(c.alloc()));
p.addAfter("ssl", "chunked-writer", new ChunkedWriteHandler());
p.addAfter("chunked-writer", "decoder", decoder); // ByteToMessageDecoder (Anonymous... ommitted)
```

- First I tried removing the handler on both ends after handshake success.

```
  sslHandler.handshakeFuture().addListener(channelFuture -> {
       if (channelFuture.isSuccess()) {
           p.remove(sslHandler);
           ChannelFuture future = c.writeAndFlush(PooledByteBufAllocator.DEFAULT.directBuffer().writeInt(DEVELOPMENT_FILE_SERVER_MAGIC_NUMBER));
        }
   });
```

Results in
```
io.netty.handler.codec.DecoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1711)
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1666)
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1407)
	at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1353)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.internalNioBuffer(PooledUnsafeDirectByteBuf.java:331)
	at io.netty.buffer.WrappedByteBuf.internalNioBuffer(WrappedByteBuf.java:939)
	at io.netty.buffer.AdvancedLeakAwareByteBuf.internalNioBuffer(AdvancedLeakAwareByteBuf.java:736)
	at io.netty.handler.ssl.SslHandler.toByteBuffer(SslHandler.java:1102)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1094)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:966)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:900)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 20 more
```

- Second I tried closing the handler first then removing it. 

```
    sslHandler.handshakeFuture().addListener(channelFuture -> {
        if (channelFuture.isSuccess()) {
            ChannelFuture close = sslHandler.close();
            close.addListeners(new ChannelFutureListener() {

                @Override
                 public void operationComplete(final ChannelFuture channelFuture) throws Exception {
                     p.remove(sslHandler);
                     ChannelFuture future = c.writeAndFlush(PooledByteBufAllocator.DEFAULT.directBuffer().writeInt(DEVELOPMENT_FILE_SERVER_MAGIC_NUMBER));
             }
     });
```

Results In: (Appears some data is being fired and hitting my other handler because the client is not writing data yet as I have not implemented that during the test)

```
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(16) + length(770414) exceeds writerIndex(31): PooledUnsafeDirectByteBuf(ridx: 16, widx: 31, cap: 512)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.internal.chmv8.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1412)
	at io.netty.util.internal.chmv8.ForkJoinTask.doExec(ForkJoinTask.java:280)
	at io.netty.util.internal.chmv8.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:877)
	at io.netty.util.internal.chmv8.ForkJoinPool.scan(ForkJoinPool.java:1711)
	at io.netty.util.internal.chmv8.ForkJoinPool.runWorker(ForkJoinPool.java:1666)
	at io.netty.util.internal.chmv8.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:126)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(16) + length(770414) exceeds writerIndex(31): PooledUnsafeDirectByteBuf(ridx: 16, widx: 31, cap: 512)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1395)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1389)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850)
	at io.netty.buffer.WrappedByteBuf.readBytes(WrappedByteBuf.java:655)
	at io.netty.buffer.AdvancedLeakAwareByteBuf.readBytes(AdvancedLeakAwareByteBuf.java:502)
	at com.freeuniversegames.general.general_eight.netty.variant.VLQDecoder.unsafeDecodeArray(VLQDecoder.java:199)
	at com.freeuniversegames.general.general_eight.netty.variant.VLQDecoder.unsafeDecodeString(VLQDecoder.java:140)
	at com.freeuniversegames.general.general_eight.netty.variant.VLQDecoder.unsafeDecodeString(VLQDecoder.java:162)
	at com.freeuniversegames.general.general_eight.netty.variant.NetworkFileEncoderDecoder.readMetaData(NetworkFileEncoderDecoder.java:128)
	at com.freeuniversegames.general.general_eight.netty.variant.NetworkFileEncoderDecoder.read(NetworkFileEncoderDecoder.java:146)
	at com.freeuniversegames.infastructure.development_file_server.FileServer$1$2.decode(FileServer.java:253)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 24 more
```

**Comment by normanmaurer** [comment]
Please share the code of you custom handlers. In general it seems like you do something bad in your handler. Also it seems like you use a very old version of netty. Please upgrade to latest 4.1 release.

**Comment by Underbalanced** [comment]
@normanmaurer 

- My apologize I should have known to provide the tested versions as well as the code showing without my handlers.
- The code below is neutral and basic using only Netty and produces the same exception when removing the SSL handlers, the error happens on both ends and it happens on both `4.1.5.Final` and `4.0.41.Final`

> Note: I just wrote this on a computer I cannot transfer it from so I hand jammed this; please excuse any errors.

```
public static final String SSL_HANDLER = "ssl-handler";
public static final String HOST = "localhost";
public static final String POST = "6987";

public static main (String[] args){
	ForkJoinPool threading = new ForkJoinPool(3);
	NioEventLoopGroup executors = new NioEventLoopGroup(2, threading);
	
	Bootstrap bootstrap = new Bootstrap()
		.group(executors)
		.channel(NioSocketChannel.class)
		.handler(new ChannelInitializer<Channel>() {
			@Override
			protected void initChannel (Channel ch) throws Exception {
					SslContext build = SslContextBuilder.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build();
					final SslHandler sslHandler = build.newHandler(ch.alloc());
					ch.pipeline().addFirst(SSL_HANDLER, sslHandler);
					sslHandler.handshakeFuture().addListener(future -> ch.pipeline().remove(SSL_HANDLER));
			}
		});
	
	ServerBootstrap serverBootstrap = new ServerBootstrap()
		.group(executors)
		.channel(NioServerSocketChannel.class)
		.handler(new ChannelInitializer<Channel>() {
			@Override
			protected void initChannel (Channel ch) throws Exception {
					SelfSignedCertificate ssc = new SelfSignedCertificate();
					SslContext build = SslContextBuilder.forServer(ssc.certificate(), ssc.privateKey()).build();
					final SslHandler sslHandler = build.newHandler(ch.alloc());
					ch.pipeline().addFirst(SSL_HANDLER, sslHandler);
					sslHandler.handshakeFuture().addListener(future -> ch.pipeline().remove(SSL_HANDLER));
			}
		});
	
	ChannelFuture bind = serverBootstrap.bind(HOST, PORT);
	bind.addListener(future -> bootstrap.connect(HOST, PORT));
}

```

**Comment by normanmaurer** [comment]
@Underbalanced awesome... will have a look later today.

**Comment by Underbalanced** [comment]
@normanmaurer

 I edited. Just added this...

•The exception is still thrown when I add  sslHandler.close();  before  ch.pipeline().remove(SSL_HANDLER);  in the Handshake Future Listener

•A better question might be what is the proper way to upon SSL handshake completion breakdown the SSL and remove the handlers and ensure the channels are ready for communications again?

**Comment by normanmaurer** [comment]
@Underbalanced this was a bug fixed by https://github.com/netty/netty/pull/5880. That said I am not sure why you would remove the SslHandler after the handshake.

**Comment by Underbalanced** [comment]
@normanmaurer I was watching you fix and discuss this and I reviewed the bug on source code. I use the handshake with client authentication required as a way for my company proxies to connect to each other. The main connection stays encrypted (administrative connection), but the other bulk data like file sending and specific messages go over a second non encrypted connection. Initially it starts out encrypted as my way of authenticating the connection, each proxy has its own private key the SSL is broken down once the connection is good for those bulk data I do not need secured. I was designing a inner connected Proxy system to help mitigate DDOS/DOS and thus proxies talk to each other and replicate resources for the Massively Multiplayer game.

**Comment by unoexperto** [comment]
Guys, could you please suggest if there connection between this change and https://github.com/AsyncHttpClient/async-http-client/issues/1645 ?
