### ISSUE TITLE
Using DefaultEventExecutorGroup leads to high CPU usage & low throughput in Netty 4.1.5

### ISSUE THREAD

**Issue by spshukla** [netty/netty#5881]
I am using `Netty 4.1.5.Final` and observed the following issue while using **DefaultEventExecutorGroup**.

The threads spawned from this event executor group is eating up all CPU. I took the thread dump of application and verified the thread count is same as defined as constructor param in **DefaultEventExecutorGroup**.

**Observation:-**
If I assign more threads (greater than CPU cores) to DefaultEventExecutorGroup, average load of system is increasing. The average remains low when I keep this value to number of CPU cores. Any specific reason for the same?

I am performing benchmarking for an application using **ab**. Please find the stats for following request per seconds (rps). The throughput achieved is around 40 requests processed per second.

**60 rps -** CPU Usage(80%); Load average = 1-1.5
**100 rps -** CPU Usage(80-90%); Load average = 1.8-2

Attached the channel handlers group in Channel Pipeline like this (Code Snippet)
```
private DefaultEventExecutorGroup eventExecutorGroup = new DefaultEventExecutorGroup(20, new DefaultThreadFactory("eventExecutorGroup"));

protected void initChannel(SocketChannel ch) throws Exception {
        ChannelPipeline p = ch.pipeline();
        p.addLast(new HttpServerCodec(4096, 8192, 8192, false));
        p.addLast("decompressor", new HttpContentDecompressor());
        p.addLast("aggregator", new HttpObjectAggregator(512 * 1024));
        p.addLast(eventExecutorGroup, baseNettyServerHandler);
        p.addLast(new HttpContentCompressor());
    }
```
Please find the server bootstrapping code

```
private void bootstrapServer(ChannelInitializer<SocketChannel> channelInitializer, int port) throws Exception {
        EventLoopGroup bossGroup = new NioEventLoopGroup();
        EventLoopGroup workerGroup = new NioEventLoopGroup();
        try {
            ServerBootstrap b = new ServerBootstrap();
            b.group(bossGroup, workerGroup).channel(NioServerSocketChannel.class).childHandler(channelInitializer);
            //b.option(ChannelOption.SO_BACKLOG, 128);
            b.childOption(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT);
            b.childOption(ChannelOption.SO_KEEPALIVE, true).childOption(ChannelOption.TCP_NODELAY, true);
            b.childOption(ChannelOption.WRITE_BUFFER_HIGH_WATER_MARK, 32 * 1024);
            b.childOption(ChannelOption.WRITE_BUFFER_LOW_WATER_MARK, 8 * 1024);
            Channel ch = b.bind(port).sync().channel();
            ch.closeFuture().sync();
        } catch (Exception e) {
            throw e;
        } finally {
            bossGroup.shutdownGracefully();
            workerGroup.shutdownGracefully();
        }
    }
```
As per the https://github.com/netty/netty/issues/473 comments, I couldn't find any solution for this issue.This is the reason I upgraded to this version to resolve the issue. Please help me with this.

**OS Version:-**
Linux N2MCITL-ALA016 2.6.32-573.el6.x86_64 #1 SMP Wed Jul 1 18:23:37 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Java Version:-**
openjdk version "1.8.0_101"
OpenJDK Runtime Environment (build 1.8.0_101-b13)
OpenJDK 64-Bit Server VM (build 25.101-b13, mixed mode)

**Comment by spshukla** [comment]
Please find the thread dump for few threads

```
"nioEventLoopGroup-4-1" #26 prio=10 os_prio=0 tid=0x00007f394c008000 nid=0x52ea runnable [0x00007f399fdfd000]
   java.lang.Thread.State: RUNNABLE
        at java.util.zip.ZipFile.getEntryTime(Native Method)
        at java.util.zip.ZipFile.getZipEntry(ZipFile.java:569)
        at java.util.zip.ZipFile.access$900(ZipFile.java:60)
        at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:524)
        - locked <0x000000076ac40480> (a java.util.jar.JarFile)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:499)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:480)
        at java.util.jar.JarFile$JarEntryIterator.next(JarFile.java:257)
        at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:266)
        at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:247)
        at com.google.common.reflect.ClassPath$DefaultScanner.scanJarFile(ClassPath.java:429)
        at com.google.common.reflect.ClassPath$Scanner.scanJar(ClassPath.java:339)
        at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:323)
        at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:312)
        at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:299)
        at com.google.common.reflect.ClassPath.from(ClassPath.java:91)
        at com.lex.platform.core.netty.handler.NettyServerHandler.lookupRequestUrlHandler(NettyServerHandler.java:222)
        at com.lex.platform.core.netty.handler.NettyServerHandler.handleRequest(NettyServerHandler.java:99)
        at com.lex.platform.core.netty.handler.BaseNettyServerHandler.channelRead(BaseNettyServerHandler.java:88)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)


"nioEventLoopGroup-3-1" #18 prio=10 os_prio=0 tid=0x00007f39bcabc800 nid=0x52e8 runnable [0x00007f39a416e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x00000006c00b6b90> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x00000006c00b6bb0> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000006c00b6b48> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)


"nioEventLoopGroup-4-5" #30 prio=10 os_prio=0 tid=0x00007f394c00e800 nid=0x52ee runnable [0x00007f399f9f9000]
   java.lang.Thread.State: RUNNABLE
        at java.util.zip.ZipFile.freeEntry(Native Method)
        at java.util.zip.ZipFile.access$1000(ZipFile.java:60)
        at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:525)
        - locked <0x00000007b57a0040> (a java.util.jar.JarFile)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:499)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:480)
        at java.util.jar.JarFile$JarEntryIterator.next(JarFile.java:257)
        at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:266)
        at java.util.jar.JarFile$JarEntryIterator.nextElement(JarFile.java:247)
        at com.google.common.reflect.ClassPath$DefaultScanner.scanJarFile(ClassPath.java:429)
        at com.google.common.reflect.ClassPath$Scanner.scanJar(ClassPath.java:339)
        at com.google.common.reflect.ClassPath$Scanner.scanFrom(ClassPath.java:323)
        at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:312)
        at com.google.common.reflect.ClassPath$Scanner.scan(ClassPath.java:299)
        at com.google.common.reflect.ClassPath.from(ClassPath.java:91)
        at com.lex.platform.core.netty.handler.NettyServerHandler.lookupRequestUrlHandler(NettyServerHandler.java:222)
        at com.lex.platform.core.netty.handler.NettyServerHandler.handleRequest(NettyServerHandler.java:99)
        at com.lex.platform.core.netty.handler.BaseNettyServerHandler.channelRead(BaseNettyServerHandler.java:88)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
```

**Comment by spshukla** [comment]
<img width="762" alt="screenshot 2016-09-29 17 40 27" src="https://cloud.githubusercontent.com/assets/5301451/18953411/fe797254-866b-11e6-8141-b97908a0b333.png">

The graph for 100 concurrent requests.

**Comment by normanmaurer** [comment]
@spshukla attach a profiler to understand which thread ties up resources and what it does.

**Comment by spshukla** [comment]
@normanmaurer  Please find the details

<img width="1139" alt="screenshot 2016-09-29 18 18 32" src="https://cloud.githubusercontent.com/assets/5301451/18954680/b00b4bf0-8671-11e6-9063-710b51f98c2c.png">
<img width="1117" alt="screenshot 2016-09-29 18 19 23" src="https://cloud.githubusercontent.com/assets/5301451/18954684/b1ad645c-8671-11e6-8a8b-a87e5a981114.png">

https://github.com/spshukla/codedev/blob/master/CPU%20profiler.html

**Comment by normanmaurer** [comment]
@spshukla as the screenshot shows all the threads related to the `EventExecutorGroup` are super busy. Check with a profiler why these are busy. I guess its the code you run in your handler that you use and have the EventExecutorGroup bound to. Nothing we can do here...

**Comment by spshukla** [comment]
Sure @normanmaurer I will have a look at that part.

Could you please verify once that I am correctly configuring the channel pipeline & else? (Code snippet attached above)

Is there any threshold count (recommended) for `EventExecutorGroup` threads like the number of CPU cores or could I assign as per the nature of application?

**Comment by normanmaurer** [comment]
@spshukla init looks good. No the number of threads you should use depends on what you do.

**Comment by spshukla** [comment]
Thanks @normanmaurer for pinpointing the probable cause. I was able to resolve the issue and now I am able to serve 450+ requests per second.

**Comment by mrtechit** [comment]
Hi,

How did you resolve this ?

My eventloopgroup keeps on increasing on each and every request to NioServerSocketChannel
