### ISSUE TITLE
Server stops working after the exceptionCaught being called

### ISSUE THREAD

**Issue by MagicDroidX** [netty/netty#5893]
```
Network dropped connection on reset: no further information
at sun.nio.ch.DatagramChannelImpl.receive0(Native Method)
at sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(Unknown Source)
at sun.nio.ch.DatagramChannelImpl.receive(Unknown Source)
at sun.nio.ch.DatagramChannelImpl.receive(Unknown Source)
at io.netty.channel.socket.nio.NioDatagramChannel.doReadMessages(NioDatagramChannel.java:240)
at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:75)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
at java.lang.Thread.run(Unknown Source)
```
Using netty 4.
Protocol: UDP
Override the `exceptionCaught()` to print the stack trace.
Since then the server stops working.
What should I do to recover the server?

**Comment by normanmaurer** [comment]
What version of Netty exactly? Also is this an IOException?

**Comment by MagicDroidX** [comment]
I am using Netty 4.1.4.Final and it is a java.net.SocketException

**Comment by normanmaurer** [comment]
@MagicDroidX are you sure you not call `Channel.close()` in some handler ?

**Comment by MagicDroidX** [comment]
Yes, and it happens randomly. But whenever the exception was thrown, the server will stop working.

**Comment by MagicDroidX** [comment]
just a SocketException.

**Comment by normanmaurer** [comment]
@MagicDroidX ok thanks... let me look into it.

**Comment by normanmaurer** [comment]
@MagicDroidX PTAL https://github.com/netty/netty/pull/5899

**Comment by MagicDroidX** [comment]
Okay thanks. :)

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/5899
