### ISSUE TITLE
when sending a long HTTP Request, I get a TooLongFrameException, but would expect an HTTP code 413/414

### ISSUE THREAD

**Issue by Anke-L** [netty/netty#5922]
Vertx Core: 3.3.2
Netty: 4.1.3 Final

Context:
I'm sending a long HTTP request (e.g. GET or DELETE) using Vertx/Netty. 
Before the request can be handled by the server I get an exception from Netty (see below).

When looking into the code I see a comment in HttpObjectDecoder.HeaderParser.process():
"TODO: Response with Bad Request....“
Is there a chance, that this ToDo will be implemented in the near future and an HTTP 413 or 414 will be returned?

Exception:
```
17:46:05.836 [vert.x-eventloop-thread-0] ERROR io.vertx.core.logging.JULLogDelegate 167 log - io.netty.handler.codec.TooLongFrameException: An HTTP line is larger than 4096 bytes.
17:46:05.848 [vert.x-eventloop-thread-0] INFO  org.apache.kafka.clients.producer.KafkaProducer 613 close - Closing the Kafka producer with timeoutMillis = 9223372036854775807 ms.
17:46:05.847 [globalEventExecutor-1-3] ERROR io.netty.util.internal.logging.Slf4JLogger 181 error - Failed to submit a listener notification task. Event loop shut down? java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:840) ~[netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:342) ~[netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:335) ~[netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765) ~[netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:120) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87) [netty-transport-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1022) [netty-transport-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:620) [netty-transport-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:475) [netty-transport-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964) [netty-transport-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234) [netty-transport-4.1.3.Final.jar:4.1.3.Final]
	at io.vertx.core.dns.impl.fix.DnsNameResolver.close(DnsNameResolver.java:281) [vertx-core-3.3.2.jar:?]
	at io.vertx.core.impl.AddressResolver$1$1.close(AddressResolver.java:148) [vertx-core-3.3.2.jar:?]
	at io.netty.resolver.AddressResolverGroup$1.operationComplete(AddressResolverGroup.java:79) [netty-resolver-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:438) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:233) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-common-4.1.3.Final.jar:4.1.3.Final]
	at java.lang.Thread.run(Thread.java:785) [?:1.8.0]

```

**Comment by rkapsi** [comment]
Not sure Netty should return a response on its own. You maybe want to return a fancy error page such as Github does for example (e.g. http://github.com/404).

Write a ChannelHandler that handles the TooLongFrameException and have it return a HTTP error of your liking.

**Comment by Scottmitch** [comment]
We could make this more directly overridable ... but I agree with @rkapsi can you just override a `exceptionCaught` from a handler in your pipeline and handle the `TooLongFrameException` for your needs?

**Comment by Anke-L** [comment]
Thanks for your answers @Scottmitch and @rkapsi .

I will give your suggestions a try.

**Comment by Scottmitch** [comment]
@Anke-L - sounds good. I will close this issue for now. Feel free to re-open if things do not work as expected.
