### ISSUE TITLE
Don't log the exception object while FD is full

### ISSUE THREAD

**Issue by Hanson1129** [netty/netty#5962]
check this stack

``` java
Exception in thread "HSF-Boss-15-thread-1" java.lang.NoClassDefFoundError: ch/qos/logback/core/pattern/SpacePadder
        at ch.qos.logback.core.pattern.FormattingConverter.write(FormattingConverter.java:66)
        at ch.qos.logback.core.pattern.PatternLayoutBase.writeLoopOnConverters(PatternLayoutBase.java:119)
        at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:168)
        at ch.qos.logback.classic.PatternLayout.doLayout(PatternLayout.java:59)
        at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:134)
        at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:188)
        at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:103)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:88)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:48)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:272)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:259)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:441)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:395)
        at ch.qos.logback.classic.Logger.warn(Logger.java:712)
        at io.netty.util.internal.logging.Slf4JLogger.warn(Slf4JLogger.java:151)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:115)

```

while vm 's fd is full, if you try to log the object of throwable,the JVM may try to do some class loading.Because of fxxking "too many open files", my JVM she cannot load any class then.

see this:

![image](https://cloud.githubusercontent.com/assets/4310631/19845965/d3ddc5bc-9f76-11e6-9d24-2653fa6e0465.png)

So my boss worker is down... 

Can we judge the throwable is some "Too many open files" exception or not ,to decide if we should log or not the object.

```

**Comment by Hanson1129** [comment]
``` java

java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~[na:1.6.0_32]
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:152) ~[na:1.6.0_32]
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:135) ~[netty-all-4.0.35.Final.jar!/:na]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:69) ~[netty-all-4.0.35.Final.jar!/:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-all-4.0.35.Final.jar!/:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-all-4.0.35.Final.jar!/:na]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-all-4.0.35.Final.jar!/:na]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-all-4.0.35.Final.jar!/:na]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-all-4.0.35.Final.jar!/:na]
        at com.taobao.hsf.remoting.netty.common.RemotingThreadFactory$PooledByteBufRunnable.run(RemotingThreadFactory.java:34) [hsf.remoting.netty-2.1.1.6.3-mtop.jar!/:na]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_32]

```

**Comment by normanmaurer** [comment]
@Hanson1129 I think there is not much we can do here as first of the message may be localized and also the user may use a logger which not use a file at all and so want to log in all cases.
