### ISSUE TITLE
Kernel Panic on Raspberry Pi 3

### ISSUE THREAD

**Issue by tomjmul** [netty/netty#5964]
Running Logstash in a docker container (as a swarm service) on a Raspberry Pi 3 and seeing a stacktrace in the logs, which seems to correlate with a kernel panic that takes the whole node down

```
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:313)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)
```

Kernel logs:

```
ct 31 15:20:26 swarm-pi01 kernel: [ 1417.489807] Hardware name: BCM2709
Oct 31 15:20:26 swarm-pi01 kernel: [ 1417.554045] [<800193e4>] (unwind_backtrace) from [<800149e0>] (show_stack+0x20/0x24)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1417.614318] [<800149e0>] (show_stack) from [<8033575c>] (dump_stack+0xbc/0x108)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1417.673780] [<8033575c>] (dump_stack) from [<80350024>] (check_preemption_disabled+0x104/0x134)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1417.745752] [<80350024>] (check_preemption_disabled) from [<8035006c>] (debug_smp_processor_id+0x18/0x24)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1417.819982] [<8035006c>] (debug_smp_processor_id) from [<7f1ab50c>] (ip_vs_schedule+0x180/0x738 [ip_vs])
Oct 31 15:20:26 swarm-pi01 kernel: [ 1417.891925] [<7f1ab50c>] (ip_vs_schedule [ip_vs]) from [<7f1b9590>] (tcp_conn_schedule+0x118/0x22c [ip_vs])
Oct 31 15:20:26 swarm-pi01 kernel: [ 1417.958147] [<7f1b9590>] (tcp_conn_schedule [ip_vs]) from [<7f1acf78>] (ip_vs_in.part.2.constprop.9+0x6e4/0x75c [ip_vs])
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.025265] [<7f1acf78>] (ip_vs_in.part.2.constprop.9 [ip_vs]) from [<7f1ad074>] (ip_vs_local_request4+0x40/0x44 [ip_vs])
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.102047] [<7f1ad074>] (ip_vs_local_request4 [ip_vs]) from [<8050c474>] (nf_iterate+0x80/0x90)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.181007] [<8050c474>] (nf_iterate) from [<8050c504>] (nf_hook_slow+0x80/0xec)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.259014] [<8050c504>] (nf_hook_slow) from [<80518d2c>] (__ip_local_out+0xac/0xb8)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.331194] [<80518d2c>] (__ip_local_out) from [<80518d5c>] (ip_local_out+0x24/0x4c)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.409402] [<80518d5c>] (ip_local_out) from [<80519084>] (ip_queue_xmit+0x144/0x3c0)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.488301] [<80519084>] (ip_queue_xmit) from [<80531424>] (tcp_transmit_skb+0x4d0/0x918)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.567141] [<80531424>] (tcp_transmit_skb) from [<80533014>] (tcp_connect+0x584/0x798)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.646048] [<80533014>] (tcp_connect) from [<80536170>] (tcp_v4_connect+0x2fc/0x468)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.714525] [<80536170>] (tcp_v4_connect) from [<7f02e230>] (tcp_v6_connect+0x530/0x598 [ipv6])
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.784969] [<7f02e230>] (tcp_v6_connect [ipv6]) from [<8054dfd8>] (__inet_stream_connect+0x1a4/0x330)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.866581] [<8054dfd8>] (__inet_stream_connect) from [<8054e1a8>] (inet_stream_connect+0x44/0x58)
Oct 31 15:20:26 swarm-pi01 kernel: [ 1418.948642] [<8054e1a8>] (inet_stream_connect) from [<804bc8c4>] (SyS_connect+0x74/0xa4)
```

**Comment by normanmaurer** [comment]
Sorry but this has nothing todo with netty. You will need to investigate on the Raspberry side.
