### ISSUE TITLE
Epoll channel configs throw UnsatisfiedLinkError in getOptions()

### ISSUE THREAD

**Issue by meshcow** [netty/netty#5969]
Netty version: `5.0.0.Alpha2`, maven artifact: `netty-all`

Operating system: Debian Linux 64-bit
```
$ uname -a
Linux wwwntdeb 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux
$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```
Boss channel (due to `SO_REUSEADDR` gets queried)
```
java.lang.UnsatisfiedLinkError: io.netty.channel.epoll.Native.isReuseAddress(I)I
        at io.netty.channel.epoll.Native.isReuseAddress(Native Method)
        at io.netty.channel.epoll.EpollServerChannelConfig.isReuseAddress(EpollServerChannelConfig.java:77)
        at io.netty.channel.epoll.EpollServerChannelConfig.getOption(EpollServerChannelConfig.java:51)
        at io.netty.channel.epoll.EpollServerSocketChannelConfig.getOption(EpollServerSocketChannelConfig.java:49)
        at io.netty.channel.DefaultChannelConfig.getOptions(DefaultChannelConfig.java:96)
        at io.netty.channel.epoll.EpollServerChannelConfig.getOptions(EpollServerChannelConfig.java:41)
        at io.netty.channel.epoll.EpollServerSocketChannelConfig.getOptions(EpollServerSocketChannelConfig.java:40)
```
Worker channel (due to `SO_KEEPALIVE` gets queried)
```
java.lang.UnsatisfiedLinkError: io.netty.channel.epoll.Native.isKeepAlive(I)I
	at io.netty.channel.epoll.Native.isKeepAlive(Native Method)
	at io.netty.channel.epoll.EpollSocketChannelConfig.isKeepAlive(EpollSocketChannelConfig.java:154)
	at io.netty.channel.epoll.EpollSocketChannelConfig.getOption(EpollSocketChannelConfig.java:68)
	at io.netty.channel.DefaultChannelConfig.getOptions(DefaultChannelConfig.java:96)
	at io.netty.channel.epoll.EpollSocketChannelConfig.getOptions(EpollSocketChannelConfig.java:48)
```

**Comment by normanmaurer** [comment]
@meshcow this is a very old version... Please use the latest 4.0 or 4.1 version
