### ISSUE TITLE
Clash With Android RecycleView

### ISSUE THREAD

**Issue by 925941723** [netty/netty#5989]
The code in gradle is:   
    compile files('libs/netty-all-4.1.6.Final.jar')
    compile 'com.android.support:recyclerview-v7:24.2.0'
And the error is:
 FATAL EXCEPTION: Thread-214
 java.lang.ExceptionInInitializerError at   com.qiaoqiao.qaoqaoapplication.socket.QAOLoginClient.connect(QAOLoginClient.java:49)
      at com.qiaoqiao.qaoqaoapplication.ui.activity.LoginActivity$2.run(LoginActivity.java:106)
Caused by: java.lang.NoClassDefFoundError: io.netty.util.internal.logging.InternalLoggerFactory
      at io.netty.channel.MultithreadEventLoopGroup.<clinit>(MultithreadEventLoopGroup.java:34)
       at com.qiaoqiao.qaoqaoapplication.socket.QAOLoginClient.connect(QAOLoginClient.java:49) 
      at com.qiaoqiao.qaoqaoapplication.ui.activity.LoginActivity$2.run(LoginActivity.java:106) 
I have to use RecycleView,but I have no idea how to resolve it.

**Comment by normanmaurer** [comment]
@925941723 this is more an android question (in terms how to setup the build). Be sure to include the classes in the netty-common jar in the classpath and all should be good.

**Comment by 925941723** [comment]
I want to say that before I compile 'com.android.support:recyclerview-v7:24.2.0' all is good. And is netty-all jar is not enough?  Should I compile other netty jar?
