### ISSUE TITLE
Netty3 masks OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by henrikno** [netty/netty#6005]
Netty version: 3.10.6.Final

We're running Elasticsearch 2.4.1, which uses netty, and get the following exception:

```
[2016-10-12 02:47:54,770][WARN ][netty.channel.socket.nio.AbstractNioSelector] Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: Direct buffer memory
    at java.nio.Bits.reserveMemory(Bits.java:658)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
    at org.elasticsearch.common.netty.channel.socket.nio.SocketReceiveBufferAllocator.newBuffer(SocketReceiveBufferAllocator.java:64)
    at org.elasticsearch.common.netty.channel.socket.nio.SocketReceiveBufferAllocator.get(SocketReceiveBufferAllocator.java:41)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:62)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

We're not setting any limits on direct memory size, so it probably happens because the machine is low on OS memory. However, netty catches this exception, and continues like everything is normal, but Elasticsearch is in a weird state.

We'd expect netty to bubble errors up when cricital memory failures happen, so that we can handle it.

**Comment by Scottmitch** [comment]
Netty 3.x has been EOL for a while now [1]. Please try to update to Netty 4 and we will be able to provide support.

[1] http://netty.io/news/2016/06/29/3-10-6-Final.html

**Comment by jasontedor** [comment]
This should not have been closed, Netty 4 does the same thing. I opened #6096 to re-raise the broader issue that I've raised before of catching and swallowing throwable.

**Comment by Scottmitch** [comment]
> This should not have been closed,

Netty 3 is EOL, we no longer support Netty 3, and this is why the issue was closed.

Lets continue discussion on #6096 for 4.x.
