### ISSUE TITLE
when I received an unknown or have closed the TCP service, will collapse.

### ISSUE THREAD

**Issue by TitleChen** [netty/netty#6017]
I use in the android netty implements a client, when I received an unknown or have closed the TCP service, will collapse.

**Comment by normanmaurer** [comment]
Not sure what issue you have... can you give more details?

**Comment by TitleChen** [comment]
OK.thank you:
EventLoopGroup workerGroup = new NioEventLoopGroup();
                    try {
                        Bootstrap b = new Bootstrap(); // (1)
                        b.group(workerGroup); // (2)
                        b.channel(NioSocketChannel.class); // (3)
                        b.handler(new LoggingHandler(LogLevel.DEBUG));
                        b.option(ChannelOption.SO_KEEPALIVE, true); // (4)
                        b.option(ChannelOption.TCP_NODELAY, true);
                        b.handler(new ChannelInitializer<SocketChannel>() {
                            @Override
                            public void initChannel(SocketChannel ch) throws Exception {
                                ch.pipeline().addLast(new IdleStateHandler(60, 60, 60));
                                ch.pipeline().addLast(new AppDelimiterBasedFrameDecoder(10240, false, Unpooled.copiedBuffer(new byte[]{(byte) 0x61, (byte) 0x76})));
                                ch.pipeline().addLast(new MessageNettyDecoder());
                                ch.pipeline().addLast(new MessageNettyEncoder());
                                ch.pipeline().addLast(new ProcessNettyInHandler(getInstance().context));
				ch.pipeline().addLast(new ProcessNettyOutHandler(getInstance().context)); 
                            }
                        });

                        // Start the client.
                        ChannelFuture f = b.connect(address).sync(); // (5)

                        // Wait until the connection is closed.
                        f.channel().closeFuture().sync();
                    } catch (InterruptedException e) {
                        Log.e(TAG, "连接服务器异常", e);
                    } finally {
                        workerGroup.shutdownGracefully();
                    }
 this is create a netty client in new thread.


ProcessNettyOutHandler.java
@Override
	public void connect(ChannelHandlerContext ctx, SocketAddress remoteAddress, SocketAddress localAddress, ChannelPromise promise) {
		SyncClientNettyConnector.getInstance().setCtx(null);
		try{
			super.connect(ctx, remoteAddress, localAddress, promise);
		}catch (Exception ex){
			Log.i(TAG,"connection exception: ",ex);
		}
	}

when I received an unknown or have closed the TCP service, will collapse.

exception:
java.lang.Error: io.netty.channel.AbstractChannel$AnnotatedConnectException: failed to connect to dev.smart-ism.com/120.24.56.175 (port 7778): isConnected failed: ECONNREFUSED (Connection refused): dev.smart-ism.com/120.24.56.175:7778
                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                              at java.lang.Thread.run(Thread.java:831)
                                           Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: failed to connect to dev.smart-ism.com/120.24.56.175 (port 7778): isConnected failed: ECONNREFUSED (Connection refused): dev.smart-ism.com/120.24.56.175:7778
                                              at libcore.io.IoBridge.isConnected(IoBridge.java:238)
                                              at java.nio.SocketChannelImpl.finishConnect(SocketChannelImpl.java:277)
                                              at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:346)
                                              at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
                                              at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:639)
                                              at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:536)
                                              at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:490)
                                              at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
                                              at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
                                              at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)


When I on the server, and then turn off the phone network, there will echo exception, but the app does not collapse

where exception: ProcessNettyInHandler.java
@Override
	public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception {
		Log.e(TAG,"exception:",cause);
	}

**Comment by normanmaurer** [comment]
What you means with "collapse" ? The error you see here is that it basically can not connect to the remote host as it refused the connection attempt.

**Comment by TitleChen** [comment]
yes. but this exception throws in main/UI thread and app will exit. "collapse" is means “crash”。 thank you answer my question。

**Comment by normanmaurer** [comment]
@TitleChen this is because you call `sync()` which will throw the exception that you not catch. Call `get()` and catch the exceptions.

**Comment by TitleChen** [comment]
very good!!
 // Start the client.
                        b.connect(address).get(); 
//                        ChannelFuture f = b.connect(address).sync(); // (5)
                        // Wait until the connection is closed.
//                        f.channel().closeFuture().sync();

i changed to this is ok.
