### ISSUE TITLE
jvm crashed during io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.init

### ISSUE THREAD

**Issue by qdaxb** [netty/netty#6021]
Hi all,

Our service was randomly crashed after tomcat started, we found some information reference to netty in hs_err.log:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ff20fb82612, pid=9, tid=140666414700288
#
# JRE version: Java(TM) SE Runtime Environment (8.0_65-b17) (build 1.8.0_65-b17)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.65-b01 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# J 13598 C2 io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.init(Lio/netty/channel/AbstractChannelHandlerContext$AbstractWriteTask;Lio/netty/channel/AbstractChannelHandlerContext;Ljava/lang/Object;Lio/netty/channel/ChannelPromise;)V (90 bytes) @ 0x00007ff20fb82612 [0x00007ff20fb82540+0xd2]
#
# Core dump written. Default location: /data1/bin/core or core.9
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

---------------  T H R E A D  ---------------

Current thread (0x00007ff000200000):  JavaThread "AsyncMsgHandler-ThreadPool-3-506" [_thread_in_Java, id=1553, stack(0x00007fef739e1000,0x00007fef73ae2000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x00000000000000b0

Registers:
RAX=0x000000065be96cc8, RBX=0x00000006a87ded80, RCX=0x00000000d8771deb, RDX=0x00000006a87deb70
RSP=0x00007fef73ae0440, RBP=0x000000065be96cc8, RSI=0x000000065be96cc8, RDI=0x000000065be96c80
R8 =0x0000000000000010, R9 =0x00000007c001ad80, R10=0x0000000000000080, R11=0x00000000d50fbdb0
R12=0x0000000000000000, R13=0x000000065be96c30, R14=0x00000007c00016d0, R15=0x00007ff000200000
RIP=0x00007ff20fb82612, EFLAGS=0x0000000000010202, CSGSFS=0x0000000000000033, ERR=0x0000000000000004
  TRAPNO=0x000000000000000e

Top of Stack: (sp=0x00007fef73ae0440)
0x00007fef73ae0440:   0000000000000000 00000006a6f67910
0x00007fef73ae0450:   00000006a801bab0 00000006a67a5aa0
0x00007fef73ae0460:   000000065be96b08 00007ff20000000e
0x00007fef73ae0470:   00000000582a8e3e 0000000000013342
0x00007fef73ae0480:   000000065be96cc8 00007ff20f5f87b0
0x00007fef73ae0490:   00000007c001ad80 00007ff200000001
0x00007fef73ae04a0:   000000065be96c80 00000006a87deb70
0x00007fef73ae04b0:   00000006c0e52180 0000000000000000
0x00007fef73ae04c0:   00000007c00016d0 000000065be96b08
0x00007fef73ae04d0:   00000000d519e235 00007ff20fb115ac
0x00007fef73ae04e0:   00000006a6f678d0 000000060000000b
0x00007fef73ae04f0:   00000006a6f678d0 00007ff100000022
0x00007fef73ae0500:   0000000000000000 0000000000000001
0x00007fef73ae0510:   0000000000000002 00000007c001ad80
0x00007fef73ae0520:   000000065be96c80 00000006a87de948
0x00007fef73ae0530:   00000000582a8e3e 0000000000013343
0x00007fef73ae0540:   00000000d519e235 00007ff20fa339b0
0x00007fef73ae0550:   0000000300000001 00000006c3b8c9b8
0x00007fef73ae0560:   00000001d519e232 00000006a87de948
0x00007fef73ae0570:   00000006d50fbd29 00000006c262e978
0x00007fef73ae0580:   000000065be96c80 000e5c39bde016c3
0x00007fef73ae0590:   00000007c001ad80 00000006a8cf11a8
0x00007fef73ae05a0:   00000006c1806150 00000006a8cf1190
0x00007fef73ae05b0:   00000158663ba27e 00000006a8db8de8
0x00007fef73ae05c0:   000000065be968d0 0000000100000006
0x00007fef73ae05d0:   000000065be96950 00000006a8799dc0
0x00007fef73ae05e0:   0000000000000003 0000000000000001
0x00007fef73ae05f0:   0000000000000001 000000065be96938
0x00007fef73ae0600:   0000000000000000 000000065be2bf38
0x00007fef73ae0610:   000000065be2b420 00007ff21e237000
0x00007fef73ae0620:   0000000000000009 00000006b37eaf98
0x00007fef73ae0630:   00000000d519e232 00007ff20fb40020

Instructions: (pc=0x00007ff20fb82612)
0x00007ff20fb825f2:   00 4b 8d 1c dc 4d 85 c9 0f 84 ef 00 00 00 45 8b
0x00007ff20fb82602:   41 08 49 ba 00 00 00 00 00 00 00 00 4f 8d 14 c2
0x00007ff20fb82612:   4d 8b 52 30 49 b8 28 80 5e c0 07 00 00 00 4d 3b
0x00007ff20fb82622:   d0 0f 85 c6 00 00 00 49 8b f1 44 8b 56 08 41 81

Register to memory mapping:

RAX=
[error occurred during error reporting (printing register info), id 0xb]

Stack: [0x00007fef739e1000,0x00007fef73ae2000],  sp=0x00007fef73ae0440,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
J 13598 C2 io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.init(Lio/netty/channel/AbstractChannelHandlerContext$AbstractWriteTask;Lio/netty/channel/AbstractChannelHandlerContext;Ljava/lang/Object;Lio/netty/channel/ChannelPromise;)V (90 bytes) @ 0x00007ff20fb82612 [0x00007ff20fb82540+0xd2]
J 12174 C2 io.netty.channel.AbstractChannelHandlerContext.write(Ljava/lang/Object;ZLio/netty/channel/ChannelPromise;)V (82 bytes) @ 0x00007ff20f5f87b0 [0x00007ff20f5f85c0+0x1f0]
J 13592 C1 io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(Ljava/lang/Object;Lio/netty/channel/ChannelPromise;)Lio/netty/channel/ChannelFuture; (39 bytes) @ 0x00007ff20fb115ac [0x00007ff20fb11120+0x48c]
```

and some log by log4j:

```
java.lang.NullPointerException
        at io.netty.channel.DefaultMessageSizeEstimator$HandleImpl.size(DefaultMessageSizeEstimator.java:36) ~[netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.init(AbstractChannelHandlerContext.java:1044) ~[netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.newInstance(AbstractChannelHandlerContext.java:1117) ~[netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.access$1600(AbstractChannelHandlerContext.java:1105) ~[netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:824) ~[netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:798) ~[netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:834) ~[netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1017) ~[netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:256) ~[netty-all-4.0.41.Final.jar:4.0.41.Final]
```

The NPE is here:

```
DefaultMessageSizeEstimator.java:36
 @Override
        public int size(Object msg) {
            if (msg instanceof ByteBuf) {   <- NullPointerExecption
                return ((ByteBuf) msg).readableBytes();
            }
            if (msg instanceof ByteBufHolder) {
                return ((ByteBufHolder) msg).content().readableBytes();
            }
            if (msg instanceof FileRegion) {
                return 0;
            }
            return unknownSize;
        }
```
 I think there's may something wrong in RECYCLER, but I can't find the bug.

Our netty version is `netty-all-4.0.41.Final`

Any thoughts? Thanks.

**Comment by normanmaurer** [comment]
@qdaxb honestly I think this is an Java bug.  Your Java version is very old, so I would advice updating it and see if this still happens. Also it may be a good idea to upgrade netty as well, even if I not think this is related to netty at all.

**Comment by normanmaurer** [comment]
Let me close this and please re-open if you think there is anything wrong in netty
