### ISSUE TITLE
netty java.io.IOException: Connection reset by peer caused by RST,ACK

### ISSUE THREAD

**Issue by craigwu9** [netty/netty#6029]
We use haproxy to do load balance, and the netty server keep to rise "java.io.IOException: Connection reset by peer"
below is the exception stack:
`java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1055)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:245)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:112)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
        at java.lang.Thread.run(Thread.java:745)`
 
I use tcpdump to dump the network data of the netty server, and see below
 
![image](https://cloud.githubusercontent.com/assets/4964874/20335748/c6c3e2a6-ab8a-11e6-86e7-2749a74f6338.png)
10.125.137.11,10.125.137.13,10.125.137.14 are hapxory server ip
Seems haproxy just send [RST,ACK] to finish a health check. 

So, I am wondering if I have to handle this situation in my handler(like check exception is IOException, just ignore it, because the log is full of this exception) , or it should be handled by netty it self?

**Comment by Scottmitch** [comment]
If your peer sends a RST the TCP socket will be closed. You can ignore the exception at the application level but that doesn't change the kernel's behavior. Please identify why HAProxy is sending a RST and re-open this issue if you feel it can be attributed to a bug related to Netty.

**Comment by kiransunkari** [comment]
@craigw, iam also facing the same problem when I deployed in azure, how you solved the problem

**Comment by craigw** [comment]
@kirunsunkari I think you meant to tag @craigwu9 not me.

**Comment by kiransunkari** [comment]
@craigwu sry

**Comment by craigwu9** [comment]
@kiransunkari no good solution yet, just ignore it and log to a specific log file.

**Comment by MarsYoung** [comment]
how to ignore this log @kiransunkari

**Comment by fudaohui** [comment]
lvs tcp_check cause this question

**Comment by zipper01** [comment]
Still happen in 12.2.0. How to capture? I need to capture it and release session resource.

**Comment by cloudyunfan** [comment]
> Still happen in 4.1.58 --- it does not go through the pipeline. How to capture this? I need to capture it and release session resources.

I also want to know how to capture it

**Comment by fudaohui** [comment]
> > Still happen in 4.1.58 --- it does not go through the pipeline. How to capture this? I need to capture it and release session resources.
> 
> I also want to know how to capture it

Hope it works！

`      String message = cause.getMessage();
        try {
            if (!message.contains("Connection reset by peer")) {//tcp  rst
                log.error("do something");
                ctx.channel().close();
            }
        } catch (Exception e) {
               log.error("do something");
        }`

**Comment by nikolaosinlight** [comment]
This is exactly my issue as well.  HA Proxy appears to be returning a RST for health check and Netty is spewing these errors in the logs.  We are using a Netty module as part of Jooby 2 framework and updated to 4.1.72 Final and still have issues.

If the error is a non-issue that is great but it would be nice to be able to eliminate this from the logs (using logback) but I am not sure how exactly that can be accomplished as we don't really want to patch Jooby or Netty.  Any thoughts?
