### ISSUE TITLE
4.0.42: java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0

### ISSUE THREAD

**Issue by jesperpedersen** [netty/netty#6038]
In WildFly (a JavaEE server) I get the following during init using Netty 4.0.42
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
        at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:694)
        at io.netty.channel.nio.NioEventLoop$4.run(NioEventLoop.java:171)
        at java.security.AccessController.doPrivileged(Native Method) [rt.jar:1.8.0_91]
        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:167)
        at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
        at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:102)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:70)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:65)
        at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:56)
```

The jar contains
```
io/netty/util/internal/PlatformDependent0.class
io/netty/util/internal/PlatformDependent0$4.class
io/netty/util/internal/PlatformDependent0$5.class
io/netty/util/internal/PlatformDependent0$7.class
io/netty/util/internal/PlatformDependent0$6.class
io/netty/util/internal/PlatformDependent0$3.class
io/netty/util/internal/PlatformDependent.class
io/netty/util/internal/PlatformDependent0$8.class
io/netty/util/internal/PlatformDependent0$1.class
io/netty/util/internal/PlatformDependent$Mpsc.class
io/netty/util/internal/PlatformDependent$1.class
io/netty/util/internal/PlatformDependent$AtomicLongCounter.class
io/netty/util/internal/PlatformDependent$Mpsc$1.class
io/netty/util/internal/PlatformDependent0$2.class
```

Previous version (Netty 4.0.32) gave no NCDFE, but logged
```
INFO  [io.netty.util.internal.PlatformDependent] (management-handler-thread - 1) Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
```
during startup.

WildFly is using an isolated classloader environment based on JBoss Modules.

**Comment by jesperpedersen** [comment]
Netty 4.0.40 works

**Comment by Scottmitch** [comment]
what OS and JVM?

**Comment by jesperpedersen** [comment]
```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```
on Fedora 24

**Comment by Scottmitch** [comment]
Looks like we just need to be more careful about exceptions here.
