### ISSUE TITLE
SocketTest#testPeerCreds failure

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#6048]
https://garage.netty.io/teamcity/viewLog.html?buildId=13836&buildTypeId=pulls_netty&guest=1 while building PR https://github.com/netty/netty/pull/6044#pullrequestreview-9349114

```
[11:13:38][io.netty:netty-transport-native-epoll] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.002 sec <<< FAILURE! - in io.netty.channel.unix.SocketTest
[11:13:38][io.netty:netty-transport-native-epoll] testPeerCreds(io.netty.channel.unix.SocketTest)  Time elapsed: 0.002 sec  <<< ERROR!
[11:13:38][io.netty:netty-transport-native-epoll] io.netty.channel.unix.Errors$NativeIoException: bind() failed: Address already in use
[11:13:38][io.netty:netty-transport-native-epoll] 	at io.netty.channel.unix.SocketTest.testPeerCreds(SocketTest.java:110)
[11:13:38][io.netty:netty-transport-native-epoll] 
[11:13:38][io.netty:netty-transport-native-epoll] Running io.netty.channel.epoll.EpollSocketStartTlsTest
[11:13:39][io.netty:netty-transport-native-epoll] io.netty.channel.unix.SocketTest
[11:13:39][io.netty.channel.unix.SocketTest] testPeerCreds
[11:13:39][testPeerCreds] io.netty.channel.unix.Errors$NativeIoException: bind() failed: Address already in use
[11:13:39]
[testPeerCreds] io.netty.channel.unix.Errors$NativeIoException: bind() failed: Address already in use
	at io.netty.channel.unix.SocketTest.testPeerCreds(SocketTest.java:110)
```

**Comment by Scottmitch** [comment]
This should be fixed by https://github.com/netty/netty/pull/6000

**Comment by normanmaurer** [comment]
@Scottmitch why is this fixed by #6000 ?

**Comment by Scottmitch** [comment]
if a name collision occurs then we still may fail, however the existing test doesn't delete temp files and #6000 does ... this may make a collision less likely to occur. So "fixed" isn't the right word but it should help ... in addition to cleaning out temp directories on the build servers.

**Comment by normanmaurer** [comment]
I did not see this for a long time... let me close it
