### ISSUE TITLE
EPollArrayWrapper.epollWait 100% CPU load

### ISSUE THREAD

**Issue by AcceptedBoy** [netty/netty#6126]
### Description
I wrote a program to simulate data, which sent to our project using netty to receive, and then when the end of the transmission, CPU has remain 100% rather than decline.

### Actual behavior
a part of command `jstack`:
```java
"nioEventLoopGroup-5-5" prio=10 tid=0x00007f6f9800d800 nid=0x1600 runnable [0x00007f6f8bbfa000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x0000000093c04348> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000093c461e0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000093c042b0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"nioEventLoopGroup-5-4" prio=10 tid=0x00007f6f9800b800 nid=0x15ff runnable [0x00007f6f8bcfb000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x0000000093c46958> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000093c489d8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000093c468c0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"nioEventLoopGroup-5-3" prio=10 tid=0x00007f6f98009800 nid=0x15fe runnable [0x00007f6f8bdfc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x0000000093c49150> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000093c4b1d0> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000093c490b8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"nioEventLoopGroup-5-2" prio=10 tid=0x00007f6f98008000 nid=0x15fd runnable [0x00007f6f8befd000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x0000000093c4b948> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000093c85958> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000093c4b8b0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None

"nioEventLoopGroup-5-1" prio=10 tid=0x00007f6f98004800 nid=0x15fc runnable [0x00007f6f8bffe000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
	- locked <0x0000000093c860d0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000093c88150> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000093c86038> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
	- None
```

command `top` shows:
![2016-12-11 19-14-06](https://cloud.githubusercontent.com/assets/15062819/21079735/10fd7e7c-bfd6-11e6-9c80-444bd07cd69b.png)

the jvisualvm show:
![2016-12-11 19-12-13](https://cloud.githubusercontent.com/assets/15062819/21079726/d19da540-bfd5-11e6-94c5-8f8158f9cc91.png)

### Project code
netty config: 
```java
SslContext sslCtx = null;
		SelfSignedCertificate ssc = null;

		EventLoopGroup bossGroup = new NioEventLoopGroup(1);
		EventLoopGroup workerGroup = new NioEventLoopGroup();
		if (SSL) {
			try {
				ssc = new SelfSignedCertificate();
				sslCtx = SslContextBuilder.forServer(ssc.certificate(),
						ssc.privateKey()).build();
			} catch (CertificateException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (SSLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		} else {
			sslCtx = null;
		}

		try {
			ServerBootstrap b = new ServerBootstrap();
			initializer.setSslCtx(sslCtx);
			b.group(bossGroup, workerGroup)
					// NioDatagramChannel.class
					// NioServerSocketChannel
					.channel(NioServerSocketChannel.class)
					.handler(new LoggingHandler(LogLevel.INFO))
					.childHandler(initializer);
			ChannelFuture f = null;
			if (port != 0) {

				f = b.bind(port).sync();
				f.awaitUninterruptibly();
			}
			channel = f.channel();
			System.out.println("inside" + channel);
		} catch (InterruptedException e) {

			e.printStackTrace();
		}
```
receive the data:
```java
@Override
	public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {

		String rowMsg = (String) msg;
		logger.info("receivce data： " + rowMsg);
		char[] data = CharUtils.removeSpace(rowMsg.toCharArray());

		if (data.length == 190) {
			hitchEventDesc = "×××";
		}
		handleIdenCode(ctx, data); // to solve data
	}
```

### Netty version
```
4.0.29.Final
```
### JVM version
```
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
```
### OS version
```
Linux symon-ThinkPad-Edge-E545 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Thanks, and forgive my pool English.

**Comment by normanmaurer** [comment]
Can you share a full reproducer ?

**Comment by normanmaurer** [comment]
@AcceptedBoy like something I can run myself locally

**Comment by AcceptedBoy** [comment]
tht github:`https://github.com/AcceptedBoy/dongjun`.
And the step:
* in `dongjun-hardware`, run command `mvn spring-boot:run`: start project
* in `dongjun-simulate` run the java class  `com.gdut.symon.getMessageSource`: send data
* after some minutes, stop the java main class, and monitor the dongjun-hardware, which use netty to receive data.

**Comment by normanmaurer** [comment]
@AcceptedBoy what exact ubuntu Version you are using and also do you use openjdk or oracle JDK?

**Comment by AcceptedBoy** [comment]
@normanmaurer
ubuntu version:16.04
and Oracle jdk

**Comment by normanmaurer** [comment]
@AcceptedBoy ok cool... will try to reproduce

**Comment by AcceptedBoy** [comment]
@normanmaurer
thanks so much

**Comment by normanmaurer** [comment]
@AcceptedBoy can you also provide me with the tables for the database ?

**Comment by AcceptedBoy** [comment]
@normanmaurer I push SQL script file to the github, so please pull it. and I am sorry that it's the first step to run `mvn spring-boot:run` in module `dongjun-website` if you don't want to see the exception occur in module `dongjun-hardware`.

**Comment by normanmaurer** [comment]
@AcceptedBoy where did you put the sql script ? I don't see it :(

**Comment by AcceptedBoy** [comment]
@normanmaurer https://github.com/AcceptedBoy/dongjun.Its name is elecon.sql, and the database name is elecon.

**Comment by normanmaurer** [comment]
@AcceptedBoy I tried it now multiple times but I can not reproduce it... I did run the server and client via intellij. Anything else I need to do ?

**Comment by AcceptedBoy** [comment]
@normanmaurer . I reproduced it through steps:
* run website
* run hardware(server)
* run simulate(client)
and the problem occured.

**Comment by normanmaurer** [comment]
@AcceptedBoy this is not a netty bug...

What happens is that your program end up in an endless loop in:

```java
getSwitchAllInfo(...)
```

This is easily spottable using a profiler like yourkit and see where all the cycles are burned.
