### ISSUE TITLE
HTTP/2 client in examples fails for https://http2.akamai.com/demo/h2_demo_frame.html

### ISSUE THREAD

**Issue by rhatlapa** [netty/netty#6129]
When using HTTP/2 client example like this `./run-example.sh -Dport=443 -Dhost=http2.akamai.com -Dssl -Durl=/demo/h2_demo_frame.html -DlogLevel=debug http2-client` it fails with [1]. Note, curl --http2 works just fine and uses properly HTTP/2.0 for this site.

So the issue is that netty fails to initialize connection for HTTP/2 and fallbacks to defined protocol, any idea why it doesn't succeed using HTTP/2.0 ?

### Expected behavior
successful HTTP/2.0 response for https://http2.akamai.com/demo/h2_demo_frame.html when using http2-client example
### Actual behavior
fails with [1]

### Steps to reproduce
`./run-example.sh -Dport=443 -Dhost=http2.akamai.com -Dssl -Durl=/demo/h2_demo_frame.html -DlogLevel=debug http2-client`

### Netty version
4.1 branch, current latest commit => commit 4639d56

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-b16)
OpenJDK 64-Bit Server VM (build 25.111-b16, mixed mode)

### OS version (e.g. `uname -a`)
Fedora 24

[1]
```
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker$2
14:13:36.779 [nioEventLoopGroup-3-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x81dcfd6e, L:/10.40.4.184:44314 - R:http2.akamai.com/23.199.211.57:443] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
14:13:36.791 [nioEventLoopGroup-3-1] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalStateException: unknown protocol: 
	at io.netty.example.http2.helloworld.client.Http2ClientInitializer$1.configurePipeline(Http2ClientInitializer.java:110)
	at io.netty.handler.ssl.ApplicationProtocolNegotiationHandler.userEventTriggered(ApplicationProtocolNegotiationHandler.java:92)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:318)
	at io.netty.handler.ssl.SslHandler.setHandshakeSuccess(SslHandler.java:1240)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1083)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:950)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "main" java.lang.IllegalStateException: Timed out waiting for settings
	at io.netty.example.http2.helloworld.client.Http2SettingsHandler.awaitSettings(Http2SettingsHandler.java:49)
	at io.netty.example.http2.helloworld.client.Http2Client.main(Http2Client.java:107)
```

**Comment by normanmaurer** [comment]
@nmittler @Scottmitch PTAL

**Comment by Scottmitch** [comment]
The example [helloworld client](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/http2/helloworld/client) currently requires that the remote peer use ALPN to negotiate the HTTP/2 protocol. It looks like the web server at the above address not selecting the `h2` protocol which is [advertised by the helloworld client](https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/http2/helloworld/client/Http2Client.java#L82) (see https://tools.ietf.org/html/rfc7540#section-3.3). I have tried both OpenSSL and JDK SSL engines (via https://github.com/jetty-project/jetty-alpn-agent) and neither negotiated as expected. Let me look at the packet trace and see if the client is advertising support for ALPN correctly...

**Comment by rhatlapa** [comment]
I've tried to connect via curl [1] `curl -Iv --http2 https://http2.akamai.com/demo/h2_demo_frame.html` and I can see in the verbose output `ALPN, server accepted to use h2` also when trying okhttp client (its okcurl) and checking the transported packets via wireshark, I can see that ALPN is successfully negotiated.

When using netty and its example, I can see Client Hello packet requesting via ALPN to use h2, but the response Server Hello seems to be in different packet than Server Hello Done and I don't see there ALPN negotiation response from server.

As it works with different clients (curl and okhttp), the issue seems to be on netty side.

[1] curl --version
curl 7.47.1 (x86_64-redhat-linux-gnu) libcurl/7.47.1 NSS/3.27 zlib/1.2.8 libidn/1.33 libpsl/0.13.0 (+libidn/1.33) libssh2/1.7.0 nghttp2/1.7.1
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz HTTP2 UnixSockets Metalink PSL

**Comment by Scottmitch** [comment]
The ALPN extension in the Client Hello from Netty and from curl are identical. The issue is that the server requires the SNI extension to be enabled and the server name to be `http2.akamai.com`, or it will not negotiate ALPN. The Netty example does not configure SNI. See below for a quick and dirty hack to enable SNI for this specific case:

```diff
diff --git a/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java b/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java
index 182c156..4795674 100644
--- a/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java
+++ b/example/src/main/java/io/netty/example/http2/helloworld/client/Http2ClientInitializer.java
@@ -35,6 +35,13 @@ import io.netty.handler.codec.http2.InboundHttp2ToHttpAdapterBuilder;
 import io.netty.handler.ssl.ApplicationProtocolNames;
 import io.netty.handler.ssl.ApplicationProtocolNegotiationHandler;
 import io.netty.handler.ssl.SslContext;
+import io.netty.handler.ssl.SslHandler;
+
+import java.util.Arrays;
+import javax.net.ssl.SNIHostName;
+import javax.net.ssl.SNIServerName;
+import javax.net.ssl.SSLEngine;
+import javax.net.ssl.SSLParameters;
 
 import static io.netty.handler.logging.LogLevel.INFO;
 
@@ -94,7 +101,17 @@ public class Http2ClientInitializer extends ChannelInitializer<SocketChannel> {
      */
     private void configureSsl(SocketChannel ch) {
         ChannelPipeline pipeline = ch.pipeline();
-        pipeline.addLast(sslCtx.newHandler(ch.alloc()));
+        SslHandler handler = sslCtx.newHandler(ch.alloc());
+        try {
+            SSLEngine engine = handler.engine();
+            SSLParameters params = engine.getSSLParameters();
+            params.setServerNames(Arrays.asList(new SNIServerName[]{new SNIHostName("http2.akamai.com")}));
+            engine.setSSLParameters(params);
+        } finally {
+            // Always insert the SslHandler into the pipeline. This was if the SslHandler is ReferenceCounted the
+            // pipeline will take ReferenceCount ownership.
+            pipeline.addLast(handler);
+        }
         // We must wait for the handshake to finish and the protocol to be negotiated before configuring
         // the HTTP/2 components of the pipeline.
         pipeline.addLast(new ApplicationProtocolNegotiationHandler("") {
```


> Server Hello seems to be in different packet than Server Hello Done

Can you explain why this is significant? The ALPN selection must come in the Server Hello [1].

[1] https://tools.ietf.org/html/rfc7301
