### ISSUE TITLE
NioServerSocketChannelFactory.<init> is very slow in 3.5.7

### ISSUE THREAD

**Issue by deinlandel** [netty/netty#614]
Recently I have upgraded from Netty 3.5.5 to 3.5.7 and noticed that binding to a port became very slow.

I am using code like this

``` java
logger.debug("Port {} starting", port);
bootstrap = new ServerBootstrap(new NioServerSocketChannelFactory(
                Executors.newCachedThreadPool(), Executors.newFixedThreadPool(Settings.getDemuxPoolSize()),
                Settings.getDemuxPoolSize()));   
logger.debug("Port {} started", port);  
 ... continue inittialization of bootstrap ...
```

The delay between "Port {} starting" and "Port {} started" is about 5-8 seconds on my machine, which was not hte case with Netty 3.5.5

most of the thread dumps during binding to a port looked like this:

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
      at java.lang.String.length(String.java:651)
      at java.net.InetAddress.getAllByName(InetAddress.java:1026)
      at java.net.InetAddress.getAllByName(InetAddress.java:1020)
      at java.net.InetAddress.getByName(InetAddress.java:970)
      at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:67)
      at java.security.AccessController.doPrivileged(AccessController.java:-1)
      at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:122)
      at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:27)
      at java.nio.channels.Pipe.open(Pipe.java:133)
      at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:104)
      at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:26)
      at java.nio.channels.Selector.open(Selector.java:209)
      at org.jboss.netty.channel.socket.nio.AbstractNioWorker.openSelector(AbstractNioWorker.java:196)
      at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:127)
      at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:40)
      at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:34)
      at org.jboss.netty.channel.socket.nio.NioWorkerPool.createWorker(NioWorkerPool.java:26)
      at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.<init>(AbstractNioWorkerPool.java:56)
      at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:29)
      at org.jboss.netty.channel.socket.nio.NioServerSocketChannelFactory.<init>(NioServerSocketChannelFactory.java:131)
     <call from my code>(NettyPort.java:35)
```

So I guess the problem is in NioServerSocketChannelFactory.<init> method.

Tested on Windows 7, JDK 1.6.0u26

**Comment by oberlies** [comment]
> For Linux and Solaris portion of PipeImpl.java, it does not do such lookup, so I believe it affects only Windows.

Right, Windows doesn't support pipes, so they are implemented through a connection to the loopback device (see also this [wontfix JDK bug](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=6907260)).

I today also had the the problem that the PipeImpl constructor took several seconds on Windows, but an OS restart fixed the problem for me...
