### ISSUE TITLE
Potential endless loop in Recycler.Stack.scavengeSome

### ISSUE THREAD

**Issue by zsxwing** [netty/netty#6153]
### Expected behavior

Recycler.Stack.scavengeSome should never run forever.

### Actual behavior

Recycler.Stack.scavengeSome may not stop and it prevents the event loop from running other tasks.

### Steps to reproduce

I cannot reproduce it. But I found out a cycle linked list of `io.netty.util.Recycler.WeakOrderQueue` when I was investigating an issue that a netty client was hung forever.

![screen shot 2016-12-21 at 5 21 52 pm](https://cloud.githubusercontent.com/assets/1000778/21412114/8eca8fd8-c7a2-11e6-9e9a-b7dc62a3314b.png)

The stack trace of this thread is 

```
"shuffle-client-7-4" daemon prio=5 tid=97 RUNNABLE
        at io.netty.util.Recycler$Stack.scavengeSome(Recycler.java:504)
           Local Variable: io.netty.util.Recycler$WeakOrderQueue#111
           Local Variable: io.netty.util.Recycler$WeakOrderQueue#112
        at io.netty.util.Recycler$Stack.scavenge(Recycler.java:454)
        at io.netty.util.Recycler$Stack.pop(Recycler.java:435)
        at io.netty.util.Recycler.get(Recycler.java:144)
           Local Variable: io.netty.util.Recycler$Stack#26
           Local Variable: io.netty.buffer.PooledUnsafeDirectByteBuf$1#1
        at io.netty.buffer.PooledUnsafeDirectByteBuf.newInstance(PooledUnsafeDirectByteBuf.java:39)
        at io.netty.buffer.PoolArena$DirectArena.newByteBuf(PoolArena.java:727)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:140)
           Local Variable: io.netty.buffer.PoolArena$DirectArena#4
           Local Variable: io.netty.buffer.PoolThreadCache#7
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:271)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:177)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:168)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:129)
        at io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl.allocate(AdaptiveRecvByteBufAllocator.java:104)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
           Local Variable: io.netty.buffer.PooledByteBufAllocator#6
           Local Variable: io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig#10
           Local Variable: io.netty.channel.DefaultChannelPipeline#11
           Local Variable: io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl#10
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
           Local Variable: io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe#10
           Local Variable: io.netty.channel.socket.nio.NioSocketChannel#10
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
           Local Variable: java.nio.channels.SelectionKey[]#7
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
           Local Variable: io.netty.channel.nio.NioEventLoop#2
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
           Local Variable: io.netty.util.concurrent.SingleThreadEventExecutor$2#3
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)
```

### Minimal yet complete reproducer code (or URL to code)

N/A

### Netty version

4.0.42.Final

### JVM version (e.g. `java -version`)

N/A

### OS version (e.g. `uname -a`)

N/A

**Comment by rxin** [comment]
Note that this is found in Spark.

**Comment by normanmaurer** [comment]
Interesting.... never saw this :( will have a look

**Comment by rxin** [comment]
Thanks Norman.

**Comment by normanmaurer** [comment]
@zsxwing @rxin if you find anything else in the meantime that you can share which may help please let me know. Would it also be possible to get the heap-dump itself or does it contain sensitive data ?

**Comment by normanmaurer** [comment]
@zsxwing @rxin I tried to reproduce it via a test-case but so far no luck :( 

One question do you often create new threads which will die later ?

**Comment by zsxwing** [comment]
@normanmaurer Thanks for taking a look. Sorry that I'm not allowed to share the heap-dump as it's a production job.

We don't call NioEventLoop directly. Here are the codes creating the EventLoopGroup: https://github.com/apache/spark/blob/v2.1.0-rc5/common/network-common/src/main/java/org/apache/spark/network/client/TransportClientFactory.java#L104
and the codes set up the client: https://github.com/apache/spark/blob/v2.1.0-rc5/common/network-common/src/main/java/org/apache/spark/network/client/TransportClientFactory.java#L200

One notable thing is we use the same EventLoopGroup for multiple clients.

**Comment by normanmaurer** [comment]
@zsxwing but do you ofthen create new "TransportClientFactory" instances and destroy them ?

**Comment by zsxwing** [comment]
@normanmaurer We create several `TransportClientFactory`s for different modules but never destroy them until stopping the whole application.

**Comment by normanmaurer** [comment]
And you you allocate buffers only from within EventLoop threads or also from outside ?

**Comment by zsxwing** [comment]
> And you you allocate buffers only from within EventLoop threads or also from outside ?

Only within EventLoop thread. We also use Unpooled to allocate buffers outside. By the way, is it safe to release a ByteBuf outside the EventLoop thread? This may happen in our codes.

**Comment by normanmaurer** [comment]
Yes it is allowed... may these threads die frequently?

**Comment by zsxwing** [comment]
> Yes it is allowed... may these threads die frequently?

I don't think, unless Netty kills them internally.

**Comment by zsxwing** [comment]
Saw this issue again today. Since I only saw this after Spark upgraded Netty from 4.0.41.Final to 4.0.42.Final, it's likely because of some change between these two versions. Hope this is helpful.

**Comment by zsxwing** [comment]
> Saw this issue again today. Since I only saw this after Spark upgraded Netty from 4.0.41.Final to 4.0.42.Final, it's likely because of some change between these two versions. Hope this is helpful.

@normanmaurer NVM. I figured it out. Please take a look at #6180

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6180
