### ISSUE TITLE
EventLoopGroup.shutdownGracefully() may produce thread leak

### ISSUE THREAD

**Issue by hylddd** [netty/netty#6154]
### Expected behavior
All threads in EventLoopGroup closed.

### Actual behavior
Some threads still alive after `EventLoopGroup.shutdownGracefully()` returned.

Leak thread stack:
```
 "webSocketClient-346-1" prio=10 tid=0x00007f06801da000 nid=0xd529 runnable [0x00007f0671b00000]
    java.lang.Thread.State: RUNNABLE
         at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
         at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:210)
         at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:65)
         at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
         - locked <0x00000000f8884bc0> (a io.netty.channel.nio.SelectedSelectionKeySet)
         - locked <0x00000000f8884be0> (a java.util.Collections$UnmodifiableSet)
         - locked <0x00000000f8884b78> (a sun.nio.ch.EPollSelectorImpl)
         at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
         at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:622)
         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:310)
         at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
         at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) 
```

Something in stderr output:
```
java.io.IOException: Connection reset by peer 
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:251)
	at sun.nio.ch.IOUtil.read(IOUtil.java:218)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:254)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:242)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:110)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:701)
```

This `IOException` always happen together with one thread leak.

Netty Code:
```
EventLoopGroup group = new NioEventLoopGroup(POOL_SIZE, clientDefaultThreadFactory);

        final DefaultClientHandler handler = new DefaultClientHandler(
                WebSocketClientHandshakerFactory.newHandshaker(uri,
                        WebSocketVersion.V13,
                        null,
                        false,
                        new DefaultHttpHeaders()));

        Bootstrap b = new Bootstrap();
        b.group(group).channel(NioSocketChannel.class).option(ChannelOption.CONNECT_TIMEOUT_MILLIS, 5000).handler(new ChannelInitializer<SocketChannel>() {

            @Override
            protected void initChannel(SocketChannel ch) {
                ChannelPipeline p = ch.pipeline();
                p.addLast(new HttpClientCodec(),
                        new HttpObjectAggregator(
                                8192),
                        handler);
            }
        });

        final ChannelFuture channelFuture = b.connect(host, port);
        final boolean await = channelFuture.await(3, TimeUnit.SECONDS); // true
        if (!await) {
            throw new Exception("...");
        }

        Channel channel = channelFuture.channel();

        ChannelFuture closeFuture = channel.close();
        boolean await = closeFuture.await(3L, TimeUnit.SECONDS);    // true
        if (!await) {
            throw new Exception("...");
        }

        Future<?> future = group.shutdownGracefully();
        boolean await = future.await(20L, TimeUnit.SECONDS);    // true
        if (!await) {
            throw new Exception("...");
        }
```

I traced some code and found that `SingleThreadEventExecutor.state` of the leak thread was 2 (`ST_STARTED`), so it never came into shutdown process, what happened to this thread?

### Netty version
4.0.30.Final

### JVM version
java version "1.6.0_45"
Java(TM) SE Runtime Environment (build 1.6.0_45-b06)
Java HotSpot(TM) 64-Bit Server VM (build 20.45-b01, mixed mode)

### OS version
Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.32-1 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@hylddd sorry but your version of netty is super old. Please upgrade to 4.0.42.Final and let us know if the problem still exists.

**Comment by hylddd** [comment]
@normanmaurer I tried with Netty-4.0.42.Final, and the problem still exists.

**Comment by normanmaurer** [comment]
@hylddd did you actually make sure you called:

```java
EventLoopGroup.shutdownGracefully().sync();
```
? 

As this is an async operation.

**Comment by hylddd** [comment]
@normanmaurer I called `EventLoopGroup.shutdownGracefully().await(20L, TimeUnit.SECONDS)`, await returned `true` in about 2 seconds.

**Comment by Scottmitch** [comment]
@hylddd - Can you include a complete code reproducer? The above code is not sufficient to reproduce.

**Comment by normanmaurer** [comment]
@hylddd I will close this now as you did not come back to us. Please re-open with a reproducer when you sell think there is an issue
