### ISSUE TITLE
http2-reverse-proxy error when bench marking:Frame length: 393509 exceeds maximum: 16384

### ISSUE THREAD

**Issue by killjason** [netty/netty#6159]
### Expected behavior
http2-reverse-proxy works with no error
### Actual behavior
bench mark client(grpc-client) throws error as following:

> Encountered an error in unaryCall. Status is Status{code=INTERNAL, description=null, cause=io.netty.handler.codec.http2.Http2Exception: Frame length: 393509 exceeds maximum: 16384}
Encountered an error in unaryCall. Status is Status{code=INTERNAL, description=null, cause=io.netty.handler.codec.http2.Http2Exception: Frame length: 393509 exceeds maximum: 16384}
io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.Status.asRuntimeException(Status.java:545)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: io.netty.handler.codec.http2.Http2Exception: Frame length: 393509 exceeds maximum: 16384
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processHeaderState(DefaultHttp2FrameReader.java:182)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:143)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:335)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:395)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:574)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:488)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:744)
io.grpc.StatusRuntimeException: INTERNAL
	at io.grpc.Status.asRuntimeException(Status.java:545)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:395)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:481)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:398)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:513)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:902)
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1644)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

### Netty version
4.1.6.Final
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
centos-7-64

**Comment by Scottmitch** [comment]
@killjason - Please describe how you reproduce this error, and provide any additional code if necessary to repro. Assume we don't know how to run grpc-java code (this is not the grpc-java repo).

/cc @nmittler

**Comment by killjason** [comment]
http2-reverse-proxy is a proxy I wrote using netty based on http2 protocol for reverse proxy using. in my case, the scenario is : 
http2-client(grpc-java-client) make grpc request to http2-reverse-proxy, then http2-reverse-proxy pass the request to backend service which is based on grpc-service. There are two handlers being used: Http2FrontendHandler and TcpBackendHandler:

> Http2FrontendHandler extends Http2ConnectionHandler implements Http2FrameListener

> TcpBackendHandler extends ChannelInboundHandlerAdapter

the Http2FrontendHandler is in ServerBootStrap used for accept http2 request from client,
the TcpBackendHandler is in BootStrap which is used for connect to backend service.
when ServerBootStrap started, I triggered channel.read(the channel contains Http2FrontendHandler), then 
" io.netty.handler.codec.http2.Http2FrameListener.onHeadersRead(..)/onDataRead(..)"... methods are triggered. then I pass the http2 frame to BootStrap channel to backend service.
when TcpBackendHandler read response(Byte) from backend service, it simply write the Byte to ServerBootStrap`s channel connected with client.

the errors above is captured in client side.
grpc-java version is 1.0.2

**Comment by killjason** [comment]
the related issue is also in grpc-java repo:
https://github.com/grpc/grpc-java/issues/2558

**Comment by Scottmitch** [comment]
thanks for the additional details. Describing generally what your are doing doesn't provide too much context here. Can you share a minimal reproducer for this issue?

Do you have any idea what frame type is written which violates the max frame size?

**Comment by killjason** [comment]
@Scottmitch , the frame type is DATA frame.
 I debug the DefaultHttp2FrameReader when violates max frame size, the 'frameType' is 0.

**Comment by killjason** [comment]
@Scottmitch 
**Th reproducer jars:**
[proxy.zip](https://github.com/netty/netty/files/679450/proxy.zip)
[grpc-benchmark-server.zip](https://github.com/netty/netty/files/679452/grpc-benchmark-server.zip)
[grpc-benchmark-client.zip](https://github.com/netty/netty/files/679453/grpc-benchmark-client.zip)
**Steps to reproduce:**
(run the following commands in the same server, **please use a good performance server** because this problem only occurs in high qps)
1.java -jar proxy.jar
2.java -jar grpc-benchmark-server.jar --address=127.0.0.1:50051
3.java -jar grpc-benchmark-client.jar --address=127.0.0.1:50051
The error will captured in the console of grpc-benchmark-client. if not, please run the grpc-benchmark-client again.

the proxy sample source : 
[proxy-src.zip](https://github.com/netty/netty/files/679461/proxy-src.zip)

**Comment by Scottmitch** [comment]
@killjason - Few question:

`Http2ChannelHandler`:
1. I don't see any coordination between sending the connection preface to `outBoundContext` and sending other frames. Is it possible other data may be sent before the connection preface?
2. You are directly using the `Http2FrameWriter` via `encoder.frameWriter()`. You should be using the`Http2ConnectionEncoder` to write which enforces flow control and manages other stream/connection state.

Correcting the second issue, plus the [section 6.5.2 SETTINGS_ENABLE_PUSH restriction of not including a value of 0](https://tools.ietf.org/html/rfc7540#section-6.5.2), leads me to a too many concurrent streams violation. The peer is sending a `SETTINGS_MAX_CONCURRENT_STREAMS` with a value of `0`. Please correct these issues and report back with new source code if you think there is still a Netty issue.

**Comment by killjason** [comment]
@Scottmitch I think the problem is that I use encoder().writeHeader(context)/writeData(context) in the server type http2connectionhandler, and the context parameter is the backed handler context

**Comment by Scottmitch** [comment]
@killjason - thanks for reporting back. so some wires got crossed ... that will do it :)
