### ISSUE TITLE
ByteBuf#compareTo() "violates its general contract"

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#6169]
### Expected behavior

`ByteBuf` implements the Comparable interface but it appears to not work correctly.

### Actual behavior

The following exception occurs:

```java
Exception in thread "main" java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
	at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
	at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
	at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
	at java.util.Arrays.sort(Arrays.java:1312)
	at java.util.Arrays.sort(Arrays.java:1506)
	at java.util.ArrayList.sort(ArrayList.java:1454)
	at java.util.Collections.sort(Collections.java:141)
	at Main.main(Main.java:23)
```

### Steps to reproduce

See below.

### Minimal yet complete reproducer code (or URL to code)

```java
public class Main {

  public static void main(String[] args) {
    Random generator = new Random();
    
    List<ByteBuf> values = new ArrayList<>();
    
    for (int i = 0; i < 10000; i++) {
      byte[] value = new byte[20];
      generator.nextBytes(value);
      
      values.add(Unpooled.wrappedBuffer(value));
    }
    
    Collections.sort(values);
  }
}
```

### Netty version

4.1.7.Final-SNAPSHOT

### JVM version (e.g. `java -version`)

```
$ java -version
openjdk version "1.8.0_112"
OpenJDK Runtime Environment (build 1.8.0_112-b15)
OpenJDK 64-Bit Server VM (build 25.112-b15, mixed mode)
```

### OS version (e.g. `uname -a`)

Linux

**Comment by Scottmitch** [comment]
Thanks for reporting @rkapsi ... standby for a PR.
