### ISSUE TITLE
SSL handshake fails with Received fatal alert: internal_error

### ISSUE THREAD

**Issue by mp911de** [netty/netty#6178]
### Expected behavior

Successful SSL handshake should work with `SslHandler`. Using Java's `URLConnection` works.

### Actual behavior

`javax.net.ssl.SSLException: Received fatal alert: internal_error` thrown

```
Caused by: javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:1083)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1097)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:968)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:902)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
```

### Steps to reproduce

1. Connect to `randomuser.me`, Port 443
2. Initiate SSL handshake

### Minimal yet complete reproducer code (or URL to code)

```java
// works
URL url = new URL("https://randomuser.me/");
HttpURLConnection urlConnection = (HttpURLConnection) url.openConnection();
urlConnection.connect();
InputStream inputStream = urlConnection.getInputStream();

inputStream.read();
urlConnection.disconnect();
```

```java
// fails
EventLoopGroup workerGroup = new NioEventLoopGroup();

Bootstrap b = new Bootstrap();
b.group(workerGroup);
b.channel(NioSocketChannel.class);
b.handler(new ChannelInitializer<SocketChannel>() {
	@Override
	public void initChannel(SocketChannel ch) throws Exception {

		SslContext nettySslContext = SslContextBuilder.forClient()
				.sslProvider(SslProvider.JDK).build();

		ch.pipeline().addLast(nettySslContext.newHandler(ch.alloc()));
	}
});

ChannelFuture f = b.connect("randomuser.me", 443).sync();

f.channel().writeAndFlush(Unpooled.wrappedBuffer("GET / HTTP/1.0\r\n".getBytes()));
```

### Netty version

4.1.6

### JVM version (e.g. `java -version`)

1.8.0_112

### OS version (e.g. `uname -a`)

macOS 10.12.2

**Comment by slandelle** [comment]
Have you tried enabling SSL/TLS debug (`-Djavax.net.debug=ssl`)?
This could be caused by Netty disabling unsecured protocols and cipher suites by default, while those are enabled with HttpsUrlConnection.

Without more information and without a way to reproduce your problem (as you hide your actual url), I don't expect anyone to be able to help and investigate.

**Comment by slandelle** [comment]
Also:
* AFAIK, `SslContext.newHandler` doesn't configure the `HTTPS` `EndpointIdentificationAlgorithm` on the `SSLEngine` it creates, so things like SNI might not work.
* You use the `newHandler` overloaded version that doesn't take the hostname and port.

**Comment by mp911de** [comment]
Using `newHandler(ByteBufAllocator, String, int)` did the trick. 

https://randomuser.me/ is the real URL, even if it does not look like. In this case, TLSv1.2 with ECDHE_ECDSA with P-256 and AES_128_GCM was used, so I could exclude the weak protocols as a possible cause.

Thanks a lot for your support.

**Comment by slandelle** [comment]
Great!
