### ISSUE TITLE
DecoderException: setMasterSecret() error

### ISSUE THREAD

**Issue by doom369** [netty/netty#6218]
Hello. I recently updated to latest netty version 4.1.7.Final and now from time to time I see next error in logs : 

```
017-01-15 12:31:16.525 ERROR - DecoderException.
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: setMasterSecret() error
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[server-0.21.7.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[server-0.21.7.jar:?]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[server-0.21.7.jar:?]
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:510) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[server-0.21.7.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[server-0.21.7.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018) ~[server-0.21.7.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) ~[server-0.21.7.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) ~[server-0.21.7.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[server-0.21.7.jar:?]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[server-0.21.7.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.RuntimeException: setMasterSecret() error
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1429) ~[?:1.8.0_111]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[?:1.8.0_111]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[?:1.8.0_111]
        at 0.21.7.jar:?]
        ... 22 more
sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_111]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_111]
        at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:218) ~[server-0.21.7.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1028) ~[server-0.21.7.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:950) ~[server-0.21.7.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[server-0.21.7.jar:?]
        ... 22 more
```

What does it mean?

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

Ubuntu

**Comment by normanmaurer** [comment]
@doom369 hmm that is strange... are you sure you not also upgrade the jdk ?

**Comment by doom369** [comment]
> are you sure you not also upgrade the jdk ?

What do you mean by that?

Usually I'm using epoll +openSSL enabled. However this time I'm turned off openSSL after upgrade to 4.1.7.Final. So during this period I saw this error on different servers where I deployed 4.1.7 with turned off openSSL. Now I made a build of tcnative-parent-FORK-25 and switched back to openSSL no such errors anymore.

**Comment by normanmaurer** [comment]
@doom369 I was asking if you maybe also have upgrade Java itself to another version. Honestly I never saw this error before :/

**Comment by doom369** [comment]
@normanmaurer 

> I was asking if you maybe also have upgrade Java itself to another version.

I updated recently all my envs from 1.8.0_96 to 1.8.0_111 if that what are you asking.

> Honestly I never saw this error before :/

Same here :).

**Comment by normanmaurer** [comment]
@doom369 yes... let me dig a bit.

**Comment by doom369** [comment]
I did many changes to own server too so for now issue is not reproducible for 4.1.9. Closing for now.
