### ISSUE TITLE
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:11235 when established 2000 connections from netty client program at netty client side 

### ISSUE THREAD

**Issue by maybhi** [netty/netty#6220]
### Expected behavior
No Error
### Actual behavior
As i am making 2000 concurrent connections(TLS Connections) from java netty client program to netty server which is running on same host. But after 500 or 1000 connections i am getting below error at netty client side,

Jan 16, 2017 8:30:28 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by veni.client.Client$1.operationComplete()
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /127.0.0.1:11235
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(Unknown Source)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:346)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:630)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Unknown Source)

but when i run the same client program with inserting Thread.sleep(50) i didn't get above error at client side. So whats the reason or whats wrong in the code? 

 
### Minimal yet complete reproducer code (or URL to code)
https://drive.google.com/drive/folders/0B4wkBrJ4uyHMY3lraVVMWnBBRE0?usp=sharing

### Netty version
Netty client version 4.1.7.Final and netty server v

ersion 4.1.7.Final

### JVM version (e.g. `java -version`)
JRE1.8.0_101

### OS version (e.g. `uname -a`)
Windows Server 2012 R2 Standard

**Comment by normanmaurer** [comment]
@maybhi maybe some sort of firewall ? This error comes from the jdk classes directly so there is nothing we can do here in netty.

**Comment by Scottmitch** [comment]
It sounds like slowing down the rate at which the client attempts to establish new connections make the issue go away and you are able to open the desired amount of sockets? If so you may want to check your SO_BACKLOG parameter is large enough to handle the burst of connection attempts.

**Comment by maybhi** [comment]
@normanmaurer as i am running both client and server on same host and Can you please tell me about this exception from your io.netty.channel.AbstractChannel implementation?

**Comment by maybhi** [comment]
@Scottmitch I have already set backlog= 5000 in ServerBootstrap option. and i am attempting only 2000 connections simultaneously. is there anything else?

**Comment by Scottmitch** [comment]
>but when i run the same client program with inserting Thread.sleep(50) i didn't get above error at client side

Where do you put this `sleep` call?

> is there anything else?

I'm not very familiar with Windows but I would check your backlog queue lengths as you run your scenario to make sure your configuration is being applied as expected. I would also check if there are any max file descriptor limits or other limits imposed by your environment.

**Comment by maybhi** [comment]
@Scottmitch  please find below client code,

package veni.client;

import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.net.InetSocketAddress;
import java.net.SocketAddress;
import java.security.KeyStore;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.Scanner;
import java.util.UUID;

import javax.net.ssl.KeyManager;
import javax.net.ssl.KeyManagerFactory;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLEngine;
import javax.net.ssl.TrustManager;
import javax.net.ssl.TrustManagerFactory;

import io.netty.bootstrap.Bootstrap;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelOption;
import io.netty.channel.EventLoopGroup;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioSocketChannel;
import io.netty.util.concurrent.Future;
import io.netty.util.concurrent.FutureListener;
import veni.client.configuration.ClientConfigProperties;

public class Client {
//	private EventLoopGroup loop = new NioEventLoopGroup();

	public String clientId;
	public String receiverId;
	public String groupId;
	public Channel channel;
	public static ClientConfigProperties properties = new ClientConfigProperties();

	public static String serverIp;
	public static int serverPort;
	static List<UUID> idsArrayList = new ArrayList<UUID>();
	static List<Client> clientsList = new ArrayList<Client>();

	public Client(String clientId) {
		this.serverIp = this.properties.getServerIp();
		this.serverPort = this.properties.getPort();
		this.clientId = clientId;

	}

	public Client(String clientId, String receiverId, String groupid) {
		this.serverIp = this.properties.getServerIp();
		this.serverPort = this.properties.getPort();

		this.clientId = clientId;
		this.receiverId = receiverId;
		this.groupId = groupid;

	}

	public void run() throws Exception {

		createBootstrap(new Bootstrap(), new NioEventLoopGroup());
	}

	public static void main(String[] args) throws Exception {

		// Client client=new Client("mayank", "dhaval", "mygroup");
		Scanner scanner = new Scanner(System.in);
		scanner.useDelimiter(System.getProperty("line.separator"));
		System.out.println("No of connections to make:-");
		String noofConnections = scanner.nextLine();

		for (int i = 0; i < Integer.parseInt(noofConnections); i++) {

			UUID idOne = UUID.randomUUID();
//			System.out.println(idOne.toString());

			while (idsArrayList.contains(idOne)) {
				idOne = UUID.randomUUID();
			}
			idsArrayList.add(idOne);

			int arrayListSize = idsArrayList.size();
			Random random = new Random();
			int randomIndex = 0;
			if (arrayListSize > 1) {
				randomIndex = random.nextInt(arrayListSize - 1) == 0 ? 0 : random.nextInt(arrayListSize - 1);
			}
			Client client = new Client(idOne.toString(), idsArrayList.get(randomIndex).toString(), "mygroup");
			client.run();
			clientsList.add(client);
			System.out.println("Connections:- "+i);
//			Thread.sleep(50);
		}

		System.out.println("No of messages do you want to send by each conenction?:-");
		String noOfMessages = scanner.nextLine();

		System.out.println("Please type message text:-");
		String Message = scanner.nextLine();
		for (int i = 0; i < Integer.parseInt(noofConnections); i++) {
			Client client = clientsList.get(i);
			client.publishMessage(noOfMessages, Message, client);
		}

		// new Client("hardik","vivek","mygroup").run();
		// new Client("vivek","hardik","mygroup").run();

		/*
		 * int i=1; while(true) { new
		 * Client("dhaval_"+i,"mayank_"+i,"mygroup").run("odd"); i++;
		 * System.out.println("sys : "+i); }
		 * 
		 * 
		 * 
		 */

	}

	public void publishMessage(String noOfMessages, String Message, Client client) {
		try {
			// BufferedReader bufferedReader = new BufferedReader(new
			// InputStreamReader(System.in));
			// while (true) {
			// String input = bufferedReader.readLine();
			for (int i = 0; i < Integer.parseInt(noOfMessages); i++) {
				if (!client.channel.isActive()) {
					client.run();

				}
				// if(!input.equals(""))
				//
				// clientBasicMethods.sendMessageToGroup(clientId,groupId,input,channel);

				// if (!input.equals("")) {
				ClientBasicMethods clientBasicMethods = new ClientBasicMethods();
				clientBasicMethods.sendMessageToClient(client.clientId, client.receiverId, Message, client.channel);
				// }
				// }
			}
		} catch (InterruptedException e) {
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	public Bootstrap createBootstrap(Bootstrap bootstrap, EventLoopGroup eventLoop)  {
		try {
			bootstrap = new Bootstrap().group(eventLoop).channel(NioSocketChannel.class)
					.option(ChannelOption.TCP_NODELAY, true).option(ChannelOption.SO_KEEPALIVE, true)
					.option(ChannelOption.CONNECT_TIMEOUT_MILLIS,20000).handler(new ClientInitializer(this));

			final ChannelFuture channelFuture = bootstrap.connect(serverIp, serverPort);
			channelFuture.addListener(new FutureListener<Void>() {

				public void operationComplete(Future<Void> future) throws Exception {
					// TODO Auto-generated method stub

					if (!future.isSuccess()) {
				
						ChannelFuture f = channelFuture.sync();
						f.await();						
						channel = channelFuture.sync().channel();
						System.out.println("Test Connection failed");

					} else {
						channel = channelFuture.sync().channel();
					}
				}
			});

		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		} finally {
			// eventLoop.shutdownGracefully();
		}

		return bootstrap;
	}

	public SSLEngine getSslEngine() throws Exception {

		TrustManagerFactory tmFactory = TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());
		String keystorePass = "123456";

		KeyStore ks = KeyStore.getInstance("JKS");
		tmFactory.init(ks);

		ks.load(new FileInputStream("resources/newssl/keystore.jks"), keystorePass.toCharArray());

		// Set up key manager factory to use our key store
		KeyManagerFactory kmf = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
		kmf.init(ks, keystorePass.toCharArray());

		KeyManager[] km = kmf.getKeyManagers();
		TrustManager[] tm = tmFactory.getTrustManagers();

		SSLContext sslContext = SSLContext.getInstance("TLS");
		sslContext.init(km, tm, null);
		sslContext.getServerSessionContext().setSessionCacheSize(1);
		sslContext.getServerSessionContext().setSessionTimeout(60);
		SSLEngine sslEngine = sslContext.getDefault().createSSLEngine(serverIp, serverPort);

		sslEngine.setUseClientMode(true);
		sslEngine.setEnabledProtocols(sslEngine.getSupportedProtocols());
		sslEngine.setEnabledCipherSuites(sslEngine.getSupportedCipherSuites());
		return sslEngine;
	}

	public String getClientId() {
		return clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	public String getReceiverId() {
		return receiverId;
	}

	public void setReceiverId(String receiverId) {
		this.receiverId = receiverId;
	}

}

and file descriptor limit i have already set to 60000 in windows from registry.

**Comment by Scottmitch** [comment]
As I assumed in https://github.com/netty/netty/issues/6220#issuecomment-272962548 the `sleep` is slowing the rate at which connection attempts are made.

As @normanmaurer suggested above in https://github.com/netty/netty/issues/6220#issuecomment-272893409 this condition is encountered by the JDK so we don't have much visibility into it. If I had to guess it would be related to environment issues. Maybe try to run your client/server on a Linux VM (appropriately configured for the number of FDs you want to use) and see if you have similar issues. If you can use the [transport-native-epoll](http://netty.io/wiki/native-transports.html) (only supported on linux) perhaps you will get different behavior or a more descriptive error message.

**Comment by KillerMaster184** [comment]
I can't Play murderer In this sever in minecraft mc.pigparty.eu so if you can fix i will be super happy

**Comment by XiaLeon** [comment]
Hi @maybhi 
I met this same issue, have you solved this issue now ? If you have resolved it, can you please tell me the solution? Thanks a lot !
