### ISSUE TITLE
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Bad arguments

### ISSUE THREAD

**Issue by doom369** [netty/netty#6222]
One more strange exception in latest 4.1.7-Final. I'm don't think this netty specific. However it never appeared before : 

```
2017-01-16 14:33:05.301 ERROR - DecoderException.
io.netty.handler.codec.DecoderException: java.lang.IllegalArgumentException: Bad arguments
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:510) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[server-0.21.7-3.jar:?]  
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) ~[server-0.21.7-3.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[server-0.21.7-3.jar:?]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[server-0.21.7-3.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Bad arguments
        at javax.crypto.Mac.update(Mac.java:509) ~[?:1.8.0_121]
        at sun.security.ssl.MAC.compute(MAC.java:135) ~[?:1.8.0_111]
        at sun.security.ssl.InputRecord.checkMacTags(InputRecord.java:265) ~[?:1.8.0_111]
        at sun.security.ssl.InputRecord.decrypt(InputRecord.java:216) ~[?:1.8.0_111]
        at sun.security.ssl.EngineInputRecord.decrypt(EngineInputRecord.java:177) ~[?:1.8.0_111]
        at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:974) ~[?:1.8.0_111]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:907) ~[?:1.8.0_111]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_111]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_111]
        at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:218) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1028) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:950) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[server-0.21.7-3.jar:?]
        ... 22 more
```

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

Ubuntu

**Comment by Scottmitch** [comment]
Can you provide a reproducer? Do you see a similar issue when using OpenSSL?

**Comment by doom369** [comment]
`Do you see a similar issue when using OpenSSL?`

No.

`Can you provide a reproducer?`

Reproducible only on production servers with many different traffic.

**Comment by Scottmitch** [comment]
You also reported https://github.com/netty/netty/issues/6218. Is the environment and scenario (upgraded java and Netty, don't usually use Java SSLEngine but did during the upgrade process) the same for this issue too?

**Comment by doom369** [comment]
Correct.

**Comment by Scottmitch** [comment]
just for additional context ... you are using JDK based SSLEngine because you are seeing other issues which may be related to the OpenSSL based SSLEngine https://github.com/netty/netty/issues/6221?

**Comment by doom369** [comment]
Initially I switched to JDK based SSLEngine in order to build openSSL on same machine. So I updated netty version, turned off openSSL and started new server where those errors become to appear. After that I made a build of tcnative, turned openSSL on and restarted server again. And memory leaks started.

**Comment by doom369** [comment]
One more but a bit different : 

```
2017-01-17 09:16:18.954 ERROR - DecoderException.
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Delegated task threw Exception/Error
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442) ~[server-0.21.7-3.jar
:?]        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.traffic.AbstractTrafficShapingHandler.channelRead(AbstractTrafficShapingHandler.java:510) 
~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394) ~[server-0.21.7-3.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299) ~[server-0.21.7-3.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) ~[server-0.21.7-3.jar:?]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) ~[server-0.21.7-3.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.RuntimeException: Delegated task threw Exception/Error
        at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1429) ~[?:1.8.0_111]
        at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535) ~[?:1.8.0_111]
        at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813) ~[?:1.8.0_111]
        at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781) ~[?:1.8.0_111]
        at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624) ~[?:1.8.0_111]
        at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:218) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1028) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:950) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[server-0.21.7-3.jar:?]
        ... 22 more
Caused by: java.lang.IllegalStateException
        at sun.security.ec.ECDHKeyAgreement.deriveKey(Native Method) ~[sunec.jar:1.8.0_111]
        at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:130) ~[sunec.jar:1.8.0_111]
        at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:163) ~[sunec.jar:1.8.0_111]
        at javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:648) ~[?:1.8.0_121]
        at sun.security.ssl.ECDHCrypt.getAgreedSecret(ECDHCrypt.java:101) ~[?:1.8.0_111]
        at sun.security.ssl.ECDHCrypt.getAgreedSecret(ECDHCrypt.java:119) ~[?:1.8.0_111]
        at sun.security.ssl.ServerHandshaker.clientKeyExchange(ServerHandshaker.java:1616) ~[?:1.8.0_111]
        at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:278) ~[?:1.8.0_111]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_111]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:919) ~[?:1.8.0_111]
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:916) ~[?:1.8.0_111]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369) ~[?:1.8.0_111]
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1167) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1080) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:950) ~[server-0.21.7-3.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411) ~[server-0.21.7-3.jar:?]
        ... 22 more

```

**Comment by normanmaurer** [comment]
@doom369 could you also try to use JDK SSLEngine with the "previous" netty version and see if this happens there as well ? Sorry to ask you for all of this but I try to find out if it was recently introduced or not.

**Comment by doom369** [comment]
@normanmaurer no problem. I'll see what I can do here.

**Comment by normanmaurer** [comment]
Thx! A reproducer would be even better 😜

**Comment by normanmaurer** [comment]
@doom369 ping

**Comment by doom369** [comment]
No update far. I switched back to openSSL. And no errors. I'll check on QA.

**Comment by Scottmitch** [comment]
@doom369 - Can you clarify what versions of Netty and netty-tcnative you are using?

**Comment by doom369** [comment]
@Scottmitch The issue was in 4.1.7-Final and JDK SSL. I have and had no issues with tcnative.

**Comment by Scottmitch** [comment]
Have you tried reproducing with 4.1.8?

**Comment by doom369** [comment]
Not reproduced in 4.1.9.

**Comment by normanmaurer** [comment]
@doom369 thanks for the update :)

**Comment by leonchen83** [comment]
appeared once in netty-4.0.53

JDK SSLEngine

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

**Comment by leonchen83** [comment]
seems this exception appeared which choose `HMAC` family cipher suits to decrypt data
