### ISSUE TITLE
it is too slow when using loopback interface

### ISSUE THREAD

**Issue by yiguolei** [netty/netty#6226]
I write a simple ping pong code. the client send a long value to server and the server reply the long value to the client and then the client send the value again....

the client and server are on the same machine and tcp_nodelay=true.

I found netty could only send and receive only about 60k ping pong messages.  while thrift could send and receive about 600k ping pong messages in the same environment.

I am using jstack to check the bottleneck and found both the server and the client are running epollWait. the stack is:
"nioEventLoopGroup-2-1" prio=10 tid=0x00007f7f0059d800 nid=0x7a5b runnable [0x00007f7ee2cb8000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x000000021e62c630> (a io.netty.channel.nio.SelectedSelectionKeySet)
        - locked <0x000000021e62d720> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000021e62c588> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:746)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:391)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

### Netty version
4.1.7 
### JVM version (e.g. `java -version`)
java version "1.7.0_79"
### OS version (e.g. `uname -a`)
 2.6.32_1-18-0-0 #1 SMP Fri Jan 29 18:37:55 CST 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Scottmitch** [comment]
I would recommend starting with the [echo example](https://github.com/netty/netty/tree/4.1/example/src/main/java/io/netty/example/echo) and ensure you understand the mechanics of sending/receiving messages and flushing. Please re-open if you still feel there is an issue attributed to Netty.
