### ISSUE TITLE
4.1.7: java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0

### ISSUE THREAD

**Issue by jesperpedersen** [netty/netty#6246]
### Expected behavior

No error

### Actual behavior

```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.internal.PlatformDependent0
        at io.netty.util.internal.PlatformDependent.getClassLoader(PlatformDependent.java:881)
        at io.netty.channel.DefaultChannelId.defaultProcessId(DefaultChannelId.java:110)
        at io.netty.channel.DefaultChannelId.<clinit>(DefaultChannelId.java:78)
        at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
        at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
        at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
        at io.netty.channel.nio.AbstractNioByteChannel.<init>(AbstractNioByteChannel.java:54)
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:97)
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:87)
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:80)
        at io.netty.channel.socket.nio.NioSocketChannel.<init>(NioSocketChannel.java:73)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:319)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
```

### Minimal yet complete reproducer code (or URL to code)

Same as https://github.com/netty/netty/issues/6038

### Netty version

4.1.7

### JVM version (e.g. `java -version`)

```
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)
```

### OS version (e.g. `uname -a`)

```
Fedora 24
Linux localhost.localdomain 4.8.16-200.fc24.x86_64 #1 SMP Fri Jan 6 18:13:39 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jesperpedersen** [comment]
@Scottmitch  Looks like an upport of https://github.com/netty/netty/commit/e5ac9d3c9e753008c9fa13f3631b06a45a182096 is needed

**Comment by normanmaurer** [comment]
@Scottmitch can you take a look ?

**Comment by Scottmitch** [comment]
PR https://github.com/netty/netty/pull/6042 was developed against 4.1 and merged into both 4.1 and 4.0 but was specifically target at `getSystemClassLoader`.  This issue is for `PlatformDependent.getClassLoader` which was not addressed ... let me investigate.

**Comment by Scottmitch** [comment]
@jesperpedersen - You also verified #6042 in https://github.com/netty/netty/pull/6042#issuecomment-261929942. Did your use case or something else change?

**Comment by jesperpedersen** [comment]
No, nothing changed other than we switched to Netty 4.1.

Netty 4.0.43 worked, and reverting back to Netty 4.1.4 also worked.

**Comment by Scottmitch** [comment]
> No, nothing changed other than we switched to Netty 4.1.

To clarify ... your version of Netty changed? You verified on 4.x but you are now using 4.1, correct?

**Comment by jesperpedersen** [comment]
I originally verified with the patch for 4.0, since we ere using that version at the time. We later moved to 4.1, which I now have verified. So correct.

**Comment by Scottmitch** [comment]
thx for clarifying ... based on https://github.com/netty/netty/pull/6251#issuecomment-273782967 you should now also be able to use 4.1.
