### ISSUE TITLE
javax.net.ssl.SSLException: error:140D00CF:SSL routines:SSL_write:protocol is shutdown

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#6260]
```
 javax.net.ssl.SSLException: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:745) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:734) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:711) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_102]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:764) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:596) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:568) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:549) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:530) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:355) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
...
```

Reported by @rkapsi in https://github.com/netty/netty/issues/6249#issuecomment-274139907

**Comment by normanmaurer** [comment]
Looking....

**Comment by normanmaurer** [comment]
@rkapsi do you have a more complete stacktrace for me ?

**Comment by rkapsi** [comment]
Sure... Here's one for H2

```java
javax.net.ssl.SSLException: error:140D00CF:SSL routines:SSL_write:protocol is shutdown
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:745) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:734) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:711) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_102]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:764) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:596) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:568) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:549) ~[netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:777) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:769) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:750) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:561) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledData.error(DefaultHttp2ConnectionEncoder.java:367) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.writeError(DefaultHttp2RemoteFlowController.java:537) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:487) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.cancel(DefaultHttp2RemoteFlowController.java:468) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$1.onStreamClosed(DefaultHttp2RemoteFlowController.java:103) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.notifyClosed(DefaultHttp2Connection.java:345) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.removeFromActiveStreams(DefaultHttp2Connection.java:1224) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.deactivate(DefaultHttp2Connection.java:1172) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.close(DefaultHttp2Connection.java:549) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection.close(DefaultHttp2Connection.java:151) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.Http2ConnectionHandler$BaseDecoder.channelInactive(Http2ConnectionHandler.java:187) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:380) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:794) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:278) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at com.squarespace.aaa.bbb.ccc.Ddd.channelInactive(Ddd.java:56) [aaa-bbb-1.2.3.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.8.Final-SNAPSHOT.jar:4.1.8.Final-SNAPSHOT]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by rkapsi** [comment]
The common thing appears to be `channelInactive()` triggering a `flush()` which then throws.

**Comment by normanmaurer** [comment]
@rkapsi PTAL https://github.com/netty/netty/pull/6262 and if possible test the change. I am trying to write a unit test for it now.

**Comment by normanmaurer** [comment]
fixed by https://github.com/netty/netty/pull/6262#issuecomment-274183090
