### ISSUE TITLE
DnsNameResolver leaks memory on error

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#6274]
`resolver.query()` returns a future, which potentially can be in error state.

In that scenario a user cannot get hold of the DatagramDnsResponse to release it.

### Netty version
4.1.7

```
Jan 25, 2017 10:40:36 AM io.netty.util.ResourceLeakDetector reportTracedLeak
SEVERE: LEAK: DnsMessage.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 1
#1:
	Hint: 'DnsNameResolver$DnsResponseHandler#0' will handle the message from this point.
	io.netty.handler.codec.dns.AbstractDnsMessage.touch(AbstractDnsMessage.java:363)
	io.netty.handler.codec.dns.DefaultDnsResponse.touch(DefaultDnsResponse.java:161)
	io.netty.handler.codec.dns.DatagramDnsResponse.touch(DatagramDnsResponse.java:167)
	io.netty.handler.codec.dns.DatagramDnsResponse.touch(DatagramDnsResponse.java:27)
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:107)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:346)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	java.lang.Thread.run(Thread.java:745)
Created at:
	io.netty.util.ResourceLeakDetector.track(ResourceLeakDetector.java:219)
	io.netty.handler.codec.dns.AbstractDnsMessage.<init>(AbstractDnsMessage.java:44)
	io.netty.handler.codec.dns.DefaultDnsResponse.<init>(DefaultDnsResponse.java:61)
	io.netty.handler.codec.dns.DatagramDnsResponse.<init>(DatagramDnsResponse.java:70)
	io.netty.handler.codec.dns.DatagramDnsResponseDecoder.newResponse(DatagramDnsResponseDecoder.java:87)
	io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:57)
	io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:33)
	io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	java.lang.Thread.run(Thread.java:745)
Jan 25, 2017 10:40:37 AM io.netty.util.ResourceLeakDetector reportTracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
```

I know the description is rough, i am trying to extract a reproducer out of my app, but maybe this is sufficient for somebody to go:
oh yeah...

**Comment by normanmaurer** [comment]
@CodingFabian doh! Let me check

**Comment by normanmaurer** [comment]
@CodingFabian do you also have the stacktrace of the exception?

**Comment by normanmaurer** [comment]
I may have an idea tho ....

**Comment by CodingFabian** [comment]
```
resolver = new DnsNameResolverBuilder(group.next()).channelType(NioDatagramChannel.class)        .nameServerAddresses(DnsServerAddresses.singleton(inetSocketAddress)).queryTimeoutMillis(500).build();

      Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> query = resolver.query(dnsQuery));
      AddressedEnvelope<DnsResponse, InetSocketAddress> response = query.get(600, MILLISECONDS);
```

for example results in:
```
java.util.concurrent.ExecutionException: io.netty.resolver.dns.DnsNameResolverException: [/8.8.8.8:53] query timed out after 500 milliseconds (no stack trace available)
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:54)
```

**Comment by CodingFabian** [comment]
I might have missed something, but this reproducer leaks memory for me:
```
public class NettyLeak {

  private static NioEventLoopGroup group;
  private static DnsNameResolver resolver;

  public static void main(String[] args) throws Exception {
    ResourceLeakDetector.setLevel(Level.PARANOID);

    group = new NioEventLoopGroup(2, new DefaultThreadFactory("dnsresolver"));
    resolver = new DnsNameResolverBuilder(group.next()).channelType(NioDatagramChannel.class)
        .nameServerAddresses(DnsServerAddresses.singleton(new InetSocketAddress("8.8.8.8", 53))).queryTimeoutMillis(50)
        .build();
    int i = 0;
    while (i++ < 200_000) {
      AddressedEnvelope<DnsResponse, InetSocketAddress> response = null;
      try {
        Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> query = resolver
            .query(new DefaultDnsQuestion("netty-bug-domain.that.does.not.exist", DnsRecordType.A));
        response = query.get(60, MILLISECONDS);
      } catch (Exception e) {
        e.printStackTrace();
      } finally {
        if (response != null) {
          response.release();
        }
      }
    }
    System.out.println("ENDED");
    System.gc();
    Thread.sleep(1000000000);
  }
}
```

**Comment by CodingFabian** [comment]
in this case my code never gets a releaseable object.

**Comment by normanmaurer** [comment]
@CodingFabian thanks will have a fix soon :)

**Comment by normanmaurer** [comment]
@CodingFabian actually in the code you provided it makes sense as `Future.get(..., TimeUnit)` will return a `TimeoutException` when it times out but NOT fail the original Future.  You should just call `Future.get()` and thats it.

**Comment by CodingFabian** [comment]
This alternative solution leaks even harder:
```
      try {
        Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> query = resolver
            .query(new DefaultDnsQuestion("netty-bug-domain.that.does.not.exist", DnsRecordType.A));
        query.addListener((f) -> {
          try {
            if (f.isSuccess()) {
              AddressedEnvelope<DnsResponse, InetSocketAddress> r = (AddressedEnvelope<DnsResponse, InetSocketAddress>) f
                  .get();
              r.release();
            }
          } catch (Exception e) {
            e.printStackTrace();
          }
        });
      } catch (Exception e) {
        e.printStackTrace();
      }
```

```
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:101)
	at io.netty.util.ResourceLeakDetector.newRecord(ResourceLeakDetector.java:447)
	at io.netty.util.ResourceLeakDetector$DefaultResourceLeak.record0(ResourceLeakDetector.java:359)
	at io.netty.util.ResourceLeakDetector$DefaultResourceLeak.record(ResourceLeakDetector.java:354)
	at io.netty.handler.codec.dns.AbstractDnsMessage.touch(AbstractDnsMessage.java:363)
	at io.netty.handler.codec.dns.DefaultDnsQuery.touch(DefaultDnsQuery.java:97)
	at io.netty.handler.codec.dns.DatagramDnsQuery.touch(DatagramDnsQuery.java:133)
	at io.netty.handler.codec.dns.DatagramDnsQuery.touch(DatagramDnsQuery.java:27)
	at io.netty.util.ReferenceCountUtil.touch(ReferenceCountUtil.java:73)
	at io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:811)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:795)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:832)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at io.netty.resolver.dns.DnsQueryContext.writeQuery(DnsQueryContext.java:129)
	at io.netty.resolver.dns.DnsQueryContext.sendQuery(DnsQueryContext.java:113)
	at io.netty.resolver.dns.DnsQueryContext.query(DnsQueryContext.java:108)
	at io.netty.resolver.dns.DnsNameResolver.query0(DnsNameResolver.java:773)
	at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:730)
	at io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:701)
```

```
Jan 25, 2017 3:55:16 PM io.netty.util.ResourceLeakDetector reportTracedLeak
SEVERE: LEAK: DnsMessage.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 0
Created at:
	io.netty.util.ResourceLeakDetector.track(ResourceLeakDetector.java:219)
	io.netty.handler.codec.dns.AbstractDnsMessage.<init>(AbstractDnsMessage.java:44)
	io.netty.handler.codec.dns.DefaultDnsQuery.<init>(DefaultDnsQuery.java:42)
	io.netty.handler.codec.dns.DatagramDnsQuery.<init>(DatagramDnsQuery.java:56)
	io.netty.handler.codec.dns.DatagramDnsQuery.<init>(DatagramDnsQuery.java:43)
	io.netty.resolver.dns.DnsQueryContext.query(DnsQueryContext.java:90)
	io.netty.resolver.dns.DnsNameResolver.query0(DnsNameResolver.java:773)
	io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:730)
	io.netty.resolver.dns.DnsNameResolver.query(DnsNameResolver.java:701)
```

I have the feeling that releasing the buffers in failures is just not really working

**Comment by CodingFabian** [comment]
and it also produces
```
, L:/0:0:0:0:0:0:0:0:55588] Received a DNS response with an unknown ID: 42887
Jan 25, 2017 4:21:27 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
WARNING: [id: 0x570666b4, L:/0:0:0:0:0:0:0:0:55588] Received a DNS response with an unknown ID: 51758
Jan 25, 2017 4:21:27 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
WARNING: [id: 0x570666b4, L:/0:0:0:0:0:0:0:0:55588] Received a DNS response with an unknown ID: 43777
Jan 25, 2017 4:21:27 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
WARNING: [id: 0x570666b4, L:/0:0:0:0:0:0:0:0:55588] Received a DNS response with an unknown ID: 64504
Jan 25, 2017 4:21:27 PM io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler channelRead
```

I now the reproducer is a bit contrived, but we might be at something here

**Comment by normanmaurer** [comment]
@CodingFabian can not reproduce here... Can you test with latest 4.1 branch ?

**Comment by CodingFabian** [comment]
```
package io.netty.resolver.dns;

import java.net.InetSocketAddress;

import io.netty.channel.AddressedEnvelope;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioDatagramChannel;
import io.netty.handler.codec.dns.DefaultDnsQuestion;
import io.netty.handler.codec.dns.DnsRecordType;
import io.netty.handler.codec.dns.DnsResponse;
import io.netty.util.ResourceLeakDetector;
import io.netty.util.ResourceLeakDetector.Level;
import io.netty.util.concurrent.DefaultThreadFactory;
import io.netty.util.concurrent.Future;
import io.netty.util.concurrent.GenericFutureListener;

public class NettyLeak {

  private static NioEventLoopGroup group;
  private static DnsNameResolver resolver;

  public static void main(String[] args) throws Exception {
    ResourceLeakDetector.setLevel(Level.PARANOID);

    group = new NioEventLoopGroup(2, new DefaultThreadFactory("dnsresolver"));
    resolver = new DnsNameResolverBuilder(group.next()).channelType(NioDatagramChannel.class)
        .nameServerAddresses(DnsServerAddresses.singleton(new InetSocketAddress("8.8.8.8", 53))).queryTimeoutMillis(50)
        .build();
    int i = 0;
    while (i++ < 200000) {
      try {
        Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> query = resolver
            .query(new DefaultDnsQuestion("netty-bug-domain.that.does.not.exist", DnsRecordType.A));
        query.addListener(new GenericFutureListener<Future<AddressedEnvelope<DnsResponse, InetSocketAddress>>>() {

          @Override
          public void operationComplete(Future<AddressedEnvelope<DnsResponse, InetSocketAddress>> f) throws Exception {
            try {
              if (f.isSuccess()) {
                AddressedEnvelope<DnsResponse, InetSocketAddress> r = f.get();
                r.release();
              } else {
                f.cancel(true);
              }
            } catch (Exception e) {
              e.printStackTrace();
            }
          }

        });
      } catch (Exception e) {
        e.printStackTrace();
      }
      Thread.sleep(50);
    }
    System.out.println("ENDED");
    System.gc();
    Thread.sleep(1000000000);
  }
}
```
is the reproducer I am using on netty 4.1 head.
i run it with -Xms128m -Xmx128 

it still grows native memory (watched via ps && /proc/pid/statm)

**Comment by normanmaurer** [comment]
looking...

**Comment by CodingFabian** [comment]
at the moment i can also pretty reliably reproduce
```
18:21:22.287 [dnsresolver-1-1] WARN  i.netty.resolver.dns.DnsNameResolver - [id: 0xa69b7126, L:/0:0:0:0:0:0:0:0:51160] Received a DNS response with an unknown ID: 47486
```

**Comment by CodingFabian** [comment]
maybe some idea:
`io.netty.resolver.dns.DnsQueryContext.onQueryWriteCompletion(ChannelFuture)``
this schedules a runnable to check the timeout by querying the promise.
but if i see it right, it never cancels the actual query that might be still going on? and worse if it returns an answer that will not be released?

**Comment by normanmaurer** [comment]
@CodingFabian the answer will be released as the release happens in the finally block or I am missing anything ?

**Comment by normanmaurer** [comment]
After more debugging and looking I can not see any leak in the resolver. Please re-open if you find one.

**Comment by CodingFabian** [comment]
Thanks for your time, i will keep looking here. It is strange that it doesn't reproduce for you, while it reliably does for me. Guess we need to meet some day :)

**Comment by CodingFabian** [comment]
maybe something interesting for this (and potentially other native memory leak issues)

https://bugs.openjdk.java.net/browse/JDK-8164293

The Hotspot compiler leaks memory. it can be worked around by turning TieredCompilation off:
-XX:-TieredCompilation

**Comment by Scottmitch** [comment]
@CodingFabian - Interesting! Thanks for a link to the JDK leak!

**Comment by CodingFabian** [comment]
https://bugs.openjdk.java.net/browse/JDK-8172319
has the TieredCompilation hint.
I was able to reproduce this with a plain 4 line loop.
