### ISSUE TITLE
Increase test flakiness in 4.1.8

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#6296]
Relevant backtrace:
```
Jan 30, 2017 1:00:20 PM io.grpc.netty.NettyServerTransport notifyTerminated
SEVERE: Transport failed
io.netty.handler.codec.http2.Http2Exception: Request stream 3 is not correct for server connection
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:1095)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:942)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:960)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:868)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:158)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:148)
	at io.grpc.netty.NettyServerHandler.sendResponseHeaders(NettyServerHandler.java:360)
	at io.grpc.netty.NettyServerHandler.write(NettyServerHandler.java:305)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1022)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:291)
	at io.grpc.netty.WriteQueue.flush(WriteQueue.java:126)
	at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:48)
	at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:60)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

When trying out 4.1.8, we noticed that one of [our tests](https://github.com/grpc/grpc-java/blob/89bc2cd3b23d583387d104bb1ca6ec86ad9816be/testing/src/main/java/io/grpc/internal/testing/AbstractTransportTest.java#L190)  started failing about 70% of the time.  The test tries to see what happens if the HTTP/2 stream is cancelled early.  It appears that netty tries to look up the stream when responding server side, fails to find it, and then tries to initiate a push promise.  This doesn't make sense, since it is using a client side, odd-numbered ID.  This is the failure above.

I suspect that one of the recent HTTP/2 refactors caused this bug to be unearthed.   @Scottmitch do you have any ideas on why this would start happening in the latest version of Netty?

**Comment by Scottmitch** [comment]
there were a few spots where we forgot to catch errors and now we handle them but I'm not sure that is impacting this scenario. Here is the sequence of events that I see when I run locally:

1. Client writeHeaders(streamId=3)
2. Server onRstStreamRead(streamId=3)
3. Client writeHeaders(streamId=5)
4. Server writeHeaders(streamId=3) ... BOOM

In step (2) we synchronously close the stream (@ [1]) which may remove the stream from the `streamMap` [2]. However based on the stack trace provided above it looks like step (4) is executed via a `Runnable` at a later time. If the stream cannot be found by `DefaultHttp2ConnectionEncoder` it [attempts to create a stream for the local endpoint [3], but since the stream ID belongs to the remote endpoint ... boom.

Is this inline with your observations? If so we could try to be more forgiving in `DefaultHttp2ConnectionEncoder` and only try to create streams if they may not have previously existed (considering the correct endpoint, etc...). However if you are executing `Runnable`s in an asynchronous fashion what you are doing in https://github.com/grpc/grpc-java/pull/2671 also seems reasonable.

[1] https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L378
[2] https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java#L297
[3] (https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L158)

**Comment by Scottmitch** [comment]
> If so we could try to be more forgiving in DefaultHttp2ConnectionEncoder and only try to create streams if they may not have previously existed (considering the correct endpoint, etc...)

Actually I'm not sure how practical this is. What would the expected behavior of Netty be?

- Drop the message ... the application thinks it sent something but in reality we just dropped it on the floor ... bad.
- Call some method additional API to figure out what todo ... requires extra APIs when the application can just check before hand if this is anticipated to be an issue (async code execution).
- Send a RST ... what if we already sent a RST but we have already discarded the `Http2Stream` object. Sending multiple RST is permitted but not for this purpose:

https://tools.ietf.org/html/rfc7540#section-5.4.2
> Normally, an endpoint SHOULD NOT send more than one RST_STREAM frame
   for any stream.  However, an endpoint MAY send additional RST_STREAM
   frames if it receives frames on a closed stream after more than a
   round-trip time.  This behavior is permitted to deal with misbehaving
   implementations.

**Comment by carl-mastrangelo** [comment]
> Is this inline with your observations?
yes.  

> What would the expected behavior of Netty be?
I think we can agree that the server trying to create a stream is not right.  

Are there any unit tests in Netty for the behavior here?  I think it would be easier to talk about what should happen after we can definitely know that the existing behavior is intentional.

**Comment by Scottmitch** [comment]
I'm not sure what exactly you are looking for but if the line which leads to the stream being closed and removed from the stream map is commented out [1]. Then the following tests fail:

```
Failed tests:
  DefaultHttp2ConnectionDecoderTest.rstStreamReadAfterGoAwayShouldSucceed:571
Wanted but not invoked:
lifecycleManager.closeStream(stream, future);
-> at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoderTest.rstStreamReadAfterGoAwayShouldSucceed(DefaultHttp2ConnectionDecoderTest.java:571)
Actually, there were zero interactions with this mock.

  DefaultHttp2ConnectionDecoderTest.rstStreamReadShouldCloseStream:600
Wanted but not invoked:
lifecycleManager.closeStream(stream, future);
-> at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoderTest.rstStreamReadShouldCloseStream(DefaultHttp2ConnectionDecoderTest.java:600)
Actually, there were zero interactions with this mock.

  Http2FrameCodecTest.receiveRstStream:217
  Http2FrameCodecTest.streamClosedShouldFireUserEvent:355 expected:<CLOSED> but was:<OPEN>

Tests run: 502, Failures: 4, Errors: 0, Skipped: 0
```

Do you have an alternative behavior in mind? For example delaying the close of the stream, or removal from the connection (`streamMap`)? If we do this couldn't we run into similar issues if we didn't "delay long enough"?

[1] https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionDecoder.java#L345

**Comment by ejona86** [comment]
> Drop the message ... the application thinks it sent something but in reality we just dropped it on the floor ... bad.

Not entirely bad. This is already the semantics in presence of RST_STREAM. The problem is that it is unclear the problem is due to a race with RST_STREAM. Failing the future seems like it could be reasonable.

> Send a RST ... 

I don't understand why RST would be appropriate if the application is sending on a stream we think doesn't exist. I could understand "emulate receiving a RST".

**Comment by Scottmitch** [comment]
> Failing the future seems like it could be reasonable.

We should do this now right [1]? The code recently changed but we have been doing this for a while [2]. Is the issue that the error message is misleading? In this case we could check if the stream ID is for the remote endpoint and provide a more informative error message.

> I don't understand why RST would be appropriate if the application is sending on a stream we think doesn't exist

I agree. I wasn't suggesting it was appropriate. Just trying to follow the through process and probe for more information.

[1] https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L208
[2] https://github.com/netty/netty/blame/ead87b7df8d923417475ead2d7680747b1a72f07/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L207

**Comment by carl-mastrangelo** [comment]
>We should do this now right [1]? The code recently changed but we have been doing this for a while [2]. Is the issue that the error message is misleading? In this case we could check if the stream ID is for the remote endpoint and provide a more informative error message.

Hmm, even with a better error message, it still causes us to have to check if the stream exists first.  Ideally there shouldn't be any error message.  There isn't anything the server code can do differently, so why bother it with an exception?

**Comment by Scottmitch** [comment]
> it still causes us to have to check if the stream exists first. 

If the stream is remote, and may have existed we could handle this case differently (stream error, don't send a GO_AWAY and don't send a RST). Currently it looks like we send a GO_AWAY in this condition which may be harsh considering scenarios described in this issue.

> There isn't anything the server code can do differently, so why bother it with an exception?

The server tried to write headers and this operation failed. IMHO we should not swallow this event and failing the promise is the interface contract. The server can do with this what it makes sense (log, metrics, check if the stream exists only if the error occurs, etc..).

**Comment by normanmaurer** [comment]
@carl-mastrangelo @Scottmitch any update here ?

**Comment by Scottmitch** [comment]
It is still not clear to me what action should be taken in Netty as a result of this.

**Comment by normanmaurer** [comment]
@carl-mastrangelo I will close this for now. Please re-open if you still think there is an issue
