### ISSUE TITLE
Initialization of PlatformDependent0 fails on Java 9

### ISSUE THREAD

**Issue by mp911de** [netty/netty#6345]
Initialization of `PlatformDependent0` fails on Java 9 in static initializer when calling `setAccessible(true)`.

```
Field field = Buffer.class.getDeclaredField("address");
field.setAccessible(true);
```

### Expected behavior

Initialization should not fail without `--add-opens=java.base/java.nio=ALL-UNNAMED`

### Actual behavior

Class initialization fails with:

```
java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @598067a5
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:207)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:171)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:165)
	at io.netty.util.internal.PlatformDependent0$1.run(PlatformDependent0.java:72)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:67)
	at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:888)
	at io.netty.util.internal.PlatformDependent.isAndroid0(PlatformDependent.java:905)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:81)
	at io.netty.buffer.PooledByteBufAllocator.<clinit>(PooledByteBufAllocator.java:87)

```
### Steps to reproduce

Trigger class initialization of `PlatformDependent0` or call to `PlatformDependent.getContextClassLoader()`.

### Minimal yet complete reproducer code (or URL to code)

Variant 1:
```
PlatformDependent.getContextClassLoader()
```

Variant 2:
```
Version nettyBufferVersion = Version.identify().get("netty-buffer");
```
### Netty version

4.1.8

### JVM version (e.g. `java -version`)

Java(TM) SE Runtime Environment (build 9-ea+156)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+156, mixed mode)

### OS version (e.g. `uname -a`)

macOS Sierra (16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64)

**Comment by normanmaurer** [comment]
@mp911de thanks for reporting... let me fix this

**Comment by normanmaurer** [comment]
Started working on a fix... should have a PR soon

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/6356
