### ISSUE TITLE
EventLoopException at client side on load

### ISSUE THREAD

**Issue by Amitunreal** [netty/netty#639]
I have worked on Netty 3.x.x and after encountering EPOLL Exceptions I decided to upgrade to Netty 4.0.0 alpha 5. So I am pretty new to this version.

I have a test setup involving a client and server which are using WebSocket Protocol of Netty 4.0.0 alpha 5 and running on

java version "1.6.0_35"
Java(TM) SE Runtime Environment (build 1.6.0_35-b10)
Java HotSpot(TM) 64-Bit Server VM (build 20.10-b01, mixed mode)

I have also applied following workaround as suggested by Netty developer to tackle EPOLL Exception,
-Dio.netty.epollBugWorkaround=true

With above setup, I am trying to download a 1mb file from server to client with the load of 50 request(files) per second and after 2 to 5 minutes I am getting following Exception,

The Exception block of main
io.netty.channel.EventLoopException: failed to create a child event loop
        at io.netty.channel.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:53)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:24)
        at io.netty.channel.socket.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:36)
        at io.netty.channel.socket.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:32)
        at io.netty.channel.socket.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:28)
        at com.rancore.netty.Netty4Client.run(Netty4Client.java:88)
        at com.rancore.netty.Netty4Client$2.run(Netty4Client.java:122)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
        at io.netty.channel.socket.nio.NioEventLoop.openSelector(NioEventLoop.java:90)
        at io.netty.channel.socket.nio.NioEventLoop.<init>(NioEventLoop.java:83)
        at io.netty.channel.socket.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:53)
        at io.netty.channel.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:50)
        ... 6 more
Caused by: java.io.IOException: Too many open files
        at sun.nio.ch.IOUtil.initPipe(Native Method)
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:49)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:18)
        at io.netty.channel.socket.nio.NioEventLoop.openSelector(NioEventLoop.java:88)
        ... 9 more
The Exception block of main
io.netty.channel.EventLoopException: failed to create a child event loop
        at io.netty.channel.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:53)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:24)
        at io.netty.channel.socket.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:36)
        at io.netty.channel.socket.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:32)
        at io.netty.channel.socket.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:28)
        at com.rancore.netty.Netty4Client.run(Netty4Client.java:88)
        at com.rancore.netty.Netty4Client$2.run(Netty4Client.java:122)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
        at io.netty.channel.socket.nio.NioEventLoop.openSelector(NioEventLoop.java:90)
        at io.netty.channel.socket.nio.NioEventLoop.<init>(NioEventLoop.java:83)
        at io.netty.channel.socket.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:53)
        at io.netty.channel.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:50)
        ... 6 more
Caused by: java.io.IOException: Too many open files
        at sun.nio.ch.EPollArrayWrapper.epollCreate(Native Method)
        at sun.nio.ch.EPollArrayWrapper.<init>(EPollArrayWrapper.java:69)
        at sun.nio.ch.EPollSelectorImpl.<init>(EPollSelectorImpl.java:52)
        at sun.nio.ch.EPollSelectorProvider.openSelector(EPollSelectorProvider.java:18)
        at io.netty.channel.socket.nio.NioEventLoop.openSelector(NioEventLoop.java:88)
        ... 9 more

The Scenario at client side is
1. Client creates a Bootstrap and initializes it.
2. Client connects to the Server
3. With the returned channel it writes a Http Post request to server and wait for 200 OK.
4. After receiving 200 OK it starts the Handshake process.
5. As soon as the handshake process completes the client receives a TextWebSocketFrame with metadata of requested file.
6. After receiving above, Client receives a BinaryWebSocketFrame having binary data of requested file.

There is no Error reported on the Server Side at all. 

Please provide insight for above problem.

**Comment by lizuojing** [comment]
@Amitunreal  I also get this Exception when i run my application for about two hours. I am try a  few times and then i get  the same exception.I want to know whether your solution is working,and whether you finally solve the problem.how to do it?
