### ISSUE TITLE
netty 3.5/3.6 - java.lang.ArrayIndexOutOfBoundsException during deflate compression

### ISSUE THREAD

**Issue by prayagupd** [netty/netty#6457]
### Expected behavior
I am using flume with netty to [write to file channel](https://github.com/netty/netty/blob/3.6/src/main/java/org/jboss/netty/channel/AbstractChannel.java#L248). 

The code flow is, [AbstractChannel#write](https://github.com/netty/netty/blob/3.6/src/main/java/org/jboss/netty/channel/AbstractChannel.java#L248)

```java
    public ChannelFuture write(Object message) {
        return Channels.write(this, message);
    }
```

which delegates to [Channels#write](https://github.com/netty/netty/blob/3.6/src/main/java/org/jboss/netty/channel/Channels.java#L702)

```java
    public static ChannelFuture write(Channel channel, Object message, SocketAddress remoteAddress) {
        ChannelFuture future = future(channel);
        channel.getPipeline().sendDownstream(
                new DownstreamMessageEvent(channel, future, message, remoteAddress));
        return future;
    }
```

And while writing to the file channel, it fails on compression(only sometimes). Works most of the times but once it fails on compression, keeps failing, only solution for me now is to start flume fresh until it fails again, as I'm wrapping my head around [deflation algorithm](https://github.com/netty/netty/blob/3.6/src/main/java/org/jboss/netty/util/internal/jzlib/Tree.java#L127).

```java
    static int d_code(int dist) {
        return dist < 256? _dist_code[dist] : _dist_code[256 + (dist >>> 7)];
    }
```
 
Well, it is somehow a flume question too, but I think its more a compression issue too. I have a flume [JIRA-issue](https://issues.apache.org/jira/browse/FLUME-3040) too, but they are unresponsive

### Actual behavior

```
Caused by: java.lang.ArrayIndexOutOfBoundsException
	at org.jboss.netty.util.internal.jzlib.Tree.d_code(Tree.java:127)
	at org.jboss.netty.util.internal.jzlib.Deflate.compress_block(Deflate.java:637)
	at org.jboss.netty.util.internal.jzlib.Deflate._tr_flush_block(Deflate.java:860)
	at org.jboss.netty.util.internal.jzlib.Deflate.flush_block_only(Deflate.java:724)
	at org.jboss.netty.util.internal.jzlib.Deflate.deflate_slow(Deflate.java:1168)
	at org.jboss.netty.util.internal.jzlib.Deflate.deflate(Deflate.java:1601)
	at org.jboss.netty.util.internal.jzlib.ZStream.deflate(ZStream.java:140)
	at org.jboss.netty.handler.codec.compression.ZlibEncoder.encode(ZlibEncoder.java:282)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:66)
	at org.jboss.netty.handler.codec.oneone.OneToOneStrictEncoder.doEncode(OneToOneStrictEncoder.java:35)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
	at org.jboss.netty.handler.codec.compression.ZlibEncoder.handleDownstream(ZlibEncoder.java:322)
	at org.jboss.netty.channel.Channels.write(Channels.java:725)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.doEncode(OneToOneEncoder.java:71)
	at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:59)
	at org.jboss.netty.channel.Channels.write(Channels.java:704)
	at org.jboss.netty.channel.Channels.write(Channels.java:671)
	at org.jboss.netty.channel.AbstractChannel.write(AbstractChannel.java:248)
	at org.apache.avro.ipc.NettyTransceiver.writeDataPack(NettyTransceiver.java:515)
```

One thing I could do is add loggings for what exact message did the compression fail. 

### Netty version

https://github.com/netty/netty/tree/3.6/src/main/java/org/jboss/netty

```
root@prayagupd:~# ls -l /flume/server/lib/ | grep netty
-rwxrwxrwx. 1  500  500  1132988 Nov  2 14:35 netty-3.5.12.Final.jar
-rwxrwxrwx. 1  500  500  1199572 Nov  2 14:34 netty-3.6.2.Final.jar
```

### JVM version (e.g. `java -version`)

```
java version "1.8.0"
Java(TM) SE Runtime Environment (build pxa6480sr3fp20-20161019_02(SR3 FP20))
IBM J9 VM (build 2.8, JRE 1.8.0 Linux amd64-64 Compressed References 20161013_322271 (JIT enabled, AOT enabled)
J9VM - R28_Java8_SR3_20161013_1635_B322271
JIT  - tr.r14.java.green_20161011_125790
GC   - R28_Java8_SR3_20161013_1635_B322271_CMPRSS
J9CL - 20161013_322271)
JCL - 20161018_01 based on Oracle jdk8u111-b14
```

### OS version (e.g. `uname -a`)

```
Linux y0319p10254 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by slandelle** [comment]
Netty 3 has reached end of line and is no longer maintained.
Please upgrade to Netty 4.1 and report back if issue still occurs.

**Comment by normanmaurer** [comment]
@prayagupd as @slandelle said 3.x is EOL and so not supported anymore.

**Comment by prayagupd** [comment]
Damn it. You are basically asking me to change the whole world, as [latest flume api](https://github.com/apache/flume/blob/flume-1.7/pom.xml#L1260) uses `netty 3.9.4`. No choice, back deflate encoding. Thanks guys.

**Comment by Scottmitch** [comment]
Releases are tagged (`netty-3.6.2.Final`) and development for the `3.x` releases is on the `3.x` branch. Note that there is no active development on the `3.x` branch and we generally do not do releases for `3.x`.

**Comment by ITzhangqiang** [comment]
> Damn it. You are basically asking me to change the whole world, as [latest flume api](https://github.com/apache/flume/blob/flume-1.7/pom.xml#L1260) uses `netty 3.9.4`. No choice, back deflate encoding. Thanks guys.
How did you finally solve the problem

**Comment by ITzhangqiang** [comment]
How did you finally solve the problem？
@prayagupa
