### ISSUE TITLE
using bazel to test spring-cloud-config-server got this error

### ISSUE THREAD

**Issue by ddwolf** [netty/netty#6499]
### Expected behavior
exit on demand
### Actual behavior
the system keep running on and on
### Steps to reproduce
using bazel0.4.4 to test spring-cloud-config-server

### Netty version
netty-all4.1.4
### JVM version (e.g. `java -version`)
1.8
### OS version (e.g. `uname -a`)
ubuntu 14.04

here is the output
```
[ INFO ] [2017-03-06 12:25:45.970] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext [987] - Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@5b7ea70d: startup date [Mon Mar 06 12:25:40 UTC 2017]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@247d8ae
```

and the thread dump
```
"Thread-4" Id=37 WAITING on io.netty.channel.AbstractChannel$CloseFuture@7cc9269d
        at java.lang.Object.wait(Native Method)
        -  waiting on io.netty.channel.AbstractChannel$CloseFuture@7cc9269d
        at java.lang.Object.wait(Object.java:502)
        at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:239)
        at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129)
        at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28)
        at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:340)
        at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:117)
        at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:28)
        at com.huawei.hsa.config.netty.NettyServer.stop(NettyServer.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeDestroyMethods(InitDestroyAnnotationBeanPostProcessor.java:325)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeDestruction(InitDestroyAnnotationBeanPostProcessor.java:154)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:253)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:954)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:961)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1033)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1009)
        at org.springframework.context.support.AbstractApplicationContext$2.run(AbstractApplicationContext.java:928)
        -  locked java.lang.Object@39cbafc0

"nioEventLoopGroup-3-1" Id=31 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@38e10c36
        -  locked java.util.Collections$UnmodifiableSet@611cf6ee
        -  locked sun.nio.ch.EPollSelectorImpl@4007e591
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

"nioEventLoopGroup-4-1" Id=30 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@528168b8
        -  locked java.util.Collections$UnmodifiableSet@62b14e62
        -  locked sun.nio.ch.EPollSelectorImpl@641c6f5c
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

"Thread-2" Id=29 TIMED_WAITING on com.google.common.util.concurrent.Futures$AsyncChainingFuture@1b482523
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on com.google.common.util.concurrent.Futures$AsyncChainingFuture@1b482523
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:369)
        at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:84)
        at com.huawei.hsa.config.etcd.controller.Watcher.run(Watcher.java:66)

"nioEventLoopGroup-2-1" Id=28 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked io.netty.channel.nio.SelectedSelectionKeySet@42554a5a
        -  locked java.util.Collections$UnmodifiableSet@2a7fce2c
        -  locked sun.nio.ch.EPollSelectorImpl@2d9e22b0
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:692)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:352)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 8" Id=26 RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@1fcae829
        -  locked java.util.Collections$UnmodifiableSet@4b105b52
        -  locked sun.nio.ch.EPollSelectorImpl@17c77b22
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:257)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 7" Id=25 RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@4be60744
        -  locked java.util.Collections$UnmodifiableSet@3a535b1
        -  locked sun.nio.ch.EPollSelectorImpl@4aa6345c
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:257)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 6" Id=24 RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@66945841
        -  locked java.util.Collections$UnmodifiableSet@1db3bff0
        -  locked sun.nio.ch.EPollSelectorImpl@3791094a
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:257)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 5" Id=23 RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@4c6edf30
        -  locked java.util.Collections$UnmodifiableSet@87cc0ac
        -  locked sun.nio.ch.EPollSelectorImpl@8b0a26c
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:257)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 4" Id=22 RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@37d42169
        -  locked java.util.Collections$UnmodifiableSet@df9fffc
        -  locked sun.nio.ch.EPollSelectorImpl@63ee274f
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:257)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 3" Id=21 RUNNABLE
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@6ec04a9c
        -  locked java.util.Collections$UnmodifiableSet@7809e144
        -  locked sun.nio.ch.EPollSelectorImpl@3acde7a6
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:257)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 2" Id=20 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@280b6bef
        -  locked java.util.Collections$UnmodifiableSet@447350d8
        -  locked sun.nio.ch.EPollSelectorImpl@73c78ad3
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:257)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
        at java.lang.Thread.run(Thread.java:745)

"I/O dispatcher 1" Id=19 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@2662a3da
        -  locked java.util.Collections$UnmodifiableSet@5545e0ea
        -  locked sun.nio.ch.EPollSelectorImpl@bee8f0a
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:257)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:106)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:590)
        at java.lang.Thread.run(Thread.java:745)

"pool-1-thread-1" Id=18 RUNNABLE (in native)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@44300db6
        -  locked java.util.Collections$UnmodifiableSet@777f0a99
        -  locked sun.nio.ch.EPollSelectorImpl@d47f62c
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:342)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        at java.lang.Thread.run(Thread.java:745)

"container-0" Id=17 TIMED_WAITING
        at java.lang.Thread.sleep(Native Method)
        at org.apache.catalina.core.StandardServer.await(StandardServer.java:407)
        at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer$1.run(TomcatEmbeddedServletContainer.java:140)

"main" Id=1 WAITING on org.springframework.context.support.AbstractApplicationContext$2@7417ef4f
        at java.lang.Object.wait(Native Method)
        -  waiting on org.springframework.context.support.AbstractApplicationContext$2@7417ef4f
        at java.lang.Thread.join(Thread.java:1245)
        at java.lang.Thread.join(Thread.java:1319)
        at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:106)
        at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
        at java.lang.Shutdown.runHooks(Shutdown.java:123)
        at java.lang.Shutdown.sequence(Shutdown.java:167)
        at java.lang.Shutdown.exit(Shutdown.java:212)
        -  locked java.lang.Class@3993af92
        at java.lang.Runtime.exit(Runtime.java:109)
        at java.lang.System.exit(System.java:971)
        at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:97)

"BazelTestRunner: Print stack traces if JVM exit hangs" Id=39 RUNNABLE (daemon)
        at sun.management.ThreadImpl.dumpThreads0(Native Method)
        at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:446)
        at com.google.testing.junit.runner.internal.StackTraces.printAll(StackTraces.java:43)
        at com.google.testing.junit.runner.BazelTestRunner$1.run(BazelTestRunner.java:173)
        at java.lang.Thread.run(Thread.java:745)

"http-nio-8080-Acceptor-0" Id=36 RUNNABLE (in native) (daemon)
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        -  locked java.lang.Object@51f27bf0
        at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:682)
        at java.lang.Thread.run(Thread.java:745)

"http-nio-8080-ClientPoller-1" Id=35 RUNNABLE (in native) (daemon)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@4dfffc74
        -  locked java.util.Collections$UnmodifiableSet@292effa4
        -  locked sun.nio.ch.EPollSelectorImpl@1ce6d9d2
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:1034)
        at java.lang.Thread.run(Thread.java:745)

"http-nio-8080-ClientPoller-0" Id=34 RUNNABLE (in native) (daemon)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@5e091c45
        -  locked java.util.Collections$UnmodifiableSet@6c2757ac
        -  locked sun.nio.ch.EPollSelectorImpl@322a5653
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.tomcat.util.net.NioEndpoint$Poller.run(NioEndpoint.java:1034)
        at java.lang.Thread.run(Thread.java:745)

"NioBlockingSelector.BlockPoller-1" Id=33 RUNNABLE (in native) (daemon)
        at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
        at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
        at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        -  locked sun.nio.ch.Util$2@18a8218d
        -  locked java.util.Collections$UnmodifiableSet@e55fde9
        -  locked sun.nio.ch.EPollSelectorImpl@589951b8
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at org.apache.tomcat.util.net.NioBlockingSelector$BlockPoller.run(NioBlockingSelector.java:342)

"threadDeathWatcher-5-1" Id=32 TIMED_WAITING (daemon)
        at java.lang.Thread.sleep(Native Method)
        at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

"process reaper" Id=27 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@77a56b1d (daemon)
        at sun.misc.Unsafe.park(Native Method)
        -  waiting on java.util.concurrent.SynchronousQueue$TransferStack@77a56b1d
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
        at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
        at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
        at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"ContainerBackgroundProcessor[StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]" Id=16 TIMED_WAITING (daemon)
        at java.lang.Thread.sleep(Native Method)
        at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1344)
        at java.lang.Thread.run(Thread.java:745)

"Signal Dispatcher" Id=4 RUNNABLE (daemon)

"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@72aebe51 (daemon)
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.ReferenceQueue$Lock@72aebe51
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@3637500f (daemon)
        at java.lang.Object.wait(Native Method)
        -  waiting on java.lang.ref.Reference$Lock@3637500f
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:157)

```

**Comment by Scottmitch** [comment]
Can you please clarify the following:

- What evaluation have you done to make you believe this is a Netty bug?
- Have you consulted with the folks that maintain `spring-cloud-config-server`?
- Why is `bazel0.4.4` necessary to reproduce?
- Specific steps on how can this be reproduced. Assume we know nothing about `bazel` or `spring-cloud-config-server`.

**Comment by ddwolf** [comment]
actually, I am not quite sure it's Netty's problem, I just don't know how to fix this and where to find a solution, I've also filed a issue in bazel's repo too. may be you can close this for now.

**Comment by Scottmitch** [comment]
@ddwolf - I will close for now. Please re-open if you get more information to indicate a Netty issue and have the information requested in https://github.com/netty/netty/issues/6499#issuecomment-284476206.

**Comment by ddwolf** [comment]
@Scottmitch hi, I was debugging this problems days, now I probably found that, this is nothing about bazel, because When I use mvn test , I got hanged too. just because maven's surefire plugin has a block of code forcibly invoke Runtime.getRuntime.halt( exitCode ) 30 seconds later after the tests passed , here is the code from [ForkedBlocker:L245](https://github.com/apache/maven-surefire/blob/master/surefire-booter/src/main/java/org/apache/maven/surefire/booter/ForkedBooter.java#L245):
```java
234:    private static void exit( int returnCode, Shutdown shutdownType, CommandReader reader, boolean stopReaderOnExit )
235:    {
236:        switch ( shutdownType )
237:        {
238:            case KILL:
239:                Runtime.getRuntime().halt( returnCode );
240:            case EXIT:
241:                if ( stopReaderOnExit )
242:                {
243:                    reader.stop();
244:                }
245:                launchLastDitchDaemonShutdownThread( returnCode );
246:                System.exit( returnCode );
247:            case DEFAULT:
248:                // refers to shutdown=testset, but not used now, keeping reader open
249:            default:
250:                break;
251:        }
252:    }
```
So the problem may be that when the tests all finished, why the netty server won't quit? but this should be the spring-boot's problem.

Any way, just ignore me, leave this thread still closed:)
