### ISSUE TITLE
[error] (run-main-0) java.lang.IllegalStateException: failed to create a child event loop

### ISSUE THREAD

**Issue by fangqiao** [netty/netty#6522]
My startup's REST API services is based on Netty and use Elasticsearch's Java client API to connect to ES servers.

Es was 5.1.2 and now it is being upgraded to 5.2.0 so is the Java client API.

During upgrade testing, the REST API service can not be started. Error trace is as bellow.

The REST service is built with Scala 2.11.8, with SBT as the build tool. Help much appreciated as it is at beta testing and we have got some users already. And we also need to upgrade Elasticsearch to 5.2 as it provides range date types, which are important for our business case.

I am looking into it. In the meanwhile, any insight is much appreciated.

[error] (run-main-0) java.lang.IllegalStateException: failed to create a child event loop
java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:100)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:87)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:64)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:48)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:41)
	at cn.shujubiji.bj.BjServiceServer$.main(BjServiceServer.scala:147)
	at cn.shujubiji.bj.BjServiceServer.main(BjServiceServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at io.netty.util.internal.PlatformDependent0.allocateMemory(PlatformDependent0.java:524)
	at io.netty.util.internal.PlatformDependent.allocateMemory(PlatformDependent.java:260)
	at io.netty.channel.epoll.IovArray.<init>(IovArray.java:64)
	at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:62)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:130)
	at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:58)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:100)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:87)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:64)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:48)
	at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:41)
	at cn.shujubiji.bj.BjServiceServer$.main(BjServiceServer.scala:147)
	at cn.shujubiji.bj.BjServiceServer.main(BjServiceServer.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
[debug] 	Thread run-main-0 exited.
[debug] Interrupting remaining threads (should be all daemons).
[debug] Interrupting thread MasterListener-shujubiji-[192.168.0.214:26380]
[debug] 	Interrupted MasterListener-shujubiji-[192.168.0.214:26380]
[debug] Interrupting thread elasticsearch[_client_][transport_client_boss][T#5]
[debug] 	Interrupted elasticsearch[_client_][transport_client_boss][T#5]
[debug] Interrupting thread elasticsearch[_client_][transport_client_boss][T#3]
[debug] 	Interrupted elasticsearch[_client_][transport_client_boss][T#3]
[debug] Interrupting thread elasticsearch[_client_][generic][T#4]
[debug] 	Interrupted elasticsearch[_client_][generic][T#4]
[debug] Interrupting thread AsyncAppender-Worker-ASYNC
[debug] 	Interrupted AsyncAppender-Worker-ASYNC
[debug] Interrupting thread elasticsearch[_client_][transport_client_boss][T#1]
[debug] 	Interrupted elasticsearch[_client_][transport_client_boss][T#1]
[debug] Interrupting thread threadDeathWatcher-2-1
[debug] 	Interrupted threadDeathWatcher-2-1
[debug] Interrupting thread elasticsearch[_client_][management][T#1]
[debug] 	Interrupted elasticsearch[_client_][management][T#1]
[debug] Interrupting thread elasticsearch[_client_][transport_client_boss][T#4]
[debug] 	Interrupted elasticsearch[_client_][transport_client_boss][T#4]
[debug] Interrupting thread Thread-2
[debug] 	Interrupted Thread-2
[debug] Interrupting thread MasterListener-shujubiji-[192.168.0.214:26381]
[debug] 	Interrupted MasterListener-shujubiji-[192.168.0.214:26381]
[debug] Interrupting thread elasticsearch[_client_][transport_client_boss][T#6]
[debug] 	Interrupted elasticsearch[_client_][transport_client_boss][T#6]
[debug] Interrupting thread commons-pool-EvictionTimer
[debug] 	Interrupted commons-pool-EvictionTimer
[debug] Interrupting thread elasticsearch[_client_][generic][T#1]
[debug] 	Interrupted elasticsearch[_client_][generic][T#1]
[debug] Interrupting thread elasticsearch[_client_][generic][T#2]
[debug] 	Interrupted elasticsearch[_client_][generic][T#2]
[debug] Interrupting thread idle_connection_reaper
[debug] 	Interrupted idle_connection_reaper
[debug] Interrupting thread elasticsearch[_client_][generic][T#3]
[debug] 	Interrupted elasticsearch[_client_][generic][T#3]
[debug] Interrupting thread elasticsearch[_client_][transport_client_boss][T#7]
[debug] 	Interrupted elasticsearch[_client_][transport_client_boss][T#7]
[debug] Interrupting thread elasticsearch[_client_][scheduler][T#1]
[debug] 	Interrupted elasticsearch[_client_][scheduler][T#1]
[debug] Interrupting thread elasticsearch[_client_][transport_client_boss][T#8]
[debug] 	Interrupted elasticsearch[_client_][transport_client_boss][T#8]
[debug] Interrupting thread elasticsearch[_client_][transport_client_boss][T#2]
[debug] 	Interrupted elasticsearch[_client_][transport_client_boss][T#2]
[debug] Interrupting thread elasticsearch[_client_][[timer]]
[debug] 	Interrupted elasticsearch[_client_][[timer]]
[debug] Interrupting thread MasterListener-shujubiji-[192.168.0.214:26382]
[debug] 	Interrupted MasterListener-shujubiji-[192.168.0.214:26382]
[debug] Interrupting thread MasterListener-shujubiji-[192.168.0.214:26379]
[debug] 	Interrupted MasterListener-shujubiji-[192.168.0.214:26379]
[debug] Sandboxed run complete..
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2128)
	at sbt.BuildCommon$$anonfun$toError$1.apply(Defaults.scala:2128)
	at scala.Option.foreach(Option.scala:236)
	at sbt.BuildCommon$class.toError(Defaults.scala:2128)
	at sbt.Defaults$.toError(Defaults.scala:39)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$46$$anonfun$apply$47.apply(Defaults.scala:769)
	at sbt.Defaults$$anonfun$runTask$1$$anonfun$apply$46$$anonfun$apply$47.apply(Defaults.scala:767)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (bj/compile:run) Nonzero exit code: 1

Full dependencies are as :

### Expected behavior[debug] 	/home/fqye/projects/shujubiji/bj/target/scala-2.11/classes
[debug] 	/home/fqye/projects/shujubiji/util/target/scala-2.11/classes
[debug] 	/home/fqye/projects/shujubiji/common/target/scala-2.11/classes
[debug] 	/home/fqye/projects/shujubiji/bj/lib/netty-all-4.1.4.Final.jar
[debug] 	/home/fqye/projects/shujubiji/bj/lib/logback-classic-1.1.7.jar
[debug] 	/home/fqye/projects/shujubiji/bj/lib/logback-core-1.1.7.jar
[debug] 	/home/fqye/projects/shujubiji/util/lib/netty-all-4.1.4.Final.jar
[debug] 	/home/fqye/.ivy2/cache/org.scalactic/scalactic_2.11/bundles/scalactic_2.11-3.0.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.8.jar
[debug] 	/home/fqye/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.8.jar
[debug] 	/home/fqye/.ivy2/cache/org.asynchttpclient/async-http-client/jars/async-http-client-2.0.11.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty-transport-native-epoll/jars/netty-transport-native-epoll-4.0.39.Final-linux-x86_64.jar
[debug] 	/home/fqye/.ivy2/cache/org.asynchttpclient/netty-resolver-dns/jars/netty-resolver-dns-2.0.11.jar
[debug] 	/home/fqye/.ivy2/cache/org.asynchttpclient/netty-resolver/jars/netty-resolver-2.0.11.jar
[debug] 	/home/fqye/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.21.jar
[debug] 	/home/fqye/.ivy2/cache/org.asynchttpclient/netty-codec-dns/jars/netty-codec-dns-2.0.11.jar
[debug] 	/home/fqye/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.0.jar
[debug] 	/home/fqye/.ivy2/cache/com.typesafe.netty/netty-reactive-streams/jars/netty-reactive-streams-1.0.6.jar
[debug] 	/home/fqye/.ivy2/cache/org.javassist/javassist/bundles/javassist-3.20.0-GA.jar
[debug] 	/home/fqye/.ivy2/cache/com.typesafe/config/bundles/config-1.3.1.jar
[debug] 	/home/fqye/.ivy2/cache/io.argonaut/argonaut_2.11/jars/argonaut_2.11-6.1.jar
[debug] 	/home/fqye/.ivy2/cache/org.scalaz/scalaz-core_2.11/bundles/scalaz-core_2.11-7.1.1.jar
[debug] 	/home/fqye/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.2.jar
[debug] 	/home/fqye/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.2.jar
[debug] 	/home/fqye/.ivy2/cache/com.github.julien-truffaut/monocle-core_2.11/jars/monocle-core_2.11-1.1.0.jar
[debug] 	/home/fqye/.ivy2/cache/com.github.julien-truffaut/monocle-macro_2.11/jars/monocle-macro_2.11-1.1.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.elasticsearch/elasticsearch/jars/elasticsearch-5.2.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-core/jars/lucene-core-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-analyzers-common/jars/lucene-analyzers-common-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-backward-codecs/jars/lucene-backward-codecs-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-grouping/jars/lucene-grouping-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-highlighter/jars/lucene-highlighter-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-join/jars/lucene-join-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-memory/jars/lucene-memory-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-misc/jars/lucene-misc-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-queries/jars/lucene-queries-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-queryparser/jars/lucene-queryparser-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-sandbox/jars/lucene-sandbox-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-spatial/jars/lucene-spatial-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-spatial-extras/jars/lucene-spatial-extras-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-spatial3d/jars/lucene-spatial3d-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.lucene/lucene-suggest/jars/lucene-suggest-6.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.elasticsearch/securesm/jars/securesm-1.1.jar
[debug] 	/home/fqye/.ivy2/cache/net.sf.jopt-simple/jopt-simple/jars/jopt-simple-5.0.2.jar
[debug] 	/home/fqye/.ivy2/cache/com.carrotsearch/hppc/jars/hppc-0.7.1.jar
[debug] 	/home/fqye/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.9.5.jar
[debug] 	/home/fqye/.ivy2/cache/org.yaml/snakeyaml/bundles/snakeyaml-1.15.jar
[debug] 	/home/fqye/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.8.6.jar
[debug] 	/home/fqye/.ivy2/cache/com.fasterxml.jackson.dataformat/jackson-dataformat-smile/bundles/jackson-dataformat-smile-2.8.6.jar
[debug] 	/home/fqye/.ivy2/cache/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/bundles/jackson-dataformat-yaml-2.8.6.jar
[debug] 	/home/fqye/.ivy2/cache/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor/bundles/jackson-dataformat-cbor-2.8.6.jar
[debug] 	/home/fqye/.ivy2/cache/com.tdunning/t-digest/jars/t-digest-3.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.hdrhistogram/HdrHistogram/bundles/HdrHistogram-2.1.6.jar
[debug] 	/home/fqye/.ivy2/cache/net.java.dev.jna/jna/jars/jna-4.2.2.jar
[debug] 	/home/fqye/.ivy2/cache/org.elasticsearch.client/transport/jars/transport-5.2.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.elasticsearch.plugin/transport-netty3-client/jars/transport-netty3-client-5.2.0.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty/bundles/netty-3.10.6.Final.jar
[debug] 	/home/fqye/.ivy2/cache/org.elasticsearch.plugin/transport-netty4-client/jars/transport-netty4-client-5.2.0.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty-buffer/jars/netty-buffer-4.1.7.Final.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty-common/jars/netty-common-4.1.7.Final.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty-codec/jars/netty-codec-4.1.7.Final.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty-transport/jars/netty-transport-4.1.7.Final.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty-resolver/jars/netty-resolver-4.1.7.Final.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty-codec-http/jars/netty-codec-http-4.1.7.Final.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty-handler/jars/netty-handler-4.1.7.Final.jar
[debug] 	/home/fqye/.ivy2/cache/org.elasticsearch.plugin/reindex-client/jars/reindex-client-5.2.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.elasticsearch.client/rest/jars/rest-5.2.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.httpcomponents/httpclient/jars/httpclient-4.5.2.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.httpcomponents/httpcore/jars/httpcore-4.4.5.jar
[debug] 	/home/fqye/.ivy2/cache/commons-logging/commons-logging/jars/commons-logging-1.1.3.jar
[debug] 	/home/fqye/.ivy2/cache/commons-codec/commons-codec/jars/commons-codec-1.10.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.httpcomponents/httpasyncclient/jars/httpasyncclient-4.1.2.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.httpcomponents/httpcore-nio/jars/httpcore-nio-4.4.5.jar
[debug] 	/home/fqye/.ivy2/cache/org.elasticsearch.plugin/lang-mustache-client/jars/lang-mustache-client-5.2.0.jar
[debug] 	/home/fqye/.ivy2/cache/com.github.spullara.mustache.java/compiler/jars/compiler-0.9.3.jar
[debug] 	/home/fqye/.ivy2/cache/org.elasticsearch.plugin/percolator-client/jars/percolator-client-5.2.0.jar
[debug] 	/home/fqye/.ivy2/cache/io.netty/netty-all/jars/netty-all-4.1.7.Final.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.logging.log4j/log4j-to-slf4j/jars/log4j-to-slf4j-2.7.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.logging.log4j/log4j-api/jars/log4j-api-2.7.jar
[debug] 	/home/fqye/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.7.jar
[debug] 	/home/fqye/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.1.7.jar
[debug] 	/home/fqye/.ivy2/cache/redis.clients/jedis/jars/jedis-2.9.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.commons/commons-pool2/jars/commons-pool2-2.4.2.jar
[debug] 	/home/fqye/.ivy2/cache/com.aliyun.oss/aliyun-sdk-oss/jars/aliyun-sdk-oss-2.4.0.jar
[debug] 	/home/fqye/.ivy2/cache/org.jdom/jdom/jars/jdom-1.1.jar
[debug] 	/home/fqye/.ivy2/cache/net.sf.json-lib/json-lib/jars/json-lib-2.4-jdk15.jar
[debug] 	/home/fqye/.ivy2/cache/commons-beanutils/commons-beanutils/jars/commons-beanutils-1.8.0.jar
[debug] 	/home/fqye/.ivy2/cache/commons-collections/commons-collections/jars/commons-collections-3.2.1.jar
[debug] 	/home/fqye/.ivy2/cache/commons-lang/commons-lang/jars/commons-lang-2.5.jar
[debug] 	/home/fqye/.ivy2/cache/net.sf.ezmorph/ezmorph/jars/ezmorph-1.0.6.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.poi/poi/jars/poi-3.15.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.commons/commons-collections4/jars/commons-collections4-4.1.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.poi/poi-scratchpad/jars/poi-scratchpad-3.15.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.poi/poi-ooxml/jars/poi-ooxml-3.15.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.poi/poi-ooxml-schemas/jars/poi-ooxml-schemas-3.15.jar
[debug] 	/home/fqye/.ivy2/cache/org.apache.xmlbeans/xmlbeans/jars/xmlbeans-2.6.0.jar
[debug] 	/home/fqye/.ivy2/cache/stax/stax-api/jars/stax-api-1.0.1.jar
[debug] 	/home/fqye/.ivy2/cache/com.github.virtuald/curvesapi/jars/curvesapi-1.04.jar

### Netty version
4.17
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (IcedTea 3.3.0) (suse-3.1-x86_64)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
Linux linux-68qh 4.9.11-1-default #1 SMP PREEMPT Sat Feb 18 17:59:27 UTC 2017 (cf9c670) x86_64 x86_64 x86_64 GNU/Linux

**Comment by Scottmitch** [comment]
What cause trace (each `getCause()` until null) of this exception?

**Comment by normanmaurer** [comment]
@Scottmitch yeah its because he tries to use the native transport while `sun.misc.Unsafe` is not accessible.  

@fangqiao please use the NIO transport if you can not use `sun.misc.Unsafe`. In 4.1.8.Final we throw a more meaningful error.

**Comment by Scottmitch** [comment]
That is what I figured. Update Netty :)

**Comment by fangqiao** [comment]
Thanks. It worked when I tried Nio. 

But I am curious why I can use Epoll before I upgrade Elasticsearch Java client to 5.2.2? It worked with Epoll very well and was deployed to production with no problems at all.

**Comment by normanmaurer** [comment]
@fangqiao from what I understand elastic search has a very tight securitymanager config these days. @jasontedor any idea ?
