### ISSUE TITLE
HTTP2 Channel between BIGENDIAN and LITTLEENDIAN platform does not work

### ISSUE THREAD

**Issue by denisgaebler** [netty/netty#6535]
### Expected behavior
Fix HTTP2 codec to be endianess save.

### Actual behavior
On ByteBuf some methods use endianess dependent methods like buf.writeInt or buf.writeMedium where in other places of the same class readUnsignedint(buf) or other endianess save methods or used (that were implemented in Http2CodecUtil.java).

### Steps to reproduce
Just try to connect a big endian and a little endian platform.

### Netty version
Probably all, I used netty-all-4.1.8.Final.jar

### JVM version (e.g. `java -version`)
JDK 8 on z/OS for one side and OpenJDK 8 on the other side of the channel:
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Zero VM (build 25.121-b13, interpreted mode)

### OS version (e.g. `uname -a`)
Ubuntu 16.04 and z/OS 2.2

**Comment by denisgaebler** [comment]
This is the Exception. It seams there is a need to agree, that binary fields need to be treated with the same endianess on both ends of a Channel, lets say always Little Endian, otherwise the other end is confused.

Caused by: io.netty.handler.codec.http2.Http2Exception: Invalid frame length 1024.
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.verifyWindowUpdateFrame(DefaultHttp2FrameReader.java:382)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processHeaderState(DefaultHttp2FrameReader.java:223)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:148)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:341)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:220)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:401)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)

**Comment by denisgaebler** [comment]
Maybe the problem is in this line of code of DefaultHttp2FrameReader.java in package io.netty.handler.codec.http2 of netty/codec-http2
// Read the header and prepare the unmarshaller to read the frame.
payloadLength = in.readUnsignedMedium();
Needs likely be changed to readUnsignedMediumLE();

**Comment by denisgaebler** [comment]
I found another piece of code which is not endianess save in Http2CodecUtil.java


    static void writeFrameHeaderInternal(ByteBuf out, int payloadLength, byte ty
pe,
            Http2Flags flags, int streamId) {
        out.writeMedium(payloadLength);
        out.writeByte(type);
        out.writeByte(flags.value());
        out.writeInt(streamId);
    }

The writeMedium and writeInt depend on Platform endianess but should use the same endianess on both ends of the wire.
From a endianess perspective the HTTP2 implementation of netty codec is broken. In the DefaultHttp2FrameReader.java and DefaultHttp2FrameWriter.java and Http2CodecUtil.java there is a mix of endian dependent (out.write...) and endian independent (e.g. writeMediumInt(int, buf)) use of methods for writing and reading to and from the bytebuffer.

**Comment by CodingFabian** [comment]
aha, thanks for digging this up, we were suspecting something like this in #6437 already

**Comment by normanmaurer** [comment]
@Scottmitch @nmittler @ejona86 could someone of you have a look ?

**Comment by denisgaebler** [comment]
When I managed to make it work, I replaced the writeInt method with the existing writeUnsignedInt method from Http2CodecUtil und for readMedium and writeMedium I added two new methods to Http2CodecUtil like:

    public static void writeUnsignedIntMedium(long value, ByteBuf out) {
        out.writeByte((int) (value >> 16 & 0xFF));
        out.writeByte((int) (value >> 8 & 0xFF));
        out.writeByte((int) (value & 0xFF));
    }

and 

   public static int readIntMedium(ByteBuf buf) {
       return (buf.readByte() & 0xFF) << 16
               | (buf.readByte() & 0xFF) << 8 | buf.readByte() & 0xFF;
   }

Hope that helps.

**Comment by Scottmitch** [comment]
> The writeMedium and writeInt depend on Platform endianess but should use the same endianess on both ends of the wire.

The intention is that by default ByteBuf's memory is in Network Byte Order (big endian). Methods on the ByteBuf interface without the `LE` suffix should be represented in memory as big endian. I found some bugs in the ByteBuf code which handles reading/writing primitives and fixed them in PR https://github.com/netty/netty/pull/6582.

There are also some unnecessary methods in codec-http2 which are not necessary and I submitted https://github.com/netty/netty/pull/6584 to clean these methods up.

Unfortunately I don't have access to a little endian machine at the moment. Would you mind running with PR https://github.com/netty/netty/pull/6584 and report back if there are still issues?

**Comment by Scottmitch** [comment]
@denisgaebler - These fixes have been merged. Please try with 4.1 HEAD and report back.

**Comment by Scottmitch** [comment]
@CodingFabian - fyi. could you also see if behavior has changed?

**Comment by denisgaebler** [comment]
Hi,

I can do the test, however, I have used Hyperledger when I found the problem. Is there an easier testcase that I can execute?

**Comment by Scottmitch** [comment]
I would prefer you run what ever scenario lead to your discovery of this issue. If you are unable to build the software on your own I would suggest waiting for the next release.

**Comment by normanmaurer** [comment]
@denisgaebler any update ?

**Comment by denisgaebler** [comment]
Hi Norman,

basically I have asked for an easier (http2 netty only) testcase because I have trouble building the hyperledger project, since there are lots of changes and my original testcase does not work anymore.
I will give it another try tomorrow and let you know.

**Comment by denisgaebler** [comment]
Hi,

unfortunatly I cannot test it with Hyperledger, because it uses grpc-netty:
https://github.com/grpc/grpc-java/tree/master/netty/src/main/java/io/grpc/netty

Which has hard coded gone classes with 4.10:
import io.netty.handler.codec.http2.internal.hpack.Decoder;

So I will open a ticket with netty and continue.

Thanks.

**Comment by Scottmitch** [comment]
thanks for the update. Let me close this issue for now. Please re-open if 4.10 doesn't solve this issue.
