### ISSUE TITLE
SSLHandler handleRemoved called before handlerAdded

### ISSUE THREAD

**Issue by yogeshvedpathak** [netty/netty#6536]
I am getting following stack trace when a connection terminates. I think the null pointer exception is originated because `pendingUnencryptedWrites` is null at link `415`. This could happen when `handleRemoved` is called before the `handleAdded`

2017-03-10 00:04:12.063 WARN  [nioEventLoopGroup-3-5] io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: io.netty.handler.ssl.SslHandler.handlerRemoved() has thrown an exception.
        at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:621) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:868) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:834) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:826) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:43) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1276) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:185) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:171) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:811) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:699) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) [netty-all-4.0.41.Final.jar:4.0.41.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException

**Comment by johnou** [comment]
@yogeshvedpathak would be nice if you could provide more information, reproducer would be a huge help.

**Comment by normanmaurer** [comment]
Is there no stack for the NPE?

**Comment by yogeshvedpathak** [comment]
Unfortunately there is no stack trace for NPE (i was surprised by that that.) From the other logs from our application i can tell that thi happens right after connection termination. So my best guess is that NPE is coming from pendingUnencryptedWrites being null.

**Comment by normanmaurer** [comment]
Could you upgrade to latest netty version and see if it still happens?

**Comment by johnou** [comment]
@yogeshvedpathak you might also consider adding ```-XX:-OmitStackTraceInFastThrow``` to your JVM args.

**Comment by normanmaurer** [comment]
As noted please upgrade to latest version and re-open if you still see the issue with more details

**Comment by normanmaurer** [comment]
@yogeshvedpathak https://github.com/netty/netty/pull/8684 PTAL
