### ISSUE TITLE
When sending partial sync command by the RedisClient, Got RedisCodecException: Unknown RedisMessageType: 13

### ISSUE THREAD

**Issue by Aegeaner** [netty/netty#6546]
### Expected behavior
Get normal redis sync backlog after the "FULLRESYNC $runid $offset" response or the "CONTINUE" response.

### Actual behavior

```
exceptionCaught: io.netty.handler.codec.DecoderException: io.netty.handler.codec.redis.RedisCodecException: delimiter: [42,49] (expected: \r\n)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.handler.codec.redis.RedisCodecException: delimiter: [42,49] (expected: \r\n)
	at io.netty.handler.codec.redis.RedisDecoder.readEndOfLine(RedisDecoder.java:231)
	at io.netty.handler.codec.redis.RedisDecoder.decodeBulkStringContent(RedisDecoder.java:211)
	at io.netty.handler.codec.redis.RedisDecoder.decode(RedisDecoder.java:103)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 16 more
exceptionCaught: io.netty.handler.codec.DecoderException: io.netty.handler.codec.redis.RedisCodecException: Unknown RedisMessageType: 13
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:375)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.handler.codec.redis.RedisCodecException: Unknown RedisMessageType: 13
	at io.netty.handler.codec.redis.RedisMessageType.valueOf(RedisMessageType.java:72)
	at io.netty.handler.codec.redis.RedisDecoder.decodeType(RedisDecoder.java:129)
	at io.netty.handler.codec.redis.RedisDecoder.decode(RedisDecoder.java:83)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 17 more

```

### Steps to reproduce

```
Enter Redis commands (quit to end)
psync 3257845d7944b30160fdb3e96409a715d232f585 2
FULLRESYNC 3257845d7944b30160fdb3e96409a715d232f585 6623
```

### Minimal yet complete reproducer code (or URL to code)
Example class: io.netty.example.redis.RedisClient

### Netty version
4.1.9.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b16, mixed mode)

### OS version (e.g. `uname -a`)
Darwin localhost 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64

**Comment by Scottmitch** [comment]
Redis documentation is typically very clear. However I cannot find any documentation on the expected structure of the `FULLRESYNC` response (other than https://redis.io/topics/replication). Based upon this documentation it seems like this is a redis-to-redis command:

> If you set up a slave, upon connection it sends a PSYNC command.

The response to this command doesn't follow the same structure as described in https://redis.io/topics/protocol. Here is the response I see:

First is the simple inline string
```
+FULLRESYNC 9bf43b059e64ed04582bfea7d8e385fcdc438f3d 1
```

Then is a bulk string
```
$1393
REDIS0007�	redis-ver3.2.8
...
```

Then when we try to read the delimiter (`\r\n`) we instead get a `*1`. After this point the remote redis server actually sends PING commands to us:

```
$4
PING
*1
$4
PING
```

Are you sure this is part of the typically client API, and if so can you provide a link to some documentation on this command?

**Comment by Aegeaner** [comment]
The PING command is sent by the slave.
When the slave try to sync with the master, it will periodly send PING command to master every second.
See: [https://redis.io/topics/replication](https://redis.io/topics/replication)

**Comment by Scottmitch** [comment]
It seems like you provided a high level summary of my response https://github.com/netty/netty/issues/6546#issuecomment-290566465.

To clarify my response ... `codec-redis` is and implementation of the client protocol described in https://redis.io/topics/protocol. The command structure between master/slaves (e.g. `PSYNC`) is not supported by `codec-redis`.

**Comment by Aegeaner** [comment]
yeah that's the cause of this issue.

**Comment by Scottmitch** [comment]
As described this is not supported by `codec-redis`, and is expected behavior. Feel free to submit a PR to support the redis-server protocol if you are interested.
