### ISSUE TITLE
cannot determine the type of the type parameter 'I' in MessageToMessageEncoder when define a generic encoder

### ISSUE THREAD

**Issue by suemi994** [netty/netty#6547]
### Expected behavior

The Client use my self-define encoder inherited from MessageToMessageEncoder.

### Actual behavior

It report the error "can't determine I in MessageToMessageEncoder" in TypeParameterMatcher 

### Minimal yet complete reproducer code (or URL to code)

First, I define a generic type coder as follow

```java

public class JsonEncoder<I> extends MessageToMessageEncoder<I> {

  @Override
  protected void encode(ChannelHandlerContext ctx, I msg, List<Object> out) throws Exception {
    out.add(JSON.toJSONString(msg));
  }
}
```

Then I use it in a client 

```java
public void connect(String host, short port) throws InterruptedException {
    EventLoopGroup group = new NioEventLoopGroup();
    try {
      Bootstrap boot = new Bootstrap();
      boot.group(group).channel(NioSocketChannel.class)
              .option(ChannelOption.TCP_NODELAY, true)
              .handler(new ChannelInitializer<SocketChannel>() {
                @Override
                protected void initChannel(SocketChannel ch) throws Exception {
                  ch.pipeline().addLast(new LineBasedFrameDecoder(1024))
                          .addLast(new StringDecoder())
                          .addLast(new JsonDecoder(JsonResponse.class))
                          .addLast(new JsonEncoder<JsonRequest>())
                          .addLast(new JsonClientHandler());
                }
              });
      ChannelFuture future = boot.connect(host, port).sync();
      future.channel().closeFuture().sync();
    } finally {
      group.shutdownGracefully();
    }
  }
```

It report the error in TypeParameterMatcher 

```
java.lang.IllegalStateException: cannot determine the type of the type parameter 'I': class com.suemi.network.json.JsonEncoder
	at io.netty.util.internal.TypeParameterMatcher.fail(TypeParameterMatcher.java:156)
	at io.netty.util.internal.TypeParameterMatcher.find0(TypeParameterMatcher.java:150)
	at io.netty.util.internal.TypeParameterMatcher.find(TypeParameterMatcher.java:78)
	at io.netty.handler.codec.MessageToMessageEncoder.<init>(MessageToMessageEncoder.java:59)
	at com.suemi.network.json.JsonEncoder.<init>(JsonEncoder.java:10)
	at com.suemi.network.json.JsonClient$1.initChannel(JsonClient.java:43)
	at com.suemi.network.json.JsonClient$1.initChannel(JsonClient.java:38)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

### Netty version

4.1.8-Final

### JVM version (e.g. `java -version`)

java version "1.8.0_65"

### OS version (e.g. `uname -a`)

Mac OSX 10.12.3

Darwin suemi-PC-2.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

**Comment by Underbalanced** [comment]
Not sure why this is happening but try using the constructor of MessageToMessageEncoder.java it should fix this.

`protected  MessageToMessageEncoder(Class<? extends I> outboundMessageType)`
Create a new instance 

I.E.
```
public class JsonEncoder<I> extends MessageToMessageEncoder<I> {
 
  public JsonEncoder(Class<? extends I> classI){
       super(classI);
  }

  @Override
  protected void encode(ChannelHandlerContext ctx, I msg, List<Object> out) throws Exception {
    out.add(JSON.toJSONString(msg));
  }
}

```


`                          .addLast(new JsonEncoder<JsonRequest>(JsonRequest.class))`



Link to the class API 
[MessageToMessageEncoder.java](http://netty.io/4.1/api/io/netty/handler/codec/MessageToMessageEncoder.html#MessageToMessageEncoder-java.lang.Class-)

**Comment by johnou** [comment]
It's happening because I is not an actual type and the class needs to be passed in for it to know, above usage is correct.

**Comment by Underbalanced** [comment]
So have you resolved this because this isn't a issue. If so please close.
