### ISSUE TITLE
DnsNameResolver fails for some hostnames

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#6559]
The following test is failing for me as of Netty 4.1.9.Final. To be exact, it fails most of the time and succeeds once every dozen of runs. I've tested setting the DNS servers explicitly (e.g. just 8.8.8.8:53) but that hasn't made a difference. 

It seems to be specific to certain hostnames (a few examples are included in the test) and more "normal" hostnames such as netty.io, google.com, apple.com work just fine.

### Netty version

Fails: 4.1.9.Final and later
Succeeds: versions prior to 4.1.9.Final

### Steps to reproduce

```java
public class ResolveTest {

  @Test
  public void testResolve() {
    
    EventLoopGroup group = new NioEventLoopGroup();
    try {
      DnsNameResolver resolver = new DnsNameResolverBuilder(group.next())
          .channelType(NioDatagramChannel.class)
          .build();
      try {
        // A few options that show the same result
        // msnbot-157-55-33-18.search.msn.com
        // b110352.yse.yahoo.net
        Future<InetAddress> future = resolver.resolve("crawl-66-249-64-1.googlebot.com");
        InetAddress address = future.syncUninterruptibly().getNow();
        
        assertNotNull(address);
        
      } finally {
        resolver.close();
      }
    } finally {
      group.shutdownGracefully();
    }
  }
}
```

```
java.net.UnknownHostException: failed to resolve 'crawl-66-249-64-1.googlebot.com' after 3 queries 
	at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:648)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:568)
	at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:278)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.resolver.dns.DnsQueryContext.setSuccess(DnsQueryContext.java:194)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:177)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:929)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```

```bash
$ dig crawl-66-249-64-1.googlebot.com

;; ANSWER SECTION:
crawl-66-249-64-1.googlebot.com. 59 IN	A	66.249.64.1
```

### JVM version (e.g. `java -version`)

```
$ java -version
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by normanmaurer** [comment]
Have you tried to increase some number of allowed queries ?

**Comment by rkapsi** [comment]
@normanmaurer via `maxQueriesPerResolve(...)`? That had no effect but... I've just changed `maxPayloadSize()` from the default value of 4kb to 10kb and that seems to fix it.

**Comment by rkapsi** [comment]
Actually, I take that back. The results flip flop.

**Comment by rkapsi** [comment]
But setting `resolvedAddressTypes(ResolvedAddressTypes.IPV4_ONLY)` seems to fix it (default value is IPV4_PREFERRED)

**Comment by normanmaurer** [comment]
interesting... I will have a look soon

**Comment by Scottmitch** [comment]
@rkapsi - Also note that as of 4.1.9 we respect the system DNS configuration and use this over provided hostnames. The ambiguity will be resolved soon as part of https://github.com/netty/netty/issues/6573. However is it possible you are using unexpected DNS servers?

**Comment by rkapsi** [comment]
@normanmaurer @Scottmitch I have tried setting `nameServerAddresses()` explicitly to 8.8.8.8 but that didn't make a difference (unless that's what you mean with system DNS being used over provided).

Here's a more complete test. Notice that the IPv6 tests are expected to fail (the test doesn't check for it though). The IPv4 tests are supposed to succeed and most importantly... The `testResolveDefault()` will be flapping. I guess depending on whether IPv4 or 6 gets picket.

You maybe need to run it a few times to see the effect.

```java
public class ResolveTest {
  
  @Test
  public void testResolveDefault() {
    doResolve(null);
  }
  
  @Test
  public void testResolveIPv4Only() {
    doResolve(ResolvedAddressTypes.IPV4_ONLY);
  }

  @Test
  public void testResolveIPv4Preferred() {
    doResolve(ResolvedAddressTypes.IPV4_PREFERRED);
  }

  @Test
  public void testResolveIPv6Only() {
    doResolve(ResolvedAddressTypes.IPV6_ONLY);
  }

  @Test
  public void testResolveIPv6Preferred() {
    doResolve(ResolvedAddressTypes.IPV6_PREFERRED);
  }
  
  private static void doResolve(ResolvedAddressTypes types) {
    EventLoopGroup group = new NioEventLoopGroup();
    try {
      DnsNameResolverBuilder builder = new DnsNameResolverBuilder(group.next())
          .channelType(NioDatagramChannel.class)
          .nameServerCache(NoopDnsServerAddressStreamProvider.INSTANCE);
      
      if (types != null) {
        builder.resolvedAddressTypes(types);
      }

      DnsNameResolver resolver = builder.build();
      try {
        // A few options that show the same result
        // msnbot-157-55-33-18.search.msn.com
        // b110352.yse.yahoo.net
        Future<InetAddress> future = resolver.resolve("crawl-66-249-64-1.googlebot.com");
        InetAddress address = future.syncUninterruptibly().getNow();
        
        Assert.assertNotNull(address);
        
      } finally {
        resolver.close();
      }
    } finally {
      group.shutdownGracefully();
    }
  }
}
```

![screenshot from 2017-03-31 09-23-06](https://cloud.githubusercontent.com/assets/191635/24552244/b3e47e4c-15f3-11e7-8785-63f35cbfdf5a.png)

**Comment by Scottmitch** [comment]
> I have tried setting nameServerAddresses() explicitly to 8.8.8.8 but that didn't make a difference (unless that's what you mean with system DNS being used over provided).

@rkapsi - https://github.com/netty/netty/issues/6573#issuecomment-289554271 communicates what I was getting after. Let me know if you accounted for this and we are on the same page. Note that this ambiguity has been resolved via PR https://github.com/netty/netty/pull/6588.

**Comment by Scottmitch** [comment]
Can you clarify what your expectations are for this particular domain (`crawl-66-249-64-1.googlebot.com`) for an AAAA lookup? This lookup returns an SOA record, but using the name-server and treating it like a redirect provides the same results.

Original query:
```
dig crawl-66-249-64-1.googlebot.com AAAA

; <<>> DiG 9.8.3-P1 <<>> crawl-66-249-64-1.googlebot.com AAAA
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31988
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;crawl-66-249-64-1.googlebot.com. IN	AAAA

;; AUTHORITY SECTION:
googlebot.com.		600	IN	SOA	ns2.google.com. dns-admin.google.com. 151855960 900 900 1800 60

;; Query time: 29 msec
;; SERVER: 17.128.100.12#53(17.128.100.12)
;; WHEN: Fri Mar 31 17:25:30 2017
;; MSG SIZE  rcvd: 106
```

If I try the same query using `ns2.google.com.` I get the same results (no answers):

```
dig @ns2.google.com. crawl-66-249-64-1.googlebot.com AAAA

; <<>> DiG 9.8.3-P1 <<>> @ns2.google.com. crawl-66-249-64-1.googlebot.com AAAA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41082
;; flags: qr aa rd; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;crawl-66-249-64-1.googlebot.com. IN	AAAA

;; AUTHORITY SECTION:
googlebot.com.		600	IN	SOA	ns2.google.com. dns-admin.google.com. 151855960 900 900 1800 60

;; Query time: 46 msec
;; SERVER: 216.239.34.10#53(216.239.34.10)
;; WHEN: Fri Mar 31 17:26:30 2017
;; MSG SIZE  rcvd: 106
```

To contrast if I try wikipedia's DNS servers I actually get an answer:

```
dig SOA wikipedia.com

; <<>> DiG 9.8.3-P1 <<>> SOA wikipedia.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52040
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;wikipedia.com.			IN	SOA

;; ANSWER SECTION:
wikipedia.com.		86398	IN	SOA	ns0.wikimedia.org. hostmaster.wikimedia.org. 2017032822 43200 7200 1209600 3600

;; Query time: 30 msec
;; SERVER: 17.128.100.12#53(17.128.100.12)
;; WHEN: Fri Mar 31 17:23:30 2017
;; MSG SIZE  rcvd: 95
```

Following the name-server like a redirect:

```
dig @ns0.wikimedia.org. wikipedia.com AAAA

; <<>> DiG 9.8.3-P1 <<>> @ns0.wikimedia.org. wikipedia.com AAAA
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19982
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;wikipedia.com.			IN	AAAA

;; ANSWER SECTION:
wikipedia.com.		600	IN	AAAA	2620:0:863:ed1a::1

;; ADDITIONAL SECTION:
wikipedia.com.		600	IN	A	198.35.26.96

;; Query time: 75 msec
;; SERVER: 208.80.154.238#53(208.80.154.238)
;; WHEN: Fri Mar 31 17:23:43 2017
;; MSG SIZE  rcvd: 75
```

**Comment by Scottmitch** [comment]
Possibly related: https://github.com/netty/netty/issues/6600. Although it is unclear to me (based upon the above unit test in https://github.com/netty/netty/issues/6559#issuecomment-290713440) if the expectation is we should also some how obtain AAAA records.

**Comment by rkapsi** [comment]
@Scottmitch I'm expecting `AAAA` to fail and `A` to succeed for `crawl-66-249-64-1.googlebot.com`. 

In the context of `DnsNameResolver` I'm expecting it to resolve to an IP address when I'm using a default configuration for it. That's how it used to be before `ResolvedAddressTypes` was introduced. To put it differently, I'm expecting it to behave like JDK's own InetAddress and resolve to a IP address. I don't care if it's IPv4 or IPv6 (figuratively speaking).

The observed behavior is that the default configuration will flap between failure and success.

I'm currently working around the problem by explicitly setting `resolvedAddressTypes(IPV4_PREFERRED)`.

**Comment by rkapsi** [comment]
I think this and #6600 are the same

**Comment by Scottmitch** [comment]
@rkapsi - Thanks for clarifying and confirming. Let me close this issue for now. Please reopen if PR https://github.com/netty/netty/pull/6601 doesn't resolve the issue.
