### ISSUE TITLE
WebSocketHandshakeException: not a WebSocket handshake request: missing upgrade

### ISSUE THREAD

**Issue by fbettag** [netty/netty#656]
When using the Netty 3.5 code for WebSocket handshaking on 4.0a5, under load i sometimes get:

```
Oct 15, 2012 7:32:30 PM io.netty.channel.DefaultChannelPipeline
WARNING: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: not a WebSocket handshake request: missing upgrade
        at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker00.handshake(WebSocketServerHandshaker00.java:124)
        at io.thruput.netty.AuthenticationHandler$.shakeShakeShake(AuthenticationHandler.scala:62)
        at io.thruput.netty.AuthenticationHandler$.handleHttp(AuthenticationHandler.scala:96)
        at io.thruput.netty.AuthenticationHandler$.messageReceived(AuthenticationHandler.scala:35)
        at io.netty.channel.ChannelInboundMessageHandlerAdapter.inboundBufferUpdated(ChannelInboundMessageHandlerAdapter.java:40)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.handler.codec.MessageToMessageDecoder.inboundBufferUpdated(MessageToMessageDecoder.java:76)
        at io.netty.handler.codec.MessageToMessageCodec.inboundBufferUpdated(MessageToMessageCodec.java:77)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.handler.codec.MessageToMessageDecoder.inboundBufferUpdated(MessageToMessageDecoder.java:76)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.handler.codec.ReplayingDecoder.fireInboundBufferUpdated(ReplayingDecoder.java:462)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:453)
        at io.netty.handler.codec.ByteToMessageDecoder.inboundBufferUpdated(ByteToMessageDecoder.java:43)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.thruput.netty.ProtoNegoHandler.inboundBufferUpdated(ProtoNegoHandler.scala:92)
        at io.netty.channel.ChannelInboundByteHandlerAdapter.inboundBufferUpdated(ChannelInboundByteHandlerAdapter.java:44)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.handler.timeout.IdleStateHandler.inboundBufferUpdated(IdleStateHandler.java:273)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.channel.DefaultChannelPipeline.fireInboundBufferUpdated(DefaultChannelPipeline.java:1068)
        at io.netty.channel.socket.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:91)
        at io.netty.channel.socket.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:274)
        at io.netty.channel.socket.nio.NioEventLoop.run(NioEventLoop.java:211)
        at io.netty.channel.SingleThreadEventExecutor$1.run(SingleThreadEventExecutor.java:80)
        at java.lang.Thread.run(Unknown Source)
```

sometimes it is "missing key":

```
Oct 15, 2012 7:32:35 PM io.netty.channel.DefaultChannelPipeline
WARNING: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.handler.codec.http.websocketx.WebSocketHandshakeException: not a WebSocket request: missing key
        at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker13.handshake(WebSocketServerHandshaker13.java:120)
        at io.thruput.netty.AuthenticationHandler$.shakeShakeShake(AuthenticationHandler.scala:62)
        at io.thruput.netty.AuthenticationHandler$.handleHttp(AuthenticationHandler.scala:96)
        at io.thruput.netty.AuthenticationHandler$.messageReceived(AuthenticationHandler.scala:35)
        at io.netty.channel.ChannelInboundMessageHandlerAdapter.inboundBufferUpdated(ChannelInboundMessageHandlerAdapter.java:40)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.handler.codec.MessageToMessageDecoder.inboundBufferUpdated(MessageToMessageDecoder.java:76)
        at io.netty.handler.codec.MessageToMessageCodec.inboundBufferUpdated(MessageToMessageCodec.java:77)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.handler.codec.MessageToMessageDecoder.inboundBufferUpdated(MessageToMessageDecoder.java:76)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.handler.codec.ReplayingDecoder.fireInboundBufferUpdated(ReplayingDecoder.java:462)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:453)
        at io.netty.handler.codec.ByteToMessageDecoder.inboundBufferUpdated(ByteToMessageDecoder.java:43)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.thruput.netty.ProtoNegoHandler.inboundBufferUpdated(ProtoNegoHandler.scala:92)
        at io.netty.channel.ChannelInboundByteHandlerAdapter.inboundBufferUpdated(ChannelInboundByteHandlerAdapter.java:44)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.handler.timeout.IdleStateHandler.inboundBufferUpdated(IdleStateHandler.java:273)
        at io.netty.channel.DefaultChannelHandlerContext$5.run(DefaultChannelHandlerContext.java:119)
        at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141)
        at io.netty.channel.DefaultChannelHandlerContext.fireInboundBufferUpdated(DefaultChannelHandlerContext.java:695)
        at io.netty.channel.DefaultChannelPipeline.fireInboundBufferUpdated(DefaultChannelPipeline.java:1068)
        at io.netty.channel.socket.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:91)
        at io.netty.channel.socket.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:274)
        at io.netty.channel.socket.nio.NioEventLoop.run(NioEventLoop.java:211)
        at io.netty.channel.SingleThreadEventExecutor$1.run(SingleThreadEventExecutor.java:80)
        at java.lang.Thread.run(Unknown Source)
`
``

absolutely no idea whats going wrong here.
```

**Comment by RAMYAREDDYKETHIRI** [comment]
today we have seen this issue again .

 not a WebSocket request: missing key

**Comment by Scottmitch** [comment]
@RAMYAREDDYKETHIRI - what version of netty, and can you include a new stack trace?

**Comment by RAMYAREDDYKETHIRI** [comment]
We are using 4.0.26.Final , we will be upgrading very soon but version not yet finalized. 

Actually as of now we dont have stacktrace as it happened in PRODUCTION and we dont have stacktrace enabled. We have seen this error for 5 connections only.

**Comment by Scottmitch** [comment]
Just to clarify the first exception originally reported in this issue (`not a WebSocket handshake request: missing upgrade`) has been superseded by https://github.com/netty/netty/issues/4754.

@RAMYAREDDYKETHIRI - I would need to consult the RFC to understand if what Netty is doing is correct. However if your case is the same as the second exception reported in this issue it is because the `sec-websocket-key` header is not found (see [WebSocketServerHandshaker13](https://github.com/netty/netty/blob/4.1/codec-http/src/main/java/io/netty/handler/codec/http/websocketx/WebSocketServerHandshaker13.java#L129)).

**Comment by yushaohang** [comment]
@Scottmitch I know the reason is that the program can't find sec-wbesockt-key, but I have no idea why it can't be found. I guess that's probably why HTTP headers are too large

**Comment by wushuang122** [comment]
hello, Have you solved this issue? I met this issue recently.@yushaohang

**Comment by wushuang122** [comment]
And the netty version is 4.1.65.Final.@yushaohang
