### ISSUE TITLE
SslHandler fails io.netty.util.internal.OutOfDirectMemoryError when used with OpenSSL

### ISSUE THREAD

**Issue by floragunncom** [netty/netty#6572]
### Expected behavior
No errors when run netty with SslHandler+OpenSSL and sample data size of 20 mb.

### Actual behavior
OpenSSL fails with "io.netty.util.internal.OutOfDirectMemoryError", see https://gist.github.com/floragunncom/c9e46f1e80c047d093995979c8b0fcbc
It works with reduced amount data (on my machine it seems failing above 8 or 9 mb) 
Java SSL works in every case

### Steps to reproduce
Run the provided code:
`java -Xmx4g -jar  -Dopenssl target/netty-sslslow-1.0-jar-with-dependencies.jar`

Running the tests with fewer data (for example with 5mb instead of 20mb) works:
`java -Xmx4g -jar  -Ddata=5 -Dopenssl target/netty-sslslow-1.0-jar-with-dependencies.jar`

### Minimal yet complete reproducer code (or URL to code)
https://github.com/floragunncom/netty-memleak/tree/bigsslslow (see README)
https://github.com/floragunncom/netty-memleak/releases/tag/slow1

### Netty version
4.1.9.Final
tcnative 2.0.0.Final

### JVM version (e.g. `java -version`)
Java Version: 1.8.0_102 Oracle Corporation
JVM Impl.: 25.102-b14 Oracle Corporation Java HotSpot(TM) 64-Bit Server VM

### OS version (e.g. `uname -a`)
Mac OS X x86_64 10.10.5

This issue is related to https://github.com/netty/netty/issues/6571

**Comment by normanmaurer** [comment]
@floragunncom please share the full stacktrace

**Comment by floragunncom** [comment]
(see also link mentioned above)

<pre>
Your session is protected by TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 cipher suite.
Peer certificates length: 1
20:56:25.495 [nioEventLoopGroup-4-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0xd1f0a988, L:/127.0.0.1:8992 - R:/127.0.0.1:65131] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
20:56:25.496 [nioEventLoopGroup-5-1] DEBUG io.netty.handler.ssl.SslHandler - [id: 0x73ce5038, L:/127.0.0.1:65131 - R:/127.0.0.1:8992] HANDSHAKEN: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
io.netty.handler.codec.DecoderException: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 17485594 byte(s) of direct memory (used: 3814432244, max: 3817865216)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 17485594 byte(s) of direct memory (used: 3814432244, max: 3817865216)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:585)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:539)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:760)
	at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:750)
	at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:260)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:231)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:320)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
	at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1684)
	at io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:1695)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:652)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:627)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1046)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 16 more
Clienthandler context closedException in thread "Thread-1"
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 17485594 byte(s) of direct memory (used: 3814432244, max: 3817865216)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:585)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:539)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:760)
	at io.netty.buffer.PoolArena$DirectArena.newUnpooledChunk(PoolArena.java:750)
	at io.netty.buffer.PoolArena.allocateHuge(PoolArena.java:260)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:231)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:320)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
	at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1684)
	at io.netty.handler.ssl.SslHandler.allocateOutNetBuf(SslHandler.java:1695)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:652)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1229)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1041)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
</pre>

**Comment by normanmaurer** [comment]
@floragunncom I think this is expected as you write faster then the remote peer can read.

You should use `sync()` here https://github.com/floragunncom/netty-memleak/blob/bigsslslow/src/main/java/io/netty/example/securechat/SecureChatClient.java#L76 . Remember all writes are non-blocking. That said we should try to no allocate to big buffers in `SslHandler` to make allocating more efficient when the `PooledByteBufAllocator` is used.

See https://github.com/netty/netty/pull/6569

**Comment by floragunncom** [comment]
But why is it working with Java SSL and only failing with OpenSSL?

**Comment by floragunncom** [comment]
I also tried with `.sync()` but same exception. Also changing `ChannelOption.ALLOCATOR` to `UnpooledByteBufAllocator` does not help.

**Comment by trustin** [comment]
Probably a duplicate of #6564

**Comment by floragunncom** [comment]
I can confirm that this issue is fixed in current 4.1 branch, hopefully the fix will be shipped with 4.1.10

**Comment by normanmaurer** [comment]
Yes it will
