### ISSUE TITLE
4.1.9 breaks epoll selector rebuild

### ISSUE THREAD

**Issue by nhw76** [netty/netty#6607]
The following commit appears to break the epoll selector rebuild logic in rebuildSelector():

https://github.com/netty/netty/commit/795f318c3c11ec0520e7acd963ad4b310c287c20

If the logic is fired by an excessive number of premature returns, you will hit an exception like this:

```
java.lang.ClassCastException: io.netty.channel.nio.SelectedSelectionKeySetSelector cannot be cast to java.nio.channels.spi.AbstractSelector
        at java.nio.channels.spi.AbstractSelectableChannel.register(AbstractSelectableChannel.java:212)
        at io.netty.channel.nio.NioEventLoop.rebuildSelector0(NioEventLoop.java:347)
        at io.netty.channel.nio.NioEventLoop.rebuildSelector(NioEventLoop.java:318)
        at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:769)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
```

Looks like a case of replacing the selector member with the unwrappedSelector() method may have been missed?

**Comment by Scottmitch** [comment]
see #6608

**Comment by Scottmitch** [comment]
please re-open if PR #6608 didn't fix the issue

**Comment by md-5** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-3418
User is suggesting this issue is there in 4.1.13

**Comment by normanmaurer** [comment]
Let me check

**Comment by normanmaurer** [comment]
@md-5 it is fixed in 4.1.13 and to prove this I added a unit-test. Please check:
https://github.com/netty/netty/pull/6971

**Comment by md-5** [comment]
Hmm thanks for looking, this is strange.
It is an isolated report so far, I can only think maybe the user ended up with a different Netty version than the one we bundled.

**Comment by md-5** [comment]
Apologies @normanmaurer , looks like a packaging error on our behalf caused the incorrect version to be used.

Thanks for looking anyway

**Comment by normanmaurer** [comment]
No worries... more unit tests FTW
