### ISSUE TITLE
Netty and Java 9 builds

### ISSUE THREAD

**Issue by doom369** [netty/netty#6679]
Hello everybody. 

I saw that you already did some preparations for Java 9, that will be released in 3 months.
So my question is - do you have any plans for building Netty with Java 9 and releasing it to maven central? 

Or for now recommended way is to use SNAPSHOTs from your CI? I'm asking cause wasn't able to use  Netty from maven central with Java 9.

**Comment by normanmaurer** [comment]
@doom369 there are no plans... Why you could not use netty with Java9 ?

**Comment by doom369** [comment]
@normanmaurer 

```
017-04-28 08:40:54.202 DEBUG- Failed to generate a self-signed X.509 certificate using sun.security.x509:
java.lang.IllegalAccessError: class io.netty.handler.ssl.util.OpenJdkSelfSignedCertGenerator (in unnamed module @0x258d79be) cannot access class sun.security.x509.X509CertInfo (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x258d79be
        at io.netty.handler.ssl.util.OpenJdkSelfSignedCertGenerator.generate(OpenJdkSelfSignedCertGenerator.java:50) ~[server-0.24.1.jar:?]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:149) ~[server-0.24.1.jar:?]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:110) ~[server-0.24.1.jar:?]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:88) ~[server-0.24.1.jar:?]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:79) ~[server-0.24.1.jar:?]
        at cc.blynk.utils.SslUtil.build(SslUtil.java:76) ~[server-0.24.1.jar:?]
        at cc.blynk.utils.SslUtil.initSslContext(SslUtil.java:65) ~[server-0.24.1.jar:?]
        at cc.blynk.server.hardware.HardwareSSLServer.<init>(HardwareSSLServer.java:36) ~[server-0.24.1.jar:?]
        at cc.blynk.server.launcher.ServerLauncher.start(ServerLauncher.java:78) ~[server-0.24.1.jar:?]
        at cc.blynk.server.launcher.ServerLauncher.main(ServerLauncher.java:70) ~[server-0.24.1.jar:?]
2017-04-28 08:40:54.209 DEBUG- Failed to generate a self-signed X.509 certificate using Bouncy Castle:
java.lang.NoClassDefFoundError: org/bouncycastle/cert/X509v3CertificateBuilder
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:154) ~[server-0.24.1.jar:?]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:110) ~[server-0.24.1.jar:?]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:88) ~[server-0.24.1.jar:?]
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:79) ~[server-0.24.1.jar:?]
        at cc.blynk.utils.SslUtil.build(SslUtil.java:76) ~[server-0.24.1.jar:?]
        at cc.blynk.utils.SslUtil.initSslContext(SslUtil.java:65) ~[server-0.24.1.jar:?]
        at cc.blynk.server.hardware.HardwareSSLServer.<init>(HardwareSSLServer.java:36) ~[server-0.24.1.jar:?]
        at cc.blynk.server.launcher.ServerLauncher.start(ServerLauncher.java:78) ~[server-0.24.1.jar:?]
        at cc.blynk.server.launcher.ServerLauncher.main(ServerLauncher.java:70) ~[server-0.24.1.jar:?]
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.cert.X509v3CertificateBuilder
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:533) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:186) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:476) ~[?:?]
        ... 9 more

```

**Comment by normanmaurer** [comment]
Yeah that's because you use SelfSignedCertificate which used Java internal apis. Just not use it and you are ok

**Comment by slandelle** [comment]
or provide BouncyCastle, right?

**Comment by doom369** [comment]
Mmm. Sure, I can rewrite this. However, it doesn't seem like correct way of solving this. Shouldn't netty just include correct modules in order to make it work?

I also see other issues, however, they not critical. Is that planned to be fixed?

```
2017-04-28 08:40:51.806 DEBUG- direct buffer constructor: unavailable
java.lang.reflect.InaccessibleObjectException: Unable to make private java.nio.DirectByteBuffer(long,int) accessible: module java.base does not "opens java.nio" to unnamed module @258d79be
```

```
2017-04-28 08:40:51.817 DEBUG- java.nio.Bits.unaligned: unavailable true
java.lang.reflect.InaccessibleObjectException: Unable to make static boolean java.nio.Bits.unaligned() accessible: module java.base does not "opens java.nio" to unnamed module @258d79be
```

```
2017-04-28 08:40:51.818 DEBUG- java.nio.ByteBuffer.cleaner(): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.Cleaner0 cannot access class jdk.internal.ref.Cleaner (in module java.base) because module java.base does not export jdk.internal.ref to unnamed module @258d79be
```

**Comment by jyemin** [comment]
As the maintainer of a widely-used [library](https://github.com/mongodb/mongo-java-driver) that has an optional dependency on Netty, it would be helpful if a Netty release was published that defines the module names that will be used by Netty in Java 9.  That would allow downstream libraries to create their own modules that reliably depend on Netty modules.

See https://www.slf4j.org/faq.html#changesInVersion18 as an example of a widely used library that has committed to specific module names.

**Comment by alek-sys** [comment]
Another issue is that `netty-transport-native-epoll` (and any other native transport) cannot be added to the module path as an *automatic module*. This is because generated module name includes `native` which is a Java keyword and cannot be used as a module name.

**Comment by ohumbel** [comment]
If I run:
`jdeps --jdk-internals -cp ./netty-handler-4.1.21.Final.jar`, I get a bunch of `sun.security.*` related warnings:

```
netty-handler-4.1.21.Final.jar -> java.base
io.netty.handler.ssl.util.OpenJdkSelfSignedCertGenerator
    -> sun.security.util.ObjectIdentifier                 JDK internal API (java.base)
    -> sun.security.x509.AlgorithmId                      JDK internal API (java.base)
    -> sun.security.x509.CertificateAlgorithmId           JDK internal API (java.base)
    -> sun.security.x509.CertificateIssuerName            JDK internal API (java.base)
    -> sun.security.x509.CertificateSerialNumber          JDK internal API (java.base)
    -> sun.security.x509.CertificateSubjectName           JDK internal API (java.base)
    -> sun.security.x509.CertificateValidity              JDK internal API (java.base)
    -> sun.security.x509.CertificateVersion               JDK internal API (java.base)
    -> sun.security.x509.CertificateX509Key               JDK internal API (java.base)
    -> sun.security.x509.X500Name                         JDK internal API (java.base)
    -> sun.security.x509.X509CertImpl                     JDK internal API (java.base)
    -> sun.security.x509.X509CertInfo                     JDK internal API (java.base)

Warning: JDK internal APIs are unsupported and private to JDK implementation that are
subject to be removed or changed incompatibly and could break your application.
Please modify your code to eliminate dependence on any JDK internal APIs.
For the most recent update on JDK internal API replacements, please check:
https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

JDK Internal API                         Suggested Replacement
----------------                         ---------------------
sun.security.x509.X500Name               Use javax.security.auth.x500.X500Principal @since 1.4
```

So this is - IMHO - not only a question what your users do, but also a question what you provide.
The last line suggests that there are replacements since JDK 1.4 (but I am not a security expert).

Please let me know how you plan to deal with this.

**Comment by normanmaurer** [comment]
@ohumbel this is just an utility that allows to create a self-signed cert and is normally not used by end-users. I think this is just fine ?

**Comment by ohumbel** [comment]
@normanmaurer Hi Norman, many thanks for the speedy answer!
 
I am getting rid of such dependencies as much as I can. Currently I try to prevent `jython` from illegal accesses. On this way I also ran `jdeps` on `jython-standalone.jar`, which bundles (using `jarjar`) your `netty-handler`. So the netty warnings appear there. 

If you were able to replace the `sun.security.*` stuff, this would be great. Otherwise it is good to know that it is just a utility, and I could probably safely remove this class from `jython`. Thanks! Oti.

**Comment by normanmaurer** [comment]
@ohumbel We could try to replace these but I am not sure if there a any good public replacements. Its not a high priority imho. That said we love PRs if you want to work on it :)

**Comment by ohumbel** [comment]
Fair enough 😄 - no promises though...

My thoughts are that people will run `jdeps` against all their `.jar` files as soon as they consider moving to Java `>= 9`. That is the reason I'd like to clean up `jython` first.

**Comment by vietj** [comment]
any plans to address the use of `OpenJdkSelfSignedCertGenerator` ?

**Comment by normanmaurer** [comment]
@vietj what you mean ? Just put `BouncyCastle` on the classpath and call it a day ?

**Comment by vietj** [comment]
that adds a new dependency where before we didn't need one

**Comment by normanmaurer** [comment]
@vietj sure but a self signed cert should only be used in tests anyway so I am not sure why this is a problem

**Comment by vietj** [comment]
yes that's a fair point

**Comment by chrisvest** [comment]
I think we're past the original issue, and new Java 9+ problems that pop up should be reported in separate issues. How about we close this one, @doom369 ?

**Comment by doom369** [comment]
@chrisvest yes. all problems were solved.
