### ISSUE TITLE
java.io.IOException: Connection timed out

### ISSUE THREAD

**Issue by cz279708573** [netty/netty#6693]
I have about 40 applications , each connected to others with long connection.
just like: application A as a client connect to applicationB and application B as a client connect to applicaitionA.so each application may have 39 clients and 1 server.
After the connections build succeede and worked well,  several hours later or more (this happens randomly) 
" java.io.IOException: Connection timed out " occurred , is that meaning there is something wrong with the network absolutely ? 
or  i create to many EventLoopGroup ? because i create myclient use this code and every application have about 39client.  Each client (connect to different server) has a bootstrap and a group.
`
Bootstrap b = new Bootstrap();
b.group(new NioEventLoopGroup()).connect(host,port);
`

when the client cause  java.io.IOException: Connection timed out
the server also has exception java.io.IOException: Connection reset by peer

java.io.IOException: Connection timed out
	at sun.nio.ch.FileDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:21)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:198)
	at sun.nio.ch.IOUtil.read(IOUtil.java:166)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:245)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:447)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:241)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	at java.lang.Thread.run(Thread.java:662)

### Netty version
4.0.27.final
Linux\Weblogic

**Comment by jagansankara** [comment]
Any solution found for above issue? We're also facing same issue. Since timeout is happening randomly, we couldn't recreate it and once occurred, app goes to hung state & stop processing request. @cz279708573
