### ISSUE TITLE
HttpServerKeepAliveHandler throws java.lang.IllegalStateException: void future

### ISSUE THREAD

**Issue by doom369** [netty/netty#6698]
### Expected behavior

No error when I do `ctx.writeAndFlush(msg, ctx.voidPromise());` where msg is with header "Connection:close".

### Actual behavior

HttpServerKeepAliveHandler throws IllegalStateException exception.

### Steps to reproduce

Use `ctx.writeAndFlush(msg, ctx.voidPromise());` where msg is `DefaultFullHttpResponse` with header "Connection:close".

```
java.lang.IllegalStateException: void future
	at io.netty.channel.VoidChannelPromise.fail(VoidChannelPromise.java:178) ~[netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:44) ~[netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:24) ~[netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.handler.codec.http.HttpServerKeepAliveHandler.write(HttpServerKeepAliveHandler.java:85) ~[netty-codec-http-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:304) [netty-handler-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:137) [netty-handler-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) [netty-transport-4.1.10.Final.jar:4.1.10.Final]
```

### Netty version

4.1.10

**Comment by normanmaurer** [comment]
Fixed by #6699
