### ISSUE TITLE
SNIServerName class not found when creating SslHandler after upgrading to Netty 4.1.10/netty-tcnative 2.0.1 under Java 7

### ISSUE THREAD

**Issue by jchambers** [netty/netty#6700]
Using Java 7, Netty 4.1.9, and netty-tcnative 2.0.0, the following code works just fine:

```java
import io.netty.buffer.PooledByteBufAllocator;
import io.netty.handler.ssl.*;

public class NettySslHandlerExample {

    public static void main(final String[] args) throws Exception {

        final SslContext sslContext = SslContextBuilder.forClient()
                .sslProvider(SslProvider.OPENSSL)
                .build();

        sslContext.newHandler(PooledByteBufAllocator.DEFAULT);
    }
}
```

After upgrading to Netty 4.1.10/netty-tcnative 2.0.1, though, it fails under Java 7 with the following stack trace:

```
Exception in thread "main" java.lang.NoClassDefFoundError: javax/net/ssl/SNIServerName
	at io.netty.handler.ssl.OpenSslContext.newEngine0(OpenSslContext.java:49)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newEngine(ReferenceCountedOpenSslContext.java:409)
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.newEngine(ReferenceCountedOpenSslContext.java:423)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:903)
	at NettySslHandlerExample.main(NettySslHandlerExample.java:12)
Caused by: java.lang.ClassNotFoundException: javax.net.ssl.SNIServerName
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 5 more
```

Everything is fine with Netty 4.1.10/netty-tcnative 2.0.1 under Java 8, or when using `SslProvider.JDK` under Java 7.

**Comment by normanmaurer** [comment]
@jchambers will check ... thanks!

**Comment by normanmaurer** [comment]
Please check https://github.com/netty/netty/pull/6703
