### ISSUE TITLE
Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel

### ISSUE THREAD

**Issue by fangqiao** [netty/netty#6722]
Hi, 

I am using Netty as basis of a REST service in production, which talks to Elasticsearch backend.

My whole environment works very well with ES5.3. Now I am trying to upgrade ES to ES5.4.

When I try to start the REST service, the messages below are shown:

io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:40)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:321)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:283)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:279)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:254)
	at cn.shujubiji.bj.BjServiceServer$.main(BjServiceServer.scala:157)
	at cn.shujubiji.bj.BjServiceServer.main(BjServiceServer.scala)
Caused by: java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:107)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:79)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:84)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:86)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:72)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:38)
	... 6 more

My Netty related jars are:

lib5.4.0/netty-3.10.6.Final.jar        lib5.4.0/netty-codec-4.1.9.Final.jar       lib5.4.0/netty-handler-4.1.9.Final.jar     lib5.4.0/netty-transport-4.1.9.Final.jar
lib5.4.0/netty-all-4.1.9.Final.jar     lib5.4.0/netty-codec-http-4.1.9.Final.jar  lib5.4.0/netty-reactive-streams-1.0.8.jar  lib5.4.0/netty-transport-native-epoll-4.0.45.Final-linux-x86_64.jar
lib5.4.0/netty-buffer-4.1.9.Final.jar  lib5.4.0/netty-common-4.1.9.Final.jar      lib5.4.0/netty-resolver-4.1.9.Final.jar

Any conflicts in there?

Many thanks in advance.

**Comment by normanmaurer** [comment]
@fangqiao yes as you can see you have 4.0 and 4.1 in your dependencies. You need to big one of these.

**Comment by fangqiao** [comment]
Do you mean this jar netty-transport-native-epoll-4.0.45.Final-linux-x86_64.jar? It is provided by Elasticsearch. I did a search and found out this page : http://netty.io/wiki/native-transports.html#wiki-h2-2 about "Using the native transport". Do you mean I should compile against 4.1.9? 

I will give it a try. Thanks.

**Comment by normanmaurer** [comment]
@fangqiao yes ... you will need to use the same version and not mix stuff up
