### ISSUE TITLE
Incorrect UnixResolverDnsServerAddressStreamProvider

### ISSUE THREAD

**Issue by trustin** [netty/netty#6736]
### Minimal yet complete reproducer code (or URL to code)

```java
import static org.junit.Assert.assertNotNull;

import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider;

public class ResolverTest {

    @Rule
    public final TemporaryFolder folder = new TemporaryFolder();

    @Test
    public void test() throws Exception {
        File f = folder.newFile();
        try (OutputStream out = new FileOutputStream(f)) {
            out.write(("domain linecorp.local\n" +
                       "nameserver 1.2.3.4\n" +
                       "nameserver 5.6.7.8\n").getBytes(StandardCharsets.UTF_8));
        }
        UnixResolverDnsServerAddressStreamProvider p =
                new UnixResolverDnsServerAddressStreamProvider(f, null);

        assertNotNull(p.nameServerAddressStream("somehost"));
    }
}
```

### Expected behavior

`UnixResolverDnsServerAddressStreamProvider.nameServerAddressStream()` should not return `null`.

The expected behavior of `DnsNameResolver` is to try `somehost.` and then `somehost.linecorp.local.`

### Actual behavior

Attempting to resolve a host will trigger a NPE:

```
java.lang.NullPointerException: nameServerAddrs
 at io.netty.util.internal.ObjectUtil.checkNotNull(ObjectUtil.java:31)
 at io.netty.resolver.dns.DnsNameResolverContext.<init>(DnsNameResolverContext.java:120)
 at io.netty.resolver.dns.DnsNameResolver$SingleResolverContext.<init>(DnsNameResolver.java:659)
 at io.netty.resolver.dns.DnsNameResolver.doResolveUncached(DnsNameResolver.java:653)
 at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:590)
 at io.netty.resolver.dns.DnsNameResolver.doResolve(DnsNameResolver.java:523)
 at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:63)
 at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:100)
 at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:66)
 at io.netty.resolver.dns.InflightNameResolver.resolve(InflightNameResolver.java:51)
 at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:57)
 at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:32)
 at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:108)
 at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:208)
 at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:170)
 at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
```
### Netty version

4.1.11

### Workaround

Use `DefaultDnsServerAddressStreamProvider.INSTANCE` instead of `DnsServerAddressStreamProviders.platformDefault()`.

**Comment by normanmaurer** [comment]
@trustin can you submit a pr with a fix ?

**Comment by trustin** [comment]
Can't promise it at the moment because of busyness... 😢

**Comment by Scottmitch** [comment]
> The expected behavior of DnsNameResolver is to try somehost and then somehost.linecorp.local.

The behavior of modifying the hostname should be provided at a higher layer (e.g. [DnsNameResolverContext.java](https://github.com/netty/netty/blob/4.1/resolver-dns/src/main/java/io/netty/resolver/dns/DnsNameResolverContext.java#L141)). However `UnixResolverDnsServerAddressStreamProvider` default value when no match was found needs some work.

**Comment by Scottmitch** [comment]
See PR https://github.com/netty/netty/pull/6748
