### ISSUE TITLE
SslHandlerTest#testCompositeBufSizeEstimationGuaranteesSynchronousWrite failure

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#6755]
Encountered while building PR https://github.com/netty/netty/pull/6493 on CI servers.

https://garage.netty.io/teamcity/viewLog.html?buildId=20267&buildTypeId=pulls_netty&tab=buildLog#_focus=40344

```
[19:57:50][io.netty:netty-handler] testCompositeBufSizeEstimationGuaranteesSynchronousWrite(io.netty.handler.ssl.SslHandlerTest)  Time elapsed: 122.061 sec  <<< ERROR!
[19:57:50][io.netty:netty-handler] java.util.concurrent.ExecutionException: java.lang.IllegalStateException: client closed
[19:57:50][io.netty:netty-handler] 	at io.netty.handler.ssl.SslHandlerTest.compositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:702)
[19:57:50][io.netty:netty-handler] 	at io.netty.handler.ssl.SslHandlerTest.testCompositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:585)
[19:57:50][io.netty:netty-handler] Caused by: java.lang.IllegalStateException: client closed
[19:57:50][io.netty:netty-handler] 
[19:57:50][io.netty:netty-handler] Running io.netty.handler.ssl.SniHandlerTest
[19:57:50][io.netty:netty-handler] 15:56:47.281 [threadDeathWatcher-5-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 5 thread-local buffer(s) from thread: threadDeathWatcher-5-1
[19:57:51][io.netty:netty-handler] io.netty.handler.ssl.SslHandlerTest
[19:57:51][io.netty.handler.ssl.SslHandlerTest] testCompositeBufSizeEstimationGuaranteesSynchronousWrite
[19:57:51][testCompositeBufSizeEstimationGuaranteesSynchronousWrite] java.util.concurrent.ExecutionException: java.lang.IllegalStateException: client closed
[19:57:51]
[testCompositeBufSizeEstimationGuaranteesSynchronousWrite] java.util.concurrent.ExecutionException: java.lang.IllegalStateException: client closed
	at io.netty.handler.ssl.SslHandlerTest.compositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:702)
	at io.netty.handler.ssl.SslHandlerTest.testCompositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:585)
Caused by: java.lang.IllegalStateException: client closed
```

**Comment by Scottmitch** [comment]
Observed again https://garage.netty.io/teamcity/viewLog.html?buildId=23392&buildTypeId=pulls_netty&guest=1

**Comment by Scottmitch** [comment]
Observed again https://garage.netty.io/teamcity/viewLog.html?buildId=23623&buildTypeId=pulls_netty&guest=1

```
[15:59:42][io.netty:netty-handler] Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 235.179 sec <<< FAILURE! - in io.netty.handler.ssl.SslHandlerTest
[15:59:42][io.netty:netty-handler] testCompositeBufSizeEstimationGuaranteesSynchronousWrite(io.netty.handler.ssl.SslHandlerTest)  Time elapsed: 178.755 sec  <<< ERROR!
[15:59:42][io.netty:netty-handler] java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: handshake timed out
[15:59:42][io.netty:netty-handler] 	at io.netty.handler.ssl.SslHandlerTest.compositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:825)
[15:59:42][io.netty:netty-handler] 	at io.netty.handler.ssl.SslHandlerTest.testCompositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:670)
[15:59:42][io.netty:netty-handler] Caused by: javax.net.ssl.SSLException: handshake timed out
[15:59:42][io.netty:netty-handler] 
[15:59:42][io.netty:netty-handler] Running io.netty.handler.ssl.SslContextBuilderTest
[15:59:42][io.netty:netty-handler] io.netty.handler.ssl.SslHandlerTest
[15:59:42][io.netty.handler.ssl.SslHandlerTest] testCompositeBufSizeEstimationGuaranteesSynchronousWrite
[15:59:42][testCompositeBufSizeEstimationGuaranteesSynchronousWrite] java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: handshake timed out
[15:59:42]
[testCompositeBufSizeEstimationGuaranteesSynchronousWrite] java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: handshake timed out
	at io.netty.handler.ssl.SslHandlerTest.compositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:825)
	at io.netty.handler.ssl.SslHandlerTest.testCompositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:670)
Caused by: javax.net.ssl.SSLException: handshake timed out
```

**Comment by Scottmitch** [comment]
Even more visibility: https://github.com/netty/netty/pull/7136

**Comment by normanmaurer** [comment]
Didn't see this for a long time... Let's close it
