### ISSUE TITLE
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)

### ISSUE THREAD

**Issue by CodingMartin** [netty/netty#6767]
###                                                                             java.net.SocketException: recvfrom failed: ### 
 ECONNRESET (Connection reset by peer)
                                                                                 at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:634)
                                                                                 at libcore.io.IoBridge.recvfrom(IoBridge.java:608)
                                                                                 at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342)
                                                                                 at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304)
                                                                                 at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:289)
                                                                                 at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
                                                                                 at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
                                                                                 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:524)
                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:478)
                                                                                 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
                                                                                 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
                                                                                 at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
                                                                                 at java.lang.Thread.run(Thread.java:818)
###                                                                              Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
                                                                                 at libcore.io.Posix.recvfromBytes(Native Method)
                                                                                 at libcore.io.Posix.recvfrom(Posix.java:177)
                                                                                 at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:245)
                                                                                 at libcore.io.IoBridge.recvfrom(IoBridge.java:605)
                                                                                 at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342) 
                                                                                 at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304) 
                                                                                 at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:289) 
                                                                                 at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100) 
                                                                                 at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372) 
                                                                                 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) 
                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624) 
                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:524) 
                                                                                 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:478) 
                                                                                 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438) 
                                                                                 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) 
                                                                                 at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144) 
                                                                                 at java.lang.Thread.run(Thread.java:818)

**Comment by Scottmitch** [comment]
Can you describe your issue, and the expected behavior. Connection reset may occur and even be expected in various scenarios.

**Comment by normanmaurer** [comment]
Closing as no feedback was provided for a year

**Comment by bingo-asif** [comment]
I have same issue i am trying to add custom header as an example below, it doent work

`.addInterceptor(
                    { chain ->
                        val request = chain.request().newBuilder()
                                //.url(SERVER_URL)
                                .header("Accept", "application/json")
                                //.header("Content-Type", "application/json")
                                .addHeader("x-commercial-app-date-on-tablet", AppUtils.getTodayDateTime())
                                .addHeader("x-commercial-app-tablet-name", "")
                                .addHeader("x-commercial-app-driver-id", PrefManager.getDriverId().toString())
                                .addHeader("x-commercial-app-driver-name", PrefManager.getUserName())
                                .addHeader("x-commercial-app-rego-on-tablet", PrefManager.getRego())
                                .addHeader("imei-number", PrefManager.getRego())
                                .addHeader("x-commercial-app-app-version", "")
                                .build()
                        chain.proceed(request)
                    }
            )`
