### ISSUE TITLE
java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)

### ISSUE THREAD

**Issue by zhou0061223** [netty/netty#6805]
FATAL EXCEPTION: nioEventLoopGroup-11-1
                                                                  Process: com.yuncun.smart, PID: 13783
                                                                  java.net.SocketException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                                      at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
                                                                      at libcore.io.IoBridge.recvfrom(IoBridge.java:564)
                                                                      at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342)
                                                                      at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304)
                                                                      at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:256)
                                                                      at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881)
                                                                      at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225)
                                                                      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119)
                                                                      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
                                                                      at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430)
                                                                      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384)
                                                                      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
                                                                      at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
                                                                      at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
                                                                      at java.lang.Thread.run(Thread.java:818)
                                                                   Caused by: android.system.ErrnoException: recvfrom failed: ETIMEDOUT (Connection timed out)
                                                                      at libcore.io.Posix.recvfromBytes(Native Method)
                                                                      at libcore.io.Posix.recvfrom(Posix.java:181)
                                                                      at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:245)
                                                                      at libcore.io.IoBridge.recvfrom(IoBridge.java:561)
                                                                      at java.nio.SocketChannelImpl.readImpl(SocketChannelImpl.java:342) 
                                                                      at java.nio.SocketChannelImpl.read(SocketChannelImpl.java:304) 
                                                                      at io.netty.buffer.UnpooledHeapByteBuf.setBytes(UnpooledHeapByteBuf.java:256) 
                                                                      at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:881) 
                                                                      at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:225) 
                                                                      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:119) 
                                                                      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) 
                                                                      at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430) 
                                                                      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384) 
                                                                      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) 
                                                                      at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) 
                                                                      at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) 
                                                                      at java.lang.Thread.run(Thread.java:818) 

version 4.024 ,work on android,close  wifi and open wifi,show reconnect sucess ,Channel isActive=ture,but
it does not working

**Comment by zhou0061223** [comment]
I try call the  Channel.close()  and then reconnect  sucess and it working normal

**Comment by Scottmitch** [comment]
Please update to the latest version of Netty, and provide a minimal yet complete way for us to reproduce the issue.

**Comment by normanmaurer** [comment]
Please reopen if you still think there an issue and attach more details as @Scottmitch requested
