### ISSUE TITLE
Failed to use EpollEventLoopGroup in Alpine

### ISSUE THREAD

**Issue by asafm** [netty/netty#6841]
### Expected behavior
Can create a Netty based server using EpollEventLoopGroup in Alpine

### Actual behavior
Exception in debug:
```
17/06/12 07:49:50 DEBUG i.n.u.i.NativeLibraryLoader: -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
17/06/12 07:49:50 DEBUG i.n.u.i.NativeLibraryLoader: -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
17/06/12 07:49:50 DEBUG i.n.u.i.NativeLibraryLoader: Unable to load the library '/tmp/libnetty-transport-native-epoll46794586764
45765506.so', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: /tmp/libnetty-transport-native-epoll4679458676445765506.so: Error relocating /tmp/libnetty-trans
port-native-epoll4679458676445765506.so: __strndup: symbol not found
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:272)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:264)
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:252)
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:226)
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:269)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:64)
        at io.netty.channel.epoll.IovArray.<clinit>(IovArray.java:57)
        at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:54)
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:117)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:50)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:93)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:80)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:61)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:45)
        ...
```

### Steps to reproduce
This line of code fails ```new EpollEventLoopGroup(1)```

### Minimal yet complete reproducer code (or URL to code)
```new EpollEventLoopGroup(1)```

### Netty version
4.0.47.Final

Gradle dependencies used:
```
    compile 'io.netty:netty-all:4.0.47.Final'
    compile 'io.netty:netty-transport-native-epoll:4.0.47.Final:linux-x86_64'
```

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (IcedTea 3.3.0) (Alpine 8.121.13-r0)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)
Linux b36a0939a7e8 4.9.27-moby #1 SMP Thu May 11 04:01:18 UTC 2017 x86_64 Linux

Running using Alpine from this docker image: `openjdk:8u121-alpine`

**Comment by normanmaurer** [comment]
@asafm alpine is currently not supported as we depend on glibc here.

**Comment by Scottmitch** [comment]
PRs are welcome if you can make the JNI code more cross platform ... of course it must still work on existing platforms

**Comment by asafm** [comment]
After reading Norman tweets on coding in C and JNI, I'll just switch back
to Ubuntu :)

**Comment by normanmaurer** [comment]
@asafm lol all these fans 😆

**Comment by Scottmitch** [comment]
don't let @normanmaurer scare you ... C/JNI can be "fun" 😉

**Comment by saamalik** [comment]
Not probably _officially_ supported, but you can install the proper _glibc_ in Alpine:
```
curl -sS -L -o /etc/apk/keys/sgerrand.rsa.pub http://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub && curl -sS -L -O http://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.25-r0/glibc-2.25-r0.apk && apk --no-cache add glibc-2.25-r0.apk
```

Tested it with Playframework/Netty and it works good! However, most of us who're using _Alpine_ are doing so in _Docker_ containers (where the docker host VM is Linux--even on a Mac). Turns out that the performance difference between using _native_ and _jdk_ on Linux was very marginally in favor of native; presumambly because on Linux the selectors still use _epoll_. Anyway, I kept the _jdk_ transport, but the instructions are above if anyone wants to use _native_ transport in alpine.

**Comment by saamalik** [comment]
So actually it turns out that _netty_ with the _native_ transport is running perfectly fine in the latest alpine (3.6). This is without installing _glibc_ above and just using the default _musl_ libc. I have to do some more testing, but looks okay.

**Comment by binakot** [comment]
I have the same problem 👍 
Even with alpine 3.6
@saamalik Can you show me your Dockerfile? Or give me some advice hot to fix it? Please...

The main problem:

```
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
```

Should I pass some path to `-Djava.library.path=<...>`? And why? I already added `netty-transport-native-epoll` in my dependencies and built jar artifact with all dependencies inside.

build.gradle:

```
dependencies {
    // ...
    compile "io.netty:netty-all:4.1.15.Final"
    compile "io.netty:netty-transport-native-epoll:4.1.15.Final:linux-x86_64"
    // ...
}
```

Dockerfile:

```
FROM openjdk:8-jdk-alpine
RUN apk --no-cache add nano

EXPOSE 30000-30100

ADD my-app.jar /app.jar

ENV JAVA_OPTS "-Dlog4j.configurationFile=log4j2.xml"
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
```

Logs from container:

```
microservice_1  | 2017-09-04 11:25:35.509 DEBUG [main][io.netty.util.internal.NativeLibraryLoader] Unable to load the library 'netty_transport_native_epoll', trying other loading mechanism.
microservice_1  | java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
microservice_1  |       at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_131]
microservice_1  |       at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_131]
microservice_1  |       at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_131]
microservice_1  |       at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[app.jar:?]
microservice_1  |       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
microservice_1  |       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
microservice_1  |       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
microservice_1  |       at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
microservice_1  |       at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:222) ~[app.jar:?]
microservice_1  |       at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
microservice_1  |       at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:214) ~[app.jar:?]
microservice_1  |       at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:202) [app.jar:?]
microservice_1  |       at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:118) [app.jar:?]
microservice_1  |       at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:199) [app.jar:?]
microservice_1  |       at io.netty.channel.epoll.Native.<clinit>(Native.java:61) [app.jar:?]
microservice_1  |       at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.network.server.TcpServer.<init>(TcpServer.java:60) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.network.protocol.adm.AdmProtocol.initServer(AdmProtocol.java:37) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.network.server.ServerManager.initProtocolServer(ServerManager.java:97) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.network.server.ServerManager.<init>(ServerManager.java:69) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.Context.init(Context.java:46) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.Main.main(Main.java:23) [app.jar:?]
microservice_1  | 2017-09-04 11:25:35.525 DEBUG [main][io.netty.util.internal.NativeLibraryLoader] netty_transport_native_epoll cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /tmp
microservice_1  | java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
microservice_1  |       at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_131]
microservice_1  |       at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_131]
microservice_1  |       at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_131]
microservice_1  |       at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[app.jar:?]
microservice_1  |       at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:209) ~[app.jar:?]
microservice_1  |       at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:118) [app.jar:?]
microservice_1  |       at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:199) [app.jar:?]
microservice_1  |       at io.netty.channel.epoll.Native.<clinit>(Native.java:61) [app.jar:?]
microservice_1  |       at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.network.server.TcpServer.<init>(TcpServer.java:60) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.network.protocol.adm.AdmProtocol.initServer(AdmProtocol.java:37) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.network.server.ServerManager.initProtocolServer(ServerManager.java:97) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.network.server.ServerManager.<init>(ServerManager.java:69) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.Context.init(Context.java:46) [app.jar:?]
microservice_1  |       at com.waliot.deviceserver.Main.main(Main.java:23) [app.jar:?]
```

Also I tried with `ubuntu 16.04` and `alpine with gclib`. Nothing helps. Any suggestions?

**Comment by carlvine500** [comment]
Dockerfile add :

RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
    && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.34-r0/glibc-2.34-r0.apk \
    && apk add glibc-2.34-r0.apk
