### ISSUE TITLE
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe

### ISSUE THREAD

**Issue by ashkanpaya88** [netty/netty#6855]
### Actual behavior: 

```
D 06-06 11:01:33.811 pool-1-thread-2 i.n.u.i.l.InternalLoggerFactory:71 |::] Using SLF4J as the default logging framework
D 06-06 11:01:33.819 pool-1-thread-2 i.n.u.i.PlatformDependent0:76 |::] -Dio.netty.noUnsafe: false
D 06-06 11:01:33.823 pool-1-thread-2 i.n.u.i.PlatformDependent0:71 |::] sun.misc.Unsafe.theUnsafe: available
D 06-06 11:01:33.824 pool-1-thread-2 i.n.u.i.PlatformDependent0:71 |::] sun.misc.Unsafe.copyMemory: available
D 06-06 11:01:33.825 pool-1-thread-2 i.n.u.i.PlatformDependent0:71 |::] java.nio.Buffer.address: available
D 06-06 11:01:33.826 pool-1-thread-2 i.n.u.i.PlatformDependent0:71 |::] direct buffer constructor: available
D 06-06 11:01:33.828 pool-1-thread-2 i.n.u.i.PlatformDependent0:76 |::] java.nio.Bits.unaligned: available, true
D 06-06 11:01:33.834 pool-1-thread-2 i.n.u.i.PlatformDependent0:91 |::] jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:288)
	at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:895)
	at io.netty.util.internal.PlatformDependent.isAndroid0(PlatformDependent.java:919)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:70)
	at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
	at io.netty.util.AttributeKey$1.<init>(AttributeKey.java:27)
	at io.netty.util.AttributeKey.<clinit>(AttributeKey.java:27)
....
	at com.google.inject.internal.cglib.reflect.$FastConstructor.newInstance(FastConstructor.java:40)
	at com.google.inject.internal.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:60)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:85)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:65)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.SingleFieldInjector.inject(SingleFieldInjector.java:53)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:110)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:75)
	at com.google.inject.internal.MembersInjectorImpl$1.call(MembersInjectorImpl.java:73)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:73)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:60)
	at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:944)
....
	at org.junit.rules.RunRules.applyAll(RunRules.java:26)
	at org.junit.rules.RunRules.<init>(RunRules.java:15)
	at org.junit.runners.BlockJUnit4ClassRunner.withTestRules(BlockJUnit4ClassRunner.java:400)
	at org.junit.runners.BlockJUnit4ClassRunner.withRules(BlockJUnit4ClassRunner.java:356)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:278)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at org.apache.maven.surefire.junitcore.pc.InvokerStrategy.schedule(InvokerStrategy.java:54)
	at org.apache.maven.surefire.junitcore.pc.Scheduler.schedule(Scheduler.java:352)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
D 06-06 11:01:33.835 pool-1-thread-2 i.n.u.i.PlatformDependent0:76 |::] java.nio.DirectByteBuffer.<init>(long, int): available
D 06-06 11:01:33.836 pool-1-thread-2 i.n.u.i.PlatformDependent:76 |::] Java version: 8
D 06-06 11:01:33.836 pool-1-thread-2 i.n.u.i.PlatformDependent:76 |::] sun.misc.Unsafe: available
D 06-06 11:01:33.837 pool-1-thread-2 i.n.u.i.PlatformDependent:76 |::] -Dio.netty.tmpdir: /var/folders/nx/jmr5yqhx6ksgz00ftry92g0rqp6l0q/T (java.io.tmpdir)
D 06-06 11:01:33.838 pool-1-thread-2 i.n.u.i.PlatformDependent:76 |::] -Dio.netty.bitMode: 64 (sun.arch.data.model)
D 06-06 11:01:33.840 pool-1-thread-2 i.n.u.i.PlatformDependent:76 |::] -Dio.netty.noPreferDirect: false
D 06-06 11:01:33.841 pool-1-thread-2 i.n.u.i.PlatformDependent:76 |::] -Dio.netty.maxDirectMemory: 954728448 bytes
D 06-06 11:01:33.841 pool-1-thread-2 i.n.u.i.PlatformDependent:76 |::] -Dio.netty.uninitializedArrayAllocationThreshold: -1
D 06-06 11:01:33.842 pool-1-thread-2 i.n.util.internal.CleanerJava6:71 |::] java.nio.ByteBuffer.cleaner(): available
```

### Steps to reproduce

We were using netty 4.0.x branch for long time and once we switch to 4.1.x, this stack trace appeared.

### JVM version (e.g. `java -version`)

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

### OS version (e.g. `uname -a`)

Ubuntu 16.04 and Mac 10.11.4

**Comment by normanmaurer** [comment]
@ashkanpaya88 ah this was fixed recently and is harmless:
https://github.com/netty/netty/commit/0ee49e6d668bd100320003b7d6b287bc289db28f

Upgrade to 4.1.12.Final and you will not see it anymore

**Comment by ashkanpaya88** [comment]
Great, thank you!
