### ISSUE TITLE
Exception occours if client sends reset frame while the server is sending headers

### ISSUE THREAD

**Issue by qwangseu** [netty/netty#6906]
when I use netty http2 to build a server, exception will occour if the client sents a reset frame to the server while the server is sending headers (netty version is 4.1.8.final),
```
io.netty.handler.codec.http2.Http2Exception: Request stream 2414839 is not correct for server connection
   at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
   at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:1095)
   at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:942)
   at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:960)
   at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:868)
   at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:158)
   at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:148)
   at com.c.t.h2c.netty.NettyServerHandler.sendResponseHeaders(NettyServerHandler.java:293)
   at com.c.t.h2c.netty.NettyServerHandler.write(NettyServerHandler.java:253)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
   at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHutor$5.run(SingleThreadEventExecutor.java:858)
   at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
   at java.lang.Thread.run(Thread.java:745)
```

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L156
when the server receives reset frame  it will remove the stream from the streamMap, but  it will create the stream when it writes headers if it finds the stream is null。

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2Connection.java#L687
here the netty will check whether the streamId is even, but the streamId from upstream is always odd.So is there any method to resolve this problem?

**Comment by twjitm** [comment]
so do I,   How  are you to solve it?

**Comment by normanmaurer** [comment]
@ejona86 @nmittler @Scottmitch PTAL...

**Comment by Scottmitch** [comment]
It looks like we are sending GO_AWAY in this scenario ... can you confirm this @qwangseu? If so this is a bug.

**Comment by Zeymo** [comment]
The same to me . I occurs when http2-client send RSTFrame(maybe time-out) as @qwangseu say

I seems http2-server must maintain stream **status** (like `create`,`done`) , when receive  _RSTFrame_ server must change **status** locked to `done` and don't remove from map until server write trailer which alway responsed according to the **status** ,then remove stream .This delete action can and must only can do in server side

**Comment by qwangseu** [comment]
The client sends a request to the server but the server dose not response immediately，so the client sends a reset frame when timeout,  if then the server response the request, it will trigger the exception because the stream has been deleted from the streamMap and the netty will try to create a new stream。
https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2ConnectionEncoder.java#L155

**Comment by Scottmitch** [comment]
@qwangseu - yes I understand the sequence of events ... I was just confirming that the issue is there is a GO_AWAY being sent.

**Comment by qwangseu** [comment]
It seems like that the modification can resolve this problem.
