### ISSUE TITLE
java.lang.IndexOutOfBoundsException:  at org.jboss.netty.buffer.CompositeChannelBuffer.componentId(CompositeChannelBuffer.java:710)

### ISSUE THREAD

**Issue by anton-tsiatsko** [netty/netty#6921]
Hi Guys,
Can you please take a look at the following issue.

Im using Avro with Netty-server  for.  After updating version of avro 1.7.7 to 1.8.2 -> I'm getting error on server-side:

2017-06-28 10:30:00 INFO  NettyServer:171 - [id: 0xd7d41dd9, /10.0.2.15:44260 => /10.0.2.15:65123] OPEN
2017-06-28 10:30:00 INFO  NettyServer:171 - [id: 0xd7d41dd9, /10.0.2.15:44260 => /10.0.2.15:65123] BOUND: /10.0.2.15:65123
2017-06-28 10:30:00 INFO  NettyServer:171 - [id: 0xd7d41dd9, /10.0.2.15:44260 => /10.0.2.15:65123] CONNECTED: /10.0.2.15:44260
2017-06-28 10:30:00 WARN  NettyServer:201 - Unexpected exception from downstream.
java.lang.IndexOutOfBoundsException: Invalid index: 2690, maximum: 3
	at org.jboss.netty.buffer.CompositeChannelBuffer.componentId(CompositeChannelBuffer.java:710)
	at org.jboss.netty.buffer.CompositeChannelBuffer.getBytes(CompositeChannelBuffer.java:259)
	at org.jboss.netty.buffer.AbstractChannelBuffer.readBytes(AbstractChannelBuffer.java:351)
	at org.apache.avro.ipc.NettyTransportCodec$NettyFrameDecoder.decodePackBody(NettyTransportCodec.java:193)
	at org.apache.avro.ipc.NettyTransportCodec$NettyFrameDecoder.decode(NettyTransportCodec.java:144)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:310)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

And error on client-side:
 java.io.IOException: NettyTransceiver closed
	at org.apache.avro.ipc.NettyTransceiver.disconnect(NettyTransceiver.java:375)
	at org.apache.avro.ipc.NettyTransceiver.access$200(NettyTransceiver.java:61)
	at org.apache.avro.ipc.NettyTransceiver$NettyClientAvroHandler.handleUpstream(NettyTransceiver.java:592)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.cleanup(FrameDecoder.java:493)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.channelClosed(FrameDecoder.java:371)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:88)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireChannelClosed(Channels.java:468)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:375)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:93)

Same behavior with dependency : Netty 3.10.6.Final
I can stable reporoduce the issue.

### Actual behavior
Debug variables:

CompositeChannelBuffer(ridx=2690, widx=2690, cap=2690, components=2)
	components	ChannelBuffer[2]  (id=27269)	 [BigEndianHeapChannelBuffer(ridx=0, widx=2040, cap=2040), BigEndianHeapChannelBuffer(ridx=0, widx=650, cap=650)]
	gathering	false	
	indices	(id=27270)	[0, 2040, 2690]
	lastAccessedComponentId	1	
	markedReaderIndex	2686	
	markedWriterIndex	0	
	order	ByteOrder  (id=27125)	BIG_ENDIAN
	readerIndex	2690	
	writerIndex	2690	
	
componentId():
index	2690	
lastComponentId	1	

### Netty version
3.10.6.Final

### JVM version (e.g. `java -version`)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

### OS version (e.g. `uname -a`)
Amazon Linux AMI x86_64 GNU/Linux

Can you please tell if there is any Netty/Avro configuration that may fix this issue?

**Comment by normanmaurer** [comment]
@anton-tsiatsko hard to say but netty 3.x is EOL for a long time...

**Comment by Scottmitch** [comment]
As @normanmaurer said 3.x is EOL. Please update or file an issue with avro to update and report back if a similar issue occurs.
