### ISSUE TITLE
 An existing connection was forcibly closed by the remote host #6426 

### ISSUE THREAD

**Issue by krzys6301** [netty/netty#6938]
### Expected behavior 
the exception not thrown

### Actual behavior 
throws IOException that the remote hos is forcibly closing connections:

java.io.IOException: An existing connection was forcibly closed by the remote host
    at sun.nio.ch.SocketDispatcher.read0(Native Method)
    at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
    at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
    at sun.nio.ch.IOUtil.read(IOUtil.java:192)
    at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
    at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) 
    at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
    at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:372)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
    at java.lang.Thread.run(Thread.java:745)

### Steps to reproduce
run the code that is under the link to StackOverflow site

### Minimal yet complete reproducer code (or URL to code)
SO https://stackoverflow.com/questions/44942666/netty-netty-all-4-1-12-final-jar-java-io-ioexception-an-existing-connection-w

**Comment by Scottmitch** [comment]
Can you please translate the exception to English?

Possibly unrelated but the way you use `ThreadLocal` in `TimeClientHandler` doesn't seem right. There may be multiple instances of `TimeClientHandler` per thread.

Your backlog is 128 ... how do you control back pressure for accepting new sockets? It could be that you are creating connections faster than the server can keep up.

**Comment by krzys6301** [comment]
The exception in english is: An existing connection was forcibly closed by the remote host
When i've changed the BACKLOG from 128 to 65536 the exception still occured.
I understand that I could create the connections faster than the server could accept, but the exception is about "existing connection was forcibly closed by the remote host". What this BACKLOG option is for? I found nothing about it in javadoc, What do you mean with "how do you control back pressure for accepting new sockets" are there any patterns for that? Please elaborate or point me to some documentation about it.

**Comment by Scottmitch** [comment]
Im away from the computer but checkout http://www.linuxjournal.com/files/linuxjournal.com/linuxjournal/articles/023/2333/2333s2.html for more info on the backlog. Make sure there are not OS limits which prevent/limit the value your are setting in the application. Use something like lsof (not sure what this would be on windows) to see socket parameters.

**Comment by normanmaurer** [comment]
I will close this for now due lack of response. Please re-open if you still think there is anything wrong in netty
