### ISSUE TITLE
SslHandlerTest#testCompositeBufSizeEstimationGuaranteesSynchronousWrite failure

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#6946]
Discovered while building PR https://github.com/netty/netty/pull/6944.

https://garage.netty.io/teamcity/viewLog.html?buildId=21865&buildTypeId=pulls_netty&tab=buildLog#_focus=39163
```
[17:55:03][io.netty:netty-handler] testCompositeBufSizeEstimationGuaranteesSynchronousWrite(io.netty.handler.ssl.SslHandlerTest)  Time elapsed: 36.717 sec  <<< ERROR!
[17:55:03][io.netty:netty-handler] java.util.concurrent.ExecutionException: java.lang.IllegalStateException: client closed
[17:55:03][io.netty:netty-handler] 	at io.netty.handler.ssl.SslHandlerTest.compositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:702)
[17:55:03][io.netty:netty-handler] 	at io.netty.handler.ssl.SslHandlerTest.testCompositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:583)
[17:55:03][io.netty:netty-handler] Caused by: java.lang.IllegalStateException: client closed
```

**Comment by Scottmitch** [comment]
Commits were added to increase visibility for this issue:

4.1 (4d51eca21) 4.0 (1902cd4b1)

**Comment by normanmaurer** [comment]
Thanks

**Comment by Scottmitch** [comment]
duplicate of https://github.com/netty/netty/issues/6755
