### ISSUE TITLE
Exception when io.netty.channel.unix.FileDescriptor constructor called

### ISSUE THREAD

**Issue by spyff** [netty/netty#6948]
### Expected behavior
A io.netty.channel.unix.FileDescriptor object created successfully from a unix like integer file descriptor ID

### Actual behavior
Throws exception instead
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errnoENOTCONN()I
	at io.netty.channel.unix.ErrorsStaticallyReferencedJniMethods.errnoENOTCONN(Native Method)
	at io.netty.channel.unix.Errors.<clinit>(Errors.java:36)
	at io.netty.channel.unix.FileDescriptor.<clinit>(FileDescriptor.java:47)
	at Main.main(Main.java:21)
```

### Steps to reproduce
1. Create a project with the source code from below. 
2. Compile and run it.

### Minimal yet complete reproducer code (or URL to code)
Main.java:
```
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.lang.reflect.Field;
import java.nio.ByteBuffer;

import io.netty.channel.unix.FileDescriptor;

public class Main {

    public static void main(String[] args) throws Exception {
        //System.out.println(args[1]);
        FileInputStream f = new FileInputStream("/dev/zero");

        Field privateFd;
        privateFd=java.io.FileDescriptor.class.getDeclaredField("fd");
        privateFd.setAccessible(true);
        java.io.FileDescriptor fd = f.getFD();
        int intFd = ((Integer) privateFd.get(fd)).intValue();
        System.out.println("" + intFd);
        FileDescriptor fin = new FileDescriptor(intFd); //throws
        if(fin.isOpen()){
            System.out.println("File descriptor opened successfully.");
        }
        else {
            System.out.printf("File open error!");
        }
    }
}
```

pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cloud</groupId>
    <artifactId>functions</artifactId>
    <version>1.0</version>
    <packaging>jar</packaging>

    <properties>
        <netty.version>4.1.9.Final</netty.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-all</artifactId>
            <version>4.1.9.Final</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.0.1</version>
                <executions>
                    <execution>
                        <id>unpack-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>unpack-dependencies</goal>
                        </goals>
                        <configuration>
                            <includes>**/*.class</includes>
                            <excludes>**/*.properties</excludes>
                            <outputDirectory>${project.build.directory}/classes</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>true</overWriteSnapshots>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.0.2</version>
                <configuration>
                    <archive>
                        <manifestFile>${project.build.sourceDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

### Netty version
4.1.9

### JVM version (e.g. `java -version`)
**openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)**

### OS version (e.g. `uname -a`)
**Linux Latitude-E6540 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux**

**Comment by Scottmitch** [comment]
You must load the 'Epoll' class which will load the JNI library on Linux. Use [Epoll.iSAvailable](https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/Epoll.java#L66) to attempted to load the JNI libraries and determine if the load was successful.
