### ISSUE TITLE
Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel 	at

### ISSUE THREAD

**Issue by twjitm** [netty/netty#6960]
D:\Java\jdk1.8.0_91\bin\java "-javaagent:D:\Program Files\JetBrains\IntelliJ IDEA 2017.1.1\lib\idea_rt.jar=64641:D:\Program Files\JetBrains\IntelliJ IDEA 2017.1.1\bin" -Dfile.encoding=UTF-8 -classpath D:\Java\jdk1.8.0_91\jre\lib\charsets.jar;D:\Java\jdk1.8.0_91\jre\lib\deploy.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\access-bridge-32.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\cldrdata.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\dnsns.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\jaccess.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\jfxrt.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\localedata.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\nashorn.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\sunec.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\sunjce_provider.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\sunmscapi.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\sunpkcs11.jar;D:\Java\jdk1.8.0_91\jre\lib\ext\zipfs.jar;D:\Java\jdk1.8.0_91\jre\lib\javaws.jar;D:\Java\jdk1.8.0_91\jre\lib\jce.jar;D:\Java\jdk1.8.0_91\jre\lib\jfr.jar;D:\Java\jdk1.8.0_91\jre\lib\jfxswt.jar;D:\Java\jdk1.8.0_91\jre\lib\jsse.jar;D:\Java\jdk1.8.0_91\jre\lib\management-agent.jar;D:\Java\jdk1.8.0_91\jre\lib\plugin.jar;D:\Java\jdk1.8.0_91\jre\lib\resources.jar;D:\Java\jdk1.8.0_91\jre\lib\rt.jar;F:\leitinggongzuo\Server-Code-new\out\production\nettys;C:\Users\Administrator\Desktop\学习记录\netty-5.0.0.Alpha1\netty-5.0.0.Alpha1\jar\all-in-one\netty-all-5.0.0.Alpha1.jar com.nettys.echo.client.EchoClient
Exception in thread "main" io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
	at io.netty.bootstrap.Bootstrap$BootstrapChannelFactory.newChannel(Bootstrap.java:299)
	at io.netty.bootstrap.Bootstrap.createChannel(Bootstrap.java:99)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:263)
	at io.netty.bootstrap.Bootstrap.doConnect(Bootstrap.java:181)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:163)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:144)
	at com.nettys.echo.client.EchoClient.connect(EchoClient.java:37)
	at com.nettys.echo.client.EchoClient.main(EchoClient.java:47)
Caused by: java.lang.NoSuchMethodException: io.netty.channel.socket.nio.NioServerSocketChannel.<init>(io.netty.channel.EventLoop)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getConstructor(Class.java:1825)
	at io.netty.bootstrap.Bootstrap$BootstrapChannelFactory.newChannel(Bootstrap.java:296)
	... 7 more

Process finished with exit code 1

**Comment by normanmaurer** [comment]
Please give us the full stacktrace and more info about netty version , JVM version , OS etc

**Comment by fenik17** [comment]
> netty-all-5.0.0.Alpha1

5.0.0.Alpha1 is outdated.

**Comment by twjitm** [comment]
@normanmaurer  ,My computer operating system is win7 64 bit, and I use the netty version number is 5,

**Comment by twjitm** [comment]
@fenik17  What versions do you use now? mogul

**Comment by fenik17** [comment]
The latest version is 4.1.13.

**Comment by twjitm** [comment]
@fenik17 ，I come from China, Download netty4.1.13 strenuous

**Comment by Scottmitch** [comment]
5.0 has been abandoned for a long time. Please use 4.1 as suggested, and re-open if you are still experiencing issues. I would recommend following one of the [examples](https://github.com/netty/netty/tree/4.1/example) to get started.

**Comment by twjitm** [comment]
@Scottmitch  I think so.I have solved the problem and thank you for your answer
