### ISSUE TITLE
Speed up the CI pipeline

### ISSUE THREAD

**Issue by maseev** [netty/netty#6983]
I'm not sure if this is the best place to ask this kind of question. Have you thought about speeding up the current CI pipeline? It looks like that it takes [about an hour and a half](https://garage.netty.io/teamcity/viewLog.html?buildId=22194&buildTypeId=pulls_netty&guest=1) to build the project and run all tests.

Have you thought about running your unit-tests in parallel? If I'm not mistaken, Maven can run JUnit tests in parallel via the [surefire plugin](https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html).

Or maybe migrating to [Gradle](https://gradle.org/) would be a good idea to improve the performance of the project's builds? Gradle [claims](https://gradle.org/gradle-vs-maven-performance/) that it's much faster than Maven on different types of projects, can compile your project using [incremental compilation](https://guides.gradle.org/performance/#incremental_compilation), run your [tests in parallel](https://guides.gradle.org/performance/#parallel_test_execution) and much more. 

I'm not quite sure if this is a problem right now (slow CI builds), but maybe it could save you some time in the long run and increase the overall responsiveness. WDYT?

**Comment by Scottmitch** [comment]
We have discussed it before offline ... our builds on CI take way too long. We enable a good deal of extra debugging (e.g. resource leak detection) when building on CI which bumps test time up. It hasn't been that high of a priority because PRs mostly build in the background but any speed up or parallelization would be greatly appreciated. A change to gradle would be worth discussing the approach and understanding the scope before hand (this will require some work).

**Comment by maseev** [comment]
Well, enabling parallel test execution should be a pretty straightforward task. And yeah, I agree that migrating to Gradle is a big move that must be considered very thoroughly. Let me enable parallel task execution in my local build and see how it goes. If everything is alright I'll submit a PR. Running unit tests in parallel should improve CI build that's for sure.

**Comment by maseev** [comment]
When I run `mvn test` according to this [checklist](http://netty.io/wiki/developer-guide.html#checklist) I get the following error message:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-transport-native-epoll: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-transport-native-epoll: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98.
```

I'm not sure this is an expected behavior.

**Comment by Scottmitch** [comment]
You get this error without making any changes? Its possible if you are trying to enable parallel execution that we have a bug in our maven files where the goals (and dependencies/sequencing between then) are not setup correctly.

**Comment by maseev** [comment]
No. I just ran `mvn test` on the latest `4.1` branch and got this error.

**Comment by Scottmitch** [comment]
I would need to investigate ... can you list details about your environment (maven version, java, OS, etc...). Please try running `mvn clean install -DskipTests` at the root project level.

**Comment by maseev** [comment]
Ran once again and got this error:

```
Failed tests: 
  HttpPostRequestEncoderTest.testDataIsMultipleOfChunkSize2:412->checkNextChunkSize:423 Chunk is not 8096 bytes expected:<8096> but was:<8094>
```

**Comment by Scottmitch** [comment]
These tests appear to be unreliable due to a recent commit. See https://github.com/netty/netty/issues/7001 and try to work around (ignore) this issue until we fix it.

**Comment by maseev** [comment]
Ran `mvn clean install -DskipTests`, got the same error:

```
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-transport-native-epoll: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
```

Here are the details about my environment if this still makes sense:

```
Maven: Apache Maven 3.3.9
Java: 1.8.0_112
OS: Linux 4.4.0-83-generic #106-Ubuntu SMP
```

**Comment by maseev** [comment]
Updated Maven and Java:

```
Maven: 3.5.0
Java: 1.8.0_141
```

Still no luck. The strange thing is that now Maven passes when I run `mvn clean install -DskipTests`, but fails with the same error:

```
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-transport-native-epoll: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
```

when I run `mvn test`:

```
[INFO] Netty/Transport/Native/Epoll ....................... FAILURE [  0.450 s]
```

I'm not entirely sure whether it's my environment or something else. I wonder how the tests pass without any problems on CI :hushed:

**Comment by Scottmitch** [comment]
> The strange thing is that now Maven passes when I run mvn clean install -DskipTests, but fails with the same error:

What do you mean "maven passes"? You list and error `Failed to execute...` after this statement.

**Comment by maseev** [comment]
I mean that `mvn clean install -DskipTests` passes without any errors, but then fails when I run `mvn test` with this error message:

```
Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-transport-native-epoll: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
```

**Comment by normanmaurer** [comment]
Even with 4.1? Or just with this branch?

**Comment by maseev** [comment]
I've been trying to build Netty and run all tests on the 4.1 branch so far.

**Comment by maseev** [comment]
OK, `mvn install` passes without any errors. According to CI's build log it firstly calls `mvn clean install -DskipTests` and then `mvn install`.

**Comment by maseev** [comment]
Spotted the following exceptions while running the build. Is this expected?

```
Exception in thread "Jython-Netty-Client-4" java.lang.NoClassDefFoundError: org/python/netty/util/concurrent/DefaultPromise$2
	at org.python.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at org.python.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Jython-Netty-Client-1" java.lang.NoClassDefFoundError: org/python/netty/util/concurrent/DefaultPromise$2
	at org.python.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at org.python.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Jython-Netty-Client-5" java.lang.NoClassDefFoundError: org/python/netty/util/concurrent/DefaultPromise$2
	at org.python.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at org.python.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Jython-Netty-Client-3" java.lang.NoClassDefFoundError: org/python/netty/util/concurrent/DefaultPromise$2
	at org.python.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at org.python.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.python.netty.util.concurrent.DefaultPromise$2
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 4 more
Exception in thread "Jython-Netty-Client-6" java.lang.NoClassDefFoundError: org/python/netty/util/concurrent/DefaultPromise$2
	at org.python.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at org.python.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Jython-Netty-Client-7" java.lang.NoClassDefFoundError: org/python/netty/util/concurrent/DefaultPromise$2
	at org.python.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at org.python.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Jython-Netty-Client-8" java.lang.NoClassDefFoundError: org/python/netty/util/concurrent/DefaultPromise$2
	at org.python.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at org.python.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at java.lang.Thread.run(Thread.java:748)
Exception in thread "Jython-Netty-Client-2" Exception in thread "Jython-Netty-Client-9" java.lang.NoClassDefFoundError: org/python/netty/util/concurrent/DefaultPromise$2
	at org.python.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at org.python.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at java.lang.Thread.run(Thread.java:748)
java.lang.NoClassDefFoundError: org/python/netty/util/concurrent/DefaultPromise$2
	at org.python.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:589)
	at org.python.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:397)
	at org.python.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:151)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by normanmaurer** [comment]
Yep a jython bug while unload classes but harmless

**Comment by maseev** [comment]
Sorry, I don't have enough free time to work on this ticket. Feel free to reopen if you think it's worth the effort.

**Comment by maseev** [comment]
I'm just curious, the CI server you use, is it a dedicated server (bare metal) or a virtual one? Can you also share some specs (total amount of RAM, number of cores) of this server box please?

**Comment by maseev** [comment]
It looks like that Clinker provided the CI server for 12 months according to [this](http://netty.io/sponsor/thanks.html) page. But it was in 2014. Before that, it [cost](https://netty.io/news/2014/11/08/new-build-server.html) about $80 a month.

Maybe it'd be a good idea to get one of [these](https://www.scaleway.com/baremetal-cloud-servers/) servers. They are dedicated/bare metal (so there are no "noisy neighbors" around) and they are relatively inexpensive.

The most powerful server with 8 dedicated x86 64bit cores and 32GB of memory costs €24 per month. Adding the value-added tax, which in Europe is about 20%, if I'm not mistaken, works out at €28.8, which in dollars is about $34.58.

It will probably solve the OOM problem for some Netty's modules, like [this one](https://garage.netty.io/teamcity/viewLog.html?buildId=24502&tab=buildResultsDiv&buildTypeId=netty_BuildBoringsslStatic), for example, and allow to build PRs much faster. WDYT?

**Comment by normanmaurer** [comment]
I think we can close this for now as with the changes to our leak detectors its not a real issue anymore
