### ISSUE TITLE
ReadOnlyBufferException regression due to "SslHandler aggregation of plaintext data on write"

### ISSUE THREAD

**Issue by ejona86** [netty/netty#7002]
### Actual behavior

gRPC is now seeing a `ReadOnlyBufferException`:

```
Caused by: java.nio.ReadOnlyBufferException
	at io.netty.buffer.ReadOnlyByteBuf.capacity(ReadOnlyByteBuf.java:413)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:315)
	at io.netty.buffer.WrappedByteBuf.ensureWritable(WrappedByteBuf.java:214)
	at io.netty.handler.ssl.SslHandler$SslHandlerCoalescingBufferQueue.attemptCopyToCumulation(SslHandler.java:1851)
	at io.netty.handler.ssl.SslHandler$SslHandlerCoalescingBufferQueue.compose(SslHandler.java:1817)
	at io.netty.channel.AbstractCoalescingBufferQueue.remove(AbstractCoalescingBufferQueue.java:154)
	at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:752)
	at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:731)
	at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:712)
        ...
```

### Steps to reproduce

```sh
$ git clone https://github.com/grpc/grpc-java.git # I'm at 8572f5ff6
$ cd grpc-java
$ patch -p1 <<EOF
diff --git a/build.gradle b/build.gradle
index 45d87574..83d62a14 100644
--- a/build.gradle
+++ b/build.gradle
@@ -90,7 +90,7 @@ subprojects {
         protocPluginBaseName = 'protoc-gen-grpc-java'
         javaPluginPath = "$rootDir/compiler/build/exe/java_plugin/$protocPluginBaseName$exeSuffix"
 
-        nettyVersion = '4.1.13.Final'
+        nettyVersion = '4.1.14.Final-SNAPSHOT'
         guavaVersion = '19.0'
         protobufVersion = '3.3.1'
         protocVersion = '3.3.0' // TODO(carl-mastrangelo): set this from protobufVersion when versions align again
EOF
$ ./gradlew :grpc-interop-testing:installDist -PskipCodegen=true
$ ./run-test-server.sh
$ # In different terminal
$ ./run-test-client.sh --server_host_override=foo.test.google.fr --use_test_ca=true
```

### Netty version

4.1.13 and commit f7b3cae work fine. But it is broken the "next" commit 24263c2b (86e653e), "SslHandler aggregation of plaintext data on write". It is still present on master at commit f23b2fc25, although I need to revert 43ae974 due to an unrelated cipher issue (and I actually first revert 64a3e6c6 and d4b9f3e4, to make the reverts clean).

------

@Scottmitch, I'm sort of expecting this will be obvious to you since we know the breaking commit. If it's not, I can dig in more to root-cause it. Also, if you suspect we are doing something strange in gRPC I can dig in more on our side.

**Comment by normanmaurer** [comment]
Will have a Look tomorrow

**Comment by Scottmitch** [comment]
@ejona86 - Yip I got this ... accumulation doesn't account for read only buffers.

**Comment by Scottmitch** [comment]
Actually I don't think its SslHandler's fault ... see PR #7004.

**Comment by normanmaurer** [comment]
@Scottmitch thanks!
