### ISSUE TITLE
KQueue shutdownGracefully behavior oddity

### ISSUE THREAD

**Issue by rschmitt** [netty/netty#7047]
### Expected behavior

When running the example code below, the behavior should match that of Nio and Epoll:

```
Iteration 1
Iteration 2
Iteration 3
Done.

Process finished with exit code 0
```

### Actual behavior

The socket is left open, resulting in the second bind() call failing:

```
Iteration 1
Iteration 2
Exception in thread "main" io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use
	at io.netty.channel.unix.Errors.newIOException(Errors.java:117)
	at io.netty.channel.unix.Socket.bind(Socket.java:266)
	at io.netty.channel.kqueue.KQueueServerSocketChannel.doBind(KQueueServerSocketChannel.java:71)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:274)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

### Minimal yet complete reproducer code (or URL to code)

```java
    public static void main(String[] args) throws InterruptedException {
        for (int i = 0; i < 3; i++) {
            System.out.printf("Iteration %d%n", i + 1);
            EventLoopGroup eventLoopGroup = new KQueueEventLoopGroup(4);
            new ServerBootstrap().group(eventLoopGroup)
                    .channelFactory(KQueueServerSocketChannel::new)
                    .childHandler(new ChannelInitializer<Channel>() {
                        @Override
                        protected void initChannel(Channel ch) throws Exception {

                        }
                    })
                    .localAddress(8000)
                    .bind()
                    .sync();

            eventLoopGroup.shutdownGracefully().sync();
        }
        System.out.printf("Done.%n");
    }
```

### Netty version

Latest 4.1 branch

### JVM version (e.g. `java -version`)

java 8u144

### OS version (e.g. `uname -a`)

macOS Sierra 10.12.6

**Comment by Scottmitch** [comment]
This is "expected"/"known" behavior at the moment. The KQueueEventLoop doesn't keep a collection of all registered file descriptors to reduce memory and avoid a map lookup for each notification from `kevent`. I will need to think about approaches here ... not sure if there is an alternative to keeping an additional `Set` just for cleanup purposes. It would be ideal if there was a way to retrieve/iterate all `kevents`.
