### ISSUE TITLE
SslHandlerTest.compositeBufSizeEstimationGuaranteesSynchronousWrite failure

### ISSUE THREAD

**Issue by Scottmitch** [netty/netty#7055]
Observed while building PR https://github.com/netty/netty/pull/7052

https://garage.netty.io/teamcity/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=23001#_focus=40648

```
[io.netty:netty-handler] Tests run: 18, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 98.39 sec <<< FAILURE! - in io.netty.handler.ssl.SslHandlerTest
[20:11:53][io.netty:netty-handler] testCompositeBufSizeEstimationGuaranteesSynchronousWrite(io.netty.handler.ssl.SslHandlerTest)  Time elapsed: 50.3 sec  <<< ERROR!
[20:11:53][io.netty:netty-handler] java.util.concurrent.ExecutionException: java.lang.IllegalStateException: client closed. bytesSeen: 0
[20:11:53][io.netty:netty-handler] 	at io.netty.handler.ssl.SslHandlerTest.compositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:799)
[20:11:53][io.netty:netty-handler] 	at io.netty.handler.ssl.SslHandlerTest.testCompositeBufSizeEstimationGuaranteesSynchronousWrite(SslHandlerTest.java:670)
[20:11:53][io.netty:netty-handler] Caused by: java.lang.IllegalStateException: client closed. bytesSeen: 0
[20:11:53][io.netty:netty-handler] 
[20:11:53][io.netty:netty-handler] Running io.netty.handler.ssl.SslContextBuilderTest
[20:11:54][io.netty:netty-handler] io.netty.handler.ssl.SslHandlerTest
[20:11:54][io.netty.handler.ssl.SslHandlerTest] testCompositeBufSizeEstimationGuaranteesSynchronousWrite
```

**Comment by Scottmitch** [comment]
duplicate of https://github.com/netty/netty/issues/6755
