### ISSUE TITLE
mvn compile fails on netty-transport-native-epoll

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#7101]
The following happens with Maven 3.3 as well as 3.5.

`mvn compile` fails with the following error when it run it from the root of the project. It succeeds when I run `mvn -pl transport-native-epoll compile` or run `mvn compile` from inside the transport-native-epoll directory. `mvn install` always works.

The same error happens when I compile Netty in the IDE (Eclipse).

```java
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Netty .............................................. SUCCESS [  4.532 s]
[INFO] Netty/Common ....................................... SUCCESS [  5.806 s]
[INFO] Netty/Buffer ....................................... SUCCESS [  4.636 s]
[INFO] Netty/Resolver ..................................... SUCCESS [  1.353 s]
[INFO] Netty/Transport .................................... SUCCESS [  3.613 s]
[INFO] Netty/Codec ........................................ SUCCESS [  3.779 s]
[INFO] Netty/Codec/DNS .................................... SUCCESS [  1.853 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  1.350 s]
[INFO] Netty/Handler ...................................... SUCCESS [  3.518 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [  4.044 s]
[INFO] Netty/Codec/HTTP2 .................................. SUCCESS [  3.379 s]
[INFO] Netty/Codec/Memcache ............................... SUCCESS [  1.305 s]
[INFO] Netty/Codec/MQTT ................................... SUCCESS [  1.499 s]
[INFO] Netty/Codec/Redis .................................. SUCCESS [  1.275 s]
[INFO] Netty/Codec/SMTP ................................... SUCCESS [  1.309 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  1.609 s]
[INFO] Netty/Codec/Stomp .................................. SUCCESS [  1.265 s]
[INFO] Netty/Codec/XML .................................... SUCCESS [  1.104 s]
[INFO] Netty/Handler/Proxy ................................ SUCCESS [  1.429 s]
[INFO] Netty/Resolver/DNS ................................. SUCCESS [  1.753 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  0.975 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  1.363 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [  1.270 s]
[INFO] Netty/Example ...................................... SUCCESS [  3.112 s]
[INFO] Netty/Transport/Native/Unix/Common ................. SUCCESS [  1.967 s]
[INFO] Netty/Testsuite .................................... SUCCESS [  2.199 s]
[INFO] Netty/Transport/Native/Unix/Common/Tests ........... SUCCESS [  0.732 s]
[INFO] Netty/Transport/Native/Epoll ....................... FAILURE [  0.498 s]
[INFO] Netty/All-in-One ................................... SKIPPED
[INFO] Netty/Dev-Tools .................................... SKIPPED
[INFO] Netty/Tarball ...................................... SKIPPED
[INFO] Netty/Transport/Native/KQueue ...................... SKIPPED
[INFO] Netty/Testsuite/Autobahn ........................... SKIPPED
[INFO] Netty/Testsuite/OSGI ............................... SKIPPED
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/BOM .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:03 min
[INFO] Finished at: 2017-08-14T11:14:28-04:00
[INFO] Final Memory: 41M/490M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-transport-native-epoll: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:2.10:unpack-dependencies (unpack) on project netty-transport-native-epoll: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Artifact has not been packaged yet. When used on reactor artifact, unpack should be executed after packaging: see MDEP-98.
	at org.apache.maven.plugin.dependency.AbstractDependencyMojo.unpack(AbstractDependencyMojo.java:265)
	at org.apache.maven.plugin.dependency.fromDependencies.UnpackDependenciesMojo.doExecute(UnpackDependenciesMojo.java:91)
	at org.apache.maven.plugin.dependency.AbstractDependencyMojo.execute(AbstractDependencyMojo.java:167)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-transport-native-epoll
```

### JVM version (e.g. `java -version`)

```
$ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)
```

### OS version (e.g. `uname -a`)

```
$ uname -a
Linux ardverk 4.12.6-1-ARCH #1 SMP PREEMPT Sat Aug 12 09:16:22 CEST 2017 x86_64 GNU/Linux
```

**Comment by normanmaurer** [comment]
Thanks will check

**Comment by normanmaurer** [comment]
@rkapsi it just works here :(

```
^Croot@1aa112464b4b:/code# mvn -pl transport-native-epoll compile
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Detecting the operating system and CPU architecture
[INFO] ------------------------------------------------------------------------
[INFO] os.detected.name: linux
[INFO] os.detected.arch: x86_64
[INFO] os.detected.version: 4.9
[INFO] os.detected.version.major: 4
[INFO] os.detected.version.minor: 9
[INFO] os.detected.release: ubuntu
[INFO] os.detected.release.version: 16.10
[INFO] os.detected.release.like.ubuntu: true
[INFO] os.detected.release.like.debian: true
[INFO] os.detected.classifier: linux-x86_64
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Netty/Transport/Native/Epoll 4.1.15.Final-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-transport-native-unix-common/4.1.15.Final-SNAPSHOT/netty-transport-native-unix-common-4.1.15.Final-20170814.120454-14-linux-x86_64.jar
Downloaded: https://oss.sonatype.org/content/repositories/snapshots/io/netty/netty-transport-native-unix-common/4.1.15.Final-SNAPSHOT/netty-transport-native-unix-common-4.1.15.Final-20170814.120454-14-linux-x86_64.jar (49 KB at 29.0 KB/sec)
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ netty-transport-native-epoll ---
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-tools) @ netty-transport-native-epoll ---
[INFO]
[INFO] --- maven-checkstyle-plugin:2.12.1:check (check-style) @ netty-transport-native-epoll ---
[INFO] Starting audit...
Audit done.

[INFO]
[INFO] --- xml-maven-plugin:1.0.1:check-format (check-style) @ netty-transport-native-epoll ---
[INFO]
[INFO] --- maven-dependency-plugin:2.10:get (get-jetty-alpn-agent) @ netty-transport-native-epoll ---
[INFO] Resolving org.mortbay.jetty.alpn:jetty-alpn-agent:jar:2.0.6 with transitive dependencies
[INFO]
[INFO] --- build-helper-maven-plugin:1.10:parse-version (parse-version) @ netty-transport-native-epoll ---
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (ant-get-systeminfo) @ netty-transport-native-epoll ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
[INFO] Executed tasks
[INFO]
[INFO] --- build-helper-maven-plugin:1.10:regex-property (regex-glibc-sendmmsg) @ netty-transport-native-epoll ---
[INFO] No match to regex '^((?!^[^)]+\)\s+(0*2\.1[4-9]|0*2\.[2-9][0-9]+|0*[3-9][0-9]*|0*[1-9]+[0-9]+).*).)*$' found in 'ldd (Ubuntu GLIBC 2.24-3ubuntu2.2) 2.24'. The initial value 'ldd (Ubuntu GLIBC 2.24-3ubuntu2.2) 2.24' is left as-is...
[INFO]
[INFO] --- build-helper-maven-plugin:1.10:regex-property (regex-linux-sendmmsg) @ netty-transport-native-epoll ---
[INFO] No match to regex '^((?!^[0-9]*[3-9]\.?.*).)*$' found in '4.9.36-moby'. The initial value '4.9.36-moby' is left as-is...
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (write-version-properties) @ netty-transport-native-epoll ---
[INFO] Executing tasks

main:
     [echo] Current commit: 505993a on 2017-08-12 11:19:12 -0700
   [delete] Deleting: /code/transport-native-epoll/target/classes/META-INF/io.netty.versions.properties
[propertyfile] Creating new property file: /code/transport-native-epoll/target/classes/META-INF/io.netty.versions.properties
[INFO] Executed tasks
[INFO]
[INFO] --- maven-dependency-plugin:2.10:unpack-dependencies (unpack) @ netty-transport-native-epoll ---
[INFO] Unpacking /root/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.15.Final-SNAPSHOT/netty-transport-native-unix-common-4.1.15.Final-SNAPSHOT-linux-x86_64.jar to /code/transport-native-epoll/target/unix-common-lib with includes "META-INF/native/**" and excludes ""
[INFO]
[INFO] --- build-helper-maven-plugin:1.10:regex-property (regex-combined-sendmmsg) @ netty-transport-native-epoll ---
[INFO] No match to regex '.*IO_NETTY_SENDMSSG_NOT_FOUND.*' found in '4.9.36-mobyldd (Ubuntu GLIBC 2.24-3ubuntu2.2) 2.24'. The initial value '4.9.36-mobyldd (Ubuntu GLIBC 2.24-3ubuntu2.2) 2.24' is left as-is...
[INFO]
[INFO] --- build-helper-maven-plugin:1.10:regex-property (regex-unset-if-needed-sendmmsg) @ netty-transport-native-epoll ---
[INFO]
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ netty-transport-native-epoll ---
[INFO]
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ netty-transport-native-epoll ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /code/transport-native-epoll/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.0:compile (default-compile) @ netty-transport-native-epoll ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 28 source files to /code/transport-native-epoll/target/classes
[WARNING] /code/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java:[860,54] [deprecation] Handle in RecvByteBufAllocator has been deprecated
[WARNING] /code/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java:[862,81] [deprecation] Handle in RecvByteBufAllocator has been deprecated
[WARNING] /code/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java:[897,52] [deprecation] Handle in RecvByteBufAllocator has been deprecated
[WARNING] /code/transport-native-epoll/src/main/java/io/netty/channel/epoll/AbstractEpollStreamChannel.java:[1001,52] [deprecation] Handle in RecvByteBufAllocator has been deprecated
[INFO]
[INFO] --- maven-hawtjni-plugin:1.14:generate (build-native-lib) @ netty-transport-native-epoll ---
[INFO] executing: /bin/sh -c ./autogen.sh
[INFO]
[INFO] --- maven-hawtjni-plugin:1.14:build (build-native-lib) @ netty-transport-native-epoll ---
[INFO] executing: /bin/sh -c ./configure --disable-ccache --prefix=/code/transport-native-epoll/target/native-build/target 'LDFLAGS=-L/code/transport-native-epoll/target/unix-common-lib/META-INF/native/lib -Wl,--no-as-needed -lrt -Wl,--whole-archive -lnetty-unix-common -Wl,--no-whole-archive' 'CFLAGS=-O3 -Werror -fno-omit-frame-pointer -Wunused-variable -I/code/transport-native-epoll/target/unix-common-lib/META-INF/native/include'
[INFO] executing: /bin/sh -c make install
[INFO] Adding test resource root: /code/transport-native-epoll/target/classes
[INFO]
[INFO] --- forbiddenapis:2.2:check (check-forbidden-apis) @ netty-transport-native-epoll ---
[INFO] Scanning for classes to check...
[INFO] Reading API signatures: /code/transport-native-epoll/target/dev-tools/forbidden/signatures.txt
[INFO] Loading classes to check...
[INFO] Scanning classes for violations...
[INFO] Scanned 59 (and 179 related) class file(s) for forbidden API invocations (in 1.65s), 0 error(s).
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min
[INFO] Finished at: 2017-08-14T18:03:58+00:00
[INFO] Final Memory: 35M/204M
[INFO] ------------------------------------------------------------------------
```

```
root@1aa112464b4b:/code# mvn --version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "4.9.36-moby", arch: "amd64", family: "unix"
```

```
root@1aa112464b4b:/code# uname -a
Linux 1aa112464b4b 4.9.36-moby #1 SMP Wed Jul 12 15:29:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I just used a docker image to test it

**Comment by rkapsi** [comment]
@normanmaurer `mvn -pl transport-native-epoll compile` works here as well. Try `mvn compile` from the root of the project.

**Comment by normanmaurer** [comment]
@rkapsi ah sorry... I did misread your comment. Let me check

**Comment by normanmaurer** [comment]
@rkapsi ok I can reproduce it 👍

**Comment by normanmaurer** [comment]
@rkapsi after looking more into it and also check some maven issues I think there is not much we can do here... The problem is that transport-native-epoll depends on transport-native-unix-common to be packaged as it will try to unpack the jar and copy over some files. The problem here is that the jar was not build yet and so it fails. When you use -pl this is not an issue as it will search fro the jar in your local maven repos.

**Comment by rkapsi** [comment]
Hmm hmm - I see. I can live with it that I can't compile `transport-native-epoll` in my IDE (on the CLI I'm usually going the install route) but conceptually I'd say it's a bad dependency in the sense that `transport-native-unix-common` should use the output of `transport-native-epoll` and not depend on the packaged artifact?!

Not sure the above makes sense. I forgot everything about maven years ago. Something is off about that dependency/lifecycle.

**Comment by Scottmitch** [comment]
The goal was that `transport-native-unix-common` builds a static JNI library for the current platform (in addition to the java code which isn't platform dependent), then `transport-native-epoll`/`transport-native-kqueue` can include that static compiled code in its shared JNI library. It looks like I may have got some wires crossed here but hopefully we can correct the issue and declare the dependencies correctly.

**Comment by normanmaurer** [comment]
I will have a look again soon.

**Comment by dancingfrog** [comment]
Could the compilation error be related to the promotion of `native` to a keyword in Java 9? 
https://stackoverflow.com/questions/46501388/how-to-deal-with-java-keywords-in-auto-generated-module-names-in-java-9

**Comment by JLofgren** [comment]
What is the workaround for this?  I am trying to submit a PR to netty and getting this error when trying to run 'mvn test' on the root - as is in the checklist for submitting a PR.

**Comment by normanmaurer** [comment]
@JLofgren try `mvn clean package`

**Comment by JLofgren** [comment]
@normanmaurer Thanks, that worked!

**Comment by kachayev** [comment]
@normanmaurer as it happens quite often... (I've caught this yesterday myself trying to submit a PR) I would suggest you mention this issue (or workaround for it) here: https://github.com/netty/netty/wiki/Developer-guide - this would definitely safe hole lot of hours for submitters

**Comment by arukshani** [comment]
I ran into the same issue. Would be great if this can be updated here. https://netty.io/wiki/developer-guide.html#checklist

**Comment by carryxyh** [comment]
Hi, all

Same problem.
Personally think this way is not very friendly to developers. A better way is to directly execute examples such as echo client and echo server after downloading the source code. Instead of doing some other things before executing.
What do u think about it?

**Comment by sandyKamath** [comment]
I am using ant with ivy and not maven.
Any idea of how can I proceed.
ant build is failing to get netty-transport-native-epoll-4.1.48.Final-linux-x86_64.jar

**Comment by auxor** [comment]
Got the same issue.
"mvn -pl transport-native-kqueue" and "mvn clean install" do not work.

My env info: 
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-18T02:33:14+08:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.11+9/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"

**Comment by hahahaha123567** [comment]
try to delete netty-transport-native-* cache in .m2 if your system is mac

**Comment by diegolovison** [comment]
I am facing a different issue but in the same project. Decided to not open a new issue ( I can do if needed ).

```
[ERROR] Failed to execute goal org.fusesource.hawtjni:hawtjni-maven-plugin:1.18:build (build-native-lib) on project netty-transport-native-epoll: build failed: org.apache.maven.plugin.MojoExecutionException: Requested download does not exist.: The following artifacts could not be resolved: io.netty:netty-transport-native-epoll:zip:native-src:4.1.115.Final-SNAPSHOT (absent): io.netty:netty-transport-native-epoll:zip:native-src:4.1.115.Final-SNAPSHOT was not found in https://oss.sonatype.org/content/repositories/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command: 
[ERROR]     mvn install:install-file -DgroupId=io.netty -DartifactId=netty-transport-native-epoll -Dversion=4.1.115.Final-SNAPSHOT -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]     mvn deploy:deploy-file -DgroupId=io.netty -DartifactId=netty-transport-native-epoll -Dversion=4.1.115.Final-SNAPSHOT -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR]   io.netty:netty-transport-native-epoll:zip:4.1.115.Final-SNAPSHOT
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]

```

```
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /home/dlovison/.sdkman/candidates/maven/current
Java version: 21.0.2, vendor: Oracle Corporation, runtime: /home/dlovison/.sdkman/candidates/java/21.0.2-open
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.10.9-200.fc40.x86_64", arch: "amd64", family: "unix"
```
