### ISSUE TITLE
Netty 4.1.14.Final fails to load on android

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#7117]
From the comments of our release announcement:

```
netty 4.1.14.Final cannot work on android. An exception thrown when creating an instance of NioEventLoopGroup, but netty 4.1.13.Final no problem.

java.lang.NoSuchMethodError: No virtual method pageSize()I in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
at io.netty.util.internal.shaded.org.jctools.util.JvmInfo.<clinit>(JvmInfo.java:5)
at io.netty.util.internal.shaded.org.jctools.queues.atomic.BaseMpscLinkedAtomicArrayQueue.<clinit>(BaseMpscLinkedAtomicArrayQu...:73)
at io.netty.util.internal.PlatformDependent$Mpsc.newMpscQueue(PlatformDependent.java:841)
at io.netty.util.internal.PlatformDependent.newMpscQueue(PlatformDependent.java:852)
at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:259)
at io.netty.util.concurrent.SingleThreadEventExecutor.<init>(SingleThreadEventExecutor.java:164)
at io.netty.channel.SingleThreadEventLoop.<init>(SingleThreadEventLoop.java:58)
at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:141)
at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGro...:84)
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGro...:58)
at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
```

http://netty.io/news/2017/08/03/4-0-50-Final-4-1-14-Final.html#comment-3472176139

**Comment by normanmaurer** [comment]
@nitsanw can you check ? We upgraded to a new version of jctools ...

**Comment by nitsanw** [comment]
Bugger :-(, will add a safe version and cut a release ASAP.

**Comment by normanmaurer** [comment]
@nitsanw <3... Let me know once ready or even better just provide a pr to update the version we are using once it is ready...

**Comment by lgengsy** [comment]
I found this  bug  on  Android device 魅蓝M5，the  netty-all-4.1.15.Final-20170819.120514-18.jar   is not   fix  .

**Comment by Scottmitch** [comment]
*should* be fixed by https://github.com/netty/netty/pull/7134

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7134

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7284
