### ISSUE TITLE
Unexpected exception in the selector loop(EpollEventLoop)

### ISSUE THREAD

**Issue by Sammers21** [netty/netty#7128]
### Steps to reproduce
* in pom
```xml
<netty.version>4.1.14.Final</netty.version>

<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-all</artifactId> 
      <version>${netty.version}</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-transport-native-epoll</artifactId>
      <version>${netty.version}</version>
      <classifier>${os.detected.name}-${os.detected.arch}</classifier>
</dependency>

<build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.5.0.Final</version>
      </extension>
    </extensions>
</build>

```

* code:

```java
public class NettyServer {

  public void run() throws InterruptedException {
    EventLoopGroup bossGroup = new EpollEventLoopGroup(); 
    EventLoopGroup workerGroup = new EpollEventLoopGroup();
    try {
      ServerBootstrap b = new ServerBootstrap(); 
      b.group(bossGroup)
        .channel(EpollServerSocketChannel.class) 
        .childHandler(new ChannelInitializer<EpollSocketChannel>() { 
          @Override
          public void initChannel(EpollSocketChannel ch) throws Exception {

            ch.pipeline().addLast("decoder", new HttpRequestDecoder());
            ch.pipeline().addLast("encoder", new HttpResponseEncoder());
            ch.pipeline().addLast(new NettyHttpRequestHandler());
          }
        });
      ChannelFuture f = b.bind(8080).sync(); 
      f.channel().closeFuture().sync();
    } finally {
      workerGroup.shutdownGracefully();
      bossGroup.shutdownGracefully();
    }
  }
}

public class NettyHttpRequestHandler extends SimpleChannelInboundHandler<Object> {
  
  @Override
  protected void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {
    System.out.println("read");
    System.out.println(msg.getClass().getName());
    if (msg instanceof HttpRequest) {
      System.out.println("receive request");
      final HttpRequest request = (HttpRequest) msg;
      HttpMethod method = request.method();
      
      System.out.println("uri: " + request.uri());
      
      FullHttpResponse response = new DefaultFullHttpResponse(
        HttpVersion.HTTP_1_1,
        HttpResponseStatus.OK,
        copiedBuffer("kek".getBytes())
      );

      if (HttpHeaders.isKeepAlive(request)) {
        response.headers().set(
          HttpHeaders.Names.CONNECTION,
          HttpHeaders.Values.KEEP_ALIVE
        );
      }
      response.headers().set(HttpHeaders.Names.CONTENT_TYPE,
        "text/plain");
      response.headers().set(HttpHeaders.Names.CONTENT_LENGTH,
        "hello".length());
      ctx.writeAndFlush(response);
    }
  }

  @Override
  public void exceptionCaught(ChannelHandlerContext ctx,
                              Throwable cause) throws Exception {
    ctx.writeAndFlush(new DefaultFullHttpResponse(
      HttpVersion.HTTP_1_1,
      HttpResponseStatus.INTERNAL_SERVER_ERROR,
      copiedBuffer(cause.getMessage().getBytes())
    ));
  }


public static void main(String[] args) {
    try {
      new NettyServer().run();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
}
```

* run the example
* execute code:
```bahs
curl http://localhost:8080/hello
```
and then exception appears:
```
Aug 18, 2017 10:58:57 PM io.netty.channel.epoll.EpollEventLoop handleLoopException
WARNING: Unexpected exception in the selector loop.
java.lang.ClassCastException: io.netty.channel.AdaptiveRecvByteBufAllocator$HandleImpl cannot be cast to io.netty.channel.RecvByteBufAllocator$ExtendedHandle
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.recvBufAllocHandle(AbstractEpollChannel.java:448)
	at io.netty.channel.epoll.AbstractEpollServerChannel$EpollServerSocketUnsafe.epollInReady(AbstractEpollServerChannel.java:97)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

```

### Netty version
4.1.14.Final

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (Zulu 8.21.0.1-linux64) (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (Zulu 8.21.0.1-linux64) (build 25.131-b11, mixed mode)

### OS version (e.g. `uname -a`)
Linux 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@Sammers21 do you maybe have multiple netty versions on your class path ?

**Comment by Sammers21** [comment]
@normanmaurer , it seems that you are right. I have vertx.io dependency in my class path

**Comment by normanmaurer** [comment]
Ensure you only have one version and all should be fine

**Comment by Sammers21** [comment]
@normanmaurer, thank you for lightning fast help!
