### ISSUE TITLE
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1

### ISSUE THREAD

**Issue by Sammers21** [netty/netty#7131]
I have following things in pipeline 
```java
            ch.pipeline().addLast("decoder", new HttpRequestDecoder());
            ch.pipeline().addLast("encoder", new HttpResponseEncoder());
            ch.pipeline().addLast("aggregator", new HttpObjectAggregator(1048576));
            ch.pipeline().addLast(new MyServerInboundhandler());
         
```
and in MyServerInboundhandler I have:
```java
@Override
  public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
    super.channelRead(ctx, msg);
    if (msg instanceof FullHttpRequest) {
      final FullHttpRequest request = (FullHttpRequest) msg;
      String bodyString = request.content().retain().toString(CharsetUtil.UTF_8); //ERROR HERE
     }
}
```

This code produces an error 
```
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.retain0(AbstractReferenceCountedByteBuf.java:68)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.retain(AbstractReferenceCountedByteBuf.java:53)
	at io.netty.buffer.CompositeByteBuf.retain(CompositeByteBuf.java:1906)
	at io.netty.buffer.CompositeByteBuf.retain(CompositeByteBuf.java:44)
	at io.netty.buffer.AbstractDerivedByteBuf.retain0(AbstractDerivedByteBuf.java:49)
	at io.netty.buffer.AbstractDerivedByteBuf.retain(AbstractDerivedByteBuf.java:45)
	at io.netty.buffer.AbstractByteBuf.retainedDuplicate(AbstractByteBuf.java:1173)
	at my.class.MyServerInboundhandler.channelRead(MyServerInboundhandler.java:118)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
```
### Expected behavior
I m expect that all should be okay :)
### Actual behavior
An error occur
### Netty version
4.1.8.Final
### JVM version (e.g. `java -version`)
openjdk_8_131
### OS version (e.g. `uname -a`)
Linux4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Sammers21** [comment]
It seems that the buffer I use is already released by the decoder, how I can reuse them?

**Comment by normanmaurer** [comment]
@Sammers21 remove the `super.channelRead(...)` call and ensure you call release() on the `FullHttpRequest` once you are done. Also remove the `retain()` call.

**Comment by Sammers21** [comment]
@normanmaurer, thank you! It helped!

**Comment by Scottmitch** [comment]
See http://netty.io/wiki/reference-counted-objects.html for additional context too
