### ISSUE TITLE
ByteToMessageDecoder NullPointerException

### ISSUE THREAD

**Issue by daenius** [netty/netty#7154]
### Netty version
4.1.13 FINAL

### JVM version (e.g. `java -version`)
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

and 

java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

### OS version (e.g. `uname -a`)
OSX El Capitan 10.11.6
RHEL 5

**I have an HTTP/2 server and a client**

I'm able to connect to the server initially and the streams seem to open properly (stream ID3)

I'm able to send requests to the server, but whenever a server has a response, I can ONLY read the HEADERS, as everything else seems to cause a "Connection Error"

Upon more debugging I'm seeing this: 

```
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1273)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1084)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
```

NPE in the Decoder is very suspicious, and it seems to only happen after receiving a happy 200 from the server.

I noticed 2 things, one is the SslHandler in the above stack trace, and another is a stack strace that always shows up when I try to create a stream.

Here is the createStream() Stack trace, it doesn't seem to stop the stream from being created and returned, but it looks concerning:

```
20:55:49.912 [pool-2-thread-2] ERROR io.netty.handler.codec.http2.DefaultHttp2Connection - Caught Throwable from listener onStreamActive.
java.lang.AssertionError
	at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.window(DefaultHttp2LocalFlowController.java:360) ~[netty-all-4.1.jar:4.1.13.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.<init>(DefaultHttp2LocalFlowController.java:354) ~[netty-all-4.1.jar:4.1.13.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$1.onStreamActive(DefaultHttp2LocalFlowController.java:100) ~[netty-all-4.1.jar:4.1.13.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.addToActiveStreams(DefaultHttp2Connection.java:945) [netty-all-4.1.jar:4.1.13.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.activate(DefaultHttp2Connection.java:900) [netty-all-4.1.jar:4.1.13.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultStream.activate(DefaultHttp2Connection.java:458) [netty-all-4.1.jar:4.1.13.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:714) [netty-all-4.1.jar:4.1.13.Final-SNAPSHOT]
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:625) [netty-all-4.1.jar:4.1.13.Final-SNAPSHOT]


```

As for the SslHandler, I'm using this code for setting up the SslContext, I wonder if this is could be related?

```
public SslContext getSslContext(boolean isSecure)
        throws SSLException, CertificateException {

        // This accepts any server X509 certificate without validation
        if (DEBUG) Log.d(TAG, "Warning: using unsecure trust manager!");
        final SslContextBuilder b = SslContextBuilder.forClient().trustManager(
                InsecureTrustManagerFactory.INSTANCE);
        return b.sslProvider(SslProvider.JDK)
                .ciphers(Http2SecurityUtil.CIPHERS, SupportedCipherSuiteFilter.INSTANCE)
                .build();
    }
}
```

Any help is greatly appreciated!
Thanks!

**Comment by Scottmitch** [comment]
> at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.window(DefaultHttp2LocalFlowController.java:360) ~[netty-all-4.1.jar:4.1.13.Final-SNAPSHOT]

This assertion indicates either:
1. `ChannelHandlerContext` has not been set. Which would point to a configuration/initialization bug.
2. The HTTP/2 codec is not thread safe. You must only interact with it from the EventLoop thread.

**Comment by daenius** [comment]
Thank you very much for the quick reply!

It would be difficult to provide a reproducer as of now since it deals with a specific server that has some specific setups, but I'll certainly try my best to see if I can rule out the above scenarios.

Do you think the NPE in the decoder is likely due to the fact that it isn't threadsafe then?

**Comment by daenius** [comment]
Upon much more digging I was able to arrive at the place that's disconnecting in my client whenever it tries to read DATA frames:

In **DefaultHttp2LocalFlowController**, the **private static final DefaultHttp2LocalFlowController.FlowState REDUCED_FLOW_STATE** implementation of FlowState

```
        public void endOfStream(boolean endOfStream) {
            throw new UnsupportedOperationException();
        }
```
Regardless of the state of endOfStream, it'll ALWAYS throw UnsupportedOperationException, causing the client to die.

How did I end up with that particular implementation of FlowState? Scrolling down further in the DefaultHttp2LocalFlowController class reveals that there's another implementation called DefaultState, **private class DefaultState implements DefaultHttp2LocalFlowController.FlowState**

Which has a much more normal looking implementation of endOfStream:

```
        public void endOfStream(boolean endOfStream) {
            this.endOfStream = endOfStream;
        }
```

Did I miss something here that's causing it to use that FlowState?

**Comment by normanmaurer** [comment]
@ejona86 PTAL as well

**Comment by normanmaurer** [comment]
@ejona86 ping

**Comment by daenius** [comment]
Got it to work now! It had to do with the way the threads were managed

**Comment by normanmaurer** [comment]
@daenius thanks for the update

**Comment by ag250615** [comment]
exceptionCaught	
io.netty.handler.codec.DecoderException: java.lang.NullPointerException
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:480)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
	at org.spongycastle.crypto.signers.PSSSigner.generateSignature(PSSSigner.java:189)
	at org.spongycastle.jcajce.provider.asymmetric.rsa.PSSSignatureSpi.engineSign(PSSSignatureSpi.java:161)
	at java.base/java.security.Signature$Delegate.engineSign(Signature.java:1404)
	at java.base/java.security.Signature.sign(Signature.java:713)
	at java.base/sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeMessage.<init>(ECDHServerKeyExchange.java:181)
	at java.base/sun.security.ssl.ECDHServerKeyExchange$ECDHServerKeyExchangeProducer.produce(ECDHServerKeyExchange.java:499)
	at java.base/sun.security.ssl.ClientHello$T12ClientHelloConsumer.consume(ClientHello.java:1102)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.onClientHello(ClientHello.java:854)
	at java.base/sun.security.ssl.ClientHello$ClientHelloConsumer.consume(ClientHello.java:813)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
