### ISSUE TITLE
The ChannelHandler which is used to construct Http2MultiplexCodecBuilder will also be added to out bound streams

### ISSUE THREAD

**Issue by Apache9** [netty/netty#7178]
### Expected behavior
The `ChannelHandler` which is used to construct `Http2MultiplexCodecBuilder` should only be added to remotely-created streams.
### Actual behavior
It is also added to out bound streams.
### Steps to reproduce
Modify `Http2MultiplexCodecBuilderTest`, replace the code in `setUp`

```
        Bootstrap cb = new Bootstrap()
                .channel(LocalChannel.class)
                .group(group)
                .handler(new Http2MultiplexCodecBuilder(false, new TestChannelInitializer()).build());
```
to
```
        Bootstrap cb = new Bootstrap()
                .channel(LocalChannel.class)
                .group(group)
                .handler(new Http2MultiplexCodecBuilder(false, new ChannelInitializer<Channel>() {

                    @Override
                    protected void initChannel(Channel ch) throws Exception {
                        throw new RuntimeException("should not be call for outbound stream");
                    }
                }).build());
```
Then `createOutboundStream` and `multipleOutboundStreams` will both fail.
### Minimal yet complete reproducer code (or URL to code)
Just apply this patch
https://github.com/Apache9/netty/commit/2dcbae3109bbab5699dbfd64176694c8d43f69ca
### Netty version
4.1.15.Final
### JVM version (e.g. `java -version`)
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
### OS version (e.g. `uname -a`)
Linux zhangduo-ubuntu 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Apache9** [comment]
The stracktrace of the exception when running modified `Http2MultiplexCodecBuilderTest`.
```
15:49:13.120 [defaultEventLoop-1-1] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x70bc891d, L:local:E:e07decb9 - R:local:io.netty.handler.codec.http2.http2multiplexcodecbuildertest](HTTP/2 - -1)
java.lang.RuntimeException: should not be call for outbound stream
	at io.netty.handler.codec.http2.Http2MultiplexCodecBuilderTest$2.initChannel(Http2MultiplexCodecBuilderTest.java:89)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
	at io.netty.channel.DefaultChannelPipeline.access$15(DefaultChannelPipeline.java:604)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1412)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1131)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:656)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1331)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:829)
	at io.netty.handler.codec.http2.Http2MultiplexCodec$DefaultHttp2StreamChannel$Http2ChannelUnsafe.register(Http2MultiplexCodec.java:799)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:80)
	at io.netty.channel.SingleThreadEventLoop.register(SingleThreadEventLoop.java:74)
	at io.netty.handler.codec.http2.Http2StreamChannelBootstrap.open0(Http2StreamChannelBootstrap.java:143)
	at io.netty.handler.codec.http2.Http2StreamChannelBootstrap$1.run(Http2StreamChannelBootstrap.java:124)
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:745)
```
Seems in `Http2MultiplexCodec.DefaultHttp2StreamChannel.Http2ChannelUnsafe.register`
, we always add the `inboundStreamHandler` to the pipeline of the `Http2Stream`, no matter it is inbound or not.

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2MultiplexCodec.java#L795

@normanmaurer

**Comment by normanmaurer** [comment]
Yep.. not sure if this is a bug or not tho as you will need to have an handler that handles inbound frames as well here. @ejona86 WDYT?

**Comment by Apache9** [comment]
Yeah we need this handler to handle the inbound streams. But for outboud streams, we will provide one by calling  `Http2StreamChannelBootstrap.handler`.

**Comment by ejona86** [comment]
I agree that outbound streams should have their channel initializer specified via `Http2StreamChannelBootstrap.handler()`. `Http2MultiplexCodecBuilder`'s handler is only for inbound streams.

**Comment by normanmaurer** [comment]
Got it... let me do a fix quickly

**Comment by normanmaurer** [comment]
Should be fixed by https://github.com/netty/netty/pull/7180 . Please check

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7180
