### ISSUE TITLE
DatagramUnicastTest.testSimpleSendWithConnect test failure

### ISSUE THREAD

**Issue by normanmaurer** [netty/netty#7190]
```
[09:49:38][io.netty:netty-testsuite] java.lang.AssertionError
[09:49:38][io.netty:netty-testsuite] 	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendWithConnect0(DatagramUnicastTest.java:246)
[09:49:38][io.netty:netty-testsuite] 	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendWithConnect(DatagramUnicastTest.java:197)
[09:49:38][io.netty:netty-testsuite] 	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendWithConnect(DatagramUnicastTest.java:141)
[09:49:38][io.netty:netty-testsuite] 	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendWithConnect(DatagramUnicastTest.java:137)
```

**Comment by normanmaurer** [comment]
Was triggered here https://garage.netty.io/teamcity/viewLog.html?buildId=24114&buildTypeId=pulls_netty&tab=buildLog#_focus=84596 while building https://github.com/netty/netty/pull/7162

**Comment by normanmaurer** [comment]
Openend PR to log more infos:

https://github.com/netty/netty/pull/7191

**Comment by normanmaurer** [comment]
This was actually a valid one as #7162 had a bug.
