### ISSUE TITLE
useCacheForAllThreads no longer seems to work.

### ISSUE THREAD

**Issue by carl-mastrangelo** [netty/netty#7194]
While playing with jvm flags to control memory pooling, I noticed `io.netty.allocator.useCacheForAllThreads`.  From reading the source, it seems to control whether or not buffers are cached per thread.

However, setting it to false and using the default allocator causes lots of exceptions to be thrown:

```

java.lang.IllegalArgumentException: freeSweepAllocationThreshold: 0 (expected: > 0)
	at io.netty.buffer.PoolThreadCache.<init>(PoolThreadCache.java:75)
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:430)
	at io.netty.buffer.PooledByteBufAllocator$PoolThreadLocalCache.initialValue(PooledByteBufAllocator.java:412)
	at io.netty.util.concurrent.FastThreadLocal.initialize(FastThreadLocal.java:155)
	at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:149)
	at io.netty.util.concurrent.FastThreadLocal.get(FastThreadLocal.java:135)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:319)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
	at io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:109)
	...
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

Here is the debug output for start up
```

Sep 07, 2017 5:45:48 PM io.netty.util.internal.logging.InternalLoggerFactory newDefaultFactory
FINE: Using java.util.logging as the default logging framework
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent0 explicitNoUnsafe0
FINE: -Dio.netty.noUnsafe: false
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent0 javaVersion0
FINE: Java version: 8
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: sun.misc.Unsafe.theUnsafe: available
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: sun.misc.Unsafe.copyMemory: available
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: java.nio.Buffer.address: available
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: direct buffer constructor: available
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: java.nio.Bits.unaligned: available, true
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent0 <clinit>
FINE: java.nio.DirectByteBuffer.<init>(long, int): available
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent hasUnsafe0
FINE: sun.misc.Unsafe: available
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent tmpdir0
FINE: -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent bitMode0
FINE: -Dio.netty.bitMode: 64 (sun.arch.data.model)
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent <clinit>
FINE: -Dio.netty.noPreferDirect: false
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent <clinit>
FINE: -Dio.netty.maxDirectMemory: 8125284352 bytes
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent <clinit>
FINE: -Dio.netty.uninitializedArrayAllocationThreshold: -1
Sep 07, 2017 5:45:48 PM io.netty.util.internal.CleanerJava6 <clinit>
FINE: java.nio.ByteBuffer.cleaner(): available
Sep 07, 2017 5:45:48 PM io.netty.channel.MultithreadEventLoopGroup <clinit>
FINE: -Dio.netty.eventLoopThreads: 24
Sep 07, 2017 5:45:48 PM io.netty.util.internal.NativeLibraryLoader <clinit>
FINE: -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
Sep 07, 2017 5:45:48 PM io.netty.util.NetUtil <clinit>
FINE: -Djava.net.preferIPv4Stack: false
Sep 07, 2017 5:45:48 PM io.netty.util.NetUtil <clinit>
FINE: -Djava.net.preferIPv6Addresses: false
Sep 07, 2017 5:45:48 PM io.netty.util.NetUtil <clinit>
FINE: Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
Sep 07, 2017 5:45:48 PM io.netty.util.NetUtil$1 run
FINE: /proc/sys/net/core/somaxconn: 128
Sep 07, 2017 5:45:48 PM io.netty.util.internal.NativeLibraryLoader load
FINE: netty_transport_native_epoll was loaded from java.libary.path
Sep 07, 2017 5:45:48 PM io.netty.util.internal.PlatformDependent$Mpsc <clinit>
FINE: org.jctools-core.MpscChunkedArrayQueue: available
Sep 07, 2017 5:45:48 PM io.netty.channel.DefaultChannelId <clinit>
FINE: -Dio.netty.processId: 11488 (auto-detected)
Sep 07, 2017 5:45:48 PM io.netty.channel.DefaultChannelId <clinit>
FINE: -Dio.netty.machineId: ec:b1:d7:ff:fe:2c:87:92 (auto-detected)
Sep 07, 2017 5:45:48 PM io.netty.util.internal.InternalThreadLocalMap <clinit>
FINE: -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
Sep 07, 2017 5:45:48 PM io.netty.util.internal.InternalThreadLocalMap <clinit>
FINE: -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
Sep 07, 2017 5:45:48 PM io.netty.util.ResourceLeakDetector <clinit>
FINE: -Dio.netty.leakDetection.level: simple
Sep 07, 2017 5:45:48 PM io.netty.util.ResourceLeakDetector <clinit>
FINE: -Dio.netty.leakDetection.maxRecords: 4
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.numHeapArenas: 24
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.numDirectArenas: 24
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.pageSize: 8192
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.maxOrder: 11
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.chunkSize: 16777216
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.tinyCacheSize: 512
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.smallCacheSize: 256
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.normalCacheSize: 64
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.maxCachedBufferCapacity: 32768
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.cacheTrimInterval: 8192
Sep 07, 2017 5:45:48 PM io.netty.buffer.PooledByteBufAllocator <clinit>
FINE: -Dio.netty.allocator.useCacheForAllThreads: false
Sep 07, 2017 5:45:48 PM io.netty.buffer.ByteBufUtil <clinit>
FINE: -Dio.netty.allocator.type: pooled
Sep 07, 2017 5:45:48 PM io.netty.buffer.ByteBufUtil <clinit>
FINE: -Dio.netty.threadLocalDirectBufferSize: 65536
Sep 07, 2017 5:45:48 PM io.netty.buffer.ByteBufUtil <clinit>
FINE: -Dio.netty.maxThreadLocalCharBufferSize: 16384
```

### Netty version
4.1.15

### JVM version (e.g. `java -version`)
1.8.0_112

### OS version (e.g. `uname -a`)
4.4.0-83-generic

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7195... Thanks @carl-mastrangelo
