### ISSUE TITLE
Error: Unable to load the library 'netty_transport_native_epoll' in CENTOS 6

### ISSUE THREAD

**Issue by onderaycicek** [netty/netty#7220]
### Expected behavior
it is netty run error. We cannot run Netty project in Centos/Red-Hat 6.7
### Actual behavior
it throws "`Unable to load the library 'netty_transport_native_epoll'`"
`java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_91]
        at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_91]
        at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_91]
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:222) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_91]
        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:214) ~[netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:202) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:118) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:199) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.Native.<clinit>(Native.java:61) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:55) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:134) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:35) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68) [netty-all-4.1.15.Final.jar:4.1.15.Final]
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:52) [netty-all-4.1.15.Final.jar:4.1.15.Final]`
### Minimal yet complete reproducer code (or URL to code)
netty-all-4.1.15-Final.jar
`EventLoopGroup group = new NioEventLoopGroup();
        try {
            scktHndlr = new UDPSocketHandler();
            Bootstrap b = new Bootstrap();
            ChannelFuture future = null;
            if (!OS.startsWith("Windows")) {
                b.group(new EpollEventLoopGroup(5))
                        .channel(EpollDatagramChannel.class)
                        .option(ChannelOption.ALLOCATOR, PooledByteBufAllocator.DEFAULT)
                        .option(EpollChannelOption.SO_REUSEPORT, true)
                        .handler(scktHndlr);
                for (int i = 0; i < 5; ++i) {                    
                    future = b.bind(port).await();
                    if (!future.isSuccess()) {
                        logger.debug("ERROR UDP server on Port " + port + " " + i);
                    }else{
                        logger.debug("Opened UDP server on Port " + port + " " + i);
                    }
                }
            } else {
                b.group(group)
                        .channel(NioDatagramChannel.class)
                        .handler(scktHndlr)
                        .option(ChannelOption.SO_BROADCAST, true)
                        .option(ChannelOption.SO_REUSEADDR, true);
                future = b.bind(port).sync().channel().closeFuture().await();
                if (!future.isSuccess()) {
                    logger.debug("ERROR UDP server on Port " + port + " ");
                }else{
                    logger.debug("Opened UDP server on Port " + port + " ");
                }                
            }
        } finally {
            group.shutdownGracefully();
            logger.debug("Closed UDP server on Port " + port);
        }`
### Netty version
Netty 4.1.15(netty-all-4.1.15-Final.jar)
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
### OS version (e.g. `uname -a`)
Linux localhost.localdomain 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 00:57:44 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
can you try again with 4.1.16.Final ?

**Comment by onderaycicek** [comment]
Problem solved. Thanks.


`2017-09-29 13:59:37,223 DEBUG [main] io.netty.util.internal.NativeLibraryLoader [] - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)

2017-09-29 13:59:37,225 DEBUG [main] io.netty.util.internal.NativeLibraryLoader [] - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.

2017-09-29 13:59:37,238 DEBUG [main] io.netty.util.internal.NativeLibraryLoader [] - netty_transport_native_epoll_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /tmp

**2017-09-29 13:59:37,270 DEBUG [main] io.netty.util.internal.NativeLibraryLoader [] - Successfully loaded the library /tmp/libnetty_transport_native_epoll_x86_645568419128263411328.so**`

**Comment by xiangwangcheng** [comment]
@onderaycicek Did you solve this problem by just changing to version  4.1.16.Final.
I also encountered this problem and I'm using 4.1.25.Final.
![image](https://user-images.githubusercontent.com/8049014/69592282-71af2600-1030-11ea-9867-16479e6ca39d.png)

I'm using centos-release-7-3.1611.el7.

**Comment by SebastienTr** [comment]
Same issue with the 4.1.43.Final

**Comment by onderaycicek** [comment]
@xiangwangcheng This issue was solved by upgrade to version 4.1.16.

**Comment by paulo-maia** [comment]
Still getting this error with version 4.1.45.Final...

**Comment by sandorvasas** [comment]
4.1.50.Final throwing this

**Comment by MadinaBonuAlisherova** [comment]
> 4.1.50.Final throwing this

Yes, did you find some solution for this version?
