### ISSUE TITLE
h2c cleartext upgrades fail every time

### ISSUE THREAD

**Issue by mosesn** [netty/netty#7226]
### Expected behavior

Clients should successfully upgrade.

### Actual behavior

Clients fail to upgrade, and instead throw the exception:

```
                     Caused by: io.netty.handler.codec.http2.Http2Exception: HTTP upgrade must occur after preface was sent
                     	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
                     	at io.netty.handler.codec.http2.Http2ConnectionHandler.onHttpClientUpgrade(Http2ConnectionHandler.java:162)
                     	at io.netty.handler.codec.http2.Http2ClientUpgradeCodec.upgradeTo(Http2ClientUpgradeCodec.java:104)
                     	at io.netty.handler.codec.http.HttpClientUpgradeHandler.decode(HttpClientUpgradeHandler.java:237)
                     	... 40 more
```

### Steps to reproduce

Try to use the Http2ClientUpgradeCodec with the h2c upgrade.

### Minimal yet complete reproducer code (or URL to code)

Try 4.1.16.Final-SNAPSHOT with finagle.

### Netty version
nightlies

**Comment by normanmaurer** [comment]
will try soon.

**Comment by mosesn** [comment]
I think we can fix this by swapping these two lines: https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ClientUpgradeCodec.java#L104-L107

**Comment by normanmaurer** [comment]
@mosesn sounds good! Can you do the change ? Extra point if you can also add a unit test.

**Comment by mosesn** [comment]
@normanmaurer I don't have time to add the unit test tonight, but I can take a stab at it tomorrow.

**Comment by normanmaurer** [comment]
@mosesn yes please do... that said the changes LGTM.

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7227
