### ISSUE TITLE
Is it possible to wrap "connection forcibly closed" error into a exception of its own

### ISSUE THREAD

**Issue by manish-panwar** [netty/netty#7229]
### Expected behavior

Connection error should be wrapped in a specific class instead of IOException. IOException is too raw to put a check on and do error handling. "connection forcibly closed" are expected and harmless for us, so we need to know which error to ignore.

### Actual behavior

We are using Vertx, which internally uses Netty for HTTP requests. We are using keep-alive connection, and seeing following error in logs. We totally understand that it's okay to get this error on keep-alive connection but exception type is raw (IOException) and it's difficult to just rely on IOException to control the app behavior.

java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(Unknown Source)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)
	at sun.nio.ch.IOUtil.read(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1100)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:367)

### Steps to reproduce

Open keep-alive connection with remote server and leave it for couple of minutes/hours.

### Netty version

4.1.15.Final

### JVM version (e.g. `java -version`)

1.8.0_144

### OS version (e.g. `uname -a`)

Windows 2012 R2 , 64 Bit

**Comment by normanmaurer** [comment]
@manish-panwar  its what the JDK gives us so there is not much we can do... Maybe you should open a bug in the openjdk tracker.
