### ISSUE TITLE
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1446)

### ISSUE THREAD

**Issue by ranjankumar03** [netty/netty#7275]
Encountering mentioned issue on app startup.

2017-10-03 05:18:13,854 DEBUG APP=697 COMP=1661 [main] netty.util.internal.PlatformDependent0:351 - -Dio.netty.noUnsafe: false
2017-10-03 05:18:13,855 DEBUG APP=697 COMP=1661 [main] netty.util.internal.PlatformDependent0:102 - sun.misc.Unsafe.theUnsafe: available
2017-10-03 05:18:13,856 DEBUG APP=697 COMP=1661 [main] netty.util.internal.PlatformDependent0:126 - sun.misc.Unsafe.copyMemory: available
2017-10-03 05:18:13,857 DEBUG APP=697 COMP=1661 [main] netty.util.internal.PlatformDependent0:163 - java.nio.Buffer.address: available
2017-10-03 05:18:13,857 DEBUG APP=697 COMP=1661 [main] netty.util.internal.PlatformDependent0:221 - direct buffer constructor: available
2017-10-03 05:18:13,866 DEBUG APP=697 COMP=1661 [main] netty.util.internal.PlatformDependent0:271 - java.nio.Bits.unaligned: available, true
2017-10-03 05:18:13,869 DEBUG APP=697 COMP=1661 [main] netty.util.internal.PlatformDependent0:332 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.ClassNotFoundException: jdk.internal.misc.Unsafe
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at com.cme.sas.bootstrap.starter.AppClassLoader.loadClass(AppClassLoader.java:236)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:290)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:283)
        at io.netty.util.internal.PlatformDependent.getSystemClassLoader(PlatformDependent.java:641)
        at io.netty.util.internal.PlatformDependent.isAndroid0(PlatformDependent.java:665)
        at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:65)
        at io.netty.util.Signal.<clinit>(Signal.java:31)
        at io.netty.util.concurrent.DefaultPromise.<clinit>(DefaultPromise.java:43)
        at io.netty.util.concurrent.GlobalEventExecutor.<init>(GlobalEventExecutor.java:44)
        at io.netty.util.concurrent.GlobalEventExecutor.<clinit>(GlobalEventExecutor.java:41)
        at com.datastax.driver.core.Connection$Factory.<init>(Connection.java:752)
        at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1446)
        at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:399)

**Comment by slandelle** [comment]
That's not an issue. That's just a DEBUG log being too verbose (that's been fixed but you're running an older version without the fix) that you just see because you have DEBUG logging level enabled.

**Comment by normanmaurer** [comment]
As @slandelle said... Closing
