### ISSUE TITLE
throwing exception on h2c upgrade

### ISSUE THREAD

**Issue by mosesn** [netty/netty#7280]
I occasionally see a failure when I'm doing an h2c upgrade, although not very frequently.

The exception looks like:

```
WAR [20171004-22:30:36.811] twitter: Unhandled exception in connection with /10.70.113.107:40092, shutting down connection
WAR [20171004-22:30:36.811] twitter: io.netty.handler.codec.http2.Http2Exception: Attempting to return too many bytes for stream 0
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:128)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.returnProcessedBytes(DefaultHttp2LocalFlowController.java\
:432)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController$DefaultState.consumeBytes(DefaultHttp2LocalFlowController.java:441)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.DefaultHttp2LocalFlowController.consumeBytes(DefaultHttp2LocalFlowController.java:190)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2FrameCodec.consumeBytes(Http2FrameCodec.java:315)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2MultiplexCodec.onBytesConsumed(Http2MultiplexCodec.java:384)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2MultiplexCodec$DefaultHttp2StreamChannel$Http2ChannelUnsafe.doRead0(Http2MultiplexCodec.java:947)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2MultiplexCodec$DefaultHttp2StreamChannel.fireChildRead(Http2MultiplexCodec.java:734)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2MultiplexCodec.onHttp2StreamFrame(Http2MultiplexCodec.java:286)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2MultiplexCodec.onHttp2Frame(Http2MultiplexCodec.java:221)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2FrameCodec$FrameListener.onDataRead(Http2FrameCodec.java:527)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.InboundHttpToHttp2Adapter.handle(InboundHttpToHttp2Adapter.java:67)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http2.Http2FrameCodec.userEventTriggered(Http2FrameCodec.java:250)
WAR [20171004-22:30:36.811] twitter:     at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
WAR [20171004-22:30:36.811] twitter:     at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
WAR [20171004-22:30:36.811] twitter:     at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler$1.operationComplete(HttpServerUpgradeHandler.java:329)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler$1.operationComplete(HttpServerUpgradeHandler.java:318)
WAR [20171004-22:30:36.811] twitter:     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
WAR [20171004-22:30:36.811] twitter:     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
WAR [20171004-22:30:36.811] twitter:     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
WAR [20171004-22:30:36.811] twitter:     at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
WAR [20171004-22:30:36.811] twitter:     at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
WAR [20171004-22:30:36.811] twitter:     at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler.upgrade(HttpServerUpgradeHandler.java:318)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler.decode(HttpServerUpgradeHandler.java:239)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler.decode(HttpServerUpgradeHandler.java:40)
WAR [20171004-22:30:36.811] twitter:     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
WAR [20171004-22:30:36.811] twitter:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
```

And it comes from [here](https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2LocalFlowController.java?utf8=%E2%9C%93#L432-L433):

```
        private void returnProcessedBytes(int delta) throws Http2Exception {
            if (processedWindow - delta < window) {
                throw streamError(stream.id(), INTERNAL_ERROR,
                        "Attempting to return too many bytes for stream %d", stream.id());
            }
            processedWindow -= delta;
        }
```

Any idea what's going on here?  Is the issue that the client isn't respecting flow control?

**Comment by mosesn** [comment]
Also what stream has stream id 0?

**Comment by mosesn** [comment]
It looks like `ConnectionStream` has stream id 0 trying to figure out what that means in context of everything else.

**Comment by mosesn** [comment]
OK, so it looks like that means it's not an error specific to a single stream, but instead an error with the overall connection?

```
     * @return If the {@code id} is not
     * {@link Http2CodecUtil#CONNECTION_STREAM_ID} then a {@link Http2Exception.StreamException} will be returned.
     * Otherwise the error is considered a connection error and a {@link Http2Exception} is returned.
```

**Comment by mosesn** [comment]
I think I've figured out the problem.  In the http/2 upgrade, we upgrade the http/1.1 message to http/2

```
InboundHttpToHttp2Adapter.handle(ctx, connection(), decoder().frameListener(), upgrade.upgradeRequest().retain());
```

However, I don't think the h2c upgrade message, which is an http/1.1 message with the upgrade:h2c header, should not be eligible for flow control.  The spec isn't super clear here however.

@normanmaurer @Scottmitch @ejona86 any idea what we should do here?

**Comment by ejona86** [comment]
Yeah, the request is fully received (half closed) and so doesn't need any flow control. The response follows flow control like normal.

This problem would happen reliably with PUT/POST, but wouldn't be triggered by the GET/OPTIONS that we typically see.

This seems to be a problem with the InboundHttpToHttp2Adapter abstraction: it doesn't work with consumeBytes, but it does correctly [throw away the onDataRead return value](https://github.com/netty/netty/blob/74f24a5/codec-http2/src/main/java/io/netty/handler/codec/http2/InboundHttpToHttp2Adapter.java?utf8=%E2%9C%93#L67) which is the simpler form of flow control. Worst-case, I guess we could hack `Http2FrameCodec.consumeBytes` to do nothing when it's the upgrade stream, say, with logic like `streamId == 1 && stream.getProperty(upgradeKey)` (we'd create upgradeKey; it doesn't exist now). Doing it "right" looks pretty ugly; if we leave `InboundHttpToHttp2Adapter` as-is it deserves a warning.

**Comment by mosesn** [comment]
Cool, what do you think the next step should be?  Adding this hack?  And right now the only work-around I can think of is extending Http2MultiplexCodecBuilder . . . anything else I could plausibly do?

**Comment by mosesn** [comment]
I've also found

```
WAR [20171006-20:49:51.503] twitter: java.lang.IllegalArgumentException: Invalid value for te: deflate,gzip;q=0.3
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.http2.HttpConversionUtil.toHttp2Headers(HttpConversionUtil.java:423)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.http2.HttpConversionUtil.toHttp2Headers(HttpConversionUtil.java:399)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.http2.InboundHttpToHttp2Adapter.handle(InboundHttpToHttp2Adapter.java:61)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.http2.Http2FrameCodec.userEventTriggered(Http2FrameCodec.java:250)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler$1.operationComplete(HttpServerUpgradeHandler.java:329)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler$1.operationComplete(HttpServerUpgradeHandler.java:318)
WAR [20171006-20:49:51.503] twitter:     at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
WAR [20171006-20:49:51.503] twitter:     at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
WAR [20171006-20:49:51.503] twitter:     at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
WAR [20171006-20:49:51.503] twitter:     at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler.upgrade(HttpServerUpgradeHandler.java:318)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler.decode(HttpServerUpgradeHandler.java:239)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.http.HttpServerUpgradeHandler.decode(HttpServerUpgradeHandler.java:40)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
WAR [20171006-20:49:51.503] twitter:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
WAR [20171006-20:49:51.503] twitter:     at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
WAR [20171006-20:49:51.503] twitter:     (...more...)
```

Which makes it seem like we should be stripping more headers here.  The only valid TE header is "trailers".

**Comment by ejona86** [comment]
Adding the hack sounds good to me. It's quick and easy. We can fix it up better if/when we figure out an alternative.

As far as workarounds... If patching Netty isn't an option, then yeah, extending Http2MultiplexCodecBuilder is probably about the only option.

**Comment by normanmaurer** [comment]
@mosesn ping

**Comment by mosesn** [comment]
@normanmaurer I've been busy with shipping something, haven't had a chance to look at this yet, but I'm still happy to add the hack when I have time.  I was able to work around this by extending the bejeezus out of Http2MultiplexCodecBuilder.

**Comment by ximyu** [comment]
@mosesn could you be more specific how did you extend Http2MultiplexCodecBuilder to workaround this issue?  Thanks.

**Comment by mosesn** [comment]
@ximyu sure, I have an open source copy you can take a look at: https://github.com/twitter/finagle/blob/develop/finagle-http2/src/main/scala/io/netty/handler/codec/http2/UpgradeMultiplexCodecBuilder.scala

**Comment by ximyu** [comment]
Ah, I see. Thanks a lot for sending the code snippet.  Having to put this class under package io.netty.handler.codec.http2 is really annoying :)

**Comment by normanmaurer** [comment]
@mosesn so you think this is also what we should do in netty ?

**Comment by mosesn** [comment]
@normanmaurer yep, but we should have something nice around it so we only do it for the h2c upgrade (and not the prior knowledge or alpn upgrades).

**Comment by mosesn** [comment]
I have most of a fix here, but I need a bit more help with testing it: https://github.com/netty/netty/pull/7400
