### ISSUE TITLE
Many tcp conections in ESTABLISHED, while all the client has closed the connections. 

### ISSUE THREAD

**Issue by allan00** [netty/netty#7292]
When doing stress test in my server ( EpollEventLoopGroup), i met this situation after 8 hour(90000 TPS by 18000 connections).
The server has a slow reponse. There exists many tcp connection in  **ESTABLISHED**(using netstat) in my server,  while all the clients has closed the connections. Many bytes are blocked in Recv-Q of these channels(using netstat to see ). 

Proto Recv-Q          Send-Q                Local Address               Foreign Address             State      
tcp    41480    0 ::ffff:10.255.2.35:10911    ::ffff:10.255.1.145:59666   ESTABLISHED 18554/java  off(0.00/0/0)
tcp    33283    0 ::ffff:10.255.2.35:10911    ::ffff:10.255.1.220:39666   ESTABLISHED 18554/java  off(0.00/0/0)
tcp    51933    0 ::ffff:10.255.2.35:10911    ::ffff:10.255.0.173:39666   ESTABLISHED 18554/java  off(0.00/0/0)

My server codes
this.eventLoopGroupBoss = new EpollEventLoopGroup(1, new ThreadFactory() {
                private AtomicInteger threadIndex = new AtomicInteger(0);

                public Thread newThread(Runnable r) {
                    return new Thread(r, String.format("NettyBossEpoll_%d", this.threadIndex.incrementAndGet()));
                }
            });

            this.eventLoopGroupSelector = new EpollEventLoopGroup(nettyServerConfig.getServerSelectorThreads(), new ThreadFactory() {
                private AtomicInteger threadIndex = new AtomicInteger(0);
                private int threadTotal = nettyServerConfig.getServerSelectorThreads();
                public Thread newThread(Runnable r) {
                    return new Thread(r, String.format("NettyServerEPOLLSelector_%d_%d", threadTotal, this.threadIndex.incrementAndGet()));
                }
            });

ServerBootstrap childHandler =
            this.serverBootstrap.group(this.eventLoopGroupBoss, this.eventLoopGroupSelector)
                .channel(useEpoll() ? EpollServerSocketChannel.class : NioServerSocketChannel.class)
                .option(ChannelOption.SO_BACKLOG, 1024)
                .option(ChannelOption.SO_REUSEADDR, true)
                .option(ChannelOption.SO_KEEPALIVE, false)
                .childOption(ChannelOption.TCP_NODELAY, true)
                .childOption(ChannelOption.SO_SNDBUF, 32000)
                .childOption(ChannelOption.SO_RCVBUF, 32000)
                .localAddress(new InetSocketAddress(this.nettyServerConfig.getListenPort()))
                .childHandler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    public void initChannel(SocketChannel ch) throws Exception {
                        ch.pipeline().addLast(
                            defaultEventExecutorGroup,
                            new NettyEncoder(),
                            new NettyDecoder(),
                            new IdleStateHandler(0, 0, nettyServerConfig.getServerChannelMaxIdleTimeSeconds()),
                            new NettyConnectManageHandler(),
                            new NettyServerHandler());
                    }
                });

Netty version    4.0.36 final
JVM version    1.8.0_131

**Comment by allan00** [comment]
`this.eventLoopGroupBoss = new EpollEventLoopGroup(1, new ThreadFactory() {
                private AtomicInteger threadIndex = new AtomicInteger(0);

                public Thread newThread(Runnable r) {
                    return new Thread(r, String.format("NettyBossEpoll_%d", this.threadIndex.incrementAndGet()));
                }
            });

            this.eventLoopGroupSelector = new EpollEventLoopGroup(nettyServerConfig.getServerSelectorThreads(), new ThreadFactory() {
                private AtomicInteger threadIndex = new AtomicInteger(0);
                private int threadTotal = nettyServerConfig.getServerSelectorThreads();
                public Thread newThread(Runnable r) {
                    return new Thread(r, String.format("NettyServerEPOLLSelector_%d_%d", threadTotal, this.threadIndex.incrementAndGet()));
                }
            });

ServerBootstrap childHandler =
            this.serverBootstrap.group(this.eventLoopGroupBoss, this.eventLoopGroupSelector)
                .channel(useEpoll() ? EpollServerSocketChannel.class : NioServerSocketChannel.class)
                .option(ChannelOption.SO_BACKLOG, 1024)
                .option(ChannelOption.SO_REUSEADDR, true)
                .option(ChannelOption.SO_KEEPALIVE, false)
                .childOption(ChannelOption.TCP_NODELAY, true)
                .childOption(ChannelOption.SO_SNDBUF, 32000)
                .childOption(ChannelOption.SO_RCVBUF, 32000)
                .localAddress(new InetSocketAddress(this.nettyServerConfig.getListenPort()))
                .childHandler(new ChannelInitializer<SocketChannel>() {
                    @Override
                    public void initChannel(SocketChannel ch) throws Exception {
                        ch.pipeline().addLast(
                            defaultEventExecutorGroup,
                            new NettyEncoder(),
                            new NettyDecoder(),
                            new IdleStateHandler(0, 0, nettyServerConfig.getServerChannelMaxIdleTimeSeconds()),
                            new NettyConnectManageHandler(),
                            new NettyServerHandler());
                    }
                });`

**Comment by NiteshKant** [comment]
Data sitting in the Recv-Q maybe because of eventloop being slow/busy/blocked or AUTO_READ off and no read request made. You may want to check that first. For debugging, you can add a `io.netty.channel.LoggingHandler` which will give you insights into what is happening on the channel.

**Comment by allan00** [comment]
@NiteshKant  Tks. This situation happens occasionally.  I've add LogginHandler in my netty server, so i can know what happens in netty when meeting this situation next time.

**Comment by allan00** [comment]
This is my jstack
[18554.zip](https://github.com/netty/netty/files/1382224/18554.zip)

**Comment by NiteshKant** [comment]
There are a few threads which look like eventloops that do not look happy:

```
"NettyServerCodecThread_2" #70 prio=5 os_prio=0 tid=0x00007f352400bdc0 nid=0x4924 waiting on condition [0x00007f3574550000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
	at java.lang.Thread.sleep(Native Method)
	at java.nio.Bits.reserveMemory(Bits.java:683)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:672)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:234)
	- locked <0x00000005c2a671e0> (a io.netty.buffer.PoolArena$DirectArena)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:210)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:138)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:270)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:177)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:168)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:121)
	at io.netty.handler.codec.MessageToByteEncoder.allocateBuffer(MessageToByteEncoder.java:140)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:619)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:676)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:612)
	at io.netty.handler.timeout.IdleStateHandler.write(IdleStateHandler.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:619)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:676)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:612)
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:619)
	at io.netty.channel.AbstractChannelHandlerContext.access$1800(AbstractChannelHandlerContext.java:32)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:904)
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:956)
	at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:889)
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:748)
```

Looks like you do not have enough direct memory.

**Comment by normanmaurer** [comment]
+1... It seems like you allocate more direct memory then your system provides and so it tries to trigger a GC run and sleep for some time to let if free up memory. Increase your direct memory limits and see if the problem persists. I will close this issue for now ... Please reopen if you still think its netty fault and did more tests.
