### ISSUE TITLE
Android Issue : NotFoundClassException in android 4.4 below.

### ISSUE THREAD

**Issue by kurniawanrizzki** [netty/netty#7313]
> `10-17 14:17:17.764 18989-22668/com.origin.app W/System.err: java.lang.NoClassDefFoundError: io.netty.channel.nio.NioEventLoopGroup
10-17 14:17:17.772 18989-22668/com.origin.app W/System.err:     at com.origin.app.util.socket.SocketCommunicator.getInstance(SocketCommunicator.java:48)
10-17 14:17:17.772 18989-22668/com.origin.app W/System.err:     at com.origin.app.util.socket.SocketHandler.initCommunicator(SocketHandler.java:70)
10-17 14:17:17.772 18989-22668/com.origin.app W/System.err:     at com.origin.app.util.socket.SocketHandler.<init>(SocketHandler.java:58)
10-17 14:17:17.772 18989-22668/com.origin.app W/System.err:     at com.origin.app.controller.MessageRequestController.sendViaAvailableChannel(MessageRequestController.java:144)
10-17 14:17:17.780 18989-22668/com.origin.app W/System.err:     at com.origin.app.controller.MessageRequestController.sendRequestMessage(MessageRequestController.java:134)
10-17 14:17:17.780 18989-22668/com.origin.app W/System.err:     at com.origin.app.services.CommunicationService.onHandleIntent(CommunicationService.java:49)
10-17 14:17:17.780 18989-22668/com.origin.app W/System.err:     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
10-17 14:17:17.780 18989-22668/com.origin.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
10-17 14:17:17.780 18989-22668/com.origin.app W/System.err:     at android.os.Looper.loop(Looper.java:137)
10-17 14:17:17.788 18989-22668/com.origin.app W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:60)`

Why this error always occurred in android 4.4 below even the netty's version downgraded? (in this case we use 4.2).

**Comment by kurniawanrizzki** [comment]
It just because of multidex, as a note please to follow this link https://developer.android.com/studio/build/multidex.html if you have a problem related with 64K methods before.
