### ISSUE TITLE
When netty_transport_native_epoll_x86_64 cannot be found, stacktrace is logged

### ISSUE THREAD

**Issue by jcrossley** [netty/netty#7319]
### Expected behavior
When the library "netty_transport_native_epoll_x86_64" cannot be loaded, log the error at DEBUG but don't log a "scary" stack trace that users may construe as an error, when, in fact, the library is loaded fine through another mechansism, which is logged later:
`1582 [main] DEBUG io.netty.util.internal.NativeLibraryLoader  - Successfully loaded the library /tmp/libnetty_transport_native_epoll_x86_646303477118324058101.so`

### Actual behavior
"scary" stacktrace is logged if users are running with debug logging, and they wonder if there is an error.

```
05:30:46.950 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
05:30:47.013 [main] DEBUG io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:229)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:221)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:207)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:118)
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:199)
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61)
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:33)
	at com.twitter.finagle.netty4.nativeEpoll$.enabled$lzycompute(nativeEpoll.scala:14)
	at com.twitter.finagle.netty4.nativeEpoll$.enabled(nativeEpoll.scala:14)
	at 

```
### Netty version
4.1.16.Final

**Comment by linking12** [comment]
I think this is same with #7320

**Comment by johnou** [comment]
@jcrossley what version of netty-tcnative is on the classpath?

**Comment by linking12** [comment]
@johnou  netty-tcnative is my exception and netty-tcnative is  2.0.5.Final

http://search.maven.org/remotecontent?filepath=io/netty/netty-tcnative/2.0.6.Final/netty-tcnative-2.0.6.Final-osx-x86_64.jar

**Comment by johnou** [comment]
@jcrossley @linking12 please make sure you are running netty-tcnative 2.0.6.Final with 4.1.16.Final, there were changes to the native library filenames.

**Comment by slandelle** [comment]
@linking12 You wrote you're using netty-tcnative **2.0.5.Final** but I think Netty 4.1.16.Final is supposed to be used with netty-tcnative **2.0.6.Final** (just like in your link to search.maven.org).

**Comment by linking12** [comment]
@johnou @slandelle 
sorry,I use 2.0.5.Final follow 
https://github.com/grpc/grpc-java/blob/master/SECURITY.md

2.0.6.Final is ok

thanks

**Comment by jcrossley** [comment]
@johnou yep I'm using with 2.0.6.Final with 4.1.16.Final. Here's the full sequence of logs:
1471 [main] DEBUG io.netty.util.internal.NativeLibraryLoader  - Unable to load the library ```
'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
...
1476 [main] DEBUG io.netty.util.internal.NativeLibraryLoader  - netty_transport_native_epoll_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /tmp
...
1582 [main] DEBUG io.netty.util.internal.NativeLibraryLoader  - Successfully loaded the library /tmp/libnetty_transport_native_epoll_x86_646303477118324058101.so
```

**Comment by johnou** [comment]
@jcrossley what platform and architecture?

**Comment by jcrossley** [comment]
@johnou x86_64 GNU/Linux and Centos 7.

**Comment by normanmaurer** [comment]
Actually we log the stack trace to make it easier to debug stuff. Do you think its too noisy ?

**Comment by johnou** [comment]
tbh I would expect things to be noisy if the log level is set to DEBUG.

**Comment by jcrossley** [comment]
@johnou I would expect it to log, yes, but would be great if it didn't have those stacktraces, too. Our customers are routinely alarmed by them.

**Comment by normanmaurer** [comment]
@jcrossley IMHO you should expect to have a noisy log if you use debug logging. Why not just change the log level if you think its too verbose ?

**Comment by jcrossley** [comment]
@normanmaurer our customers sometimes set it to debug. But I understand what you're saying, fair point. I'll close this. Thanks!.

**Comment by pcj** [comment]
I agree with @jcrossley on this one.  It's plenty information to just log the attempted load path in debug mode.  Stacktrace is not expected behavior for a java app, even at debug level.  Wastes people's time (like mine!).

**Comment by enesunal** [comment]
Setting log level to debug for my project doesn't mean I set it to debug for libraries. Please exclude the stack traces when you're releasing for production. It's the default log level(debug) for almost any developer who tries to make things works, these stacktraces just make initial development **harder**. If it's important, you can even print a warning explaining the issue.

**Comment by DeclanWang** [comment]
this stack traces information on debug level actually confuse me

**Comment by shatestest** [comment]
Hi , finally what is the solution ? I am using but still getting same error ...what is the solution for this error :

**Comment by johnou** [comment]
The stacktrace is essential for debugging native library loading problems (especially when Netty is shaded).

**Comment by Ravipatel401** [comment]
Hey Guys,

**Tying to identifying this issues from last 4 days but found the perfect solution that is just checked when** 
###  Experiment 1. :- Java 8 32bit with eclipse 32 bit :---- **Failed to load any of the given libraries: [netty_tcnative_windows_x86_32, netty_tcnative_x86_32, netty_tcnative]**
**Experiment 2.:- Java 8 64bit  with Eclipse Luna 64 bit 👍 :- Worked Without Error.**

Thanks

**Comment by BlackHe** [comment]
my project also find this problem , I set log level to 'INFO' , but I want to know this is why? and how to solve the trouble

**Comment by Ravipatel401** [comment]
@BlackHe Can you Share details about Version of jdk ,jre(Java)and OS version  using now?

**Comment by CrazySabri** [comment]
when using redis, same behavior would appear because of nio after the project started and getting value from redis;
I want to asure that the problem have bean solved ever;

**Comment by Kevinlyz** [comment]
> my project also find this problem , I set log level to 'INFO' , but I want to know this is why? and how to solve the trouble

So did I, have you find the reason why this appear?

**Comment by Ravipatel401** [comment]
Please share Configuration of system and Library version and JAVAC version

**Comment by hartmut27** [comment]
as stated [here](https://github.com/netty/netty/issues/8263) it's a "loading strategy until succeed"  tagged with `DEBUG` log messages, for me this explains why this is needed, it has the character of an "false positive", and switching away from DEBUG log level or suppressing this message by means of the log library could work as a work-around

**Comment by murad-mirzabalaev** [comment]
**Env**: 

OS: `CentOS Linux release 7.7.1908 (Core)`

```
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```
**ClassPath**:
```
ls /opt/zookeeper/| grep netty
netty-buffer-4.1.45.Final.jar
netty-codec-4.1.45.Final.jar
netty-common-4.1.45.Final.jar
netty-handler-4.1.45.Final.jar
netty-resolver-4.1.45.Final.jar
netty-tcnative-2.0.31.Final.jar
netty-transport-4.1.45.Final.jar
netty-transport-native-epoll-4.1.45.Final.jar
netty-transport-native-unix-common-4.1.45.Final.jar

```
**Stacktrace**: fragment of zookeeper log

```
2020-07-14 03:45:56,223 [myid:1] - DEBUG [main:NativeLibraryLoader@344] - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
at java.lang.Runtime.loadLibrary0(Runtime.java:871)
at java.lang.System.loadLibrary(System.java:1124)
at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
at java.security.AccessController.doPrivileged(Native Method)
at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:231)
at io.netty.channel.epoll.Native.<clinit>(Native.java:58)
at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
at org.apache.zookeeper.common.NettyUtils.newNioOrEpollEventLoopGroup(NettyUtils.java:74)
at org.apache.zookeeper.server.NettyServerCnxnFactory.<init>(NettyServerCnxnFactory.java:499)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.zookeeper.server.ServerCnxnFactory.createFactory(ServerCnxnFactory.java:168)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:166)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:136)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
2020-07-14 03:45:56,226 [myid:1] - DEBUG [main:NativeLibraryLoader@140] - netty_transport_native_epoll_x86_64 cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
at java.lang.Runtime.loadLibrary0(Runtime.java:871)
at java.lang.System.loadLibrary(System.java:1124)
at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:231)
at io.netty.channel.epoll.Native.<clinit>(Native.java:58)
at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
at org.apache.zookeeper.common.NettyUtils.newNioOrEpollEventLoopGroup(NettyUtils.java:74)
at org.apache.zookeeper.server.NettyServerCnxnFactory.<init>(NettyServerCnxnFactory.java:499)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.zookeeper.server.ServerCnxnFactory.createFactory(ServerCnxnFactory.java:168)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:166)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:136)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
at java.lang.Runtime.loadLibrary0(Runtime.java:871)
at java.lang.System.loadLibrary(System.java:1124)
at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
at java.security.AccessController.doPrivileged(Native Method)
at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
... 14 more
2020-07-14 03:45:56,227 [myid:1] - DEBUG [main:NativeLibraryLoader@344] - Unable to load the library 'netty_transport_native_epoll', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
at java.lang.Runtime.loadLibrary0(Runtime.java:871)
at java.lang.System.loadLibrary(System.java:1124)
at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
at java.security.AccessController.doPrivileged(Native Method)
at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:234)
at io.netty.channel.epoll.Native.<clinit>(Native.java:58)
at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
at org.apache.zookeeper.common.NettyUtils.newNioOrEpollEventLoopGroup(NettyUtils.java:74)
at org.apache.zookeeper.server.NettyServerCnxnFactory.<init>(NettyServerCnxnFactory.java:499)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.zookeeper.server.ServerCnxnFactory.createFactory(ServerCnxnFactory.java:168)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:166)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:136)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
2020-07-14 03:45:56,228 [myid:1] - DEBUG [main:NativeLibraryLoader@140] - netty_transport_native_epoll cannot be loaded from java.library.path, now trying export to -Dio.netty.native.workdir: /tmp
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
at java.lang.Runtime.loadLibrary0(Runtime.java:871)
at java.lang.System.loadLibrary(System.java:1124)
at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:349)
at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:234)
at io.netty.channel.epoll.Native.<clinit>(Native.java:58)
at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
at org.apache.zookeeper.common.NettyUtils.newNioOrEpollEventLoopGroup(NettyUtils.java:74)
at org.apache.zookeeper.server.NettyServerCnxnFactory.<init>(NettyServerCnxnFactory.java:499)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.zookeeper.server.ServerCnxnFactory.createFactory(ServerCnxnFactory.java:168)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:166)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:136)
at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path
at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1871)
at java.lang.Runtime.loadLibrary0(Runtime.java:871)
at java.lang.System.loadLibrary(System.java:1124)
at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
at java.security.AccessController.doPrivileged(Native Method)
at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
... 14 more
2020-07-14 03:45:56,266 [myid:1] - DEBUG [main:MultithreadEventLoopGroup@44] - -Dio.netty.eventLoopThreads: 4
2020-07-14 03:45:56,315 [myid:1] - DEBUG [main:NioEventLoop@106] - -Dio.netty.noKeySetOptimization: false
2020-07-14 03:45:56,315 [myid:1] - DEBUG [main:NioEventLoop@107] - -Dio.netty.selectorAutoRebuildThreshold: 512
2020-07-14 03:45:56,346 [myid:1] - DEBUG [main:PlatformDependent$Mpsc@891] - org.jctools-core.MpscChunkedArrayQueue: available
2020-07-14 03:45:56,352 [myid:1] - TRACE [main:NioEventLoop@260] - instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@7791a895
2020-07-14 03:45:56,357 [myid:1] - TRACE [main:NioEventLoop@260] - instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@61f8bee4
2020-07-14 03:45:56,357 [myid:1] - TRACE [main:NioEventLoop@260] - instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@7b49cea0
2020-07-14 03:45:56,357 [myid:1] - TRACE [main:NioEventLoop@260] - instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@887af79
2020-07-14 03:45:56,357 [myid:1] - TRACE [main:NioEventLoop@260] - instrumented a special java.util.Set into: sun.nio.ch.EPollSelectorImpl@7fac631b
2020-07-14 03:45:56,388 [myid:1] - INFO  [main:ServerCnxnFactory@169] - Using org.apache.zookeeper.server.NettyServerCnxnFactory as server connection factory
2020-07-14 03:45:56,390 [myid:1] - INFO  [main:ServerCnxnFactory@312] - maxCnxns configured value is 2000.

```


```
2020-07-14 03:45:57,887 [myid:1] - ERROR [nioEventLoopGroup-7-1:NettyServerCnxnFactory$CertificateVerifier@434] - Unsuccessful handshake with session 0x0
2020-07-14 03:45:57,887 [myid:1] - DEBUG [nioEventLoopGroup-7-1:NettyServerCnxn@106] - close called for session id: 0x0
2020-07-14 03:45:57,887 [myid:1] - DEBUG [nioEventLoopGroup-7-1:NettyServerCnxn@117] - cnxns size:0
2020-07-14 03:45:57,890 [myid:1] - WARN  [nioEventLoopGroup-7-1:NettyServerCnxnFactory$CnxnChannelHandler@273] - Exception caught
io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 0000002d000000000000000000000000000017700000000000000000000000100000000000000000000000000000000000
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 0000002d000000000000000000000000000017700000000000000000000000100000000000000000000000000000000000
at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1198)
at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:498)
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437)
... 17 more
```

**Comment by maoling** [comment]
@murad-mirzabalaev please join the discussion of [ZOOKEEPER-3940](https://issues.apache.org/jira/browse/ZOOKEEPER-3940)
