### ISSUE TITLE
NPN clients fail when talking to NPN servers that don't advertise

### ISSUE THREAD

**Issue by mosesn** [netty/netty#7346]
### Expected behavior
Netty clients that support NPN should be able to talk to any server that supports NPN.

### Actual behavior
When netty clients using tcnative + NPN try to talk to servers that support NPN but don't advertise any protocols, netty barfs.

### Steps to reproduce
Use an SslContextBuilder, and call the applicationProtocolConfig, passing an ApplicationProtocolConfig where the Protocol is either Protocol.NPN_AND_ALPN or Protocol.NPN.  Then talk to a server that supports NPN but doesn't advertise NPN protocols, like happylifestyle.com or ossifrage.net.

### Minimal yet complete reproducer code (or URL to code)
Using finagle:

```
import com.twitter.util.Await
import com.twitter.finagle.Http
import com.twitter.finagle.http.Request
val req = Request("/")
req.host = "happylifestyle.com"
val client = Http.client.configuredParams(Http.Http2).withTls("happylifestyle.com").newService("happylifestyle.com:443")
Await.result(client(req))
```

You can also do this when talking to ossifrage.net.

Note if you use `openssl s_client -tlsextdebug -connect ossifrage.net:443 -nextprotoneg 'h2,http/1.1'` that it doesn't advertise any protocols.

### Netty version

4.1.16.Final

### tcnative version

2.0.6.Final

### JVM version (e.g. `java -version`)

JDK8

### OS version (e.g. `uname -a`)

Darwin tw-mbp13-mnakamura.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

**Comment by ryanoneill** [comment]
FYI, I think @mosesn meant to put `4.1.16.Final` as the version of Netty that we're using, not `4.1.6.Final`.

**Comment by normanmaurer** [comment]
Will check tomorrow

**Comment by normanmaurer** [comment]
@mosesn what you mean with "barf" ? Handshake fails or what ?

**Comment by normanmaurer** [comment]
@mosesn I just checked your code in finagle and I think what you want to use is `ApplicationProtocolConfig.SelectorFailureBehavior.CHOOSE_MY_LAST_PROTOCOL`:
https://github.com/twitter/finagle/commit/454761f89e86daf15e0beb32eda0e9fa6bd4916c#diff-2ccffbb99fd97f6986181b0368bcfd55R98

 This will give you the "same" behavior as `openssl s_client`

**Comment by normanmaurer** [comment]
@mosesn ping

**Comment by normanmaurer** [comment]
@mosesn ping again :)

**Comment by mosesn** [comment]
@normanmaurer sorry, it's a holiday in the US this week (Thanksgiving), so I'm not going to get to this until next week.

**Comment by mosesn** [comment]
@normanmaurer hmm, there's a comment that says that only NO_ADVERTISE is supported by both JDK and native?  Do you know if that's still the case?

**Comment by normanmaurer** [comment]
@mosesn I think this is still true...  (maybe not for java9 tho).

**Comment by mosesn** [comment]
@normanmaurer we're not switching to java9, unfortunately.  We're not going to pick up the java9 goodies until the next LTS java.

**Comment by normanmaurer** [comment]
@mosesn I hear ya... can you please test my suggestion with openssl provider and let me know if these work ?

**Comment by mosesn** [comment]
@normanmaurer it doesn't seem to fix the issue with boringssl.

**Comment by normanmaurer** [comment]
hmm... what about using openssl ? I tested it locally and it seems to have worked :(

**Comment by mosesn** [comment]
@normanmaurer it seems to fail *differently* with openssl.  Now the client hangs.  Without NPN, it returns.  With boringssl I get these errors:

```
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:10000095:SSL routines:OPENSSL_internal:ERROR_PARSING_EXTENSION
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mosesn** [comment]
@normanmaurer I don't know, we are having trouble updating to latest netty, and we've disabled NPN on the client-side.

**Comment by normanmaurer** [comment]
Ok... anything I can help with to resolve the trouble ? What trouble you have ?

**Comment by normanmaurer** [comment]
@mosesn <3 thanks for closing the loop.

**Comment by mosesn** [comment]
Ah, to clarify, the issue around draining was what made it so we couldn't upgrade–I haven't had a chance to check if NPN clients work with current netty yet.

**Comment by normanmaurer** [comment]
@mosesn should we close this or what now ?

**Comment by normanmaurer** [comment]
Let me just close this for now. @mosesn please re-open if you still think there is an issue.
