### ISSUE TITLE
netty dns resolver - issue with CNAME-only resolution

### ISSUE THREAD

**Issue by mazurkin** [netty/netty#7359]
I need to resolve domain "beinghacked.blogspot.fr" (used only just an example) to IPv4 address

dig report:
```
$ dig @8.8.8.8 beinghacked.blogspot.fr ANY

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @8.8.8.8 beinghacked.blogspot.fr ANY
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 10855
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;beinghacked.blogspot.fr.	IN	ANY

;; ANSWER SECTION:
beinghacked.blogspot.fr. 599	IN	CNAME	blogspot.l.googleusercontent.com.

;; Query time: 21 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Thu Nov 02 11:26:12 MSK 2017
;; MSG SIZE  rcvd: 98
```

nslookup report:
```
$ nslookup beinghacked.blogspot.fr
Server:		10.201.9.35
Address:	10.201.9.35#53

Non-authoritative answer:
beinghacked.blogspot.fr	canonical name = blogspot.l.googleusercontent.com.
Name:	blogspot.l.googleusercontent.com
Address: 172.217.12.161
```

### Expected behavior

netty dns resolves "beinghacked.blogspot.fr" to "172.217.12.161" like InetAddress.getByName() does

### Actual behavior

netty dns reports "java.net.UnknownHostException: failed to resolve 'fsnusantara.blogspot.fr' after 2 queries"

### Steps to reproduce

run org.test.DnsTest#testAsyncCname in https://github.com/mazurkin/test-netty-dns

### Minimal yet complete reproducer code (or URL to code)

https://github.com/mazurkin/test-netty-dns

### Netty version

    <version.netty>4.1.16.Final</version.netty>
    <version.netty-dns>4.1.16.Final</version.netty-dns>

### JVM version (e.g. `java -version`)

    jdk1.8.0_91

### OS version (e.g. `uname -a`)

    4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mazurkin** [comment]
I just left all DnsNameResolver options by default state and now it works, please close the issue.

**Comment by mazurkin** [comment]
ops. the problem appeared again even with default settings:

```
15:09:39.976 [main] ERROR org.test.DnsTest - Fail to resolve address
java.util.concurrent.ExecutionException: java.net.UnknownHostException: failed to resolve 'fsnusantara.blogspot.fr' after 2 queries 
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at org.test.DnsTest.testAsyncCname(DnsTest.java:178)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.net.UnknownHostException: failed to resolve 'fsnusantara.blogspot.fr' after 2 queries 
	at io.netty.resolver.dns.DnsNameResolverContext.finishResolve(DnsNameResolverContext.java:699)
	at io.netty.resolver.dns.DnsNameResolverContext.tryToFinishResolve(DnsNameResolverContext.java:641)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:290)
	at io.netty.resolver.dns.DnsNameResolverContext.query(DnsNameResolverContext.java:280)
	at io.netty.resolver.dns.DnsNameResolverContext.access$600(DnsNameResolverContext.java:60)
	at io.netty.resolver.dns.DnsNameResolverContext$3.operationComplete(DnsNameResolverContext.java:322)
```

synchronous DNS resolving always works for this domain
