### ISSUE TITLE
SslHandler java.lang.IllegalStateException: null at sun.security.ec.ECDHKeyAgreement.deriveKey(Native Method)

### ISSUE THREAD

**Issue by leonchen83** [netty/netty#7391]
### Expected behavior

No Exception Occur  

### Actual behavior

```
java.lang.IllegalStateException: null
	at sun.security.ec.ECDHKeyAgreement.deriveKey(Native Method)
	at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:130)
	at sun.security.ec.ECDHKeyAgreement.engineGenerateSecret(ECDHKeyAgreement.java:163)
	at javax.crypto.KeyAgreement.generateSecret(KeyAgreement.java:648)
	at sun.security.ssl.ECDHCrypt.getAgreedSecret(ECDHCrypt.java:101)
	at sun.security.ssl.ECDHCrypt.getAgreedSecret(ECDHCrypt.java:119)
	at sun.security.ssl.ServerHandshaker.clientKeyExchange(ServerHandshaker.java:1616)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:278)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:919)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:916)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1369)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1324)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1232)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1087)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1122)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:491)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:430)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at java.lang.Thread.run(Thread.java:745)
```
### Netty version
```
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-all</artifactId>
    <version>4.0.50.Final</version>
</dependency>
```
### JVM version (e.g. `java -version`)
oraclejdk
java version "1.8.0_92"
### OS version (e.g. `uname -a`)
`Linux 2.6.32-573.el6.x86_64`

**Comment by normanmaurer** [comment]
Please upgrade to latest netty version and test again

**Comment by normanmaurer** [comment]
@leonchen83 also please upgrade to latest java version (your version is quite old).

**Comment by normanmaurer** [comment]
Please re-open if it still happens
