### ISSUE TITLE
OutOfDirectMemoryError

### ISSUE THREAD

**Issue by lanzhuning** [netty/netty#7396]
-- netty channel exception 192.168.171.76:24637
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 503316480, max: 515375104)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:615)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:569)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:181)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:172)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:133)
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:80)
	at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:71)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:968)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:401)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

**Comment by lanzhuning** [comment]
Version  4.1.12.Final

**Comment by Scottmitch** [comment]
please update your version of Netty and provide a heap dump.

**Comment by albertok** [comment]
Make sure you are not writing to your receivers faster than they can handle.

See http://normanmaurer.me/presentations/2014-twitter-meetup-netty/slides.html#9.0

**Comment by normanmaurer** [comment]
Like @albertok said you most likely write to fast. Please-reopen with more infos if you still think its a netty bug.
