### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by fbettag** [netty/netty#741]
15:56:59.570 WARN  i.n.c.SingleThreadEventExecutor - A task raised an exception.
java.lang.ArrayIndexOutOfBoundsException: null
    at java.util.ArrayDeque.copyElements(ArrayDeque.java:172) ~[na:1.7.0_09]
    at java.util.ArrayDeque.toArray(ArrayDeque.java:756) ~[na:1.7.0_09]
    at io.netty.channel.DefaultChannelHandlerContext$MessageBridge.fill(DefaultChannelHandlerContext.java:1037) ~[thruput-0.9.0-13-g6e3dbfd.jar:na]
    at io.netty.channel.DefaultChannelHandlerContext.fillBridge(DefaultChannelHandlerContext.java:277) ~[thruput-0.9.0-13-g6e3dbfd.jar:na]
    at io.netty.channel.DefaultChannelHandlerContext$6.run(DefaultChannelHandlerContext.java:141) ~[thruput-0.9.0-13-g6e3dbfd.jar:na]
    at io.netty.channel.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:186) ~[thruput-0.9.0-13-g6e3dbfd.jar:na]
    at io.netty.channel.socket.nio.NioEventLoop.run(NioEventLoop.java:247) [thruput-0.9.0-13-g6e3dbfd.jar:na]
    at io.netty.channel.SingleThreadEventExecutor$1.run(SingleThreadEventExecutor.java:80) [thruput-0.9.0-13-g6e3dbfd.jar:na]
    at java.lang.Thread.run(Thread.java:722) [na:1.7.0_09]

**Comment by gaoyn-cn** [comment]
any update? we hava got this issue on ibm jdk

java.lang.ArrayIndexOutOfBoundsException: null
    at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:399) ~[?:1.8.0]
    at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:408) ~[?:1.8.0]
    at com.alibaba.druid.filter.FilterChainImpl.nextFilter(FilterChainImpl.java:421) ~[druid-1.1.5.jar:1.1.5]
