### ISSUE TITLE
grpc mutual authentication issue

### ISSUE THREAD

**Issue by shank9918** [netty/netty#7431]
### Expected behavior
To enable ssl mutual authentication

### Actual behavior
Using PKCS11 as keystore provider and loading certs from HSM.
Client fails during mutual authentication with following error and stacktrace

[DEBUG] 2017-11-22 00:34:21.484 [grpc-default-worker-ELG-2-2] ReferenceCountedOpenSslClientContext - **request of key failed**
 javax.net.ssl.SSLException: java.lang.NullPointerException
        at io.netty.handler.ssl.OpenSslKeyMaterialManager.keyMaterial(OpenSslKeyMaterialManager.java:121) ~[netty-handler-4.1.16.Final.jar!/:4.1.16.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$OpenSslCertificateRequestedCallback.requested(ReferenceCountedOpenSslClientContext.java:249) [netty-handler-4.1.16.Final.jar!/:4.1.16.Final]
        at io.netty.internal.tcnative.SSL.readFromSSL(Native Method) ~[netty-tcnative-boringssl-static-2.0.6.Final.jar!/:2.0.6.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:482) [netty-handler-4.1.16.Final.jar!/:4.1.16.Final]

### Steps to reproduce
Works with JKS store provider but while using PKCS11 it fails.

### Minimal yet complete reproducer code (or URL to code)
Client code:
ManagedChannel channel = null;
try {

	channel = NettyChannelBuilder.forAddress(host, port)
			.sslContext(GrpcSslContexts.forClient()
					.keyManager(this.keyManagerFactory)
					.trustManager(this.trustManagerFactory)
					.build())
			.overrideAuthority(this.authority)
			.build();
} catch (SSLException e) {
	throw new IllegalStateException("gRPC client cannot be started", e);
}

Server Code:
Server server = NettyServerBuilder.forPort(Integer.valueOf(environment.getProperty("grpc.port")))
.sslContext(GrpcSslContexts.configure(SslContextBuilder.forServer(sslUtil.keyManagerFactory())
		.trustManager(sslUtil.trustManagerFactory()))
		.clientAuth(ClientAuth.REQUIRE)
		.build())
.addService(grpcServer)
.build();

### Netty version
<grpc.version>1.7.0</grpc.version>
<netty-tcnative.version>2.0.6.Final</netty-tcnative.version>

### JVM version (e.g. `java -version`)
java version "1.8.0_144"

### OS version (e.g. `uname -a`)
x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@shank9918 can you please also provide an example how it works ?

**Comment by Scottmitch** [comment]
`key.getEncoded()` is returning `null`. Can you show how `this.keyManagerFactory` is being initialized?

[1] https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/PemPrivateKey.java#L63

**Comment by normanmaurer** [comment]
@shank9918 ping

**Comment by shank9918** [comment]
It's using PKCS11 as keystore provider and here is the code which initializes KeyManagerFactory
```
public KeyManagerFactory keyManagerFactory() {
		final String defaultAlgorithm = KeyManagerFactory.getDefaultAlgorithm();
		final String providerProperty = serverProperties.getSsl().getKeyStoreProvider();
		final Provider provider = Security.getProvider(providerProperty);
		final String keyStorePassword = serverProperties.getSsl().getKeyStorePassword();
		KeyManagerFactory keyManagerFactory = null;
		try {
			keyManagerFactory = KeyManagerFactory.getInstance(defaultAlgorithm);
			keyManagerFactory.init(getKeyStore(provider, keyStorePassword), keyStorePassword != null ? keyStorePassword.toCharArray() : null);
		} catch (Exception e) {
			LOGGER.error("Error building KeyManagerFactory.", e);
		}
		return keyManagerFactory;
	}
```

And these are the properties it uses for initialization
server.ssl.key-store=NONE
server.ssl.key-store-type=PKCS11
server.ssl.key-store-provider=SunPKCS11-test

Apart from this other configurations are passed using java.security.properties system param which points to java.security file which then loads the hardware certs

**Comment by normanmaurer** [comment]
@Scottmitch I just noticed this javadoc of `Key`.

```
    /**
     * Returns the key in its primary encoding format, or null
     * if this key does not support encoding.
     *
     * @return the encoded key, or null if the key does not support
     * encoding.
     */
    public byte[] getEncoded();
```

So I think we need to at least do something if null is returned. 

I suspect getEncoded() returns `null` here which seems to be valid. 

@nmittler @ejona86 @carl-mastrangelo FYI

**Comment by ejona86** [comment]
Hmm... and I think Java 9 swaps away from JKS by default, so this will become more noticeable.

Do we know what class the key is?

**Comment by normanmaurer** [comment]
@shank9918 ^^ any idea ? Could you add some logging ?

**Comment by normanmaurer** [comment]
@shank9918 ping

**Comment by normanmaurer** [comment]
@shank9918 ping

**Comment by normanmaurer** [comment]
@ejona86 @carl-mastrangelo any idea what to do wit this one?

**Comment by ErkiHallasoo** [comment]
Any workaround for this problem, when pkcs11 tokens are used for TLS?
