### ISSUE TITLE
ClassFormatError in java8

### ISSUE THREAD

**Issue by biezhi** [netty/netty#7436]
- Netty Version: 4.1.16
- Java Version "1.8.0_151"

Exception log:

```java
 java.lang.ClassFormatError: Attribute name has bad constant pool index 20226 in class file io/netty/util/internal/PlatformDependent
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
	at io.netty.channel.ChannelOption$1.<init>(ChannelOption.java:35)
	at io.netty.channel.ChannelOption.<clinit>(ChannelOption.java:35)
```

during startup.

**Comment by normanmaurer** [comment]
@biezhi happens all the time ? Never saw this before :(

**Comment by normanmaurer** [comment]
@ejona86 @carl-mastrangelo any idea ?

**Comment by carl-mastrangelo** [comment]
Is shading being used, or the class being modified in any way?  If possible, upload the class file from the jar.   The class file from maven central doesn't have that constant anywhere in the file.

**Comment by johnou** [comment]
Could also be a profiler, you might be able to work around it with ```-XX:-UseSplitVerifier``` but that's a bit of a nasty hack..

**Comment by johnou** [comment]
@biezhi care to share what the issue was?

**Comment by biezhi** [comment]
@johnou i,m sorry, this is a problem encountered by a [blade](https://github.com/biezhi/blade) user, he can not reproduce it again, I had to close the issue.
