### ISSUE TITLE
IllegalReferenceCountException with HTTP/2 if maximum number of streams is exceeded

### ISSUE THREAD

**Issue by eun-ice** [netty/netty#7464]
### Expected behavior

No exception should be thrown.

### Actual behavior

Http2ConnectionHandler.exceptionCaught  is  called with an IllegalReferenceCountException

```

io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:273)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1379)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:801)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)

```

### Steps to reproduce

Call this 200 times in an Http2ConnectionHandler

```
        ChannelPromise promise = ctx.newPromise();
        int outStreamId = connection().local().incrementAndGetNextStreamId();
   encoder().writeHeaders(ctx, outStreamId, http2Headers, 0, true, promise);
        flush(ctx);


```

### Netty version

Netty 4.1.17.Final
Tcnative 2.0.7.Final
Using Epoll Transport and OpenSSL

### JVM version (e.g. `java -version`)
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version (e.g. `uname -a`)

Linux 4.9.44+grsec

**Comment by Scottmitch** [comment]
The reproducer you provided is only writing data, but the exception occurs while data is being read. Can you provide a complete reproducer?

**Comment by eun-ice** [comment]
The problem arises without (actively) reading any data and seems to happen on shutdown.
In practice we send push notifications to google, if we send to many at once the above exception happens after netty hits its maximum open streams limit.
We solved it for our use case to limit the number of streams we open, but the exception above hints at an underlying problem. 
Let me check if I can provide a stand-alone reproducer soon. It will take me s few days though

**Comment by normanmaurer** [comment]
@eun-ice let us know once you have more to share

**Comment by normanmaurer** [comment]
@eun-ice any news ?

**Comment by eun-ice** [comment]
@normanmaurer I just tried to build a reprocuder. With netty on both ends, I am not able to reproduce it. It only happens if I connect to google push servers. (https://fcm.googleapis.com/fcm/send)

It seems to me, that google sends data after netty sent a GO_AWAY.



`19:16:30,336  INFO Http2FrameLogger - [id: 0x4072becc, L:/10.2.0.238:55390 - R:fcm.googleapis.com/172.217.18.170:443] OUTBOUND HEADERS: streamId=203 headers=DefaultHttp2Headers[:path: /fcm/send, :method: POST, :scheme: https, :authority: fcm.googleapis.com, accept: application/json, authorization: key=AAAAkQNCgyw:APA91bHxqMqew-L5M5H2W9mY9Aass00jDrSDyKNiYKdhgFcnF7AmoZZq2c7nCWOSgyK7OCDqQqBzV9Yf6DgpyVlx9LIMdXXiXJyQs_nCGFCKZaZLc8dpaA_4hHXzwE747zjrJovfkKK5, content-type: application/json] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
19:16:30,336  INFO Http2FrameLogger - [id: 0x4072becc, L:/10.2.0.238:55390 - R:fcm.googleapis.com/172.217.18.170:443] OUTBOUND DATA: streamId=201 padding=0 endStream=true length=267 bytes=7b200a202022746f223a20226334684557364f59446e6f3a4150413931624678575943785833713753736c5a365f7454694e435559784d36664e674a6e576e72...
19:16:30,337  INFO Http2FrameLogger - [id: 0x4072becc, L:/10.2.0.238:55390 - R:fcm.googleapis.com/172.217.18.170:443] OUTBOUND RST_STREAM: streamId=205 errorCode=7


io.netty.handler.codec.http2.Http2Exception$StreamException: Maximum active streams violated for this endpoint.
	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:881)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:733)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:653)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:166)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder.writeHeaders(DefaultHttp2ConnectionEncoder.java:146)
...
	at de.crown.netty.eventloop.CatchingRunnable.run(CatchingRunnable.java:17)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:273)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)


19:16:30,340  INFO Http2FrameLogger - [id: 0x4072becc, L:/10.2.0.238:55390 - R:fcm.googleapis.com/172.217.18.170:443] OUTBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=
19:16:30,342  INFO Http2FrameLogger - [id: 0x4072becc, L:/10.2.0.238:55390 - R:fcm.googleapis.com/172.217.18.170:443] OUTBOUND DATA: streamId=203 padding=0 endStream=true length=267 bytes=7b200a202022746f223a20226334684557364f59446e6f3a4150413931624678575943785833713753736c5a365f7454694e435559784d36664e674a6e576e72...
19:16:30,361  INFO Http2FrameLogger - [id: 0x4072becc, L:/10.2.0.238:55390 - R:fcm.googleapis.com/172.217.18.170:443] INBOUND HEADERS: streamId=65 headers=DefaultHttp2Headers[:status: 200, content-type: application/json; charset=UTF-8, date: Thu, 21 Dec 2017 18:16:30 GMT, expires: Thu, 21 Dec 2017 18:16:30 GMT, cache-control: private, max-age=0, x-content-type-options: nosniff, x-frame-options: SAMEORIGIN, x-xss-protection: 1; mode=block, server: GSE, alt-svc: hq=":443"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=":443"; ma=2592000; v="41,39,38,37,35", accept-ranges: none, vary: Accept-Encoding] padding=0 endStream=false
19:16:30,362  INFO Http2FrameLogger - [id: 0x4072becc, L:/10.2.0.238:55390 - R:fcm.googleapis.com/172.217.18.170:443] INBOUND DATA: streamId=65 padding=0 endStream=false length=143 bytes=7b226d756c7469636173745f6964223a353734353237363935393236363534303237382c2273756363657373223a312c226661696c757265223a302c2263616e...

19:16:30,368 ERROR 
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:273)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1379)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)`

**Comment by eun-ice** [comment]
Ok, I close this issue.

I was releasing the ByteBuf here:
```
    public int onDataRead(ChannelHandlerContext ctx, int streamId, ByteBuf data, int padding, boolean endOfStream) {
   if (error) {
         ReferenceCountUtil.release(data);
         return 0;
   }
```

However, the ByteBuf data does NOT need to be released.

**Comment by normanmaurer** [comment]
@eun-ice ah yes... all `on*` methods of this class will "NOT" take ownership of the buffer.

**Comment by Scottmitch** [comment]
thanks for closing the loop @eun-ice

**Comment by eun-ice** [comment]
Sorry for bothering you guys and thanks for looking into it.
