### ISSUE TITLE
SingleThreadEventExecutor stops working after 14 tasks, upcoming tasks are never executed

### ISSUE THREAD

**Issue by konsultaner** [netty/netty#7498]
### Expected behavior
Should execute the tasks and call their run method after a while. This is related to an earlier [issue](https://github.com/netty/netty/issues/7488) I posted here: 

### Actual behavior
After 14 `offerTask` calls the BaseMpscLinkedArrayQueue fills up its buffer and never executes them. 

### Steps to reproduce
This is the hard part. It is a huge project I'm working in. I could offer a quick teamviewer session, which shows the issue in about 1 minute. you could send me a mail to burkhardt[at]konsultaner.de

The issue starts here:

    @Override
    public void execute(Runnable task) {
        if (task == null) {
            throw new NullPointerException("task");
        }

        boolean inEventLoop = inEventLoop();
        if (inEventLoop) {
            addTask(task);
        } else {
            startThread();
            // THIS IS WHERE ADDTASK IS CALLED, BUT THE TASK IS NEVER EXECUTED
            addTask(task);
            if (isShutdown() && removeTask(task)) {
                reject();
            }
        }

        if (!addTaskWakesUp && wakesUpForTask(task)) {
            wakeup(inEventLoop);
        }
    }

In the BaseMpscLinkedArrayQueue class this is the last action before nothing happens

    public boolean offer(E e) {
        if (null == e) {
            throw new NullPointerException();
        } else {
            while(true) {
                while(true) {
                    long offset = this.lvProducerLimit();
                    long pIndex = this.lvProducerIndex();
                    if ((pIndex & 1L) != 1L) {
                        long mask = this.producerMask;
                        E[] buffer = this.producerBuffer;
                        if (offset <= pIndex) {
                            int result = this.offerSlowPath(mask, pIndex, offset);
                            switch(result) {
                            case 0:
                            default:
                                break;
                            case 1:
                                continue;
                            case 2:
                                return false;
                            case 3:
                                this.resize(mask, buffer, pIndex, e);
                                return true;
                            }
                        }

                        if (this.casProducerIndex(pIndex, pIndex + 2L)) {
                            offset = LinkedArrayQueueUtil.modifiedCalcElementOffset(pIndex, mask);
                            // THIS IS WHERE I STOPED AND THE BUFFER WAS FILLED WITH EARLIER UNEXECUTED TASKS
                            UnsafeRefArrayAccess.soElement(buffer, offset, e);
                            return true;
                        }
                    }
                }
            }
        }
    }

I also added the stack and the memory for the SingleThreadEventExecutor at that point:
![last_stack_entry](https://user-images.githubusercontent.com/2699538/33894200-a93a33b8-df5d-11e7-9061-9840f5e40c70.jpg)

### Netty version
4.1.17

### JVM version (e.g. `java -version`)
1.8.0_152

### OS version (e.g. `uname -a`)
any

**Comment by normanmaurer** [comment]
@konsultaner so does it busy spin in the while loop ?

**Comment by normanmaurer** [comment]
Also @nitsanw as it may be a bug in jctools 😭

**Comment by konsultaner** [comment]
@normanmaurer I don't quite get what you mean by 

> so does it busy spin in the while loop ?

Do you want to know if the BaseMpscLinkedArrayQueue::offer while loop forever?

An update:
![problem_before_not_working](https://user-images.githubusercontent.com/2699538/33897436-bbdc37ca-df65-11e7-9d81-0fc78750c01a.jpg)

This is the stack trace before the issue occurs after the 14 events

**Comment by normanmaurer** [comment]
@konsultaner yes I want to know if it ever returns or just stay in its `while` loop.

**Comment by konsultaner** [comment]
@normanmaurer  no it does not loop forever

**Comment by nitsanw** [comment]
So far it seems like you are successfully putting elements into the queue. I'm not familiar with the scheduler consumer side, so can't say what would make a task disappear into it. I'm happy to look into it if you have more details or preferably a reproducer.

**Comment by konsultaner** [comment]
@nitsanw Thank you for that offer. Would you help me if I let you debug the problem on my computer via a teamviewer session?

**Comment by normanmaurer** [comment]
@konsultaner is this always happening after the `offer` is called from within `fetchFromScheduledTaskQueue` ?

**Comment by normanmaurer** [comment]
Also can you reproduce the issue on Linux or MacOS as well @konsultaner  ?

**Comment by nitsanw** [comment]
@konsultaner I'm happy to help you with consulting (paid at hourly rate), if that is what you need. Debugging remotely via some remote desktop is usually a very time consuming and frustrating business, and this would take a while. If you have a reproducer I can run/debug/test locally I'm happy to help you out of my own pocket. I'm afraid those are the limitations of my OSS generosity at these busy times. Sorry.

**Comment by konsultaner** [comment]
@normanmaurer 

>  is this always happening after the offer is called from within fetchFromScheduledTaskQueue ?

No, fetchFromScheduledTaskQueue is never called as soon as the error occurs. If you look at the first image I posted, you can see on the left side how the call stack never jumps into an extra thread. There is one gray line that actually starts the call. The second image is the one where the error is not present. After 14 calls the stack shows the result of image one.

> Also can you reproduce the issue on Linux or MacOS as well

Yes on any machine

**Comment by konsultaner** [comment]
@normanmaurer If you want, I could let you debug it on my machine using teamviewer. I'm at work for another couple of hours.

**Comment by normanmaurer** [comment]
@konsultaner sorry but I can't really do the remote debugging. Cant you share something I can run locally ? 

I asked about the `fetchFromScheduledTaskQueue` as it shows up in the stack on the second image. Also can you attach a thread-dump to ensure you are not blocking the thread somehow.

**Comment by konsultaner** [comment]
@normanmaurer 

> I asked about the fetchFromScheduledTaskQueue as it shows up in the stack on the second image.

The second image shows where everything is still fine.

> Also can you attach a thread-dump to ensure you are not blocking the thread somehow.

I have never done this before. I hope I did it right. I had a breakpoint set to the position where it stops. Then I started jstack and continued. This is the result: 
[threaddump.log](https://github.com/netty/netty/files/1555617/threaddump.log)

**Comment by normanmaurer** [comment]
@konsultaner there are multiple things that look very concerning to me...

If you look at the thread dump you see multiple calls to
```
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
```

while be processed in an `NioEventLoop`.  This means you will block the IO Thread which could have the side-effect of not picking up work that is scheduled on it.

For example see this one that is the stack you told me to look at (and there are multiple of such blocking actions):

```
"nioEventLoopGroup-4-2" #61 prio=10 os_prio=2 tid=0x00000000273c9000 nid=0x1d80 waiting on condition [0x000000002fa6d000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000775aa43f0> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at com.imilia.timerbee.sac.hive.remote.RemoteOAuth2TokenService.authenticate(RemoteOAuth2TokenService.java:84)
	at com.imilia.sac.challenger.oauth.impl.InternalPasswordChallenger.authenticate(InternalPasswordChallenger.java:84)
	at com.imilia.sac.challenger.oauth.impl.InternalPasswordChallenger.remoteAuthenticate(InternalPasswordChallenger.java:64)
	at de.konsultaner.wamp.peer.authentication.server.implementation.OAuth2Executor.lambda$authenticate$6(OAuth2Executor.java:97)
	at de.konsultaner.wamp.peer.authentication.server.implementation.OAuth2Executor$$Lambda$43/319202086.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at de.konsultaner.wamp.peer.authentication.server.implementation.OAuth2Executor.authenticate(OAuth2Executor.java:94)
	at de.konsultaner.wamp.peer.authentication.server.RealmStorage.authenticate(RealmStorage.java:117)
	at de.konsultaner.wamp.peer.netty.handler.codec.wamp.router.WampHandler.channelRead0(WampHandler.java:105)
	at de.konsultaner.wamp.peer.netty.handler.codec.wamp.router.WampHandler.channelRead0(WampHandler.java:29)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:77)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler$1.channelRead(WebSocketServerProtocolHandler.java:204)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

You MUST NEVER block within an EventLoop as one EventLoop will handle multiple connections to process its IO. When blocking you basically block all of these to do anything which will lead to timeouts / errors and other things. I

**Comment by konsultaner** [comment]
@normanmaurer now as I understand how the eventprocessing works, I understand. Thanks a lot! 

> You MUST NEVER block within an EventLoop

I see I need to pack all my blocking stuff into events. I wanted to solve things syncronized, which is obviously stupid within an NIO environment.

**Comment by normanmaurer** [comment]
@konsultaner let me close this issue ... Basically if you need to block you need to offload it to another thread which does not do the IO.
