### ISSUE TITLE
onos seldom has netty error. Failed to initialize a channel

### ISSUE THREAD

**Issue by mingcd** [netty/netty#7529]
### Actual behavior
2017-10-26 15:10:16,440 | WARN  | VSDB-C-worker-29 | ChannelInitializer               | 96 - io.netty.common - 4.1.8.Final | Failed to initialize a channel. Closing: [id: 0xd6cfb5e6]
java.lang.NoClassDefFoundError: io/netty/util/internal/TypeParameterMatcher
	at java.lang.Class.forName0(Native Method)[:1.8.0_141]
	at java.lang.Class.forName(Class.java:348)[:1.8.0_141]
	at io.netty.util.internal.JavassistTypeParameterMatcherGenerator.generate(JavassistTypeParameterMatcherGenerator.java:66)
	at io.netty.util.internal.JavassistTypeParameterMatcherGenerator.generate(JavassistTypeParameterMatcherGenerator.java:58)
	at io.netty.util.internal.TypeParameterMatcher.get(TypeParameterMatcher.java:42)
	at io.netty.util.internal.TypeParameterMatcher.find(TypeParameterMatcher.java:78)
	at io.netty.handler.codec.MessageToMessageEncoder.<init>(MessageToMessageEncoder.java:59)
	at io.netty.handler.codec.string.StringEncoder.<init>(StringEncoder.java:67)
	at org.onosproject.ovsdb.controller.impl.Controller$2.initChannel(Controller.java:260)
	at org.onosproject.ovsdb.controller.impl.Controller$2.initChannel(Controller.java:255)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)[98:io.netty.transport:4.1.8.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)[98:io.netty.transport:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)[98:io.netty.transport:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)[98:io.netty.transport:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)[98:io.netty.transport:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)[98:io.netty.transport:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)[98:io.netty.transport:4.1.8.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)[98:io.netty.transport:4.1.8.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)[98:io.netty.transport:4.1.8.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)[98:io.netty.transport:4.1.8.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)[96:io.netty.common:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)[96:io.netty.common:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)[98:io.netty.transport:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)[96:io.netty.common:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_141]
Caused by: java.lang.ClassNotFoundException: io.netty.util.internal.TypeParameterMatcher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)[:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)[:1.8.0_141]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)[:1.8.0_141]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_141]
	... 25 more
Let me know if any other information is required.
### Netty version
4.1.8.Final
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_141"

OpenJDK Runtime Environment (build 1.8.0_141-b16)

OpenJDK 64-Bit Server VM (build 25.141-b16, mixed mode)
### OS version (e.g. `uname -a`)
4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Scottmitch** [comment]
Please update to the latest Netty version and report back if the issue still exists.

**Comment by normanmaurer** [comment]
Maybe you missed to include netty-common in the class path ?  Let me close this until you provide more details
