### ISSUE TITLE
Using Netty on Android, throw out abnormal javax.net.ssl.SSLException: failed to initialize the server-side SSL context

### ISSUE THREAD

**Issue by litangyu** [netty/netty#7546]
### Expected behavior
I want to use the Netty in Android, and create a capture software.

Can you change the code into a BKS KeyStore library that is compatible with Android.

I find the method of name buildKeyStore in SslContext, which uses KeyStore.getInstance ("JKS"). I think if you use KeyStore.getInstance (KeyStore.getDefaultType ()), it will be better.

My English is not very good. It may not express what I mean. But I'm looking forward to getting back to me, or giving me some advice.

### Actual behavior

~~~
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err: javax.net.ssl.SSLException: failed to initialize the server-side SSL context
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:278)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:237)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:415)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:441)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at me.lty.myapplication.proxy.handler.HttpProxyServerHandle.channelRead(HttpProxyServerHandle.java:140)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
12-28 19:01:36.910 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err: Caused by: java.security.KeyStoreException: java.security.NoSuchAlgorithmException: KeyStore JKS implementation not found
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at java.security.KeyStore.getInstance(KeyStore.java:119)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:1001)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1162)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1153)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:256)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err: 	... 19 more
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err: Caused by: java.security.NoSuchAlgorithmException: KeyStore JKS implementation not found
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at org.apache.harmony.security.fortress.Engine.notFound(Engine.java:190)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:139)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err:     at java.security.KeyStore.getInstance(KeyStore.java:116)
12-28 19:01:36.911 23808-24612/me.lty.myapplication W/System.err: 	... 23 more
~~~

### Steps to reproduce
When create SslContext throw exception.
My code:
SslContext sslCtx = SslContextBuilder
                        .forServer(serverConfig.getServerPriKey(), CertPool.getCert(this.host, serverConfig))
                        .build();
### Netty version
4.1.15
### JVM version (e.g. `java -version`)
1.8.0_121
### OS version (e.g. `uname -a`)
Android 5.0.2  Mac OSX 10.13.2

**Comment by normanmaurer** [comment]
Did you test the suggested change ?

**Comment by normanmaurer** [comment]
@litangyu can you verify the fix https://github.com/netty/netty/pull/7547 ?

**Comment by litangyu** [comment]
@normanmaurer  I'm sorry i can't verify the fix. Because i haven't compiled Netty yet.

**Comment by normanmaurer** [comment]
@litangyu just check out the 4.1 branch and run `mvn clean package -DskipTests=true`. This will provide you with the jars. Didn't this work ?

**Comment by litangyu** [comment]
@normanmaurer I'm trying compiled. But some problems

~~~
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Netty .............................................. SUCCESS [01:29 min]
[INFO] Netty/Common ....................................... SUCCESS [ 50.151 s]
[INFO] Netty/Buffer ....................................... SUCCESS [ 12.823 s]
[INFO] Netty/Resolver ..................................... SUCCESS [  4.476 s]
[INFO] Netty/Transport .................................... SUCCESS [ 16.262 s]
[INFO] Netty/Codec ........................................ SUCCESS [ 12.454 s]
[INFO] Netty/Codec/DNS .................................... SUCCESS [  7.455 s]
[INFO] Netty/Codec/HAProxy ................................ SUCCESS [  4.734 s]
[INFO] Netty/Handler ...................................... SUCCESS [ 12.725 s]
[INFO] Netty/Codec/HTTP ................................... SUCCESS [ 14.736 s]
[INFO] Netty/Codec/HTTP2 .................................. SUCCESS [ 13.512 s]
[INFO] Netty/Codec/Memcache ............................... SUCCESS [  5.676 s]
[INFO] Netty/Codec/MQTT ................................... SUCCESS [  6.717 s]
[INFO] Netty/Codec/Redis .................................. SUCCESS [  6.766 s]
[INFO] Netty/Codec/SMTP ................................... SUCCESS [  5.900 s]
[INFO] Netty/Codec/Socks .................................. SUCCESS [  5.798 s]
[INFO] Netty/Codec/Stomp .................................. SUCCESS [  4.141 s]
[INFO] Netty/Codec/XML .................................... SUCCESS [  4.237 s]
[INFO] Netty/Handler/Proxy ................................ SUCCESS [  5.053 s]
[INFO] Netty/Resolver/DNS ................................. SUCCESS [  6.430 s]
[INFO] Netty/Transport/RXTX ............................... SUCCESS [  3.086 s]
[INFO] Netty/Transport/SCTP ............................... SUCCESS [  4.680 s]
[INFO] Netty/Transport/UDT ................................ SUCCESS [  6.103 s]
[INFO] Netty/Example ...................................... SUCCESS [ 11.836 s]
[INFO] Netty/Transport/Native/Unix/Common ................. SUCCESS [  5.793 s]
[INFO] Netty/Testsuite .................................... SUCCESS [  9.095 s]
[INFO] Netty/Transport/Native/Unix/Common/Tests ........... SUCCESS [  2.790 s]
[INFO] Netty/Transport/Native/KQueue ...................... FAILURE [  5.548 s]
[INFO] Netty/All-in-One ................................... SKIPPED
[INFO] Netty/Dev-Tools .................................... SKIPPED
[INFO] Netty/Tarball ...................................... SKIPPED
[INFO] Netty/Transport/Native/Epoll ....................... SKIPPED
[INFO] Netty/Testsuite/Autobahn ........................... SKIPPED
[INFO] Netty/Testsuite/Http2 .............................. SKIPPED
[INFO] Netty/Testsuite/OSGI ............................... SKIPPED
[INFO] Netty/Microbench ................................... SKIPPED
[INFO] Netty/BOM .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:39 min
[INFO] Finished at: 2017-12-29T15:56:52+08:00
[INFO] Final Memory: 64M/776M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fusesource.hawtjni:maven-hawtjni-plugin:1.14:build (build-native-lib) on project netty-transport-native-kqueue: build failed: org.apache.maven.plugin.MojoExecutionException: Requested download does not exist.: Could not find artifact io.netty:netty-transport-native-kqueue:zip:native-src:4.1.20.Final-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots)
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command: 
[ERROR]     mvn install:install-file -DgroupId=io.netty -DartifactId=netty-transport-native-kqueue -Dversion=4.1.20.Final-SNAPSHOT -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]     mvn deploy:deploy-file -DgroupId=io.netty -DartifactId=netty-transport-native-kqueue -Dversion=4.1.20.Final-SNAPSHOT -Dclassifier=native-src -Dpackaging=zip -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR]   io.netty:netty-transport-native-kqueue:zip:4.1.20.Final-SNAPSHOT
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :netty-transport-native-kqueue

~~~

**Comment by normanmaurer** [comment]
Seems like you are on Mac, this should fix it:

```
brew install autoconf automake libtool
```

**Comment by litangyu** [comment]
@normanmaurer  OK, I will try again. Thanks!

**Comment by normanmaurer** [comment]
@litangyu here is also a jar that includes the PR: https://drive.google.com/open?id=1wXWkm-IcWdIXp4z6-lQM_5eEQ_SoitKw

**Comment by litangyu** [comment]
@normanmaurer  Hey, i find a code that not change yet. Is that no problem?

KeyStore ks = KeyStore.getInstance("JKS");

~~~
static KeyStore buildKeyStore(X509Certificate[] certChain, PrivateKey key, char[] keyPasswordChars) throws KeyStoreException, NoSuchAlgorithmException, CertificateException, IOException {
        KeyStore ks = KeyStore.getInstance("JKS");
        ks.load((InputStream)null, (char[])null);
        ks.setKeyEntry("key", key, keyPasswordChars, certChain);
        return ks;
    }
~~~

**Comment by normanmaurer** [comment]
@litangyu good catch... I missed the missing `JKS` reference. Fixed this now. Please download the jar and try again:

https://drive.google.com/open?id=1M0dMog5gRgi3WLMoXNvt_V5RDe9P2PSa

For the compile error please run : `mvn clean install -DskipTests=true`.

**Comment by litangyu** [comment]
@normanmaurer The exception is no longer, but there is a new one. I'm not sure whether it is my code problem or the problem of Netty. Can you help me see it?

~~~
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Handshake failed
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1412)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:943)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:436)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1006)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:292)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1248)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: 	... 16 more
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x55a7110e00: Failure in SSL library, usually a protocol error
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number (external/openssl/ssl/s3_pkt.c:343 0x7f89a42f20:0x00000000)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:423)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: 	... 23 more
~~~

**Comment by normanmaurer** [comment]
@litangyu yes this has nothing to do with netty but comes from android / conscrypt itself. If I would have to guess I would double check the SSL Protocol version that you are using is compatible with the one the client is using.

**Comment by litangyu** [comment]
@normanmaurer  OK！Thank you very much！ I'll close this issues, i think the problem has been solved.And thanks again！

**Comment by litangyu** [comment]
@normanmaurer I think the exception is the problem of Netty.

~~~
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err: io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Handshake failed
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
12-29 16:31:22.783 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1412)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:943)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:436)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:1006)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:292)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1248)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: 	... 16 more
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x55a7110e00: Failure in SSL library, usually a protocol error
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number (external/openssl/ssl/s3_pkt.c:343 0x7f89a42f20:0x00000000)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake_bio(Native Method)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err:     at com.android.org.conscrypt.OpenSSLEngineImpl.unwrap(OpenSSLEngineImpl.java:423)
12-29 16:31:22.784 20586-21130/me.lty.myapplication W/System.err: 	... 23 more
~~~

Because,I tried to create a server-side SSLServerSocket using the native SSLContext. And the mistake was not found again. But I don't know exactly where it went wrong, and I haven't found the code that could go wrong.

I use that code to create the SSLServerSocket and it work good.
~~~
        X509Certificate cert = CertPool.getCert(host, serverConfig);
        X509Certificate[] keyCertChain = new X509Certificate[]{cert};

        KeyStore keyStore = KeyStore.getInstance(KeyStore.getDefaultType());
        keyStore.load(null, null);
        keyStore.setKeyEntry("key", serverConfig.getServerPriKey(), null, keyCertChain);

        KeyManagerFactory keyManagerFactory = KeyManagerFactory.getInstance(
                KeyManagerFactory.getDefaultAlgorithm());
        keyManagerFactory.init(keyStore, null);

        SSLContext context = SSLContext.getInstance("TLS");
        context.init(keyManagerFactory.getKeyManagers(), null, null);

        SSLServerSocket serverSocket = (SSLServerSocket) context
                .getServerSocketFactory()
                .createServerSocket(9990);

        Log.d(TAG, "Server Side......");
        Socket connection = serverSocket.accept();
        final InputStream input = connection.getInputStream();
        OutputStream output = connection.getOutputStream();
~~~

**Comment by litangyu** [comment]
@normanmaurer  I upload my test app [MITMProxy-for-Android](https://github.com/litangyu/MITMProxy-for-Android). It using Netty as the base framework to create a proxy server. And listening port 9999 on Android Device.It mainly uses intermediate man attacks to capture traffic.

**Comment by normanmaurer** [comment]
So you figured it out ?

**Comment by litangyu** [comment]
It's still not clear.
I'm try create a other project. And the project work good. So maybe i will figured it out when another time.

**Comment by normanmaurer** [comment]
Let me close this for now then... please reopen if the issue still happens or if you have more details
