### ISSUE TITLE
Multiple EventLoopGroup cause socketException

### ISSUE THREAD

**Issue by ztkmkoo** [netty/netty#7549]
Hi.
Recently I make a server-stress-test client with netty bootstrap.

First,
I create multiple bootstrap to connect server and it causes error: `java.net.SocketException: No buffer space available (maximum connections reached?): connect` when the bootstrap was created bout 1,000 times in my computer. 
At last i search in google find the right way to make to multiple connection with bootstrap.

And i looked at the bootstrap code and found nothing to cause SocketException.
Now i wonder why it causes SocketException when i create multiple bootstrap object and the correct way to create multiple client connection to server.

Here is the incorrect code(cause SocketException) and correct(maybe?) code.

#### Incorrect Code.
``` java
for(int i = 0; i < 5000; i++) {
  EventLoopGroup workerGroup = new NioEventLoopGroup();
  Bootstrap bootstrap = new Bootstrap();
  bootstrap
    .group(workerGroup)
    .channel(NioSocketChannel.class)
    .option(ChannelOption.SO_KEEPALIVE, true)
    .option(ChannelOption.SO_REUSEADDR, true)
    .handler(new ChannelInitializer<SocketChannel>() {
      @Override
      protected void initChannel(SocketChannel ch) throws Exception {
        ch.pipeline().addLast(new EchoHandler());
      }
    });

  try {
    ChannelFuture future = bootstrap.connect("localhost", 10000).sync();
  } catch (InterruptedException e) {
    e.printStackTrace();
  }
}
```

#### Correct(?) Code
``` java
EventLoopGroup workerGroup = new NioEventLoopGroup();
Bootstrap bootstrap = new Bootstrap();
bootstrap
  .group(workerGroup)
  .channel(NioSocketChannel.class)
  .option(ChannelOption.SO_KEEPALIVE, true)
  .option(ChannelOption.SO_REUSEADDR, true)
  .handler(new ChannelInitializer<SocketChannel>() {
    @Override
    protected void initChannel(SocketChannel ch) throws Exception {
      ch.pipeline().addLast(new EchoHandler());
    }
  });

List<ChannelFuture> list = new ArrayList<>();
for(int i = 0; i < 5000; i++) {
  ChannelFuture future = bootstrap.connect("localhost", 10000).sync();
  list.add(future);
}
```

#### Error Exception
``` 
Exception in thread "main" java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
	at com.example.demo.DemoApplication.multipleBootstrap(DemoApplication.java:54)
	at com.example.demo.DemoApplication.main(DemoApplication.java:31)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 9 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:94)
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.ch.PipeImpl.<init>(PipeImpl.java:171)
	at sun.nio.ch.SelectorProviderImpl.openPipe(SelectorProviderImpl.java:50)
	at java.nio.channels.Pipe.open(Pipe.java:155)
	at sun.nio.ch.WindowsSelectorImpl.<init>(WindowsSelectorImpl.java:127)
	at sun.nio.ch.WindowsSelectorProvider.openSelector(WindowsSelectorProvider.java:44)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
	... 13 more
Caused by: java.net.SocketException: No buffer space available (maximum connections reached?): connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Net.java:454)
	at sun.nio.ch.Net.connect(Net.java:446)
	at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
	at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(PipeImpl.java:127)
	at sun.nio.ch.PipeImpl$Initializer.run(PipeImpl.java:76)
	... 21 more
```

### Expected behavior
-
### Actual behavior
-
### Steps to reproduce
-
### Minimal yet complete reproducer code (or URL to code)
See `Incorrect Code`
### Netty version
4.1.15.Final
### JVM version (e.g. `java -version`)
java 1.8.0_151
### OS version (e.g. `uname -a`)
Windows 10-64bit Enterprise 1709

**Comment by ztkmkoo** [comment]
```
EventLoopGroup workerGroup = new NioEventLoopGroup();
```
I found if i create multiple EventLoopGroup cause this error.

**Comment by ztkmkoo** [comment]
Ref issue [EventLoopException at client side on load #639](https://github.com/netty/netty/issues/639)

`trustin`
> Usually, it's just fine to create a single event loop group instance and reuse it for all channels.

**Comment by ztkmkoo** [comment]
Eventually(?) Error was throwed here.

``` java
private SelectorTuple openSelector() {
        final Selector unwrappedSelector;
        try {
            unwrappedSelector = provider.openSelector();
        } catch (IOException e) {
            throw new ChannelException("failed to open a new selector", e);
        }
    }
```

In my local pc(windows)
at some limit,
WindowsSelectorProvider cannot open selector.

**Comment by ztkmkoo** [comment]
![image](https://user-images.githubusercontent.com/26991409/34601170-1a96a094-f23e-11e7-9f0c-897188daa8b1.png)

It my code `Call Stack`.

**Comment by normanmaurer** [comment]
This has to do with system-limits. You may need to raise some of them or not create so many instances. There is nothing we can do about it

**Comment by joseflaviojr** [comment]
Creating thousands of connections with the shutdownGracefully default does not let the JVM breathe to release the ports. If I give a rest every 1000 connections using Thread.sleep (1000) the problem is healed, but I'd rather use the deprecated action shutdownGracefully (0, 0, TimeUnit.MILLISECONDS). And if you want to be sure of the closing, use shutdownGracefully...sync().

**Comment by chamil321** [comment]
> This has to do with system-limits. You may need to raise some of them or not create so many instances. There is nothing we can do about it

@normanmaurer I create multiple servers sharing the same Eventloop group. My requirement is to close those servers individually(https://github.com/ballerina-platform/module-ballerina-http/pull/1040). I can't use `workerGroup.shutdownGracefully();` as it shutdown all the service in the same Eventloop group. Also I can't have seperate 
Eventloop groups for each server, as it causes `java.lang.IllegalStateException: failed to create a child event loop` and `Too many open files` exceptions.


What is the best practice to implement immediate stop for bunch of services which shares the same Eventloop group?

**Comment by normanmaurer** [comment]
@chamil321 just call `close()` on the `ServerChannel` ?

**Comment by chamil321** [comment]
> @chamil321 just call `close()` on the `ServerChannel` ?

Great!! Thanks. It did work.  https://github.com/chamil321/module-ballerina-http/blob/fix-too-many-file-open/native/src/main/java/io/ballerina/stdlib/http/transport/contractimpl/listener/ServerConnectorBootstrap.java#L248
