### ISSUE TITLE
No field threadProperties in

### ISSUE THREAD

**Issue by 20140103** [netty/netty#7568]
### Expected behavior
gzip content is fully consumed
### Actual behavior
gzip content is fully consumed
### Steps to reproduce
n/a
### Minimal yet complete reproducer code (or URL to code)
public ChannelFuture start() throws InterruptedException {
        workerGroup = new NioEventLoopGroup();

        Bootstrap bootstrap = new Bootstrap();
        bootstrap.group(workerGroup)
                .channel(NioDatagramChannel.class)
                .handler(new ServerChannelInitializer(handler));

        ChannelFuture channelFuture = bootstrap.bind(new InetSocketAddress(port)).syncUninterruptibly();
        channel = channelFuture.channel();

        return channelFuture;
    }
### Netty version
4.1.17

### JVM version (e.g. `java -version`)
OpenJDK1.7
### OS version (e.g. `uname -a`)
Android6.0

 java.lang.ExceptionInInitializerError
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126)
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
                                                                                   at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
                                                                                   at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
                                                                                   at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
                                                                                   at com.twt.tiantong.tiantongserver.udpservice.NettyUdpServer.start(NettyUdpServer.java:28)
                                                                                   at com.twt.tiantong.tiantongserver.DiscoveryServerService$1.run(DiscoveryServerService.java:33)
                                                                                   at java.lang.Thread.run(Thread.java:818)
                                                                                Caused by: java.lang.RuntimeException: java.lang.NoSuchFieldException: No field threadProperties in class Lio/netty/util/concurrent/SingleThreadEventExecutor; (declaration of 'io.netty.util.concurrent.SingleThreadEventExecutor' appears in /data/app/com.twt.tiantong.tiantongserver-1/base.apk)
                                                                                   at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:204)
                                                                                   at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:70)
                                                                                   at io.netty.util.concurrent.SingleThreadEventExecutor.<clinit>(SingleThreadEventExecutor.java:79)
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) 
                                                                                   at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) 
                                                                                   at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) 
                                                                                   at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43) 
                                                                                   at com.twt.tiantong.tiantongserver.udpservice.NettyUdpServer.start(NettyUdpServer.java:28) 
                                                                                   at com.twt.tiantong.tiantongserver.DiscoveryServerService$1.run(DiscoveryServerService.java:33) 
                                                                                   at java.lang.Thread.run(Thread.java:818) 
                                                                                Caused by: java.lang.NoSuchFieldException: No field threadProperties in class Lio/netty/util/concurrent/SingleThreadEventExecutor; (declaration of 'io.netty.util.concurrent.SingleThreadEventExecutor' appears in /data/app/com.twt.tiantong.tiantongserver-1/base.apk)
                                                                                   at java.lang.Class.getDeclaredField(Native Method)
                                                                                   at java.util.concurrent.atomic.AtomicReferenceFieldUpdater$AtomicReferenceFieldUpdaterImpl.<init>(AtomicReferenceFieldUpdater.java:185)
                                                                                   at java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater(AtomicReferenceFieldUpdater.java:70) 
                                                                                   at io.netty.util.concurrent.SingleThreadEventExecutor.<clinit>(SingleThreadEventExecutor.java:79) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:126) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36) 
                                                                                   at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84) 
                                                                                   at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58) 
                                                                                   at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51) 
                                                                                   at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43) 
                                                                                   at com.twt.tiantong.tiantongserver.udpservice.NettyUdpServer.start(NettyUdpServer.java:28) 
                                                                                   at com.twt.tiantong.tiantongserver.DiscoveryServerService$1.run(DiscoveryServerService.java:33) 
                                                                                   at java.lang.Thread.run(Thread.java:818)

**Comment by normanmaurer** [comment]
Seems like a Netty Version mixup... ensure you either only have 4.0.x or 4.1.x on the classpath

**Comment by normanmaurer** [comment]
Please do what I suggested and re-open if you still see the issue
