### ISSUE TITLE
Failed to get SSL certificates

### ISSUE THREAD

**Issue by pravinkumarb84** [netty/netty#7589]
I am trying to modify the URI, path of a request in my customer filter, but i am getting "Failed to get SSL certificates" exception. This works fine when i am running the application as http service but when i run it as https, this fails.

Please advice on how to handle this issue.

My code:

ServerHttpRequest request =
exchange
.getRequest()
.mutate()
.uri(URI.create(exchange.getRequest().getURI().toString().replace("sample", "")))
.path("/sample")
.build();
return chain.filter(exchange.mutate().request(request).build());

Exception log:

java.lang.IllegalStateException: Failed to get SSL certificates
at org.springframework.http.se
rver.reactive.DefaultSslInfo.initCertificates(DefaultSslInfo.java:94) ~[spring-web-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
at org.springframework.http.server.reactive.DefaultSslInfo.(DefaultSslInfo.java:51) ~[spring-web-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
at org.springframework.http.server.reactive.ReactorServerHttpRequest.initSslInfo(ReactorServerHttpRequest.java:141) ~[spring-web-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
at org.springframework.http.server.reactive.AbstractServerHttpRequest.getSslInfo(AbstractServerHttpRequest.java:162) ~[spring-web-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
at org.springframework.http.server.reactive.DefaultServerHttpRequestBuilder$DefaultServerHttpRequest.(DefaultServerHttpRequestBuilder.java:176) ~[spring-web-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]
at org.springframework.http.server.reactive.DefaultServerHttpRequestBuilder.build(DefaultServerHttpRequestBuilder.java:133) ~[spring-web-5.0.2.RELEASE.jar!/:5.0.2.RELEASE]

**Comment by normanmaurer** [comment]
@pravinkumarb84 you need to open this issue in spring as the exception comes from spring and not netty.
