### ISSUE TITLE
MultithreadEventExecutorGroup unsafe constructor

### ISSUE THREAD

**Issue by mingslogar** [netty/netty#7605]
### Expected behavior
`io.netty.util.concurrent.MultithreadEventExecutorGroup#MultithreadEventExecutorGroup(int, java.util.concurrent.Executor, io.netty.util.concurrent.EventExecutorChooserFactory, java.lang.Object...)`

See https://stackoverflow.com/a/15327631/2179987 -- a constructor should never call a method that is not private and/or final.

In this case, we're calling `newChild`, a function which may or may not be implemented. As a result, classes such as `EpollEventLoopGroup ` cannot be constructed reliably.

### Actual behavior

```
io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/ThreadFactory;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor;: java.lang.AbstractMethodError
java.lang.AbstractMethodError: io.netty.util.concurrent.MultithreadEventExecutorGroup.newChild(Ljava/util/concurrent/ThreadFactory;[Ljava/lang/Object;)Lio/netty/util/concurrent/EventExecutor;
at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:50)
at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104)
at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91)
at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:68)
```
This error appeared when calling Netty from a Redisson client.

### Netty version

4.1.19.Final

### JVM version (e.g. `java -version`)

1.8.0_141

### Runtime environment

AWS Lambda

**Comment by normanmaurer** [comment]
@mingslogar I wonder how this error can happen tho as it needs to be implemented. Can you give a reproducer ?

**Comment by normanmaurer** [comment]
@mingslogar ping

**Comment by mingslogar** [comment]
@normanmaurer Hey, sorry for the long delay. Had some unexpected medical issues that kept me offline for a while.

Looking online, it appears that the specific runtime issue that I encountered was due to some Maven versioning conflicts causing an error when loading the child class. I wish I could give you a code sample, but I don't have the bandwidth right now to reconstruct our codebase from two weeks ago.

My comment was less to the actual runtime error, however, and more to the pattern. Calling some non-immutable method via a constructor is not guaranteed to be error free.

> a function which may or may not be implemented

I was a bit hasty in typing this out, so that statement is not correct. However, I should say

> a function which may or may not behave as expected depending upon resources which may be nonexistent in a non apparent way

**Comment by normanmaurer** [comment]
Let me add it to the "next-major" version TODO List: https://github.com/netty/netty/issues/5430#issuecomment-365854774
