### ISSUE TITLE
HttpPostMultipartRequestDecoder.splitMultipartHeader() String index out of range: -1 with empty Content-Type

### ISSUE THREAD

**Issue by matteobertozzi** [netty/netty#7620]
Parsing a multi-part request with an empty content type header: e.g. "Content-Type: "
will produce a java.lang.StringIndexOutOfBoundsException: String index out of range: -1

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
 at java.lang.String.substring(String.java:1967)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.splitMultipartHeader(HttpPostMultipartRequestDecoder.java:1470)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDisposition(HttpPostMultipartRequestDecoder.java:680)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:490)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.findMultipartDelimiter(HttpPostMultipartRequestDecoder.java:642)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.decodeMultipart(HttpPostMultipartRequestDecoder.java:477)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBodyMultipart(HttpPostMultipartRequestDecoder.java:448)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.parseBody(HttpPostMultipartRequestDecoder.java:411)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.offer(HttpPostMultipartRequestDecoder.java:336)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.<init>(HttpPostMultipartRequestDecoder.java:185)
 at io.netty.handler.codec.http.multipart.HttpPostMultipartRequestDecoder.<init>(HttpPostMultipartRequestDecoder.java:142)
```

**Comment by matteobertozzi** [comment]
```
private static String[] splitMultipartHeader(String sb) {
        ...
        valueStart = HttpPostBodyUtil.findNonWhitespace(sb, colonEnd);
        valueEnd = HttpPostBodyUtil.findEndOfString(sb);
        headers.add(sb.substring(nameStart, nameEnd));

        String svalue = sb.substring(valueStart, valueEnd); // <--- StringIndexOutOfBoundsException
        ...
```

```
splitMultipartHeader("Content-Type:") -> valueStart=13 valueEnd=13
splitMultipartHeader("Content-Type: ") -> valueStart=14 valueEnd=13
splitMultipartHeader("Content-Type: \r\n") -> valueStart=16 valueEnd=13
```

**Comment by normanmaurer** [comment]
Maybe you can provide a unit test and fix ?

2018-01-24 18:54 GMT+01:00 Matteo Bertozzi <notifications@github.com>:

**Comment by matteobertozzi** [comment]
https://gist.github.com/matteobertozzi/86e1b7d5f4205beee243897050a47069

**Comment by normanmaurer** [comment]
@matteobertozzi can you open a PR against 4.1 ?

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/7622
