### ISSUE TITLE
too many file descriptor created after running a week

### ISSUE THREAD

**Issue by johnduxx** [netty/netty#7670]

**Comment by Scottmitch** [comment]
Please upgrade to the latest version of 4.1, and provide a isolated/minimal reproducer if the problem persists.

**Comment by johnduxx** [comment]
Exception in thread "Thread-24" java.lang.UnsatisfiedLinkError: failed to load the required native library
        at io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:327)
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:202)
        at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:43)
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:347)
        at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:335)
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:421)
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:441)
     
Caused by: java.lang.ClassNotFoundException: io.netty.internal.tcnative.SSL
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:344)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:77)

getting exception when using latest stable version

**Comment by normanmaurer** [comment]
@johnduxx did you also update the netty-tcnative version you are using to 2.0.7.Final ?

**Comment by johnduxx** [comment]
actually i was using netty-tcnative-openssl-static-1.1.33.Fork18-SNAPSHOT-linux-x86_64.jar but i did not find any update of it. 
can you suggest which should i use openssl-static or dynamic version?

**Comment by johnou** [comment]
2.0.7.Final

**Comment by johnduxx** [comment]
... 12 more
        Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_tcnative
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:205)
                at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:85)
                ... 10 more
        Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_tcnative.so
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
                ... 11 more
                Suppressed: java.lang.UnsatisfiedLinkError: no netty_tcnative in java.library.path
                        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
                        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
                        at java.lang.System.loadLibrary(System.java:1119)
                        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:243)
                        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:124)
                        ... 11 more

getting above exception. please help

**Comment by Scottmitch** [comment]
These exceptions do not necessarily indicate a problem, only that netty_tcnative cannot be found in the `java.library.path` directory ... which is common. We try to load tcnative from `java.library.path` before unpacking it from the jar. You should eventually see [Successfully loaded the library](https://github.com/netty/netty/blob/4.1/common/src/main/java/io/netty/util/internal/NativeLibraryLoader.java#L234) in the logs if tcnative is loaded. However is this necessary to reproduce the original issue?

**Comment by johnduxx** [comment]
i am trying to create a generator of the issue but it is slightly tough as i run the server for 3-4 weeks in a commercial environment. 

I am sharing the source of working handler, if you able to suggest me 


import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import io.netty.util.AttributeKey;
import org.apache.log4j.*;
import org.json.JSONException;
import org.json.JSONObject;
import io.netty.buffer.ByteBuf;
import io.netty.channel.Channel;
import io.netty.channel.ChannelFuture;
import io.netty.channel.ChannelFutureListener;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.SimpleChannelInboundHandler;
import io.netty.channel.ChannelHandler.Sharable;
import io.netty.handler.codec.http.DefaultFullHttpResponse;
import io.netty.handler.codec.http.DefaultHttpResponse;
import io.netty.handler.codec.http.FullHttpRequest;
import io.netty.handler.codec.http.FullHttpResponse;
import io.netty.handler.codec.http.HttpResponse;
import static io.netty.handler.codec.http.HttpHeaders.setContentLength;
import static io.netty.handler.codec.http.HttpHeaders.Names.CONNECTION;
import static io.netty.handler.codec.http.HttpHeaders.Names.CONTENT_TYPE;
import static io.netty.handler.codec.http.HttpHeaders.Names.HOST;
import static io.netty.handler.codec.http.HttpMethod.GET;
import static io.netty.handler.codec.http.HttpResponseStatus.NOT_FOUND;
import static io.netty.handler.codec.http.HttpResponseStatus.OK;
import static io.netty.handler.codec.http.HttpVersion.HTTP_1_1;

import io.netty.handler.codec.http.HttpResponseStatus;
import io.netty.handler.codec.http.websocketx.CloseWebSocketFrame;
import io.netty.handler.codec.http.websocketx.PingWebSocketFrame;
import io.netty.handler.codec.http.websocketx.PongWebSocketFrame;
import io.netty.handler.codec.http.websocketx.TextWebSocketFrame;
import io.netty.handler.codec.http.websocketx.WebSocketFrame;
import io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker;
import io.netty.handler.codec.http.websocketx.WebSocketServerHandshakerFactory;
import io.netty.handler.codec.http.websocketx.extensions.compression.WebSocketServerCompressionHandler;
import io.netty.handler.ssl.SslHandler;
import io.netty.handler.timeout.ReadTimeoutException;
import io.netty.handler.timeout.ReadTimeoutHandler;

@SuppressWarnings("deprecation")
@Sharable
public class WebSocketTransport extends SimpleChannelInboundHandler < Object > {

	private static final String WEBSOCKET_PATH = "/s/W/ws";
	private static final String XHR_PATH = "polling";
	private static final Logger logger = Logger.getLogger(WebSocketTransport.class.getName());
	public static final AttributeKey < WebSocketServerHandshaker > HANDSHAKER = AttributeKey.valueOf("handshaker");
	public static final AttributeKey < Session > SESSION = AttributeKey.valueOf("WebSocketServerHandler.Session");
  
	
	public WebSocketTransport() 
	{
		super();
	}

	@Override
	public void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {

		if (msg instanceof FullHttpRequest) {
			handleHttpRequest(ctx, (FullHttpRequest) msg);
		} else if (msg instanceof WebSocketFrame) {
			handleWebSocketFrame(ctx, (WebSocketFrame) msg);
		}
	}

	private void handleHttpRequest(ChannelHandlerContext ctx, FullHttpRequest req) throws Exception {
		try {

			if(req.getUri().indexOf(XHR_PATH) > 0) {
				handleXHR(ctx, req);
			}
			else
			{	
				initiateWebSocketHandshake(ctx, req);
			}
		} catch (Exception ex) {
			sendError(ctx);
			logger.error("error", ex);
		}
	}


	private boolean isAllChannelsClosed(VisitorSession visitorSession) {

		Map<String, Channel> channelMap = visitorSession.getWebsocketSessionData().getChannelMap();	

		if(channelMap.size() == 1)
			return true;

		/**
		 * if channelMap has more than one element, then
		 * iterate over them
		 */
		Iterator<Entry<String, Channel>> it = channelMap.entrySet().iterator();
		while(it.hasNext()){

			Map.Entry<String, Channel> pair = it.next();
			Channel channel = pair.getValue();

			if(channel.isActive())
				return false;
		}

		return true;
	}

	public void handleCloseEvent(final ChannelHandlerContext ctx, WebSocketFrame frame) 
	{	
		try
		{
			ctx.channel().attr(HANDSHAKER).get().close(ctx.channel(), (CloseWebSocketFrame) frame.retain());
			ChannelFuture future = ctx.channel().close();
			future.addListener(new ChannelFutureListener() {

				@Override
				public void operationComplete(ChannelFuture future) throws Exception {

					if(future.isDone() && future.isSuccess()){

						Session session = ctx.attr(SESSION).get();

						
					}

				}
			});
		}
		catch(Exception ex)
		{
			logger.fatal("error", ex);
		}
	}


	private void handleXHR(ChannelHandlerContext ctx, FullHttpRequest req )
	{
		try 
		{
			if(req.getUri().indexOf(XHR_PATH) > 0) 
			{	
				if(req.getMethod() == GET) 
				{
					try 
					{	
						QueryStringDecoder queryDecoder = new QueryStringDecoder(req.getUri());

						List < String > data = queryDecoder.parameters().get("data");

						List < String > callback = queryDecoder.parameters().get("callback");

						if(data == null || callback == null || !callback.get(0).equals("getResponse")) 
						{
							sendError(ctx);
							return;
						}

						JSONObject receivedParameters = new JSONObject(data.get(0));

						if (receivedParameters.has("data")) 
						{
							Request request = new Request(receivedParameters.getJSONObject("data"), ctx, 1);
							request.setParameters(receivedParameters);
							request.setHttpRequest(req);
							request.setDataAvailable(true);
							InPacketHandler.onRequest(ctx, request);
						} 
						else 
						{
							Request request = new Request(receivedParameters, ctx, 1);
							request.setHttpRequest(req);
							request.setParameters(receivedParameters);
							request.setDataAvailable(false);
							InPacketHandler.onRequest(ctx, request);
						}
					} 
					catch (Exception ex) {
						ResponseProcessor.sendError(ctx);
					}
				}
			}	
		} 
		catch (Exception ex) {
			logger.error("error at handleXHR:", ex);
		}

	}

	private void handleWebSocketFrame(ChannelHandlerContext ctx, WebSocketFrame frame) throws JSONException 
	{
		try 
		{	
			if(frame instanceof CloseWebSocketFrame) 
			{
				handleCloseEvent(ctx, frame);		
			} 
			else if (frame instanceof PingWebSocketFrame) 
			{
				ctx.channel().writeAndFlush(new PongWebSocketFrame(frame.content().retain()));
				return;	
			} 
			else if ((frame instanceof TextWebSocketFrame)) 
			{
				String payload = ((TextWebSocketFrame) frame).text();	

				JSONObject object = new JSONObject(payload);
				Request request = new Request(object, ctx, 0);
				InPacketHandler.onRequest(ctx, request);
			}
		} 
		catch(Exception ex) 
		{
			logger.error("##########error at handleWebSocketFrame", ex);
		}
	}

	private void sendError(ChannelHandlerContext ctx) 
	{
		HttpResponse res = new DefaultHttpResponse(HTTP_1_1, HttpResponseStatus.INTERNAL_SERVER_ERROR);
		ctx.channel().writeAndFlush(res).addListener(ChannelFutureListener.CLOSE);
	}

	private static String getWebSocketLocation(ChannelHandlerContext ctx, FullHttpRequest req) 
	{
		if (ctx.pipeline().get(SslHandler.class) != null) 
		{
			return "wss://" + req.headers().get(HOST) + WEBSOCKET_PATH;
		} 
		else 
		{

			return "ws://" + req.headers().get(HOST) + WEBSOCKET_PATH;
		}
	}

	
	private void initiateWebSocketHandshake(ChannelHandlerContext ctx, FullHttpRequest req) throws Exception 
	{
		try 
		{
			String connectionInformation = (String) req.headers().get(CONNECTION);

			if(connectionInformation != null && connectionInformation.indexOf("Upgrade") < 0) 
			{
				sendError(ctx);
				return;
			}

			if (!req.getDecoderResult().isSuccess()) 
			{
				sendError(ctx);
				return;
			}


			if (req.getMethod() != GET) 
			{	
				sendError(ctx);
				return;
			}

			if("/".equals(req.getUri())) 
			{
				ByteBuf content = WebSocketServerIndexPage.getContent(getWebSocketLocation(ctx, req));
				FullHttpResponse res = new DefaultFullHttpResponse(HTTP_1_1, OK, content);

				res.headers().set(CONTENT_TYPE, "text/html; charset=UTF-8");
				setContentLength(res, content.readableBytes());

				ResponseProcessor.sendHttpResponse(ctx, req, res);
				return;
			}

			if("/favicon.ico".equals(req.getUri())) 
			{
				FullHttpResponse res = new DefaultFullHttpResponse(HTTP_1_1, NOT_FOUND);
				ResponseProcessor.sendHttpResponse(ctx, req, res);
				return;
			}

			WebSocketServerHandshakerFactory wsFactory = new WebSocketServerHandshakerFactory(getWebSocketLocation(ctx, req), null, true);

			final WebSocketServerHandshaker handshaker = wsFactory.newHandshaker(req);

			if(handshaker == null) 
			{
				WebSocketServerHandshakerFactory.sendUnsupportedVersionResponse(ctx.channel());
			} 
			else 
			{
				final Channel channel = ctx.channel();
				ChannelFuture f = handshaker.handshake(ctx.channel(), req);
				f.addListener(new ChannelFutureListener() 
				{
					@Override
					public void operationComplete(ChannelFuture future) 
					{
						if (!future.isSuccess()) 
						{
							logger.error("Can't handshake ", future.cause());
							return;
						}
				
						channel.attr(HANDSHAKER).set(handshaker);
						channel.pipeline().addBefore("websocket-handler", "timeout-handler", new ReadTimeoutHandler(60));
						channel.pipeline().addBefore("timeout-handler", "webSocketTransportCompression",  new WebSocketServerCompressionHandler());
					}
				});
			}
		} catch (Exception ex) {
			logger.error("error" , ex);
			sendError(ctx);
		}
	}


	@Override
	public void channelReadComplete(ChannelHandlerContext ctx) throws Exception 
	{
		ctx.flush();
	}

	@Override
	public void channelInactive(ChannelHandlerContext ctx) 
	{
		try
		{
			Session session = ctx.attr(SESSION).get();
			if (session != null) {	

			} 
			else {

			}
			ctx.close();	

		}
		catch(Exception ex) {
			logger.fatal("error", ex);
		}
	}

	@Override
	public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) throws Exception 
	{	
		
		try
		{
			if(cause instanceof ReadTimeoutException) 
			{
				Session session = ctx.attr(SESSION).get();
				if (session != null) {	
				} 
				else {

				}
			}
			ctx.close();	
		}
		catch(Exception ex){
			logger.fatal("error", ex);
		}

	}

	@Override
	public void channelWritabilityChanged(ChannelHandlerContext ctx) 
	{

	}
}


pipeline
========
	/*
		 * Netty+ openssl engine 
		 * 
		 */
		ChannelPipeline pipeline = ch.pipeline();
		SslHandler handler =  this.sslCtx.newHandler(ch.alloc());
		pipeline.addLast( "ssl", handler);
		
		
		pipeline.addLast("codec-http", new HttpServerCodec());
		pipeline.addLast("deflater", new HttpContentCompressor(1));
		pipeline.addLast("aggregator", new HttpObjectAggregator(65536));
		
		pipeline.addLast(CommonExecutorProvider.getTaskexecutors(), "websocket-handler", WebSocketServer.INSTANCE_TRANSPORT);

**Comment by Scottmitch** [comment]
This doesn't give the complete picture but the following line looks interesting:

```java
Map<String, Channel> channelMap = visitorSession.getWebsocketSessionData().getChannelMap();
```

- You are cacheing channels, and do you take care to close them before they are GCed? How do you manage the lifetime of these `Channels`?
- What transport are you using (NIO, EPOLL, KQUEUE)?
- What type of file descriptors are leaking on your server, and what state are they in (e.g. `lsof`, `netstat`, info from `proc`, etc...)

**Comment by johnduxx** [comment]
@Scottmitch 

you have raised a very good point


but will it @Override
	public void channelInactive(ChannelHandlerContext ctx) 
	{
		try
		{
			Session session = ctx.attr(SESSION).get();
			if (session != null) {	

			} 
			else {

			}
			ctx.close();	

		}
		catch(Exception ex) {
			logger.fatal("error", ex);
		}
	}


not close all connection??

I am maintaining a session timeout and removing channel instance when session timeout happen but i am not closing the channel explicitly from session out section, 

I am checking your mentioned parameters

thanks again
