### ISSUE TITLE
HTTP/2 with TLS is broken since 4.1.10

### ISSUE THREAD

**Issue by slaskawi** [netty/netty#7766]
### Expected behavior

When invoking curl against the HTTP/2 server located in `io.netty.example.http2.helloworld.server` I always get `NSS error -5938 (PR_END_OF_FILE_ERROR)` and the following exception on Netty side:

```
java.lang.RuntimeException: Unable to wrap SSLEngine of type sun.security.ssl.SSLEngineImpl
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$AlpnWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:132)
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:249)
	at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:227)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:903)
	at io.netty.example.http2.helloworld.server.Http2ServerInitializer.configureSsl(Http2ServerInitializer.java:83)
	at io.netty.example.http2.helloworld.server.Http2ServerInitializer.initChannel(Http2ServerInitializer.java:73)
	at io.netty.example.http2.helloworld.server.Http2ServerInitializer.initChannel(Http2ServerInitializer.java:42)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

It is worth to mention that this happen in JDK8. With JDK9 it works correctly. It is also worth to mention that a plain text upgrade to HTTP/2 works correctly.

### Actual behavior

Described the above.

### Steps to reproduce

1. Start the Http2Server with SSL parameter
2. Invoke `curl -k -v --http2-prior-knowledge https://127.0.0.1:8443`

### Minimal yet complete reproducer code (or URL to code)

Described the above.

### Netty version

>= 4.1.10. Previously in Infinispan we used 4.1.9 and this worked correctly.

### JVM version (e.g. `java -version`)

```
JDK8:
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

JDK9:
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```

### OS version (e.g. `uname -a`)

```
Linux slaskawi 4.15.4-200.fc26.x86_64 #1 SMP Mon Feb 19 19:43:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by slaskawi** [comment]
I think this might be related with https://github.com/netty/netty/issues/7744 in some way.

**Comment by slaskawi** [comment]
After looking a bit more into code I think I understand what's going on:
* In `JdkAlpnApplicationProtocolNegotiator`, `ConscryptAlpnSslEngine.isAvailable()` returns `true`. So we are assuming that we can use Conscrypt ALPN.
* Then in `AlpnWrapper#wrapSslEngine` we try to wrap the engine but it turned out that this is pure JDK SSLEngine, not Conscrypt. That's why we're observing the exception.

The thing is that you can always use `JdkSslContext`, which will give you JDK's SSLEngine. This seems incorrect to me. Maybe we should prevent users from using `JdkSslContext` when using ALPN (it's more like a though actually)?

**Comment by normanmaurer** [comment]
Let me look into it

**Comment by slaskawi** [comment]
We also noticed similar failures in Infinispan, after migrating to `4.1.21`. However we are using a [custom SSLEngine](https://github.com/infinispan/infinispan/blob/master/server/core/src/main/java/io/netty/handler/ssl/ALPNHackSSLEngine.java). So I think in that case we would need also a custom ALPN Negotiator... or switch to Conscrypt...

**Comment by normanmaurer** [comment]
@slaskawi do you have a stacktrace ?

**Comment by slaskawi** [comment]
@normanmaurer From Infinispan - unfortunately no. I was looking into it a while ago in a completely dirty workspace. As for the `HTTP2Server` - yes, it's in ticket description but let me repaste it:

```
java.lang.RuntimeException: Unable to wrap SSLEngine of type sun.security.ssl.SSLEngineImpl
	at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$AlpnWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:132)
	at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:249)
	at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:227)
	at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:903)
	at io.netty.example.http2.helloworld.server.Http2ServerInitializer.configureSsl(Http2ServerInitializer.java:83)
	at io.netty.example.http2.helloworld.server.Http2ServerInitializer.initChannel(Http2ServerInitializer.java:73)
	at io.netty.example.http2.helloworld.server.Http2ServerInitializer.initChannel(Http2ServerInitializer.java:42)
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:113)
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:105)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:597)
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:44)
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1387)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1122)
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:647)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:506)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:419)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:478)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by normanmaurer** [comment]
@slaskawi hmm works for me from within the netty project. Can you please list the exact steps you did ?

**Comment by slaskawi** [comment]
@normanmaurer Ok, I think I know what happened... 

The issue exists on tag `netty-4.1.10.Final` but is not present on `netty-4.1.22.Final` and `HEAD` of course. I guess it has been fixed somewhere down the road. Sorry for confusion and thanks for checking it!

**Comment by normanmaurer** [comment]
Thanks for checking :)
