### ISSUE TITLE
Running tests in java 9 causes jdk.internal.misc.Unsafe exception.

### ISSUE THREAD

**Issue by Bhashinee** [netty/netty#7768]
We have used netty 4.1.19.Final version in our project. We recently moved to java 9. We have a test which uses netty's DefaultChannelGroup.

`ChannelGroup allChannels = new DefaultChannelGroup(GlobalEventExecutor.INSTANCE)`

When running that test case we get the following error,

```
[io.netty.util.internal.PlatformDependent0] : jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @36ebc363
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:312)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:303)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
	at io.netty.util.Signal$1.<init>(Signal.java:27)
	at io.netty.util.Signal.<clinit>(Signal.java:27)
	at io.netty.util.concurrent.DefaultPromise.<clinit>(DefaultPromise.java:43)WARNING: An illegal reflective access operation has occurred
	at io.netty.util.concurrent.GlobalEventExecutor.<init>(GlobalEventExecutor.java:44)
	at io.netty.util.concurrent.GlobalEventExecutor.<clinit>(GlobalEventExecutor.java:41)


```

### Steps to reproduce

Add following line in a main method and run in java 9.

```
 public static void main(String[] args) {
       Object exec = GlobalEventExecutor.INSTANCE;
    }
```

### Netty version
4.1.19.Final

### JVM version (e.g. `java -version`)
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

### OS version (e.g. `uname -a`)
16.04.1-Ubuntu

**Comment by normanmaurer** [comment]
Upgrade to latest Netty version as it was fixed there
