### ISSUE TITLE
Creating DefaultChannelGroup gives 'Reflective setAccessible(true) disabled' error

### ISSUE THREAD

**Issue by Bhashinee** [netty/netty#7769]
When executing the code under the 'Steps to reproduce' section in java 9 gives following error.
```
[io.netty.util.internal.PlatformDependent0] : direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:224)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:218)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:47)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:83)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:64)
	at org.wso2.transport.http.netty.contractimpl.websocket.Test123.main(Test123.java:12)
[io.netty.util.internal.PlatformDependent0] : java.nio.Bits.unaligned: unavailable true
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$5.run(PlatformDependent0.java:273)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:266)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:47)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:83)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:64)
	at org.wso2.transport.http.netty.contractimpl.websocket.Test123.main(Test123.java:12)
[io.netty.util.internal.PlatformDependent0] : jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @2a17b7b6
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:361)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:315)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:306)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:47)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:83)
	at io.netty.channel.group.DefaultChannelGroup.<init>(DefaultChannelGroup.java:64)
	at org.wso2.transport.http.netty.contractimpl.websocket.Test123.main(Test123.java:12)
```

### Steps to reproduce
Run following code in java 9.
```
import io.netty.channel.group.ChannelGroup;
import io.netty.channel.group.DefaultChannelGroup;
import io.netty.util.concurrent.GlobalEventExecutor;

/**
 * Test.
 */
public class Test123 {
    public static void main(String[] args) {
        ChannelGroup allChannels = new DefaultChannelGroup(GlobalEventExecutor.INSTANCE);
    }
}
```
### Netty version
4.1.22.Final

### JVM version (e.g. `java -version`)
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

### OS version (e.g. `uname -a`)
16.04.1-Ubuntu

**Comment by kiril-me** [comment]
@Bhashinee this is Java9 related issue. You should export jdk.internal.misc:
java --add-exports java.base/jdk.internal.misc=ALL-UNNAMED ...

**Comment by normanmaurer** [comment]
@Bhashinee this is expected and just a debug statement... This tells you we could not do some "optimizations" due jigsaw. You will need to do what @kiril-me said and may also need to specify the following system property to tell netty to try using reflective access: "-Dio.netty.tryReflectionSetAccessible=true"
