### ISSUE TITLE
Transferring a ByteBuf to Outputstream without duplicating memory

### ISSUE THREAD

**Issue by CodingFabian** [netty/netty#7804]
(running io.netty.buffer:4.1.21.Final)

I have a Java Output stream (java.io.OutputStream) I want to incrementally copy a ByteBuffer too.

The byte buffer is off heap and big.
I naively used:
    public abstract ByteBuf getBytes(int index, OutputStream out, int length) throws IOException;

assuming that it would copy all the data to the output stream.

It does, but to do so it copies the whole native buffer into the heap! I do not have that much heap, resulting in:

```
java.lang.OutOfMemoryError: Java heap space 
at io.netty.util.internal.PlatformDependent.allocateUninitializedArray(PlatformDependent.java:200) ~[40:io.netty.common:4.1.21.Final] 
at io.netty.buffer.UnpooledUnsafeHeapByteBuf.allocateArray(UnpooledUnsafeHeapByteBuf.java:34) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.allocateArray(UnpooledByteBufAllocator.java:144) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledHeapByteBuf.<init>(UnpooledHeapByteBuf.java:60) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledUnsafeHeapByteBuf.<init>(UnpooledUnsafeHeapByteBuf.java:29) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf.<init>(UnpooledByteBufAllocator.java:139) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledByteBufAllocator.newHeapBuffer(UnpooledByteBufAllocator.java:82) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:166) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:157) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnsafeByteBufUtil.getBytes(UnsafeByteBufUtil.java:572) ~[34:io.netty.buffer:4.1.21.Final] 
at io.netty.buffer.UnpooledUnsafeDirectByteBuf.getBytes(UnpooledUnsafeDirectByteBuf.java:365) ~[34:io.netty.buffer:4.1.21.Final] 
```

I checked io.netty.buffer.UnsafeByteBufUtil.getBytes(AbstractByteBuf, long, int, OutputStream, int)
and behold. It creates a heap bytebuffer of that size to copy the array into it and then to copy that to the output stream.

Bummer!

Shouldn't netty do this better by itself? it seems that I need to manually do this by using a (reasonably sized) byte array and read from byteBuf into that and flush that to my stream in a loop

**Comment by normanmaurer** [comment]
You are right...
Want to do a pr?

**Comment by CodingFabian** [comment]
Doing a userspace fix for my immediate need right now. 
The question for a netty internal implementation would be how big that buffer should be. right now its full size, so it can do that in one pass.
The typical buffer size is 8k. do we want this configurable (yet another method overload?)

**Comment by normanmaurer** [comment]
I think just using 8k (or less if the ByteBuf is smaller ) is ok for now
