### ISSUE TITLE
ArrayIndexOutOfBoundsException in AsciiString().indexOf()

### ISSUE THREAD

**Issue by Stefan-Weber** [netty/netty#7863]
### Actual behavior
Calling the method indexOf() in a special case throws ArrayIndexOutOfBoundsException.

java.lang.ArrayIndexOutOfBoundsException: 6
	at io.netty.util.AsciiString.indexOf(AsciiString.java:693)
	at ByteBufsTests.indexOfSuccess(ByteBufsTests.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
...

### Steps to reproduce
Run the following 2 lines of JUnit code, I hope this is enough for reproduction.

### Minimal yet complete reproducer code (or URL to code)
Assert.assertEquals("Test success in 4.1.(22|23).Final", 3, new AsciiString("012345").indexOf("345", 3));
Assert.assertEquals("Test fails with 'ArrayIndexOutOfBoundsException: 6' in 4.1.23.Final", -1, new AsciiString("012345").indexOf("abc", 3));

### Netty version
4.1.23.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

### OS version (e.g. `uname -a`)
Win7

**Comment by normanmaurer** [comment]
@Stefan-Weber yes thanks... working on a patch
