### ISSUE TITLE
The number of threads has exploded

### ISSUE THREAD

**Issue by echokk11** [netty/netty#7913]
### Actual behavior
The number of threads has exploded, server is hangup at last. But CPU is fine.

### Steps to reproduce
run for a while

### Minimal yet complete reproducer code (or URL to code)
lots of thread info like this
```
"nioEventLoopGroup-3-7" prio=10 tid=0x00007f6e14045800 nid=0x557e runnable [0x00007f6dd7dbc000]
       java.lang.Thread.State: RUNNABLE
    	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
    	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
    	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:79)
    	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
    	- locked <0x0000000702fc9c90> (a io.netty.channel.nio.SelectedSelectionKeySet)
    	- locked <0x0000000702fc9d80> (a java.util.Collections$UnmodifiableSet)
    	- locked <0x0000000702fc9ca8> (a sun.nio.ch.EPollSelectorImpl)
    	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
    	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
    	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
    	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    	at java.lang.Thread.run(Thread.java:745)
```
### Netty version
4.1.22.Final

### JVM version (e.g. `java -version`)
java version "1.7.0_79"
### OS version (e.g. `uname -a`)
centos 7
Linux iZ23639ct9zZ 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@echokk11 sorry but you will have to give a bit more details about what you expect and what you see. Also some code would help to understand what you are doing. The stacktrace you showed basically only means that the Selector waits for IO to process (which is expected)

**Comment by normanmaurer** [comment]
@echokk11 so did you find the problem ?

**Comment by normanmaurer** [comment]
or you think there is no problem at all ?

**Comment by echokk11** [comment]
Not yet.sorry to trouble you , maybe it is my own problem. I am trying my best to find it out.
