### ISSUE TITLE
Http2MultiplexCodec.handlerRemoved() throws Exception on Channel#close()

### ISSUE THREAD

**Issue by Bennett-Lynch** [netty/netty#7963]
_Let me preface this by saying that I'm not convinced this is a bug with Netty and I might be doing something wrong based on my understanding of how to close channels with `Http2MultiplexCodec`._

### Expected behavior

Closing a channel with Http2MultiplexCodec and all idle streams should not throw an exception.

### Actual behavior

Closing a channel with Http2MultiplexCodec and all idle streams results in the following:

```
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:273)
	at io.netty.handler.codec.http2.Http2MultiplexCodec.channelRead(Http2MultiplexCodec.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	...
```

```
io.netty.util.IllegalReferenceCountException: refCnt: 0, increment: 1
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release0(AbstractReferenceCountedByteBuf.java:100)
	at io.netty.buffer.AbstractReferenceCountedByteBuf.release(AbstractReferenceCountedByteBuf.java:84)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:367)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:427)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	...
```

```
May 23, 2018 10:47:02 AM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.channel.ChannelPipelineException: io.netty.handler.codec.http2.Http2MultiplexCodec.handlerRemoved() has thrown an exception.
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:676)
	at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:922)
	at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:888)
	at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:880)
	at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46)
	...
```

This appears to be thrown from the following:

https://github.com/netty/netty/blob/1df5b02fd95bf77683b20de87556f5b20cd75979/codec-http2/src/main/java/io/netty/handler/codec/http2/Http2ConnectionHandler.java#L284-L289

### Steps to reproduce

* Create a client/server using `Http2MultiplexCodecBuilder`
* For the sake of simplicity, use a `Http2StreamFrameToHttpObjectCodec` and `HttpObjectAggregator` in the child channel pipeline
* Initiate a connection, await the `Http2ConnectionPrefaceAndSettingsFrameWrittenEvent`, open a new child channel with `Http2StreamChannelBootstrap`, and write a trivial `FullHttpRequest` to the child channel
* Await the server's `FullHttpResponse`
* Close the channel on the client side

### Minimal yet complete reproducer code (or URL to code)

Apologies, but none.  No working client/server `Http2MultiplexCodec` in the repository examples to work with.

### Netty version

4.1.24.Final

### JVM version (e.g. `java -version`)

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

### OS version (e.g. `uname -a`)

Linux

**Comment by normanmaurer** [comment]
Before I start to investigate can you upgrade to 4.1.25.Final and see if you still see it ?

**Comment by Bennett-Lynch** [comment]
Just ran it with 4.1.25.Final and it did not throw any exceptions.

Sorry for the false alarm, didn't realize there was a recent fix in this area.

Thanks for the quick fix. ;)

**Comment by Bennett-Lynch** [comment]
For reference: https://github.com/netty/netty/pull/7894

**Comment by normanmaurer** [comment]
@Bennett-Lynch no worries... thanks for testing :)
