### ISSUE TITLE
use  FixedChannelPool get channel happen BlockingOperationException

### ISSUE THREAD

**Issue by mazijun104** [netty/netty#7982]
Exception:

io.netty.util.concurrent.BlockingOperationException: DefaultPromise@329e2ef8(incomplete)
	at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:391) ~[netty-all-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.DefaultPromise.await0(DefaultPromise.java:587) ~[netty-all-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:273) ~[netty-all-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:46) ~[netty-all-4.1.19.Final.jar:4.1.19.Final]

code:

 poolMap = new AbstractChannelPoolMap<InetSocketAddress, SimpleChannelPool>() {
                @Override
                protected SimpleChannelPool newPool(InetSocketAddress key) {
                    return new FixedChannelPool(SingleBootstrap.bootstrap.remoteAddress(key), new UkPoolHandler(), UK_CONNECT_NUM);
                }
            };

protected Channel getChannel(ChannelPoolMap<InetSocketAddress, SimpleChannelPool> poolMap, InetSocketAddress address) {
		pool = poolMap.get(address);
		Future<Channel> future = pool.acquire();
		try {
			Channel channel = future.get(ClientConstants.GET_CONN_TIMEOUT, TimeUnit.MILLISECONDS);
			if (channel == null || !channel.isActive()) {
				Thread.sleep(ClientConstants.RETRY_SPLIT_TIME);
				return getChannel(poolMap, address);
			}
			connected = true;
			return channel;
		} catch (Exception e) {
			logger.error("获取channel异常", e);
		}
		return null;
	}

**Comment by mazijun104** [comment]
netty version  4.1.19.Final

**Comment by mazijun104** [comment]
Thank you for your answer
