### ISSUE TITLE
Failed to submit a listener notification task. Event loop shut down? while Shutting down Etcd4j Netty client

### ISSUE THREAD

**Issue by SantoshNesaragi** [netty/netty#8010]
Defined two camel routes to perform ETCD CRUD operation while shutting down Etcd4j Netty client i am getting 

 ERROR   --- [entExecutor-1-1] i.n.u.c.D.rejectedExecution              : Failed to submit a listener notification task. Event loop shut down?

java.util.concurrent.RejectedExecutionException: event executor terminated
	at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:840)
	at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:342)
	at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765)
	at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:767)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:435)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:120)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:87)
	at io.netty.channel.AbstractChannelHandlerContext.safeExecute(AbstractChannelHandlerContext.java:1022)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:620)
	at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:475)
	at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964)
	at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234)
	at io.netty.resolver.dns.DnsNameResolver.close(DnsNameResolver.java:310)
	at io.netty.resolver.dns.InflightNameResolver.close(InflightNameResolver.java:61)
	at io.netty.resolver.InetSocketAddressResolver.close(InetSocketAddressResolver.java:94)
	at io.netty.resolver.AddressResolverGroup$1.operationComplete(AddressResolverGroup.java:79)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:514)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:486)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:438)
	at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:233)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

Using Apache camel 2.18.2 version which has inbuilt camel-etcd and netty , JVM 1.8 on windows 10 OS

**Comment by normanmaurer** [comment]
From the stack trace it looks like you shutdown the `EventLoopGroup` that is used by the `resolver` before the resolver itself. You will need to flip the ordering here.
