### ISSUE TITLE
get  exception DefaultChannelPromise@72f53755(incomplete) when using netty client to visit web side with WSS protocol

### ISSUE THREAD

**Issue by shengqr** [netty/netty#8065]
### Expected behavior
WSS protocol handshake success
### Actual behavior
io.netty.util.concurrent.BlockingOperationException: DefaultChannelPromise@72f53755(incomplete)
	at io.netty.util.concurrent.DefaultPromise.checkDeadLock(DefaultPromise.java:391)
	at io.netty.channel.DefaultChannelPromise.checkDeadLock(DefaultChannelPromise.java:157)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:226)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:129)
	at io.netty.channel.DefaultChannelPromise.await(DefaultChannelPromise.java:28)
	at io.netty.util.concurrent.DefaultPromise.sync(DefaultPromise.java:333)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:117)
	at io.netty.channel.DefaultChannelPromise.sync(DefaultChannelPromise.java:28)
	at com.netty.ws.util.WebSocketClientHandler.channelActive(WebSocketClientHandler.java:51)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelActive(CombinedChannelDuplexHandler.java:414)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:64)
	at io.netty.channel.CombinedChannelDuplexHandler.channelActive(CombinedChannelDuplexHandler.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.handler.ssl.SslHandler.channelActive(SslHandler.java:1617)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1322)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:902)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	at java.lang.Thread.run(Thread.java:748)
### Minimal yet complete reproducer code (or URL to code)
client code:
static String url = "wss://localhost:1443/websocket?version=j1.0";
final URI uri = new URI(url);
        String scheme = uri.getScheme() == null? "ws" : uri.getScheme();  
        final String host = uri.getHost() == null? "127.0.0.1" : uri.getHost();  
        final int port;  
        if (uri.getPort() == -1) {  
            if ("ws".equalsIgnoreCase(scheme)) {  
                port = 80;  
            } else if ("wss".equalsIgnoreCase(scheme)) {  
                port = 1443;  
            } else {  
                port = -1;  
            }
        } else {  
            port = uri.getPort();  
        }  
  
        if (!"ws".equalsIgnoreCase(scheme) && !"wss".equalsIgnoreCase(scheme)) {  
            System.err.println("Only WS(S) is supported.");  
            return;  
        }  
  
        final boolean ssl = "wss".equalsIgnoreCase(scheme);  
        final SslContext sslCtx;  
        if (ssl) {  
            sslCtx = SslContextBuilder.forClient().trustManager(InsecureTrustManagerFactory.INSTANCE).build();
        } else {  
            sslCtx = null;  
        }  
  
        EventLoopGroup group = new NioEventLoopGroup();
       
        try {  
            final WebSocketClientHandler handler =  
                    new WebSocketClientHandler(  
                            WebSocketClientHandshakerFactory.newHandshaker(  
                                    uri, WebSocketVersion.V13, null, true, new DefaultHttpHeaders()),data);

            final SSLEngine sslEngine = SSLContext.getDefault().createSSLEngine();
            sslEngine.setUseClientMode(true);
            sslEngine.setNeedClientAuth(false);
            sslEngine.setWantClientAuth(false);
            Bootstrap b = new Bootstrap();  
            b.group(group).option(ChannelOption.SO_KEEPALIVE, true)
             .channel(NioSocketChannel.class)  
             .handler(new ChannelInitializer<SocketChannel>() {  
                 @Override  
                 protected void initChannel(SocketChannel ch) {  
                     ChannelPipeline p = ch.pipeline();  
                     if (ssl) {
                         p.addLast(new SslHandler(sslEngine));  
                     }  
                     p.addLast(
                    		 new HttpClientCodec(),
                    		 new HttpObjectAggregator(8192),
                    		 handler
                    		 );
                 }  
             });  
  
            ChannelFuture future = b.connect(host, port).sync();
            future.addListener(new ChannelFutureListener(){
            	
            	@Override
				public void operationComplete(ChannelFuture future) throws Exception {
					// TODO Auto-generated method stub
					if(future.isSuccess()){
						System.out.println("connect success");
						
					}else{
						System.out.println(future.cause());
					}
				}
            });

ChannelHandler code:
public class WebSocketClientHandler extends SimpleChannelInboundHandler<Object> {  
    
    private final WebSocketClientHandshaker handshaker;  
    private ChannelPromise handshakeFuture; 
    private String data;
  
    public WebSocketClientHandler(WebSocketClientHandshaker handshaker,String data) {  
        this.handshaker = handshaker;
        this.data = data;
        System.out.println("URL："+handshaker.uri());
        
    }  
  
    public ChannelFuture handshakeFuture() {
    	System.out.println("return handshakeFuture");
        return handshakeFuture;
    }  
  
    @Override  
    public void handlerAdded(ChannelHandlerContext ctx) {  
        handshakeFuture = ctx.newPromise();
        System.out.println("handleradded");
    }  
  
    @Override  
    public void channelActive(ChannelHandlerContext ctx) {
    	ChannelFuture f = null;
		try {
			f = handshaker.handshake(ctx.channel()).sync();
		} catch (InterruptedException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	System.out.println("handshake error："+f.cause());
    	System.out.println("handshake status："+handshaker.isHandshakeComplete());
//		ctx.writeAndFlush(Unpooled.copiedBuffer(data.getBytes(Charset.forName("utf-8"))));
		
    }  
  
    @Override  
    public void channelInactive(ChannelHandlerContext ctx) {
    	
        System.out.println("InActive: WebSocket Client disconnected!");  
    }
  
    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception{
    	System.out.println("AAAAAAAAAAA");
    	channelRead0(ctx, msg);
    }
    @Override  
    public void channelRead0(ChannelHandlerContext ctx, Object msg) throws Exception {
    	System.out.println("channelRead0");
        Channel ch = ctx.channel();  
        if (!handshaker.isHandshakeComplete()) {  
            handshaker.finishHandshake(ch, (FullHttpResponse) msg);  
            System.out.println("WebSocket Client connected!");  
            handshakeFuture.setSuccess();  
            return;  
        }  
  
        if (msg instanceof HttpResponse) {  
            FullHttpResponse response = (FullHttpResponse) msg;  
            throw new IllegalStateException(  
                    "Unexpected FullHttpResponse (getStatus=" + response.getStatus() +  
                            ", content=" + response.content().toString(CharsetUtil.UTF_8) + ')');  
        }  
  
        WebSocketFrame frame = (WebSocketFrame) msg;  
        if (frame instanceof TextWebSocketFrame) {  
            TextWebSocketFrame textFrame = (TextWebSocketFrame) frame;  
            System.out.println("WebSocket Client received message: " + textFrame.text());  
        } else if (frame instanceof PongWebSocketFrame) {  
            System.out.println("WebSocket Client received pong");  
        } else if (frame instanceof CloseWebSocketFrame) {  
            System.out.println("WebSocket Client received closing");  
            ch.close();  
        }  
    }  
  
    @Override
    public void userEventTriggered(ChannelHandlerContext ctx, Object evt){
    	if(handshaker.isHandshakeComplete()){
    		ctx.pipeline().remove(HttpClientCodec.class);
    		ctx.pipeline().remove(HttpObjectAggregator.class);
    		ctx.pipeline().remove(SslHandler.class);
    		System.out.println("remove success");
    	}
    }
    @Override  
    public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {  
        cause.printStackTrace();  
        if (!handshakeFuture.isDone()) {  
            handshakeFuture.setFailure(cause);  
        }  
        System.out.println("AAAAAAAAAAAAAA:"+cause);
        ctx.close();  
    }  
}  
### Netty version
netty-4.1.13
### JVM version (e.g. `java -version`)
jdk-1.8.131
### OS version (e.g. `uname -a`)
windows 7

**Comment by normanmaurer** [comment]
That's expected you call `sync()` in the `EventLoop`. This is not allowed as this would lead to a dead-lock.

You used `f = handshaker.handshake(ctx.channel()).sync();`. You should use a `FutureListener`.

**Comment by shengqr** [comment]
thank you very much for replay so fast, I try it

**Comment by shengqr** [comment]
I remove call sync(), it not throw exception now, but it handshake failed yet

**Comment by shengqr** [comment]
how to use ssl handler right in client ?  ssl handler is ok in my code?

**Comment by shengqr** [comment]
I add a FutureListener to handshake,  i get exception:

**Comment by shengqr** [comment]
java.nio.channels.ClosedChannelException
	at io.netty.handler.ssl.SslHandler.channelInactive(...)(Unknown Source)
