### ISSUE TITLE
netty io.netty.util.internal.OutOfDirectMemoryError

### ISSUE THREAD

**Issue by yu199195** [netty/netty#8081]
this is error:
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 100663303, max: 104857600)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640) ~[netty-common-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594) ~[netty-common-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764) ~[netty-buffer-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740) ~[netty-buffer-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244) ~[netty-buffer-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214) ~[netty-buffer-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146) ~[netty-buffer-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324) ~[netty-buffer-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185) ~[netty-buffer-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176) ~[netty-buffer-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137) ~[netty-buffer-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114) ~[netty-transport-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.channel.epoll.EpollRecvByteAllocatorHandle.allocate(EpollRecvByteAllocatorHandle.java:71) ~[netty-transport-native-epoll-4.1.24.Final-linux-x86_64.jar!/:4.1.24.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:793) ~[netty-transport-native-epoll-4.1.24.Final-linux-x86_64.jar!/:4.1.24.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:387) [netty-transport-native-epoll-4.1.24.Final-linux-x86_64.jar!/:4.1.24.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-common-4.1.24.Final.jar!/:4.1.24.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309) [netty-transport-native-epoll-4.1.24.Final-linux-x86_64.jar!/:4.1.24.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.24.Final.jar!/:4.1.24.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]

i find netty use DIRECT_MEMORY_COUNTER To count the memory out of the heap
in the PlatformDependent.java 101 line.
i try debug ,It just adds up ,it doesn't decrease. why?
As the number of requests increases, It will definitely exceed the size of the memory outside the heap.
its netty bug?
netty vesion 4.1.25
JDK 1.8 
os: liunx

**Comment by normanmaurer** [comment]
See https://github.com/netty/netty/issues/8082 ...

You may need to adjust the configuration of `PooledByteBufAllocator` depending on how many `EventLoop`s you use etc.

**Comment by yu199195** [comment]
i find netty use DIRECT_MEMORY_COUNTER To count the memory out of the heap
in the PlatformDependent.java 101 line.
i try debug ,It just adds up ,it doesn't decrease. why?
As the number of requests increases, It will definitely exceed the size of the memory outside the heap.
its netty bug?

**Comment by yu199195** [comment]
@normanmaurer i find netty use DIRECT_MEMORY_COUNTER To count the memory out of the heap
in the PlatformDependent.java 101 line.
i try debug ,It just adds up ,it doesn't decrease. why?
As the number of requests increases, It will definitely exceed the size of the memory outside the heap.
its netty bug?
