### ISSUE TITLE
if  OutOfDirectMemoryError . netty Circular output log Blow up the server disk

### ISSUE THREAD

**Issue by yu199195** [netty/netty#8082]
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 16777216 byte(s) of direct memory (used: 16777223, max: 20971520)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594) ~[netty-common-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764) ~[netty-buffer-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740) ~[netty-buffer-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244) ~[netty-buffer-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:214) ~[netty-buffer-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:146) ~[netty-buffer-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324) ~[netty-buffer-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185) ~[netty-buffer-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176) ~[netty-buffer-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137) ~[netty-buffer-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147) ~[netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [netty-transport-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-common-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]

netty  4.1.25
jdk 1.8 
os : liunx

**Comment by yu199195** [comment]
i set  -Dio.netty.maxDirectMemory=20971520

**Comment by normanmaurer** [comment]
@yu199195 its exactly what the exception tells you. The amount of memory you try to allocate (or in this case the `PooledByteBufAllocator` is large then the limit that you used. 20mb is really to low when using pooling. If you have such a tight memory constraint you should use the `UnpooledByteBufAllocator`, which can be done during bootstrap via `ChannelOptions.ALLOCATOR`.

**Comment by normanmaurer** [comment]
and it fills the disk because it throws exceptions and you log it ;)

**Comment by yu199195** [comment]
@normanmaurer  now  i set -Dio.netty.maxDirectMemory=20971520 for test 
i alos set -Dio.netty.maxDirectMemory=2g 
but also happe OutOfDirectMemoryError.
in my debug , in PlatformDependent.java   this DIRECT_MEMORY_LIMIT attr  It will only add up, not decrease why？If so, the size of the Settings will be full。。

**Comment by normanmaurer** [comment]
It will be decreased once the memory is given back.... I suspect it is still in use by the `PooledByteBufAllocator`.

**Comment by yu199195** [comment]
now i use netty4.1.25，but No matter how much memory I set outside the heap, it will overflow
I found it by debugging DIRECT_MEMORY_LIMIT  not be decreased。。

**Comment by normanmaurer** [comment]
The first 16 MB per `PoolArena` is never given back as we expect it will be reused frequently (just as in jemalloc). By default you will use 2 * cores PoolArena when using the `PooledByteBufAllocator`. The rest will be returned as soon as there is no more usage in the 16MB chunk. 

You can adjust the number of used `PoolArena`s either via a System property (check `PooledByteBufAllocator` or the constructor of `PooledByteBufAllocator`.

**Comment by normanmaurer** [comment]
Again if you have tight memory limits you may be better of using `UnpooledByteBufAllocator` which will return memory directly once `ByteBuf.release()` is called and its reference count is 0.

**Comment by yu199195** [comment]
thanks，i know what you mean，using UnpooledByteBufAllocator 。。
but now  i set  -Dio.netty.maxDirectMemory=4g ，The same mistake will happen ，I don't know where the leak happened

**Comment by normanmaurer** [comment]
@yu199195 enable paranoid leak detection and check if there is anything logged. You may forgot to release buffers somewhere:

http://netty.io/wiki/reference-counted-objects.html#wiki-h2-10

**Comment by yu199195** [comment]
let my try。。I'm a little confused ，In a request, DIRECT_MEMORY_COUNTER accumulate
for example ：
 if (DIRECT_MEMORY_COUNTER != null) {
            for (;;) {
                long usedMemory = DIRECT_MEMORY_COUNTER.get();
                long newUsedMemory = usedMemory + capacity;
                if (newUsedMemory > DIRECT_MEMORY_LIMIT) {
                    throw new OutOfDirectMemoryError("failed to allocate " + capacity
                            + " byte(s) of direct memory (used: " + usedMemory + ", max: " + DIRECT_MEMORY_LIMIT + ')');
                }
                if (DIRECT_MEMORY_COUNTER.compareAndSet(usedMemory, newUsedMemory)) {
                    break;
                }
            }
        }

but End of the request DIRECT_MEMORY_COUNTER not be decreased。。。
