### ISSUE TITLE
Fails to load native library when shading Netty epoll or kqueue (osx or linux)

### ISSUE THREAD

**Issue by cchantep** [netty/netty#8090]
### Expected behavior

With shaded Netty libraries, succeed to call `foo.io.netty.channel.epoll.Epoll.ensureAvailability()` (with `foo.` being the package prefix) or `foo.io.netty.channel.kqueue.KQueue.ensureAvailability()` without `Exception`.

### Actual behavior

When calling the `.ensureAvailability()` or directly loading a Netty native lib, then an `UnsatisfiedLinkError` is thrown with root cause `RuntimeException: failed to get method ID: DatagramSocketAddress.<init>(String, int, int, DatagramSocketAddress) [error] at java.base/java.lang.ClassLoader$NativeLibrary.load(Native Method)`.

*Mac OS X/kqueue:*

```
[error] java.lang.UnsatisfiedLinkError: failed to load the required native library [error] at foo.io.netty.channel.kqueue.KQueue.ensureAvailability(KQueue.java:78) ... [error] Caused by: java.lang.UnsatisfiedLinkError: could not load a native library: foo_netty_transport_native_kqueue_x86_64 [error] at foo.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:205) [error] at foo.io.netty.channel.kqueue.Native.loadNativeLibrary(Native.java:125) [error] at foo.io.netty.channel.kqueue.Native.<clinit>(Native.java:60) [error] at foo.io.netty.channel.kqueue.KQueue.<clinit>(KQueue.java:37) [error] at foo.Main$.delayedEndpoint$foo$Main$1(Main.scala:6) [error] at foo.Main$delayedInit$body.apply(Main.scala:5) ... [error] Caused by: java.lang.RuntimeException: failed to get method ID: DatagramSocketAddress.<init>(String, int, int, DatagramSocketAddress) [error] at java.base/java.lang.ClassLoader$NativeLibrary.load(Native Method) [error] at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2614) [error] at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2499) [error] at java.base/java.lang.Runtime.load0(Runtime.java:812) [error] at java.base/java.lang.System.load(System.java:1821) [error] at foo.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36) [error] at foo.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:243) [error] at foo.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:187) [error] at foo.io.netty.channel.kqueue.Native.loadNativeLibrary(Native.java:125) [error] at foo.io.netty.channel.kqueue.Native.<clinit>(Native.java:60) [error] at foo.io.netty.channel.kqueue.KQueue.<clinit>(KQueue.java:37)
```

*Linux/epoll:*

```
[error] Caused by: java.lang.UnsatisfiedLinkError: failed to load the required native library [error] at foo.io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:88) [error] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [error] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [error] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [error] at java.lang.reflect.Method.invoke(Method.java:498) ... [error] Caused by: java.lang.UnsatisfiedLinkError: could not load a native library: foo_netty_transport_native_epoll_x86_64 [error] at foo.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:205) [error] at foo.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:183) [error] at foo.io.netty.channel.epoll.Native.<clinit>(Native.java:61) [error] at foo.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39) [error] at java.lang.Class.forName0(Native Method) [error] at java.lang.Class.forName(Class.java:264) [error] at foo.Main$.$anonfun$cls$1(Main.scala:6) ... [error] Caused by: java.lang.RuntimeException: failed to get method ID: DatagramSocketAddress.<init>(String, int, int, DatagramSocketAddress) [error] at java.lang.ClassLoader$NativeLibrary.load(Native Method) [error] at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941) [error] at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824) [error] at java.lang.Runtime.load0(Runtime.java:809) [error] at java.lang.System.load(System.java:1086) [error] at foo.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:36) [error] at foo.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:243) [error] at foo.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:187) [error] at foo.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:183) [error] at foo.io.netty.channel.epoll.Native.<clinit>(Native.java:61) [error] at foo.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
```

### Minimal yet complete reproducer code (or URL to code)

https://github.com/cchantep/netty-native-shading

### Netty version

4.1.25-Final

### JVM version (e.g. `java -version`)

1.{8, 9}

### OS version (e.g. `uname -a`)

{osx, linux}-x64_86

**Comment by normanmaurer** [comment]
@Scottmitch can you check as you setup our usage of it if I remember correctly.

**Comment by cchantep** [comment]
I'm wondering whether the `packagePrefix` should be used when calling [`env->GetMethodID(..)`](https://github.com/netty/netty/blob/4.1/transport-native-unix-common/src/main/c/netty_unix_socket.c#L1025)? As classes from netty-transport-native-unix-common are shaded along with kqueue or epoll? To look for something like `"(Ljava/lang/String;IILfoo/io/netty/channel/unix/DatagramSocketAddress;)V"` ?

**Comment by normanmaurer** [comment]
@cchantep btw is it still working after this is thrown or not ?

**Comment by normanmaurer** [comment]
@cchantep I did some more digging and you are right... This was "broken" by https://github.com/netty/netty/commit/b818852cdb0ee56ce3cf939e2faa538d519baabd. Which is most likely also the reason why we did not see it yet as this was only in the last release. I tried to modify your reproducer to use a snapshot version to verify a fix but did not manager to do so. Could you please try the PR https://github.com/netty/netty/pull/8091 and let me know if this works ? 

I think we also should include some sort of integration test that validates that shading works as expected. Need to think about how to do this tho.

**Comment by cchantep** [comment]
Thx @normanmaurer, I will try the reproducer with your branch.

**Comment by cchantep** [comment]
It seems OK with the reproducer, will confirm it with the original project. Thx.

**Comment by normanmaurer** [comment]
@cchantep please report back once done.

**Comment by cchantep** [comment]
Thx @normanmaurer , I can confirm it's ok after your fix.
