### ISSUE TITLE
NetworkInterface.getNetworkInterfaces() Blocked

### ISSUE THREAD

**Issue by wanlxp** [netty/netty#8094]
### Expected behavior
Get network interfaces and return

### Actual behavior
The code block here, the thread can't continue, i use jstack, the thread is always here, but the thread state is runable:
"init_context_comm_t0" #14 daemon prio=5 os_prio=0 tid=0x00007f5fdc889800 nid=0x27 in Object.wait() [0x00007f5fd7ffc000]
   java.lang.Thread.State: RUNNABLE
  at io.netty.util.NetUtil.<clinit>(NetUtil.java:156)
  at java.lang.ClassLoader$NativeLibrary.load(Native Method)
  at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
  - locked <0x00000000835e5868> (a java.util.Vector)
  - locked <0x00000000837abda8> (a java.util.Vector)
  at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
  at java.lang.Runtime.load0(Runtime.java:809)
  - locked <0x0000000083320da8> (a java.lang.Runtime)
  at java.lang.System.load(System.java:1086)
  at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:214)
  at io.netty.channel.epoll.Native.<clinit>(Native.java:60)
  at io.netty.channel.epoll.IovArray.<clinit>(IovArray.java:57)
  at io.netty.channel.epoll.EpollEventLoop.<init>(EpollEventLoop.java:60)
  at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:106)
  at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:64)
  at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
  at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:91)
  at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:78)
  at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:59)
  at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:43)
  at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:36)
  at com.sunyainfo.sunyacloud.communication.server.CommunicateEndpoint.<init>(CommunicateEndpoint.java:46)
  at com.sunyainfo.sunyacloud.communication.server.CommunicateEndpoint.init(CommunicateEndpoint.java:115)
  at com.sunyainfo.sunyacloud.mvc.ContextListener$1.run(ContextListener.java:39)
  at java.lang.Thread.run(Thread.java:748)

### Steps to reproduce
In the spring init code, call this:
group = SysUtil.isLinux()?new EpollEventLoopGroup():new NioEventLoopGroup();

### Minimal yet complete reproducer code (or URL to code)
group = SysUtil.isLinux()?new EpollEventLoopGroup():new NioEventLoopGroup();

### Netty version
4.0.36.Final

### JVM version (e.g. `java -version`)
openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

### OS version (e.g. `uname -a`)
Linux debian 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux

Tips: i run this code in docker

**Comment by normanmaurer** [comment]
@wanlxp can you please provide a full-reproducer using the latest netty release. I think this was fixed here:

https://github.com/netty/netty/commit/f921ea344e2117eb6398daaf903f0df272b916fe

This is included in 4.0.54.Final and later. See also https://github.com/netty/netty/issues/7458

**Comment by normanmaurer** [comment]
Please re-open if you still see the issue after upgrading.

**Comment by wanlxp** [comment]
@normanmaurer Thank you very much， the problem happens occasionally，I will update and retry.
