### ISSUE TITLE
NPE with BoringSSL when trying to init with unsupported Cipher

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#8170]
Trying to run the code from #8165 will NPE when a client attempts to connect.

```java
java.lang.NullPointerException: null
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.destroy(ReferenceCountedOpenSslContext.java:489) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.access$100(ReferenceCountedOpenSslContext.java:75) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$2.deallocate(ReferenceCountedOpenSslContext.java:122) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.util.AbstractReferenceCounted.release0(AbstractReferenceCounted.java:82) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.util.AbstractReferenceCounted.release(AbstractReferenceCounted.java:71) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.release(ReferenceCountedOpenSslContext.java:601) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:309) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:43) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:347) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:335) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:421) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:447) ~[netty-all-4.1.28.Final.jar:4.1.28.Final]
	at Main$1.initChannel(Main.java:40) ~[test/:?]
	at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:115) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:107) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.28.Final.jar:4.1.28.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Comment by normanmaurer** [comment]
Will try to check later today.
