### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no netty_transport_native_kqueue_x86_64 in java.library.path

### ISSUE THREAD

**Issue by Mrchenli** [netty/netty#8179]
### Minimal yet complete reproducer code (or URL to code)
when use redisTemplate
here is maven pom.xml
<dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-transport-native-kqueue</artifactId>
            <version>${netty.version}</version>
            <classifier>${os.detected.name}-${os.detected.arch}</classifier>
</dependency>
<extensions>
            <extension>
                <groupId>kr.motd.maven</groupId>
                <artifactId>os-maven-plugin</artifactId>
                <version>1.5.0.Final</version>
            </extension>
</extensions>

### Netty version
4.1.28.Final
### JVM version (e.g. `java -version`)
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)
### OS version (e.g. `uname -a`)
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88

**Comment by normanmaurer** [comment]
Please share the full debug log.

**Comment by Mrchenli** [comment]
DEBUG io.netty.util.internal.NativeLibraryLoader 71 DEVICE_ID: - -Dio.netty.native.workdir: /var/folders/k5/7_ykq_sn3dx16yjjjmrygj_m0000gn/T (io.netty.tmpdir)
2018-08-10 10:24:58.574 [main] DEBUG io.netty.util.internal.NativeLibraryLoader 81 DEVICE_ID: - Unable to load the library 'netty_transport_native_kqueue_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_kqueue_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:263)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:255)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:233)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:124)
	at io.netty.channel.kqueue.Native.loadNativeLibrary(Native.java:125)
	at io.netty.channel.kqueue.Native.<clinit>(Native.java:60)
	at io.netty.channel.kqueue.KQueue.<clinit>(KQueue.java:37)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.lettuce.core.KqueueProvider.<clinit>(KqueueProvider.java:55)
	at io.lettuce.core.Transports$NativeTransports.isSocketSupported(Transports.java:66)
	at io.lettuce.core.Transports.eventLoopGroupClass(Transports.java:38)
	at io.lettuce.core.AbstractRedisClient.getEventLoopGroup(AbstractRedisClient.java:184)
	at io.lettuce.core.AbstractRedisClient.channelType(AbstractRedisClient.java:172)
	at io.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:308)
	at io.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:276)
	at io.lettuce.core.RedisClient.connectStandalone(RedisClient.java:252)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:202)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:56)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:959)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:934)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:786)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:300)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:132)
	at org.springframework.data.redis.core.RedisConnectionUtils.bindConnection(RedisConnectionUtils.java:70)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:209)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:198)
	at com.iotbull.dataacceptence.server.session.SessionManagerTest.before(SessionManagerTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
2018-08-10 10:24:58.575 [main] DEBUG io.netty.util.internal.NativeLibraryLoader 86 DEVICE_ID: - netty_transport_native_kqueue_x86_64 cannot be loaded from java.libary.path, now trying export to -Dio.netty.native.workdir: /var/folders/k5/7_ykq_sn3dx16yjjjmrygj_m0000gn/T
java.lang.UnsatisfiedLinkError: no netty_transport_native_kqueue_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:243)
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:124)
	at io.netty.channel.kqueue.Native.loadNativeLibrary(Native.java:125)
	at io.netty.channel.kqueue.Native.<clinit>(Native.java:60)
	at io.netty.channel.kqueue.KQueue.<clinit>(KQueue.java:37)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at io.lettuce.core.KqueueProvider.<clinit>(KqueueProvider.java:55)
	at io.lettuce.core.Transports$NativeTransports.isSocketSupported(Transports.java:66)
	at io.lettuce.core.Transports.eventLoopGroupClass(Transports.java:38)
	at io.lettuce.core.AbstractRedisClient.getEventLoopGroup(AbstractRedisClient.java:184)
	at io.lettuce.core.AbstractRedisClient.channelType(AbstractRedisClient.java:172)
	at io.lettuce.core.RedisClient.connectStatefulAsync(RedisClient.java:308)
	at io.lettuce.core.RedisClient.connectStandaloneAsync(RedisClient.java:276)
	at io.lettuce.core.RedisClient.connectStandalone(RedisClient.java:252)
	at io.lettuce.core.RedisClient.connect(RedisClient.java:202)
	at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection(StandaloneConnectionProvider.java:56)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:959)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:934)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:786)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection(LettuceConnectionFactory.java:300)
	at org.springframework.data.redis.core.RedisConnectionUtils.doGetConnection(RedisConnectionUtils.java:132)
	at org.springframework.data.redis.core.RedisConnectionUtils.bindConnection(RedisConnectionUtils.java:70)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:209)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:184)
	at org.springframework.data.redis.core.AbstractOperations.execute(AbstractOperations.java:95)
	at org.springframework.data.redis.core.DefaultValueOperations.set(DefaultValueOperations.java:198)
	at com.iotbull.dataacceptence.server.session.SessionManagerTest.before(SessionManagerTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_kqueue_x86_64 in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
		at java.lang.Runtime.loadLibrary0(Runtime.java:870)
		at java.lang.System.loadLibrary(System.java:1122)
		at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:263)
		at java.security.AccessController.doPrivileged(Native Method)
		at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:255)
		at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:233)
		... 55 common frames omitted
2018-08-10 10:24:58.598 [main] DEBUG io.netty.util.internal.NativeLibraryLoader 76 DEVICE_ID: - Successfully loaded the library /var/folders/k5/7_ykq_sn3dx16yjjjmrygj_m0000gn/T/libnetty_transport_native_kqueue_x86_645386950238428147255.dylib
2018-08-10 10:24:58.599 [main] INFO  io.lettuce.core.KqueueProvider 101 DEVICE_ID: - Starting with kqueue library
2018-08-10 10:24:58.632 [lettuce-kqueueEventLoop-4-1] DEBUG io.netty.util.Recycler 76 DEVICE_ID: - -Dio.netty.recycler.maxCapacityPerThread: 4096

**Comment by Mrchenli** [comment]
but the last three logs shows successfully loaded the library  and starting with kqueue library

**Comment by normanmaurer** [comment]
@Mrchenli yeah we do try different loading strategies. So this is just fine... Thats why we log it in debug mode.

**Comment by zzy1fd** [comment]
How can we solve this problem

**Comment by xiaoyuyidai** [comment]
> @Mrchenli yeah we do try different loading strategies. So this is just fine... Thats why we log it in debug mode.

why print the Exception Log
if this is never something important， the best way is not to print it
we expend too many time to location error！！

**Comment by trustin** [comment]
@xiaoyuyidai wrote:

> if this is never something important， the best way is not to print it
we expend too many time to location error！！

As @normanmaurer said, we log the error at DEBUG level. You should not set `DEBUG` to the log level of `io.netty.*`. If so, you should reconfigure your logging framework properly, unless you want the detail only Netty devs will be interested in.

**Comment by chrisvest** [comment]
@xiaoyuyidai Adding to what Trustin said, the stack trace will now also only be logged when TRACE or FINEST level logging is enabled. Use a logging framework that has finer levels than DEBUG, and then only use DEBUG level. Then you won't get these stack traces.
