### ISSUE TITLE
AssertionError in Channel.config().getOptions() when nio is used

### ISSUE THREAD

**Issue by meshcow** [netty/netty#8182]
After migrating from 4.1.27.Final to 4.1.28.Final the following error appeared
### Expected behavior
no errors
### Actual behavior
```
java.lang.AssertionError: Option not found

	at sun.nio.ch.Net.getSocketOption(Net.java:360)
	at sun.nio.ch.ServerSocketChannelImpl.getOption(ServerSocketChannelImpl.java:177)
	at io.netty.channel.socket.nio.NioChannelOption.getOption(NioChannelOption.java:65)
	at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.getOption(NioServerSocketChannel.java:216)
	at io.netty.channel.DefaultChannelConfig.getOptions(DefaultChannelConfig.java:94)
	at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.getOptions(NioServerSocketChannel.java:225)
	at NettyNioChannelGetOptions.test(NettyNioChannelGetOptions.java:36)
```
### Steps to reproduce
run below test
### Minimal yet complete reproducer code (or URL to code)
```
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.Channel;
import io.netty.channel.ChannelHandler;
import io.netty.channel.ChannelHandlerContext;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import org.junit.Test;

import java.net.InetSocketAddress;
import java.net.SocketAddress;

public class NettyNioChannelGetOptions {

    @Test
    public void test() throws InterruptedException {
        ServerBootstrap bootstrap = new ServerBootstrap().
            group(new NioEventLoopGroup(1), new NioEventLoopGroup(1)).
            channel(NioServerSocketChannel.class).
            childHandler(new ChannelHandler() {
                @Override
                public void handlerAdded(ChannelHandlerContext ctx) {
                }

                @Override
                public void handlerRemoved(ChannelHandlerContext ctx) {
                }

                @Override
                public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause) {
                }
            });
        SocketAddress address = new InetSocketAddress("0.0.0.0", 18389);
        Channel channel = bootstrap.bind(address).sync().channel();
        channel.config().getOptions(); // throws java.lang.AssertionError: Option not found
        channel.close();
    }
}
```
### Netty version
4.1.28.Final
### JVM version (e.g. `java -version`)
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```
### OS version (e.g. `uname -a`)
OS X El Capitan 10.11.6 
`Darwin xxx 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64`

**Comment by normanmaurer** [comment]
Will check

**Comment by amizurov** [comment]
Same issue on my environment:
- JVM:
   ``java version "1.8.0_161"``
   ``Java(TM) SE Runtime Environment (build 1.8.0_161-b12)``
   ``Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)``
-  OS:
   ``macOS High Sierra``
   ``17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-     4570.71.2~1/RELEASE_X86_64 x86_64``

The option ``IP_TOS`` in the class ``ServerSocketChannelImpl.java:177`` try find for ``Net.UNSPEC`` family but in registry it is registered with ``StandardProtocolFamily.INET``.

**Comment by normanmaurer** [comment]
i had no time yet to look into t but at the end I think it’s a JDK bug that we just not triggered before. Will know more soon

**Comment by amizurov** [comment]
@normanmaurer You are right, small reproducer:

```@Test
    public void ipTosNotFound() throws IOException {
        ServerSocketChannel serverSocketChannel = ServerSocketChannel.open();
        serverSocketChannel.getOption(StandardSocketOptions.IP_TOS);
    }
 
But I don't know is it expected behavior or not ((

**Comment by meshcow** [comment]
I've made a quick check with same code on Ubuntu 14.04.5 & 16.04.3, same error:

Ubuntu 14.04.5 LTS, java 1.8.0_101:
```
java.lang.AssertionError: Option not found
        at sun.nio.ch.Net.getSocketOption(Net.java:360)
        at sun.nio.ch.ServerSocketChannelImpl.getOption(ServerSocketChannelImpl.java:177)
        at io.netty.channel.socket.nio.NioChannelOption.getOption(NioChannelOption.java:65)
        at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.getOption(NioServerSocketChannel.java:216)
        at io.netty.channel.DefaultChannelConfig.getOptions(DefaultChannelConfig.java:94)
        at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.getOptions(NioServerSocketChannel.java:225)
```
Ubuntu 16.04.3 LTS, java 1.8.0_144:
```
java.lang.AssertionError: Option not found
        at sun.nio.ch.Net.getSocketOption(Net.java:360)
        at sun.nio.ch.ServerSocketChannelImpl.getOption(ServerSocketChannelImpl.java:177)
        at io.netty.channel.socket.nio.NioChannelOption.getOption(NioChannelOption.java:65)
        at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.getOption(NioServerSocketChannel.java:216)
        at io.netty.channel.DefaultChannelConfig.getOptions(DefaultChannelConfig.java:94)
        at io.netty.channel.socket.nio.NioServerSocketChannel$NioServerSocketChannelConfig.getOptions(NioServerSocketChannel.java:225)
```

**Comment by normanmaurer** [comment]
Here is a PR with a workaround: https://github.com/netty/netty/pull/8183

**Comment by meshcow** [comment]
I've just tried 4.1.28.Final with #8183 applied -> LGTM

**Comment by normanmaurer** [comment]
@meshcow thanks!

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty/pull/8183
