### ISSUE TITLE
java.lang.ClassNotFoundException: io.netty.util.internal.OneTimeTask

### ISSUE THREAD

**Issue by issararab** [netty/netty#8203]
### Expected behavior
I am trying to create a connection from a java producer to amazonMQ broker using amqps wiring through the port 5671 but the connection fails and the exception raised is as follows.

### Actual behavior
13:26:42.897 [main] ERROR org.apache.qpid.jms.JmsConnection - Failed to connect to remote at: amqps://XXXXXXX-XXXXX-XXXX.amazonaws.com:5671
13:26:42.913 [nioEventLoopGroup-2-1] DEBUG io.netty.buffer.PoolThreadCache - Freed 3 thread-local buffer(s) from thread: nioEventLoopGroup-2-1
13:26:42.928 [main] DEBUG org.apache.qpid.jms.util.ThreadPoolUtils - Shutdown of ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@74a10858[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2] is shutdown: true and terminated: true took: 0.015 seconds.
Exception in thread "main" javax.jms.JMSException: Error while attempting to add new Connection to the pool
	at org.apache.activemq.jms.pool.PooledConnectionFactory.createJmsException(PooledConnectionFactory.java:266)
	at org.apache.activemq.jms.pool.PooledConnectionFactory.createConnection(PooledConnectionFactory.java:225)
	at org.fortiss.digicor.amazonmq.QpidClientExample.main(QpidClientExample.java:48)
Caused by: javax.jms.JMSException: io/netty/util/internal/OneTimeTask
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:86)
	at org.apache.qpid.jms.exceptions.JmsExceptionSupport.create(JmsExceptionSupport.java:108)
	at org.apache.qpid.jms.JmsConnection.connect(JmsConnection.java:168)
	at org.apache.qpid.jms.JmsConnectionFactory.createConnection(JmsConnectionFactory.java:203)
	at org.apache.activemq.jms.pool.PooledConnectionFactory.createConnection(PooledConnectionFactory.java:277)
	at org.apache.activemq.jms.pool.PooledConnectionFactory$1.makeObject(PooledConnectionFactory.java:95)
	at org.apache.activemq.jms.pool.PooledConnectionFactory$1.makeObject(PooledConnectionFactory.java:92)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.create(GenericKeyedObjectPool.java:1012)
	at org.apache.commons.pool2.impl.GenericKeyedObjectPool.addObject(GenericKeyedObjectPool.java:1192)
	at org.apache.activemq.jms.pool.PooledConnectionFactory.createConnection(PooledConnectionFactory.java:221)
	... 1 more
Caused by: java.io.IOException: io/netty/util/internal/OneTimeTask
	at org.apache.qpid.jms.util.IOExceptionSupport.create(IOExceptionSupport.java:45)
	at org.apache.qpid.jms.provider.amqp.AmqpProvider$1.run(AmqpProvider.java:218)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: io/netty/util/internal/OneTimeTask
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.handler.ssl.SslHandler.safeClose(SslHandler.java:1416)
	at io.netty.handler.ssl.SslHandler.closeOutboundAndChannel(SslHandler.java:1261)
	at io.netty.handler.ssl.SslHandler.close(SslHandler.java:459)
	at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624)
	at io.netty.channel.AbstractChannelHandlerContext.access$1100(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$13.run(AbstractChannelHandlerContext.java:613)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.lang.ClassNotFoundException: io.netty.util.internal.OneTimeTask
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 24 more

### Minimal yet complete reproducer code (or URL to code)
To reproduce the same exception please run the example in the following link:

https://aws.amazon.com/blogs/compute/migrating-from-rabbitmq-to-amazon-mq/

Example of "Qpid JMS queue example" at the bottom.

Note that in the examples he provide, the architect didn't mention any netty versions on his pom file .

### Netty version
When I first faced this problem, I had a look at pom file and find no Netty version. I included the dependency with the latest stable version "4.1.28.Final"

I typed the path to the class online and found that version netty-4.0.36.Final includes "io.netty.util.internal.OneTimeTask". I hve changed the version to this one still facing the same issue.

### JVM version (e.g. `java -version`)
Java 8

### OS version (e.g. `uname -a`)
Windows 10

**Comment by normanmaurer** [comment]
@issararab you are most likely still have another netty version on the class path. Ensure you only have 4.1.28.Final in there. At the end I would say its a qpid bug as they should not depend on internal classes (as these can be removed / changed) at any time.
