### ISSUE TITLE
Linux syscall error when Client Fails to connect

### ISSUE THREAD

**Issue by SplotyCode** [netty/netty#8212]
Linux and Windows get diffrent Exceptions one is a normal Java Eception(Windows) and on linux it is like a im-killing-your-thread-and-i-am-ignoring-your-try-catch.
### Expected behavior
This happen on Windows:
`io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: localhost/127.0.0.1:30000
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:634)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information
    ... 11 more`
### Actual behavior
This happens on Linux:
`io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: localhost/127.0.0.1:30000
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source)
Caused by: io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused
	... 1 more`
### Steps to reproduce
Just run an client on Linux.
### Minimal yet complete reproducer code (or URL to code)
https://github.com/SplotyCode/Dinstagram/blob/master/NetLib/src/main/java/team/gutterteam123/netlib/NetClient.java
### Netty version
4.1.28.Final (Maven)
### JVM version (e.g. `java -version`)
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-8u144-b01-2-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

### OS version (e.g. `uname -a`)
Linux david-thinkpad 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@SplotyCode actually it is basically the same as the errors is reported by the sys call also for NIO we just log it different.y
