### ISSUE TITLE
PortUnreachableException thrown in different

### ISSUE THREAD

**Issue by Shany100** [netty/netty#8228]
Have a doubt,
The same wrong **port**,
The location where the two send exceptions are thrown is different?
as follows:
```
java.net.PortUnreachableException
        at sun.nio.ch.DatagramDispatcher.write0(Native Method)
        at sun.nio.ch.DatagramDispatcher.write(DatagramDispatcher.java:51)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:94)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.DatagramChannelImpl.write(DatagramChannelImpl.java:598)
        at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:278)
        at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:133)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:682)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.flush0(AbstractNioChannel.java:271)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:651)
        at io.netty.channel.DefaultChannelPipeline$HeadHandler.flush(DefaultChannelPipeline.java:1038)
        at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:675)
        at io.netty.channel.DefaultChannelHandlerContext.flush(DefaultChannelHandlerContext.java:656)
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
        at io.netty.channel.DefaultChannelHandlerContext.invokeFlush(DefaultChannelHandlerContext.java:675)
        at io.netty.channel.DefaultChannelHandlerContext.access$1600(DefaultChannelHandlerContext.java:29)
        at io.netty.channel.DefaultChannelHandlerContext$17.run(DefaultChannelHandlerContext.java:663)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Thread.java:722)

```
```
java.net.PortUnreachableException
        at sun.nio.ch.DatagramChannelImpl.receive0(Native Method)
        at sun.nio.ch.DatagramChannelImpl.receiveIntoNativeBuffer(DatagramChannelImpl.java:407)
        at sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:385)
        at sun.nio.ch.DatagramChannelImpl.receive(DatagramChannelImpl.java:338)
        at io.netty.channel.socket.nio.NioDatagramChannel.doReadMessages(NioDatagramChannel.java:209)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:74)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:485)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:452)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:346)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101)
        at java.lang.Thread.run(Thread.java:722)
```

**Comment by Mr00Anderson** [comment]
This i vague. Also this is not a netty.io issue at all.

This exception both time is thrown by `sun.nio.ch ...` package. 

[sun.nio.ch.DatagramChannelImpl.receive0](http://www.docjar.com/html/api/sun/nio/ch/DatagramChannelImpl.java.html) is using a native method so the exception is likely thrown by the Operating System. 

[sun.nio.ch.DatagramDispatcher.write0](http://www.docjar.com/docs/api/sun/nio/ch/DatagramDispatcher.html) is also using a native method

**Comment by normanmaurer** [comment]
As @Mr00Anderson said this is just how it works in NIO... There is nothing we can do about it. If you write something in DatagramChannel it may be reported on read or write

**Comment by Shany100** [comment]
thanks.
