### ISSUE TITLE
OpenJDK 10 OpenJ9 OutOfMemoryError

### ISSUE THREAD

**Issue by MarkTiedemann** [netty/netty#8248]
### Description

After switching from OpenJDK 10 with Hotspot to Eclipse OpenJ9, every request seems to cause an `OutOfMemoryError`.

```
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(java.base@10.0.2-adoptopenjdk/Bits.java:187)
        at java.nio.DirectByteBuffer.<init>(java.base@10.0.2-adoptopenjdk/DirectByteBuffer.java:129)
        at java.nio.ByteBuffer.allocateDirect(java.base@10.0.2-adoptopenjdk/ByteBuffer.java:310)
        at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:764)
        at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:740)
        at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:244)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:214)
        at io.netty.buffer.PoolArena.allocate(PoolArena.java:146)
        at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:324)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
        at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
        at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
        at io.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:147)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:528)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:482)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(java.base@10.0.2-adoptopenjdk/Thread.java:835)
```

### Netty version

```
io.netty:netty-all:4.1.29.Final
```

### JVM version (e.g. `java -version`)

```
λ java -version
openjdk version "10.0.2-adoptopenjdk" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2-adoptopenjdk+13)
Eclipse OpenJ9 VM (build openj9-0.9.0, JRE 10 Windows 8.1 amd64-64-Bit Compressed References 20180813_95 (JIT enabled, AOT enabled)
OpenJ9   - 24e53631
OMR      - fad6bf6e
JCL      - 7db90eda56 based on jdk-10.0.2+13)
```

### OS version (e.g. `uname -a`)

```
λ ver

Microsoft Windows [Version 10.0.16299.611]
```

**Comment by normanmaurer** [comment]
Can you also share the program that reproduce this ? Or maybe a small subset ?

**Comment by MarkTiedemann** [comment]
@normanmaurer I cannot share the whole program, but I created a minimal reproduction. Please checkout [https://github.com/MarkTiedemann/netty-repro-8248](https://github.com/MarkTiedemann/netty-repro-8248).

Many thanks in advance! Hope the reproduction helps.

**Comment by normanmaurer** [comment]
@MarkTiedemann I actually think this is an openj9 bug.

See:
https://github.com/eclipse/openj9/issues/2604
https://github.com/pdbain-ibm/openj9/commit/961cf752da7ef8ae0de1ac0c824d9d9dab7bd42b

WDYT ?

**Comment by MarkTiedemann** [comment]
Yep, this is indeed an OpenJ9 bug.

Thanks a lot, @normanmaurer!
