### ISSUE TITLE
exceptionCaught DecoderException: javax.net.ssl.SSLHandshakeException: error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST at random time

### ISSUE THREAD

**Issue by lijiawen** [netty/netty#8252]
### Expected behavior
the exception throws from the exceptionCaught method,which extends SimpleChannelInboundHandler;

```
@Slf4j
@Service
@ChannelHandler.Sharable
public class ServerChannelInboundHandler extends SimpleChannelInboundHandler<StompFrame> {

  @Override
  public void channelActive(ChannelHandlerContext context) throws Exception {
    log.info("channel:{} active.", context.channel().id().asLongText());
  }

  @Override
  public void channelInactive(ChannelHandlerContext context) throws Exception {
    log.info("channel:{} inactive.", context.channel().id().asLongText());
    super.channelInactive(context);
  }

  @Override
  public void channelReadComplete(ChannelHandlerContext context) throws Exception {
    context.flush();
  }

  @Override
  public void exceptionCaught(ChannelHandlerContext context, Throwable e) throws Exception {
    **log.error("Unexpected exception occur,channel:{} will be closed, exception is:{} ",
        context.channel().id().asLongText(), e);**
        context.close();
  }
  @Override
  protected void channelRead0(ChannelHandlerContext context, StompFrame stompFrame) throws Exception { ...... }
}

```
the initializer is:

```
@Slf4j
@Service
public class WebSocketChannelInitializer extends ChannelInitializer<SocketChannel> {
  @Override
  protected void initChannel(SocketChannel socketChannel) throws Exception {

    ChannelPipeline pipeline = socketChannel.pipeline();
    DomainNameMapping<SslContext> domainNameMapping = sslFactory.newSslContext();
    if (domainNameMapping != null) {
      pipeline.addLast(new SniHandler(domainNameMapping));
    }

    pipeline.addLast("trafficHandler", trafficHandler);
    pipeline.addLast("stompDecoder", new StompSubframeDecoder());
    pipeline.addLast("stompEncoder", new StompSubframeEncoder());
    pipeline.addLast("aggregator", new StompSubframeAggregator(65535);
    pipeline.addLast(eventExecutorGroup, webSocketChannelInboundHandler);
  }
}

```
### Actual behavior
```
18:04:52.015 195363572 ERROR   c.t.s.o.s.h.WebSocketChannelInboundHandler(57) - Unexpected exception occur,channel:001cacfffe1d3139-000025e7-00000006-72cf32c68d85b5a7-45441840 will be closed, exception is:{}
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:236)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:494)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1414)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:945)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:146)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: error:1000009c:SSL routines:OPENSSL_internal:HTTP_REQUEST
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:862)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.sslReadErrorResult(ReferenceCountedOpenSslEngine.java:1110)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1066)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1132)
	at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1175)
	at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:216)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1257)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1171)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1205)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	... 23 common frames omitted

```
### Netty version
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-all</artifactId>
        <version>4.1.22.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-tcnative</artifactId>
        <version>2.0.7.Final</version>
      </dependency>
      <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-tcnative-boringssl-static</artifactId>
        <version>2.0.7.Final</version>
      </dependency>
### JVM version (e.g. `java -version`)
java version "1.8.0_121"
### OS version (e.g. `uname -a`)
2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@lijiawen this version is very old... Please upgrade to the latest one and report back if the problem still persist.

**Comment by lijiawen** [comment]
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-all</artifactId>
    <version>4.1.22.Final</version>
  </dependency>

@normanmaurer , you mean this 4.1.22.Final is old? which version should i use，please give me a suggest,thanks a lot.

**Comment by normanmaurer** [comment]
Yes... the latest. 4.1.29.Final

**Comment by normanmaurer** [comment]
@lijiawen maybe I dont get what problem you think you have...

It seems like there is an SSL error which is propagated thought the `ChannelPipeline` until it is handled in `WebSocketChannelInboundHandler`. This all looks correct to me. Can you try to explain in more detail what issue you think is there ?

**Comment by lijiawen** [comment]
@normanmaurer ，the error is occured at random time, and it is not thrown from my business code,but  
 caused by sslhandshake? i dont know why this exception will occur，what situation can cause this problem? what should i do to avoid this exception? this is very strange. can you understand?

**Comment by normanmaurer** [comment]
@lijiawen there is not much you can do here as it is caused by a malfunction remote peer. So really nothing to worry about. From the error message itself it seems like they try to use a SSL protocol version that you not support

**Comment by lijiawen** [comment]
@normanmaurer ,but there is no other users to access my code，only myself to access this function，and the error is not occured during my request，it just occured at random time

**Comment by normanmaurer** [comment]
if you can share a reproducer I will have a look... Without that I have no idea.

**Comment by bigbang555** [comment]
> > @normanmaurer ,but there is no other users to access my code，only myself to access this function，and the error is not occured during my request，it just occured at random time
> 
> hi,have you solve it?I meet the same problem

I find the cause why the problem happen.
In my project,I config the ssl,but some requests send by http.So errors occur

**Comment by normanmaurer** [comment]
again if someone is doing http and not https on a port where SSL is used there is not much we can do about.
