### ISSUE TITLE
Deadlock caused race between adding SslHandler and disconnecting a channel

### ISSUE THREAD

**Issue by mingyu89** [netty/netty#8302]
Hello, we were using Netty version 4.0.41 and almost all our threads were blocked at "wakeup" method. It seems a deadlock between adding a handler and destroy the pipeline. 

```
"pool-21-thread-20" Id=56 BLOCKED on io.netty.channel.DefaultChannelPipeline@7a12db0a owned by "lower-pool: 17" Id=316
        at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:826)
        -  blocked on io.netty.channel.DefaultChannelPipeline@7a12db0a
        at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:43)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:185)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:171)
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:811)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:699)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:408)
        ...


"lower-pool: 17" Id=316 BLOCKED on java.lang.Object@4643cba3 owned by "pool-21-thread-20" Id=56
        at sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:205)
        -  blocked on java.lang.Object@4643cba3
        at io.netty.channel.nio.NioEventLoop.wakeup(NioEventLoop.java:691)
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:755)
        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:158)
        -  locked io.netty.channel.DefaultChannelPipeline@7a12db0a
        at io.netty.channel.DefaultChannelPipeline.addFirst(DefaultChannelPipeline.java:132)
        ...

        Number of locked synchronizers = 1
        - java.util.concurrent.ThreadPoolExecutor$Worker@46d74886

```
Is this a known issue? We recently upgraded to use Netty version 4.1.28. Is it fixed?
Thank you.

**Comment by normanmaurer** [comment]
I remember we fixed some deadlocks when doing pipeline operations. So I think it should be fixed. If not please re-open

**Comment by mingyu89** [comment]
@normanmaurer Thank you!
