### ISSUE TITLE
HTTP/2 over TLS example throws an exception

### ISSUE THREAD

**Issue by arukshani** [netty/netty#8309]
I was following HTTP/2 hello world sample and I get the following exception
```java
ARNING: Failed to initialize a channel. Closing: [id: 0x34f9686c, L:/127.0.0.1:9090 - R:/127.0.0.1:32824]
java.lang.RuntimeException: Unable to wrap SSLEngine of type sun.security.ssl.SSLEngineImpl
        at io.netty.handler.ssl.JdkAlpnApplicationProtocolNegotiator$AlpnWrapper.wrapSslEngine(JdkAlpnApplicationProtocolNegotiator.java:144)
        at io.netty.handler.ssl.JdkSslContext.configureAndWrapEngine(JdkSslContext.java:251)
        at io.netty.handler.ssl.JdkSslContext.newEngine(JdkSslContext.java:221)
        at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:913)
        at io.netty.handler.ssl.SslContext.newHandler(SslContext.java:905)
        at com.ruk.withpriorknowledge.Http2ChannelInitializer.configureSsl(Http2ChannelInitializer.java:62)
        at com.ruk.withpriorknowledge.Http2ChannelInitializer.initChannel(Http2ChannelInitializer.java:51)
        at com.ruk.withpriorknowledge.Http2ChannelInitializer.initChannel(Http2ChannelInitializer.java:36)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:115)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:107)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:637)
        at io.netty.channel.DefaultChannelPipeline.access$000(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1487)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1161)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:686)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:510)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:464)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

Curl output is as follows
`curl -k -v --http2 https://localhost:9090
* Rebuilt URL to: https://localhost:9090/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9090 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:9090 
* stopped the pause stream!
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:9090 
`
Netty version I use - 4.1.27.Final
java version "1.8.0_181"

**Comment by arukshani** [comment]
Closing this since I was able to get this working by adding the proper netty-tcnative dependency.

**Comment by decoded4620** [comment]
@arukshani Which dependency did you add there? I'm using a self signed Cert from a self created CA, and I'm getting this exception. Yet i have the latest netty-tcnative dependency in my classpath. What was the dependency you added (and version)?
