### ISSUE TITLE
Netty cannot handle encrypted (pkcs8-) private-key

### ISSUE THREAD

**Issue by jarmoni** [netty/netty#8311]
### Expected behavior
Private-Key should be be decrypted properly.
### Actual behavior
Using an encrypted private-key throws:
```
Exception in thread "main" java.lang.IllegalArgumentException: Input stream does not contain valid private key.
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:296)
	at io.netty.handler.ssl.SslContextBuilder.forServer(SslContextBuilder.java:104)
	at com.diehl.dcs.stratus.hsp.client.java.HspTestServer.start(HspTestServer.java:61)
	at com.diehl.dcs.stratus.hsp.client.java.HspTestServer.start(HspTestServer.java:56)
	at com.diehl.dcs.stratus.hsp.client.java.HspTestServer.main(HspTestServer.java:211)
Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
	at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:257)
	at sun.security.util.DerInputStream.getOID(DerInputStream.java:314)
	at com.sun.crypto.provider.PBES2Parameters.engineInit(PBES2Parameters.java:267)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.x509.AlgorithmId.decodeParams(AlgorithmId.java:132)
	at sun.security.x509.AlgorithmId.<init>(AlgorithmId.java:114)
	at sun.security.x509.AlgorithmId.parse(AlgorithmId.java:372)
	at javax.crypto.EncryptedPrivateKeyInfo.<init>(EncryptedPrivateKeyInfo.java:95)
	at io.netty.handler.ssl.SslContext.generateKeySpec(SslContext.java:979)
	at io.netty.handler.ssl.SslContext.getPrivateKeyFromByteBuffer(SslContext.java:1035)
	at io.netty.handler.ssl.SslContext.toPrivateKey(SslContext.java:1025)
	at io.netty.handler.ssl.SslContextBuilder.keyManager(SslContextBuilder.java:294)
	... 4 more
```
Unencrypted private-key works fine.
I tested the key in several (non-Java-) applications (Nginx, Mosquitto, ...) and it worked well.
### Steps to reproduce
See below
### Minimal yet complete reproducer code (or URL to code)
```bash
openssl genrsa -aes256 -passout pass:xyz -out my.key 4096
openssl pkcs8 -topk8 -inform pem -in my.key -passin pass:xyz -outform pem -passout pass:xyz -out my-pkcs8.key
# created CSR, signed it,.....
```
```java
final SslContext sslContext = SslContextBuilder.forServer(
      TestServer2.class.getClassLoader().getResourceAsStream("my-cert.pem"),
      TestServer2.class.getClassLoader().getResourceAsStream("my-pkcs8.key"),
      "xyz")
   .sslProvider(SslProvider.OPENSSL)
   .build();
```

### Netty version
4.1.29.Final
### JVM version (e.g. `java -version`)
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
### OS version (e.g. `uname -a`)
4.15.0-34-generic #37-Ubuntu SMP

**Comment by jarmoni** [comment]
It seems that the real problem is not on Netty's but on JDK's side. I know, Java and TLS is sometimes a bit weird... Is there a workaround? In my current project unencrypted PK's are no option....

**Comment by normanmaurer** [comment]
@jarmoni .p12 definitely works (encrypted and unencrypted). We even use it in tests.

**Comment by DiegoBravo** [comment]
I had the same issue. Looks like a JVM issue related with the openssl pkcs8 algorithm used. See the comment
https://github.com/kaikramer/keystore-explorer/issues/79#issuecomment-287918175
Not a netty issue at all.
