### ISSUE TITLE
IllegalStateException Vertx with OpenJDK 11

### ISSUE THREAD

**Issue by benishak** [netty/netty#8330]
I'm using latest version of Vert.x 3.5.x
and compiled successfully my application with OpenJDK 11+28

My application start fine but as soon Vert.x received a request it shows that warning and the whole Vertx server get restarted and returns Server Internal Error

Same code runs fine when compiled and run with Java 8 (Oracle)

### Expected behavior
Should be able to register channel

### Actual behavior

```
WARN  [ServerBootstrap] 16:16:33.446: Failed to register an accepted channel: [id: 0x5d14897d, L:0.0.0.0/0.0.0.0:8090]
java.lang.IllegalStateException: null
	at io.vertx.core.net.impl.VertxEventLoopGroup.next(VertxEventLoopGroup.java:37) ~[auctioncore.jar:?]
	at io.vertx.core.net.impl.VertxEventLoopGroup.register(VertxEventLoopGroup.java:53) ~[auctioncore.jar:?]
	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:255) ~[auctioncore.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[auctioncore.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[auctioncore.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[auctioncore.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) ~[auctioncore.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[auctioncore.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[auctioncore.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) ~[auctioncore.jar:?]
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93) ~[auctioncore.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[auctioncore.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) ~[auctioncore.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) ~[auctioncore.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451) ~[auctioncore.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) ~[auctioncore.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[auctioncore.jar:?]
	at java.lang.Thread.run(Thread.java:834) ~[?:]
```

## Steps to reproduce

Use Vertx Server with OpenJDK 11 
send request 

### Netty version
Latest from Vertx

### JVM version (e.g. `java -version`)
OpenJDK 11+28

### OS version (e.g. `uname -a`)
Oracle Linux 7 on Docker

**Comment by normanmaurer** [comment]
@benishak this is thrown in Vert.x you need to open an issue there:

```
	at io.vertx.core.net.impl.VertxEventLoopGroup.next(VertxEventLoopGroup.java:37) ~[auctioncore.jar:?]
```

**Comment by benishak** [comment]
it is thrown in Vertx but it is originating from Netty
Vertx just caught it and logged it as warning
or am I missing something?

**Comment by normanmaurer** [comment]
@benishak its thrown from vertx code which is called from netty code:

```
	at io.vertx.core.net.impl.VertxEventLoopGroup.next(VertxEventLoopGroup.java:37) ~[auctioncore.jar:?]
```

So it must be a vert.x bug in `VertxEventLoopGroup.next`

**Comment by benishak** [comment]
ok thanks
