### ISSUE TITLE
FixedChannelPool#close() can return before idle channels are closed

### ISSUE THREAD

**Issue by lutovich** [netty/netty#8398]
### Expected behavior
`FixedChannelPool#close()` should return only after all idle channels are closed. Such behavior is expected after https://github.com/netty/netty/pull/7927. Before this PR, method was asynchronous and provided no such guarantees.

### Actual behavior
`FixedChannelPool#close()` offloads actual closing of idle channels to `GlobalEventExecutor` and can return before the submitted task completes.

### Steps to reproduce

1. Create a `FixedChannelPool`
2. Acquire and release a channel, but keep a reference to it
3. Call `#close()` on the pool
4. Assert channel close future is done

### Minimal yet complete reproducer code (or URL to code)
The following test can be added to the `FixedChannelPoolTest` class to reproduce the problem:
```java
@Test
public void testClose() {
    LocalAddress addr = new LocalAddress(LOCAL_ADDR_ID);
    Bootstrap cb = new Bootstrap();
    cb.remoteAddress(addr);
    cb.group(group).channel(LocalChannel.class);

    ServerBootstrap sb = new ServerBootstrap();
    sb.group(group)
      .channel(LocalServerChannel.class)
      .childHandler(new ChannelInitializer<LocalChannel>() {
        @Override
        public void initChannel(LocalChannel ch) throws Exception {
            ch.pipeline().addLast(new ChannelInboundHandlerAdapter());
        }
    });

    // Start server
    Channel sc = sb.bind(addr).syncUninterruptibly().channel();

    FixedChannelPool pool = new FixedChannelPool(cb, new TestChannelPoolHandler(), 2);
    Channel channel = pool.acquire().syncUninterruptibly().getNow();
    pool.release(channel).syncUninterruptibly().getNow();

    pool.close();

    assertTrue(channel.closeFuture().isDone()); // <<-- failing assertion

    sc.close().syncUninterruptibly();
}
```

### Netty version
4.1.26+

### JVM version (e.g. `java -version`)
```
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```

### OS version (e.g. `uname -a`)
```
Darwin MacBook-Pro.local 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64
```

### More details
We use Netty in a client app which hangs extremely infrequently during shutdown when updated from 4.1.22 to 4.1.26+. Shutdown sequence looks roughly like this:

```java
fixedChannelPool.close();
eventLoopGroup.shutdownGracefully();
eventLoopGroup.terminationFuture().awaitUninterruptibly(); // this line can block forever
```

Unfortunately, I'm unable to reproduce such hanging with a test. Was only able to catch it once in a debugger with the following code: https://gist.github.com/lutovich/dc1fe9414e728d12b29b65c15727df93.

Stacktraces of the two blocked threads look like:

```
"main@1" prio=5 tid=0x1 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:253)
	  at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:33)
	  at io.netty.channel.pool. NettyPoolCloseTest.poolClose(NettyIT.java:62)
          ...
```

```
"globalEventExecutor-1-1@2059" prio=5 tid=0x1a nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:502)
	  at io.netty.util.concurrent.DefaultPromise.awaitUninterruptibly(DefaultPromise.java:253)
	  at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:137)
	  at io.netty.channel.DefaultChannelPromise.awaitUninterruptibly(DefaultChannelPromise.java:30)
	  at io.netty.channel.pool.SimpleChannelPool.close(SimpleChannelPool.java:398)
	  at io.netty.channel.pool.FixedChannelPool.access$1301(FixedChannelPool.java:40)
	  at io.netty.channel.pool.FixedChannelPool$6.run(FixedChannelPool.java:480)
	  at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:248)
	  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	  at java.lang.Thread.run(Thread.java:748)
```

First one is the blocked executing `clientGroup.terminationFuture().awaitUninterruptibly()`. Second is blocked executing `channel.close().awaitUninterruptibly()` in `SimpleChannelPool#close()`. I also have a heap dump of a hanging test run and can upload it somewhere, if needed.

I **think** the problem happens because `FixedChannelPool#close()` might exit before all pooled channels are closed and closing of the event loop group will race with closing of pooled channels.

`FixedChannelPool#close()` offloads actual closing of idle channels to the `GlobalEventExecutor`, which executes `SimpleChannelPool#close()`. So `FixedChannelPool#close()` can return to the caller before idle channels are closed. This might be a scenario that causes hanging:

1. Given a `FixedChannelPool` with an idle connection
2. Code calls `FixedChannelPool#close()` which adds a task to close all idle channels to the `GlobalEventExecutor` and returns
3. Code calls `NioEventLoopGroup#close()` which now races with the `GlobalEventExecutor` who tries to close the channel
4. Somehow, `GlobalEventExecutor` manages to add a close task to the event executor while it is shutting down and a message "An event executor terminated with non-empty task queue (1)" is logged. Tbh, I can't understand how this step is possible by looking at Netty code :(
5. `GlobalEventExecutor` is blocked in `SimpleChannelPool#close()` waiting for the channel close future which will never be notified because executor has been terminated
6. Main thread is blocked on `NioEventLoopGroup#terminationFuture()`. Termination future in  `NioEventLoopGroup` relies on `GlobalEventExecutor` to get notifications but `GlobalEventExecutor` is blocked, as described in step 5.
7. `GlobalEventExecutor` is blocked and will never receive the notification about the channel being closed. It also contains a queued task to notify the event loop termination future, which will never get executed.

If `FixedChannelPool#close()` returns only after all idle channels are closed then there will be no race in step 3 and the problem will hopefully be solved.

**Comment by lutovich** [comment]
Here is a tentative fix for the described problem: https://github.com/lutovich/netty/commit/bb6b371f0e974814ce1175283c0c06e660180202. I can make it into a PR if the change is acceptable.

**Comment by lutovich** [comment]
Thanks, @normanmaurer. I created a PR.

**Comment by lutovich** [comment]
Fixed in https://github.com/netty/netty/pull/9226.
