### ISSUE TITLE
java.lang.IllegalArgumentException: TLSv1.3 when trying to perform https request to Facebook

### ISSUE THREAD

**Issue by doom369** [netty/netty#8458]
Not sure this is the netty issue as TLS should be disabled by default as read in the release notes. But maybe it is not. Stack:

```
14:58:27.539 DEBUG- Unexpected I/O exception on channel [id: 0xf84db998, L:/x.x.x.x:42654 ! R:graph.facebook.com/x.x.x.x:443]
java.lang.IllegalArgumentException: TLSv1.3
        at sun.security.ssl.ProtocolVersion.valueOf(ProtocolVersion.java:215) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:264) ~[?:?]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:145) ~[?:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:237) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:625) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.internal.tcnative.SSL.readFromSSL(Native Method) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.readPlaintextData(ReferenceCountedOpenSslEngine.java:511) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1060) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.unwrap(ReferenceCountedOpenSslEngine.java:1169) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:211) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1297) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1199) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1243) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:382) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[server-0.41.0-SNAPSHOT.jar:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server-0.41.0-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:844) [?:?]
```

Happens on our QA when the user tries to login via facebook.

```
        <netty.version>4.1.31.Final</netty.version>
        <netty.boring.ssl.version>2.0.19.Final</netty.boring.ssl.version>
        <async-http-client.version>2.6.0</async-http-client.version>
```

```
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

The request is performed with async-http-client (async http client uses 4.1.30 version, could be a reason.). FYI @slandelle

**Comment by doom369** [comment]
@normanmaurer ok, I'll try to enable TLS 1.3 for now as quick fix.

**Comment by normanmaurer** [comment]
This will only work with java11 tho and not sure if it will Workman general

**Comment by normanmaurer** [comment]
MaBe the easiest would be to just use 4.1.31 there as well

**Comment by doom369** [comment]
@normanmaurer yeap. Exclusions helped.
