### ISSUE TITLE
Java 11: javax.net.ssl.SSLException not 'swallowed' when log level is set to Debug

### ISSUE THREAD

**Issue by JStroom** [netty/netty#8463]
### Expected behavior
No "javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify" is thrown when running a netty application with Java 11 and log level set to debug. 

### Actual behavior
The following exception is logged with Java 11 and netty in log level debug: 
SSLEngine.closeInbound() raised an exception.
javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:255)
	at java.base/sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:724)
	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1561)
	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1045)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:466)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

### Steps to reproduce
Run the netty HttpHelloWorldServer example with Java 11 and change the log level to debug (logback.xml).
Open a browser and point the URL to the listening port: https://localhost:8443/

### Minimal yet complete reproducer code (or URL to code)
https://github.com/netty/netty/tree/4.1/example/

### Netty version
4.1.32.Final-SNAPSHOT

### JVM version (e.g. `java -version`)
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### OS version (e.g. `uname -a`)
windows 10

### Suggestion to change:
```java
if (msg == null || !msg.contains("possible truncation attack")) {
    logger.debug("{} SSLEngine.closeInbound() raised an exception.", ctx.channel(), e);
}
```
to 
```java
if (msg == null || !msg.contains("before receiving peer's close_notify")) {
    logger.debug("{} SSLEngine.closeInbound() raised an exception.", ctx.channel(), e);
}
```

**Comment by normanmaurer** [comment]
@JStroom I think we should also keep the old `contains` check but also add the new one.

Are you interested in doing a PR ?

**Comment by JStroom** [comment]
@normanmaurer Sounds like a plan to keep the old contains and add a new one for Java 11. 
Sure, I'm interested in doing a PR. I'll follow the developer guideline and submit the PR later this week.

**Comment by normanmaurer** [comment]
@JStroom thanks!
