### ISSUE TITLE
Disable direct buffer usage and enable only heap buffers

### ISSUE THREAD

**Issue by arukshani** [netty/netty#8488]
### Actual behavior
I have disabled the direct buffer usage with the following properties. But it seems somehow netty still uses direct buffer with `DefaultMaxMessagesRecvByteBufAllocator`. 
```
 -Dio.netty.allocator.numDirectArenas=0 \
 -Dio.netty.noPreferDirect=true \
```
 Is there a way to completely disable direct buffer usage and enable only heap buffers so that instead of  the following`OutOfDirectMemoryError` I can get a heap dump?

` 
[2018-11-09 19:50:06,484] ERROR 
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 1024 byte(s) of direct memory (used: 954727718, max: 954728448)
	at io.netty.util.internal.PlatformDependent.incrementMemoryCounter(PlatformDependent.java:640)
	at io.netty.util.internal.PlatformDependent.allocateDirectNoCleaner(PlatformDependent.java:594)
	at io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf.allocateDirect(UnpooledUnsafeNoCleanerDirectByteBuf.java:30)
	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.<init>(UnpooledUnsafeDirectByteBuf.java:68)
	at io.netty.buffer.UnpooledUnsafeNoCleanerDirectByteBuf.<init>(UnpooledUnsafeNoCleanerDirectByteBuf.java:25)
	at io.netty.buffer.UnsafeByteBufUtil.newUnsafeDirectByteBuf(UnsafeByteBufUtil.java:595)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:327)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	at io.netty.buffer.AbstractByteBufAllocator.ioBuffer(AbstractByteBufAllocator.java:137)
	atio.netty.channel.DefaultMaxMessagesRecvByteBufAllocator$MaxMessageHandle.allocate(DefaultMaxMessagesRecvByteBufAllocator.java:114)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)`

### Netty version
4.1.31.Final

### JVM version (e.g. `java -version`)
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

### OS version (e.g. `uname -a`)
Linux  Ubuntu SMP Wed Oct 10 20:16:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@arukshani the problem is for some stuff you will still need direct memory. That said I guess for what you want to do it would be good enough to extend `AbstractByteBufAllocator` and be sure that `ioBuffer(...)` will call `heapBuffer(...)`
