### ISSUE TITLE
java.lang.NoClassDefFoundError: io/netty/bootstrap/FailedChannel

### ISSUE THREAD

**Issue by pez1420** [netty/netty#8498]
### Actual behavior
```
2018-11-13 12:58:03,207 [ERROR] [jupiter-0-ClientToProxyWorker-0] cn.com.servyou.xqy.jupiter.gateway.netty.ClientToProxyHandler - 非超时请求异常
java.lang.NoClassDefFoundError: io/netty/bootstrap/FailedChannel
        at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:330)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:163)
        at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:145)
        at cn.com.servyou.xqy.jupiter.gateway.netty.upstream.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:178)
        at cn.com.servyou.xqy.jupiter.gateway.netty.upstream.NettyRequestSender.sendRequest(NettyRequestSender.java:164)
        at cn.com.servyou.xqy.jupiter.gateway.netty.upstream.NettyRequestSender.retry(NettyRequestSender.java:278)
        at cn.com.servyou.xqy.jupiter.gateway.netty.upstream.NettyRequestSender.handleUnexpectedClosedChannel(NettyRequestSender.java:234)
        at cn.com.servyou.xqy.jupiter.gateway.netty.upstream.NettyRequestSender.handleAndReleaseUnexpectedClosedChannel(NettyRequestSender.java:219)
        at cn.com.servyou.xqy.jupiter.gateway.netty.upstream.NettyRequestSender.sendRequest(NettyRequestSender.java:167)
        at cn.com.servyou.xqy.jupiter.gateway.netty.upstream.NettyRequestSender.sendRequest(NettyRequestSender.java:125)
        at cn.com.servyou.xqy.jupiter.gateway.netty.ClientToProxyHandler.channelRead0(ClientToProxyHandler.java:305)
        at cn.com.servyou.xqy.jupiter.gateway.netty.ClientToProxyHandler.channelRead0(ClientToProxyHandler.java:69)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.lang.Thread.run(Thread.java:745) 
```
### Netty version
4..1.25.final

### JVM version (e.g. `java -version`)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

### OS version (e.g. `uname -a`)
Linux hz-bd-gw-199-137-181 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
Seems like you have a mix of different netty versions on your class path. Please ensure you use only one version for 4.x

**Comment by pez1420** [comment]
I am sure just only one netty version on my class path.

**Comment by normanmaurer** [comment]
@pez1420 there is definitely something wrong with your class path:

https://github.com/netty/netty/blob/netty-4.1.25.Final/transport/src/main/java/io/netty/bootstrap/FailedChannel.java

**Comment by pez1420** [comment]
I also had imported  **rxneety** in my project, which depends on **netty-transport**.Hence, it caused class confliction.

**Comment by pez1420** [comment]
@normanmaurer  I also had imported rxneety in my project, which depends on netty-transport.Hence, it caused class confliction.

**Comment by normanmaurer** [comment]
@pez1420 makes sense...
