### ISSUE TITLE
High CPU Usage with NioEventLoopGroup

### ISSUE THREAD

**Issue by rohitsahay2000** [netty/netty#8553]

**Comment by rohitsahay2000** [comment]
[thread_dump.zip](https://github.com/netty/netty/files/2579247/thread_dump.zip)
Have attached thread dump taken over 3 days. You can see the constant increase in the number of eventloopgroups. 

For eventloop creation
`eventLoopGroup = new NioEventLoopGroup();`

For closing:
eventLoopGroup.shutdownGracefully().addListener(new GenericFutureListener() {

                            @Override
                            public void operationComplete(final Future future) throws Exception {
                               -------------
                            }
          });

**Comment by normanmaurer** [comment]
I am pretty sure you not shutdown in all cases or continue creating new ones.

**Comment by rohitsahay2000** [comment]
The first thing that i did was to check the number of shutdowns versus the number of creations of event loop groups. And they exactly match. Any workarounds you suggest?

**Comment by normanmaurer** [comment]
@rohitsahay2000 the only thing I can tell you from the thread dumps is that there are many `NioEventLoop`s that are not shutdown. Are you sure the `shutdownGracefully()` really completes ? 

Also just generally I wonder why you create and shutdown so many groups. Normally you create one group at the start and re-use it during the life-time of the whole app.

**Comment by rohitsahay2000** [comment]
Are you sure the shutdownGracefully() really completes ?
--> I can only call this method for shutting down the event loop group gracefully. Anything else you suggest to shutdown the event loop group and monitor the completes?

Also just generally I wonder why you create and shutdown so many groups. Normally you create one group at the start and re-use it during the life-time of the whole app.
--> One event loop group causes very high CPU usage because of the volume of data which needs to be processed.

I have seen similar issues like this:
https://github.com/netty/netty/issues/327
https://github.com/netty/netty/issues/5278

and there are many others which says the problem very similar to i have pointed out. I see there are lot of comments but the bug was generally closed because of lack of response or it was very old. Don't see any fixes which was done around this. 
If anything you can suggest would be great.

**Comment by rohitsahay2000** [comment]
Hi @normanmaurer , Did some more profiling. I have a event loop group of 100 threads. Seeing lot of threads going in awaiting state before CPU going more than 100% and app becomes unresponsive. Example 
`Name: nioEventLoopGroup-2-11
State: RUNNABLE
Total blocked: 129  Total waited: 95

Stack trace: 
sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:281)
sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:105)
sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:98)
   - locked io.netty.channel.nio.SelectedSelectionKeySet@8f0ca6c6
   - locked java.util.Collections$UnmodifiableSet@dba88c4
   - locked sun.nio.ch.EPollSelectorImpl@ed7a1c60
sun.nio.ch.SelectorImpl.select(SelectorImpl.java:109)
io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
java.lang.Thread.run(Thread.java:811)
`
This is one example, there are many threads like this and the count of such thread increases eventually. Can you please help?

**Comment by ejona86** [comment]
@rohitsahay2000, I think you are discussing two different things: 1) high CPU usage and 2) old event loops not shutting down.

I don't think (2) is an "issue" or at least it is working as intended. Netty creates new threads pretty aggressively and doesn't really shut them down until the end. (And when shutting down an event loop, it even creates any threads that hadn't been created earlier!)

(1) is interesting though. Could you give the precise jvm version? Like at least including the patch version like "1.8.0_121", but the full output of `java -version` would be great.

**Comment by ejona86** [comment]
@rohitsahay2000, could you also provide `uname -a`?

**Comment by ejona86** [comment]
An easy way to see which threads are using CPU is to use `top` and type shift-H. That shows all threads. Thread ids in `jstack` are hex, so you will need to convert the thread id to hex to compare to `jstack` output.

http://www.boxjar.com/using-top-and-jstack-to-find-the-java-thread-that-is-hogging-the-cpu/ is an example walkthrough.

**Comment by rohitsahay2000** [comment]
Attaching 
1. Screenshot of the process with high CPU. (top -pXXXX)
<img width="527" alt="processwithhighcpu" src="https://user-images.githubusercontent.com/32896980/49580118-32497e80-f974-11e8-8894-ff9a6e77781f.png">

2. Screenshot of all the threads for that process (shift -H result)

<img width="619" alt="threadsfortheprocess" src="https://user-images.githubusercontent.com/32896980/49580133-3b3a5000-f974-11e8-9bbc-ef57f70ccfec.png">

3. stack of one such thread is 

` nioEventLoopGroup-2-72 tid=183
	java.lang.Thread.State:  RUNNABLE
		at sun.nio.ch.DatagramChannelImpl.send0(Native Method)
		at sun.nio.ch.DatagramChannelImpl.sendFromNativeBuffer(DatagramChannelImpl.java:533)
		at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:495)
		at sun.nio.ch.DatagramChannelImpl.send(DatagramChannelImpl.java:474)
		  locked <0x93a2fc8c> (a java.lang.Object)
		at io.netty.channel.socket.nio.NioDatagramChannel.doWriteMessage(NioDatagramChannel.java:293)
		at io.netty.channel.nio.AbstractNioMessageChannel.doWrite(AbstractNioMessageChannel.java:142)
		at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:934)
		at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:367)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:640)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
		at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:811)
	Locked ownable synchronizers:
	 None
`

**Comment by normanmaurer** [comment]
These stacks look like you are just producing a lot of data that needs to be send. There is nothing we can do about it.

**Comment by normanmaurer** [comment]
That said you may want to try to use `EpollDatagramChannel` as it supports using `sendmmsg` which will help to reduce the syscalls.

**Comment by ZooDoz** [comment]
i find the same question. only 8 threads ,when cpu high , it won't fall.

**Comment by medusar** [comment]
@rohitsahay2000 I have some suggestions for you 

- check if the outbound bandwidth is enough, if it is not enough, CPU will be high sometimes.
- check if your CPU cores are balanced well with your internet card, you may need [this:](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/performance_tuning_guide/s-cpu-irq)
- check the interrupts for each CPU core, if they are not balanced well, CPU will be high. You can use `mpstat -I SUM -P ALL` to check it out.

**Comment by rohitsahay2000** [comment]
Strange ! You can put a disclaimer that high data usage is not advisable while using netty. I thought a issue is closed only when a resolution is provided not when "nothing can be done" and there is an existing bug.

**Comment by normanmaurer** [comment]
Sure high data usage is supported but what you show is basically the overhead of sending data via UDP. At least this is what the stack trace is showing and as this is a syscall there is nothing we can do about this. The only thing you could do is to try to batch these. If you can share a reproducer that allows us to observe the same "problem" I am more then happy to have a look. But without seeing code etc there is really nothing we can do. 

`sun.nio.ch.DatagramChannelImpl.send0 ` is basically the native method of the JDK that will do the sys call.
