### ISSUE TITLE
NioEventLoop selector crash and can't recover

### ISSUE THREAD

**Issue by qinliujie** [netty/netty#8566]
### Expected behavior

```
WARN [HSF-Worker-2-thread-5:t.h.remoting] [] [] [] Unexpected exception in the selector loop.
java.io.IOException: Broken pipe
	at sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
	at sun.nio.ch.EPollArrayWrapper.interrupt(EPollArrayWrapper.java:323)
	at sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:207)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.wakeup(SelectedSelectionKeySetSelector.java:73)
	at io.netty.channel.nio.NioEventLoop.selectNow(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop$1.get(NioEventLoop.java:71)
	at io.netty.channel.DefaultSelectStrategy.calculateStrategy(DefaultSelectStrategy.java:30)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:405)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at com.taobao.hsf.io.netty.util.PooledThreadFactory$PooledByteBufRunnable.run(PooledThreadFactory.java:37)
	at java.lang.Thread.run(Thread.java:882)

```

NioEventLoop can recover from exception or rebuild  a new selector

### Actual behavior

NioEventLoop dead totally

### Steps to reproduce

Can't reproduce this case,but we can mock;

see below code

```
protected void run() {
        for (;;) {
            try {
                switch (selectStrategy.calculateStrategy(selectNowSupplier, hasTasks())) {
                    case SelectStrategy.CONTINUE:
                        continue;
                    case SelectStrategy.SELECT:
                    .....
            } catch (Throwable t) {
                handleLoopException(t);
            }
```

notice that,`(selectStrategy.calculateStrategy(selectNowSupplier, hasTasks())`  can throw an exception every loop;

now we look at `selectNowSupplier`,

```
    private final IntSupplier selectNowSupplier = new IntSupplier() {
        @Override
        public int get() throws Exception {
            return selectNow();
        }
    };
```

and I find `selector` api document

```
    /**
     * Selects a set of keys whose corresponding channels are ready for I/O
     * operations.
     *
     * <p> This method performs a non-blocking <a href="#selop">selection
     * operation</a>.  If no channels have become selectable since the previous
     * selection operation then this method immediately returns zero.
     *
     * <p> Invoking this method clears the effect of any previous invocations
     * of the {@link #wakeup wakeup} method.  </p>
     *
     * @return  The number of keys, possibly zero, whose ready-operation sets
     *          were updated by the selection operation
     *
     * @throws  IOException
     *          If an I/O error occurs
     *
     * @throws  ClosedSelectorException
     *          If this selector is closed
     */
    public abstract int selectNow() throws IOException;
```

java.nio.channels.Selector#selectNow may throw an exception ! but we don't handle it!

### Netty version
4.1.16.Final
### JVM version (e.g. `java -version`)
1.8

**Comment by normanmaurer** [comment]
@qinliujie Please check https://github.com/netty/netty/pull/8569
