### ISSUE TITLE
NPE in SSLContext#clearOptions()

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#8570]
I wanted to see what happens if I attempt to fiddle with the context's `OpenSslSessionContext` (e.g. setting session tickets) if the `SslContext` gets free'd or something else as there are no guards against it.

Seems it's NPE'ing which may or may not a good way of handling it.

### Actual behavior

```java
java.lang.NullPointerException: ctx
	at io.netty.internal.tcnative.SSLContext.clearOptions(Native Method)
	at io.netty.handler.ssl.OpenSslSessionContext.setTicketKeys(OpenSslSessionContext.java:109)
	at io.netty.handler.ssl.SessionTicketsTest.npeSetTicketKeys(SessionTicketsTest.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

### Minimal yet complete reproducer code (or URL to code)

```java
public class SessionTicketsTest {

  @Test
  public void npeSetTicketKeys() throws Exception {
    SslContext sslContext = SslContextBuilder.forClient()
        .sslProvider(SslProvider.OPENSSL_REFCNT)
        .build();
    
    // Silly me!
    ReferenceCountUtil.release(sslContext);
    
    // Ooops!
    ((OpenSslSessionContext)sslContext.sessionContext())
        .setTicketKeys(new OpenSslSessionTicketKey(new byte[16], new byte[16], new byte[16]));
  }
}
```

### Netty version

4.1.32-SNAPSHOT
TCN 2.0.19

**Comment by normanmaurer** [comment]
@rkapsi yep that is exactly how we wanted to handle it :) So I would say "works as expected"

**Comment by rkapsi** [comment]
Closing, works as expected.
