### ISSUE TITLE
NoClassDefFoundError on Android platform

### ISSUE THREAD

**Issue by mrniko** [netty/netty#8654]
### Expected behavior

No exception

### Actual behavior

Exception arise during invocation DnsServerAddressStreamProviders.platformDefault method in Android application:
```java
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/naming/directory/InitialDirContext;
        at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.<clinit>(DefaultDnsServerAddressStreamProvider.java:68)
        at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:76)
        at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:32)
        at io.netty.resolver.dns.DnsServerAddressStreamProviders.platformDefault(DnsServerAddressStreamProviders.java:45)
```
### Steps to reproduce

execute `DnsServerAddressStreamProviders.platformDefault` method

### Netty version

4.1.31.Final

**Comment by normanmaurer** [comment]
@mrniko thanks for reporting... should be fixed by https://github.com/netty/netty/pull/8656
