### ISSUE TITLE
this error is makes me crazy  "java.lang.NoClassDefFoundError: io/netty/channel/socket/nio/NioSocketChannel "

### ISSUE THREAD

**Issue by yosephadane** [netty/netty#8659]
```
java.lang.NoClassDefFoundError: io/netty/channel/socket/nio/NioSocketChannel
	at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:79) ~[whatalokation-grpc-client.jar:?]
	at io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:121) ~[whatalokation-grpc-client.jar:?]
	at io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:107) ~[whatalokation-grpc-client.jar:?]
	at io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:52) ~[whatalokation-grpc-client.jar:?]
	at io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:38) ~[whatalokation-grpc-client.jar:?]
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:45) ~[whatalokation-grpc-client.jar:?]
	at org.jmeter.grpc.client.GrpcClientSampler.initGrpcClient(GrpcClientSampler.java:56) ~[grpc-client-sampler.jar:?]
	at org.jmeter.grpc.client.GrpcClientSampler.sample(GrpcClientSampler.java:79) ~[grpc-client-sampler.jar:?]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:622) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:546) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:486) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:253) ~[ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by normanmaurer** [comment]
@ejona86

**Comment by ejona86** [comment]
I have no clue how NioSocketChannel could be missing. It seems you would have to manually exclude some netty dependencies. Are you using Maven? If so, could you try running `mvn dependency:tree` and share any parts of the hierarchy below an io.grpc dependency (that is to mean, any things that grpc depends on)?

**Comment by ninja-** [comment]
to me it seems like you need to include and shade netty manually in your project

**Comment by ejona86** [comment]
Yes, using `grpc-netty-shaded` instead of `grpc-netty` should also resolve this issue.
