### ISSUE TITLE
SslProvider.OPENSSL and SslProvider.JDK perform different under same cipher

### ISSUE THREAD

**Issue by Zeymo** [netty/netty#8675]
Client communicate ssl record with SslProvider.OPENSSL and SslProvider.JDK both both success with same cipher
 
In order to support tlsv1.3,we upgrade netty 4.1.15.Final to 4.1.32.Final

client platform:
```
OpenSSL 1.0.2j  26 Sep 2016
built on: reproducible build, date unspecified
platform: linux-generic-openwrt
options:  bn(64,32) rc4(ptr,char) des(idx,cisc,2,long) blowfish(ptr) 
compiler: i486-openwrt-linux-uclibc-gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -I/sdb1/tpeng/src/iKuai_Router3/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/usr/include -I/sdb1/tpeng/src/iKuai_Router3/x86/staging_dir/target-i386_i486_uClibc-0.9.33.2/include -I/sdb1/tpeng/src/iKuai_Router3/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/usr/include -I/sdb1/tpeng/src/iKuai_Router3/x86/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/include -DOPENSSL_SMALL_FOOTPRINT -DOPENSSL_NO_ERR -DTERMIOS -Os -pipe -march=i486 -fno-caller-saves -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fpic -fomit-frame-pointer -Wall
OPENSSLDIR: "/etc/ssl"
```
server platform: jdk1.8.0_181
```
Linux x86_64 x86_64 x86_64 GNU/Linux
```

+ netty 4.1.15-Final (SslProvider.JDK)
handshake : TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
behavior :success

+ netty 4.1.32-Final (SslProvider.JDK)
handshake : TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
behavior :success

 + netty 4.1.32-Final + netty-tcnative-boringssl-static 2.0.20.Final (SslProvider.OPENSSL)
handshake : TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
behavior :error run in a period time

 + netty 4.1.15-Final + netty-tcnative-boringssl-static 2.0.20.Final (SslProvider.OPENSSL)
handshake : TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
behavior :error run in a period time

Error stack under SslProvider.OPENSSL
```
2018-12-19 16:04:46,713 [main] DEBUG io.netty.handler.ssl.OpenSsl - Initialize netty-tcnative using engine: 'default'
2018-12-19 16:04:46,713 [main] DEBUG io.netty.handler.ssl.OpenSsl - netty-tcnative using native library: BoringSSL
......

2018-12-19 16:05:50,796 [proxy-lws-legacy-core-12-12] DEBUG c.d.p.handlers.ExceptionHandler - ExceptionHandler_unexpected_failed] [id: 0x0400aadb, L:/xx.xx.xxx.xxx:7002 - R:/xx.xxx.xxx.xxx:61410]
java.lang.IllegalStateException: Invalid header: [1553ec94f19049cfaa244fa3a770]
        at com.xxx.protocol.Preconditions.checkState(Preconditions.java:17)
        at com.xxx.protocol.handlers.xxxMessageReader$ReadHeaders.read(xxxMessageReader.java:164)
        at com.xx.protocol.handlers.xxxMessageReader.read(xxxMessageReader.java:37)
        at com.xx.protocol.handlers.xxxMessageDecoder.read(xxxMessageDecoder.java:29)
        at com.xxx.protocol.handlers.SimpleLwpHandler.channelRead(SimpleLwpHandler.java:71)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1436)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1215)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1249)
```

**Comment by normanmaurer** [comment]
@Zeymo what protocol version are you using ? Also can you provide a reproducer ?

**Comment by Zeymo** [comment]
@normanmaurer TLS1.2
reproducer is difficult , because client is Intelligent hardware for isv
for now , I just have server log some detail

SslProvider.OPENSSL

```
2018-12-19 11:48:23,921 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 => ECDHE-ECDSA-AES128-GCM-SHA256
2018-12-19 11:48:23,921 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 => ECDHE-ECDSA-AES128-GCM-SHA256
2018-12-19 11:48:23,921 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 => ECDHE-RSA-AES128-GCM-SHA256
2018-12-19 11:48:23,921 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_AES_128_GCM_SHA256 => ECDHE-RSA-AES128-GCM-SHA256
2018-12-19 11:48:23,921 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 => ECDHE-ECDSA-AES256-GCM-SHA384
2018-12-19 11:48:23,921 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 => ECDHE-ECDSA-AES256-GCM-SHA384
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 => ECDHE-RSA-AES256-GCM-SHA384
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_AES_256_GCM_SHA384 => ECDHE-RSA-AES256-GCM-SHA384
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-ECDSA-CHACHA20-POLY1305
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-ECDSA-CHACHA20-POLY1305
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-RSA-CHACHA20-POLY1305
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-RSA-CHACHA20-POLY1305
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-PSK-CHACHA20-POLY1305
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 => ECDHE-PSK-CHACHA20-POLY1305
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA => ECDHE-ECDSA-AES128-SHA
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_128_CBC_SHA => ECDHE-ECDSA-AES128-SHA
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA => ECDHE-RSA-AES128-SHA
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_AES_128_CBC_SHA => ECDHE-RSA-AES128-SHA
2018-12-19 11:48:23,922 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA => ECDHE-PSK-AES128-CBC-SHA
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_PSK_WITH_AES_128_CBC_SHA => ECDHE-PSK-AES128-CBC-SHA
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA => ECDHE-ECDSA-AES256-SHA
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_ECDSA_WITH_AES_256_CBC_SHA => ECDHE-ECDSA-AES256-SHA
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA => ECDHE-RSA-AES256-SHA
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_RSA_WITH_AES_256_CBC_SHA => ECDHE-RSA-AES256-SHA
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA => ECDHE-PSK-AES256-CBC-SHA
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_ECDHE_PSK_WITH_AES_256_CBC_SHA => ECDHE-PSK-AES256-CBC-SHA
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_AES_128_GCM_SHA256 => AES128-GCM-SHA256
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_AES_128_GCM_SHA256 => AES128-GCM-SHA256
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_AES_256_GCM_SHA384 => AES256-GCM-SHA384
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_AES_256_GCM_SHA384 => AES256-GCM-SHA384
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_AES_128_CBC_SHA => AES128-SHA
2018-12-19 11:48:23,923 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_AES_128_CBC_SHA => AES128-SHA
2018-12-19 11:48:23,924 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_PSK_WITH_AES_128_CBC_SHA => PSK-AES128-CBC-SHA
2018-12-19 11:48:23,924 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_PSK_WITH_AES_128_CBC_SHA => PSK-AES128-CBC-SHA
2018-12-19 11:48:23,924 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_AES_256_CBC_SHA => AES256-SHA
2018-12-19 11:48:23,924 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_AES_256_CBC_SHA => AES256-SHA
2018-12-19 11:48:23,924 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_PSK_WITH_AES_256_CBC_SHA => PSK-AES256-CBC-SHA
2018-12-19 11:48:23,924 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_PSK_WITH_AES_256_CBC_SHA => PSK-AES256-CBC-SHA
2018-12-19 11:48:23,924 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: TLS_RSA_WITH_3DES_EDE_CBC_SHA => DES-CBC3-SHA
2018-12-19 11:48:23,924 [main] DEBUG i.n.h.ssl.CipherSuiteConverter - Cipher suite mapping: SSL_RSA_WITH_3DES_EDE_CBC_SHA => DES-CBC3-SHA
2018-12-19 11:48:23,924 [main] DEBUG io.netty.handler.ssl.OpenSsl - Supported protocols (OpenSSL): [SSLv2Hello, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3]
2018-12-19 11:48:23,924 [main] DEBUG io.netty.handler.ssl.OpenSsl - Default cipher suites (OpenSSL): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA, TLS_AES_128_GCM_SHA256, TLS_AES_256_GCM_SHA384]

suites in server-preferred order
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f) 
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014) 

```  

SslProvider.JDK
```
Using SSLEngineImpl.
Allow unsafe renegotiation: false
Allow legacy hello messages: true
Is initial handshake: true
Is secure renegotiation: false
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 for TLSv1.1
Ignoring unsupported cipher suite: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 for TLSv1.1

Cipher suite:  TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
```

in order to compare ,we set custom ciphers
```
public static final List<String> AVAILABLE_JAVA_CIPHER_SUITES = ImmutableList.of(
            "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
            "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"

    );

......

eturn SslContextBuilder.forServer(new File(ProxyConfig.DIR + File.separator + ProxyConfig.certPrefix + ".crt"),
                    new File(ProxyConfig.DIR + File.separator + ProxyConfig.certPrefix + ".key"))
                    .ciphers(AVAILABLE_JAVA_CIPHER_SUITES).build();
```

I will report more detail later

**Comment by Zeymo** [comment]
when occur error under SslProvider.OPENSSL also print leak info
```
2018-12-19 21:14:44,681 ERROR proxy-lws-legacy-core-12-1 LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records:
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:331)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:185)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:176)
	io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:1912)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1345)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1215)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1249)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
	io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:591)
	io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:508)
	io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.lang.Thread.run(Thread.java:834)

```

**Comment by normanmaurer** [comment]
Are you sure you handle fragmentation correctly ?

**Comment by Zeymo** [comment]
use SslProvider.JDK work correctly under same code space

it happened communication with Intelligent hardware and I will check another client (e.g. mac or moble) soon

**Comment by normanmaurer** [comment]
@Zeymo it doesn't matter if JDK works correctly here if you do not handle fragmentation as you can not make any assumption about this. How do you handler fragmentation of your data ?

**Comment by normanmaurer** [comment]
@Zeymo did you see my comment... From what I read in this issue it looks more like a bug in how you handle fragmentation.

**Comment by Zeymo** [comment]
sorry for hang , handle fragmentation after sslHandler  which wire work correct for long time in production. now, I have more important thing to resolve then this issue so I will close it and mayebe reopen in some future time . Thank for ur time ：）
