### ISSUE TITLE
PromiseNotificationUtil#tryFailure bug, I think~

### ISSUE THREAD

**Issue by gMan1990** [netty/netty#8688]
https://github.com/netty/netty/blob/66ccd1483a9f0c18b707711558c7bbea8bfc73da/common/src/main/java/io/netty/util/internal/PromiseNotificationUtil.java#L64
```java
    public static void tryFailure(Promise<?> p, Throwable cause, InternalLogger logger) {
        if (!p.tryFailure(cause) && logger != null) {
            Throwable err = p.cause();
            if (err == null) {
                logger.warn("Failed to mark a promise as failure because it has succeeded already: {}", p, cause);
            } else {
                logger.warn(
                        "Failed to mark a promise as failure because it has failed already: {}, unnotified cause: {}",
                        p, ThrowableUtil.stackTraceToString(err), cause);
            }
            // why not "else { throw new RuntimeException(cause); }"?
        }
    }
```
if ```p.tryFailure(cause)``` return true, then nothing output to ```logger```, so the ```Throwable cause``` is missing.

```text
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) [netty-all-4.1.23.Final.jar:4.1.23.Final]
	at io.netty.channel.ChannelDuplexHandler.write(ChannelDuplexHandler.java:106) [netty-all-4.1.23.Final.jar:4.1.23.Final]
```

**Comment by normanmaurer** [comment]
@gMan1990 I am not sure I understand you... if `tryFailure` returns true we could notify the promise and so the failure is visible there. So I think all works as designed.
