### ISSUE TITLE
OOME in SslHandlerCoalescingBufferQueue w/ H2

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#8707]
I have opened similar/same tickets (see #7659 and #8265) before but ended up closing them as they appeared to be user errors. It happens very rarely and trying to add instrumentation could be tricky. We see maybe 1 occurrence once or maybe even only every other week across a "large" (relatively speaking) fleet of Netty servers.

The theory was that flush is being called on a closed connection for example but I've added various guards against it and you can see on the screenshot below that the channel is active.

Basically, when it happen then something is filling up the SslHandlerCoalescingBufferQueue with millions of `Unpooled#EMPTY_BUFFER` very fast until an OOME occurs. It appears to be tied to H2.

Below is a stack trace which I find interesting and a view of the heap dump. From the state of the pipeline and access logs (we log certain TCP and TLS events) I can see that the client/server triggered this condition after the handshake but before any requests were received from the client.

A few places that I find interesting are:

DefaultHttp2RemoteFlowController line 626
FlowControlledData lines 411/412

 In particular the latter which may be the source for the EMPTY_BUFFER but I don't see (yet) the condition why it'd loop (although DefaultHttp2RemoteFlowController line 626 is technically inside an infinite loop).

```java
Stack traces at the moment of snapshot capture

HttpsWorkerThread-11 State: BLOCKED tid: 148
io.netty.channel.AbstractCoalescingBufferQueue.toChannelFutureListener(ChannelPromise) AbstractCoalescingBufferQueue.java:375
io.netty.channel.AbstractCoalescingBufferQueue.add(ByteBuf, ChannelPromise) AbstractCoalescingBufferQueue.java:84
io.netty.handler.ssl.SslHandler.write(ChannelHandlerContext, Object, ChannelPromise) SslHandler.java:759
io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(Object, ChannelPromise) AbstractChannelHandlerContext.java:738
io.netty.channel.AbstractChannelHandlerContext.invokeWrite(Object, ChannelPromise) AbstractChannelHandlerContext.java:730
io.netty.channel.AbstractChannelHandlerContext.write(Object, boolean, ChannelPromise) AbstractChannelHandlerContext.java:816
io.netty.channel.AbstractChannelHandlerContext.write(Object, ChannelPromise) AbstractChannelHandlerContext.java:723
io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledData.write(ChannelHandlerContext, int) DefaultHttp2ConnectionEncoder.java:412
io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.writeAllocatedBytes(int) DefaultHttp2RemoteFlowController.java:361
io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.write(Http2Stream, int) DefaultHttp2RemoteFlowController.java:546
io.netty.handler.codec.http2.UniformStreamByteDistributor$State.write(int, StreamByteDistributor$Writer) UniformStreamByteDistributor.java:176
io.netty.handler.codec.http2.UniformStreamByteDistributor.distribute(int, StreamByteDistributor$Writer) UniformStreamByteDistributor.java:122
io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes() DefaultHttp2RemoteFlowController.java:626
io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes() DefaultHttp2RemoteFlowController.java:266
io.netty.handler.codec.http2.Http2ConnectionHandler.flush(ChannelHandlerContext) Http2ConnectionHandler.java:200
io.netty.handler.codec.http2.Http2ConnectionHandler.channelWritabilityChanged(ChannelHandlerContext) Http2ConnectionHandler.java:440
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged() AbstractChannelHandlerContext.java:434
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext) AbstractChannelHandlerContext.java:416
io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged() AbstractChannelHandlerContext.java:409
io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelHandlerContext) ChannelInboundHandlerAdapter.java:119
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged() AbstractChannelHandlerContext.java:434
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext) AbstractChannelHandlerContext.java:416
io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged() AbstractChannelHandlerContext.java:409
io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelHandlerContext) ChannelInboundHandlerAdapter.java:119
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged() AbstractChannelHandlerContext.java:434
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext) AbstractChannelHandlerContext.java:416
io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged() AbstractChannelHandlerContext.java:409
io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelHandlerContext) ChannelInboundHandlerAdapter.java:119
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged() AbstractChannelHandlerContext.java:434
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext) AbstractChannelHandlerContext.java:416
io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged() AbstractChannelHandlerContext.java:409
io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelHandlerContext) ChannelInboundHandlerAdapter.java:119
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged() AbstractChannelHandlerContext.java:434
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext) AbstractChannelHandlerContext.java:416
io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged() AbstractChannelHandlerContext.java:409
io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelHandlerContext) ChannelInboundHandlerAdapter.java:119
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged() AbstractChannelHandlerContext.java:434
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext) AbstractChannelHandlerContext.java:416
io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged() AbstractChannelHandlerContext.java:409
io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelHandlerContext) ChannelInboundHandlerAdapter.java:119
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged() AbstractChannelHandlerContext.java:434
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext) AbstractChannelHandlerContext.java:416
io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged() AbstractChannelHandlerContext.java:409
io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelHandlerContext) ChannelInboundHandlerAdapter.java:119
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged() AbstractChannelHandlerContext.java:434
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext) AbstractChannelHandlerContext.java:416
io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged() AbstractChannelHandlerContext.java:409
io.netty.channel.DefaultChannelPipeline$HeadContext.channelWritabilityChanged(ChannelHandlerContext) DefaultChannelPipeline.java:1457
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged() AbstractChannelHandlerContext.java:434
io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext) AbstractChannelHandlerContext.java:416
io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged() DefaultChannelPipeline.java:977
io.netty.channel.ChannelOutboundBuffer$2.run() ChannelOutboundBuffer.java:608
io.netty.util.concurrent.AbstractEventExecutor.safeExecute(Runnable) AbstractEventExecutor.java:163
io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(long) SingleThreadEventExecutor.java:404
io.netty.channel.epoll.EpollEventLoop.run() EpollEventLoop.java:335
io.netty.util.concurrent.SingleThreadEventExecutor$5.run() SingleThreadEventExecutor.java:909
java.lang.Thread.run() Thread.java:745
```

![screenshot from 2019-01-07 13-20-47](https://user-images.githubusercontent.com/191635/50787194-bf3d6b80-1283-11e9-9099-aaaba8e62d0f.png)

### Netty version

4.1.32.Final w/ TCN

**Comment by rkapsi** [comment]
Looks like I have kept many of the memory dumps. Looking at the stack traces I either see what I already posted or this:

```java
"HttpsWorkerThread-9" #145 prio=5 os_prio=0 tid=0x00007ff450149800 nid=0x7d2c waiting for monitor entry [0x00007ff414e85000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.netty.channel.AbstractChannelHandlerContext.newPromise(AbstractChannelHandlerContext.java:881)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledData.write(DefaultHttp2ConnectionEncoder.java:411)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$FlowState.writeAllocatedBytes(DefaultHttp2RemoteFlowController.java:361)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.write(DefaultHttp2RemoteFlowController.java:546)
	at io.netty.handler.codec.http2.UniformStreamByteDistributor$State.write(UniformStreamByteDistributor.java:176)
	at io.netty.handler.codec.http2.UniformStreamByteDistributor.distribute(UniformStreamByteDistributor.java:122)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController$WritabilityMonitor.writePendingBytes(DefaultHttp2RemoteFlowController.java:626)
	at io.netty.handler.codec.http2.DefaultHttp2RemoteFlowController.writePendingBytes(DefaultHttp2RemoteFlowController.java:266)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.flush(Http2ConnectionHandler.java:200)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.channelWritabilityChanged(Http2ConnectionHandler.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelWritabilityChanged(ChannelInboundHandlerAdapter.java:119)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelWritabilityChanged(AbstractChannelHandlerContext.java:409)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelWritabilityChanged(DefaultChannelPipeline.java:1457)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:416)
	at io.netty.channel.DefaultChannelPipeline.fireChannelWritabilityChanged(DefaultChannelPipeline.java:977)
	at io.netty.channel.ChannelOutboundBuffer$2.run(ChannelOutboundBuffer.java:608)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:745)
```

Since both variants are hovering around `DefaultHttp2RemoteFlowController$FlowState.writeAllocatedBytes(DefaultHttp2RemoteFlowController.java:361)` I wonder if it could be this while loop.

https://github.com/netty/netty/blob/4.1/codec-http2/src/main/java/io/netty/handler/codec/http2/DefaultHttp2RemoteFlowController.java#L351-L373

The heap dump in all cases is saying that `pendingWriteQueue` has one element and the size() of the frame is non-zero which will result in the element never getting removed after the write.

**Comment by rkapsi** [comment]
![screenshot from 2019-01-11 16-34-21](https://user-images.githubusercontent.com/191635/51060851-32feb180-15bf-11e9-8a75-599787f2476e.png)

**Comment by normanmaurer** [comment]
@rkapsi thanks ... looking into it as we speak.

**Comment by normanmaurer** [comment]
@ejona86 please have a look as well.

**Comment by normanmaurer** [comment]
@rkapsi I think you are on something here... I think what happens here is that `FlowControlledData.write(...)` returns early as `queuedData` is `0` and its not `endOfStream` while `size()` still returns a positive value and so `write(...)` will be called forever. WDYT ?

**Comment by rkapsi** [comment]
@normanmaurer yes, that sounds plausible and the heap dump(s) confirm the values.

![screenshot from 2019-01-14 10-14-10](https://user-images.githubusercontent.com/191635/51121655-f06aee00-17e5-11e9-8f8d-38e4b2af5cf4.png)

**Comment by normanmaurer** [comment]
@rkapsi now I just need to understand how this happens 😢

**Comment by normanmaurer** [comment]
And @carl-mastrangelo

**Comment by normanmaurer** [comment]
Still not sure yet how this happens :/

**Comment by normanmaurer** [comment]
@rkapsi ok I think I found the problem... writing a reproducer now.

**Comment by normanmaurer** [comment]
@rkapsi PTAL https://github.com/netty/netty/pull/8726
