### ISSUE TITLE
NativeIoException: readAddress(..) failed: Connection timed out

### ISSUE THREAD

**Issue by weiguovmware** [netty/netty#8801]
I'm facing an exception from Netty. My tests restarted the client and server throw out the netty exception.

io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection timed out
     at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
     at io.netty.channel.unix.Errors.ioResult(Errors.java:146) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
     at io.netty.channel.unix.FileDescriptor.readAddress(FileDescriptor.java:178) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
     at io.netty.channel.epoll.AbstractEpollChannel.doReadBytes(AbstractEpollChannel.java:343) ~[netty-all-4.1.27.Final.jar:4.1.27.Final]
     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:794) [netty-all-4.1.27.Final.jar:4.1.27.Final]
     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:417) [netty-all-4.1.27.Final.jar:4.1.27.Final]
     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:317) [netty-all-4.1.27.Final.jar:4.1.27.Final]
     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.27.Final.jar:4.1.27.Final]
     at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]

**Comment by weiguovmware** [comment]
Hi Norman,

I saw some cases that connection established then throw out this exception around 25s. 

I'm wondering what's the time limitation of the readAddress() message. Also the "forcibility" closed is from the client side? Is there any TCP message or state changes triggered the readAddress() time out?

Thanks

**Comment by trajano** [comment]
I'm getting the same issue but with GRPC Java.  It occurs randomly

**Comment by BBartosz** [comment]
@trajano Had the same problem, you have to set idleTimeout in grpcJava. I think also keepAlive might help you but in my case idleTimeout set to 2 minutes was better approach. Differences between them you can find in this answer: https://stackoverflow.com/questions/57930529/grpc-connection-use-keepalive-or-idletimeout

For people non using grpcJava and having this issue in netty: set the idleTimeout to smaller value than default (30 mins afaik)
