### ISSUE TITLE
Failed test DatagramUnicastTest#testSimpleSendWithConnect 4.1.34.Final-SNAPSHOT

### ISSUE THREAD

**Issue by amizurov** [netty/netty#8857]
### Expected behavior
Test is work properly

### Actual behavior
Test failed:
```
14:18:52.756 [main] INFO  i.n.t.t.socket.DatagramUnicastTest - Running: testSimpleSendWithConnect 1 of 4 (Bootstrap(BootstrapConfig(group: NioEventLoopGroup, channelFactory: NioDatagramChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@5702b3b1)) + Bootstrap(BootstrapConfig(group: NioEventLoopGroup, channelFactory: NioDatagramChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@5702b3b1))) with UnpooledByteBufAllocator
14:18:52.792 [main] INFO  i.n.t.t.socket.DatagramUnicastTest - Running: testSimpleSendWithConnect 2 of 4 (Bootstrap(BootstrapConfig(group: NioEventLoopGroup, channelFactory: NioDatagramChannel.class, options: {ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@5702b3b1)) + Bootstrap(BootstrapConfig(group: OioEventLoopGroup, channelFactory: ReflectiveChannelFactory(OioDatagramChannel.class), options: {SO_TIMEOUT=10, ALLOCATOR=UnpooledByteBufAllocator(directByDefault: true)}, resolver: io.netty.resolver.DefaultAddressResolverGroup@5702b3b1))) with UnpooledByteBufAllocator

java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendWithConnect0(DatagramUnicastTest.java:257)
	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendWithConnect(DatagramUnicastTest.java:203)
	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendWithConnect(DatagramUnicastTest.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.netty.testsuite.transport.AbstractComboTestsuiteTest.run(AbstractComboTestsuiteTest.java:67)
	at io.netty.testsuite.transport.socket.DatagramUnicastTest.testSimpleSendWithConnect(DatagramUnicastTest.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

### Steps to reproduce
Run DatagramUnicastTest#testSimpleSendWithConnect

### Netty version
4.1.34.Final-SNAPSHOT

### JVM version (e.g. `java -version`)
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)

### OS version (e.g. `uname -a`)
18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by normanmaurer** [comment]
Can you reproduce this all the time or is it a flaky test ?

**Comment by amizurov** [comment]
This is test fails on my machine all the time

**Comment by normanmaurer** [comment]
Hmm strange works here

**Comment by amizurov** [comment]
In this suite ``testSimpleSendWithConnect 2 of 4`` first ``WrapType NONE`` passed then second type ``DUP`` stuck and never happened:  ``assertTrue(clientLatch.await(10, TimeUnit.SECONDS))``.

**Comment by amizurov** [comment]
@normanmaurer I don't now how, but after last sync with Netty upstream everything work properly ))) Maybe problem was in my environment.
