### ISSUE TITLE
objectcleaner cpu 100%

### ISSUE THREAD

**Issue by onethehappy** [netty/netty#8873]
### Actual behavior
below is the result of "ps -mp 2633 -o THREAD,tid,time | sort -rn"

![cpu](https://user-images.githubusercontent.com/9351329/52937856-2ed26a80-339b-11e9-9062-8de3fe8e7f02.jpeg)

below is the relust of "jstat -gcutil 2633 1000 100":
![webwxgetmsgimg](https://user-images.githubusercontent.com/9351329/52938224-1dd62900-339c-11e9-924c-486e96ab23ae.jpeg)

the jstack info:
`
"ObjectCleanerThread" #23 daemon prio=1 os_prio=0 tid=0x00007f53bcf85800 nid=0x28 runnable [0x00007f533abc7000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.Recycler$WeakOrderQueue$Head.run(Recycler.java:264)
	at io.netty.util.internal.ObjectCleaner$AutomaticCleanerReference.cleanup(ObjectCleaner.java:143)
	at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:62)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
"grpc-default-worker-ELG-1-8" #32 daemon prio=5 os_prio=0 tid=0x00007f53bd956000 nid=0x31 runnable [0x00007f5321cf9000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000086ed5690> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x0000000086ed66f8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000086ed55f8> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

"grpc-default-worker-ELG-1-7" #31 daemon prio=5 os_prio=0 tid=0x00007f531c00a800 nid=0x30 runnable [0x00007f5321dfa000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000086f761c8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000000871c5ef8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000086f76130> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

"grpc-default-worker-ELG-1-6" #30 daemon prio=5 os_prio=0 tid=0x00007f53252f9800 nid=0x2f runnable [0x00007f5322efc000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000871a40f0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000000871a7e80> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000871a4058> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

"grpc-default-worker-ELG-1-5" #29 daemon prio=5 os_prio=0 tid=0x00007f53bc628000 nid=0x2e runnable [0x00007f539c1b4000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000008704b6d0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000008704c738> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000008704b638> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

"grpc-default-worker-ELG-1-4" #28 daemon prio=5 os_prio=0 tid=0x00007f53285a7000 nid=0x2d runnable [0x00007f5322ffd000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000871770e0> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000000871781b8> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000087177038> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

"grpc-default-worker-ELG-1-3" #27 daemon prio=5 os_prio=0 tid=0x00007f5328275800 nid=0x2c runnable [0x00007f53383c1000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000870891b8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000008708a220> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000087089120> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

"grpc-default-worker-ELG-1-2" #26 daemon prio=5 os_prio=0 tid=0x00007f5324cda000 nid=0x2b runnable [0x00007f53394c3000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x0000000086f78cd8> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000008704dc68> (a java.util.Collections$UnmodifiableSet)
	- locked <0x0000000086f78c30> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

"grpc-default-worker-ELG-1-1" #24 daemon prio=5 os_prio=0 tid=0x00007f53be3ce000 nid=0x29 runnable [0x00007f53398c5000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x000000008708c968> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x000000008708da40> (a java.util.Collections$UnmodifiableSet)
	- locked <0x000000008708c8c0> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

"ObjectCleanerThread" #23 daemon prio=1 os_prio=0 tid=0x00007f53bcf85800 nid=0x28 runnable [0x00007f533abc7000]
   java.lang.Thread.State: RUNNABLE
	at io.netty.util.Recycler$WeakOrderQueue$Head.run(Recycler.java:264)
	at io.netty.util.internal.ObjectCleaner$AutomaticCleanerReference.cleanup(ObjectCleaner.java:143)
	at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:62)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
`

### Netty version
4.1.23.final
### JVM version (e.g. `java -version`)
jdk8

**Comment by normanmaurer** [comment]
Yes this is a know bug and was fixed a long time ago (4.1.23.final is quite old). Please upgrade to latest version of Netty

**Comment by benshuai5D** [comment]
Hi, could you describe the cause of the problem and the version of the solution? 😄 @normanmaurer

**Comment by carl-HelloWorld** [comment]
> Yes this is a know bug and was fixed a long time ago (4.1.23.final is quite old). Please upgrade to latest version of Netty

upgrade to verison?
