### ISSUE TITLE
KeyManagerFactory not supported when using openssl 1.0.2 at runtime

### ISSUE THREAD

**Issue by philsttr** [netty/netty#8879]
PR #368 was supposed to enable KeyManagerFactory when the dynamically linked netty-tcnative binary is used with openssl 1.0.2 at runtime, but I'm finding that it is still not working for me.

### Expected behavior

KeyManagerFactory is supported when using the dynamically linked netty-tcnative binary with openssl 1.0.2 at runtime.

### Actual behavior

KeyManagerFactory is NOT supported when using the dynamically linked netty-tcnative binary with openssl 1.0.2 at runtime.

At runtime, with debug logging enabled, I see the following log entries:

```
19:40:22.263 DEBUG [io.netty.handler.ssl.OpenSsl] - Initialize netty-tcnative using engine: 'default'
19:41:34.240 DEBUG [io.netty.handler.ssl.OpenSsl] - netty-tcnative using native library: OpenSSL 1.0.1e-fips 11 Feb 2013
19:41:34.885 DEBUG [io.netty.handler.ssl.OpenSsl] - KeyManagerFactory not supported.
```
The log statement indicates that it is using OpenSSL 1.0.1e-fips, but that version of OpenSSL is not installed on this machine.
Is the version reported the version that the netty-tcnative binary was compiled against?

When I step through in a debugger, I can see that when OpenSsl is detecting if KeyManagerFactory is supported [here](https://github.com/netty/netty/blob/netty-4.1.33.Final/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L200),
`SSL.setCertificateChainBio` throws this exception (which is caught [here](https://github.com/netty/netty/blob/netty-4.1.33.Final/handler/src/main/java/io/netty/handler/ssl/OpenSsl.java#L214)):

```
java.lang.Exception: Error setting certificate chain (error:00000000:lib(0):func(0):reason(0))
        at io.netty.internal.tcnative.SSL.setCertificateChainBio(Native Method)
        at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:200)
```

### Steps to reproduce

Use the Dockerfile mentioned below to reproduce.

Otherwise, create an environment similar to what I have mentioned in the versions section below, and just attempt to use KeyManagerFactory.

### Minimal yet complete reproducer code (or URL to code)

Here's a Dockerfile that creates an Docker image that duplicates my environment and runs a test:

https://gist.github.com/philsttr/f3db79e88ac2c93e46ba289000d389cc

Copy the Dockerfile into an empty local directory, then...

```
docker build --tag netty-tcnative-test .
docker run -it --rm netty-tcnative-test
```

Output will look similar to the following

```
++ cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)
++ uname -a
Linux 3433339e5227 4.9.49-moby #1 SMP Fri Dec 8 13:40:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
++ java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
++ rpm -qa openssl apr
apr-1.4.8-3.el7_4.1.x86_64
openssl-1.0.2k-16.el7.x86_64
++ ls -1 netty-buffer-4.1.33.Final.jar netty-codec-4.1.33.Final.jar netty-common-4.1.33.Final.jar netty-handler-4.1.33.Final.jar netty-tcnative-2.0.20.Final-linux-x86_64-fedora.jar
 netty-transport-4.1.33.Final.jar
netty-buffer-4.1.33.Final.jar
netty-codec-4.1.33.Final.jar
netty-common-4.1.33.Final.jar
netty-handler-4.1.33.Final.jar
netty-tcnative-2.0.20.Final-linux-x86_64-fedora.jar
netty-transport-4.1.33.Final.jar
++ java -cp '*:.' -Djava.util.logging.config.file=logging.properties NettyTest
Feb 22, 2019 1:14:35 AM io.netty.handler.ssl.OpenSsl <clinit>
FINE: Initialize netty-tcnative using engine: 'default'
Feb 22, 2019 1:14:35 AM io.netty.handler.ssl.OpenSsl <clinit>
FINE: netty-tcnative using native library: OpenSSL 1.0.1e-fips 11 Feb 2013
Feb 22, 2019 1:14:35 AM io.netty.handler.ssl.OpenSsl <clinit>
FINE: KeyManagerFactory not supported.
Feb 22, 2019 1:14:35 AM io.netty.handler.ssl.OpenSsl <clinit>
FINE: Supported protocols (OpenSSL): [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2]
Feb 22, 2019 1:14:35 AM io.netty.handler.ssl.OpenSsl <clinit>
FINE: Default cipher suites (OpenSSL): [TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_
AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_CBC_SHA]
OpenSsl.supportsKeyManagerFactory()=false
```

### Versions

|what|version|
|-----|-------|
|netty         | 4.1.33.Final                       |
|netty-tcnative| 2.0.20.Final (linux-x86_64-fedora) |
|openssl       | 1.0.2k-16.el7                      |
|apr           | 1.4.8-3.el7_4.1                    |
|centos        | 7.6.1810                           |
|openjdk       | 11.0.2                             |

**Comment by philsttr** [comment]
Closing.  Meant to open this under netty-tcnative

**Comment by philsttr** [comment]
https://github.com/netty/netty-tcnative/issues/434
