### ISSUE TITLE
java.lang.VerifyError: io/netty/handler/codec/protobuf/ProtobufDecoder

### ISSUE THREAD

**Issue by tracyis** [netty/netty#8928]
I tried use netty on Android 4.4, but it doesn't work

> Netty version `"io.netty:netty-all:4.1.34.Final"`
> Java version `"1.8.0_152"`

here is the log

```
W/ChannelInitializer: Failed to initialize a channel. Closing: [id: 0x87e041e0]
    java.lang.VerifyError: io/netty/handler/codec/protobuf/ProtobufDecoder
        at cn.xiaoman.android.mail.service.socket.GatewayInitializer.initChannel(GatewayInitializer.kt:44)
        at cn.xiaoman.android.mail.service.socket.GatewayInitializer.initChannel(GatewayInitializer.kt:19)
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129)
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112)
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:953)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:610)
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46)
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1461)
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1126)
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:651)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:515)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:428)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:487)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:841)
```

initial code

```
class GatewayInitializer(private val gatewayHandler: ChannelHandler) : ChannelInitializer<SocketChannel>() {

    @Throws(Exception::class)
    override fun initChannel(ch: SocketChannel?) {
        ch?.let {
            ch.pipeline().addLast(
                    SslContextBuilder
                            .forClient()
                            .trustManager(GateWayTrustManagerFactory { it.close()?.sync() })
                            .build()
                            .newHandler(it.alloc())
            )
            ch.pipeline().addLast(LengthFieldBasedFrameDecoder(MAX_FRAME_LENGTH, 0, 4, 0, 4))
            ch.pipeline().addLast(ProtobufDecoder(PBCommon.PBPackage.getDefaultInstance()))
            ch.pipeline().addLast(LengthFieldPrepender(4))
            ch.pipeline().addLast(ProtobufEncoder())
            ch.pipeline().addLast(IdleStateHandler(PING_TIME, PING_TIME, PING_TIME))
            ch.pipeline().addLast(gatewayHandler)
        }
    }

    companion object {
        private const val MAX_FRAME_LENGTH = 1024 * 1024 * 16
        const val PING_TIME = 210
    }
}
```

**Comment by normanmaurer** [comment]
@tracyis this looks more like an android issue (may how you setup the project) then Netty. Are you sure you have the correct protobuf version on the class path ?

**Comment by tracyis** [comment]
> @tracyis this looks more like an android issue (may how you setup the project) then Netty. Are you sure you have the correct protobuf version on the class path ?

I checked out it may be a problem caused by multidex support to Android 5.0 or lower version.

**Comment by normanmaurer** [comment]
@tracyis yeah this looks more like a android / runtime / dependency problem then netty. Let me close this issue and please re-open if you still think its netty
