### ISSUE TITLE
Netty 2.0.22 bound to openssl 1.0.0

### ISSUE THREAD

**Issue by rpandar** [netty/netty#8935]
Does netty support latest versions of ssl - 1.0.2 / 1.1.1 ? Here's the error is see when attempting to use it dynamically with version 1.0.2 installed on my box ( Linux x86_64) 

-bash-4.2$ java -jar target/test-1.0-SNAPSHOT.jar -verbose
starting execution
Exception in thread "main" java.lang.UnsatisfiedLinkError: /scratch/opensslpoc/nettyJar/META-INF/native/libnetty_tcnative.so: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /scratch/opensslpoc/nettyJar/META-INF/native/libnetty_tcnative.so)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at com.sample.openssl.App.main(App.java:15)

**Comment by normanmaurer** [comment]
Please upgrade to latest netty / netty-tcnative version. This should work with 1.0.2
