### ISSUE TITLE
OOM when uploading large files

### ISSUE THREAD

**Issue by doom369** [netty/netty#9007]
I was recently guarding our app with security checks and decided to limit the size of the http request. After this I found that server dies with OOM when I try to upload few large files.

In my test I:

- Run the server;
- Upload 3 times the same file with 1.4GB size;
- Server throws exceptions below;

```
java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
	at io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:768)
	at io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:744)
	at io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:227)
	at io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
	at io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:327)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	at io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:2120)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1325)
	at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1237)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Profiles result after 3 uploads:

```
    34008984   29.13%       65  io.netty.buffer.PooledSlicedByteBuf
    27497824   23.55%       50  io.netty.util.Recycler$DefaultHandle
    17348936   14.86%       36  io.netty.buffer.PooledUnsafeDirectByteBuf
    12710968   10.89%       27  java.nio.DirectByteBuffer
    10978400    9.40%       26  io.netty.handler.codec.http.DefaultHttpContent
     5043456    4.32%       16  javax.net.ssl.SSLEngineResult
     3215928    2.75%        5  byte[]
     1961568    1.68%        4  io.netty.buffer.PoolSubpage[]
     1150160    0.99%        2  java.lang.String
      702952    0.60%        1  java.util.ArrayDeque
```

Server eats 8 GB after 3 tries.

The main difference I found between OOM server and normal server (server that frees the memory between large file uploads) is `HttpObjectAggregator`.

Server that has OOM has:

```
                                .addLast("HttpsObjectAggregator",
                                        new HttpObjectAggregator(holder.limits.webRequestMaxSize, true))
web.request.max.size=5242880
```

Server that frees the memory between file uploads:
```

                                .addLast("HttpsObjectAggregator",
                                        new HttpObjectAggregator(Integer.MAX_VALUE, true))
```

Profiles result after 3 uploads without request size limit:

```
       bytes  percent  samples  top
  ----------  -------  -------  ---
    19270216   16.74%       95  byte[]
    17301648   15.03%        9  byte[] (out)
    15983536   13.88%       56  io.netty.buffer.CompositeByteBuf$Component
    15472152   13.44%       53  io.netty.handler.codec.http.DefaultHttpContent
    12619656   10.96%       46  long[]
     8130168    7.06%       32  java.lang.Object[]
     7883232    6.85%       29  javax.net.ssl.SSLEngineResult
     3072624    2.67%        8  java.lang.String
     2181960    1.90%        7  int[]
     1889664    1.64%        5  short[]
     1754400    1.52%        8  java.util.concurrent.locks.AbstractQueuedSynchronizer$Node
     1731048    1.50%        8  io.netty.buffer.PooledSlicedByteBuf
     1620920    1.41%        7  java.lang.String[]
     1332704    1.16%        5  io.netty.util.Recycler$DefaultHandle
      978648    0.85%        5  io.netty.util.ResourceLeakDetector$Record
```

Similar issue - https://github.com/netty/netty/issues/3559.

```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu116.04ppa1, mixed mode, sharing)
```

```
        <netty.version>4.1.34.Final</netty.version>
        <netty.boring.ssl.version>2.0.22.Final</netty.boring.ssl.version>
```

Pipeline is pretty complex, however this is main handlers:

```
.addLast(holder.sslContextHolder.sslCtx.newHandler(ch.alloc()))
.addLast("HttpsServerCodec", new HttpServerCodec())
.addLast("HttpsObjectAggregator", new HttpObjectAggregator(holder.limits.webRequestMaxSize, true))
.addLast("HttpsChunkedWrite", new ChunkedWriteHandler())
```

**Comment by normanmaurer** [comment]
@doom369 I wonder if you can also run this with paranoid leak detection.

**Comment by doom369** [comment]
I tried - no luck. No leaks.

**Comment by normanmaurer** [comment]
@doom369 just to be sure I not misunderstood you...

The server that did NOT OOME did have `Integer.MAX_VALUE` and the one that did had a value of `5242880 ` ?

**Comment by doom369** [comment]
@normanmaurer correct. Flow that discard the upload due to large request size has OOM.

**Comment by normanmaurer** [comment]
@doom369 can you also show me the rest of the pipeline ?

**Comment by doom369** [comment]
@normanmaurer my bad regarding leaks. I had turned off logging in other place. I see the leak now.

```
10:40:10.055 ERROR- LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1476)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1237)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:834)
#2:
	io.netty.buffer.AdvancedLeakAwareByteBuf.readRetainedSlice(AdvancedLeakAwareByteBuf.java:106)
	io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:296)
	io.netty.handler.codec.http.HttpServerCodec$HttpServerRequestDecoder.decode(HttpServerCodec.java:103)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1476)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1237)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:834)
#3:
	Hint: 'HttpsServerCodec' will handle the message from this point.
	io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1476)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1237)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:834)
#4:
	io.netty.buffer.AdvancedLeakAwareByteBuf.internalNioBuffer(AdvancedLeakAwareByteBuf.java:736)
	io.netty.handler.ssl.SslHandler.toByteBuffer(SslHandler.java:1486)
	io.netty.handler.ssl.SslHandler.access$300(SslHandler.java:166)
	io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:218)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1330)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1237)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:834)
#5:
	io.netty.buffer.AdvancedLeakAwareByteBuf.nioBufferCount(AdvancedLeakAwareByteBuf.java:706)
	io.netty.handler.ssl.SslHandler.toByteBuffer(SslHandler.java:1486)
	io.netty.handler.ssl.SslHandler.access$300(SslHandler.java:166)
	io.netty.handler.ssl.SslHandler$SslEngineType$1.unwrap(SslHandler.java:218)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1330)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1237)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:834)
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:334)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	io.netty.handler.ssl.SslHandler.allocate(SslHandler.java:2120)
	io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1325)
	io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1237)
	io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
	io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
	io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
	io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796)
	io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427)
	io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328)
	io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by doom369** [comment]
@normanmaurer please ignore for now. It could be a bug in my handler due to changed flow introduced by request limit.

**Comment by normanmaurer** [comment]
@doom369 ok... keep me posted

**Comment by normanmaurer** [comment]
@doom369 from the log it looks like you missed to release in `HttpStaticFile `.

**Comment by doom369** [comment]
@normanmaurer yes, you are right. But what I don't get is why in case of large file size next handler  receives `DefaultHttpContent` chunks. My understanding was that in case of large file `HttpObjectAggregator` with return `FullHttpResponse TOO_LARGE`, however, seems like even in that case `DefaultHttpContent` are still received by next handler. So file is partially uploaded. Is that expected?

**Comment by normanmaurer** [comment]
@doom369 no this is not expected...

**Comment by doom369** [comment]
@normanmaurer ok, I have one suggestion, but this could be just a guess.

`HttpObjectAggregator.handleOversizedMessage` has next code

```
            } else {
                ctx.writeAndFlush(TOO_LARGE.retainedDuplicate()).addListener(new ChannelFutureListener() {
                    @Override
                    public void operationComplete(ChannelFuture future) throws Exception {
                        if (!future.isSuccess()) {
                            logger.debug("Failed to send a 413 Request Entity Too Large.", future.cause());
                            ctx.close();
                        }
                    }
                });
            }

            // If an oversized request was handled properly and the connection is still alive
            // (i.e. rejected 100-continue). the decoder should prepare to handle a new message.
            HttpObjectDecoder decoder = ctx.pipeline().get(HttpObjectDecoder.class);
            if (decoder != null) {
                decoder.reset();
            }
```

`TOO_LARGE` is sent. That's correct.
However, `ctx.pipeline().get(HttpObjectDecoder.class)` always returns null.
I thinks this could be because I use `HttpServerCodec` in my pipeline and not `HttpRequestDecoder`. I didn't find a code that adds `HttpRequestDecoder` to the pipeline. I'm not very familiar with this part of code. So maybe you have some clues here.

**Comment by normanmaurer** [comment]
@doom369 yep this looks not correct... let me check

**Comment by normanmaurer** [comment]
@doom369 hmm while this code has a bug (as you pointed out) I don't get why you would receive more `HttpContent` instances for the request in the next handler as we should drop these on the floor as far as I see.

**Comment by doom369** [comment]
@normanmaurer I believe browser start sending file chunks. Also, one detail - after I dropped file to the browser and 413 response in browser ~4 seconds are passed. During this periods server and browser consumes CPU a lot.

> as we should drop these on the floor as far as I see

could you please point me to code you are refferring to?

**Comment by normanmaurer** [comment]
@doom369 https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/MessageAggregator.java#L277 ... That said from reading the code I think we need to also set `currentMessage = null` here:

https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/MessageAggregator.java#L294

WDYT ?

**Comment by doom369** [comment]
@normanmaurer it is null due to this method https://github.com/netty/netty/blob/4.1/codec/src/main/java/io/netty/handler/codec/MessageAggregator.java#L400

**Comment by normanmaurer** [comment]
@doom369 true... so I am not sure why you would see more content :/

**Comment by doom369** [comment]
@normanmaurer according to the debug it comes from:

`HttpObjectAggregator.MessageToMessageDecoder.channelRead()` finallly block:

```
        } finally {
            int size = out.size();
            for (int i = 0; i < size; i ++) {
                ctx.fireChannelRead(out.getUnsafe(i));
            }
            out.recycle();
        }
```

And `out` is not empty because of this commit https://github.com/netty/netty/pull/8793/files where `MessageAggregator.acceptInboundMessage` method was changed.

**Comment by normanmaurer** [comment]
Interesting.... @rkapsi mind having a look ?

**Comment by normanmaurer** [comment]
@doom369 @rkapsi from a quick look I think this line must be removed:

https://github.com/netty/netty/pull/8793/files#diff-0522c090d2ed17d5b357324a06ace7a9R403

**Comment by normanmaurer** [comment]
@doom369 could you do the change and test it ?

**Comment by doom369** [comment]
@normanmaurer tried the fix. Now file upload dropped instantly, however I don't get 413 error in the browser, just broken connection. Maybe not related, but it is hard to tell right now.

**Comment by normanmaurer** [comment]
@doom369 what happens if you revert https://github.com/netty/netty/pull/8793 ? Do you get the 413 error ?
