### ISSUE TITLE
OpenSslX509TrustManagerWrapper in netty-handler is not Java 6 compatible

### ISSUE THREAD

**Issue by kwart** [netty/netty#9064]
Netty 4.y should work on Java 6, it's not the case of the `OpenSslX509TrustManagerWrapper` which fails to load the class:

```
java.lang.NoClassDefFoundError: Could not initialize class io.netty.handler.ssl.OpenSslX509TrustManagerWrapper
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext.chooseTrustManager(ReferenceCountedOpenSslContext.java:541)
	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:142)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:350)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:333)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:422)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:447)
	at ...
```

The problem is rooted in using `javax.net.ssl.X509ExtendedTrustManager` which was introduced in Java 7.

The netty-handler versions with the issue: 4.1.31 - 4.1.34 (current)

**Comment by normanmaurer** [comment]
@kwart hmmm will need to check... you are interested in providing a PR ?

**Comment by normanmaurer** [comment]
@kwart fixed in https://github.com/netty/netty/pull/9065

**Comment by kwart** [comment]
You're too fast :+1: :) I'll check the PR in our tests. Thanks.

**Comment by normanmaurer** [comment]
@kwart let me know once you know the outcome as I plan to release a new version tomorrow ;)

**Comment by kwart** [comment]
All our TLS tests passed on Java 6 with the fix. Well done!
