### ISSUE TITLE
java.io.IOException: Transport endpoint is not connected

### ISSUE THREAD

**Issue by sysulincn** [netty/netty#9110]
### Actual behavior

After running for some time, my application log down an exception:
```
2019-04-24 23:39:00 WARN NettyBoss_1 - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Transport endpoint is not connected
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:140)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:69)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
        at java.lang.Thread.run(Thread.java:748)
```
after this exception(I guess), remote applications cannot connect to the specific port, and 
`netstat -alnp | grep $listeningPort` showed nothing, i.e. netty was not listening
`jstack` showed that netty nioEventLoop was still waiting for incoming connection
```
"NettyBoss_1" #62 prio=5 os_prio=0 tid=0x00007f2340949020 nid=0x93ce runnable [0x00007efa7bcfb000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.epollWait(Native Method)
	at sun.nio.ch.EPollArrayWrapper.poll(EPollArrayWrapper.java:269)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:93)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000005c13d7250> (a io.netty.channel.nio.SelectedSelectionKeySet)
	- locked <0x00000005c13d7240> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000005c13d7270> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:760)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:401)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None
```

### Minimal yet complete reproducer code (or URL to code)
```java
this.eventLoopGroupSelector = new EpollEventLoopGroup(nettyServerConfig.getServerSelectorThreads(), new ThreadFactory() {
	private AtomicInteger threadIndex = new AtomicInteger(0);
	private int threadTotal = nettyServerConfig.getServerSelectorThreads();

	@Override
	public Thread newThread(Runnable r) {
		return new Thread(r, String.format("NettyServerEPOLLSelector_%d_%d", threadTotal, this.threadIndex.incrementAndGet()));
	}
});

this.eventLoopGroupBoss = new NioEventLoopGroup(1, new ThreadFactory() {
	private AtomicInteger threadIndex = new AtomicInteger(0);

	@Override
	public Thread newThread(Runnable r) {
		return new Thread(r, String.format("NettyBoss_%d", this.threadIndex.incrementAndGet()));
	}
});

ServerBootstrap childHandler = this.serverBootstrap.group(this.eventLoopGroupBoss, this.eventLoopGroupSelector)
	.channel(EpollServerSocketChannel.class)
	.option(ChannelOption.SO_BACKLOG, 1024)
	.option(ChannelOption.SO_REUSEADDR, true)
	.option(ChannelOption.SO_KEEPALIVE, false)
	.childOption(ChannelOption.TCP_NODELAY, true)
	.childOption(ChannelOption.SO_SNDBUF, nettyServerConfig.getServerSocketSndBufSize())
	.childOption(ChannelOption.SO_RCVBUF, nettyServerConfig.getServerSocketRcvBufSize())
	.localAddress(new InetSocketAddress(this.nettyServerConfig.getListenPort()))
	.childHandler(new ChannelInitializer<SocketChannel>() {
		@Override
		public void initChannel(SocketChannel ch) throws Exception {
			ch.pipeline()
				.addLast(defaultEventExecutorGroup, HANDSHAKE_HANDLER_NAME,
					new HandshakeHandler(TlsSystemConfig.tlsMode))
				.addLast(defaultEventExecutorGroup,
					new NettyEncoder(),
					new NettyDecoder(),
					new IdleStateHandler(0, 0, nettyServerConfig.getServerChannelMaxIdleTimeSeconds()),
					new NettyConnectManageHandler(),
					new NettyServerHandler()
				);
		}
	});
```

### Netty version
netty-all-4.0.42.Final.jar

### JVM version (e.g. `java -version`)
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

### OS version (e.g. `uname -a`)
Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Is it a bug or can I do something to avoid this happening again?
I have the application running in multiple environments, only one will take this sometimes

**Comment by normanmaurer** [comment]
Please upgrade to latest netty version (4.1.36.Final) + java version and see if the problem still persists.

**Comment by normanmaurer** [comment]
Let me close this and please reopen if you still think it is an issue after upgrading
