### ISSUE TITLE
SslContextBuilder is failing with Not supported using BoringSSL

### ISSUE THREAD

**Issue by rkapsi** [netty/netty#9147]
TCN w/ BoringSSL fails with the following error. The change was introduced with https://github.com/netty/netty-tcnative/commit/913df47adc07c9b8b083cdb92789356d3e864e55 but I'm not sure it's supposed to happen with `SslContextBuilder#keyManager(file, file, pass)`?!

```java
Caused by: java.lang.Exception: Not supported using BoringSSL
        at io.netty.internal.tcnative.SSLContext.setCertificateBio(Native Method) ~[netty-tcnative-boringssl-static-2.0.25.Final-osx-x86_64.jar:2.0.25.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.setKeyMaterial(ReferenceCountedOpenSslContext.java:787) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext.newSessionContext(ReferenceCountedOpenSslClientContext.java:104) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.handler.ssl.OpenSslClientContext.<init>(OpenSslClientContext.java:193) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:777) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:452) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
```

**Comment by normanmaurer** [comment]
@rkapsi what Netty version and tcnative version ?

**Comment by rkapsi** [comment]
@normanmaurer 2.0.25.Final (in this case the `netty-tcnative-boringssl-static` for `osx-x86_64` from Maven Central)

**Comment by normanmaurer** [comment]
and which netty version @rkapsi ?

**Comment by rkapsi** [comment]
`netty-all-4.1.36.Final`

**Comment by normanmaurer** [comment]
ah sorry... stupid me. I did not see it :( . Let me check.

**Comment by normanmaurer** [comment]
@rkapsi do you use `io.netty.handler.ssl.openssl.useKeyManagerFactory=false` by any chance ?

**Comment by rkapsi** [comment]
:eek: I do

```groovy
systemProperties['io.netty.handler.ssl.openssl.useKeyManagerFactory'] = 'false'
```

**Comment by normanmaurer** [comment]
@rkapsi I see... Can you remove this and see if it fixes your problem ? I think it should.... In the meantime let me come up with a fix.

**Comment by rkapsi** [comment]
@normanmaurer confirm, appear to fix it.

**Comment by normanmaurer** [comment]
@rkapsi after thinking a bit more about it I lean to just remove support for the system property. It was only present to allow easy switching to not using `KeyManagerFactory` when we introduce the feature at some point to give the user a chance to disable it if there is a bug. This should not be needed anymore at all as the feature is stable. 

WDYT ?

**Comment by rkapsi** [comment]
@normanmaurer SGTM

**Comment by normanmaurer** [comment]
@rkapsi https://github.com/netty/netty/pull/9162 PTAL
