### ISSUE TITLE
Failed to decode Websocket Frame due to size being too big on Java 12+

### ISSUE THREAD

**Issue by adriantodt** [netty/netty#9150]
### Expected behavior
Hi, I'm using a Netty-based Websocket Client [Catnip](https://github.com/mewna/catnip), which relies on Vert.x to connect to a WebSocket-based Service [Discord](https://discordapp.com).
On Java 11 and before, it connected just fine to the websocket.

### Actual behavior
On Java 12 (and also latest 13-ea builds), it errors with the following:

```
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Fail to unwrap network record
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: javax.net.ssl.SSLException: Fail to unwrap network record
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:470)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:295)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1332)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1227)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1274)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	... 17 common frames omitted
Caused by: java.lang.RuntimeException: javax.crypto.ShortBufferException: Output buffer too small
	at java.base/com.sun.crypto.provider.ChaCha20Cipher.engineDoFinal(ChaCha20Cipher.java:703)
	at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:826)
	at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2503)
	at java.base/sun.security.ssl.SSLCipher$T12CC20P1305ReadCipherGenerator$CC20P1305ReadCipher.decrypt(SSLCipher.java:2188)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decodeInputRecord(SSLEngineInputRecord.java:240)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:197)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
	at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
	... 25 common frames omitted
Caused by: javax.crypto.ShortBufferException: Output buffer too small
	at java.base/com.sun.crypto.provider.ChaCha20Cipher$EngineAEADDec.doFinal(ChaCha20Cipher.java:1360)
	at java.base/com.sun.crypto.provider.ChaCha20Cipher.engineDoFinal(ChaCha20Cipher.java:701)
	... 36 common frames omitted
```

The full log is: https://hasteb.in/alubotop.lua

### Steps to reproduce
I made a Gradle-based mini test with just the bare minimum required.

This bug was found while trying to connect to a Discord Bot, which requires you to create a account, which is free, and also create an application at https://discordapp.com/developers, which is also free.

The test code requires a bot token as the only parameter of the program.

Discord proxies itself through Cloudflare so there are probably better ways to set-up a way to reproduce, I just doesn't have the tools to do it.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/adriantodt/catnip-netty-failtest

### Netty version
Tested on Netty 4.1.30.Final and 4.1.36.Final

### JVM version (e.g. `java -version`)
On Linux:
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode)
```
On Windows:
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 12.0.1+12)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 12.0.1+12, mixed mode, sharing)
```

### OS version (e.g. `uname -a`)
Linux:
```
Linux 03f498af05e1 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 Linux
and
Linux aru.pw 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
Windows:
```
Microsoft Windows 10 Pro Version 1803 (OS Build 17134.706)
```

**Comment by adriantodt** [comment]
(Accidentally send an incomplete message, sorry. Filling the rest of it right now.)

**Comment by normanmaurer** [comment]
This looks like a JDK bug imho...

**Comment by adriantodt** [comment]
Tried reproducing with more JDKs available. Got the same exception for ZuluVM and OracleJDK on the same Ubuntu
```
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment Zulu12.2+3-CA (build 12.0.1+12)
OpenJDK 64-Bit Server VM Zulu12.2+3-CA (build 12.0.1+12, mixed mode, sharing)
```
```
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**Comment by normanmaurer** [comment]
@adriantodt like I said I think it is a JDK bug... could your provide SSL debug logs as requested here:

http://mail.openjdk.java.net/pipermail/security-dev/2019-May/019900.html

**Comment by adriantodt** [comment]
> @adriantodt like I said I think it is a JDK bug... could your provide SSL debug logs as requested here:
> 
> http://mail.openjdk.java.net/pipermail/security-dev/2019-May/019900.html

Executed the code with the debug properties as asked, got this log: https://hasteb.in/ucalevob.makefile

**Comment by normanmaurer** [comment]
@adriantodt thanks a lot!

**Comment by bradical** [comment]
I believe I may be running into the same issue with a failing ChaCha cipher. I read through: http://mail.openjdk.java.net/pipermail/security-dev/2019-May/019900.html but does anyone know if a bug report was ever filed? Also, was any workaround ever found such as disabling the use of that cipher? 

In my case, I'm using:

- OpenJDK 12.0.1
- `-Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2`

and seeing the error at the bottom. I have found that removing the param `jdk.tls.client.protocols` above seems to fix the issue but I've got it in place to [workaround another JDK bug with TLS v1.3](https://bugs.openjdk.java.net/browse/JDK-8221253)

```
EDT|TransportContext.java:312|Fatal (INTERNAL_ERROR): Fail to unwrap network record (
"throwable" : {
  java.lang.RuntimeException: javax.crypto.ShortBufferException: Output buffer too small
    at java.base/com.sun.crypto.provider.ChaCha20Cipher.engineDoFinal(ChaCha20Cipher.java:703)
    at java.base/javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:826)
    at java.base/javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730)
    at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2503)
    at java.base/sun.security.ssl.SSLCipher$T12CC20P1305ReadCipherGenerator$CC20P1305ReadCipher.decrypt(SSLCipher.java:2188)
    at java.base/sun.security.ssl.SSLEngineInputRecord.decodeInputRecord(SSLEngineInputRecord.java:240)
    at java.base/sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:197)
    at java.base/sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:160)
    at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
    at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:681)
    at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:636)
    at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:454)
    at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:433)
    at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634)
    at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.fill(SslConnection.java:681)
    at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.process(HttpReceiverOverHTTP.java:128)
    at org.eclipse.jetty.client.http.HttpReceiverOverHTTP.receive(HttpReceiverOverHTTP.java:73)
    at org.eclipse.jetty.client.http.HttpChannelOverHTTP.receive(HttpChannelOverHTTP.java:133)
    at org.eclipse.jetty.client.http.HttpConnectionOverHTTP.onFillable(HttpConnectionOverHTTP.java:155)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
    at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:291)
    at org.eclipse.jetty.io.ssl.SslConnection$3.succeeded(SslConnection.java:151)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
    at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
    at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
    at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
    at java.base/java.lang.Thread.run(Thread.java:835)
  Caused by: javax.crypto.ShortBufferException: Output buffer too small
    at java.base/com.sun.crypto.provider.ChaCha20Cipher$EngineAEADDec.doFinal(ChaCha20Cipher.java:1360)
    at java.base/com.sun.crypto.provider.ChaCha20Cipher.engineDoFinal(ChaCha20Cipher.java:701)
    ... 32 more}
```

**Comment by adriantodt** [comment]
cc http://mail.openjdk.java.net/pipermail/security-dev/2019-May/019956.html
> It did help some, yes.  I'm trying to get to a point where I can 
> reproduce the issue because it isn't immediately clear why that last 
> record is causing the ShortBufferException.  I'm hoping there's a way to 
> do that without having to hit that discord server.  Ideally I'd need to 
> turn this into some kind of regression test that more easily isolates 
> the issue.
> 
> --Jamil
> 
> On 5/23/2019 11:24 AM, Norman Maurer wrote:
> > Hi there,
> > 
> > 
> > Did the debug log help at all or should I try to gather more 
> > informations from the user ?
> >
> > Bye
> > Norman

Information that might be useful:
- I'm getting the ShortBufferException on a websocket connection (that's kinda obvious on the log tho)
- the server sends JSON of easily 1 MB in size each
- there is a [event flowchart for the websocket I'm trying to connect](https://s.gus.host/flowchart.png), if that's any useful

**Comment by bradical** [comment]
Interesting. We're definitely seeing a pretty large response from the server as well in our case.

Is disabling that specific cipher an option for you? We ended supplementing our `java.security` file with:

```
jdk.tls.disabledAlgorithms=<other stuff...> CHACHA20-POLY1305
```

**Comment by adriantodt** [comment]
> Interesting. We're definitely seeing a pretty large response from the server as well in our case.
> 
> Is disabling that specific cipher an option for you? We ended supplementing our `java.security` file with:
> 
> ```
> jdk.tls.disabledAlgorithms=<other stuff...> CHACHA20-POLY1305
> ```

This worked as a workaround by now. Managed to connect to the websocket and get to working state. Apparently everything boils down to the faulty TLSv1.3 implementation -.-

**Comment by normanmaurer** [comment]
I will update here once I hear back from OpenJDK folks.

**Comment by bradical** [comment]
> This worked as a workaround by now. Managed to connect to the websocket and get to working state. Apparently everything boils down to the faulty TLSv1.3 implementation -.-

Glad to hear that worked for you. Thanks @timreilly for the suggestion there.

> I will update here once I hear back from OpenJDK folks.

Thanks @normanmaurer!

**Comment by normanmaurer** [comment]
A patch was proposed for OpenJDK that should fix it:

https://mail.openjdk.java.net/pipermail/security-dev/2019-August/020535.html

Will close the issue as it is not a Netty issue but a openJDK one.
