### ISSUE TITLE
Netty SSL handshake timeout intermittently 

### ISSUE THREAD

**Issue by SuganyaRajendran** [netty/netty#9266]
I have netty server that uses bogus certificate. Below is the code that I used, 

```
SslContext sslContext =  SslContextBuilder.forServer(certStream, keyStream)..protocols("TLSv1.1”).build();
SslHandler sslHandler = sslContext.newHandler(ctx.alloc());
ctx.pipeline().addFirst(HandlerNames.SSL_HANDLER, sslHandler);
```

SSL handshake is success 3 out 10 times, and it fails remaining time with below error. 

```
javax.net.ssl.SSLException: handshake timed out
	at io.netty.handler.ssl.SslHandler.handshake(...)(Unknown Source)
```

I have enabled `javax.net.debug` to `all` to enable debug logs. For success request, I see initial ClientHello, ServerHello, Key/Certificate exchange, etc. For failed request, I see only below stack trace with above error, 

```
javax.net.ssl|ERROR|14|nioEventLoopGroup-3-2|2019-06-21 12:17:13.561 PDT|TransportContext.java:313|Fatal (INTERNAL_ERROR): closing inbound before receiving peer's close_notify (
"throwable" : {
  javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
  	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
  	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:255)
  	at java.base/sun.security.ssl.SSLEngineImpl.closeInbound(SSLEngineImpl.java:724)
  	at io.netty.handler.ssl.SslHandler.setHandshakeFailure(SslHandler.java:1776)
  	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1073)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
  	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:236)
  	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1403)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:257)
  	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:243)
  	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:912)
  	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827)
  	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
  	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
  	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
  	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
  	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  	at java.base/java.lang.Thread.run(Thread.java:834)}

)
```

However, I am able to see ClientHello message in WireShark for failure requests. Server acks the client message and the next packet is FIN packet to close the connection due to handshake timeout. 

I tried initializing server context with list of ciphers that client supports (sent in client hello message), didnt help much. If i run the connection (Requests are sequential with delay as well) on loop, it success 30% times and fails remaining.

I am looking to understand if this is some issue being faced recently by others. 

### Netty version

Netty 4.1.36.Final

### JVM version (e.g. `java -version`)

openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Corretto-11.0.3.7.1 (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.3.7.1 (build 11.0.3+7-LTS, mixed mode)

### OS version (e.g. `uname -a`)

MAC and Linux

**Comment by normanmaurer** [comment]
without more infos it is hard to say anything... are you sure you not block the EventLoop somehow ?

**Comment by normanmaurer** [comment]
Closing as the reporter did not provide more infos

**Comment by ashok003** [comment]
@SuganyaRajendran , were you able to resolve this issue?

**Comment by setu123** [comment]
Having same issue with Netty 4.1.31.Final. @SuganyaRajendran , were you able to resolve this issue?
