### ISSUE TITLE
Wrong websocket status code

### ISSUE THREAD

**Issue by KevinBlandy** [netty/netty#9300]
### Overview
I am trying to send a message larger than `maxFrameSize` to the server.However, the status code in the client close event is not `WebSocketCloseStatus.MESSAGE_TOO_BIG`
### Client
```java
let webSocket = new WebSocket('ws://localhost:1024/channel?_token=123456');
let count = 0;
webSocket.onopen = (event) => {
	console.log('连接打开', event);
	// Message length greater than 10 bytes
	let message = {
		'flag':count ++,
		'time':new Date().getTime()
	}
	webSocket.send(JSON.stringify(message))
}
webSocket.onclose = (event) => {
	console.log('连接断开', event);
}
```
#### ClonseEvent
![image](https://user-images.githubusercontent.com/17979625/60378684-976fd900-9a58-11e9-9418-32b641c5f8cc.png)

### Server
```java
channelPipeline.addLast(new HttpServerCodec());
channelPipeline.addLast(new ChunkedWriteHandler());
channelPipeline.addLast(new HttpObjectAggregator(65536));
channelPipeline.addLast(new TokenValidateHandler(this.websocketPath));
channelPipeline.addLast(new WebSocketServerCompressionHandler());

// maxFrameSize = 10
channelPipeline.addLast(new WebSocketServerProtocolHandler(this.websocketPath, null, true, 10, false, true, true, 20000L));
channelPipeline.addLast(new HttpHandler());

//TODO 业务 handler，单独使用业务线程池
channelPipeline.addLast(new WebSocketFrameHandler());
channelPipeline.addLast(new ExceptionHandler());
```
#### Debug Info
![image](https://user-images.githubusercontent.com/17979625/60378705-0cdba980-9a59-11e9-9e9a-8e24dcc5bdaa.png)

> It seems that the response to the client's `CloseWebSocketFrame`  is correct.

#### Exception Stack
```java
io.netty.handler.codec.http.websocketx.CorruptedWebSocketFrameException: Max frame length of 10 has been exceeded.
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.protocolViolation(WebSocket08FrameDecoder.java:426)
	at io.netty.handler.codec.http.websocketx.WebSocket08FrameDecoder.decode(WebSocket08FrameDecoder.java:286)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:500)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:439)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

### Netty version
4.1.37.Final

**Comment by normanmaurer** [comment]
@ursaj can you have look ?

**Comment by ursaj** [comment]
hi, @normanmaurer 

as I remember - there is still a bug with handlers ordering and violation exceptions handling in `WebSocket08FrameDecoder.protocolViolation()`:

        if (ctx.channel().isActive() && config.closeOnProtocolViolation()) {
            ...
            ctx.writeAndFlush(closeMessage).addListener(ChannelFutureListener.CLOSE);
        }
        throw ex;
    }

Close message is NOT actually passed into encoder - it is higher in pipeline (see `WebSocketServerHandshaker.handshake()`).
This is why channel is closed with generic exception...

I did NOT find any proper solution for this bug (yet), so disabled this feature in my project through config:

    config = WebSocketDecoderConfig.newBuilder()
        .closeOnProtocolViolation(false)

**Comment by amizurov** [comment]
@ursaj Hi, if I right understood you, when `closeOnProtocolViolation(false)` is set then throws exception and we should manually handle `DecoderException` and close channel  in properly way ?  Maybe we can change `ctx.writeAndFlash(..)` to ctx.channel().writeAndFlush() in ` protocolViolation(ChannelHandlerContext ctx, ByteBuf in, CorruptedWebSocketFrameException ex)` this is add some overhead but rethrowing exception also is not free.

**Comment by ursaj** [comment]
it will solve handlers ordering problem. however `ctx.channel().writeAndFlush()` is not something expected by upper (business-logic) handlers. it would bring side-effects on existing code.

**Comment by normanmaurer** [comment]
I agree with @ursaj here... calling `ctx.channel().writeAndFlush(...)` may produce problems.

**Comment by normanmaurer** [comment]
@KevinBlandy @ursaj @amizurov I think this should be fixed by https://github.com/netty/netty/pull/9386. Please verify

**Comment by amizurov** [comment]
@normanmaurer Thanks, work fine on our project.
