### ISSUE TITLE
NullPointerException at line 179 in Http2MultiplexHandler.java

### ISSUE THREAD

**Issue by ljnelson** [netty/netty#9314]
Hello; thanks for a great project.

In accordance with the [upgrade advice found on the wiki](https://netty.io/news/2019/06/28/4-1-37-Final.html), I introduced the usage of `Http2MultiplexHandler` in my codebase.

I now get this in my logs when I issue a request that upgrades from HTTP to HTTP/2 (via `curl --http2`):

```
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.NullPointerException
	at io.netty.handler.codec.http2.Http2MultiplexHandler.channelRead(Http2MultiplexHandler.java:179)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.http2.Http2FrameCodec.onHttp2Frame(Http2FrameCodec.java:632)
[snip]
```

I'm happy to try to provide more details.  I'm sure I'm doing something wrong, but I don't entirely know what.  My end goal in case it helps is to allow my server to handle HTTP, HTTP/2, upgrade scenarios, prior knowledge, etc. etc. all-in-one.

**Comment by ljnelson** [comment]
My code looks like this:

```
final HttpServerCodec httpServerCodec = new HttpServerCodec();
final MyHandler myHandler = new MyHandler();
final HttpServerUpgradeHandler httpServerUpgradeHandler =
  new HttpServerUpgradeHandler(httpServerCodec,
                               protocolName -> {
                                 final UpgradeCodec returnValue;
                                 if (AsciiString.contentEquals(Http2CodecUtil.HTTP_UPGRADE_PROTOCOL_NAME, protocolName)) {
                                   final Http2FrameCodec http2FrameCodec = Http2FrameCodecBuilder.forServer().build();
                                   returnValue = new Http2ServerUpgradeCodec(http2FrameCodec, new Http2MultiplexHandler(myHandler));
                                 } else {
                                   returnValue = null;
                                 }
                                 return returnValue;
                               },
                               maxIncomingContentLength);

final CleartextHttp2ServerUpgradeHandler cleartextHttp2ServerUpgradeHandler =
  new CleartextHttp2ServerUpgradeHandler(httpServerCodec,
                                         httpServerUpgradeHandler,
                                         myHandler);
channelPipeline.addLast(cleartextHttp2ServerUpgradeHandler);
```
This code worked fine using the deprecated `Http2MultiplexCodecBuilder` class, i.e. the ["old" code style referenced in the wiki](https://netty.io/news/2019/06/28/4-1-37-Final.html).

**Comment by normanmaurer** [comment]
@ljnelson this looks like a bug... let me investigate and fix it.

**Comment by normanmaurer** [comment]
@ljnelson thanks for reporting... fixed by https://github.com/netty/netty/pull/9318
