### ISSUE TITLE
NullPointerException in FlowControlHandler

### ISSUE THREAD

**Issue by graemerocher** [netty/netty#9319]
The following change in 4.1.37 causes a NPE in `FlowControlHandler`:

https://github.com/netty/netty/commit/2c99fc0f1290c65685c5036fdc9884921823ad7d#diff-bb753cb6291385d58a60bc0f59d5402d

The NPE stack:

```
java.lang.NullPointerException: null
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:193)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)

```

### Expected behavior

FlowControlHandler should not fail with a NPE.

### Actual behavior

FlowControlHandler sometimes fails with a NPE

### Steps to reproduce

Hard to come up with a reproducer, but the issue manifests if you upgrade to Netty 4.1.37 in a Micronaut application.

Related discussion can be found at https://github.com/micronaut-projects/micronaut-core/pull/1802

### Netty version

4.1.37

### JVM version (e.g. `java -version`)

Any

### OS version (e.g. `uname -a`)

Any

**Comment by normanmaurer** [comment]
Alright I think I know what is going on... writing a unit test now.
