### ISSUE TITLE
The CompositeByteBuf of the CompositeByteBuf class (ByteBufAllocator alloc, boolean direct, int maxNumComponents, ByteBuf... buffers) does not verify that buffers have a length of 0.

### ISSUE THREAD

**Issue by xiaoheng1** [netty/netty#9326]
i use netty 4.1.34.

the source code in the CompositeByteBuf class：

```
public CompositeByteBuf(ByteBufAllocator alloc, boolean direct, int maxNumComponents, ByteBuf... buffers) {
        this(alloc, direct, maxNumComponents, buffers, 0);
    }

    CompositeByteBuf(ByteBufAllocator alloc, boolean direct, int maxNumComponents,
            ByteBuf[] buffers, int offset) {
        this(alloc, direct, maxNumComponents, buffers.length - offset);

        addComponents0(false, 0, buffers, offset);
        consolidateIfNeeded();
        setIndex0(0, capacity());
    }
```

test case1：
```
@Test
    public void test(){
        ByteBuf[] buffers = new ByteBuf[0];
        CompositeByteBuf byteBufs = new CompositeByteBuf(ByteBufAllocator.DEFAULT, false, 16, buffers);
        System.out.println(byteBufs);
    }
```
error info:
java.lang.AssertionError
	at io.netty.buffer.CompositeByteBuf.shiftComps(CompositeByteBuf.java:2257)
	at io.netty.buffer.CompositeByteBuf.addComponents0(CompositeByteBuf.java:375)
	at io.netty.buffer.CompositeByteBuf.<init>(CompositeByteBuf.java:98)
	at io.netty.buffer.CompositeByteBuf.<init>(CompositeByteBuf.java:88)
	at io.netty.buffer.CompositeByteBufTest.test(CompositeByteBufTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

In my opinion, it should be implemented like public CompositeByteBuf(
             ByteBufAllocator alloc, boolean direct, int maxNumComponents, Iterable<ByteBuf> buffers) The processing logic of the method.

**Comment by normanmaurer** [comment]
This was fixed ... Please update to latest Netty release (4.1.37.Final)

**Comment by xiaoheng1** [comment]
ok，thanks!
