### ISSUE TITLE
NullPointerException in HttpPostRequestEncoder encodeNextChunkUrlEncoded

### ISSUE THREAD

**Issue by emlittleworth** [netty/netty#9351]
### Expected behavior
No `NullPointerException`.

### Actual behavior
When given a certain input size, the `encodeNextChunkUrlEncoded` throws a `NullPointerException` in the following line
```
if (currentBuffer.readableBytes() >= HttpPostBodyUtil.chunkSize) {
```
because the `currentBuffer` is null (which was set to the `delimiter` which was null). There seems to have been a similar issue in the past: https://github.com/netty/netty/issues/5478.

### Steps to reproduce / Minimal yet complete reproducer code (or URL to code)
```
@Test
public void testWriteChunkedContent() throws Exception {
    EmbeddedChannel ch = new EmbeddedChannel(new ChunkedWriteHandler());
    HttpRequest req = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, "/");
    HttpPostRequestEncoder encoder = new HttpPostRequestEncoder(req, false);

    int length = 8077 + 8096;
    char[] array = new char[length];
    Arrays.fill(array, 'a');
    String longText = new String(array);

    encoder.addBodyAttribute("data", longText);
    encoder.addBodyAttribute("moreData", "abcd");

    HttpRequest finalRequest = encoder.finalizeRequest();

    ch.writeOutbound(finalRequest);
    ch.writeOutbound(encoder);
    ch.flushOutbound();
}
```

### Netty version
4.1

### JVM version (e.g. `java -version`)
java version "1.8.0_111"

### OS version (e.g. `uname -a`)
Darwin Kernel Version 18.6.0

**Comment by normanmaurer** [comment]
@emlittleworth what exact Netty version ?

**Comment by normanmaurer** [comment]
Also can you please provide the full stack trace.

**Comment by emlittleworth** [comment]
Hi, sure it's 4.1.35.
```
java.lang.NullPointerException
	at io.netty.handler.codec.http.multipart.HttpPostRequestEncoder.encodeNextChunkUrlEncoded(HttpPostRequestEncoder.java:986)
	at io.netty.handler.codec.http.multipart.HttpPostRequestEncoder.nextChunk(HttpPostRequestEncoder.java:1077)
	at io.netty.handler.codec.http.multipart.HttpPostRequestEncoder.readChunk(HttpPostRequestEncoder.java:1044)
	at io.netty.handler.codec.http.multipart.HttpPostRequestEncoder.readChunk(HttpPostRequestEncoder.java:67)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:242)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:135)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741)
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727)
	at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:978)
	at io.netty.channel.AbstractChannel.flush(AbstractChannel.java:241)
	at io.netty.channel.embedded.EmbeddedChannel.flushOutbound0(EmbeddedChannel.java:473)
	at io.netty.channel.embedded.EmbeddedChannel.writeOutbound(EmbeddedChannel.java:412)
	at io.netty.handler.codec.http.multipart.HttpPostRequestEncoderTest.testWriteChunkedContent(HttpPostRequestEncoderTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```

**Comment by normanmaurer** [comment]
@emlittleworth I see.. interested to provide a PR to fix it ?

**Comment by emlittleworth** [comment]
Sure, I'll return `null` for this case.
