### ISSUE TITLE
DefaultDnsRecordDecoder failed

### ISSUE THREAD

**Issue by leotu** [netty/netty#9365]
Cannot found a good way to reproduct it

```java
22:52:28.047 [vert.x-eventloop-thread-0] WARN  [Test] [io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler:1311,exceptionCaught()] [id: 0xcbd9e081, L:/0:0:0:0:0:0:0:0:56705] Unexpected exception: 
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(511) + length(2) exceeds writerIndex(512): PooledUnsafeDirectByteBuf(ridx: 511, widx: 512, cap: 4096)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(511) + length(2) exceeds writerIndex(512): PooledUnsafeDirectByteBuf(ridx: 511, widx: 512, cap: 4096)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1451)
	at io.netty.buffer.AbstractByteBuf.readShort(AbstractByteBuf.java:757)
	at io.netty.buffer.AbstractByteBuf.readUnsignedShort(AbstractByteBuf.java:773)
	at io.netty.handler.codec.dns.DefaultDnsRecordDecoder.decodeRecord(DefaultDnsRecordDecoder.java:61)
	at io.netty.handler.codec.dns.DnsResponseDecoder.decodeRecords(DnsResponseDecoder.java:88)
	at io.netty.handler.codec.dns.DnsResponseDecoder.decode(DnsResponseDecoder.java:66)
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:58)
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:30)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	... 16 common frames omitted

```

### Netty version
4.1.37.Final

### JVM version (e.g. `java -version`)
Java SE 8 [1.8.0_212]

### OS version (e.g. `uname -a`)
Mac OS 10.13.6

**Comment by normanmaurer** [comment]
I am pretty sure that is related to a truncated datagram packet which can alway happen.

**Comment by normanmaurer** [comment]
@leotu please let me know if you ever find a query that will reproduce it ...

**Comment by normanmaurer** [comment]
@leotu finally understood what was wrong... See https://github.com/netty/netty/pull/9468
