### ISSUE TITLE
Seeing HttpDataFrame's (and maybe others) getting out of order in AbstractHttp2StreamChannel

### ISSUE THREAD

**Issue by bryce-anderson** [netty/netty#9387]
### Expected behavior

All stream header and data frames being pushed down the stream pipeline in the order received.

### Actual behavior

Some frames are pushed down the pipeline while messages are still in the internal `inboundBuffer`.

### Netty version

4.1.35.Final and 4.1.37.Final, likely others as well.

**Comment by bryce-anderson** [comment]
When I put the following snipped at the head of the `doRead0` method [here](https://github.com/netty/netty/blob/netty-4.1.37.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java#L843)
```java
if (frame instanceof Http2DataFrame) {
                Http2DataFrame f = (Http2DataFrame) frame;
                dataBytes += f.content().readableBytes();
                if (f.isEndStream() && dataBytes != 1024 * 10) {
                    Exception ex = new Exception("Received short message. Only " +
                        dataBytes + " received. Stream id: " + f.stream().id() +
                        ". Buffer contents: " + bufferContents());
                    logger.error(ex);
                }
            }
```
and run a throughput test that sends exactly 10 KB of data I see log entries like this:
```
W 0717 19:09:21.144 THREAD48: Failed to read entire message. Remaining bytes: 4096W 0717 19:09:21.144 THREAD48: Failed to read entire message. Remaining bytes: 4096java.lang.Exception: Received short message. Only 6144 received. Stream id: 95907. Buffer contents: [, DefaultHttp2DataFrame(stream=95907, content=UnpooledSlicedByteBuf(ridx: 0, widx: 1024, cap: 1024/1024, unwrapped: PooledUnsafeDirectByteBuf(ridx: 31021, widx: 31021, cap: 65536)), endStream=false, padding=0), DefaultHttp2DataFrame(stream=95907, content=UnpooledSlicedByteBuf(ridx: 0, widx: 1024, cap: 1024/1024, unwrapped: PooledUnsafeDirectByteBuf(ridx: 31021, widx: 31021, cap: 65536)), endStream=false, padding=0), DefaultHttp2DataFrame(stream=95907, content=UnpooledSlicedByteBuf(ridx: 0, widx: 1024, cap: 1024/1024, unwrapped: PooledUnsafeDirectByteBuf(ridx: 32768, widx: 32768, cap: 32768)), endStream=false, padding=0), DefaultHttp2DataFrame(stream=95907, content=UnpooledSlicedByteBuf(ridx: 0, widx: 1024, cap: 1024/1024, unwrapped: PooledUnsafeDirectByteBuf(ridx: 32768, widx: 32768, cap: 32768)), endStream=false, padding=0)] at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$Http2ChannelUnsafe.doRead0(AbstractHttp2StreamChannel.java:864) at io.netty.handler.codec.http2.AbstractHttp2StreamChannel.fireChildRead(AbstractHttp2StreamChannel.java:535) at io.netty.handler.codec.http2.Http2MultiplexCodec.onHttp2Frame(Http2MultiplexCodec.java:146) at io.netty.handler.codec.http2.Http2FrameCodec$FrameListener.onDataRead(Http2FrameCodec.java:581) at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:266) at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:422) at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251) at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160) at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:148) at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:378) at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:438) at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:500) at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:439) at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) at io.netty.handler.codec.http2.Http2MultiplexCodec.channelRead(Http2MultiplexCodec.java:273) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelRead(ChannelRequestStatsHandler.scala:48) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelRead(ChannelStatsHandler.scala:155) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697) at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632) at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549) at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23) at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) at java.lang.Thread.run(Thread.java:748) 
```

**Comment by bryce-anderson** [comment]
Other notable observation: this only happens when autoRead is disabled. Somewhere along the way I believe we're corrupting the read state machine and hitting the assert [here](https://github.com/netty/netty/blob/netty-4.1.37.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java#L531). If we add that assert block as a `&&` to the `if` statement above eg
```java
} else if (readStatus != ReadStatus.IDLE &&
            (inboundBuffer == null || inboundBuffer.isEmpty())) {
```
I dont see the error, though we're probably getting to a place where we have a read interest and data in the queue but nothing is happening.

**Comment by bryce-anderson** [comment]
The core problem is that if you're in the `IN_PROGRESS` state, do to say a `read()` call with data in the queue, your handler calls `ctx.read()`, you transition to the `REQUESTED` state. However, the loop can terminate [here](https://github.com/netty/netty/blob/netty-4.1.37.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java#L785) (especially if we're not set to autoRead) with data still in the queue. We then fall down to the `notifyReadComplete` method and transition back to `IN_PROGRESS` [here](https://github.com/netty/netty/blob/netty-4.1.37.Final/codec-http2/src/main/java/io/netty/handler/codec/http2/AbstractHttp2StreamChannel.java#L824) with data in the queue. What we need to do is manage the case where a `doRead0` call triggered a call to `read()` and this a transition to the `REQUESTED` state by continuing regardless of what the alloc handle says and retransitioning back to `IN_PROGRESS`. Of course there may be other ways.

I have a patch I'm testing and then I'll put it up.

**Comment by bryce-anderson** [comment]
My diff will take a bit more work. We have the same problem if `.read()` is called multiple times within a `.fireChannelReadComplete()` call.

**Comment by bryce-anderson** [comment]
This is a commit looks like it fixes it but the state machine is kinda out of control at this point. https://github.com/bryce-anderson/netty/commit/9b8d7053ee516da4a08e648dfcd4417728fdff53

**Comment by normanmaurer** [comment]
@bryce-anderson thanks a lot... I will check if I can come up with something based on this today

**Comment by normanmaurer** [comment]
@bryce-anderson PTAL https://github.com/netty/netty/pull/9389
