### ISSUE TITLE
failed to create a child event loop, Too many open files

### ISSUE THREAD

**Issue by dsreddy2384** [netty/netty#9413]
### Expected behavior
Same code works on seperate jvm, so i expect it to create the connections to redis
### Actual behavior
Exception thrown - failed to create a child event loop, Too many open files
### Netty version
4.1.13
### JVM version (e.g. `java -version`)
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)

### OS version (e.g. `uname -a`)
SunOS scr2t2z1 5.11 ssc-jidr-on-11.3-sru36.7 sun4v sparc sun4v 

2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender) java.lang.IllegalStateException: failed to create a child event loop
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEven
tExecutorGroup.java:88)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEven
tExecutorGroup.java:58)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.j
ava:52)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:43)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.client.RedisClientConfig.<init>(RedisClientConfig.java:42)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.connection.MasterSlaveConnectionManager.createRedisConfig(Master
SlaveConnectionManager.java:363)
2019-07-29 13:40:40,399 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.cluster.ClusterConnectionManager.createRedisConfig(ClusterConnec
tionManager.java:159)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlave
ConnectionManager.java:358)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.connection.MasterSlaveConnectionManager.createClient(MasterSlave
ConnectionManager.java:345)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.connection.MasterSlaveEntry.addSlave(MasterSlaveEntry.java:318)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.connection.MasterSlaveEntry.initSlaveBalancer(MasterSlaveEntry.j
ava:95)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.cluster.ClusterConnectionManager$2$1.operationComplete(ClusterCo
nnectionManager.java:263)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:5
07)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:
500)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.jav
a:479)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:4
20)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.misc.RedissonPromise.trySuccess(RedissonPromise.java:78)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.client.handler.CommandDecoder.handleResult(CommandDecoder.java:3
22)
2019-07-29 13:40:40,400 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:261)
2019-07-29 13:40:40,401 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at org.redisson.client.handler.CommandDecoder.decode(CommandDecoder.java:103)
2019-07-29 13:40:40,401 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(By
teToMessageDecoder.java:489)
2019-07-29 13:40:40,401 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:367)
2019-07-29 13:40:40,401 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.
java:265)
2019-07-29 13:40:40,401 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChan
nelHandlerContext.java:362)
2019-07-29 13:40:40,401 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChan
nelHandlerContext.java:348)
2019-07-29 13:40:40,401 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChanne
lHandlerContext.java:340)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandl
erAdapter.java:86)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChan
nelHandlerContext.java:362)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChan
nelHandlerContext.java:348)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChanne
lHandlerContext.java:340)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandl
erAdapter.java:86)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChan
nelHandlerContext.java:362)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChan
nelHandlerContext.java:348)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChanne
lHandlerContext.java:340)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChanne
lPipeline.java:1334)
2019-07-29 13:40:40,402 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChan
nelHandlerContext.java:362)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChan
nelHandlerContext.java:348)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipelin
e.java:926)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByt
eChannel.java:134)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.j
ava:579)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExe
cutor.java:858)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(De
faultThreadFactory.java:138)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at java.lang.Thread.run(Thread.java:748)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender) Caused by: io.netty.channel.ChannelException: failed to open a new selector
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
2019-07-29 13:40:40,403 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEven
tExecutorGroup.java:84)
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      ... 50 common frames omitted
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender) Caused by: java.io.IOException: Too many open files
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at sun.nio.ch.IOUtil.makePipe(Native Method)
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at sun.nio.ch.DevPollSelectorImpl.<init>(DevPollSelectorImpl.java:68)
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at sun.nio.ch.DevPollSelectorProvider.openSelector(DevPollSelectorProvider.java:
36)
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
2019-07-29 13:40:40,404 INFO  [stdout] (AsyncAppender-Worker-asyncConsoleAppender)      ... 54 common frames omitted

**Comment by ninja-** [comment]
https://docs.oracle.com/cd/E19455-01/806-1075/msgs-2152/index.html

**Comment by dsreddy2384** [comment]
We have discovered the issue with swap memory was not capped on the server, after  capping the memory it is resolved.
