### ISSUE TITLE
My Android App，show this log-----""

### ISSUE THREAD

**Issue by cs1991** [netty/netty#9445]
### JVM version   1.8

2019-08-13 10:18:27.224 [pool-7-thread-1] DEBUG i.n.c.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
2019-08-13 10:18:27.368 [pool-7-thread-1] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
2019-08-13 10:18:27.369 [pool-7-thread-1] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
2019-08-13 10:18:27.430 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
2019-08-13 10:18:27.431 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent0 - Platform: Android
2019-08-13 10:18:27.431 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent0 - Java version: 6
2019-08-13 10:18:27.432 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent0 - Platform: Android
2019-08-13 10:18:27.433 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
2019-08-13 10:18:27.435 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: unavailable
java.lang.NoSuchMethodException: copyMemory [class java.lang.Object, long, class java.lang.Object, long, long]
	at java.lang.Class.getDeclaredMethod(Class.java:635)
	at io.netty.util.internal.PlatformDependent0$2.run(PlatformDependent0.java:132)
	at java.security.AccessController.doPrivileged(AccessController.java:45)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:128)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:214)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:82)
	at io.netty.channel.nio.NioEventLoop.newTaskQueue0(NioEventLoop.java:284)
	at io.netty.channel.nio.NioEventLoop.newTaskQueue(NioEventLoop.java:155)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:137)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:138)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:88)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:83)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:64)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:44)
	at com.tyky.zhengwu.terminal.service.NettyService$2.run(NettyService.java:84)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
2019-08-13 10:18:27.437 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
2019-08-13 10:18:27.438 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent - sun.misc.Unsafe: unavailable (Android)
2019-08-13 10:18:27.440 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent - maxDirectMemory: 536870912 bytes (maybe)
2019-08-13 10:18:27.441 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.tmpdir: /data/data/com.tyky.zhengwu.terminal/cache (java.io.tmpdir)
2019-08-13 10:18:27.447 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
2019-08-13 10:18:27.448 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
2019-08-13 10:18:27.449 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: true
2019-08-13 10:18:27.450 [pool-7-thread-1] INFO  i.n.util.internal.PlatformDependent - Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system instability.
2019-08-13 10:18:27.451 [pool-7-thread-1] DEBUG i.n.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: unavailable
2019-08-13 10:18:27.461 [pool-7-thread-1] TRACE io.netty.channel.nio.NioEventLoop - failed to instrument a special java.util.Set into: java.nio.SelectorImpl@81b16e8
java.lang.ClassNotFoundException: sun.nio.ch.SelectorImpl
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:308)
	at io.netty.channel.nio.NioEventLoop$3.run(NioEventLoop.java:191)
	at java.security.AccessController.doPrivileged(AccessController.java:45)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:187)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:146)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:138)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:37)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:88)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:83)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:64)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:44)
	at com.tyky.zhengwu.terminal.service.NettyService$2.run(NettyService.java:84)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.ClassNotFoundException: Didn't find class "sun.nio.ch.SelectorImpl" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
	... 20 common frames omitted
	Suppressed: java.lang.ClassNotFoundException: sun.nio.ch.SelectorImpl
		at java.lang.Class.classForName(Native Method)
		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
		... 21 common frames omitted
	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
2019-08-13 10:18:27.465 [pool-7-thread-1] TRACE io.netty.channel.nio.NioEventLoop - failed to instrument a special java.util.Set into: java.nio.SelectorImpl@3a784c3d

**Comment by medusar** [comment]
You can change your log level to `info` to see if these error logs still exist, error logs in debug mode sometimes do not matter.

**Comment by normanmaurer** [comment]
Closing as no response from reporter
