### ISSUE TITLE
Logstash log showing "error:1e00007d:Cipher functions:OPENSSL_internal:INVALID_NONCE"

### ISSUE THREAD

**Issue by AnitaNayak** [netty/netty#9491]
Hi, we are testing logstash 6.6.1 (netty-tcnative version: netty-tcnative-boringssl-static-2.0.17.Final-linux-s390_64.jar ) on s390x platform (Linux on Z/s390x).

After starting the ELK 6.6.1 stack, everything seems working fine and we can see logs on Kibana UI, but logstash log has following entries from time to time:
```
[2019-07-07T12:11:35,834][INFO ][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.79.173:48148] Handling exception: error:1e00007d:Cipher functions:OPENSSL_internal:INVALID_NONCE
[2019-07-07T12:11:35,834][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
javax.net.ssl.SSLException: error:1e00007d:Cipher functions:OPENSSL_internal:INVALID_NONCE
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:895) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:882) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.wrap(ReferenceCountedOpenSslEngine.java:824) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at javax.net.ssl.SSLEngine.wrap(SSLEngine.java:509) ~[?:1.8.0_212]
at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:1019) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:825) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.handler.ssl.SslHandler.wrapAndFlush(SslHandler.java:793) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:774) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.channel.AbstractChannelHandlerContext.access$1500(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.channel.AbstractChannelHandlerContext$16.run(AbstractChannelHandlerContext.java:756) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) [netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```
After turning on org.logstash.beats.BeatsHandler debug level tracing, we can see following pattern:

(normal pipeline processing...)
```
[2019-07-07T21:09:38,423][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.10.165:34646] Sending a new message for the listener, sequence: 73
[2019-07-07T21:09:38,427][DEBUG][org.logstash.beats.BeatsHandler] 5cc2452e: batches pending: false
[2019-07-07T21:09:38,429][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.10.165:34646] Received a new payload
[2019-07-07T21:09:38,430][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.10.165:34646] Sending a new message for the listener, sequence: 1
[2019-07-07T21:09:38,434][DEBUG][org.logstash.beats.BeatsHandler] 5cc2452e: batches pending: false
[2019-07-07T21:09:38,436][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.79.173:54172] Handling exception: error:1e00007d:Cipher functions:OPENSSL_internal:INVALID_NONCE
javax.net.ssl.SSLException: error:1e00007d:Cipher functions:OPENSSL_internal:INVALID_NONCE
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:895) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
(similar call stack like above)
...
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

[2019-07-07T21:09:38,439][INFO ][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.79.173:54172] Handling exception: error:1e00007d:Cipher functions:OPENSSL_internal:INVALID_NONCE
[2019-07-07T21:09:38,440][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.10.165:34646] Received a new payload
[2019-07-07T21:09:38,440][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.10.165:34646] Sending a new message for the listener, sequence: 1
[2019-07-07T21:09:38,439][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
javax.net.ssl.SSLException: error:1e00007d:Cipher functions:OPENSSL_internal:INVALID_NONCE
at io.netty.handler.ssl.ReferenceCountedOpenSslEngine.shutdownWithError(ReferenceCountedOpenSslEngine.java:895) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
(similar call stack like above)
...
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

[2019-07-07T21:09:38,444][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.10.165:34646] Sending a new message for the listener, sequence: 2
[2019-07-07T21:09:38,448][DEBUG][org.logstash.beats.BeatsHandler] 5cc2452e: batches pending: false
[2019-07-07T21:09:38,727][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.79.173:53042] Received a new payload

(started new sequence...)

[2019-07-07T21:09:38,727][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.79.173:53042] Sending a new message for the listener, sequence: 1
[2019-07-07T21:09:38,731][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.79.173:53042] Sending a new message for the listener, sequence: 2
[2019-07-07T21:09:38,734][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.79.146:5044, remote: 10.1.79.173:53042] Sending a new message for the listener, sequence: 3
```
It looks like that logstash recovered the exception and resumes processing logs from filebeat (version is 6.6.1)

Any idea what's going on here? How can we find the root cause of this issue?

Thank you.

**Comment by AnitaNayak** [comment]
After enabled, `log.level: debug` in logstash yaml file, got below additional message:
```
[2019-08-21T16:46:43,056][DEBUG][org.logstash.dissect.Dissector] Event after dissection {"event"=>{"input"=>{"type"=>"log"}, "host"=>{"name"=>"logging-elk-filebeat-ds-8mzwv"}, "kubernetes.namespace"=>"kube-system", "@timestamp"=>2019-08-21T14:40:52.901Z, "stream"=>"stdout", "source"=>"/var/log/containers/logging-elk-logstash-6599f87cd7-m7zcx_kube-system_logstash-c66d4ff9509213e47b58eb32a5856778538192f116bf9917f74b075caeee555b.log", "kubernetes.pod"=>"logging-elk-logstash-6599f87cd7-m7zcx", "tags"=>["k8s-app", "beats_input_raw_event"], "container_file_ext"=>"logstash-c66d4ff9509213e47b58eb32a5856778538192f116bf9917f74b075caeee555b.log", "prospector"=>{"type"=>"log"}, "log"=>"[2019-08-21T14:40:52,882][DEBUG][org.logstash.dissect.Dissector] Event before dissection {\"event\"=>{\"host\"=>{\"name\"=>\"logging-elk-filebeat-ds-jgl8h\"}, \"@timestamp\"=>2019-08-21T14:25:45.462Z, \"stream\"=>\"stderr\", \"offset\"=>2888763, \"tags\"=>[\"k8s-app\", \"beats_input_raw_event\"], \"prospector\"=>{\"type\"=>\"log\"}, \"@version\"=>\"1\", \"log\"=>\"I0821 14:25:45.461725       1 handler.go:143] admission-server: GET \\\"/apis/admission.certmanager.k8s.io/v1beta1\\\" satisfied by gorestful with webservice /apis/admission.certmanager.k8s.io/v1beta1\", \"time\"=>\"2019-08-21T14:25:45.46247285Z\", \"input\"=>{\"type\"=>\"log\"}, \"source\"=>\"/var/log/containers/cert-manager-webhook-ibm-cert-manager-webhook-77df99d65f-zc5wn_cert-manager_ibm-cert-manager-webhook-f5fc8a32ce195b7dcd7734d9d3501e831289bddcacdc12e30e4296892adbb296.log\", \"beat\"=>{\"name\"=>\"logging-elk-filebeat-ds-jgl8h\", \"hostname\"=>\"logging-elk-filebeat-ds-jgl8h\", \"podip\"=>\"10.1.159.93\", \"version\"=>\"6.6.1\"}}}", "time"=>"2019-08-21T14:40:52.901357842Z", "@version"=>"1", "offset"=>11131012, "beat"=>{"version"=>"6.6.1", "name"=>"logging-elk-filebeat-ds-8mzwv", "podip"=>"10.1.132.150", "hostname"=>"logging-elk-filebeat-ds-8mzwv"}}}
[2019-08-21T16:46:43,067][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.132.161:5044, remote: 10.1.159.93:51358] Sending a new message for the listener, sequence: 396
[2019-08-21T16:46:43,076][DEBUG][io.netty.handler.ssl.ReferenceCountedOpenSslEngine] SSL_write failed with 1: OpenSSL error: 503316605 error:1e00007d:Cipher functions:OPENSSL_internal:INVALID_NONCE
[2019-08-21T16:46:43,079][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.132.161:5044, remote: 10.1.159.93:51358] Sending a new message for the listener, sequence: 397
[2019-08-21T16:46:43,069][DEBUG][org.logstash.dissect.Dissector] Event before dissection {"event"=>{"input"=>{"type"=>"log"}, "host"=>{"name"=>"logging-elk-filebeat-ds-8mzwv"}, "@timestamp"=>2019-08-21T14:40:52.912Z, "stream"=>"stdout", "source"=>"/var/log/containers/logging-elk-logstash-6599f87cd7-m7zcx_kube-system_logstash-c66d4ff9509213e47b58eb32a5856778538192f116bf9917f74b075caeee555b.log", "tags"=>["k8s-app", "beats_input_raw_event"], "prospector"=>{"type"=>"log"}, "log"=>"[2019-08-21T14:40:52,894][DEBUG][org.logstash.dissect.Dissector] Event after dissection {\"event\"=>{\"host\"=>{\"name\"=>\"logging-elk-filebeat-ds-jgl8h\"}, \"@timestamp\"=>2019-08-21T14:25:45.462Z, \"stream\"=>\"stderr\", \"container_file_ext\"=>\"ibm-cert-manager-webhook-f5fc8a32ce195b7dcd7734d9d3501e831289bddcacdc12e30e4296892adbb296.log\", \"offset\"=>2888763, \"tags\"=>[\"k8s-app\", \"beats_input_raw_event\"], \"prospector\"=>{\"type\"=>\"log\"}, \"@version\"=>\"1\", \"log\"=>\"I0821 14:25:45.461725       1 handler.go:143] admission-server: GET \\\"/apis/admission.certmanager.k8s.io/v1beta1\\\" satisfied by gorestful with webservice /apis/admission.certmanager.k8s.io/v1beta1\", \"time\"=>\"2019-08-21T14:25:45.46247285Z\", \"kubernetes.namespace\"=>\"cert-manager\", \"kubernetes.pod\"=>\"cert-manager-webhook-ibm-cert-manager-webhook-77df99d65f-zc5wn\", \"input\"=>{\"type\"=>\"log\"}, \"source\"=>\"/var/log/containers/cert-manager-webhook-ibm-cert-manager-webhook-77df99d65f-zc5wn_cert-manager_ibm-cert-manager-webhook-f5fc8a32ce195b7dcd7734d9d3501e831289bddcacdc12e30e4296892adbb296.log\", \"beat\"=>{\"name\"=>\"logging-elk-filebeat-ds-jgl8h\", \"hostname\"=>\"logging-elk-filebeat-ds-jgl8h\", \"podip\"=>\"10.1.159.93\", \"version\"=>\"6.6.1\"}}}", "time"=>"2019-08-21T14:40:52.912656218Z", "@version"=>"1", "offset"=>11132196, "beat"=>{"version"=>"6.6.1", "name"=>"logging-elk-filebeat-ds-8mzwv", "podip"=>"10.1.132.150", "hostname"=>"logging-elk-filebeat-ds-8mzwv"}}}
[2019-08-21T16:46:43,095][DEBUG][org.logstash.beats.BeatsHandler] [local: 10.1.132.161:5044, remote: 10.1.159.93:51358] Sending a new message for the listener, sequence: 398
```
Please suggest ...

**Comment by normanmaurer** [comment]
Sorry but no idea.. you may want to research if boringssl even supports s390x at all. I am not sure about this.

**Comment by AnitaNayak** [comment]
Hi Logs are flowing. But getting this exception. Could you please let me know from code analysis, at which condition we get this `INVALID-NONCE` SSL_Write error.
Some hint would help a lot. Thank you for responding.

**Comment by normanmaurer** [comment]
Sorry but we just report back what BoringSSL gives us. Also I am not sure if your platform is even supported by BoringSSL.
