### ISSUE TITLE
NullPointerException during Client Side ClearText Upgrade with new Http2MultiplexHandler.java

### ISSUE THREAD

**Issue by nizarm** [netty/netty#9495]
When cleartext upgrade is implemented in client side using **HttpClientUpgradeHandler** there is no way to pass the newly created **Http2MultiplexHandler**. 

It seems like we need a way to correctly add Http2MultiplexHandler to the pipeline before calling Http2FrameCodec.onHttpClientUpgrade(...). Since this special case is not handled in HttpClientUpgradeHandler (but seems like this case is correctly taken care in Http2ServerUpgradeCodec). This did lead to the situation that we did not correctly receive the event on the Http2MultiplexHandler and so did not correctly created the Http2StreamChannel for the upgrade stream. Because of this we ended up with an NPE if a frame was dispatched to the upgrade stream later on.

Following is the exception I am receiving when I setup the Http2MultiplexHandler after the upgrade is taken place

va.lang.NullPointerException
        at io.netty.handler.codec.http2.AbstractHttp2StreamChannel$1.visit(AbstractHttp2StreamChannel.java:64) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.Http2FrameCodec$2.visit(Http2FrameCodec.java:200) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.DefaultHttp2Connection$ActiveStreams.forEachActiveStream(DefaultHttp2Connection.java:971) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.DefaultHttp2Connection.forEachActiveStream(DefaultHttp2Connection.java:208) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.Http2FrameCodec.forEachActiveStream(Http2FrameCodec.java:196) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.Http2ChannelDuplexHandler.forEachActiveStream(Http2ChannelDuplexHandler.java:83) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.handler.codec.http2.Http2MultiplexHandler.channelWritabilityChanged(Http2MultiplexHandler.java:199) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelWritabilityChanged(AbstractChannelHandlerContext.java:436) ~[netty-all-4.1.39.Final.jar:4.1.39.Final]

My Code looks something like this
```java
    Http2ClientUpgradeCodec upgradeCodec = new Http2ClientUpgradeCodec(
        "Http2Codec",
        Http2FrameCodecBuilder
        .forClient()
        .initialSettings(createHttp2Settings())
        .build()
        );

    channel.pipeline().addLast(sourceCodec);
    channel.pipeline().addLast(new HttpClientUpgradeHandler(sourceCodec, upgradeCodec, _maxContentLength));
    channel.pipeline().addLast(new Http2ProtocolUpgradeHandler(upgradePromise));
```
I add the Http2MultiplexHandler inside my Http2ProtocolUpgradeHandler during success of cleartext upgrade (as I dont have any other way to add it along with upgradecodec).

Netty Version I used : 4.1.39

When I follow the same approach to fix the serverside upgrade issue as mentioned in 
https://github.com/netty/netty/issues/9314 - it works perfectly form me.

@normanmaurer , @trustin  - let me know if this is a known bug and we are good with my proposed fix. I can give a pull request !

**Comment by normanmaurer** [comment]
@nizarm sounds like a bug yes... I would be happy to review a PR.

**Comment by nizarm** [comment]
Thanks for confirming @normanmaurer - PR is ready for your review !
