### ISSUE TITLE
org.jboss.netty.channel.socket.nio.SocketSendBufferPool throw java.lang.OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by eqzip** [netty/netty#9504]
### Expected behavior
The source code:
https://github.com/eqzip/eqchains/blob/master/EQchains%20Core/src/main/java/com/eqchains/rpc/client/MinerNetworkClient.java
public static long ping(String remoteIP) {
		Log.info("Begin ping: " + remoteIP);
		NettyTransceiver nettyTransceiver = null;
		MinerNetwork client = null;
		long time = System.currentTimeMillis();
		try {
			nettyTransceiver = new NettyTransceiver(
					new InetSocketAddress(InetAddress.getByName(remoteIP), Util.MINER_NETWORK_PORT),
					Util.DEFAULT_TIMEOUT);
			client = SpecificRequestor.getClient(MinerNetwork.class, nettyTransceiver);
			client.ping(cookie.getO());
			time = System.currentTimeMillis() - time;
			Log.info("Get ping response from " + remoteIP + " used " + time + "ms");
		} catch (Exception e) {
			Log.Error(e.getMessage());
			time = -1;
		} finally {
			if (nettyTransceiver != null) {
				nettyTransceiver.close();
				Log.info("nettyTransceiver closed");
			}
		}
		return time;
	}
Execute ping at MinerNetworkClient just use the default options it should execute normally but which throw exception.
### Actual behavior
[2019-08-23 09:25:24:024][com.eqchains.util.Util.createDir 846]C:\Users\10509\eclipse-workspace\eqchains\EQchains Core\EQchains already exists.
[2019-08-23 09:25:24:024][com.eqchains.util.Util.createDir 846]C:\Users\10509\eclipse-workspace\eqchains\EQchains Core\EQchains\DB already exists.
[2019-08-23 09:25:24:024][com.eqchains.util.Util.createDir 846]C:\Users\10509\eclipse-workspace\eqchains\EQchains Core\EQchains\DB\HIVE/ already exists.
[2019-08-23 09:25:24:024][com.eqchains.util.Util.createDir 846]C:\Users\10509\eclipse-workspace\eqchains\EQchains Core\EQchains\DB\H2 already exists.
[2019-08-23 09:25:24:024][com.eqchains.util.Util.createDir 846]C:\Users\10509\eclipse-workspace\eqchains\EQchains Core\EQchains\DB\ROCKSDB already exists.
[2019-08-23 09:25:24:024][com.eqchains.configuration.Configuration.loadConfig 78]EQchains.config exists and not empty just load it.
[2019-08-23 09:25:24:024][com.eqchains.rpc.client.MinerNetworkClient.ping 200]Begin ping: 192.168.0.0
[2019-08-23 09:25:28:028][com.eqchains.rpc.client.MinerNetworkClient.ping 213][ERROR]Error connecting to /192.168.0.0:7799
[2019-08-23 09:25:28:028][com.eqchains.rpc.client.MinerNetworkClient.ping 200]Begin ping: 192.168.0.0
[2019-08-23 09:25:31:031][com.eqchains.rpc.client.MinerNetworkClient.ping 213][ERROR]Error connecting to /192.168.0.0:7799
[2019-08-23 09:25:31:031][com.eqchains.rpc.client.MinerNetworkClient.ping 200]Begin ping: 192.168.0.0
[2019-08-23 09:25:34:034][com.eqchains.rpc.client.MinerNetworkClient.ping 213][ERROR]Error connecting to /192.168.0.0:7799
[2019-08-23 09:25:34:034][com.eqchains.rpc.client.MinerNetworkClient.ping 200]Begin ping: 192.168.0.0
[2019-08-23 09:25:37:037][com.eqchains.rpc.client.MinerNetworkClient.ping 213][ERROR]Error connecting to /192.168.0.0:7799
[2019-08-23 09:25:37:037][com.eqchains.rpc.client.MinerNetworkClient.ping 200]Begin ping: 192.168.0.0
[2019-08-23 09:25:40:040][com.eqchains.rpc.client.MinerNetworkClient.ping 213][ERROR]Error connecting to /192.168.0.0:7799
[2019-08-23 09:25:40:040][com.eqchains.rpc.client.MinerNetworkClient.ping 200]Begin ping: 192.168.0.0
[2019-08-23 09:25:43:043][com.eqchains.rpc.client.MinerNetworkClient.ping 213][ERROR]Error connecting to /192.168.0.0:7799
[2019-08-23 09:25:43:043][com.eqchains.rpc.client.MinerNetworkClient.ping 200]Begin ping: 192.168.0.0
[2019-08-23 09:25:46:046][com.eqchains.rpc.client.MinerNetworkClient.ping 213][ERROR]Error connecting to /192.168.0.0:7799
[2019-08-23 09:25:46:046][com.eqchains.rpc.client.MinerNetworkClient.ping 200]Begin ping: 192.168.0.0
Exception in thread "main" java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
	at org.jboss.netty.channel.socket.nio.SocketSendBufferPool$Preallocation.<init>(SocketSendBufferPool.java:156)
	at org.jboss.netty.channel.socket.nio.SocketSendBufferPool.<init>(SocketSendBufferPool.java:42)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.<init>(AbstractNioWorker.java:45)
	at org.jboss.netty.channel.socket.nio.NioWorker.<init>(NioWorker.java:45)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:44)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.newWorker(NioWorkerPool.java:28)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorkerPool.init(AbstractNioWorkerPool.java:80)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:39)
	at org.jboss.netty.channel.socket.nio.NioWorkerPool.<init>(NioWorkerPool.java:33)
	at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:151)
	at org.jboss.netty.channel.socket.nio.NioClientSocketChannelFactory.<init>(NioClientSocketChannelFactory.java:116)
	at org.apache.avro.ipc.netty.NettyTransceiver.<init>(NettyTransceiver.java:127)
	at com.eqchains.rpc.client.MinerNetworkClient.ping(MinerNetworkClient.java:205)
	at com.eqchains.Singularity.main(Singularity.java:150)

### Steps to reproduce
run java -Xmx900m -XX:MaxDirectMemorySize=8m -Dio.netty.leakDetection.level=advanced -jar singularity.jar 192.168.0.101
### Minimal yet complete reproducer code (or URL to code)
https://github.com/eqzip/eqchains.git
### Netty version
I am not sure. I just use AVRO 1.9.0 which use Netty as it RPC server.
### JVM version (e.g. `java -version`)
java version "12.0.1" 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
### OS version (e.g. `uname -a`)
Windows 10

**Comment by normanmaurer** [comment]
This basically means you need to use a larger limit for the direct memory. That Netty 3.x is EOL for years.
