### ISSUE TITLE
Netty communication failed in docker

### ISSUE THREAD

**Issue by elenagarrido** [netty/netty#9537]
We've created an application that uses the Apache ActiveMQ Artemis in native mode. Which means that it uses netty. 

The software is a java based application that should run in docker. We've tried with base docker image koosiedemoer/netty-tcnative-alpine  and openjdk:8-jdk-alpine and both cases we allways have the same error.

Here we add parts of the pom.xml  related to jetty
```
   <build>
    <extensions>
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>1.6.1</version>
      </extension>
    </extensions>
  </build>

<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-transport-native-epoll</artifactId>
	<classifier>linux-x86_64</classifier>
	<version>4.1.16.Final</version>
</dependency>
<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty-all</artifactId>
</dependency>
```

The exception we have got is the following:
```
2019-09-04 12:23:55.488 [main] [DEBUG] [GNFRDiskLoader] [b9a1691f7edb] NativeLibraryLoader - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_191]
        at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_191]
        at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_191]
        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_191]
        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.channel.epoll.Native.<clinit>(Native.java:61) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:38) ~[netty-all-4.1.36.Final.jar:4.1.36.Final]
        at org.apache.activemq.artemis.core.remoting.impl.netty.NettyConnector.start(NettyConnector.java:441) ~[artemis-core-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.openTransportConnection(ClientSessionFactoryImpl.java:1045) ~[artemis-core-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.createTransportConnection(ClientSessionFactoryImpl.java:1096) ~[artemis-core-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.establishNewConnection(ClientSessionFactoryImpl.java:1307) ~[artemis-core-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.getConnection(ClientSessionFactoryImpl.java:902) ~[artemis-core-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.getConnectionWithRetry(ClientSessionFactoryImpl.java:798) ~[artemis-core-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.core.client.impl.ClientSessionFactoryImpl.connect(ClientSessionFactoryImpl.java:241) ~[artemis-core-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.core.client.impl.ServerLocatorImpl.createSessionFactory(ServerLocatorImpl.java:782) ~[artemis-core-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnectionInternal(ActiveMQConnectionFactory.java:844) ~[artemis-jms-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:282) ~[artemis-jms-client-2.6.4.jar:2.6.4]
        at org.apache.activemq.artemis.jms.client.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:277) ~[artemis-jms-client-2.6.4.jar:2.6.4]
        at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:196) ~[spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:494) ~[spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:584) ~[spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
        at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:661) ~[spring-jms-5.1.8.RELEASE.jar:5.1.8.RELEASE]
```
Any help would be appreciated

**Comment by normanmaurer** [comment]
@elenagarrido this is just a debug log that we could not load the native SSL lib.. This is expected as we do not ship a version that supports alpine atm. So either you need to use a base-image that is not based on alpine or just ignore it. The application should work never less .

**Comment by elenagarrido** [comment]
Ok, I see that artemis is not connecting to my server and the only log I have before is the exception related to netty. There is no other clue of why it is not able to establish the connection.
I've done other tests and there is no issue from the server side.

**Comment by normanmaurer** [comment]
@elenagarrido please followup with with the`Artemis` team

**Comment by elenagarrido** [comment]
Thanks
