### ISSUE TITLE
Random ConnectionClosedException exception on client side during calling netty with simple http server.

### ISSUE THREAD

**Issue by artemkulick** [netty/netty#9563]
I'm using 4.1.39 netty version. 
11 java http non blocking client.

In my ChannelHandler (extends ChannelInboundHandlerAdapter) http request is received, writeAndFlush is executed and resources are freed up.

```
class ServerHttpChannelHandler extends ChannelDuplexHandler {

    public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
        if (msg instanceof FullHttpRequest) {
            DefaultFullHttpResponse defaultFullHttpResponse = new DefaultFullHttpResponse(HttpVersion.HTTP_1_1, HttpResponseStatus.NO_CONTENT);
            defaultFullHttpResponse.headers().set(HttpHeaders.Names.CONTENT_TYPE, "application/json");
            defaultFullHttpResponse.headers().set(HttpHeaders.Names.CONTENT_LENGTH, 0);
            ChannelFuture channelFuture = ctx.writeAndFlush(defaultFullHttpResponse);
            channelFuture.addListener(ChannelFutureListener.CLOSE);
            channelFuture.addListener(future -> {
                if (!future.isSuccess()) {
                    Throwable t = future.cause();
                    if (t instanceof ClosedChannelException) {
                        System.out.println("Failed to send HTTP response due to ClosedChannelException.");
                    } else {
                        System.out.println("Failure on sending HTTP response" + t);
                    }
                    ctx.close();
                }
            });
            ((FullHttpRequest) msg).release();
        } else {
            super.channelRead(ctx, msg);
        }
    }


    @Override
    public void channelReadComplete(ChannelHandlerContext ctx) throws Exception {
        ctx.flush();
    }

}
```

My pipeline settings:
```
protected void initChannel(SocketChannel ch) {
        ChannelPipeline pipeline = ch.pipeline();
        pipeline.addLast("http-codec", new HttpServerCodec());
        pipeline.addLast("http-aggregator", new HttpObjectAggregator(30 * 1024 * 1024));
        pipeline.addLast("http-handle", new ServerHttpChannelHandler());
    }
```

Im trying three http clients (AsyncHttpClient based on Netty, Java 11 Http Client, Apache Http Client, Gatling)

When I increase the load RPS my http clients sometimes throw ConnectionClosedException exception.
Ex with Apache HttpClient:
```
Caused by: org.apache.http.ConnectionClosedException: Connection closed
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.connectionAllocated(AbstractClientExchangeHandler.java:332)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.access$000(AbstractClientExchangeHandler.java:62)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.completed(AbstractClientExchangeHandler.java:387)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler$1.completed(AbstractClientExchangeHandler.java:383)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.completed(PoolingNHttpClientConnectionManager.java:306)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager$1.completed(PoolingNHttpClientConnectionManager.java:297)
	at org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:122)
	at org.apache.http.nio.pool.AbstractNIOConnPool.fireCallbacks(AbstractNIOConnPool.java:506)
	at org.apache.http.nio.pool.AbstractNIOConnPool.lease(AbstractNIOConnPool.java:290)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.requestConnection(PoolingNHttpClientConnectionManager.java:295)
	at org.apache.http.impl.nio.client.AbstractClientExchangeHandler.requestConnection(AbstractClientExchangeHandler.java:377)
	at org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.start(DefaultClientExchangeHandlerImpl.java:129)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:141)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
	**at myproject.loadtest.Test.lambda$main$1(Test.java:94)** (execute future)
	at io.reactivex.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onNext(FlowableFlatMapCompletableCompletable.java:117)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.onNext(FlowableOnBackpressureBuffer.java:112)
	at io.reactivex.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:54)
	at io.reactivex.internal.operators.observable.ObservableInterval$IntervalObserver.run(ObservableInterval.java:82)
	at io.reactivex.internal.schedulers.ScheduledDirectPeriodicTask.run(ScheduledDirectPeriodicTask.java:38)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
```

Gatling exception: 
```
io.netty.channel.ConnectTimeoutException: connection timed out: localhost/127.0.0.1:8080
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

Code snippet which reproduces this problem (based on RxJava):
```public static void main(String[] args) {

        from = Schedulers.from(Executors.newFixedThreadPool(64));
        NettyServer nettyServer = new NettyServer();
        nettyServer.init(new NettyServerConfiguration(8080, 64));

        CloseableHttpAsyncClient httpApacheClient = HttpAsyncClients.custom()
                .setMaxConnPerRoute(1000)
                .setMaxConnTotal(1000)
                .build();
        httpApacheClient.start();
        AtomicInteger rps = new AtomicInteger(0);
        Observable.interval(1L, 1000, TimeUnit.MILLISECONDS)
                .subscribe(aLong -> {
                    System.out.println("RPS " + rps.getAndSet(0));
                });

        HttpGet get = new HttpGet("http://localhost:8080/");

//500 RPS

Observable.interval(10L, 2, TimeUnit.MILLISECONDS)
                .toFlowable(BackpressureStrategy.BUFFER)
                .flatMapCompletable(aLong ->
                        Completable.fromFuture(httpApacheClient.execute(get, HttpClientContext.create(),null))
                                        .subscribeOn(from)
                                        .observeOn(from)
                                        .doOnError(Throwable::printStackTrace)
                        , true, 100)
                .blockingAwait();
    }
```

What am I doing wrong?

JVM version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

OS version
18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by amizurov** [comment]
@artemkulick Hi you close connection after each request 
`channelFuture.addListener(ChannelFutureListener.CLOSE);` also if you use `ctx.writeAndFlush(...)` is no need to invoke `ctx.flush()` in `channelReadComplete()`

**Comment by normanmaurer** [comment]
Like @amizurov said.  Please address his comment and re-open if you still think there is an issue
