### ISSUE TITLE
Http2 example not work well

### ISSUE THREAD

**Issue by LinShunKang** [netty/netty#9573]
### Expected behavior
receive channelInactive() event

### Actual behavior
java.io.IOException: Connection reset by peer

### Steps to reproduce
* Run io.netty.example.http2.helloworld.server.Http2Server
* Run nghttp HTTP/2 client to HTTP/2 server: `nghttp -nvu http://127.0.0.1:8080`
* Or run curl client to HTTP/2 server: `curl --http2 http://127.0.0.1:8080 -vv`

### Netty version
4.1.39

### JVM version (e.g. `java -version`)
1.8.0_181

### OS version (e.g. `uname -a`)
MacOS Darwin Kernel Version 18.7.0

## Netty Http2Server log
```
10:20:17.974 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x15485a4b, L:/0:0:0:0:0:0:0:0:8080] ACTIVE
10:20:20.013 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x15485a4b, L:/0:0:0:0:0:0:0:0:8080] READ: [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725]
10:20:20.014 [nioEventLoopGroup-2-1] INFO  i.n.handler.logging.LoggingHandler - [id: 0x15485a4b, L:/0:0:0:0:0:0:0:0:8080] READ COMPLETE
10:20:20.201 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] OUTBOUND SETTINGS: ack=false settings={MAX_HEADER_LIST_SIZE=8192}
10:20:20.208 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] OUTBOUND HEADERS: streamId=1 headers=DefaultHttp2Headers[:status: 200] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
User Event Triggered: UpgradeEvent [protocol=h2c, upgradeRequest=HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
GET / HTTP/1.1
host: 127.0.0.1:8080
connection: Upgrade, HTTP2-Settings
upgrade: h2c
http2-settings: AAMAAABkAAQAAP__
accept: */*
user-agent: nghttp2/1.39.2
content-length: 0]
10:20:20.220 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] OUTBOUND DATA: streamId=1 padding=0 endStream=true length=24 bytes=48656c6c6f20576f726c64202d2076696120485454502f32
10:20:20.224 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] INBOUND SETTINGS: ack=false settings={MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=65535}
10:20:20.225 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] OUTBOUND SETTINGS: ack=true
10:20:20.225 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] INBOUND PRIORITY: streamId=3 streamDependency=0 weight=201 exclusive=false
10:20:20.225 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] INBOUND PRIORITY: streamId=5 streamDependency=0 weight=101 exclusive=false
10:20:20.225 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] INBOUND PRIORITY: streamId=7 streamDependency=0 weight=1 exclusive=false
10:20:20.225 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] INBOUND PRIORITY: streamId=9 streamDependency=7 weight=1 exclusive=false
10:20:20.225 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] INBOUND PRIORITY: streamId=11 streamDependency=3 weight=1 exclusive=false
10:20:20.226 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] INBOUND PRIORITY: streamId=1 streamDependency=11 weight=16 exclusive=false
10:20:20.226 [nioEventLoopGroup-2-2] INFO  i.n.e.h.h.s.HelloWorldHttp2Handler - [id: 0x08506364, L:/127.0.0.1:8080 - R:/127.0.0.1:54725] INBOUND GO_AWAY: lastStreamId=0 errorCode=0 length=0 bytes=
10:20:20.229 [nioEventLoopGroup-2-2] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1147)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
User Event Triggered: io.netty.channel.socket.ChannelInputShutdownReadComplete@6e288923
```
### nghttp log
```
[  0.000] Connected
[  0.001] HTTP Upgrade request
GET / HTTP/1.1
host: 127.0.0.1:8080
connection: Upgrade, HTTP2-Settings
upgrade: h2c
http2-settings: AAMAAABkAAQAAP__
accept: */*
user-agent: nghttp2/1.39.2


[  0.245] HTTP Upgrade response
HTTP/1.1 101 Switching Protocols
connection: upgrade
upgrade: h2c


[  0.245] HTTP Upgrade success
[  0.245] send SETTINGS frame <length=12, flags=0x00, stream_id=0>
          (niv=2)
          [SETTINGS_MAX_CONCURRENT_STREAMS(0x03):100]
          [SETTINGS_INITIAL_WINDOW_SIZE(0x04):65535]
[  0.245] send PRIORITY frame <length=5, flags=0x00, stream_id=3>
          (dep_stream_id=0, weight=201, exclusive=0)
[  0.245] send PRIORITY frame <length=5, flags=0x00, stream_id=5>
          (dep_stream_id=0, weight=101, exclusive=0)
[  0.245] send PRIORITY frame <length=5, flags=0x00, stream_id=7>
          (dep_stream_id=0, weight=1, exclusive=0)
[  0.245] send PRIORITY frame <length=5, flags=0x00, stream_id=9>
          (dep_stream_id=7, weight=1, exclusive=0)
[  0.245] send PRIORITY frame <length=5, flags=0x00, stream_id=11>
          (dep_stream_id=3, weight=1, exclusive=0)
[  0.245] send PRIORITY frame <length=5, flags=0x00, stream_id=1>
          (dep_stream_id=11, weight=16, exclusive=0)
[  0.270] recv SETTINGS frame <length=6, flags=0x00, stream_id=0>
          (niv=1)
          [SETTINGS_MAX_HEADER_LIST_SIZE(0x06):8192]
[  0.270] recv (stream_id=1) :status: 200
[  0.270] recv HEADERS frame <length=6, flags=0x24, stream_id=1>
          ; END_HEADERS | PRIORITY
          (padlen=0, dep_stream_id=0, weight=16, exclusive=0)
          ; First response header
[  0.270] recv DATA frame <length=24, flags=0x01, stream_id=1>
          ; END_STREAM
[  0.270] send GOAWAY frame <length=8, flags=0x00, stream_id=0>
          (last_stream_id=0, error_code=NO_ERROR(0x00), opaque_data(0)=[])
```

**Comment by normanmaurer** [comment]
@LinShunKang there is nothing wrong with receiving a connection reset as long as you also get a `channelInactive`. What is the problem ?

**Comment by LinShunKang** [comment]
@normanmaurer I mean that Http2Client already send `GOAWAY` frame with `NO_ERROR (0x0)` to indicate graceful shutdown of a connection, why Netty Http2Server still throw `Connection reset by peer` exception ?

**Comment by joachern** [comment]
@normanmaurer I find that when I write   httpTohttp2  client ,I use 10 threads to  send  http message ,server accept every Http2HeadersFrame message,and sometime  lost some Http2DataFrame message,Client log also dispaly that some outbound message is not write.

Would you please give some suggest? Thank you 
### Thread code
         for(int i=0;i<10 ;i++)          **// 10 Tread** 
            {
                URI uriSimple = new URI("http://127.0.0.1:8080/postfile333"+"?+id="+i);
            	TaskFile taskFile =    new TaskFile(  streamId+2*i,  responseHandler, channel ,   uriSimple,   file1,   factory );
         //   EventLoopGroup workerGroup = new NioEventLoopGroup();
            	workerGroup.next().execute(taskFile);  
            }
### Main Task Code
                 HttpScheme scheme =  HttpScheme.HTTP;
	        AsciiString hostName = new AsciiString(HOST + ':' + PORT);
	        HttpRequest request = new DefaultHttpRequest(HttpVersion.HTTP_1_1, HttpMethod.POST, uriSimple.toASCIIString());
	        HttpHeaders headers = request.headers();
	        headers.add(HttpHeaderNames.HOST, hostName);
	        headers.add(HttpConversionUtil.ExtensionHeaderNames.SCHEME.text(), scheme.name());
	        headers.add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.GZIP);
	        headers.add(HttpHeaderNames.ACCEPT_ENCODING, HttpHeaderValues.DEFLATE);
	        headers.set(HttpHeaderNames.ACCEPT, "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8");
	    		HttpPostRequestEncoder bodyRequestEncoder;
				bodyRequestEncoder = new HttpPostRequestEncoder(factory, request, true);
				bodyRequestEncoder.addBodyAttribute("getform", "luAAAAAAAAAaa");			
				bodyRequestEncoder.addBodyAttribute("info", "first valuAAAAAe");
			**bodyRequestEncoder.addBodyFileUpload("myfile", file, "application/x-zip-compressed", false);**    
	        // finalize request
	        request = bodyRequestEncoder.finalizeRequest();        
	        channel.writeflush( request,);
	        if (bodyRequestEncoder.isChunked()) { // could do either request.isChunked()
	        	channel.writeflush( bodyRequestEncoder);
	        	
	        }
	      
	        bodyRequestEncoder.cleanFiles();
	        bodyRequestEncoder.close();
