### ISSUE TITLE
ArrayIndexOutOfBoundsException in Recycler

### ISSUE THREAD

**Issue by carryxyh** [netty/netty#9608]
### Exception

we just call like:  `channel.writeAndFlush(request);`, then exception occurs

can someone help to check if this has bean fixed at higher version?

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at io.netty.util.Recycler$Stack.pop(Recycler.java:473) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.util.Recycler.get(Recycler.java:151) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.newInstance(AbstractChannelHandlerContext.java:1126) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.access$1600(AbstractChannelHandlerContext.java:1115) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:822) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:795) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:832) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
```

### Netty version

4.1.7.Final

**Comment by carryxyh** [comment]
occurs twice. Hasn't find a way to reproduce it...
