### ISSUE TITLE
accidental IndexOutOfBoundsException

### ISSUE THREAD

**Issue by yzh1127116449** [netty/netty#9620]
### Expected behavior
When receiving data sent by the client, occasionally there are exceptions: IndexOutOfBoundsException throw, this was not real.  I am very confused, I hope the technical masters can help me analyze.Thank you very much!  This is my email: yzh_jobs@163.com looking forward to your reply!
### Actual behavior
java.lang.IndexOutOfBoundsException: index: 0, length: 1 (expected: range(0, 4096))
        at io.netty.buffer.AbstractByteBuf.checkIndex0(AbstractByteBuf.java:1362)
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1357)
        at io.netty.buffer.AbstractByteBuf.checkIndex(AbstractByteBuf.java:1352)
        at io.netty.buffer.CompositeByteBuf.toComponentIndex(CompositeByteBuf.java:723)
        at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:859)
        at io.netty.buffer.CompositeByteBuf.getBytes(CompositeByteBuf.java:44)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:873)
        at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:1805)
        at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:44)
        at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:880)
        at io.netty.buffer.CompositeByteBuf.readBytes(CompositeByteBuf.java:1800)
        at com.custome.runner.CheckRunnable.getReceiveBuf(CheckRunnable.java:156)
        at com.custome.runner.CheckRunnable.run(CheckRunnable.java:43)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

### Netty version
4.1.27.Final
### JVM version (e.g. `java -version`)
1.8.0_144

**Comment by njhill** [comment]
@yzh1127116449 there have been many changes and fixes to this part of the code since the version you are using (4.1.27.Final). Could you first update to the latest release (4.1.42.Final) and report back if the problem reoccurs?

**Comment by normanmaurer** [comment]
I will close this for now. Please update to latest version and reopen if you still see the problem. In this case also share code please as you may just not take fragmentation correctly into account .
