### ISSUE TITLE
Netty “cannot read uncompressed buffer” when decompressing certain zipped files

### ISSUE THREAD

**Issue by thomas-henley** [netty/netty#9628]
### Expected behavior
Zip archives should transfer and decompress without issue.
### Actual behavior
If the archive contains a .tla file larger than ~300kb, during decompression this `DeflateDecoder` error occurs and the transfer fails.
```
10:56:12.344 [NettyClient-NIO-1] DEBUG ///DispatchingClientEndpoint - API REQUEST received [endpoint id: 0] APIRequestMessage [requestId: 1777, endpointId: -1, sessionId: -1, method: POST, entityName: RemoteFileRepo, characteristic: Unknown, target: , multipart: true, packet #: 1, total packets: 9]
10:56:12.348 [NettyClient-NIO-1] DEBUG ///DispatchingClientEndpoint - API REQUEST received [endpoint id: 0] APIRequestMessage [requestId: 1777, endpointId: -1, sessionId: -1, method: POST, entityName: RemoteFileRepo, characteristic: Unknown, target: , multipart: true, packet #: 2, total packets: 9]
10:56:12.351 [NettyClient-NIO-1] DEBUG ///DispatchingClientEndpoint - API REQUEST received [endpoint id: 0] APIRequestMessage [requestId: 1777, endpointId: -1, sessionId: -1, method: POST, entityName: RemoteFileRepo, characteristic: Unknown, target: , multipart: true, packet #: 3, total packets: 9]
10:56:12.360 [NettyClient-NIO-1] DEBUG ///DispatchingClientEndpoint - API REQUEST received [endpoint id: 0] APIRequestMessage [requestId: 1777, endpointId: -1, sessionId: -1, method: POST, entityName: RemoteFileRepo, characteristic: Unknown, target: , multipart: true, packet #: 4, total packets: 9]
10:56:12.366 [NettyClient-NIO-1] ERROR ///ClientConnectionHandler - WebSocket exception caught!, closing connection!
io.netty.handler.codec.DecoderException: io.netty.handler.codec.CodecException: cannot read uncompressed buffer
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1475)
    at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1224)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1271)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
    at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.codec.CodecException: cannot read uncompressed buffer
    at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder.decompressContent(DeflateDecoder.java:140)
    at io.netty.handler.codec.http.websocketx.extensions.compression.DeflateDecoder.decode(DeflateDecoder.java:80)
    at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder.decode(PerMessageDeflateDecoder.java:87)
    at io.netty.handler.codec.http.websocketx.extensions.compression.PerMessageDeflateDecoder.decode(PerMessageDeflateDecoder.java:31)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
    ... 29 common frames omitted
```
### Steps to reproduce
Transfer the following file from one machine to another (transferring from one VM to another will hit the error, "transferring" on the same localhost will not) with compression on.
[9S6EJ02Z.zip](https://github.com/netty/netty/files/3676489/9S6EJ02Z.zip)

### Minimal yet complete reproducer code (or URL to code)
The error appears to be originating in `decompressContent` in `DeflateDecoder.java`. During some packet transfers, specifically the 5th when tested with the attached file, the first frame proceeds normally -
`BinaryWebSocketFrame(data: PooledUnsafeDirectByteBuf(ridx: 0, widx: 8192, cap: 8192))`. Then, when `decompressContent` is invoked with the continuation frame - `ContinuationWebSocketFrame(data: PooledUnsafeDirectByteBuf(ridx: 0, widx: 9, cap: 9))`, the call to `decoder.writeInbound(msg.content().retain());` does not queue an inbound message for the decoder. This leads to `if (partUncompressedContent == null) break;`, which then causes the CodecException because `compositeDecompressedContent.numComponents()` is 0 on line 138.
```
// DeflateDecoder.java line 119
decoder.writeInbound(msg.content().retain());     // This does not add an inbound message with the continuation frame
if (appendFrameTail(msg)) {
    decoder.writeInbound(FRAME_TAIL.duplicate());
}

CompositeByteBuf compositeDecompressedContent = ctx.alloc().compositeBuffer();
for (;;) {
     ByteBuf partUncompressedContent = decoder.readInbound();   // There are no inbound messages, so this is set to null
     if (partUncompressedContent == null) {
         break;
     }
     if (!partUncompressedContent.isReadable()) {
        partUncompressedContent.release();
        continue;
     }
     compositeDecompressedContent.addComponent(true, partUncompressedContent);
}
// (numComponents == 0 here)
if (!emptyDeflateBlock && readable && compositeDecompressedContent.numComponents() <= 0) {
     compositeDecompressedContent.release();
     throw new CodecException("cannot read uncompressed buffer");
}
```
### Netty version
Tested on 4.1.15, 4.1.40, 4.1.41, 4.1.42
### JVM version (e.g. `java -version`)
1.8.0_221
### OS version (e.g. `uname -a`)
Ubuntu 18.04.1

**Comment by amizurov** [comment]
Hi @thomas-henley could you please provide some reproducer. I'm interesting in how you split the content to continuation chain frames (BinaryFrame(not final),.. Continuation(not final).. Continuation(final)) and also `Sec-WebSocket_Extensions` header value.

**Comment by normanmaurer** [comment]
@thomas-henley ping

**Comment by thomas-henley** [comment]
@amizurov @normanmaurer Our platform breaks up the file into chunks before handing those chunks to netty for compression and transfer. It seems like when the client receiving the transfer gets the small remainder chunk at the end of the file, it runs into this issue decompressing it. Using our platform, we've seen it with .tla files (like in the original report) and also more recently with a zipped .txt file. However, without using our platform, we haven't been able to recreate that breaking-up of the file in a way that reproduces the bug, so I couldn't provide reproducer code.

Thank you for taking a look. For now I think we will just have to try to find a workaround.

**Comment by normanmaurer** [comment]
@thomas-henley i see ... please continue trying and share if you was able to
