### ISSUE TITLE
DNS resolver doesn't work some times

### ISSUE THREAD

**Issue by mrniko** [netty/netty#9632]
### Netty version
4.1.34.Final

### OS version (e.g. `uname -a`)

Here the output:
```
DatagramDnsResponse(from: /10.0.0.2:53, to: /0:0:0:0:0:0:0:0:53018, 52723, QUERY(0), NoError(0), RD RA)
DefaultDnsQuestion(useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com. IN A)
DefaultDnsRawRecord(useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com. 15 IN A 4B)
DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
2019-09-11 06:50:21,154-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] DEBUG - [id: 0x9099eb92] WRITE: [58273: /10.0.0.2:53], DefaultDnsQuestion(useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com. IN A)
2019-09-11 06:50:21,155-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] DEBUG - [id: 0x9099eb92] WRITE: [31257: /10.0.0.2:53], DefaultDnsQuestion(useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com. IN AAAA)
2019-09-11 06:50:21,155-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] DEBUG - [id: 0x9099eb92] WRITE: [54664: /10.0.0.2:53], DefaultDnsQuestion(useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com. IN A)
2019-09-11 06:50:22,881-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] DEBUG - [id: 0x9099eb92] WRITE: [32392: /10.0.0.2:53], DefaultDnsQuestion(useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com. IN AAAA)

2019-09-11 06:50:37,598-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] ERROR - Unable to resolve useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com' failed to resolve 'useast101-rd01-0002.j2b5o9.0001.use1.cache.amazonaws.com' after 2 queries
at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:877) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:838) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:382) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:220) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:170) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.0.0.2:53] query timed out after 5000 milliseconds (no stack trace available)

2019-09-11 06:51:13,388-0700 [toe=00p4dqty02gn9h] [redisson-netty-2-24] ERROR - Unable to resolve useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com' failed to resolve 'useast101-rd01-0001.j2b5o9.0001.use1.cache.amazonaws.com' after 2 queries
at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:877) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:838) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:333) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:63) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsResolveContext$3.operationComplete(DnsResolveContext.java:382) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.resolver.dns.DnsQueryContext.setFailure(DnsQueryContext.java:220) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsQueryContext.access$300(DnsQueryContext.java:43) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:170) [netty-resolver-dns-4.1.34.Final.jar:4.1.34.Final]
at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:127) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) [netty-transport-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.35.Final.jar:4.1.35.Final]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/10.0.0.2:53] query timed out after 5000 milliseconds (no stack trace available)
```

**Comment by mrniko** [comment]
Could anyone assist please?

**Comment by normanmaurer** [comment]
@mrniko please update to latest netty release (4.1.42.Final) and let us know if you still see the problems. Also a reproducer would be good.

**Comment by mrniko** [comment]
@normanmaurer 

Here is the log output for this issue:

```
07:39:58.566[redisson-netty-2-14] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0x7d835670] WRITE: UDP, [40490: /127.0.0.11:53], DefaultDnsQuestion(redis-master. IN A)
07:39:58.569[redisson-netty-2-14] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0x7d835670] RECEIVED: UDP [40490: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /0.0.0.0:53290, 40490, QUERY(0), NXDomain(3), RD RA)
        DefaultDnsQuestion(redis-master. IN A)
        DefaultDnsRawRecord(. 4277 IN SOA 64B)
        DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
07:39:58.569[redisson-netty-2-14] DEBUG i.netty.resolver.dns.DnsQueryContext - [id: 0x7d835670] WRITE: UDP, [15257: /127.0.0.11:53], DefaultDnsQuestion(redis-master. IN CNAME)
07:39:58.575[redisson-netty-2-14] DEBUG i.netty.resolver.dns.DnsNameResolver - [id: 0x7d835670] RECEIVED: UDP [15257: /127.0.0.11:53], DatagramDnsResponse(from: /127.0.0.11:53, to: /0.0.0.0:53290, 15257, QUERY(0), NXDomain(3), RD RA)
        DefaultDnsQuestion(redis-master. IN CNAME)
        DefaultDnsRawRecord(. 4277 IN SOA 64B)
        DefaultDnsRawRecord(OPT flags:0 udp:4096 0B)
07:39:58.575[redisson-netty-2-14] ERROR o.r.c.ReplicatedConnectionManager - failed to resolve 'redis-master' after 2 queries
java.net.UnknownHostException: failed to resolve 'redis-master' after 2 queries
```

**Comment by vietj** [comment]
we have a similar concern reported in our tracker that sporadically fails and the error seems to be related to the presence of the OPT record in the server response: https://github.com/eclipse-vertx/vert.x/issues/3150
