### ISSUE TITLE
NPE in Recycler

### ISSUE THREAD

**Issue by carryxyh** [netty/netty#9640]
### Behavior

```
java.lang.NullPointerException: null
	at io.netty.util.Recycler$DefaultHandle.access$1500(Recycler.java:191) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.util.Recycler$WeakOrderQueue.transfer(Recycler.java:361) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.util.Recycler$Stack.scavengeSome(Recycler.java:511) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.util.Recycler$Stack.scavenge(Recycler.java:486) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.util.Recycler$Stack.pop(Recycler.java:467) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.util.Recycler.get(Recycler.java:151) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.newInstance(AbstractChannelHandlerContext.java:1126) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.access$1600(AbstractChannelHandlerContext.java:1115) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:822) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:795) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:832) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[netty-all-4.1.7.Final.jar:4.1.7.Final]
        at ............
```

NPE occurs when use `writeAndFlush`.

**Comment by carryxyh** [comment]
![image](https://user-images.githubusercontent.com/12047600/66373325-fbe8ef80-e9da-11e9-8e65-635610317ed9.png)

Root cause is `element.recycleId`, the `element` is null.

**Comment by slandelle** [comment]
Netty 4.1.7 is super old (January 2017), so there's a very good chance your issue has been fixed since then.
You should first upgrade to latest 4.1.42 and then report again if you still have an issue.

**Comment by carryxyh** [comment]
Hi, indeed, as you said, 4.1.7 is an older version. But I checked the commit record for Recycler after 2017, and no related commit is related to this issue.

Just a few days ago, we also had another exception about Recycler (https://github.com/netty/netty/issues/9608). It seems that Recycler's problem is not only in the old version.

According this NPE in 4.1.7, we may find some details we should optimize in latest version.

**Comment by normanmaurer** [comment]
@carryxyh like @slandelle said please upgrade and then report back with a stack trace if you still encounter the issue. This will at least ensure that the line numbers etc are correct etc.

**Comment by carryxyh** [comment]
Alright, this is an occasional exception, maybe we will need some time to reproduce it...

Temporarily turn it off. Reopen it when the NPE appears again.

**Comment by carryxyh** [comment]
java.lang.NullPointerException: null
	at io.netty.util.Recycler$DefaultHandle.access$1400(Recycler.java:201) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.Recycler$WeakOrderQueue.transfer(Recycler.java:414) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.Recycler$Stack.scavengeSome(Recycler.java:554) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.Recycler$Stack.scavenge(Recycler.java:529) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.Recycler$Stack.pop(Recycler.java:510) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.util.Recycler.get(Recycler.java:161) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.newInstance(AbstractChannelHandlerContext.java:1138) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:796) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:812) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:293) ~[netty-all-4.1.38.Final.jar:4.1.38.Final]

**Comment by carryxyh** [comment]
@normanmaurer 
reopen this issue, since we find a same npe in netty 4.1.38.Final.

and a same exception occurs in pulsar: https://github.com/apache/pulsar/issues/5727

**Comment by normanmaurer** [comment]
Can you Upgrade to the latest netty version ?
