### ISSUE TITLE
IllegalStateException 

### ISSUE THREAD

**Issue by loki1985** [netty/netty#9669]

**Comment by normanmaurer** [comment]
@loki1985 can you show me how you use the pool in your code ?

**Comment by romanblachman** [comment]
@normanmaurer we have the same problem reproducing with spring 2.1.6 / netty 4.1.36:

Opened TRACE logs for "reactor.netty":

`
2020-01-05 15:21:13,614 DEBUG 10520 [ctor-http-nio-2] r.n.resources.PooledConnectionProvider   : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Channel acquired, now 3 active connections and 397 inactive connections
2020-01-05 15:21:13,614 DEBUG 10520 [ctor-http-nio-2] reactor.netty.ReactorNetty               : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Added decoder [ReadTimeoutHandler] at the end of the user pipeline, full pipeline: [reactor.left.httpCodec, ReadTimeoutHandler, reactor.right.reactiveBridge, DefaultChannelPipeline$TailContext#0]
2020-01-05 15:21:13,614 DEBUG 10520 [ctor-http-nio-2] r.netty.http.client.HttpClientConnect    : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Handler is being applied: {uri=http://localhost:5151/api/external-reporting, method=POST}
2020-01-05 15:21:13,615 DEBUG 10520 [ctor-http-nio-2] r.n.resources.PooledConnectionProvider   : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] onStateChange(POST{uri=/api/external-reporting, connection=PooledConnection{channel=[id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151]}}, [request_sent])

2020-01-05 15:21:13,622 DEBUG 10520 [ctor-http-nio-2] r.n.http.client.HttpClientOperations     : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Received response (auto-read:false) : [Content-Length=0, Date=Sun, 05 Jan 2020 15:21:13 GMT]
2020-01-05 15:21:13,622 DEBUG 10520 [ctor-http-nio-2] r.n.resources.PooledConnectionProvider   : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] onStateChange(POST{uri=/api/external-reporting, connection=PooledConnection{channel=[id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151]}}, [response_received])
2020-01-05 15:21:13,622 DEBUG 10520 [ctor-http-nio-2] reactor.netty.channel.FluxReceive        : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Subscribing inbound receiver [pending: 0, cancelled:false, inboundDone: false]
2020-01-05 15:21:13,622 DEBUG 10520 [ctor-http-nio-2] r.n.http.client.HttpClientOperations     : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Received last HTTP packet
2020-01-05 15:21:13,622 TRACE 10520 [ctor-http-nio-2] reactor.netty.channel.ChannelOperations  : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Disposing ChannelOperation from a channel

java.lang.Exception: ChannelOperation terminal stack
	at reactor.netty.channel.ChannelOperations.terminate(ChannelOperations.java:391)
	at reactor.netty.http.client.HttpClientOperations.onInboundNext(HttpClientOperations.java:555)
	at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:91)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

2020-01-05 15:21:13,623 DEBUG 10520 [ctor-http-nio-2] reactor.netty.ReactorNetty               : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Removed handler: ReadTimeoutHandler, pipeline: DefaultChannelPipeline{(reactor.left.httpCodec = io.netty.handler.codec.http.HttpClientCodec), (reactor.right.reactiveBridge = reactor.netty.channel.ChannelOperationsHandler)}
2020-01-05 15:21:13,623 DEBUG 10520 [ctor-http-nio-2] r.n.resources.PooledConnectionProvider   : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] onStateChange(POST{uri=/api/external-reporting, connection=PooledConnection{channel=[id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151]}}, [disconnecting])
2020-01-05 15:21:13,623 DEBUG 10520 [ctor-http-nio-2] r.n.resources.PooledConnectionProvider   : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Releasing channel
2020-01-05 15:21:13,623 DEBUG 10520 [ctor-http-nio-2] r.n.resources.PooledConnectionProvider   : [id: 0xff6fc2ad, L:/127.0.0.1:48476 - R:localhost/127.0.0.1:5151] Channel cleaned, now 1 active connections and 399 inactive connections
`

Does this help?

**Comment by romanblachman** [comment]
@normanmaurer we have the same issue reproducing:

`2020-01-05 15:21:32,891  WARN 10520 [ctor-http-nio-5] io.netty.util.concurrent.DefaultPromise  : An exception was thrown by io.netty.channel.pool.FixedChannelPool$AcquireListener.operationComplete()

java.lang.IllegalStateException: complete already: DefaultPromise@1724b3c9(failure: java.util.concurrent.CancellationException)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:96)
	at io.netty.channel.pool.FixedChannelPool$AcquireListener.operationComplete(FixedChannelPool.java:423)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:476)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:33)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:426)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)`


This is the pool configuration:

`    private HttpClient httpClient(WebClientOptions options)
    {
        BiConsumer<HttpInfos, Throwable> exceptionHandler = WebClientConfiguration::handleIOException;
        return HttpClient
                .create(ConnectionProvider.fixed("webClientPool", maxConnections))
                .doOnError(exceptionHandler, exceptionHandler)
                .followRedirect(true)
                .secure(spec -> spec.sslContext(getSslContextBuilder(options))
                                    .defaultConfiguration(SslProvider.DefaultConfigurationType.NONE));
    }
`

**Comment by normanmaurer** [comment]
@romanblachman which version ?

**Comment by romanblachman** [comment]
reactor-netty-0.8.9.RELEASE.jar
netty-common-4.1.36.Final.jar
