### ISSUE TITLE
UnixResolverDnsServerAddressStreamProvider : unresolved DNS server address 

### ISSUE THREAD

**Issue by shivabhalla** [netty/netty#9684]
Getting Following exception when UnixResolverDnsServerAddressStreamProvider is trying to read from /etc/resolver.conf

`java.lang.ExceptionInInitializerError: null
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:72) ~[AdExchange%23%23redisson-upgrade_9557.jar:?]
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:28) ~[AdExchange%23%23redisson-upgrade_9557.jar:?]
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:195) ~[AdExchange%23%23redisson-upgrade_9557.jar:?]
	at org.redisson.connection.MasterSlaveConnectionManager.<init>(MasterSlaveConnectionManager.java:169) ~[AdExchange%23%23redisson-upgrade_9557.jar:?]`

`Caused by: java.lang.IllegalArgumentException: cannot use an unresolved DNS server address: nil:53
	at io.netty.resolver.dns.DnsServerAddresses.sanitize(DnsServerAddresses.java:204) ~[AdExchange%23%23redisson-upgrade_9557.jar:?]
	at io.netty.resolver.dns.DnsServerAddresses.sequential(DnsServerAddresses.java:77) ~[AdExchange%23%23redisson-upgrade_9557.jar:?]
	at io.netty.resolver.dns.DefaultDnsServerAddressStreamProvider.<clinit>(DefaultDnsServerAddressStreamProvider.java:146) ~[AdExchange%23%23redisson-upgrade_9557.jar:?]`

/etc/resolver.conf file contains following data ->

nameserver {A Valid IP}

nameserver {A Valid IP}

nameserver nil

Issue is resolved if we remove "nameserver nil" from file.

**Comment by normanmaurer** [comment]
@shivabhalla hmm.. why you have `nameserver nil` in there ? This sounds like an invalid entry.

**Comment by shivabhalla** [comment]
This is being created by some job, but I wasn't facing this issue with earlier versions of netty. Currently I shifted to 4.1.17 where I started facing this.

**Comment by normanmaurer** [comment]
@shivabhalla sure because we did not read this file in earlier releases (which was a bug). That said I wonder if we should just skip "corrupt" entries.

**Comment by normanmaurer** [comment]
@slandelle what are your thoughts on this ?

**Comment by slandelle** [comment]
Agree, we should skip invalid entries.

**Comment by normanmaurer** [comment]
@slandelle @shivabhalla PTAL https://github.com/netty/netty/pull/9697

**Comment by shivabhalla** [comment]
Thanks @normanmaurer  😊

**Comment by fax4ever** [comment]
I have the same issue with the following /etc/resolv.conf (I have in my VM):
```
# Generated by NetworkManager
search localdomain
nameserver 10.211.55.1
nameserver fe80::21c:42ff:fe00:18%enp0s5
```

It works commenting the IPv6 line. Is it normal?

**Comment by normanmaurer** [comment]
@fax4ever no... can you please open a issue ?

**Comment by normanmaurer** [comment]
@fax4ever I suspect the problem is that `enp0s5` does not exist on the host as interface, correct ?

**Comment by normanmaurer** [comment]
So what exactly happens on your system ? Throws an exception when the entry is present or what ?

**Comment by fax4ever** [comment]
I opened https://github.com/netty/netty/issues/13612
