### ISSUE TITLE
CorruptedFrameException in LengthFieldBasedFrameDecoder when using Epoll with AdaptiveRecvByteBufAllocator

### ISSUE THREAD

**Issue by morvael** [netty/netty#9788]
Been using this code for years:
```
    new LengthFieldBasedFrameDecoder(1400, 0, 2, -2, 0, true),
```
It worked with NIO for a long time, and with EPOLL for several Netty versions. But now it fails with the exception seen below.

### Expected behavior
Frames are read correctly.

### Actual behavior
Exception is thrown when using EPOLL mode:
```
    io.netty.handler.codec.CorruptedFrameException: Adjusted frame length (0) is less than lengthFieldEndOffset: 2
    	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failOnFrameLengthLessThanLengthFieldEndOffset(LengthFieldBasedFrameDecoder.java:360)
    	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:417)
    	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:334)
    	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
    	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
    	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
    	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
    	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
    	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
    	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
    	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
    	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
    	at io.netty.channel.epoll.EpollDatagramChannel.read(EpollDatagramChannel.java:688)
    	at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:57)
    	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:507)
    	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:394)
    	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
    	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413)
    	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
    	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    	at java.base/java.lang.Thread.run(Thread.java:834)
```
### Steps to reproduce
Unable to provide access to private data stream.

### Netty version
4.1.43.Final

### JVM version (e.g. `java -version`)
openjdk version "11.0.5" 2019-10-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.5+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.5+10, mixed mode)

### OS version (e.g. `uname -a`)
Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by morvael** [comment]
Similar code works for another stream (not UDP though):
```
new LengthFieldBasedFrameDecoder(16224, 2, 2, -4, 0, true),
````

**Comment by normanmaurer** [comment]
Can you show me how you bootstrap your Channel ?

**Comment by morvael** [comment]
In a class extending `ChannelInitializer<Channel>` in the `void initChannel(Channel ch) throws Exception` method, I'm creating ChannelHandlers and add them like this:
```
ChannelHandler[] handlers = factory.createHandlers();
            for (int i = 0; i < handlers.length; i++) {
                pipe.addLast("customHandler" + i, handlers[i]);
            }
```
in case of UDP clients factory code is:
```
return new ChannelHandler[]{
                        new DatagramPacketDecoder(),
                        new LengthFieldBasedFrameDecoder(DataHandler.MAX_LENGTH, 0, 2, -2, 0, true),
                        new Handler()
                };
```
where DatagramPacketDecoder is:
```
public class DatagramPacketDecoder extends MessageToMessageDecoder<DatagramPacket> {

    @Override
    protected void decode(ChannelHandlerContext ctx, DatagramPacket msg, List<Object> out) throws Exception {
        out.add(msg.content().retain());
    }

}
```
As I said this code is used quite a lot (~15 million messages per day, 5 days per week, for many years). It was always using NIO and had no problems, we recently started testing EPOLL (in July 2019), and it worked fine. Maybe the problem lies in switch to JDK 11, which I have attempted today.

**Comment by normanmaurer** [comment]
@morvael I want to see what you do related to using `Bootstrap` ...

**Comment by morvael** [comment]
I think this is the relevant code. Maybe AdaptiveRecvByteBufAllocator wasn't correctly initialized? I have passed maxPacketSize 1400. That's indeed a fragment that differs for EPOLL vs NIO.
```
    ClientUDP(NettyManager manager, IOMode mode, InternetProtocolFamily family, int maxPacketSize) {
        super(manager, mode);
        logger.info(String.format("Creating UDP %s client using %s", family, mode));
        bootstrapSrc = new Bootstrap();
        bootstrapSrc.channelFactory(new UDPChannelFactory(mode, family));
        if (mode == IOMode.EPOLL) {
            if (maxPacketSize <= 0) {
                maxPacketSize = 1024;
            }
            bootstrapSrc.option(ChannelOption.RCVBUF_ALLOCATOR, new AdaptiveRecvByteBufAllocator(maxPacketSize, maxPacketSize, Math.max(maxPacketSize, 65536 / maxPacketSize)));
            bootstrapSrc.option(EpollChannelOption.MAX_DATAGRAM_PAYLOAD_SIZE, maxPacketSize);
        }
        bootstrapSrc.handler(getInitializer());
    }
```
and
```
    @Override
    protected void onStart() throws IOException {
        group = createGroup(1);

        bootstrapRun = bootstrapSrc.clone().group(group);

        ChannelFuture future = bootstrapRun.bind();
        if (future.awaitUninterruptibly(30, TimeUnit.SECONDS) == false || future.isSuccess() == false) {
            throw new IOException("Problem binding UDP socket", future.cause());
        } else {
            DatagramChannel c = (DatagramChannel) future.channel();
            if ((multicastAddress != null) && (networkInterface != null)) {
                ChannelFuture future2 = c.joinGroup(multicastAddress, networkInterface);
                if (future2.awaitUninterruptibly(30, TimeUnit.SECONDS) == false || future2.isSuccess() == false) {
                    c.close().awaitUninterruptibly(10, TimeUnit.SECONDS);
                    throw new IOException("Problem joining multicast", future2.cause());
                } else {
                    channel.set(c);
                    getGroup().add(c);
                }
            }
        }
    }
```

**Comment by morvael** [comment]
I guess there's a mistake in AdaptiveRecvByteBufAllocator constructor, but it means it's actually set to non-adaptive mode (1400,1400,1400). 65536 / maxPacketSize should be multiplied by maxPacketSize again (so that maximum is equal to multiple of maxPacketSize).

**Comment by morvael** [comment]
I can now see that bootstrapSrc.clone() may cause reuse of the same instance of AdaptiveRecvByteBufAllocator. My bad.

**Comment by morvael** [comment]
Didn't help. The problem is only gone when I will remove usage of RCVBUF_ALLOCATOR and MAX_DATAGRAM_PAYLOAD_SIZE.

**Comment by morvael** [comment]
```
            if (maxAllocatorSize > 0) {
                bootstrapRun.option(ChannelOption.RCVBUF_ALLOCATOR, new AdaptiveRecvByteBufAllocator(maxPacketSize, maxPacketSize, maxAllocatorSize));
                bootstrapRun.option(EpollChannelOption.MAX_DATAGRAM_PAYLOAD_SIZE, maxPacketSize);
            } else {
                bootstrapRun.option(ChannelOption.RCVBUF_ALLOCATOR, new FixedRecvByteBufAllocator(maxPacketSize));
            }
```
Same code with AdaptiveRecvByteBufAllocator doesn't work, with FixedRecvByteBufAllocator works. Migration instructions were taken from https://netty.io/news/2019/09/12/4-1-41-Final.html

**Comment by normanmaurer** [comment]
@morvael I will investigate. Seems like something is wrong with our "slicing" here.

**Comment by normanmaurer** [comment]
@morvael can you now show me your full code where you configure the `Bootstrap` ? I just want to ensure I understand what exactly you configure for the case when it works and also for the case when it not works.

**Comment by morvael** [comment]
Currently the code is:

constructor:
```
bootstrapSrc = new Bootstrap();
bootstrapSrc.channelFactory(new UDPChannelFactory(mode, family));
bootstrapSrc.handler(getInitializer());
```
start method:
```
group = createGroup(1);

bootstrapRun = bootstrapSrc.clone().group(group);
if (maxPacketSize > 0) {
    if (maxAllocatorSize > 0) {
        bootstrapRun.option(ChannelOption.RCVBUF_ALLOCATOR, new AdaptiveRecvByteBufAllocator(maxPacketSize, maxPacketSize, maxAllocatorSize));
        bootstrapRun.option(EpollChannelOption.MAX_DATAGRAM_PAYLOAD_SIZE, maxPacketSize);
    } else {
        bootstrapRun.option(ChannelOption.RCVBUF_ALLOCATOR, new FixedRecvByteBufAllocator(maxPacketSize));
    }
}

ChannelFuture future = bootstrapRun.bind();
if (future.awaitUninterruptibly(30, TimeUnit.SECONDS) == false || future.isSuccess() == false) {
    throw new IOException("Problem binding UDP socket", future.cause());
} else {
    DatagramChannel c = (DatagramChannel) future.channel();
    if ((multicastAddress != null) && (networkInterface != null)) {
        ChannelFuture future2 = c.joinGroup(multicastAddress, networkInterface);
        if (future2.awaitUninterruptibly(30, TimeUnit.SECONDS) == false || future2.isSuccess() == false) {
            c.close().awaitUninterruptibly(10, TimeUnit.SECONDS);
            throw new IOException("Problem joining multicast", future2.cause());
        } else {
            channel.set(c);
            getGroup().add(c);
        }
    }
}
```

UPDChannelFactory implements ChannelFactory and returns new EpollDatagramChannel(family) in newChannel() in this case
getInitializer() returns implementation of ChannelInitializer which adds various handlers in initChannel(Channel), like IdleStateHandler, ReadTimeoutHandler, WriteTimeoutHandler plus extra handlers for given case (always creates new objects, they are not shared)
createGroup(1) returns new EpollEventLoopGroup(1, threadFactory) in this case
maxAllocatorSize equals to Math.max(1, 65536 / maxPacketSize) * maxPacketSize in case when I'm using EPOLL and want to use adaptive mode

**Comment by normanmaurer** [comment]
@morvael and what is `maxPacketSize` ?

**Comment by morvael** [comment]
1400 in this case

**Comment by morvael** [comment]
Yes, copied from https://netty.io/news/2019/09/12/4-1-41-Final.html, but with dynamic packet size. In this case formula results in 64400 max buffer size.

**Comment by morvael** [comment]
Maybe I misunderstood minimum parameter? Smallest possible packet is 16 bytes, but buffer should never go below 1400, as this is maximum packet size of a single packet.

**Comment by normanmaurer** [comment]
And I understand it right that the maximum datagram packet size you would expect is `1400` ?

**Comment by morvael** [comment]
Yes, that's what the protocol documentation says, and experience confirms. Is there something extra in UDP itself that may increase packet size beyond what the protocol states? I only know that what goes into LengthFieldBasedFrameDecoder will be never larger than 1400 bytes. I don't know if it's the same value AdaptiveRecvByteBufAllocator and MAX_DATAGRAM_PAYLOAD_SIZE think about.

**Comment by normanmaurer** [comment]
@morvael can you do me a favour and try if you see the same issue with:

```java
bootstrapRun.option(ChannelOption.RCVBUF_ALLOCATOR, new FixedRecvByteBufAllocator((65536 / 1400) * 1400);
bootstrapRun.option(EpollChannelOption.MAX_DATAGRAM_PAYLOAD_SIZE, 1400);
```

**Comment by morvael** [comment]
It's working without problems.

**Comment by morvael** [comment]
Here's log:
[log.txt](https://github.com/netty/netty/files/3891094/log.txt)

**Comment by morvael** [comment]
Different length packets incoming on a longer run:
[log2.txt](https://github.com/netty/netty/files/3891163/log2.txt)

**Comment by normanmaurer** [comment]
@morvael and does this work as well?: 

```
int limit = (65536 / 1400) * 1400;
bootstrapRun.option(ChannelOption.RCVBUF_ALLOCATOR, new AdaptiveRecvByteBufAllocator(limit, limit, limit);
bootstrapRun.option(EpollChannelOption.MAX_DATAGRAM_PAYLOAD_SIZE, 1400);
```

**Comment by morvael** [comment]
This works, I guess it isn't much adaptive with such settings.

**Comment by normanmaurer** [comment]
@morvael yep... I still don't get why it would make any difference tho. As at the end we should always try to read into buffers of size `1400` :/ 

Can you please use the following again:

```
bootstrapRun.option(ChannelOption.RCVBUF_ALLOCATOR, new AdaptiveRecvByteBufAllocator(1400, 1400, Math.max(1, 65536 / 1400) * 1400);
bootstrapRun.option(EpollChannelOption.MAX_DATAGRAM_PAYLOAD_SIZE, 1400);
```
and log what `datagramPacket.content().capacity()` returns before passing it to `DatagramPacketDecoder()` (Basically adding a handler in front of it and log the capacity). 
Something like:

```
public final class LogHandler extends ChannelInboundHandlerAdapter {
    @Override
    public void channelRead(ChannelHandlerContext ctx, Object msg) {
        log((DatagramPacket) msg).content().capacity());
    }
}
```
The capacity should always be == `MAX_DATAGRAM_PAYLOAD_SIZE`.

**Comment by morvael** [comment]
Seems like first packet is arriving, and then the corruption starts:
```
2019-11-27 10:29:27.253 INFO  capacity 2048
2019-11-27 10:29:27.256 DEBUG packet [16 bytes]
2019-11-27 10:29:27.256 ERROR problem
io.netty.handler.codec.CorruptedFrameException: Adjusted frame length (0) is less than lengthFieldEndOffset: 2
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failOnFrameLengthLessThanLengthFieldEndOffset(LengthFieldBasedFrameDecoder.java:360)
  ...
2019-11-27 10:29:29.238 INFO  capacity 2048
2019-11-27 10:29:29.242 ERROR problem
io.netty.handler.codec.CorruptedFrameException: Adjusted frame length (0) is less than lengthFieldEndOffset: 2
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failOnFrameLengthLessThanLengthFieldEndOffset(LengthFieldBasedFrameDecoder.java:360)
  ...
```
Without forwarding in "LogHandler" (calling super.channelRead(ctx, msg) after logging), I get a sequence of "capacity 2048" messages.

**Comment by morvael** [comment]
As you can see capacity is not equal to MAX_DATAGRAM_PAYLOAD_SIZE.

**Comment by normanmaurer** [comment]
can you also log `buffer.toString()` ?

**Comment by morvael** [comment]
And what is buffer?

**Comment by normanmaurer** [comment]
@morvael ups sorry... `(DatagramPacket) msg).content().toString()`

**Comment by morvael** [comment]
```
2019-11-27 10:48:22.254 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:24.209 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:26.209 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:28.209 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:30.209 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:32.209 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:34.209 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:36.209 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:38.212 INFO  capacity 2048 content SimpleLeakAwareByteBuf(PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048))
2019-11-27 10:48:40.210 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:42.211 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:48:44.211 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
```

**Comment by normanmaurer** [comment]
@morvael can you show me the last log line before when the problem happens ? I want to see if widx is 1400 as well in this case

**Comment by morvael** [comment]
```
2019-11-27 10:57:22.323 INFO  capacity 2048 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 1400, cap: 2048)
2019-11-27 10:57:22.326 DEBUG packet [16 bytes]
2019-11-27 10:57:22.326 ERROR problem
io.netty.handler.codec.CorruptedFrameException: Adjusted frame length (0) is less than lengthFieldEndOffset: 2
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.failOnFrameLengthLessThanLengthFieldEndOffset(LengthFieldBasedFrameDecoder.java:360)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:417)
	at io.netty.handler.codec.LengthFieldBasedFrameDecoder.decode(LengthFieldBasedFrameDecoder.java:334)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at "my LogHandler"
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.epoll.EpollDatagramChannel.read(EpollDatagramChannel.java:688)
	at io.netty.channel.epoll.EpollDatagramChannel.access$100(EpollDatagramChannel.java:57)
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:507)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:502)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Now it looks to me like the problems happen after decoding? It's happens at the same time as first packet read, not when the second comes. Also, I don't remember now why I had to use manual retain/release mechanism by adding MessageToMessageDecoder to the pipeline which does:
```
    @Override
    protected void decode(ChannelHandlerContext ctx, DatagramPacket msg, List<Object> out) throws Exception {
        out.add(msg.content().retain());
    }
```
Maybe this causes issues? It's been working for more than 6 years now, mostly on NIO, and now with EPOLL, only without AdaptiveRecvByteBufAllocator.

**Comment by morvael** [comment]
Skipping my MessageToMessageDecoder and LengthFieldBasedFrameDecoder, and accessing DatagramPacket.content() directly results in no bug. I guess those intermediate steps (conversion of DatagramPacket to ByteBuf, and decoding frames) are not needed at all in UDP, where packets come at full size. Right?

**Comment by morvael** [comment]
The only difference is that ByteBuf.readableBytes() returns 1400, not packet length, so I would have to make sure not to use this method.

**Comment by normanmaurer** [comment]
@morvael right... with UDP you should receive everything at once... I am still a bit confused tho why it would not show up with `FixedRecvByteBufAllocator`. 

So can you please use this again + logging and paste the logs:

```
bootstrapRun.option(ChannelOption.RCVBUF_ALLOCATOR, new FixedRecvByteBufAllocator((65536 / 1400) * 1400);
bootstrapRun.option(EpollChannelOption.MAX_DATAGRAM_PAYLOAD_SIZE, 1400);
```

**Comment by morvael** [comment]
I think I wanted to use retained ByteBuffers, because I feed them into Akka actor system, and they will be processed by different thread and at different time, so they may not be reused by Netty before that.

**Comment by normanmaurer** [comment]
@morvael they will not be re-used as long as you not call `release()`.

**Comment by morvael** [comment]
```
2019-11-27 11:30:08.586 INFO  capacity 64400 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 64400)
2019-11-27 11:30:08.590 DEBUG packet [16 bytes]
2019-11-27 11:30:10.557 INFO  capacity 64400 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 64400)
2019-11-27 11:30:10.559 DEBUG packet [16 bytes]
2019-11-27 11:30:12.557 INFO  capacity 64400 content PooledUnsafeDirectByteBuf(ridx: 0, widx: 16, cap: 64400)
2019-11-27 11:30:12.559 DEBUG packet [16 bytes]
```

**Comment by morvael** [comment]
So one has widx 1400, and one has widx 16 (correct size of incoming packet). That must be the difference, that causes problems in LengthFieldBasedFrameDecoder, it tries to find another packet after the first one, but buffer is empty, and size turns out as 0.

**Comment by normanmaurer** [comment]
so widx `16` is correct ? Can you show me the order of the handlers in the pipeline ? You still use `EpollChannelOption.MAX_DATAGRAM_PAYLOAD_SIZE, 1400` ?

**Comment by morvael** [comment]
For this packet (it's a heartbeat packet), 16 is correct. It's important that widx is correct for LengthFieldBasedFrameDecoder, so it doesn't try to look for other packets in long but empty buffer.

Pipeline is:
io.netty.handler.timeout.IdleStateHandler
my capacity / content logging handler
my datagram packet decoder (MessageToMessageDecoder: DatagramPacket to ByteBuf)
io.netty.handler.codec.LengthFieldBasedFrameDecoder
my packet logging handler

Yes, still using MAX_DATAGRAM_PAYLOAD_SIZE.

**Comment by morvael** [comment]
By changing my datagram packet decoder to:
```
    protected void decode(ChannelHandlerContext ctx, DatagramPacket msg, List<Object> out) throws Exception {
        ByteBuf content = msg.content().retain();
        content.writerIndex(content.getUnsignedShort(0));
        out.add(content);
    }
```
I'm setting correct writer index from packet header, and I'm able to fool LengthFieldBasedFrameDecoder and bypass the problem caused by AdaptiveRecvByteBufAllocator.

**Comment by normanmaurer** [comment]
Can you run with debugger attached ? I would be interested to know if this method is called with all of the `*RecvByteBufAllocators`: https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannel.java#L596

Also I would be interested to know if we hit this line:

https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannel.java#L623

**Comment by morvael** [comment]
Never entering into scatteringRead as it seems numDatagram is <= 1 and connected is false always:
```
if (numDatagram <= 1) {
                                if (connected) {
                                    read = connectedRead(allocHandle, byteBuf, datagramSize);
                                } else {
                                    read = read(allocHandle, byteBuf, datagramSize);
                                }
                            } else {
                                // Try to use scattering reads via recvmmsg(...) syscall.
                                read = scatteringRead(allocHandle, byteBuf, datagramSize, numDatagram);
                            }
```

**Comment by morvael** [comment]
I guess it would require heavier traffic to get more than one datagram, and it's pretty hard to achieve this on test system.

**Comment by morvael** [comment]
I'll let it run for a longer time, in the log buffer only version, maybe it will stop at breakpoint at some time.

**Comment by morvael** [comment]
But I would look for a bug in setting writerIndex in
```
private boolean read(EpollRecvByteAllocatorHandle allocHandle, ByteBuf byteBuf, int maxDatagramPacketSize)
```

**Comment by normanmaurer** [comment]
this is strange... What `RecvByteBufAllocator` you are using here ? Also how you init it ?

**Comment by morvael** [comment]
The buggy one:
```
                bootstrapRun.option(ChannelOption.RCVBUF_ALLOCATOR, new AdaptiveRecvByteBufAllocator(1400, 1400, 64400));
                bootstrapRun.option(EpollChannelOption.MAX_DATAGRAM_PAYLOAD_SIZE, 1400);
```
I think I will never get into that "else", there are now about 50 packets per second, as much as it's likely to get on test system.

**Comment by normanmaurer** [comment]
ok I may have spotted something... let me test something

**Comment by morvael** [comment]
When it's calculating writable at start of read function byteBuf.writableBytes() is 2048, maxDatagramPacketSize is 1400, so it selects 1400 (when using Adaptive).

With Fixed it actually gets into scatteringRead!

**Comment by normanmaurer** [comment]
Yeah I think this line is not correct: https://github.com/netty/netty/blob/4.1/transport-native-epoll/src/main/java/io/netty/channel/epoll/EpollDatagramChannel.java#L689

**Comment by morvael** [comment]
But why is Fixed getting into scatteringRead, and Adaptive not?

**Comment by normanmaurer** [comment]
it should at some point... I will have a look but let me first fix this bug.

**Comment by normanmaurer** [comment]
@morvael thanks a lot for all the help to track this down... Fix is https://github.com/netty/netty/pull/9819

**Comment by morvael** [comment]
Thanks, will wait for 4.1.44.Final release to test it.

**Comment by normanmaurer** [comment]
@morvael I can also provide you with a snapshot jar to test if you like. Just let me know if you need netty-all or netty-transport-native-epoll jar

**Comment by morvael** [comment]
I'm using netty-all with extra epoll .so compiled under and for ppc64le.

**Comment by normanmaurer** [comment]
@morvael maybe you can then just use my branch(https://github.com/netty/netty/tree/epoll_writer_index)  and compile and test with it ?

**Comment by morvael** [comment]
Ok, but that will have to wait for tomorrow.

**Comment by morvael** [comment]
I think the branch is gone now?

**Comment by normanmaurer** [comment]
Yes just use latest 4.1 branch (I merged it)

**Comment by morvael** [comment]
Not so easy, first hit a problem requiring CMake upgrade from 2.8.12.2 to 3.0+, and now this: https://github.com/netty/netty-tcnative/issues/512

**Comment by morvael** [comment]
Turns out to be too complicated. #512 was fixed, but not in the release used by netty 44 snapshot. Also, when compiled under ppc64le, I get a netty-all version that I can't test on my x86_64 machine (for that I would use your x86_64 so), because there is no epoll .so for me. I don't want to setup another compilation environment on my machine, so I guess I'll have to wait for 44 release :)
