### ISSUE TITLE
NoClassDefFoundError: Could not initialize class io.netty.util.ReferenceCountUtil

### ISSUE THREAD

**Issue by Sridhar-1987** [netty/netty#9810]
### Expected behavior
NoClassDefFoundError shouldn't be thrown from netty.

### Actual behavior

`java.lang.NoClassDefFoundError: Could not initialize class io.netty.util.ReferenceCountUtil

	at io.netty.channel.DefaultChannelPipeline.touch(DefaultChannelPipeline.java:116)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:785)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:812)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1036)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:305)`

### Steps to reproduce

I am unable to reproduce the issue. Application works most of the time, issue is sporadic and random.

### Netty version
4.1.36

### JVM version (e.g. `java -version`)
java version "1.8.0_191"

### OS version (e.g. `uname -a`)
Linux ************* 2.6.32.23-0.3-default #1 SMP 2010-10-07 14:57:45 +0200 x86_64 x86_64 x86_64 GNU/Linux

We recently migrated from 4.1.33 to 4.1.36, issue is still happening in both the labels.

**Comment by normanmaurer** [comment]
@Sridhar-1987 this sounds more like class loader issue. Ensure you not have multiple netty version on the class path
