### ISSUE TITLE
rest service call with ssl blocks reactive thread

### ISSUE THREAD

**Issue by urferr** [netty/netty#9834]
I opened this issue in already  in reactor-netty project but there they recommended to open it here in the netty project.

when using Spring webflux with reactor-netty i get a blocking exception when calling another rest service using ssl. Adding allowBlockingCallsInside("io.netty.handler.ssl.SslHandler", "handshake") to the Blockhound builder can be used as workaround

Stack trace:
at reactor.blockhound.BlockHound$Builder.lambda$new$0(BlockHound.java:196)
at reactor.blockhound.BlockHound$Builder.lambda$install$6(BlockHound.java:318)
at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:46)
at java.base/java.io.FileInputStream.readBytes(FileInputStream.java)
at java.base/java.io.FileInputStream.read(FileInputStream.java:279)
at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
at java.base/sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424)
at java.base/sun.security.provider.NativePRNG$RandomIO.ensureBufferValid(NativePRNG.java:526)
at java.base/sun.security.provider.NativePRNG$RandomIO.implNextBytes(NativePRNG.java:545)
at java.base/sun.security.provider.NativePRNG.engineNextBytes(NativePRNG.java:220)
at java.base/java.security.SecureRandom.nextBytes(SecureRandom.java:741)
at java.base/sun.security.ssl.RandomCookie.(RandomCookie.java:67)
at java.base/sun.security.ssl.ClientHello$ClientHelloMessage.(ClientHello.java:93)
at java.base/sun.security.ssl.ClientHello$ClientHelloKickstartProducer.produce(ClientHello.java:639)
at java.base/sun.security.ssl.SSLHandshake.kickstart(SSLHandshake.java:515)
at java.base/sun.security.ssl.ClientHandshakeContext.kickstart(ClientHandshakeContext.java:104)
at java.base/sun.security.ssl.TransportContext.kickstart(TransportContext.java:228)
at java.base/sun.security.ssl.SSLEngineImpl.beginHandshake(SSLEngineImpl.java:103)
at io.netty.handler.ssl.SslHandler.handshake(SslHandler.java:1987)
at io.netty.handler.ssl.SslHandler.startHandshakeProcessing(SslHandler.java:1906)
at io.netty.handler.ssl.SslHandler.channelActive(SslHandler.java:2042)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204)
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1410)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211)
at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:907)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:305)
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)
at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base/java.lang.Thread.run(Thread.java:834)

Reactor version(s) used: 3.3.0, reactor-netty 0.9.1
Other relevant libraries versions: netty 4.1.43, spring 5.2.1
JVM version (javar -version): openjdk version "11.0.2" 2018-10-16
OS and version (eg uname -a): Linux pdvmdev15.profidatagroup.com 3.10.0-957.10.1.el7.x86_64 #1 SMP Thu Feb 7 07:12:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by normanmaurer** [comment]
@urferr you can specify an `Executor` when building your `SslHandler` / `SslContext` that will be used to offload such operations. Not sure if this is expected by `project-reactor` tho.

**Comment by normanmaurer** [comment]
Like I mentioned this kind of stuff can be offloaded.

**Comment by violetagg** [comment]
@normanmaurer I'm evaluating how I can add this configuration by default in Reactor Netty.
I tested your proposal by adding an Executor, but it is still blocking. I don't think that this `io.netty.handler.ssl.SslHandler#delegatedTaskExecutor` is used for the handshake.

The stack trace:

```
...
at io.netty.handler.ssl.SslHandler.handshake(SslHandler.java:1987)
at io.netty.handler.ssl.SslHandler.startHandshakeProcessing(SslHandler.java:1906)
at io.netty.handler.ssl.SslHandler.channelActive(SslHandler.java:2042)
...
```

I'm using the following API:
`io.netty.handler.ssl.SslContext#newHandler(io.netty.buffer.ByteBufAllocator, java.util.concurrent.Executor)`
`io.netty.handler.ssl.SslContext#newHandler(io.netty.buffer.ByteBufAllocator, java.lang.String, int, java.util.concurrent.Executor)`

**Comment by normanmaurer** [comment]
@violetagg if you use the native implementation you will also need to add "-Dio.netty.handler.ssl.openssl.useTasks=true" otherwise it should offload this stuff.

**Comment by violetagg** [comment]
@normanmaurer I'm testing with this https://github.com/violetagg/netty/commit/e24767c5d894978b0861e3e2a104395cb45a97a3

**Comment by violetagg** [comment]
@normanmaurer Should we reopen this issue?

**Comment by violetagg** [comment]
@normanmaurer I tested the proposed solution and I'm still not able to test it successful. Any other suggestions how to test it and make it running? (https://github.com/violetagg/netty/commit/e24767c5d894978b0861e3e2a104395cb45a97a3)

**Comment by johnou** [comment]
@violetagg try with `.sslProvider(SslProvider.OPENSSL)` and make sure you set the system property `io.netty.handler.ssl.openssl.useTasks` to `true`.

**Comment by johnou** [comment]
@normanmaurer probably makes sense to anyway adjust the Netty config to include allowBlockingCallsInside("io.netty.handler.ssl.SslHandler", "handshake") given the default is JDK..
