### ISSUE TITLE
NPE in CompositeByteBuf.forEachByte with ResourceLeakDetector enabled

### ISSUE THREAD

**Issue by dkomanov** [netty/netty#9873]
### Expected behavior
No exception.

### Actual behavior
Throws NullPointerException:
```
java.lang.NullPointerException
	at io.netty.buffer.CompositeByteBuf.toComponentIndex0(CompositeByteBuf.java:888)
	at io.netty.buffer.CompositeByteBuf.forEachByteAsc0(CompositeByteBuf.java:637)
	at io.netty.buffer.CompositeByteBuf.forEachByteAsc0(CompositeByteBuf.java:647)
	at io.netty.buffer.AbstractByteBuf.forEachByte(AbstractByteBuf.java:1271)
	at io.netty.buffer.WrappedCompositeByteBuf.forEachByte(WrappedCompositeByteBuf.java:388)
	at io.netty.buffer.AdvancedLeakAwareCompositeByteBuf.forEachByte(AdvancedLeakAwareCompositeByteBuf.java:657)
```

### Minimal yet complete reproducer code
```
@Test
public void forEachByteUnderLeakDetectionShouldNotThrowException() {
    ResourceLeakDetector.setLevel(ResourceLeakDetector.Level.PARANOID);
    PooledByteBufAllocator alloc = PooledByteBufAllocator.DEFAULT;
    CompositeByteBuf buf = alloc.compositeDirectBuffer();
    CompositeByteBuf comp = alloc.compositeDirectBuffer();
    ByteBuf inner = alloc.directBuffer(1).writeByte(0);
    comp.addComponent(true, inner);
    buf.addComponent(true, comp);

    Assert.assertEquals(-1, buf.forEachByte(b -> true)); // throws NPE
}
```

### Netty version
4.1.35-Final

### JVM version
```
$ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```

### OS version
```
$ uname -a
Linux dk 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by normanmaurer** [comment]
@dkomanov this issue does not exists in latest netty release. I added a unit test as prove as well in https://github.com/netty/netty/pull/9875
