### ISSUE TITLE
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;

### ISSUE THREAD

**Issue by izeye** [netty/netty#9880]
### Expected behavior
No error is thrown.

### Actual behavior
The following error is thrown:

```
2019-12-13 16:58:20.020  WARN 60628 --- [r-http-kqueue-1] r.netty.http.client.HttpClientConnect    : [id: 0x49887326, L:/127.0.0.1:64914 - R:localhost/127.0.0.1:64912] The connection observed an error

io.netty.channel.socket.ChannelOutputShutdownException: Channel output shutdown
	at io.netty.channel.AbstractChannel$AbstractUnsafe.shutdownOutput(AbstractChannel.java:638) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:946) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.flush0(AbstractKQueueChannel.java:505) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:898) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1384) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:741) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:727) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.flush(CombinedChannelDuplexHandler.java:533) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:125) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.flush(CombinedChannelDuplexHandler.java:358) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:749) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:789) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:757) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:812) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1037) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:293) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at reactor.netty.http.HttpOperations.lambda$then$2(HttpOperations.java:163) ~[reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.netty.FutureMono$DeferredFutureMono.subscribe(FutureMono.java:116) ~[reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4105) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxConcatIterable$ConcatIterableSubscriber.onComplete(FluxConcatIterable.java:146) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.FluxConcatIterable.subscribe(FluxConcatIterable.java:60) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.MonoFromFluxOperator.subscribe(MonoFromFluxOperator.java:72) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) [reactor-core-3.3.1.RELEASE.jar:3.3.1.RELEASE]
	at reactor.netty.http.client.HttpClientConnect$HttpIOHandlerObserver.onStateChange(HttpClientConnect.java:430) [reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:494) [reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.netty.resources.PooledConnectionProvider$DisposableAcquire.onStateChange(PooledConnectionProvider.java:526) [reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.netty.resources.PooledConnectionProvider$PooledConnection.onStateChange(PooledConnectionProvider.java:435) [reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:60) [reactor-netty-0.9.2.RELEASE.jar:0.9.2.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelActive(CombinedChannelDuplexHandler.java:414) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelActive(ChannelInboundHandlerAdapter.java:69) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelActive(CombinedChannelDuplexHandler.java:213) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:204) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1410) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:225) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:211) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:907) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.fulfillConnectPromise(AbstractKQueueChannel.java:606) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.finishConnect(AbstractKQueueChannel.java:639) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.writeReady(AbstractKQueueChannel.java:432) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:208) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.43.Final.jar:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_231]
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at io.netty.channel.kqueue.AbstractKQueueChannel.doWriteBytes(AbstractKQueueChannel.java:288) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel.writeBytes(AbstractKQueueStreamChannel.java:111) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel.doWriteSingle(AbstractKQueueStreamChannel.java:323) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.kqueue.AbstractKQueueStreamChannel.doWrite(AbstractKQueueStreamChannel.java:281) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:931) ~[netty-all-4.1.43.Final.jar:4.1.43.Final]
	... 50 common frames omitted
```

### Steps to reproduce
Run the provided reproducer code.

### Minimal yet complete reproducer code (or URL to code)
https://github.com/izeye/spring-boot-throwaway-branches/blob/netty-nsme/src/test/java/com/izeye/throwaway/HomeControllerWebTestClientTests.java#L34

### Netty version
4.1.43.Final

### JVM version (e.g. `java -version`)
```bash
$ /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/bin/java -version
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
$
```

### OS version (e.g. `uname -a`)
```bash
$ uname -a
Darwin xxx 17.7.0 Darwin Kernel Version 17.7.0: Fri Oct  4 23:08:59 PDT 2019; root:xnu-4570.71.57~1/RELEASE_X86_64 x86_64
$
```

### Description

Based on the error, it seems to be compiled in JDK 8 incompatible way somehow. FYI, the method signature of `java.nio.ByteBuffer.position()` has been changed since JDK 9.

JDK 8:

```java
Buffer position(int newPosition)
```

JDK 9:

```java
ByteBuffer position(int newPosition)
```

I confirmed that it's working with JDK 9, and 4.1.38.Final is working with JDK 8.

**Comment by normanmaurer** [comment]
@izeye I suspect there was an "mistake" while building the jar that picked-up Java11 :( I will fix this as part of the next release (which should be out soon).

**Comment by izeye** [comment]
@normanmaurer Thanks! I confirmed that Netty 4.1.44.Final works with the sample.
