### ISSUE TITLE
Blockhound detects blocking call: SingleThreadEventExecutor.confirmShutdown

### ISSUE THREAD

**Issue by IrishkA13** [netty/netty#9899]
Netty version
4.1.39.Final

JVM version (e.g. java -version)
java 11.0.3 2019-04-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.3+12-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.3+12-LTS, mixed mode)

OS version (e.g. uname -a)
macOS Mojave 10.14.5

```
	at reactor.blockhound.BlockHound$Builder.lambda$install$8(BlockHound.java:259)
	at reactor.blockhound.BlockHoundRuntime.checkBlocking(BlockHoundRuntime.java:43)
	at java.base/java.lang.Thread.sleep(Thread.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.confirmShutdown(SingleThreadEventExecutor.java:731)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:345)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by amizurov** [comment]
Hi @IrishkA13, this is allowed behavior see 
https://github.com/netty/netty/blob/687308b4de56ff77a03d731d67153947497271f5/common/src/main/java/io/netty/util/internal/Hidden.java#L63-L65

**Comment by normanmaurer** [comment]
Like @amizurov said
