### ISSUE TITLE
Native image generation fails with Netty 4.1.44.Final

### ISSUE THREAD

**Issue by tovbinm** [netty/netty#9918]
### Expected behavior

A working native image

### Actual behavior

When I am trying to generate a native image on a project with Netty dependency I get the following error:

```
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.channel.DefaultFileRegion the class was requested to be initialized at build time (subtype of io.netty.util.AbstractReferenceCounted and from the command line). io.netty.channel.DefaultFileRegion has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of io.netty.channel.DefaultFileRegion
io.netty.util.AbstractReferenceCounted the class was requested to be initialized at build time (from the command line). io.netty.util.AbstractReferenceCounted has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of io.netty.util.AbstractReferenceCounted
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.channel.DefaultFileRegion the class was requested to be initialized at build time (subtype of io.netty.util.AbstractReferenceCounted and from the command line). io.netty.channel.DefaultFileRegion has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of io.netty.channel.DefaultFileRegion
io.netty.util.AbstractReferenceCounted the class was requested to be initialized at build time (from the command line). io.netty.util.AbstractReferenceCounted has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try avoiding to initialize the class that caused initialization of io.netty.util.AbstractReferenceCounted
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:510)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:187)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:710)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:710)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1482)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1260)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1222)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1181)
```

### Steps to reproduce

"Hello world" server with 4.1.44.Final dependency

### Minimal yet complete reproducer code (or URL to code)

N/A

### Netty version

`4.1.44.Final`

### JVM version (e.g. `java -version`)

```
$ docker run oracle/graalvm-ce:19.3.0.2 sh -c "java -version"
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-b07)
OpenJDK 64-Bit GraalVM CE 19.3.0.2 (build 25.232-b07-jvmci-19.3-b06, mixed mode)
```

### OS version (e.g. `uname -a`)
```
$ docker run oracle/graalvm-ce:19.3.0.2 sh -c "uname -a"
Linux 161cd47fc3af 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

(I also opened a similar issue here - https://github.com/oracle/graal/issues/2050)

**Comment by normanmaurer** [comment]
@tovbinm we love contributions. If you have any idea how to fix this I am happy to review a pr.

**Comment by tovbinm** [comment]
I have been told here - https://github.com/oracle/graal/issues/2050 that it should be possible, but I failed to confirm yet.

**Comment by keddie** [comment]
I saw exactly this symptom in a different project. The cause was that my agent-generated reflect.config contained:

```
{
  "name":"io.netty.channel.epoll.Epoll"
},
{
  "name":"io.netty.channel.epoll.EpollSocketChannel",
  "methods":[{"name":"<init>","parameterTypes":[] }]
},
```

... which was causing the `AbstractReferenceCounted` to initialize.

**Comment by normanmaurer** [comment]
Should all work in latest netty releases
