### ISSUE TITLE
I had this exception : java.nio.channels.ClosedChannelException: null

### ISSUE THREAD

**Issue by shakarelic** [netty/netty#9927]
- java.nio.channels.ClosedChannelException: null
at io.netty.channel.AbstractChannel$AbstractUnsafe.newClosedChannelException(AbstractChannel.java:958)
at io.netty.channel.AbstractChannel$AbstractUnsafe.write(AbstractChannel.java:866)
at io.netty.channel.DefaultChannelPipeline$HeadContext.write(DefaultChannelPipeline.java:1379)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:716)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:708)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:710)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:791)
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:701)
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:710)
at io.netty.channel.AbstractChannelHandlerContext.access$1700(AbstractChannelHandlerContext.java:56)
at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.write(AbstractChannelHandlerContext.java:1102)
at io.netty.channel.AbstractChannelHandlerContext$WriteAndFlushTask.write(AbstractChannelHandlerContext.java:1149)
at io.netty.channel.AbstractChannelHandlerContext$AbstractWriteTask.run(AbstractChannelHandlerContext.java:1073)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:748)
---------
- client：netty 4.1.42
---------
- server:  url Corresponding api not had exception
---------

**Comment by amizurov** [comment]
Hi, could you please provide more info, at the current moment I see that you channel already closed and you trying write some data to it in this case this is expected behavior.

**Comment by shakarelic** [comment]
no having other info
------
client use async-http-client Make http request,
server not have any exception , but client had this exception
-----

**Comment by normanmaurer** [comment]
sorry but without more informations there is nothing we can do.. This basically just means you are trying to write to a `Channel` that was closed before.

**Comment by StVl** [comment]
@normanmaurer  hi!

when i try to do that:
` private val client: WebClient = Webclient.builder().baseUrl(config.url).httpProxyConnector(config.proxyHost, config.proxyPort).build() `

` fun serverToServer(checkBody: String) = client
    .post()
    .uri("...")
    .bodyValue(Body(checkBody, password))
    .retrieve()
    .bodyToMono<String>()
    .map{ mapper.readValue(it, SomeBody::class.java)} `

i get the same exception. I I doubt and am looking for fault at netty part because this code i' don't touch many time

**Comment by StVl** [comment]
@shakarelic  did you find response for your question ?

**Comment by shakarelic** [comment]
no,no time for chattering now,i add  cache and reduce requests
