### ISSUE TITLE
Attempting to open a websocket throws NPE

### ISSUE THREAD

**Issue by Milinai** [netty/netty#9949]
### Expected behavior
The websocket connection should succesfully be established.
### Actual behavior
The server throws an exception
```
java.lang.NullPointerException
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:218)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:169)
	at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandshakeHandler.channelRead(WebSocketServerProtocolHandshakeHandler.java:92)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93)
	at io.netty.handler.codec.http.websocketx.extensions.WebSocketServerExtensionHandler.channelRead(WebSocketServerExtensionHandler.java:101)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
### Steps to reproduce
1. Start a websocket server using the code below.
2. Attempt to connect a websocket client to the server at `/websocket` (tested on Firefox on the same device, using `new WebSocket("ws://localhost:8080/websocket")`).
3. The server throws the exception above instead of connecting the websocket.
### Minimal yet complete reproducer code
The following code has been tested and causes the error described.
```java
import io.netty.bootstrap.ServerBootstrap;
import io.netty.channel.*;
import io.netty.channel.nio.NioEventLoopGroup;
import io.netty.channel.socket.SocketChannel;
import io.netty.channel.socket.nio.NioServerSocketChannel;
import io.netty.handler.codec.http.*;
import io.netty.handler.codec.http.websocketx.*;
import io.netty.handler.codec.http.websocketx.extensions.compression.WebSocketServerCompressionHandler;

public class Main {
	private ChannelFuture channel;
	private final EventLoopGroup masterGroup;
	private final EventLoopGroup subGroup;
	public Main() {
		masterGroup = new NioEventLoopGroup();
		subGroup = new NioEventLoopGroup();
	}

	public void start(){
		Runtime.getRuntime().addShutdownHook(new Thread(this::shutdown));

		try{
			final ServerBootstrap bootstrap =
				new ServerBootstrap()
					.group(masterGroup, subGroup)
					.channel(NioServerSocketChannel.class)
					.childHandler(new ChannelInitializer<SocketChannel>() {
						@Override
						public void initChannel(final SocketChannel ch) {
							ChannelPipeline p = ch.pipeline();
							p.addLast(new HttpServerCodec());
							p.addLast(new HttpRequestDecoder());
							p.addLast(new HttpObjectAggregator(512*1024));
							p.addLast(new WebSocketServerCompressionHandler());
							p.addLast(new WebSocketServerProtocolHandler("/websocket", null, true));
							p.addLast(
								new ChannelInboundHandlerAdapter() {
									@Override
									public void channelRead(ChannelHandlerContext ctx, Object msg) throws Exception {
										if(!(msg instanceof FullHttpRequest)){
											super.channelRead(ctx, msg);
										}
									}

									@Override
									public void channelReadComplete(ChannelHandlerContext ctx) {
										ctx.flush();
									}

									@Override
									public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause){
										cause.printStackTrace();
									}
								});
							p.addLast(new SimpleChannelInboundHandler<WebSocketFrame>() {
								@Override
								protected void channelRead0(ChannelHandlerContext ctx, WebSocketFrame frame) {
									if(frame instanceof TextWebSocketFrame){
										
										ctx.channel().writeAndFlush(new TextWebSocketFrame("Hello World!"));
									}
									else{
										String message = "unsupported frame type: " + frame.getClass().getName();
										throw new UnsupportedOperationException(message);
									}
								}
								@Override
								public void exceptionCaught(ChannelHandlerContext ctx, Throwable cause){
									cause.printStackTrace();
									ctx.close();
								}
							});
						}
					})
					.option(ChannelOption.SO_BACKLOG, 128)
					.childOption(ChannelOption.SO_KEEPALIVE, true);
			channel = bootstrap.bind(8080).sync();
		}
		catch (final InterruptedException e) {
			e.printStackTrace();
		}
	}

	public void shutdown() {
		subGroup.shutdownGracefully();
		masterGroup.shutdownGracefully();
		try{
			channel.channel().closeFuture().sync();
		}
		catch (InterruptedException e) {
			e.printStackTrace();
		}
	}

	public static void main(String[] args) {
		new Main().start();
	}
}
```
### Netty version
4.1.44.Final
### JVM version (`java -version`)
```
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
Dynamic Code Evolution 64-Bit Server VM (build 25.71-b01-dcevmlight-26, mixed mode)
```
### OS version (`uname -srvmpio`)
```
Linux 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Milinai** [comment]
A little side note is that this code is mostly copied from the example code, which is supposed to work as intended.

**Comment by amizurov** [comment]
Hi @Milinai you cannot use both `HttpServerCodec` and `HttpRequestDecoder` in pipeline, because `WebSocketServerHandshaker` trying to remove http's handler on handshake, so if it found the `HttpRequestDecoder` then it also expect `HttpResponseEncoder`. Remove `p.addLast(new` HttpRequestDecoder());` from your channel initializer.

**Comment by Milinai** [comment]
Thanks! That was not clear, I probably didn't read enough about the `? extends ChannelHandler` classes. I would expect a more clear error message than a NPE without any reference to my code. Now that I know an `HttpResponseEncoder` is expected to exist, the error makes more sense, but without that knowledge, a user can be totally clueless as to what the cause could possibly be. I'm going to close the issue for now, although I'm considering adding/suggesting a check throwing a new exception mentioning the issue to make the cause more clear to the user.
